### ISSUE TITLE
Add docs and example on how to use live update in dynamic chart.

### ISSUE THREAD

**Issue by prakash-cr7** [syncfusion/flutter-widgets#100]
i am trying to figure out how to use live update for dynamic chart. please refer any link or  explain in short if you can.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @prakash-cr7,

Greetings from Syncfusion. We have analyzed query at our end and as per your request, we have attached the example GitHub repo links of our dynamic live update chart samples below for your reference. Please check with the below sample links and revert us if you still have further concerns on this.
Live update samples: https://github.com/syncfusion/flutter-examples/tree/master/lib/samples/chart/cartesian_charts/real_time_charts/live_update

Regards,
Sriram Kiran

**Comment by prakash-cr7** [comment]
Thank you! This is exactly what I was looking for.
