### ISSUE TITLE
SfCartesianChart tooltipBehavior 

### ISSUE THREAD

**Issue by BitleTeng** [syncfusion/flutter-widgets#1000]
tooltipBehavior-->builder, 设置自定义的tooltip UI,点击事件会点击穿透到图表,导致点击事件冲突,严重影响体验

**Comment by LokeshPalani** [comment]
Hi @BitleTeng,

We have analyzed your requirement from our end. We kindly request that you provide us with more detailed information, including screen recordings, regarding the event you want to occur when you click, resulting in conflicts with the tooltip builder and chart. This will help us better assist you.

Regards,
Lokesh.

**Comment by LavanyaGowtham2021** [comment]
Hi @BitleTeng,
 
Please reopen this ticket with requested details to proceed further on this.

Regards,
Lavanya A.
