### ISSUE TITLE
[syncfusion_flutter_charts] How to trigger onSelectionChanged event with tap the whole column in ColumnSeries?

### ISSUE THREAD

**Issue by YaoShuwei** [syncfusion/flutter-widgets#1004]
I tried onPointTap, onAxisLabelTapped, onDataLabelTapped, onSelectionChanged, but they wouldn't triggered on the whole column.
For example: This is a columnSeries, there are some zero value column, I can just tap on blue area to change selection area, how can I trigger onSelectionChanged event?

![image](https://user-images.githubusercontent.com/17966298/207529488-48e3002b-0a3a-43b8-8174-24dedff104ee.png)

**Comment by Yuvaraj-Gajaraj** [comment]
The [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onSelectionChanged.html) callback only triggers when the tapped position is inside the column region, in your sample you have tried to tap on the zero value column that didn't have a region. This is the reason the [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onSelectionChanged.html) callback is not triggered. Hence you can achieve this with the help of [onDataLabelTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onDataLabelTapped.html) and [selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html) public method of selection behavior. When tapping on the data label you can get the respective [pointIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelTapDetails/pointIndex.html) value of that column segment and pass the index value in [selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html) public method. We have shared the sample below for your reference.


Screenshot:
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61863686/207875588-564810f9-ae5a-48ce-942e-45474fdfbd92.gif)

Sample: 
[i425249.zip](https://github.com/syncfusion/flutter-widgets/files/10237498/i425249.zip)

**Comment by YaoShuwei** [comment]
> The [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onSelectionChanged.html) callback only triggers when the tapped position is inside the column region, in your sample you have tried to tap on the zero value column that didn't have a region. This is the reason the [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onSelectionChanged.html) callback is not triggered. Hence you can achieve this with the help of [onDataLabelTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onDataLabelTapped.html) and [selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html) public method of selection behavior. When tapping on the data label you can get the respective [pointIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelTapDetails/pointIndex.html) value of that column segment and pass the index value in [selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html) public method. We have shared the sample below for your reference.
> 
> Screenshot: ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61863686/207875588-564810f9-ae5a-48ce-942e-45474fdfbd92.gif) [ ![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61863686/207875588-564810f9-ae5a-48ce-942e-45474fdfbd92.gif) ](https://user-images.githubusercontent.com/61863686/207875588-564810f9-ae5a-48ce-942e-45474fdfbd92.gif) [ ](https://user-images.githubusercontent.com/61863686/207875588-564810f9-ae5a-48ce-942e-45474fdfbd92.gif)
> 
> Sample: [i425249.zip](https://github.com/syncfusion/flutter-widgets/files/10237498/i425249.zip)

Thank you very much. I'm already forked and edit the source code to fix it.

![image](https://user-images.githubusercontent.com/17966298/208797286-eb754518-fbe4-4562-843a-ad83c311ea6c.png)
