### ISSUE TITLE
[Paginated DataGrid] rowsPerPage should support user can choose.

### ISSUE THREAD

**Issue by svsno1** [syncfusion/flutter-widgets#101]
Hi,

SfDataPager (rowsPerPage: 20) --> SfDataPager (rowsPerPage: [10, 20, 50], defaultRowsPerPage: 20)

User can choose 10, 20 or 50 rows per page.

It's my idea. Thanks!

**Comment by NeelakandanKannan** [comment]
Hi @svsno1 ,

Thanks for your feedback.

SfDataPager just creates the page buttons in view alone based on the rows count and rowsPerPage. It does not process and allocate the available rows to datagrid automatically. But, still you can load any number of rows to datagrid via handlePageChange method. You can load required number of rows based on page index. Please find the code snippet in below,

```dart
class OrderInfoDataSource extends DataGridSource<OrderInfo> {
  @override
  List<OrderInfo> get dataSource => paginatedDataSource;

  @override
  Object getValue(OrderInfo orderInfos, String columnName) {
    switch (columnName) {
      case 'orderID':
        return orderInfos.orderID;
        break;
      case 'customerID':
        return orderInfos.customerID;
        break;
      case 'freight':
        return orderInfos.freight;
        break;
      case 'orderDate':
        return orderInfos.orderData;
        break;
      default:
        return '';
        break;
    }
  }

  @override
  int get rowCount => orderInfos.length;

  @override
  @override
  Future<bool> handlePageChange(int oldPageIndex, int newPageIndex,
      int startRowIndex, int rowsPerPage) async {
    if (newPageIndex == 1) {
      _paginatedData = _employeeData.sublist(0, 9);
    } else if (newPageIndex == 2) {
      _paginatedData = _employeeData.sublist(10, 29);
    } else {
      _paginatedData = _employeeData.sublist(30, 80);
    }
    notifyListeners();
  }
}

```

**Comment by svsno1** [comment]
Hi @NeelakandanKannan,

Perhaps you have misunderstood me.

https://programmer.help/images/blog/42a2ae75e9778d7a0039cf59880bf6aa.jpg

I want the rowsPerPage to be similar to Flutter's PaginatedDataTable at https://api.flutter.dev/flutter/material/PaginatedDataTable-class.html

Sorry for this ambiguity!

**Comment by BalasubramaniSundaram** [comment]
Hi @svsno1,

Thank you for the update.
  
Currently, we are analyzing the feasibility of the support to show the drop-down widget to change the rowsPerPage in Datagrid, we will validate and let you know the details within 6th January 2021. We appreciate your patience until then.  
 
Regards,  
Balasubramani Sundaram.

**Comment by NeelakandanKannan** [comment]
Hi @svsno1 ,

Thanks for your patience.

We have considered your request. We have logged the feature request and this feature will be included in any of our upcoming release. Please refer the below feedback for better follow up,

https://www.syncfusion.com/feedback/21168/support-to-show-dropdown-in-datapager-to-choose-the-different-rows-per-page-option

**Comment by Sangeetha-Raju** [comment]
Hi @svsno1 ,

We are glad to announce that your requested feature “Support to show dropdown in datapager to choose the different rows per page option” was included in our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards, 
Sangeetha Raju.
