### ISSUE TITLE
LateInitializationError: Field '_barPointerOffset@352180565' has not been initialized.

### ISSUE THREAD

**Issue by WizardingStudios** [syncfusion/flutter-widgets#1010]
Edit: I should confirm that the excpetion is caused by animation. This happens anytime the value change during animation.

By setting animation: false there are no issue. However I hope you will correct this because animation is a cool part of your widgets.

Hello,

here the stack (apparently happening if I change the value before the animation finish):

════════ Exception caught by widgets library ═══════════════════════════════════
The following LateError was thrown building LinearGaugeScope:
LateInitializationError: Field '_barPointerOffset@352180565' has not been initialized.

The relevant error-causing widget was
SfLinearGauge
lib/calculator.dart:587
When the exception was thrown, this was the stack
#0      RenderLinearBarPointer._barPointerOffset (package:syncfusion_flutter_gauges/src/linear_gauge/pointers/linear_bar_renderer.dart)
package:syncfusion_flutter_gauges/…/pointers/linear_bar_renderer.dart:1
#1      RenderLinearBarPointer.value=
package:syncfusion_flutter_gauges/…/pointers/linear_bar_renderer.dart:70
#2      LinearBarPointer.updateRenderObject
package:syncfusion_flutter_gauges/…/pointers/linear_bar_pointer.dart:296
#3      RenderObjectElement._performRebuild
package:flutter/…/widgets/framework.dart:5784
#4      RenderObjectElement.update
package:flutter/…/widgets/framework.dart:5763

With no more text to see the problem.

And here my gauge:

```
Expanded(
                            flex: 75,
                            child: SfLinearGauge(
                              barPointers: [
                                LinearBarPointer(
                                  thickness: 15,
                                  value: Variables.lipValue,
                                  offset: 5,
                                  position: LinearElementPosition.outside,
                                  color: Colors.yellow.shade600,
                                ),
                                LinearBarPointer(
                                  thickness: 15,
                                  value: Variables.protValue,
                                  offset: 25,
                                  position: LinearElementPosition.outside,
                                  color: Colors.red,
                                ),
                                LinearBarPointer(
                                  thickness: 15,
                                  value: Variables.carbValue,
                                  offset: 45,
                                  position: LinearElementPosition.outside,
                                  color: Colors.brown.shade300,
                                ),
                              ],
                            ),
                          ),
```

**Comment by LokeshPalani** [comment]
Hi @WizardingStudios,

We tried to replicate the reported issue at our end. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure on what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.


Regards,
Lokesh.

[slider_471160.zip](https://github.com/syncfusion/flutter-widgets/files/11702290/slider_471160.zip)

**Comment by LavanyaGowtham2021** [comment]
Hi @WizardingStudios,
 
Please reopen this ticket with requested details, if you still face an issue with latest gauges version.

Regards,
Lavanya A.
