### ISSUE TITLE
I want to create this type of graph in flutter

### ISSUE THREAD

**Issue by impatelravi** [syncfusion/flutter-widgets#1013]
Video Link for Graph View - https://drive.google.com/file/d/1gx9aSOivB8gfoiYcAlQf2V2l8Al6SLW8/view?usp=share_link

DataPoints I'm getting - `[{"open":"2022-12-21 06:02:26.578","close":"2022-12-21 06:02:26.578"},{"open":"2022-12-21 06:06:12.469","close":"2022-12-21 06:07:11.349"},{"open":"2022-12-21 06:10:55.376","close":"2022-12-21 06:11:11.683"},{"open":"2022-12-21 06:58:20.581","close":"2022-12-21 07:10:44.646"},{"open":"2022-12-21 08:39:49.717","close":"2022-12-21 08:53:24.835"},{"open":"2022-12-21 08:57:54.668","close":"2022-12-21 09:12:38.918"},{"open":"2022-12-21 17:31:17.070","close":"2022-12-22 07:21:53.479"}]`

Eg. [{"open":"2022-12-21 12:00:00.000","close": "2022-12-21 13:00:00.000"}, {"open":"2022-12-21 15:00:00.000","close": "2022-12-21 17:00:00.000"} 
Then Graph will be drawn from 12 to 13 in Green Bar, 13 to 15 Grey Bar, 15 to 17 Green Bar - Missing Data will be drawn in Grey Bar

Please help me to draw this graph in Flutter -  Web, Android and iOS

**Comment by LokeshPalani** [comment]
Hi @impatelravi,

After analyzing the provided data in JSON format, we have noticed that both the x and y values are in DateTime format, representing the open and close values. We have a question regarding how to configure the chart data using these DateTime values. Additionally, we are unsure about the purpose of changing colors based on range, and what is missing data by changing it to a grey color. To better assist you, we kindly request for more detailed information regarding your requirement and the specific purpose of the DateTime data. This will enable us to suggest a suitable chart type and provide more effective assistance.

Regards,
Lokesh.

**Comment by LavanyaGowtham2021** [comment]
Hi @impatelravi,
 
Please reopen this ticket with requested details to proceed further on this.

Regards,
Lavanya A.
