### ISSUE TITLE
xcodebuild command failing

### ISSUE THREAD

**Issue by cesarodriguez4** [syncfusion/flutter-widgets#1015]
xcodebuild fails when executing:

`xcodebuild -scheme "Runner" BUILD_DIR=".../_appcircle_temp/appcircle_build_ios_simulator/SimulatorBuildDir" -derivedDataPath ".../_appcircle_temp/appcircle_build_ios_simulator/SimulatorDerivedData" -configuration "Debug"  COMPILER_INDEX_STORE_ENABLE=NO  ONLY_ACTIVE_ARCH=NO  -arch x86_64   -quiet  -workspace ".../_appcircle_temp/Repository/ios/Runner.xcworkspace"`

Response:
```
error: Build input file cannot be found: '....syncfusion_flutter_pdfviewer/syncfusion_flutter_pdfviewer.framework/syncfusion_flutter_pdfviewer'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'syncfusion_flutter_pdfviewer' from project 'Pods')
```

I have tried adding `syncfusion_flutter_pdfviewer` to my POD file, but it stills failing (And documentation doesn't require to adding to pod file)

Any ideas how to solve this?

**Comment by ramkumarsync** [comment]
We are unable to replicate the reported issue. Could be please share the exact replication procedure for this issue? It would help us analyze the issue and provide a better solution at the earliest.

**Comment by ramkumarsync** [comment]
Since we don't have enough information to proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.
