### ISSUE TITLE
Is it possible to set the default zoom?

### ISSUE THREAD

**Issue by jonbhanson** [syncfusion/flutter-widgets#1016]
I would like to show a chart that contains data in the past few days, which can be panned back to see.  I would like to start initially zoomed to the last 12 hours.  Is is possible to set a default zoom?

**Comment by Yuvaraj-Gajaraj** [comment]
Your requirement can be achieved with the help of the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property in the axis, you can set the count of data you want to show in the visible area, and set [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) to start or end based on your requirement. We have shared the code snippet below for your reference.



Code snippet:
```dart
SfCartesianChart(
        primaryXAxis: DateTimeAxis(
          autoScrollingDelta: 12,
          autoScrollingMode: AutoScrollingMode.end,
        ),
        series: <ChartSeries<ChartData, DateTime>>[
          ColumnSeries(
            dataSource: chartData,
            xValueMapper: (ChartData data, int index) => data.x,
            yValueMapper: (ChartData data, int index) => data.y,
          )
        ],
      ),
```
Sample: [i427025.zip](https://github.com/syncfusion/flutter-widgets/files/10317392/i427025.zip)

**Comment by jonbhanson** [comment]
Great, thank you!
