### ISSUE TITLE
[syncfusion_flutter_pdf] PDFBrush does not support translucent brush. Alpha channel is ignored

### ISSUE THREAD

**Issue by theniceboy** [syncfusion/flutter-widgets#1018]
`PdfSolidBrush(PdfColor(0, 0, 0, 0))` creates a fully transparent brush, however, `PdfSolidBrush(PdfColor(0, 0, 0, 20))` creates a fully solid brush instead of a translucent brush

**Comment by theniceboy** [comment]
Related #958

**Comment by theniceboy** [comment]
When using `page.graphics.drawPath` with a translucent brush, strokes become fully opaque.

**Comment by theniceboy** [comment]
Perhaps opacity can be achieved with the `/OPacity` PDF operator

**Comment by irfanajaffer** [comment]
<html>
<body>
<p style="-webkit-font-smoothing: antialiased; box-sizing: border-box; margin: 0px 0px 1em; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">To achieve translucent brush behavior in PDF page, we can set transparency to page graphics before drawing path.</p><p style="-webkit-font-smoothing: antialiased; box-sizing: border-box; margin: 0px 0px 1em; color: rgb(36, 36, 36); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, system-ui, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Web&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Kindly use the following code snippet for reference,</p>

`//Create a new PDF document

 PdfDocument document = PdfDocument();

 //Adds a page to the document

 PdfPage page = document.pages.add();

 //Save the current graphics state

 PdfGraphicsState state = page.graphics.save();

 //Apply transparency

 page.graphics.setTransparency(0.5);

 //Draw path

 final PdfPath path = PdfPath();

 path.addLine(const Offset(10, 100), const Offset(10, 200));

 path.addLine(const Offset(100, 100), const Offset(100, 200));

 path.addLine(const Offset(100, 200), const Offset(55, 150));

 page.graphics.drawPath(path, brush: PdfBrushes.red);

 //Restore the graphics state

 page.graphics.restore(state);

 //Draw path in restored graphics with no transparency.

 final PdfPath path2 = PdfPath();

 path2.addLine(const Offset(310, 100), const Offset(310, 200));

 path2.addLine(const Offset(400, 100), const Offset(400, 200));

 path2.addLine(const Offset(400, 200), const Offset(355, 150));

 page.graphics.drawPath(path2, brush: PdfBrushes.red);

 //Saves the document

 List<int> bytes = await document.save();

 //Disposes the document

 document.dispose();`


</body>
</html>

**Comment by theniceboy** [comment]
That works! Thank you! @irfanajaffer
