### ISSUE TITLE
OnMarkerRenderer weird behavior

### ISSUE THREAD

**Issue by marcusmvfa** [syncfusion/flutter-widgets#1020]
Hello,
I've been getting a weird situation using the **onMarkerRender**. The correct behavior is to show a marker more bigger only on the last item of the series.

This issue happens randomly, and i have no idea of what is causing it.

The data is coming correct, i've already checked it.

<img width="280" alt="Screen Shot 2022-12-29 at 18 49 59" src="https://user-images.githubusercontent.com/43256442/210018573-115897a1-8286-4bd5-af39-46dbcfeaf2c9.png">

Here's the code for the rendering:

```

onMarkerRender(MarkerRenderArgs markerargs) {
    try {
      bool lastMarker = false;

      switch (markerargs.seriesIndex) {
        case 0:
          lastMarker = (markerargs.pointIndex == (homePossession.length - 1));
          break;
        case 1:
          lastMarker = (markerargs.pointIndex == (visitorPossession.length - 1));
          break;

        default:
      }

      if (lastMarker) {
        markerargs.markerHeight = 6.0;
        markerargs.markerWidth = 6.0;
      } else {
        markerargs.markerHeight = 0.0;
        markerargs.markerWidth = 0.0;
      }
    } catch (e) {
      //
    }
  }

```

Best regards!!!
Happy new year!!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @marcusmvfa ,

We have provided an alternative solution to achieve your requirement of rendering a marker at the last data point of the series.   Please find the code snippet below.

code snippet:
```dart
onMarkerRender: (MarkerRenderArgs markerargs) {
  if ((markerargs.seriesIndex == 0 &&
          markerargs.pointIndex == chartData1.length - 1) ||
      (markerargs.seriesIndex == 1 &&
          markerargs.pointIndex == chartData2.length - 1)) {
    markerargs.markerHeight = 6.0;
    markerargs.markerWidth = 6.0;
  } else {
    markerargs.markerHeight = 0.0;
    markerargs.markerWidth = 0.0;
  }
​},
```

Screenshot:

 

![rte_image_145](https://user-images.githubusercontent.com/61863686/210564788-25cee266-2e14-4c69-a050-e4eb1693c9f0.png)

Sample: 
[i427716.zip](https://github.com/syncfusion/flutter-widgets/files/10344445/i427716.zip)



Regards,

Yuvaraj.
