### ISSUE TITLE
【syncfusion_flutter_charts 】 infinite-scrolling case loading drag bug?

### ISSUE THREAD

**Issue by wuzeqiang2030** [syncfusion/flutter-widgets#1022]
【**### syncfusion_flutter_charts**】Loading more data, more data in the case of sorting disorder: [infinite-scrolling ](https://flutter.syncfusion.com/?_ga=2.29817791.1230240964.1672277352-1850465966.1634885222&_gl=1*16irn5l*_ga*MTg1MDQ2NTk2Ni4xNjM0ODg1MjIy*_ga_WC4JKKPHH0*MTY3MjI5NzUxNC4xMi4wLjE2NzIyOTc1MTQuMC4wLjA.#/cartesian-charts/infinite-scrolling)  Is there a way to fix this？

> 
![image](https://user-images.githubusercontent.com/31439684/210497862-2354732b-4ceb-47c6-87f7-52c9b2ed13b3.png)

**Comment by Yuvaraj-Gajaraj** [comment]
To have the same count of data points in the visible range you can use the following code snippet and achieve your requirement. We have also shared the modified sample for your reference.

code snippet:
```dart
List<int> getIndexes(int length) {
  final List<int> indexes = <int>[];
  for (int i = length - 1; i >= 0; i--) {
    indexes.add(chartData.length - 1 + i);
  }
  return indexes;
}
```

Sample: 
[i427936.zip](https://github.com/syncfusion/flutter-widgets/files/10357601/i427936.zip)
