### ISSUE TITLE
Error: The getter 'clearFilterFromDataGridFilteringLabel' isn't defined for the class 'SfLocalizations'

### ISSUE THREAD

**Issue by MalikSamiAwan** [syncfusion/flutter-widgets#1024]
return Center(
          child: Container(
              child: SfCartesianChart(
                  // primaryXAxis: DateTimeAxis(),
                  series: <ChartSeries>[
                    // Renders line chart
                    LineSeries<CustomProjectsForCompCartModal, Blob>(
                        dataSource: provider.currentCartsOfGRIDProjectsList,
                        xValueMapper: (CustomProjectsForCompCartModal cart, _) => cart.title,
                        yValueMapper: (CustomProjectsForCompCartModal cart, _) => cart.cume,
                    )
                  ]
              )
          )
      );
      
      
      
      Error:
      Launching lib/main.dart on macOS in debug mode...
Building macOS application...
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.56/lib/src/datagrid_widget/widgets/cell_widget.dart:1143:28: Error: The getter 'clearFilterFromDataGridFilteringLabel' isn't defined for the class 'SfLocalizations'.
 - 'SfLocalizations' is from 'package:syncfusion_flutter_core/src/localizations/global_localizations.dart' ('../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.42/lib/src/localizations/global_localizations.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'clearFilterFromDataGridFilteringLabel'.
    return '${localization.clearFilterFromDataGridFilteringLabel} "${widget.column.columnName}"';
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           Command PhaseScriptExecution failed with a nonzero exit code
** BUILD FAILED **

Exception: Build process failed

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @MalikSamiAwan,

Based on the information you have provided, we have identified that you are using an older version (**20.3.56**) of the **DataGrid** with the latest version (**20.4.42**) of the **syncfusion_flutter_core**. This combination may be causing the issue you are experiencing.

To help resolve the issue, we recommend upgrading your **DataGrid** version to **20.4.38** or the latest version (**20.4.42**). This will ensure that you are using compatible versions of the DataGrid and syncfusion_flutter_core, and may resolve the issue you are experiencing.

Regards,
Tamilarasan

**Comment by MalikSamiAwan** [comment]
@Tamilarasan-Paranthaman Thanks
