### ISSUE TITLE
Sorting RangeError (index): Invalid value: Not in inclusive range 0..19: -1 (SFDATAGRID)

### ISSUE THREAD

**Issue by madmouse17** [syncfusion/flutter-widgets#1025]
my data is 20, went i sorting data column is range error -1 , how fix this problem?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @madmouse17,

Attempting the sorting scenario with SfDataGrid version **20.4.42** and confirming that the sorting working properly on my end. I've attached a simple sample. Please check the following sample.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-2029079411 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @madmouse17,

We hope the reported issue has been resolved in your end. We are closing this issue now. Please don't hesitate to reopen this issue if you have any more questions. We are always happy to help you.

Regards,
Ashok K
