### ISSUE TITLE
Zoom in/out with buttons in a SfCartesianChart

### ISSUE THREAD

**Issue by joaquin-amenta** [syncfusion/flutter-widgets#1032]
Hello, I wanted to know if is it possible to handle zoom in/out tapping a button instead doing a gesture in the graph. This would be for a desktop app.

Thank you!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @joaquin-amenta ,

Yes, you can zoom in and zoom out the chart with the button click by calling the [zoomIn](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomIn.html) and [zoomOut](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomOut.html) public methods in [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html). We have shared the code snippet below for your reference.

Code snippet:
```dart
late ZoomPanBehavior _zoomPanBehavior;
  @override
  void initState() {
    _zoomPanBehavior =
        ZoomPanBehavior(enablePinching: true, enablePanning: true);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
          child: Column(
        children: [
          SfCartesianChart(
            zoomPanBehavior: _zoomPanBehavior,
            // Other required properties
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(
                  onPressed: () {
                    _zoomPanBehavior.zoomIn();
                  },
                  child: const Icon(Icons.add)),
              ElevatedButton(
                  onPressed: () {
                    _zoomPanBehavior.zoomOut();
                  },
                  child: const Icon(Icons.remove)),
            ],
          )
        ],
      )),
    );
  }

```

**Comment by joaquin-amenta** [comment]
Thank you! I totally missed those methods, the package is amazing
