### ISSUE TITLE
Slider between positive and negative values

### ISSUE THREAD

**Issue by Fudal** [syncfusion/flutter-widgets#1034]
Is it possible to display a slider where you choose a value between positive and negative? E.g. the default value is 0 - we can go left on the slider and select a value between 0 and -1, or we can go right and select a value between 0 and 1. 

I would like the tack to highlight only the left or right side of the thumb. 

An example in the screenshot below:

@Yuvaraj-Gajaraj @SriramKiranSenthilkumar do you have any idea?

![image](https://user-images.githubusercontent.com/13346676/212089090-84d9b624-0461-4019-bc0a-0b1a96074f4c.png)

**Comment by LokeshPalani** [comment]
Hi,

You can achieve your requirements with the help of the [thumbShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/thumbShape.html) property in the slider. By using the [thumbShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/thumbShape.html) property, you can create a custom thumb with a specific shape and size. We have shared a sample and User Guide documentation below for your reference. Please get back to us if you need any further assistance.


UG,
https://help.syncfusion.com/flutter/slider/shapes#thumb-shape  


Regards,
Lokesh.

[slider_470818.zip](https://github.com/syncfusion/flutter-widgets/files/11784403/slider_470818.zip)
