### ISSUE TITLE
[syncfusion_flutter_map] a big space of margins display on the edges of map after scrolling

### ISSUE THREAD

**Issue by chenjie4255** [syncfusion/flutter-widgets#1036]
Hi, I tried to follow the tutorial from https://help.syncfusion.com/flutter/maps/getting-started , but after setting the tilemap layer and enabled the scrollController. I noticed a large blank area on the border. I looked up the documentation, but there were no instructions on how to get rid of this area.

Screenshots and code are pasted below.

![Screenshot_20230115-231124](https://user-images.githubusercontent.com/5313665/212549469-dd7f4faa-3b4d-41a1-b6f8-4372d7335698.png)

![Screenshot_20230115-231133](https://user-images.githubusercontent.com/5313665/212549505-82496252-e3ff-4e7f-8c5b-63844930a21e.png)

```
import 'package:flutter/material.dart';

import 'package:syncfusion_flutter_maps/maps.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  final MapZoomPanBehavior _zoomPanBehavior = MapZoomPanBehavior();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Container(
        color: Colors.yellow,
        width: 300,
        height: 300,
        child: SfMaps(
          layers: [
            MapTileLayer(
                urlTemplate: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                zoomPanBehavior: _zoomPanBehavior,
                onWillPan: (p0) {
                  print(p0.newVisibleBounds);
                  return true;
                }),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by LokeshPalani** [comment]
Hi @chenjie4255,

Currently, we do not have support for hiding the border when panning on the edge of the tile layer map. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.



We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.



Feedback, https://www.syncfusion.com/feedback/42719/provide-a-continuous-map-support-in-sfmaps

Regards,
Lokesh.
