### ISSUE TITLE
Can i use this for free my unpublic application?  That is not going to host in play store.

### ISSUE THREAD

**Issue by ManeeshDev** [syncfusion/flutter-widgets#1038]

**Comment by busslina** [comment]
I think there is not any problem. You can find those all packages on pub.dev, so you can install it by adding to the pubspec.yaml file.

https://pub.dev/packages/syncfusion_flutter_core
https://pub.dev/packages/syncfusion_flutter_datagrid

**Comment by ManeeshDev** [comment]
> I think there is not any problem to use it. You can find those all packages on pub.dev, so you can install it by adding to the pubspec.yaml file. If someone wants to get paid by using their libraries I doubt that would put in for free on pub.dev.
> 
> Lets say that, I see the License on pub.dev and it is:
> 
> > Syncfusion License
> > Syncfusion Flutter Core package is available under the Syncfusion Essential Studio program, and can be licensed either under the Syncfusion Community License Program or the Syncfusion commercial license.
> > To be qualified for the Syncfusion Community License Program you must have a gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization, and agree to be bound by Syncfusion’s terms and conditions.
> > Customers who do not qualify for the community license can contact [sales@syncfusion.com](mailto:sales@syncfusion.com) for commercial licensing options.
> > Under no circumstances can you use this product without (1) either a Community License or a commercial license and (2) without agreeing and abiding by Syncfusion’s license containing all terms and conditions.
> > The Syncfusion license that contains the terms and conditions can be found at
> > https://www.syncfusion.com/content/downloads/syncfusion_license.pdf
> 
> > Syncfusion License
> > Syncfusion Flutter DataGrid package is available under the Syncfusion Essential Studio program, and can be licensed either under the Syncfusion Community License Program or the Syncfusion commercial license.
> > To be qualified for the Syncfusion Community License Program you must have a gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization, and agree to be bound by Syncfusion’s terms and conditions.
> > Customers who do not qualify for the community license can contact [sales@syncfusion.com](mailto:sales@syncfusion.com) for commercial licensing options.
> > Under no circumstances can you use this product without (1) either a Community License or a commercial license and (2) without agreeing and abiding by Syncfusion’s license containing all terms and conditions.
> > The Syncfusion license that contains the terms and conditions can be found at
> > https://www.syncfusion.com/content/downloads/syncfusion_license.pdf
> 
> https://pub.dev/packages/syncfusion_flutter_core https://pub.dev/packages/syncfusion_flutter_datagrid

Thanks.
