### ISSUE TITLE
Focus issue with SfDataGrid 

### ISSUE THREAD

**Issue by busslina** [syncfusion/flutter-widgets#1039]
I have my Flutter Web App and I want to handle surgically the Focus in order to provide a good user experience with the keyboard. 

When using SfDataGrid seems to work nice. If I enable allow filtering option, also works fine. I recover the focus after interact with filtering dialog (including textfield, check buttons, ...). I found out that this feature is envolved by FocusScope and it works nice.

The problem came when I enable the sorting option. Once clicked on sort button, focus never comes back. I suspect it is a bug because sort feature its much more easier (there is only a button, there is not any dialog). Also I suspect that the problem is to not using a FocusScope around this feature.

For the moment, I disabled this feature waiting this problem to be resolved.

Any help would be appreciate.

Thanks

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @busslina,

I have confirmed that the sorting scenario is working as expected with SfDataGrid version **20.4.44**. I have tested the scenario where the focus comes back to the DataGrid after sorting through the sorting button in the filter UI. I have attached a sample that demonstrates this.

In the sample, I first select one row and then filter the records through the filter UI. After that, I perform the sorting through the sort button in the filter UI. The focus comes back to the DataGrid, and the row navigation works properly when pressing the down and up keys on the keyboard.

Please refer to the attached sample and the reference video for further details.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample979402725  


https://user-images.githubusercontent.com/93904422/213680678-14d84c55-0bc2-4716-90d3-131a1f845b01.mp4



Can you please provide me with more details about your issue in case I have misunderstood your use case? It would be greatly appreciated if you could also provide a simple example and the steps to reproduce the issue.

Regards,
Tamilarasan

**Comment by busslina** [comment]
The thing is that I wanted to keep the primary focus on my widgets. Maybe is is not achievable using your Table lib. So I decided to create my own Table implementation with fixed header row.

Thank you for your time.

I attach her the code of my implementatio for anyone that may find it useful:

### A) Custom table class
```
import 'package:...' as flib;

import 'package:.../typedefs.dart' as typdefs;
import 'package:.../custom_table_data.dart';

import 'package:flutter/material.dart';

class CustomTable extends StatefulWidget {
  // Data
  // final bool fixHeaderRow;
  final CustomTableData data;
  final ScrollController? scrollController;

  /// Consntructor.
  const CustomTable({
    super.key,
    // this.fixHeaderRow = true,
    required this.data,
    this.scrollController,
  });

  // Getter functions
  //
  // - 01 - Header cell builder
  // - 02 - Data cell builder

  //#region
  /// 01 - Header cell builder.
  typdefs.HeaderCellBuilder get headerCellBuilder {
    return data.headerCellBuilder != null
        ? data.headerCellBuilder!
        : (int columnIndex) {
            return flib.Label(
              data.headerRow[columnIndex],
              fontSize: 18,
              color: flib.gold,
            );
          };
  }

  /// 02 - Data cell builder.
  typdefs.DataCellBuilder get dataCellBuilder {
    return data.dataCellBuilder != null
        ? data.dataCellBuilder!
        : (int rowIndex, int columnIndex) {
            return flib.Label(
              data.dataRows[rowIndex][columnIndex],
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
            );
          };
  }
  //#endregion

  // Functions
  //
  // - 01 - Create state

  //#region
  /// 01 - Create state.
  @override
  State<StatefulWidget> createState() {
    return _CustomTableState();
  }
  //#endregion
}

class _CustomTableState extends flib.CustomState<CustomTable> {
  /// Constructor.
  _CustomTableState();

  // Override functions
  //
  // - 01 - Init state
  // - 02 - Did update widget
  // - 03 - Dispose

  //#region
  /// 01 - Init state.
  @override
  void initState() {
    super.initState();
  }

  /// 02 - Did update widget.
  @override
  void didUpdateWidget(covariant CustomTable oldWidget) {
    super.didUpdateWidget(oldWidget);

    // Data changed
    if (oldWidget.data != widget.data) {
      refresh();
    }
  }

  /// 03 - Dispose.
  @override
  void dispose() {
    super.dispose();
  }
  //#endregion

  // Inherited functions
  //
  // - 01 - Build

  //#region
  /// 01 - Build.
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        // Header row
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: List.generate(
            widget.data.columnLength,
            (columnIndex) => Flexible(
              flex: 1,
              child: SizedBox(
                width: double.infinity,
                height: 50,
                child: Center(
                  child: widget.headerCellBuilder(
                    columnIndex,
                  ),
                ),
              ),
            ),
          ),
        ),

        // Data row
        Expanded(
          child: SingleChildScrollView(
            controller: widget.scrollController,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: List.generate(
                widget.data.columnLength,
                (columnIndex) => Flexible(
                  flex: 1,
                  child: Column(
                    children: List.generate(
                      widget.data.dataRows.length,
                      (rowIndex) => SizedBox(
                        width: double.infinity,
                        height: 50,
                        child: Center(
                          child: widget.dataCellBuilder(
                            rowIndex,
                            columnIndex,
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ],
    );
  }
  //#endregion
}
```

### B) Custom table data class
