### ISSUE TITLE
[syncfusion_flutter_datagrid] headerCellBuilder

### ISSUE THREAD

**Issue by vecharm** [syncfusion/flutter-widgets#104]
If the permission to build header widget is given to the developer, I think it should be set by the developer freely rather than fixed padding:16
![image](https://user-images.githubusercontent.com/25290829/103511340-d4b0f480-4ea1-11eb-82ec-3ed973955778.png)
Version:18.4.30-beta

**Comment by BalasubramaniSundaram** [comment]
Hi @vecharm,
  
Currently, we are validating the reported “Constant headerCell padding” issue, we will validate and let you know the details on 6th January 2021. We appreciate your patience until then. 

Regards,  
Balasubramani Sundaram.

**Comment by RenugaSadagoban98** [comment]
Hi vecharm, 

The changes have been included in our weekly pub release. Please update datagrid package to 18.4.43-beta version.

Regards, 
Renugadevi S.
