### ISSUE TITLE
flutter_pdfviewer: Change max zoom?

### ISSUE THREAD

**Issue by kfina91** [syncfusion/flutter-widgets#1040]
The maximum zoom level seems to be fixed at 3. How can you change that limit?

**Comment by deepika134** [comment]
Hi @kfina91 ,The support to set the maximum zoom level will help you to zoom out beyond the default zoom level (default zoom level: 3). At present we do not have support to set the maximum zoom level in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked through the following link,
https://www.syncfusion.com/feedback/26648/support-to-set-minimum-and-maximum-zoom-level

**Comment by itibs** [comment]
https://github.com/syncfusion/flutter-widgets/blob/73d2f82496b7541a7955f9d0ab7636de5aa867b9/packages/syncfusion_flutter_pdfviewer/lib/src/pdfviewer.dart#L183

seems to me like this has been implemented, should this be closed?
