### ISSUE TITLE
[syncfusion_flutter_datagrid] Filter text field inside column header

### ISSUE THREAD

**Issue by divan** [syncfusion/flutter-widgets#1046]
So UI Filter is a fantastic feature for DataGrid as it allows filter by different columns. However, user needs to click on each column header, then go to the textfield, enter query, then click OK - that's 3 clicks. I had a many year experience with one of the web datagrids, where you have search textfield directly in the column headers.

![Screenshot 2023-01-20 at 20 36 48](https://user-images.githubusercontent.com/880202/213779430-5d1e1746-b3e6-4c75-81fc-208df843bc95.png)

Another life example is an angular datagrid demo: https://www.ag-grid.com/example

This approach is extremely productive in practice. Search takes just 1 click. In 90% of cases users need just enter 3-4 characters to find what they want.

It would be really helpful to have this option in Syncfusion datagrid. Is it planned/discussed? Popup with extedned UI filtering is nice, however I would love to be able to disable it for some cases.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @divan,

As of now, Flutter SfDataGrid does not have support for filtering the records through the built-in filter row. We have considered your request as a feature. We may implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.  

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.  

You can also communicate with us regarding the open features any time using our Feature Report page.   

Feedback link: https://www.syncfusion.com/feedback/40560/support-to-filter-the-rows-through-the-built-in-filter-row

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.  

Regards,
Tamilarasan
