### ISSUE TITLE
Increment pdf viewer's page navigation dialog value

### ISSUE THREAD

**Issue by ShehabSN** [syncfusion/flutter-widgets#1050]
I have a use case where the pdf provided has a few introductory pages at the start, let's say 3 pages for example. When a user uses the page navigation dialog to visit page 2 for example, the intention is to visit page 2 **after** the first 3 introductory pages, so that would be page 5 of the pdf in this case.

However, since I don't want the user to have to manually consider how many introductory pages there are in the pdf and then sum that up with their desired page number (3 + 2 = 5 ), I was wondering if there was some sort of callback or way to custom define some action, in this case incrementing the dialog's input page number by an offset of 3. The alternative is to hide the page navigation dialog, create my own, and use the navigation functions, which is not too big of a deal but I just wanted to make sure before moving forward with that.

Thank you

**Comment by deepika134** [comment]
Hi Shahab,

The SfPdfViewer pagenavigation supports [PdfPageChangedCallback](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfPageChangedCallback.html) to identify the pages changes. Kindly refer the following link for know more details about the pagechanged callback,
https://help.syncfusion.com/flutter/pdf-viewer/page-navigation#page-changed-callback 

To move the desired page use the [jumpToPage()](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfViewerController/jumpToPage.html)method in SfPdfViewer . Kindly refer the following details about the page navigation,
https://help.syncfusion.com/flutter/pdf-viewer/page-navigation 

Could you please confirm us whether this fulfills your requirement?

**Comment by ramkumarsync** [comment]
We are closing this issue since we haven't heard back from you for a long time. Please feel free to contact us anytime if you need any further assistance.
