### ISSUE TITLE
how create axis line like that 

### ISSUE THREAD

**Issue by demoYang** [syncfusion/flutter-widgets#1053]
![image](https://user-images.githubusercontent.com/7134823/215307742-64ba631b-6646-4891-b681-f75cd953be72.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @demoYang,

Your requirement can be achieved with the help of a  [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html),  you can give the line series data source X values as the area series start and end X values, and Y values as the Y-axis minimum value. It will render a line series in the required place. We have created a sample and shared it below for your reference.

Screenshot:
![rte_image_139](https://user-images.githubusercontent.com/61863686/215654539-1eccd5c9-b96b-4c42-bddb-f4cc2cbfe044.png)

Sample: 
[i433921.zip](https://github.com/syncfusion/flutter-widgets/files/10542338/i433921.zip)


Regards,
Yuvaraj.
