### ISSUE TITLE
[syncfusion_flutter_datagrid] It is not possible to handle custom Keyboard Shortcuts (cmd+c; cmd+v; etc...)

### ISSUE THREAD

**Issue by socramm9** [syncfusion/flutter-widgets#1057]
Maybe I am doing something wrong, but I think the implementation of [keyboard-navigation](https://help.syncfusion.com/flutter/datagrid/accessibility#keyboard-navigation) is stoping Shortcut events to be received.

I have a feature where the user can use copy and past to move entries around. For the Desktop version it should be also possible for the users to use keyboard shortcuts. 

Example code:
```
CallbackShortcuts(
    bindings: {
        SingleActivator(LogicalKeyboardKey.keyX, meta: true): () {
            print("TEST");
        }
    },
    child: Focus(
        autofocus: true,
        child: SfDataGrid(...)
    )
)
```
I could identify this code to be the issue https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_datagrid/lib/src/datagrid_widget/widgets/scrollview_widget.dart
<img width="695" alt="Bildschirm­foto 2023-01-30 um 10 49 07" src="https://user-images.githubusercontent.com/52098754/215444067-d0a4ca9b-4683-4123-8148-cc292a989b2f.png">

I am not sure what the best fix for the problem would be, but for my project I will just fork and remove the Focus widget in `scrollview_widget.dart`. 

Maybe SfGrid could add a new prop that passes events from `_handleKeyOperation`.? Or maybe it is Possible to let child Focus widgets to also receive events?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @socramm9,

Currently, Flutter SfDataGrid does not have support for handling keyboard shortcuts. We have considered your request as a feature. We may implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience and understanding until then.   

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.   

You can also communicate with us regarding the open features any time using our Feature Report page.    

Feedback link:  https://www.syncfusion.com/feedback/40747/support-to-handle-the-custom-keyboard-actions-through-shortcuts-widget 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.   

As of now, you can achieve the desired behavior by utilizing the **RowSelectionManager** class. To do so, you will need to override the **handleKeyEvent** method in the **RowSelectionManager** class and add custom logic to perform the desired action when the corresponding key is pressed. To implement this, create an instance of the custom RowSelectionManager class and assign it to the **SfDataGrid.selectionManager** property. A sample code snippet and demonstration can be found in the attached sample.

```dart
class _SfDataGridDemoState extends State<SfDataGridDemo> {
  late CustomSelectionManager customSelectionManager;
  late EmployeeDataSource _employeeDataSource;
  List<Employee> _employees = <Employee>[];

  @override
  void initState() {
    super.initState();
    _employees = getEmployeeData();
    _employeeDataSource = EmployeeDataSource(_employees);
    customSelectionManager = CustomSelectionManager();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Syncfusion Flutter SfDataGrid')),
        body: SfDataGrid(
            source: _employeeDataSource,
            columns: getColumns,
            selectionMode: SelectionMode.multiple,
            selectionManager: customSelectionManager,
            columnWidthMode: ColumnWidthMode.fill));
  }
}

class CustomSelectionManager extends RowSelectionManager {
  CustomSelectionManager();

  @override
  void handleKeyEvent(RawKeyEvent keyEvent) {
    if (keyEvent.logicalKey == LogicalKeyboardKey.keyX &&
        (keyEvent.isControlPressed || keyEvent.isMetaPressed)) {
      /// Write your logics.
      return;
    }
    super.handleKeyEvent(keyEvent);
  }
}

```

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample1232290810 
 
Regards,
Tamilarasan

**Comment by socramm9** [comment]
Thanks for your solution it works like a charm.
