### ISSUE TITLE
[syncfusion_flutter_datagrid] scrolling extremely slow with variable height rows and 1000+ rows

### ISSUE THREAD

**Issue by klondikedragon** [syncfusion/flutter-widgets#1058]
As first reported [here](https://www.syncfusion.com/forums/180143/variable-height-rows-very-slow-with-1k-rows-unusable-with-10k-rows) in the forum, if you have an SfDataGrid where `onQueryRowHeight` is used to set a variable row height, and if the grid has a large number of rows, e.g., 1000 rows or more, then if you use the mouse on the web or desktop to take the scroll thumb and attempt to scroll rapidly down the list, scrolling will freeze up for several seconds at a time. With 10,000+ rows, scrolling becomes unusable and the whole control freezes up for 10+ seconds as you scroll farther down the list.

Some profiling with flutter devtools was showing a couple of problems:
1. On every vertical scrollbar position change, it was rebuilding the line size for *every* row:
    * When the vertical scrollbar changes position it triggers the `_verticalListener` inside of `_ScrollViewWidgetState`
    * This then calls `_container.setRowHeights()`
    * `setRowHeights` function was calling `lineSizeCollection.suspendUpdates()` and then after updating the line size only for currently visible rows (which is fine), it calls `lineSizeCollection.resumeUpdates()`, which was then clearing out the `TreeTable` and repopulating it with the new line size information for every row.
2. Inside of `TreeTable` the red/black tree implementation had several bugs that caused the tree to never rebalance and always have a depth equal to the number of nodes in the tree. This caused operations on the tree to be O(n) instead of O(log n) and thus became very slow the larger the tree became. Bugs in the red/black tree implementation included:
    * Never setting the color of a newly inserted node to red (or any color at all), so no rebalancing/fixup operations were ever run.
    * The leftRotate and rightRotate functions called setLeft and setRight in an order which could cause an infinite loop during bottoms up invalidation inside of those methods, because as it was re-parenting nodes as part of the rotation a loop was temporarily created. The order of operations was changed to carefully avoid all of these scenarios.
    * The delete fixup had several wrong cases that led to an infinite loop as well as incorrect balancing of the tree.

Here is a simple program that reproduces the issue:
```dart
class LargeListDataPoint {
  final DateTime dt;
  final String message;
  const LargeListDataPoint({
    required this.dt,
    required this.message,
  });
}

class LargeListDataGridRow extends DataGridRow {
  final LargeListDataPoint data;
  const LargeListDataGridRow({required super.cells, required this.data});
}

class LargeListDataSource extends DataGridSource {
  static const columnNameDateTime = 'datetime';
  static const columnNameMessage = 'message';

  late final List _rows;
  LargeListDataSource(int desiredRows) {
    final rnd = Random();
    _rows = List.generate(desiredRows, (index) {
      final data = LargeListDataPoint(
        severity:
            SeverityGroups.values[rnd.nextInt(SeverityGroups.values.length)],
        dt: DateTime.now().toUtc(),
        message: List.generate(rnd.nextInt(40), (_) => rnd.nextInt(1 << 31))
            .join(" "),
      );
      return LargeListDataGridRow(
        data: data,
        cells: [
          DataGridCell(
              columnName: columnNameDateTime, value: data.dt.toIso8601String()),
          DataGridCell(columnName: columnNameMessage, value: data.message),
        ],
      );
    }).toList();
  }

  @override
  List get rows => _rows;

  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map((cell) {
      final child = () {
        switch (cell.columnName) {
          case columnNameDateTime:
          case columnNameMessage:
            final text = (cell.value ?? "").toString();
            return Padding(
                padding: const EdgeInsets.only(left: 4.0, right: 4.0),
                child: Text(text));
          default:
            return null;
        }
      }();
      return Container(child: child);
    }).toList());
  }
}

class TestLargeListWidget extends HookWidget {
  const TestLargeListWidget({super.key});

  @override
  Widget build(BuildContext context) {
    const kNumTestItems = 10000;
    final source = useMemoized(
        () => LargeListDataSource(kNumTestItems), [kNumTestItems]);
    return SfDataGrid(
      source: source,
      onQueryRowHeight: (details) {
        return details.getIntrinsicRowHeight(
          details.rowIndex,
          excludedColumns: [
            LargeListDataSource.columnNameDateTime,
          ],
        );
      },
      allowColumnsResizing: false,
      shrinkWrapColumns: false,
      shrinkWrapRows: false,
      headerRowHeight: 25,
      //rowHeight: 32,
      columnWidthMode: ColumnWidthMode.lastColumnFill,
      columns: [
        GridColumn(
          columnName: LargeListDataSource.columnNameDateTime,
          label: const Text("Date/Time"),
        ),
        GridColumn(
          columnName: LargeListDataSource.columnNameMessage,
          label: const Text("Message"),
        ),
      ],
    );
  }
}
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @klondikedragon,

The fix for the reported issue “The scrolling performance is degrading when autofitting the rows using onQueryRowHeight with large set of rows” has been included in the latest DataGrid version **20.4.53**. [Update](https://pub.dev/packages/syncfusion_flutter_datagrid/changelog) your DataGrid to get the issue resolved.

Regards,
Tamilarasan

**Comment by ps6067966** [comment]
Even when onQueryRowHeight  is not used. if we scroll in 1000+ rows, screen will freeze. 
and If use pagination and download all the records in not working using sf grid key. 

if anyone have any workaround for this then please help.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ps6067966,

**Regarding: Even when onQueryRowHeight is not used. if we scroll in 1000+ rows, screen will freeze.** 

We have thoroughly tested the attached sample(contains 2000 rows without using onQueryRowHeight) with the latest version of DataGrid (21.1.35) and were unable to reproduce the issue you reported. The sample appears to be functioning correctly, as evidenced by the video output we have provided for your reference.

If you are still experiencing the same issue, please provide us with additional information including the sample you are using, the versions of DataGrid you are currently using and Flutter Doctor details, and any other relevant details. This will help us better understand the problem and provide an appropriate solution as soon as possible.

**Regarding: and If use pagination and download all the records in not working using sf grid key.**

We would like to request for additional information regarding your query. Are you currently using pagination and attempting to export all data into a PDF document or Excel workbook using the DataGrid-Export feature? Providing more specific details regarding your issue will allow us to offer a more accurate solution in a timely manner.


https://user-images.githubusercontent.com/93904422/228461030-7a2859d2-cce8-4339-87d9-60ab1846c7f1.mp4



Sample Link:  [sample.zip](https://github.com/syncfusion/flutter-widgets/files/11097751/sample.zip)


Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @klondikedragon,

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
