### ISSUE TITLE
Custom tooltip for SfSlider

### ISSUE THREAD

**Issue by madhukesh048** [syncfusion/flutter-widgets#1062]
Hi, I m trying to customise tooltip for my slider. Is there any way or are you guys considering to add this anytime soon?
Thanks in advance

**Comment by Yuvaraj-Gajaraj** [comment]
We already have the option to customize the tooltip UI and its shapes by follows,

1. ​Using [SfSliderThemeData.tooltipBackgroundColor](https://help.syncfusion.com/flutter/slider/tooltip#tooltip-color) and [SfSliderThemeData.tooltipTextStyle](https://help.syncfusion.com/flutter/slider/tooltip#tooltip-label-style), we can customize the default tooltip's background and text style.
2. Using [SfSlider.tooltipShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/tooltipShape.html) to re-render the complete tooltip UI (refer to further details https://help.syncfusion.com/flutter/slider/tooltip#tooltip-shape).
3. Additionally, we can also place a widget on the thumbs using [SfSlider.thumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/thumbIcon.html).
