### ISSUE TITLE
Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null

### ISSUE THREAD

**Issue by lotustha** [syncfusion/flutter-widgets#1063]
/C:/Users/allth/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.4.48/lib/src/datagrid_widget/widgets/cell_widget.dart:700:31: Error: Property 'context' cannot be accessed on 'OverlayState?' because it is potentially null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
Try accessing using ?. instead.
          Overlay.of(context).context.findRenderObject()! as RenderBox;
                              ^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

syncfusion_flutter_datagrid: ^20.4.48

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by berkanaslan** [comment]
Same issue here.

![image](https://user-images.githubusercontent.com/42192003/216363430-52afecc5-c71d-40fe-ab25-725e69b5b3c1.png)

**Comment by mariumshah** [comment]
Getting the same issue since yesterday. It was however working fine before.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @lotustha / @berkanaslan ,

Based on the information you have provided, it appears that you may be using an outdated version of the Flutter SDK. I have tested the DataGrid using the latest version (**3.7.1**) and have not encountered the issue you have described.

To help resolve the issue you are experiencing, I recommend upgrading your **Flutter SDK to the latest stable version (3.7.1)**. This may resolve the issue you are experiencing.

Regards,
Tamilarasan

**Comment by galiperkin** [comment]
Upgrading to Flutter 3.7.1 solved this issue. @Tamilarasan-Paranthaman thank you 🥳
