### ISSUE TITLE
[syncfusion_flutter_core] error build in 20.4.48

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#1064]
i get this error 
```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not found.
  final PanAxis panAxis;
        ^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:15:22: Error: Undefined name 'PanAxis'.
      this.panAxis = PanAxis.free,
                     ^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: 'PanAxis' isn't a type.
  final PanAxis panAxis;
        ^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:299:9: Error: No named parameter with the name 'panAxis'.
        panAxis: widget.panAxis,
        ^^^^^^^
../../../flutter/packages/flutter/lib/src/widgets/interactive_viewer.dart:61:3: Context: Found this candidate, but the arguments don't match.
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^
```

**Comment by juangabrielsl1015** [comment]
I have the same error when i use Flutter SDK 3.3.6, but if i update to the latest 3.7.0 the package syncfusion_flutter_pdfviewer works fine. They should continue to support the previous versions =(

**Comment by iliasaddab** [comment]
same here

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue is caused by a recent upgrade to the Flutter version. In previous versions, the alignPanAxis property was a Boolean, but in version 3.7.0, it was changed to an enum type. To resolve this issue, either upgrade the Flutter SDK to the latest version or use Syncfusion package version 20.4.44. The breaking change PR can be found below for your reference

https://github.com/flutter/flutter/pull/109014/commits/1c6f20c8b3dc8e10258a626d401161db2942ddca

**Comment by GSORF** [comment]
Hi @Yuvaraj-Gajaraj,

> The reported issue is caused by a recent upgrade to the Flutter version. In previous versions, the alignPanAxis property was a Boolean, but in version 3.7.0, it was changed to an enum type. To resolve this issue, either upgrade the Flutter SDK to the latest version or use Syncfusion package version 20.4.44. The breaking change PR can be found below for your reference
> 
> [flutter/flutter@1c6f20c](https://github.com/flutter/flutter/commit/1c6f20c8b3dc8e10258a626d401161db2942ddca)

Thank you for your suggestion. With your help I was able to resolve my problem in the duplicate issue [#1069](https://github.com/syncfusion/flutter-widgets/issues/1069#issuecomment-1418298429)! It wasn't smooth, so I tried to document as much as possible.

Thanks a lot!

Kind regards,
Adam
