### ISSUE TITLE
[syncfusion_flutter_charts] Horizontal drag problem with line chart

### ISSUE THREAD

**Issue by hoanguyenthai11** [syncfusion/flutter-widgets#1068]
Hello. I am facing a line chart horizontal drag action problem. Specifically on the virtual device iphone 13 pro max (syncfusion_flutter_charts: lastest version) I can't drag all the way to the left resulting in the first value in the X axis not showing up. However on all devices at 19.2.47 version and on Android devices (latest version) this does not occur. How can I solve it. 

19.2.47 version on the virtual device iphone 13 pro max
![Simulator Screen Shot - iPhone 13 Pro Max - 2023-02-04 at 20 47 37](https://user-images.githubusercontent.com/91382480/216771252-1ee12c87-4648-475b-8665-d657f8b2d4e5.png)

The lastest version on the virtual device iphone 13 pro max
![Simulator Screen Shot - iPhone 13 Pro Max - 2023-02-04 at 20 50 37](https://user-images.githubusercontent.com/91382480/216771332-f526b58a-47b0-41bb-bc3e-93abcbba6037.png)

I clone source code from here : https://github.com/SyncfusionExamples/how-to-create-a-flutter-line-chart-in-10-minutes

Hope to hear from you soon.

**Comment by natrayansf** [comment]
We have reviewed your inquiry and have been able to replicate the reported issue regarding the 'Horizontal drag problem with line chart with iPhone 13 pro max'. We have logged a bug report for it in our feedback portal and will fix and include the changes in the first weekly patch release after the Volume 2 main release, which is expected to be released by the end of this month. We will update you once the release is rolled out and appreciate your patience until then. You can also track the status of the bug with the feedback below.

FR Link - https://www.syncfusion.com/feedback/44233/horizontal-panning-is-not-working-properly-in-ios-device

**Comment by sfHariHaraSudhan** [comment]
Hi @hoanguyenthai11,

The reported issue regarding **Horizontal panning is not working properly in iOS device** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.1.36

Regards,
Hari Hara Sudhan. K.
