### ISSUE TITLE
[SFCartersianChart] FireStore Data Pagination Support inside FutureBuilder

### ISSUE THREAD

**Issue by devrajraut** [syncfusion/flutter-widgets#107]
Is there a Way to Paginate Data from FireStore to use in 'series' of SFCartesianChart() inside a FutureBuilder

For Eg:

return FutureBuilder(
    future: _futureFirestoreGetDocuments,
    builder: (context, snapshot) {
        return SfCartesianChart(
            series: SplineSeries<DataPoint<DateTime>, DateTime>(
                            dataSource: _primarySource,
            )
        )
     }
);

I want to know how to Paginate _primarySource to fetch only Limited Documents from Firestore and fetch more only when I PAN the Chart to the left on a DateTime Axis Chart for older Data.

**Comment by Dharanipalani** [comment]
Hi Devraj,   

Greetings from Syncfusion. We have already logged a feature request for your scenario and this will be available in our upcoming vol 1 main release 2021 which is expected to be rolled out at the end of March 2021. We will update you once the feature has been rolled out and we appreciate your patience until then. Using this, you can fetch the required data from your database. You can track the status of this feature using the feedback link.   

Feedback link:  [https://www.syncfusion.com/feedback/11947](url)

Thanks,   
Dharanitharan. P

**Comment by Dineshkumar-kovalan** [comment]
Hi @devrajraut, 
  
Thanks for your patience. The requested pagination feature is now rolled out in our vol 1 main release. Here’s an overview of the feature. 
  
SfCartesianChart now comes with an onPlotAreaSwipe callback and by using this callback, the user will be able to achieve pagination functionality (on swiping over chart area, next set of data points can be loaded to the chart). Also, this callback provides the direction of the swipe through ChartSwipeDirection enum. 
  
Demo: https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/pagination 
User guide: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onplotareaswipe 
Code snippet: https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/on_demand_loading/pagination.dart 
  
To use the feature, kindly upgrade to the latest version below. 
https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1 
  
Please revert us if you still have further concerns. 
  
Regards, 
Dineshkumar K
