### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt, SfCartesianChart.

### ISSUE THREAD

**Issue by barilki** [syncfusion/flutter-widgets#1071]
I'm using SfCartesianChart and CandleSeries.
When I add ChartRangePadding.additional, an exception is thrown
primaryXAxis: DateTimeCategoryAxis(
                          rangePadding: ChartRangePadding.additional,
                          .....
                           )

**Comment by Yuvaraj-Gajaraj** [comment]
We have tried to reproduce the reported issue regarding getting an infinity or NaN toInt exception while setting the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) to [additional](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartRangePadding.html). But the reported issue is not getting reproduced at our end. So, we kindly request you share more information about your chart complete code snippet, and data source, and please try to reproduce the reported issue in the shared sample below. it will be more helpful for us to assist you in a better way.

Sample: 
[i436064.zip](https://github.com/syncfusion/flutter-widgets/files/10663382/i436064.zip)
