### ISSUE TITLE
Support for flip animation

### ISSUE THREAD

**Issue by bishal-rumba007** [syncfusion/flutter-widgets#1075]
is it possible to use flip book animation instead of normal slide animation?

**Comment by LavanyaGowtham2021** [comment]
Hi bishal,

We have checked your query and we are unable to understand your requirement clearly. Please provide us with more information on your requirement in detail, along with screenshots/screen recordings, so that we can assist you better. 

Regards,
Lavanya A.

**Comment by bishal-rumba007** [comment]
I want to achieve flip animation like this using your pdf viewer. for example, I have a pdf of a book and I want to show the content in pdf view along with the flip effect. the image below is for reference of the book flip animation


![images](https://user-images.githubusercontent.com/80207943/218943691-eafe1363-2e29-4a61-8529-ca4fc7e9d43d.jpeg)

**Comment by deepika134** [comment]
Hi bishal, we do not have support to show a Pdf document with flip animation in the Flutter Pdf Viewer and also it is an out of box requirement of Pdf Viewer.
