### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Material design loader shown when initializing SfPdfViewer.memory

### ISSUE THREAD

**Issue by peer-f** [syncfusion/flutter-widgets#1077]
I'm using the newest version 20.4.48 of the PDF viewer package and I've discovered that after onDocumentLoaded() was called which I use to end the loading state of the document the SfPdfViewer widget shows a small blue circular loader. This is the case when using SfPdfViewer.memory which is the only type of viewer that we use right now. Does this have anything to do with the viewer not being fully initialized? I would like to be able to disable this behaviour or provide a custom loading widget since the current implementation violates our corporate design. This loader also appears when scrolling quickly through pages using PdfPageLayoutMode.continuous. Thank you!

![IMG_0058](https://user-images.githubusercontent.com/26091730/216988234-c90fecaa-ce58-4b0e-b6c2-fd7b1e2db69c.jpg)

**Comment by deepika134** [comment]
Hi @peer-f , We have used the native platform renderer (a plugin-based approach) to retrieve the PDF pages in our Flutter PdfViewer and this causes the delay (approx. 1 second) on displaying the pages while performing page transition. In this case, we are showing the loading indicator until the pages are displayed in our PdfViewer so, that it indicates that the pages are still loading. Kindly share your complete use case and requirement to proceed further.

**Comment by peer-f** [comment]
Hi, thanks for the quick reply. Currently we handle all the logic of our PDF viewer through riverpod/statenotifier so we display the correct PDF viewer widget for each type of PDF (asset, network, memory) by giving a freezed union with the required data as parameter into the widget.

This works fine so far and the performance is good but after calling onDocumentLoaded() we set the state.documentLoading variable to false to display the SfPdfViewer widget. After that there is still another loader being shown by SfPdfViewer widget which works the way you described it. I would like to be able to provide a custom loading widget to the SfPdfViewer or atleast be able to customize the way the loader looks while initializing the viewer or fetching more pages.

I've attached you a small demo that shows how our PDF viewer works:

```
import 'package:common/common.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class PdfViewer extends ConsumerWidget {
  const PdfViewer({
    required this.param,
    Key? key,
  }) : super(key: key);

  final PdfViewerParam param;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(pdfViewerControllerProvider(param));

    return Scaffold(
      appBar: BasicAppBar(
        onBackPressed: param.onPdfClosed,
        title: param.title,
      ),
      body: state.documentLoading
          ? const Center(
              child: CircularLoader(),
            )
          : param.map(
              asset: (assetParam) => SfPdfViewer.asset(
                assetParam.path,
                controller: state.controller,
                onDocumentLoaded: (details) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).onDocumentLoaded(details),
                onDocumentLoadFailed: (details) => ref
                    .read(pdfViewerControllerProvider(param).notifier)
                    .onDocumentLoadFailed(details),
                onPageChanged: (page) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).changePage(
                          page.newPageNumber,
                        ),
                canShowScrollHead: false,
                interactionMode: PdfInteractionMode.pan,
                pageLayoutMode: PdfPageLayoutMode.single,
                scrollDirection: PdfScrollDirection.horizontal,
              ),
              network: (networkParam) => SfPdfViewer.network(
                networkParam.url,
                controller: state.controller,
                onDocumentLoaded: (details) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).onDocumentLoaded(details),
                onDocumentLoadFailed: (details) => ref
                    .read(pdfViewerControllerProvider(param).notifier)
                    .onDocumentLoadFailed(details),
                onPageChanged: (page) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).changePage(
                          page.newPageNumber,
                        ),
                canShowScrollHead: false,
                interactionMode: PdfInteractionMode.pan,
                pageLayoutMode: PdfPageLayoutMode.single,
                scrollDirection: PdfScrollDirection.horizontal,
              ),
              memory: (memoryParam) => SfPdfViewer.memory(
                memoryParam.bytes,
                controller: state.controller,
                onDocumentLoaded: (details) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).onDocumentLoaded(details),
                onDocumentLoadFailed: (details) => ref
                    .read(pdfViewerControllerProvider(param).notifier)
                    .onDocumentLoadFailed(details),
                onPageChanged: (page) =>
                    ref.read(pdfViewerControllerProvider(param).notifier).changePage(
                          page.newPageNumber,
                        ),
                canShowScrollHead: false,
                interactionMode: PdfInteractionMode.pan,
                pageLayoutMode: PdfPageLayoutMode.single,
                scrollDirection: PdfScrollDirection.horizontal,
              ),
            ),
    );
  }
}

```

**Comment by deepika134** [comment]
Hi @peer-f , We do not have support for adding a custom loading widget in SfPdfViewer. We can provide the option to disable the loading indicator, but SfPdfViewer will show a white page until the page is loaded or do you want to change the loading indicator? Please let us know if the above meets your needs so that we can check further.

**Comment by peer-f** [comment]
HI @deepika134, I think it would be nice to have both options. A custom widget would awesome because this way we would be able to use consistent loaders throughout the whole application but it's not a must in my opinion. I liked the customization options for different elements in syncfusion_flutter_charts. A class like TrackballMarkerSettings with a couple of options to customize the loader design would be more than enough.

**Comment by deepika134** [comment]
Hi @peer-f , we are checking on the feasibility for disable the circular progress bar indicator in SfPdfViewer. Kindly provide the more information about the customisation needs for the circular progress bar on your end.

**Comment by shamil-pp** [comment]
I cache network files and display them from storage when a user opens them again.  The Syncfusion progress indicator only appears after a file has been downloaded from the network; a blank white screen is displayed while the file is being downloaded from the network. Is there any simple workaround to display the progress bar during download?

PDFViewerScreen
`class PDFViewerScreen extends StatefulWidget {
  final Map<String, dynamic> material;

  const PDFViewerScreen({
    key,
    required this.material,
  }) : super(key: key);

  @override
  _PDFViewerScreenState createState() => _PDFViewerScreenState();
}

class _PDFViewerScreenState extends State<PDFViewerScreen> {
  String? _title;
  File? _file;
  bool _isReady = false;

  @override
  void initState() {
    super.initState();
    _title = widget.material['title'];
    PDFBrain.loadFile(widget.material['link']).then(
      (file) {
        setState(() {
          _file = file;
        });
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_title!)
),
      body: _file != null
          ? SfPdfViewer.file(
              _file!,
              onDocumentLoaded: (_) {
                setState(() {
                  _isReady = true;
                });
              },
            )
          : Container(),
    );
  }
}`

PDFBrain
`class PDFBrain {
  static Future<File> loadFile(String url) async {
    final filename = basename(url);
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$filename');
    if (await file.exists()) {
      return file;
    }

    final response = await http.get(Uri.parse(url));
    final bytes = response.bodyBytes;
    if (response.statusCode == 200) {
      return _storeFile(file, bytes);
    } else {
      throw Exception('Failed to load PDF. Error code: ${response.statusCode}');
    }
  }

  static Future<File> _storeFile(File file, List<int> bytes) async {
    await file.writeAsBytes(bytes, flush: true);
    return file;
  }`

**Comment by shamil-pp** [comment]
I cache network files and display them from storage when a user opens them again.  The Syncfusion progress indicator only appears after a file has been downloaded from the network; a blank white screen is displayed while the file is being downloaded from the network. Is there any simple workaround to display the progress bar during download?

PDFViewerScreen
```
class PDFViewerScreen extends StatefulWidget {
  final Map<String, dynamic> material;
  const PDFViewerScreen({
    key,
    required this.material,
  }) : super(key: key);

  @override
  _PDFViewerScreenState createState() => _PDFViewerScreenState();
}

class _PDFViewerScreenState extends State<PDFViewerScreen> {
  String? _title;
  File? _file;
  bool _isReady = false;

  @override
  void initState() {
    super.initState();
    _title = widget.material['title'];
    PDFBrain.loadFile(widget.material['link']).then(
      (file) {
        setState(() {
          _file = file;
        });
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(_title!)
),
      body: _file != null
          ? SfPdfViewer.file(
              _file!,
              onDocumentLoaded: (_) {
                setState(() {
                  _isReady = true;
                });
              },
            )
          : Container(),
    );
  }
}
```
PDFBrain
```
class PDFBrain {
  static Future<File> loadFile(String url) async {
    final filename = basename(url);
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$filename');
    if (await file.exists()) {
      return file;
    }

    final response = await http.get(Uri.parse(url));
    final bytes = response.bodyBytes;
    if (response.statusCode == 200) {
      return _storeFile(file, bytes);
    } else {
      throw Exception('Failed to load PDF. Error code: ${response.statusCode}');
    }
  }

  static Future<File> _storeFile(File file, List<int> bytes) async {
    await file.writeAsBytes(bytes, flush: true);
    return file;
  }
```

**Comment by deepika134** [comment]
Hi @shamil-pp , I have modified your sample as per your requirement and please find the modified sample from the attachment (along with the output screen record of the same).
Please try the shared example and let us know if this meets your requirement or not.
[github.zip](https://github.com/syncfusion/flutter-widgets/files/10779557/github.zip)

**Comment by peer-f** [comment]
Hi @deepika134 I think having customization options similar to the ones of the Material CircularProgressIndicator would be more than enough. Having the option to disable the loading indicator would be nice too.

**Comment by deepika134** [comment]
Hi @peer-f , At present, we do not have support to hide the circular progress bar indicator in SfPdfViewer. We have considered this requirement, and it will be included in the Volume 1 SP release, which is expected to be rolled out at the end of April 2023.

**Comment by peer-f** [comment]
Awesome, thank you so much! I'm looking forward to the release.

**Comment by deepika134** [comment]
We are glad to announce that the support for hide the circular progress bar indicator has been included in our Essential Studio 2023 Volume 1 Service Pack release v21.2.3 is rolled out and is available for download under the following link.



[Essential Studio 2023 Volume 1 Service Pack Release v21.2.3 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/182145/essential-studio-2023-volume-1-service-pack-release-v21-2-3-is-available-for-download)



We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
