### ISSUE TITLE
Slider gradient background color

### ISSUE THREAD

**Issue by guyluz11** [syncfusion/flutter-widgets#1078]
Is there a way to select a gradient background color for the slider?

![image](https://user-images.githubusercontent.com/9304740/217878528-801b84d3-aaa9-4220-8def-6361d5661122.png)

**Comment by daddowzoubair** [comment]
Browse here 

https://flutter.syncfusion.com/?_gl=1*zjhchb*_ga*NzU1NTE5ODI1LjE2NjkwMzc1NTE.*_ga_WC4JKKPHH0*MTY3MjkyNjUyOC4yMy4xLjE2NzI5MjY1NDkuMC4wLjA.&_ga=2.183238959.882172536.1672926528-755519825.1669037551#/linear-gauge/axis/track

**Comment by guyluz11** [comment]
Thanks, I couldn't find anything that resembles gradient background for slider

> Browse here
> 
> https://flutter.syncfusion.com/?_gl=1*zjhchb*_ga*NzU1NTE5ODI1LjE2NjkwMzc1NTE.*_ga_WC4JKKPHH0*MTY3MjkyNjUyOC4yMy4xLjE2NzI5MjY1NDkuMC4wLjA.&_ga=2.183238959.882172536.1672926528-755519825.1669037551#/linear-gauge/axis/track

**Comment by guyluz11** [comment]
Cool option thanks @natrayansf 

Owner of the package
Sould I close this issue or so you want to create more straight forward way with properties?

**Comment by LokeshPalani** [comment]
Hi @guyluz11,

Most Welcome. Please feel free to contact us if you have any further questions. We are always happy to assist you.

Unfortunately, there is currently no direct API available to create a gradient background for the slider. We are closing this GitHub issue.

Regards,
Lokesh.
