### ISSUE TITLE
[syncfusion_flutter_calendar] appointmentBuilder difficulty showing (Day n/N)

### ISSUE THREAD

**Issue by pauldemarco** [syncfusion/flutter-widgets#108]
I'm attempting to use the appointmentBuilder but running into some trouble calculating which day count I'm trying to build, i.e. **(Day 1/2), (Day 2/3), ...**.

The CalendarAppointmentDetails carries **details.date** and the recurring event information. One solution is to rebuild all instances of the recurring event, find the instance that falls previous to **details.date**, and then count the days up from there until we have **details.date**. But this would have some nasty edge cases.

I'd like to propose a feature request where the day count is passed in through CalendarAppointmentDetails.

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are validating the reported scenario. We will validate and update you on the details on or before January 11, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi, 
 
We will consider this as a feature and logged the feature request for “Getting the occurrence date details from occurrence appointments in the Flutter calendar”. We will implement this feature in our upcoming 2021 Volume 1 release, which is expected to rolled out on March 2021, and let you know once the release rolled out. We appreciate your patience until then. 
 
You can track the status of this report through the following feedback link, 
 
**Feedback link:** 
https://www.syncfusion.com/feedback/21277/provide-occurrence-date-details-for-occurrence-appointments 
 
We hope that this helps you. Please let us know if you need further assistance. 
 
Regards, 
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

As we have more highly prioritized and promised release plans, we didn’t plan this feature in our 2021 Volume 1 release. We will consider this feature with high priority and implement this feature in our upcoming 2021 Volume 2 release, which is expected to be rolled out by end of June 2021. We will let you know when this feature is implemented. We appreciate your patience until then.   

You can track the status of this report through the following feedback link, 

**Feedback link:** 
https://www.syncfusion.com/feedback/21277/provide-occurrence-date-details-for-occurrence-appointments

Regards,
Indumathi R
