### ISSUE TITLE
Flutter SyncFusion DataGrid get index of Focused Row which focused by arrow up or down key or enter key.

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1080]
i want to get index of focused row which focused by arrow up and down key. butt row not yet selected.
![image](https://user-images.githubusercontent.com/62530396/218261373-67aa0452-445c-4146-b44d-ac8b1c624fcc.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

As of now, DataGrid does not have support for getting current cell details when the **navigation** mode is **row**. We have considered your request as a feature. This feature will be implemented in our 2023 Volume 1 release, which is expected to be rolled out at the end of March 2023. We will let you know when this feature is implemented. We appreciate your patience until then. You can follow up with the below feedback for further details,

Feedback link: https://www.syncfusion.com/feedback/41070/support-to-get-the-current-cell-details-from-the-datagridcontroller-when-the 

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
waiting for this feature .please need it urgent. waiting for your positive response thanks.

**Comment by Tamilarasan-Paranthaman** [comment]
@abdulrehmananwar,

We are glad to announce that our Essential Studio 2023 Volume 1 Main Release V21.1.0.35 is rolled out. The support to get the current cell details from the **DataGridController.currentCell.rowIndex** when the navigation mode is row has been included in version **21.1.35**.

Pub Link: https://pub.dev/packages/syncfusion_flutter_datagrid/changelog 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Comment by abdulrehmananwar** [comment]
THANKS
