### ISSUE TITLE
Exception has occurred. _CastError (Null check operator used on a null value) - needAnimation

### ISSUE THREAD

**Issue by daddowzoubair** [syncfusion/flutter-widgets#1082]
I have this exception after update 
base -> series-base.dart

![image](https://user-images.githubusercontent.com/117348118/218750241-7f19e407-87a2-4d7d-81b5-d247ed63332b.png)

**Comment by LavanyaGowtham2021** [comment]
Hi @daddowzoubair,

Please reopen this ticket with requested details, if you still face an issue with latest charts version.

Regards,
Lavanya A.

**Comment by daddowzoubair** [comment]
Thank you very much @LavanyaGowtham2021  && @LokeshPalani 
the problem fixed when I used the latest version
