### ISSUE TITLE
[syncfusion_flutter_charts] type 'Null' is not a subtype of type 'TrackballTemplateState' in type cast

### ISSUE THREAD

**Issue by demoYang** [syncfusion/flutter-widgets#1083]
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/7134823/219576460-baf93853-8cc2-44be-a183-84761a3997ca.png">

```
  void showTemplateTrackball(Offset position) {
    final GlobalKey key = trackballTemplate!.key as GlobalKey;
    final TrackballTemplateState trackballTemplateState = key.currentState as TrackballTemplateState;
   ....
}
```
 `key.currentState may null`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi,



We suspect that you have used as [groupAllPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html) mode for the trackball tooltip display. When using this mode, all available series values are stored in a list field called [groupingModeInfo](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/groupingModeInfo.html) within the [TrackballDetails](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails-class.html). To get the grouped trackball details, we suggest that you use the [groupingModeInfo](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/groupingModeInfo.html)field in the [TrackballDetails](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails-class.html) argument.  We have shared the code snippet and online sample below for your reference.



Code snippet:
```dart
trackballBehavior = TrackballBehavior(
   enable: true,
   tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
   builder: (context, trackballDetails) {
     return Container(
       child: Center(
         child: Text(
             '${trackballDetails.groupingModeInfo!.points[0].x} \n
              ${trackballDetails.groupingModeInfo!.points[0].y}'),
       ),
     );
   },
 )
```

Sample: https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/trackball/customized-trackball



Regards,
Yuvaraj.

**Comment by demoYang** [comment]
> We suspect that you have used as [groupAllPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html) mode for the trackball tooltip display. When using this mode, all available series values are stored in a list field called [groupingModeInfo](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/groupingModeInfo.html) within the [TrackballDetails](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails-class.html). To get the grouped trackball details, we suggest that you use the [groupingModeInfo](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/groupingModeInfo.html)field in the [TrackballDetails](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails-class.html) argument. We have shared the code snippet and online sample below for your reference.
> 
> Code snippet:
> 
> ```dart
> trackballBehavior = TrackballBehavior(
>    enable: true,
>    tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
>    builder: (context, trackballDetails) {
>      return Container(
>        child: Center(
>          child: Text(
>              '${trackballDetails.groupingModeInfo!.points[0].x} \n
>               ${trackballDetails.groupingModeInfo!.points[0].y}'),
>        ),
>      );
>    },
>  )
> ```
> 
> Sample: https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/trackball/customized-trackball

yes , i use  groupingModeInfofield in the TrackballDetails argument, but still has this issue,  
The issue happens only on iPad. 
 Why not adjust key.currentState is null ?

**Comment by timonaldenhoff** [comment]
Same issue in 20.4.51: 

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type 'Null' is not a subtype of type 'TrackballTemplateState' in type cast. Error thrown Instance of 'ErrorDescription'.
       at TrackballRenderingDetails.showTemplateTrackball(trackball.dart:807)
       at TrackballRenderingDetails.showTrackball(trackball.dart:798)
       at TrackballRenderingDetails.internalShowByIndex(trackball.dart:1865)
       at SfCartesianChartState._validateStateMaintenance(chart_base.dart:2126)
       at SfCartesianChartState._renderChartElements.<fn>.<fn>(chart_base.dart:1800)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1289)
       at SchedulerBinding.handleDrawFrame(binding.dart:1227)
       at SchedulerBinding._handleDrawFrame(binding.dart:1076)

**Comment by Yuvaraj-Gajaraj** [comment]
We have tried to reproduce the reported issue that is getting a null exception while using the trackball public method [show](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/show.html) with the tooltip display mode as groupAllPoints, but the issue is not reproduced at our end. So, we kindly request you to share more information on your requirement in detail along with screenshots or screen recordings, and we have also shared the sample below, please try to reproduce the reported issue and get back to us. So that it will help us assist you in a better way.

sample: [i439664.zip](https://github.com/syncfusion/flutter-widgets/files/10964903/i439664.zip)
