### ISSUE TITLE
SfDataGrid: DataGridSource lacks of build context 

### ISSUE THREAD

**Issue by gwsch** [syncfusion/flutter-widgets#1085]
The DataGridSource helper class of SfDataGrid is the abstraction handling with the raw data. However the `DataGridRowAdapter? buildRow(DataGridRow row)` and `Widget? buildEditWidget(DataGridRow dataGridRow, RowColumnIndex rowColumnIndex, GridColumn column, CellSubmit submitCell)` depends on Widget construction. But in which BuildContext? For the time being I'm just guessing by setting e.g. a theme property in DataGridSource while in State<SfDataGrid>'s `@override Widget build(BuildContext context)` and hope for the best. Pretty dirty.
Please equip build methods with a BuildContext parameter -it's redundant in State<T> but not in other classes.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @gwsch,

Based on your requirement, you can access the build context by either declaring the build context in the DataGridSource class or by using the [**builder**](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget. We recommend using the [**builder**](https://api.flutter.dev/flutter/widgets/Builder-class.html) widget to access the context inside the DataGridSource, as it allows you to create widgets dynamically during the build process. You can use the builder widget in the respective methods to access the **context**.

Here's an example code snippet that demonstrates how to use the builder widget in the DataGridSource class.

```dart
class EmployeeDataSource extends DataGridSource {

…

 @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((DataGridCell cell) {
      return Builder(
        builder: (context) {
          return Container(
            alignment: Alignment.center,
            child: Text(
              cell.value.toString(),
            ),
          );
        }
      );
    }).toList());
  }

@override
  Widget? buildEditWidget(DataGridRow dataGridRow,
      RowColumnIndex rowColumnIndex, GridColumn column, CellSubmit submitCell) {

…

    return Builder(builder: (context) {
      return Container(
        padding: const EdgeInsets.symmetric(horizontal: 8.0),
        child: TextField(),
      );
    });
  }

}

```
Regards,
Tamilarasan

**Comment by gwsch** [comment]
Hi Tamilarasan,
thanks very much. But there's still a slight problem with this approach caused by the 'context free' DataGridRowAdapter:
  ```
@override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    final vertex =
        row.getCells().firstWhere((element) => element.columnName == elementIdColumn).value as _GraphEditVertex;
    return DataGridRowAdapter(
          color: _getRowBackground(vertex, themeData),
          cells: row.getCells().map<Widget>((dataCell) {
            return Builder(builder: (BuildContext context) => _dataCell(context, dataCell, vertex));
          }).toList());
  }
```
The color is calculated via context settings and here is it were some 'magic' must be applied. I don't know the context of the DataGridAdapter and I cannot create one because it's not a widget.

by the way: Here is my 'wrapper suggestion' for issue #940 in action

**Comment by gwsch** [comment]
Thank you very much.
