### ISSUE TITLE
 live charts in flutter, I set up a marker, and after the graph updates once it just disappears

### ISSUE THREAD

**Issue by Yuval270** [syncfusion/flutter-widgets#1087]
Marker disappears after the live chart updates once

I tried 3 main ways. The first one was using setState, that did not work. The second one was using updateDataSource, took inspiration from https://github.com/SyncfusionExamples/how-to-create-a-real-time-flutter-chart-in-10-minutes/blob/main/lib/main.dart, but it seems that the graph doesnt appear for me in this technique. Lastly, the only thing that actually shows the graph for me is using stream builder, but with stream builder the marker only appears for a split second before the graph updates.

keep in mind i couldnt copy paste this code, it was on a different computer not connected to the internet, thus I had to type it on my own, so there might be small typos here and there.

class _GraphState extends State<Graph>{
    @override
    Widget build(BuildContext context{
    final pointsProvider = Provider.of(PointsProvider>(context);
    
    Stream<List<Point>> stream() async*{
    while (true){
    await Future<void>delayed(Duration(miliseconds: 200));
    await pointsProvider.fetchPoints();
    yield pointsProvider.points as List<Point>;
    }
  }
  

    return StreamBuilder(
      stream: stream(),
      builder: (context, snapshot){
        return Container(
          margin: EdgeInsets.symmetric(horizontal: 40),
          decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(7)),
          width: 960
          height: 360,
          child: SfCartesianChart(
            onMarkerRender: (args){
              if (args.pointsIndex! != 50){
                args.markerHeight = 0;
                args.markerWidth = 0;
                }
            },
        plotAreaBackgroundColor: Color.fromRGBO(46, 46, 46, 1),
        series: <ChartSeries>[
          LineSeries<Point, double>(
            markerSettings: MarkerSettings(
              isVisible: true,
              height: 40,
              color: Colors.black,
              width: 20,
              ),
            color: Colors.yellow,
            dataSource:
            pointsProvider.points as List<Point>,
            xValueMapper: (Point data, _) => point.x,
            yValueMapper: (Point data, _) => point.y,
            ),
          ],
         ),
       );
       },
       );
      

}
}

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your query at our end and, as we are unable to understand what you are proposing as your requirement, we kindly request that you share more information on the required chart code snippet to reproduce the issue and screenshots or screen recordings, so that it will help us to assist you better.

**Comment by Yuval270** [comment]
What information do you require?
Unfortunately I cannot show either screen shots or recording, as I've signed an nda.
Could you tell me what other information is lacking from on my part?

**Comment by Yuval270** [comment]
What information do you require?
Unfortunately I cannot show either screen shots or recording, as I've signed an nda.
Could you tell me what other information is lacking from on my part?
