### ISSUE TITLE
[syncfusion_flutter_datagrid] How to access original data source item in onTap?

### ISSUE THREAD

**Issue by divan** [syncfusion/flutter-widgets#1089]
So my common pattern of using datagrid is following:

1. Pass `List<SomeType>` to DataSource and build rows.
2. Allow user filter/sort data
3. By clicking on the found entries, open some widget (like modal with editing form)

Currently what I'm doing to achieve it is following:

1. Store original data in DataSource class
2. When user clicks the row, I pass these to `onCellTap`:
```dart
  _onCellTap(DataGridCellTapDetails details) {
    // get the index, excluding header row
    final idx = details.rowColumnIndex.rowIndex - 1;
    if (idx < 0 || idx >= source!.data!.length) return;

    // find the original source item by the index
    final item = source?.itemAt(idx);

    // launch popup with the given item
    if (widget.onTap != null && item != null) {
      widget.onTap!(item);
    }
  }
```
Function `itemAt(idx)` looks like this:
```dart
  dynamic itemAt(int idx) {
    // get the row from effective rows

    var row = effectiveRows[idx];
     // first column is, by convention, is an ID value

    final id = row.getCells()[0].value;
     // find actual item by ID
    return _originalData!.firstWhere((e) => e?.id == id);
  }

```

This approach kind works, though forces me to specify "id" column for each caller (I use a class that is a wrapper around SfDataGrid which minimizes the number of things to pass). It's probably not efficient (now sure how fast `firstWhere` lookup, maybe need to build a map for faster lookup here).

Another approach I considered is to store original item object in the hidden column (like always the last column) and then retrieve it from in onCellTap. But, again, not sure about performance implication of such a solution.

Both of those feel too heavy and complicated for such a simple thing as "getting the data of the clicked row". The complicated part also is that naive approach (lookup by index from _originalData) kinda works and gives the feeling that problem solved, until you realize that sorted/filtered data will have different indexes and you need to use effectiveRows.

So two questions:
 1. Is it possible somehow to achieve what I want without forcing usage of "id" column?
 2. Maybe there are other approaches to do so haven't mentioned in my post?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @divan,

In accordance with your requirements, you can get the sorted/filtered row from the **DataGridSource.effectiveRows**. Using this row, you can find the unsorted/unfiltered row index from the **DataGridSource.dataGridRows** (a local property maintained in the DataGridSource to obtain row values — and which can be used directly) and fetch the original record from the collection utilizing that index. I have attached a simple example. Please inspect the following sample and code snippet.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: SfDataGrid(
        source: _employeeDataSource,
        allowSorting: true,
        onCellTap: (details) {
          if (details.rowColumnIndex.rowIndex != 0) {
            int selectedRowIndex = details.rowColumnIndex.rowIndex - 1;
            var row =
                _employeeDataSource.effectiveRows.elementAt(selectedRowIndex);
            int originalRowIndex = _employeeDataSource.rows.indexOf(row);

            // Here you can get the original data from the source using the `originalRowIndex`
            // For example
            // var originalData = _originalData!.elementAt(originalRowIndex);
          }
        },
        columns: getColumns,
        columnWidthMode: ColumnWidthMode.fill,
      ),
    );
  }

```
[sample.zip](https://github.com/syncfusion/flutter-widgets/files/10793334/sample.zip)

Regards,
Tamilarasan
