### ISSUE TITLE
[syncfusion_flutter_calendar] onTap not firing on CalendarView.schedule

### ISSUE THREAD

**Issue by pauldemarco** [syncfusion/flutter-widgets#109]
Steps to reproduce:
Step 1.) Replace the build function in the example file:
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SfCalendar(
      view: CalendarView.schedule,
      dataSource: MeetingDataSource(_getDataSource()),
      // by default the month appointment display mode set as Indicator, we can
      // change the display mode as appointment using the appointment display
      // mode property
      monthViewSettings: MonthViewSettings(
          appointmentDisplayMode: MonthAppointmentDisplayMode.appointment),
      onTap: (t) => print(t),
    ));
  }
```
Step 2.) Notice that onTap does not fire when the view is set to Schedule.

**Comment by Indumathi1195R** [comment]
Hi,
 
We have included the mentioned issue fix for “**onTap callback not working in schedule view of the calendar**” in our latest Weekly NuGet package version 18.4.32. Kindly update the Flutter calendar package to this version for resolving this mentioned issue. Please find the latest version from the following link. 
 
**Link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance. 
 
Regards, 
Indumathi R

**Comment by pauldemarco** [comment]
This does resolve the onTap.
In the future, will their be the ability to include GestureDetector's within the appointmentBuilder? As of right now they don't seem to be firing.
