### ISSUE TITLE
I have table i want to create non equal size of row

### ISSUE THREAD

**Issue by parmeetmaster** [syncfusion/flutter-widgets#1090]
Please assist how to non equal size or rows data grid using this plugin

![image](https://user-images.githubusercontent.com/42370506/220335652-a6df66ec-ba59-4bbb-8931-ad1597131f00.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @parmeetmaster,

As of now, DataGrid doesn’t have support for merging row cells. We have already considered your request as a feature. We may implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience and understanding until then. You can follow up with the below feedback for further follow-up,

Feedback Link: https://www.syncfusion.com/feedback/23230/support-to-merge-the-rows-and-cells 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Elixell,

We are closing this ticket as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Ashok K
