### ISSUE TITLE
The Guage gets stuck when you hold for 500ms and try to slide. 

### ISSUE THREAD

**Issue by harishkthedeveloper** [syncfusion/flutter-widgets#1091]
1. there is a issue with the guage. if you try to slide slow and for small distance the guage is not working it gets stuck.
2. if you hold little more than 500 miliseconds aprox then the guage gets stuck.

please have a look into the video attached 

LINK - https://drive.google.com/file/d/1Ft-QVjN-OY9PdIstZftI_nqu2rR5LLoV/view?usp=sharing

is there any solution to this ?

**Comment by Yuvaraj-Gajaraj** [comment]
We have tested the radial gauge with the pointer and attempted to slide a marker after holding for 500ms, but we were unable to reproduce the reported issue at our end. We have shared a sample and screenshot for your reference. We kindly request you share more information about the complete code snippet for the radial gauge or try to reproduce the issue using the sample we provided. This will help us to better assist you.



Screenshot:
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/61863686/221523243-8beeefde-3a5e-40b2-abf5-b8ce1406ea7e.gif)

Sample: 
[i441656.zip](https://github.com/syncfusion/flutter-widgets/files/10838004/i441656.zip)
