### ISSUE TITLE
[syncfusion_flutter_PdfViewer] it is too slow to show page if images are encoded in jbig2.

### ISSUE THREAD

**Issue by pndaza** [syncfusion/flutter-widgets#1092]
It take almost 5 second to show  a single page

[jbig2_sample.pdf](https://github.com/syncfusion/flutter-widgets/files/10820998/jbig2_sample.pdf)

tested on windows, flutter 3.7

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by ramkumarsync** [comment]
We are closing this issue since we haven't heard back from you for a long time. Please feel free to contact us anytime if you need any further assistance.
