### ISSUE TITLE
[syncfusion_flutter_pdf ]Pdf file size on page removal remains the same with incrementalUpdate == false, and more than doubles when incrementalUpdate == true

### ISSUE THREAD

**Issue by crystalcleardesigns** [syncfusion/flutter-widgets#1093]
Tested on version: syncfusion_flutter_pdf  20.4.51

If I try and remove the last 3 pages of this 4 page pdf:

[sample.pdf](https://github.com/syncfusion/flutter-widgets/files/10821130/sfbb-diary-week.pdf)

Like so:

```
PdfDocument document = PdfDocument(inputBytes: pdf.buffer.asUint8List());
document.fileStructure.incrementalUpdate = false;
while(document.pages.count > 1) {
   document.pages.removeAt(1);
}
```

The size goes from 195kb to 519kb if incrementalUpdate set to false, and doesn't change at all if set to true (default).

Possibly related to https://github.com/syncfusion/flutter-widgets/issues/260 ?

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
