### ISSUE TITLE
Is there a maximum range feature for the RangeSlider?

### ISSUE THREAD

**Issue by desmeit** [syncfusion/flutter-widgets#1095]
I want to have a maximum range. For example it should not be possible to have a range greater than 2. Is that possible? Thanks

**Comment by Yuvaraj-Gajaraj** [comment]
The requirement can be achieved with the help of the [max](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/max.html) property in the [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html), this property is used to set the maximum range of RangeSlider. We have shared the code snippet and UG documentation below for your reference.

Code snippet:
```dart
SfRangeSlider(
  max: 50.0,
  // Other required properties
)
```

UG, https://help.syncfusion.com/flutter/slider/basic-features#maximum

**Comment by desmeit** [comment]
as I understand the max property is to define the maximum value of the whole slider.
But I want to have a minimum selected range of 1 hour:

```
SfRangeSlider(
              min: DateTime(2010, 01, 01, 9, 00, 00),
              max: DateTime(2010, 01, 01, 21, 05, 00),
              values: _values,
              interval: 3,
              dateIntervalType: DateIntervalType.hours,
              dateFormat: DateFormat('h:mm'),
              showTicks: true,
              showLabels: true,
              enableTooltip: true,
              minorTicksPerInterval: 1,
              //stepSize: 0.15,
              stepDuration: SliderStepDuration(minutes: 15),
...
```
![Simulator Screen Shot - iPhone 14 Pro - 2023-02-27 at 10 59 42](https://user-images.githubusercontent.com/9454529/221533369-5494a3e2-b0a4-4240-a8cc-0ac77428b10a.png)

**Comment by Yuvaraj-Gajaraj** [comment]
The requirement can be achieved with the help of the [stepDuration](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/stepDuration.html) and [dragMode](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/dragMode.html) properties in the range slider. We have set the [stepDuration](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/stepDuration.html) value to 1 hour and the [dragMode](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/dragMode.html) as between ticks, now the range will be a minimum of 1 hour. We have shared the sample and code snippet below for your reference.

Code snippet:
```dart
SfRangeSlider(
  dragMode: SliderDragMode.betweenThumbs,
  stepDuration: SliderStepDuration(hours: 1),
)
```

Sample: 
[i442086.zip](https://github.com/syncfusion/flutter-widgets/files/10861943/i442086.zip)
