### ISSUE TITLE
[syncfusion_flutter_calendar] support appointment customisation for month view

### ISSUE THREAD

**Issue by AAverin** [syncfusion/flutter-widgets#1098]
It would be great to customise how appointment looks in the month view. At the moment only dot indicator or line indicator are supported, even if custom `appointmentBuidler` is provided. That builder only applies when agenda is displayed for the day of the month.

**Comment by MuniappanSubramanian** [comment]
@AAverin 

In the Flutter Calendar, you can customize the appearance of appointments in various views including Day, Week, Workweek, Month, Schedule, and Timeline views using “**appointmentBuilder**“support.  The appointments displayed within month cells are based on the size of the cell. 

Note:
In the Month view, the appointment builder is applicable only for the displayed appointments in the month cells and agenda views. This is only possible when the **AppointmentDisplayMode** is set to **appointment**.

Refer to the following documentation to learn more about the appointment builder support in the calendar:
https://help.syncfusion.com/flutter/calendar/builders#appointment-builder 

To customize the number of appointments displayed in the month cell, you can use the appointmentDisplayCount property of MonthViewSettings in SfCalendar. Refer to the link below for more details:
https://help.syncfusion.com/flutter/calendar/month-view#appointment-display-count 

Additionally, you can customize the month cells in the Month View of the Flutter Calendar by using the “MonthCellBuilder” support. Refer to our UG documentation for more details about the month's cell builder support in the calendar:
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder 

To further assist you, you can explore the Flutter Calendar SampleBrowser demos and sample from the link below:
https://flutter.syncfusion.com/#/event-calendar/getting-started

**Comment by AAverin** [comment]
I have worked around by using `monthCellBuilder` and removing default appointment display, instead using cellDetail.appointments to build a custom UI

**Comment by Sumit258000** [comment]
There must be a way to customize appointment looks in the month view.Something like changing background color.
