### ISSUE TITLE
[SfCartesianChart] Area between the two lines is poorly painted

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-widgets#110]
Hello!
My idea is to represent two lines, one blue and one green. When the values ​​of the green line are greater than the values ​​of the blue line, the painted area is green, and when the values ​​of the blue line are greater than the values ​​of the green line, then the painted area is blue.
```dart
series: [
            SplineSeries(
                dataSource: values,
                xValueMapper: (AccumulatedValue data, _) => data.month,
                yValueMapper: (AccumulatedValue data, _) => data.sale,
                color: Theme.of(context).hintColor,
                width: 2,
                markerSettings:
                    MarkerSettings(isVisible: true, width: 0, height: 0)),
            SplineSeries(
                dataSource: values,
                xValueMapper: (AccumulatedValue data, _) => data.month,
                yValueMapper: (AccumulatedValue data, _) => data.expense,
                color: Theme.of(context).hoverColor,
                width: 2,
                markerSettings:
                    MarkerSettings(isVisible: true, width: 0, height: 0)),
            SplineRangeAreaSeries(
              dataSource: values,
              xValueMapper: (AccumulatedValue value, _) => value.month,
              highValueMapper: (AccumulatedValue value, _) =>
                  value.isPositive ? value.sale : null,
              lowValueMapper: (AccumulatedValue value, _) =>
                  value.isPositive ? value.expense : null,
              color: Theme.of(context).hintColor.withOpacity(0.60),
            ),
            SplineRangeAreaSeries(
                dataSource: values,
                xValueMapper: (AccumulatedValue value, _) => value.month,
                highValueMapper: (AccumulatedValue value, _) =>
                    !value.isPositive ? value.expense : null,
                lowValueMapper: (AccumulatedValue value, _) =>
                    !value.isPositive ? value.sale : null,
                color: Theme.of(context).hoverColor.withOpacity(0.60))
          ]
```

And with this code I managed to get to the result, the problem is that the area often appears poorly painted as you can see in the image:
![image](https://user-images.githubusercontent.com/33434500/103911066-7d0ec500-50fd-11eb-9f2e-0bf99829ad48.png)

**Can someone help me put the area well painted? Or if they find another solution simpler than mine to make this effect, I would be grateful.**

Thank you very much,
Luís Campos

**Comment by Dharanipalani** [comment]
Hi LuisCampos97,

Greetings from Syncfusion. We have analyzed your scenario and we are not clear on your exact requirement with the provided screenshot.
 
![image](https://user-images.githubusercontent.com/19763272/104007011-486a3e80-51cd-11eb-9017-dbb6d35c9eaa.png)
 
We suspect that you are expecting that the red color marked area to be filled with blue and green respectively? If so, please share the data which you have used to render the chart. This will help to analyze further on your scenario and we will provide you the solution sooner. We have also added the sample for your reference, kindly replicate with this and revert back to us.

Sample: [https://www.syncfusion.com/downloads/support/directtrac/general/ze/Spline_range_area-1181117684](url)

Thanks,
Dharanitharan.P

**Comment by LuisCampos97** [comment]
Hi @Dharanipalani ,
That's exactly what you said I want to do.

I can't download the sample from that link, it redirects to the git hub :(

**Comment by LuisCampos97** [comment]
But I'm using this data:
```dart
class Value {
  int month;
  double sale;
  double expense;
  bool isPositive;

  Value(
      {this.month, this.sale, this.expense, this.isPositive});
}

[
List<Value> values = [
  Value(1, 13998.19, 16237.23, false),
  Value(2, 32300.54, 57095.67, false),
  Value(3, 49083.6, 58514.6, false),
  Value(4, 88565.39, 153499.51, false),
  Value(5, 113867.88, 155337.22, false),
  Value(6, 142123.49, 156149.34, false),
  Value(7, 142233.49, 166991.02, false),
  Value(8, 190615.31, 175611.76, true),
  Value(9, 199215.47, 194340.29, true),
  Value(10, 199215.47, 205538.37, false),
  Value(11, 199454.77, 212906.53, false),
  Value(12, 199454.77, 225542.32, false)
]

**Comment by LuisCampos97** [comment]
Hi!
I added my code to sample.zip. Thanks.

[sample.zip](https://github.com/syncfusion/flutter-widgets/files/5801439/sample.zip)

**Comment by LuisCampos97** [comment]
@Dharanipalani Any conclusions that can help me?

**Comment by dharanidharandharmasivam** [comment]
Hi @LuisCampos97 ,

Thanks for the information you have shared. We have analyzed with the provided code and we would like to let you know that, this is our default behaviour. To achieve this, you have used the spline and spline range area series. The reported scenario is due to the difference in the control points calculated for spline type series. We have ensured with some other competitors like highcharts, our Essential Javascript charts(EJ2), Xamarin charts, but the same behaviour exists in all. So, as of now, this is not achievable. However, we are trying to achieve the same at our end and we are unable to provide a definite timeline on this since this is the default behaviour and we regret the inconvenience.

Thanks,
Dharani.

**Comment by LuisCampos97** [comment]
Hi @dharanidharandharmasivam,
Can you not help me to achieve the same result but through another approach? Maybe using other charts, I don't know

**Comment by dharanidharandharmasivam** [comment]
Hi @LuisCampos97 ,

Thanks for being patience. We have analyzed further in achieving your requirement with all other possible approaches, unfortunately we are unable to achieve the exact scenario. Due to the difference in control point calculation between the points as stated earlier. We regret for the inconvenience.

Thanks,
Dharani.
