### ISSUE TITLE
[syncfusion_flutter_calendar] appointments get missing switching month in the calendar 

### ISSUE THREAD

**Issue by AAverin** [syncfusion/flutter-widgets#1100]
Platform: MacOS

Having DataSource set and `monthCellBuilder` configured I am checking for `MonthCellDetails.appointments` to decide how I want to display it on the screen. `showNavigationArrow` is set to true.

When changing a month in the Calendar navigation, `monthCellBuilder` gets called again, but appointments are empty, even though the previous call data was there. Switching 2 months behind and then 2 months ahead again I can see the appointments.

**Comment by AAverin** [comment]
The bug only seems to happen if navigating by clicking on arrows.
Navigation by swiping the calendar works correctly and appointments are present on cellDetails

**Comment by Indumathi1195R** [comment]
AAverin,

As per the shared information, we have checked the issue "**Appointments missing while switching month view with cell builder in the Flutter Calendar**" from our side with the attached sample, it was working fine. Please find the sample and video from the following link.


**Sample link:**
[monthcell_appointment.zip](https://github.com/syncfusion/flutter-widgets/files/11271310/monthcell_appointment.zip)

 
**Video link:**
[Video.zip](https://github.com/syncfusion/flutter-widgets/files/11271311/Video.zip)


Please check the sample and let us know still if you are facing same issue? If not, please modify the sample based on your scenario and revert us with more details, it will be helpful for us to analyze further.

**Comment by AAverin** [comment]
@Indumathi1195R I the video, you switch >2 pages forward and >2 pages backwards.
The bug doesn't reproduce if you switch >2 pages from the content.
Try switching one page forward and return back to the page with the content to see the bug.

Here is a video from my product. Notice that by default, green crosses are displayed, but if I use the button to switch pages, only red crosses are visible.

[Kapture 2023-05-01 at 13.59.20.webm](https://user-images.githubusercontent.com/1481332/235448877-dc33fda2-eab6-4a3d-8e25-82bb83c73dca.webm)
