### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Is it possible to know when the current PDF page was rendered?

### ISSUE THREAD

**Issue by plauzul** [syncfusion/flutter-widgets#1102]
Currently there is the ondocumentLoaded, but when it is called the page has not yet been rendered, it is still on the screen the CircularProgressIndicator Widget.

It would be interesting to have one more listener to be called when this widget is exchanged for the PDF, or is there any way to do that?

**Comment by deepika134** [comment]
Hi @plauzul , Can we trigger the onDocumentLoaded callback after SfPdfViewer disables the circular progress bar indicator? Please let us know if the above meets your requirement so that we can check further.

**Comment by plauzul** [comment]
Hi @deepika134.

No problem calling onDocumentLoaded after removing the CircularProgressIndicator from the screen.

Probably the right time would be after the completion of FutureBuilder https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_pdfviewer/lib/src/pdfviewer.dart#L1974

**Comment by ramkumarsync** [comment]
The issue "The onDocumentLoaded callback is executed before the PDF document loads in the SfPdfViewer" has been resolved and the fix is available in the weekly (v21.2.4) release. Please find the link below,

https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/21.2.4
