### ISSUE TITLE
[syncfusion_flutter_pdfviewer][web] How to fit page to available width?

### ISSUE THREAD

**Issue by jriegraf** [syncfusion/flutter-widgets#1107]
When I load a PDF document, it is zoomed so that the whole page can be seen. As a result, the free space on the left and right of the document shows gray bars.

How can I fit the page to the width of the widget? Is there a 'fit' parameter which takes an argument of type BoxFit, like in an image widget? That would be great.

Thanks, Julian

**Comment by deepika134** [comment]
Hi @jriegraf , At present, we do not have support to load the document with "Fit width" in SfPdfViewer on the web and windows platforms. We have considered this requirement and will implement it to load the document with a fit width as a default in the web and windows platforms. This support will be included in the Volume 1 SP release, which is expected to be rolled out at the end of April 2023.

**Comment by jriegraf** [comment]
Hi @deepika134, thanks for your reply. Sounds great. I am looking forward to this release.

**Comment by deepika134** [comment]
The support to load the document with "Fit width" in SfPdfViewer will be included in the Volume 2 main release, which is expected to be rolled out at the end of June 2023. Kindly use the following link for track the status of the feature,

https://www.syncfusion.com/feedback/42911/windows-web-support-to-load-the-pages-with-the-width-fitted

**Comment by deepika134** [comment]
Hi @jriegraf ,

We are glad to announce that the support to load the pages with the width fitted in Windows and Web platforms has been included in our Essential Studio 2023 Volume 2 release v22.1.34 and it is available for download under the following link.

[Essential Studio 2023 Volume 2 Main Release v22.1.34 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/183035/essential-studio-2023-volume-2-main-release-v22-1-34-is-available-for-download)

https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/22.1.34

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,          
Deepika R

**Comment by JayronKhong** [comment]
Hi can make this as property? so that user can select the desired fit option.

**Comment by immankumarsync** [comment]
@JayronKhong, In SfPdfViewer, the PDF document is loaded with the fitted width on the Windows and web platforms. This is the default behavior of SfPdfViewer. Currently, there is no API available to override this behavior. Kindly share your complete requirements and use case. This will be helpful for us to proceed further.

**Comment by JayronKhong** [comment]
> @JayronKhong, In SfPdfViewer, the PDF document is loaded with the fitted width on the Windows and web platforms. This is the default behavior of SfPdfViewer. Currently, there is no API available to override this behavior. Kindly share your complete requirements and use case. This will be helpful for us to proceed further.

Hi @immankumarsync ,  I simply desire the ability to opt for a choice that doesn't automatically adjust to the width on both Windows and web platforms.

This is my desired outcome during pagelayout.continuous:
<img width="1440" alt="Screenshot 2023-12-13 at 11 06 23 AM" src="https://github.com/syncfusion/flutter-widgets/assets/50298326/11f96098-e8d4-481a-a432-9fa0d201bb17">
