### ISSUE TITLE
sfslider failed assertion

### ISSUE THREAD

**Issue by jeongwoobin** [syncfusion/flutter-widgets#1108]
i want list of slider but i can't
i set slider's height 50 but it's not applied and overflow parent's view

```
@override
  Widget build(BuildContext context) {
    return SfSliderTheme(
        data: SfSliderThemeData(
            thumbRadius: 8.0,
            thumbColor: const Color(0xFF4A515F),
            activeTrackHeight: 2.0,
            inactiveTrackHeight: 2.0,
            activeTrackColor: SortColor.lineSecond,
            inactiveTrackColor: SortColor.lineSecond,
            // tickSize: const Size(0, 0),
            overlayRadius: 0,
            activeLabelStyle:
                SortKorStyle.b1.copyWith(color: SortColor.text_800),
            inactiveLabelStyle:
                SortKorStyle.b1.copyWith(color: SortColor.text_800)),
        child: SizedBox(
          height: 50,
          child: SfSlider(
            min: min,
            max: max,
            value: value,
            interval: 1.0,
            stepSize: 1.0,
            showLabels: true,
            onChanged: (newValue) {
              updateValue(newValue);
            },
          ),
        ));
  }
```

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/45030068/222385997-6fed35e5-cd23-44cb-8b3b-bcc9d6216501.png">

**Comment by natrayansf** [comment]
You can overcome this issue by setting color and **fontSize** when setting the text style for the active and inactive labels in [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html). 

```
SfTheme( 
   data: SfThemeData(
     sliderThemeData: SfSliderThemeData(
         activeLabelStyle: const TextStyle(color: Colors.red, fontSize: 14),
         inactiveLabelStyle: const TextStyle(color: Colors.red, fontSize: 14),
     )
   ),
)
```
If you like to set the color alone for the label, then you can use the [textTheme](https://api.flutter.dev/flutter/material/TextTheme-class.html)’s text style values retrieved from context’s [ThemeData](https://api.flutter.dev/flutter/material/ThemeData-class.html) and using the [copyWith](https://api.flutter.dev/flutter/painting/TextStyle/copyWith.html)() method to set the desired color. 
```
final ThemeData themeData = Theme.of(context);

SfTheme(
    data: SfThemeData(
         sliderThemeData: SfSliderThemeData(
            activeLabelStyle: themeData.textTheme.bodyLarge!.copyWith(color: Colors.red),
            inactiveLabelStyle: themeData.textTheme.bodyLarge!.copyWith(color: Colors.red),
         )
    ),
)
```

**Comment by jeongwoobin** [comment]
i think it is not a problem.. :(
and I put the matter off until later.
thx

**Comment by jeongwoobin** [comment]
I solved with 

listView.builder(
  shrinkWrap: true,  // this is work!
  itemBuilder: (context, index) {
    sfSlider...
  }
)
