### ISSUE TITLE
Line chart error when no data because using CrosshairBehavior

### ISSUE THREAD

**Issue by Halim-Elmenshawi** [syncfusion/flutter-widgets#1109]
When there is no data in the line chart and the plot area is touched, the debug stops and routes me to chart_base.dart file to the line 3753 `SeriesHelper.getSeriesRendererDetails(_findSeries(_touchPosition!)!)` without giving me any message. 
```
 // ignore: unnecessary_null_comparison
    if ((chart.crosshairBehavior != null &&
            chart.crosshairBehavior.enable == true &&
            chart.crosshairBehavior.activationMode ==
                ActivationMode.longPress) &&
        SeriesHelper.getSeriesRendererDetails(_findSeries(position!)!).series
            is! ErrorBarSeries &&
        !chart.zoomPanBehavior.enableSelectionZooming &&
        zoomingBehaviorDetails.isPinching != true &&
        // ignore: unnecessary_null_comparison
        position != null) {
      CrosshairHelper.getRenderingDetails(
              _stateProperties.crosshairBehaviorRenderer)
          .isLongPressActivated = true;
      _stateProperties.crosshairBehaviorRenderer
          .onTouchDown(position.dx, position.dy);
    }
  }
```
Additionally, when I start the program without debugging, I get the following message in the debug console:
════════ Exception caught by gesture ═══════════════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
that's due to CrosshairBehavior
`My code`
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

class LineChartWidget extends StatefulWidget {
  const LineChartWidget({
    Key? key,
  }) : super(key: key);

  @override
  State<LineChartWidget> createState() => _LineChartWidgetState();
}

class _LineChartWidgetState extends State<LineChartWidget> {
  CrosshairBehavior? _crosshairBehavior;

  @override
  void initState() {
    _crosshairBehavior = CrosshairBehavior(enable: true, hideDelay: 5000.0);
    super.initState();
  }

  List<LineSeries> lines = [];
  List<ChartAxis> yAxes = [];
  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      legend: Legend(
        isVisible: true,
        position: LegendPosition.top,
      ),
      enableMultiSelection: true,
      crosshairBehavior: _crosshairBehavior,
      primaryYAxis: NumericAxis(isVisible: false),
      primaryXAxis: DateTimeAxis(),
      series: lines,
      axes: yAxes,
    );
  }
}
```

**Comment by LokeshPalani** [comment]
We can replicate the reported issue regarding Exception is thrown when trying to show the crosshair with an empty data source in series at our end and have logged bug report for it in our feedback portal. We will fix it and include the changes in our weekly patch release which is expected to be rolled out by July 11,2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.



Feedback link:

https://www.syncfusion.com/feedback/44755/exception-is-thrown-when-trying-to-show-the-crosshair-with-an-empty-data-source-in

**Comment by LokeshPalani** [comment]
We can replicate the reported issue regarding Exception is thrown when trying to show the crosshair with an empty data source in series at our end and have logged bug report for it in our feedback portal. We will fix it and include the changes in our weekly patch release which is expected to be rolled out by July 11,2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.



Feedback link:

https://www.syncfusion.com/feedback/44755/exception-is-thrown-when-trying-to-show-the-crosshair-with-an-empty-data-source-in

**Comment by LokeshPalani** [comment]
Hi,

Sorry for the inconvenience, we missed to notify the weekly release details here. The reported issue regarding the 'Exception is thrown when trying to show the crosshair with an empty data source in series' has been fixed already and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version link,
https://pub.dev/packages/syncfusion_flutter_charts/versions/23.2.7 

Regards,
Lokesh P.
