### ISSUE TITLE
how to make mixed bold and normal font in one paragraph (pdf)?

### ISSUE THREAD

**Issue by tas-unn** [syncfusion/flutter-widgets#1114]
how to make mixed bold and normal font in one paragraph (pdf)?
Like:
"Hello, my name is **John**. I'm **18** years old. I am living in **America**". 

The number of characters in the text can be different, so it is very problematic to calculate the point each time (for example, you can easily go beyond the page)

**Comment by irfanajaffer** [comment]
We do not have direct support for this requirement. However, as a workaround, we can provide a sample by drawing text with different fonts.

Please refer to the code snippet and output attached below:

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/txt/createmultiplefont-322883325
Output: https://www.syncfusion.com/downloads/support/directtrac/general/pd/output1485864334

We have already KB documentation related to this in our Syncfusion PDF library:

https://www.syncfusion.com/faq/windowsforms/fonts/how-can-i-draw-a-single-line-of-text-with-different-fonts-using-drawstring

Please try this on your end and let us know the result

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
