### ISSUE TITLE
[syncfusion_flutter_charts] intl version error

### ISSUE THREAD

**Issue by LuisCampos97** [syncfusion/flutter-widgets#112]
Hi!
Flutter 1.22.5 • channel stable

This error happens when I do flutter pub get. I have the intl version: ^ 0.16.1 and syncfusion_flutter_charts:

Running "flutter pub get" in fact-mobile-app...                 
Because my_app depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.
So, because my_app depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because my_app depends on intl ^0.16.1, version solving failed.)

Can you help me please?
Thank you!

**Comment by Dharanipalani** [comment]
Hi @LuisCampos97, 
   
We have analyzed your scenario and we would like to suggest using dependency_overrides in pubspec.yaml file resolves the reported scenario. Find the code below to accomplish this,

`dependency_overrides:   
    intl: ^0.17.0-nullsafety.2 `

Thanks,
Dharanitharan. P
