### ISSUE TITLE
PDF Viewer page reloading again and again

### ISSUE THREAD

**Issue by raaja-guidely** [syncfusion/flutter-widgets#1123]
PDF Viewer: after opening PDF scrolled down each page loading , coming up then also all pages are reloading again,

**Comment by deepika134** [comment]
Hi @raaja-guidely , We loaded the PDF pages in our Flutter PDF Viewer only based on the virtualization, which means that initially 3 pages will be rendered, and on-demand scrolling will render the rest of the pages [i.e., we load the next and previous pages with the current page based on the current page number in the viewport]. If we load all of the pages at once, the loading time and memory consumption will increase depending on the size of the document, so we avoided that behaviour.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by raaja-guidely** [comment]
@deepika134 yes we agree, it will take time if we load full pdf but in our case previously loaded pages are again loading while we scroll top. let me know the solutions for this how to cache the already loaded pages. its very much need for the students.

The problem is, the PDF pages are already loaded by internet, but after visit same page its not taking any internet, only visibility time is taking too much. pls give us solution for this, we should not allow already loaded pages again to load, its annoying..

**Comment by raaja-guidely** [comment]
@deepika134 waiting for the reply. we need document load at once. All our document size is less than 1 mb but if we are loading 3 3 pages its annoying. we need a option load document at once. reply as soon as possible

**Comment by ramkumarsync** [comment]
We do have support to render all the pages at once and do not have any plans to implement the same.
