### ISSUE TITLE
syncfusion_flutter_xlsio support pure dart

### ISSUE THREAD

**Issue by Viper-Bit** [syncfusion/flutter-widgets#1125]
hi,
do u have any plan to make syncfusion_flutter_xlsio package compatible with dart (just dart not flutter framework). its very handy for making exports in servers.
right now syncfusion_flutter_xlsio uses dart:ui that is not available in dart

**Comment by Kurmitha4004** [comment]
Unfortunately, we don't have support for your requirement. And, we don’t have any plans to implement this support.
