### ISSUE TITLE
How can i get touch position

### ISSUE THREAD

**Issue by CengizhanAsCsi** [syncfusion/flutter-widgets#1126]
I wonder ,How can I get the exact location of that place when I click somewhere in the pdf file

**Comment by deepika134** [comment]
Hi @CengizhanAsCsi , We have prepared a workaround to retrieve the tapped coordinates when the user taps the SfPdfViewer, which can be downloaded from the attachment. Please find the workflow for this example application below,

We have used the **TapGestureRecoginzer** to catch the tap action and onTapDown callback we have called **_getPdfCoordinates()** and **_addTextToPdfCoordinates()** methods.

**_getPdfCoordinates()** method has the logic to return the tapped location coordinates relative to the PDF page.

**_addTextToPdfCoordinates()** method has the logic to add a text to the tapped location.

[tapped_position.zip](https://github.com/syncfusion/flutter-widgets/files/10997824/tapped_position.zip)
