### ISSUE TITLE
support for independent stroke color 

### ISSUE THREAD

**Issue by nadas00** [syncfusion/flutter-widgets#1128]
<img width="364" alt="Ekran Resmi 2023-03-14 18 14 45" src="https://user-images.githubusercontent.com/46631211/225047303-18911f3d-e5aa-4ec7-a7a1-6f9bc70d2166.png">
should have independent stroke color like that but we can only give one stroke color for all.
Like that. Only black. :/ 
<img width="269" alt="Ekran Resmi 2023-03-14 18 15 21" src="https://user-images.githubusercontent.com/46631211/225047487-69b8e322-a772-4425-83aa-2bee60b0d4a1.png">

**Comment by Yuvaraj-Gajaraj** [comment]
We tried to provide a feasible workaround to achieve your requirement. But currently, we don't have support for customizing the border color for individual segments. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.



We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.



Feedback, https://www.syncfusion.com/feedback/42143
