### ISSUE TITLE
DataGrid / Paging / allowFiltering / cant's filter across all pages

### ISSUE THREAD

**Issue by gortecsol** [syncfusion/flutter-widgets#1130]
Hello, 

1. Sorting works as here https://help.syncfusion.com/flutter/datagrid/paging#sort-all-the-rows-instead-of-rows-available-in-a-page
2. But filtering doesn't

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @gortecsol,

We believe that you have not overridden the handlePageChange method in the DataGridSource class at the sample level to perform whole row sorting, in the same way, you can filter whole rows of the DataGrid. We have checked the reported issue on our end, and it is working properly. We have attached the sample that we have checked on our end. Please review the following sample and output reference video.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-2058441148 


https://user-images.githubusercontent.com/93904422/225640505-2b30642e-5c4d-44bd-9e99-2be615852694.mp4



Regards,
Tamilarasan
