### ISSUE TITLE
not show digital signature in pdfview

### ISSUE THREAD

**Issue by hung-hust-97** [syncfusion/flutter-widgets#1132]
[CIST_BNT_signed_khong_doc_duoc.pdf](https://github.com/syncfusion/flutter-widgets/files/10992579/CIST_BNT_signed_khong_doc_duoc.pdf)
When I use lib, most pdf not show the digital signature. Example above

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by deepika134** [comment]
Hi @hung-hust-97 , At present we do not have support for adding or modifying "Digital Signature" in PDF documents. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked through the following link,

https://www.syncfusion.com/feedback/26234/support-for-digital-signature

However, we have a workaround for preserve the existing signature in SfPdfViewer. Kindly check the below KB link for preserve the existing annotation in Flutter PdfViewer,

https://www.syncfusion.com/kb/13014/how-to-preserve-the-existing-annotation-in-flutter-pdf-viewer-sfpdfviewer

**Comment by ramkumarsync** [comment]
Currently, the SfPdfViewer will just render the existing Digital signatures in the PDF document. However, they cannot be edited. We believe this meets your requirements.
