### ISSUE TITLE
pdfviewer example can run in Windows and Web, but does not render content.

### ISSUE THREAD

**Issue by Leadrive** [syncfusion/flutter-widgets#114]
not report any error.
thanks.

**Comment by dillibabun** [comment]
Hi @Leadrive 

Greetings from Syncfusion.

We are unable to reproduce the reported error with the given information. Kindly share us the issue reproducing procedure with complete error log and flutter doctor output(to known your flutter version) which will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

>

 
Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @Leadrive 

Greetings from Syncfusion.

We regret to let you know that SfPdfViewer widget is supported only in Android and iOS. We are yet to provide support in other platforms. Kindly tell us know the platforms in which you need SfPdfViewer widget.

Regards,
Dilli babu.
