### ISSUE TITLE
SfRangeSliderTheme not found

### ISSUE THREAD

**Issue by AdrianaBucurel** [syncfusion/flutter-widgets#1140]
Hello! Android Studio with Flutter version 3.7.7 doesn't recognize SfRangeSliderTheme or other Themes. I have the last version installed for library ( syncfusion_flutter_sliders: ^20.4.54)

**Comment by AdrianaBucurel** [comment]
![image](https://user-images.githubusercontent.com/42340333/226830200-ce4d69ef-89a8-45b4-b367-187085331b5f.png)

**Comment by AdrianaBucurel** [comment]
![image](https://user-images.githubusercontent.com/42340333/226830655-6fe8f483-d847-45db-a07b-b214b9c3a87f.png)

**Comment by Yuvaraj-Gajaraj** [comment]
It seems that you haven’t imported a theme package from syncfusion_flutter_core in your project. To resolve this issue, we recommend importing the following package into your project.

Code snippet:
```dart
import 'package:syncfusion_flutter_core/theme.dart';
```

Regards,
Yuvaraj.
