### ISSUE TITLE
can not pub get version 21.1.35

### ISSUE THREAD

**Issue by wengxianxun** [syncfusion/flutter-widgets#1145]
Because flutter_examples depends on syncfusion_flutter_treemap ^21.1.35 which doesn't match any versions, version solving failed.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/831898/227813852-e387eabf-27dc-4510-9609-b2ec6d1f8300.png">

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked the [flutter_examples](https://github.com/syncfusion/flutter-examples) repository and tried to pub get at our end it is working fine and no issue getting reproduced at our end. We suspect that it's a cache issue and we suggest you clean the cache using flutter clean, flutter pub cache clean commands once and try to flutter pub get again, it will help you to resolve the issue.

**Comment by fernandooliiveira** [comment]
Same problem here!

![image](https://user-images.githubusercontent.com/66748755/228221067-396f213b-ce51-4e37-8fcf-0434fe52e11d.png)

To solve use older version for now, like *syncfusion_flutter_datepicker: ^20.0.0*

**Comment by LavanyaGowtham2021** [comment]
Reopen this ticket if still facing issue with the latest version
