### ISSUE TITLE
ChartSeriesController doesn't update plot bands

### ISSUE THREAD

**Issue by Paddington12345** [syncfusion/flutter-widgets#1147]
I use chartSeriesController  to avoid rebuilding chart whenever real time data changes. It works fast, but I do have some other features in the chart (such as plot Bands) that are dependent on real time data. The issue is they don't get updated as well. Controller works great for data points, but not for plot bands. How can I update plot bands  as well (without calling setState)?

I've also notice some different behaviour for autoscaling when using controller instead of setState. The intervals seem to be less dense. Is this the expected behavior?

**Comment by Yuvaraj-Gajaraj** [comment]
We can able to replicate the reported issue regarding the plotBand not updating while updating the data using the updtateDataSource method at our end and have logged a bug report for it in our feedback portal. We will fix this by updating while the updateDataSource method call and without calling setState and include the changes in our weekly patch release which is expected to be rolled out in the second week of April. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.



Feedback, https://www.syncfusion.com/feedback/42529/
