### ISSUE TITLE
Autoscaling not working for similar negative values 

### ISSUE THREAD

**Issue by Paddington12345** [syncfusion/flutter-widgets#1150]
I use fastLineSeries for real time data without setting interval/min/max on the primary Y-axis. It all works fine, but I've noticed that the autoscaling stops working as expected if I have only negative similar values (for example, -201.95, -201.82, - 200.44, etc). The intervals get dense and the performance is 100x worse. 

It is similar to the last answer here - https://github.com/syncfusion/flutter-widgets/issues/227. Is this bug still present?

**Comment by Yuvaraj-Gajaraj** [comment]
You can achieve your requirement with the help of the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) property in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) it will help you to eliminate the unwanted range in the axis and calculate the range based on the visible point. We have shared the related UG documentation below for your reference.



UG, https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range

**Comment by Paddington12345** [comment]
It does help to set rangePadding as 'additional' or 'round' with these negative values, but I'd prefer to have the default ('normal' or 'auto') rangePaddings. Normal or auto aren't working - there are 30+ of intervals on Y axis + chart starts to lag. Is there are a reason for this? 

As long as the values are not close-by and negative, all rangePaddings work.

**Comment by Yuvaraj-Gajaraj** [comment]
We are able to replicate the reported issue regarding autoscaling not working when having a negative range in the numeric axis when range padding is set to normal or auto at our end and have logged a bug report for it in our feedback portal. We will fix and include the changes in our SP release which is expected to be rolled out in the first week of May. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.



Feedback, https://www.syncfusion.com/feedback/42814

**Comment by LokeshPalani** [comment]
We have resolved the reported issue. However, due to an automation disruption, we were unable to incorporate this fix into our weekly patch release on May 9, 2023. We plan to include this fix in our forthcoming weekly patch release, which is anticipated to be deployed on May 16, 2023. We will inform you once the release has been implemented, and we appreciate your patience in the meantime.

**Comment by LokeshPalani** [comment]
The reported issue regarding **Autoscaling not working for negative intervals in numeric axis when the range padding is normal and auto** has been fixed and rolled out in our SP release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.



Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/21.2.5
