### ISSUE TITLE
Need customize FilterPopupMenu buttons

### ISSUE THREAD

**Issue by wxpcl123** [syncfusion/flutter-widgets#1151]
When I use syncfusion_flutter_datagrid: ^21.1.37 to popup a FilterPopupMenu,  the button("OK" & "Cancel") has urgly backgroundColor and Text Color. see below.
![button_not_clear](https://user-images.githubusercontent.com/34614907/229333586-34489b94-407f-4f98-85cc-93071a0aedcb.png)

I tried to find the way to solve the problem, even use new bing. The new bing give me a feedback that I can use filterPopupButtonStyle in SfDataGridThemeData to change it. But in fact the property cannot be found in it.

Finally I find that when I change the useMaterial3 from true to false in MaterialApp class, the buttons become normal.
`  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: false),
    );
  }`
pic below:
![button_clear](https://user-images.githubusercontent.com/34614907/229333867-1417fe64-940e-4a35-8ffc-199906dbefc5.png)

I hope you can fix the bug, or hope you will give me filterPopupButtonStyle.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @wxpcl123,

We have checked your query at our end, and we are able to replicate the reported issue when using the Material 3 design at our end. We have considered this as a bug and logged a bug in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release which is expected to be rolled out on April 18, 2023. We will update you once the release is rolled out and we appreciate your patience until then. 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
@wxpcl123,

We are glad to inform you that the fix has been included in our weekly pub release for the mentioned issue. Please update the DataGrid package to version **21.1.41.**

https://pub.dev/packages/syncfusion_flutter_datagrid/changelog 

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you require any further assistance.

**Comment by wxpcl123** [comment]
Thanks a lot, it works now in 21.1.41.
