### ISSUE TITLE
[syncfusion_flutter_calendar] Feature request : Calendar view - Half hour slot

### ISSUE THREAD

**Issue by QuentinSc** [syncfusion/flutter-widgets#1152]
Hello,

Could be great to be able to select half hour slot and not only full hour

Thank you

**Comment by MuniappanSubramanian** [comment]
The current implementation of the Flutter Calendar does not have support for selecting half-hour time slots in the timeslot views.  

But You can customize the interval of timeslots (30 minutes) in all the timeslots views by using the timeInterval property of TimeSlotViewSettings in the calendar. Refer to our UG documentation to know more details about time interval customization support in the calendar, 

https://help.syncfusion.com/flutter/calendar/timeslot-views#change-time-interval

**Comment by QuentinSc** [comment]
Yes, thank you. Half-hour selection could be add to the roadmap ?

**Comment by IndumathiR-1995** [comment]
Hi,

If possible can you please share the more details or below details to us. It would be helpful for us to analyze and provide you a solution at the earliest.

- Use case scenario for half-hour selection
- Pictorial representation of your requirement

Regards,
Indumathi R
