### ISSUE TITLE
[SfDatagrid] GridColumn.sortIconPosition doesn't exist

### ISSUE THREAD

**Issue by Methamorphe** [syncfusion/flutter-widgets#1153]
Hello,

I'm trying to align the sort icon to the left, following the docs I found that I should be using the GridColumn.sortIconPosition prop,
but it doesn't exist in the GridColumn class.
![image](https://user-images.githubusercontent.com/40505181/229476176-916f5f79-2a95-4e2d-89ae-731a666d2ed1.png)

What should I use instead ?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Methamorphe,

**It appears that you may be using an older version of DataGrid. We want to inform you that the feature you are referring to was implemented in the 2023 volume 1 [release](https://pub.dev/packages/syncfusion_flutter_datagrid/changelog)**. To make sure that you can use this feature, we recommend that you update to the latest version of DataGrid. We have tested the feature with the latest version of DataGrid (**21.1.37**) and can confirm that it is working as expected. For your convenience, we have attached a sample that demonstrates how the feature works with the latest version of DataGrid.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: SfDataGrid(
        source: employeeDataSource,
        allowSorting: true,
        columnWidthMode: ColumnWidthMode.fill,
        columns: <GridColumn>[
          GridColumn(
              columnName: 'id',
              sortIconPosition: ColumnHeaderIconPosition.start,
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text(
                    'ID',
                  ))),
          GridColumn(
              columnName: 'name',
              sortIconPosition: ColumnHeaderIconPosition.start,
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text('Name'))),
          GridColumn(
              columnName: 'designation',
              sortIconPosition: ColumnHeaderIconPosition.start,
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text(
                    'Designation',
                    overflow: TextOverflow.ellipsis,
                  ))),
          GridColumn(
              columnName: 'salary',
              sortIconPosition: ColumnHeaderIconPosition.start,
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text('Salary'))),
        ],
      ),
    );
  }

```

**[sample.zip](https://github.com/syncfusion/flutter-widgets/files/11145551/sample.zip)**


Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Methamorphe,

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
