### ISSUE TITLE
[syncfusion_flutter_pdf] PdfUriAnnotation which will be added to page could cause a Null check Exception

### ISSUE THREAD

**Issue by marcel-ploch** [syncfusion/flutter-widgets#1155]
Hi together,

I added following up Code.
It will open a PDF Document and iterate over all the form fields and check is some have a specific name.
If so it will add a PdfUriAnnotation to this field.

```
            field.backColor = (PdfColor(100, 100, 100, 50));
            final uriAnnotation = PdfUriAnnotation(
                bounds:
                    Rect.fromLTWH(field.bounds.left, field.bounds.top, 100, 50),
                uri: 'open_signature');
            print(field.bounds);

            field.page!.annotations.add(uriAnnotation);
```

With some PDF it could happen that i got following error:

```
E/flutter (17522): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (17522): #0      PdfFieldItem.page
pdf_field_item.dart:88
E/flutter (17522): #1      PdfTextBoxFieldHelper.draw
pdf_text_box_field.dart:711
E/flutter (17522): #2      PdfFormHelper.beginSave
pdf_form.dart:995
E/flutter (17522): #3      PdfDictionary.onBeginSave
pdf_dictionary.dart:554
E/flutter (17522): #4      PdfDictionary.saveDictionary
pdf_dictionary.dart:221
E/flutter (17522): #5      PdfDictionary.save
pdf_dictionary.dart:518
E/flutter (17522): #6      PdfCrossTable._doSaveObject
pdf_cross_table.dart:871
E/flutter (17522): #7      PdfCrossTable._saveIndirectObject
pdf_cross_table.dart:493
E/flutter (17522): #8      PdfCrossTable._saveObjects
pdf_cross_table.dart:361
E/flutter (17522): #9      PdfCrossTable.save
pdf_cross_table.dart:215
E/flutter (17522): #10     PdfDocument._appendDocument
pdf_document.dart:823
E/flutter (17522): #11     PdfDocument.saveSync
pdf_document.dart:583
E/flutter (17522): #12     _MyHomePageState.loadData
```

I could fix this if I add a Null check to the pdf_field_item file here:
L86 following.
```
holder is PdfReferenceHolder &&
//Null check here 
//holder.reference != null &&
holder.reference!.objNum == widgetReference.objNum &&
holder.reference!.genNum == widgetReference.genNum) {
```

Is a potentially fix or do I do something wrong?

Kind regards

Marcel Ploch

**Comment by irfanajaffer** [comment]
We have tried to reproduce the reported behavior with the provided details on our end, but it was working fine. We have attached the code snippet. We suspect that the issue might be with the specific PDF document. We request you share the input document with us so that we can assist you further in this.
[codesnippet.txt](https://github.com/syncfusion/flutter-widgets/files/11156984/codesnippet.txt)

**Comment by marcel-ploch** [comment]
There are two places missing the null check:

```
holder.reference != null
```

If this is present in any places it is working like a charm.

I tested this localy.

I changed it in pdf_field_item and pdf_field.

If the null check is there it is working.

Kind regards

Shall I create a PullRequest?

**Comment by irfanajaffer** [comment]
We will resolve the reported issues in our upcoming weekly releases, which will be available on April 25, 2023.

**Comment by irfanajaffer** [comment]
Since our 2023 volume 1 SP release is expected to be rolled out in this week. So, there will be no weekly release this week. We will include the fix for the reported issue in our Volume 1 SP release which we excepted within this week.



Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.

**Comment by irfanajaffer** [comment]
We are glad to announce that our Essential Studio 2023 Volume 1 Service Pack release v21.2.3 is rolled out and is available for download under the following link.

[Essential Studio 2023 Volume 1 Service Pack Release v21.2.3 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/182145/essential-studio-2023-volume-1-service-pack-release-v21-2-3-is-available-for-download)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance
