### ISSUE TITLE
How to dynamically create pdf or excel with template and data?

### ISSUE THREAD

**Issue by bahman2000** [syncfusion/flutter-widgets#1156]
We have multiple invoice templates and each template has its own structure. We want to generate invoices dynamically(based on the selected template  by the user). According to our analysis, We should have three json files to create an invoice.
1) template.json --> To specify invoice structure(template)
2) map.json        --> To specify how to map the data in the invoice(pdf or excel) file
3) data.json        -->  To specify invoice data 

How can we do this in the best possible way?

**Comment by superAndroidMan** [comment]
I have same problem

**Comment by wcfCode** [comment]
Solve it? How did you solve it?

**Comment by wcfCode** [comment]
thanks and best wishes

**Comment by irfanajaffer** [comment]
You can create a PDF document from scratch using our PDF library. Additionally, we can also generate PDF invoices based on template data. 

For further details, please refer to the following demo and user guide documentation.
[flutter.syncfusion.com/#/pdf/invoice](http://flutter.syncfusion.com/#/pdf/invoice)
[Getting started with Flutter PDF library | Syncfusion](https://help.syncfusion.com/flutter/pdf/getting-started#creating-a-simple-pdf-document-with-basic-elements)
