### ISSUE TITLE
SFDataGrid Stacked Headers PDF Export Problem

### ISSUE THREAD

**Issue by bahadirarslan** [syncfusion/flutter-widgets#1157]
I am using SFDataGrid in one of my projects and facing an issue with Stacked Headers.

In my project, I am using both Excel and pdf exports. Excel export is working tremendously but PDF export has a problem with stacked headers. 

This is the result of the Excel export and this is correct.
<img width="1366" alt="Screenshot 2023-04-05 at 02 32 03" src="https://user-images.githubusercontent.com/130344/229944810-7d24a611-0868-4538-998c-43976dea3941.png">

But this is the result of PDF export, as you can see stacked headers were omitted.
<img width="1311" alt="Screenshot 2023-04-05 at 02 31 01" src="https://user-images.githubusercontent.com/130344/229944878-c9bc8fe5-537c-4aa1-81d7-ad457d4d7779.png">

here is the PDF export code
```dart
PdfGrid pdfGrid = key.currentState!.exportToPdfGrid(
                              converter: converter,
                              rows: page,
                              excludeColumns: excludeColumns,
                              fitAllColumnsInOnePage: true,
                              cellExport: (details) async {
                                details.pdfCell.style.font = PdfTrueTypeFont(fontBytes, 6);
                              });
```

Converter code
```dart
class CustomDataGridToPdfConverter extends DataGridToPdfConverter {
  int page = 0;

  @override
  PdfGrid exportToPdfGrid(SfDataGrid dataGrid, List<DataGridRow>? rows) {
    (dataGrid.source as LogbookViewModel).silentHandlePageChange(page == 0 ? 0 : page - 1, page);
    return super.exportToPdfGrid(dataGrid, rows);
  }

  @override
  Object? getCellValue(GridColumn column, DataGridRow row) {
    var value = super.getCellValue(column, row);

    if (value.toString() == "0" || value.toString() == "00:00") {
      return "";
    }
    return value;
  }

  @override
  void exportColumnHeader(SfDataGrid dataGrid, GridColumn column, String columnName, PdfGrid pdfGrid) {
    var label = "";
    if (column.label is Text) {
      label = (column.label as Text).data!;
    } else if (column.label is Center) {
      label = ((column.label as Center).child as Text).data!;
    } else {
      label = (((column.label as Padding).child as Center).child as Text).data!;
    }
    super.exportColumnHeader(dataGrid, column, label, pdfGrid);
  }
}
```

I couldn't find what is wrong with PDF export.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @bahadirarslan,

**We have extensively tested the attached simple sample using the latest version of DataGrid Export (21.1.38) and we could not replicate the issue you reported**. The simple sample is working correctly, and the stacked headers are being exported to the PDF document without any problems, as demonstrated by the video output we have provided for your reference.

Based on our testing, we suspect that the issue you are experiencing may be specific to your sample. If you are still encountering the problem, **please provide us with additional information such as the sample you are using, along with any other relevant details**. This will enable us to gain a better understanding of the issue and provide an appropriate solution as quickly as possible.

**[sample_and_demo.zip](https://github.com/syncfusion/flutter-widgets/files/11158201/sample_and_demo.zip)**

Regards,
Tamilarasan

**Comment by bahadirarslan** [comment]
I will check the sample again and let you know about the result.
By the way, I might be over customize the data grid. If I can replicate the problem in a sample project. I will share it with you.

**Comment by bahadirarslan** [comment]
I checked the example. My problem caused by converter's `exportColumnHeader `method. Some how PDF exporter ignores the data but if comment the method I can see all the rows as it should be except column names.
Because `StackedHeaderCell` class has text property for exporting but `GridColumn`'s doesn't have. So the exporter uses `columnName` property. This is what I don't want. In my example I was trying to correct this behaviour at `exportColumnHeader` method. I couldn't understand why this is not working for PDF.

I think you need to add text property like as `StackedHeaderCell` to `GridColumn` class, so we can set column names for export. Otherwise like at your example, user sees "Designation" before export and "designation" after export. I think it shouldn't be like this.

**Comment by bahadirarslan** [comment]
I think the problem is with export methods. For example here is excel's export method.
```dart
@protected
  void exportColumnHeader(SfDataGrid dataGrid, GridColumn column,
      String columnName, Worksheet worksheet) {
    Range range;
    int rowSpan = 0;

    if (exportStackedHeaders && dataGrid.stackedHeaderRows.isNotEmpty) {
      rowSpan = getRowSpan(
          dataGrid: dataGrid,
          isStackedHeader: false,
          columnName: column.columnName, // <- getting column name from column.columnName
          rowIndex: excelRowIndex - startRowIndex - 1,
          columnIndex: dataGrid.columns.indexOf(column));
    }

    if (rowSpan > 0) {
      range = worksheet.getRangeByIndex(excelRowIndex - rowSpan,
          excelColumnIndex, excelRowIndex, excelColumnIndex);
      range.merge();
    } else {
      range = worksheet.getRangeByIndex(excelRowIndex, excelColumnIndex);
    }

    // Align cell content to the center position.
    range.cellStyle
      ..hAlign = HAlignType.center
      ..vAlign = VAlignType.center;

    _exportCellToExcel(worksheet, range, column,
        DataGridExportCellType.columnHeader, columnName);
  }
```

and here is the pdf exporter method
```dart
@protected
  void exportColumnHeader(SfDataGrid dataGrid, GridColumn column,
      String columnName, PdfGrid pdfGrid) {
    int rowSpan = 0;
    PdfGridRow columnHeader = pdfGrid.headers[rowIndex];
    PdfGridCell pdfCell = columnHeader.cells[_columnIndex];

    if (dataGrid.stackedHeaderRows.isNotEmpty && exportStackedHeaders) {
      rowSpan = getRowSpan(
          dataGrid: dataGrid,
          isStackedHeader: false,
          columnName: columnName, // <- getting column name from directly columName argument.
          rowIndex: rowIndex - 1,
          columnIndex: dataGrid.columns.indexOf(column));
    }
    if (rowSpan > 0) {
      columnHeader = pdfGrid.headers[rowIndex - 1];
      pdfCell = columnHeader.cells[_columnIndex];
      pdfCell.rowSpan = rowSpan + 1;
      pdfCell.value = columnName;
    } else {
      pdfCell.value = columnName;
    }
    pdfCell.style.borders.all = _pdfPen;
    _exportCellToPdf(
        DataGridExportCellType.columnHeader, pdfCell, columnName, column);
  }
```

Which one is correct I don't know but I prefer Excel's one because I can modify `columnName` argument before sending you, so the exporter writes the document that value. But in PDF exporter if I change the value system couldn't find the correct column.

So if it is possible, please change PDF exporter like Excel exporter or add text property to GridColumn class so I can use that property to set the correct header for exporting.

**Comment by Tamilarasan-Paranthaman** [comment]
@bahadirarslan, we have checked your query at our end, and we are able to replicate the reported issue when using the DataGridToPdfConverter at our end. We have considered this as a bug and logged a bug in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release which is expected to be rolled out on April 18, 2023. We will update you once the release is rolled out.

**Comment by Tamilarasan-Paranthaman** [comment]
@bahadirarslan,

We are glad to inform you that the fix has been included in our weekly pub release for the mentioned issue. Please update the **syncfusion_flutter_datagrid_export** package to version **21.1.41**.

https://pub.dev/packages/syncfusion_flutter_datagrid_export/changelog 

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you require any further assistance.

**Comment by ashok-kuvaraja** [comment]
Hi @bahadirarslan,

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
