### ISSUE TITLE
Relative position of PlotBand text in graph moves while scrolling

### ISSUE THREAD

**Issue by equinestudio** [syncfusion/flutter-widgets#1158]
I'm using PlotBand in SfCartesianChart, and set `horizontalTextAlignment`  to middle.
Relative position of PlotBand text in graph moves while scrolling,  I assume this is the behavior for the text to appear in the middle of the PlotBand even at the edge of the graph, but it is not, I want to fix the relative position of the text.

<img width="105" alt="スクリーンショット 2023-04-06 15 39 10" src="https://user-images.githubusercontent.com/11992021/230292145-f0bf2c9d-b1b6-491e-bfc3-27b0767d4947.png"> == scroll graph => <img width="94" alt="スクリーンショット 2023-04-06 15 39 32" src="https://user-images.githubusercontent.com/11992021/230292234-e2065c25-fb72-4bd1-bb13-3067ccd04729.png">

I think my request could be solved by adding an enum value like TextAnchor.start or TextAnchor.end where the relative position of the text does not move, and writing the code so that it works that way.

``` dart
enum TextAnchor {
  /// - TextAnchor.start, anchors the text at the start position.
  start,

  /// - TextAnchor.middle, anchors the text at the middle position.
  middle,

  /// - TextAnchor.end, anchors the text at the end position.
  end
}

```

**Comment by LokeshPalani** [comment]
Hi equinestudio,

The [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) will work for scrolling. It will calculate the dataPoints based on the visible range only. If customer wants the Plotband text to be visible while scrolling, this can be achieved by setting the [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) to false in both axes and by enabling [ZoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomMode.html) in the x-axis only. We have provided the code snippet and related user guide documentation for your reference.

```
late ZoomPanBehavior _zoomPanBehavior;
 
 @override
  void initState() {
    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
      zoomMode: ZoomMode.x,
      enableMouseWheelZooming: true,
    );
  super.initState();
 
  SfCartesianChart(
    zoomPanBehavior: _zoomPanBehavior,
    primaryXAxis: NumericAxis(anchorRangeToVisiblePoints: false),
  primaryYAxis: NumericAxis(anchorRangeToVisiblePoints: false),
)
```
 
UG,
https://help.syncfusion.com/flutter/cartesian-charts/zoom-pan#calculate-range-based-on-visible-points

Regards,
Lokesh.

**Comment by equinestudio** [comment]
Thank you for your comment! However, it does not seem to be what I want to do.

The numbers such as 26.4 in the image I plucked are all drawn by PlotBand and Text in it.
I want to make sure that the relative position of that Text in the graph does not change.
I am also attaching a video for reference.


https://user-images.githubusercontent.com/11992021/231180113-eaee052d-42f9-4846-9f35-021fc712ac08.mov

**Comment by LokeshPalani** [comment]
There is no direct support for preventing text in the [plotBands](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/plotBands.html) from scrolling. However, you can achieve your requirement by using [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property, placing the text, and setting the [CoordinateUnit](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CoordinateUnit.html) to [logicalPixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CoordinateUnit.html#logicalPixel). We have shared the related UG Documentation below for your reference.



UG,
https://help.syncfusion.com/flutter/cartesian-charts/annotations#positioning-the-annotation
