### ISSUE TITLE
[Flutter Web] Add example to use the syncfusion_flutter_pdfviewer with deferred loading

### ISSUE THREAD

**Issue by zogol** [syncfusion/flutter-widgets#1159]
Aas described by a user here https://github.com/flutter/flutter/issues/46589#issuecomment-1427138076 it is possible to reduce the main.dart.js by 1 mb when using deferred loading.

If you provide an official **how to** for this it could be another important reason for many, myself included, to switch from other pdf viewer libraries to the syncfusion_flutter_pdfviewer package.

**Comment by deepika134** [comment]
@zogol , The main.dart file is created and handled in the application level it doesn’t comes under the Syncfusion Pdf Viewer package and we didn’t have a main.dart.js in our package. Kindly share more details about your requirement.

**Comment by zogol** [comment]
by adding the syncfusion pdf viewer to the pubspec.yaml the main.dart.js increases by roughly 1mb.

Simple steps to reproduce:

1. create a hallo world flutter web project
2. Run flutter build web --> check size of main.dart.js
3. add synfusion pdf viewer package to pubspec.yaml
4. Run flutter build web --> check size of main.dart.js (becomes roughly 1mb bigger)

**Comment by deepika134** [comment]
We prepared a sample with the help of deferred loading to reduce the size of the main.dart.js . Please check the below sample and let us know if it meets your requirement. Once you confirmed, we will add this to our documentation.
[deffredloading.zip](https://github.com/syncfusion/flutter-widgets/files/11591970/deffredloading.zip)

**Comment by ramkumarsync** [comment]
We are closing this for now. Please acknowledge whether the provided sample met your requirements so that we can consider this in our documentation.
