### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by michael-william** [syncfusion/flutter-widgets#116]
I get an error message when running Pub get in yaml:
Because every version of integration_test from sdk depends on test_core 0.3.12-nullsafety.9 which depends on pedantic >=1.10.0-nullsafety <1.10.0, every version of integration_test from sdk requires pedantic >=1.10.0-nullsafety <1.10.0.
And because syncfusion_flutter_core >=18.2.54 depends on pedantic >=1.9.0 <1.9.9, integration_test from sdk is incompatible with syncfusion_flutter_core >=18.2.54.
So, because dash depends on both syncfusion_flutter_core ^18.4.34 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because dash depends on both syncfusion_flutter_core ^18.4.34 and integration_test any from sdk, version solving failed.)
Process finished with exit code 1

**Comment by Cali0707** [comment]
I had the same problem today.

**Comment by CLD1994** [comment]
depends on both syncfusion_flutter_charts ^18.4.34 and bloc_test ^7.1.0, version solving failed.

**Comment by Dharanipalani** [comment]
Hi @michael-william,

We are glad to inform you that the reported issue has been resolved in the syncfusion_flutter_core package with our latest version **v18.4.35+1**. Now, you will not get any error message while running the pub get command. To resolve the issue, kindly upgrade our core package to the latest version and you can download it from the following link.

**Latest version:** [https://pub.dev/packages/syncfusion_flutter_core/versions/18.4.35+1](url)

Kindly revert us if you need any further assistance.

Thanks,
Dharanitharan. P
