### ISSUE TITLE
seriesRendererDetails Null check operator exception

### ISSUE THREAD

**Issue by 999Rub** [syncfusion/flutter-widgets#1165]
Hi, I can't face this exception anymore.

I am using SfCartesiansCharts and FastLineSeries for high amount of data rendering.

Sometimes, when I update the data source, there is 

`"Null check operator used on null value"`

 exception.

After few investigations, I've found that in the series.dart file:

![image](https://user-images.githubusercontent.com/49523387/231411378-ca0a8e57-7ba2-4426-9cce-d582a9610c13.png)

This `if ` condition exists for `seriesRendererDetails` minimum/maximum for X and Y.
But, there is a **null check operator (!)**  which trigger this exception because of this:

![image](https://user-images.githubusercontent.com/49523387/231411794-d512f2b9-4fd3-4fd5-8dde-f7ebaaba20c2.png)

If it need recalculation, it set those values to null of then it check if it is not null.

If someone has a bypass to this or could fix it and open a PR  I would be grateful.

The exception occurs randomly when updating data source in Debug mode for both X and Y.

I currently use those versions:

- Flutter: 3.76 channel stable
- Dart: 2.19.3
- syncfusion_flutter_charts: ^20.1.60+1

**Comment by LokeshPalani** [comment]
We would like to let you know that the reported issue is already fixed and rolled out in our weekly patch release on April 11, 2023. So, we kindly request you to upgrade the syncfusion_flutter_chart package to the latest version below.



Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/21.1.39
