### ISSUE TITLE
Datagrid: ColumnChooser is missing (need something similar like the one in Angular)

### ISSUE THREAD

**Issue by ledjoncili** [syncfusion/flutter-widgets#1166]

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ledjoncili,

As of now, SfDataGrid doesn’t have support for column chooser feature. However, there is a workaround that you can use to achieve your requirement. You can choose which columns should be visible in the view by using the **GridColumn.visible** property. You can also write a custom checkbox pop-up menu and update the GridColumn.visible property value based on the checkbox selection. We have attached a sample demonstrating a workaround for your issue. To learn more, please refer to the included sample files.

**Sample Link:  [sample.zip](https://github.com/syncfusion/flutter-widgets/files/11406634/sample.zip)**

[screen-capture.webm](https://user-images.githubusercontent.com/93904422/236470549-c3e23725-d851-4abe-acb5-5f6707647e99.webm)

Regards,
Tamilarasan

**Comment by bubnenkoff** [comment]
+1 vote for implementing native ColumnChooser

**Comment by ashok-kuvaraja** [comment]
Hi @ledjoncili,

It appears that the workaround we've suggested may fulfill your needs. Please inform us if you need any additional assistance or further clarification.

Regards, 
Ashok K
