### ISSUE TITLE
[syncfusion_flutter_charts] Null check operator used on a null value

### ISSUE THREAD

**Issue by Oleksii-Milkov** [syncfusion/flutter-widgets#1167]
Flutter version: 3.7.7
Min Dart sdk in project: 2.7.0

syncfusion_flutter_charts: 21.1.39

I have this error after hot reload or after folding and opening app from background (If chart is visible).

> The following _CastError was thrown building LayoutBuilder:
> Null check operator used on a null value
> 
> The relevant error-causing widget was: 
>   SfCartesianChart SfCartesianChart:file:///home/oleksii/StudioProjects/InvoiceCopy%20(copy)/lib/pages/reports_page/widgets/cupertino/widgets/cupertino_payments_chart.dart:35:16
> When the exception was thrown, this was the stack: 
> #0      ChartSeriesPanel._needAxisAnimation (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:103:66)
> #1      ChartSeriesPanel._populateDataPoints (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:261:23)
> #2      ChartSeriesPanel.processData (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:90:7)
> #3      _ContainerAreaState._calculateBounds (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2573:41)
> #4      _ContainerAreaState._initializeChart (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2557:5)
> #5      _ContainerAreaState.build.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2548:34)
> #6      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:119:77)
> #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2682:19)

As i noticed it happens when i am trying to set visibleMinimum or visibleMaximum properties inside **DateTimeCategoryAxis**. If this properties empty - everything works fine

**Comment by vasa137** [comment]
I face the same error on Hot Reload and Value Update..

`The relevant error-causing widget was: 
  SfCartesianChart SfCartesianChart:file:///D:/Desktop/Posao/Julien/quatour/quatour_app/lib/widgets/screens/user/home/quatuor_chart.dart:113:12
When the exception was thrown, this was the stack: 
#0      SplineAreaChartPainter.paint (package:syncfusion_flutter_charts/src/chart/series_painter/spline_area_painter.dart:277:46)
#1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:571:13)
#2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:613:7)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#5      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#7      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#8      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#9      PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#11     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#12     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#13     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#17     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#21     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#24     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#40     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#43     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#46     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#49     _RenderLayoutBuilder.paint (package:flutter/src/widgets/layout_builder.dart:338:15)
#50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#52     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#53     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
#54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#56     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#59     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#62     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#63     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#66     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#67     _ChartContainerBox.paint (package:syncfusion_flutter_charts/src/common/common.dart:45:11)
#68     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#69     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#70     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#71     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#72     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#73     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#74     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:264:7)
#75     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:245:7)
#76     RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:778:13)
#77     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#79     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#80     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#81     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
#82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#84     RenderIndexedStack.paintStack (package:flutter/src/rendering/stack.dart:778:13)
#85     RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#86     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#87     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#88     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#89     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1089:7)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#91     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#92     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:74:15)
#93     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#94     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#95     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#96     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2383:11)
#97     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#98     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#99     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2924:15)
#100    RenderStack.paintStack (package:flutter/src/rendering/stack.dart:654:5)
#101    RenderStack.paint (package:flutter/src/rendering/stack.dart:670:7)
#102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#104    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:253:13)
#107    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#108    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2853:7)
#109    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:169:11)
#110    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:112:5)
#111    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1137:31)
#112    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:19)
#113    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#114    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#115    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#116    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#117    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#121    _invoke (dart:ui/hooks.dart:147:10)
#122    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#123    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 3 frames from dart:async)
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#9565b relayoutBoundary=up2
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=262.0)
...  size: Size(0.0, 0.0)
...  painter: SplineAreaChartPainter#1ea93(ValueNotifier<int>#148ad(169))
RenderObject: RenderCustomPaint#9565b relayoutBoundary=up2
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=262.0)
  size: Size(0.0, 0.0)
  painter: SplineAreaChartPainter#1ea93(ValueNotifier<int>#148ad(169))
====================================================================================================
D/EGL_emulation( 7766): app_time_stats: avg=12.29ms min=2.54ms max=87.05ms count=55
`

**Comment by Yuvaraj-Gajaraj** [comment]
We tried to replicate the reported issue at our end. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure on what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.

Sample: 
[chart_469458.zip](https://github.com/syncfusion/flutter-widgets/files/11648998/chart_469458.zip)

**Comment by LavanyaGowtham2021** [comment]
Hi @vasa137, @Oleksii-Milkov 
Please share the requested details to proceed further on this.
