### ISSUE TITLE
[syncfusion_flutter_pdf] PdfGraphics.scaleTransform is missing

### ISSUE THREAD

**Issue by pietervp** [syncfusion/flutter-widgets#1168]
While C# version has a way to set a scale transformation (https://help.syncfusion.com/cr/file-formats/Syncfusion.Pdf.Graphics.PdfGraphics.html#Syncfusion_Pdf_Graphics_PdfGraphics_ScaleTransform_System_Single_System_Single_) this functionality is not present for the Dart code: https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfGraphics-class.html

This seems to be something that was forgotten, can this be added? Additionaly maybe there is a way for us to add it ourselves?

**Comment by irfanajaffer** [comment]
Currently we do not have support for scale transform in PDF graphics in Flutter. We have logged the feature for “Support for scale transform in PDF graphics in Flutter” and added to our feature request list. We will implement this feature in any of our upcoming release.  

 

You can track the feature status using the feedback from[ https://www.syncfusion.com/feedback/43525/support-for-scale-transform-in-pdf-graphics-in-flutter](https://www.syncfusion.com/feedback/43525/support-for-scale-transform-in-pdf-graphics-in-flutter).
