### ISSUE TITLE
[syncfusion.SfCircularChart] Change graph directionality (not legend)

### ISSUE THREAD

**Issue by fmjabato** [syncfusion/flutter-widgets#1171]
I cannot change graph rendering directionality. I'm not meaning text directionality which is currently explained at your documentation, I mean the bar directionatility.

Obviously, negative values don't fix my problem and cannot play with angles like Pie and doughnut charts.

In order to explain my target. I have setted `useSeriesColor: true` and `trackOpacity` in order to show the full ring. I have implemented a switch button which changes between the value A and it's complementary. When I switch, I want to plot the complementary area which corresponds to the not plotted (zone with blurred color) but in the same position, not as a new CircularGraph which changes the bar position.

Sorry If I didn't explain properly

**Comment by LokeshPalani** [comment]
Hi @fmjabato,

We have checked your query on our end and kindly request that you share a screenshot of the expected output. This will help us better understand your requirement and provide more effective assistance.

Regards,
Lokesh.

**Comment by fmjabato** [comment]
Of course, thanks for quick response.

I want to do something like that (ignore numbers). Left chart is currently implemented and I want to have a field like "renderClockwise: false" which changes the direction of rendering (currently clockwise direction) and, (obviously, using the complementary dataset) generates the right chart
![image](https://user-images.githubusercontent.com/3104434/233053355-3c417778-c8bd-4cb2-a5c5-94c87dcc7d89.png)

**Comment by LokeshPalani** [comment]
We would like to let you know that currently, we don’t have support to render the RadialBarSeries in the anticlockwise direction. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback, https://www.syncfusion.com/feedback/43064/provide-anti-clock-wise-rendering-support-for-radial-bar-series
