### ISSUE TITLE
[syncfusion.SfCircularChart] Is it possible to Get combo circular charts ?

### ISSUE THREAD

**Issue by pradeep14598** [syncfusion/flutter-widgets#1172]
Is it possible to combine Pie chart and doughnut chart/ Pie chart like following image?

![image](https://user-images.githubusercontent.com/83265168/233764429-54826a81-307f-48f5-af1f-afea02fca4af.png)

**Comment by LokeshPalani** [comment]
Hi @pradeep14598,

We would like to inform you that we currently do not have support for the Sunburst chart. However, we have already logged a feature request for it in our feedback portal.

We will prioritize the features for each release based on demand and priority. Therefore, this feature will be available in one of our upcoming releases. You can also track the status of the feature with the feedback provided below.

Feedback, https://www.syncfusion.com/feedback/32217/sunburst-chart-with-all-its-functionalities

Regards,
Lokesh.
