### ISSUE TITLE
Layout problem  

### ISSUE THREAD

**Issue by flywithbug** [syncfusion/flutter-widgets#1177]
![image](https://user-images.githubusercontent.com/3955387/234196733-9fd9549c-d57c-4592-b6ac-dd176861c2a0.png)
display problem
SfPaddleTooltipShape(), thumb is out of slider range

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your query. Flutter was designed with Material. Therefore, in [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html), when the thumb is moved to the start and end positions, the thumb takes up half of the center position, causing it to display outside the divider. To address this issue, we have created a custom [trackShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/trackShape.html) with extended left and right positions. We have provided a sample and user guide documentation for your reference. Please let us know if you require further assistance.



UG,

https://help.syncfusion.com/flutter/slider/shapes#track-shape

Sample: 
[chart_457539.zip](https://github.com/syncfusion/flutter-widgets/files/11370074/chart_457539.zip)
