### ISSUE TITLE
Ui freezing when creating pdf with heavy images and  huge pages

### ISSUE THREAD

**Issue by jonex41** [syncfusion/flutter-widgets#1181]
i have been trying to use isolate for this, but i been getting this error  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart':

**Comment by irfanajaffer** [comment]
We were unable to reproduce the reported issue. We have created a simple sample to run heavy operations in a separate, isolate without hanging the UI for reference.

 

Kindly use the following link to download the sample,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_demo_sample-1493714408

 

If you are still facing the reported issue, kindly provide us with a working sample or complete code snippet with the required files for analyzing further this.
