### ISSUE TITLE
On going back to previous page, the data reloads again

### ISSUE THREAD

**Issue by lakshydeep-14** [syncfusion/flutter-widgets#1182]
Issue:
I am fetching the pdf from network. I also used file.writeAsBytes method.
But still when I go back to 1st page it shows circularprogressindicator instead of data which is already loaded .[ Video is attached here]

https://user-images.githubusercontent.com/58506078/235365454-fb1bff5d-bbff-4460-8a8a-9ab11edc2369.mp4

Expected:
1. Load pdf files from network as fast as possible so that user don't have to wait.
2. If I get back to previous page again then it must show the data directly without loading.

**Comment by deepika134** [comment]
We retrieve the PDF pages from the native platform renderer and loaded those pages in our Flutter PDF Viewer only based on the virtualization, that is initially 3 or 2 pages will be rendered based on the view port size and on-demand scrolling rest of the pages will be rendered. If we load all the pages at once, it will increase the loading time and memory consumption depending on the size of the document and so, we have avoided that behaviour.

**Comment by lakshydeep-14** [comment]
@deepika134 
Can I get the code for your approach?

I implemented Flutter PDF viewer by saving the pdf files. 
In this approach, saving files is taking take time.
How to overcome this?

**Comment by raaja-guidely** [comment]
@lakshydeep-14 are fixed this loading issue

**Comment by lakshydeep-14** [comment]
@deepika134  No... it's taking time to write to file/ download the pdf file even the file is of less size.

**Comment by ramkumarsync** [comment]
Since the PDF is downloaded and saved in the local storage before loading the PDF document, it will not be downloaded again when scrolling through the pages.
 
To conserve memory usage, we dispose of the page image not visible in the viewport. Only the page image will be re-rendered on scrolling, and the document will not be downloaded again. This is the current behavior of the SfPdfViewer widget.
