### ISSUE TITLE
Vertical spacing between X-Axis value and multilevel label for chart

### ISSUE THREAD

**Issue by Shilpa26v** [syncfusion/flutter-widgets#1185]
i am using CategoryAxis as X- Axis now according to requirement i hide XiAxis value using TextStyle(fontSize: 0)
And added multiLevelLabels list with 3 level. so when i have added multiLevelLabels theres more vertical padding between X- Axis line and multilevel lable i want to reduce that how can i do that ?
any help or suggestion would be appreciated 
Thanks.

**Comment by LokeshPalani** [comment]
We would like to let you know that currently, we don’t have support to reduce the spacing between the axis label and multilevel labels in the chart. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.



We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.



Feedback, https://www.syncfusion.com/feedback/43397/provide-support-to-reduce-the-spacing-between-the-axis-label-and-multilevel-labels

**Comment by LokeshPalani** [comment]
You are most welcome. You can customize the space between the [AxisLabel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AxisLabel-class.html) and [multiLevelLabels](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/multiLevelLabels.html) by changing the axisLabelPadding value. We have provided the necessary code below. Please let us know if you require further assistance.

File and Line number:

https://github.com/essential-studio/flutter-charts/blob/development/flutter_charts/syncfusion_flutter_charts/lib/src/chart/axis/axis_panel.dart#L272
