### ISSUE TITLE
[syncfusion charts] Datalabel alignment issue 

### ISSUE THREAD

**Issue by manjupm-iouring** [syncfusion/flutter-widgets#1186]
The data label in the charts is aligning next to the chart, I need to align the data label to the end of the screen. Is there any way to do this with this package

![image](https://user-images.githubusercontent.com/132569747/236188540-ff877ec3-44e0-4fe6-a102-48489363b8f6.png)

**Comment by LokeshPalani** [comment]
Hi @manjupm-iouring,

You can achieve your requirement by using the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/offset.html) property in the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html). By using the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/offset.html) property, you can move the data label in both the vertical and horizontal directions from its position. To align the data label at the end of the screen, you can set the value for the x position in the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/offset.html). We have shared a user guide documentation for your reference. Please let us know if you need any further assistance.


UG,
https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#data-label-padding


Regards,
Lokesh.
