### ISSUE TITLE
[syncfusion_flutter_sliders] RangeSlider with only one thumb

### ISSUE THREAD

**Issue by desmeit** [syncfusion/flutter-widgets#1188]
Is it possible to have a Rangeslider like the example below?

I could take a normal Slider but here the starting point is always 0.

![Bildschirmfoto 2023-05-04 um 16 46 12](https://user-images.githubusercontent.com/9454529/236244413-15e68552-c93e-4c78-b1b9-f3911b9adab0.png)

The second point (without the thumb) should not be clickable.

Is there a solution for this use case?

Thanks

**Comment by LokeshPalani** [comment]
Hi @desmeit, 

Currently, there is no option to disable the starting thumb always zero in the [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html). You can achieve your requirement by using [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html). In the [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html), we have drawn the path on the track with the help of [trackShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/trackShape.html) from the thumb center position. We have shared a code snippet, user guide documentation, and a sample for your reference. You can modify the sample based on your use case. Please let us know if you need any further assistance.


UG,
https://help.syncfusion.com/flutter/slider/shapes#thumb-shape

**code snippet**

``` 
   trackCenter = trackCenter ?? center;

   Path path = Path();
    path.moveTo(trackCenter!.dx, trackCenter!.dy);
    path.lineTo(center.dx, center.dy);

    context.canvas.drawPath(path, activeTrackPaint);
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/f1874321-5097-4e7c-bf4c-e11140c27019)

Regards,
Lokesh.


[slider_477214.zip](https://github.com/syncfusion/flutter-widgets/files/11933970/slider_477214.zip)
