### ISSUE TITLE
[syncfusion charts] Radialbar: Datalabel text color does not dynamically change

### ISSUE THREAD

**Issue by scalz** [syncfusion/flutter-widgets#1189]
Hello,

I noticed that datalabel's text color dynamically change (white/black) on pie/donut etc, but not on radialBar.

![Capture d’écran 2023-05-08 110538](https://user-images.githubusercontent.com/12609100/236789081-bc653504-894d-421e-8911-2a74832ea017.png)

Thank you for this awesome package and your help

**Comment by LokeshPalani** [comment]
Hi @scalz,

We have looked into your inquiry and found that, by default, the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/dataLabelSettings.html) in the [RadialBarSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries-class.html) are displayed within the track before the segment begins. To modify the text color of the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/dataLabelSettings.html), you can enable [trackColor](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries/trackColor.html) in the [RadialBarSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries-class.html). This is the typical behavior of the [RadialBarSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/RadialBarSeries-class.html) in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). We have provided a link to the user guide documentation for your reference. If you need any further assistance, please feel free to ask.

User Guide:
https://help.syncfusion.com/flutter/circular-charts/chart-types/radial-bar-chart#track-customization

Best Regards,
Lokesh.
