### ISSUE TITLE
Flutter web network file is not displaying

### ISSUE THREAD

**Issue by aliaafreen** [syncfusion/flutter-widgets#1190]
I am using syncfusion_flutter_pdfviewer for rendering pdf using network url on flutter web.
here not showing any errors but not showing pdf just a blank page is shown.
on failed it shows only message
"There was an error opening this document."
not any specific error.

flutter - 3.3.2
  syncfusion_flutter_pdfviewer: 20.3.47
  
  Will you please give some solution as soon as possible?

**Comment by SittiphanSittisak** [comment]
Hi, Did you add
```
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
<script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
</script>
```
in the body tag of the index.html file that locates in the web folder?

**Comment by deepika134** [comment]
Hi @aliaafreen ,

For the web platform, we have used PdfJs for rendering the PDF pages, so the script file must be referred to in your web/index.html file. On your web/index.html file, add the following script tags, somewhere in the head or body of the document:
 
Script:
 
`<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script> <script type="text/javascript"> pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js"; </script>`
 
UG documentation link: https://help.syncfusion.com/flutter/pdf-viewer/getting-started#add-the-flutter-pdf-viewer-to-an-application
