### ISSUE TITLE
How to set conditional label to primaryYAxis or primaryXAxis?

### ISSUE THREAD

**Issue by jatin-vvdn** [syncfusion/flutter-widgets#1195]
We require to show conditional format string to any one axis X or Y like below.

if size=1000000000 in bytes

    double b = size;
    double k = size / 1024.0;
    double m = ((size / 1024.0) / 1024.0);
    double g = (((size / 1024.0) / 1024.0) / 1024.0);
    double t = ((((size / 1024.0) / 1024.0) / 1024.0) / 1024.0);

Based on this we have to show Bytes, KB, MB, GB and TB.

currently we have done code for this label as below.

    primaryYAxis: CategoryAxis(
          isVisible: true,
          axisLabelFormatter: (AxisLabelRenderDetails args) {
            String label = AppUtils.applicationVolumeValue(args.value);
            return ChartAxisLabel(label, args.textStyle);
          },
        ),

**Error:**

> Class 'CategoryAxis' has no instance getter 'labelFormat'.
> Receiver: Instance of 'CategoryAxis'
> Tried calling: labelFormat

On clicking we are facing above error and label is not visible on the chart.

**Comment by LokeshPalani** [comment]
Hi @jatin-vvdn,

You can achieve your requirement with help of [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback. By using [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, you can customize the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html) and [textstyle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/textStyle.html) using the [ChartAxisLabel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel-class.html) and return to it. We have shared a code snippet, user guide documentation and sample for your reference. You can modify the sample based on your use case. Please let us know if you need any further assistance.

**Code snippet:**

```
body: SfCartesianChart(
          primaryXAxis: NumericAxis(
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              double k = 1000000000 / 1024.0;
              double m = ((1000000000 / 1024.0) / 1024.0);
              double g = (((1000000000 / 1024.0) / 1024.0) / 1024.0);
              double t = ((((1000000000 / 1024.0) / 1024.0) / 1024.0) / 1024.0);
              String label = details.value == 2
                  ? '$k KB'
                  : details.value == 4
                      ? '$m MB'
                      : details.value == 6
                          ? '$g GB'
                          : details.value == 8
                              ? '$t TB'
                              : '';
              return ChartAxisLabel(label, details.textStyle);
            },
          ),
          primaryYAxis:
              NumericAxis(numberFormat: NumberFormat.compactSimpleCurrency()),
```
 
**UG,**
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter

**Output:**
![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/c5c051db-576f-4932-87cc-83ccdc5fd897)


Regards,
Lokesh.


[chart_468919.zip](https://github.com/syncfusion/flutter-widgets/files/11614166/chart_468919.zip)

**Comment by jatin-vvdn** [comment]
@LokeshPalani  Thanks for details answered! really helpful to us. Thanks again.
