### ISSUE TITLE
Syncfusion Flutter PdfViewer displaying a gray screen instead of the PDF File

### ISSUE THREAD

**Issue by kertukagreisi** [syncfusion/flutter-widgets#1201]
Hello
We need to display a pdf file in our Flutter application. It is located on the assets/templates folder. When we open the pdf screen for the first time, we don't see the pdf, but a grey screen, this is when we have cleared the browser cache. Sometimes when we refresh the page on the web, the attachment is displayed. We use SfPdfViewer.memory method to display the file. It also occurs on the test server where we deployed the app.
We need the pdf to load at first attempt.
Below is the code that we implemented to display the file and attached is a similar example that I implemented.

  `
  
     Future<Uint8List> loadPdfFromAsset(String assetPath) async {

       final ByteData byteData = await rootBundle.load(assetPath);
    
       return byteData.buffer.asUint8List();
    }
  
  `

  `
    
    Widget getDocumentWidget() {
    return FutureBuilder<Uint8List>(
      future: loadPdfFromAsset('assets/templates/Task_Card.pdf'),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(
            child: CircularProgressIndicator(),
          );
        } else if (snapshot.hasError) {
          return const Center(
            child: Text('Error loading PDF'),
          );
        } else if (snapshot.connectionState == ConnectionState.done && snapshot.hasData) {
          return SfPdfViewer.memory(
            snapshot.data!,
          );
        } else {
          return const Center(
            child: Text('PDF data not available'),
          );
        }
      },
    );
    }
  
  
  `

[flutter_syncfusion_pdf_issue.zip](https://github.com/syncfusion/flutter-widgets/files/11496664/flutter_syncfusion_pdf_issue.zip)

**Comment by duytient31** [comment]
help me

**Comment by kertukagreisi** [comment]
I only needed to include pdfjs library on the index.html file on the web directory of the application, because the issue occurs only on web.
