### ISSUE TITLE
A constant constructor can't call a non-constant super constructor. - datepicker

### ISSUE THREAD

**Issue by LuvJain** [syncfusion/flutter-widgets#1205]
Not a duplicate of https://github.com/syncfusion/flutter-widgets/issues/1199.
Encountering this issue on syncfusion_flutter_datepicker version ^21.2.5 & 21.2.0.

Error: Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-21.2.5/lib/src/date_picker/date_picker.dart:7584:8: Error: A constant constructor can't call a
non-constant super constructor.

**Comment by mauriziopinotti** [comment]
Same here on all platforms (Android, iOS, Web):

```
[        ] ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-21.2.5/lib/src/date_picker/year_view.dart:1399:9: Error: A constant constructor can't call a non-constant super constructor.
[        ]       : super(children: widgets);
```

It started in 21.2.5 and works fine if I go back to 21.2.4.

**Comment by LuvJain** [comment]
Thanks @mauriziopinotti! I didn't 21.2.4 but that seems to have provided a solution for now.

my updated pubspeck.lock to have it work:


  syncfusion_flutter_core:
    dependency: transitive
    description:
      name: syncfusion_flutter_core
      url: "https://pub.dev"
    source: hosted
    version: "21.2.4"
  syncfusion_flutter_datepicker:
    dependency: "direct main"
    description:
      name: syncfusion_flutter_datepicker
      url: "https://pub.dev"
    source: hosted
    version: "21.2.4"

pubspec.yaml
  syncfusion_flutter_datepicker: 21.2.4

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared information, we have checked the issue “**A constant constructor can't call a non-constant super constructor**” in a simple sample of the Flutter calendar in macOs and iPhone Simulator, but we are unable to reproduce the mentioned issue, it was working fine as expected from our end. 

  **Tested details:**
1. Flutter version: Stable channel-3.10.1
2. Flutter  Date Picker version: 21.2.5

Kindly run the flutter clean command then check and let us know still if you are facing the same issue, please share the below details with us.

1. Replication procedure

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
