### ISSUE TITLE
Tooltip Rotation Issue when using isTransposed: true in SfCartesianChart 

### ISSUE THREAD

**Issue by kanwarmanraj** [syncfusion/flutter-widgets#1207]
When the isTransposed property is set to true in the SfCartesianChart widget in Flutter, the chart axes are transposed, resulting in the X-axis becoming vertical and the Y-axis becoming horizontal. However, the tooltips associated with the chart elements (such as data points) do not automatically rotate to match the transposed axes. As a result, the tooltips appear in their default horizontal orientation, which can cause confusion and inconsistency with the chart's visual representation.

**Comment by LokeshPalani** [comment]
Hi @kanwarmanraj,

When the [isTransposed](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/isTransposed.html) property is set to true in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), the orientation of the x-axis is set to vertical and the orientation of the y-axis is set to horizontal. As per the chart's behavior, by default, the tooltip will render in a horizontal orientation only. Please let us know if you need any further assistance.

Regards,
Lokesh.
