### ISSUE TITLE
PDF Form filled data is not visible

### ISSUE THREAD

**Issue by yassinsameh** [syncfusion/flutter-widgets#1208]
I have a PDF form that is filled using the python package pypdf using the method  
```
pdf_writer.update_page_form_field_values(
      pdf_writer.pages[0], data,
            flags=1
        )
```
**The PDF is viewable in browsers on Mobile and Desktop, However when using  SfPdfViewer the form data is empty but the other text is visible.**

PDF sample is attached here.
[sample_contract.pdf](https://github.com/syncfusion/flutter-widgets/files/11542970/sample_contract.pdf)

_Package Versions:_
syncfusion_flutter_pdfviewer: ^21.2.5
syncfusion_flutter_core: ^21.2.5

**Comment by buivanhieu2105** [comment]
Hi ad, 
Same issue, I face with showing PDF file and I got result as question's yassinsameh, 
Pls help to check if you have any solution
Thanks!

**Comment by tynn** [comment]
The `syncfusion_flutter_pdfviewer` seems to use the standard `android.graphics.pdf.PdfRenderer`, which doesn't seem render forms. I even found, that the standard printer was not displaying it.

**Comment by ramkumarsync** [comment]
The SfPdfViewer supports the rendering and editing of form data since the 2023 Volume 3 release (v23.1.36). Kindly use the mentioned version or later to overcome your case.
