### ISSUE TITLE
syncfusion_flutter_core: ^21.2.6 ERROR

### ISSUE THREAD

**Issue by berkansevimli** [syncfusion/flutter-widgets#1209]
After made "flutter pub upgrade" I get this error both platform(android and iOS):

../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-21.2.6/lib/src/calendar/custom_looping_widget.dart:50:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(children: children);
        ^

**Comment by celiamauredev** [comment]
Hello, 
I am facing the same issue since version 21.2.6

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared information, we have checked the issue “**A constant constructor can't call a non-constant super constructor**” in the simple sample of the Flutter calendar. But we are unable to reproduce the mentioned issue, it was working fine as expected from our end.

**Tested details:**
1. Flutter version: Stable channel-3.10.1
2. Flutter  Date Picker version: 21.2.6

Kindly update the Flutter version to latest version 3.10.1 then check and let us know still if you are facing the same issue, please share the below details with us.

1.Replication procedure

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
