### ISSUE TITLE
DataLabelSettings labelAlignment for ColumnSeries chart

### ISSUE THREAD

**Issue by Shilpa26v** [syncfusion/flutter-widgets#1211]
I am using ColumnSeries char when i wanted to align label of each column bar. The issue i am facing is when i add this property  labelAlignment:ChartDataLabelAlignment.outer it's not working according exact position. The current position for labelAlignment is ChartDataLabelAlignment.outer.
I wanted to have each label outside of the each column bar and top of bar. 
can anyone suggest me here is there somethings i am missing as property for column series chart.
Any help or suggestions would be appreciate.
Thanks.

![graph](https://github.com/syncfusion/flutter-widgets/assets/52877030/a35e90a1-b5b9-42e9-97a4-901ec43781c2)
![pgraph2](https://github.com/syncfusion/flutter-widgets/assets/52877030/6eb3025f-1923-4f42-87bb-6019ce6abbba)

```
ColumnSeries<ReportData, String>(
                  animationDuration: 0,
                  // Width of the columns
                  dataSource: masterAssayData.results!,
                  dataLabelSettings: const DataLabelSettings(
                    isVisible: true,
                    labelAlignment:ChartDataLabelAlignment.outer
                  ),
                  dataLabelMapper: (ReportData data, _) {
                    var value = ctrl.getDataMapperValue(data, masterAssayData.selectedValue?.unitId);
                    return value;
                  },
                  pointColorMapper: (ReportData data, _) => Color(int.parse("0xff${data.backgroundColor!.substring(1)}")),
                  xValueMapper: (ReportData data, _) => data.resultData?.date,
                  yValueMapper: (ReportData data, _) => ctrl.getReportYAxisValue(data, masterAssayData.selectedValue?.unitId))
```

**Comment by LokeshPalani** [comment]
Hi @Shilpa26v ,

You can achieve your requirement by enabling the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/offset.html) property in the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html). By using this, you can move the dataLabel horizontally or vertically from its position. By default, the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html) will render above the segment. When the segment is small, the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html) will render inside the segment. Please let us know if you require any further assistance.

Regards,
Lokesh.

**Comment by Shilpa26v** [comment]
@LokeshPalani 
Thanks for response.

Applying offset will apply for all column and all chart 
As you said if segment is small the dataLabelSettings will render inside the segment and 
As per my requirement labelAlignment property is working but when it comes to  maxheight of ColumnSeries its showing under bar.So i wanted to fix this for higher ColumnSeries bar that it should be always on top not inside the bar.

so here i wanted to customise this if we can want add lable outside top of the ColumnSeries ?
can you suggest which file and and linenumber will have that logic and where i can make customising this height when label apply for hight ColumnSeries bar ?

**Comment by LokeshPalani** [comment]
Hi @Shilpa26v,

You can achieve your requirement by using the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback to render the data label position. We have created a sample by overriding the [drawDataLabel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeriesRenderer/drawDataLabel.html) method, which allows you to create a data label with a custom position. We have shared the sample below for your reference. You can modify the sample as per your requirement.

Regards,
Lokesh.

[chart_467308.zip](https://github.com/syncfusion/flutter-widgets/files/11597144/chart_467308.zip)
