### ISSUE TITLE
DoughnutSeries not working properly in some case

### ISSUE THREAD

**Issue by gnassro** [syncfusion/flutter-widgets#1212]
when i pass 2 ChartData with small difference between the values (like 20 and 30) it work properly, but when pass ChartData with big difference (like 1684922401211.0 and 1.0) the chart disapear, it show only blank.

```
final List<ChartData<String, double>> dataList = [
      ChartData('ts', 1684922401211.0),
      ChartData('long_v', 1.0),
    ];

    return SfCircularChart(
      series: [
        DoughnutSeries<ChartData<String, double>, String>(
          animationDuration: 0,
          dataSource: dataList,
          xValueMapper: (ChartData<String, double> data, _) => data.x,
          yValueMapper: (ChartData<String, double> data, _) => data.y,
        )
      ],
    );
```
Flutter version:  3.7.12
syncfusion_flutter_charts: ^20.4.50

**Comment by LokeshPalani** [comment]
Hi @gnassro ,

We can replicate the reported issue at our end and have logged a bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on 2nd week of June. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.

Feedback,

https://www.syncfusion.com/feedback/44070/doughnut-series-is-not-rendering-when-given-two-data-with-large-difference

Regards,
Lokesh.

**Comment by LokeshPalani** [comment]
Hi @gnassro,

The reported issue regarding **Doughnut series was not rendering properly when having two data points with large differences** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/21.2.10

Regards,
Lokesh.
