### ISSUE TITLE
Error: Member not found: 'EdgeInsets.fromViewPadding'.                         double keyPadHeight = EdgeInsets.fromViewPadding()

### ISSUE THREAD

**Issue by vocsygautam** [syncfusion/flutter-widgets#1213]
syncfusion_flutter_pdfviewer: ^21.2.6
flutter sdk 3.7.12

**Comment by andfaraway** [comment]
I also encountered this problem,try syncfusion_flutter_pdfviewer: ^21.2.3, it's work

**Comment by Eagle799** [comment]
> I also encountered this problem,try syncfusion_flutter_pdfviewer: ^21.2.3, it's work

i did the same but not working and show the same problem

**Comment by fabioselau077** [comment]
same here... resolved?
