### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Don't get item height from pdf list

### ISSUE THREAD

**Issue by chepizhko-ruslan** [syncfusion/flutter-widgets#1214]
[syncfusion_flutter_pdfviewer]
How to get item height from pdf list. I only find the method of taking the height of list. 
PdfPageSettings height = details.document.pageSettings.height or details.document.pages[0].size.height
The height of the item is needed to determine the number of the item in the list when tapping and extracting the tap coordinates.
Or perhaps you will make a tap callback? So that you can get information about the item and its position in the list.

![Screenshot 2023-05-24 at 19 02 47](https://github.com/syncfusion/flutter-widgets/assets/129733056/db022776-e1b1-49c5-b5d0-4717d29bba45)

**Comment by chepizhko-ruslan** [comment]
![Screenshot 2023-05-24 at 19 02 47](https://github.com/syncfusion/flutter-widgets/assets/129733056/1234f458-bfbb-4e1f-aefb-d21f1b21b72b)

**Comment by deepika134** [comment]
We have prepared a sample for retrieving the tapped coordinates relative to the PDF page, which can be downloaded from the attachment. Please find the workflow of this example application below.

We used the **TapGestureRecognizer** to catch the tap action and the **onTapDown** callback. We have the **_getPdfCoordinates()** method, which has the logic to return the tapped location coordinates relative to the PDF page.

Please review it and let us know if it meets your requirements.
[pdf_coordinates_8b478afe.zip](https://github.com/syncfusion/flutter-widgets/files/11571748/pdf_coordinates_8b478afe.zip)

**Comment by ramkumarsync** [comment]
We are closing this issue since we haven't heard back from you for a long time. Please feel free to contact us anytime if you need any further assistance.
