### ISSUE TITLE
[syncfusion_flutter_pdfviewer]

### ISSUE THREAD

**Issue by aurnabsbd** [syncfusion/flutter-widgets#1215]
please update the http package for [syncfusion_flutter_pdfviewer] as it is still using the package http 0.13.0 but http package is upgraded to 1.0.0 2 days ago

**Comment by Alvirwalid** [comment]
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
                          View.of(context).viewInsets.bottom != 0.0;
                          ^^^^

**Comment by ramkumarsync** [comment]
The http package version has been upgraded to the latest version 1.0.0 since the SfPdfViewer version v22.1.34.
