### ISSUE TITLE
Error: A constant constructor can't call a non-constant super constructor.       : super(children: children);

### ISSUE THREAD

**Issue by suresh161229** [syncfusion/flutter-widgets#1217]
Im getting this error while using the syncfusion_flutter_charts package in my project..please tell me howot resolve it.

**Comment by savadodesigns** [comment]
Same here

**Comment by Mashi-91** [comment]
just change package version to this syncfusion_flutter_charts: 21.2.4 :)

**Comment by LokeshPalani** [comment]
Hi @suresh161229,

We have checked the issue "A constant constructor can't call a non-constant super constructor" in a simple sample, but we were unable to reproduce the mentioned issue. It was working fine from our end. To resolve this issue, we kindly request that you update to the latest version of Flutter, 3.10.0. Please let us know if you need further assistance.

Regards,
Lokesh.

**Comment by nirex0** [comment]
Adding the library to the pubspec file and running `flutter clean` and `flutter pub get` and then building for windows throws this exact error. "A constant constructor can't call a non-constant super constructor"

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you still face an issue with latest charts version.
