### ISSUE TITLE
[syncfusion_flutter_datagrid] How to use onSelectionChanged ?

### ISSUE THREAD

**Issue by bubnenkoff** [syncfusion/flutter-widgets#1218]
Hi!
I can't find examples how to make list of selected rows:
```
onSelectionChanged: (List<DataGridRow> addedRows, List<DataGridRow> removedRows) {
ctrl.commonTableSelected = addedRows.map((dataGridRow) => dataGridRow as ComplexSearchCommonModel).toList();
},
```                  
this code is suggested by GPT but I am getting an error:
```
"Error: Expected a value of type 'ComplexSearchCommonModel', but got one of type 'DataGridRow'
```

He also suggested to use `dataGridRow.data` property, but `dataGridRow` have not it.

**Comment by Tamilarasan-Paranthaman** [comment]
@bubnenkoff,

Based on the provided code snippet, it seems that you are attempting to convert the selected row in the addedRows property to the corresponding underlying object. However, please note that the onSelectionChanged event provides the selected row as a DataGridRow type, which cannot be directly mapped to the desired object type.

To achieve the desired mapping, you have a couple of options:

**1. Find the index of the row and fetch the object from the underlying collection.**

```dart
          onSelectionChanged: (addedRows, removedRows) {
            for (final DataGridRow row in addedRows) {
              int rowIndex = _employeeDataSource.rows.indexOf(row);
              final Employee employee = _employees[rowIndex];
              selectedEmployees.add(employee);
            }
          },

```
2. Define an object with the respective data grid cell values: Create a new object and assign the values of the corresponding cells in the DataGridRow to the properties of the object.

```dart
onSelectionChanged: (addedRows, removedRows) {
            selectedEmployees = addedRows.map((dataGridRow) {
              final cells = dataGridRow.getCells();
              Employee employee = Employee(cells[0].value, cells[1].value,
                  cells[2].value, cells[3].value);

              return employee;
            }).toList();
          },

```

Please check the following simple sample for more details.

**Sample Link: [DataGrid-Simple-Sample](https://github.com/syncfusion/flutter-widgets/files/11589567/sample.zip)**

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi,

It appears that the workaround we've suggested may fulfill your needs. We are closing this issue. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards, 
Ashok K
