### ISSUE TITLE
Any mindmap/tree chart widgets?

### ISSUE THREAD

**Issue by Maclaon** [syncfusion/flutter-widgets#122]
![image](https://user-images.githubusercontent.com/5398475/105468741-48406780-5cd2-11eb-963c-5585fd3d278c.png)

**Comment by Dharanipalani** [comment]
Hi @Maclaon,
 
Thanks for your interest in Syncfusion Flutter widgets. We wish to let you know that, in our other platforms like Web(EJ2), Mobile(Xamarin) we have similar controls based on your requirement. So, we would like to confirm whether you wish to have the same in our Flutter widgets. We have shared our other platform links for your reference.

EJ2: [https://ej2.syncfusion.com/demos/#/material/diagram/default-functionalities.html](url)
Xamarin: [https://help.syncfusion.com/xamarin/diagram/overview](url)

If you require other features than the above, kindly share those. This will be helpful in further analysis in considering your feature requirement.

Thanks,
Dharanitharan. P

**Comment by Maclaon** [comment]
![](https://help.syncfusion.com/xamarin/diagram/Overview_images/img1.png)

Yeah, this is what i want! Maybe with a zoom animation, and auto-increase, and fold/unfold, and short line length, and different color edges, and different shapes, and so on! So i can integrate it into my flutter app! i appreciate that u can offer this tree chart!

**Comment by Dharanipalani** [comment]
Hi @Maclaon, 
 
Thanks for the revert. We log a feature request for your requirement and moreover, this is not in our Wishlist of upcoming main releases in the flutter. So, we couldn't provide a certain timeline for this feature and this may come in any of our future main releases. You can track the status of the feature from the following feedback link.

Feedback Link: [https://www.syncfusion.com/feedback/21780/diagram-widget-with-all-its-functionalities](url)

Thanks,
Dharanitharan. P

**Comment by Maclaon** [comment]
Thanks, i am looking forward to that release!
