### ISSUE TITLE
[Mobile] How to hide horizontal scroll

### ISSUE THREAD

**Issue by duypxd** [syncfusion/flutter-widgets#1222]
How to hide horizontal when scroll on Mobile?

`syncfusion_flutter_datagrid: ^21.2.6, syncfusion_flutter_core: ^21.2.6`

`isScrollbarAlwaysShown`: Indicates whether the horizontal and vertical scrollbars should always be visible. When false, both the scrollbar will be shown during scrolling and will fade out otherwise. When true, both the scrollbar will always be visible and never fade out.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @duypxd,

As of now, DataGrid does not have support for hiding the scrollbars. We have already considered your request as a feature. This feature will be implemented in our 2023 Volume 2 release, which is expected to be rolled out at the end of June 2023. We will let you know when this feature is implemented. We appreciate your patience and understanding in the meantime. You can follow up with the below feedback for further details,

**Feedback link: https://www.syncfusion.com/feedback/36456/support-to-hide-the-scroll-bars**    

Regards,
Tamilarasan

**Comment by duypxd** [comment]
> Hi @duypxd,
> 
> As of now, DataGrid does not have support for hiding the scrollbars. We have already considered your request as a feature. This feature will be implemented in our 2023 Volume 2 release, which is expected to be rolled out at the end of June 2023. We will let you know when this feature is implemented. We appreciate your patience and understanding in the meantime. You can follow up with the below feedback for further details,
> 
> **Feedback link: https://www.syncfusion.com/feedback/36456/support-to-hide-the-scroll-bars**
> 
> Regards, Tamilarasan

Thank you so much 💯

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @duypxd,

We are glad to announce that our Essential Studio 2023 Volume 2 Main Release **V22.1.34** is rolled out with the implementation of “hiding DataGrid scrollbars” and is available for download under the following link.

https://www.syncfusion.com/forums/183035/essential-studio-2023-volume-2-main-release-v22-1-34-is-available-for-downloadb 

**UG Documentation Link: https://help.syncfusion.com/flutter/datagrid/scrolling#change-scrollbars-visibility** 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Tamilarasan

**Comment by duypxd** [comment]
> Hi @duypxd,
> 
> We are glad to announce that our Essential Studio 2023 Volume 2 Main Release **V22.1.34** is rolled out with the implementation of “hiding DataGrid scrollbars” and is available for download under the following link.
> 
> https://www.syncfusion.com/forums/183035/essential-studio-2023-volume-2-main-release-v22-1-34-is-available-for-downloadb
> 
> **UG Documentation Link: https://help.syncfusion.com/flutter/datagrid/scrolling#change-scrollbars-visibility**
> 
> We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
> 
> Regards, Tamilarasan

Thank you and the team so much.
