### ISSUE TITLE
[syncfusion_flutter_gauges] How can I get a radial gradient in a radial gauge. 

### ISSUE THREAD

**Issue by rktejesh** [syncfusion/flutter-widgets#1223]
I want the gradient to happen from the center of the circle to the edges. Currently it only allows Sweep Gradient. 

![images (1) (9).jpeg](https://github.com/syncfusion/flutter-widgets/assets/73354337/f52d74a5-3f71-4c0c-8acf-06910814dada)

Something like this. Thanks!

**Comment by sfHariHaraSudhan** [comment]
Hi @rktejesh,

In [SfRadialGauge](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfRadialGauge-class.html), we can apply only a sweep gradient to the [RadialAxis](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis-class.html). However, we can apply the radial gradient with the help of [GaugeAnnotation](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/GaugeAnnotation-class.html) inside the [annotations](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/annotations.html) property. In the [GaugeAnnotation](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/GaugeAnnotation-class.html), we can provide the custom widget with the radial gradient.

Attached the user guide link and sample browser link below for your reference.
UG https://help.syncfusion.com/flutter/radial-gauge/overview.
SB https://flutter.syncfusion.com/#/radial-gauge/showcase/sleep-tracker.

Kindly refer the code snippet below:
```
SizedBox(
  width: 500,
  height: 500,
  child: SfRadialGauge(
    axes: <RadialAxis>[
      RadialAxis(
        canScaleToFit: true,
        showLabels: false,
        showTicks: false,
        startAngle: 0,
        endAngle: 360,
        ranges: [
          GaugeRange(
            startValue: 0,
            endValue: 360,
            color: Colors.blue,
          ),
        ],
        annotations: [
          GaugeAnnotation(
            widget: Align(
              alignment: const Alignment(0.5, 0),
              child: Container(
                width: 480,
                height: 480,
                decoration: const BoxDecoration(
                  backgroundBlendMode: BlendMode.darken,
                  gradient: RadialGradient(
                    colors: [
                      Colors.white,
                      Colors.lightBlue,
                      Colors.blue,
                    ],
                  ),
                  shape: BoxShape.circle,
                ),
              ),
            ),
          ),
        ],
      ),
    ],
  ),
),
```

Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/0e8bc65a-b11b-48c0-8572-7e20d24b5fe7)

Also attached the sample below for your reference.

Regards,
Hari Hara Sudhan. K.

[477212.zip](https://github.com/syncfusion/flutter-widgets/files/11891337/477212.zip)

**Comment by rktejesh** [comment]
Thanks a lot 👍
