### ISSUE TITLE
Syncfusion DataGrid without header row

### ISSUE THREAD

**Issue by mbenci** [syncfusion/flutter-widgets#1228]
I wish I could make a table without header row but I can't find the way.
Is it possible? How?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @mbenci,

The current implementation of the DataGrid requires the presence of a header column. This design choice ensures that the column count and DataGrid cell count remain synchronized. If there is a mismatch between these counts, an exception will be thrown, making it not possible to build the DataGrid without a header column.

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @mbenci,

We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
