### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Adding highlights without reloading document

### ISSUE THREAD

**Issue by vorte** [syncfusion/flutter-widgets#1229]
I've been following this [guide](https://support.syncfusion.com/kb/article/11033/how-to-add-text-markup-annotation-in-flutter-pdf-viewer-using-syncfusion-pdf-package) to allow adding annotations to PDF documents. It uses `syncfusion_flutter_pdf` and `syncfusion_flutter_pdfviewer` packages. 

The code seems to work, but every time I add a highlight, the whole document is reloaded (which takes a few seconds) and then the screen goes back to page 1 of the document.

So the question is - is it possible to add an annotation to an open document without actually reloading the document? I don't need to save the file (can do that later), just want to make it obvious to the user that the highlight has been added, i.e. make the text background yellow.

**Comment by deepika134** [comment]
At present we do not have support for text markup annotations in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following link for track the status of the feature,

https://www.syncfusion.com/feedback/26331/support-for-text-markup-annotation

**Comment by vorte** [comment]
Thank you. This is very important for us. Would love to have it implemented.

**Comment by ramkumarsync** [comment]
The support to add, remove, modify, and save text markup annotations in PDF files is available from the 2023 Volume 4 release. Please find the package link below. The available text markups are highlight, underline, strikethrough, and squiggly.

https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.1.41
