### ISSUE TITLE
When using RawGestureDetector, an error is reported after scaling

### ISSUE THREAD

**Issue by shaonianahua** [syncfusion/flutter-widgets#1231]
I applied RawGestureDetector externally to SfPdfViewer.network
Usually, he can use click events to take effect
But if the PDF is scaled, clicking on the event will result in an error
Error content：
E/flutter (18136): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/gestures/tap.dart': Failed assertion: line 210 pos 14: '_down == null && _up == null': is not true.
E/flutter (18136): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (18136): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (18136): #2      BaseTapGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/tap.dart:210:14)
E/flutter (18136): #3      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:160:7)
E/flutter (18136): #4      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1498:18)
E/flutter (18136): #5      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3168:29)
E/flutter (18136): #6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
E/flutter (18136): #7      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:336:11)
E/flutter (18136): #8      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
E/flutter (18136): #9      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
E/flutter (18136): #10     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
E/flutter (18136): #11     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (18136): #12     _invoke1 (dart:ui/hooks.dart:164:13)
E/flutter (18136): #13     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
E/flutter (18136): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)

**Comment by deepika134** [comment]
We tried to reproduce the reported issue with provided details, but the scaling is works fine without any exception in our side. We have prepared a sample for your reference and attached the output screenshot of sample which can be downloaded from the attachment. If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.
[sample~469729.zip](https://github.com/syncfusion/flutter-widgets/files/11651510/sample.469729.zip)

**Comment by shaonianahua** [comment]
The information you provided is indeed error free, but if you click on the text section in the PDF, the click event will not execute

Only this part of our code is different


 gestures: {
                        GestureRecognizer: GestureRecognizerFactoryWithHandlers<
                            GestureRecognizer>(
                          () => GestureRecognizer(),
                          (GestureRecognizer instance) {


class GestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}

My code comes from previous answers to other issues

I don't know why I reported an error now

**Comment by deepika134** [comment]
We tried to reproduce the reported issue with provided details, but when tap on the text section **onTap()** event execute properly in our side. For your reference and attached the output screenshot of sample which can be downloaded from the attachment. kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

[Output.zip](https://github.com/syncfusion/flutter-widgets/files/11687131/Output.zip)

**Comment by shaonianahua** [comment]
Okay, I probably know my problem now. Thank you

**Comment by tpouriel** [comment]
Hello @shaonianahua,
I got the exact same issue. How did you manage to resolve it please ?

**Comment by siiimaay** [comment]
Hey @shaonianahua 
I’m also getting same error, how did you handle that part kindly please?
