### ISSUE TITLE
offline map

### ISSUE THREAD

**Issue by athiraHash** [syncfusion/flutter-widgets#1233]
I have created a mobile app using the flutter framework. The app needs to show maps in offline. Is that possible with this package

**Comment by LokeshPalani** [comment]
Currently we don’t have support to load tiles from local directory. However, we have already logged a feature request for it in our feedback portal.



We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature using the below feedback link.



Feedback link:  https://www.syncfusion.com/feedback/25542/provide-an-option-to-load-tiles-from-local-directory
