### ISSUE TITLE
Flutter Syncfusion DataGridview not Scroll on change Selected Index

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1238]
i have a Scrollable DataGridview i am updating selected index on button click by
selectedindex+=1;
dataGridController.selectedIndex  = selectedindex;

 **i want to update scroll as per selectedindex.**

Issue # 2
i have a list which is scrollable.
now i clear gridview rows by button click
          await GridDataSoruce.Endedit();
// Clear data list which is List<Map<String,dynami>>  datalist
             GridDataSoruce.datalist.clear();
// rebuild DataGridRow as per datalist
    await GridDataSoruce.DataGridRow();
// GridDataSoruce notify listner
    GridDataSoruce.notifyListeners();

**issue is scroll bar still showing after rows are clear**

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported problem has been resolved at your end. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K
