### ISSUE TITLE
Flutter Datagrid Export Stacked headers is Empty in both excel and pdf

### ISSUE THREAD

**Issue by Nidhi1396-NP** [syncfusion/flutter-widgets#1240]
I want to export datagrid with Stacked header but Stacked header show with empty. Also there is no option available to add header footer in excel . I want to Export excel with header so i try stacked header but it's show empty.

**Comment by Murtoz-h** [comment]
How did you solved it?

**Comment by Nidhi1396-NP** [comment]
directly no option available. so i did it using custom header for export and set 
exportStackedHeaders: false

**Comment by Murtoz-h** [comment]
Thanks for reply, can you send the code?

**Comment by Nidhi1396-NP** [comment]
try using example in syncfusion_flutter_pdf
[](https://pub.dev/packages/syncfusion_flutter_pdf/example)
