### ISSUE TITLE
[question] Donut chart inside another donut chart

### ISSUE THREAD

**Issue by Lorenzobettega** [syncfusion/flutter-widgets#1245]
I'm trying to do something like this using `syncfusion_flutter_charts: 21.2.5`:
![image](https://github.com/syncfusion/flutter-widgets/assets/84482292/460ae1f7-c36e-47e5-bbbc-f282c46eb329)

Is there any way to achieve the above result with the package?

If not, can the team help with an option?

Just to clarify, both charts are related

**Comment by LokeshPalani** [comment]
Hi,



You can achieve your requirement by using the [offset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/offset.html) property in the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html). This will allow you to place the legend inside the chart. We have provided a code snippet, output, and sample for your reference. Please let us know if you require any further assistance.



Code snippet:

```
SfCircularChart(
                legend: Legend(
                  isVisible: true,
                  offset: Offset(-450, -200),
                         ),
                    )
```

SB,

https://flutter.syncfusion.com/#/circular-charts/legend/legend-with-various-options



Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/f7c77285-4e1c-420e-bbcf-25e727c34bc5)



Regards,
Lokesh.


[chart_472088.zip](https://github.com/syncfusion/flutter-widgets/files/11786552/chart_472088.zip)

**Comment by Lorenzobettega** [comment]
Thanks for all, nice support :)

**Comment by Lorenzobettega** [comment]
Hi, in this sample that you invite me you solve the question about legend position, but I still missing a controller for both grapichs, for example:

When I tap this option, will hidden all the circle part, both at the first and the second graph:
![image](https://github.com/syncfusion/flutter-widgets/assets/84482292/24ac77d7-4eee-4159-aa2a-a32c09a5c395)


it's possible to do that ?

**Comment by LokeshPalani** [comment]
We have analyzed your query and would like to inform you that there is currently no option to hide the two-chart series when tapping on the [legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/legend.html) while using the [Stack](https://api.flutter.dev/flutter/widgets/Stack-class.html) widget. The user interactions will only work on the top of the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html), as this is the behavior of the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). Please let us know if you require any further assistance.

**Comment by Lorenzobettega** [comment]
I cannot render the outside grapich all time I tap the legend?

**Comment by LokeshPalani** [comment]
You can achieve your requirement by using the [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onLegendTapped.html) property and [UniqueKey](https://api.flutter.dev/flutter/foundation/UniqueKey-class.html) in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). In the [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onLegendTapped.html) property, we take the [pointIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LegendTapArgs/pointIndex.html) and check if the tapped index is zero by setting a boolean property. If the tapped index is zero, we change the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) in the first chart with the help of [UniqueKey](https://api.flutter.dev/flutter/foundation/UniqueKey-class.html) in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). We have shared a code snippet and sample for your reference. Please check and let us know if you need any further assistance.

code snippet:

```
SfCircularChart(
                onLegendTapped: (legendTapArgs) {
                  setState(() {
                   uniqueKey = UniqueKey();
                    isLegendTapped = legendTapArgs.pointIndex == 0
                        ? !isLegendTapped
                        : isLegendTapped;
                  });
                },
SfCircularChart(
                key: uniqueKey,
                series: <CircularSeries>[
                  DoughnutSeries<ChartData, String>(
                    dataSource: isLegendTapped ? chartData3 : chartData2,
              )
          ]
        )
```
[cicularchart_472088.zip](https://github.com/syncfusion/flutter-widgets/files/11885155/cicularchart_472088.zip)

**Comment by Lorenzobettega** [comment]
Thanks for all, It works.
