### ISSUE TITLE
Error removing page from pdf

### ISSUE THREAD

**Issue by nicop2000** [syncfusion/flutter-widgets#1246]
The pdf file I get from a webpage starts with a blank page, which I want to remove before writing the file, but removing a page from PdfDocument throws an exception.
I tried it like this:

`final path = Constants.filePath;

  final PdfDocument document = PdfDocument(inputBytes: response.bodyBytes);

  int count = document.pages.count; //8

  final page = document.pages[0]; //works

  document.pages.remove(page); //exception occurs here, removeAt() doesn't work either

  File file = File(path);

  file.writeAsBytesSync(document.saveSync());

  document.dispose();`

This is the exception:
Unhandled Exception: Null check operator used on a null value
#0      PdfDocumentHelper.createBookmarkDestinationDictionary (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:1370:38)
#1      PdfPageCollection._removePage (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:567:16)
#2      PdfPageCollection.remove (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:207:5)
#3      QisConnector._getDiplomaSupplementFile (package:pa_pdf_crawler/data/qis_connector.dart:137:24)
<asynchronous suspension>
#4      QisConnector.getDiplomaSupplement (package:pa_pdf_crawler/data/qis_connector.dart:156:27)
<asynchronous suspension>
#5      Functions.loadAllDocuments (package:pa_pdf_crawler/data/functions.dart:21:9)
<asynchronous suspension>
#6      _MassPrintState.build.<anonymous closure> (package:pa_pdf_crawler/presentation/mass_print.dart:116:28)
<asynchronous suspension>

Does anyone know how to solve this?

**Comment by irfanajaffer** [comment]
We were unable to reproduce the reported behavior with the provided details on our end. We suspect that the issue might be with the specific PDF document. We request you to share the input document with us, so that we can assist with you further in this.

**Comment by ammarghias** [comment]
hi 
can you tell me how you solve this problem bcz i am facing the exact same problem

**Comment by ammarghias** [comment]
and i have to solve it as soon as possible

**Comment by irfanajaffer** [comment]
The fix for the reported issue is included in our weekly release v24.1.44.
 
Kindly use the following link to refer to our latest release version,
https://pub.dev/packages/syncfusion_flutter_pdf/versions
