### ISSUE TITLE
Customization options for trackball tooltip arrow

### ISSUE THREAD

**Issue by Phantom-101** [syncfusion/flutter-widgets#125]
I customized my own tooltips but couldn't find a way to customize the arrow pointing from the tooltips to the markers. I want to do this because sometimes the arrows look pixelated. Is there a way I can turn them off or customize them?

![image](https://user-images.githubusercontent.com/63253361/105645347-c8400c00-5e4f-11eb-938e-4dff97bd0b0c.png)

**Comment by Dharanipalani** [comment]
Hi @Phantom-101,
 
Thanks for your interest in our Flutter chart widget. By default, both the trackball tooltips and trackball templates appear with arrows. If you wish to hide the arrows, you can turn off them by giving the **arrowLength** and **arrowWidth** as 0 like in the following code snippet.

`
trackballBehavior: TrackballBehavior(enable: true, tooltipSettings: InteractiveTooltip(arrowWidth: 0, arrowLength: 0)),
`
To know more details about trackball, please refer to the following help document.
[https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair#trackball](url)

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/105671226-5bd51380-5f08-11eb-8898-4c8e2e41f6d9.png)

Kindly revert us if you have any further queries.
 
Thanks,
Dharanitharan. P

**Comment by Phantom-101** [comment]
Hello @Dharanipalani 

I set both the arrow width and length to 0 but it doesn't appear to work correctly when you have multiple series:

![image](https://user-images.githubusercontent.com/63253361/105739982-8f567480-5eed-11eb-9137-de9d7e16cf0d.png)

There is a thin vertical line next to the tooltips. What can I do to disable them?

Thanks in advance.

**Comment by Dharanipalani** [comment]
Hi @Phantom - 101, 
 
You can use the **tooltipDisplayMode** property as group mode to avoid arrows like in the following code snippet. 
 
`trackballBehavior: TrackballBehavior(
enable: true, tooltipDisplayMode: TrackballDisplayMode.groupAllPoints
), 
`

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/105837614-f6ab1c00-5ff4-11eb-807f-96cd2bb6358d.png)

Please revert us if you need any further assistance.
 
Thanks,
Dharanitharan. P

**Comment by Phantom-101** [comment]
Hello @Dharanipalani 

I've already tried TrackballDisplayMode.groupAllPoints, but I'd rather not use it as there are some issues when the two series do not have the same domain. The trackball is pointing to two different x-values:

![image](https://user-images.githubusercontent.com/63253361/105876966-4f0df980-5fb4-11eb-8de9-21f5fbe2cb47.png)

I've also encountered situations where a large label will display in the center of the line instead of to the side, overlapping with the markers and trackball line. I'm not sure whether or not this is intended behavior.

![image](https://user-images.githubusercontent.com/63253361/105878060-787b5500-5fb5-11eb-8ef4-1cdcb3e10370.png)

Then I have to use either ChartAlignment.far or .near, both of which does display the tooltip to the side but also snaps it to the top or bottom, which I don't personally like.

Are the aforementioned issues bugs? If so, please fix. Thanks for all the help.

**Comment by chongbo2013** [comment]
I also encountered the problem of overlap

**Comment by Dharanipalani** [comment]
Hi @Phantom - 101,
 
To avoid the arrow for the trackball in the float mode, you can simply **borderColor** as transparent, **arrowWidth**, **arowLength** as 0 like in the following code snippet.

`trackballBehavior: TrackballBehavior(
  enable: true,  
  tooltipSettings: 
  InteractiveTooltip(
  arrowWidth: 0, arrowLength: 0, borderColor: Colors.transparent) 
), 
`

Screenshot:

![image](https://user-images.githubusercontent.com/19763272/106139477-7d95fb00-6193-11eb-8dc5-ebaab867be7f.png)

And regarding the grouping mode scenario, we can replicate this at our end. When the parent widget height is small then the trackball tooltip renders below the chart area and then the tooltip renders along the vertical line like your screenshot. This scenario will be resolved in the weekly patch release which is expected to be rolled out on 9th Feb 2021.  Please be patience until then.
 
Thanks,
Dharanitharan. P

**Comment by Phantom-101** [comment]
Hello @Dharanipalani 

Thank you very much! The borderColor fix worked.
