### ISSUE TITLE
我的项目是get_cil脚手架搭建的，安装最新版的syncfusion_flutter_charts 却运行不了，在我降低版本至20.4.54 后才能成功运行，望修复这个问题 谢谢

### ISSUE THREAD

**Issue by kangtian** [syncfusion/flutter-widgets#1251]
Error (Xcode): ../../.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-21.2.9/lib/src/common/template/rendering.dart:401:9: Error: A constant constructor can't call a non-constant super constructor.

**Comment by kangtian** [comment]
flutter:v3.66
 get: 4.6.5
  syncfusion_flutter_charts: ^21.2.10

我已经更新至最新版本，但还是会出现该问题，我的的继承自GetxController ，我只能使用20.4.54的版本才行，如果需要例子，我可以提供demo

**Comment by LokeshPalani** [comment]
Hi @kangtian,
 
As previously mentioned, the reported issue has already been fixed and rolled out in our **weekly patch release**. Therefore, we kindly request that you upgrade the **syncfusion_flutter_charts** package to the latest version.

**Version Link:**
https://pub.dev/packages/syncfusion_flutter_charts/versions/24.2.5
 
If you prefer to avoid upgrading to the latest Flutter SDK version, please let us know the current SDK version you are using. We will then suggest a compatible version of our charts package for that specific SDK version.
 
Regards,
Lokesh P.
