### ISSUE TITLE
Upgrade Dependency

### ISSUE THREAD

**Issue by parmarjitesh** [syncfusion/flutter-widgets#1253]
Kindly Upgrade to Latest Version
1) http
2) device_info_plus

**Comment by LokeshPalani** [comment]
Hi @parmarjitesh,

We have analyzed your query and will upgrade both the HTTP version and device_info_plus version in Volume 2 Main Release. We appreciate your patience until then.

Regards,
Lokesh.

**Comment by LokeshPalani** [comment]
Hi @parmarjitesh,

We are glad to announce that our Essential Studio 2023 Volume 2 release v22.1.34 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/183035/essential-studio-2023-volume-2-main-release-v22-1-34-is-available-for-download


We have upgraded the http version and rolled out in this release. So, kindly please upgrade the maps widget package version to the latest version below.

https://pub.dev/packages/syncfusion_flutter_maps/versions/22.1.34


We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.


Regards,          
Lokesh.
