### ISSUE TITLE
[syncfusion_flutter_datepicker] Flutter 3.12.0: highlighted/selected elements displaced

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#1254]
On Flutter 3.12.0, I have encountered an issue with syncfusion_flutter_datepicker: all selected/highlighted elements (e.g. selected day in a day picker, or current day in date picker) are displaced horizontally.
<img width="50%" src="https://github.com/syncfusion/flutter-widgets/assets/8345062/fbbfb21f-4a0a-4ad6-9104-3ddf39053e0a" alt="Simulator Screenshot - iPhone 14 Pro Max - 2023-06-13 at 15 05 09" />

```dart
Scaffold(
  appBar: AppBar(
    backgroundColor: Theme.of(context).colorScheme.inversePrimary,
    title: Text(widget.title),
  ),
  body: Center(
    child: SizedBox(
      width: 400,
      height: 500,
      child: SfDateRangePicker(),
    ),
  ),
);
```

This happens on a freshly created app using Flutter 3.12.0. Using `syncfusion_flutter_datepicker: 21.2.10`.
On Flutter 3.7.11 and `syncfusion_flutter_datepicker: 21.1.41` it's still working fine...

Edit: can be reproduced also exactly the same in the example app of syncfusion_flutter_datepicker.
On flutter 3.10.0 it still works fine

This commit in the Flutter framework seems to cause this bug: https://github.com/flutter/flutter/commit/62e78bf1437a4c566849ef584b66cf7c2c5f08e4
Calls to `TextPainter.layout(minWidth: cellWidth, maxWidth: cellWidth)` yielded the actual width of the text before, but yield just the `cellWidth` on Flutter versions from commit 62e78bf1437a4c566849ef584b66cf7c2c5f08e4 (i.e. version 3.12.0) on.

**Comment by rasakmubarak** [comment]
Facing same issue also on 21.2.10

**Comment by WieFel** [comment]
Updating to the newer version `22.2.10` solved it for me!
