### ISSUE TITLE
[syncfusion_flutter_pdf] how to sign a PDF from a CRT/PEM certificate file and a key without a PFX file

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#1255]
how to sign a PDF from a CRT/PEM certificate file and a key without a PFX file

**Comment by irfanajaffer** [comment]
It is not possible to sign a PDF document without private key. Please refer to the below documentation for more details:

https://help.syncfusion.com/flutter/pdf/working-with-digital-signature#externally-sign-a-pdf-document

**Comment by insinfo** [comment]
I have the private key and the certificate I just wanted to sign without having to generate the PFX files

**Comment by irfanajaffer** [comment]
Yes, we can externally sign the PDF document without the using PFX file.
 
Kindly refer the following UG link on externally signing a PDF document, https://help.syncfusion.com/flutter/pdf/working-with-digital-signature#externally-sign-a-pdf-document
