### ISSUE TITLE
[syncfusion_flutter_pdf]  how to extract PDF signature

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#1256]
how to extract PDF signature/signed data from digitally signed PDF to verify signature with OpenSSL.
like 
https://gist.github.com/trueroad/5fc2de151f717e34b250ac99fa141604

**Comment by irfanajaffer** [comment]
As of now, we do not have any immediate plans to implement this feature and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage of every release cycle, we will review all the open features and we will notify you once this support is included.

You can use the below feedback to track the status of this support:

https://www.syncfusion.com/feedback/25198/support-to-validate-the-digital-signatures-in-an-existing-pdf-document

**Comment by insinfo** [comment]
@irfanajaffer  This feature is of great value for validating signatures in PDFs.
