### ISSUE TITLE
add the possibility to add static vector SVG in a PDF

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#1257]
add the possibility to add static vector SVG in a PDF, for example draws the signature image

**Comment by irfanajaffer** [comment]
We do not have support to convert SVG to PDF document and we do not have any immediate plan to implement this in future.

**Comment by insinfo** [comment]
@irfanajaffer the implementation could be similar to pdf 3.10.8 this open source lib supports adding an SVG to a PDF
https://pub.dev/packages/pdf
