### ISSUE TITLE
Update PdfJs lib in syncfusion_flutter_pdfviewer

### ISSUE THREAD

**Issue by rodrigorafaeldamaceno** [syncfusion/flutter-widgets#1258]
Hi, I need to update PdfJs to latest version, but syncfusion_flutter_pdfviewer is not compatible, I tried with 3.4.120 version and got a internal error. Follow my Index.html script

```
<script
      src="https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.min.js"
      type="text/javascript">
</script>
```
```
    <script type="text/javascript">
      pdfjsLib.GlobalWorkerOptions.workerSrc =
        "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/build/pdf.worker.min.js";
      pdfRenderOptions = {
        // where cmaps are downloaded from
        cMapUrl: "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.4.120/cmaps/",
        // The cmaps are compressed in the case
        cMapPacked: true,
        // any other options for pdfjsLib.getDocument.
        // params: {}
      };
    </script>
```

**Comment by deepika134** [comment]
Please provide additional details about why you need to upgrade to the recent version since the Pdfjs: 2.4.456 package is works properly in PdfViewer web platform.

**Comment by ramkumarsync** [comment]
We updated the Pdfjs to the version v2.11.338 in our SfPdfViewer and this change is available from version v24,1,41.

https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.1.41
