### ISSUE TITLE
Default margins

### ISSUE THREAD

**Issue by Godfather6666** [syncfusion/flutter-widgets#126]
Hello, I want to know how to remove the default margin of the slider component, thank you very much!

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,  
  
Greetings from Syncfusion.  
  
Could you please confirm whether you are trying to remove the space which is left for rendering the overlay during interaction? If so, you may set the overlayRadius property of SfSliderThemeData to zero.  
  
https://help.syncfusion.com/flutter/slider/thumb-and-overlay#thumb-overlay-size    
  
If your requirement is different from the above kindly provide more details about your requirement or share the screenshot if possible, which will be helpful for us to provide solution earlier.  
  
Regards,  
Lakshmi R.
