### ISSUE TITLE
[syncfusion_flutter_pdfviewer], [syncfusion_flutter_charts] - Unable to install package

### ISSUE THREAD

**Issue by nizom333** [syncfusion/flutter-widgets#1261]
Because gmlogistics depends on syncfusion_flutter_pdfviewer ^21.2.10 which depends on device_info_plus ^8.1.0, device_info_plus ^8.1.0 is required.
So, because gmlogistics depends on device_info_plus ^9.0.2, version solving failed.

pubspec.yaml
`device_info_plus: ^9.0.2`

![image](https://github.com/syncfusion/flutter-widgets/assets/28598438/a09bc6d9-322b-4447-9440-7a3fa64acc99)

**Comment by sagnik-sanyal** [comment]
Same here it breaks the AWS Libraries. When can we expect this to be fixed ?

**Comment by deepika134** [comment]
In Syncfusion Flutter PdfViewer, we have upgraded device_info_plus to the latest version (9.0.2), which will be included in our upcoming Volume 2 main release. This release is expected to be rolled out at the end of June 2023. We will notify you once the release has been rolled out.
