### ISSUE TITLE
[syncfusion_flutter_charts] add an option to change the border individually for each Bar

### ISSUE THREAD

**Issue by Lorenzobettega** [syncfusion/flutter-widgets#1262]
We are tryng to create a bar series chart like this one on the image:
![image](https://github.com/syncfusion/flutter-widgets/assets/84482292/dc6ddd7b-de67-4c22-a384-482a349b761c)

But the current definition of border radius allows only to set the same radius for all the bars:

```
final bars = BarSeries<ChartSampleData, String>(
      dataSource: criargrafico(lista),
      xValueMapper: (ChartSampleData sales, _) => sales.x as String,
      yValueMapper: (ChartSampleData sales, _) => sales.y,
      sortingOrder: SortingOrder.descending,
      spacing: 0,
      width: 1,
      dataLabelSettings: const DataLabelSettings(
        isVisible: true, 
        labelAlignment: ChartDataLabelAlignment.top,
        labelPosition: ChartDataLabelPosition.inside,
      ),
      sortFieldValueMapper: (ChartSampleData sales, _) => cores.mapWithIndex((value, index) => value == sales.cor)[0],
      pointColorMapper: (ChartSampleData sales, _) => sales.cor,
      borderRadius: BorderRadius.all(Radius.circular(5))
    );
```

resulting in this view:

![image](https://github.com/syncfusion/flutter-widgets/assets/84482292/b4269459-362b-4839-9dcc-706150f830bc)

Is it possible to have the first image result or this will need to be added to the package?

**Comment by sfHariHaraSudhan** [comment]
Hi,

To customize each segment, we can create the renderer for the specific series using the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback. Here, we create a _Custom[BarSeriesRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSeriesRenderer-class.html) which extends from the BarSeriesRenderer where we create a _BarCustomPainter for _CustomBarSeriesRenderer. _BarCustomPainter is each individual segment which is extended from the [BarSegment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSegment-class.html).

In the _BarCustomPainter, we can access the [currentSegmentIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSegment/currentSegmentIndex.html) by overriding from the [BarSegment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSegment-class.html) and we render the bar segment in the [onPaint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSegment/onPaint.html) method by overriding it. With the help of the [currentSegmentIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSegment/currentSegmentIndex.html) and the [segmentRect](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSegment/segmentRect.html) property, we can customize the segment with border radius as we needed.

Snapshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/8ee3423d-6ad2-42fc-bb52-fceeb2407fce)

Kindly refer the code snippet below:
```
class _CustomBarSeriesRenderer extends BarSeriesRenderer {
  _CustomBarSeriesRenderer();
 
  @override
  BarSegment createSegment() {
    return _BarCustomPainter();
  }
}
 
class _BarCustomPainter extends BarSegment {
  _BarCustomPainter();
 
  @override
  int get currentSegmentIndex => super.currentSegmentIndex!;
 
  @override
  void onPaint(Canvas canvas) {
    if (currentSegmentIndex == 0) {
      segmentRect = RRect.fromRectAndCorners(
        segmentRect.safeInnerRect,
        topRight: const Radius.circular(15),
        topLeft: const Radius.circular(15),
      );
    } else {
      segmentRect = RRect.fromRectAndCorners(
        segmentRect.safeInnerRect,
        bottomRight: const Radius.circular(15),
      );
    }
    super.onPaint(canvas);
  }
}
```

Also shared the sample below for your reference.

Regards,
Hari Hara Sudhan. K

[474656.zip](https://github.com/syncfusion/flutter-widgets/files/11796076/474656.zip)

**Comment by Lorenzobettega** [comment]
Thanks for all, nice suport.
