### ISSUE TITLE
[syncfusion_flutter_charts] Null check operator used on a null value in CircularArea._performPointerMove method.

### ISSUE THREAD

**Issue by rabismail** [syncfusion/flutter-widgets#1263]
I keep getting this crashes multiple times from production... unfortunately logs are not enough to say more or when/where/how it happens.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at RenderObject.getTransformTo(object.dart:2921)
       at RenderBox.globalToLocal(box.dart:2637)
       at CircularArea._performPointerMove(circular_area.dart:149)
       at CircularArea.build.<fn>.<fn>(circular_area.dart:79)
       at RenderPointerListener.handleEvent(proxy_box.dart:3166)
       at GestureBinding.dispatchEvent(binding.dart:440)
       at RendererBinding.dispatchEvent(binding.dart:334)
       at GestureBinding._handlePointerEventImmediately(binding.dart:395)
       at GestureBinding.handlePointerEvent(binding.dart:357)
       at GestureBinding._flushPointerEventQueue(binding.dart:314)
       at GestureBinding._handlePointerDataPacket(binding.dart:295)
```

I'm using this version...[but I got this error in the previous versions as well]
**syncfusion_flutter_charts: 20.3.59**

Could you please check it? what could it be related to?

**Comment by rabismail** [comment]
Unfortunately I wasn't able to reproduce it as well even with my codes, all crash reports comes from production

**66 crash** events affecting **10 users** only in one app. [I have also other apps which gives the same issue]

![image](https://github.com/syncfusion/flutter-widgets/assets/125277581/d8bdb8cc-230e-4f4b-b5fc-3c7afd908001)

<br>
<br>

This is how much unique crash reports I got, they are repeating...

<img width="1561" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/125277581/075d7a68-c9ef-407e-abb6-bef3bee18fb8">

<br>
<br>

It could happen when we interact with the chart, mainly click, long click...

Could you please recheck it?

**Comment by LokeshPalani** [comment]
We have checked the provided callstack and chart interaction methods, but we are not able to reproduce the reported issue since we are unsure of the exact scenario in which it is occurring. Therefore, we kindly request that you attempt to replicate the issue in the test sample attached below and notify us of the results so that we can better assist you.

[taking_datas_from_online.zip](https://github.com/syncfusion/flutter-widgets/files/11866229/taking_datas_from_online.zip)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.

**Comment by onewOne** [comment]
I've encountered it too, it's an occasional bug, please help to solve it.
