### ISSUE TITLE
DataGrid async filtering example

### ISSUE THREAD

**Issue by fehernyul** [syncfusion/flutter-widgets#1265]
Hi,

Have you an example flutter project to the following case?
- use SfDataGrid (and SfDataPager)
- the user clicks on the filter UI, but the actual filtering is not done within the existing data source, but a remote async (http) call must have to run again, passing the all the existing filters to that. Also, onFilterChanging event should work to prevent unwanted filters.

Regards,
Gabor

**Comment by francois-robert** [comment]
Hi @fehernyul,

Have you found an example for this ?
