### ISSUE TITLE
Rounded Borders on the Gauge Chart

### ISSUE THREAD

**Issue by gpigatto** [syncfusion/flutter-widgets#1266]
Hello SyncFusion Team!

I'm working on a Gauge Chart and the only thing missing to fully complete the design as intended is a cornerStyle on the GaugeRange, there is a workaround to it?

<img width="386" alt="image" src="https://github.com/syncfusion/flutter-examples/assets/12770899/de8959cf-e59f-42b1-9c03-53ed4c4d7735">

**Comment by LokeshPalani** [comment]
Hi @gpigatto,

You can achieve your requirement by using the [startAngle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/startAngle.html) and [endAngle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/endAngle.html) property in the [RadialAxis](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis-class.html) widget within the [axes](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfRadialGauge/axes.html) Property. We have used multiple [RadialAxis](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis-class.html) widget and changed the [startAngle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/startAngle.html) and [endAngle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/endAngle.html) to render the [cornerStyle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RangePointer/cornerStyle.html) in the [RangePointer](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RangePointer-class.html) widget within the [pointers](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/pointers.html) property. We have provided a sample for your reference. You can modify the sample based on your use case. Please let us know if you need any further assistance.

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/06753e45-ab18-4ccb-a77f-77d3da38bac6)


Regards,
Lokesh.

[gauge_475379.zip](https://github.com/syncfusion/flutter-widgets/files/11815878/gauge_475379.zip)

**Comment by gpigatto** [comment]
Thanks for the help, worked here!

**Comment by gpigatto** [comment]
Thanks for the help, worked here!
