### ISSUE TITLE
DataGrid - SfDataPager - availableRowsPerPage initial value

### ISSUE THREAD

**Issue by fehernyul** [syncfusion/flutter-widgets#1267]
Hi,
Can I do that, if my pager's availableRowsPerPage == const <int>[2, 5, 10, 20, 50],
but I want to the initial rowsPerPage be equals 10.

Thanks,
Gabor

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @fehernyul,

The DataGrid in Flutter automatically splits the rows required for each page based on the **SfDataPager.pageCount** property. This property is calculated by dividing the total number of rows by the page count. However, if you want to maintain a specific number of rows for each page at initial loading, you can utilize the **[SfDataGrid.rowsPerPage](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/rowsPerPage.html)** property.

To achieve your requirement, you need to set the desired number of rows per page by updating the value of the **SfDataGrid.rowsPerPage** property. Additionally, you should handle the scenario when the rows per page value is changed by updating the property accordingly.

Here is a code snippet that demonstrates how to set and update the rows per page in the SfDataGrid:

```dart
  int _rowsPerPage = 10;

  @override
  void initState() {
    super.initState();
    _employees = populateData();
    _employeeDataSource = EmployeeDataSource(employees: _employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PageNavigation Demo'),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return Column(
            children: [
              SizedBox(
                  height: constraints.maxHeight - 60,
                  width: constraints.maxWidth,
                  child: SfDataGrid(
                      rowsPerPage: _rowsPerPage,   // Set rows per page count here
                      source: _employeeDataSource,
                      columnWidthMode: ColumnWidthMode.fill,
                      columns: getColumns)),
              SizedBox(
                height: 60,
                width: constraints.maxWidth,
                child: SfDataPager(
                  pageCount: (_employees.length / _rowsPerPage).ceilToDouble(),
                  availableRowsPerPage: const [2, 5, 10, 15],
                  onRowsPerPageChanged: (int? rowsPerPage) {
                    setState(() {
                      _rowsPerPage = rowsPerPage!;  // Update the rows per page count when value changes
                      _employeeDataSource.updateDataGriDataSource();  // call notify li
                    });
                  },
                  delegate: _employeeDataSource,
                ),
              )
            ],
          );
        },
      ),
    );
  }

```
**In EmployeeDataSource class:**

```dart
class EmployeeDataSource extends DataGridSource {

...

  void updateDataGriDataSource() {
    notifyListeners();
  }
}
```

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
@fehernyul,

According to the current implementation of the DataPager, the initial value displayed will be the first value in the **SfDataPager.availableRowsPerPage** list. If you want to show "10" as the initial value, you can achieve this by reordering the values in the **availableRowsPerPage** list as **[10, 2, 5, 15]**.

**Comment by fehernyul** [comment]
Thank you for your answer!
