### ISSUE TITLE
How to get pdf form field by name?

### ISSUE THREAD

**Issue by Ri-car-do-1989** [syncfusion/flutter-widgets#1271]
Documentation says a pdf form field can be gotten by index or name, but all examples show only getting it with index.

I tried changing: 
fields[0] 

To:
fields["name"]

But it doesn't work. Also, in PdfFormFieldCollectionHelper there is a method called "getFieldIndex(String name)" which, supposedly, I would be able to use to get the index using the field name, but that method is not called anywhere in the lib and I can't seem to be able to call it.

So, taking for example, these lines of code:

final PdfDocument document = PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());
PdfFormFieldCollection fields = document.form.fields;

How do I get a field called "field1" and change its value?

**Comment by irfanajaffer** [comment]
<html>
<body>
<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(45, 55, 72); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box;"><span class="ui-provider fz b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr" style="box-sizing: border-box;">As of now, we have not support to retrieve the form fields by name, We will modify the UG documentation. However, we can achieve this by using the following code to get the field by name in the sample level.</span></span></p>


![image](https://github.com/syncfusion/flutter-widgets/assets/93319208/d46e7c83-928d-4463-8753-22a62f00fa1d)


<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(45, 55, 72); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgb(45, 55, 72); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Please try this on your end and let us know the result.</p>
</body>
</html>

**Comment by Ri-car-do-1989** [comment]
Yes, I've done something similar and it does work. I just read in the documentation that getting fields by name was possible, and I wanted that to write better code that used what the lib already offered. And when I saw the "getFieldIndex(String name)" function I really thought there was some way to do that.

But thanks for the answer. I'll close this as the answer does work.
