### ISSUE TITLE
Limit thumb position to slider size

### ISSUE THREAD

**Issue by guyluz11** [syncfusion/flutter-widgets#1276]
When using the slider I see that the thumb is getting out of the slider bounds 
![image](https://github.com/syncfusion/flutter-widgets/assets/9304740/2f19f2a1-7c9f-421c-8acd-18b784292c3d)

Here is another example using the regular sliders
The left side is the max, the middle is what I want to be the max, and the right side is a little bit below the end of the track so that we can compare the ending.
![image](https://github.com/syncfusion/flutter-widgets/assets/9304740/36a654cd-2656-4cc9-8fe0-a9c26892eb44)

How can I set the max position of the thumb so that it will not get out of the track

**Comment by sfHariHaraSudhan** [comment]
Hi @guyluz11,

In [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html), we can customize the thumb and track using the [SfThumbShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfThumbShape-class.html) and [SfTrackShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfTrackShape-class.html) where we can access the size of the thumb and track. While dragging the slider, in the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/onChanged.html) callback, we can check whether the size of the thumb is lesser than the width of the track. If the thumb exceeds the size of the track width, then we can be able to restrict the values been changed. Hence the slider will not move further the track width. 

Also, we can achieve this use case by checking whether the [start](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues/start.html) or [end](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues/end.html) property in the [SfRangeValues](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues-class.html) exceeds the [maximum](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/max.html) property or we can declare the required limit in default. 

Kindly refer the code snippet below:
```
class _MyAppState extends State<MyApp> {
  final double _min = 0.0;
  final double _max = 10.0;
  num limitValue = 0.50;
  SfRangeValues _values = const SfRangeValues(2.0, 6.0);

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfRangeSlider(
          min: _min,
          max: _max,
          values: _values,
          showLabels: true,
          interval: 1,
          showDividers: true,
          showTicks: true,
          enableTooltip: true,
          onChanged: (SfRangeValues newValues) {
            if (_values.end < (_max - limitValue)) {
              setState(() {
                _values = newValues;
              });
            }
          },
        ),
      ),
    );
  }
}
```

Snapshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/4cc1385a-100c-4ec7-9945-a744966a811b)

If you have any further queries, please get back to us.

Regards,
Hari Hara Sudhan. K

**Comment by guyluz11** [comment]
Thanks @sfHariHaraSudhan :D
