### ISSUE TITLE
[syncfusion_flutter_charts] Doughnut Chart change selection ui Question

### ISSUE THREAD

**Issue by OlehMysak** [syncfusion/flutter-widgets#1277]
<img width="251" alt="Screenshot 2023-06-26 at 15 25 31" src="https://github.com/syncfusion/flutter-widgets/assets/110994808/fe50a652-45e3-4e53-9c75-0bc435dc8a16">

is it possible to somehow make the selected element not move away, but become bigger? Like on photo

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your query and we already have a KB for increasing the tapped segment size in the circular series. To achieve your requirement please refer to the following shared KB, it will help you to achieve your requirement.

KB, https://support.syncfusion.com/kb/article/11342/how-to-increase-the-size-of-the-tapped-segment-in-the-pie-chart-sfcircularchart

If you have any further queries please get back to us.

**Comment by OlehMysak** [comment]
And is it possible to somehow change the inner radius of the element? or move element slightly to the middle when clicked

**Comment by sfHariHaraSudhan** [comment]
Hi @OlehMysak,

In [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html), we can be able to change the inner radius of the doughnut series using the [innerRadius](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/innerRadius.html) property for all the segments commonly. However, it is not possible to change the inner radius of the selected segment or to move the selected segment to the middle in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). 

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K

**Comment by OlehMysak** [comment]
Hi @sfHariHaraSudhan, I have last question, is it possible to make the selected element to be on top of all the others because now it is only on top of the previous one but not the next one. And is it possible to change the radius, because if the element has a small value, then defects appear. Attach photos for example. 
![2023-07-06 13 14 38](https://github.com/syncfusion/flutter-widgets/assets/110994808/a46a9111-ea99-4532-8043-fac63169b83b)
![2023-07-06 13 14 47](https://github.com/syncfusion/flutter-widgets/assets/110994808/b22eeb3f-b16f-4127-9a14-bb413f414a17)

**Comment by sfHariHaraSudhan** [comment]
Hi @OlehMysak,

We would like to inform you that the mentioned requirement cannot be achieved using the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html). However, we recommend you use the [explode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/explode.html) property, where the selected segment will be exploded individually. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
