### ISSUE TITLE
audio video tracks 

### ISSUE THREAD

**Issue by rectrick** [syncfusion/flutter-widgets#1283]
i can use charts to provide audio video tracks data ? see example https://pub.dev/packages/timeline_editor

**Comment by sfHariHaraSudhan** [comment]
Hi @rectrick,

In the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), currently it is not possible to provide the audio video tracks data as mentioned in the sample video using the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K
