### ISSUE TITLE
Bugs in the selection box

### ISSUE THREAD

**Issue by han1548772930** [syncfusion/flutter-widgets#1284]
After I choose something I execute buildDataGridRows and updateDataGridSource
The selection box at the head is still checked
Similar to this
![微信截图_20230701164453](https://github.com/syncfusion/flutter-widgets/assets/83765419/0e85f45e-5e5c-48d2-8adb-8caa3e12e5a2)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @han1548772930,

We have investigated your query and successfully replicated the reported issue on our end. We have identified it as a bug and have logged a report in our feedback portal. The issue will be addressed, and the necessary changes will be included in the upcoming weekly patch release scheduled for July 18, 2023. 

In the meantime, you can temporarily resolve this issue at the sample level by utilizing the DataGridController. By setting the **DataGridController.selectedIndex** to **-1**, you can reset the state of the header cell checkbox.  Please check the following code snippet for more information.

```dart
  DataGridController dataGridController = DataGridController();

  @override
  void initState() {
    super.initState();
    _employees = populateData();
    _employeeDataSource = EmployeeDataSource();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: Column(
        children: [
          Container(
            margin: const EdgeInsets.symmetric(vertical: 20),
            width: 200,
            child: ElevatedButton(
                onPressed: () {
                  dataGridController.selectedIndex = -1;
                  _employeeDataSource.buildDataGridRows();
                  _employeeDataSource.updateDataGridSource();
                },
                child: const Text('Build Rows')),
          ),
          SfDataGrid(
            source: _employeeDataSource,
            columns: getColumns,
            controller: dataGridController,
            selectionMode: SelectionMode.multiple,
            showCheckboxColumn: true,
            columnWidthMode: ColumnWidthMode.fill,
          ),
        ],
      ),
    );
  }

```

Regards,
Tamilarasan

**Comment by han1548772930** [comment]
> 你好@han1548772930,
> 
> 我们已调查您的查询并成功复制了所报告的问题。我们已将其识别为错误，并在我们的反馈门户中记录了报告。该问题将得到解决，必要的更改将包含在计划于 2023 年 7 月 18 日发布的每周补丁中。
> 
> 同时，您可以利用 DataGridController 在示例级别临时解决此问题。通过将**DataGridController.selectedIndex**设置为**-1**，您可以重置标题单元格复选框的状态。请检查以下代码片段以获取更多信息。
> 
> ```dart
>   DataGridController dataGridController = DataGridController();
> 
>   @override
>   void initState() {
>     super.initState();
>     _employees = populateData();
>     _employeeDataSource = EmployeeDataSource();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
>       body: Column(
>         children: [
>           Container(
>             margin: const EdgeInsets.symmetric(vertical: 20),
>             width: 200,
>             child: ElevatedButton(
>                 onPressed: () {
>                   dataGridController.selectedIndex = -1;
>                   _employeeDataSource.buildDataGridRows();
>                   _employeeDataSource.updateDataGridSource();
>                 },
>                 child: const Text('Build Rows')),
>           ),
>           SfDataGrid(
>             source: _employeeDataSource,
>             columns: getColumns,
>             controller: dataGridController,
>             selectionMode: SelectionMode.multiple,
>             showCheckboxColumn: true,
>             columnWidthMode: ColumnWidthMode.fill,
>           ),
>         ],
>       ),
>     );
>   }
> ```
> 
> 问候， 塔米拉桑

Thanks.

**Comment by han1548772930** [comment]
> Hi @han1548772930,
> 
> We have investigated your query and successfully replicated the reported issue on our end. We have identified it as a bug and have logged a report in our feedback portal. The issue will be addressed, and the necessary changes will be included in the upcoming weekly patch release scheduled for July 18, 2023.
> 
> In the meantime, you can temporarily resolve this issue at the sample level by utilizing the DataGridController. By setting the **DataGridController.selectedIndex** to **-1**, you can reset the state of the header cell checkbox. Please check the following code snippet for more information.
> 
> ```dart
>   DataGridController dataGridController = DataGridController();
> 
>   @override
>   void initState() {
>     super.initState();
>     _employees = populateData();
>     _employeeDataSource = EmployeeDataSource();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
>       body: Column(
>         children: [
>           Container(
>             margin: const EdgeInsets.symmetric(vertical: 20),
>             width: 200,
>             child: ElevatedButton(
>                 onPressed: () {
>                   dataGridController.selectedIndex = -1;
>                   _employeeDataSource.buildDataGridRows();
>                   _employeeDataSource.updateDataGridSource();
>                 },
>                 child: const Text('Build Rows')),
>           ),
>           SfDataGrid(
>             source: _employeeDataSource,
>             columns: getColumns,
>             controller: dataGridController,
>             selectionMode: SelectionMode.multiple,
>             showCheckboxColumn: true,
>             columnWidthMode: ColumnWidthMode.fill,
>           ),
>         ],
>       ),
>     );
>   }
> ```
> 
> Regards, Tamilarasan

Thanks
