### ISSUE TITLE
How to connect two existing points to form a new line?

### ISSUE THREAD

**Issue by linhlc-agiletech** [syncfusion/flutter-widgets#1285]
https://github.com/syncfusion/flutter-widgets/assets/135201039/0aca3f0d-53ab-43d9-ad9c-ac0719242ca0

Like title say, I need to connect two existing points to draw a new dotted line in the video. I'm using LineSeries in the chart. I use onPointLongPress to get first point's data but I don't know how to get data for second point.

I read the examples of range slider but I didn't see any one like this. Can anyone help me with the solution?

**Comment by sfHariHaraSudhan** [comment]
Hi @linhlc-agiletech,

We have analyzed your query and we can be able to achieve the expected output using the [CartesianChartAnnotation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation-class.html) widget in the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property. However, we need some time to investigate and to work on the workaround sample and will update the further details in two business days on July 07, 2023. We appreciate your patience until then.

Regards,
Hari Hara Sudhan. K

**Comment by le-liam-realestateanalytics** [comment]
Hi @sfHariHaraSudhan,

Thank you for responding. Please take your time.

**Comment by linhlc-agiletech** [comment]
Hi @sfHariHaraSudhan,

Are there any news about workaround sample?

**Comment by sfHariHaraSudhan** [comment]
Hi @linhlc-agiletech,

Sorry for the delay. We're currently trying to create a sample workaround to meet the stated requirement by using the onChartTouchInteractionUp and onChartTouchInteractionDown callbacks. However, we've experienced issues in getting the desired result from the onChartTouchInteractionUp callback. Therefore, we're considering the use of the onPointTap callback within each series to provide the most efficient solution on our part. We will provide further details within one business day, on July 11, 2023. We appreciate your patience until then.

Regards,
Hari Hara Sudhan. K

**Comment by linhlc-agiletech** [comment]
Hi @sfHariHaraSudhan 

It's been a week, have you make any progress on the workaround sample?

**Comment by sfHariHaraSudhan** [comment]
Hi @linhlc-agiletech,

Sorry for the delay, we have analyzed your query and we suspect that you need to render the line between the two points while dragging from the first current point to the second target point. In [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), we do not have direct support to tap and drag between the two series points. However, we have implemented a simple workaround sample to render the dashed line while tapped on the first current point and the second current point.

We have achieved the expected output using the public method [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) using [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html) and [onDataLabelTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onDataLabelTapped.html) callback. Here when we click on the two data labels for which the line should be rendered between two points, the selected data points will be updated using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method and the dashed [line series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) will be rendered with the help of CustomLineSeriesRenderer using the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback.

Modify the attached sample below based on your requirement to achieve the expected output.

Kindly refer the code snippet below:
```
class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> firstData;
  late List<ChartSampleData> secondData;
  List<ChartSampleData> targetData = [];
  late ChartSeriesController _controller;
  int count = 0;
 
  @override
  void initState() {
    firstData = [
      ChartSampleData(01, 05),
      ChartSampleData(02, 10),
      ChartSampleData(03, 07),
      ChartSampleData(04, 02),
      ChartSampleData(05, 09),
      ChartSampleData(06, 01),
      ChartSampleData(07, 04),
      ChartSampleData(08, 06),
      ChartSampleData(09, 08),
      ChartSampleData(10, 03),
    ];
    secondData = [
      ChartSampleData(01, 15),
      ChartSampleData(02, 20),
      ChartSampleData(03, 17),
      ChartSampleData(04, 12),
      ChartSampleData(05, 19),
      ChartSampleData(06, 11),
      ChartSampleData(07, 14),
      ChartSampleData(08, 16),
      ChartSampleData(09, 18),
      ChartSampleData(10, 13),
    ];
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        onDataLabelTapped: (onTapArgs) {
          count++;
          if (onTapArgs.seriesIndex == 0) {
            targetData.add(firstData[onTapArgs.pointIndex]);
          } else if (onTapArgs.seriesIndex == 1) {
            targetData.add(secondData[onTapArgs.pointIndex]);
          }
          if (count == 2) {
            count = 0;
            _controller.updateDataSource(addedDataIndexes: [
              targetData.length - 2,
              targetData.length - 1
            ]);
          }
        },
        primaryXAxis: NumericAxis(),
        primaryYAxis: NumericAxis(),
        series: <CartesianSeries<ChartSampleData, num>>[
          LineSeries(
            dataSource: firstData,
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            yValueMapper: (ChartSampleData sales, int index) => sales.y,
            color: Colors.blue,
            dataLabelSettings: DataLabelSettings(
              isVisible: true,
              labelAlignment: ChartDataLabelAlignment.middle,
              builder: (data, point, series, pointIndex, seriesIndex) {
                return Container(
                  height: 10,
                  width: 10,
                  decoration: const BoxDecoration(
                    shape: BoxShape.circle,
                    color: Colors.green,
                  ),
                );
              },
            ),
          ),
          LineSeries(
            dataSource: secondData,
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            yValueMapper: (ChartSampleData sales, int index) => sales.y,
            color: Colors.red,
            dataLabelSettings: DataLabelSettings(
              isVisible: true,
              labelAlignment: ChartDataLabelAlignment.middle,
              builder: (data, point, series, pointIndex, seriesIndex) {
                return Container(
                  height: 10,
                  width: 10,
                  decoration: const BoxDecoration(
                    shape: BoxShape.circle,
                    color: Colors.yellow,
                  ),
                );
              },
            ),
          ),
          LineSeries(
            dataSource: targetData,
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            yValueMapper: (ChartSampleData sales, int index) => sales.y,
            color: Colors.orange,
            onRendererCreated: (controller) {
              _controller = controller;
            },
            onCreateRenderer: (series) {
              return CustomLineSeriesRenderer();
            },
            dashArray: const [5, 5],
          ),
        ],
      ),
    );
  }
 
  @override
  void dispose() {
    targetData.clear();
    firstData.clear();
    secondData.clear();
    super.dispose();
  }
}
 
class CustomLineSeriesRenderer extends LineSeriesRenderer {
  @override
  LineSegment createSegment() {
    return CustomLineSegment();
  }
}
 
class CustomLineSegment extends LineSegment {
  @override
  void onPaint(Canvas canvas) {
    if (currentSegmentIndex! % 2 == 0) {
      super.onPaint(canvas);
    }
  }
}
```

Also attached the recording below for your reference. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

[478729.zip](https://github.com/syncfusion/flutter-widgets/files/12066349/478729.zip)
[_478729.zip](https://github.com/syncfusion/flutter-widgets/files/12066350/_478729.zip)
