### ISSUE TITLE
[syncfusion_flutter_pdfviewer] zoomLevel < 1

### ISSUE THREAD

**Issue by juliaen-dr** [syncfusion/flutter-widgets#1288]
Hello everybody,

I would like to ask if there is a possibility to zoom below zoomLevel = 1. Use case is, that I want to display the whole pdf page on a small screen, which is not possible with a zoomLevel = 1.

**Comment by juliaen-dr** [comment]
Found out, that I just needed to change the pagelayout to single

**Comment by deepika134** [comment]
The support for setting the minimum zoom level will allow you to zoom in beyond the default zoom level, which is less than the screen width. Currently, we do not have support to set the minimum zoom level in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.

https://www.syncfusion.com/feedback/26648/support-to-set-minimum-and-maximum-zoom-level
