### ISSUE TITLE
How do I use the same name field for LineSeries

### ISSUE THREAD

**Issue by ahmtydn** [syncfusion/flutter-widgets#1290]
https://github.com/syncfusion/flutter-widgets/assets/84200491/9c1b2faa-39d7-4e9a-9265-3787a3600199

```
LineSeries<_ChartData, DateTime>(
          animationDuration: 2500,
          dataSource: chartData,
          name: "test",
          width: 2,
          markerSettings: const MarkerSettings(
            isVisible: true,
          ),
        )
        
```
   Filtering does not work properly when the name field is the same in LineSeries. Is there a way to assign a different key for this or to solve the problem in the video in a different way?

**Comment by sfHariHaraSudhan** [comment]
Hi @ahmtydn, 
 
We are able to replicate the reported issue regarding **Legend-toggling-is-not-working-properly-when-same-name-is-given-to-all-the-series** at our end and have logged bug report for it in our feedback portal. We will fix and include the changes in our SP release which will be rolled out at the end of July. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.
 
Feedback Link: https://www.syncfusion.com/feedback/45141.
 
Regards,
Hari Hara Sudhan. K.

**Comment by ahmtydn** [comment]
Hi  @sfHariHaraSudhan 

Can you give an exact date?

Thanks.

**Comment by sfHariHaraSudhan** [comment]
Hi @ahmtydn,

The SP release will be rolled out by today. We will update you here once the SP is released and will share further details within one business day on July 28, 2023. We appreciate your patience until then.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @ahmtydn,

The reported issue regarding **Legend toggling is not working properly when same name is given to all the series** has been fixed and rolled out in our SP release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.2.5

Regards,
Hari Hara Sudhan. K.

**Comment by ahmtydn** [comment]
I thank you and your development team. Happy development.
