### ISSUE TITLE
call stack running issue

### ISSUE THREAD

**Issue by nurullahturkoglu** [syncfusion/flutter-widgets#1292]
Whenever I try to generate multiple PDF's page, it gets stuck when the call stack is operating. It doesn't give an error and the memory keeps inflating. I have debugged many times to find out the source of the problem. It gets stuck and inflates the memory in the contentElement.draw() function, without throwing any error. Has anyone else encountered this?
![call stack](https://github.com/syncfusion/flutter-widgets/assets/73299153/b34fa11d-0ab3-4918-8067-47ce30cf4daa)

**Comment by irfanajaffer** [comment]
We request you to share additonal details like code snippet and sample document to analyze further on this. so that we can assist with you further in this.
