### ISSUE TITLE
showValue to add text at the top

### ISSUE THREAD

**Issue by andre-ab** [syncfusion/flutter-widgets#1293]
showValue to add text at the top??
see:

SfBarcodeGenerator SfBarcodeGenerator({
  Key? key,
  required String? value,
  Symbology? symbology,
  Color? barColor,
  Color? backgroundColor,
  bool showValue = false,
  double textSpacing = 2,
  TextAlign textAlign = TextAlign.center,
  TextStyle? textStyle,
**//here bottom or top, default bottom
alingText = bottom**
}) 

 **// alingText:bottom**
![image](https://github.com/syncfusion/flutter-widgets/assets/10952239/fb13fab2-78d1-47b9-b834-746ac7d11fee)

**alingText:top**
![image](https://github.com/syncfusion/flutter-widgets/assets/10952239/4381b807-42af-4ba9-9b2c-c67cf7207e4e)

**Comment by sfHariHaraSudhan** [comment]
Hi @andre-ab,

We would like to let you know that currently, we don’t have support for Provide-support-for-displaying-text-on-top-of-the-barcode. However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback Link: [https://www.syncfusion.com/feedback/45136](https://www.syncfusion.com/feedback/45136/provide-support-for-displaying-text-on-top-of-the-barcode).

Regards,
Hari Hara Sudhan. K
