### ISSUE TITLE
[syncfusion_flutter_charts] How to get relative position in the chart

### ISSUE THREAD

**Issue by nvtphong200401** [syncfusion/flutter-widgets#1299]
Currently, I am using the chart like this

             
```
               SfCartesianChart(
                borderColor: Colors.red,
                primaryXAxis: NumericAxis(maximum: 0.75, interval: 0.1),
                primaryYAxis: NumericAxis(maximum: 0.85),
                onChartTouchInteractionUp: (tapArgs) {
                  print(tapArgs.position.dx);
                  print(tapArgs.position.dy);
                },
```

Whenever I tap into the chart, it shows the offset position based on the size of the chart and the origin is on the top left corner which is not what I want.

How can I get the relative position based on the XAxis and YAxis that I have defined ? Thanks in advance.

**Comment by sfHariHaraSudhan** [comment]
Hi @nvtphong200401,

We have analyzed your query and your requirement can be achieved using the public method [pixelToPoint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pixelToPoint.html) with the help of [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html).

We have attached the Sample Browser link below for your reference and in that sample, we are rendering a new line segment by adding the data point to the [line series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) when we tap on the chart area. Here, we have used the [onChartTouchInteractionUp](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onChartTouchInteractionUp.html) callback to access the current position while tapped and converted the current position to the relative position using the [pixelToPoint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pixelToPoint.html) method with the help of [ChartSeriesController](https://support.syncfusion.com/agent/ChartSeriesController). We add the relative position to the [data source](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataSource.html) of the [line series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) and thus when we tap on the chart area, the new line segment will be rendered based on the relative position.

SB: https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/add-a-point-on-click.

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by nvtphong200401** [comment]
Thank you @sfHariHaraSudhan but if I do not use any series so that I cannot assign to get the `ChartSeriesController` as in the example. What is the solution for this ? Thank you

**Comment by sfHariHaraSudhan** [comment]
Hi @nvtphong200401,

There is no other way to obtain a [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html) without a series. Therefore, we recommend adding a series and then hiding it by utilizing the [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) property of the series if you do not wish to display it.

Regards,
Hari Hara Sudhan. K

**Comment by nvtphong200401** [comment]
Thank you for your response!
