### ISSUE TITLE
[syncfusion_flutter_datagrid] Scroll to specific row/column programmatically 

### ISSUE THREAD

**Issue by szymonmazanik** [syncfusion/flutter-widgets#130]
Hello 
Is there possibility to scroll to picked row or column from within the code? 

I can't find any `scrollToRow` or `scrollToColumn` or `scrollController` property in SfDataGrid.

I'm processing a lot of data in my app and I need to save the scroll position user is on and then restore it once he relaunches the app.

I also found out that Xamarin has this feature: https://www.syncfusion.com/kb/7162/how-to-scroll-to-a-specific-row-column-programmatically-in-sfdatagrid

**Comment by BalasubramaniSundaram** [comment]
Hi  @szymonmazanik,

Greeting from Syncufusion,

We have considered your request. We have logged the feature request and this feature will be included in any of our upcoming release and we will share the feature details link by 5th feb 2020. We appreciate your patience until then.

regards, 
Balasubramani Sundaram.

**Comment by BalasubramaniSundaram** [comment]
HI @szymonmazanik, 

  You can follow the feature details from the below link. As we mentioned earlier this feature will include in any of our upcoming release and we appreciate your patience until then.

Feature link: https://www.syncfusion.com/feedback/22088/support-to-programmatic-scrolling

Regards, 
Balasubramani Sundaram.

**Comment by szymonmazanik** [comment]
Thanks a lot @BalasubramaniSundaram 

Please also keep in mind that there should be an option to read the current vertical and horizontal scroll position in order to solve my use case. 
That's probably worth adding in the suncfusion feedback ticket. 

Thank you for support,
Szymon

**Comment by BalasubramaniSundaram** [comment]
Hi @szymonmazanik ,
 
Thanks for your feedback and showing interest.
 
We have consider your requirement and we planned to maintain the API of **vertialScrollOffset** and **horizontalScrollOffset** as read-only property in our SfDataGrid.controller and also we are going to introduce the programmatic scrolling API **scrollToVerticalOffset()** and **scrollToHorizontalOffset()** methods.
 
You can save the horizontal and vertical offsets using those properties and pass the saved vertical and horizontal offsets to those methods respectively on launching the app.
 
Example
 
```
  final DataGridController _dataGridController = DataGridController();
 
   SfDataGrid(
    controller: _dataGridController,
   )
 
```
 
Using
 
`_dataGridController.scrollToVerticalOffset(vertialOffset);`
 
 
Regards,
Balasubramani Sundaram.
