### ISSUE TITLE
How to select/unselect data points programmatically in SfCircularChart?

### ISSUE THREAD

**Issue by MuhammedRefaat** [syncfusion/flutter-widgets#1302]
I'm using SfCircularChart with DoughnutSeries, and I want to be able to programmatically select/unselect data points as per certain user actions, but nothing is working with me since the selectionBehavior doesn't have a proper controller to do so, and what is named `selectionController` there is just a `RangeController` which is not helping a lot, here is my implementation for reference:
             
              SfCircularChart(
                    enableMultiSelection: false,
                    series: <DoughnutSeries<Shortlisted, String>>[
                      DoughnutSeries<Shortlisted, String>(
                        animationDuration: 800,
                        dataSource: widget.shortlisted,
                        xValueMapper: (Shortlisted data, _) => data.title,
                        yValueMapper: (Shortlisted data, _) => data.value,
                        onPointTap: (details) {
                          // This works fine, is there is a way to call it programmatically with the required details?
                          if (details.pointIndex != null) {
                            handlePieChartSelection(details.pointIndex!);
                          }
                        },
                        explode: true,
                        explodeAll: false,
                        explodeIndex: selectedIndex,
                        selectionBehavior: SelectionBehavior(
                          enable: true,
                          selectionController:  rangeController,   // ?!!
                          selectedBorderWidth: 2,
                          selectedOpacity: 1,
                          unselectedOpacity: 0.5,
                        ),
                        radius: (MediaQuery.of(context).size.width / 4.8)
                            .toString(),
                        innerRadius: (MediaQuery.of(context).size.width / 6.8)
                            .toString(),
                      ),
                    ],
                  ),

**Comment by sfHariHaraSudhan** [comment]
Hi @MuhammedRefaat,

In the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html), the current behavior of the selection is that the segments can be selected only with the user interactions and there is no option to select the segments programmatically. However, you can explode the segments programmatically using the [explodeIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/explodeIndex.html) property as per the code snippet below.

```
class _MyHomePageState extends State<MyHomePage> {
  int _explodeIndex = 2;
  late SelectionBehavior _selectionBehavior;
  late List<ChartData> _chartData;

  @override
  void initState() {
    _chartData = [
      ChartData('David', 25),
      ChartData('Steve', 38),
      ChartData('Jack', 34),
      ChartData('Others', 52),
    ];
    _selectionBehavior = SelectionBehavior(
      enable: true,
      selectedBorderWidth: 2,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SfCircularChart(
          enableMultiSelection: false,
          series: <CircularSeries>[
            DoughnutSeries<ChartData, String>(
              dataSource: _chartData,
              xValueMapper: (ChartData data, _) => data.x,
              yValueMapper: (ChartData data, _) => data.y,
              explode: true,
              explodeIndex: _explodeIndex,
              selectionBehavior: _selectionBehavior,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            _explodeIndex = 0;
          });
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
```
Also attached the sample and recording below for your reference. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

[_483334.zip](https://github.com/syncfusion/flutter-widgets/files/12104371/_483334.zip)
[483334.zip](https://github.com/syncfusion/flutter-widgets/files/12104375/483334.zip)
