### ISSUE TITLE
Stamp is not displaying in SfPdfViewer.network.

### ISSUE THREAD

**Issue by cgztzero** [syncfusion/flutter-widgets#1304]
I try to use SfPdfViewer.network() show a online pdf file，but the stamp in the pdf is not displaying.
Could someone help me ?
The pdf display without stamp in flutter
![1](https://github.com/syncfusion/flutter-widgets/assets/8406065/fef7ae79-a9df-4eb5-86d3-a7f187b095c1)

The pdf display normal in chrome on mac
![2](https://github.com/syncfusion/flutter-widgets/assets/8406065/6a272cba-672a-45bb-b360-d9d94171453c)

**Comment by deepika134** [comment]
At present we do not have support for shape annotations in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following link for track the status of the feature,

https://www.syncfusion.com/feedback/26332/support-for-shape-annotations

**Comment by cgztzero** [comment]
> At present we do not have support for shape annotations in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following link for track the status of the feature,
> 
> https://www.syncfusion.com/feedback/26332/support-for-shape-annotations

Thank you for reply me , I see.

**Comment by ruqaiyasattar** [comment]
How to sign [sign widget] in SfPdfViewer.network document? I am able to add sign on PDF from asset, but can't add sign in network.

**Comment by ramkumarsync** [comment]
> How to sign [sign widget] in SfPdfViewer.network document? I am able to add sign on PDF from asset, but can't add sign in network.

We are unable to replicate the reported issue with our network document. Could be please share the exact replication procedure or the network document URL (if possible) for this issue? It would help us analyze the issue and provide a better solution at the earliest.

**Comment by ramkumarsync** [comment]
Since we don't have enough information to proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.
