### ISSUE TITLE
Exception:LateInitializationError: Field 'actualIntervalType' has not been initialized.

### ISSUE THREAD

**Issue by garinasset** [syncfusion/flutter-widgets#1305]
***
### Issue Description
When I use SfCartesianChart and set the primaryXAxis to DateTimeCategoryAxis, I occasionally encounter the following error:

> ════════ Exception caught by widgets library ═══
> LateInitializationError: Field 'actualIntervalType' has not been initialized.
> The relevant error-causing widget was
> SfCartesianChart
> widget_chart_area.dart:38
> ═══════════════════════════════════

This issue does not always occur and seems to happen when the time axis is continuous . Here's my code for reference:
```
primaryXAxis: DateTimeCategoryAxis(
  isVisible: true,
  axisLine: AxisLine(width: 0.01),
  labelStyle: TextStyle(),
  edgeLabelPlacement: EdgeLabelPlacement.shift,
  majorGridLines: MajorGridLines(
    width: 0.1,
    color: CupertinoColors.systemGrey.withOpacity(0.2),
  ),
  dateFormat: DateFormat.y(),
),
```
### Steps to Reproduce

1. Set the primaryXAxis to DateTimeCategoryAxis.
2. To fill the time axis data with continuous YYYY-MM-DD format.

### Environment

- SfCartesianChart version: ^22.1.39
- Platform: Flutter
- Operating System: [IOS]
- Device: [iPhone&iPad]
***

**Comment by sfHariHaraSudhan** [comment]
Hi @garinops,

We have analyzed your query and implemented a simple sample to check whether the mentioned issue replicates or not with the provided code snippet. Unfortunately, the late exception is not replicated from our end while using the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) as [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html).

We recommend you reproduce the mentioned issue in the attached sample below and it will be very useful for us to provide the best possible solution from our end.

Kindly refer the code snippet:
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> _data;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(x: DateTime(2023, 07, 01), y: 40),
      ChartSampleData(x: DateTime(2023, 07, 02), y: 60),
      ChartSampleData(x: DateTime(2023, 07, 03), y: 20),
      ChartSampleData(x: DateTime(2023, 07, 04), y: 30),
      ChartSampleData(x: DateTime(2023, 07, 05), y: 40),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        primaryXAxis: DateTimeCategoryAxis(
          isVisible: true,
          axisLine: const AxisLine(width: 0.01),
          labelStyle: const TextStyle(),
          edgeLabelPlacement: EdgeLabelPlacement.shift,
          majorGridLines: const MajorGridLines(
            width: 0.1,
            color: Colors.grey,
          ),
          dateFormat: DateFormat.y(),
        ),
        primaryYAxis: NumericAxis(),
        series: <CartesianSeries<ChartSampleData, DateTime>>[
          ColumnSeries<ChartSampleData, DateTime>(
            dataSource: _data,
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            yValueMapper: (ChartSampleData sales, int index) => sales.y,
          ),
        ],
      ),
    );
  }
}
```
Regards,
Hari Hara Sudhan. K.

[484692.zip](https://github.com/syncfusion/flutter-widgets/files/12122779/484692.zip)

**Comment by garinops** [comment]
@sfHariHaraSudhan Sorry,I reported the issue as soon as I encountered it. I have now identified the conditions that reproduce the issue. In the code you provided, if you use the following data population code instead, it will trigger the issue:
 ```
 //……
@override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(x: DateTime.parse('1952-12-31'), y: 7.88),
      ChartSampleData(x: DateTime.parse('1953-12-31'), y: 19.28),
      ChartSampleData(x: DateTime.parse('1954-12-31'), y: 21.13),
      ChartSampleData(x: DateTime.parse('1955-12-31'), y: 23.88),
      ChartSampleData(x: DateTime.parse('1956-12-31'), y: 26.83),
      ChartSampleData(x: DateTime.parse('1957-12-31'), y: 32.81),
    ];
    super.initState();
  }
//……
```

>

**Comment by garinops** [comment]
> Hi @garinops,
> 
> We have analyzed your query and implemented a simple sample to check whether the mentioned issue replicates or not with the provided code snippet. Unfortunately, the late exception is not replicated from our end while using the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html) as [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html).
> 
> We recommend you reproduce the mentioned issue in the attached sample below and it will be very useful for us to provide the best possible solution from our end.
> 
> Kindly refer the code snippet:
> 
> ```
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   late List<ChartSampleData> _data;
> 
>   @override
>   void initState() {
>     _data = <ChartSampleData>[
>       ChartSampleData(x: DateTime(2023, 07, 01), y: 40),
>       ChartSampleData(x: DateTime(2023, 07, 02), y: 60),
>       ChartSampleData(x: DateTime(2023, 07, 03), y: 20),
>       ChartSampleData(x: DateTime(2023, 07, 04), y: 30),
>       ChartSampleData(x: DateTime(2023, 07, 05), y: 40),
>     ];
>     super.initState();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: SfCartesianChart(
>         primaryXAxis: DateTimeCategoryAxis(
>           isVisible: true,
>           axisLine: const AxisLine(width: 0.01),
>           labelStyle: const TextStyle(),
>           edgeLabelPlacement: EdgeLabelPlacement.shift,
>           majorGridLines: const MajorGridLines(
>             width: 0.1,
>             color: Colors.grey,
>           ),
>           dateFormat: DateFormat.y(),
>         ),
>         primaryYAxis: NumericAxis(),
>         series: <CartesianSeries<ChartSampleData, DateTime>>[
>           ColumnSeries<ChartSampleData, DateTime>(
>             dataSource: _data,
>             xValueMapper: (ChartSampleData sales, int index) => sales.x,
>             yValueMapper: (ChartSampleData sales, int index) => sales.y,
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```
> 
> Regards, Hari Hara Sudhan. K.
> 
> [484692.zip](https://github.com/syncfusion/flutter-widgets/files/12122779/484692.zip)

@sfHariHaraSudhan Sorry,I reported the issue as soon as I encountered it. I have now identified the conditions that reproduce the issue. In the code you provided, if you use the following data population code instead, it will trigger the issue:
 ```
 //……
@override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(x: DateTime.parse('1952-12-31'), y: 7.88),
      ChartSampleData(x: DateTime.parse('1953-12-31'), y: 19.28),
      ChartSampleData(x: DateTime.parse('1954-12-31'), y: 21.13),
      ChartSampleData(x: DateTime.parse('1955-12-31'), y: 23.88),
      ChartSampleData(x: DateTime.parse('1956-12-31'), y: 26.83),
      ChartSampleData(x: DateTime.parse('1957-12-31'), y: 32.81),
    ];
    super.initState();
  }
//……
```

>

**Comment by sfHariHaraSudhan** [comment]
Hi @garinops,

We have replicated the mentioned exception from our end using the provided code snippet. The reason for the exception is that you have used dates prior to 1970. We would like to inform you that the minimum value for DateTime is January 01, 1970, and this is the current behavior of the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). However, we recommend that you share your requirements and use case for utilizing the dates before 1970. Based on your requirements, it will be helpful for us to decide whether to consider it as a feature request or provide any possible solution from our end.

Regards,
Hari Hara Sudhan K.

**Comment by garinops** [comment]
> We have replicated the mentioned exception from our end using the provided code snippet. The reason for the exception is that you have used dates prior to 1970. We would like to inform you that the minimum value for DateTime is January 01, 1970, and this is the current behavior of the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). However, we recommend that you share your requirements and use case for utilizing the dates before 1970. Based on your requirements, it will be helpful for us to decide whether to consider it as a feature request or provide any possible solution from our end.

Hi @sfHariHaraSudhan 
I have received your response and have also identified the issue. However, I believe this problem should be considered as an improvement for the **DateTimeCategoryAxis**, as I have found that the exception does not occur even when the date is earlier than January 1st, 1970, if using **DateTimeAxis** with **SfCartesianChart**.

I need to use SfCartesianChart to display some financial market data, and many of the data have a start date earlier than January 1st, 1970, such as the Dow Jones Industrial Average, which dates back to the 19th century.

The reason why I used DateTimeCategoryAxis instead of DateTimeAxis is because DateTimeCategoryAxis has a good display effect when handling irregular time data. In some cases, using DateTimeAxis may cause distortion.

Thank you for your reply.

**Comment by sfHariHaraSudhan** [comment]
Hi @garinops,

Currently, we don’t have support for **Providing an option to give dates prior to January 01, 1970, in DateTimeCategoryAxis**. However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback link below.

Feedback Link: [https://www.syncfusion.com/feedback/45630](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F45630&data=05%7C01%7Chariharasudhan.kanagaraj%40syncfusion.com%7C89a7e81bda8040cb991608db8dda8837%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638259741955342460%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LwkfitIffW0%2F7GtOg0WcgvMDT860PBm7kqr7HJNurps%3D&reserved=0)

Regards,
Hari Hara Sudhan. K.

**Comment by garinops** [comment]
Hi @sfHariHaraSudhan,

I have received your response and have reviewed the tracking link. Your workflow is great and I will keep track of it. 

Thank you for your reply.
