### ISSUE TITLE
[syncfusion_flutter_charts] TooltipRenderingDetails.internalShowByPixel

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#1306]
Crashlytics - Stack trace
Platform: apple
Version: 1.1.86 (136)
Issue: a18a3d5354ba80a319948f97d390e0fb
Session: e71e8159245844fda67752df14cb55c6_DNE_0_v2

Fatal Exception: FlutterError
0  ???                            0x0 TooltipRenderingDetails.internalShowByPixel + 803 (tooltip_rendering_details.dart:803)
1  ???                            0x0 TooltipBehavior.showByPixel + 610 (tooltip.dart:610)
2  ???                            0x0 TooltipBehaviorRenderer.onTouchUp + 828 (tooltip.dart:828)
3  ???                            0x0 (null)._showTrimmedDataLabelTooltip + 779 (circular_area.dart:779)
4  ???                            0x0 CircularArea._onPointerUp + 256 (circular_area.dart:256)
5  ???                            0x0 CircularArea.build.<fn>.<fn> + 76 (circular_area.dart:76)
6  ???                            0x0 RenderPointerListener.handleEvent + 3117 (proxy_box.dart:3117)
7  ???                            0x0 GestureBinding.dispatchEvent + 445 (binding.dart:445)
8  ???                            0x0 RendererBinding.dispatchEvent + 331 (binding.dart:331)
9  ???                            0x0 GestureBinding._handlePointerEventImmediately + 400 (binding.dart:400)
10 ???                            0x0 GestureBinding.handlePointerEvent + 363 (binding.dart:363)
11 ???                            0x0 GestureBinding._flushPointerEventQueue + 320 (binding.dart:320)
12 ???                            0x0 GestureBinding._handlePointerDataPacket + 293 (binding.dart:293)

Crashed: com.apple.main-thread
0  FirebaseCrashlytics            0x1e2cc FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1e6ac FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x15744 FIRCLSHandler + 48
3  FirebaseCrashlytics            0xfbd8 FIRCLSExceptionRecordOnDemand + 1328
4  FirebaseCrashlytics            0xf618 FIRCLSExceptionRecordOnDemandModel + 228
5  FirebaseCrashlytics            0x1da98 -[FIRCLSOnDemandModel recordOnDemandExceptionWithModel:] + 68
6  FirebaseCrashlytics            0x1d4f4 -[FIRCLSOnDemandModel recordOnDemandExceptionIfQuota:withDataCollectionEnabled:usingExistingReportManager:] + 164
7  FirebaseCrashlytics            0x2b9a8 -[FIRCrashlytics recordOnDemandExceptionModel:] + 140
8  Runner                         0x228284 -[FLTFirebaseCrashlyticsPlugin recordError:withMethodCallResult:] + 177 (FLTFirebaseCrashlyticsPlugin.m:177)
9  Runner                         0x227b40 -[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:] + 101 (FLTFirebaseCrashlyticsPlugin.m:101)
10 Flutter                        0x5d5f98 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
11 Flutter                        0x3736c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
12 libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x4300 _dispatch_client_callout + 20
14 libdispatch.dylib              0x12998 _dispatch_main_queue_drain + 984
15 libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
16 CoreFoundation                 0x997e0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
17 CoreFoundation                 0x7ceb4 __CFRunLoopRun + 1996
18 CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
19 GraphicsServices               0x1224 GSEventRunModal + 164
20 UIKitCore                      0x38ed2c -[UIApplication _run] + 888
21 UIKitCore                      0x38e990 UIApplicationMain + 340
22 Runner                         0x4e90 main + 5 (AppDelegate.swift:5)
23 ???                            0x1acc9c4f8 (Ausente)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  CoreFoundation                 0x7b978 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7cba0 __CFRunLoopRun + 1208
6  CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
7  Foundation                     0x41cb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8  Foundation                     0x41b9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9  UIKitCore                      0x4bd714 -[UIEventFetcher threadMain] + 420
10 Foundation                     0x5ac9c __NSThread__start__ + 732
11 libsystem_pthread.dylib        0x1710 _pthread_start + 136
12 libsystem_pthread.dylib        0xbfc thread_start + 8

io.flutter.1.ui
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  CoreFoundation                 0x7b978 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7cba0 __CFRunLoopRun + 1208
6  CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
7  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
8  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
9  libsystem_pthread.dylib        0x1710 _pthread_start + 136
10 libsystem_pthread.dylib        0xbfc thread_start + 8

io.flutter.1.raster
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  CoreFoundation                 0x7b978 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7cba0 __CFRunLoopRun + 1208
6  CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
7  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
8  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
9  libsystem_pthread.dylib        0x1710 _pthread_start + 136
10 libsystem_pthread.dylib        0xbfc thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  CoreFoundation                 0x7b978 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7cba0 __CFRunLoopRun + 1208
6  CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
7  Flutter                        0x2e654c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
8  Flutter                        0x2e603c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
9  libsystem_pthread.dylib        0x1710 _pthread_start + 136
10 libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  Flutter                        0x48a60 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x2e00cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  libsystem_pthread.dylib        0x1710 _pthread_start + 136
5  libsystem_pthread.dylib        0xbfc thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x258c kevent + 8
1  Flutter                        0x4d77e0 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
2  Flutter                        0x506780 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  libsystem_pthread.dylib        0x1710 _pthread_start + 136
4  libsystem_pthread.dylib        0xbfc thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  FirebaseCrashlytics            0x17d58 FIRCLSMachExceptionServer + 104
5  libsystem_pthread.dylib        0x1710 _pthread_start + 136
6  libsystem_pthread.dylib        0xbfc thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0xc64 mach_msg2_trap + 8
1  libsystem_kernel.dylib         0x14348 mach_msg2_internal + 80
2  libsystem_kernel.dylib         0x145b8 mach_msg_overwrite + 436
3  libsystem_kernel.dylib         0x11b4 mach_msg + 24
4  CoreFoundation                 0x7b978 __CFRunLoopServiceMachPort + 160
5  CoreFoundation                 0x7cba0 __CFRunLoopRun + 1208
6  CoreFoundation                 0x816c0 CFRunLoopRunSpecific + 600
7  CFNetwork                      0x26335c _CFURLStorageSessionDisableCache + 60404
8  Foundation                     0x5ac9c __NSThread__start__ + 732
9  libsystem_pthread.dylib        0x1710 _pthread_start + 136
10 libsystem_pthread.dylib        0xbfc thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1178 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe9c _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xbf0 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1178 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe9c _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xbf0 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1178 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe9c _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xbf0 start_wqthread + 8

JavaScriptCore libpas scavenger
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80ac _pthread_cond_wait + 1228
2  JavaScriptCore                 0x150af1c scavenger_thread_main + 1512
3  libsystem_pthread.dylib        0x1710 _pthread_start + 136
4  libsystem_pthread.dylib        0xbfc thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1178 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe9c _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xbf0 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1178 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0xe9c _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xbf0 start_wqthread + 8

DartWorker
0  libsystem_kernel.dylib         0x1544 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x80d8 _pthread_cond_wait + 1272
2  Flutter                        0x68c180 (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
3  Flutter                        0x6c61cc (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
4  Flutter                        0x68bb4c (Ausente UUID 4c4c448b55553144a1517a35ce73c4aa)
5  libsystem_pthread.dylib        0x1710 _pthread_start + 136
6  libsystem_pthread.dylib        0xbfc thread_start + 8

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

We have analyzed your query and based on the provided call stack, we suspect that you are trying to render the tooltip at the specified position when tapping on the segment. In the attached sample, we have tried to customize the text of the tooltip based on the tapped segment index and attempted to replicate the mentioned issue. However, we are unable to reproduce the issue from our end with the provided call stack. We recommend that you try to reproduce the mentioned issue using the attached sample below. This will be very helpful for us to provide the best possible solution.

Kindly refer the code snippet below:
```
class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> chartData;
  late TooltipBehavior tooltipBehavior;

  @override
  void initState() {
    chartData = [
      ChartSampleData('David', 25, const Color.fromRGBO(9, 0, 136, 1)),
      ChartSampleData('Steve', 38, const Color.fromRGBO(147, 0, 119, 1)),
      ChartSampleData('Jack', 34, const Color.fromRGBO(228, 0, 124, 1)),
      ChartSampleData('Others', 52, const Color.fromRGBO(255, 189, 57, 1)),
    ];
    tooltipBehavior = TooltipBehavior(
      enable: true,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCircularChart(
        onTooltipRender: (TooltipArgs tooltipArgs) {
          tooltipArgs.text =
              '${tooltipArgs.pointIndex}) ${chartData[tooltipArgs.pointIndex!.toInt()].name} : ${chartData[tooltipArgs.pointIndex!.toInt()].value}';
        },
        series: <DoughnutSeries<ChartSampleData, String>>[
          DoughnutSeries<ChartSampleData, String>(
            dataSource: chartData,
            onPointTap: (ChartPointDetails pointInteractionDetails) {
              pointInteractionDetails.pointIndex;
            },
            pointColorMapper: (ChartSampleData data, _) => data.color,
            xValueMapper: (ChartSampleData data, _) => data.name,
            yValueMapper: (ChartSampleData data, _) => data.value,
          ),
        ],
        tooltipBehavior: tooltipBehavior,
      ),
    );
  }
}
```
Regards,
Hari Hara Sudhan. K.
[485241.zip](https://github.com/syncfusion/flutter-widgets/files/12146013/485241.zip)

**Comment by mdmota** [comment]
the problem is that I have several graphs and I couldn't find the origin of the problem with the pile of errors.

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

We are able to replicate the reported issue regarding **Type cast exception thrown when rendering the tooltip with trimmed text in the data label** at our end and have logged bug report for it in our feedback portal. We will fix and include the changes after the SP release which is expected to be rolled out at the start of August 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.

Feedback Link: https://www.syncfusion.com/feedback/45592.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @mdmota,

The reported issue regarding **Type cast exception thrown when rendering the tooltip with trimmed text in the data label** has been fixed and rolled out in our weekly release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.2.8

Regards,
Hari Hara Sudhan. K.
