### ISSUE TITLE
Added to project and testing example code, unable to run

### ISSUE THREAD

**Issue by DitoXD** [syncfusion/flutter-widgets#1307]
I get the following error:

../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-22.1.39/lib/src
/calendar/views/calendar_view.dart:12553:9: Error: A constant constructor can't call a  
non-constant super constructor.
[   +1 ms]       : super(children: children);
[        ]         ^

throughout multiple files that were pulled through pub.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22621.1992],
    locale en-JM)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc3)    
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)       
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.80.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

Device being used to run is Nexus 7 API 32(android-x64 emulator).

I'd like to figure out what the issue is because this is a brand new project and straight off the bat I cant use the first package I've added.

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the shared information, we have checked the issue “**A constant constructor can't call a non-constant super constructor**” in the simple sample of the Flutter calendar. But we are unable to reproduce the mentioned issue, it was working fine as expected from our end.

**Tested details:**
1. Flutter version: Stable channel-3.10.1
2. Flutter Calendar version: 22.1.39

Kindly update the Flutter version to latest version 3.10.1 then check and let us know still if you are facing the same issue, please share the below details with us.

1.Replication procedure

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by DitoXD** [comment]
Upgrading both the flutter and dart sdk got it working, appreciate the timely feedback. Many thanks!
