### ISSUE TITLE
Issue Regarding Constant ( I am not so sure )

### ISSUE THREAD

**Issue by PistonShot1** [syncfusion/flutter-widgets#1308]
hi , i am not sure where to post problem or ask question, so I post here 

error: 
...../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_gauges-22.1.39/lib/src/radial_gauge/axis/radial_axis_parent_widget.dart:36:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(key: key, children: children);
        ^
 I run into this error when try to make any gauge with this flutter syncfusion gauge dependency, I am not sure if this issue has been solved before , or error on my side, but I just removed the const keyword for that part it says using const keyword (line 35, radial_axis_parent_widget.dart) (I just removed the const keyword and it works now for some reason)

**Comment by sfHariHaraSudhan** [comment]
Hi @PistonShot1,

The reported issue "A constant constructor can't call a non-constant super constructor” linter warnings have been raised in the Flutter 3.10 SDK version. To avoid this issue, please use the latest Flutter SDK v3.10 or later.  Please let us know if you need any further assistance. 

Regards,
Hari Hara Sudhan. K.

**Comment by PistonShot1** [comment]
Ah I see, it works now after flutter upgrade. Thanks Hari for the reply.
