### ISSUE TITLE
SfCircularChart Not Showing Legends Inside CustomScrollView

### ISSUE THREAD

**Issue by DominicOrga** [syncfusion/flutter-widgets#1309]
When attempting to add a `SfCircularChart` within a `CustomScrollView`, the legends are not visible in the user interface.

```dart
    CustomScrollView(
      slivers: [
        SliverToBoxAdapter(
          child: SfCircularChart(
            legend: const Legend(
              isVisible: true,
              position: LegendPosition.bottom,
              overflowMode: LegendItemOverflowMode.wrap,
            ),
            ...
          ),
        ),
      ],
    )
```

**Actual**
<img width="339" alt="Screenshot 2023-07-25 at 2 58 36 PM" src="https://github.com/syncfusion/flutter-widgets/assets/12520299/b46b7d7d-9c3b-4f4c-b862-4cf394c5dc37">

**Expected**
<img width="348" alt="Screenshot 2023-07-25 at 2 59 06 PM" src="https://github.com/syncfusion/flutter-widgets/assets/12520299/ae670e9c-52ff-449d-b543-9dcc5380c768">

**Comment by sfHariHaraSudhan** [comment]
Hi @DominicOrga,

In the attached sample below, we have rendered the [Pie Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PieSeries-class.html) with the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html) and [ChartTitle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartTitle-class.html) and added SliverToBoxAdapter widgets inside the CustomScrollView to achieve the scrollable effect based on the provided snapshot and code snippet. Unfortunately, we were unable to replicate the mentioned behavior on our end.

Kindly refer the below code snippet:
```
class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> chartData;
 
  @override
  void initState() {
    chartData = <ChartSampleData>[
      ChartSampleData('20', 20, 'Caffeine'),
      ChartSampleData('10', 10, 'Digital Devices'),
      ChartSampleData('30', 30, 'Stress & Anxiety'),
      ChartSampleData('40', 40, 'Hot Temperature'),
    ];
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverToBoxAdapter(
            child: SfCircularChart(
              onDataLabelRender: (dataLabelArgs) {
                dataLabelArgs.text = '${chartData[dataLabelArgs.pointIndex!].x} %';
              },
              onLegendItemRender: (legendRenderArgs) {
                legendRenderArgs.text = chartData[legendRenderArgs.pointIndex!].text;
              },
              title: ChartTitle(
                text: 'Probable Sleep Distribution Factors',
                textStyle: const TextStyle(
                  color: Colors.black,
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                ),
              ),
              legend: const Legend(
                isVisible: true,
                overflowMode: LegendItemOverflowMode.wrap,
                position: LegendPosition.bottom,
                height: '200',
              ),
              series: <CircularSeries<ChartSampleData, String>>[
                PieSeries<ChartSampleData, String>(
                  dataSource: chartData,
                  xValueMapper: (ChartSampleData data, _) => data.x,
                  yValueMapper: (ChartSampleData data, _) => data.y,
                  dataLabelSettings: const DataLabelSettings(
                    isVisible: true,
                  ),
                  explode: true,
                ),
              ],
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              width: 200,
              height: 200,
              color: Colors.blue,
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              width: 200,
              height: 200,
              color: Colors.red,
            ),
          ),
          SliverToBoxAdapter(
            child: Container(
              width: 200,
              height: 200,
              color: Colors.green,
            ),
          ),
        ],
      ),
    );
  }
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/f7d5630d-f495-4f3d-8599-7bb8add25339)

We recommend that you reproduce the mentioned behavior in the attached sample below, as it will be helpful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.
[485704.zip](https://github.com/syncfusion/flutter-widgets/files/12171394/485704.zip)

**Comment by DominicOrga** [comment]
Hi @sfHariHaraSudhan,

I appreciate the help. I just tried it on my side as well and it turns out it's a bug on my end. Thanks!
I'll be closing this issue now.
