### ISSUE TITLE
Adding operator == to TechnicalIndicators

### ISSUE THREAD

**Issue by barilki** [syncfusion/flutter-widgets#1310]
Hi,
It would be helpful if you could add the operator == and hashCode to the TechnicalIndicators class so that it has comparable option.

Thanks.

**Comment by sfHariHaraSudhan** [comment]
Hi @barilki,

[TechnicalIndicators](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicators-class.html) is a base class of indicators that cannot be initialized and used at the sample level. We have included the == operator and hashCode in all the derived classes of [TechnicalIndicators](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicators-class.html). Here, the base class [TechnicalIndicators](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicators-class.html) must be kept as an abstract class. We will address this and make it abstract in our upcoming weekly release. Therefore, there is no need to include the == operator and hashCode in the [TechnicalIndicators](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TechnicalIndicators-class.html) class.

If you have any further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @barilki,

As mentioned, **the TechnicalIndicators class has been updated as abstract class** and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.2.9.

Regards,
Hari Hara Sudhan. K.
