### ISSUE TITLE
W/HiTouch_PressGestureDetector(25375): Touch pointer move a lot. The moving distance of X is:3.0, limit is:60The moving distance of Y is:91.0, limit is:60

### ISSUE THREAD

**Issue by haoxuhong** [syncfusion/flutter-widgets#1312]
点击出现的弹框，当数据很多时，弹框需要上下滑动时报如下错误信息：

W/HiTouch_PressGestureDetector(25375): Touch pointer move a lot. The moving distance of X is:3.0, limit is:60The moving distance of Y is:91.0, limit is:60

**Comment by sfHariHaraSudhan** [comment]
Hi @haoxuhong,

To create a pop-up with scrollable features, you can use a [AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html) or [BottomSheet](https://api.flutter.dev/flutter/material/BottomSheet-class.html) widget along with a [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) or [SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) widget to enable scrolling. You can customize the content of the pop-up based on your needs, using any combination of widgets you require. The [SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) will ensure that the pop-up remains scrollable if the content exceeds the available space.

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K
