### ISSUE TITLE
No scrollbar for PDFViewer dropdown

### ISSUE THREAD

**Issue by isenbj** [syncfusion/flutter-widgets#1313]
Could we add a scrollbar to the List Box field on the pdf viewer? Right now it is hard to tell when there are more items past 6

![Screenshot 2023-07-29 at 4 41 28 PM](https://github.com/syncfusion/flutter-widgets/assets/49786150/84fb8948-6f70-414e-aeda-96dbc67b25df)

**Comment by deepika134** [comment]
We are utilizing the PopupMenuButton widget to create the combo box form field in SfPdfViewer. On the mobile platform, the scrollbar will not be visible. This is the default behavior for PopupMenuButton.

**Comment by ramkumarsync** [comment]
We enhanced the user experience of the combo box form field by switching the PopupMenuButton with a DropdownButton widget in SfPdfViewer. Now, the scrollbar will be displayed by default and this change is available from version v22.2.10
