### ISSUE TITLE
How can i plot Hours on x-axis based on 12-hour format?

### ISSUE THREAD

**Issue by shivmaurya-creator** [syncfusion/flutter-widgets#132]
What i'm looking to achieve is something like mentioned below.

![chart](https://user-images.githubusercontent.com/69803905/107158185-536fe480-69ae-11eb-845c-59d9e7133cb8.PNG)

So how can i plot hours on x-axis based on 12-hour format, with the interval of 2:00 hrs.

**Comment by Dharanipalani** [comment]
Hi Shivmaurya,
 
We have analyzed your scenario and attached a sample with a screenshot for your reference, kindly make use of it. Following code snippets will help you understand the sample we provided for you.

In the respective axis (say primaryXAxis), using the **dateFormat** property to change the date format as your requirement.  The following code snippet will display the date format in the 12 hours format.

`dateFormat: DateFormat("h: mma"), `

And then specify the **intervalType** and **interval** property as following, 

`primaryXAxis: DateTimeAxis(`
`// To avoid collision between data labels`
`labelIntersectAction: AxisLabelIntersectAction.rotate45,`
`// Converts 24 hours date format into 12 hours date format with AM and PM.`
`dateFormat:DateFormat("h:mma"),`
`// Specifying interval type as hours.`
`intervalType: DateTimeIntervalType.hours,`
`// Specifying interval as 2.`
`interval: 2,`
`)`

Sample: [https://www.syncfusion.com/downloads/support/directtrac/314170/ze/I314170_12_hours_format1385210108](url)

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/107216330-a12e3080-6a32-11eb-9cae-c858449cf2ea.png)

Kindly revert us if you need any further assistance.

Thanks,
Dharanitharan. P

**Comment by mshivkumar** [comment]
Hi Dharanitharan. P,

Thank you for your response, but the link shared above for reference, is'nt working could u please check and maybe provide the working link.

**Comment by Dharanipalani** [comment]
Hi @mshivkumar,

We regret the inconvenience that caused and now we attached the sample below, kindly make use of it. Please revert us if you need any further assistance.

Sample: [I314170_12_hours_format.zip](https://github.com/syncfusion/flutter-widgets/files/5949483/I314170_12_hours_format.zip)


Thanks,
Dharanitharan. P
