### ISSUE TITLE
add namespace

### ISSUE THREAD

**Issue by RichardsonTsavo** [syncfusion/flutter-widgets#1321]
A problem occurred configuring project ':syncfusion_flutter_pdfviewer'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

 android {
     namespace 'com.example.namespace'
 }

**Comment by arcas0803** [comment]
Any solution t o this proble?

**Comment by MattEndare** [comment]
Same issue.

**Comment by ramkumarsync** [comment]
We have resolved this issue and the fix for the same will be available from version v24.1.41.

https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.1.41
