### ISSUE TITLE
Add marker for line series when click to show tooltip

### ISSUE THREAD

**Issue by 1712916** [syncfusion/flutter-widgets#1322]
Hello team,
Please help me answer this question.

I have a line chart, by initial it have not any marker. I want to show a marker at position i click to show tooltip. how any way to do this?

Thank you.

![image](https://github.com/syncfusion/flutter-widgets/assets/37785271/4ae60728-5a73-4221-b967-3e104b67b4b0)

**Comment by sfHariHaraSudhan** [comment]
Hi @1712916,

We have prepared the sample with an [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onPointTap.html) and [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) to render the tooltip and the marker in the tapped location. Here, we get the point index and series index of the tapped location using the [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onPointTap.html) callback, give the marker the required height and width based on the tapped point index, and hide all the other markers by setting their height and width to 0 in the [onMarkerRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onMarkerRender.html). To make the tooltip visible only on the tapped point, we have passed the series index and the point index to the [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) method in the addPostFrameCallback method, and we have hidden the other tooltip using the [TooltipBehavior.hide](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/hide.html) method.

Kindly refer the code snippet below:
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  int? dataPointIndex;
  int? seriesIndex;
  late TooltipBehavior _tooltipBehavior;

  @override
  void initState() {
    _data = [
      ChartSampleData(01, 40),
      ChartSampleData(02, 80),
      ChartSampleData(03, 40),
      ChartSampleData(04, 60),
      ChartSampleData(05, 50),
      ChartSampleData(06, 90),
      ChartSampleData(07, 110),
      ChartSampleData(08, 70),
      ChartSampleData(09, 120),
      ChartSampleData(10, 100),
    ];
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      builder: (data, point, series, pointIndex, seriesIndex) {
        if (pointIndex == dataPointIndex) {
          return Container(
            height: 50.0,
            width: 50.0,
            color: Colors.blue,
          );
        } else {
          _tooltipBehavior.hide();
          return Container();
        }
      },
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
      _tooltipBehavior.showByIndex(seriesIndex ?? 0, dataPointIndex ?? 0);
    });

    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            SfCartesianChart(
              onMarkerRender: (MarkerRenderArgs markerArgs) {
                if (markerArgs.pointIndex == dataPointIndex) {
                  markerArgs.markerHeight = 10;
                  markerArgs.markerWidth = 10;
                  markerArgs.color = Colors.blue;
                } else {
                  markerArgs.color = Colors.transparent;
                  markerArgs.markerHeight = 0;
                  markerArgs.markerWidth = 0;
                }
              },
              primaryXAxis: NumericAxis(),
              primaryYAxis: NumericAxis(),
              series: <CartesianSeries<ChartSampleData, num>>[
                LineSeries<ChartSampleData, num>(
                  onPointTap: (ChartPointDetails details) {
                    setState(() {
                      dataPointIndex = details.pointIndex;
                      seriesIndex = details.seriesIndex;
                    });
                  },
                  dataSource: _data,
                  enableTooltip: true,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y,
                  color: Colors.blue,
                  markerSettings: const MarkerSettings(
                    isVisible: true,
                  ),
                ),
              ],
              tooltipBehavior: _tooltipBehavior,
            ),
          ],
        ),
      ),
    );
  }
}
```
Also shared the recording and sample below for your reference and you can modify the sample based on your requirement. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[489005.zip](https://github.com/syncfusion/flutter-widgets/files/12299451/489005.zip)
[_489005.zip](https://github.com/syncfusion/flutter-widgets/files/12299457/_489005.zip)

**Comment by 1712916** [comment]
@sfHariHaraSudhan 
Thank you for your detailed reply.

Additionally, I have another question:
How do I listen when the tooltip is hidden? In this case, I want to hide the market I showed before.

**Comment by 1712916** [comment]
@sfHariHaraSudhan 

I had tried this solution before. But I realized that when we use setState to rebuild the marker, it is unstable. So the performance is not good.

**Comment by sfHariHaraSudhan** [comment]
Hi @1712916,

**Query 1: How do I listen when the tooltip is hidden? In this case, I want to hide the market I showed before.**

You can able to hide the marker when the tooltip is hidden using the [duration](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/duration.html) property in the [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html) and Timer widget. Here, we have given same time to both the [duration](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/duration.html) property in the [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html) and to the Timer widget and when it reaches the time we reset the position.

**Query 2: I had tried this solution before. But I realized that when we use setState to rebuild the marker, it is unstable. So the performance is not good.**

To achieve better performance and to avoid using setState, we have used CustomPaint widget to render the marker at the tapped location. Here, when the point is tapped, we convert the tapped point values to the pixel values using the [pointToPixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method in the [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html) and render the custom marker at the tapped location.

Kindly refer the code snippet:
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  int? dataPointIndex;
  int? seriesIndex;
  late TooltipBehavior _tooltipBehavior;
  ValueNotifier<Offset?> position = ValueNotifier(null);
  late ChartSeriesController _controller;
  final EdgeInsets _chartPadding = const EdgeInsets.all(10.0);
 
  @override
  void initState() {
    _data = [
      ChartSampleData(01, 40),
      ChartSampleData(02, 80),
      ChartSampleData(03, 40),
      ChartSampleData(04, 60),
      ChartSampleData(05, 50),
      ChartSampleData(06, 90),
      ChartSampleData(07, 110),
      ChartSampleData(08, 70),
      ChartSampleData(09, 120),
      ChartSampleData(10, 100),
    ];
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      duration: 3000,
      builder: (data, point, series, pointIndex, seriesIndex) {
        if (pointIndex == dataPointIndex) {
          return Container(
            height: 50.0,
            width: 50.0,
            color: Colors.blue,
          );
        } else {
          _tooltipBehavior.hide();
          return Container();
        }
      },
    );
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Stack(
          children: [
            SfCartesianChart(
              margin: _chartPadding,
              primaryXAxis: NumericAxis(),
              primaryYAxis: NumericAxis(),
              series: <CartesianSeries<ChartSampleData, num>>[
                LineSeries<ChartSampleData, num>(
                  onPointTap: (ChartPointDetails details) {
                    dataPointIndex = details.pointIndex;
                    seriesIndex = details.seriesIndex;
                    CartesianChartPoint point = CartesianChartPoint(
                        details.dataPoints![details.pointIndex!].x,
                        details.dataPoints![details.pointIndex!].y);
                    position.value = _controller.pointToPixel(point);
                    Timer(const Duration(milliseconds: 3000), () {
                      position.value = null;
                    });
                  },
                  onRendererCreated: (controller) {
                    _controller = controller;
                  },
                  dataSource: _data,
                  enableTooltip: true,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y,
                  color: Colors.blue,
                ),
              ],
              tooltipBehavior: _tooltipBehavior,
            ),
            ValueListenableBuilder(
              valueListenable: position,
              builder: (BuildContext context, Offset? value, Widget? child) {
                if (position.value != null) {
                  SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
                    _tooltipBehavior.showByIndex(
                        seriesIndex ?? 0, dataPointIndex ?? 0);
                  });
                }
                return CustomPaint(
                  painter: Marker(position.value, _chartPadding),
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
Also shared the sample and recording below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[489005.zip](https://github.com/syncfusion/flutter-widgets/files/12341063/489005.zip)
[_489005.zip](https://github.com/syncfusion/flutter-widgets/files/12341066/_489005.zip)
