### ISSUE TITLE
[syncfusion_flutter_pdf]Potential Null Reference Error in pdf_pkcs_certificate.dart

### ISSUE THREAD

**Issue by motucraft** [syncfusion/flutter-widgets#1323]
I've identified a potential issue in the file pdf_pkcs_certificate.dart, specifically in this section:

```dart
      if (mechanism != null && mechanism!.startsWith('PBEwithMD2') ||
          mechanism!.startsWith('PBEwithMD5') ||
          mechanism!.startsWith('PBEwithSHA-1') ||
          mechanism!.startsWith('PBEwithSHA-256')) {
        if (mechanism!.endsWith('AES-CBC-BC') ||
            mechanism!.endsWith('AES-CBC-OPENSSL')) {
          result = _cipherUtils.getCipher('AES/CBC');
        } else if (mechanism!.endsWith('DES-CBC')) {
          result = _cipherUtils.getCipher('DES/CBC');
        } else if (mechanism!.endsWith('DESEDE-CBC')) {
          result = _cipherUtils.getCipher('DESEDE/CBC');
        } else if (mechanism!.endsWith('RC2-CBC')) {
          result = _cipherUtils.getCipher('RC2/CBC');
        } else if (mechanism!.endsWith('RC4')) {
          result = _cipherUtils.getCipher('RC4');
        }
      }
```

This code has the potential to throw "Unhandled Exception: Null check operator used on a null value" if mechanism is null. 

Link to the file: [pdf_pkcs_certificate.dart](https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_pdf/lib/src/pdf/implementation/security/digital_signature/pdf_pkcs_certificate.dart#L738)

**Comment by irfanajaffer** [comment]
We have included the fix for the reported issue in our latest weekly release (22.2.10). Please use the below link to download our latest NuGet,



https://pub.dev/packages/syncfusion_flutter_pdf/versions/22.2.10
