### ISSUE TITLE
How to override "Fit Width" previous behavior in new update?

### ISSUE THREAD

**Issue by ahmeedev** [syncfusion/flutter-widgets#1324]
Reference Fix [22.1.34]:- Support for loading the pages with the width fitted on the Windows and Web platforms has been provided.

I want the old version's behavior, but I'm not able to find any parameters by which I can achieve that functionality.

**Comment by deepika134** [comment]
In SfPdfViewer, the PDF document is loaded with the fitted width on the Windows and web platforms. This is the default behavior of SfPdfViewer. Currently, there is no API available to override this behavior. kindly share your complete requirements and use case. This will be helpful for us to proceed further.

**Comment by ahmeedev** [comment]
i just want to fit pdf on the available space in my widget. but, it show zoom view of the pdf rather after the update.

**Comment by ramkumarsync** [comment]
As mentioned earlier, we have provided support for fit width in the Windows and web platforms. This feature allows the PDF pages to be loaded with the width fitted, and it is a default functionality of the PDF viewer. It is important to note that this is not a zoom view.
 
However, in the single-page layout, we have not provided support for fit width. In this layout, the pages are displayed with their original document width and height on desktop platforms. For more information about the single-page layout option in PDF Viewer, please refer to the following link:
 
https://help.syncfusion.com/flutter/pdf-viewer/page-layout-and-scroll-direction#single-page-layout-mode
