### ISSUE TITLE
View.of(context).viewInsets.bottom != 0.0;

### ISSUE THREAD

**Issue by therasuldev** [syncfusion/flutter-widgets#1329]
Launching lib/main.dart on sdk gphone arm64 in debug mode...
: Error: Member not found: 'EdgeInsets.fromViewPadding'.
                        double keyPadHeight = EdgeInsets.fromViewPadding(
                                                         ^^^^^^^^^^^^^^^
: Error: The getter 'View' isn't defined for the class 'SfPdfViewerState'.
- 'SfPdfViewerState' is from 'package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart' ('../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-21.2.10/lib/src/pdfviewer.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'View'.
                          View.of(context).viewInsets.bottom != 0.0;
                          ^^^^

Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script '/Users/rasulramixanov/FlutterDev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1157

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/rasulramixanov/FlutterDev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 10s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

**Comment by deepika134** [comment]
kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.

Flutter SDK setup link for the latest version:  https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk
