### ISSUE TITLE
nullsafety plans

### ISSUE THREAD

**Issue by Coimbra1984** [syncfusion/flutter-widgets#133]
Hello,
do you have any plans to migrate to nullsafety? You are the last missing package in my project which prevents me from migrating.

**Comment by JayavigneshwaranG** [comment]
Hi @Coimbra1984 ,

We have analyzed your query and we wish to let you know that, we have planned to provide null-safety support for our packages before our 2021 Volume 1 SP 1 release. It can be expected to roll out at the beginning of May 2021.
We appreciate your patience until then and let us know if you have any other concerns.

Thanks,
Jayavigneshwaran

**Comment by tneotia** [comment]
May seems a bit far out considering Dart 2.12 just landed stable with nullsafety. I would like my app to be on sound null-safety but it will be a blocker if these libraries are not migrated until May. 

I would try to help with PRs but I have no knowledge of the code here to make sure I am making the correct assumptions when migrating.

**Comment by Dharanipalani** [comment]
Hi @tneotia,

We are analyzing the timeline for providing null safety support for all our widgets. And thus, will update you on the status in two business days (9th March 2021), we appreciate your patience till then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hello All,

Thanks for being patience and we are glad to inform you that we will provide null safety support to all our widgets in the upcoming volume1 main release itself which is expected to be rolled out at the end of March 2021. We appreciate your patience till then.

Thanks,
Dharanitharan. P

**Comment by netgfx** [comment]
Thank you for this, your package is one of the best looking out there! Keep up the good work!
Looking forward for the next release.

**Comment by Dharanipalani** [comment]
Hi All,

Thanks for being patience. We are glad to inform you that we have provided null safety support to all our widgets and rolled out in our main release. To use this, please upgrade our charts to the latest version from the below link.

**Latest version:** [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1)

Thanks,
Dharanitharan. P
