### ISSUE TITLE
How do I remove the numbers that come with my system

### ISSUE THREAD

**Issue by haoxuhong** [syncfusion/flutter-widgets#1330]
![WechatIMG45](https://github.com/syncfusion/flutter-widgets/assets/18694420/c40edafe-d62f-4394-98e8-b610e0a0cda2)

How do I remove the numbers that come with my system

**Comment by sfHariHaraSudhan** [comment]
Hi @haoxuhong,

You can achieve the mentioned requirement by modifying the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback according to your needs. In this case, we have implemented a [Bar Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSeries-class.html) and we are displaying the x axis labels only when the value of the data point is 1. For all other values, we are using an empty string to hide the rest of the x axis labels, as shown in the snippet below.
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;

  @override
  void initState() {
    _data = [
      ChartSampleData(01, 01),
      ChartSampleData(02, 02),
      ChartSampleData(03, 03),
      ChartSampleData(04, 04),
      ChartSampleData(05, 05),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfCartesianChart(
          primaryXAxis: NumericAxis(
            visibleMinimum: 0,
            visibleMaximum: 6,
            interval: 1,
            majorTickLines: const MajorTickLines(width: 0),
            axisLine: const AxisLine(width: 0),
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              if (details.value == 1) {
                return ChartAxisLabel('first value', details.textStyle);
              } else {
                return ChartAxisLabel('', details.textStyle);
              }
            },
          ),
          primaryYAxis: NumericAxis(),
          series: <CartesianSeries<ChartSampleData, num>>[
            BarSeries(
              dataSource: _data,
              xValueMapper: (ChartSampleData sales, _) => sales.x,
              yValueMapper: (ChartSampleData sales, _) => sales.y,
            ),
          ],
        ),
      ),
    );
  }
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/a90ebf18-4a6a-4772-993b-753bbf51b8ed)

Also shared the sample below for your reference and you can modify the sample based on your requirements. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by haoxuhong** [comment]
好的，谢谢，解决了我的问题
