### ISSUE TITLE
[syncfusion_flutter_charts] Improve performance Column chart

### ISSUE THREAD

**Issue by XuanTung95** [syncfusion/flutter-widgets#1331]
At these block of code in `column_painter.dart`
``` dart
      for (int pointIndex = 0; pointIndex < dataPoints.length; pointIndex++) {
        point = dataPoints[pointIndex];
        final bool withInXRange =
            withInRange(point.xValue, seriesRendererDetails.xAxisDetails!);
        // ignore: unnecessary_null_comparison
        final bool withInYRange = point != null &&
            point.yValue != null &&
            withInRange(point.yValue, seriesRendererDetails.yAxisDetails!);
        if (withInXRange || withInYRange) {
          seriesRendererDetails.calculateRegionData(stateProperties,
              seriesRendererDetails, painterKey.index, point, pointIndex);
          if (point.isVisible && !point.isGap) {
            seriesRendererDetails.drawSegment(
                canvas,
                seriesRenderer._createSegments(point, segmentIndex += 1,
                    painterKey.index, animationFactor));
          }
        }
      }
```

It will paint the column `if (withInXRange || withInYRange)`.
I think only `withInXRange` is needed, if include `withInYRange`, it might paint columns that are outside of the viewport.
Example: 100 columns, 20 column is visible, but 100 columns may satisfy `withInYRange`

**Comment by sfHariHaraSudhan** [comment]
Hi @XuanTung95,

We have analyzed your query and would like to inform you that we have considered both withInXRange and withInYRange based on the [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) property. The [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) property has a default value of true, which means that the range of the y axis is calculated based on the visible data points, therefore only values greater than the visible minimum and lesser than the visible maximum will be considered. However, when you set the [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) property to false, the range of the y axis will be calculated based on all the data points provided.

If you have any further queries, please let us know.

Regards,
Hari Hara Sudhan. K.

**Comment by XuanTung95** [comment]
Hi @sfHariHaraSudhan,

Sorry, I'm still confused.

As I understand, the bloc of code above is related to drawing the column, if the column is not visible (not withInXRange) there is no need to draw it, right?
About the `anchorRangeToVisiblePoints` I think this can be determined using the data, without the need to draw all column?
And as you said, if set `anchorRangeToVisiblePoints` = false, the range is calculated based on ALL the data, but the code is checking `(withInXRange || withInYRange)`, this will not go through all the data point.
Maybe I'm missing something?

**Comment by ekuleshov** [comment]
It even worse when you have to draw the entire dataset. See issue https://github.com/syncfusion/flutter-widgets/issues/1362

**Comment by LokeshPalani** [comment]
Hi @XuanTung95,
 
We have made some performance improvements in our **Volume 4 Main Release** in 2023. Therefore, we kindly request that you upgrade the **syncfusion_flutter_chart**s package to the latest version provided below.
 
**Version Link:**
https://pub.dev/packages/syncfusion_flutter_charts/versions/24.2.4+3
 
Please try the above-mentioned chart version and let us know the result.
 
Regards,
Lokesh P.

**Comment by XuanTung95** [comment]
Hi @LokeshPalani,

I tested the new version.
The performance is still not optimized in the case where the amount of data is large but the number of data in the viewport is small.

**Comment by LokeshPalani** [comment]
Hi @XuanTung95,

The following are the key points that can be used to boost the performance of the chart when there is a need to plot high volume data.
 

- Use [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) or [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/DateTimeAxis.html) instead of [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/CategoryAxis.html).
- Set [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) to false in both axes so that the axis range will be calculated based on the visible data points when zooming.
- Set series [animationDuration](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/animationDuration.html) as 0 to disable the animation while loading large number of data points.
- Use [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method while updating dynamic data points instead of calling setState. For more details refer ug -  https://help.syncfusion.com/flutter/cartesian-charts/methods#updatedatasource.
- Use On-demand loading while rendering large data points, it can be used to load more data to the chart when the visible range reaches the end on dragging in the chart.  https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading

 
Regards,
Lokesh P.

**Comment by XuanTung95** [comment]
Hi @LokeshPalani 

Thanks for your support.

I tried to change from `CategoryAxis` to `NumericAxis` as you suggested, and the performance does improve dramatically, about 10 ~ 20 times faster. The other suggestions do not improve much.

But I still need to display text on the X axis, not the number, and I cannot find a way to show text the same as CategoryAxis does while using NumericAxis. So is there a way I can keep the good performance of `NumericAxis` and still show the custom text on the X axis?

I imagine this is trivial, the X axis already displays numbers as text, I only need a way to convert that number to a custom text. E.g. "1", "2", "3" => "red", "green", "blue"

**Comment by XuanTung95** [comment]
@ekuleshov 

`NumericAxis.axisLabelFormatter` does not work as expected because `NumericAxis` is not showing axisLabel the same way `CategoryAxis` does. For example: there are 3 columns: "0", "1", "2", when I zoom in, `NumericAxis` will increase the number of axisLabel to "0", "0.5", "1", "1.5" , "2". On the other hand, CategoryAxis only shows 3 labels "red", "green", "blue"

**Comment by ekuleshov** [comment]
> `NumericAxis` is not showing axisLabel the same way `CategoryAxis` does...

Yes. Hence the need to map the `value` to your data. e.g use rounding if needed. Can also set `NumericAxis .interval` to 1.

But I also find decimal values in `NumericAxis` unexpected and unnecessary, even when zoom is used. Especially for the column chart.

**Comment by XuanTung95** [comment]
@ekuleshov 

`NumericAxis .interval to 1` does not work, the number of axisLabel still increase.
If you still think `NumericAxis` can display the label the same as `CategoryAxis`, can you give me the full example code?

**Comment by ekuleshov** [comment]
I don't have an example code and it all depends on your chart's data source. Like I said, you can round decimal values to ints in order to get X-axis index to your data source.

**Comment by LokeshPalani** [comment]
Hi @ekuleshov,

You can achieve your requirement by setting [enableAutoIntervalOnZooming](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/enableAutoIntervalOnZooming.html) to false in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). By doing this, you can avoid interval calculation on zooming and the specified interval will be calculated without any intermediate intervals. Please let us know if you need any further assistance.

Regards,
Lokesh P.

**Comment by XuanTung95** [comment]
Hi @LokeshPalani 

For now, using `NumericAxis` for better performance and trying to modify the code to make it look like `CategoryAxis` might work.
But it is ugly and not user-friendly at all.
I think it's better to find a way to improve CategoryAxis's performance rather than work around it.
I would be glad if you have a plan to improve it in the future.

**Comment by XuanTung95** [comment]
Hi @PreethikaSelvam,

OK.
How about improving `NumericAxis` by adding custom label mapping?
```
ColumnSeries<ChartData, int>(
        xValueMapper: (ChartData data, _) => data.index,
        yValueMapper: (ChartData data, _) => data.value,
        xLabelMapper: (ChartData data, _) => data.name,   <= add this option to show "red", "blue", "green" instead of 1,2,3
)
```
or provide `ChartData data` in `NumericAxis.axisLabelFormatter` so I can provide `data.name` in the `ChartAxisLabel`

**Comment by XuanTung95** [comment]
@PreethikaSelvam 

Thanks, I think we can close this.
