### ISSUE TITLE
 'PointerPanZoomUpdateEvent' isn't a type.     } else if (event is PointerPanZoomUpdateEvent) {

### ISSUE THREAD

**Issue by sinhashruti18** [syncfusion/flutter-widgets#1336]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:44: Error: 'PointerPanZoomUpdateEvent' isn't a type.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/base/chart_base.dart:2420:19: Error: No named parameter with the name 'onPointerPanZoomUpdate'.
                  onPointerPanZoomUpdate: (PointerPanZoomUpdateEvent event) {
                  ^^^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/basic.dart:6053:9: Context: Found this candidate, but the arguments don't match.
  const Listener({
        ^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-21.2.4/lib/src/chart/user_interaction/zooming_panning.dart:1021:25: Error: 'PointerPanZoomUpdateEvent' isn't a type.
    } else if (event is PointerPanZoomUpdateEvent) {
this issue always throw in my code

**Comment by sfHariHaraSudhan** [comment]
Hi @sinhashruti18

We suspect that the mentioned exception might occur while performing the mouse wheel zooming based on the provided call stack and tried to replicate the mentioned exception by implementing a simple sample, but Unfortunately, we are unable to replicate the exception from our end, and it is working properly.

We have checked with [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html), [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html), and [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We also tried zooming by enabling and disabling the following properties: [enableMouseWheelZooming](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enableMouseWheelZooming.html), [enablePanning](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enablePanning.html), and [enablePinching](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enablePinching.html). Additionally, we checked the [zoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomMode.html) property to zoom only in the horizontal or vertical direction, as well as in both directions.

We recommend that you share some additional details regarding the specific case in which the exception occurs or provide steps to reproduce the mentioned exception in the attached sample below. With this additional information, it will be very helpful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.
[_490833.zip](https://github.com/syncfusion/flutter-widgets/files/12341085/_490833.zip)

**Comment by Kalela** [comment]
For me. This is happening when I attempt to build my apk with the following pubspec.yaml
```
name: appname
description: App description

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.5+25

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Package Imports
  flutter_svg: ^0.22.0
  google_fonts: 2.2.0
  local_auth: ^1.1.9
  flutter_remix: ^0.0.3
  shared_preferences: ^2.0.7
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  syncfusion_flutter_datepicker: ^20.4.38
  image_picker: ^0.8.4+1
  image_cropper: ^1.4.1
  cached_network_image: ^3.1.0+1
  syncfusion_flutter_charts: ^20.4.38
  move_to_background: ^1.0.2
  pin_code_fields: ^7.3.0
  modal_bottom_sheet: ^2.0.0
  intl_phone_number_input: ^0.7.0+2
  intl_phone_field: ^3.1.0
  dart_date: ^1.1.0
  dio: ^4.0.4
  flutter_image_compress: ^1.1.0
  webview_flutter: ^3.0.1
  pdf: ^3.6.0
  path_provider: ^2.0.4
  open_file: ^3.3.0
  intl: ^0.17.0
  flutter_stripe: ^8.0.0
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  url_launcher: ^6.0.17
  in_app_purchase: ^3.0.7
  pubnub: ^4.1.0
  flutter_rating_bar: ^4.0.0
  screenshot: ^1.2.3
  d_chart: ^0.0.4
  syncfusion_flutter_xlsio: ^20.4.38-beta
  easy_localization: ^3.0.0
  palette_generator:
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  carousel_pro: ^1.0.0
  shimmer: ^2.0.0




dev_dependencies:
  # flutter_test:
  #   sdk: flutter

  flutter_native_splash: ^1.2.1
  build_runner:
  freezed: ^2.2.0
  json_serializable: ^6.1.2

  flutter_lints: 

flutter:
  uses-material-design: true
...
``` .
I am running flutter 3.0.0 using fvm

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
