### ISSUE TITLE
Infinite Scrolling is not working effectively

### ISSUE THREAD

**Issue by tuceturan** [syncfusion/flutter-widgets#1339]
Hello ,

I'ım using Infinite scrolling .I have 6 different serie and 8200 data but there is a problem  

My Code;

/// dart import
import 'dart:math';

/// Package import
import 'package:flutter/material.dart';

/// Chart import
import 'package:syncfusion_flutter_charts/charts.dart';

import '../../../commands/get_waveform_command.dart';
import '../../../controller/language_controller.dart';
import '../../../helper/syncfusion_helper/barChart/chart_sample_data.dart';

/// Local imports
//import '../../../../model/sample_view.dart';

/// Renders the chart with default trackball sample.
class InfiniteScrolling extends StatefulWidget {
  final GetWaveformCommand waveForm;

  /// Creates the chart with default trackball sample.
  InfiniteScrolling(Key key, this.waveForm) : super(key: key);

  @override
  _InfiniteScrollingState createState() => _InfiniteScrollingState();
}

/// State class the chart with default trackball.
class _InfiniteScrollingState extends State<InfiniteScrolling> {
  _InfiniteScrollingState();

  ChartSeriesController seriesController;
  List<List<ChartSampleData>> waveChartData = [];

  bool isLoadMoreView, isNeedToUpdateView, isDataUpdated;

  double oldAxisVisibleMin, oldAxisVisibleMax;

  ZoomPanBehavior _zoomPanBehavior;

  GlobalKey<State> globalKey;

  String _txt = "";
  String _txt2 = "";
  int bolen = 0;
  int bolen2 = 0;
  List<ChartSampleData> chartData1, chartData2, chartData3;
  int _rangeStart = 0;
  int _rangeEnd = 400;

  @override
  void initState() {
    chartData1 = [];
    chartData2 = [];
    chartData3 = [];
    _initializeVariables();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return _buildInfiniteScrollingChart();
  }

  void _initializeVariables() {
    setWaveformData();
    isLoadMoreView = false;
    isNeedToUpdateView = false;
    isDataUpdated = true;
    globalKey = GlobalKey<State>();
    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
    );
  }

  /// Returns the cartesian chart with default trackball.
  SfCartesianChart _buildInfiniteScrollingChart() {
    return SfCartesianChart(
        key: GlobalKey<State>(),
        zoomPanBehavior: _zoomPanBehavior,
        plotAreaBorderWidth: 0,
        legend: Legend(
            isVisible: true,
            position: LegendPosition.top,
            textStyle: TextStyle(fontSize: 15)),
        loadMoreIndicatorBuilder:
            (BuildContext context, ChartSwipeDirection direction) =>
                getloadMoreIndicatorBuilder(context, direction),
        onActualRangeChanged: (ActualRangeChangedArgs args) {
          if (args.orientation == AxisOrientation.horizontal) {
            if (isLoadMoreView) {
              args.visibleMin = oldAxisVisibleMin;
              args.visibleMax = oldAxisVisibleMax;
            }
            oldAxisVisibleMin = args.visibleMin as double;
            oldAxisVisibleMax = args.visibleMax as double;
          }
          isLoadMoreView = false;
        },
        axes: <ChartAxis>[
          NumericAxis(
            title: AxisTitle(
                text: TranslateLanguage.of(context).trans('voltage') +
                    "[" +
                    _txt +
                    "V]",
                alignment: ChartAlignment.center),
            opposedPosition: true,
            name: 'Voltage',
            // anchorRangeToVisiblePoints: false,
            placeLabelsNearAxisLine: true,
            isVisible: true,
            axisLabelFormatter: (AxisLabelRenderDetails args) {
              return ChartAxisLabel(args.value.toStringAsFixed(5),
                  TextStyle(color: const Color.fromRGBO(104, 104, 104, 1)));
            },
            //  interval:(_txt=="k") ? 3000 : (_txt=="M") ? 1000000 :100
          )
        ],
        primaryXAxis: NumericAxis(
          //name: 'XAxis',
          interval: 50,
          isVisible: true,
          crossesAt: 0,
          enableAutoIntervalOnZooming: false,
          edgeLabelPlacement: EdgeLabelPlacement.shift,
          majorGridLines: const MajorGridLines(width: 0),
          majorTickLines: MajorTickLines(size: 0, width: 0),
        ),
        primaryYAxis: NumericAxis(
            title: AxisTitle(
                text: TranslateLanguage.of(context).trans('current') +
                    "[" +
                    _txt2 +
                    "A]",
                alignment: ChartAlignment.center),
            majorGridLines: const MajorGridLines(width: 0),
            opposedPosition: false,
            axisLabelFormatter: (AxisLabelRenderDetails args) {
              return ChartAxisLabel(args.value.toStringAsFixed(2),
                  TextStyle(color: const Color.fromRGBO(104, 104, 104, 1)));
            }),
        // series: getSeries(),
        series: getMultipleAxisLineSeriesDevice(),
        trackballBehavior: TrackballBehavior(
          enable: true,
          lineType: TrackballLineType.none,
          activationMode: ActivationMode.singleTap,
          // tooltipSettings: const InteractiveTooltip(canShowMarker: false),
          markerSettings: TrackballMarkerSettings(
            markerVisibility: TrackballVisibilityMode.visible,
            height: 10,
            width: 10,
            borderWidth: 1,
          ),
          tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
        ));
  }

  //WaveFormSeries
  List<ChartSeries<ChartSampleData, dynamic>>
      getMultipleAxisLineSeriesDevice() {
    List<Color> _colorList = [
      Color.fromRGBO(155, 31, 33, 100),
      Color.fromRGBO(255, 103, 106, 100),
      Color.fromRGBO(37, 101, 39, 100),
      Color.fromRGBO(99, 196, 101, 100),
      Color.fromRGBO(55, 104, 155, 100),
      Color.fromRGBO(150, 194, 236, 100)
    ];
    List<ChartSeries<ChartSampleData, dynamic>> _series = [];
    int j = 0;
    for (int i = 0; i < waveChartData.length; i++) {
      _series.add(FastLineSeries(
          dataSource: waveChartData[i],
          xValueMapper: (ChartSampleData sales, _) => sales.x,
          yValueMapper: (ChartSampleData sales, _) => sales.y,
          yAxisName: 'Voltage',
          name: 'VL' + (i + 1).toString(),
          color: _colorList[j],
          animationDuration: 0,
          onRendererCreated: (ChartSeriesController controller) {
            seriesController = controller;
          },
          selectionBehavior: SelectionBehavior(enable: true)));
      j += 2;
    }
    j = 0;
    for (int i = 0; i < waveChartData.length; i++) {
      _series.add(FastLineSeries<ChartSampleData, dynamic>(
          dataSource: waveChartData[i],
          xValueMapper: (ChartSampleData sales, _) => sales.x,
          yValueMapper: (ChartSampleData sales, _) => sales.secondSeriesYValue,
          yAxisName: 'Current',
          animationDuration: 0,
          name: 'IL' + (i + 1).toString(),
          selectionBehavior: SelectionBehavior(enable: true),
          onRendererCreated: (ChartSeriesController controller) {
            seriesController = controller;
          },
          color: _colorList[j + 1]));
      j += 2;
    }
    return _series;
  }

  Widget getloadMoreIndicatorBuilder(
      BuildContext context, ChartSwipeDirection direction) {
    if (direction == ChartSwipeDirection.end) {
      isNeedToUpdateView = true;
      globalKey = GlobalKey<State>();
      return StatefulBuilder(
          key: globalKey,
          builder: (BuildContext context, StateSetter stateSetter) {
            Widget widget;
            if (isNeedToUpdateView) {
              widget = getProgressIndicator();
              _updateView();
              isDataUpdated = true;
            } else {
              widget = Container();
            }
            return widget;
          });
    } else {
      return SizedBox.fromSize(size: Size.zero);
    }
  }

  Widget getProgressIndicator() {
    return Align(
        alignment: Alignment.centerRight,
        child: Padding(
            padding: const EdgeInsets.only(bottom: 22),
            child: Container(
                width: 50,
                alignment: Alignment.centerLeft,
                decoration: BoxDecoration(
                  gradient: LinearGradient(colors: <Color>[
                    Colors.white.withOpacity(0.0),
                    Colors.white.withOpacity(0.74)
                  ], stops: const <double>[
                    0.0,
                    1
                  ]),
                ),
                child: SizedBox(
                    height: 35,
                    width: 35,
                    child: CircularProgressIndicator(
                      valueColor: AlwaysStoppedAnimation<Color>(
                          Colors.lightGreenAccent),
                      backgroundColor: Colors.transparent,
                      strokeWidth: 3,
                    )))));
  }

  void _updateData() {
    _rangeStart = _rangeEnd;
    _rangeEnd += 200;
    double _vVal = 0;
    double _cVal = 0;
    for (int i = _rangeStart; i < _rangeEnd; i++) {
      _vVal = widget.waveForm.vRRmsValues[i];
      _cVal = widget.waveForm.iRRmsValues[i];

      chartData1.add(ChartSampleData(
          x: chartData1[chartData1.length - 1].x + 1,
          y: _vVal,
          secondSeriesYValue: _cVal,
          text: ""));

      _vVal = widget.waveForm.vSRmsValues[i];
      _cVal = widget.waveForm.iSRmsValues[i];

      chartData2.add(ChartSampleData(
          x: chartData2[chartData2.length - 1].x + 1,
          y: _vVal,
          secondSeriesYValue: _cVal,
          text: ""));

      _vVal = widget.waveForm.vTRmsValues[i];
      _cVal = widget.waveForm.iTRmsValues[i];

      chartData3.add(ChartSampleData(
          x: chartData3[chartData3.length - 1].x + 1,
          y: _vVal,
          secondSeriesYValue: _cVal,
          text: ""));
    }
    waveChartData[0] = chartData1;
    waveChartData[1] = chartData2;
    waveChartData[2] = chartData3;

    isLoadMoreView = true;
    seriesController.updateDataSource(
      addedDataIndexes: getIndexes(200),
      // removedDataIndexes: getIndexesRemove(200)
    );
  }

  Future<void> _updateView() async {
    await Future<void>.delayed(const Duration(seconds: 1), () {
      isNeedToUpdateView = false;
      if (isDataUpdated) {
        _updateData();
        isDataUpdated = false;
      }
      if (globalKey.currentState != null) {
        (globalKey.currentState as dynamic).setState(() {});
      }
    });
  }

  List<int> getIndexes(int length) {
    final List<int> indexes = <int>[];
    for (int i = length - 1; i >= 0; i--) {
      indexes.add(chartData1.length - 1 - i);
    }
    return indexes;
  }

/*
  List<int> getIndexesRemove(int length) {
    final List<int> indexes = <int>[];
    for (int i = chartData1.length - 600; i < chartData1.length - 400; i++) {
      indexes.add(chartData1.length + i);
      indexes.add(chartData2.length + i);
      indexes.add(chartData3.length + i);
    }
    return indexes;
  }
*/
  int getRandomInt(int min, int max) {
    final Random random = Random();
    final int result = min + random.nextInt(max - min);
    return result < 50 ? 95 : result;
  }

  @override
  void dispose() {
    seriesController = null;
    super.dispose();
  }

  void setWaveformData() {
    double _maxValue = widget.waveForm.vRRmsValues.reduce(max);
    _maxValue = (widget.waveForm.vSRmsValues.reduce(max) > _maxValue
        ? widget.waveForm.vSRmsValues.reduce(max)
        : _maxValue);
    _maxValue = (widget.waveForm.vTRmsValues.reduce(max) > _maxValue
        ? widget.waveForm.vTRmsValues.reduce(max)
        : _maxValue);
    double _maxValue2 = widget.waveForm.iRRmsValues.reduce(max);
    _maxValue2 = (widget.waveForm.iSRmsValues.reduce(max) > _maxValue2
        ? widget.waveForm.iSRmsValues.reduce(max)
        : _maxValue2);
    _maxValue2 = (widget.waveForm.iTRmsValues.reduce(max) > _maxValue2
        ? widget.waveForm.iTRmsValues.reduce(max)
        : _maxValue2);

    setChartData(_maxValue, _maxValue2);
  }

  void setWaveData2(List<double> _vValues, List<double> _cValues,
      double _minVal, double _minVal2) {
    if (waveChartData.length == 3) waveChartData = [];
    List<ChartSampleData> _chartData = [];

    for (int i = _rangeStart; i < _rangeEnd; i++) {
      _chartData.add(ChartSampleData(
          x: i, y: _vValues[i], secondSeriesYValue: _cValues[i], text: ""));
    }

    waveChartData.add(_chartData);
  }

  void setChartData(double _minVal, double _minVal2) {
    if (waveChartData.length == 3) waveChartData = [];

    for (int i = _rangeStart; i < _rangeEnd; i++) {
      _vVal = widget.waveForm.vRRmsValues[i];
      _cVal = widget.waveForm.iRRmsValues[i];

      chartData1.add(
          ChartSampleData(x: i, y: _vVal, secondSeriesYValue: _cVal, text: ""));
    }
    for (int i = _rangeStart; i < _rangeEnd; i++) {
      _vVal = widget.waveForm.vSRmsValues[i];
      _cVal = widget.waveForm.iSRmsValues[i];
  
      chartData2.add(
          ChartSampleData(x: i, y: _vVal, secondSeriesYValue: _cVal, text: ""));
    }
    for (int i = _rangeStart; i < _rangeEnd; i++) {
      _vVal = widget.waveForm.vTRmsValues[i];
      _cVal = widget.waveForm.iTRmsValues[i];

      chartData3.add(
          ChartSampleData(x: i, y: _vVal, secondSeriesYValue: _cVal, text: ""));
    }

    waveChartData.add(chartData1);
    waveChartData.add(chartData2);
    waveChartData.add(chartData3);
  }
}
 
First screen 
![Screenshot_20230814-102445 1](https://github.com/syncfusion/flutter-widgets/assets/47599661/1a7b273f-5a43-452c-8f80-5787a91dc0af)

1 scrolling
![Screenshot_20230814-102453 1](https://github.com/syncfusion/flutter-widgets/assets/47599661/16736733-e60b-4a29-bc9a-fd654bfad0d1)

and second
![Screenshot_20230814-102500 1](https://github.com/syncfusion/flutter-widgets/assets/47599661/9f1925d0-b3a7-4fc0-807b-2562d51fbe82)

**Comment by sfHariHaraSudhan** [comment]
Hi @tuceturan,

We have prepared a sample based on the provided code snippet with six series, each containing 200 random data points, at load time. Additionally, we have updated another 200 random data points using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method while scrolling the chart to the end with the help of [loadMoreIndicator](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/loadMoreIndicatorBuilder.html) property. Unfortunately, we have not faced any issues with infinite scrolling, and we are unable to replicate the behavior described using the provided code snippet. 

Kindly refer the code snippet below:
```
class _MainAppState extends State<MainApp> {
  final List<_ChartSampleData> _chartData1 = [];
  final List<_ChartSampleData> _chartData2 = [];
  final List<_ChartSampleData> _chartData3 = [];
  late ChartSeriesController _seriesController;
  late bool isLoadMoreView, isNeedToUpdateView, isDataUpdated;
  double? oldAxisVisibleMin, oldAxisVisibleMax;
  late ZoomPanBehavior _zoomPanBehavior;
  late GlobalKey<State> globalKey;
  late Random random;

  @override
  void initState() {
    random = Random();
    for (int i = 0; i < 200; i++) {
      _chartData1.add(
        _ChartSampleData(
          xValue: i,
          yValue: random.nextInt(600),
          secondaryYValue: random.nextInt(800) * 100,
        ),
      );
      _chartData2.add(
        _ChartSampleData(
          xValue: i,
          yValue: random.nextInt(800),
          secondaryYValue: random.nextInt(600) * 100,
        ),
      );
      _chartData3.add(
        _ChartSampleData(
          xValue: i,
          yValue: random.nextInt(400),
          secondaryYValue: random.nextInt(500) * 100,
        ),
      );
    }
    isLoadMoreView = false;
    isNeedToUpdateView = false;
    isDataUpdated = true;

    globalKey = GlobalKey<State>();

    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
    );

    super.initState();
  }

  Widget buildLoadMoreIndicatorView(
      BuildContext context, ChartSwipeDirection direction) {
    if (direction == ChartSwipeDirection.end) {
      isNeedToUpdateView = true;
      globalKey = GlobalKey<State>();
      return StatefulBuilder(
        key: globalKey,
        builder: (BuildContext context, StateSetter stateSetter) {
          Widget widget;
          if (isNeedToUpdateView) {
            widget = getProgressIndicator();
            _updateView();
            isDataUpdated = true;
          } else {
            widget = Container();
          }
          return widget;
        },
      );
    } else {
      return SizedBox.fromSize(size: Size.zero);
    }
  }

  Widget getProgressIndicator() {
    return Align(
      alignment: Alignment.centerRight,
      child: Padding(
        padding: const EdgeInsets.only(bottom: 22),
        child: Container(
          width: 50,
          alignment: Alignment.centerRight,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: <Color>[
                Colors.white.withOpacity(0.0),
                Colors.white.withOpacity(0.74),
              ],
              stops: const <double>[
                0.0,
                1,
              ],
            ),
          ),
          child: const SizedBox(
            height: 35,
            width: 35,
            child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(Colors.lightGreenAccent),
              backgroundColor: Colors.transparent,
              strokeWidth: 3,
            ),
          ),
        ),
      ),
    );
  }

  void _updateData() {
    for (int i = 0; i < 500; i++) {
      _chartData1.add(
        _ChartSampleData(
          xValue: _chartData1[_chartData1.length - 1].xValue! + 1,
          yValue: getRandomInt(0, 600),
          secondaryYValue: getRandomInt(0, 600) * 100,
        ),
      );
      _chartData2.add(
        _ChartSampleData(
          xValue: _chartData2[_chartData2.length - 1].xValue! + 1,
          yValue: getRandomInt(0, 1000),
          secondaryYValue: getRandomInt(0, 1000) * 100,
        ),
      );
      _chartData3.add(
        _ChartSampleData(
          xValue: _chartData3[_chartData3.length - 1].xValue! + 1,
          yValue: getRandomInt(0, 1000),
          secondaryYValue: getRandomInt(0, 1000) * 100,
        ),
      );
    }
    isLoadMoreView = true;
    _seriesController.updateDataSource(
      addedDataIndexes: getIndexes(500),
    );
  }

  List<int> getIndexes(int length) {
    final List<int> indexes = <int>[];
    for (int i = length - 1; i >= 0; i--) {
      indexes.add(_chartData1.length - 1 - i);
    }
    return indexes;
  }

  int getRandomInt(int min, int max) {
    final int result = min + random.nextInt(max - min);
    return result < 50 ? 95 : result;
  }

  Future<void> _updateView() async {
    await Future<void>.delayed(const Duration(seconds: 1), () {
      isNeedToUpdateView = false;
      if (isDataUpdated) {
        _updateData();
        isDataUpdated = false;
      }
      if (globalKey.currentState != null) {
        (globalKey.currentState as dynamic).setState(() {});
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfCartesianChart(
          key: globalKey,
          legend: Legend(
            isVisible: true,
            position: LegendPosition.top,
            textStyle: const TextStyle(fontSize: 15),
          ),
          loadMoreIndicatorBuilder:
              (BuildContext context, ChartSwipeDirection direction) =>
                  buildLoadMoreIndicatorView(context, direction),
          onActualRangeChanged: (ActualRangeChangedArgs args) {
            if (args.orientation == AxisOrientation.horizontal) {
              if (isLoadMoreView) {
                args.visibleMin = oldAxisVisibleMin;
                args.visibleMax = oldAxisVisibleMax;
              }
              oldAxisVisibleMin = args.visibleMin;
              oldAxisVisibleMax = args.visibleMax;
            }
            isLoadMoreView = false;
          },
          primaryXAxis: NumericAxis(
            name: 'XAxis',
            interval: 50,
            isVisible: true,
            crossesAt: 0,
            decimalPlaces: 0,
            enableAutoIntervalOnZooming: true,
            edgeLabelPlacement: EdgeLabelPlacement.shift,
            majorGridLines: const MajorGridLines(width: 0),
            majorTickLines: const MajorTickLines(size: 0, width: 0),
          ),
          primaryYAxis: NumericAxis(
            title: AxisTitle(
              text: 'Current[kA]',
              alignment: ChartAlignment.center,
            ),
            name: 'Current',
            majorGridLines: const MajorGridLines(width: 0),
            opposedPosition: false,
            axisLabelFormatter: (AxisLabelRenderDetails args) {
              return ChartAxisLabel(
                args.value.toStringAsFixed(2),
                const TextStyle(
                  color: Color.fromRGBO(104, 104, 104, 1),
                ),
              );
            },
          ),
          axes: [
            NumericAxis(
              title: AxisTitle(
                text: 'Voltage[kA]',
                alignment: ChartAlignment.center,
              ),
              opposedPosition: true,
              name: 'Voltage',
              placeLabelsNearAxisLine: true,
              isVisible: true,
              axisLabelFormatter: (AxisLabelRenderDetails args) {
                return ChartAxisLabel(
                  args.value.toStringAsFixed(5),
                  const TextStyle(
                    color: Color.fromRGBO(104, 104, 104, 1),
                  ),
                );
              },
            )
          ],
          series: <CartesianSeries<_ChartSampleData, num>>[
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData1,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) => sales.yValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Current',
              color: Colors.red,
            ),
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData1,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) =>
                  sales.secondaryYValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Voltage',
              color: Colors.blue,
            ),
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData2,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) => sales.yValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Current',
              color: Colors.amber,
            ),
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData2,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) =>
                  sales.secondaryYValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Voltage',
              color: Colors.purpleAccent,
            ),
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData3,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) =>
                  sales.secondaryYValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Voltage',
              color: Colors.deepOrangeAccent,
            ),
            FastLineSeries<_ChartSampleData, num>(
              dataSource: _chartData3,
              xValueMapper: (_ChartSampleData sales, _) => sales.xValue,
              yValueMapper: (_ChartSampleData sales, _) =>
                  sales.secondaryYValue,
              onRendererCreated: (controller) {
                _seriesController = controller;
              },
              xAxisName: 'XAxis',
              yAxisName: 'Voltage',
              color: Colors.greenAccent,
            ),
          ],
          zoomPanBehavior: _zoomPanBehavior,
        ),
      ),
    );
  }
}
```
We recommend that you share any recordings and details of the mentioned behavior and modify the sample according to your need to reproduce it. This additional information will be very helpful for us to provide the best possible solution. Also attached the recording below for your reference.

Regards,
Hari Hara Sudhan. K.
[_491816.zip](https://github.com/syncfusion/flutter-widgets/files/12342067/_491816.zip)
[491816.zip](https://github.com/syncfusion/flutter-widgets/files/12342070/491816.zip)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
