### ISSUE TITLE
[Calender] add jalali datePicker 

### ISSUE THREAD

**Issue by imthemobin** [syncfusion/flutter-widgets#1342]
Hi syncfusion team I and other persion developers want to add Jalali date to this package: 
syncfusion_flutter_datepicker

**Comment by IndumathiR-1995** [comment]
Hi,

We have already logged the feature request for “**Providing a support for jalali calendar in the Flutter Date Range Picker (SfDateRangePicker)**”. We will implement this feature in any of our upcoming releases.

Now you can track the status of this feedback from the following link. Please find the feedback from the following link.

**Feedback link:** https://www.syncfusion.com/feedback/24246/providing-a-support-for-jalali-calendar-in-the-flutter-date-range-picker 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
