### ISSUE TITLE
[SfCartesianChart] ToolTip got hidden when realtime plotBand data update in BarChart

### ISSUE THREAD

**Issue by rajkotiyakishan** [syncfusion/flutter-widgets#1343]
Hello Team,

I am facing issue of ToolTip in Bar Chart where I am showing one real time line using Plot Band data. That real time line is continuously updated so when I click on Bar series tooltip open for 1-2 seconds but once plot band data updated tooltip got hidden automatically, If there is no real time data update in plot band then ToolTip show perfectly. Is there any way that I can update only plot band data (don't want to update series data) in background and my ToolTip doesn't hide? 

My requirements is in attached Image.

Thanks.

![WhatsApp Image 2023-08-17 at 9 20 46 AM](https://github.com/syncfusion/flutter-widgets/assets/48147536/c03e6a32-de4f-4508-a0b0-e67bfd0b2ce9)

**Comment by sfHariHaraSudhan** [comment]
Hi @rajkotiyakishan,

You can achieve your mentioned requirement using the [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) method within the addPostFrameCallback method. We have prepared a sample by updating the [PlotBand](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand-class.html) with the real time update and it will stop when the real time update exceeds the [visible maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMaximum.html) of the x axis. Here, we have obtained the [visible maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMaximum.html) of the x axis using the [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) callback and while hovering the [bar series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSeries-class.html), the [series index](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipArgs/seriesIndex.html) and [point index](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipArgs/pointIndex.html) of the current segment will be obtained using the [onTooltipRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onTooltipRender.html) callback. We then pass the [series index](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipArgs/seriesIndex.html) and [point index](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipArgs/pointIndex.html) to the [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) to make the tooltip visible always as shown in the code snippet below.
```
class _MyHomePageState extends State<MyHomePage> {
  late List<ChartSampleData> _data;
  late TooltipBehavior _tooltipBehavior;
  double _value = 0.5;
  int? pointIndex;
  int? seriesIndex;
  double visibleMax = 1;
 
  @override
  void initState() {
    _data = [
      ChartSampleData(x: 01, y: 20),
      ChartSampleData(x: 02, y: 60),
      ChartSampleData(x: 03, y: 20),
      ChartSampleData(x: 04, y: 40),
      ChartSampleData(x: 05, y: 70),
      ChartSampleData(x: 06, y: 30),
      ChartSampleData(x: 07, y: 50),
      ChartSampleData(x: 08, y: 80),
      ChartSampleData(x: 09, y: 60),
      ChartSampleData(x: 10, y: 90),
    ];
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      animationDuration: 0,
      shouldAlwaysShow: true,
    );
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    if (_value < visibleMax) {
      Timer(const Duration(seconds: 1), _updatePlotBand);
    }
 
    return Scaffold(
      body: SfCartesianChart(
        onActualRangeChanged: (rangeChangedArgs) {
          if (rangeChangedArgs.orientation == AxisOrientation.vertical) {
            visibleMax = rangeChangedArgs.visibleMax;
          }
        },
        onTooltipRender: (tooltipArgs) {
          seriesIndex = tooltipArgs.seriesIndex;
          pointIndex = tooltipArgs.pointIndex!.toInt();
        },
        primaryXAxis: NumericAxis(
          plotBands: [
            PlotBand(
              start: _value,
              end: _value,
              borderWidth: 2,
              borderColor: Colors.red,
              dashArray: const <double>[5, 5],
            ),
          ],
        ),
        primaryYAxis: NumericAxis(),
        series: <CartesianSeries<ChartSampleData, num>>[
          BarSeries(
            dataSource: _data,
            xValueMapper: (ChartSampleData sales, int index) => sales.x,
            yValueMapper: (ChartSampleData sales, int index) => sales.y,
          ),
        ],
        tooltipBehavior: _tooltipBehavior,
      ),
    );
  }
 
  void _updatePlotBand() {
    setState(() {
      _value = _value + 1;
    });
    if (seriesIndex != null && pointIndex != null) {
      SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
        _tooltipBehavior.showByIndex(seriesIndex!, pointIndex!);
      });
    }
  }
}
```
Also attached the sample and recording below for your reference and you can modify the sample according to your needs. If you have any queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[492994.zip](https://github.com/syncfusion/flutter-widgets/files/12408117/492994.zip)
[_492994.zip](https://github.com/syncfusion/flutter-widgets/files/12408118/_492994.zip)

**Comment by sfHariHaraSudhan** [comment]
Hi @rajkotiyakishan,

We would like to inform you that currently, in [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), the [PlotBand](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand-class.html) can only be updated by calling the setState method. When the setState method is called, the tooltip will be hidden. Here, we have used the [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) method to make the tooltip always visible. However, due to this, the tooltip will be hidden and then rendered at the specified index using the [TooltipBehavior.showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) method in the addPostFrameCallback method which renders after the current rendering frame is completed. This is the reason for the blinking of the tooltip, and this is the current behavior.

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
