### ISSUE TITLE
Can we create an empty pdf/merge pdfs/split pdf in syncfusion_flutter_pdf

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#1344]
Hi,

pdfbox (Java tool for working with pdf documents) has functionality implemented for creating an empty pdf, splitting a pdf document and merging multiple pdf documents (tutorial links below)

1. https://www.tutorialspoint.com/pdfbox/pdfbox_creating_a_pdf_document.htm
2. https://www.tutorialspoint.com/pdfbox/pdfbox_splitting_a_pdf_document.htm
3. https://www.tutorialspoint.com/pdfbox/pdfbox_merging_multiple_pdf_documents.htm
4. https://pdfium.patagames.com/

I wanted to know if these features are available in syncfusion_flutter_pdf and if yes, how to use them. Could you please let me know?

Thanks & Regards,

**Comment by irfanajaffer** [comment]
As of now, we do not have support to split and merge the pdf documents and we already logged this requirement as a feature request in our library. And we do not have any immediate plans to implement these features and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.     

The status of implementation can be tracked through our Feature Management System:    

https://www.syncfusion.com/feedback/45217/support-to-import-pages-from-existing-pdf-document

**Comment by AjinkyaP1998** [comment]
+1. Need this feature - Merging and splitting the PDF document.

The temporary solution provided has worked well for now.
