### ISSUE TITLE
[syncfusion_flutter_charts] hide trackball when click outside the chart

### ISSUE THREAD

**Issue by komhkomh** [syncfusion/flutter-widgets#1345]
How to hide trackball when click on a part outside the chart and always show trackball when click on chart？

1、When click outside the chart, I call the hide method，but it  only works if shouldAlwaysShow is false.
2、 So I set shouldAlwaysShow to false and ActivationMode to none, then call show method in onChartTouchInteractionUp，but this doesn't work.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

You can achieve your mentioned requirement by enabling the [shouldAlwaysShow](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/shouldAlwaysShow.html) property in the [trackball behavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html) of the chart and by wrapping the GestureDetector widget around the Scaffold. In this case, when we click outside the chart, the trackball will be hidden using the [_trackballBehavior.hide](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/hide.html) method, and when we click inside the chart, the trackball will be visible.

Kindly refer the below code snippet:
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late TrackballBehavior _trackballBehavior;
 
  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(10, 50),
      ChartSampleData(20, 60),
      ChartSampleData(30, 20),
      ChartSampleData(40, 10),
      ChartSampleData(50, 30),
      ChartSampleData(60, 40),
      ChartSampleData(70, 80),
      ChartSampleData(80, 90),
      ChartSampleData(90, 70),
      ChartSampleData(100, 50),
    ];
    _trackballBehavior = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      activationMode: ActivationMode.singleTap,
    );
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: GestureDetector(
        onTap: () {
          _trackballBehavior.hide();
        },
        child: Scaffold(
          body: Center(
            child: SizedBox(
              height: 500,
              width: 500,
              child: SfCartesianChart(
                primaryXAxis: NumericAxis(),
                primaryYAxis: NumericAxis(),
                series: <CartesianSeries<ChartSampleData, num>>[
                  ColumnSeries<ChartSampleData, num>(
                    dataSource: _data,
                    xValueMapper: (ChartSampleData sales, int index) => sales.x,
                    yValueMapper: (ChartSampleData sales, int index) => sales.x,
                  ),
                ],
                trackballBehavior: _trackballBehavior,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
```
Also attached the sample and recording below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[_493279.zip](https://github.com/syncfusion/flutter-widgets/files/12418105/_493279.zip)
[493279.zip](https://github.com/syncfusion/flutter-widgets/files/12418111/493279.zip)

**Comment by komhkomh** [comment]
@sfHariHaraSudhan, thanks for your kindly reply. The method you used did function in the samaple, however, my trackballBehavior used the 'builder' attribute, and I found the trackballBehavior will not hide when  hide() method runs to the part shown in the figure.

![Image_20230905150631](https://github.com/syncfusion/flutter-widgets/assets/65888407/1ef59073-9cf5-412c-bea6-823892c2aacd)

The sample is attached as follows, where _trackballBehavior and _trackballBehavior1 show different hide behavior when _trackballBehavior’s builder is customized and the other one is not.

```class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late TrackballBehavior _trackballBehavior;
  late TrackballBehavior _trackballBehavior1;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(10, 50),
      ChartSampleData(20, 60),
      ChartSampleData(30, 20),
      ChartSampleData(40, 10),
      ChartSampleData(50, 30),
      ChartSampleData(60, 40),
      ChartSampleData(70, 80),
      ChartSampleData(80, 90),
      ChartSampleData(90, 70),
      ChartSampleData(100, 50),
    ];
    _trackballBehavior = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      activationMode: ActivationMode.singleTap,
      builder: (context, trackballDetails) {
        return Container(
          height: 50,
          width: 150,
          decoration: const BoxDecoration(
            color: Color.fromRGBO(0, 8, 22, 0.75),
            borderRadius: BorderRadius.all(Radius.circular(6.0)),
          ),
          child: Row(
            children: [
              Padding(
                  padding: const EdgeInsets.only(left: 5),
                  child: Container(
                    height: 30,
                    width: 30,
                    color: Colors.red,
                  )),
              Center(
                  child: Container(
                      padding: const EdgeInsets.only(top: 11, left: 7),
                      height: 40,
                      width: 100,
                      child: Text(
                          '${trackballDetails.point!.x.toString()} : \$${trackballDetails.point!.y.toString()}',
                          style: const TextStyle(
                              fontSize: 13,
                              color: Color.fromRGBO(255, 255, 255, 1)))))
            ],
          ),
        );
      },
    );
    _trackballBehavior1 = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      activationMode: ActivationMode.singleTap,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: GestureDetector(
        onTap: () {
          _trackballBehavior.hide();
          _trackballBehavior1.hide();
        },
        child: Scaffold(
          body: SingleChildScrollView(
            child: Column(
              children: [
                SizedBox(
                  height: 200,
                  width: 500,
                  child: SfCartesianChart(
                    primaryXAxis: NumericAxis(),
                    primaryYAxis: NumericAxis(),
                    series: <CartesianSeries<ChartSampleData, num>>[
                      ColumnSeries<ChartSampleData, num>(
                        dataSource: _data,
                        xValueMapper: (ChartSampleData sales, int index) =>
                            sales.x,
                        yValueMapper: (ChartSampleData sales, int index) =>
                            sales.x,
                      ),
                    ],
                    trackballBehavior: _trackballBehavior,
                  ),
                ),
                const SizedBox(
                  height: 16,
                ),
                SizedBox(
                  height: 200,
                  width: 500,
                  child: SfCartesianChart(
                    primaryXAxis: NumericAxis(),
                    primaryYAxis: NumericAxis(),
                    series: <CartesianSeries<ChartSampleData, num>>[
                      ColumnSeries<ChartSampleData, num>(
                        dataSource: _data,
                        xValueMapper: (ChartSampleData sales, int index) =>
                            sales.x,
                        yValueMapper: (ChartSampleData sales, int index) =>
                            sales.x,
                      ),
                    ],
                    trackballBehavior: _trackballBehavior1,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

Again, thank you for your patient and time. I am looking forward to your answer.

[hide_trackball_1345.zip](https://github.com/syncfusion/flutter-widgets/files/12520435/hide_trackball_1345.zip)

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

We are able to replicate the reported issue regarding **Hide method is not working properly when we render the trackball using the builder property** at our end and have logged bug report for it in our feedback portal. We will fix and include the changes after the main release which is expected to be rolled out on end of September 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.

Feedback Link: https://www.syncfusion.com/feedback/46888.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

Sorry for the inconvenience. We have fixed this issue but due to automation pending at our end, we are unable to move this fix within the end of September. We will move this issue fix in our upcoming weekly release, which is expected to be rolled out on October 3, 2023. We will update you here once the release is rolled out, and we appreciate your patience until then.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

The reported issue regarding **Hide method is not working properly when we render the trackball using the builder property** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/23.1.39.

Regards,
Hari Hara Sudhan. K.

**Comment by komhkomh** [comment]
@sfHariHaraSudhan, thanks! The issue is fixed after I upgraded the plugin  to the latest version. Thanks for your help! This had been bothering me for a long time. Looking forward to more features in the future.
