### ISSUE TITLE
[syncfusion_flutter_datepicker] v22.2.9 latest - no HijriDateTime object

### ISSUE THREAD

**Issue by msayed-net** [syncfusion/flutter-widgets#1346]
Hello, I'm trying to use `SfHijriDateRangePicker` and trying to define a variable with the correct data type to use with it.

but something is not correct, please review

![Screenshot 2023-08-17 at 10 49 33 AM](https://github.com/syncfusion/flutter-widgets/assets/25801517/9e09b322-db2f-4089-9968-0d70e064b28b)

![Screenshot 2023-08-17 at 10 45 24 AM](https://github.com/syncfusion/flutter-widgets/assets/25801517/5c185100-4f74-4edf-be8a-1dc32437ee4a)

**Comment by IndumathiR-1995** [comment]
Hi Team,

Based on the shared information, we have checked the issue “Unable to use the HijriDateTime in the SfHijriDateRangePicker” and it was working fine as expected from our end. Kindly, import the Syncfusion core package to use the HijriDateTime. We have attached the code snippet for the same. Please find the core snippet from below.

**Code snippet:**

```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';
import 'package:syncfusion_flutter_core/core.dart';

void main() {
  return runApp(const HijriPicker());
}

class HijriPicker extends StatelessWidget {
  const HijriPicker({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Hijri(),
    );
  }
}

class Hijri extends StatefulWidget {
  const Hijri({super.key});

  @override
  _HijriState createState() => _HijriState();
}

class _HijriState extends State<Hijri> {
   HijriDatePickerController _controller = HijriDatePickerController();
  @override void initState() {
 _controller.selectedDate = HijriDateTime.now();
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
      child: SfHijriDateRangePicker( 
        selectionMode: DateRangePickerSelectionMode.single,
            controller: _controller,)
    ));
  }
}
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by msayed-net** [comment]
Hello,

Thank you for your quick respond.

I tried importing core package and worked like a charm, please add this to docs or something to help others.

Thank you again
