### ISSUE TITLE
there is an issue with tooltip

### ISSUE THREAD

**Issue by mahdiqdi** [syncfusion/flutter-widgets#1348]
i want to build my own builder

tooltipBehavior = TooltipBehavior(
      enable: true,
      // opacity: 0.6,
      // textStyle: const TextStyle(fontSize: 8),
      // format: 'point.x\n Today Pnl:point.y',
      // canShowMarker: false,
      builder: (dynamic data, dynamic point, dynamic series, int pointIndex, int seriesIndex) {
        return Container(
            height: 50,
            width: 100,
            decoration: BoxDecoration(
                color: Color.fromRGBO(66, 244, 164, 1)),
                child: Text('$pointIndex')
        );
      }
    );

this is my tooltip as an example
but the problem is that default flash is still in there
when i want to build my own builder there is no need to that flash bottom of tooltip
please take a look at this issue
thanks for your great package

**Comment by sfHariHaraSudhan** [comment]
Hi @mahdiqdi,

We have replicated the mentioned behavior while rendering a custom tooltip using the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property with the provided code snippet, and it can be avoided by setting the same color of the custom tooltip to the color property in the [Tooltip Behavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html), as shown in the code snippet below.
```
class _MainAppState extends State<MainApp> {
  late List<SalesData> salesData;
  late TooltipBehavior _tooltipBehavior;
 
  @override
  void initState() {
    salesData = [
      SalesData(DateTime(2023, 01), 70),
      SalesData(DateTime(2023, 02), 60),
      SalesData(DateTime(2023, 03), 20),
      SalesData(DateTime(2023, 04), 40),
      SalesData(DateTime(2023, 05), 50),
    ];
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      color: const Color.fromRGBO(66, 244, 164, 1),
      builder: (dynamic data, dynamic point, dynamic series, int pointIndex,
          int seriesIndex) {
        return Container(
          height: 50,
          width: 100,
          decoration:
              const BoxDecoration(color: Color.fromRGBO(66, 244, 164, 1)),
          child: Text('$pointIndex'),
        );
      },
    );
 
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfCartesianChart(
          primaryXAxis: DateTimeAxis(
            intervalType: DateTimeIntervalType.months,
          ),
          primaryYAxis: NumericAxis(),
          series: <ChartSeries>[
            ColumnSeries<SalesData, DateTime>(
              dataSource: salesData,
              xValueMapper: (SalesData sales, _) => sales.date,
              yValueMapper: (SalesData sales, _) => sales.sales,
              markerSettings: const MarkerSettings(isVisible: true),
              color: Colors.indigoAccent,
            ),
          ],
          tooltipBehavior: _tooltipBehavior,
        ),
      ),
    );
  }
}
```
Snapshot:

Before setting the color to the color property of the tooltip.
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/8f76f90e-063e-4c2e-8509-abd94d8597cd)

After setting the color to the color property of the tooltip.
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/50d4ed98-e324-485b-a685-244e5b966e5a)

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by mahdiqdi** [comment]
@sfHariHaraSudhan thanks for your answer.it solved my problem

**Comment by sfHariHaraSudhan** [comment]
Hi @mahdiqdi,
 
Most Welcome. Kindly get back to us if you have further queries. We are always happy to assist you.
 
Regards,
Hari Hara Sudhan. K.
