### ISSUE TITLE
How we add x-axis labels and y-axis labels in SfSparkLineChart option. 

### ISSUE THREAD

**Issue by DTharaka** [syncfusion/flutter-widgets#135]
I want to display a monthly earning chart using y-axis label in earning amount ($) and x-axis label in a month. How can I achieve this with SfSparkLineChart widget?

**Comment by Dharanipalani** [comment]
Hi @DTharaka, 
 
Thanks for the interest in our Flutter charts. We would like to inform you that the SparkChart is used for small places and for best performance, so we neglect most of the features like axis labels, etc. If you wish to show the labels, then kindly use our line chart from the [SfCartesianChart](https://help.syncfusion.com/flutter/cartesian-charts/chart-types#line-chart) widget.  To know more about axis types and their customization find the user guide and samples below.
 
User guide: [https://help.syncfusion.com/flutter/cartesian-charts/axis-types]( https://help.syncfusion.com/flutter/cartesian-charts/axis-types)
Github sample link: [https://github.com/syncfusion/flutter-examples/tree/master/lib/samples/chart/cartesian_charts/axis_features](https://github.com/syncfusion/flutter-examples/tree/master/lib/samples/chart/cartesian_charts/axis_features)
 
Also, find the sample from below to format the axis labels. This can be modified based on your requirement.
[https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart](https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart)
 
Please revert us if you need further assistance. 

Thanks,
Dharanitharan. P

**Comment by DTharaka** [comment]
Thank you @Dharanipalani for your support.
