### ISSUE TITLE
Calendar display wrongly on android with 6.8 inch screen size

### ISSUE THREAD

**Issue by hoangthienvn97** [syncfusion/flutter-widgets#1350]
![Screenshot_20230822_141147_Family tool Dev](https://github.com/syncfusion/flutter-widgets/assets/58758213/b6da8584-bdbc-40e2-98ed-aa9e6c593783)
![Screenshot_20230822_141206_Family tool Dev](https://github.com/syncfusion/flutter-widgets/assets/58758213/ffa76730-3e1b-4f9a-8347-ce277de81bba)
![Screenshot_20230822_141219_Family tool Dev](https://github.com/syncfusion/flutter-widgets/assets/58758213/76f49851-bb5e-46c4-8952-1b099a9ec080)

**Comment by hoangthienvn97** [comment]
Only fail on 6.7 inchs devices 
Help me , check error

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared information, we have checked the mentioned issue “**Calendar displays wrongly in Android with 6.8 inch device**” from our end. It was working fine as expected from our end. We have attached the tested sample for same. Please find the sample from the following link.

**Tested device:**

•	Pixel 6 pro API 33 simulator (6.7 inches)

**Tested scenario:**
•	Ensured with localization (vietnamese)

**Tested version:**

•	Flutter Calendar: 22.2.10

[month_calendar.zip](https://github.com/syncfusion/flutter-widgets/files/12417122/month_calendar.zip)

Please check the sample and let us know if you still facing the same issue? If not, please modify the sample based on your scenario and revert us with below details. It will be helpful for us to check on it and provide you solution at the earliest.

•	Code snippet
•	Replication procedure

Regards,
Indumathi R

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
