### ISSUE TITLE
[DatePicker] changing focus by tab not working on mobile (emulator)

### ISSUE THREAD

**Issue by slaci** [syncfusion/flutter-widgets#1354]
Hello,

When trying to change focus between the days in a month view by pressing tab, the calendar isn't doing anything in the 22.2.10 version, or maybe focuses on the first day.

There is a `FocusScope` around the widget which has an `onKey` handler. In that, the tab and shift+tab keys are "handled", but this does not seem to work. When I delete this tab handling part or just return `KeyEventResult.ignored` then focusing starts to work again.

So why is the tab key handled specially? I think flutter moves the focus on pressing tab by default.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need ay further assistance on this.

**Comment by slaci** [comment]
hi @LavanyaGowtham2021 @PreethikaSelvam I don't need assistance, just saying it seems to be a bug. You are saying the `shift + tab` does not support any interaction, but in the code it is handled. Check [this](https://github.com/syncfusion/flutter-widgets/blob/8f0096cba87c414cc913d897df4850f32dc40bc9/packages/syncfusion_flutter_datepicker/lib/src/date_picker/date_picker.dart#L10321) file line 10321.

The relevant part is:

```dart
if (HardwareKeyboard.instance.isShiftPressed &&
        event.logicalKey == LogicalKeyboardKey.tab) {
      FocusScope.of(context).previousFocus();
      return KeyEventResult.handled;
    }
    if (event.logicalKey == LogicalKeyboardKey.tab) {
      FocusScope.of(context).nextFocus();
      return KeyEventResult.handled;
    }
```

As you can see both `tab` and `shift + tab` keydown events  are handled. It seems like they are mimicking the "default" behavior, but as you can see in my original report, these don't really work. And my suggestion was to replace these lines to something like this:

```dart
if (event.logicalKey == LogicalKeyboardKey.tab) {
  return KeyEventResult.ignored;
}
```

I didn't test this with the latest version though.
