### ISSUE TITLE
font error on web release build

### ISSUE THREAD

**Issue by rmasarovic** [syncfusion/flutter-widgets#1355]
Hi  in new flutter 3.13

when i create release web then font shake tree has this error 

Codepoint 32 not found in font, aborting.
Target web_release_bundle failed: IconTreeShakerException: Font subsetting failed with exit code 255.

problem is in unsortIcon.ttf

**Comment by sfHariHaraSudhan** [comment]
Hi @rmasarovic,

The reported issue was resolved by the Flutter team and shared the link below for your reference. 

https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#3131-august-23-2023.

We recommend you update the Flutter SDK to 3.13.1 to avoid the reported issue. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
