### ISSUE TITLE
Invalid argument (The character is not supported by the font.): 8172

### ISSUE THREAD

**Issue by YawarOsman** [syncfusion/flutter-widgets#1359]
I have a list of data and i tried to create a pdf, but it shows the error `The character is not supported by the font` even i haven't any unusual character or emojies, what happes?? does the package doesn't support that? or it is related to flutter? even i have changed the font.

This my code for generating pdf:

```
  // this method will generate pdf for sales report and print it
  Future<bool> ordersReportPdf(List<OrdersModel> ordersList) async {
    try {
      // Create a new PDF document.
      final PdfDocument document = PdfDocument();
      // Add a new page to the document.
      final PdfPage page = document.pages.add();

      final stringFormat = PdfStringFormat(
        alignment: PdfTextAlignment.center,
        lineAlignment: PdfVerticalAlignment.middle,
      );

      // // Load the Arial Unicode MS font from the asset
      // final PdfFont arialUnicodeFont =  PdfTrueTypeFont.fromBase64String(
      //   'assets/fonts/UniQAIDAR019.ttf', // Replace with the actual path to the font file
      //   12,
      // );

      //Read font data.
      final Uint8List fontData =
          await XFile('assets/fonts/arial-unicode-ms.ttf').readAsBytes();
//Create a PDF true type font object.
      final PdfFont font = PdfTrueTypeFont(fontData, 12);

      page.graphics.drawString(
        'Invoice Report',
        // PdfStandardFont(PdfFontFamily.zapfDingbats, 24, style: PdfFontStyle.bold),
        font,
        brush: PdfSolidBrush(PdfColor(0, 0, 0)),
        bounds: Rect.fromLTWH(
          0,
          0,
          page.getClientSize().width,
          70,
        ),
        format: PdfStringFormat(
          alignment: PdfTextAlignment.center,
          lineAlignment: PdfVerticalAlignment.top,
        ),
      );

      // Create a PDF grid class to add tables.
      final PdfGrid grid = PdfGrid();

      // Specify the grid column count.
      grid.columns.add(count: 6);

      PdfStandardFont(PdfFontFamily.helvetica, 9, style: PdfFontStyle.bold);

      // Add rows to the grid.
      PdfGridRow row;

      double totalAmount = 0;
      double totalDiscount = 0;
      double totalTax = 0;
      double totalService = 0;
      int totalQty = 0;

      for (final order in ordersList) {
        totalAmount += order.totalAmount;
        totalDiscount += order.discountAmount;
        totalTax += order.taxAmount;
        totalService += order.serviceAmount;

        row = grid.rows.add();
        DateTime dateTime = DateTime.parse(order.createdAt);
        String formattedDate =
            DateFormat('yyyy/MM/dd hh:mm aa').format(dateTime);
        row.cells[0].value = 'Invoice: ${order.id.toString()}';
        row.cells[1].value =
            'Discount: ${addComma(order.discountAmount.toInt().toString())}';
        row.cells[2].value =
            'Tax: ${addComma(order.taxAmount.toInt().toString())}';
        row.cells[3].value =
            'Service: ${addComma(order.serviceAmount.toInt().toString())}';
        row.cells[4].value =
            'Total: ${addComma(order.totalAmount.toInt().toString())}';
        row.cells[5].value = formattedDate.toString();
        row.style.font = PdfStandardFont(PdfFontFamily.helvetica, 9,
            style: PdfFontStyle.bold);
        row.cells[0].style.stringFormat = stringFormat;
        row.cells[1].style.stringFormat = stringFormat;
        row.cells[2].style.stringFormat = stringFormat;
        row.cells[3].style.stringFormat = stringFormat;
        row.cells[4].style.stringFormat = stringFormat;
        row.cells[5].style.stringFormat = stringFormat;

        // add background color to the row
        row.style.backgroundBrush = PdfSolidBrush(PdfColor(82, 109, 130));

        row.style.textBrush = PdfBrushes.white;

        // Add rows to the grid.
        PdfGridRow row1 = grid.rows.add();

        row1.cells[0].value = 'Item Name';
        row1.cells[1].value = 'Option Name';
        row1.cells[2].value = 'Price';
        row1.cells[3].value = 'Quantity';
        row1.cells[4].value = 'Category';
        row1.cells[5].value = 'Sub Category';

        // add background color to the row
        row1.style.backgroundBrush = PdfSolidBrush(PdfColor(221, 230, 237));
        row1.style.font = PdfStandardFont(PdfFontFamily.helvetica, 9,
            style: PdfFontStyle.bold);

        row1.cells[0].style.stringFormat = stringFormat;
        row1.cells[1].style.stringFormat = stringFormat;
        row1.cells[2].style.stringFormat = stringFormat;
        row1.cells[3].style.stringFormat = stringFormat;
        row1.cells[4].style.stringFormat = stringFormat;
        row1.cells[5].style.stringFormat = stringFormat;

        for (final item in order.orderProducts) {
          totalQty += item.quantity;
          row1 = grid.rows.add();
      
          row1.cells[0].value = item.product.name;
          row1.cells[1].value = item.productOption.optionName;
          row1.cells[2].value = addComma(item.productOption.price.toString());
          row1.cells[3].value = item.quantity.toString();
          row1.cells[4].value = item.product.subCategory.name;
          row1.cells[5].value = item.product.subCategory.categoryName;

          row1.cells[0].style.stringFormat = stringFormat;
          row1.cells[1].style.stringFormat = stringFormat;
          row1.cells[2].style.stringFormat = stringFormat;
          row1.cells[3].style.stringFormat = stringFormat;
          row1.cells[4].style.stringFormat = stringFormat;
          row1.cells[5].style.stringFormat = stringFormat;
        }
      }

      final PdfPage lastPage1 = document.pages[document.pages.count - 1];
      // Draw table in the PDF page.
      grid.draw(
        page: page,
        bounds: Rect.fromLTWH(
          0,
          50,
          page.getClientSize().width,
          lastPage1.getClientSize().height - 60,
        ),
      );

      final PdfPage lastPage = document.pages[document.pages.count - 1];

      // Add the footer text to the last page.
      lastPage.graphics.drawString(
        'Total Amount: ${addComma(totalAmount.toInt().toString())}    Sub Total: ${addComma(((totalAmount - totalService - totalTax) + totalDiscount).toInt().toString())}    Total Tax: ${addComma(totalTax.toInt().toString())}      Total Service: ${addComma(totalService.toInt().toString())}',
        PdfStandardFont(PdfFontFamily.helvetica, 11),
        brush: PdfSolidBrush(PdfColor(0, 0, 0)),
        bounds: Rect.fromLTWH(
          0,
          lastPage.getClientSize().height - 30, // Adjust for footer height
          lastPage.getClientSize().width,
          30, // Adjust for footer height
        ),
        format: PdfStringFormat(
          alignment: PdfTextAlignment.left,
          lineAlignment: PdfVerticalAlignment.top,
        ),
      );
      lastPage.graphics.drawString(
        'Total Discount: ${addComma(totalDiscount.toInt().toString())}    Item Qty: $totalQty    Order Qty: ${ordersList.length}     DateTime: ${DateFormat('yyyy/MM/dd hh:mm aa').format(DateTime.now())}',
        PdfStandardFont(PdfFontFamily.helvetica, 11),
        brush: PdfSolidBrush(PdfColor(0, 0, 0)),
        bounds: Rect.fromLTWH(
          0,
          lastPage.getClientSize().height - 15, // Adjust for footer height
          lastPage.getClientSize().width,
          15, // Adjust for footer height
        ),
        format: PdfStringFormat(
          alignment: PdfTextAlignment.left,
          lineAlignment: PdfVerticalAlignment.bottom,
        ),
      );

      // Save the document.
      final bytes = await document.save();

      // Convert bytes to Uint8List.
      final Uint8List data = Uint8List.fromList(bytes);

      // Create a blob from the PDF data.
      final Blob pdfBlob = Blob([data], 'application/pdf');

      // Create a blob URL.
      final String url = html.Url.createObjectUrlFromBlob(pdfBlob);

      // Create a virtual anchor element to initiate download.
      final html.AnchorElement anchor = html.AnchorElement(href: url)
        ..target = 'blank'
        ..download = 'Orders_Report.pdf';

      // Trigger a click event on the anchor element to initiate download.
      anchor.click();

      // Release the object URL after initiating the download.
      html.Url.revokeObjectUrl(url);

      // Dispose the document.
      document.dispose();
      return true;
    } catch (e) {
      debugPrint('Error: $e');
      return false;
    }
  }

```

**Comment by irfanajaffer** [comment]
On analysis with the provided code, the Helvetica font is being used to preserve characters inside the PDF Grid. To preserve Arabic and other RTL language characters, we have to use a suitable font that supports that character.

Kindly use the following link to know more about drawing RTL text,
https://help.syncfusion.com/flutter/pdf/working-with-text#drawing-right-to-left-text

We can also see that the "Arial Unicode MS" font was used to preserve character outside the grid. We can use this same font to preserve characters inside the PDF Grid to resolve the issue.

Kindly use the following code snippet for reference,

`/ this method will generate pdf for sales report and print it
Future<bool> ordersReportPdf(List<OrdersModel> ordersList) async {
  try {
    // Create a new PDF document.
    final PdfDocument document = PdfDocument();
    // Add a new page to the document.
    final PdfPage page = document.pages.add();

    final stringFormat = PdfStringFormat(
      alignment: PdfTextAlignment.center,
      lineAlignment: PdfVerticalAlignment.middle,
      wordWrap: PdfWordWrapType.word,
    );

    //Read font data.
    final Uint8List fontData =
        await XFile('assets/fonts/arial-unicode-ms.ttf').readAsBytes();
//Create a PDF true type font object.
    final PdfFont font = PdfTrueTypeFont(fontData, 12);
    final PdfFont arialBold =
        PdfTrueTypeFont(fontData, 12, style: PdfFontStyle.bold);

    page.graphics.drawString(
      'Invoice Report',
      font,
      brush: PdfSolidBrush(PdfColor(0, 0, 0)),
      bounds: Rect.fromLTWH(
        0,
        0,
        page.getClientSize().width,
        70,
      ),
      format: PdfStringFormat(
        alignment: PdfTextAlignment.center,
        lineAlignment: PdfVerticalAlignment.top,
      ),
    );

    // Create a PDF grid class to add tables.
    final PdfGrid grid = PdfGrid();

    // Specify the grid column count.
    grid.columns.add(count: 6);

    // Add rows to the grid.
    PdfGridRow row;

    double totalAmount = 0;
    double totalDiscount = 0;
    double totalTax = 0;
    double totalService = 0;
    int totalQty = 0;

    for (final order in ordersList) {
      totalAmount += order.totalAmount;
      totalDiscount += order.discountAmount;
      totalTax += order.taxAmount;
      totalService += order.serviceAmount;

      row = grid.rows.add();
      DateTime dateTime = DateTime.parse(order.createdAt);
      String formattedDate = DateFormat('yyyy/MM/dd hh:mm aa').format(dateTime);
      row.cells[0].value = 'Invoice: ${order.id.toString()}';
      row.cells[1].value =
          'Discount: ${addComma(order.discountAmount.toInt().toString())}';
      row.cells[2].value =
          'Tax: ${addComma(order.taxAmount.toInt().toString())}';
      row.cells[3].value =
          'Service: ${addComma(order.serviceAmount.toInt().toString())}';
      row.cells[4].value =
          'Total: ${addComma(order.totalAmount.toInt().toString())}';
      row.cells[5].value = formattedDate.toString();
      row.style.font = arialBold;
      row.cells[0].style.stringFormat = stringFormat;
      row.cells[1].style.stringFormat = stringFormat;
      row.cells[2].style.stringFormat = stringFormat;
      row.cells[3].style.stringFormat = stringFormat;
      row.cells[4].style.stringFormat = stringFormat;
      row.cells[5].style.stringFormat = stringFormat;

      // add background color to the row
      row.style.backgroundBrush = PdfSolidBrush(PdfColor(82, 109, 130));

      row.style.textBrush = PdfBrushes.white;

      // Add rows to the grid.
      PdfGridRow row1 = grid.rows.add();

      row1.cells[0].value = 'Item Name';
      row1.cells[1].value = 'Option Name';
      row1.cells[2].value = 'Price';
      row1.cells[3].value = 'Quantity';
      row1.cells[4].value = 'Category';
      row1.cells[5].value = 'Sub Category';

      // add background color to the row
      row1.style.backgroundBrush = PdfSolidBrush(PdfColor(221, 230, 237));
      row1.style.font = arialBold;

      row1.cells[0].style.stringFormat = stringFormat;
      row1.cells[1].style.stringFormat = stringFormat;
      row1.cells[2].style.stringFormat = stringFormat;
      row1.cells[3].style.stringFormat = stringFormat;
      row1.cells[4].style.stringFormat = stringFormat;
      row1.cells[5].style.stringFormat = stringFormat;

      for (final item in order.orderProducts) {
        totalQty += item.quantity;
        row1 = grid.rows.add();

        row1.cells[0].value = item.product.name;
        row1.cells[1].value = item.productOption.optionName;
        row1.cells[2].value = addComma(item.productOption.price.toString());
        row1.cells[3].value = item.quantity.toString();
        row1.cells[4].value = item.product.subCategory.name;
        row1.cells[5].value = item.product.subCategory.categoryName;

        row1.cells[0].style.stringFormat = stringFormat;
        row1.cells[1].style.stringFormat = stringFormat;
        row1.cells[2].style.stringFormat = stringFormat;
        row1.cells[3].style.stringFormat = stringFormat;
        row1.cells[4].style.stringFormat = stringFormat;
        row1.cells[5].style.stringFormat = stringFormat;
      }
    }

    final PdfPage lastPage1 = document.pages[document.pages.count - 1];
    // Draw table in the PDF page.
    grid.draw(
      page: page,
      bounds: Rect.fromLTWH(
        0,
        50,
        page.getClientSize().width,
        lastPage1.getClientSize().height - 60,
      ),
    );

    final PdfPage lastPage = document.pages[document.pages.count - 1];

    // Add the footer text to the last page.
    lastPage.graphics.drawString(
      'Total Amount: ${addComma(totalAmount.toInt().toString())}    Sub Total: ${addComma(((totalAmount - totalService - totalTax) + totalDiscount).toInt().toString())}    Total Tax: ${addComma(totalTax.toInt().toString())}      Total Service: ${addComma(totalService.toInt().toString())}',
      font,
      brush: PdfSolidBrush(PdfColor(0, 0, 0)),
      bounds: Rect.fromLTWH(
        0,
        lastPage.getClientSize().height - 30, // Adjust for footer height
        lastPage.getClientSize().width,
        30, // Adjust for footer height
      ),
      format: PdfStringFormat(
        alignment: PdfTextAlignment.left,
        lineAlignment: PdfVerticalAlignment.top,
      ),
    );
    lastPage.graphics.drawString(
      'Total Discount: ${addComma(totalDiscount.toInt().toString())}    Item Qty: $totalQty    Order Qty: ${ordersList.length}     DateTime: ${DateFormat('yyyy/MM/dd hh:mm aa').format(DateTime.now())}',
      font,
      brush: PdfSolidBrush(PdfColor(0, 0, 0)),
      bounds: Rect.fromLTWH(
        0,
        lastPage.getClientSize().height - 15, // Adjust for footer height
        lastPage.getClientSize().width,
        15, // Adjust for footer height
      ),
      format: PdfStringFormat(
        alignment: PdfTextAlignment.left,
        lineAlignment: PdfVerticalAlignment.bottom,
      ),
    );

    // Save the document.
    final bytes = await document.save();

    // Convert bytes to Uint8List.
    final Uint8List data = Uint8List.fromList(bytes);

    // Create a blob from the PDF data.
    final Blob pdfBlob = Blob([data], 'application/pdf');

    // Create a blob URL.
    final String url = html.Url.createObjectUrlFromBlob(pdfBlob);

    // Create a virtual anchor element to initiate download.
    final html.AnchorElement anchor = html.AnchorElement(href: url)
      ..target = 'blank'
      ..download = 'Orders_Report.pdf';

    // Trigger a click event on the anchor element to initiate download.
    anchor.click();

    // Release the object URL after initiating the download.
    html.Url.revokeObjectUrl(url);

    // Dispose the document.
    document.dispose();
    return true;
  } catch (e) {
    debugPrint('Error: $e');
    return false;
  }
}`
