### ISSUE TITLE
You have a BUG in xlsio with rows counting!

### ISSUE THREAD

**Issue by darkstarx** [syncfusion/flutter-widgets#136]
There is a stupid bug in your code.
You have zero-based counting list in the `RowCollection` but your references are 1-based (i.e. "A0" is bad and "A1" is good), and you access to a row in `RowCollection` by 1-based index.

Please, fix this bug!

How to reproduce this bug.
```
    final workbook = Workbook();
    final sheet = workbook.worksheets[0];
    sheet.rows.add();
    sheet.getRangeByName('A1')..setText('a1');
    sheet.rows.add();  // < CRASH! Unsupported operation: Cannot add to a fixed-length list
```

Why rows became a fixed-length list? Because of your SECOND BUG here:
```
  void _updateSize(int iCount) {
    if (iCount > _iCount) {
      final int iBufCount = _iCount * 2;

      _iCount = (iCount >= iBufCount) ? iCount : iBufCount;

      final List<Row> list = List<Row>.filled(_iCount, null, growable: false);  // < BUG! Why growable: false????????

      if (_innerList != null) list.setAll(0, _innerList);

      _innerList = list;
    }
  }
```

Why _updateSize have been called? Because there is a BUG in the _setRange:
```
  void _setRange() {
    Row currRow;
    final RowCollection rows = worksheet.rows;
    if (rows[row] != null) {         // < HERE row = 1 (because of "A1", where 1 means first row, which is 0 for 0-based list of rows!)
      currRow = rows[row];
      currRow.ranges[column] = this;
    } else {
      currRow = Row(worksheet);
      currRow.index = row;
      rows[row] = currRow;
      currRow.ranges[column] = this;
    }
```

I wonder what logic you followed? Where were your eyes? WTF?!!

**Comment by ShaminiKiruba** [comment]
Hi darkstarx,

We have implemented add() method in the RowCollection class for an internal purpose. We have exposed that API as public by mistake. We request to use the below codes by accessing range from the worksheet. This is the recommended approach for using Flutter XlsIO.

`// Create a new Excel document.
final Workbook workbook = new Workbook();
//Accessing worksheet via index.
final Worksheet sheet = workbook.worksheets[0];
//Add Text.
sheet.getRangeByName('A1').setText('Hello World');
//Add Number
sheet.getRangeByName('A3').setNumber(44);
//Add DateTime
sheet.getRangeByName('A5').setDateTime(DateTime(2020,12,12,1,10,20));
// Save the document.
List<int> bytes = workbook.saveAsStream();
File('Excel.xlsx').writeAsBytes(bytes);
//Dispose the workbook.
workbook.dispose();
`

However, we will check the reported issue and fix it ASAP.

Regards,
Sridhar

**Comment by Sridhar-Sukumar** [comment]
Hi darkstarx,

We have implemented add() method in the RowCollection class for an internal purpose. We have exposed that API as public by mistake. We request to use the below codes by accessing range from the worksheet. This is the recommended approach for using Flutter XlsIO.

```
// Create a new Excel document.
final Workbook workbook = new Workbook();
//Accessing worksheet via index.
final Worksheet sheet = workbook.worksheets[0];
//Add Text.
sheet.getRangeByName('A1').setText('Hello World');
//Add Number
sheet.getRangeByName('A3').setNumber(44);
//Add DateTime
sheet.getRangeByName('A5').setDateTime(DateTime(2020,12,12,1,10,20));
// Save the document.
List<int> bytes = workbook.saveAsStream();
File('Excel.xlsx').writeAsBytes(bytes);
//Dispose the workbook.
workbook.dispose();
```

However, we will check the reported issue and fix it ASAP.

Regards,
Sridhar.

**Comment by darkstarx** [comment]
Got it. Thanks!

**Comment by Sridhar-Sukumar** [comment]
Hi @darkstarx,

We have fixed the reported "Exception is thrown while adding rows in Flutter XlsIO" issue and the fix is included in the latest syncfusion_flutter_xlsio version (18.4.47-beta)

Regards,
Sridhar.

**Comment by darkstarx** [comment]
It's a good news, thank you!
