### ISSUE TITLE
[SfCartesianChart] [Flutter] How to pan the chart programmatically to specified position?

### ISSUE THREAD

**Issue by sabachimp** [syncfusion/flutter-widgets#1361]
Hello Team,

I am using flutter library with version **syncfusion_flutter_charts: ^22.2.10**

I am getting the following error when programmatically selecting data points of the chart,

**Error:** _Provided point index is not in the visible range. Provide point index which is in the visible range._ 
**Code snippet:** _selectionBehavior.selectDataPoints(point index, series index)

Is there any way to pan the chart horizontally to specific index?

Thanks.

**Comment by sfHariHaraSudhan** [comment]
Hi @sabachimp,

We would like to inform you that the stated assertion throws an error when we try to select a segment that is not within the visible range of the chart. To achieve your mentioned requirement, you can use the methods [ZoomPanBehavior.panToDirection](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/panToDirection.html) and [SelectionBehavior.selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html).

We have prepared a sample that renders the [Column Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html) with fifteen segments. We have set the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property to ten and [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) property to [AutoScrollingMode.start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html). This ensures that only ten segments are visible at load time, and the remaining segments become visible when scrolling the chart using the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html).

When the center button is clicked, we need to select the twelfth index of the Column Segment using the [SelectionBehavior.selectDataPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SelectionBehavior/selectDataPoints.html) method. Additionally, when the left or right button is clicked, the chart will be panned programmatically to the right or left using the [ZoomPanBehavior.panToDirection](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/panToDirection.html) method.

Kindly refer the code snippet below:
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late ZoomPanBehavior _zoomPanBehavior;
  late SelectionBehavior _selectionBehavior;
 
  @override
  void initState() {
    _data = [
      ChartSampleData(01, 40),
      ChartSampleData(02, 80),
      ChartSampleData(03, 40),
      ChartSampleData(04, 60),
      ChartSampleData(05, 50),
      ChartSampleData(06, 90),
      ChartSampleData(07, 110),
      ChartSampleData(08, 70),
      ChartSampleData(09, 120),
      ChartSampleData(10, 100),
      ChartSampleData(11, 50),
      ChartSampleData(12, 60),
      ChartSampleData(13, 40),
      ChartSampleData(14, 70),
      ChartSampleData(15, 80),
    ];
    _zoomPanBehavior = ZoomPanBehavior(enablePanning: true);
    _selectionBehavior = SelectionBehavior(enable: true);
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Expanded(
                child: SfCartesianChart(
                  primaryXAxis: NumericAxis(
                    autoScrollingDelta: 10,
                    autoScrollingMode: AutoScrollingMode.start,
                  ),
                  primaryYAxis: NumericAxis(),
                  series: <CartesianSeries<ChartSampleData, num>>[
                    ColumnSeries<ChartSampleData, num>(
                      dataSource: _data,
                      xValueMapper: (ChartSampleData sales, int index) =>
                          sales.x,
                      yValueMapper: (ChartSampleData sales, int index) =>
                          sales.y,
                      selectionBehavior: _selectionBehavior,
                    ),
                  ],
                  zoomPanBehavior: _zoomPanBehavior,
                ),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      _zoomPanBehavior.panToDirection('left');
                    },
                    child: const Icon(Icons.arrow_left_sharp),
                  ),
                  const SizedBox(width: 10),
                  ElevatedButton(
                    onPressed: () {
                      _selectionBehavior.selectDataPoints(12);
                    },
                    child: const Icon(Icons.select_all_sharp),
                  ),
                  const SizedBox(width: 10),
                  ElevatedButton(
                    onPressed: () {
                      _zoomPanBehavior.panToDirection('right');
                    },
                    child: const Icon(Icons.arrow_right_sharp),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
Shared the User Guide documentation regarding the public methods in the ZoomPanBehavior for your reference.
UG: https://help.syncfusion.com/flutter/cartesian-charts/methods#methods-in-zoompanbehavior.

Also attached the sample and recording below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[497071.zip](https://github.com/syncfusion/flutter-widgets/files/12484821/497071.zip)
[_497071.zip](https://github.com/syncfusion/flutter-widgets/files/12484823/_497071.zip)

**Comment by sabachimp** [comment]
Hi @sfHariHaraSudhan ,

Thanks for the detailed response, Will try this solution and get back to you if needed.

**Comment by sabachimp** [comment]
Thanks for the detailed solution.
