### ISSUE TITLE
Cannot find 'DispatchQueue' in scope

### ISSUE THREAD

**Issue by trihandhoko** [syncfusion/flutter-widgets#1365]
Hello, i'm new in flutter, I got this error after updating XCode to version 14.3.1 on my M1 Macbook

```
Swift Compiler Error (Xcode): Cannot find 'DispatchQueue' in scope
/Users/randytrihandhoko/.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-21.2.10/ios/Classes/SwiftSyncfusionFlutterPdfViewerPlugin.swift:11:21
```

has anyone experienced this too, please help me how to solve this problem. thank you :)

**Comment by deepika134** [comment]
Hi trihandhoko, We have checked the reported issue with the provided details, and the PDF document loaded properly in the iOS [Xcode version: 14.3.1, iPhone 14 Pro Max simulator] platform without any exceptions in SfPdfViewer on our end. For your reference, we have attached the tested sample, as well as a screen recording of the output, which can be downloaded from the following link : https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-1932320186 . Please clear the cache and update the Flutter SDK to the latest version, then check the shared sample and let us know if you are still experiencing the issue on your end. If so, please provide a modified issue reproducing sample.

**Comment by ramkumarsync** [comment]
We are closing this issue since we haven't heard back from you for a long time. Please feel free to contact us anytime if you need any further assistance.
