### ISSUE TITLE
When the text is long, click the text how to hide the pop-up tips

### ISSUE THREAD

**Issue by haoxuhong** [syncfusion/flutter-widgets#1366]
![WechatIMG60](https://github.com/syncfusion/flutter-widgets/assets/18694420/d5094483-7366-4dbe-8e6a-634ed2d6c909)

**Comment by Yuvaraj-Gajaraj** [comment]
Currently, there is no direct support to hide an axis tooltip in the SfCartesianchart. However, you can achieve your requirement with the help of setting the [activationMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ActivationMode.html) property to none in [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html), then using the [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onPointTap.html) callback in series and calling the tooltip behavior public method [showByIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/showByIndex.html) with the tapped point [seriesIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPointDetails/seriesIndex.html) and [pointIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartPointDetails/pointIndex.html) value to show the tooltip for that data point.

We have shared the code snippet and attached the simple sample below for your reference, We hope it will help you to achieve your requirements.



Code snippet:
```dart
final TooltipBehavior _tooltipBehavior =
      TooltipBehavior(enable: true, activationMode: ActivationMode.none);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        tooltipBehavior: _tooltipBehavior,
        primaryXAxis: CategoryAxis(
            maximumLabelWidth: 80,
            interactiveTooltip: const InteractiveTooltip(enable: false)),
        series: <ChartSeries>[
          BarSeries<SalesData, String>(
            onPointTap: (pointTapArgs) {
              _tooltipBehavior.showByIndex(
                  pointTapArgs.seriesIndex!, pointTapArgs.pointIndex!);
            },
            dataSource: <SalesData>[
              SalesData(x: 'Goldin Finance 117', y: 597),
              SalesData(x: 'Ping An Finance Center', y: 599),
              SalesData(x: 'Makkah Clock Royal Tower', y: 601),
              SalesData(x: 'Shanghai Tower', y: 632),
              SalesData(x: 'Burj Khalifa', y: 828)
            ],
            xValueMapper: (SalesData sales, _) => sales.x,
            yValueMapper: (SalesData sales, _) => sales.y,
          )
        ],
      ),
    );
  }
```

Sample: 
[i497622.zip](https://github.com/syncfusion/flutter-widgets/files/12496135/i497622.zip)
