### ISSUE TITLE
Slow Loading Pdf File

### ISSUE THREAD

**Issue by AmjidKhani** [syncfusion/flutter-widgets#1367]
too slow loading PDF and also too slow the next page comes when i scroll for next page .as other packages like :flutter_pdfview load pdf soo fast also scrolling is too fast .and it also contains ligh mode and dark mode but in this package:syncfusion_flutter_pdfviewer 22.2.11 the light mode and dark mode not work as expected

**Comment by deepika134** [comment]
**Regarding Support for night mode :**
At present we do not have support for night mode in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following feedback link for track the status of the feature,

https://www.syncfusion.com/feedback/32848/support-for-night-mode

**Comment by yanshouwang** [comment]
This rendering strategy makes bad experience, I noticed some pdf pages are loaded really slow, and I think the pages that already loaded should not be reloaded again when the user swipe up and down.
So my suggestion is improve the loading speed(maybe load pdf directly form the flutter side) and keep the pages which already loaded in memory until the SfPdfViewer disposed.

**Comment by ramkumarsync** [comment]
> This rendering strategy makes bad experience, I noticed some pdf pages are loaded really slow, and I think the pages that already loaded should not be reloaded again when the user swipe up and down. So my suggestion is improve the loading speed(maybe load pdf directly form the flutter side) and keep the pages which already loaded in memory until the SfPdfViewer disposed. Or maybe use a PlatformView to render PDF on native side?

Thank you for your suggestions. As we built the Flutter PDF Viewer with the Native renderer as the base, it is not feasible for us to use PlatformView for rendering PDF pages.

Keeping the loaded pages in the memory will lead us to memory heap issues. As of now the PDF viewer only renders 2 or 3 pages (depending on the size of the screen). To overcome this memory issue we have planned to expose an API to increase the number of pages that can be rendered at a time in the viewport. We believe that this will resolve the page reloading issue for the loaded pages. Please let us know if this solution would work for you.

**Comment by ramkumarsync** [comment]
Please confirm whether the solution shared before (exposing an API to increase the number of pages that can be rendered at a time in the viewport) will help you overcome the problem at your end or not. This will help us proceed further in meeting your needs.

**Comment by immankumarsync** [comment]
We have improved the page rendering performance in [syncfusion_flutter_pdfviewer v26.1.35](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/26.1.35). Could you please try with the [latest](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/26.2.5) version and let us know whether it resolves your issue?

Changelog: [v26.1.36](https://pub.dev/packages/syncfusion_flutter_pdfviewer/changelog#26135---06112024)

**Comment by Deepak1799** [comment]
@AmjidKhani We believe that the issue has been resolved; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.
