### ISSUE TITLE
Flutter Cartesian Charts Line Chart: No Scrollbar

### ISSUE THREAD

**Issue by kkruel8100** [syncfusion/flutter-widgets#1368]
Working with Flutter Line Charts.  Need scrolling with a visible scrollbar.  Have read implementation for infinite scrolling but this chart type doesn't have a visible scrollbar.  Have seen some old content and issues that Sync Fusion doesn't support scrollbars on all of the charts and one suggestion about possible implementing a slider as a possible work around.

Getting a lot of feedback that this is a poor user experience.  And the slider is not the desired look and functionality.  

Do you have any plans on implementing a visible scrollbar on the Line Charts and the Cartesian Charts as a whole?  If yes, do you have any timeline for release schedule?

If not, do you have any recommendations for the user experience to address the absence of the scrollbar.

The use case is a simple line chart with data points in 1 hour increments with 12 hours visible on the screen.  User wants the ability to scroll forwards or backwards in small increments and maintain the 12 hours visible.
i.e. User is presented with 12 am -> 12 pm. Can then scroll to left and see 1 am -> 1 pm and so on or scroll to the right and see 11 pm -> 11 am.

Thank you.

**Comment by sfHariHaraSudhan** [comment]
Hi @kkruel8100,

We would like to let you know that currently, we don’t have support for **Provide axis scrollbar support for panning the chart** feature. However, we have considered your requirement as a new feature and already logged feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback Link: https://www.syncfusion.com/feedback/43312.

We have also prepared a sample with a feasible solution for panning the chart using the [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html). In this sample, we have utilized the [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html) and implemented the SfCartesianChart as a [child](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/child.html) by using the child property of the [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html). We obtain the current [range values](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues-class.html) while dragging the [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html) using the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/onChanged.html) callback, and then assign these values to the [visible minimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/visibleMinimum.html) and [visible maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/visibleMaximum.html) properties of the chart. As a result, when we drag the [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector-class.html), the chart is properly panned according to the selected [range values](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeValues-class.html).

Kindly refer the code snippet below:
```
class _MainAppState extends State<MainApp> {
  late List<_ChartSampleData> _chartData;
  late RangeController _rangeController;
  SfRangeValues _rangeValues = SfRangeValues(
    DateTime(2023, 09, 04, 00),
    DateTime(2023, 09, 04, 12),
  );
 
  @override
  void initState() {
    super.initState();
    _chartData = <_ChartSampleData>[
      _ChartSampleData(x: DateTime(2023, 09, 04, 00), y: 5.2),
      _ChartSampleData(x: DateTime(2023, 09, 04, 01), y: 2.2),
      _ChartSampleData(x: DateTime(2023, 09, 04, 02), y: 3.4),
      _ChartSampleData(x: DateTime(2023, 09, 04, 03), y: 2.8),
      _ChartSampleData(x: DateTime(2023, 09, 04, 04), y: 1.6),
      _ChartSampleData(x: DateTime(2023, 09, 04, 05), y: 2.3),
      _ChartSampleData(x: DateTime(2023, 09, 04, 06), y: 2.5),
      _ChartSampleData(x: DateTime(2023, 09, 04, 07), y: 2.9),
      _ChartSampleData(x: DateTime(2023, 09, 04, 08), y: 3.8),
      _ChartSampleData(x: DateTime(2023, 09, 04, 09), y: 1.4),
      _ChartSampleData(x: DateTime(2023, 09, 04, 10), y: 3.1),
      _ChartSampleData(x: DateTime(2023, 09, 04, 11), y: 6.1),
      _ChartSampleData(x: DateTime(2023, 09, 04, 12), y: 2.1),
    ];
    _rangeController = RangeController(
      start: _rangeValues.start,
      end: _rangeValues.end,
    );
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.all(10),
          child: Center(
            child: SfRangeSelectorTheme(
              data: SfRangeSelectorThemeData(
                inactiveRegionColor: Colors.transparent,
              ),
              child: SfRangeSelector(
                onChanged: (SfRangeValues values) {
                  setState(() {
                    _rangeValues = values;
                  });
                },
                min: DateTime(2023, 09, 04, 00),
                max: DateTime(2023, 09, 04, 12),
                interval: 1,
                controller: _rangeController,
                dateFormat: DateFormat.jz(),
                dateIntervalType: DateIntervalType.hours,
                showTicks: true,
                showLabels: true,
                child: SfCartesianChart(
                  margin: EdgeInsets.zero,
                  primaryXAxis: DateTimeAxis(
                    visibleMinimum: _rangeValues.start,
                    visibleMaximum: _rangeValues.end,
                    isVisible: false,
                  ),
                  primaryYAxis: NumericAxis(
                    isVisible: false,
                  ),
                  series: <CartesianSeries<_ChartSampleData, DateTime>>[
                    ColumnSeries<_ChartSampleData, DateTime>(
                      dataSource: _chartData,
                      xValueMapper: (_ChartSampleData sales, _) => sales.x,
                      yValueMapper: (_ChartSampleData sales, _) => sales.y,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
 
  @override
  void dispose() {
    _rangeController.dispose();
    _chartData.clear();
    super.dispose();
  }
}
```
Also attached the sample and recording below for your reference. You can modify the below sample according to your needs and if you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[_498086.zip](https://github.com/syncfusion/flutter-widgets/files/12534412/_498086.zip)
[498086.zip](https://github.com/syncfusion/flutter-widgets/files/12534414/498086.zip)

**Comment by kkruel8100** [comment]
Hari Hara Sudhan. K.,

Thank you for creating a feature request and supplying the code snippet and video. It was very helpful.

Regards.
