### ISSUE TITLE
create support for dart also for syncfusion pdf flutter

### ISSUE THREAD

**Issue by alihassan143** [syncfusion/flutter-widgets#1370]
currently the package only support flutter the library is already written in dart than just update yaml file and add support for dart that will support both flutter and dart

**Comment by NotTsunami** [comment]
Taking a very brief look at it, `syncfusion_pdf_flutter` has a dependency on `syncfusion_flutter_core`, which seems to be pretty heavily dependent on Flutter. It might be possible to extract the required code out, but it looks like it would be a little bit more than just a quick .yaml file edit unfortunately.

**Comment by AnanthaGokulaRaman** [comment]
Currently, we don't have support for creating or manipulating PDF documents in Dart. We have added it to our feature request list. As of now, we don't have any immediate plans to implement this. It will be available any of our upcoming releases. 
 
Kindly use the below feedback link to track the status of the feature.
[PDF document creation and manipulation support in Dart in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/54179/pdf-document-creation-and-manipulation-support-in-dart)
