### ISSUE TITLE
[SfDataGrid] Horizontal Scrollbar position issue

### ISSUE THREAD

**Issue by marcosgcd** [syncfusion/flutter-widgets#1371]
<img width="557" alt="Bildschirmfoto 2023-09-04 um 00 52 48" src="https://github.com/syncfusion/flutter-widgets/assets/137309939/ecc03b5d-e171-47c4-8acc-a961c0d566f4">

To reproduce I used the Example https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datagrid/example/lib
and only added the Container

<img width="457" alt="Bildschirmfoto 2023-09-04 um 00 56 01" src="https://github.com/syncfusion/flutter-widgets/assets/137309939/fc8b36cf-3654-4e2d-a1eb-13159c700365">

I would expect the Scrollbar to be positioned like the Vertical version
<img width="557" alt="Bildschirmfoto 2023-09-04 um 01 00 26" src="https://github.com/syncfusion/flutter-widgets/assets/137309939/c3c5cec4-c1a0-4534-ba54-479158deb22b">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @marcosgcd,

We've previously reported this issue to the Flutter framework, and they suggested a solution for it. As per the framework suggestion, you can remove the bottom padding of the scrollbar by utilizing the **MediaQuery**. Please check the following code snippet.

```dart
@override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: Container(
        height: 500,
        color: Colors.red.withOpacity(0.1),
        child: MediaQuery(
          data: MediaQuery.of(context).removePadding(removeBottom: true),
          child: SfDataGrid(
            source: employeeDataSource,
            columns: getColumns,
          ),
        ),
      ),
    );
  }

```

![image](https://github.com/syncfusion/flutter-widgets/assets/93904422/f4ff92e8-d7d3-4d50-a95b-e5e3bbfc7375)

Furthermore, we have already published a Knowledge Base (KB) document that provides step-by-step instructions on how to remove the default padding applied to the horizontal scrollbar of SfDataGrid on the iOS platform. Please check the following KB document for more information.

KB Document: https://support.syncfusion.com/kb/article/12288/how-to-remove-the-default-padding-applied-to-the-horizontal-scrollbar-of-flutter-datatable 

Regards,
Tamilarasan

**Comment by marcosgcd** [comment]
Sorry for the Late response. 

Thanks for your help. Was not expecting it to be an Flutter issue
