### ISSUE TITLE
[SfCalendar] Need option to turn off timezone initializeDatabase

### ISSUE THREAD

**Issue by pxsanghyo** [syncfusion/flutter-widgets#1373]
We need an option to turn off `initializeDatabase`.
For apps that depend on same `timezone` package and database is already initialized and/or local location is already set.

SfCalendar assumes it needs to `initializeDatabase` and set the IANA database variant to `latest_all`
This also resets the app's local location back to default `UTC` even if `setLocalLocation` is previously set.

```dart
  void initState() {
    _loadDataBase().then((bool value) => _getAppointment());
    super.initState();
  }
```

```dart
  Future<bool> _loadDataBase() async {
    final ByteData byteData =
        await rootBundle.load('packages/timezone/data/latest_all.tzf');
    initializeDatabase(byteData.buffer.asUint8List());
    _timeZoneLoaded = true;
    return true;
  }
```

Thanks!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @pxsanghyo ,

We have checked your query at our end and as we are not able to understand what you are proposing as your requirement, we kindly request you to share us with more information on your requirement in detail along with screenshots or screen recordings so that it will help us assist you in a better way.

Regards,
Yuvaraj

**Comment by pxsanghyo** [comment]
@Yuvaraj-Gajaraj 
Thanks for replying.

In the clip you will see that the current Local Location is set to "America/Detroit" and it will change back to "UTC" once you open SfCalendar. This is because, SfCalendar widget initializes tz database. For apps that already rely on the `timezone` package, it will be reset.

https://github.com/syncfusion/flutter-widgets/assets/73404579/689404f9-d127-4f38-b93f-2908568c7f2a

**Comment by pxsanghyo** [comment]
I'm surprised nobody else is running to this issue.

**sfcalendar.dart**
```
  /// loads the time zone data base to handle the time zone for calendar
  Future<bool> _loadDataBase() async {
    final ByteData byteData =
        await rootBundle.load('packages/timezone/data/latest_all.tzf');
    initializeDatabase(byteData.buffer.asUint8List());
    _timeZoneLoaded = true;
    return true;
  }
```

When SfCalendar widget gets built, it changes the timezone data to `latest_all` and `initializeDatabase`. If your app uses `timezone` package, `SfCalendar` resets the `timezone` settings. For example, say your app loads timezone with `latest` data and sets local timezone to user's location. Loading `SfCalendar` widget changes the data to `latest_all` and sets the local timezone to `UTC`.

**Comment by LokeshPalani** [comment]
Hi @pxsanghyo,

 

Currently, we don't have support to **disable the SfCalendar time zone database to get initialized.** We have logged a feature request for **to turn off time zone initializeDatabase** in our feedback portal and it is uncertain. This feature will be available in one of our upcoming releases. We will notify you when this feature is implemented. We appreciate your patience until then.

 

If you have any additional specifications or suggestions for this feature request, please feel free to leave them in the comments section of the feedback link. This will help us understand how you would like to use it and how we can improve it.

 

Feedback Link,

 https://www.syncfusion.com/feedback/54423

 

Regards,
Lokesh P.
