### ISSUE TITLE
Rerender on zoom for better quality

### ISSUE THREAD

**Issue by InspectlyMads** [syncfusion/flutter-widgets#1374]
Is rerendering the view on zoom for better quality currently possible? I cant seems find anything about this feature

**Comment by sfHariHaraSudhan** [comment]
Hi @InspectlyMads,

We have analyzed your query, but unfortunately, we are unable to understand what you are referring to as "quality" based on the information provided. We require some clarifications on the below mentioned points regarding the mentioned query.

1. While zooming, the rendering will be repeated and whether do you need to avoid the rendering being repeated based on some performance factors. 
2. We recommend you share any recordings or snapshot regarding the mentioned behavior with detailed explanation of your use case or requirements.
3. If possible, kindly share some reference links or samples to understand the mentioned behavior clearly.

With that additional information, it will be very useful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by InspectlyMads** [comment]
I was thinking something like the PdfViewPinch in the "Pdfx" package. Where zoom rerender svg and text  in pdf to make it better quality. When I zoom a lot with the sfPdfViewer the quality gets really bad on very large pdf files.

I have linked the demo from the package. 
https://raw.githubusercontent.com/ScerIO/packages.flutter/main/packages/pdfx/example/media/pinch.gif?raw=true

**Comment by immankumarsync** [comment]
At present, SfPdfViewer does not support Tile rendering, but the whole page will be re-rendered on zooming the page and this behavior is working as expected. Please find the attached video for reference. Since the whole page is re-rendered, the page will be redrawn with some delay if the pdf page contains high resolution image.


https://github.com/syncfusion/flutter-widgets/assets/93641486/8e4dd27b-edb4-4dcd-8fcb-992d843df39e

**Comment by ramkumarsync** [comment]
In SfPdfViewer, we planned to deliver the active viewport/tiled rendering support in the 2024 Volume 1 release which is expected to be available in mid-March 2024. You can track the status of this feature from the below feedback link. We will notify in the feedback link once rolled out.

https://www.syncfusion.com/feedback/31524/active-viewport-rendering
