### ISSUE TITLE
[SfCartesianChart] Trackball's marker overlap text when it is formatted

### ISSUE THREAD

**Issue by komhkomh** [syncfusion/flutter-widgets#1379]
I need to add unit in the trackball templete so that I used format in InteractiveTooltip, then I found marker in the trackball overlapped text which is displayed in the image. And even I remove the format attribute, the overlap is still exist when the decimal precision of yData are different.

![20230906160859636](https://github.com/syncfusion/flutter-widgets/assets/65888407/2030219e-790f-4010-a369-b1dc9a61dd39)

The code is as below. Thanks for your review.
```
class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  late TrackballBehavior _trackballBehavior;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(10, 50),
      ChartSampleData(20, 60),
      ChartSampleData(30, 20),
      ChartSampleData(40, 10),
      ChartSampleData(50, 30),
      ChartSampleData(60, 40),
      ChartSampleData(70, 80),
      ChartSampleData(80, 90),
      ChartSampleData(90, 70),
      ChartSampleData(100, 50),
    ];

    _trackballBehavior = TrackballBehavior(
      enable: true,
      shouldAlwaysShow: true,
      tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
      activationMode: ActivationMode.singleTap,
      tooltipSettings:
          const InteractiveTooltip(format: 'series.name: point.y%'),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 400,
            width: 500,
            child: SfCartesianChart(
              primaryXAxis: NumericAxis(),
              primaryYAxis: NumericAxis(),
              enableSideBySideSeriesPlacement: false,
              series: <CartesianSeries<ChartSampleData, num>>[
                ColumnSeries<ChartSampleData, num>(
                  dataSource: _data,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y,
                ),
                ColumnSeries<ChartSampleData, num>(
                  dataSource: _data,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) =>
                      sales.y - Random().nextDouble() * 10,
                ),
              ],
              trackballBehavior: _trackballBehavior,
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,
 
We are able to replicate the reported issue regarding **Marker and text of the tooltip gets overlap when the text length of the values of multiple series is different** at our end and have logged bug report for it in our feedback portal. We will fix and include the changes after the main release which is expected to be rolled out on end of September 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.

Feedback Link: https://www.syncfusion.com/feedback/46698.

However, you can also try rendering the text of the multiple series inside the tooltip with same length to avoid the mentioned issue for now.
 
Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

Sorry for the inconvenience. We have fixed this issue but due to automation pending at our end, we are unable to move this fix within the end of September. We will move this issue fix in our upcoming weekly release, which is expected to be rolled out on October 3, 2023. We will update you here once the release is rolled out, and we appreciate your patience until then.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh ,

The reported issue regarding **Marker and text of the tooltip gets overlap when the text length of the values of multiple series is different** has been fixed. However, we regret to inform you that due to some automation breaks from end, we are unable to include this fix in the upcoming weekly release as mentioned earlier. We will include it in our next weekly patch release, which is scheduled for 10th October 2023 without fail. We will let you know once the release gets rolled out. We appreciate your patience until then.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @komhkomh,

The reported issue regarding **Marker and text of the tooltip gets overlap when the text length of the values of multiple series is different** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/23.1.40.

Regards,
Hari Hara Sudhan. K.

**Comment by komhkomh** [comment]
Thanks for update!
