### ISSUE TITLE
[syncfusion_flutter_datagrid] Auto fit columns and rows

### ISSUE THREAD

**Issue by gombal88** [syncfusion/flutter-widgets#138]
Hi,
The grid is not able to properly calculate the column width and rows height based on cell content if `GridWidgetColumn` and `cellBuilder` is used. Grid and columns has `SfDataGrid.columnWidthMode.auto` set and `onQueryRowHeight` with `ColumnSizer.getAutoRowHeight()` is called.

**Comment by RenugaSadagoban98** [comment]
Hi Customer,
 
Thanks for contacting Syncfusion support.
 
Currently, SfDataGrid does not have support for autofit (width and height) for the widget column. Initially, the default width is set to the widget column unless you have not set the width to the widget column. We have considered this feature “Support to autofit the widget column based on widget loaded inside it”. This feature will be implemented in our any of our upcoming release.
 
Please refer to the below feedback link for further follow up,
Feedback link: https://www.syncfusion.com/feedback/22622/support-to-autofit-the-column-and-row-for-widget-column


Regards,
Renuga devi S
