### ISSUE TITLE
How to use a button inside annotation in radial gauge?

### ISSUE THREAD

**Issue by shishir2sr** [syncfusion/flutter-widgets#1381]
I want to use a button inside annotation widget of the package. But unfortunately the onPressed button not works. I am assume that other widgets of the package is covering the button.

**Comment by sfHariHaraSudhan** [comment]
Hi @shishir2sr,
 
We would like to let you know that currently we don’t have support for **Need interaction support for the gauge annotations**. However, we have considered your requirement as a new feature and already logged feature request for it in our feedback portal.
 
We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback Link: https://www.syncfusion.com/feedback/32000.

Regards,
Hari Hara Sudhan. K.
