### ISSUE TITLE
add possibility to toggle legend by series index

### ISSUE THREAD

**Issue by sh4nm** [syncfusion/flutter-widgets#1382]
I'm developing dashboard tv app with remote controller navigation using Focus and Shortcuts.

I'm using legendItemBuilder to create custom legends with focus to chose it by remote controller but I can't show/hide series programmatically like just tap to legend.

**Comment by sh4nm** [comment]
don't understand how to make it works like with cursor tap.

https://github.com/syncfusion/flutter-widgets/assets/110997513/6968befb-76f9-4222-a7b9-062b20dc36b7

**Comment by sfHariHaraSudhan** [comment]
Hi @sh4nm,

We understand that you need to toggle the visibility of the series while tapping on the legend item programmatically. You can achieve this requirement by enabling or disabling the [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) property of the respective series based on the legend item tapped. The default value of the [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) property is true. For example, In this case, we have two [Column Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html) along with two legend items. When the FloatingActionButton is clicked, the first series will be displayed only if the [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) property is true. It will not render if the [isVisible](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/isVisible.html) property is false, as shown in the code snippet below.

```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _data;
  bool isFirstSeriesVisible = true;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(x: 10, y1: 50, y2: 40),
      ChartSampleData(x: 20, y1: 60, y2: 80),
      ChartSampleData(x: 30, y1: 20, y2: 90),
      ChartSampleData(x: 40, y1: 10, y2: 70),
      ChartSampleData(x: 50, y1: 30, y2: 50),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SizedBox(
            height: 400,
            width: 500,
            child: SfCartesianChart(
              primaryXAxis: NumericAxis(),
              primaryYAxis: NumericAxis(),
              enableSideBySideSeriesPlacement: true,
              legend: const Legend(isVisible: true),
              series: <CartesianSeries<ChartSampleData, num>>[
                ColumnSeries<ChartSampleData, num>(
                  dataSource: _data,
                  isVisible: isFirstSeriesVisible,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y1,
                ),
                ColumnSeries<ChartSampleData, num>(
                  dataSource: _data,
                  xValueMapper: (ChartSampleData sales, int index) => sales.x,
                  yValueMapper: (ChartSampleData sales, int index) => sales.y2,
                ),
              ],
            ),
          ),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            setState(() {
              isFirstSeriesVisible = !isFirstSeriesVisible;
            });
          },
          child: const Icon(Icons.touch_app),
        ),
      ),
    );
  }
}

class ChartSampleData {
  final num? x;
  final num? y1;
  final num? y2;

  ChartSampleData({this.x, this.y1, this.y2});
}
```
If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by sh4nm** [comment]
Hi.
Thank you, thats all
