### ISSUE TITLE
set multiple range 

### ISSUE THREAD

**Issue by yogeshkaharmis** [syncfusion/flutter-widgets#1383]
hello,
I want to set multiple range.
how can get this.

**Comment by sfHariHaraSudhan** [comment]
Hi @yogeshkaharmis,

We are unable to understand your need clearly based on the provided query and we need some clarifications regarding the below mentioned points.

1. What is the Syncfusion Flutter Widget you are using?
2. Share some detailed explanation regarding the use case of the mentioned requirement.
3. If possible, Share any recordings or snapshots and code snippet regarding the mentioned requirement.

With that additional information, it will be very helpful for us to provide the best possible solution from our end.

Regards,
Hari Hara Sudhan. K.

**Comment by yogeshkaharmis** [comment]
Hi @sfHariHaraSudhan,
I am using SfDateRangePicker flutter widget. I want to set dynamic multiple date range on widget, but I am not able to set and there are no any function about this. 
![Screenshot (11)](https://github.com/syncfusion/flutter-widgets/assets/138681998/59ba6597-ea6f-4c34-90f5-4249497fa460)
above image for multiple range.

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared information, we have checked and your requirement is “**Selecting multiple date ranges dynamically in the Flutter DateRangePicker**”. By using the **selectedDateRanges** property of the **DateRangePickerController** you can select the more than one date ranges dynamically. We have documentation for the same. Please find it from the following link.

**UG link:** 
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#multi-range-selection

Also, we have prepared the simple sample for dynamic multi range selection. Please find the sample from attached link. We hope that this helps you. Please let us know if you need further assistance.

[dynamic_selected_dateranges.zip](https://github.com/syncfusion/flutter-widgets/files/12595785/dynamic_selected_dateranges.zip)

Regards,
Indumathi R

**Comment by yogeshkaharmis** [comment]
hello, 
I have another issue with week name like (mon, tue, wed, thu), I want show only sun in red color and other in white color. 
it is possible or not?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.
