### ISSUE TITLE
[SfCartesianChart] TrackballBehavior arrow pointer behavior (TrackballDisplayMode)

### ISSUE THREAD

**Issue by RBianko** [syncfusion/flutter-widgets#1384]
Hello, have a small issue with `TrackballBehavior`, I have a custom chart tooltip, and if chart detail appers close to the top or bottom of the view, I have a strage behavior of "arrow pointer" of the tooltip, details on the screens:
First screen, I used `tooltipDisplayMode: TrackballDisplayMode.floatAllPoints`:
![Screenshot_1](https://github.com/syncfusion/flutter-widgets/assets/43778717/0a9f8559-81af-4bae-a228-77f56d83088d)
Stretches to the chart point

Second screen, I used `tooltipDisplayMode: TrackballDisplayMode.nearestPoint`:
![Screenshot_2](https://github.com/syncfusion/flutter-widgets/assets/43778717/663748cf-2b48-42de-b904-b6d1aa32bdf6)
Points right to the chart point, but arrow+tooltip seems like built as column

Expected (correct) result, works well with any `tooltipDisplayMode`:
![Screenshot_3](https://github.com/syncfusion/flutter-widgets/assets/43778717/cda09fde-3a62-443e-8803-a3e5420484bc)

If you need any clarifications, please ask. Thank you.

**Comment by sfHariHaraSudhan** [comment]
Hi @RBianko,

We would like to inform you that the tooltip arrow will be rendered at half the height of the trackball tooltip and if the tooltip height exceeds the plot area height, the tooltip will be positioned below or above within the plot area. As a result, the center of the tooltip height and the data point will not be the same. Therefore, the mentioned behavior will occur in both [TrackballDisplayMode.floatAllPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html) and [TrackballDisplayMode.nearestPoint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html) to denote clearly and it is the current behavior.

However, to avoid this, use the [visibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMinimum.html) and [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/visibleMaximum.html) properties or you can also set [ChartRangePadding.additional](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartRangePadding.html) to the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) property to add some padding to the y-axis based on the provided data points. This will ensure that the tooltip height does not exceed the plot area height, therefore, the arrow will render at the tooltip center. 

Also, shared the User Guide documentation link below regarding the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) property for your reference.

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
