### ISSUE TITLE
Selected date's circle is not centered correctly

### ISSUE THREAD

**Issue by VasilisPH** [syncfusion/flutter-widgets#1385]
In  selectionMode: DateRangePickerSelectionMode.range while clicking on a date the circle is not centered as expceted.
<img width="343" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/89184975/92c57dde-ca72-417c-9b4c-29ef0f27c6ea">

**Comment by adham-ashraf77** [comment]
is there any solution?

**Comment by adham-ashraf77** [comment]
syncfusion_flutter_calendar 22.2.12 to solve it try it now

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you still face an issue with latest charts version.
