### ISSUE TITLE
Dynamic ResourceViewSettings

### ISSUE THREAD

**Issue by erluxman** [syncfusion/flutter-widgets#1386]
We have to provide a fixed ResourceSetting into SfCalendar. But sometimes the height of the calendar resource need to be dynamic in order for it show full appointment if more than one appointments are at one time. 

As you can see here. the height of each row is fixed no matter the count of appointments that need to be adjusted inside it.

<img width="239" alt="CleanShot 2023-09-08 at 21 57 42@2x" src="https://github.com/syncfusion/flutter-widgets/assets/6260014/090ad658-8039-4c17-8a32-dabda3ec6443">

### Similarly

We can't even dectate how we want to show the list of appointments in one day. when there are many appoinements in a day, there doesn't seem to be solution for pixel overflow to bottom. 

Am i missing something? or library is missing all this?

**Comment by IndumathiR-1995** [comment]
Hi,

**Regarding Query: Dynamic ResourceViewSettings.**

We have already logged the feature request for “**Providing a dynamic height support for resource view in the Flutter Calendar (SfCalendar)**”. We will implement this feature in any of our upcoming releases and let you know once the release rolled out. 

You can track the status of this report through the following feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/29362/providing-a-dynamic-height-support-for-resource-view-in-the-flutter 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.

If you have any more specification/suggestions for the feature request, you can add it as a comment in the portal and cast your vote to make it count.

**Regarding Query: there doesn't seem to be solution for pixel overflow to bottom. Am i missing something? or library is missing all this?**

Can you please use **Expanded** widget or **SingleChildScrollView** widget for resolving the pixel overflow issue or else, if possible, can you please share the code snippet. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest version.
