### ISSUE TITLE
SfRangeSlider OnSelected Function

### ISSUE THREAD

**Issue by danieramiz** [syncfusion/flutter-widgets#139]
Right now the widget has a function to onChanged which is ok to get the value of each movement on slider. 
But in my case would be great a function that only triggers when is user stop selecting the value on the slider, I need to make API call to filter some data with the daterange on the slider so in that case the onchanged calls the API alot of times while the member is selecting the daterange.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,  
 
Greetings from Syncfusion.  
  
Though this is not possible using **SfRangeSlider**, could you please check the below behavior of our **SfRangeSelector** widget will be suitable for you?  
  
You may restrict the call to the onChanged callback while thumbs are being dragged continuously using **SfRangeSelector.enableDeferredUpdate** property. The delay in the update can be achieved by setting the **SfRangeSelector.deferredUpdateDelay** property.The default value of the deferredUpdateDelay property is 500 milliseconds.  
  
It will invoke the onChanged callback when the thumb is dragged and held for the duration specified in the deferredUpdateDelay. However, thumb values are immediately updated in touch up action. 

**Code Snippet:**

`import 'package:flutter/material.dart';
  import 'package:flutter/rendering.dart';
  import 'package:intl/intl.dart' show DateFormat;
  import 'package:syncfusion_flutter_sliders/sliders.dart';

  class RangeSelectorPage extends StatefulWidget {
  @override
  _RangeSelectorPageState createState() => _RangeSelectorPageState();
  }

  class _RangeSelectorPageState extends State<RangeSelectorPage> {
    final DateTime _min = DateTime(2010, 01, 01, 0),
      _max = DateTime(2015, 01, 01);
   final SfRangeValues _initialValues =
   SfRangeValues(DateTime(2012, 01, 01, 0), DateTime(2013, 01, 01, 0));

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Deferred update')),
      body: Container(
        padding: const EdgeInsets.only(top: 30),
        width: 400,
        child: SfRangeSelector(
          min: _min,
          max: _max,
          initialValues: _initialValues,
          interval: 1,
          enableDeferredUpdate: true,
          deferredUpdateDelay: 500,
          dateIntervalType: DateIntervalType.years,
          dateFormat: DateFormat.y(),
          showTicks: true,
          showLabels: true,
          onChanged: (SfRangeValues values) {},
          child: SizedBox(),
        ),
      ),
    );
  }
} `

**UG link:** https://help.syncfusion.com/flutter/range-selector/range-controller#deferred-update   
  
Kindly check whether able to fulfil your requirement with the above code snippet. If your requirement is different from the above, kindly provide brief details about your requirement.  
  
Regards,  
Lakshmi R.

**Comment by danieramiz** [comment]
Thats the perfect solution.

Thank you
