### ISSUE TITLE
Flutter SfDataGrid While Pressing Keyupdown into TextField Move selection between SfDataGrid

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1390]
i am using textfield to filter SfDataGrid data . i want to always stay in textfield and with up and down arrow want to move between SfDataGrid .
Requirement:- 
1-1st Row Selected need to highlighted on initial.
2- When i press down-arrow key then page don't scrolling .

below is my code

  import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Employee> employees = <Employee>[];
  late EmployeeDataSource employeeDataSource;
  late TextEditingController filterController;
  late FocusNode filterFocusNode;

    int currentSelectedIndex = 0;
    
  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
//
    filterController = TextEditingController();
    filterFocusNode = FocusNode();
  }

  @override
  void dispose() {
    filterController.dispose();
    filterFocusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: RawKeyboardListener(
        focusNode: filterFocusNode,
        onKey: (RawKeyEvent event) {
              currentSelectedIndex = employeeDataSource.dataGridController.currentCell.rowIndex;
              if (event is RawKeyDownEvent && event.logicalKey == LogicalKeyboardKey.arrowDown) {
              if(currentSelectedIndex>=0 && currentSelectedIndex<employeeDataSource.rows.length-1)
                {
                  currentSelectedIndex +=1;
                  employeeDataSource.dataGridController.selectedIndex = currentSelectedIndex;
                }
                // Call your function here when arrow key down is pressed
                print('Arrow key down event occurred!');
              }
              else if (event is RawKeyDownEvent && event.logicalKey == LogicalKeyboardKey.arrowUp) {
            if(currentSelectedIndex > 0 && currentSelectedIndex <= (employeeDataSource.rows.length))
              {
                currentSelectedIndex-= 1;
                employeeDataSource.dataGridController.selectedIndex = currentSelectedIndex;
              }

                // Call your function here when arrow key down is pressed
                print('Arrow key up event occurred!');

              }
              else if(event is RawKeyDownEvent && event.logicalKey == LogicalKeyboardKey.enter)
                {
                  print(currentSelectedIndex);
                }
        },
        child: Column(
          children: [
            TextField(
              controller: filterController,
              onChanged: (text) {
                // Apply filtering based on the text entered in the TextField
                final filteredEmployees = employees
                    .where((e) =>
                    e.name.toLowerCase().contains(text.toLowerCase()))
                    .toList();
                employeeDataSource.updateEmployees(filteredEmployees);
              },
            ),
            Expanded(
              child: SfDataGrid(
                source: employeeDataSource,
                controller:employeeDataSource.dataGridController,
                columnWidthMode: ColumnWidthMode.fill,
                selectionMode: SelectionMode.single,
                columns: <GridColumn>[
                  GridColumn(
                      columnName: 'id',
                      label: Container(
                          padding: EdgeInsets.all(16.0),
                          alignment: Alignment.center,
                          child: Text(
                            'ID',
                          ))),
                  GridColumn(
                      columnName: 'name',
                      label: Container(
                          padding: EdgeInsets.all(8.0),
                          alignment: Alignment.center,
                          child: Text('Name'))),
                  GridColumn(
                      columnName: 'designation',
                      label: Container(
                          padding: EdgeInsets.all(8.0),
                          alignment: Alignment.center,
                          child: Text(
                            'Designation',
                            overflow: TextOverflow.ellipsis,
                          ))),
                  GridColumn(
                      columnName: 'salary',
                      label: Container(
                          padding: EdgeInsets.all(8.0),
                          alignment: Alignment.center,
                          child: Text('Salary'))),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'James', 'Project Lead', 20000),
      Employee(10002, 'Kathryn', 'Manager', 30000),
      Employee(10003, 'Lara', 'Developer', 15000),
      Employee(10004, 'Michael', 'Designer', 15000),
      Employee(10005, 'Martin', 'Developer', 15000),
      Employee(10006, 'Newberry', 'Developer', 15000),
      Employee(10007, 'Balnc', 'Developer', 15000),
      Employee(10008, 'Perry', 'Developer', 15000),
      Employee(10009, 'Gable', 'Developer', 15000),
      Employee(10010, 'Grimes', 'Developer', 15000)
    ];
  }

}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource({required List<Employee> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
      DataGridCell<int>(columnName: 'id', value: e.id),
      DataGridCell<String>(columnName: 'name', value: e.name),
      DataGridCell<String>(
          columnName: 'designation', value: e.designation),
      DataGridCell<int>(columnName: 'salary', value: e.salary),
    ]))
        .toList();
  }

  DataGridController dataGridController = DataGridController();

  late List<DataGridRow> _employeeData;

  @override
  List<DataGridRow> get rows => _employeeData;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
          return Container(
            alignment: Alignment.center,
            padding: EdgeInsets.all(8.0),
            child: Text(e.value.toString()),
          );
        }).toList());
  }

  void updateEmployees(List<Employee> employees) {
    _employeeData = employees
        .map<DataGridRow>((e) => DataGridRow(cells: [
      DataGridCell<int>(columnName: 'id', value: e.id),
      DataGridCell<String>(columnName: 'name', value: e.name),
      DataGridCell<String>(
          columnName: 'designation', value: e.designation),
      DataGridCell<int>(columnName: 'salary', value: e.salary),
    ]))
        .toList();

    if(_employeeData.length>0)
      {
        dataGridController.selectedIndex = 0;
      }

    notifyListeners();
  }
}

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);

  final int id;
  final String name;
  final String designation;
  final int salary;
}

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Based on your requirements and the provided sample, it appears that you are currently listening to keyboard events using  RawKeyboardListener and programmatically setting the next row index to the DataGridController.selectedIndex. It's important to note that by default, the DataGrid does not automatically move or scroll to the selected row defined through the **`DataGridController.selectedIndex`** property. This property is primarily used for selecting rows programmatically and doesn't handle scrolling behavior.

If your intention is to programmatically scroll the DataGrid to a specific row, you should utilize the **`DataGridController.scrollToRow`** property. This property allows you to achieve the desired scrolling effect. To further assist you, please refer to the following code snippet for implementation details:

```dart
   if (currentSelectedIndex >= 0 &&
                currentSelectedIndex < employeeDataSource.rows.length - 1) {
              currentSelectedIndex += 1;
              employeeDataSource.dataGridController.selectedIndex =
                  currentSelectedIndex;
                  
              // Scroll to the current selected index
              employeeDataSource.dataGridController
                  .scrollToRow(currentSelectedIndex.toDouble());

            }

```

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
in this way the behavior of default scrolling is changed.  
as per this code when i press down key it hide previous record butt default scrolling started when focus reached to end.

**Comment by abdulrehmananwar** [comment]
Still waiting for this

**Comment by abdulrehmananwar** [comment]
Still waiting please update on it

**Comment by abdulrehmananwar** [comment]
Option:-1
if there any function to detect last row of visible page then i can make a check on it that if currentrows is pagelastvisible row then scroll 
Option 2
while calling this auto scroll into your package and update
 _employeeDataSource?.dataGridController.selectedIndex  = selectedindex;

please guide me thanks

**Comment by FarjanaParveen** [comment]
Hi @abdulrehmananwar ,

We are closing this ticket as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Farjana Parveen A
