### ISSUE TITLE
[syncfusion_flutter_calendar] ViewHeaderStyle can not change today text color

### ISSUE THREAD

**Issue by NitiLTechscape** [syncfusion/flutter-widgets#1392]
I try to change ViewHeader text color and everything work well except today's day in ViewHeader.

May be there are some other methods but I did not see it in document.

`viewHeaderStyle: sf_calendar.ViewHeaderStyle(
                  dayTextStyle:
                      themeManager.body4(color: themeManager.themeColor4),
                ),`

![Screenshot 2566-09-11 at 17 30 07](https://github.com/syncfusion/flutter-widgets/assets/116702363/58f3c2d5-6942-463c-859f-d484194349c6)

**Comment by IndumathiR-1995** [comment]
Hi,

**Regarding Query: ViewHeaderStyle can not change today text color.**

As per the current implementation, TextColor property of the viewHeaderStyle doesn’t change the Today text.  By using the todayHighlightColor, you can change color of the Today day text of the view header is. So, kindly use the **todayHighlightColor** property for the today day text color. We have attached code snippet and screenshot for the same.

**Code snippet:**
```
  child: SfCalendar(
	view: CalendarView.month,
	viewHeaderStyle:
		ViewHeaderStyle(dayTextStyle: TextStyle(color: Colors.amber)),
	todayHighlightColor: Colors.amber,
	dataSource: _getCalendarDataSource(),
  ),
```

**Screenshot:**

![Screenshot 2023-09-12 114326](https://github.com/syncfusion/flutter-widgets/assets/48712435/b1120210-b306-4daa-9386-1b923d3c967e)

Also please find the UG link for today high light color.

**UG link:**
https://help.syncfusion.com/flutter/calendar/getting-started#today-highlight-color

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by NitiLTechscape** [comment]
Thank you very much for your assistance.
