### ISSUE TITLE
When I use SfDateRangePicker with selectionMode: DateRangePickerSelectionMode.range, and I want to select a range . how I can select the range from the day I select to another day , because when I select a first day the range starts from today

### ISSUE THREAD

**Issue by mazab99** [syncfusion/flutter-widgets#1395]

**Comment by mazab99** [comment]
ex : today is 12 and I select the range from 22 
why it make range from 12 to 22 
I need when I select 22 it shouldn't make the range until I select second day

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
