### ISSUE TITLE
SfDataGrid Can each row support an expandable page, meaning to display an expanded page beneath each row?This is a crucial feature.

### ISSUE THREAD

**Issue by hardgit** [syncfusion/flutter-widgets#1397]
![image](https://github.com/syncfusion/flutter-widgets/assets/31436497/ca84956b-f41a-4358-b6a3-5d8e8e763ce0)

**Comment by hardgit** [comment]
Last year we mentioned implementing the feature where clicking on a row expands to show detailed data, and clicking again collapses it. Is this feature now implemented? This type of functionality is common in front-end JavaScript data tables, and I currently have a pressing need for it as well.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @hardgit,

We regret to inform you that the "**preview rows**" feature has not yet been implemented, and there are currently no immediate plans to implement it. **At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. You can follow up with the following feedback link for further updates.** We appreciate your patience and understanding until then.

**Feedback link: https://www.syncfusion.com/feedback/34627/support-to-show-the-preview-rows** 

Regards,
Tamilarasan

**Comment by FarjanaParveen** [comment]
Hi @hardgit ,

We are closing this ticket as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Farjana Parveen A
