### ISSUE TITLE
How i can apply license key to my flutter application

### ISSUE THREAD

**Issue by skyberk** [syncfusion/flutter-widgets#14]
Hi ,

Firstly thank you for this elegant chart library. I registered your system with Community license programme. I can see my license key on dashboard panel but i did not find any documentation about how i can apply this license on my flutter application. Do I need to take action on my flutter application with this license key ? 

Thanks.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @skyberk,

Thanks for contacting Syncfusion support. 

Find below the documentation for flutter license key generation and registration. 

To generate license key: https://help.syncfusion.com/common/essential-studio/licensing/license-key#how-to-generate-syncfusion-license-key 

To register the license key: https://help.syncfusion.com/common/essential-studio/licensing/license-key#flutter  
 
Note:  
 
License key registration is not required for Flutter if you are using v18.3.0.x or later.
 
Syncfusion license keys are different from Syncfusion unlock keys, find below the details in below knowledge base article,
https://www.syncfusion.com/kb/8950/difference-between-the-unlock-key-and-licensing-key  
 
Let us know if you have any other queries. 

Regards,
Sriram Kiran
