### ISSUE TITLE
Wrong tooltip info shown on data ranga

### ISSUE THREAD

**Issue by azamatdev** [syncfusion/flutter-widgets#1402]
![image](https://github.com/syncfusion/flutter-widgets/assets/29502563/6581bb91-6ce9-405a-b7e4-34c58c720034)
![image](https://github.com/syncfusion/flutter-widgets/assets/29502563/48335507-eefb-4aa7-af0f-8f985ffdb0a9)

I am trying to show tooltip on click. But it is showing unstable and incorrect information. As you can see the image above, it is showing 12 but the actual click point is within 13th range. The second picture has the same problem. It usually happens after zooming in, out and sliding.

````
late TooltipBehavior _tooltipBehavior;

  @override
  void initState() {
    _tooltipBehavior = TooltipBehavior(enable: true, header: "");
    super.initState();
  }
````

```
  _chartInfo() {
    return DefaultRoundedContainer(
      height: 150,
      padding: EdgeInsets.only(
          right: 24,
          top: 24,
          bottom: 24),
      child: SfCartesianChart(
          enableAxisAnimation: true,
          tooltipBehavior: _tooltipBehavior,
          zoomPanBehavior: ZoomPanBehavior(
              enablePinching: true, enablePanning: true, zoomMode: ZoomMode.x),
          title: ChartTitle(text: ''),
          primaryXAxis: DateTimeCategoryAxis(
              intervalType: DateTimeIntervalType.days,
              borderColor: ColorManager.lightPrimaryColor,
              dateFormat:
                  DateFormat("dd.MM", MyAppState.locale.locale.languageCode),
              labelIntersectAction: AxisLabelIntersectAction.rotate45,
              minorGridLines: MinorGridLines(
                  width: 1,
                  dashArray: <double>[4, 6],
                  color: ColorManager.backgroundDark),
              majorGridLines: MajorGridLines(
                  width: 1.0,
                  dashArray: <double>[4, 6],
                  color: ColorManager.backgroundDark),
              labelStyle: TextStyle(fontSize: 8.sp)),
          primaryYAxis: NumericAxis(
              title: AxisTitle(
                  text:"",
              minimum: 0.0,
              borderColor: Colors.blue,
              rangePadding: ChartRangePadding.additional,
              majorGridLines:
                  MajorGridLines(width: 1, color: Colors.grey),
              minorGridLines:
                  MinorGridLines(width: 1, color: Colors.grey),
              majorTickLines:
                  MajorTickLines(size: 1, color: Colors.grey),
              name: 'primaryYAxis'),
          series: <ChartSeries<HashrateList, DateTime>>[
            SplineAreaSeries<HashrateList, DateTime>(
              dataSource: widget.pool.hash rates,
              color: Colors.blue.withOpacity(0.4),
              splineType: SplineType.monotonic,
              borderColor: Colors.blue,
              borderWidth: 2,
              cardinalSplineTension: 1.0,
              xValueMapper: (HashrateList data, _) {
                return DateTime.fromMillisecondsSinceEpoch(data.x);
              },
              yValueMapper: (HashrateList data, _) {
                // Converted the date time y-values from the chart data source to millisecondSinceEpoch
                // integer values and then mapped to numeric y-axis.
                return data.y.toInt();
              },
            )
          ]),
    );
  }`
```

**widget.pool.hashrates** - `HashrateList` data list is response from the server which has only x(unix time) and y(hashrate) values, I would like to put json values here.

`   "hashrateList": [
        {
            "x": 1694257200000,
            "y": 2256.89
        },
        {
            "x": 1694260800000,
            "y": 2251.94
        },
        {
            "x": 1694264400000,
            "y": 2247.66
        },
        {
            "x": 1694268000000,
            "y": 2255.24
        },
        {
            "x": 1694271600000,
            "y": 2276.21
        },
        {
            "x": 1694275200000,
            "y": 2293.1
        },
        {
            "x": 1694278800000,
            "y": 2306.75
        },
        {
            "x": 1694282400000,
            "y": 2313.12
        },
        {
            "x": 1694286000000,
            "y": 2318.47
        },
        {
            "x": 1694289600000,
            "y": 2325.92
        },
        {
            "x": 1694293200000,
            "y": 2333.08
        },
        {
            "x": 1694296800000,
            "y": 2334.76
        },
        {
            "x": 1694300400000,
            "y": 2335.35
        },
        {
            "x": 1694304000000,
            "y": 2338.01
        },
        {
            "x": 1694307600000,
            "y": 2338.3
        },
        {
            "x": 1694311200000,
            "y": 2336.85
        },
        {
            "x": 1694314800000,
            "y": 2335
        },
        {
            "x": 1694318400000,
            "y": 2326.78
        },
        {
            "x": 1694322000000,
            "y": 2319.32
        },
        {
            "x": 1694325600000,
            "y": 2320.55
        },
        {
            "x": 1694329200000,
            "y": 2320.48
        },
        {
            "x": 1694332800000,
            "y": 2309.29
        },
        {
            "x": 1694336400000,
            "y": 2300.43
        },
        {
            "x": 1694340000000,
            "y": 2296.28
        },
        {
            "x": 1694343600000,
            "y": 2300.61
        },
        {
            "x": 1694347200000,
            "y": 2305.49
        },
        {
            "x": 1694350800000,
            "y": 2311.19
        },
        {
            "x": 1694354400000,
            "y": 2314.89
        },
        {
            "x": 1694358000000,
            "y": 2319.33
        },
        {
            "x": 1694361600000,
            "y": 2312.05
        },
        {
            "x": 1694365200000,
            "y": 2301.7
        },
        {
            "x": 1694368800000,
            "y": 2305.34
        },
        {
            "x": 1694372400000,
            "y": 2312.1
        },
        {
            "x": 1694376000000,
            "y": 2315.98
        },
        {
            "x": 1694379600000,
            "y": 2317.02
        },
        {
            "x": 1694383200000,
            "y": 2321.05
        },
        {
            "x": 1694386800000,
            "y": 2323.24
        },
        {
            "x": 1694390400000,
            "y": 2323.63
        },
        {
            "x": 1694394000000,
            "y": 2314.81
        },
        {
            "x": 1694397600000,
            "y": 2273.7
        },
        {
            "x": 1694401200000,
            "y": 2232.93
        },
        {
            "x": 1694404800000,
            "y": 2195.48
        },
        {
            "x": 1694408400000,
            "y": 2163.57
        },
        {
            "x": 1694412000000,
            "y": 2142.61
        },
        {
            "x": 1694415600000,
            "y": 2137.41
        },
        {
            "x": 1694419200000,
            "y": 2141.91
        },
        {
            "x": 1694422800000,
            "y": 2149.42
        },
        {
            "x": 1694426400000,
            "y": 2147.24
        },
        {
            "x": 1694430000000,
            "y": 2141.39
        },
        {
            "x": 1694433600000,
            "y": 2154.24
        },
        {
            "x": 1694437200000,
            "y": 2179.88
        },
        {
            "x": 1694440800000,
            "y": 2208.56
        },
        {
            "x": 1694444400000,
            "y": 2250.36
        },
        {
            "x": 1694448000000,
            "y": 2290.77
        },
        {
            "x": 1694451600000,
            "y": 2318.68
        },
        {
            "x": 1694455200000,
            "y": 2336.28
        },
        {
            "x": 1694458800000,
            "y": 2344.75
        },
        {
            "x": 1694462400000,
            "y": 2353.67
        },
        {
            "x": 1694466000000,
            "y": 2353.26
        },
        {
            "x": 1694469600000,
            "y": 2342.95
        },
        {
            "x": 1694473200000,
            "y": 2341
        },
        {
            "x": 1694476800000,
            "y": 2344.98
        },
        {
            "x": 1694480400000,
            "y": 2347.43
        },
        {
            "x": 1694484000000,
            "y": 2326.63
        },
        {
            "x": 1694487600000,
            "y": 2303.4
        },
        {
            "x": 1694491200000,
            "y": 2286.14
        },
        {
            "x": 1694494800000,
            "y": 2273.76
        },
        {
            "x": 1694498400000,
            "y": 2259.71
        },
        {
            "x": 1694502000000,
            "y": 2243.01
        },
        {
            "x": 1694505600000,
            "y": 2240.77
        },
        {
            "x": 1694509200000,
            "y": 2243.78
        },
        {
            "x": 1694512800000,
            "y": 2249.23
        },
        {
            "x": 1694516400000,
            "y": 2252.93
        },
        {
            "x": 1694520000000,
            "y": 2256.25
        },
        {
            "x": 1694523600000,
            "y": 2256.88
        },
        {
            "x": 1694527200000,
            "y": 2264.26
        },
        {
            "x": 1694530800000,
            "y": 2284.43
        },
        {
            "x": 1694534400000,
            "y": 2309.3
        },
        {
            "x": 1694538000000,
            "y": 2327.86
        },
        {
            "x": 1694541600000,
            "y": 2337.19
        },
        {
            "x": 1694545200000,
            "y": 2345.86
        },
        {
            "x": 1694548800000,
            "y": 2350.89
        },
        {
            "x": 1694552400000,
            "y": 2354.72
        },
        {
            "x": 1694556000000,
            "y": 2354.2
        },
        {
            "x": 1694559600000,
            "y": 2333.47
        },
        {
            "x": 1694563200000,
            "y": 2311.93
        },
        {
            "x": 1694566800000,
            "y": 2293.47
        },
        {
            "x": 1694570400000,
            "y": 2281.32
        },
        {
            "x": 1694574000000,
            "y": 2272.44
        },
        {
            "x": 1694577600000,
            "y": 2269.1
        },
        {
            "x": 1694581200000,
            "y": 2267.28
        },
        {
            "x": 1694584800000,
            "y": 2263.14
        },
        {
            "x": 1694588400000,
            "y": 2258.31
        },
        {
            "x": 1694592000000,
            "y": 2254.43
        },
        {
            "x": 1694595600000,
            "y": 2249.98
        },
        {
            "x": 1694599200000,
            "y": 2244.22
        },
        {
            "x": 1694602800000,
            "y": 2246.29
        },
        {
            "x": 1694606400000,
            "y": 2248.94
        },
        {
            "x": 1694610000000,
            "y": 2253.02
        },
        {
            "x": 1694613600000,
            "y": 2262.39
        },
        {
            "x": 1694617200000,
            "y": 2283.19
        },
        {
            "x": 1694620800000,
            "y": 2303.49
        },
        {
            "x": 1694624400000,
            "y": 2310.13
        },
        {
            "x": 1694628000000,
            "y": 2316.55
        },
        {
            "x": 1694631600000,
            "y": 2328.45
        },
        {
            "x": 1694635200000,
            "y": 2336.5
        },
        {
            "x": 1694638800000,
            "y": 2345.19
        },
        {
            "x": 1694642400000,
            "y": 2350.28
        },
        {
            "x": 1694646000000,
            "y": 2351.97
        },
        {
            "x": 1694649600000,
            "y": 2353.23
        },
        {
            "x": 1694653200000,
            "y": 2354.64
        },
        {
            "x": 1694656800000,
            "y": 2335.7
        },
        {
            "x": 1694660400000,
            "y": 2311.15
        },
        {
            "x": 1694664000000,
            "y": 2292.72
        },
        {
            "x": 1694667600000,
            "y": 2279.07
        },
        {
            "x": 1694671200000,
            "y": 2267.94
        },
        {
            "x": 1694674800000,
            "y": 2259.81
        },
        {
            "x": 1694678400000,
            "y": 2255.07
        },
        {
            "x": 1694682000000,
            "y": 2249.53
        },
        {
            "x": 1694685600000,
            "y": 2248.03
        },
        {
            "x": 1694689200000,
            "y": 2242.84
        },
        {
            "x": 1694692800000,
            "y": 2239.81
        },
        {
            "x": 1694696400000,
            "y": 2244.57
        },
        {
            "x": 1694700000000,
            "y": 2254.99
        },
        {
            "x": 1694703600000,
            "y": 2281.38
        },
        {
            "x": 1694707200000,
            "y": 2306.7
        },
        {
            "x": 1694710800000,
            "y": 2324.09
        },
        {
            "x": 1694714400000,
            "y": 2335.67
        },
        {
            "x": 1694718000000,
            "y": 2344.2
        },
        {
            "x": 1694721600000,
            "y": 2347.55
        },
        {
            "x": 1694725200000,
            "y": 2349.48
        },
        {
            "x": 1694728800000,
            "y": 2348.11
        },
        {
            "x": 1694732400000,
            "y": 2345.27
        },
        {
            "x": 1694736000000,
            "y": 2347.51
        },
        {
            "x": 1694739600000,
            "y": 2345.13
        },
        {
            "x": 1694743200000,
            "y": 2326.85
        },
        {
            "x": 1694746800000,
            "y": 2292.13
        },
        {
            "x": 1694750400000,
            "y": 2261.07
        },
        {
            "x": 1694754000000,
            "y": 2247.29
        },
        {
            "x": 1694757600000,
            "y": 2245.26
        },
        {
            "x": 1694761200000,
            "y": 2246.27
        },
        {
            "x": 1694764800000,
            "y": 2248.72
        },
        {
            "x": 1694768400000,
            "y": 2251.88
        },
        {
            "x": 1694772000000,
            "y": 2253.44
        },
        {
            "x": 1694775600000,
            "y": 2255.81
        },
        {
            "x": 1694779200000,
            "y": 2257.75
        },
        {
            "x": 1694782800000,
            "y": 2258.32
        },
        {
            "x": 1694786400000,
            "y": 2263.89
        },
        {
            "x": 1694790000000,
            "y": 2287.1
        },
        {
            "x": 1694793600000,
            "y": 2311.6
        },
        {
            "x": 1694797200000,
            "y": 2328.09
        },
        {
            "x": 1694800800000,
            "y": 2334.06
        },
        {
            "x": 1694804400000,
            "y": 2342.13
        },
        {
            "x": 1694808000000,
            "y": 2346.24
        },
        {
            "x": 1694811600000,
            "y": 2349.02
        },
        {
            "x": 1694815200000,
            "y": 2351.41
        },
        {
            "x": 1694818800000,
            "y": 2354.86
        },
        {
            "x": 1694822400000,
            "y": 2355.61
        },
        {
            "x": 1694826000000,
            "y": 2355.7
        },
        {
            "x": 1694829600000,
            "y": 2357.53
        },
        {
            "x": 1694833200000,
            "y": 2356.88
        },
        {
            "x": 1694836800000,
            "y": 2355.8
        },
        {
            "x": 1694840400000,
            "y": 2358.44
        },
        {
            "x": 1694844000000,
            "y": 2360.39
        },
        {
            "x": 1694847600000,
            "y": 2356.18
        },
        {
            "x": 1694851200000,
            "y": 2353.45
        },
        {
            "x": 1694854800000,
            "y": 2354.77
        },
        {
            "x": 1694858400000,
            "y": 2354.27
        },
        {
            "x": 1694862000000,
            "y": 2360.75
        }
    ],`

if you zoom in and out, this inconsistency happens. Could you please fix this? Please let me know if you need anything extra.

**Comment by azamatdev** [comment]
Hi @sfHariHaraSudhan, thank you for your detailed answer. I changed DateTimeCategoryAxis for the DateTimeAxis for the primaryXAxis. And put time interval 1 for different interval types. The issue still remains. I understand your example with 12-hour format. But in the data, it mainly returns 24 hour period of time. It would be really great if the tooltip show the correct info whenever clicking on the point. Could you please help me with this?

**Comment by LokeshPalani** [comment]
Hi @azamatdev,

We have used [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html) instead of [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html) in the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html), the tooltip information was displayed properly. When tapping on the segment, the tooltip will show the correct datetime, and when tapping between the axis labels, the tooltip will display a 30-minute difference. We have modified the sample and attached it below. Please let us know if you have any further needs.

Regards,
Lokesh P.

[github_1402_tooltip.zip](https://github.com/syncfusion/flutter-widgets/files/14311648/github_1402_tooltip.zip)
