### ISSUE TITLE
[SfPdfViewer] Access to visible page coordinates that is being renderd 

### ISSUE THREAD

**Issue by drakejest** [syncfusion/flutter-widgets#1403]
I have a widget that tracks a specific coordinate in a pdf page, what im trying to do is similar to an annotation but instead of the annotation is done within the pdf file it is done on the app(pdf file remains untouched), which means i am not confined to the limits of the inbuilt pdf annotations. This is to my knowledge is impossible to do with continuous page scrolling. Although there is a page change callback i could not think of a way to extrapolate what valid pdf/page coordinates are being displayed. i might be able to get away if it  is only 1 page that is being displayed, the problem is when there is 2 or more partial pages being displayed, i could not tell what coordinates of the first page and second page is being visible.

Proposal ideas:

- [Best Case Scenario] Creation of a new call back something along the lines of  `onPdfMoved()` that gives access to the range of coordinates that being drawn, and some other stuff that might be useful
- A helper function that returns true/fals if a coordinates being passed onto it is currently on view `bool isOnView (int pageNumber, offset coordinates)`
- I think the bare minimum needed for this to be possible is give access to scroll position (can be included in PdfPageChangeDetail so it can be accessed on the onPdfPageChange callback), along with that given the pdfviewer size, zoom level, and some geometry calculation i think it can be now calculated what coordinates are on view. Adding a onscroll callback would also compliment this very well.

Thanks for the great work.

**Comment by deepika134** [comment]
Please find the example application from the attachment (along with the output screen record of the same) for retrieving the tapped coordinates relative to the PDF page. Please find the workflow of this example application below,

We have used the **TapGestureRecoginze**r to catch the tap action and **onTapDown** callback we have called **_getPdfCoordinates()** and **_addTextToPdfCoordinates()** methods.
**_getPdfCoordinates()** method has the logic to return the tapped location coordinates relative to the PDF page.
**_addTextToPdfCoordinates()** method has the logic to add a text to the tapped location in the PDF page.

Note: By keeping this example application as a reference, you can achieve your requirement for calculate the coordinates relative to PDF page and tapped page number.
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/12668608/Sample.zip)

**Comment by drakejest** [comment]
> Please find the example application from the attachment (along with the output screen record of the same) for retrieving the tapped coordinates relative to the PDF page. Please find the workflow of this example application below,
> 
> We have used the **TapGestureRecoginze**r to catch the tap action and **onTapDown** callback we have called **_getPdfCoordinates()** and **_addTextToPdfCoordinates()** methods. **_getPdfCoordinates()** method has the logic to return the tapped location coordinates relative to the PDF page. **_addTextToPdfCoordinates()** method has the logic to add a text to the tapped location in the PDF page.
> 
> Note: By keeping this example application as a reference, you can achieve your requirement for calculate the coordinates relative to PDF page and tapped page number. [Sample.zip](https://github.com/syncfusion/flutter-widgets/files/12668608/Sample.zip)

Can you make it so that the sample program to places a Text widget instead of saving the text inside the PDF file ? Getting the touch coordinates is not the hard part as there is already methods for native in SfPdfViewer. What really is needed is for a way to identify what pdf page and coordinates are in the viewport.

**Comment by deepika134** [comment]
**Regarding adding text widget in SfPdfViewer :**

Currently, we do not have support for the free text annotation in Flutter PdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following for track the status of the feature,
https://www.syncfusion.com/feedback/45202/support-for-free-text-annotations 

**Regarding retrieve the Page coordinates and pagenumber:**

In SfPdfViewer, we have an option for retrieve the page position, position and pagenumber with the help of onTap() callback, which is triggers only when the page is tapped .To know more about the details, Kindly refer the following UG link for know
[Gesture callbacks in Flutter PDF Viewer widget | Syncfusion](https://help.syncfusion.com/flutter/pdf-viewer/gesture-callbacks)

Please check this and let us know if it meets your requirements. If not, kindly share your use case with us. This will be helpful for us to provide a prompt solution as soon as possible.
