### ISSUE TITLE
In SfCartesianChart autoScrollingDelta is not wokring , I want to scroll chart at the last last horizontally but autoScrollingDelta showing no effect

### ISSUE THREAD

**Issue by neerajwork20** [syncfusion/flutter-widgets#1406]
Have a look the code of SfCartesianChart

Container(
              height: 200,
              child: SfCartesianChart(
                enableSideBySideSeriesPlacement: true,
                enableAxisAnimation: true,
                enableMultiSelection: true,
                plotAreaBorderWidth : 0.7,
                // only grapbh auther line width
                plotAreaBorderColor: Colors.grey, // only grapbh auther line color
                zoomPanBehavior: _zoomPanBehavior,
                series: <ChartSeries>[ // <ChartData, int>

                  ColumnSeries<Day, String> (
                      width : 0.25,
                      dataSource: ( (isOptionSelected == 1) ? ( widget.days ?? [] ) : (isOptionSelected == 2) ? (widget.week ?? []) : (widget.month ?? []) ),
                      xValueMapper: (Day data, _) {
                        if ( (isOptionSelected == 2) ) {
                          var parts = (data.date ?? "").split(' ');
                          return "${parts[0].trim()}\n${parts[1].trim()}";
                        } else {
                          return data.date ?? "";
                        }
                      },
                      yValueMapper: (Day data, _) => ( (data.performPercent ?? 0.0) ) ,
                    color: AppColors.lineGraphGreenLight, // AppColors.lineGraphGreenLight,
                      spacing: 0.3,
                      enableTooltip: true,
                      borderRadius: const BorderRadius.only(
                        topRight: Radius.circular(20),
                        topLeft: Radius.circular(20),
                        bottomLeft: Radius.circular(0),
                        bottomRight: Radius.circular(0),
                      ),
                      animationDuration: 1000,
                  ),

                  ColumnSeries<Day, String> (
                      width : 0.25,
                      dataSource: ( (isOptionSelected == 1) ? ( widget.days ?? [] ) : (isOptionSelected == 2) ? (widget.week ?? []) : (widget.month ?? []) ),
                    xValueMapper: (Day data, _) {
                      if ( (isOptionSelected == 2) ) {
                        var parts = (data.date ?? "").split(' ');
                        return "${parts[0].trim()}\n${parts[1].trim()}";
                      } else {
                        return data.date ?? "";
                      }
                    },
                    yValueMapper: (Day data, _) => ((data.reportedPercent ?? 0.0) ),
                    color: AppColors.lineGraphGreenDark, // AppColors.lineGraphGreenDark,
                    spacing: 0.3,
                    borderRadius: const BorderRadius.only(
                      topRight: Radius.circular(20),
                      topLeft: Radius.circular(20),
                      bottomLeft: Radius.circular(0),
                      bottomRight: Radius.circular(0),
                    ),
                    animationDuration: 1000,
                      dataLabelSettings: const DataLabelSettings(isVisible: false)
                  )

                ],

                // Bottom
                primaryXAxis: CategoryAxis (
                    visibleMaximum: 4,
                    labelStyle:  const TextStyle(
                        fontSize: 11,
                    ),
                    isVisible: true,
                    interval: 1,
                    majorGridLines: const MajorGridLines(width: 0.0, color: Colors.black),
                    majorTickLines : const MajorTickLines(width: 0.0, color: Colors.black),
                    labelIntersectAction: AxisLabelIntersectAction.wrap,

                    autoScrollingDelta : 5,
                    autoScrollingMode : AutoScrollingMode.start
                ),
                // Left
                primaryYAxis: NumericAxis(
                    majorGridLines: const MajorGridLines(width: 0.7, color: Colors.black),
                    majorTickLines : const MajorTickLines(width: 0.0, color: Colors.black),
                    interval : 20,
                    minimum: 0.0,
                    maximum: 100.0,
                    labelFormat: '{value}%'
                ),
              ),
            ),

**Comment by neerajwork20** [comment]
Hi @All,

Please help , I needed above issue to be fix, Looking forward to hearing from you

**Comment by sfHariHaraSudhan** [comment]
Hi @neerajwork20,

We have prepared a sample based on the provided code snippet by setting the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) as 5 and [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) as [AutoScrollingMode.start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html) in order to render only five [Column Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) at load time. The remaining [Column Segments](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) will become visible while scrolling the chart by enabling the [enablePanning](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enablePanning.html) property and by setting the [zoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomMode.html) property as [ZoomMode.x](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomMode.html) in the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html) to scroll the chart only horizontally. The [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property is working properly from our end based on the provided code snippet.

It is important to note that the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property is used to display a specified number of segments or data points at load time and the remaining data points can be viewed by scrolling the chart.

If we set an [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) property as [AutoScrollingMode.start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html), only the first set of data points from the data collection, based on the value specified in the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property, will be rendered at load time. The remaining segments will become visible while scrolling the chart from right to left.

If we set an [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingMode.html) property as [AutoScrollingMode.end](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html), only the last set of data points from the data collection, based on the value specified in the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property, will be rendered at load time. The remaining segments will become visible while scrolling the chart from left to right.

Kindly refer the code snippet below:
```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _firstData;
  late List<ChartSampleData> _secondData;
  late ZoomPanBehavior _zoomPanBehavior;

  @override
  void initState() {
    _firstData = [
      ChartSampleData('India', 40),
      ChartSampleData('America', 50),
      ChartSampleData('London', 20),
      ChartSampleData('China', 10),
      ChartSampleData('Japan', 60),
      ChartSampleData('Russia', 80),
      ChartSampleData('New Zealand', 30),
      ChartSampleData('Ireland', 110),
      ChartSampleData('Germany', 140),
      ChartSampleData('Brazil', 130),
      ChartSampleData('Paris', 70),
      ChartSampleData('Argentina', 50),
      ChartSampleData('Mexico', 70),
      ChartSampleData('Pakistan', 60),
      ChartSampleData('Bangladesh', 90),
    ];
    _secondData = [
      ChartSampleData('India', 110),
      ChartSampleData('America', 120),
      ChartSampleData('London', 80),
      ChartSampleData('China', 30),
      ChartSampleData('Japan', 70),
      ChartSampleData('Russia', 90),
      ChartSampleData('New Zealand', 120),
      ChartSampleData('Ireland', 130),
      ChartSampleData('Germany', 60),
      ChartSampleData('Brazil', 90),
      ChartSampleData('Paris', 140),
      ChartSampleData('Argentina', 20),
      ChartSampleData('Mexico', 10),
      ChartSampleData('Pakistan', 80),
      ChartSampleData('Bangladesh', 30),
    ];
    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
      zoomMode: ZoomMode.x,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SizedBox(
          height: 500,
          child: SfCartesianChart(
            enableSideBySideSeriesPlacement: true,
            enableMultiSelection: true,
            plotAreaBorderWidth: 0.7,
            plotAreaBorderColor: Colors.grey,
            zoomPanBehavior: _zoomPanBehavior,
            primaryXAxis: CategoryAxis(
              labelStyle: const TextStyle(
                fontSize: 11,
              ),
              isVisible: true,
              interval: 1,
              majorGridLines: const MajorGridLines(
                width: 0.0,
                color: Colors.black,
              ),
              majorTickLines: const MajorTickLines(
                width: 0.0,
                color: Colors.black,
              ),
              labelIntersectAction: AxisLabelIntersectAction.wrap,
              autoScrollingDelta: 5,
              autoScrollingMode: AutoScrollingMode.start,
            ),
            primaryYAxis: NumericAxis(
              majorGridLines: const MajorGridLines(
                width: 0.7,
                color: Colors.black,
              ),
              majorTickLines: const MajorTickLines(
                width: 0.0,
                color: Colors.black,
              ),
              interval: 20,
              minimum: 0.0,
              maximum: 140.0,
              labelFormat: '{value}%',
            ),
            series: <CartesianSeries<ChartSampleData, String>>[
              ColumnSeries<ChartSampleData, String>(
                width: 0.25,
                dataSource: _firstData,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) => sales.y,
                color: Colors.lightGreenAccent,
                spacing: 0.3,
                enableTooltip: true,
                borderRadius: const BorderRadius.only(
                  topRight: Radius.circular(20),
                  topLeft: Radius.circular(20),
                  bottomLeft: Radius.circular(0),
                  bottomRight: Radius.circular(0),
                ),
                animationDuration: 1000,
              ),
              ColumnSeries<ChartSampleData, String>(
                width: 0.25,
                dataSource: _secondData,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) => sales.y,
                color: Colors.lightBlueAccent,
                spacing: 0.3,
                borderRadius: const BorderRadius.only(
                  topRight: Radius.circular(20),
                  topLeft: Radius.circular(20),
                  bottomLeft: Radius.circular(0),
                  bottomRight: Radius.circular(0),
                ),
                animationDuration: 1000,
                dataLabelSettings: const DataLabelSettings(
                  isVisible: false,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ChartSampleData {
  final String x;
  final num y;

  ChartSampleData(this.x, this.y);
}
```
Shared the UserGuide Documentation link below regarding the Auto Scrolling and Zooming features for your reference.

Auto Scrolling : https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-scrolling.
Zooming : https://help.syncfusion.com/flutter/cartesian-charts/zoom-pan.

Also attached the sample and recording below for your reference. If you still feel that the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property is not working, then, we recommend you share the sample by modifying it according to your needs to reproduce the mentioned behavior with a detailed explanation of your use case and along with any recording or snapshot regarding the requirement. With that additional information, it will be very useful for us to provide possible solution from our end.

Regards,
Hari Hara Sudhan. K.
[_503313.zip](https://github.com/syncfusion/flutter-widgets/files/12659897/_503313.zip)
[503313.zip](https://github.com/syncfusion/flutter-widgets/files/12659903/503313.zip)

**Comment by neerajwork20** [comment]
Thanks , it is working like charm, I just remove visibleMaximum: 4, from CategoryAxis then it start working. visibleMaximum is the real properly was not working with the autoScrollingDelta and autoScrollingMode.

**Comment by neerajwork20** [comment]
I also check if I remove visibleMaximum: 4 then on other chart it showing it's width too much.

can you provide solution to this, it's width should come all same in all the time in all chart data

![Screenshot 2023-09-19 at 7 47 20 PM](https://github.com/syncfusion/flutter-widgets/assets/104897399/6dbb53fa-9159-453d-8e74-199c5954b1b3)
, 
![Screenshot 2023-09-19 at 7 47 08 PM](https://github.com/syncfusion/flutter-widgets/assets/104897399/b46b096a-01fb-4ba9-bf16-ae2622ce6ca8)

![Screenshot 2023-09-19 at 7 47 01 PM](https://github.com/syncfusion/flutter-widgets/assets/104897399/4fe1d042-c782-4aff-a089-98b4ae2d37ee)

**Comment by sfHariHaraSudhan** [comment]
Hi @neerajwork20,

You can achieve the mentioned requirement by rendering the column with the fixed width using the [ColumnSeriesRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeriesRenderer-class.html) and [Column Segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html). In [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html), the [width](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/width.html) property is used to change the width of the rectangle. The default value of the width is 0.7, and the value ranges from 0 to 1. Here, 1 and 0 correspond to 100% and 0% of the available width, respectively.

To render all the [Column Segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) with equal width, you can render the [Column Segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) with the fixed width in the [ColumnSeriesRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeriesRenderer-class.html) by creating a renderer using the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback.

Disclaimer: However, while rendering the [Column Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html) with the fixed width, the [Column Segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html) might overlap with the other [Column Segment](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSegment-class.html).

Kindly refer the code snippet below:
```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  late List<ChartSampleData> _firstData;
  late List<ChartSampleData> _secondData;
  late ZoomPanBehavior _zoomPanBehavior;

  @override
  void initState() {
    _firstData = [
      ChartSampleData('India', 40),
      ChartSampleData('America', 50),
      ChartSampleData('London', 20),
      ChartSampleData('China', 10),
      ChartSampleData('Japan', 60),
      ChartSampleData('Russia', 80),
      ChartSampleData('New Zealand', 30),
      ChartSampleData('Ireland', 110),
      ChartSampleData('Germany', 140),
      ChartSampleData('Brazil', 130),
      ChartSampleData('Paris', 70),
      ChartSampleData('Argentina', 50),
      ChartSampleData('Mexico', 70),
      ChartSampleData('Pakistan', 60),
      ChartSampleData('Bangladesh', 90),
    ];
    _secondData = [
      ChartSampleData('India', 110),
      ChartSampleData('America', 120),
      ChartSampleData('London', 80),
      ChartSampleData('China', 30),
      ChartSampleData('Japan', 70),
      ChartSampleData('Russia', 90),
      ChartSampleData('New Zealand', 120),
      ChartSampleData('Ireland', 130),
      ChartSampleData('Germany', 60),
      ChartSampleData('Brazil', 90),
      ChartSampleData('Paris', 140),
      ChartSampleData('Argentina', 20),
      ChartSampleData('Mexico', 10),
      ChartSampleData('Pakistan', 80),
      ChartSampleData('Bangladesh', 30),
    ];
    _zoomPanBehavior = ZoomPanBehavior(
      enablePanning: true,
      zoomMode: ZoomMode.x,
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SizedBox(
          height: 500,
          child: SfCartesianChart(
            enableSideBySideSeriesPlacement: true,
            enableMultiSelection: true,
            plotAreaBorderWidth: 0.7,
            plotAreaBorderColor: Colors.grey,
            zoomPanBehavior: _zoomPanBehavior,
            primaryXAxis: CategoryAxis(
              labelStyle: const TextStyle(
                fontSize: 11,
              ),
              isVisible: true,
              interval: 1,
              majorGridLines: const MajorGridLines(
                width: 0.0,
                color: Colors.black,
              ),
              majorTickLines: const MajorTickLines(
                width: 0.0,
                color: Colors.black,
              ),
              labelIntersectAction: AxisLabelIntersectAction.wrap,
              autoScrollingDelta: 3,
              autoScrollingMode: AutoScrollingMode.start,
            ),
            primaryYAxis: NumericAxis(
              majorGridLines: const MajorGridLines(
                width: 0.7,
                color: Colors.black,
              ),
              majorTickLines: const MajorTickLines(
                width: 0.0,
                color: Colors.black,
              ),
              interval: 20,
              minimum: 0.0,
              maximum: 140.0,
              labelFormat: '{value}%',
            ),
            series: <CartesianSeries<ChartSampleData, String>>[
              ColumnSeries<ChartSampleData, String>(
                width: 0.25,
                spacing: 0.3,
                dataSource: _firstData,
                animationDuration: 1000,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) => sales.y,
                onCreateRenderer: (series) {
                  return CustomColumnSeriesRenderer(
                    color: Colors.lightGreenAccent,
                  );
                },
              ),
              ColumnSeries<ChartSampleData, String>(
                width: 0.25,
                spacing: 0.3,
                dataSource: _secondData,
                animationDuration: 1000,
                xValueMapper: (ChartSampleData sales, int index) => sales.x,
                yValueMapper: (ChartSampleData sales, int index) => sales.y,
                onCreateRenderer: (series) {
                  return CustomColumnSeriesRenderer(
                    color: Colors.lightBlueAccent,
                  );
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class CustomColumnSeriesRenderer extends ColumnSeriesRenderer {
  CustomColumnSeriesRenderer({required this.color});
  final Color color;
  @override
  ColumnSegment createSegment() {
    return CustomColumnSegment(color: color);
  }
}

class CustomColumnSegment extends ColumnSegment {
  CustomColumnSegment({required this.color});
  final Color color;
  final double width = 20;
  final double cornerRadius = 20; // Radius for top-left and top-right corners

  @override
  void onPaint(Canvas canvas) {
    final double centerX = segmentRect.center.dx;
    final double left = centerX - (width / 2);
    final double right = centerX + (width / 2);
    final Paint paint = Paint();

    paint
      ..color = color
      ..style = PaintingStyle.fill;

    final RRect roundedRect = RRect.fromRectAndCorners(
      Rect.fromLTRB(left, segmentRect.top, right, segmentRect.bottom),
      topLeft: Radius.circular(cornerRadius),
      topRight: Radius.circular(cornerRadius),
    );

    canvas.drawRRect(roundedRect, paint);
  }
}

class ChartSampleData {
  final String x;
  final num y;

  ChartSampleData(this.x, this.y);
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/4de942a0-112c-4d3b-894c-9c140fd5c30d)

Also attached the sample below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[503313.zip](https://github.com/syncfusion/flutter-widgets/files/12684507/503313.zip)
