### ISSUE TITLE
how to create GaugeRange radius

### ISSUE THREAD

**Issue by hoangnam714** [syncfusion/flutter-widgets#1408]
I have an interface like below, how can I customize it like below
<img width="442" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/51524705/87508cc0-ea30-4373-9c7a-0577d8c2da76">

**Comment by sfHariHaraSudhan** [comment]
Hi @hoangnam714, 

We would like to inform you that currently in [SfRadialGauge](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfRadialGauge-class.html), there is no option to render the [Gauge Range](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/GaugeRange-class.html) along with the radius. However, we have considered the Support for corner style to ranges as a new feature and already logged feature request for it in our feedback portal. With the help of this feature, you can be able to achieve the mentioned requirement.
 
We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback Link : https://www.syncfusion.com/feedback/31565

Regards,
Hari Hara Sudhan. K.

**Comment by hoangnam714** [comment]
Thank you, that would be great

**Comment by Abhishek01039** [comment]
Is this feature implemented @sfHariHaraSudhan ?

**Comment by Mugunthan-Ramalingam** [comment]
Hi @Abhishek01039,

As of now, this feature is uncertain and does not have a specific timeline for implementation. We will prioritize features for each release based on demand and priority, so this feature may be available in one of our upcoming releases. You can also track the status of the feature with the feedback provided.

FR link: [Support for corner style to ranges in Flutter | Feedback Portal](https://www.syncfusion.com/feedback/31565/support-for-corner-style-to-ranges)

 
Regards,
Mugunthan.
