### ISSUE TITLE
Can zoomByFactor zoom with signle axis.

### ISSUE THREAD

**Issue by blackpatton17** [syncfusion/flutter-widgets#1411]
To Syncfusion,

zoomByFactor(double factor) in the ZoomPanBehavior now only supports magnifying the chart in the area by applying the zoom factor to both the x-axis and y-axis. So are there any other methods that can programmingly control the zooming behavior of the chart with a specific axis?

**Comment by keskink** [comment]
I need this functionality as well. How can I set zoom only horizontal or vertical. Not both axis.
