### ISSUE TITLE
[SfCalendar] Need option to change for today text color

### ISSUE THREAD

**Issue by PierreNewmans** [syncfusion/flutter-widgets#1413]
How change today text when view mode is month in [syncfusion_flutter_calendar]

**Comment by IndumathiR-1995** [comment]
Hi,

**Regarding Query: Need option to change the today text color.**

By using the color property in the [todayTextStyle](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/todayTextStyle.html), you can change the today text color. Also, you can customize the background, size, font family from the properties of [todayTextStyle](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/todayTextStyle.html). We have attached the code snippet and screenshot for the same.


**Code snippet:**

```
child: SfCalendar(
  view: CalendarView.month,
  todayTextStyle: TextStyle(
	  color: Colors.yellow,
),
  dataSource: _getCalendarDataSource()),
```
**Screenshot:**
![todaytext](https://github.com/syncfusion/flutter-widgets/assets/48712435/43c53f2c-943b-4c60-a976-d5b980ed99e0)

Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by PierreNewmans** [comment]
I'd like to change the color of this text.

![IMG_1400](https://github.com/syncfusion/flutter-widgets/assets/107397158/2e5404d0-44d2-458a-88cc-3981f0ef44c7)

**Comment by IndumathiR-1995** [comment]
Hi,

By using the **todayHighlightColor** property, you can change color of the Today day text of the view header. So, kindly use the todayHighlightColor property for the today day text color. We have attached code snippet  for the same.

**Code snippet:**
```
  child: SfCalendar(
	view: CalendarView.month,
	todayHighlightColor: Colors.amber,
	dataSource: _getCalendarDataSource(),
  ),

```
Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Sumit258000** [comment]
How to change color and style of created event or `dataSource `

**Comment by IndumathiR-1995** [comment]
Hi,

By using the **appointmentTextStyle** property of the calendar, you cann customize the event color and style. We have UG documentation for the same. Please find the UG documentation for the same. 

https://help.syncfusion.com/flutter/calendar/appointments#appearance-customization 
 
We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
