### ISSUE TITLE
 Invalid argument (Unexpected token PdfTokenType.reference before 154580): Instance of '_ErrorType'

### ISSUE THREAD

**Issue by harsh8088** [syncfusion/flutter-widgets#1415]
Getting this exception on SfPdfViewer.network()
Document URL: https://qb-innocirc-backups.s3.ap-south-1.amazonaws.com/Pre-Prod/1/document/2023/9/20/5fec9ea7-765f-4556-9b8b-0931b8f5dd1f.pdf

`E/flutter ( 4846): [ERROR:flutter/runtime/dart_isolate.cc(1097)] Unhandled exception:
E/flutter ( 4846): Invalid argument (Unexpected token PdfTokenType.reference before 154580): Instance of '_ErrorType'
E/flutter ( 4846): #0      PdfParser._error (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_parser.dart:817:5)
E/flutter ( 4846): #1      PdfParser._match (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_parser.dart:779:7)
E/flutter ( 4846): #2      PdfParser._parse (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_parser.dart:233:5)
E/flutter ( 4846): #3      PdfParser.parseOffset (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_parser.dart:229:12)
E/flutter ( 4846): #4      CrossTable.getObject (package:syncfusion_flutter_pdf/src/pdf/implementation/io/cross_table.dart:287:23)
E/flutter ( 4846): #5      PdfCrossTable.getObject (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:1166:27)
E/flutter ( 4846): #6      PdfReferenceHolder.index (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:77:18)
E/flutter ( 4846): #7      PdfReferenceHolder._obtainObject (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:156:11)
E/flutter ( 4846): #8      PdfReferenceHolder.object (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_reference_holder.dart:63:25)
E/flutter ( 4846): #9      PdfPageCollection._getParent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:419:37)
E/flutter ( 4846): #10     PdfPageCollection._returnValue (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:238:43)
E/flutter ( 4846): #11     PdfPageCollection.[]
 (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_collection.dart:62:37)
E/flutter ( 4846): #12     PdfTextExtractor._extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:192:38)
E/flutter ( 4846): #13     PdfTextExtractor.extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:108:12)
E/flutter ( 4846): #14     SfPdfViewerState._extractTextAsync (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1706:30)
E/flutter ( 4846): <asynchronous suspension>`

**PDF Screen keeps on loading like this:**

 
<img width="338" alt="Screenshot 2023-09-20 at 3 13 06 PM" src="https://github.com/syncfusion/flutter-widgets/assets/7496696/7aa1049c-8efb-4ede-adcf-c586c09439cf">

**Widget Code and PDF URL:**

Document URL: https://qb-innocirc-backups.s3.ap-south-1.amazonaws.com/Pre-Prod/1/document/2023/9/20/5fec9ea7-765f-4556-9b8b-0931b8f5dd1f.pdf

<img width="613" alt="Screenshot 2023-09-20 at 3 15 08 PM" src="https://github.com/syncfusion/flutter-widgets/assets/7496696/70ee22a7-7214-4343-b6fd-74da4d776639">

```
[✓] Flutter (Channel stable, 3.13.3, on macOS 12.6.3 21G419 darwin-x64, locale en-IN)
    • Flutter version 3.13.3 on channel stable at /Users/harshbangari/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2524052335 (2 weeks ago), 2023-09-06 14:32:31 -0700
    • Engine revision b8d35810e9
    • Dart version 3.1.1
    • DevTools version 2.25.0
```
 

 sdk: '>=3.1.0 <4.0.0'
 syncfusion_flutter_pdfviewer: ^22.2.12

**Comment by deepika134** [comment]
The provided document [Document URL: <https://qb-innocirc-backups.s3.ap-south-1.amazonaws.com/Pre-Prod/1/document/2023/9/20/5fec9ea7-765f-4556-9b8b-0931b8f5dd1f.pdf>] is corrupted, so the document does not load in the SfPdfViewer. We have checked the provided document in Adobe Acrobat, which also shows the exception and the PDF pages not loaded properly. Some viewers, such as chrome browser, can fix the corrupted entries in a PDF document and load it successfully. However, we do not have this support to fix corrupted entries in a PDF document.
