### ISSUE TITLE
How to show Line's label in LineSeries

### ISSUE THREAD

**Issue by linhlc-agiletech** [syncfusion/flutter-widgets#1416]
<img width="366" alt="Screen Shot 2023-09-20 at 17 12 38" src="https://github.com/syncfusion/flutter-widgets/assets/135201039/5670c4e6-e06c-4a2b-b2a7-850ca60ecb91">

 Hi, like title said, I want to ask if there's anyway to add a text in the middle of line. It will look like the "L1" text above the red dotted line in the image above. I'm using LineSeries and I didn't see any properties that support this. Can anyone help me with the solution?

Thanks in advance.

**Comment by sfHariHaraSudhan** [comment]
Hi @linhlc-agiletech,

Based on the provided snapshot, you can render the text in the middle of the [Line Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) or at any required position using the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property and you can render any widget based on the [data points](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CoordinateUnit.html), [pixel values](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CoordinateUnit.html) or in [percentage](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CoordinateUnit.html) using the [coordinateUnit](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation/coordinateUnit.html) property of the [CartesianChartAnnotation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation-class.html).

Shared the User Guide Documentation and Sample Browser links below regarding the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property for your reference.

UG : https://help.syncfusion.com/flutter/cartesian-charts/annotations.
SB : https://flutter.syncfusion.com/#/cartesian-charts/series-features/annotation/chart-with-annotation.

Kindly refer the code snippet below:
```
class LineCustomization extends StatefulWidget {
  const LineCustomization({super.key});

  @override
  State<LineCustomization> createState() => _LineVerticalState();
}

class _LineVerticalState extends State<LineCustomization> {
  late List<ChartSampleData> _data;

  @override
  void initState() {
    _data = <ChartSampleData>[
      ChartSampleData(x: 01, y: 10),
      ChartSampleData(x: 02, y: 30),
      ChartSampleData(x: 03, y: 10),
      ChartSampleData(x: 04, y: 70),
      ChartSampleData(x: 05, y: 40),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfCartesianChart(
          primaryXAxis: NumericAxis(
            interval: 1,
          ),
          primaryYAxis: NumericAxis(),
          series: <CartesianSeries<ChartSampleData, num>>[
            LineSeries<ChartSampleData, num>(
              dataSource: _data,
              xValueMapper: (ChartSampleData sales, _) => sales.x,
              yValueMapper: (ChartSampleData sales, _) => sales.y,
              markerSettings: const MarkerSettings(isVisible: true),
              dataLabelSettings: const DataLabelSettings(
                isVisible: true,
              ),
            ),
          ],
          annotations: const <CartesianChartAnnotation>[
            CartesianChartAnnotation(
              x: 3.5,
              y: 45,
              coordinateUnit: CoordinateUnit.point,
              horizontalAlignment: ChartAlignment.far,
              widget: Text(
                'L1',
                style: TextStyle(
                  fontSize: 15,
                  color: Colors.red,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class ChartSampleData {
  final num? x;
  final num? y;

  ChartSampleData({
    this.x,
    this.y,
  });
}

```
Snapshot :
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/4372a87f-1719-4e0d-9fdc-7e08e100d4e7)

Also attached the sample below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[504024.zip](https://github.com/syncfusion/flutter-widgets/files/12684432/504024.zip)
