### ISSUE TITLE
[syncfusion_flutter_calendar] add padding to "today" button

### ISSUE THREAD

**Issue by garv-shah** [syncfusion/flutter-widgets#1417]
Hi There! Would it be possible to implement an option to add padding to the header buttons?
<img width="1532" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/64292655/1b5de102-f590-4721-8eff-8596cf0438d5">
Namely, I'd like an option to move the "today" button slightly to the left, as the lack of padding makes it look a bit bad.

Thank you!

**Comment by MuniappanSubramanian** [comment]
@garv-shah 

As per the current implementation of the Flutter calendar does not have direct support to add padding for today button in the header. But you can achieve your requirement by hiding the default header and placing your custom header in the Flutter calendar. For your reference, we have prepared a sample, which is attached,

Refer to our UG document to know more details about date navigation in the Flutter Calendar,
https://help.syncfusion.com/flutter/calendar/date-navigations 

We hope that this helps you. Please let us know if you need further assistance.

[Output.zip](https://github.com/syncfusion/flutter-widgets/files/12699063/Output.zip)
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/12699065/Sample.zip)

**Comment by garv-shah** [comment]
thank you, that worked perfectly!
