### ISSUE TITLE
[syncfusion_flutter_calendar] enexpected null value when enlarging the viewable "all day" events in month view 

### ISSUE THREAD

**Issue by Kuhno92** [syncfusion/flutter-widgets#1418]
<img width="1262" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/5812823/61345f90-7824-43fe-9540-b1e56485bb64">

by clicking on the "+more" button, an unexpected null value error occurs. Also reproducible with the example code, by adding multiple events for one day.
This happens only in "month" view. Not reproducible in "Week" or "Day" view.

======== Exception caught by services library ======================================================
The following TypeErrorImpl was thrown while processing the key message handler:
Unexpected null value.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49        throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 606:63    nullCheck
packages/syncfusion_flutter_calendar/src/calendar/views/calendar_view.dart 4810:54  [_onKeyDown]
packages/flutter/src/widgets/focus_manager.dart 1807:25                             handleKeyMessage
packages/flutter/src/services/hardware_keyboard.dart 899:16                         [_dispatchKeyMessage]
packages/flutter/src/services/hardware_keyboard.dart 964:75                         handleRawKeyMessage
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter/src/services/hardware_keyboard.dart 925:51                         handleRawKeyMessage
packages/flutter/src/services/platform_channel.dart 212:49                          <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter/src/services/platform_channel.dart 211:58                          <fn>
packages/flutter/src/services/binding.dart 479:35                                   <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                  runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                  _async
packages/flutter/src/services/binding.dart 476:98                                   <fn>
lib/_engine/engine/platform_dispatcher.dart 1267:13                                 invoke2
lib/ui/channel_buffers.dart 25:12                                                   invoke
lib/ui/channel_buffers.dart 65:7                                                    push
lib/ui/channel_buffers.dart 131:16                                                  push
lib/_engine/engine/platform_dispatcher.dart 404:25                                  invokeOnPlatformMessage
lib/_engine/engine/raw_keyboard.dart 142:39                                         [_handleHtmlEvent]
lib/_engine/engine/raw_keyboard.dart 12:7                                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 367:37    _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 372:39    dcall
KeyMessage: KeyMessage([KeyDownEvent#d9cec(physicalKey: PhysicalKeyboardKey#700e3(usbHidUsage: "0x000700e3", debugName: "Meta Left"), logicalKey: LogicalKeyboardKey#4b191(keyId: "0x200000106", keyLabel: "Meta Left", debugName: "Meta Left"), character: null, timeStamp: 0:14:56.419099)])
====================================================================================================

**Comment by MuniappanSubramanian** [comment]
@Kuhno92 

We followed the provided instructions to check the reported issue, but we were unable to replicate it on our end. We conducted tests by adding multiple all-day appointments in a single day and by clicking on the 'more button,' both with and without using the appointment builder, and everything appears to be working correctly. For your reference, we have prepared a sample, which is attached.

Please note that the version of SfCalendar used for this test is **23.1.36.**

Please check our sample and let us know if you are still facing the same issue. If the issue persists, please provide us with the following details:

•	Share the architecture of your requirement 
•	Used custom appointment or default appointment?
•	Used SfCalendar version details
•	A video demonstrating the issue you are facing.
•	The code snippets for your calendar implementation.
•	A reproducible sample that demonstrates the issue.

Providing these details would be helpful for us to investigate the issue and provide you with a solution as soon as possible.

[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/12699113/Sample.zip)
[Output.zip](https://github.com/syncfusion/flutter-widgets/files/12699115/Output.zip)

**Comment by Kuhno92** [comment]
It happens for me with the basic example from pub.dev, by just adding multiple all day events.

I am using a Macbook M1
Flutter Doctor:
`[✓] Flutter (Channel stable, 3.10.2, on macOS 13.0.1 22A400 darwin-arm64, locale en-GB)
    • Flutter version 3.10.2 on channel stable at /Users/kuhnico/Applications/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9cd3d0d9ff (4 months ago), 2023-05-23 20:57:28 -0700
    • Engine revision 90fa3ae28f
    • Dart version 3.0.2
    • DevTools version 2.23.1`


See code:

`import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';

void main() {
  return runApp(CalendarApp());
}

/// The app which hosts the home page which contains the calendar on it.
class CalendarApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(title: 'Calendar Demo', home: MyHomePage());
  }
}

/// The hove page which hosts the calendar
class MyHomePage extends StatefulWidget {
  /// Creates the home page to display teh calendar widget.
  const MyHomePage({Key? key}) : super(key: key);

  @override
  // ignore: library_private_types_in_public_api
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SfCalendar(
      view: CalendarView.month,
      dataSource: MeetingDataSource(_getDataSource()),
      // by default the month appointment display mode set as Indicator, we can
      // change the display mode as appointment using the appointment display
      // mode property
      monthViewSettings: const MonthViewSettings(
          appointmentDisplayMode: MonthAppointmentDisplayMode.appointment),
    ));
  }

  List<Meeting> _getDataSource() {
    final List<Meeting> meetings = <Meeting>[];
    final DateTime today = DateTime.now();
    final DateTime startTime = DateTime(today.year, today.month, today.day, 9);
    final DateTime endTime = startTime.add(const Duration(hours: 2));
    meetings.add(Meeting(
        'Conference', startTime, endTime, const Color(0xFF0F8644), false));
    meetings.add(Meeting(
        'Conference1', startTime, endTime, const Color(0xFF0F8644), false));
    meetings.add(Meeting(
        'Conference2', startTime, endTime, const Color(0xFF0F8644), false));
    meetings.add(Meeting(
        'Conference3', startTime, endTime, const Color(0xFF0F8644), false));
    meetings.add(Meeting(
        'Conference4', startTime, endTime, const Color(0xFF0F8644), false));
    return meetings;
  }
}

/// An object to set the appointment collection data source to calendar, which
/// used to map the custom appointment data to the calendar appointment, and
/// allows to add, remove or reset the appointment collection.
class MeetingDataSource extends CalendarDataSource {
  /// Creates a meeting data source, which used to set the appointment
  /// collection to the calendar
  MeetingDataSource(List<Meeting> source) {
    appointments = source;
  }

  @override
  DateTime getStartTime(int index) {
    return _getMeetingData(index).from;
  }

  @override
  DateTime getEndTime(int index) {
    return _getMeetingData(index).to;
  }

  @override
  String getSubject(int index) {
    return _getMeetingData(index).eventName;
  }

  @override
  Color getColor(int index) {
    return _getMeetingData(index).background;
  }

  @override
  bool isAllDay(int index) {
    return _getMeetingData(index).isAllDay;
  }

  Meeting _getMeetingData(int index) {
    final dynamic meeting = appointments![index];
    late final Meeting meetingData;
    if (meeting is Meeting) {
      meetingData = meeting;
    }

    return meetingData;
  }
}

/// Custom business object class which contains properties to hold the detailed
/// information about the event data which will be rendered in calendar.
class Meeting {
  /// Creates a meeting class with required details.
  Meeting(this.eventName, this.from, this.to, this.background, this.isAllDay);

  /// Event name which is equivalent to subject property of [Appointment].
  String eventName;

  /// From which is equivalent to start time property of [Appointment].
  DateTime from;

  /// To which is equivalent to end time property of [Appointment].
  DateTime to;

  /// Background which is equivalent to color property of [Appointment].
  Color background;

  /// IsAllDay which is equivalent to isAllDay property of [Appointment].
  bool isAllDay;
}
`

**Comment by IndumathiR-1995** [comment]
Hi,

As per the shared code snippet, we have checked the mentioned issue “**Exception occurred when clicking the more appointment region in Flutter Calendar**” and we are not able to reproduce the mentioned issue from our end. We have attached the tested sample for the same. Please find the sample from the attached link. We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/13785997/Sample.zip)
