### ISSUE TITLE
Can't use updateDataSource() to fully refresh a SfCartesianChart

### ISSUE THREAD

**Issue by Dragenix1** [syncfusion/flutter-widgets#1419]
Hello! I am currently testing out multiple platforms and chart libraries. My test is a sawtooth like dataset which i send via WebSockets (which is why the following code is written in the channel.stream.listen()). The first update method i tried was to rerender the chart widget which worked pretty easily but as the documentation said isn't recommended. So i tried using the updateDataSource() of the corresponding ChartSeriesController but i'm having a few problems with it:

- When (hopefully correctly) using the updateDataSource() my chart won't display any Line, except when i'm zooming in but it will reset to not showing any line again on the next incoming data (The whole thing is happening in a SfCartesianChart)
- When i put removedDataIndexes first and newIndices second (while only having newIndices.add(i) in the loop above) the chart won't be updated at all
- Same thing happens when i only use updatedDataIndexes (only sending the same amount of datapoints everytime)

The code (More information below the code):

```
void ListenToSocket() {
      channel.stream.listen((message) {
        List<int> oldIndices =
            List<int>.generate(sawToothProfile.length, (index) => index);
        List<int> newIndices = [];

        // channel.sink.add('received!');
        if (isTickRateMessage) {
          isTickRateMessage = false;
        } else {
          isTickRateMessage = true;
        }

        if (isTickRateMessage) {
          print("Tick rate is: $message");
        } else {
          sawToothProfile = [];

          if (!sawToothProfile.isNotEmpty) {
            print("Saw tooth profile is empty");
          }

          List<double> sawToothData = BlobToDoubleList(message);

          for (int i = 0; i < sawToothData.length; i++) {
            double xValue = i.toDouble();
            sawToothProfile.add(DetailedPointCloud(xValue, sawToothData[i]));
            newIndices.add(/*oldIndices.length +*/ i);
          }

          if (sawToothProfile.isNotEmpty) {
            print("Saw tooth profile is definitely not empty");
            _chartSeriesController?.updateDataSource(
              removedDataIndexes: oldIndices,
              addedDataIndexes: newIndices,
            );
          }
        }

        // if (isTickRateMessage) {
        //   print("Sample rate is: $message samples");
        // } else {
        //   List<double> sawToothData = BlobToDoubleList(message);
        //   List<DetailedPointCloud> sawToothProfile = [];
        //   for (int i = 0; i < sawToothData.length; i++) {
        //     double xValue = i.toDouble();
        //     sawToothProfile.add(DetailedPointCloud(xValue, sawToothData[i]));
        //   }
        //
        //   appStateProfile.ChangeBenchmark(sawToothProfile);
        // }
      });
    }
```
    
- isTickRateMessage is used to display the time between the following messages (in my websocket server i can reduce the time between sending the next data set)
- the commented block is the rerender example which works with the provider package but isn't important for this issue
- BlobToDoubleList() is a custom function to well turn the incoming blob of binary data to a usable list of double values

Also when i stop the connection and make tiny changes (like commenting something and saving) the hot reload will trigger my chart to display the correct outcome (as in the last dataset which was send will be displayed)

Thanks in advance!

**Comment by sfHariHaraSudhan** [comment]
Hi @Dragenix1,

We have prepared a sample to refresh the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) every two seconds with random data points using the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method and StreamBuilder widget, based on your specified requirement. In this sample, we render the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) only when we get valid data from the stream or else the CircularProgressIndicator widget will be displayed. 

We initialize the data source of the chart in the initState method and assign it to the dataSource property. We then remove all previous data points from the chartData list and added new random data points. We pass the indexes of the data points to be updated to the updatedDataIndexes parameter of the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method, which updates the chart with new values every two seconds, based on the provided Stream.

Unfortunately, we were unable to replicate the mentioned behavior from our end, as the chart is updated properly based on indexes passed to the updatedDataIndexes parameter. The chart is also updated correctly when we first pass the indexes of the segments to be removed to the removedDataIndexes and then pass the indexes of the segments to be added to the addedDataIndexes of the [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) method.

Kindly refer the code snippet below:
```
class StreamExample extends StatefulWidget {
  const StreamExample({super.key});

  @override
  State<StatefulWidget> createState() {
    return _StreamExampleState();
  }
}

class _StreamExampleState extends State<StreamExample> {
  ChartSeriesController? _chartSeriesController;
  late List<ChartData> chartData;
  late Random _random;

  @override
  void initState() {
    _random = Random();
    chartData = [
      ChartData(0, 30),
      ChartData(1, 50),
      ChartData(2, 20),
      ChartData(3, 40),
      ChartData(4, 60),
      ChartData(5, 70),
    ];
    super.initState();
  }

  Stream<List<ChartData>> generateData() {
    return Stream.periodic(
      const Duration(seconds: 2),
      (int index) => chartData,
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: StreamBuilder<List<ChartData>>(
          stream: generateData(),
          builder:
              (BuildContext context, AsyncSnapshot<List<ChartData>> snapshot) {
            if (snapshot.hasData) {
              chartData.removeRange(0, chartData.length);
              chartData.addAll(
                [
                  ChartData(0, (_random.nextInt(10) * 10)),
                  ChartData(1, (_random.nextInt(10) * 10)),
                  ChartData(2, (_random.nextInt(10) * 10)),
                  ChartData(3, (_random.nextInt(10) * 10)),
                  ChartData(4, (_random.nextInt(10) * 10)),
                  ChartData(5, (_random.nextInt(10) * 10)),
                ],
              );
              _chartSeriesController?.updateDataSource(
                // Uncomment the below lines to remove and add
                // the required data points.
                // removedDataIndexes: [0, 1, 2, 3, 4, 5],
                // addedDataIndexes: [0, 1, 2, 3, 4, 5],
                updatedDataIndexes: [0, 1, 2, 3, 4, 5],
              );
              return Container(
                margin: const EdgeInsets.symmetric(horizontal: 40),
                decoration:
                    BoxDecoration(borderRadius: BorderRadius.circular(7)),
                width: 960,
                height: 360,
                child: SfCartesianChart(
                  primaryXAxis: NumericAxis(
                    interval: 01,
                  ),
                  primaryYAxis: NumericAxis(
                    visibleMinimum: 0,
                    visibleMaximum: 100,
                  ),
                  series: <CartesianSeries<ChartData, num>>[
                    LineSeries<ChartData, num>(
                      onRendererCreated: (ChartSeriesController controller) {
                        _chartSeriesController = controller;
                      },
                      color: Colors.red,
                      animationDuration: 2000,
                      dataSource: chartData,
                      xValueMapper: (ChartData data, _) => data.x,
                      yValueMapper: (ChartData data, _) => data.y,
                    ),
                  ],
                ),
              );
            } else if (snapshot.hasError) {
              return Text(snapshot.error.toString());
            } else {
              return const CircularProgressIndicator();
            }
          },
        ),
      ),
    );
  }
}

class ChartData {
  ChartData(this.x, this.y);

  final num x;
  final num y;
}
```
Also attached the sample and recording below for your reference and we recommend you share the sample by modifying it according to your needs to reproduce the mentioned behavior. Please provide a runnable sample, along with any recordings or snapshots and with that additional information, it will be very useful for us to provide a possible solution from our end.

Regards,
Hari Hara Sudhan. K. 
[504398.zip](https://github.com/syncfusion/flutter-widgets/files/12700788/504398.zip)
[_504398.zip](https://github.com/syncfusion/flutter-widgets/files/12700791/_504398.zip)

**Comment by Dragenix1** [comment]
Thank you very much for your example @sfHariHaraSudhan!
Because of your example i found my mistake:
Dart will generate a new reference of the dataSource when i reset it to 0 entries by doing sawToothProfile = []; but the chart still holds a reference to the first instance of the data. By writing chartData.removeRange(0, chartData.length); like you did it started working, since i'm not creating a new reference anymore.
