### ISSUE TITLE
Empty space between Half circle DoughnutSeries and legend between

### ISSUE THREAD

**Issue by 4estfall** [syncfusion/flutter-widgets#142]
![image](https://user-images.githubusercontent.com/78297465/109310508-f918c400-7887-11eb-8fbe-fcef02452cd0.png)

```dart
class RecordCircular extends StatelessWidget {
  // Tooltip

  @override
  Widget build(BuildContext context) {
    return SfCircularChart(
      margin: EdgeInsets.all(0),
      legend: Legend(
        isVisible: true,
        position: LegendPosition.bottom,
      ),
      series: [
        DoughnutSeries(
          dataSource: [
            {'name': 'label 1', 'value': 1, 'color': Colors.lightGreen},
            {'name': 'label 2', 'value': 5, 'color': Colors.amber},
            {'name': 'label 3', 'value': 5, 'color': Colors.lightBlue},
          ],
          pointColorMapper: (data, _) => data['color'],
          xValueMapper: (data, _) => data['name'],
          yValueMapper: (data, _) => data['value'],
          startAngle: 270,
          endAngle: 90,
        ),
      ],
    );
  }
}
```

How can i get rid of the empty space?

**Comment by Dharanipalani** [comment]
Hi @4estfall,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and your requirement to get rid of empty space between the legend and the chart can be achieved by using **centerY** property which is used to position the chart vertically. Similarly, you can move and place them horizontally at the required place using the **centerX** property. We have attached the screenshot for your reference and please make use of it.  

**Code snippet**
`SfCircularChart( 
  centerY: '750',  
) 
`

Screenshot
![image](https://user-images.githubusercontent.com/19763272/109494124-7b390080-7ab3-11eb-9f11-682e1fe12962.png)

Please revert us if you need any further assistance. 
 
Thanks, 
Dharanitharan. P
