### ISSUE TITLE
[SfMaps] Stroke for individual country

### ISSUE THREAD

**Issue by ozz-rjq** [syncfusion/flutter-widgets#1423]
It's possible to set a custom stroke color/width for all shapes using the `MapShapeLayer`, but seems like there's no way to add a different stroke width and color for an individual shape like we do for colors: https://help.syncfusion.com/flutter/maps/shape#applying-colors-based-on-the-data

**Comment by sfHariHaraSudhan** [comment]
Hi @ozz-rjq,

We would like to inform you that currently, there is no direct option to provide stroke color and stroke width to the individual shapes as similar to applying the color based on data points. However, you can render a new shape within the [MapShapeLayer](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeLayer-class.html) using the [sublayers](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/sublayers.html) property and you can provide the [stroke color](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSublayer/strokeColor.html) and [stroke width](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSublayer/strokeWidth.html) to the [sublayers](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/sublayers.html) based on your requirement as shown in the code snippet below.
```
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late MapShapeSource _shapeSource;
  late MapShapeSource _indiaSubSource;
  late MapShapeSource _australiaSubSource;
  late List<MapModel> _data;
  int index = 0;
  @override
  void initState() {
    _data = <MapModel>[
      MapModel(
        states: 'Angola',
        count: 150,
        name: "Low",
      ),
      MapModel(
        states: 'Brazil',
        count: 250,
        name: "Low",
      ),
      MapModel(
        states: 'China',
        count: 350,
        name: "Low",
      ),
    ];

    _shapeSource = MapShapeSource.asset(
      'assets/world_map.json',
      shapeDataField: 'name',
      dataCount: _data.length,
      primaryValueMapper: (int index) {
        return _data[index].states!;
      },
      shapeColorValueMapper: (int index) {
        return _data[index].count;
      },
      shapeColorMappers: [
        const MapColorMapper(
          from: 101,
          to: 200,
          color: Colors.blue,
          text: 'Angola',
        ),
        const MapColorMapper(
          from: 201,
          to: 300,
          color: Colors.pink,
          text: 'Brazil',
        ),
        const MapColorMapper(
          from: 301,
          to: 400,
          color: Colors.deepPurpleAccent,
          text: 'China',
        ),
      ],
    );
    _indiaSubSource = const MapShapeSource.asset(
      'assets/india.json',
      shapeDataField: 'name',
    );
    _australiaSubSource = const MapShapeSource.asset(
      'assets/australia.json',
      shapeDataField: 'name',
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(10),
        child: SfMaps(
          layers: [
            MapShapeLayer(
              source: _shapeSource,
              color: Colors.grey.shade300,
              sublayers: [
                MapShapeSublayer(
                  source: _indiaSubSource,
                  strokeColor: Colors.blue,
                  strokeWidth: 2,
                ),
                MapShapeSublayer(
                  source: _australiaSubSource,
                  strokeColor: Colors.yellow,
                  strokeWidth: 2,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class MapModel {
  final String? states;
  final num? count;
  final String? name;

  MapModel({
    this.states,
    this.count,
    this.name,
  });
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/381006c2-a7ab-465c-8bc6-869462eccff2)

Shared the User Guide Documentation and Sample Browser links below regarding the [sublayers](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/sublayers.html) for your reference.

UG : https://help.syncfusion.com/flutter/maps/shape-sublayer. 
SB : https://flutter.syncfusion.com/#/maps/shape-layer/sublayer.

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
