### ISSUE TITLE
[syncfusion_flutter_charts]An underline is displayed below the ChartTitle text in SfCartesianChart.

### ISSUE THREAD

**Issue by TakaTeke** [syncfusion/flutter-widgets#1424]
Running on Macos.
For SfCartesianChart, the ChartTitle text is underlined.
Specifying “decoration: TextDecoration.none” in TextStyle has no effect.
For SfCircularChart, no underline is displayed in the ChartTitle text.

**Comment by sfHariHaraSudhan** [comment]
Hi @TakaTeke,

We have prepared a sample in macOS device to render the [Column Series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html) along with the chart [title](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/title.html) using the title property, as per the mentioned query. Unfortunately, we are unable to replicate the mentioned behavior as the chart title is rendering properly without an underline from our end.

Kindly refer the code snippet below:
```
class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SfCartesianChart(
          title: ChartTitle(text: 'Countries with Values'),
          primaryXAxis: CategoryAxis(),
          primaryYAxis: NumericAxis(),
          series: <CartesianSeries<ChartSampleData, String>>[
            ColumnSeries<ChartSampleData, String>(
              dataSource: [
                ChartSampleData('India', 20),
                ChartSampleData('America', 80),
                ChartSampleData('Afghanistan', 40),
                ChartSampleData('London', 60),
                ChartSampleData('Russia', 70),
                ChartSampleData('Brazil', 50),
              ],
              xValueMapper: (ChartSampleData sales, int index) => sales.x,
              yValueMapper: (ChartSampleData sales, int index) => sales.y,
            ),
          ],
        ),
      ),
    );
  }
}

class ChartSampleData {
  final String x;
  final num y;

  ChartSampleData(this.x, this.y);
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/bb69474e-4f84-453e-a59c-bd6f01f24062)

Also attached the sample below for your reference and we recommend you share the sample by modifying it according to your needs to reproduce the mentioned behavior along with any snapshot or recording.

Regards,
Hari Hara Sudhan. K.
[504751.zip](https://github.com/syncfusion/flutter-widgets/files/12700834/504751.zip)
