### ISSUE TITLE
How to make initial view is identical when PdfPageLayoutMode.single or PdfPageLayoutMode.continous

### ISSUE THREAD

**Issue by acilcrew** [syncfusion/flutter-widgets#1426]
how to make initial view is identical when PdfPageLayoutMode.single or PdfPageLayoutMode.continous, PdfPageLayoutMode.continous is showing fullscreen pdf while the single is showing nice center view ?

**Comment by ramkumarsync** [comment]
In Desktop (Windows and Web) platforms, the PDF pages will be rendered with width fitted. This is the default behavior. 

However, your use case can be achieved with the page view mode support which we already logged as a feature request. We do not have any immediate plans to implement this feature. At the planning stage of every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know here when this feature is implemented. You can track the status of this feature request further in the below feedback link.

https://www.syncfusion.com/feedback/50909/support-for-page-view-modes
