### ISSUE TITLE
[syncfusion_flutter_pdfviewer] PDF progress stopped before PDF loaded

### ISSUE THREAD

**Issue by mahendravijay** [syncfusion/flutter-widgets#1428]
In the PDF Viewer, the progress bar stops before the Network PDF is loaded.

**Comment by deepika134** [comment]
We have checked the reported issue on our end, but the progress bar is stopped properly after the document loaded. For your reference, we have attached the document [document URL <https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf> ] and a screen recording of the sample we tested. This can be downloaded from the attachment. Please provide us with the steps to replicate the issue or any videos demonstrating the problem. This will help us provide a prompt solution as soon as possible.
[BD_505737_Output.zip](https://github.com/syncfusion/flutter-widgets/files/12723473/BD_505737_Output.zip)

**Comment by mahendravijay** [comment]
In my app, after progress stops the PDF rendered correctly, but the log didn't stopped. After 10 secs the documentloaded listener calls. My usecase is after PDF loads capture signature and paste that signature inside that PDF. Everything works fine after documentloaded calls. But in the UI it's showing from the network 3-10 secs prior to the listener.
