### ISSUE TITLE
[syncfusion_flutter_datagrid] How to update table without clearing selected rows?

### ISSUE THREAD

**Issue by yosemiteyss** [syncfusion/flutter-widgets#1432]
By default, calling `notifyDataSourceListeners()` in `DataGridSource` will reset all selected rows. Is there easy way to persist the rows selection?

**Comment by ashok-kuvaraja** [comment]
Hi @yosemiteyss,

We suspect that you may be regenerating the data grid rows associated with the `DataGridSource.rows`​ when calling the `notifyDataSourceListeners`​. If this is the case, the list of data grid rows will be generated anew, which will not match with already selected rows in the datagrid. This is likely the reason why the selection isn't maintained for you. In order to maintain the selection in the datagrid rows, we suggest you avoid regenerating the datagrid rows.  Our suggestion is to avoid regenerating the rows to resolve this issue. However, if it is necessary to regenerate the rows for your requirement, you must also update the selected rows collection accordingly. 

In the below sample, we have taken the previous selected rows unique field and reset the selected rows by matching the same unique field. Please refer to the sample below to understand how to update the selected rows based on the regenerated datagrid rows:

```dart
import 'package:flutter/material.dart';

import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Employee> employees = <Employee>[];

  late EmployeeDataSource employeeDataSource;

  late DataGridController controller;

  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
    controller = DataGridController();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: Column(
        children: [
          TextButton(onPressed: refreshRows, child: Text('Rebuild rows')),
          Expanded(
            child: SfDataGrid(
              source: employeeDataSource,
              controller: controller,
              selectionMode: SelectionMode.multiple,
              defaultColumnWidth: 100,
              showCheckboxColumn: true,
              onSelectionChanged: (addedRows, removedRows) {},
              columns: <GridColumn>[
                GridColumn(
                    columnName: 'id',
                    label: Container(
                        padding: EdgeInsets.all(16.0),
                        alignment: Alignment.center,
                        child: Text(
                          'ID',
                        ))),
                GridColumn(
                    columnName: 'name',
                    label: Container(
                        padding: EdgeInsets.all(8.0),
                        alignment: Alignment.center,
                        child: Text('Name'))),
                GridColumn(
                    columnName: 'designation',
                    label: Container(
                        padding: EdgeInsets.all(8.0),
                        alignment: Alignment.center,
                        child: Text(
                          'Designation',
                          overflow: TextOverflow.ellipsis,
                        ))),
                GridColumn(
                    columnName: 'salary',
                    label: Container(
                        padding: EdgeInsets.all(8.0),
                        alignment: Alignment.center,
                        child: Text('Salary'))),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // This method regenerates the datagrid rows and updates the selected rows
  // by comparing the already selected rows in the old datagrid rows collections.
  void refreshRows() {
    List<Employee> employees = <Employee>[
      Employee(10001, 'James', 'Project Lead', 20000),
      Employee(10002, 'Kathryn', 'Manager', 30000),
      Employee(10003, 'Lara', 'Developer', 15000),
    ];

    employeeDataSource
      ..buildDataGridRows(employees)
      ..refreshSelectedRows(controller)
      ..refreshDataGridSource();
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'James', 'Project Lead', 20000),
      Employee(10002, 'Kathryn', 'Manager', 30000),
      Employee(10003, 'Lara', 'Developer', 15000),
      Employee(10004, 'Michael', 'Designer', 15000),
      Employee(10005, 'Martin', 'Developer', 15000),
      Employee(10006, 'Newberry', 'Developer', 15000),
      Employee(10007, 'Balnc', 'Developer', 15000),
      Employee(10008, 'Perry', 'Developer', 15000),
      Employee(10009, 'Gable', 'Developer', 15000),
      Employee(10010, 'Grimes', 'Developer', 15000)
    ];
  }
}

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);

  final int id;

  final String name;

  final String designation;

  final int salary;
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource({required List<Employee> employeeData}) {
    buildDataGridRows(employeeData);
  }

  List<DataGridRow> _employeeData = [];

  @override
  List<DataGridRow> get rows => _employeeData;

  void buildDataGridRows(List<Employee> employeeData) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: EdgeInsets.all(8.0),
        child: Text(e.value.toString()),
      );
    }).toList());
  }

  void refreshSelectedRows(DataGridController controller) {
    List<DataGridRow> newSelectedRows = <DataGridRow>[];

    dynamic getCellValue(DataGridRow row) {
      // I chose 'id' column since it contains the unique values in my collection.
      // If you use a column that contains the duplicate values, it will not work effectively for this case.
      return row
          .getCells()
          .firstWhere((element) => element.columnName == 'id')
          .value;
    }

    for (DataGridRow row in _employeeData) {
      var value = getCellValue(row);

      bool isSelectedRow =
          controller.selectedRows.any((row) => getCellValue(row) == value);

      if (isSelectedRow) {
        newSelectedRows.add(row);
      }
    }

    controller.selectedRows = newSelectedRows;
  }

  void refreshDataGridSource() {
    notifyListeners();
  }
}
```

Regards,
Ashok K

**Comment by yosemiteyss** [comment]
> Hi @yosemiteyss,
> 
> We suspect that you may be regenerating the data grid rows associated with the `DataGridSource.rows`​ when calling the `notifyDataSourceListeners`​. If this is the case, the list of data grid rows will be generated anew, which will not match with already selected rows in the datagrid. This is likely the reason why the selection isn't maintained for you. In order to maintain the selection in the datagrid rows, we suggest you avoid regenerating the datagrid rows. Our suggestion is to avoid regenerating the rows to resolve this issue. However, if it is necessary to regenerate the rows for your requirement, you must also update the selected rows collection accordingly.
> 
> In the below sample, we have taken the previous selected rows unique field and reset the selected rows by matching the same unique field. Please refer to the sample below to understand how to update the selected rows based on the regenerated datagrid rows:
> 
> ```dart
> import 'package:flutter/material.dart';
> 
> import 'package:syncfusion_flutter_datagrid/datagrid.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Syncfusion DataGrid Demo',
>       theme: ThemeData(primarySwatch: Colors.blue),
>       home: MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   MyHomePage({Key? key}) : super(key: key);
> 
>   @override
>   _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> {
>   List<Employee> employees = <Employee>[];
> 
>   late EmployeeDataSource employeeDataSource;
> 
>   late DataGridController controller;
> 
>   @override
>   void initState() {
>     super.initState();
>     employees = getEmployeeData();
>     employeeDataSource = EmployeeDataSource(employeeData: employees);
>     controller = DataGridController();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Syncfusion Flutter DataGrid'),
>       ),
>       body: Column(
>         children: [
>           TextButton(onPressed: refreshRows, child: Text('Rebuild rows')),
>           Expanded(
>             child: SfDataGrid(
>               source: employeeDataSource,
>               controller: controller,
>               selectionMode: SelectionMode.multiple,
>               defaultColumnWidth: 100,
>               showCheckboxColumn: true,
>               onSelectionChanged: (addedRows, removedRows) {},
>               columns: <GridColumn>[
>                 GridColumn(
>                     columnName: 'id',
>                     label: Container(
>                         padding: EdgeInsets.all(16.0),
>                         alignment: Alignment.center,
>                         child: Text(
>                           'ID',
>                         ))),
>                 GridColumn(
>                     columnName: 'name',
>                     label: Container(
>                         padding: EdgeInsets.all(8.0),
>                         alignment: Alignment.center,
>                         child: Text('Name'))),
>                 GridColumn(
>                     columnName: 'designation',
>                     label: Container(
>                         padding: EdgeInsets.all(8.0),
>                         alignment: Alignment.center,
>                         child: Text(
>                           'Designation',
>                           overflow: TextOverflow.ellipsis,
>                         ))),
>                 GridColumn(
>                     columnName: 'salary',
>                     label: Container(
>                         padding: EdgeInsets.all(8.0),
>                         alignment: Alignment.center,
>                         child: Text('Salary'))),
>               ],
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> 
>   // This method regenerates the datagrid rows and updates the selected rows
>   // by comparing the already selected rows in the old datagrid rows collections.
>   void refreshRows() {
>     List<Employee> employees = <Employee>[
>       Employee(10001, 'James', 'Project Lead', 20000),
>       Employee(10002, 'Kathryn', 'Manager', 30000),
>       Employee(10003, 'Lara', 'Developer', 15000),
>     ];
> 
>     employeeDataSource
>       ..buildDataGridRows(employees)
>       ..refreshSelectedRows(controller)
>       ..refreshDataGridSource();
>   }
> 
>   List<Employee> getEmployeeData() {
>     return [
>       Employee(10001, 'James', 'Project Lead', 20000),
>       Employee(10002, 'Kathryn', 'Manager', 30000),
>       Employee(10003, 'Lara', 'Developer', 15000),
>       Employee(10004, 'Michael', 'Designer', 15000),
>       Employee(10005, 'Martin', 'Developer', 15000),
>       Employee(10006, 'Newberry', 'Developer', 15000),
>       Employee(10007, 'Balnc', 'Developer', 15000),
>       Employee(10008, 'Perry', 'Developer', 15000),
>       Employee(10009, 'Gable', 'Developer', 15000),
>       Employee(10010, 'Grimes', 'Developer', 15000)
>     ];
>   }
> }
> 
> class Employee {
>   Employee(this.id, this.name, this.designation, this.salary);
> 
>   final int id;
> 
>   final String name;
> 
>   final String designation;
> 
>   final int salary;
> }
> 
> class EmployeeDataSource extends DataGridSource {
>   EmployeeDataSource({required List<Employee> employeeData}) {
>     buildDataGridRows(employeeData);
>   }
> 
>   List<DataGridRow> _employeeData = [];
> 
>   @override
>   List<DataGridRow> get rows => _employeeData;
> 
>   void buildDataGridRows(List<Employee> employeeData) {
>     _employeeData = employeeData
>         .map<DataGridRow>((e) => DataGridRow(cells: [
>               DataGridCell<int>(columnName: 'id', value: e.id),
>               DataGridCell<String>(columnName: 'name', value: e.name),
>               DataGridCell<String>(
>                   columnName: 'designation', value: e.designation),
>               DataGridCell<int>(columnName: 'salary', value: e.salary),
>             ]))
>         .toList();
>   }
> 
>   @override
>   DataGridRowAdapter buildRow(DataGridRow row) {
>     return DataGridRowAdapter(
>         cells: row.getCells().map<Widget>((e) {
>       return Container(
>         alignment: Alignment.center,
>         padding: EdgeInsets.all(8.0),
>         child: Text(e.value.toString()),
>       );
>     }).toList());
>   }
> 
>   void refreshSelectedRows(DataGridController controller) {
>     List<DataGridRow> newSelectedRows = <DataGridRow>[];
> 
>     dynamic getCellValue(DataGridRow row) {
>       // I chose 'id' column since it contains the unique values in my collection.
>       // If you use a column that contains the duplicate values, it will not work effectively for this case.
>       return row
>           .getCells()
>           .firstWhere((element) => element.columnName == 'id')
>           .value;
>     }
> 
>     for (DataGridRow row in _employeeData) {
>       var value = getCellValue(row);
> 
>       bool isSelectedRow =
>           controller.selectedRows.any((row) => getCellValue(row) == value);
> 
>       if (isSelectedRow) {
>         newSelectedRows.add(row);
>       }
>     }
> 
>     controller.selectedRows = newSelectedRows;
>   }
> 
>   void refreshDataGridSource() {
>     notifyListeners();
>   }
> }
> ```
> 
> Regards, Ashok K

Very detailed example. Thanks a lot.
