### ISSUE TITLE
[syncfusion_flutter_sliders] How can i reach the maximum limit of the slider

### ISSUE THREAD

**Issue by quocviet1996** [syncfusion/flutter-widgets#1433]
Hello everyone, my case is that I want to set stepSize to always default 1 and the slider can reach the maximum number (which means 6.4), but this SfSlider doesn't allow me to do that, the maximum I can achieve is 6 and i cannot slide anymore, please help me, thanks.
![image](https://github.com/syncfusion/flutter-widgets/assets/48380821/e782efef-4001-4120-b9c0-e042522292b3)

```
SfSlider(
                                              min: 1,
                                              max: 6.4,
                                              value: a,
                                              stepSize: 1,
                                              showTicks: true,
                                              showDividers: true,
                                              showLabels: true,
                                              inactiveColor: Color(0xFFD9D9D9)
                                                  .withOpacity(0.3),
                                              onChanged: (dynamic value) {
                                                setState(() {
                                                  a = value;
                                                });
                                              },
                                            )
```

**Comment by sfHariHaraSudhan** [comment]
Hi @quocviet1996,

We would like to inform you that if the [stepSize](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/stepSize.html) property is given, then the value of the slider will be increased or decreased based on the value given in the [stepSize](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/stepSize.html) property and it is the current behavior. From the provided code snippet and snapshot, the value of the slider will only be increased or decreased by one as you have set the [stepSize](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/stepSize.html) property as 1. Therefore, you cannot reach the maximum value of 6.4, but you can move the thumb of the slider to its end if you set the [max](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/max.html) property as 7 or 8 and so on.

However, you can also achieve the mentioned requirement by assigning the maximum value to the slider in the [onChangeEnd](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/onChangeEnd.html) callback. Based on the code snippet below, if you complete dragging the slider thumb to 6, then the slider thumb will be moved to its maximum value.

Kindly refer the code snippet :
```
class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  double sliderValue = 1.0;
  double minimum = 1.0;
  double maximum = 6.4;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: SfSlider(
          min: minimum,
          max: maximum,
          value: sliderValue,
          stepSize: 1,
          showTicks: true,
          showDividers: true,
          showLabels: true,
          interval: 1,
          inactiveColor: const Color(0xFFD9D9D9).withOpacity(0.3),
          onChanged: (dynamic value) {
            setState(() {
              sliderValue = value;
            });
          },
          onChangeEnd: (dynamic value) {
            setState(() {
              if (sliderValue == 6) {
                sliderValue = maximum;
              }
            });
          },
        ),
      ),
    );
  }
}
```
Shared the User Guide Documentation and Sample Browser links below regarding the discrete selection of the slider for your reference.

UG : https://help.syncfusion.com/flutter/slider/interval#discrete-selection-for-numeric-values.
SB : https://flutter.syncfusion.com/#/slider/basic-features/step.

Also attached the sample and recording below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[_506473.zip](https://github.com/syncfusion/flutter-widgets/files/12761773/_506473.zip)
[506473.zip](https://github.com/syncfusion/flutter-widgets/files/12761775/506473.zip)
