### ISSUE TITLE
SFDataGrid Controller currentCell always returns -1

### ISSUE THREAD

**Issue by shashkiranr** [syncfusion/flutter-widgets#1435]
Hi,

I am trying to get the current scrolled column or row using DataGridController().currentCell but it always returns 
```
RowColumnPosition { 
              RowIndex =
              -1,
              ColumnIndex =  -1 }
```

Also tried to listen to currentCell by adding a listener in initState but the listener is never called.

`dataGridController.addListener((){});`

I also used the example project and the same behaviour is seen there.

Is there a way to get the current Row/ Column that is scrolled and listen to it?

**Comment by ashok-kuvaraja** [comment]
Hi @shashkiranr,

The purpose of `DataGridController.currentCell` is to obtain the currently selected cell's row and column index in the DataGrid. It works only when we set `SfDataGrid.selectionMode` to something other than none. Currently, the DataGrid does not have support for listening to scrolled row and column indexes. However, we will explore possibilities to fulfill your requirement if you could let us know what you would like to achieve by listening to the scrolled row and column indexes.

Regards,
Ashok K

**Comment by shashkiranr** [comment]
Having an idea which gives the current visible rows and columns is useful for situation where you need to show the same range of cells in different formats.

Eg . When viewing months of a year, if we need to change to weekly view based on the current column or row index, the grid can be scrolled to the respective week in that month. 

There are many such examples which will benefit by having current rows and columns indexes. I think this a basic necessity since the grid is 2D scrollable widget.
