### ISSUE TITLE
how to create paragraph with different text styles in syncfusion flutter pdf

### ISSUE THREAD

**Issue by alihassan143** [syncfusion/flutter-widgets#1438]

**Comment by irfanajaffer** [comment]
We can draw text with various font styles by using ‘PdfTextElement’. We can draw text with fonts which have different font styles and get layout result to maintain the text bounds. Please find the sample to draw text with different font styles from https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_sample_11910101910

Please find the code example below,

`PdfFont regularFont = PdfStandardFont(PdfFontFamily.helvetica, 12);
PdfFont boldFont = PdfStandardFont(PdfFontFamily.helvetica, 12, style: PdfFontStyle.bold);
PdfFont italicFont = PdfStandardFont(PdfFontFamily.helvetica, 12, style: PdfFontStyle.italic);
PdfFont boldItalicFont = PdfStandardFont(PdfFontFamily.helvetica, 12, multiStyle: <PdfFontStyle>[PdfFontStyle.bold, PdfFontStyle.italic]);
 
//Load the text into PdfTextElement with standard font with regular style
PdfTextElement textElement = PdfTextElement(text: 'This is sample text with different font styles like', font: regularFont);
//Draw the text on page and maintain the position in PdfLayoutResult
PdfTextLayoutResult layoutResult = textElement.draw(page: page, bounds: Rect.fromLTWH(0, 50, page.getClientSize().width, 100))! as PdfTextLayoutResult;
 
//Load the text into PdfTextElement with standard font with bold style
textElement = PdfTextElement(text: ' bold,', font: boldFont);
//Draw the text on page and maintain the position in PdfLayoutResult
layoutResult = textElement.draw(page: page, bounds: Rect.fromLTWH(layoutResult.lastLineBounds!.right, 50, page.getClientSize().width - layoutResult.lastLineBounds!.right, 100))! as PdfTextLayoutResult;
 
//Load the text into PdfTextElement with standard font with bold style
textElement = PdfTextElement(text: ' italic,', font: italicFont);
//Draw the text on page and maintain the position in PdfLayoutResult
layoutResult = textElement.draw(page: page, bounds: Rect.fromLTWH(layoutResult.lastLineBounds!.right, 50, page.getClientSize().width - layoutResult.lastLineBounds!.right, 100))! as PdfTextLayoutResult;
 
//Load the text into PdfTextElement with standard font with bold style
textElement = PdfTextElement(text: ' bold and italic.', font: boldItalicFont);
//Draw the text on page and maintain the position in PdfLayoutResult
layoutResult = textElement.draw(page: page, bounds: Rect.fromLTWH(layoutResult.lastLineBounds!.right, 50, page.getClientSize().width - layoutResult.lastLineBounds!.right, 100))! as PdfTextLayoutResult;
 `

**Comment by alihassan143** [comment]
@irfanajaffer  this code work but if i have long strings with different attribute styles and i want to do that dynamically than how can i do that simply because this approach make things complicated and every time i have to find the last rect bound also the top margin etc etc and how it will breaks to next page

**Comment by alihassan143** [comment]
![Screenshot 2024-02-15 at 9 11 19 AM](https://github.com/syncfusion/flutter-widgets/assets/71745182/7c796bdc-2a51-4bfb-a915-3acb98cf4a40)
that is example i want to do that

**Comment by alihassan143** [comment]
@irfanajaffer  pdf package make things simple but it has one issue with page height if its pdf widget exceeds pdf page height it throws error

**Comment by irfanajaffer** [comment]
To achieve your requirement, we can create a sample that draws string dynamically based on different attributes.
 
Kindly use the following link to download the sample template for reference,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_demo_sample1386019140

**Comment by alihassan143** [comment]
@irfanajaffer thanks let me try to apply on my html parser

**Comment by alihassan143** [comment]
@irfanajaffer  that is my repository you know the idea what i am trying to do 
[Repostory](https://github.com/alihassan143/syncpdf)

**Comment by AnanthaGokulaRaman** [comment]
After analyzing the provided repository, it appears that you are attempting to convert HTML strings to PDF using our Syncfusion Flutter PDF library.

Currently, we do not support the conversion of HTML to PDF or HTML strings to PDF in Flutter. We have already logged a feature request for this support on our end. At the moment, we do not have any immediate plans to implement this feature.

Please use the feedback link below to track the status of this feature.
[Add support for converting HTML to PDF in Flutter platform in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/18068/add-support-for-converting-html-to-pdf-in-flutter-platform)
