### ISSUE TITLE
datagrid_widget range error exception

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#1443]
The `GridVirtualizingCellRendererBase.onInitializeDisplayWidget()` method throws `RangeError` in some cases. It looks like it is missing the full range check before retrieving elements from the `cells` array.

<img width="741" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/440954/c3f9ff9a-774f-425b-b682-ba19b628975f">

```
RangeError (length): Invalid value: Not in inclusive range 0..3: 4 
#0 GridVirtualizingCellRendererBase.onInitializeDisplayWidget (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/cell_renderers.dart) 
#1 GridVirtualizingCellRendererBase.onPrepareWidgets (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/cell_renderers.dart:243) 
#2 DataCell.updateColumn (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:132) 
#3 DataRowBase.rowIndexChanged (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:200) 
#4 RowGenerator._updateDataRow (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:1054) 
#5 RowGenerator._updateRow (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:921) 
#6 RowGenerator.ensureRows.reuseRow (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:641) 
#7 RowGenerator.ensureRows (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/generator.dart:688) 
#8 _ScrollViewWidgetState._ensureItems (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:173) 
#9 _ScrollViewWidgetState._ensureWidgets (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:158) 
#10 _ScrollViewWidgetState.build (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:1041) 
#11 StatefulElement.build (package:flutter/src/widgets/framework.dart:5409) 
#12 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297) 
#13 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462) 
#14 Element.rebuild (package:flutter/src/widgets/framework.dart:5016) 
#15 BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779) 
#16 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916) 
#17 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360) 
#18 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297) 
#19 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227) 
#20 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085) 
#21 _rootRun (dart:async/zone.dart:1399) 
#22 _CustomZone.run (dart:async/zone.dart:1301) 
#23 _CustomZone.runGuarded
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov,

In order to provide you with precise assistance, we kindly request that you **provide us with the steps to reproduce the issue** you're encountering. Having a set of reproducible steps will enable us to conduct a comprehensive investigation on our end and offer an effective solution. Furthermore, any additional pertinent information you can provide regarding this issue would greatly enhance our understanding of the situation and our ability to provide you with the appropriate support.

Regards,
Tamilarasan

**Comment by ekuleshov** [comment]
@Tamilarasan-Paranthaman thank you for getting back to me on this. Unfortunately this crash is happening on the user's devices and I only getting the Crashlytics report without much details or context, so I can't really provide an isolated example that would allow to reproduce issue.

However if you look at the screenshot of the `syncfusion_flutter_datagrid` code that I attached in my report above, you can see that the `index` value is only checked for the `-1` value and the code after that fail with the `RagenError` when retrieving element of the `cells` list at that index.

You could add a better range check there, or ensure that the `grid_helper.resolveToDataGridRowAdapterCellIndex(..)` call is returning the `index` value within range of the `dataCell.dataRow!.dataGridRowAdapter!.cells` list.

**Comment by Tamilarasan-Paranthaman** [comment]
@ekuleshov, we are pleased to inform you that we have promptly resolved this matter in our most recent DataGrid version. To ensure you benefit from this fix, we kindly request that you update the syncfusion_flutter_datagrid package to version **23.1.44**.

**Comment by FarjanaParveen** [comment]
Hi @ekuleshov ,

We are suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Farjana Parveen A
