### ISSUE TITLE
Too slow 🐌

### ISSUE THREAD

**Issue by Shubhgajj2004** [syncfusion/flutter-widgets#1445]
Why does it seem very laggy when scrolling through large PDFs? It also takes a long time to open those PDFs.

**Comment by ramkumarsync** [comment]
We are using the plugin-based approach to display the PDF document. For large PDF documents, it would take some time to parse the whole document and to create the document instances on each platform (Android -[ PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer), iOS & macOS -[ CGPDFDocument](https://developer.apple.com/documentation/coregraphics/cgpdfdocument), etc.,). 

We have improvised the lag faced when scrolling through the large PDFs and the changes are available from [v24.1.41](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.1.41). Please check this version and let us know whether you too could see the difference or not. 

We also suspect that you may have deployed your application in Debug mode, could you please check the performance in Release mode and let us know?

**Comment by ramkumarsync** [comment]
We believe that the issue has been resolved after upgrading to the version suggested; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.
