### ISSUE TITLE
Cannot show tool tip when custom primaryYAxis

### ISSUE THREAD

**Issue by vophucson** [syncfusion/flutter-widgets#1447]
**Cannot show tool tip when custom primaryYAxis**
```
class _MyHomePageState extends State<MyHomePage> {
  late TooltipBehavior _tooltipBehavior;
  final List<ChartData> chartData = [
    ChartData(2010, 35),
    ChartData(2011, 28),
    ChartData(2012, 34),
    ChartData(2013, 32),
    ChartData(2014, 40)
  ];
  @override
  void initState() {
    _tooltipBehavior = TooltipBehavior(enable: true);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: SfCartesianChart(
      primaryYAxis: CategoryAxis(),
      tooltipBehavior: _tooltipBehavior,
      series: <ChartSeries>[
        // Renders line chart
        LineSeries<ChartData, int>(
          name: '',
          enableTooltip: true,
          dataSource: chartData,
          xValueMapper: (ChartData data, _) => data.x,
          yValueMapper: (ChartData data, _) => data.y,
          markerSettings: const MarkerSettings(
              isVisible: true, shape: DataMarkerType.circle),
        )
      ],
    )));
  }
}
```
Restarted application in 1,370ms.
Reloaded 1 of 1764 libraries in 333ms (compile: 62 ms, reload: 131 ms, reassemble: 114 ms).
I/chatty  ( 3567): uid=10146(com.example.test_chart) 1.ui identical 6 lines
I/flutter ( 3567): Another exception was thrown: NoSuchMethodError: Class 'CategoryAxis' has no instance getter 'labelFormat'.
I/flutter ( 3567): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3567): The following NoSuchMethodError was thrown while dispatching a pointer event:
I/flutter ( 3567): Class 'CategoryAxis' has no instance getter 'labelFormat'.
I/flutter ( 3567): Receiver: Instance of 'CategoryAxis'
I/flutter ( 3567): Tried calling: labelFormat
I/flutter ( 3567):
I/flutter ( 3567): When the exception was thrown, this was the stack:
I/flutter ( 3567): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
I/flutter ( 3567): #1      getLabelValue (package:syncfusion_flutter_charts/src/chart/utils/helper.dart:1291:17)
I/flutter ( 3567): #2      TooltipRenderingDetails._calculateCartesianTooltipText (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:1785:31)
I/flutter ( 3567): #3      TooltipRenderingDetails._renderCartesianChartTooltip (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:1634:26)
I/flutter ( 3567): #4      TooltipRenderingDetails._renderTooltipView (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:119:7)
I/flutter ( 3567): #5      TooltipRenderingDetails.showTooltipView (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:145:7)
I/flutter ( 3567): #6      TooltipRenderingDetails.showTooltip (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:136:46)
I/flutter ( 3567): #7      TooltipRenderingDetails.internalShowByPixel (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip_rendering_details.dart:849:35)
I/flutter ( 3567): #8      TooltipBehavior.showByPixel (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip.dart:610:24)
I/flutter ( 3567): #9      TooltipBehaviorRenderer.onTouchUp (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip.dart:828:48)
I/flutter ( 3567): #10     _ContainerAreaState._performPointerUp (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:3444:16)
I/flutter ( 3567): #11     _ContainerAreaState.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2474:23)
I/flutter ( 3567): #12     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3090:27)
I/flutter ( 3567): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
I/flutter ( 3567): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
I/flutter ( 3567): #15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
I/flutter ( 3567): #16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
I/flutter ( 3567): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
I/flutter ( 3567): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
I/flutter ( 3567): #19     _invoke1 (dart:ui/hooks.dart:186:13)
I/flutter ( 3567): #20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424:7)
I/flutter ( 3567): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:119:31)
I/flutter ( 3567):
I/flutter ( 3567): Event:
I/flutter ( 3567):   PointerUpEvent#29a74(position: Offset(120.0, 275.7))
I/flutter ( 3567): Target:
I/flutter ( 3567):   RenderPointerListener#0f154
I/flutter ( 3567): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by sfHariHaraSudhan** [comment]
Hi @vophucson,

From the provided code snippet and call stack, we understand your use case and replicated the mentioned exception from our end. When the tooltip gets displayed, by default, it will check whether any [labelFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/labelFormat.html) property of the [Numeric Axis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) has been given to format the y-axis labels. Therefore, as you have given the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) as [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html), the mentioned exception is occurred as the [labelFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/labelFormat.html) property is not available in the [CategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis-class.html).

It is important to note that, by default, the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) renders only the numeric scale values in the vertical axis, as it is the correct behavior. Shared the User Guide documentation link below regarding the rendering of axis for your reference.

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types.

However, if you need to render the tooltip with the y-axis other than [Numeric Axis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html), you can achieve the mentioned requirement by setting the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) as [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html) and as the [labelFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/labelFormat.html) property is available in the [DateTimeAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html), the mentioned exception will not occur. In the below attached sample, we have formatted the axis labels of y-axis from milliseconds values to the datetime value using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback and displayed both the x axis values and y axis values in the tooltip using the [onTooltipRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onTooltipRender.html) callback as shown in the code snippet below.

```
class HomePage extends StatefulWidget {
  const HomePage({super.key});
 
  @override
  State<HomePage> createState() => _HomePageState();
}
 
class _HomePageState extends State<HomePage> {
  late List<ChartData> chartData;
  late TooltipBehavior _tooltipBehavior;
 
  @override
  void initState() {
    chartData = [
      ChartData('2010', DateTime(2001)),
      ChartData('2011', DateTime(2002)),
      ChartData('2012', DateTime(2003)),
      ChartData('2013', DateTime(2004)),
      ChartData('2014', DateTime(2005)),
    ];
    _tooltipBehavior = TooltipBehavior(enable: true, canShowMarker: false);
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: SfCartesianChart(
            onTooltipRender: (tooltipArgs) {
              String xValue = chartData[tooltipArgs.pointIndex!.toInt()].x;
              DateTime date = DateTime.fromMillisecondsSinceEpoch(
                chartData[tooltipArgs.pointIndex!.toInt()]
                    .y
                    .millisecondsSinceEpoch,
              );
              String yValue = DateFormat.y().format(date);
              tooltipArgs.text = 'X => $xValue.\nY => $yValue.';
            },
            primaryXAxis: CategoryAxis(),
            primaryYAxis: DateTimeAxis(
              intervalType: DateTimeIntervalType.years,
              interval: 1,
              axisLabelFormatter: (axisLabelRenderArgs) {
                DateTime date = DateTime.fromMillisecondsSinceEpoch(
                  axisLabelRenderArgs.value.toInt(),
                );
                String formattedDate = DateFormat.y().format(date);
                return ChartAxisLabel(
                  formattedDate,
                  axisLabelRenderArgs.textStyle,
                );
              },
            ),
            series: <CartesianSeries<ChartData, String>>[
              // Renders line chart
              LineSeries<ChartData, String>(
                name: '',
                enableTooltip: true,
                dataSource: chartData,
                xValueMapper: (ChartData data, _) => data.x,
                yValueMapper: (ChartData data, _) =>
                    data.y.millisecondsSinceEpoch,
                markerSettings: const MarkerSettings(
                  isVisible: true,
                  shape: DataMarkerType.circle,
                ),
              ),
            ],
            tooltipBehavior: _tooltipBehavior,
          ),
        ),
      ),
    );
  }
}
 
class ChartData {
  ChartData(
    this.x,
    this.y,
  );
 
  final String x;
  final DateTime y;
}
```
Snapshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/37dd4314-b6a1-4a86-870a-208a0cb38548)

Also attached the sample below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[508274.zip](https://github.com/syncfusion/flutter-widgets/files/12852754/508274.zip)
