### ISSUE TITLE
showDatePickerButton function is not customizable in SyncfusionCalender 

### ISSUE THREAD

**Issue by VaishaliVi** [syncfusion/flutter-widgets#1449]
SfCalendar(
        view: CalendarView.month,
        cellBorderColor: Colors.transparent,
        todayHighlightColor: const Color(0xFF5AA5E2),
        showDatePickerButton: true,
       initialDisplayDate: DateTime(selectedYear, selectedMonth),
        headerStyle: CalendarHeaderStyle(
          textStyle: GoogleFonts.asap(
            textStyle: TextStyle(
              color: const Color(0xFF5AA5E2),
              fontSize: 20.0,
              fontWeight: FontWeight.w700,
            ),
          ),
        ),
        //),
    );                      
 
In this code " showDatePickerButton" is set to true , so after clicking on this button showing in the below image - , it is showing a calender , can we customize that calender.

![Screenshot (716)](https://github.com/syncfusion/flutter-widgets/assets/89640072/96e2da02-bec5-416b-afbc-187c7be9b870)

I am attatching both the calender that it displays and that I want.

I am getting this one  below image

![Screenshot (715)](https://github.com/syncfusion/flutter-widgets/assets/89640072/c6500976-9e34-45ee-b7cb-eaf3e6c3ba4e)

What I want is this (blue colored arrows , year is also in blue color , with rounded boundary , months is in bold font)-
![Event calendar year change - mobile](https://github.com/syncfusion/flutter-widgets/assets/89640072/c7502a87-da6c-4397-a403-5f89d287f545)

Can we do the same for showDatePicker function inside this package ? Can we customize showDatePicker function?
Please  give me some solution as soon as possible.

**Comment by IndumathiR-1995** [comment]
Hi,

As per the current implementation, there is no support to customize the picker header inside the calendar control. But using custom header you can show the DateRangePicker in dialog window and customize the picker as per your requirement. We have prepared the simple sample for the same. Please find the sample from the attached link. We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
[customheader.zip](https://github.com/syncfusion/flutter-widgets/files/13792320/customheader.zip)

**Comment by VaishaliVi** [comment]
Hi ,
I have one more question . After applying multilingual functionality or we
can say that after using app localization package , showDatePickerButton on
click is not opening the calendar .How to resolve this issue?

**Comment by VaishaliVi** [comment]
Thanks

**Comment by VaishaliVi** [comment]
Don't close this ticket . This issue is still not resolved as , after using different date picker it is not able to associate with syncfusion calendar. The value selected from sfdatepicker is not updating whole calendar based on selected values. So provide me some alternative solution to above mentioned **(showdatepickerButton is not working after using localization package**).

**Comment by VaishaliVi** [comment]
My issue is resolved now.

**Comment by Aqitaniya** [comment]
Hi.  How to change background at least? Is it possible?
