### ISSUE TITLE
can i use offline from this map?

### ISSUE THREAD

**Issue by axroromonov** [syncfusion/flutter-widgets#1453]
can i use offline from this map?

**Comment by sfHariHaraSudhan** [comment]
Hi @axroromonov,

Currently, we don’t have support for "**Provide an option to load tiles from local directory**". However, we have considered your requirement as a new feature and already logged feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the below feedback link.

Feedback Link : https://www.syncfusion.com/feedback/25542.

Regards,
Hari Hara Sudhan. K.
