### ISSUE TITLE
Issue with Syncfusion Flutter PDFViewer Plugin in Test Environment

### ISSUE THREAD

**Issue by BorjiAmeni** [syncfusion/flutter-widgets#1454]
In my Flutter project, I've integrated the Syncfusion Flutter PDFViewer plugin and am encountering an issue in my test environment. When attempting to load a PDF, the viewer displays a grey screen with no error messages. It works correctly on my local machine in debug mode. 

Environment Details:

Flutter Version: 3.7.0
Syncfusion Flutter PDFViewer Plugin Version: 19.4.56-beta
Additional Information:

I'm using a community license key for the Syncfusion Flutter PDFViewer plugin in both my local and test environments.

**Comment by deepika134** [comment]
We tried to replicate the reported issue with provided details, but the PDF loaded properly on our side. For your reference, we have attached the sample, which can be downloaded from the attachment. Please review the shared sample. If the issue still occurs on your end, kindly provide us with the steps or a video demonstrating how to reproduce the issue. This will be helpful for us to provide prompt solution at earliest.
Note : Kindly upgrade the latest version of  synfusion flutter PDFViewer [[syncfusion_flutter_pdfviewer | Flutter Package (pub.dev)](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/23.1.40)] 

[github_1454.zip](https://github.com/syncfusion/flutter-widgets/files/12866903/github_1454.zip)

**Comment by BorjiAmeni** [comment]
Hello, @deepika134 . I encountered some errors when upgrading to the latest version of the package.
![Capture d'écran 2023-10-11 152332](https://github.com/syncfusion/flutter-widgets/assets/134378282/d6da1a1b-1b61-48a7-aacf-09ee72c835b3)

**Comment by deepika134** [comment]
Kindly clear the pub cache and update both the Syncfusion Flutter PDFViewer and the Flutter SDK to the latest version to resolve the issue on your side .

Syncfusion Flutter PdfViewer : [syncfusion_flutter_pdfviewer | Flutter Package (pub.dev)]
(https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/23.1.40)

Flutter SDK : https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.13.4-stable.zip
