### ISSUE TITLE
Can't you change the color of the labels on the slider?

### ISSUE THREAD

**Issue by denisgl7** [syncfusion/flutter-widgets#1458]
I looked at the structure of the slider and realized that at the moment it is impossible to change the design of the labels on the slider. What about theme support?

**Comment by sfHariHaraSudhan** [comment]
Hi @denisgl7,

You can change the color of the labels in the slider by wrapping the [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html) widget within the [SfSliderTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderTheme-class.html) widget and by setting the desired text style to the [activeLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeLabelStyle.html) or [inactiveLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveLabelStyle.html) properties of the [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html) according to your needs. It is important to note that you need to import [syncfusion_flutter_core](https://pub.dev/packages/syncfusion_flutter_core) package to use the [SfSliderTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderTheme-class.html) widget in your application.

Additionally, you can also customize the label text of the slider using the [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html) property and shared the Knowledge Base link below for your reference regarding the [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html).

KB : https://support.syncfusion.com/kb/article/11284/how-to-customize-labels-text-in-flutter-slider.

Kindly refer the code snippet below : 
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  double sliderValue = 20.0;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: SfSliderTheme(
          data: SfSliderThemeData(
            activeLabelStyle: const TextStyle(
              fontWeight: FontWeight.bold,
              color: Colors.green,
              fontSize: 16,
            ),
            inactiveLabelStyle: const TextStyle(
              fontWeight: FontWeight.w500,
              color: Colors.red,
              fontSize: 14,
            ),
          ),
          child: SfSlider(
            min: 0.0,
            max: 50.0,
            interval: 10,
            showTicks: true,
            showLabels: true,
            enableTooltip: true,
            value: sliderValue,
            edgeLabelPlacement: EdgeLabelPlacement.auto,
            labelPlacement: LabelPlacement.betweenTicks,
            onChanged: (dynamic values) {
              setState(() {
                sliderValue = values as double;
              });
            },
          ),
        ),
      ),
    );
  }
}
```
Snapshot :
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/67703495-6383-431e-921c-479952ff57b5)

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.

**Comment by rajrushilmakkar** [comment]
Hi @sfHariHaraSudhan, what if I don't want to change it based on active or inactive but want different colors for different labels irrespective of current value but based on the value of where they are located on the slider
for eg. something like this
<img width="678" alt="Screenshot 2023-12-14 at 5 25 39 PM" src="https://github.com/syncfusion/flutter-widgets/assets/56961633/1fe48211-a3f6-40c5-a973-dfae696dbfb5">
In this image, label color depends on the position of label on slider and not on current value of slider
I think it would be simpler if we could just return Text widget instead of a String in {String Function(dynamic, String) labelFormatterCallback}
let me know if there is currently a way to do that or I would love to contribute

**Comment by LokeshPalani** [comment]
Hi,
 
We would like to let you know that currently we don’t have support for ‘Customize the label style individually’. However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.
 
We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

FR Link,
https://www.syncfusion.com/feedback/49315/provide-the-option-to-customize-the-label-style-individually 
 
Regards,
Lokesh P.
