### ISSUE TITLE
pdf drawString

### ISSUE THREAD

**Issue by superAndroidMan** [syncfusion/flutter-widgets#1459]
How can i write string like 'ftH₂O'? now i use font 
‘PdfCjkStandardFont(PdfCjkFontFamily.heiseiMinchoW3, 10);’
The effect is very strange

when i use PdfStandardFont(PdfFontFamily.helvetica, 10), it was error

So I should use that？
Thank you!

**Comment by superAndroidMan** [comment]
<img width="353" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/26271318/4f6770ca-9349-44fe-bf47-9103b1c235b5">

**Comment by karmegams02** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/KARMEG~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/KARMEG~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/KARMEG~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>


<p class=MsoNormal style='margin-bottom:0in;line-height:normal'><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;color:#2D3748;
background:white;mso-font-kerning:0pt;mso-ligatures:none'>The&nbsp;PdfCjkStandardFont&nbsp;fonts
can be only used to render the Chinese, Japanese and Korean characters. We can
preserve the special characters using&nbsp;PdfTrueTypeFont.</span><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;color:#2D3748;
mso-font-kerning:0pt;mso-ligatures:none'><o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal'><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;mso-font-kerning:
0pt;mso-ligatures:none'>&nbsp;<o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:0in;line-height:normal'><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;color:#2D3748;
background:white;mso-font-kerning:0pt;mso-ligatures:none'>Please refer the
below code snippet,&nbsp;</span><span style='mso-ascii-font-family:Calibri;
mso-fareast-font-family:"Times New Roman";mso-hansi-font-family:Calibri;
mso-bidi-font-family:Calibri;color:#2D3748;mso-font-kerning:0pt;mso-ligatures:
none'><o:p></o:p></span></p>



//Create a new PDF document   PdfDocument document =   PdfDocument();   //Draw text   document.pages.add().graphics.drawString('ftH₂O' ,       PdfTrueTypeFont(File(Arial   Unicode ms.ttf').readAsBytesSync(), 14),       brush:   PdfBrushes.black, bounds: Rect.fromLTWH(10, 10, 300, 50));       //Saves the document   File('Output.pdf').writeAsBytes(await   document.save());       //Disposes the document   document.dispose();
--




<p class=MsoNormal style='margin-bottom:7.0pt;line-height:normal'><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;color:#2D3748;
background:white;mso-font-kerning:0pt;mso-ligatures:none'>Please find the below
documentation for further reference</span><span style='mso-ascii-font-family:
Calibri;mso-fareast-font-family:"Times New Roman";mso-hansi-font-family:Calibri;
mso-bidi-font-family:Calibri;color:#2D3748;mso-font-kerning:0pt;mso-ligatures:
none'><o:p></o:p></span></p>

<p class=MsoNormal style='margin-bottom:7.0pt;line-height:normal'><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;color:#2D3748;
background:white;mso-font-kerning:0pt;mso-ligatures:none'>&nbsp; </span><span
style='mso-ascii-font-family:Calibri;mso-fareast-font-family:"Times New Roman";
mso-hansi-font-family:Calibri;mso-bidi-font-family:Calibri;mso-font-kerning:
0pt;mso-ligatures:none'><a
href="https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-truetype-fonts"><span
style='color:blue;background:white'>https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-truetype-fonts</span></a><o:p></o:p></span></p>


</body>

</html>
