### ISSUE TITLE
flutter-web: upgrade from pdf.js/2.4.456 to latest pdf.js/3.x.xxx

### ISSUE THREAD

**Issue by davidecantini** [syncfusion/flutter-widgets#1460]
I tried to include the latest [pdfjs](https://www.npmjs.com/package/pdfjs-dist) version as follows, i.e.
  
```
  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>
  <script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
```

But when opening a pdf, it crashes with the following error:

`Invalid argument: Invalid array length`

Can you add support to enable the upgrade?

**Comment by deepika134** [comment]
We have created the simple plugin sample with the latest version of PDF.js, excluding SfPdfViewer. However, we are still experiencing an issue where the PDF document bytes are disposed after invoking the platform interface method. As a result, we have raised a query on PDF.js GitHub. We will inform you once we receive a proper solution.

**Comment by ramkumarsync** [comment]
We didn't get any proper updates on the bug report we created earlier. Currently, our PDF Viewer supports Pdf.js version till v2.11.338. Could you please upgrade to this version and let us know whether the issue persists or not?

**Comment by ramkumarsync** [comment]
Since we don't have enough information to proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.
