### ISSUE TITLE
DateTime Axis timezone issue

### ISSUE THREAD

**Issue by dipinsonwani** [syncfusion/flutter-widgets#1461]
While using Line Series in SfCartesianChart, I have added xValueMapper as DateTIme. The issue is I am using UTC time format and I don't want it to be in the local timezone.

Here's my code -
`            LineSeries<Pn, DateTime>(
              color: Colors.black,
              dataSource: pnList,
              xValueMapper: (data, _) =>
                  data.timeFrom,
              yValueMapper: (data, _) => num.parse(data.levelFrom),
              enableTooltip: true,
              markerSettings: const MarkerSettings(isVisible: true),
            ),`
            
I am using UTC format datetime in the whole app, While plotting in the graph it is adding 5:30 hours according to my local timezone which is GMT +05:30,
Do we have an option for having a timezone, or can we have one?

**Comment by sfHariHaraSudhan** [comment]
Hi @dipinsonwani,

We would like to inform you that currently, there is no direct option to render chart using the date time values in UTC format based on the time zone, therefore the x axis labels and data labels will be displayed with the difference of  +5.30 hours in IST format. However, you can achieve the mentioned requirement by formatting the x axis labels and dataLabels in UTC format using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback and [dataLabelMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelMapper.html) property.

Shared the User Guide Documentation link below for your reference regarding the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback.
UG : https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter.

Note : While formatting the date time values in UTC format using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, when we cast the millisecondsEpoch values of the UTC format to the DateTime value, there might be a chance to display the date time with 30 minutes difference and you can handle it by modifying and formatting the data points according to your needs.

Kindly refer the code snippet below : 
```
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late List<ChartSampleData> dateTimeData;

  @override
  void initState() {
    dateTimeData = [
      // Sample data with DateTime in UTC format
      ChartSampleData(DateTime.utc(2023, 10, 13, 08, 30), 50),
      ChartSampleData(DateTime.utc(2023, 10, 13, 09, 30), 30),
      ChartSampleData(DateTime.utc(2023, 10, 13, 10, 30), 70),
      ChartSampleData(DateTime.utc(2023, 10, 13, 11, 30), 20),
      ChartSampleData(DateTime.utc(2023, 10, 13, 12, 30), 40),
      ChartSampleData(DateTime.utc(2023, 10, 13, 13, 30), 60),
      ChartSampleData(DateTime.utc(2023, 10, 13, 14, 30), 90),
      ChartSampleData(DateTime.utc(2023, 10, 13, 15, 30), 80),
      ChartSampleData(DateTime.utc(2023, 10, 13, 16, 30), 10),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: SfCartesianChart(
            primaryXAxis: DateTimeAxis(
              labelIntersectAction: AxisLabelIntersectAction.none,
              edgeLabelPlacement: EdgeLabelPlacement.shift,
              intervalType: DateTimeIntervalType.hours,
              dateFormat: DateFormat.Hm(),
              axisLabelFormatter: (axisLabelRenderArgs) {
                DateTime time = DateTime.fromMillisecondsSinceEpoch(
                  axisLabelRenderArgs.value.toInt(),
                );
                String formattedText = DateFormat('HH:mm').format(
                  time.toUtc(),
                );
                return ChartAxisLabel(
                  formattedText,
                  axisLabelRenderArgs.textStyle,
                );
              },
            ),
            series: <ChartSeries<ChartSampleData, DateTime>>[
              LineSeries<ChartSampleData, DateTime>(
                dataSource: dateTimeData,
                enableTooltip: true,
                color: Colors.black,
                xValueMapper: (ChartSampleData data, int index) =>
                    data.timeFrom,
                yValueMapper: (ChartSampleData data, int index) =>
                    data.levelFrom,
                markerSettings: const MarkerSettings(isVisible: true),
                dataLabelSettings: const DataLabelSettings(isVisible: true),
                dataLabelMapper: (ChartSampleData data, int index) {
                  String formattedText = DateFormat('HH:mm').format(
                    data.timeFrom.toUtc(),
                  );
                  return formattedText;
                },
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class ChartSampleData {
  final DateTime timeFrom;
  final num levelFrom;

  ChartSampleData(
    this.timeFrom,
    this.levelFrom,
  );
}
```
Snapshot :
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/cac72ab5-aede-4cf8-82b6-e46ecfabcbed)

Also attached the sample below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[511424.zip](https://github.com/syncfusion/flutter-widgets/files/12929281/511424.zip)
