### ISSUE TITLE
SfCartesianChart - NumericAxis - desired highlighted y value

### ISSUE THREAD

**Issue by solarosfitness** [syncfusion/flutter-widgets#1464]
I was searching around the documentation and the code itself and didn't find a way to do it.

I have the following chart:
```
SfCartesianChart(
            plotAreaBorderWidth: 0,
            title: ChartTitle(text: 'Data States'),
            primaryXAxis: CategoryAxis(
              majorGridLines: const MajorGridLines(width: 0),
            ),
            primaryYAxis: NumericAxis(
              axisLine: const AxisLine(width: 0),
              labelFormat: '{value}',
              majorTickLines: const MajorTickLines(size: 0)
            ),
            series: _getDefaultColumnSeries(),
            // tooltipBehavior: TooltipBehavior(enable: true, header: '', canShowMarker: false),
)
```

The `_getDefaultColumnSeries` is the same as in the [example](https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/chart_types/column/default_column_chart.dart), and I added the sample values a variable named `goalY`

I want to set a number which is the goal, let's say `goalY`, when it's set to something I want the horizontal line of it will be highlighted, let's say my chart y values are from 0 till 500 and I set the `goalY` to be 400, the horizontal line in the 400 y values will be drawn in a different color for example.

Is it possible? if not, would appreciate it if you'll be able to implement it :)

**Comment by sfHariHaraSudhan** [comment]
Hi @solarosfitness,

We have achieved your mentioned requirement by using the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property to render a line at the specified y value position given in the goalY field. We also used the [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) callback to obtain the [visibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/visibleMinimum.html) and [visibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CategoryAxis/visibleMaximum.html) of the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html), the [onRendererCreated](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onRendererCreated.html) callback to initialize the controller, and the [pointToPixel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html) method to convert the data point values to the pixel values.

Shared the User Guide Documentation links below regarding the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html), [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) and [onRendererCreated](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onRendererCreated.html) features for your reference.

Annotations : https://help.syncfusion.com/flutter/cartesian-charts/annotations.
On Actual Range Changed : https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onactualrangechanged.
On Renderer Created : https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onrenderercreated.

Kindly refer the code snippet below :
```
class ColumnDefault extends StatefulWidget {
  const ColumnDefault({super.key});
 
  @override
  State<ColumnDefault> createState() => _ColumnDefaultState();
}
 
class _ColumnDefaultState extends State<ColumnDefault> {
  _ColumnDefaultState();
 
  TooltipBehavior? _tooltipBehavior;
  double? goalY = 300;
  double? visibleMin;
  double? visibleMax;
  ValueNotifier<int> count = ValueNotifier(0);
  late ChartSeriesController _chartSeriesController;
 
  @override
  void initState() {
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      header: '',
      canShowMarker: false,
    );
    super.initState();
  }
 
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        onActualRangeChanged: (rangeChangedArgs) {
          if (rangeChangedArgs.orientation == AxisOrientation.horizontal) {
            visibleMin = rangeChangedArgs.visibleMin;
            visibleMax = rangeChangedArgs.visibleMax;
            count.value++;
          }
        },
        primaryXAxis: CategoryAxis(),
        primaryYAxis: NumericAxis(
          interval: 100,
        ),
        series: _getDefaultColumnSeries(),
        tooltipBehavior: _tooltipBehavior,
        annotations: [
          CartesianChartAnnotation(
            y: 0,
            coordinateUnit: CoordinateUnit.logicalPixel,
            widget: ValueListenableBuilder(
              valueListenable: count,
              builder: (context, value, child) {
                if (visibleMin != null && visibleMax != null) {
                  CartesianChartPoint firstPoint =
                      CartesianChartPoint(visibleMin, goalY);
                  final Offset firstPosition =
                      _chartSeriesController.pointToPixel(firstPoint);
                  CartesianChartPoint secondPoint =
                      CartesianChartPoint(visibleMax, goalY);
                  final Offset secondPosition =
                      _chartSeriesController.pointToPixel(secondPoint);
                  return CustomPaint(
                    painter: LinePainter(
                      firstPosition: firstPosition,
                      secondPosition: secondPosition,
                    ),
                  );
                } else {
                  return Container();
                }
              },
            ),
          ),
        ],
      ),
    );
  }
 
  /// Get default column series
  List<CartesianSeries<ChartSampleData, String>> _getDefaultColumnSeries() {
    return <CartesianSeries<ChartSampleData, String>>[
      ColumnSeries<ChartSampleData, String>(
        dataSource: <ChartSampleData>[
          ChartSampleData(x: 'China', y: 100),
          ChartSampleData(x: 'Brazil', y: 200),
          ChartSampleData(x: 'Bolivia', y: 300),
          ChartSampleData(x: 'Mexico', y: 400),
          ChartSampleData(x: 'Egypt', y: 500),
          ChartSampleData(x: 'Mongolia', y: 600),
        ],
        xValueMapper: (ChartSampleData sales, _) => sales.x,
        yValueMapper: (ChartSampleData sales, _) => sales.y,
        onRendererCreated: (controller) {
          _chartSeriesController = controller;
        },
        dataLabelSettings: const DataLabelSettings(
          isVisible: true,
          textStyle: TextStyle(fontSize: 10),
        ),
      ),
    ];
  }
}
 
class LinePainter extends CustomPainter {
  final Offset firstPosition;
  final Offset secondPosition;
 
  LinePainter({
    required this.firstPosition,
    required this.secondPosition,
  });
 
  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawLine(
      firstPosition,
      secondPosition,
      Paint()
        ..color = Colors.red
        ..strokeWidth = 2,
    );
  }
 
  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) {
    return true;
  }
}
 
class ChartSampleData {
  final String x;
  final num? y;
 
  ChartSampleData({
    required this.x,
    required this.y,
  });
}
```
Snapshot :
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/dedbbc94-eb94-4049-81e2-657ae97559df)

Also attached the sample below for your reference and you can modify the sample according to your needs. If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
[512004.zip](https://github.com/syncfusion/flutter-widgets/files/12927704/512004.zip)
