### ISSUE TITLE
Do I need a license to use the syncfusion_flutter_charts library in my Flutter project?

### ISSUE THREAD

**Issue by hongseongyeon** [syncfusion/flutter-widgets#1471]
The License key registration is no longer required for Flutter from version 18.3.0.x. So, there is no need to generate or register Syncfusion Flutter license keys in your Flutter projects.

I found the word on the site. Nevertheless, does Flutter project require a license to use syncfusion_flutter_charts library and deploy apps?

**Comment by sfHariHaraSudhan** [comment]
Hi @hongseongyeon,

Yes, you need to have either a commercial license or a community license to use the Syncfusion Flutter widgets in your Flutter application. However, if you are using the Syncfusion Flutter Widgets with version 18.3.0.x or later, there is no need to register or add the Syncfusion Flutter license keys anywhere in your Flutter project. The Flutter widgets from Syncfusion from version 18.3.0.x or later can be used without registering or adding the license keys in your Flutter application.

**Note :** If you are using version 18.3.0.x or lower, please follow the link below to register the license key in your Flutter application.

How to register license key (18.3.0.x or lower): https://help.syncfusion.com/flutter/licensing/overview#how-to-register-in-an-application.

You can refer the Syncfusion licensing terms and conditions from the below links.

https://github.com/syncfusion/flutter-examples/blob/master/LICENSE
https://help.syncfusion.com/flutter/licensing/overview

And you can get more details about our community license from the below link.
https://www.syncfusion.com/products/communitylicense

If you have further queries, please get back to us.

Regards,
Hari Hara Sudhan. K.
