### ISSUE TITLE
Target of URI doesn't exist: 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart'.

### ISSUE THREAD

**Issue by yendrapriambada** [syncfusion/flutter-widgets#1473]
There is an error like this:
Target of URI doesn't exist: 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart'.

whereas i have done put the library in pubspec.yaml

<img width="1440" alt="Screen Shot 2023-10-19 at 22 57 44" src="https://github.com/syncfusion/flutter-widgets/assets/73283816/9532c88d-be9c-44bb-aa68-03cd2ca4aa07">

How to solve this? Thanks.

**Comment by abhinavsinghring** [comment]
Clicking on pub get should solve this.
If not try `flutter clean` then `flutter pub get`.

**Comment by techdmacq** [comment]
the issue still persisiting

**Comment by ramkumarsync** [comment]
Since we don't have enough information to proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.
