### ISSUE TITLE
tooltip width calculation with rectangular shape

### ISSUE THREAD

**Issue by yvs2014** [syncfusion/flutter-widgets#1475]
Hello, 
there's a certain inconvenience with tooltips displaying at some ratios parent and text sizes. Take a look at attached screenshots below, the longer text ("+space") doesn't fit there, whereas the shorter one ("space") does.
It was just expected that a longer text would've had a wider box (or at least the same width as a shorter text).

| tooltip "+space"| tooltip "space" |
| --- | --- |
|![plus_space](https://github.com/syncfusion/flutter-widgets/assets/7794636/6dd188d3-6c19-4683-9c07-ac00a30f1d15)|![space](https://github.com/syncfusion/flutter-widgets/assets/7794636/3fd48ed0-f157-4248-a2f3-03af475f3ee0)|

These sliders were created with
```
SizedBox(width: 80, child: SfSlider(
  min: 0, max: 2, interval: 1,
  enableTooltip: true,
  tooltipShape: const SfRectangularTooltipShape(),
  tooltipTextFormatterCallback: (_, String fmt) =>
     switch (fmt) { '0' => 'off', '1' => 'on', '2' => '+space', _ => fmt },
//     switch (fmt) { '0' => 'off', '1' => 'on', '2' => 'space', _ => fmt },
....
```

**Comment by sfHariHaraSudhan** [comment]
Hi @yvs2014,

We are able to replicate the reported issue regarding **Tooltip is not rendering based on its tooltip text width when the tooltip size is greater than its widget** at our end and have logged bug report for it in our feedback portal. We will fix and include the changes after our SP release which is expected to be rolled out on the end of November 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug with the feedback below.

Feedback Link : https://www.syncfusion.com/feedback/48050.

Regards,
Hari Hara Sudhan. K.

**Comment by LokeshPalani** [comment]
Hi,



The reported issue regarding Tooltip is not rendering based on its tooltip text width when the tooltip size is greater than its widget has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_sliders package to the latest version below to avoid this issue.



Version:  https://pub.dev/packages/syncfusion_flutter_sliders/versions/23.2.5



Regards,
Lokesh P.

**Comment by yvs2014** [comment]
Okay, it's for future times maybe, I don't use it so far to check out, just wanted to help with widget improving. Kind Regards
