### ISSUE TITLE
How to change the word "today" into other languages

### ISSUE THREAD

**Issue by niu-dali** [syncfusion/flutter-widgets#1477]
Hello, I need to translate the word "todayLabel" into other languages, such as "今天". Could you tell me how to do that? Thank you.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need ay further assistance on this.

**Comment by QuentinSc** [comment]
> Hi @niu-dali,
> 
> We have user guide documentation and an online sample demo to achieve your requirement, for translating text from one language to another. You can refer to the links below for your reference and achieve your requirements.
> 
> UG, https://help.syncfusion.com/flutter/daterangepicker/localization
> 
> Online sample link, https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/date_picker/localization.dart
> 
> Regards,
> 
> Preethika Selvam.

Hello,
I'm sorry but it does not seem to show how to translate the today button text
