### ISSUE TITLE
Can i use annotations? But it don't work

### ISSUE THREAD

**Issue by FeofanGreek** [syncfusion/flutter-widgets#1478]
Good day!
I use your plugin to display PDF documents, but it does not support displaying annotations
Conducted my research and came to the conclusion that:
for iOS you use CGPDFDocument for access via channels, but it does not support annotation, unlike PDFKit
for Android you use PdfFileRenderer, which also cannot display annotations
The situation with MacOS and Windows is the same
Unfortunately your plugin does not support Linux.

However, the plugin declares the display of annotations: enableDocumentLinkAnnotation: true

Is it possible to correct the situation?

**Comment by FeofanGreek** [comment]
Up please

**Comment by deepika134** [comment]
Hi @FeofanGreek ,

At present we do not have support for shape annotation in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the following feedback link for track the status of the feature,

https://www.syncfusion.com/feedback/26332/support-for-shape-annotations 

However, we have a workaround to preserve the existing annotation in SfPdfViewer. Kindly refer to the following link to know more about the details.

[How to preserve the existing annotation in Flutter PDF Viewer (SfPdfViewer)? | Syncfusion](https://support.syncfusion.com/kb/article/11466/how-to-preserve-the-existing-annotation-in-flutter-pdf-viewer-sfpdfviewer)
