### ISSUE TITLE
[syncfusion_flutter_pdf_viewer] Feature Request: Size customisation of ScrollHead

### ISSUE THREAD

**Issue by abhinavsinghring** [syncfusion/flutter-widgets#1479]
Default ScrollHead size of Pdf Viewer is little small and doesn't detect gesture in one time. You have to carefully touch, hold and scroll.

**Comment by deepika134** [comment]
The scroll head size is being displayed correctly on our side, and we have not encountered any challenges with the responsiveness of tap and scroll gestures. Everything is working smoothly from our end. Could you kindly let us know the platform on which you are experiencing the issue and share a video of the issue you are facing. This information will be helpful for us to provide a prompt solution as soon as possible.

**Comment by abhinavsinghring** [comment]
I'm not saying it's an issue for everyone. But for me using in 2 devices I feel sometimes when I try to hold Scroll Head but end up scrolling pdf page instead. 
So I'm asking if you can add option to set size of ScrollHead like 1 as default, 2 little bigger, 3 little more bigger and stops at certain size let's say 5.

Also if you can look into #1466

**Comment by deepika134** [comment]
Kindly share the replicating video for this query I feel sometimes when I try to hold Scroll Head but end up scrolling pdf page instead. This will be helpful for us to provide the prompt solution at earliest.

**Comment by abhinavsinghring** [comment]
I can't create a video of my experience.
If you are in emulator holding scroll head with mouse it won't feel small but in normal usage in physical device I miss gesture 5 out of 10 times. I'm explaining a simple thing and requesting for a feature to change size of scroll head upto some extent.

I'm adding picture to compare scrollhead of other app from playstore

![WhatsApp Image 2023-11-08 at 02 25 55_36d56c5a](https://github.com/syncfusion/flutter-widgets/assets/83336285/0ce4a5a1-7192-4f50-9d8d-8129f30392fc)

![WhatsApp Image 2023-11-08 at 02 25 56_24e6504e](https://github.com/syncfusion/flutter-widgets/assets/83336285/b66a748e-f4d2-4257-97d3-732882f627e1)

And here is the video of pdf viewer rendering, if it is possible why you can't have this in your plugin. Also this app use less ram while rendering whole pdf at once than my app with SfPdfViewer.

https://github.com/syncfusion/flutter-widgets/assets/83336285/a1fd9144-b063-4a8a-9039-67572ef31ca6

**Comment by deepika134** [comment]
We have considered your request to increase the size of the scroll head on mobile platforms. This feature enhancement will be included in our 2023 November 28th weekly release. Kindly use the below link for track the status of the feature ,
https://www.syncfusion.com/feedback/48485/need-to-increase-the-size-of-the-scroll-head-on-the-mobile-platforms

**Comment by abhinavsinghring** [comment]
Thank you for accepting this feature.

**Comment by deepika134** [comment]
We have improved the user experience of the scroll head in SfPdfViewer by increasing its size. This enhancement is available in our latest weekly release. Please find the package link below.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/23.2.5 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
