### ISSUE TITLE
SfDateRangePicker : Allow selection of Dates when view Mode is DateRangePickerView.year

### ISSUE THREAD

**Issue by akdu12** [syncfusion/flutter-widgets#148]
Hello
I need to allow user to select Date range when view Mode is DateRangePickerView.year. currently when you select a month it will automatically change to DateRangePickerView.month. 

is it possible to select range when using DateRangePickerView.year?

Thank you.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: is it possible to select range when using DateRangePickerView.year?**

Yes, it is possible to select the date ranges in the year view by using the allowViewNavigation property value as false. We have prepared a simple sample for the same. Please find the sample and video from the following link.

**Sample and video link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_visibledates_calendar-1357084001.zip

**Screenshot:**

![vidma_recorder_10032021_124043](https://user-images.githubusercontent.com/54974849/110593038-0e072880-81a1-11eb-98ad-64c7ab885b17.jpg)


**Code snippet:**

```
    body: SafeArea(
        child: Card(
  margin: const EdgeInsets.fromLTRB(50, 150, 50, 150),
  child: SfDateRangePicker(
    view: DateRangePickerView.year,
    allowViewNavigation: false,
    selectionMode: DateRangePickerSelectionMode.range,
  ),
))),
```

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by akdu12** [comment]
@Indumathi1195R I missed that property,
 thank you
