### ISSUE TITLE
Ability to change each border of a cell individually - Calendar

### ISSUE THREAD

**Issue by Anish-Chanda** [syncfusion/flutter-widgets#1483]
This way, it would be possible to customize the calendar even more. For example, we could achieve designs where the color/opacity of the color is different on vertical and horizontal lines for a better UX.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Anish-Chanda,

Currently, there is no direct support for setting the border color for each cell in the month view. However, you can customize each cell with the help of the monthCellBuilder callback. We have UG documentation for this and shared it below for your reference. 

UG, https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder

Regards,
Yuvaraj.
