### ISSUE TITLE
[syncfusion_flutter_datagrid] load more builder fires multiple times on mac os

### ISSUE THREAD

**Issue by mades5** [syncfusion/flutter-widgets#1485]
I downloaded this sample to try the load more functionality on DataGrid. (https://github.com/syncfusion/flutter-widgets/files/12430541/sample.zip)
On MacOS Ventura 13.6 the load more builder get called multiple times after reaching the end of the table. On Chrome everything is fine, it's just called one time.

Version:
syncfusion_flutter_datagrid: ^23.1.42

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @mades5,

We have investigated this matter on our end and encountered the same issue you described on the MacOS platform. It seems to be a platform-specific issue, as it is functioning correctly on Chrome, Android, and Windows platforms. Additionally, the loadmore event is handled from the sample level through the loadMoreViewBuilder.

However, you can resolve this issue directly from the sample level by maintaining a Boolean flag to load more rows. Here is an example code snippet to illustrate this approach:

<details>
<summary>Code Snippet</summary>

```dart
loadMoreViewBuilder: (BuildContext context, LoadMoreRows loadMoreRows) {
          Future<String> loadRows() async {
            // Set the canLoadMoreRows to true when the rows are loading.
            _employeeDataSource.canLoadMoreRows = true;

            await loadMoreRows();

            // Reset the canLoadMoreRows to false when the rows are loaded.
            _employeeDataSource.canLoadMoreRows = false;
            return Future<String>.value('loading');
          }

          return FutureBuilder<String>(
            initialData: 'loading',
            future: loadRows(),
            builder: (context, snapShot) {
              if (snapShot.data == 'loading') {
                return Container(
                    height: 60.0,
                    width: double.infinity,
                    alignment: Alignment.center,
                    child: const CircularProgressIndicator());
              } else {
                return SizedBox.fromSize(size: Size.zero);
              }
            },
          );
        },

In DataGridSource:

class EmployeeDataSource extends DataGridSource {

  bool canLoadMoreRows = false;
…
  @override
  Future<void> handleLoadMoreRows() async {
    await Future.delayed(const Duration(seconds: 5));

    if (canLoadMoreRows) {
      _addMoreRows(10);
      notifyListeners();
    }
  }
…
}

```
</details>

### Sample Link: [Flutter-DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/14222334/Sample.zip)


Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @mades5,

We suspect that the reported issue has been resolved at your end with the provided workaround. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
