### ISSUE TITLE
How to drag and drop the rows in DataGrid

### ISSUE THREAD

**Issue by maytineej** [syncfusion/flutter-widgets#1488]

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @maytineej,

As of now, Flutter SfDataGrid does not have support for row drag and drop feature. We have already considered your request as a feature. We may implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience and understanding until then. 

**Feedback Link: https://www.syncfusion.com/feedback/22292/support-to-drag-and-drop-the-rows** 

Regards, 
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @maytineej,

We are closing this issue as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Ashok K
