### ISSUE TITLE
Automatic word highlighting

### ISSUE THREAD

**Issue by julius-stuemmler** [syncfusion/flutter-widgets#1489]
Hey!
I'm searching for a possibility to highlight specific words or short text passages in the pdf.

As input I'm using a list of strings. Then we need to search for all these strings and if we found them (also if it's in multiple rows), I want to highlight them automatic. I don't need a dialog for highlighting them and the changes don't need to be saved.

Does anyone have an idea or solution for this?

**Comment by julius-stuemmler** [comment]
Has anyone any idea for this?

**Comment by irfanajaffer** [comment]
<html>
<body>
<span><span class="ui-provider a b c d e f g h i j k l m n o p q r s t u v w x y z ab ac ae af ag ah ai aj ak" dir="ltr"><p style="margin-bottom: 8px;">As of now, we do have support to find text that's spread across multiple rows in a layout. We do not have any immediate plans to implement this feature.</p><p style="margin-bottom: 8px;">But we can use FindText to search a list of strings that is spread across in a single row and use watermark or Text markup annotation to highlight the text.</p><p style="margin-bottom: 8px;">Kindly use the following code snippet for reference,</p>

```
//Loads an existing PDF document

 PdfDocument document =

     PdfDocument(inputBytes: File('input.pdf').readAsBytesSync());

 

 //Find the text and get matched items

 List<MatchedItem> textCollection =

      PdfTextExtractor(document).findText(['text1', 'text2']);

 

 for (int i = 0; i < textCollection.length; i++) {

   //Get the matched item

   MatchedItem item = textCollection[i];

 

   //Get the page number of the matched item

   int pageIndex = item.pageIndex;

 

   //Get the bounds of the matched item

   Rect bounds = item.bounds;

 

   //Get the page by page index.

   PdfPage page = document.pages[pageIndex];

   PdfGraphicsState state = page.graphics.save();

 

   //Set transparency

   page.graphics.setTransparency(0.75, mode: PdfBlendMode.color);

 

   //Draw rectangle around the matched item

   page.graphics.drawRectangle(

       bounds: bounds, brush: PdfSolidBrush(PdfColor(255, 241, 118)));

 

   //Restore graphics state

   page.graphics.restore(state);

 }

 //Save the document

 File('Output.pdf').writeAsBytesSync(await document.save());

 

 //Dispose the document

 document.dispose();
```
<p style="margin-bottom: 8px;">Kindly use the following UG documentations for reference,</p><p style="margin-bottom: 8px;"><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-text-extraction#working-with-find-text" href="https://help.syncfusion.com/flutter/pdf/working-with-text-extraction#working-with-find-text" rel="noreferrer noopener" target="_blank" class="fui-Link ___1rxvrpe f2hkw1w f3rmtva f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f1cmlufx f9n3di6 f1ids18y f1tx3yz7 f1deo86v f1eh06m1 f1iescvh fhgqx19 f1olyrje f1p93eir f1nev41a f1h8hb77 f1lqvz6u f10aw75t fsle3fq f17ae5zn" title="https://help.syncfusion.com/flutter/pdf/working-with-text-extraction#working-with-find-text">https://help.syncfusion.com/flutter/pdf/working-with-text-extraction#working-with-find-text</a><br><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-watermarks" href="https://help.syncfusion.com/flutter/pdf/working-with-watermarks" rel="noreferrer noopener" target="_blank" class="fui-Link ___1rxvrpe f2hkw1w f3rmtva f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f1cmlufx f9n3di6 f1ids18y f1tx3yz7 f1deo86v f1eh06m1 f1iescvh fhgqx19 f1olyrje f1p93eir f1nev41a f1h8hb77 f1lqvz6u f10aw75t fsle3fq f17ae5zn" title="https://help.syncfusion.com/flutter/pdf/working-with-watermarks">https://help.syncfusion.com/flutter/pdf/working-with-watermarks</a><br><a aria-label="Link https://help.syncfusion.com/flutter/pdf/working-with-annotations#text-markup-annotation" href="https://help.syncfusion.com/flutter/pdf/working-with-annotations#text-markup-annotation" rel="noreferrer noopener" target="_blank" class="fui-Link ___1rxvrpe f2hkw1w f3rmtva f1ewtqcl fyind8e f1k6fduh f1w7gpdv fk6fouc fjoy568 figsok6 f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1g0x7ka fhxju0i f1qch9an f1cnd47f fqv5qza f1vmzxwi f1o700av f13mvf36 f1cmlufx f9n3di6 f1ids18y f1tx3yz7 f1deo86v f1eh06m1 f1iescvh fhgqx19 f1olyrje f1p93eir f1nev41a f1h8hb77 f1lqvz6u f10aw75t fsle3fq f17ae5zn" title="https://help.syncfusion.com/flutter/pdf/working-with-annotations#text-markup-annotation">https://help.syncfusion.com/flutter/pdf/working-with-annotations#text-markup-annotation</a></p></span></span>
</body>
</html>
