### ISSUE TITLE
[syncfusion_flutter_datagrid 18.4.47-beta] Checkboxes glitching in widget cell while scrolling

### ISSUE THREAD

**Issue by szymonmazanik** [syncfusion/flutter-widgets#149]
Hello
I have a problem with using chceckbox within widget cell. As you can see on the attached video the selected rows are kind of glitching with the unselected ones when I try to scroll the gird.

My code is quite simple:

        SfDataGrid( 
                  rowHeight: Dimensions.gridCellHeight,
                  columnWidthMode: ColumnWidthMode.header,
                  source: dataSource,
                  frozenColumnsCount:  1,
                  columns: _buildColumns(context),
                  cellBuilder: _buildCell,
                  gridLinesVisibility: GridLinesVisibility.both,
                  headerGridLinesVisibility: GridLinesVisibility.both,
                ),

And the `_buildCell` returns

`Checkbox(value: value, onChanged: onChanged);`

for the first column.

https://user-images.githubusercontent.com/25953768/110546089-55a09c80-812e-11eb-96be-d7513a6c48aa.mov

Is there any solution to this problem?
Thanks for help,
Szymon

**Comment by NeelakandanKannan** [comment]
Hi @szymonmazanik ,

Greetings from Syncfusion.

Our Flutter DataGrid is designed with virtualization architecture. So, the rows will be reused whenever the scrolling is performed. Thats why the CheckBox looks like its state is changed. Its not a rendering or glitching issue.

**Comment by szymonmazanik** [comment]
Hello, 
Thank you for the answer @NeelakandanKannan. 

Is there any advice you can give in order to make it look nicer? 
Or maybe there is a better way to select rows and solve my use case? 

Szymon

**Comment by NeelakandanKannan** [comment]
Hi @szymonmazanik ,

Thanks for the update.

You can avoid the glitching appearance of the CheckBox when scrolling is performed by setting the unique key with the value of RowIndex for CheckBox. You can refer the below code,

```dart
Widget _buildDataGrid() {
    return SfDataGrid(
      source: employeeDataSource,
      cellBuilder: (context, column, index) {
        return Checkbox(
            key: ValueKey(index),
            value: employees[index].widget,
            onChanged: (bool value) {});
      },
      columns: <GridColumn>[
        GridNumericColumn(mappingName: 'id', headerText: 'ID'),
        GridTextColumn(mappingName: 'name', headerText: 'Name'),
        GridTextColumn(mappingName: 'designation', headerText: 'Designation'),
        GridNumericColumn(mappingName: 'salary', headerText: 'Salary'),
        GridWidgetColumn(mappingName: 'widget', headerText: 'Widget')
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter DataGrid'),
        ),
        body: _buildDataGrid());
  }
```

**Comment by szymonmazanik** [comment]
Works perfect, thanks!
