### ISSUE TITLE
LateInitializationError: Field '_zoomLevel@987372349' has not been initialized.

### ISSUE THREAD

**Issue by hridoycse197** [syncfusion/flutter-widgets#1490]
when i zoom out map, it shows this error

**Comment by LokeshPalani** [comment]
Hi,

We would like to inform you that the mentioned late exception would occur when we try to access or use the late variable before initializing its values. Therefore, we suspect that the _zoomLevel variable is used before initializing it. Unfortunately, we are unable to replicate the late exception from our end while trying to zoom out the map. However, as we need some additional information, we recommend you share chart-related code configurations or samples to reproduce the mentioned exception along with the exception call stack and it will be very helpful for us to provide a possible solution from our end.

Regards,
Lokesh Palani.
