### ISSUE TITLE
[syncfusion_flutter_charts] daylight saving time

### ISSUE THREAD

**Issue by komhkomh** [syncfusion/flutter-widgets#1491]
I was wondering if your chart plugin supports Daylight Saving Time (DST)?  BTW, I need to set custom minimum and maximum values on my axis(https://github.com/syncfusion/flutter-widgets/issues/1422#issuecomment-1735483845), so I can't use DateTimeCategoryAxis. Is there a way to display Daylight Saving Time while using DateTimeAxis?

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query on our end. While our Flutter charts partially support Daylight Saving Time, we kindly request more detailed information about your requirements. Please provide exact details and the expected images and explain the issues you are facing. This will help us better assist you and provide a possible solution earlier.



Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
