### ISSUE TITLE
[syncfusion_flutter_calendar] Event not showing if RRULE provided by Google/Apple Calendar is general.

### ISSUE THREAD

**Issue by manylittlestorms** [syncfusion/flutter-widgets#1495]
**Version: 23.1.43**

Hello,
I am building a flutter app that retrieves google calendar events and display them with SfCalendar.
I noticed that some all-day event is raising an exception and **not showed** inside SfCalendar because of its rRule. 

To be more precise, if i create an event on 1st november from Google Calendar to be repeated every month on the first wednesday of the month, Google set its rRule as: `FREQ=MONTHLY;BYDAY=1WE;UNTIL=20231105`.

I debugged the code and found out that this rRule raise an exception because the function `_getMonthlyRecurrenceDateTimeCollection` tries to do the following `int.parse(bySetPosCount);` but bySetPosCount is `''`. `bySetPosCount` doesn't contain any char.

```
    } else if (byDay == 'BYDAY') {
      int tempCount = 0;
      final int nthWeekDay = _getWeekDay(byDayValue) % DateTime.daysPerWeek;
      final int bySetPosValue = int.parse(bySetPosCount);
```
So, the raised exception is the following:
```
E/flutter (11941): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid number (at character 1)
E/flutter (11941): #0      int._handleFormatError (dart:core-patch/integers_patch.dart:124:7)
E/flutter (11941): #1      int.parse (dart:core-patch/integers_patch.dart:50:14)
E/flutter (11941): #2      RecurrenceHelper._getMonthlyRecurrenceDateTimeCollection (package:calendar/src/calendar/appointment_engine/recurrence_helper.dart:803:37)
```

If i create an Event on 1 november 2023 from Google Calendar so that the event is repeated every month the first day of the month, Google gives it the following rRule: `FREQ=MONTHLY;UNTIL=20231105`. This is confusing me, because it contains `UNTIL=20231105`, so the event should never be repeated as it can't go past 5th November. However I should at least see the event on November 1st, but SfCalendar doesn't show it anyway.

I also found out that if i create an Event from Google Calendar and it has the following rRule:
`FREQ=YEARLY` or `FREQ=MONTHLY` the event **IS NOT SHOWED**, because `recDateCollection` is empty. But the event is showed if rRule is `FREQ=DAILY`.

I think we should support this rRules.

**Comment by manylittlestorms** [comment]
I noticed that if the event has the following `RRULE:FREQ=MONTHLY` the following exception is raised. No issue at all and the event is displayed with `RRULE:FREQ:WEEKLY`. I suppose there is a bug with all-day event and monthly/yearly repetition.

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following FormatException was thrown building:
Invalid number (at character 1)

^

When the exception was thrown, this was the stack:
#0      int._handleFormatError (dart:core-patch/integers_patch.dart:124:7)
#1      int.parse (dart:core-patch/integers_patch.dart:50:14)
#2      RecurrenceHelper._getMonthlyRecurrenceDateTimeCollection (package:syncfusion_flutter_calendar/src/calendar/appointment_engine/recurrence_helper.dart:744:37)
#3      RecurrenceHelper.getRecurrenceDateTimeCollection (package:syncfusion_flutter_calendar/src/calendar/appointment_engine/recurrence_helper.dart:1077:14)
#4      AppointmentHelper._getRecurrenceAppointments (package:syncfusion_flutter_calendar/src/calendar/appointment_engine/appointment_helper.dart:1395:26)
#5      AppointmentHelper.getVisibleAppointments (package:syncfusion_flutter_calendar/src/calendar/appointment_engine/appointment_helper.dart:998:9)
#6      _SfCalendarState._getItem (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:5689:27)
#7      _SfCalendarState.addAgenda.<anonymous closure> (package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart:7151:32)
#8      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490:22)
#9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828:28)
#10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842:55)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719:19)
#12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834:12)
#13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351:23)
#14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2604:59)
#15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1059:15)
#16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2604:14)
#17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340:5)
#18     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426:5)
#19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#21     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#22     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1512:12)
#23     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1421:20)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#25     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#28     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#31     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#37     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#40     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#43     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#46     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#48     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:554:11)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#57     RenderStack.layoutPositionedChild (package:flutter/src/rendering/stack.dart:511:11)
#58     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:620:30)
#59     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#60     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:2493:7)
#63     RenderBox.layout (package:flutter/src/rendering/box.dart:2382:11)
#64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#65     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2332:7)
#66     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1013:18)
#67     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:494:19)
#68     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:918:13)
#69     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
#70     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#71     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
#72     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
#73     _invoke (dart:ui/hooks.dart:170:13)
#74     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#75     _drawFrame (dart:ui/hooks.dart:140:31)
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by IndumathiR-1995** [comment]
Hi,

As per the current implementation of the calendar, the events doesn't shown if the recurrence rule using FREQ property for YEARLY and MONTHLY recurrence events. Please find the following details for creating Monthly and Yearly recurrence appointment.

1.	For MONTHLY recurrence event - We need to set the BYMONTHDAY property for MONTHLY recurrence events. For example, when you create a Monthly recurrence appointment in the date 3, it means the BYMONTHDAY holds the value 3 and creates the appointment on 3rd day of every month.
2.	For YEARLY recurrence event - We need to set the BYMONTHDAY and BYMONTH properties. For example, when you create the yearly appointment in the Month June, it means the index value for June month is 6 and it is stored in the BYMONTH field. The appointment is created on every 6th month of a year.

Also, we have a KB documentation for creating recurrence appointment. Please find the KB from the following link.

**KB link:**
https://help.syncfusion.com/flutter/calendar/appointments#recurrence-appointment 

We hope that this helps you. If your requirement is to show the events for all days means, we suggest using the DAILY recurrence rule. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by manylittlestorms** [comment]
> Hi,
> 
> 
> 
> As per the current implementation of the calendar, the events doesn't shown if the recurrence rule using FREQ property for YEARLY and MONTHLY recurrence events. Please find the following details for creating Monthly and Yearly recurrence appointment.
> 
> 
> 
> 1.	For MONTHLY recurrence event - We need to set the BYMONTHDAY property for MONTHLY recurrence events. For example, when you create a Monthly recurrence appointment in the date 3, it means the BYMONTHDAY holds the value 3 and creates the appointment on 3rd day of every month.
> 
> 2.	For YEARLY recurrence event - We need to set the BYMONTHDAY and BYMONTH properties. For example, when you create the yearly appointment in the Month June, it means the index value for June month is 6 and it is stored in the BYMONTH field. The appointment is created on every 6th month of a year.
> 
> 
> 
> Also, we have a KB documentation for creating recurrence appointment. Please find the KB from the following link.
> 
> 
> 
> **KB link:**
> 
> https://help.syncfusion.com/flutter/calendar/appointments#recurrence-appointment 
> 
> 
> 
> We hope that this helps you. If your requirement is to show the events for all days means, we suggest using the DAILY recurrence rule. Please let us know if you need further assistance.
> 
> 
> 
> Regards,
> 
> Indumathi R
> 
> 

Hello,
The problem is that Google isn't providing a RRULE with BYMONTHDAY field when creating a monthly event. The RRULE provided is just "FREQ:MONTHLY". Also, Google isn't providing BYMONTHDAY and BYMONTH fields when creating a yearly event, they just provide the RRULE: "FREQ:YEARLY".

Could be possible to implement in the code a feature that completes the RRULE?
