### ISSUE TITLE
Syncfusion flutter charts: Funnel chart sections are inversed order of label

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-widgets#1496]
The order of the items on the legend do not match the order of the funnel. This is even the case in your example picture in the docs

<img width="782" alt="Screenshot 2023-11-02 at 11 11 46" src="https://github.com/syncfusion/flutter-widgets/assets/37046316/868d8f85-964e-4eb5-99ec-e01ca4a4b40e">

**Comment by LokeshPalani** [comment]
Hi,


Currently, we do not have support for “legend reordering” in the SfFunnelChart. We have already logged a feature request for it in our feedback portal.


We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.


FR Link,
https://www.syncfusion.com/feedback/28350/ability-to-re-order-the-elements-of-a-legend



Regards,
Lokesh Palani.
