### ISSUE TITLE
How add target Line on Bar Graph

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#150]
Hello team,
Could you please tell me how add target line bar graph? i have marked target Line please tell me functionality if you have done.
<img width="766" alt="Screen Shot 2021-03-11 at 7 05 31 PM" src="https://user-images.githubusercontent.com/65191117/110799338-e1d0d200-829c-11eb-924d-2e11a35aeca9.png">

**Comment by Dharanipalani** [comment]
Hi @waqaryounusjatt788,

Thanks for the interest in our Flutter charts. We have analyzed your query and we attached the sample and screenshot with this, please make use of it. We have achieved your requirement by using the extendability feature available in our charts. Creating the **CustomColumnSeriesRenderer** which extends from the **ColumnSeriesRenderer** which allows us to override the marker, data label, etc. Using this we had drawn the lines on the column and you can use it as per your scenario. 

Sample: [g-150-line_on_column.zip](https://github.com/syncfusion/flutter-widgets/files/6127737/g-150-line_on_column.zip)

Screenshot:  
![image](https://user-images.githubusercontent.com/19763272/110895281-6f550600-831f-11eb-84fc-b7b59e37b7cf.png)

Please revert us if you need further assistance.

Thanks,
Dharanitharan. P

**Comment by waqaryounusjatt788** [comment]
Hi,


if (animationFactor >= 1) {
  for (int i = 0; i < data.length; i++) {
    canvas.drawLine(Offset(segmentRect.left, segmentRect.top + 20),
        Offset(segmentRect.right, segmentRect.top + 20), line1);
    canvas.drawLine(Offset(segmentRect.left, segmentRect.top),
        Offset(segmentRect.right, segmentRect.top), line2);
    canvas.drawLine(Offset(segmentRect.left, segmentRect.bottom - 20),
        Offset(segmentRect.right, segmentRect.bottom - 20), line3);
  }
}


according to your logic you are just showing only lines on different
height but i want actual data line target which we get from data[]
array. How we can do that

**Comment by Dharanipalani** [comment]
Hi @waqaryounusjatt788,

The proposed workaround will work for each data point from the data array since for each data point a bar renders. We have done this like a sample work and you can draw the lines based on your requirement. Please revert us if you have any further queries.

Thanks,
Dharanitharan. P

**Comment by waqaryounusjatt788** [comment]
Hi,
actually i just only draw horizontal target line i don't want it's bar
renderer, array of data just on draw its line not bar because i am using
your StackedColumnSeries class so i have already three stacks and i want to
set one target of three stacks.

**Comment by waqaryounusjatt788** [comment]
Hi, you have done very well, but according to my requirement it was not meet, my requirement is StackedColumnSeries,
i have three array make Stacked Bar and fourth one to display its target and i want to set these array  target, samle picture i will show you for more clarity.  in your sample you showing bar along with draw line but in my case its different scenerio
<img width="224" alt="Screen Shot 2021-03-15 at 3 50 32 PM" src="https://user-images.githubusercontent.com/65191117/111142629-b6a0f800-85a6-11eb-9fb1-00ae2625d90e.png">

**Comment by Dharanipalani** [comment]
Hi @waqaryounusjatt788,

We wish you to say that there are two ways to achieve your requirement. The first one is like using the extendability feature from the previous sample and the other way is to achieve using the **annotations** property in the chart. Using the annotation you can place any widget in the required place in the chart. Now, we attached the sample by placing the image widget in the stacked column series and you can replace any widget as per your wish and you can achieve your requirement.

To know, more about annotations, please refer to the following help document,
[https://help.syncfusion.com/flutter/cartesian-charts/annotations](https://help.syncfusion.com/flutter/cartesian-charts/annotations)

Sample:  [g-150-line_using_annotation.zip](https://github.com/syncfusion/flutter-widgets/files/6159418/g-150-line_using_annotation.zip)

Please revert us if you need further assistance.

Thanks,
Dharanitharan. P

**Comment by waqaryounusjatt788** [comment]
Thank you so much, Annotation working for me.
