### ISSUE TITLE
error  A constant constructor can't call a non-constant super constructor.

### ISSUE THREAD

**Issue by wesleyxiao** [syncfusion/flutter-widgets#1501]
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-22.2.12/lib/src/date_picker/date_picker.dart:7662:8: Error: A constant constructor can't call a non-constant super constructor.

**Comment by LavanyaGowtham2021** [comment]
We have resolved the issue already and so we kindly request you to upgrade the latest version 24.2.5 to resolve this issue.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need ay further assistance on this.
