### ISSUE TITLE
[syncfusion_flutter_charts] add line extends the dots ignore the empty value

### ISSUE THREAD

**Issue by lamlengend98** [syncfusion/flutter-widgets#1502]
I have a array of month and value. For example, March and July have data and April, May, June doesn't have. In graph, I want the April, May, June have no dot and the line extends from March to July

Screenshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/37770203/646a5621-0b78-49e5-acf6-4a7477681b53)

**Comment by LokeshPalani** [comment]
Hi,

You can achieve your requirement by using [emptyPointMode.drop](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/EmptyPointMode.html#drop) in the [emptyPointSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/emptyPointSettings.html) property. By using this, you can display the line from March to July as it will drop the null value. Therefore, you can extend the line from March to July. We have provided a code snippet, screenshot, and sample for your reference.

Code snippet:

```
   series: <CartesianSeries<ChartSampleData, DateTime>>[
LineSeries<ChartSampleData, DateTime>(
dataSource: chartData,
xValueMapper: (ChartSampleData sales, _) => sales.x,
yValueMapper: (ChartSampleData sales, _) => sales.y,
emptyPointSettings: EmptyPointSettings(
mode: EmptyPointMode.drop,
                ),
dataLabelSettings: const DataLabelSettings(
isVisible: true,
                ),
              ),
            ],
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/b14f2e63-1dc1-4095-a7b4-a2f713baea8b)

Regards,
Lokesh Palani.


[chart_185350.zip](https://github.com/syncfusion/flutter-widgets/files/13308626/chart_185350.zip)
