### ISSUE TITLE
[syncfusion_flutter_datagrid] After selecting multiple rows, when I deselect them one by one, the row's style appears abnormal.

### ISSUE THREAD

**Issue by hardgit** [syncfusion/flutter-widgets#1509]
Hey! 
When I click a single row to 'select' or 'deselect,' the display is fine. However, when I choose multiple rows and then deselect them one by one, the row's selection style doesn't fully cancel.
Also, can the selection style be customized?

video：

https://github.com/syncfusion/flutter-widgets/assets/31436497/2240d42f-653e-4452-b705-bc8aaea062b9

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @hardgit,

As per the standard behavior of the DataGrid, when multiple rows are selected and deselected individually, the style of the current row should remain visible in the view. This functionality is designed to facilitate navigation between rows using keys.

Upon testing this behavior on our end, we observed that selecting and deselecting a single row resulted in the removal of the current row highlight, which ideally should not occur. The current row should persist when deselecting a single row, ensuring continuous visibility and navigation.

We have considered this as a bug and logged a bug report in our feedback portal. We will fix the reported issue and include the changes in our weekly patch release, which is expected to be rolled out on December 12, 2023. We appreciate your patience and understanding in the meantime. 

> Also, can the selection style be customized?

Please check the details in the following UG documentation for customizing the appearance of the selected rows.

**UG Link: https://help.syncfusion.com/flutter/datagrid/selection#appearance**

Regards,
Tamilarasan

**Comment by hardgit** [comment]
Hi@Tamilarasan-Paranthaman 
Is it possible to provide an option to disable this highlighting behavior if desired?

**Comment by Tamilarasan-Paranthaman** [comment]
@hardgit, 

To hide the visibility of the current row border in the view, you can utilize the **DataGridCurrentCellStyle.borderColor** property within the **[SfDataGridThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData-class.html)** class. By setting the **borderColor** to **Colors.transparent**, you can effectively remove the appearance of the current row border. For a more detailed explanation and implementation, please refer to the provided code snippet and sample.

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

…

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: SfDataGridTheme(
        data: SfDataGridThemeData(
            currentCellStyle: const DataGridCurrentCellStyle(
                borderWidth: 0, borderColor: Colors.transparent)),
        child: SfDataGrid(
          source: _employeeDataSource,
          selectionMode: SelectionMode.multiple,
          columnWidthMode: ColumnWidthMode.fill,
          columns: getColumns,
        ),
      ),
    );
  }

```

**Sample Link: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/13512544/sample.zip)**

**Comment by hardgit** [comment]
Thank you so much for your help! This plugin team has been the fastest in terms of response and resolution that I have ever encountered. Sending love!
