### ISSUE TITLE
[syncfusion_flutter_datepicker] Month and day numbers aligned too far to the left.

### ISSUE THREAD

**Issue by WaterBlueNewWorld** [syncfusion/flutter-widgets#1511]
I have been experiencing this problem 3 ago, where the date numbers and even month names are placed to the left leaving some UI inconsistencies, here are some examples:

![Captura de pantalla 2023-11-16 193448](https://github.com/syncfusion/flutter-widgets/assets/62195353/0c9dab35-dfdf-4027-b422-adb2ad6dfb6a)
![Captura de pantalla 2023-11-16 193554](https://github.com/syncfusion/flutter-widgets/assets/62195353/427681c1-a46a-43d0-94ec-b4523014d866)
![Captura de pantalla 2023-11-16 193528](https://github.com/syncfusion/flutter-widgets/assets/62195353/53f4e8a2-aa5c-4304-94b7-44f7b9bb2f8b)

First, I thought that it would be a problem with the padding and the way I am using the widget in order to be shown as a small popup, but then I made a whole screen with only the date picker and the same happened.

![Captura de pantalla 2023-11-16 193412](https://github.com/syncfusion/flutter-widgets/assets/62195353/bef30c38-8e90-4805-ae55-fec1d7011e95)

Has anyone else experienced this behavior?

**Comment by WaterBlueNewWorld** [comment]
The date picker version I'm using is: 21.2.8.

**Comment by tuannguyenneo** [comment]
@WaterBlueNewWorld 
I got the same issue on `20.4.54` version.
And it's gone after using the latest version: `23.1.44`

Thank you

**Comment by WaterBlueNewWorld** [comment]
@tuannguyenneo 
That solves my problem, still I find it weird that it happened out of nowhere.
Anyway, many thanks!
