### ISSUE TITLE
Show Arrow in Arc Tile Layer

### ISSUE THREAD

**Issue by AntonLie** [syncfusion/flutter-widgets#1513]
Hello,
it's possible to add an arrow at the end of the line?

### Screenshot
<img width="895" alt="Screenshot 2023-11-20 at 22 49 17" src="https://github.com/syncfusion/flutter-widgets/assets/89154283/d686b3b6-c878-4c54-a0b9-4144022902cd">

### Expectation
<img width="517" alt="Screenshot 2023-11-20 at 22 49 48" src="https://github.com/syncfusion/flutter-widgets/assets/89154283/aa674150-1b66-4e56-ab57-8725df448273">

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query. You can achieve your requirement by using the [markerBuilder](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/markerBuilder.html) in the [MapTileLayer](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapTileLayer-class.html). By using this, you can add the marker using the [latitude](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapMarker/latitude.html) and [longitude](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapMarker/longitude.html) properties and display the [Icon](https://api.flutter.dev/flutter/widgets/Icon-class.html) using the [child](https://api.flutter.dev/flutter/widgets/SingleChildRenderObjectWidget/child.html) property in the [MapMarker](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapMarker-class.html). By using this, you can rotate the  [Icon](https://api.flutter.dev/flutter/widgets/Icon-class.html) using [RotatedBox](https://api.flutter.dev/flutter/widgets/RotatedBox-class.html) in the [markerBuilder](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/markerBuilder.html). We have prepared a sample to show the marker at the end of the polyline. We have shared a code snippet, user guide documentation, screenshot, and sample for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.



**User Guide,**

https://help.syncfusion.com/flutter/maps/markers#adding-markers

https://help.syncfusion.com/flutter/maps/vector-layers/polyline-layer



**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/23645f94-6023-4c8e-b127-2f201332d11e)


**Code Snippet:**


``` dart
 SfMaps(
          layers: [
            MapTileLayer(
              zoomPanBehavior: MapZoomPanBehavior(
                focalLatLng: MapLatLng(24.79499378449611, 77.93678036386642),
                zoomLevel: 4.8,
              ),
              urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
              sublayers: [
                MapPolylineLayer(
                  polylines: List<MapPolyline>.generate(
                    _polylines.length,
                    (int index) {
                      return MapPolyline(
                        color: Colors.red,
                        points: _polylines[index].points,
                        width: _polylines[index].width,
                      );
                    },
                  ).toSet(),
                ),
              ],
              initialMarkersCount: 1,
              markerBuilder: (BuildContext context, int index) {
                return MapMarker(
                  latitude: _markerData[index].latitude,
                  longitude: _markerData[index].longitude,
                  child: const RotatedBox(
                    quarterTurns: 4,
                    child: Icon(
                      Icons.arrow_back,
                      color: Colors.blue,
                    ),
                  ),
                );
              },
            ),
          ],
        ),
      ),
```

Regards,
Lokesh P.

[map_524512_polyline_addmarker (1).zip](https://github.com/syncfusion/flutter-widgets/files/13460035/map_524512_polyline_addmarker.1.zip)
