### ISSUE TITLE
 [SfDatagrid] Remove default Sort Icon padding

### ISSUE THREAD

**Issue by DaathGit** [syncfusion/flutter-widgets#1515]
Hello everyone,
I recently started using the Syncfusion DataGrid package. I was testing a few functionalities, and wanted to create a table without the default sort icon, while still keeping the sorting functionality on the header cell tap.
I set it up like this:
`SfDataGridTheme(
  data: SfDataGridThemeData(
    sortIcon: Container(),
  ),
  child: SfDataGrid(
    columns: _buildColumns(dataSource),
    source: dataSource,
    allowSorting: true,
  ),
)`

But it's still adding a padding at the end of the Header cell (if i set allowSorting to false, the padding disappears)
![SfDataGrid](https://github.com/syncfusion/flutter-widgets/assets/46816187/0c3d4a5f-86cf-45a0-9e64-254f5c65a8d8)

Is there any way to remove it?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @DaathGit,

As per the current DataGrid implementation, the default outer padding is applied to the sort icons in the header cell, even when returning a Container from the **SfDataGridThemeData.sortIcon** property. Unfortunately, the SfDataGrid does not offer direct support for removing or customizing this outer padding around the sort icon.

Considering the provided image, it appears that the color applied to header cells might not extend to the icon padding space, causing it to remain transparent in the header cell. If your goal is to apply color uniformly across the entire header cell, including the icon padding space, you can utilize the **SfDataGridThemeData.headerColor** property. This property enables consistent color application throughout the header cell row.

To illustrate this and provide further insights, we have prepared a simple sample. Please refer to the code snippet and sample provided below for a more detailed understanding.

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: SfDataGridTheme(
        data: SfDataGridThemeData(
          headerColor: Colors.yellow,       // headerRowColor
          sortIcon: const SizedBox.shrink()),
        child: SfDataGrid(
          source: _employeeDataSource,
          columns: getColumns,
          columnWidthMode: ColumnWidthMode.fill,
          allowSorting: true,
        ),
      ),
    );
  }

```

**Sample Link: [SfDataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/13450995/Sample.zip)**


 
<img width="679" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/93904422/8c480441-52b1-4606-9c0b-1bde56723d3d">


We hope this helps. In case we misunderstood your requirement, please provide more specific or clear use case details. It will be helpful for us to check and provide an appropriate solution.

Regards,
Tamilarasan

**Comment by FarjanaParveen** [comment]
Hi @DaathGit ,

We are suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Farjana Parveen A
