### ISSUE TITLE
syncfusion_flutter_gauges do we need to purchase license key?

### ISSUE THREAD

**Issue by darpan-eww** [syncfusion/flutter-widgets#1516]
https://pub.dev/packages/syncfusion_flutter_gauges

Is this library we can use for free for the Flutter application or do we need to buy a license to upload the app on Play Store or app-store?

As per the official document, we don't require you to register key.
https://help.syncfusion.com/flutter/licensing/overview

**Comment by LokeshPalani** [comment]
Hi,



You need to have a Syncfusion Flutter license to use our Flutter library in your applications. But there is no need to add the license key anywhere in your project. The Flutter widgets from Syncfusion can be used without registering the license keys.



You can refer the Syncfusion licensing terms and conditions from the below links.



https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

https://help.syncfusion.com/flutter/licensing/overview



And you can get more details about our license from the below link.



https://www.syncfusion.com/sales/teamlicense



Regards,
Lokesh P.
