### ISSUE TITLE
[syncfusion_flutter_charts] : Pie chart LateInitializationError: Field 'labelRect' has not been initialized.

### ISSUE THREAD

**Issue by kadirfayzi** [syncfusion/flutter-widgets#1517]
When I tap to any legend in pie chart and then tap to any pie "LateInitializationError: Field 'labelRect' has not been initialized" throws.
Here is my code.

`class EventsChart extends StatefulWidget {
  const EventsChart({
    super.key,
    required this.graphEvents,
  });
  final List<Data?> graphEvents;

  @override
  State<EventsChart> createState() => _EventsChartState();
}

class _EventsChartState extends State<EventsChart> {
  final List<PieChartData> _chartDataList = <PieChartData>[];
  late final TooltipBehavior _tooltipBehavior;

  Map<String?, List<EventData>> _groupEventsById(List<EventData> events) =>
      groupBy(events, (EventData event) => event.eventId);

  int _sumOfEventsCount(List<EventData> eventList) =>
      eventList.fold(0, (previousValue, eventData) => previousValue += eventData.count ?? 0);

  void _loadChartData() {
    List<EventData> eventList = [];

    for (var data in widget.graphEvents) {
      for (var eventData in data!.eventDataList!) {
        eventList.add(EventData(
          eventId: eventData.eventId,
          eventName: eventData.eventName,
          eventDefinition: eventData.eventDefinition,
          count: eventData.count,
        ));
      }
    }

    final groupedEventsById = _groupEventsById(eventList);

    groupedEventsById.forEach((eventID, eventList) {
      _chartDataList.add(PieChartData(
        count: _sumOfEventsCount(eventList),
        name: eventList.firstOrNull?.eventName,
        definition: eventList.firstOrNull?.eventDefinition,
      ));
    });
  }

  void _loadTooltipBehavior() {
    _tooltipBehavior = TooltipBehavior(
      enable: true,
      builder: (data, _, __, ___, ____) => Container(
        padding: const EdgeInsets.all(8.0),
        decoration: const BoxDecoration(
          borderRadius: kBorderRadius5,
          border: Border.fromBorderSide(BorderSide(color: kPrimaryColor)),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            BuildText(text: '${data.name}: ${data.count}'),
            BuildText(text: data.definition),
          ],
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    _loadTooltipBehavior();
    _loadChartData();
  }

  @override
  Widget build(BuildContext context) {
    return SfCircularChart(
      title: ChartTitle(
        text: 'EVENT COUNT PIE CHART\n(Tap to see all information)',
        textStyle: const TextStyle(
          color: kPrimaryTextColor,
          fontSize: 14,
        ),
      ),
      legend: const Legend(
        shouldAlwaysShowScrollbar: true,
        isVisible: true,
        isResponsive: true,
        position: LegendPosition.bottom,
        overflowMode: LegendItemOverflowMode.wrap,
        textStyle: TextStyle(color: kPrimaryTextColor),
      ),
      tooltipBehavior: _tooltipBehavior,
      series: <CircularSeries>[
        PieSeries<PieChartData, String>(
          radius: '100%',
          dataLabelSettings: DataLabelSettings(
            isVisible: true,
            overflowMode: OverflowMode.shift,
            labelIntersectAction: LabelIntersectAction.shift,
            builder: (data, point, series, pointIndex, seriesIndex) => BuildText(
              text: '${data.count}',
              color: kPrimaryTextColor,
              fontSize: 18,
            ),
          ),
          dataSource: _chartDataList,
          xValueMapper: (PieChartData data, _) => data.name,
          yValueMapper: (PieChartData data, _) => data.count,
        )
      ],
    );
  }
}`

https://github.com/syncfusion/flutter-widgets/assets/24958721/937d3786-a984-46d7-9536-a545afbc6cd0

**Comment by LokeshPalani** [comment]
Hi,



We have replicated the reported issue regarding **"Exception is thrown when trying to show a tooltip with builder data label"** on our end and have logged a bug report for it in our feedback portal. We will fix the issue and include the changes in our **weekly main release**, which is expected to be rolled out in the second week of December. We will update you here once the release is rolled out, and we appreciate your patience until then. You can also track the status of the bug with the feedback provided below.



Feedback Link :  https://www.syncfusion.com/feedback/48762/exception-is-thrown-when-try-to-show-tooltip-with-builder-data-label



Regards,
Lokesh P.
