### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by athiraRajR** [syncfusion/flutter-widgets#1518]
how to Show Label instead of Values?

**Comment by LokeshPalani** [comment]
Hi,



We have validated your code snippet. You can achieve your requirement by using the [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html) in the [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html). In this callback, you will receive every axis label text that has been formatted based on the value. We have created a sample that shows how to customize the label. We have shared user guide documentation, knowledge base, code snippet, screenshot, and sample for your reference. Please let us know if you need any further details.


**UG,**

https://help.syncfusion.com/flutter/slider/labels-and-divider#horizontal-6



**KB,**

https://support.syncfusion.com/kb/article/11284/how-to-customize-labels-text-in-flutter-slider



**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/184d6e1e-3dcc-42a3-8dbf-ba8754b26401)



Code Snippet:

``` dart
 double _value = 5.0;

    child: SfSlider(
            min: 0.0,
            max: 10.0,
            interval: 5,
            showTicks: true,
            showLabels: true,
            value: _value,
            labelFormatterCallback:
                (dynamic actualValue, String formattedText) {
              return actualValue == 5 ? '\$ $formattedText' : formattedText;
            },
            onChanged: (dynamic newValue) {
              setState(
                () {
                  _value = newValue;
                },
              );
            },
          ),
```

Regards,
Lokesh P.

[slider_525321_label.zip](https://github.com/syncfusion/flutter-widgets/files/13459965/slider_525321_label.zip)

**Comment by athiraRajR** [comment]
Hi ,
What if the value like this  {10.0: low, 1.0: high, 0.0: medium, 67.0:
fgfd} how to do that .

I need the output like this . this is sample map value . these values are
dynamic.

[image: image.png]


Thanks ,
Athira

**Comment by LokeshPalani** [comment]
Hi,



We have checked your query at our end and as we are not able to understand what your proposing as your requirement, and attached image also not visible. we kindly request you to share us with more information on your requirement in detail along with screenshots/screenrecordings. This will help us assist you in a better way.

Regards,
Lokesh P.

**Comment by athiraRajR** [comment]
Hi,
Is there any way to adjust the label text width.

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query and achieved your requirement by using the [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html) in the [SfSliderTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderTheme-class.html). By utilizing this, you can modify the label text size using [activeLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeLabelStyle.html) and [inactiveLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveLabelStyle.html) in the [SfSliderTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderTheme-class.html). We have provided a sample, code snippet, and screenshot for your reference. Feel free to modify the sample according to your needs. Please inform us if you require any additional assistance.



**Code Snippet:**

``` dart
 child: SfSliderTheme(
            data: SfSliderThemeData(
              activeLabelStyle: const TextStyle(
                fontSize: 10,
                color: Colors.red,
              ),
              inactiveLabelStyle: const TextStyle(
                fontSize: 10,
                color: Colors.red,
              ),
            ),
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/fd1c39be-f069-4317-919d-044e1230afac)



Regards,
Lokesh P.
