### ISSUE TITLE
End change callbacks needed on syncfusion_flutter_sliders

### ISSUE THREAD

**Issue by skripsimu** [syncfusion/flutter-widgets#152]
Hi, I need this feature to change the value of the slider when the slider is not changed anymore. because if I change it in onChanged there will be too many changes there.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Skripsimu,   

Greetings from Syncfusion.    

Though this is not possible using SfSlider or SfRangeSlider, could you please check the below behavior of our SfRangeSelector widget will be suitable for you?    

You may restrict the call to the onChanged callback while thumbs are being dragged continuously using SfRangeSelector.enableDeferredUpdate property. The delay in the update can be achieved by setting the SfRangeSelector.deferredUpdateDelay property. The default value of the deferredUpdateDelay property is 500 milliseconds.   

It will invoke the onChanged callback when the thumb is dragged and held for the duration specified in the deferredUpdateDelay. However, thumb values are immediately updated in touch up action.    

**Code snippet:**   

  import 'package:flutter/material.dart'; 
  import 'package:flutter/rendering.dart'; 
  import 'package:intl/intl.dart' show DateFormat; 
  import 'package:syncfusion_flutter_sliders/sliders.dart'; 
   
  class RangeSelectorPage extends StatefulWidget { 
  @override 
  _RangeSelectorPageState createState() => _RangeSelectorPageState(); 
} 
   
  class _RangeSelectorPageState extends State<RangeSelectorPage> { 
  final DateTime _min = DateTime(2010, 01, 01, 0), 
      _max = DateTime(2015, 01, 01); 
  final SfRangeValues _initialValues = 
      SfRangeValues(DateTime(2012, 01, 01, 0), DateTime(2013, 01, 01, 0)); 
   
  @override 
  Widget build(BuildContext context) { 
    return Scaffold( 
      appBar: AppBar(title: Text('Deferred update')), 
      body: Container( 
        padding: const EdgeInsets.only(top: 30), 
        width: 400, 
        child: SfRangeSelector( 
          min: _min, 
          max: _max, 
          initialValues: _initialValues, 
          interval: 1, 
          enableDeferredUpdate: true, 
          deferredUpdateDelay: 500, 
          dateIntervalType: DateIntervalType.years, 
          dateFormat: DateFormat.y(), 
          showTicks: true, 
          showLabels: true, 
          onChanged: (SfRangeValues values) {}, 
          child: SizedBox(), 
        ), 
      ), 
    ); 
  } 
}  


**UG link:** https://help.syncfusion.com/flutter/range-selector/range-controller#deferred-update     

Kindly check whether able to fulfil your requirement with the above code snippet. If your requirement is different from the above, kindly provide brief details about your requirement.    

Regards,    
Lakshmi R.

**Comment by skripsimu** [comment]
I mean, is is possible for me to know the thumbs are being dragged or not? because i want to round the value when the thumbs is no longer dragged like in this video
![ezgif-6-41dce07866fa](https://user-images.githubusercontent.com/35763779/111123434-e994bd00-85a1-11eb-925a-384f5a825105.gif)

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Skripsimu,

It is currently not possible to check whether the thumbs are being dragged or not. However, we hope that you may achieve something similar using SfSlider.stepSize support. Could you please use the below link to check whether stepSize support will help you to achieve your requirement?

https://help.syncfusion.com/flutter/slider/interval#discrete-selection-for-numeric-values  

Kindly revert us, if your requirement is different from the above.

Regards,
Lakshmi R.
