### ISSUE TITLE
[syncfusion_flutter_charts] : Are there any chart type to achieve this?

### ISSUE THREAD

**Issue by kadirfayzi** [syncfusion/flutter-widgets#1520]
<img width="358" alt="Screenshot 2023-11-23 at 12 03 41" src="https://github.com/syncfusion/flutter-widgets/assets/24958721/00eed23f-3e8e-4b5f-8a8d-066ba2131e12">

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
