### ISSUE TITLE
[syncfusion_flutter_calendar] Scrollcontroller not attached when switching views

### ISSUE THREAD

**Issue by kamami** [syncfusion/flutter-widgets#1521]
When switching the view from `CalendarView.schedule` to` ​CalendarView.timelineWeek`, the widget throws following exception after trying to scroll vertically: 
`Another exception was thrown: ScrollController not attached to any scroll views.`

It only appears if timelineWeek has resources and with it vertical scrolling is enabled.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @kamami ,

The reported issue has been fixed and rolled out in our Volume 4 2023 main release. To avoid this please upgrade the syncfusion_flutter_calendar package to the latest version below.

Package, https://pub.dev/packages/syncfusion_flutter_calendar/versions/24.2.6

Regards,
Yuvaraj.
