### ISSUE TITLE
How can I create custom view header in CalendarView.timelineMonth?

### ISSUE THREAD

**Issue by Sunsiha** [syncfusion/flutter-widgets#1522]
How can I create the following way in 

` view: CalendarView.timelineMonth,`

<img width="926" alt="Screenshot 2023-11-23 at 7 32 39 PM" src="https://github.com/syncfusion/flutter-widgets/assets/27992382/84461dde-db22-485b-9af7-d74b429794c4">

I have tried to customize the header, but got the code only related like this;

```viewHeaderHeight: 100,
              viewHeaderStyle: ViewHeaderStyle(
                  backgroundColor: Colors.grey,
                  dayTextStyle: TextStyle(
                      fontSize: 22,
                      color: Color(0xFFff5eaea),
                      fontWeight: FontWeight.w500),
                  dateTextStyle: TextStyle(
                      fontSize: 22,
                      color: Color(0xFFff5eaea),
                      letterSpacing: 2,
                      fontWeight: FontWeight.w500)),
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Sunsiha ,

We already have a KB that explains, how to add a custom header and view header in the Flutter Calendar. We have shared the related KB documentation below for your reference. You can follow its guidelines and achieve your requirements.

KB, https://support.syncfusion.com/kb/article/9606/how-to-add-custom-header-and-view-header-in-the-flutter-calendar

Regards,
Yuvaraj.
