### ISSUE TITLE
Unhandled Exception: Invalid argument (The character is not supported by the font.)

### ISSUE THREAD

**Issue by yusmi25** [syncfusion/flutter-widgets#1526]
hello, I'm using syncfusion_pdf_flutter, to print the symbol ✅✔✓☑ 💯☐☒❎✗✘ using function PdfGrid, but get error invalid character, any solution? 
this is my code :

row.cells[2].value = "✅";
row.cells[3].value = "💯";
row.cells[4].value = "✗";

thanks.

**Comment by Abdullah3780** [comment]
I faced the same issue. (Emojis) Unicodes are not handled in the fonts.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (The character is not supported by the font.):
