### ISSUE TITLE
[syncfusion_flutter_maps] MapTileLayerController.pixelToLatLng null error

### ISSUE THREAD

**Issue by stha-ums** [syncfusion/flutter-widgets#153]
in MapTileLayerController there is pixelToLatLng which uses _state ehich is not initialized.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi stha-ums,  
  
Greetings from Syncfusion.  
  
We suspect that you have not set the instance of MapTileLayerController to the MapTileLayer.controller property. We have attached the code snippet for your reference.  

**Code snippet:**

`MapZoomPanBehavior _zoomPanBehavior; 
  MapTileLayerController _tileLayerController; 

@override 
  void initState() { 
  _tileLayerController = MapTileLayerController(); 
  _zoomPanBehavior = MapZoomPanBehavior( 
    zoomLevel: 2, 
  ); 
  super.initState(); 
} 

@override 
  Widget build(BuildContext context) { 
  return Scaffold( 
    body: SfMaps( 
      layers: [ 
        MapTileLayer( 
          urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png', 
          zoomPanBehavior: _zoomPanBehavior, 
          controller: _tileLayerController,
        ) 
      ] 
    ), 
  ); 
} 
`

Feel free to contact us if you need further assistance on this. 
  
Regards,
Lakshmi R.

**Comment by stha-ums** [comment]
thank you.
