### ISSUE TITLE
[SfDataGrid] Add a way to change GridTableSummaryRow

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1534]
GridTableSummaryRow is the same height with row. If i want GridTableSummaryRow  have a diffirent height, how can i do it?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Trung15010802,

Currently, the DataGrid lacks a dedicated API for adjusting the height of the table summary row, unlike the **`rowHeight`** property available for DataGridRow. However, you can dynamically customize the summary row's height using the **`SfDataGrid.onQueryRowHeight`** callback.

In this approach, you'll need to manually track the index of the table summary row within your sample. Then, within the **SfDataGrid.onQueryRowHeight** callback, you can specify the desired height based on the row index corresponding to the table summary row. Please check the following code snippet and attached sample for more information.

<details>
<summary>Code Snippet </summary>

```dart
// The DataGrid has one header row and the index is 0.
  // The DataGrid has one table summary row at the top
  // and it will be displayed next to the header row.
  // So, the table summary row index is 1.
  int tableSummaryRowIndex = 1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: SfDataGrid(
        source: _employeeDataSource,
        columns: getColumns,
        onQueryRowHeight: (details) {
          if (details.rowIndex == tableSummaryRowIndex) {
            return 100;
          } else {
            return details.rowHeight;
          }
        },
        columnWidthMode: ColumnWidthMode.fill,
        tableSummaryRows: [
          GridTableSummaryRow(
              showSummaryInRow: true,
              title: 'Total Salary: {Sum} for 30 employees',
              columns: [
                const GridSummaryColumn(
                    name: 'Sum',
                    columnName: 'Salary',
                    summaryType: GridSummaryType.sum)
              ],
              position: GridTableSummaryRowPosition.top)
        ],
      ),
    );
  }

```
</details>

<details>
<summary>Output</summary>

<img width="960" alt="Screenshot 2024-02-14 122654" src="https://github.com/syncfusion/flutter-widgets/assets/93904422/94c21d55-0253-4b2a-8ae0-7d54a315b604">

</details>

**Sample Link: [Flutter-DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/14277934/Sample.zip)**


Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Trung15010802,

We hope that the reported issue has been resolved at your end with the provided workaround. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
