### ISSUE TITLE
Smart PDF disable input editing

### ISSUE THREAD

**Issue by RitliRoland** [syncfusion/flutter-widgets#1535]
Hello! I'm using this package for showing a smart pdf, but i don't want let the user to edit the fields. Is there a way to do this?
![image](https://github.com/syncfusion/flutter-widgets/assets/48223614/513a6e31-5810-44d6-b5a1-d05c3e4ae16c)

**Comment by deepika134** [comment]
In SfPdfViewer, to prevent editing the values of the form fields in the PDF document, please refer to the following UG documentation link:

UG Link: https://help.syncfusion.com/flutter/pdf-viewer/form-filling#restrict-the-editing-of-form-fields 

Please try this and let us know if you have any concerns.
