### ISSUE TITLE
[syncfusion_flutter_calendar] changing mouse pointer to hand when hovering over a cell

### ISSUE THREAD

**Issue by wxpcl123** [syncfusion/flutter-widgets#1538]
I want to change the mouse pointer to hand when hovering over a cell when I use syncfusion_flutter_calendar. I used monthCellBuilder to create a cell.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @wxpcl123,

As per the current implementation of the calendar, we do not have the option to customize the cursor.  We have provided Drag and drop, Resizing features that handle the cursor type internally, so we restricted the cursor type. We hope that this information helps you. Please get in touch with us if you require more details.

Regards,
Yuvaraj
