### ISSUE TITLE
null safety version plz

### ISSUE THREAD

**Issue by oussaid1** [syncfusion/flutter-widgets#154]
please upgrade the package to null safety

**Comment by Dharanipalani** [comment]
Hi @oussaid1,

Thanks for the interest in our Flutter charts. We are working on it and will provide the null safety support for all our widgets in the volume1 main release, which is expected to be rolled out at the end of March 2021. We appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by vjrj** [comment]
FYI: https://github.com/syncfusion/flutter-widgets/issues/162#issuecomment-811077718

**Comment by Dineshkumar-kovalan** [comment]
Hi @oussaid1,

Thanks for your patience. We are glad to inform you that we have migrated our chart package to null safety and is rolled out in our vol 1 main release. To use the null safety version of the chart widget, kindly upgrade the package version to the latest version below.

https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.54+1

Please revert us if you still have further concerns.

Regards,
Dineshkumar K
