### ISSUE TITLE
Error: Member not found: 'MediaQuery.textScalerOf'

### ISSUE THREAD

**Issue by hurkanugur** [syncfusion/flutter-widgets#1545]
Getting this error when I upgraded syncfusion_flutter_calendar to 23.2.5:

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-23.2.5/lib/src/date_picker/date_picker.dart:5630:35: Error: Member not found: 'MediaQuery.textScalerOf'.

**Comment by KalaliEhsan** [comment]
You should upgrade Flutter SDK to the latest version and resolve this issue. @hurkanugur

**Comment by darkomenx** [comment]
Same issue with this context : 
Flutter 3.13.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d211f42860 (5 weeks ago) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

And try : 
syncfusion_flutter_calendar: ^23.2.6
syncfusion_flutter_calendar: 23.2.6
syncfusion_flutter_calendar: ^23.2.5
syncfusion_flutter_calendar: 23.2.6
syncfusion_flutter_calendar: 23.2.6

**Comment by darkomenx** [comment]
I upgrade Flutter SDK with : 
Flutter 3.16.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7f20e5d18c (2 days ago) • 2023-11-27 09:47:30 -0800
Engine • revision 22b600f240
Tools • Dart 3.2.1 • DevTools 2.28.3

and use : 
syncfusion_flutter_calendar: ^23.2.6

And I confirm that it works !

**Comment by manokrajin** [comment]
> You should upgrade Flutter SDK to the latest version and resolve this issue. @hurkanugur

this works on me, maybe you guys can try to upgrade it since i am installing the latest version of flutter sdk in november 2023. The latest version of syncfusion date picker need the latets flutter sdk available, at least for the moment i comment this

**Comment by hurkanugur** [comment]
@manokrajin Yeah, it was resolved after a later patch. I forgot to close this issue. Thanks for reminding me :)
