### ISSUE TITLE
TextScaler.linear

### ISSUE THREAD

**Issue by thisadee2897** [syncfusion/flutter-widgets#1546]
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.5/lib/src/chart/base/chart_base.dart:1838:33: Error: Couldn't find constructor
'TextScaler.linear'.

**Comment by 53huzefa-zeenwala** [comment]
I am having same problem, what's the reason?

**Comment by pen110** [comment]
me too

**Comment by cyberail** [comment]
We fixed it by keeping, 23.2.4 version without carrot symbol, so it will not upgrade.

```yaml
syncfusion_flutter_datepicker: 23.2.4
```

**Comment by KalaliEhsan** [comment]
I have the same issue with version ```syncfusion_flutter_charts:^23.2.6``` and Flutter SDK is 3.13.9.

```console
/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.6/lib/src/chart/base/chart_base.dart:1838:33: Error: Couldn't find constructor 'TextScaler.linear'.
              textScaler: const TextScaler.linear(1.2),
```

**Comment by KalaliEhsan** [comment]
You should upgrade Flutter SDK to the latest version and resolve this issue. @thisadee2897

**Comment by zakblacki** [comment]
not ideal I do not want to update my flutter right now for compatibility purpose 
Which versions is recommended to use to avoid this

**Comment by LokeshPalani** [comment]
Hi @zakblacki,

You can use syncfusion_flutter_charts: 23.2.4 without caret (^) sign to prevent upgrading the Flutter SDK to the latest version.

Regards,
Lokesh P.
