### ISSUE TITLE
Member not found: 'MediaQuery.textScalerOf'.

### ISSUE THREAD

**Issue by a4ekw** [syncfusion/flutter-widgets#1547]
syncfusion_flutter_datagrid-23.2.6/lib/src/datagrid_widget/sfdatagrid.dart:3076:50: Error: Member not found: 'MediaQuery.textScalerOf'.

**Comment by Zaveri21** [comment]
I am facing same the issues after flutter clean & flutter pib get. Any update?

**Comment by cyberail** [comment]
I fixed it by keeping, 23.2.4 version without carrot symbol, so it will not upgrade.

```yaml
syncfusion_flutter_datepicker: 23.2.4
```

**Comment by nirajjoshi** [comment]
I am also facing the similar issue. 
Here is the log: 

Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:1610:54: Error: The getter 'textScaler' isn't defined for the class 'MediaQueryData'.
legend.dart:1610

Error launching application on ***** .

**Comment by nirajjoshi** [comment]
> We fixed it by keeping, 23.2.4 version without carrot symbol, so it will not upgrade.
> 
> ```yaml
> syncfusion_flutter_datepicker: 23.2.4
> ```

Still not working.

**Comment by a4ekw** [comment]
> Still not working.

Make sure you use the rest of the dependencies of the same version
syncfusion_flutter_core: 23.2.4

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @a4ekw,

It appears that the issue you are experiencing could be due to using an older version of the Flutter SDK. We have updated our source for compatibility with the latest Flutter SDK. We recommend updating your Flutter SDK to the latest version to ensure compatibility with the most recent **Syncfusion Flutter DataGrid**. This update might resolve the problem you are encountering.

Regards,
Tamilarasan

**Comment by KalaliEhsan** [comment]
> Hi @a4ekw,
> 
> It appears that the issue you are experiencing could be due to using an older version of the Flutter SDK. We have updated our source for compatibility with the latest Flutter SDK. We recommend updating your Flutter SDK to the latest version to ensure compatibility with the most recent **Syncfusion Flutter DataGrid**. This update might resolve the problem you are encountering.
> 
> Regards, Tamilarasan

I upgraded Flutter SDK to the latest version and resolved this problem
Thanks @Tamilarasan-Paranthaman

**Comment by LokeshPalani** [comment]
Hi,



We have analyzed your query and checked the reported issue. We would like to inform you that the textScaleFactor property has been deprecated to the textScaler property from Flutter 3.16.0. Our packages are now compatible with the 3.16 version. To resolve the mentioned issue regarding "The getter 'textScaler' isn't defined for the 'MediaQueryData'", we suggest upgrading the Flutter SDK to the latest version.



Regards,
Lokesh P.
