### ISSUE TITLE
The getter 'textScaler' isn't defined for the class 'MediaQueryData'.

### ISSUE THREAD

**Issue by nirajjoshi** [syncfusion/flutter-widgets#1548]
Getting Below error:

error: ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:1610:54: Error: **The getter 'textScaler' isn't defined for the class 'MediaQueryData'.**
 - 'MediaQueryData' is from 'package:flutter/src/widgets/media_query.dart' ('../../../Softwares/flutter/packages/flutter/lib/src/widgets/media_query.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
    _textPainter.textScaler = MediaQuery.of(context).textScaler;
                                                     ^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:1610:18: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('../../../Softwares/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
    _textPainter.textScaler = MediaQuery.of(context).textScaler;
                 ^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:2618:9: Error: No named parameter with the name 'textScaler'.
        textScaler: MediaQuery.of(context).textScaler);
        ^^^^^^^^^^
../../../Softwares/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Comment by JasurbekErgashev** [comment]
the same problem is occurring today. Everything was fine yesterday. I have changed the version.
`syncfusion_flutter_datagrid: ^23.1.39`

**Comment by cyiboy** [comment]
same here, it worked for me some hours ago. building now it giving me same error,   have not changed the version.

**Comment by mfurkanyuceal** [comment]
Same problem

**Comment by ndasim** [comment]
Same here!

**Comment by cyiboy** [comment]
same problem here

**Comment by KalaliEhsan** [comment]
You should upgrade Flutter SDK to the latest version and resolve this issue. @nirajjoshi

**Comment by barretthodgson** [comment]
same problem here
