### ISSUE TITLE
DocIO library for Flutter?

### ISSUE THREAD

**Issue by jongkb** [syncfusion/flutter-widgets#155]
Any plans to release a Word document (DocIO) library for Flutter?

Thank you.

**Comment by MohanaselvamJ** [comment]
Hi @jongkb ,

Thank you for contacting Syncfusion support.

Currently, DocIO doesn't have support in Flutter. We do not have any immediate plans to implement this. Could you please share us the use case of this requirement and more details about the functionalities that you are trying to use at your end. Thereby, we will check and prioritize your requirements during our feature implementation.

**Comment by jongkb** [comment]
Thank you for the response. Essentially, my Flutter mobile app needs to be able to open an existing DOCX file and extract certain textual content for further manipulation within the app.

**Comment by MohanaselvamJ** [comment]
Hi @jongkb ,

Thank you for your details.

As we mentioned earlier, currently Syncfusion doesn’t have DocIO library in Flutter. We do not have any immediate plans to implement this. While implementing this feature, we will consider your requirements in first phase of implementation at our side.
