### ISSUE TITLE
change month cell width

### ISSUE THREAD

**Issue by SobhyAlbert** [syncfusion/flutter-widgets#1554]
hello everyone,
i tried to customize the month cell width with no success, what i am asking is can i show less than 7 days in the month view ?? i mean can i only show 4 days that fills the whole screen ??

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @SobhyAlbert ,

Yes, you can achieve your requirements with the help of the [view](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController/view.html) and [numberOfDaysInView](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/numberOfDaysInView.html) property in the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html). Here you need to set the view as week and set the [numerOfDaysInView](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/TimeSlotViewSettings/numberOfDaysInView.html) to 4 as per your requirement. We have also shared the code snippet and screenshot below for your reference. If you have any further queries please get back to us.

Code snippet:
```dart
SfCalendar(
   view: CalendarView.week,
   dataSource: _AppointmentDataSource([]),
   timeSlotViewSettings:
       const TimeSlotViewSettings(numberOfDaysInView: 4),
 ),
```

Screenshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/61863686/baf0ed95-7e4c-4101-84fc-bc0270c6b964)


Thanks,
Yuvaraj.
