### ISSUE TITLE
[syncfusion_flutter_datagrid] Problem with SfDataPager and RealTime update data

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1555]
I got this problem with SfDataPager. If i use SfDataPager, my data can't update realtime with api fetch each second.

If i use SfDataPager, my data can't update realtime with api fetch each second. I can't update table data if i'm using SFDataPaper
This is the video showing the error:
https://github.com/syncfusion/flutter-widgets/assets/90593296/0a9ddba0-5b62-49ba-a0ca-308255e9b3e7

I use this to update data:
```

  /// Runtime Updating the cell values
  void timerTick(List<User> newLists) {
    _changeRows(newLists);
  }

  void _changeRows(List<User> newList) {
    if (userList.length != newList.length) {
      userList.clear();
      userList.addAll(newList);
      buildDataGridRows();
      notifyListeners();
      return;
    }

    for (int i = 0; i < userList.length; i++) {
      void updateDataRow() {
        dataGridRows[i] = DataGridRow(
          cells: <DataGridCell>[
            DataGridCell<int>(columnName: 'id', value: userList[i].id),
            DataGridCell<String>(
                columnName: 'username', value: userList[i].username),
            DataGridCell<String>(
                columnName: 'firstName', value: userList[i].firstName),
            DataGridCell<String>(
                columnName: 'lastName', value: userList[i].lastName),
            DataGridCell<String>(
                columnName: 'password', value: userList[i].password),
            DataGridCell<String>(columnName: 'email', value: userList[i].email),
          ],
        );
      }

      if (userList[i] != newList[i]) {
        userList[i].id = newList[i].id;
        userList[i].username = newList[i].username;
        userList[i].firstName = newList[i].firstName;
        userList[i].lastName = newList[i].lastName;
        userList[i].password = newList[i].password;
        userList[i].email = newList[i].email;
        updateDataRow();
        for (var j = 1; j <= 6; j++) {
          updateDataSource(rowColumnIndex: RowColumnIndex(i, j));
        }
      }
    }
  }
```

Please look my code for more info. Thank you very much. It's great package
[realtime_data_grid.zip](https://github.com/syncfusion/flutter-widgets/files/13523762/realtime_data_grid.zip)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Trung15010802,

We are glad to inform you that the issue " The values in the DataGrid didn't refresh when calling notifyDataSourceListeners alongside DataPager" has been fixed and included in our weekly pub release. Please update the DataGrid package to version **24.1.43.**
 
https://pub.dev/packages/syncfusion_flutter_datagrid
 
Regards,
Tamilarasan

**Comment by Trung15010802** [comment]
> Hi @Trung15010802,
> 
> We are glad to inform you that the issue " The values in the DataGrid didn't refresh when calling notifyDataSourceListeners alongside DataPager" has been fixed and included in our weekly pub release. Please update the DataGrid package to version **24.1.43.**
> 
> https://pub.dev/packages/syncfusion_flutter_datagrid
> 
> Regards, Tamilarasan

It's working but have a problem. In the first time DataGrid update only the first row change.
**Before:**
![before](https://github.com/syncfusion/flutter-widgets/assets/90593296/258253ef-550a-4200-9915-acb54be7ad6c)

**After:**
![after](https://github.com/syncfusion/flutter-widgets/assets/90593296/0bca46f3-9f30-4f72-80a9-10f74afba1be)

It's only change the first row when we calling _timerTick() for the first time.

**Comment by Tamilarasan-Paranthaman** [comment]
@Trung15010802,

Upon reviewing your sample, it's apparent that you are creating a new instance of the DataGridRow each time a cell value is updated. To align with best practices for runtime changes in DataGrid implementation, particularly when using DataPager, we recommend updating the existing cells within a row instead of generating new rows. Making this adjustment might help resolve the issue experienced during the initial loading. Kindly review the suggested code changes in the **updateDataRow** method of your sample for potential resolution.

```dart
      void updateDataRow() {
      
        // Instead of creating a new DataGridRow, you can update the existing DataGridRow.
        dataGridRows[i].getCells()[0] =
            DataGridCell<int>(columnName: 'id', value: userList[i].id);
        dataGridRows[i].getCells()[1] = DataGridCell<String>(
            columnName: 'username', value: userList[i].username);
        dataGridRows[i].getCells()[2] = DataGridCell<String>(
            columnName: 'firstName', value: userList[i].firstName);
        dataGridRows[i].getCells()[3] = DataGridCell<String>(
            columnName: 'lastName', value: userList[i].lastName);
        dataGridRows[i].getCells()[4] = DataGridCell<String>(
            columnName: 'password', value: userList[i].password);
        dataGridRows[i].getCells()[5] =
            DataGridCell<String>(columnName: 'email', value: userList[i].email);

        // dataGridRows[i] = DataGridRow(
        //   cells: <DataGridCell>[
        //     DataGridCell<int>(columnName: 'id', value: userList[i].id),
        //     DataGridCell<String>(
        //         columnName: 'username', value: userList[i].username),
        //     DataGridCell<String>(
        //         columnName: 'firstName', value: userList[i].firstName),
        //     DataGridCell<String>(
        //         columnName: 'lastName', value: userList[i].lastName),
        //     DataGridCell<String>(
        //         columnName: 'password', value: userList[i].password),
        //     DataGridCell<String>(columnName: 'email', value: userList[i].email),
        //   ],
        // );
      }

```

**Comment by Trung15010802** [comment]
> @Trung15010802,
> 
> Upon reviewing your sample, it's apparent that you are creating a new instance of the DataGridRow each time a cell value is updated. To align with best practices for runtime changes in DataGrid implementation, particularly when using DataPager, we recommend updating the existing cells within a row instead of generating new rows. Making this adjustment might help resolve the issue experienced during the initial loading. Kindly review the suggested code changes in the **updateDataRow** method of your sample for potential resolution.
> 
> ```dart
>       void updateDataRow() {
>       
>         // Instead of creating a new DataGridRow, you can update the existing DataGridRow.
>         dataGridRows[i].getCells()[0] =
>             DataGridCell<int>(columnName: 'id', value: userList[i].id);
>         dataGridRows[i].getCells()[1] = DataGridCell<String>(
>             columnName: 'username', value: userList[i].username);
>         dataGridRows[i].getCells()[2] = DataGridCell<String>(
>             columnName: 'firstName', value: userList[i].firstName);
>         dataGridRows[i].getCells()[3] = DataGridCell<String>(
>             columnName: 'lastName', value: userList[i].lastName);
>         dataGridRows[i].getCells()[4] = DataGridCell<String>(
>             columnName: 'password', value: userList[i].password);
>         dataGridRows[i].getCells()[5] =
>             DataGridCell<String>(columnName: 'email', value: userList[i].email);
> 
>         // dataGridRows[i] = DataGridRow(
>         //   cells: <DataGridCell>[
>         //     DataGridCell<int>(columnName: 'id', value: userList[i].id),
>         //     DataGridCell<String>(
>         //         columnName: 'username', value: userList[i].username),
>         //     DataGridCell<String>(
>         //         columnName: 'firstName', value: userList[i].firstName),
>         //     DataGridCell<String>(
>         //         columnName: 'lastName', value: userList[i].lastName),
>         //     DataGridCell<String>(
>         //         columnName: 'password', value: userList[i].password),
>         //     DataGridCell<String>(columnName: 'email', value: userList[i].email),
>         //   ],
>         // );
>       }
> ```

Thank you for your help. It's working normaly right now
