### ISSUE TITLE
 i have got  textScaler: const TextScaler.linear(1.2) issue when i run the app

### ISSUE THREAD

**Issue by MuhammadSherdil** [syncfusion/flutter-widgets#1557]
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.6/lib/src/chart/base/chart_base.dart:1838:33: Error: Couldn't find constructor 'TextScaler.linear'.
              textScaler: const TextScaler.linear(1.2),
                                ^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.6/lib/src/chart/base/chart_base.dart:1838:15: Error: No named parameter with the name 'textScaler'.
              textScaler: const TextScaler.linear(1.2),
              ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.6/lib/src/common/utils/helper.dart:965:33: Error: Couldn't find constructor 'TextScaler.linear'.
              textScaler: const TextScaler.linear(1.2),
                                ^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.6/lib/src/common/utils/helper.dart:965:15: Error: No named parameter with the name 'textScaler'.
              textScaler: const TextScaler.linear(1.2),
              ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:1610:54: Error: The getter 'textScaler' isn't defined for the class 'MediaQueryData'.
 - 'MediaQueryData' is from 'package:flutter/src/widgets/media_query.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/media_query.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
    _textPainter.textScaler = MediaQuery.of(context).textScaler;
                                                     ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:1610:18: Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
    _textPainter.textScaler = MediaQuery.of(context).textScaler;
                 ^^^^^^^^^^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_core-23.2.6/lib/src/legend/legend.dart:2618:9: Error: No named parameter with the name 'textScaler'.
        textScaler: MediaQuery.of(context).textScaler);
        ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
Failed to compile application.
here is the issue when app is compiling

**Comment by MuhammadSherdil** [comment]
we have to update flutter latest version

**Comment by zakblacki** [comment]
I need another solution except upgrade flutter because by doing so I'm faced with another issue 

`"flutter/packages/flutter/lib/src/dart_plugin_registrant.dart:1:1: Error: The specified language version is too high. The highest supported language version is 3.1 "
`
