### ISSUE TITLE
Which version don't use textScaler ? because I downgraded flutter 

### ISSUE THREAD

**Issue by mazab99** [syncfusion/flutter-widgets#1561]

**Comment by mazab99** [comment]
I used this now

syncfusion_flutter_datepicker: ^23.1.38


but I still have 

Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
    _textPainter.textScaler = TextScaler.linear(textScaleFactor);


syncfusion_flutter_datepicker-23.2.7/lib/src/date_picker/date_picker.dart:8312:31: Error: The getter 'TextScaler' isn't defined for the class '_PickerHeaderPainter'.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you still face an issue with latest version.
