### ISSUE TITLE
when I'm trying to build ios app in xcode it give me this error ...

### ISSUE THREAD

**Issue by mamine3004** [syncfusion/flutter-widgets#1563]
Running Xcode build...
Xcode build done.                                           14.9s
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.7/lib/src/chart/base/chart_base.dart:1838:33: Error: Couldn't find constructor 'TextScaler.linear'.

Could not build the application for the simulator.
<img width="1323" alt="Screenshot 2023-12-07 at 10 08 43" src="https://github.com/syncfusion/flutter-widgets/assets/119679839/4933928a-4d84-4770-9997-331757da4fee">

**Comment by LokeshPalani** [comment]
Hi,



We would like to inform you that the textScaleFactor property has been deprecated and replaced with the textScaler property in Flutter 3.16.0. Our packages are now compatible with version 3.16 of Flutter. To resolve the issue you mentioned regarding "The getter 'textScaler' isn't defined for the 'MediaQueryData'", we suggest upgrading to the latest version of the Flutter SDK.



If you prefer to avoid upgrading to the latest Flutter SDK version, please let us know the current SDK version you are using. We will then suggest a compatible version of our charts package for that specific SDK version.



Regards,
Lokesh P.

**Comment by mamine3004** [comment]
thanks
