### ISSUE TITLE
[syncfusion_flutter_datepicker] Century navigation for the SfHijriDateRangePicker is missing

### ISSUE THREAD

**Issue by tariqshaban** [syncfusion/flutter-widgets#1564]
### Issue Description
The `SfHijriDateRangePicker()` widget does not have the century hierarchy view; unlike `SfDateRangePicker()`.

### Steps to Reproduce
Simply use the `SfHijriDateRangePicker()` without any additional arguments, and keep tapping on the date picker's header to navigate to the next view in the hierarchy.

Reproducible on version `23.1.43` and `23.2.7`.

### Expected Behavior
User can navigate between months, years, decades, and **_centuries_**.

### Actual Behavior
User can only navigate between months, years, and decades.

**Comment by Yuvaraj-Gajaraj** [comment]
HI @tariqshaban ,

We would like to let you know that currently, we don’t have support for Century View in the [SfHijriDateRangePicker](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfHijriDateRangePicker-class.html). However, we have considered your requirement as a new feature and logged a feature request for it in our feedback portal. 

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback, https://www.syncfusion.com/feedback/51884

Regards,
Yuvaraj.
