### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Migrate from ` RepositoryHandler.jcenter()` to `mavenCentral()` for gradle 8.X

### ISSUE THREAD

**Issue by dickermoshe** [syncfusion/flutter-widgets#1565]
The gradle build script for `syncfusion_flutter_pdfviewer` is not compatible with gradle 8.X
Other packages that require gradle 8.X (e.g. `flutter_stripe`) are now incompatible with this package.
```
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.5/userguide/upgrading_version_6.html#jcenter_deprecation
        at build_bo9dkyfxcrx7s70qnwg3z7u8d$_run_closure1$_closure2.doCall(C:\Users\Moshe Dicker\AppData\Local\Pub\Cache\hosted\pub.dev\syncfusion_flutter_pdfviewer-23.2.7\android\build.gradle:7)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

**Comment by ramkumarsync** [comment]
We have made this change on our end to support gradle 8.x and the fix is available from version [24.1.41](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.1.41). Please update the syncfusion_flutter_pdfviewer package to the latest version to resolve this issue.
