### ISSUE TITLE
Reset pagination when sorting or filtering

### ISSUE THREAD

**Issue by deniscass** [syncfusion/flutter-widgets#1568]
Hi Guys, 
I need reset pagination and go to first page when click in a sort column. 
Today i get wrong aproach and sorting still in current page and get user confused and need click in pagination to get correct first values. 
How i can improove usabilty in this feature?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @deniscass,

To address your requirements, you can implement a workaround using the [DataPagerController.selectedPageIndex](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataPagerController/selectedPageIndex.html) property. By programmatically resetting the current page index to the initial page whenever sorting or filtering occurs, you can achieve the desired behavior. This can be done within the SfDataGrid.onCellTap callback for sorting and the SfDataGrid.onFilterChanged callback for filtering.

We have provided a basic sample demonstrating this workaround for your reference. Please review it for further details.

<details>
<summary>Code Snippet</summary>

```dart
DataPagerController pagerController = DataPagerController();

…

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('PageNavigation Demo'),
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          return Column(
            children: [
              SizedBox(
                  height: constraints.maxHeight - 60,
                  width: constraints.maxWidth,
                  child: SfDataGrid(
                      rowsPerPage: rowsPerPage,
                      allowSorting: true,
                      allowFiltering: true,
                      source: _employeeDataSource,
                      columnWidthMode: ColumnWidthMode.fill,
                      onCellTap: (details) {
                        if (details.rowColumnIndex.rowIndex == 0) {
                          // To change the page index to 0 when the header cell is tapped.
                          // This will change the page index to 0 after sorting.
                          SchedulerBinding.instance
                              .addPostFrameCallback((timeStamp) {
                            if (pagerController.selectedPageIndex != 0) {
                              pagerController.selectedPageIndex = 0;
                            }
                          });
                        }
                      },
                      onFilterChanged: (details) {
                        setState(() {
                          _updatePageCount();
                        });
                        // To change the page index to 0 when the filter is applied.
                        if (pagerController.selectedPageIndex != 0) {
                          pagerController.selectedPageIndex = 0;
                        }
                      },
                      columns: getColumns)),
              SizedBox(
                height: 60,
                width: constraints.maxWidth,
                child: SfDataPager(
                  controller: pagerController,
                  pageCount: pageCount,
                  delegate: _employeeDataSource,
                ),
              )
            ],
          );
        },
      ),
    );
  }

```
</details>

<details>
<summary>Output</summary>

https://github.com/syncfusion/flutter-widgets/assets/93904422/b1301302-fd0b-4506-9e9d-31355eab4047


</details>

**Sample Link: [Flutter-DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/14266875/Sample.zip)**

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @deniscass,

We suspect that the reported issue has been resolved at your end with the provided workaround. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
