### ISSUE TITLE
is it possible to only have first and last index of primaryXAxis?

### ISSUE THREAD

**Issue by mahdiqdi** [syncfusion/flutter-widgets#1569]
i have a chart that i display dateTime in xAxis
but i want only first dateTime and last dateTime 
i tried to use interval and desiredInterval but i couldn't do that.the chart will change by user selection.(it is pnl chart)
![IMG_20231210_121947_711](https://github.com/syncfusion/flutter-widgets/assets/67858014/c8cc230a-d575-4569-9a70-39b17654e7d4)
this is what i want
can anyone help me?

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query and achieved your requirement by using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). We have rendered only the first and last axis labels using this [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, which is invoked while rendering each axis label in the chart. We have attached a code snippet, user guide documentation, sample, and screenshot for your reference. You can modify the sample according to your needs. Please let us know if you need any further assistance.



UG,

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter


``` dart
primaryXAxis: DateTimeCategoryAxis(
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              String text = details.value ==
                      0
                  ? '${_chartData[0].x}'
                  : details.value ==
                          _chartData.length - 1
                      ? '${_chartData[_chartData.length - 1].x}'
                      : "";
              return ChartAxisLabel(text, details.textStyle);
            },
          ),
```

Screenshot:
 
![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/aa58d029-c1ee-41df-9b74-8779789ad80d)

Regards,
Lokesh P.

**Comment by mahdiqdi** [comment]
thanks mr lokesh.you are perfect man.
i really appreciate you

**Comment by mahdiqdi** [comment]
@LokeshPalani 
hi there
i used your suggestion
but now i encounter new issue
when i have few indexes it's ok
but when i have for example 40 indexes it just shows first dateTime but the last dateTime does not show

**Comment by LokeshPalani** [comment]
Hi,



We have achieved your requirement using the [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) callback in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). By using this callback, you can get the minimum and maximum visible range for the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html). We have created a sample that displaying the first index in the x axis label by checking the visible minimum using the [ceil](https://api.flutter.dev/flutter/dart-core/num/ceil.html) function. Additionally, we have displayed the last index in the axis label by checking the visible maximum using the [floor](https://api.flutter.dev/flutter/dart-core/num/floor.html) function.



For your convenience, we have provided a code snippet, sample, and user guide documentation link. Please inform us if you have any additional requirements.



UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onactualrangechanged

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter



Code Snippet:

``` dart
 body: SfCartesianChart(
          onActualRangeChanged: (ActualRangeChangedArgs args) {
            if (args.orientation == AxisOrientation.horizontal) {
              _xMax = args.visibleMax;
              _xMin = args.visibleMin;
            }
          },
          primaryXAxis: DateTimeCategoryAxis(
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              String text = '';
              if (details.value == _xMin!.ceil()) {
                text = DateFormat.yMd().format(_chartData[0].x);
              } else if (details.value == _xMax!.floor()) {
                text = DateFormat.yMd()
                    .format(_chartData[_chartData.length - 1].x);
              }
              return ChartAxisLabel(text, details.textStyle);
            },
          ),
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/478e69f8-5978-444b-9fdb-5ba665d9a874)


Regards,
Lokesh P.

[chart_530565_show_first_and_last_label.zip](https://github.com/syncfusion/flutter-widgets/files/13723717/chart_530565_show_first_and_last_label.zip)

**Comment by mahdiqdi** [comment]
thanks mr @LokeshPalani 
i really appreciate you
