### ISSUE TITLE
Line chart renders weirdly

### ISSUE THREAD

**Issue by BenevidesLecontes** [syncfusion/flutter-widgets#157]
Hi thanks for all the work. I'm struggling to make the line chart to work correctly, I have a set of data and is being rendered weirdly as in the image.
![Simulator Screen Shot - iPhone 12 Pro - 2021-03-15 at 10 57 00](https://user-images.githubusercontent.com/1839361/111172195-61ec8580-8584-11eb-83f5-a531ac5788cc.png)

More info, you can clone this repo [https://github.com/BenevidesLecontes/chart-issue](url)

**Comment by Dharanipalani** [comment]
Hi @BenevidesLecontes,

Thanks for the interest in our Flutter charts. We have analyzed ou scenario and it is working as per correct behavior. From your given data we can see that the last six data are given in disorder format. The date-time interval is calculated correctly and the spline is rendered properly until reaching the last six data in the list. You are giving the old value than the current value so, it renders from that given value. current data is (2021-03-12, 17:54) and next give data is (2021-03- 12, 10:48). So, it renders from that point. Please revert us if you have any further queries.

Thanks,
Dharanitharan. P

**Comment by BenevidesLecontes** [comment]
Hi @Dharanipalani thank you for the answer, I did not catch this problem. One more question, how can I show markers only on serie selection?

**Comment by Dharanipalani** [comment]
Hi @BenevidesLecontes,

Yes, you can show the marker only for the selected series, using the **onSelectionChanged** and **onMarkerRender** callbacks. We have attached the sample here, please make use of it. Here we get the selected series index from the **onSelectionChanged** callback and calling the setstate to rebuild the chart, while rebuilding based on the selected series index we set marker width and height properties on the **onMarkerRender** callback. Thus, we can display the markers only for the selected series, please revert us if you need any further assistance.

Sample: [G157-marker_on_selected_series.zip](https://github.com/syncfusion/flutter-widgets/files/6161771/G157-marker_on_selected_series.zip)


Thanks,
Dharanitharan. P
