### ISSUE TITLE
Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.

### ISSUE THREAD

**Issue by hossam20520** [syncfusion/flutter-widgets#1570]
syncfusion_flutter_sliders: ^23.2.7
flutter  sdk: '>=3.1.3 <4.0.0'

syncfusion_flutter_sliders-23.2.7/lib/src/slider_base.dart:540:21: Error: The getter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/System/flutter/flutter_3/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'textScaler'.
      ? textPainter.textScaler.scale(actualLabelSize.height) +

Error: The setter 'textScaler' isn't defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart' ('/C:/System/flutter/flutter_3/flutter/packages/flutter/lib/src/painting/text_painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'textScaler'.
      ..textScaler = _mediaQueryData.textScaler;
        ^^^^^^^^^^

**Comment by Ibrahim12699** [comment]
update flutter version and will be fixed

**Comment by LokeshPalani** [comment]
Hi,



We would like to inform you that the textScaleFactor property has been deprecated and replaced with the textScaler property in Flutter 3.16.0. Our packages are now compatible with version 3.16 of Flutter. To resolve the issue you mentioned regarding "The getter 'textScaler' isn't defined for the 'MediaQueryData'", we suggest upgrading to the latest version of the Flutter SDK.



If you prefer to avoid upgrading to the latest Flutter SDK version, please let us know the current SDK version you are using. We will then suggest a compatible version of our charts package for that specific SDK version.



Regards,
Lokesh P.

**Comment by jctaoo** [comment]
> Hi,
> 
> We would like to inform you that the textScaleFactor property has been deprecated and replaced with the textScaler property in Flutter 3.16.0. Our packages are now compatible with version 3.16 of Flutter. To resolve the issue you mentioned regarding "The getter 'textScaler' isn't defined for the 'MediaQueryData'", we suggest upgrading to the latest version of the Flutter SDK.
> 
> If you prefer to avoid upgrading to the latest Flutter SDK version, please let us know the current SDK version you are using. We will then suggest a compatible version of our charts package for that specific SDK version.
> 
> Regards, Lokesh P.

I use flutter 3.13.9 because flutter 3.16 is not work as expected on macos in my project.

**Comment by LokeshPalani** [comment]
Hi,



We would like to inform you that you can use our Syncfusion_flutter_sliders package version 22.2.12. It is compatible with flutter SDK version 3.13.9.



Version link,

https://pub.dev/packages/syncfusion_flutter_sliders/versions/22.2.12



Regards,
Lokesh P.

**Comment by Devbrail** [comment]
> Hi,
> 
> We would like to inform you that you can use our Syncfusion_flutter_sliders package version 22.2.12. It is compatible with flutter SDK version 3.13.9.
> 
> Version link,
> 
> https://pub.dev/packages/syncfusion_flutter_sliders/versions/22.2.12
> 
> Regards, Lokesh P.

Worked Thanks
