### ISSUE TITLE
Change (SfCartesianChart) Line chart color on cross of y-axis threshold value

### ISSUE THREAD

**Issue by gh-yatinIshwarlalDeokar** [syncfusion/flutter-widgets#1571]
I am currently working on a (**SfCartesianChart**) line chart where the y-axis ranges from 0 to 160, and a specific threshold value is set at 120. My objective is to dynamically change the color of the line in the chart; if it crosses the threshold value of 120, the line should appear in red, and if it is below 120, the line should be displayed in blue. This functionality aims to provide a visual representation of when the line surpasses or falls below the specified threshold. refer below image

![image](https://github.com/syncfusion/flutter-widgets/assets/144206273/b2c4dc73-804a-4174-a135-7e837d8d6730)

I have tried _CustomLineSeriesRenderer but it change the color from point to point and also when I zoom in/zoom out color flicker and change to different one. I want anywhere it cross the threshold it should change color. 
Using following code: 

`class _CustomLineSeriesRenderer extends LineSeriesRenderer {
    _CustomLineSeriesRenderer(this.series);

    final LineSeries < dynamic, dynamic > series;
    static Random randomNumber = Random();

    @override
    LineSegment createSegment() {
        return _LineCustomPainter(randomNumber.nextInt(4), series);
    }
}

class _LineCustomPainter extends LineSegment {
    _LineCustomPainter(int value, this.series) {
        //ignore: prefer_initializing_formals
        index = value;
        _xValues = < num > [];
        _yValues = < num > [];
    }
final LineSeries < dynamic, dynamic > series;
    late double maximum, minimum;
    late int index;
    List < Color > colors = < Color > [
        Colors.blue,
        Colors.yellow,
        Colors.orange,
        Colors.purple,
        Colors.cyan
    ];
@override
    Paint getStrokePaint() {

        double yVal = series.dataSource[index].y;
        print("${yVal} ---------------index");
        final Paint customerStrokePaint = Paint();
        customerStrokePaint.color = yVal > 2.5 ? Colors.redAccent : Colors.green;
        customerStrokePaint.strokeWidth = 7;
        customerStrokePaint.style = PaintingStyle.stroke;
        return customerStrokePaint;
    }

    void _storeValues() {
        _xPointValues.add(points[0].dx);
        _xPointValues.add(points[1].dx);
        _yPointValues.add(points[0].dy);
        _yPointValues.add(points[1].dy);
        _xValues.add(points[0].dx);
        _xValues.add(points[1].dx);
        _yValues.add(points[0].dy);
        _yValues.add(points[1].dy);
    }

    @override
    void onPaint(Canvas canvas) {
        final double x1 = points[0].dx,
            y1 = points[0].dy,
            x2 = points[1].dx,
            y2 = points[1].dy;
        _storeValues();
        final Path path = Path();
        print("$x1 ---x1");
        print("$y1 ---y1");
        print("$x2 ---x2");
        print("$y2 ---y2");
        path.moveTo(x1, y1);
        path.lineTo(x2, y2);

        Paint paint = getStrokePaint();

        if (y1 > 100 || y2 > 100) {
            paint.color = Colors.red;
        } else {
            paint.color = Colors.green;
        }

        canvas.drawPath(path, paint);

        if (currentSegmentIndex == series.dataSource.length - 2) {
            const double labelPadding = 10;
            final Paint topLinePaint = Paint()
                ..color = Colors.black
                ..style = PaintingStyle.stroke
                ..strokeWidth = 2;

            final Paint bottomLinePaint = Paint()
                ..color = Colors.red
                ..style = PaintingStyle.stroke
                ..strokeWidth = 2;
            maximum = _yPointValues.reduce(max);
            minimum = _yPointValues.reduce(min);
            final Path bottomLinePath = Path();
            final Path topLinePath = Path();
            bottomLinePath.moveTo(_xPointValues[0], maximum);
            bottomLinePath.lineTo(_xPointValues[_xPointValues.length - 1], maximum);

            topLinePath.moveTo(_xPointValues[0], minimum);
            topLinePath.lineTo(_xPointValues[_xPointValues.length - 1], minimum);
            canvas.drawPath(
                _dashPath(
                    bottomLinePath,
                    dashArray: _CircularIntervalList < double > ( < double > [15, 3, 3, 3]),
                ) !,
                bottomLinePaint);

            canvas.drawPath(
                _dashPath(
                    topLinePath,
                    dashArray: _CircularIntervalList < double > ( < double > [15, 3, 3, 3]),
                ) !,
                topLinePaint);

            final TextSpan span = TextSpan(
                style: TextStyle(
                    color: Colors.red[800], fontSize: 12.0, fontFamily: 'Roboto'),
                text: 'Low point',
            );
            final TextPainter tp =
                TextPainter(text: span, textDirection: prefix0.TextDirection.ltr);
            tp.layout();
            tp.paint(
                canvas,
                Offset(
                    _xPointValues[_xPointValues.length - 4], maximum + labelPadding));
            final TextSpan span1 = TextSpan(
                style: TextStyle(
                    color: Colors.green[800], fontSize: 12.0, fontFamily: 'Roboto'),
                text: 'High point',
            );
            final TextPainter tp1 =
                TextPainter(text: span1, textDirection: prefix0.TextDirection.ltr);
            tp1.layout();
            tp1.paint(
                canvas,
                Offset(_xPointValues[0] + labelPadding / 2,
                    minimum - labelPadding - tp1.size.height));
            _yValues.clear();
            _yPointValues.clear();
        }
    }
}`

**Comment by LokeshPalani** [comment]
Hi,



We have validated your query and attached a screenshot. You can achieve your requirement by using the [pointColorMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/pointColorMapper.html) in the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html). By using this, you can return the specific color by adding a condition that compares the y value in the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataSource.html). We have shared a code snippet, screenshot, and sample for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.



Code snippet:

```
 LineSeries<ChartSampleData, DateTime>(
              dataSource: _chartData,
              width: 5,
              pointColorMapper: (ChartSampleData sales, _) => sales.y <= 50
                  ? Colors.red
                  : sales.y <= 75
                      ? Colors.orange
                      : Colors.green,
              xValueMapper: (ChartSampleData sales, _) => sales.x,
              yValueMapper: (ChartSampleData sales, _) => sales.y,
              markerSettings:  MarkerSettings(
                isVisible: true,
                color: Colors.blue.shade900,
              ),
            ),
```

ScreenShot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/39f75aa1-c301-409e-9077-62e521f62eed)


Regards,
Lokesh P.
