### ISSUE TITLE
remove at and remove function is not working plz check it 

### ISSUE THREAD

**Issue by ammarghias** [syncfusion/flutter-widgets#1572]
remove at and remove function is not working plz check it 
syncfusion_flutter_pdf: ^23.2.7
#1278 
#syncfusion_flutter_pdf

**Comment by irfanajaffer** [comment]
The fix for the reported issue is included in our weekly release v24.1.44.

Kindly use the following link to refer to our latest release version,
https://pub.dev/packages/syncfusion_flutter_pdf/versions
