### ISSUE TITLE
Flutter web syncfusion pdfviewer getting scale during continuous page layout

### ISSUE THREAD

**Issue by JayronKhong** [syncfusion/flutter-widgets#1574]
Hi, I was facing the issue with flutter web syncfusion pdfviewer with Pagelayout = continuous, the pdf was getting scale.

Current issue in web:
[https://drive.google.com/file/d/1yspOuIbdKT8UL3ZCpIkgvOlyWadpzR3M/view?usp=share_link](url)

Expected: Same like mobile
[https://drive.google.com/file/d/1qeoMRSFZUmVRT535Kx36HRt5ZkMyHkcl/view?usp=share_link](url)

Thanks!

**Comment by ramkumarsync** [comment]
In Desktop (Windows and Web) platforms, it is our default behavior that the PDF pages are rendered with width fitted. So the multiple pages will not be displayed on the Web or Windows platforms on the continuous page layout with horizontal scroll direction.
