### ISSUE TITLE
How to implement nested range selectors?

### ISSUE THREAD

**Issue by ddxl123** [syncfusion/flutter-widgets#1576]
As shown in the figure:
![无标题](https://github.com/syncfusion/flutter-widgets/assets/33950845/ae7a2e3f-3b6a-4a45-ae78-38b96bb40999)

**Comment by LokeshPalani** [comment]
Hi,



We would like to inform you that there is currently no support in [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/SfSlider.html) for displaying color within a specified range. The color will render from the minimum value to the maximum value, as this is the behavior of [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/SfSlider.html).



However, we have achieved your requirement in the [SfLinearGauge](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfLinearGauge-class.html). By using this, you can display the [Icon](https://api.flutter.dev/flutter/widgets/Icon-class.html) using [markerPointers](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfLinearGauge/markerPointers.html) on the [ranges](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfLinearGauge/ranges.html) using [LinearElementPosition.cross](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/LinearElementPosition.html#cross) in the [position](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/LinearGaugeRange/position.html) property. Additionally, you can display the specific color using the [ranges](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfLinearGauge/ranges.html) property in the [SfLinearGauge](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/SfLinearGauge-class.html). We have shared a code snippet, screenshot, user guide documentation, sample browser link and sample for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.



**UG Link,**

https://help.syncfusion.com/flutter/linear-gauge/range

https://help.syncfusion.com/flutter/linear-gauge/widget-marker-pointer



**SB Link,**

https://flutter.syncfusion.com/#/linear-gauge/showcase/sleep-watch-score


**Code snippet:**

``` dart
SfLinearGauge(
          minimum: 0.0,
          maximum: 100.0,
          animateRange: false,
          showLabels: false,
          showTicks: false,
          minorTicksPerInterval: 0,
          axisTrackStyle: LinearAxisTrackStyle(
            thickness: 4,
            color: Colors.grey[350],
          ),
          markerPointers: const <LinearMarkerPointer>[
            LinearWidgetPointer(
              value: 20,
              enableAnimation: false,
              position: LinearElementPosition.cross,
              child: Icon(
                Icons.circle,
                color: Colors.red,
              ),
            ),
          ],
          ranges: const <LinearGaugeRange>[
            LinearGaugeRange(
              startValue: 20.0,
              endValue: 40,
              startWidth: 8,
              position: LinearElementPosition.cross,
              midWidth: 8,
              endWidth: 8,
              color: Colors.red,
            ),
          ],
        )
```

**ScreenShot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/28079657-7abe-4292-a9a4-f50a802f1190)


Regards,
Lokesh P.
