### ISSUE TITLE
[syncfusion_flutter_datagrid] Is there a way to use a custom singleChildController or provide a custom position for scrollTo and animateTo methods??

### ISSUE THREAD

**Issue by Retr0sec7** [syncfusion/flutter-widgets#1578]
I'm having issues with `SfDataGrid` scroll controller. My grid add rows to the table programmatically, after the add operation is done, I call the scroll controller that this package provides for managing grid scroll programmatically:

```
   void scrollDataGrid(double rowIndex) { // rowIndex is arrayWithData.length -1
    state.dataGridController.scrollToRow(rowIndex, canAnimate: true); // using the agument position with DataGridScrollPosition.end just bugs the scroll and makes it not work
  }
```

The issue is that this scroll does not reaches to the end even if the rowIndex value is accurate, this call positions the scroller like 1 or 2 rows before the latest added row, which causes manual interaction to be required to be able to scroll and see the latest added row.

Also,  when  the scroller is positioned in the at the end if a new row is added it will trigger an animation that starts scrolling from center of scroller to ALMOST the end (due the issue described above), which causes a bad UX.

I have implemented what I want in a flutter `DataTable` wrapped in `SingleChildScrollView`, the latter has a controller on which a custom position can be passed:

```
    final position = scrollController.position.maxScrollExtent + 50; // I was having the same issue about the scroller not being able to fully scroll to end to show the latest row, but doing +50 here made the trick.
    scrollController.animateTo(
      position,
      duration: const Duration(milliseconds: 500),
      curve: Curves.easeInOut,
    );
```

I tried wrapping `SfDataGrid` in `SingleChildScrollView` but it just bugs the table and makes the grid shorter. There should be a way to provide your own custom position value like this. Does anyone know a workaround for this? 
Thanks.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Retr0sec7,

The SfDataGrid provides support for scrolling to specific rows using the [DataGridController.scrollToRow](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridController/scrollToRow.html) method. We have thoroughly tested this functionality on our end using a basic sample.

During our testing, we observed that the DataGrid properly scrolled to the newly added end row without encountering any issues similar to what you described. 

For your reference, we have attached the sample that we used for testing. In this sample, we added a new row to the DataGrid and consecutively scrolled to the added row through a button click.

Please review the attached sample on your end for further investigation. 

<details>
<summary>Code snippet</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: Column(
        children: [
          Container(
            padding: const EdgeInsets.symmetric(vertical: 10),
            height: 60,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton(
                  onPressed: () {
                    Employee newEmployee =
                        Employee(uniqueId, 'Peter Citeaux', 'Developer', 20000);
                    _employeeDataSource.datagridRows.add(DataGridRow(cells: [
                      DataGridCell<int>(
                          columnName: 'ID', value: newEmployee.id),
                      DataGridCell<String>(
                          columnName: 'Name', value: newEmployee.name),
                      DataGridCell<String>(
                          columnName: 'Designation',
                          value: newEmployee.designation),
                      DataGridCell<int>(
                          columnName: 'Salary', value: newEmployee.salary),
                    ]));

                    _employeeDataSource.updateDataGridSource();

                    dataGridController
                        .scrollToRow(_employeeDataSource.rows.length - 1);

                    uniqueId++;
                  },
                  child: const Text('Add New Row'),
                ),
                const SizedBox(width: 20),
                ElevatedButton(
                  onPressed: () {
                    dataGridController
                        .scrollToRow(_employeeDataSource.rows.length - 1);
                  },
                  child: const Text('Scroll to End'),
                ),
              ],
            ),
          ),
          Expanded(
            child: SfDataGrid(
              controller: dataGridController,
              source: _employeeDataSource,
              columns: getColumns,
              columnWidthMode: ColumnWidthMode.fill,
            ),
          ),
        ],
      ),
    );
  }

```
</details>

<details>
<summary>Output Video</summary>

https://github.com/syncfusion/flutter-widgets/assets/93904422/739cfb70-198c-4268-92be-6e8bdf4dd08c



</details>

### Sample Link: [Flutter-DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/14222022/Sample.zip)


Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Retr0sec7,

We suspect that the reported issue has been resolved at your end. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
