### ISSUE TITLE
How to have secondary Y-Axis only visible when a Series using it is visible

### ISSUE THREAD

**Issue by zambetpentru** [syncfusion/flutter-widgets#1579]
Hi,

I found that when I make a Series invisible the Secondary Y axis gets messed up, have you any suggestions?

When both series are visible all look great:
![image](https://github.com/syncfusion/flutter-widgets/assets/81489824/de30a21e-a960-4c50-99d1-c470671e428a)

When I hide one Series by clicking on the legend:
![image](https://github.com/syncfusion/flutter-widgets/assets/81489824/8bb9eccd-ae5b-44cc-9b3d-677fac97df86)

The demo here has a fixed secondary Y-axis so it doesn't cause the same problem:
https://flutter.syncfusion.com/#/cartesian-charts/axis-features/multiple-axis-chart

**Comment by zambetpentru** [comment]
And ideally how to only have the secondary axis show if there is a visible series attached to it?

**Comment by LokeshPalani** [comment]
HI,


We have achieved your requirement by using the [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/maximum.html) property in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). By default, the axis range will render based on the data points given in the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataSource.html). By using the [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/maximum.html) property, you can set the range for the secondary y-axis. So, when the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html) is toggled, the default range will not be calculated for the secondary y-axis. We have shared a sample, code snippet, screenshot, and user guide documentation link for your reference. Please let us know if you need any further assistance.



UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range



``` dart
Code Snippet:

   axes: [
          NumericAxis(
            name: 'yAxis',
            opposedPosition: true,
            maximum: 250,
          )
        ],

           LineSeries<ChartSampleData, String>(
            dataSource: _chartData,
            xValueMapper: (ChartSampleData sales, _) => sales.year,
            yValueMapper: (ChartSampleData sales, _) => sales.sales2,
            yAxisName: 'yAxis',
          ),

```

Screenshot:


![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/17a03915-2615-4f83-ab54-59db5c1d764f)


Regards,
Lokesh P.

[chart_532280.zip](https://github.com/syncfusion/flutter-widgets/files/13711632/chart_532280.zip)
