### ISSUE TITLE
Chart shits to right side after it reloads

### ISSUE THREAD

**Issue by utsav-savani** [syncfusion/flutter-widgets#158]
The SfCartesianChart's x-axis is being shifted to right side as soon as it reloads please provide a solution as soon as possible.

Graph before reloading,
![Screenshot 2021-03-16 at 11 36 59 AM](https://user-images.githubusercontent.com/11181921/111263459-ee15b000-864b-11eb-8059-8b7e343c76e4.png)

Graph after reloading,
![Screenshot 2021-03-16 at 11 37 32 AM](https://user-images.githubusercontent.com/11181921/111263513-01288000-864c-11eb-91b0-5cdaa91c92f1.png)

**Comment by Dharanipalani** [comment]
Hi @utsav-savani,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and we not able to replicate the reported issue at our end.  While reloading, the chart doesn't produce this issue. Please share more details and revert us with the replicated scenario in the attached sample will help us to identify and solve your problem quicker.

Sample:  [I319517-chart-reload-issue.zip](https://github.com/syncfusion/flutter-widgets/files/6154973/I319517-chart-reload-issue.zip)


Thanks,
Dharanitharan. P

**Comment by buzzware** [comment]
misspelled subject

> We have analyzed your scenario and we not able to replicate the reported issue at our end.

:)
