### ISSUE TITLE
Change month language in SplineArea

### ISSUE THREAD

**Issue by LorenzoCutrupi** [syncfusion/flutter-widgets#1582]
I have created a classical Spline Chart:

```
series: <ChartSeries<StatsRow, DateTime>>[
    SplineAreaSeries<StatsRow, DateTime>(
      markerSettings: const MarkerSettings(
        isVisible: true,
        shape: DataMarkerType.circle,
        borderWidth: 1,
        borderColor: AppColor.details,
        color: AppColor.details,
      ),
      dataSource: statsRows,
      xValueMapper: (StatsRow stats, _) => stats.date,
      yValueMapper: (StatsRow stats, _) {
        switch (yValueColumnName) {
          return stats.weight;
      },
      name: name,
      gradient: LinearGradient(
        colors: [
          AppColor.details.withOpacity(0.7),
          AppColor.red.withOpacity(0.7),
        ],
        stops: [0.0, 1.0],
      ),
      borderColor: AppColor.details,
      borderWidth: 3,
    ),
  ]
```

and it shows this type of chart:
![image](https://github.com/syncfusion/flutter-widgets/assets/80067619/627372f6-6a60-4e20-a7ac-7301aecee7df)

How can I change the language of the months shown in the x bar and when I select a point? In particular, I want it to be in italian

**Comment by LokeshPalani** [comment]
Hi,

We have achieved your requirement by using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). By using this, you can customize the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html) and [textStyle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/textStyle.html) of each axis label in the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html). In the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, we have changed the month names by checking the tapped point index and returned the stored _monthNames in the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html). 

We have prepared a sample by using the [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/onPointTap.html) callback in the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html). In that, you can get the tapped point index. We have shared a code snippet, sample, screenshot, and user guide documentation link for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.

**UG Link,**
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter 
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onpointtap

**Code Snippet:**

``` dart
final List<String> _monthNames = [
    "Gennaio",
    "Febbraio",
    "Marzo",
    "Aprile",
    "Maggio",
    "Giugno",
    "Luglio",
    "Agosto",
    "Settembre",
    "Ottobre",
    "Novembre",
    "Dicembre"
  ];


     primaryXAxis: DateTimeCategoryAxis(
          labelPlacement: LabelPlacement.onTicks,
          majorTickLines: const MajorTickLines(width: 0),
          interval: 1,
          dateFormat: DateFormat('MMMM'),

 // Determines to change the month name using point index when user tapped.
          axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
            if (_isTapped &&
                _pointIndex != null &&
                axisLabelRenderArgs.text ==
                    DateFormat('MMMM').format(_chartData[_pointIndex!].x!)) {
              return ChartAxisLabel(
                _monthNames[_pointIndex!],
                textStyle,
              );
            } else {
              return ChartAxisLabel(
                axisLabelRenderArgs.text,
                axisLabelRenderArgs.textStyle,
              );
            }
          },
        )

 SplineAreaSeries<ChartSampleData, DateTime>(
            onPointTap: (ChartPointDetails pointInteractionDetails) {
              if (pointInteractionDetails.pointIndex != null) {
                setState(
                  () {
                    _isTapped =
                        _pointIndex != pointInteractionDetails.pointIndex
                            ? true
                            : false;
                    _pointIndex = pointInteractionDetails.pointIndex;
                  },
                );
              }
            },
          ),
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/af2d9642-4eb1-4c2f-b010-f1d4922f646e)

Regards,
Lokesh P.

[chart_533108_tapped_axis_label.zip](https://github.com/syncfusion/flutter-widgets/files/13723817/chart_533108_tapped_axis_label.zip)

**Comment by LorenzoCutrupi** [comment]
> Hi,
> 
> We have achieved your requirement by using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in the [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). By using this, you can customize the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html) and [textStyle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/textStyle.html) of each axis label in the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html). In the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, we have changed the month names by checking the tapped point index and returned the stored _monthNames in the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html).
> 
> We have prepared a sample by using the [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/onPointTap.html) callback in the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html). In that, you can get the tapped point index. We have shared a code snippet, sample, screenshot, and user guide documentation link for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.
> 
> **UG Link,** https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onpointtap
> 
> **Code Snippet:**
> 
> ```dart
> final List<String> _monthNames = [
>     "Gennaio",
>     "Febbraio",
>     "Marzo",
>     "Aprile",
>     "Maggio",
>     "Giugno",
>     "Luglio",
>     "Agosto",
>     "Settembre",
>     "Ottobre",
>     "Novembre",
>     "Dicembre"
>   ];
> 
> 
>      primaryXAxis: DateTimeCategoryAxis(
>           labelPlacement: LabelPlacement.onTicks,
>           majorTickLines: const MajorTickLines(width: 0),
>           interval: 1,
>           dateFormat: DateFormat('MMMM'),
> 
>  // Determines to change the month name using point index when user tapped.
>           axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
>             if (_isTapped &&
>                 _pointIndex != null &&
>                 axisLabelRenderArgs.text ==
>                     DateFormat('MMMM').format(_chartData[_pointIndex!].x!)) {
>               return ChartAxisLabel(
>                 _monthNames[_pointIndex!],
>                 textStyle,
>               );
>             } else {
>               return ChartAxisLabel(
>                 axisLabelRenderArgs.text,
>                 axisLabelRenderArgs.textStyle,
>               );
>             }
>           },
>         )
> 
>  SplineAreaSeries<ChartSampleData, DateTime>(
>             onPointTap: (ChartPointDetails pointInteractionDetails) {
>               if (pointInteractionDetails.pointIndex != null) {
>                 setState(
>                   () {
>                     _isTapped =
>                         _pointIndex != pointInteractionDetails.pointIndex
>                             ? true
>                             : false;
>                     _pointIndex = pointInteractionDetails.pointIndex;
>                   },
>                 );
>               }
>             },
>           ),
> ```
> 
> **Screenshot:**
> 
> ![image](https://private-user-images.githubusercontent.com/105289202/291799735-af2d9642-4eb1-4c2f-b010-f1d4922f646e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MzU3MzUsIm5iZiI6MTcwMzYzNTQzNSwicGF0aCI6Ii8xMDUyODkyMDIvMjkxNzk5NzM1LWFmMmQ5NjQyLTRlYjEtNGMyZi1iMDEwLWYxZDQ5MjJmNjQ2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwMDAzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTY4ZDg0YjQ1YzcwN2MxNjQ5MWI3Yzg1ZWIwMWUzZmRiZjkwNTU2NTc5MDBhMjhmMWY5OGMwYzQzMGFlNzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kKsdW3X44oV2sDZWud1coOIwW1uX27ndiS_LWzaRsa4)
> 
> Regards, Lokesh P.
> 
> [chart_533108_tapped_axis_label.zip](https://github.com/syncfusion/flutter-widgets/files/13723817/chart_533108_tapped_axis_label.zip)

Your solution seems near to what I want to achieve but not identical. What if I want to simply show all the months name from my list instead of only the one tapped? I don't need any fancier addition, just a different list

**Comment by LokeshPalani** [comment]
Hi @LorenzoCutrupi,



As mentioned in our previous update, you can achieve your requirement by using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in the [DatatimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html). By using this callback, you can customize the [text](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/text.html) and [textStyle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel/textStyle.html) of each axis label in the [chartAxisLabel](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxisLabel-class.html). In the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback, we have formatted the labels by retrieving month names from given list ‘_monthName’ based on the index provided in ‘axisLabelRenderArgs.value’, which represents the numerical value of the label on the X-axis. We have shared the user guide documentation, code snippet and sample below for reference and modified the previously shared sample, you can modify the sample based on your needs.



**UG Link:**

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter

**Code Snippet:**

``` dart
 final List<String> _monthNames= [
    "Gennaio",
    "Febbraio",
    "Marzo",
    "Aprile",
    "Maggio",
    "Giugno",
    "Luglio",
    "Agosto",
    "Settembre",
    "Ottobre",
    "Novembre",
    "Dicembre"
  ];

 

  TextStyle textStyle = const TextStyle(
    color: Colors.indigoAccent,
    fontSize: 14,
    fontWeight: FontWeight.bold,
  );

 

  @override
  void initState() {
    _chartData = [
      ChartSampleData(x: DateTime(2023, 01, 01), y: 10),
      ChartSampleData(x: DateTime(2023, 02, 24), y: 06),
      ChartSampleData(x: DateTime(2023, 03, 28), y: 16),
      ChartSampleData(x: DateTime(2023, 04, 05), y: 23),
      ChartSampleData(x: DateTime(2023, 05, 13), y: 12),
      ChartSampleData(x: DateTime(2023, 06, 19), y: 09),
      ChartSampleData(x: DateTime(2023, 07, 22), y: 17),
      ChartSampleData(x: DateTime(2023, 08, 13), y: 21),
      ChartSampleData(x: DateTime(2023, 09, 24), y: 16),
      ChartSampleData(x: DateTime(2023, 10, 14), y: 06),
      ChartSampleData(x: DateTime(2023, 11, 03), y: 19),
      ChartSampleData(x: DateTime(2023, 12, 07), y: 13),
    ];
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCartesianChart(
        primaryXAxis: DateTimeCategoryAxis(
          labelPlacement: LabelPlacement.onTicks,
          majorTickLines: const MajorTickLines(width: 0),
          interval: 1,
          dateFormat: DateFormat('MMMM'),
          axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
            return ChartAxisLabel(
              _monthNames[axisLabelRenderArgs.value.toInt()],
              textStyle,
            );
          },
        ),
     ),
  ),
},
```

**Output Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/c6db48d6-f072-4a69-9aab-89c6e4e70403)

Regards,
Lokesh P.

[bd533108.zip](https://github.com/syncfusion/flutter-widgets/files/13783833/bd533108.zip)

**Comment by LorenzoCutrupi** [comment]
Hi @LokeshPalani,
sorry for replying this late again. I'm trying to implement a behavior similar to yours:

```
DateTimeCategoryAxis smallAxis(){
    return DateTimeCategoryAxis(
      labelPlacement: LabelPlacement.onTicks,
      majorTickLines: const MajorTickLines(width: 0),
      interval: 1,
      dateFormat: DateFormat.MMMd(),
      intervalType: DateTimeIntervalType.days,
      axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
        return ChartAxisLabel(
          italianMonthNames[axisLabelRenderArgs.value.toInt()],
          const TextStyle(
            fontFamily: 'Roboto',
            fontStyle: FontStyle.normal,
            fontWeight: FontWeight.normal,
            fontSize: 12),
        );
      },
    );
  }

DateTimeCategoryAxis bigAxis(){
  return DateTimeCategoryAxis(
    labelPlacement: LabelPlacement.onTicks,
    majorTickLines: const MajorTickLines(width: 0),
    interval: 1,
    axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
      return ChartAxisLabel(
        italianMonthNames[axisLabelRenderArgs.value.toInt()],
        const TextStyle(
            fontFamily: 'Roboto',
            fontStyle: FontStyle.normal,
            fontWeight: FontWeight.normal,
            fontSize: 12),
      );
    },
  );
}

return SfCartesianChart(
      primaryXAxis: progress.length > 5 ? bigAxis() : smallAxis(),
...
```

But I get this chart:
![image](https://github.com/syncfusion/flutter-widgets/assets/80067619/a06103e9-276f-4dae-98d7-d535d87fe40b)
Although it might seem correct, it's not, since the three measurements were:
![image](https://github.com/syncfusion/flutter-widgets/assets/80067619/e634e574-5d5a-46bb-9992-17d38c0ac748)
So, the measurements are inverted and don't follow the time constraints given by the list. For comparison, with the normal axis the chart looks like this:
![image](https://github.com/syncfusion/flutter-widgets/assets/80067619/a99dee73-f0a6-4f88-9fc2-7fd54a96dd06)

For the sake of completeness, this is the whol code of the chart:
```
return SfCartesianChart(
  primaryXAxis: progress.length > 5 ? DateTimeAxis() : DateTimeAxis(
    dateFormat: DateFormat.MMMd(), // Customize date format as needed
    intervalType: DateTimeIntervalType.days, // Set interval type to days
  ),
  primaryYAxis: NumericAxis(
    minimum: minYValue - difference,
    maximum: maxYValue + difference,
  ),
  trackballBehavior: TrackballBehavior(
    activationMode: ActivationMode.singleTap,
    lineColor: AppColor.details,
    enable: true,
    tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
  ),
  zoomPanBehavior: ZoomPanBehavior(
    enablePinching: true,
  ),
  series: <ChartSeries<Measurement, DateTime>>[
    SplineAreaSeries<Measurement, DateTime>(
      markerSettings: const MarkerSettings(
        isVisible: true,
        shape: DataMarkerType.circle,
        borderWidth: 1,
        borderColor: AppColor.details,
        color: AppColor.details,
      ),
      dataSource: progress,
      xValueMapper: (Measurement stats, _) => stats.date,
      yValueMapper: (Measurement stats, _) => stats.value,
      name: name,
      gradient: LinearGradient(
        colors: [
          AppColor.details.withOpacity(0.7),
          AppColor.red.withOpacity(0.7),
        ],
        stops: [0.0, 1.0],
      ),
      borderColor: AppColor.details,
      borderWidth: 3,
    ),
  ],
);
```
Using progress.reversed.toList() as dataSource solves the problem of having the dates reversed with smallAxis and bigAxis, but not the problem of the incorrect dates. How can I solve?
Sorry for the long text and thanks for the big help

**Comment by BPraveenBalu** [comment]
Hi,

We have validated the code snippet and shared images and the order of your data source is inversed. you can achieve the requirement with corresponding axis [isInversed](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/isInversed.html) property. we hope that this meets your expectations and is helpful to you. If not, we kindly request you to share more information on your requirement in detail along with simple data source, so that it will help us assist you in a better way.


Regards,
Praveen Balu.
