### ISSUE TITLE
The method 'clear' can't be unconditionally invoked because the receiver can be 'null'.

### ISSUE THREAD

**Issue by thisadee2897** [syncfusion/flutter-widgets#1583]
<img width="548" alt="Screenshot 2566-12-18 at 10 28 15" src="https://github.com/syncfusion/flutter-widgets/assets/69580511/3b687f9d-714a-4072-89b0-1e1e42ac1148">

**Comment by LavanyaGowtham2021** [comment]
Please share the requested details to proceed further on this.
