### ISSUE TITLE
[syncfusion_flutter_charts] Has the latest version breaking changes?

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#1586]
I have tried to update `syncfusion_flutter_charts` to latest version `24.1.41` from `23.2.7` and I noticed that `ChartPoint` class has no many properties which it has before (eg. `index`, `isVisible`). This class is used in `legend` property (class `Legend`) of `sfCircularChart` So my app has tons of error warnings. If is this breaking change why there is no any notice and migration guide?

**Comment by avocadohooman** [comment]
I received the same error messages:

`TooltipBehavior` didn't work anymore, scrolling horizontally didn't work anymore, `visibibleMinimum` & `visibleMaximum` got replaced by `initialVisibleMinimum` & `initialVisibleMaximum`, same as `isVisible` got replaced by `initialIsVisible`

**Comment by btrautmann** [comment]
I suspect that @avocadohooman is referring to this issue I've just opened when they mention horizontal scrolling: https://github.com/syncfusion/flutter-widgets/issues/1595

Please see the repo inside with reproduction. Thank you!

**Comment by avocadohooman** [comment]
Thanks @btrautmann, that's 100% the case :)

**Comment by avocadohooman** [comment]
@LavanyaGowtham2021 I can confirm that the update [24.1.44+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/24.1.44+1) fixed the issue with horizontal scrolling, similar to https://github.com/syncfusion/flutter-widgets/issues/1595 

Thanks for the great work!

**Comment by avocadohooman** [comment]
Actually, yes, the tooltip issues still persist when setting `shouldAlwaysShow: false`, if it is set to true the tooltip appears as nomalr.

**Comment by avocadohooman** [comment]
@PreethikaSelvam @LavanyaGowtham2021 
I can confirm that the tooltip works as intended. I overlooked the value I set for `duration`, which was set to `2`. All good from my end 👍

**Comment by bambinoua** [comment]
Hello @LavanyaGowtham2021 

I have this code:
![Без имени](https://github.com/syncfusion/flutter-widgets/assets/45417992/7e0cc74c-d6c1-49c1-b984-aae91bd59c46)

which is not working. How can I fix this? How can I get the `index` and `isVisible` properties of `ChartPoint`?
