### ISSUE TITLE
[DataGrid 18.4.48-beta] Grid drops frames on Android but works fine on iOS while scrolling horizontally

### ISSUE THREAD

**Issue by szymonmazanik** [syncfusion/flutter-widgets#159]
Hello,
My DataGrid is visibly dropping frames on Android but works perfectly fine on iPhone. As shown on the attached video: 

https://user-images.githubusercontent.com/25953768/111369448-5dfd5800-8697-11eb-8167-511a9b41437f.MOV

The first device is Samsung Galaxy Tab, second is Huawei P10 and last is iPhone 7
Most of the cells used in grid are WidgetCells. 
Apps on video are compiled to `release` version on both iOS and Android. 

My code is quite simple: 
```
SfDataGrid( 
          rowHeight: Dimensions.gridCellHeight,
          columnWidthMode: ColumnWidthMode.header,
          source: dataSource,
          frozenColumnsCount:  1,
          columns: _buildColumns(context),
          cellBuilder: _buildCell,
          gridLinesVisibility: GridLinesVisibility.both,
          headerGridLinesVisibility: GridLinesVisibility.both,
        ),
```
Is there a solution to that problem?

Thanks for help
Szymon

**Comment by RenugaSadagoban98** [comment]
Hi  @szymonmazanik , 
 
Greetings from syncfusion.

Based on the provided information, we could able to reproduce your reported issue. You can avoid the visibility dropping frames issue by setting the unique key for every widget which you are loading. In the below example, we are setting the unique key which is the collection of rowIndex and column name of the widget. You can refer to the following code snippet,
`  
@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(),
        body: SfDataGrid(
          source: orderInfoDataSource,
          columnWidthMode: ColumnWidthMode.header,
          frozenColumnsCount: 1,
          columns: _columns,
          cellBuilder: (context, gridColumn, index) {
            if (gridColumn.mappingName == 'orderID') {
              return Text(dataSource[index].orderID,
                  key: ValueKey([gridColumn.mappingName, index]));
            } else {
              return null;
            }
          },
        ));
  } 

`

**Comment by szymonmazanik** [comment]
Hello @RenugaSadagoban98 
Thank you for the answer.

Unfortunately the solution did not work. I added ValueKey with unique value (also tried UniuqeKey) and the grid is still lagging on horizontal scrolling. On vertical scrolling it works perfectly fine. Is there something else I can do?

**Comment by RenugaSadagoban98** [comment]
Hi @szymonmazanik, 
  
Thanks for your update. 
  
We have prepared a simple example to demonstrate how we have configured the DataGrid with widget columns. In this example, the horizontal scrolling is working fine in Samsung Galaxy Tab A device. 
  
Please check the following example and revert us if you are facing the same issue? If not, please provide your example customization to understand how you are configuring the datagrid with widget columns. It would be helpful for us to provide a prompt solution at earliest. 
 
Sample link: https://www.syncfusion.com/downloads/support/directtrac/319773/ze/main-1160996596

**Comment by szymonmazanik** [comment]
Hello @RenugaSadagoban98 

I logged in with my account and I don't have access to this link
![image](https://user-images.githubusercontent.com/25953768/111783712-c8daa900-88ba-11eb-9d83-c0dbbb837317.png)

**Comment by RenugaSadagoban98** [comment]
Hi @szymonmazanik,

Sorry for the inconvenience caused.

Please find the following sample file.

[main.zip](https://github.com/syncfusion/flutter-widgets/files/6171300/main.zip)
