### ISSUE TITLE
[syncfusion_flutter_pdfviewer 24.1.41] Chrome view isn't working

### ISSUE THREAD

**Issue by augustebalsanel** [syncfusion/flutter-widgets#1593]
I've tried using the syncfusion_flutter_pdfviewer 24.1.41 with a Chrome view, but it just doesn't work.
It works perfectly on Android, iOS, Windows, but nothing on Chrome, only a gray container.

In a demo from own pub.dev, it started not working, but later - after trying again - it started working.

**Comment by immankumarsync** [comment]
Hi @augustebalsanel,

We suspect that you might have missed the script part in the web/index.html file. Kindly include the following script in the web/index.html file.

UG documentation: https://help.syncfusion.com/flutter/pdf-viewer/getting-started#add-the-flutter-pdf-viewer-to-an-application

```
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>
<script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.worker.min.js";
</script>
```

**Comment by augustebalsanel** [comment]
Oh, it was that! Thank you and sorry for the inconvenience.

Awesome package!
