### ISSUE TITLE
[syncfusion_flutter_charts] horizontal scroll seems to be broken on 24.1.41

### ISSUE THREAD

**Issue by btrautmann** [syncfusion/flutter-widgets#1595]
On the latest version of the charts package (`24.1.41`), it seems that horizontal scroll is broken. [There is a repo that reproduces this issue here](https://github.com/btrautmann/charts_x_axis_issue_repro).

If you checkout that code, you can change the version between `24.1.41` and `23.2.6`, run `flutter pub get` and hot restart the app and you'll see the difference in behavior:

### 24.1.41 (broken)

https://github.com/syncfusion/flutter-widgets/assets/8343465/db118685-1689-4468-92dc-e51b29b4632f

### 23.2.6 (working)

https://github.com/syncfusion/flutter-widgets/assets/8343465/076dda20-f153-4586-8116-891e5519e072

Additionally, and maybe for the same reason, line chart seems to behave oddly when scrolled:

https://github.com/syncfusion/flutter-widgets/assets/8343465/73378443-6f03-4539-9bbd-5352be68bb02

It behaves as expected on the previous version.

**Edit:** I re-uploaded videos that showed tap gestures (previously it was hard to tell when I was scrolling)

**Comment by LokeshPalani** [comment]
Hi @btrautmann,

 

We have replicated the reported issue regarding **"Chart is moved to previous zoom position while try to pan the chart with autoScrollingDelta in axis"** at our end. Currently, we are investigating the issue at the source level. We will provide you with further details by December 29, 2023, within one business day. We appreciate your patience until then.

 

Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment]
Hi @btrautmann,

We have fixed the reported issue at our end and changes were published in the below version. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/24.1.44+1 

Regards,
Lavanya A.

**Comment by btrautmann** [comment]
Thanks, I did verify the fix for bar chart and line graph 👍

**Comment by btrautmann** [comment]
Should we close this ticket out?

**Comment by LavanyaGowtham2021** [comment]
Yes, i am closing this ticket now. Kindly get back to us if you have further queries. We are always happy to assist you.
