### ISSUE TITLE
PDF viewer keeps at loading state after adding a new text to the page !

### ISSUE THREAD

**Issue by farisshomali** [syncfusion/flutter-widgets#1596]
After adding a text to pdf page that holds an index bigger than 0 (any page after the first page), the PDF viewer stuck on loading state !

I can go back to normal view after scrolling down to the next index then i go back to the original index !!!!

https://github.com/syncfusion/flutter-widgets/assets/61110881/1c02e7cc-9ab3-4308-b2ae-de3ec02582fb

` 
 body: Consumer<PDFViewModel>(
        builder: (_, state, __) => state.documentBytes == null
            ? const Center(child: Text('Please download a document'))
            : SfPdfViewer.memory(
                pdfViewModel.documentBytes!,
                pageLayoutMode: PdfPageLayoutMode.single,
                scrollDirection: PdfScrollDirection.vertical,
                controller: pdfViewModel.pdfViewerController,
                key: GlobalKeys.pdfViewerKey,
                canShowSignaturePadDialog: true,
                enableDocumentLinkAnnotation: true,
                interactionMode: PdfInteractionMode.selection,
                enableHyperlinkNavigation: true,
                onTap: (PdfGestureDetails tapDetails) {
                  state
                      .handleCurrentPageIndex(details: tapDetails)
                      .then((value) => state.addTextToPdfCoordinates(tapDetails.pagePosition, value - 1));
                },
                onDocumentLoaded: (PdfDocumentLoadedDetails details) {
                  state.load_annotation();
                },
                onDocumentLoadFailed: (details) {
                  print('Document failed to load => ${details.description}');
                },
                enableTextSelection: true,
              ),
      )
`

` 
Future<int> handleCurrentPageIndex({required PdfGestureDetails details}) async {
    return details.pageNumber;
  }
`

`
void addTextToPdfCoordinates(Offset pdfCoordinates, int pageNumber) async {
    GLOBAL_DOCUMENT_DATA = PdfDocument(inputBytes: documentBytes);
    print('Write on page => $pageNumber');
    currentPage = GLOBAL_DOCUMENT_DATA.pages[pageNumber];

    PdfFont font = PdfStandardFont(PdfFontFamily.helvetica, 12);
    String text = 'this is very important';
    Size size = font.measureString(text);

    currentPage.graphics.drawString(text, font,
        brush: PdfBrushes.red, bounds: Rect.fromLTWH(pdfCoordinates.dx, pdfCoordinates.dy, size.width, size.height));

    List<int> tmp = await GLOBAL_DOCUMENT_DATA.save();

    documentBytes = Uint8List.fromList(tmp);

    final path = await _localPath;

    File('$path/copy-output.pdf').writeAsBytes(await GLOBAL_DOCUMENT_DATA.save());

    GLOBAL_DOCUMENT_DATA.dispose();
    notifyListeners();
  }
`

**PLEASE HELP! ASAP**

**Comment by deepika134** [comment]
Currently, we do not have support for the free text annotation in Flutter PdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. Kindly use the below link for track the status of the feature ,

https://www.syncfusion.com/feedback/45202/support-for-free-text-annotations

However, we have a workaround for your requirement to add text in the PDFViewer. Kindly download the sample from the attachment and check it. Please let us know if it meets your requirement.
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/13783234/Sample.zip)

**Comment by farisshomali** [comment]
@deepika134 Hi

The issue is not about "How to add a new text"!, it's clear that i'm talking about the lags and crashes that happens after refresh the state of the page as described in the video... in general, i don't think this pdf library is ready to be published 😃

Huge issues at every action user do!

**Comment by ramkumarsync** [comment]
> @deepika134 Hi
> 
> The issue is not about "How to add a new text"!, it's clear that i'm talking about the lags and crashes that happens after refresh the state of the page as described in the video... in general, i don't think this pdf library is ready to be published 😃
> 
> Huge issues at every action user do!

Sorry for the miscommunication that happened earlier. We checked your case further and were still unable to replicate the issue, that is the page is stuck in the loading state when reloading the document. Could you please try out the below new sample attached and let us know whether the issue still occurs?

Regarding the lags and crashes you mentioned, since you are reloading the modified document, it will take some time to parse the document and it is the behaviour. Also, we didn't face any crashes on our end.

[Sample 1.zip](https://github.com/syncfusion/flutter-widgets/files/14278616/Sample.1.zip)
