### ISSUE TITLE
[syncfusion_flutter_charts] How to scroll through SfCartesianChart to view more data in 24.1.41

### ISSUE THREAD

**Issue by SkyOfFeather** [syncfusion/flutter-widgets#1597]
When there is a lot of data in SfCartesianChart, it is not possible to scroll horizontally to view the data.

The following is the relevant code for primaryXAxis:
`                          
                          primaryXAxis: CategoryAxis(
                            autoScrollingMode: AutoScrollingMode.start,
                            autoScrollingDelta: 10,
                            maximumLabels: 100,
                            axisLine: const AxisLine(color: Colors.transparent, width: 0),
                            labelAlignment: LabelAlignment.center,
                          ),
`

**Comment by LavanyaGowtham2021** [comment]
Hi @SkyOfFeather 

We have fixed the reported issue at our end, currently its under testing phase. We will include this fix and share the new charts package on January 3, 2024. We appreciate your patience until then.

**Comment by LavanyaGowtham2021** [comment]
Hi @SkyOfFeather ,

We have fixed the reported issue at our end and changes were published in the below version. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/24.1.44+1
