### ISSUE TITLE
Method to check if a supplied date is inside a Recurrence Rule

### ISSUE THREAD

**Issue by Sidhesh-naik-cci** [syncfusion/flutter-widgets#1598]
Is there a way to check if a supplied date is inside a Recurrence Rule

**Comment by IndumathiR-1995** [comment]
Hi ,

**Regarding Query: Is there a way to check if a supplied date is inside a Recurrence Rule**

We have a helper method getOccurrenceAppointment, by using this we can get the recurrence appointment details with date. We have a UG documentation for the same. Please find the documentation from the following link.

**UG links:**
https://help.syncfusion.com/flutter/calendar/appointments#get-visible-appointments https://help.syncfusion.com/flutter/calendar/appointments#get-occurrence-appointment 
https://help.syncfusion.com/flutter/calendar/appointments#get-pattern-appointment 


We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
