### ISSUE TITLE
The name 'Row' is defined in the libraries 'package:flutter/src/widgets/basic.dart' and 'package:syncfusion_flutter_xlsio/xlsio.dart'.

### ISSUE THREAD

**Issue by Nandan-Wewhare** [syncfusion/flutter-widgets#160]
Ambiguous import error occurring between basic widgets.
**How to reproduce:**
Use excel syncfusion package in the same dart file where there are basic UI components.

**Comment by Sridhar-Sukumar** [comment]
Hi @Nandan-Wewhare, 

Greetings from Syncfusion support. 

Flutter XlsIO has own Row, Column, and Alignment classes. So the error will occur when you refer "syncfusion_flutter_xlsio" package in your application. Please use the below code to refer the "syncfusion_flutter_xlsio" package in your application.  

`import 'package:syncfusion_flutter_xlsio/xlsio.dart' hide Row, Column, Alignment;`

This will resolve the reported issue. However we will find a way to resolve this error in our future releases. 

Regards, 
Shamini
