### ISSUE TITLE
[syncfusion_flutter_datepicker] maximum selection count on DateRangePickerSelectionMode.multiple?

### ISSUE THREAD

**Issue by TroyTheGod** [syncfusion/flutter-widgets#1601]
is there any way to set the maximum selection count on DateRangePickerSelectionMode.multiple?

**Comment by IndumathiR-1995** [comment]
Hi,

As per the current implementation, there is no support to set the maximum count value for multiple selection.  But, by using selectableDayPredicate and blackoutDate properties you can restrict the date selection. We have UG and KB documentation for the same. Please find the documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#blackout-dates 
https://help.syncfusion.com/flutter/daterangepicker/date-restrictions#selectabledaypredicate 

**KB link:**
https://support.syncfusion.com/kb/article/10380/how-to-add-active-dates-in-the-flutter-date-range-picker-sfdaterangepicker 
https://support.syncfusion.com/kb/article/10751/how-to-update-blackout-dates-in-the-flutter-date-range-picker

If possible, can you please share your requirement details clearly with an illustration image. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by TroyTheGod** [comment]
thanks for the reply,
heres my situations, for example i have three tickets of a park and i have to select three days in the calendar. i want to limited the maximum selection count so thats it won't goes beyond 3.
but anyway, i somehow find my way to makes it work.
