### ISSUE TITLE
State on findRenderObject()

### ISSUE THREAD

**Issue by Aladdin16659** [syncfusion/flutter-widgets#1602]
need to check for mounted on file pdfviewer.dart
`
2041-      _pdfDimension =
2042-        _childKey.currentContext?.findRenderObject()?.paintBounds.size ??
2043            Size.zero;
`

**Comment by immankumarsync** [comment]
Hi @Aladdin16659,
We are unable to catch any issues with your suggestions, could you please provide additional details regarding your suggestion? If you are facing any issues, kindly update us the replication steps/video, stack trace of the issue, simple sample in which the issue replicates.

**Comment by ramkumarsync** [comment]
We are closing this issue since we haven't heard back from you for a long time and don't have enough information to proceed further. You can reopen this anytime and share the requested details to proceed further.
