### ISSUE TITLE
[Syncfusion_Flutter_Datagrid] Please seperate the checkbox customization settings for header and rows

### ISSUE THREAD

**Issue by Ajwad-Mir** [syncfusion/flutter-widgets#1604]

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Ajwad-Mir,

As of now, the DataGrid does not offer built-in support for customizing checkboxes for the header and rows separately. However, you can achieve this through a workaround. 

To implement this workaround, wrap the [CheckboxTheme](https://api.flutter.dev/flutter/material/CheckboxTheme-class.html) widget as a parent of the DataGrid with the required [CheckboxThemeData](https://api.flutter.dev/flutter/material/CheckboxThemeData-class.html). This will enable you to display all the checkboxes in the DataGrid with the corresponding theme.

Next, you can set up your own checkbox in the header cell with different customization. In the [SfDataGrid.checkboxColumnSettings](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/checkboxColumnSettings.html) property, set the [showCheckboxOnHeader](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridCheckboxColumnSettings/showCheckboxOnHeader.html) property to false to disable the header checkbox. Then, in the [DataGridCheckboxColumnSettings.label](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridCheckboxColumnSettings/label.html) property, set the checkbox with the desired CheckboxThemeData to load the header checkbox with a different appearance.

Additionally, you'll need to update the header and row checkbox state from the sample level when pressing the header checkbox or a DataGridRow. This can be achieved by utilizing programmatic selection in the Checkbox.onChanged callback to update the row checkbox when tapping the header checkbox, and using the SfDataGrid.onSelectionChanged callback to update the header checkbox when tapping the row cell.

We have attached a basic sample for your reference. Please review the sample for further implementation details.



### Sample Link: [Flutter-DataGrid-Demo](https://github.com/syncfusion/flutter-widgets/files/14221935/Sample.zip)

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Ajwad-Mir,

We suspect that the reported issue has been resolved at your end with the provided workaround. Therefore, we are closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K

**Comment by Tigran-Kosemyan** [comment]
How to get header checkbox callback when select all pressed from header checkbox
