### ISSUE TITLE
[syncfusion_flutter_calendar] Improve custom DateFormat view settings

### ISSUE THREAD

**Issue by kaseyrossanderson** [syncfusion/flutter-widgets#1606]
Hello,

I have two View types currently being used:

- CalendarView.day
- CalendarView.timelineDay

When the chosen view is `CalendarView.day`the default DateFormat 'EE' looks great.

 However, when the chosen view is `CalendarView.timelineDay` it just says '3 Wednesday' and I'd like to change that.

The problem is.. both of these views are tied to the same DateFormat options under the `TimeSlotViewSettings` config class. So changing the dateFormat to 'EEE, MMM d messes up both views.

The day view will now show 'Wed, Jan 3' instead of just '3 like it did.. and now the timelineDay view shows 'Wed, Jan 3 Wednesday' which is also not as I'd expect.

Seems like there should be a config class for each view type if you want to override each. Can something like that be added?

Thanks!
Kasey A.

**Comment by IndumathiR-1995** [comment]
Hi Team,

As per the current implementation, dayFormat and dateFormat properties in the timeSlotViewSettings class is common for the all the timeline views, day, week, work week views. But by using the viewHeaderHeight value as 0 you can hide the default view header and add the required custom widget and customize based on your requirement. We have a UG and KB documentation for the same. Please find the documentation from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/headers#customize-view-header-height-in-calendar 

**KB link:**
https://support.syncfusion.com/kb/article/9606/how-to-add-custom-header-and-view-header-in-the-flutter-calendar 

Also, we have logged the feature request for “**Provide builder support for ViewHeader in the Flutter SfCalendar**”. By using this you can customize the day and date format based on the views. 

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
**Feedback link:**
https://www.syncfusion.com/feedback/42210/provide-builder-support-for-viewheader-in-the-flutter-sfcalendar 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
