### ISSUE TITLE
syncfusion_flutter_datepicker ^24.1.44 requires intl ^0.18.0

### ISSUE THREAD

**Issue by blondie63** [syncfusion/flutter-widgets#1610]
Is there a plan to upgrade dependency to ^0.19.0?

**Comment by IndumathiR-1995** [comment]
Hi,

**Regarding Query: Is there a plat to upgrade dependency to ^0.19.0?**

As per the shared information, we are unable to understand your exact issue details clearly. If possible, could you please share the details clearly with the below details?
 
•	Reason for upgrading intl package.
•	Pubspec.yaml screenshot of your project
•	Issue code snippet
 
It would be helpful for us to analyze and provide you with a solution.


Regards,
Indumathi R

**Comment by blondie63** [comment]
It's very simple, in my apps I use various packages and I try to always keep them updated, in particular I use "intl" and "syncfusion_flutter_datepicker"
Currently syncfusion_flutter_datepicker has a constrain to intl ^0.18.0 and so I cannot update intl to the latest v 0.19.0

You can see here:
https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_datepicker/pubspec.yaml

When i try to use intl ^0.19.0 in my pubspec.yaml i've this error:
/Users/mauro/fvm/default/bin/flutter --no-color pub get
Resolving dependencies...
Because syncfusion_flutter_datepicker 24.1.44 depends on intl ^0.18.0 and no versions of syncfusion_flutter_datepicker match >24.1.44 <25.0.0, syncfusion_flutter_datepicker ^24.1.44 requires intl ^0.18.0.
So, because pic depends on both intl ^0.19.0 and syncfusion_flutter_datepicker ^24.1.44, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.18.1
Process finished with exit code 1

Regards

**Comment by guilhermedaldim** [comment]
Hey man, thanks for this package is very good!

I have the same issue here! Do you have any plans to update the version?

**Comment by EderCosta21** [comment]
I'm also having the same problem here.

**Comment by blondie63** [comment]
last version .46 have new dep to intl 0.19.0 but we still can't upgrade it because this:
https://github.com/flutter/flutter/pull/141265

**Comment by LavanyaGowtham2021** [comment]
We have already upgraded the intl version for our widgets, please use our latest version 24.2.5 to resolve this issue.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you still face an issue with latest version.
