### ISSUE TITLE
[syncfusion_flutter_charts] Pie Chart data labels throw `Invalid argument(s): string is not well-formed UTF-16`

### ISSUE THREAD

**Issue by btrautmann** [syncfusion/flutter-widgets#1611]
I've been getting reports of users experiencing issues with their pie charts, see the below logs:

 <details>
    <summary>Stacktrace</summary>
    <br>

```console
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Invalid argument(s): string is not well-formed UTF-16. Error thrown while building a TextSpan.
       at _NativeParagraphBuilder.addText(dart:ui)
       at TextSpan.build(text_span.dart:281)
       at TextPainter._createParagraph(text_painter.dart:1070)
       at TextPainter.layout(text_painter.dart:1125)
       at .drawText(helper.dart:54)
       at .drawLabel(data_label_renderer.dart:1111)
       at .renderCircularDataLabel(data_label_renderer.dart:681)
       at _CircularDataLabelPainter.paint(data_label_renderer.dart:144)
       at RenderCustomPaint._paintWithPainter(custom_paint.dart:588)
       at RenderCustomPaint.paint(custom_paint.dart:630)
       at RenderObject._paintWithContext(object.dart:3208)
       at PaintingContext.paintChild(object.dart:250)
       at RenderProxyBoxMixin.paint(proxy_box.dart:129)
       at RenderObject._paintWithContext(object.dart:3208)
       at PaintingContext._repaintCompositedChild(object.dart:166)
       at PaintingContext.repaintCompositedChild(object.dart:109)
       at PipelineOwner.flushPaint(object.dart:1156)
       at PipelineOwner.flushPaint(object.dart:1166)
       at RendererBinding.drawFrame(binding.dart:593)
       at WidgetsBinding.drawFrame(binding.dart:986)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:457)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1325)
       at SchedulerBinding.handleDrawFrame(binding.dart:1255)
       at SchedulerBinding._handleDrawFrame(binding.dart:1113)
```
</details>

I was able to reproduce this and a [repro case is here](https://github.com/btrautmann/syncfusion_charts_repros/blob/main/lib/pie_chart.dart). Just check that repo out and run the code, the pie chart is the first one in the list.

**Note:**
The issue is reproduced only (as far as I can tell) when the name _ends_ with an emoji. If the truncation of the labels is being performed by the charts library somewhere (I couldn't find it, but didn't look TOO hard), it's likely an issue similar to [this one](https://github.com/dart-lang/sdk/issues/35798) and needs a slight adjustment to use the `String` `runes` as described there.

![Simulator Screenshot - iPhone 13 mini - 2024-01-04 at 09 35 25](https://github.com/syncfusion/flutter-widgets/assets/8343465/fbc76b61-7796-41f3-b254-04dd1acc0bb3)

**Comment by btrautmann** [comment]
I attempted to use the above code but the labels are not showing. Oddly, if I replace the `point.x.toString()` passed to `Text` with something like `'Hello world'` it shows. I pushed the code changes to the repo mentioned in the issue description, let me know if I'm doing something funky.

**Comment by btrautmann** [comment]
@PreethikaSelvam I gave that a shot (see latest commit in the repo) but the result is the same unfortunately.

**Comment by btrautmann** [comment]
@PreethikaSelvam and word on this? Also:

> We will check the flutter framework and update the solution for this case

Does this mean you opened an issue with `flutter/flutter`? Do you have a link?

**Comment by LokeshPalani** [comment]
Hi Team,

**Query 1: I tried the solution mentioned (see latest commit in the repository), but unfortunately, the result remains the same.**

We have checked your GitHub repository and found that it was working fine on our end. We have attached the screenshot and screenrecording below inside the Zip folder. However, we kindly request you to provide us with more detailed information along with screenshots or screen recordings. This will help us assist you more effectively.

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/d64a55dc-cf8a-448f-9927-643a4cd5e6f7)


We also need the following details to check the mentioned issue:

1. Flutter SDK version.
2. Platform to run the sample.
3. Device details.


**Query 2: I would like to confirm if you have opened an issue with flutter/flutter. If so, could you please provide us with the link?**


For the mentioned issue regarding 'When using text painter with partially trimmed emoji, an Exception arises', we have created a GitHub issue and logged it in the Framework. For your reference, please find the attached GitHub link below. If you have any further inquiries, please feel free to contact us.


GitHub issue Link - https://github.com/flutter/flutter/issues/142037  


Regards,
Lokesh P.

**Comment by btrautmann** [comment]
Thanks for pointing me to the framework issue!

I've run the sample again and recorded a video of what I'm seeing. I'm not sure if this behavior is expected, but it's definitely related to screen size. The pie chart labels do not render at all as screen size decreases.

**iPhone 13 mini and MacOS Desktop:**
https://github.com/syncfusion/flutter-widgets/assets/8343465/2222d026-08cb-432d-bdfc-5399e976f60e

**Comment by btrautmann** [comment]
Understood, and that makes sense. Thank you! I think we can leave this issue open as the root issue still exists and is being tracked by https://github.com/flutter/flutter/issues/142037.

**Comment by btrautmann** [comment]
Following up on the above `flutter/flutter` issue that was closed: Do you all think you will be able to implement the truncation via graphemes and not manually trim the `String`?

**Comment by btrautmann** [comment]
@PreethikaSelvam the _original_ issue is the incorrect truncation of text containing emojis. You already opened an internal issue for the above problem and linked it in https://github.com/syncfusion/flutter-widgets/issues/1611#issuecomment-1910298273. I think the issue you mentioned in https://github.com/syncfusion/flutter-widgets/issues/1611#issuecomment-1932267726 is now redundant.

I have opened https://github.com/syncfusion/flutter-widgets/pull/1661 which addresses the root issue here. Note that the PR does not attempt to solve all instances of this problem, but rather serves to demonstrate a fix for the root cause. Please check it out and let me know if you have questions.
