### ISSUE TITLE
Invalid argument (fontName): invalid font name: "Times#2DRoman"

### ISSUE THREAD

**Issue by cmkz** [syncfusion/flutter-widgets#1613]
flutter_error_exception | Invalid argument (fontName): invalid font name: "Times#2DRoman"

flutter_error_reason | thrown Invalid argument (fontName): invalid font name: "Times#2DRoman". Error thrown Instance of 'ErrorDescription'.

**Comment by LavanyaGowtham2021** [comment]
Please share the requested details to proceed further on this query.
