### ISSUE TITLE
New version with needed for flutter 2.0

### ISSUE THREAD

**Issue by aghanti7** [syncfusion/flutter-widgets#162]
Need a new version of the plugin with null safety and upgraded dependencies is needed urgently for supporting flutter 2.0

**Comment by vjrj** [comment]
Dup of https://github.com/syncfusion/flutter-widgets/issues/154

**Comment by Dharanipalani** [comment]
Hi @aghanti7,

We are working on it and we will provide the null safety for all our widgets in the upcoming volume1 main release which is expected to be rolled out at the end of March 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by SriramKiranSenthilkumar** [comment]
Hi @aghanti7,

Thanks for your patience. We are glad to inform you that we have migrated all our widget packages to null safety and is rolled out in our vol 1 main release. To use the null safety version of our flutter widgets, kindly upgrade the package version to the latest version (**19.1.54+1**). We have also updated all the packages' source in our [flutter-widgets](https://github.com/syncfusion/flutter-widgets) repository.

Regards,
Sriram Kiran

**Comment by aghanti7** [comment]
> Hi @aghanti7,
> 
> Thanks for your patience. We are glad to inform you that we have migrated all our widget packages to null safety and is rolled out in our vol 1 main release. To use the null safety version of our flutter widgets, kindly upgrade the package version to the latest version (**19.1.54+1**). We have also updated all the packages' source in our [flutter-widgets](https://github.com/syncfusion/flutter-widgets) repository.
> 
> Regards,
> Sriram Kiran

Thanks much!
