### ISSUE TITLE
'CartesianChartPoint<dynamic>' is not a subtype of type 'CartesianChartPoint<DateTime>' of 'point'

### ISSUE THREAD

**Issue by barilki** [syncfusion/flutter-widgets#1621]
Hi,

I'm using SfCartesianChart with DateTimeCategoryAxis in primaryXAxis.

After upgrading to the latest Syncfusion version, I'm getting an error:

======== Exception caught by rendering library =====================================================

type 'CartesianChartPoint<dynamic>' is not a subtype of type 'CartesianChartPoint<DateTime>' of 'point'

The issue is in the following code:

```
onActualRangeChanged: (args) {
  if (args.orientation ==
      AxisOrientation.horizontal) {
    // You can get the x axis maximum value pixel point here. This is the x axis right side pixel value. So, opposed y-axis started from this position.
    final double visibleMaxX = candleController!
        .pointToPixel(CartesianChartPoint(
            x:args.visibleMax, y:0))
        .dx;

    // You can get the x axis minimum value pixel point here.
    final double visibleMinX = candleController!
        .pointToPixel(CartesianChartPoint(
            x:args.visibleMin, y:0))
        .dx;

    // You can get the x axis width here.
    xAxisWidth = visibleMaxX - visibleMinX;
  }
```

**Comment by barilki** [comment]
Any updates? @PreethikaSelvam

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need any assistance on this.

**Comment by barilki** [comment]
@PreethikaSelvam

**Comment by LokeshPalani** [comment]
Hi @barilki,

 
As mentioned in the previous update, when trying to get the width using [onActualRangeChanged ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html)callback, the [pointToPixel ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/pointToPixel.html)method would yield an incorrect position. You can get the plot area width and height by using the [onCreateRenderer ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html)callback in the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html). By using this, you can get the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) size in the performLayout method. Additionally, we have displayed [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html) size by using [TextField ](https://api.flutter.dev/flutter/material/TextField-class.html)widget below [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We have shared code snippet and a sample for your reference. You can customize the sample based on your requirements.

 

Code Snippet:

``` dart
body: Column(
        children: [
          SfCartesianChart(
            primaryXAxis: const DateTimeCategoryAxis(),
            primaryYAxis: const NumericAxis(),
            series: <CartesianSeries<ChartSampleData, DateTime>>[_lineSeries],
          ),
          TextField(
            controller: _controller,
          ),
        ],
      ),


    @override
  void performLayout() {
    super.performLayout();
    plotAreaHeight = size.height;
    plotAreaWidth = size.width;
    updateTextField('Plot Area Width: $plotAreaWidth, Height: $plotAreaHeight');
  }
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/e4755861-0290-4ef1-9b3c-7970e461cb4b)

Regards,
Lokesh P.

[chart_541384 (1).zip](https://github.com/syncfusion/flutter-widgets/files/15383990/chart_541384.1.zip)
