### ISSUE TITLE
ANDROID - LOADING FOR OPEN PDF

### ISSUE THREAD

**Issue by federicapo** [syncfusion/flutter-widgets#1624]
I am using version 20.3.47, and when I open the same PDF on an iPad, it works perfectly. However, on an Android tablet, it takes 5 to 8 seconds to load. How can I resolve this issue?

**Comment by immankumarsync** [comment]
@federicapo, we have used the native platform renderer, which is a plugin-based approach, to retrieve the PDF pages in our Flutter PDF viewer. This causes a small delay when displaying the pages. This delay may vary depending on the device's performance.

**Comment by federicapo** [comment]
Ok thanks
