### ISSUE TITLE
[syncfusion_flutter_xlsio] Workbook.dispose() method throws: Cannot clear an unmodifiable list

### ISSUE THREAD

**Issue by koltai75** [syncfusion/flutter-widgets#1625]
Using `Dart SDK 3.2.3`, `Flutter 3.16.6` and `syncfusion_flutter_xlsio 24.1.45`, the method `dispose()` of `Workbook` class throws an error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot clear an unmodifiable list
#0      UnmodifiableListMixin.clear (dart:_internal/list.dart:159:5)
#1      Workbook.dispose (package:syncfusion_flutter_xlsio/src/xlsio/general/workbook.dart:6789:24)
```

The line in the file at location referenced by the stacktrace above (`workbook.dart`), the `dispose()` method calls:

```dart
if (_archives != null) {
    _archives!.files.clear();
    _archives = null;
}
```

`_archives.files` is declared in `archive.dart` as:
```dart
 List<ArchiveFile> get files => UnmodifiableListView(_files);
```

According to the [documentation](https://api.flutter.dev/flutter/dart-collection/UnmodifiableListView/clear.html) the `clear()` method is not supported by `UnmodifiableListView`:

> This operation is not supported by an unmodifiable list.

**Comment by Kurmitha4004** [comment]
Hi @koltai75 ,

We have included the fix to resolve the reported issue in our weekly Flutter release version 24.1.46. Kindly upgrade your Syncfusion packages to this new 24.1.46 version and let us know if the issue is resolved.

Flutter Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/24.1.46

Regards,
kurmitha M.

**Comment by koltai75** [comment]
Hi @Kurmitha4004 ,

Thank you for your answer. Unfortunately I could not try this version out.
After adding `24.1.46` to my `pubspec.yaml` for every SyncFusion package, I got the following error from `flutter pub get`:

```
[aloksi] flutter pub get --no-example
Resolving dependencies...
Because syncfusion_flutter_charts >=24.1.46 depends on intl ^0.19.0 and aloksi depends on intl ^0.18.0, syncfusion_flutter_charts >=24.1.46 is forbidden.
So, because aloksi depends on syncfusion_flutter_charts ^24.1.46, version solving failed.
exit code 1
```

This seems a little strange, because if I check the `pubspec.yaml` file of [syncfusion_flutter_charts](https://github.com/syncfusion/flutter-widgets/blob/73d2f82496b7541a7955f9d0ab7636de5aa867b9/packages/syncfusion_flutter_charts/pubspec.yaml#L12C8-L12C8), it contains:
```
intl: ^0.18.0
```

I don't really understand why does the version solving failed. I know that many packages, including some Flutter components depend on `intl 0.18.0` and having `intl 0.19.0` can be problematic - but as far as I understand, the `syncfusion_flutter_charts` package depends on `intl 0.18.0`.

**Comment by koltai75** [comment]
Hi @PreethikaSelvam ,

Thank you, I tried the new version and it does indeed solve the problem described in this issue.
I am closing this issue now and thank you for your help.

Regards,

Peter
