### ISSUE TITLE
app crash on some devices "Input dispatching timed out"

### ISSUE THREAD

**Issue by Islam-galal** [syncfusion/flutter-widgets#1628]
i used this widget and working fine with all my devices but after publish app on store found that some devices add crash in loading pdf and got this error from google play console can check this error please 

ANR details
com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.getPagesHeight
Input dispatching timed out

most of this issue related to below devices 

oppo 
redme

**Comment by immankumarsync** [comment]
Hi @Islam-galal ,

We tried to reproduce reported issue with provided details, pdf is loaded properly on our end without any ANR message. For your reference, we have attached the tested sample, as well as a screen recording of the output, and it can be download from the attachment. Please check the sample and let us know if you are still experiencing the issue on your end. If so, please provide a modified issue reproducing sample, issue reproducing pdf document and issue replicating video/steps. This will be helpful for us to provide a prompt solution as soon as possible.
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/13945960/GH543642.zip)

**Comment by Islam-galal** [comment]
hi @immankumarsync  here are output from VS code after debugging on OPPO device 

E/flutter (28770): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Binding has not yet been initialized.
E/flutter (28770): The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
E/flutter (28770): Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
E/flutter (28770): In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
E/flutter (28770): If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.

E/flutter (28770): #0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:300:9)

/flutter (28770): #1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:381:6)
E/flutter (28770): #2      ServicesBinding.instance (package:flutter/src/services/binding.dart:56:54)
E/flutter (28770): #3      _findBinaryMessenger (package:flutter/src/services/platform_channel.dart:146:25)
E/flutter (28770): #4      BasicMessageChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:192:56)
E/flutter (28770): #5      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:206:38)

E/flutter (28770): #6      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:208:52)
E/flutter (28770): #7      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:54)
E/flutter (28770): #8      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:13)
E/flutter (28770): #9      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:47)
E/flutter (28770): #10     main (package:ryadelsalehen/main.dart:11:12)


E/flutter (28770): #11     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (28770): #12     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (28770): #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (28770): 
D/VRI[MainActivity](28770): registerCallbacksForSync syncBuffer=false
D/VRI[MainActivity](28770): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true syncBuffer=false
W/Parcel  (28770): Expecting binder but got null!

D/VRI[MainActivity](28770):  debugCancelDraw  cancelDraw=false,count = 392,android.view.ViewRootImpl@9629109
D/VRI[MainActivity](28770): draw finished.
D/VRI[MainActivity](28770): onFocusEvent true
W/OnBackInvokedCallback(28770): OnBackInvokedCallback is not enabled for the application.
W/OnBackInvokedCallback(28770): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
D/VRI[MainActivity](28770): onFocusEvent false
I/alelElmoasereen(28770): Background concurrent copying GC freed 260137(12MB) AllocSpace objects, 6(120KB) LOS objects, 45% free, 28MB/52MB, paused 115us,60us total 157.441ms


I/Quality (28770): Blocked msg = Package name: com.RyadelSalehen.dalelElmoasereen [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-1s23ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 1023 ms
I/Quality (28770): Skipped: false 1 cost 19.396883 refreshRate 16595090 bit true processName com.RyadelSalehen.dalelElmoasereen

I/Quality (28770): stackInfo :----- pid 28770 at 2024-01-25 18:28:45.104 -----;Cmd line: com.RyadelSalehen.dalelElmoasereen;"main" prio=5 tid=2 RUNNABLE sysTid=28770;  at android.graphics.pdf.PdfRenderer.nativeOpenPageAndGetSize(Native Method);  at android.graphics.pdf.PdfRenderer.-$$Nest$smnativeOpenPageAndGetSize(Unknown Source:0);  at android.graphics.pdf.PdfRenderer$Page.<init>(PdfRenderer.java:315);  at android.graphics.pdf.PdfRenderer$Page.<init>(Unknown Source:0);  at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:233);  at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.getPagesHeight(SyncfusionFlutterPdfViewerPlugin.java:174);  at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.onMethodCall(SyncfusionFlutterPdfViewerPlugin.java:96);  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267);  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295);  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322);  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12);  at android.os.Handler.handleCallback(Handler.java:942);  at android.os.Handler.dispatchMessage(Handler.java:99);  at android.os.Looper.loopOnce(Looper.java:240);  at android.os.Looper.loop(Looper.java:351);  at android.app.ActivityThread.main(ActivityThread.java:8377);  at java.lang.reflect.Method.invoke(Native Method);  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584);  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013);


I/Quality (28770): stackInfo :----- pid 28770 at 2024-01-25 18:28:46.628 -----;Cmd line: com.RyadelSalehen.dalelElmoasereen;"main" prio=5 tid=2 RUNNABLE sysTid=28770;  at android.graphics.pdf.PdfRenderer.nativeOpenPageAndGetSize(Native Method);  at android.graphics.pdf.PdfRenderer.-$$Nest$smnativeOpenPageAndGetSize(Unknown Source:0);  at android.graphics.pdf.PdfRenderer$Page.<init>(PdfRenderer.java:315);  at android.graphics.pdf.PdfRenderer$Page.<init>(Unknown Source:0);  at android.graphics.pdf.PdfRenderer.openPage(PdfRenderer.java:233);  at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.getPagesHeight(SyncfusionFlutterPdfViewerPlugin.java:174);  at com.syncfusion.flutter.pdfviewer.SyncfusionFlutterPdfViewerPlugin.onMethodCall(SyncfusionFlutterPdfViewerPlugin.java:96);  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267);  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295);  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322);  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12);  at android.os.Handler.handleCallback(Handler.java:942);  at android.os.Handler.dispatchMessage(Handler.java:99);  at android.os.Looper.loopOnce(Looper.java:240);  at android.os.Looper.loop(Looper.java:351);  at android.app.ActivityThread.main(ActivityThread.java:8377);  at java.lang.reflect.Method.invoke(Native Method);  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584);  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013);

E/ANR_LOG (28770): Current msg <1> = { when=-15s176ms what=0 target=android.os.Handler callback=android.view.OplusScrollToTopManager$DelayRegisterReceiverRunnable }
E/ANR_LOG (28770): Current msg <2> = { when=-10s457ms what=29 target=android.view.ViewRootImpl$ViewRootHandler obj=com.android.internal.os.SomeArgs@953fb46 }
E/ANR_LOG (28770): >>>CURRENT MSG DUMP OVER<<<
I/Quality (28770): Blocked msg = Package name: com.RyadelSalehen.dalelElmoasereen [ schedGroup: 5 schedPolicy: 0 ] process the message: { when=-16s132ms what=0 target=android.os.Handler callback=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 } took 16125 ms
Lost connection to device.

Exited.

**Comment by immankumarsync** [comment]
Still, we are unable to replicate the issue on our side. From the stacktrace you shared, it seems that the issue is with Binding. Can you check by adding WidgetsFlutterBinding.ensureInitialized()" before calling "runApp()"?

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}
```

**Comment by Islam-galal** [comment]
Hi @immankumarsync 

yes it's already added as below 

Future<void> main() async {
   WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  var bookMarkedBox = await Hive.openBox('bookMarked');
  runApp(MyApp(
    box: bookMarkedBox,
  ));
}

**Comment by vphuong1205** [comment]
Hi @immankumarsync
I also faced the same issue in some iOS device.
Currently it is simulator with this file.
[lab_report.pdf](https://github.com/syncfusion/flutter-widgets/files/14087113/lab_report.pdf)

**Comment by immankumarsync** [comment]
Could you please share a simple sample in which the issue replicates? It would be helpful in analyzing this issue further and provide you with prompt solution.
