### ISSUE TITLE
I am looking for a different kind of Pie Chart.

### ISSUE THREAD

**Issue by ShahzadUmarBaig** [syncfusion/flutter-widgets#163]
I have been searching your charts library but couldn't find a customized chart like the one I am looking for, attaching the issue with example so you can explore it. Can you improvise your package and include such charts? Else I can work on this and produce a Pull Request.

https://github.com/hashirshoaeb/star_book/issues/214#issue-825889704

Look into the attached issue.

Image: 
<img width="246" alt="Screenshot 2021-03-08 at 1 37 37 PM" src="https://user-images.githubusercontent.com/35165481/110473756-b5804e80-8100-11eb-86f8-a629560ddb63.png">

**Comment by Dharanipalani** [comment]
Hi @ShahzadUmarBaig,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and attached the sample and screenshot please make use of it. We have achieved this by using the **annotations**, **pointColorMapper**, and **pointRadiusMapper** properties. Annotations to place any widget in the required place, pointCollorMapper for giving different colors to the different slices, and pointRadiusMapper for rendering different slices with different radius. You can use annotation for placing the arrow image in the required doughnut slice. To know more about our charts, refer to the following help documents,

[https://help.syncfusion.com/flutter/circular-charts/circular-series-customization#color-mapping-for-data-points](https://help.syncfusion.com/flutter/circular-charts/circular-series-customization#color-mapping-for-data-points)

[https://help.syncfusion.com/flutter/circular-charts/annotations](https://help.syncfusion.com/flutter/circular-charts/annotations)

Sb samples link: [https://flutter.syncfusion.com/#/circular-charts/chart-types/doughnut/default-doughnut-chart](https://flutter.syncfusion.com/#/circular-charts/chart-types/doughnut/default-doughnut-chart)

Sample: 
[I320385-customized-doughnut.zip](https://github.com/syncfusion/flutter-widgets/files/6188210/I320385-customized-doughnut.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/112122082-ee7eef80-8be5-11eb-80d9-be184e7bf6ef.png)


Please revert us if you need further assistance.

Thanks,
Dharanitharan. P

**Comment by hashirshoaeb** [comment]
Hi @Dharanipalani 

I appreciate your effort and time you spent to write the example code for us. It aligns with our requirement. Thank you for your help. 
You can close the issue now. 

Best, 
Hashir
