### ISSUE TITLE
[syncfusion_flutter_datagrid] Enter button submit cell edit BUT i need to add a new line / line break when i press enter

### ISSUE THREAD

**Issue by mariopepe** [syncfusion/flutter-widgets#1641]
Pressing Enter button in Flutter on MacOs makes the cell edit to be submitted and it calls my code onSubmit.

But I want to press Enter  or maybe Shift + Enter, to add a new line in the cell.

How to add a new line in the cell in flutter? Thanks

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @mariopepe,

We have considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. 
    
**Feedback link:  https://www.syncfusion.com/feedback/50245/support-to-add-a-new-line-line-break-when-pressing-enter-in-the-edit-widget** 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @mariopepe,

We are closing this issue as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Ashok K
