### ISSUE TITLE
Flutter 3.13.6 TextScaler issue

### ISSUE THREAD

**Issue by ZameerHaider** [syncfusion/flutter-widgets#1642]
I am trying to use syncfusion_flutter_calendar-24.1.46 but in Flutter 3.13.6 TextScaler is removed but the  syncfusion_flutter_calendar still uses this property in multiple locations inside package and the package is not usable with latest flutter versions.

**Comment by ZameerHaider** [comment]
<img width="1016" alt="Screenshot 2024-01-22 at 9 06 02 PM" src="https://github.com/syncfusion/flutter-widgets/assets/35671841/6ee1dfeb-5140-446d-acbb-f536bfd1d612">

**Comment by Yuvaraj-Gajaraj** [comment]
For your information, the textScaleFactor has been deprecated and introduced TextScaler in the latest Flutter SDK version 3.16.0. We have also shared the breaking changes release note below for your reference. We request you to upgrade the Flutter SDK version to the latest one or if you want to use our package with the Flutter SDK 3.13.6, use syncfusion_flutter_calendar: 23.2.4 or lower. We hope it will help you to resolve the issue, if you have any further queries please get back to us.

Breaking changes in Flutter SDK 3.16.0 stable,  https://docs.flutter.dev/release/breaking-changes

Screenshot:
![Screenshot 2024-01-23 at 3 16 48 PM](https://github.com/syncfusion/flutter-widgets/assets/61863686/9d9d2e5f-ff2b-4e6a-8973-9b59178fa3a4)
