### ISSUE TITLE
[syncfusion_flutter_chart] PlotBand line at value does not show

### ISSUE THREAD

**Issue by cirediew** [syncfusion/flutter-widgets#1649]
Following this article:
https://support.syncfusion.com/kb/article/11458/how-to-render-line-at-a-specific-value-in-flutter-cartesianchart?isInternalRefresh=False

The plot band is not rendered when `start` and `end` are the same value.

```dart
final now = DateTime(2024, 01, 01);
List<ChartData> chartData = [
  ChartData(now, -5),
  ChartData(now.add(Duration(hours: 1)), 0),
  ChartData(now.add(Duration(hours: 2)), 10),
];

SfCartesianChart(
            primaryXAxis: DateTimeCategoryAxis(
              borderWidth: 0.0,
              axisLine: AxisLine(width: 0.0),
              majorTickLines: MajorTickLines(width: 0.0),
              majorGridLines: MajorGridLines(width: 0.0),
            ),
            borderWidth: 0.0,
            plotAreaBorderWidth: 0.0,
            primaryYAxis: NumericAxis(
              axisLine: AxisLine(width: 0.0),
              majorTickLines: MajorTickLines(size: 0.0),
              majorGridLines: MajorGridLines(dashArray: [8, 4]),
              borderWidth: 0.0,
              plotBands: [
                PlotBand(
                    //NOT rendering if start and end are the same
                    start: 0,
                    end: 0,
                    borderWidth: 2,
                    color: Colors.green,
                    shouldRenderAboveSeries: true)
              ],
            ),
            series: [
              LineSeries<ChartData, DateTime>(
                dataSource: chartData,
                xValueMapper: (ChartData data, _) => data.x,
                yValueMapper: (ChartData data, _) => data.y1,
              ),
            ],
          );
```

![image](https://github.com/syncfusion/flutter-widgets/assets/9058616/f31f0a21-466f-4bef-bcd8-33b6ee82f888)

**Comment by LokeshPalani** [comment]
Hi @cirediew,

We have checked the reported issue regarding 'PlotBand not rendered when start and end values are same’. When the [start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand/start.html) and [end](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand/end.html) values are the same, the [PlotBand](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand-class.html) Rectangle size becomes zero. As a result, the fillColor is not displayed. You can achieve your requirement by enabling the [borderColor](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand/borderColor.html) and [borderWidth](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand/borderWidth.html) in the [PlotBand](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand-class.html). To assist you further, we have provided a code snippet, screenshot, modified sample, and user guide documentation for your reference. 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#plot-line

Code Snippet:

  ``` dart
plotBands: [
            PlotBand(
              start: 0,
              end: 0,
              color: Colors.green,
              borderWidth: 2,
              borderColor: Colors.black,
              shouldRenderAboveSeries: true,
            ),
          ],
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/fe741f75-8757-43ed-acc3-bdfa1beb5a9d)

Regards,
Lokesh P.

[chart_550888_PlotBand.zip](https://github.com/syncfusion/flutter-widgets/files/14174958/chart_550888_PlotBand.zip)
