### ISSUE TITLE
[syncfusion_flutter_charts] labelStyle overflow does not apply to primaryAxis

### ISSUE THREAD

**Issue by Nikzed** [syncfusion/flutter-widgets#1654]
Hi! I have the next code, where I'm trying to solve padding issues to align all graphs by 1 line, rather than them being all different sizes.

```
primaryYAxis: const NumericAxis(
        interactiveTooltip: InteractiveTooltip(
          enable: false,
        ),
        labelStyle: TextStyle(overflow: TextOverflow.visible), // or fade
      ),
```
and the problem that the TextOverflow is not being triggered at all, if I add color here, it will be applied, but the overflow isn't.

<img width="282" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/38156331/7d282973-2b61-45cf-95a2-f10275ed4492">

**Comment by Nikzed** [comment]
Sure my friend, I'm using `maximumLabelWidth: 24`. You won't get it with default behaviour. The problem I am trying to solve, is graphs not being aligned, they're just changing size depending on their labels, which should not be if you want to make them perfectly match the right size.
<img width="274" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/38156331/6dbadc31-c490-4bb1-881e-33c854c57177"> <img width="272" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/38156331/c8a88e32-2882-43ba-a310-ccbb34bbe50c">

**Comment by Nikzed** [comment]
@PreethikaSelvam I mean, there should be definitely a good way to solve it. I feel the labelPosition inside makes it look unnatural.

**Comment by LokeshPalani** [comment]
Hi @Nikzed,


If the requirement is to avoid irregular label size, we suggest to use [numberFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/numberFormat.html) property in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). By setting '#.00' in the [NumberFormat](https://api.flutter.dev/flutter/intl/NumberFormat-class.html), it indicates that there should be two decimal places displayed after the decimal point. If the number doesn't have two decimal places, it will be added with zeros in the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) axis labels. We have shared a code snippet, screenshot, and sample for your reference. Please let us know if you need any further assistance.


**Code Snippet:**

``` dart
primaryYAxis: NumericAxis(
numberFormat: NumberFormat("#.00"),
),
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/8b1e1296-59e1-4bc7-b08e-b8258c203d25)

Regards,
Lokesh P.

[github_1654.zip](https://github.com/syncfusion/flutter-widgets/files/14383700/github_1654.zip)

**Comment by Nikzed** [comment]
@LokeshPalani  my friend, it’s really bad solution for this problem, the numbers can be from 0 to 4000 for different graphs. For example: one graph has 0-900 range, without decimal numbers, second one has range 0 to 5000, and the range changing dynamically depending on the date range, or it was just zoomed to specific diapason. The third one is 20.00 to 30.00 with decimals, and the final one is 0 to 6. 

There are a lot of cases when you can’t predict what the value will be. So mask should also not be a solution for this, but maybe the individual masks for graphs if you know the range of min and max should work fine?

For example:
NumberFormat("####")
If it will return “ 400” (with space before to fill the gap it would be good)

NumberFormat("##.0#")
and for 20.3 it would return “20.30”

But why not to be able to set specific padding to the values and be able to set text overflow how it’s supposed to be in a first place

thank you!

**Comment by VijayakumarMariappan** [comment]
Hi @Nikzed

We have a few questions regarding your requirements. Could you please clarify the following questions? Once we have more information, we will provide a solution based on your clarification.

1. Currently, the axis labels are aligned to the right when the y-axis is placed by default. Are you wishing to position them from the left side to align vertically straight like below?
![image](https://github.com/syncfusion/flutter-widgets/assets/92971875/16ef27ab-70aa-480c-a072-444e9cdfe32e)
2. If you want to align the axis labels as left alignment, the right side of the labels will not be vertically straight. Is this acceptable?
3. Are you willing to keep all labels the same size, with the minimum label size for all axis labels? If so, the maximum labels will be clipped. Could you please explain how you are expecting to visualize the labels? If possible please share a illustrated image.

**Comment by VijayakumarMariappan** [comment]
Hi @Nikzed

We have a few questions regarding your requirements. Could you please clarify the following questions? Once we have more information, we will provide a solution based on your clarification.

1. Currently, the axis labels are aligned to the right when the y-axis is placed by default. Are you wishing to position them from the left side to align vertically straight like below?
![image](https://github.com/syncfusion/flutter-widgets/assets/92971875/f8e56d77-d1ef-44ca-a4fa-32c25f453959)
2. If you want to align the axis labels as left alignment, the right side of the labels will not be vertically straight. Is this acceptable?
3. Are you willing to keep all labels the same size, with the minimum label size for all axis labels? If so, the maximum labels will be clipped. Could you please explain how you are expecting to visualize the labels? If possible, please share a illustrated image.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details if you need further assistance on this.
