### ISSUE TITLE
Flutter ios widget display gray area

### ISSUE THREAD

**Issue by rabol** [syncfusion/flutter-widgets#1655]
In a flutter app on ios I have the issue that I only get a grey area and not the PDF

This does not work:
```
Row(children: <Widget>[
  SizedBox(
   height: MediaQuery.of(context).size.height * 0.35, 
   width: MediaQuery.of(context).size.width,
   child: SfPdfViewer.memory(
     base64Decode(widget.doc.data.document),
     key: _pdfViewerKey,
   ),
 ),
]),


```
However another package works:
```
Row(
  children: <Widget>[
    SizedBox(
      height: MediaQuery.of(context).size.height * 0.35, 
      width: MediaQuery.of(context).size.width,
      child: PDFView(
        pdfData: base64Decode(widget.doc.data.document),
        enableSwipe: true,
      ),
    ),
  ],
),
```

So i know that the data that is passed to the Widget is ok.

Any hints?

**Comment by immankumarsync** [comment]
Hi @rabol, we are unable to replicate the issue, and the document is loaded properly using the base64 value. Please find the sample we used to replicate the issue.
[I1655_sample.zip](https://github.com/syncfusion/flutter-widgets/files/14164083/I1655.zip)

If the issue still occurs, kindly share with us the string data that you used while loading the pdf, which would help us analyze the issue and provide you with a better solution.

**Comment by ramkumarsync** [comment]
Since we don't have enough information to replicate the issue and proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.
