### ISSUE TITLE
syncfusion_flutter_datagrid MediaQuery.textScalerOf

### ISSUE THREAD

**Issue by Kevnlan** [syncfusion/flutter-widgets#1659]
I am trying to create an app that implements syncfusion_flutter_datagrid for work research purposes, however when I run the project after adding this import ```import 'package:syncfusion_flutter_datagrid/datagrid.dart';``` I get the following error
```
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datagrid-24.2.4/lib/src/datagrid_widget/sfdatagrid.dart:3228:20: Error: Member not found: 'MediaQuery.textScalerOf'.
        MediaQuery.textScalerOf(context).scale(1));
                   ^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datagrid-24.2.4/lib/src/datagrid_widget/runtime/column.dart:1224:9: Error: No named parameter with the name 'textScaler'.
        textScaler: TextScaler.linear(dataGridConfiguration.textScaleFactor),
        ^^^^^^^^^^
../../../dev/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.
```

I have had to comment out code inside the package for my app to run.

I am on the version ```24.2.4```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Kevnlan,
 
Based on the information provided, it seems that you might be using an older version of the Flutter SDK. We have tested the DataGrid with the latest version (**3.16.9**) and were unable to reproduce the issue you described.

If you are indeed using an older version of the Flutter SDK, we highly recommend upgrading to the latest stable version (**3.16.9**). This update might resolve the problem you are encountering.

Regards,
Tamilarasan
