### ISSUE TITLE
Drag & Drop only for specific appointments

### ISSUE THREAD

**Issue by kamami** [syncfusion/flutter-widgets#1662]
How can I allow drag & drop only for some but not all appointments?
Is there any way to cancel the dragging when some property of the appointment is false?

**Comment by Yuvaraj-Gajaraj** [comment]
Currently, we don't have support for Drag & Drop only for specific appointments and we have already logged a Feature Request in our feedback portal. We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback, https://www.syncfusion.com/feedback/31761/providing-support-for-read-only-appointments-in-flutter-calendar-sfcalendar
