### ISSUE TITLE
LateInitializationError: Field '_name@779283885' has not been initialized

### ISSUE THREAD

**Issue by jonny7737** [syncfusion/flutter-widgets#167]
No code changes after updating from syncfusion_flutter_charts: ^18.4.49 to syncfusion_flutter_charts: ^19.1.54+1.

The stack trace suggest that I did not set the name attribute when creating an EMA indicator.  My code for creating EMA indicators suggests otherwise.
```
 EmaIndicator<ChartData, dynamic> ema(List<ChartData> chartData, int period) {
    return EmaIndicator<ChartData, dynamic>(
      name: 'EMA$period',
      signalLineColor: Colors.lightGreen,
      dashArray: period == 50 ? [5, 5] : null,
      dataSource: chartData,
      xValueMapper: (ChartData data, _) => data.date,
      openValueMapper: (ChartData data, _) => data.open,
      highValueMapper: (ChartData data, _) => data.high,
      lowValueMapper: (ChartData data, _) => data.low,
      closeValueMapper: (ChartData data, _) => data.close,
      period: period,
    );
  }
```

Any help is greatly appreciated.

**Comment by Dharanipalani** [comment]
Hi Jonny,

Greetings from Syncfusion. We have analyzed your scenario and unfortunately unable to replicate the reported issue at our end. Here, we attached the sample with the given code snippet, please revert us with the issue in this sample will help us to provide the solution to you sooner.

Sample: [https://www.syncfusion.com/downloads/support/directtrac/322019/ze/f23892-ema-issue1996814432](https://www.syncfusion.com/downloads/support/directtrac/322019/ze/f23892-ema-issue1996814432)

Thanks,
Dharanitharan. P

**Comment by jonny7737** [comment]
I receive an "Access Denied" message when I try to acces the link provided.

Is the error 'thrown' by  Syncfusion code?  If yes, then can you tell me file from which the exception is thrown?  I can provide better feedback after that.

Thanks,
Jonny

**Comment by jonny7737** [comment]
Thank you for investigating.  I appologize for not providing enough information.

The link provided for the sample results in an 'Access Denied' error.

After 15 minutes of further investigation, the bug appears to be in the TechnicalIndicators class (syncfusion_flutter_charts-19.1.54+1/lib/src/chart/technical_indicators/technical_indicator.dart).

At line 506:
    seriesRenderer._seriesName = _name;
I believe this should be:
    seriesRenderer._seriesName = name;

I hope this helps.

Regards,
Jonny

**Comment by jonny7737** [comment]
And now that I can see my chart again, TrackBall ToolTiip does not display.

I'll let you know when I find the bug.

Thanks.

**Comment by Dharanipalani** [comment]
Hi Jonny,

Sorry for the inconvenience that occurs. Now, please find the sample below and revert with the issue as said earlier. 
Sample: [f23892-ema-issue1996814432.zip](https://github.com/syncfusion/flutter-widgets/files/6258311/f23892-ema-issue1996814432.zip)

Thanks,
Dharanitharan. P

**Comment by jonny7737** [comment]
syncfusion_flutter_charts-19.1.55+1/lib/src/chart/technical_indicators/technical_indicator.dart

From line 440:
```
/// To set properties of technical indicators
  void _setSeriesProperties(TechnicalIndicators<dynamic, dynamic> indicator,
      String name, Color color, double width, SfCartesianChart chart,
      [isLine = false, isRangeArea = false, isHistogram = false]) {
    List<double>? _dashArray;
    if (chart.onIndicatorRender != null &&
        !isRangeArea &&
        !isHistogram &&
        !isLine) {
      final IndicatorRenderArgs indicatorArgs = IndicatorRenderArgs(
          indicator, _index, chart.indicators[_index].seriesName, _dataPoints);
      indicatorArgs.indicatorName = name;    **<== assign value name to .indicatorName**
      indicatorArgs.signalLineColor = color;
      indicatorArgs.signalLineWidth = width;
      indicatorArgs.lineDashArray = indicator.dashArray;
      chart.onIndicatorRender!(indicatorArgs);
      color = indicatorArgs.signalLineColor;
      width = indicatorArgs.signalLineWidth;
      name = indicatorArgs.indicatorName;     **<== assign value .indicatorName to name**
      _dashArray = indicatorArgs.lineDashArray;
    }
```
The use of name like this is very odd.


Line 377 shows:
```  
late String _name;
```
then at line 510 _name is used [but no value has ever been assigned to it:
```    
seriesRenderer._seriesName = _name;
```

Perhaps the code is just to complicated for me to understand.
If none of this helps, just let me know and I will drop the issue.

--
Jonny

**Comment by Dharanipalani** [comment]
Hi Jonny,

We regret to the inconvenience that occurs. We have rendered the EMA indicator with your given code snippet and we also tried with the **onIndicatorRender** callback but unfortunately we are not able to replicate the reported issue in any of the cases, please revert us with your replicated sample or replicate the issue in our attached sample, this will help us to further investigate and provide the solution to you sooner.

Thanks,
Dharanitharan. P

**Comment by jonny7737** [comment]
The fix is simple (1 charecter edit of the indicated file).  I will continue to make the change foor each new release until it is no longer required.

Thank you for your efforts.

**Comment by Dharanipalani** [comment]
Hi @jonny7737,

Most Welcome and as said earlier we are unable to replicate this at our end and regret the inconvenience. Please revert if you need further assistance and we are always happy in assisting you.

Thanks,
Dharanitharan. P
