### ISSUE TITLE
Row height calculation

### ISSUE THREAD

**Issue by vasilich6107** [syncfusion/flutter-widgets#1670]
Hi.
Could you clarify why you are taking column icon `iconsWidth` into account while calculating the available width for column content?

The non header columns does not include any icons

<img width="758" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/6721286/4d9460c7-1f1b-48cc-a7dd-a854b8e7ba8c">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @vasilich6107,

We will ensure that the width of the icon is considered when using the **`ColumnWidthMode.fitByColumnName`** or **`ColumnWidthMode.auto.`** In the column header, we will display the column widget alongside the sort and filter icons.

For these two width modes, the content of the column widget should be fully visible within the view without any word wrapping. Consequently, we will take into account both the sort and filter icons, as well as the column header content, to ensure that the column header is entirely visible alongside the sort and filter icons.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
The **`ColumnWidthMode.auto`** calculates the width for all cell values (header and row cells) in a particular column and considers the largest value. This ensures that all values are displayed without word wrapping.

On the other hand, the **`ColumnWidthMode.fitByColumnName`** only considers the header cell values for calculating the width, regardless of the row cell values.

These are the defined behaviors of both Enums.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @vasilich6107,

Thank you for providing the sample. Following our testing, we have confirmed that this is indeed a bug. A bug report has been logged in our feedback portal to address this issue. We are committed to resolving the reported issue and will incorporate the necessary changes in the upcoming 2024 Volume 1 release, scheduled for rollout at the end of March 2024. We will let you know once it is published. We appreciate your patience and understanding until then. 

Regards,
Tamilarasan

**Comment by abineshPalanisamy** [comment]
Hi vasilich,
 
We are glad to announce that our Essential Studio 2024 Volume 1 Main Release V 25-1-35 is rolled out and is available for download under the following link.
 
[Essential Studio 2024 Volume 1 Main Release v25.1.35 is available for download | Announcements Forums | Syncfusion](https://www.syncfusion.com/forums/187257/essential-studio-2024-volume-1-main-release-v25-1-35-is-available-for-download)
 
Furthermore, we are pleased to inform you that the reported issue has been successfully addressed. The fix has been included in our 2024 Volume 1 release. Please update the DataGrid package to version 25.1.35.
 
[syncfusion_flutter_datagrid changelog | Flutter package (pub.dev)](https://pub.dev/packages/syncfusion_flutter_datagrid/changelog)
 
We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you require any further assistance.

Regards,
Abinesh P
