### ISSUE TITLE
method not found error in calendar widget 24.2.6

### ISSUE THREAD

**Issue by bgetsug** [syncfusion/flutter-widgets#1672]
After upgrading `synfusion_flutter_calendar` to `24.2.6` from `24.2.4`, our app crashes when attempting to open/view calendar events. (The Changelog shows no changes between versions.)

The error is occurring in `calendar_view_helper.dart` on line 584:

`String? notes = appointment.notes;`

```dart
  static void raiseCalendarTapCallback(
      SfCalendar calendar,
      DateTime? date,
      List<dynamic>? appointments,
      CalendarElement element,
      CalendarResource? resource) {
    if (appointments != null && appointments.isNotEmpty) {
      for (final dynamic appointment in appointments) {
        String? notes = appointment.notes;
        if (notes != null && notes.isNotEmpty) {
          notes = notes.replaceAll('isOccurrenceAppointment', '');
          appointment.notes = notes;
        }
      }
    }
    calendar.onTap!(CalendarTapDetails(appointments, date, element, resource));
  }
```

It looks like that file has changed significantly, and this is probably also an issue for the `raiseCalendarLongPressCallback` method...

Because `appointments` is a `List<dynamic>`, it may actually be a `List` of custom business objects, not `Appointment`s. In our case, the call to `appointment.notes` fails because there is no getter named `notes` on our custom object. Perhaps the `getNotes` method on `CalendarDataSource` should be used here instead? (We are properly overriding that method in our implementation, per the SfCalendar documentation.)

Rolling back to `24.2.4` is our workaround at the moment.

**Comment by mauriziopinotti** [comment]
Another workaround would be to implement the getter in your custom type (if it's your code), e.g. I added 

```dart
  // Fix for https://github.com/syncfusion/flutter-widgets/issues/1672
  String? get notes => null;
```

in my custom class I use as appointment.

**Comment by Yuvaraj-Gajaraj** [comment]
We can able to replicate the reported issue at our end and we have logged a bug report for it in our feedback portal. We will fix and include the changes in our upcoming Volume 1 main release which is expected to be rolled out on 3rd week of March 2024. We will update you here once the release is rolled out and we appreciate your patience until then.

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue regarding ﻿﻿the method not found error in the SfCalendar widget has been fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.1.35
