### ISSUE TITLE
Vector Free Hand Drawing

### ISSUE THREAD

**Issue by jtkeyva** [syncfusion/flutter-widgets#1673]
Is it possible to draw with custom painter or something similar and save the pdf as vector lines? Does it support layers?

**Comment by jeyalakshmit** [comment]
Yes, it is possible to create layers in a PDF page in Flutter. Please find the UG documentation for further details.

https://help.syncfusion.com/flutter/pdf/working-with-layers

**Comment by jtkeyva** [comment]
can you confirm the vector lines? i want to make a custom drawing app that can export vector pdf with layers.
thanks

**Comment by jeyalakshmit** [comment]
Yes, The Syncfusion Flutter PDF supports drawing various vector shapes. Kindly use the following link for reference, https://help.syncfusion.com/flutter/pdf/working-with-shapes

**Comment by jtkeyva** [comment]
thanks, i will look into it. are there any examples with different brushes or brush thickness

**Comment by jeyalakshmit** [comment]
In our Syncfusion Flutter PDF, we can add color and width using optional parameters like pen and brush in the draw methods.
Kindly use the following code snippet to add color and width in shapes for reference,

`//Create a new PDF document
 PdfDocument document = PdfDocument();
 
 //Add a page to the PDF document
 PdfPage page = document.pages.add();
 
 //Draw text in the PDF document
 page.graphics.drawString('Line',
      PdfStandardFont(PdfFontFamily.helvetica, 12, style: PdfFontStyle.bold),
     bounds: Rect.fromLTWH(10, 70, 0, 0));
 
 //Draw a line on PDF document
 page.graphics.drawLine(
     PdfPen(PdfColor(255, 0, 0), width: 5), Offset(10, 100), Offset(110, 100));
 
 //Draw text in the PDF document
 page.graphics.drawString('Rectangle',
      PdfStandardFont(PdfFontFamily.helvetica, 12, style: PdfFontStyle.bold),
     bounds: Rect.fromLTWH(10, 130, 0, 0));
 
 //Draw a rectangle on PDF document
 page.graphics.drawRectangle(
     pen: PdfPen(PdfColor(0, 0, 255), width: 2),
     brush: PdfSolidBrush(PdfColor(0, 255, 0)),
     bounds: Rect.fromLTWH(10, 160, 100, 100));
 
 //Save the PDF document
 File('output.pdf').writeAsBytesSync(await document.save());
 
 //Dispose the document
 document.dispose();
`
Output screenshot:
![MicrosoftTeams-image (4)](https://github.com/syncfusion/flutter-widgets/assets/93180080/59764474-e8f5-4f53-a767-a9b94f5514b8)

Kindly use the following links to know more about working with PdfPen and PdfBrush,
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPen-class.html
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPens-class.html
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfBrush-class.html
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfBrushes-class.html

Kindly use the following link to know more about the key features of Syncfusion Flutter PDF,
https://help.syncfusion.com/flutter/pdf/overview
