### ISSUE TITLE
y-axis title above the chart and custom content display

### ISSUE THREAD

**Issue by happylh2012** [syncfusion/flutter-widgets#1675]
1：Can the content of the y-axis on the chart be placed above the chart ? This is because the width of the display on mobile phones is limited, and expanding the display area of the chart could be helpful.
2：Is it possible to expand custom content, such as displaying weather icons at fixed intervals above the chart?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need ay further assistance on this.
