### ISSUE TITLE
DataGrid onCellSecondaryTap fires on group headers

### ISSUE THREAD

**Issue by berslen** [syncfusion/flutter-widgets#1676]
I am trying to add context menu support on row right click, to do so I am using onCellSecondaryTap(it would be great to have onRowSecondaryTap). My table has header and grouping headers. this callback fires on regular header and group headers. I am getting row data from tapDetails' row index . There is no way to determine, is clicked row is group header or not because _dataSource.effectiveRow doesn't contain group headers in it. Better approach can be implemented.

package version:24.2.6

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @berslen,

We have already considered your request as an enhancement, specifically regarding obtaining the tapped row type and retrieving the row from the effectiveRows when using grouping. We will implement this enhancement in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,

Feedback link: https://www.syncfusion.com/feedback/50282/support-for-obtaining-the-row-using-the-rowcolumnindex-from-the-oncelltap-callback  

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,

You can follow up further on this feature through the feedback link. We are closing this ticket now. If you need any further assistance, feel free to reopen this ticket. We are always happy to help you.

Regards,
Ashok K
