### ISSUE TITLE
Flutter DataGrid (SfDataGrid) MultiSelection,Double Tap Issue

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1677]
1- Double Tap is not working smooth as i sharing you a video sample. when i double click using mouse it not doing on double tap i have to click multiple times using mouse on windows app.
2- Multi Selection
when i press and down arrow key it dont include starting row. like my focused row index is 2 i press shift and down arrow key it dont include index 2 into the selection.

https://github.com/syncfusion/flutter-widgets/assets/62530396/3b550f53-6f92-4d01-b60e-c775a102df01

**Comment by abdulrehmananwar** [comment]
one more issue when dialog open i have to press down arrow key twice then it got focus to gridview. i want it on signle arrow key it do functional

**Comment by abdulrehmananwar** [comment]
One More Issue when i long press Down Arrow Key it only move one time. it should need be move down to down on Long press down arrow key as excel or other grids work

**Comment by abdulrehmananwar** [comment]
https://github.com/syncfusion/flutter-widgets/assets/62530396/9c2d57de-f63b-4254-9e84-9dfc617dea22

double tap some time work some time not work please check there must be some issue at your side

**Comment by abdulrehmananwar** [comment]
while 1st issue is still there when i press shift and down arrow key focused row dont get selected.

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported issue has been resolved at your end. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
