### ISSUE TITLE
Facing an issue After Update

### ISSUE THREAD

**Issue by sahal01** [syncfusion/flutter-widgets#1678]
I have this error:

Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-24.2.7/lib/src/control/pdf_page_view.dart:474:53: Error: The getter 'isMetaPressed' isn't defined for the class 'HardwareKeyboard'.

**Comment by Freyien** [comment]
I have this error: 

```
../../../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.7/lib/src/date_picker/date_picker.dart:10064:35: Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../../../Development/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAltPressed'.
    if (HardwareKeyboard.instance.isAltPressed) {
```

even when I use a previous version (24.1.46)

**Comment by immankumarsync** [comment]
Since the [RawKeyboardListener](https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html) widget is deprecated in Flutter 3.19, we have replaced the RawKeyboardListener with [KeyboardListener](https://api.flutter.dev/flutter/widgets/KeyboardListener-class.html) widget.

Could you please upgrade the Flutter SDK version to 3.19 and check whether the issue is resolved?

**Comment by sahal01** [comment]
I'm currently on Flutter version 3.13.4. After upgrading to version 3.19, I observed automatic design changes and encountered several issues. Can you please ensure these issues are resolved in Flutter version 3.13.4 too?

**Comment by sahal01** [comment]
> Since the [RawKeyboardListener](https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html) widget is deprecated in Flutter 3.19, we have replaced the RawKeyboardListener with [KeyboardListener](https://api.flutter.dev/flutter/widgets/KeyboardListener-class.html) widget.
> 
> Could you please upgrade the Flutter SDK version to 3.19 and check whether the issue is resolved?

I'm currently on Flutter version 3.13.4. After upgrading to version 3.19, I observed automatic design changes and encountered several issues. Can you please ensure these issues are resolved in Flutter version 3.13.4 too?

**Comment by Macacoazul01** [comment]
> > Since the [RawKeyboardListener](https://api.flutter.dev/flutter/widgets/RawKeyboardListener-class.html) widget is deprecated in Flutter 3.19, we have replaced the RawKeyboardListener with [KeyboardListener](https://api.flutter.dev/flutter/widgets/KeyboardListener-class.html) widget.
> > Could you please upgrade the Flutter SDK version to 3.19 and check whether the issue is resolved?
> 
> I'm currently on Flutter version 3.13.4. After upgrading to version 3.19, I observed automatic design changes and encountered several issues. Can you please ensure these issues are resolved in Flutter version 3.13.4 too?

The `24.1.41` version is working with flutter 3.16 (you need to import syncfusion_flutter_core too)
Not sure if it works with 3.13

**Comment by Freyien** [comment]
> Hi @Freyien / @sahal01,
> 
> We have migrated our source which is compatible with Flutter SDK 3.19.0, in Flutter SDK version 3.19.0 they have done breaking changes in the RawKeyEvent and replaced it with HardWareKeyBoard. So, we kindly request you to upgrade the Flutter SDK version to 3.19.0 or else use the packages **syncfusion_flutter_datepicker** or **syncfusion_flutter_pdfviewer** version below 24.2.7. We have also shared the breaking changes documentation below for your reference.
> 
> We hope it will help you to resolve the issue, if you have any further queries please get back to us. We are always happy to assist you.
> 
> Flutter 3.19.0 breaking change, https://docs.flutter.dev/release/breaking-changes/key-event-migration#migrating-iskeypressed-and-related-functions
> 
> Regards, Yuvaraj.

Thanks, @Yuvaraj-Gajaraj 
I update Flutter and works, but I think past versions should not be affected when a new version is released.

Again, thanks.
Amazing packages.

**Comment by Yuvaraj-Gajaraj** [comment]
Thanks for the update. Yes, the past version is not affected when a new version of the package gets released.

**Comment by karimi1064** [comment]
My Flutter version is `3.19.2` and I can run my app locally but when I wanted to build app on Bitrise I faced this error!

`Error (Xcode): ../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-24.2.8/lib/src/control/pdf_page_view.dart:474:53: Error: The getter 'isMetaPressed' isn't defined for the class 'HardwareKeyboard'.
`

**Comment by vkbaloda** [comment]
Thanks everyone to help. I resolved it by using syncfusion_flutter_pdfviewer: ^22.2.12
I'm using flutter v3.13.5, if it helps.
