### ISSUE TITLE
[syncfusion_flutter_pdf_viewer]  linux version trying to load android device info

### ISSUE THREAD

**Issue by liquidiert** [syncfusion/flutter-widgets#1679]
Hey, when I try  to use the viewer libary I get an error while reading the device info. The error is that DeviceInfoPlugin tries to read android configs while under linux. 
![image](https://github.com/syncfusion/flutter-widgets/assets/36642878/388c3915-0252-475b-9525-8587638bf3f4)
In the _findDevice method:
![image](https://github.com/syncfusion/flutter-widgets/assets/36642878/6a24c07a-c2c9-4d1f-8413-eee7daf5790c)

I think the error is that it does not include linux in the kIsDesktop flag:
![image](https://github.com/syncfusion/flutter-widgets/assets/36642878/22e66b27-13a0-4533-ba6c-01ccbf14bbd1)

**Comment by immankumarsync** [comment]
@liquidiert, at present, syncfusion_flutter_pdfviewer is not supported on the Linux platform.
https://help.syncfusion.com/flutter/system-requirements#supported-platforms

 We do not have any plans to implement Linux support. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented in the future.

Please follow the feedback link below to track the status of feature.
https://www.syncfusion.com/feedback/31376/linux-support-for-flutter-sfpdfviewer
