### ISSUE TITLE
[syncfusion_pdfviewer_web] Update JS version to 0.7.0+

### ISSUE THREAD

**Issue by dacianf** [syncfusion/flutter-widgets#1680]
JS Library got an update to version 0.7.1 and users of the lib cannot use it due to the following incompatibility error.

```
Because syncfusion_flutter_pdfviewer >=24.2.7 depends on syncfusion_pdfviewer_web ^24.2.7 which depends on js ^0.6.3, syncfusion_flutter_pdfviewer >=24.2.7 requires js ^0.6.3.
So, because project depends on both js ^0.7.1 and syncfusion_flutter_pdfviewer ^24.2.7, version solving failed.
```

**Comment by dacianf** [comment]
@immankumarsync 
I used the lasted JS version because I wanted to have a clean dependency cycle and they removed lib dependency on dart js. Moreover they increased supported sdk level and I don't really want to get to a point where I can't upgrade flutter due to an outdated library.

Since it doesn't really have breaking changes it's just a quick change in pub spec and maybe some imports.

**Comment by immankumarsync** [comment]
@dacianf, We have considered the request to upgrade the Js package to the latest one. This change will be included in our upcoming weekly release which is expected to be released on March 5th, 2024.Please find the feedback link to track the status,
https://www.syncfusion.com/feedback/51258/upgrade-the-js-package-version

**Comment by immankumarsync** [comment]
Hi @dacianf, 
We have updated the dependent js package version to 0.7.1 in the syncfusion_pdfviewer_web package, which is available in our latest (March 5, 2024) weekly release. 
We hope that the versioning issue will be resolved with the latest version, [syncfusion_flutter_pdfviewer 24.2.9](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.2.9).
