### ISSUE TITLE
[syncfusion_flutter_charts] SplineAreaSeries supports legendIconColor

### ISSUE THREAD

**Issue by M2dL1fe** [syncfusion/flutter-widgets#1681]
<img width="364" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/8074125/d4fb48ac-f322-4d0f-8ed1-e557b2e9b1e6">
When using gradient, legend's color cannot be customized

**Comment by LokeshPalani** [comment]
Hi @M2dL1fe 

Currently, we do not have an option to change the Legend icon color when using the gradient in the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html). However, we have prepared a workaround sample for your requirement by using the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback in the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html). By using this, you can change the Legend icon color by passing it into the CustomSplineAreaSeriesRenderer constructor and use it in the buildLegendItems method. We have shared the code snippet, screenshot, user guide documentation link, and sample for your reference. You can modify the sample based on your needs. Please let us know if you need any further assistance.



**UG Link,**

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#oncreaterenderer



**Code Snippet:**

``` dart
     SplineAreaSeries<ChartData, String>(
       dataSource: data,
         xValueMapper: (ChartData sales, _) => sales.x,
          yValueMapper: (ChartData sales, _) => sales.y2,
          borderDrawMode: BorderDrawMode.top,
           borderColor: Colors.black,
            borderWidth: 2,
            markerSettings: const MarkerSettings(
              isVisible: true,
            ),
            gradient: const LinearGradient(
              colors: [
                Colors.pink,
                Colors.white,
              ],
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
            ),
            opacity: 0.3,
            onCreateRenderer: (series) {
              return _CustomSplineAreaSeriesRenderer(Colors.blue);
            },
          ),


class _CustomSplineAreaSeriesRenderer
    extends SplineAreaSeriesRenderer<ChartData, String> {
  @override
  final Color color;

  _CustomSplineAreaSeriesRenderer(this.color);

  @override
  List<LegendItem>? buildLegendItems(int index) {
    LegendItem? legendItem = LegendItem(
      text: name,
      iconType: effectiveLegendIconType(),
      iconBorderWidth: legendIconBorderWidth(),
      iconColor: color,
    );
    return [legendItem];
  }
}

```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/b54ac1cd-3ade-4fcb-aa1a-70dbe479fea7)

Regards,
Lokesh P.

[github_1681_gradient_chart.zip](https://github.com/syncfusion/flutter-widgets/files/14395599/github_1681_gradient_chart.zip)

**Comment by M2dL1fe** [comment]
Okay, thank you. @LokeshPalani
