### ISSUE TITLE
The right most border

### ISSUE THREAD

**Issue by vasilich6107** [syncfusion/flutter-widgets#1684]
Hi.

I need to remove inner vertical borders from this table
<img width="790" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/6721286/2856c37c-69d9-4dc0-bb42-aa4e44f7c3d1">

The default setup of the grid does not draw the right most border
<img width="788" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/6721286/91126ed9-241e-49e3-943c-dad1e2f403c2">

this sample 
https://github.com/SyncfusionExamples/how-to-set-outer-border-for-flutter-datatable

does not solves the issue - it just draws a border around 
<img width="808" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/6721286/1b52c2f4-69a7-4e7f-9e34-352bb276c5e1">

This is what I want to achieve
<img width="820" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/6721286/50ca2435-05b6-4b1d-b1b1-1e93f27cd744">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @vasilich6107,

As of the current implementation, the left and top borders of the DataGrid are applied by default regardless of the `gridLinesVisibility` and `headerGridLinesVisibility` settings. We have taken note of the feature request to enable the drawing of the top and left borders only when the corresponding grid line visibility is specified. 

**Feedback: https://www.syncfusion.com/feedback/48012/support-for-displaying-the-left-and-top-outer-borders-when-their-respective**

**Regarding your specific requirement, we have already submitted a feature request for customizing individual cell borders in the DataGrid.** We may implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,

**Feedback: https://www.syncfusion.com/feedback/34101/support-to-customize-the-individual-cell-borders**

In the meantime, to achieve your desired border customization, you can manually set the border at the sample level as outlined in the provided KB document. Specifically, for your case, you can set the right-side border for the last column cells in the **`DataGridSource.buildRow`** method and for the last column in **`SfDataGrid.columns`.** For detailed implementation guidance, please refer to the attached sample.

<details>
<summary>Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: false,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  late EmployeeDataSource _employeeDataSource;
  late List<Employee> _employees;

  @override
  void initState() {
    super.initState();
    _employees = populateData();
    _employeeDataSource = EmployeeDataSource(_employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
      body: Padding(
        padding: const EdgeInsets.all(50),
        child: SfDataGrid(
          source: _employeeDataSource,
          gridLinesVisibility: GridLinesVisibility.horizontal,
          headerGridLinesVisibility: GridLinesVisibility.horizontal,
          columnWidthMode: ColumnWidthMode.fill,
          columns: getColumns,
        ),
      ),
    );
  }

  List<GridColumn> get getColumns {
    return <GridColumn>[
      GridColumn(
          columnName: 'ID',
          label:
              Container(alignment: Alignment.center, child: const Text('ID'))),
      GridColumn(
          columnName: 'Name',
          label: Container(
              alignment: Alignment.center, child: const Text('Name'))),
      GridColumn(
          columnName: 'Designation',
          label: Container(
              alignment: Alignment.center,
              child: const Text(
                'Designation',
                overflow: TextOverflow.ellipsis,
              ))),
      GridColumn(
          columnName: 'Salary',
          label: Container(
              decoration: const BoxDecoration(
                border: Border(
                  right: BorderSide(
                      width: 1, color: Color.fromRGBO(0, 0, 0, 0.12)),
                ),
              ),
              alignment: Alignment.center,
              child: const Text('Salary'))),
    ];
  }
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource(List<Employee> employees) {
    buildDataGridRows(employees);
  }

  List<DataGridRow> datagridRows = [];

  @override
  List<DataGridRow> get rows => datagridRows;

  void buildDataGridRows(List<Employee> employeesData) {
    datagridRows = employeesData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'ID', value: e.id),
              DataGridCell<String>(columnName: 'Name', value: e.name),
              DataGridCell<String>(
                  columnName: 'Designation', value: e.designation),
              DataGridCell<int>(columnName: 'Salary', value: e.salary),
            ]))
        .toList();
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
        decoration: getBorder(dataGridCell),
        alignment: Alignment.center,
        padding: const EdgeInsets.symmetric(horizontal: 8.0),
        child: Text(dataGridCell.value.toString()),
      );
    }).toList());
  }

  BoxDecoration? getBorder(DataGridCell dataGridCell) {
    if (dataGridCell.columnName == 'Salary') {
      return const BoxDecoration(
        border: Border(
          right: BorderSide(width: 1, color: Color.fromRGBO(0, 0, 0, 0.12)),
        ),
      );
    } else {
      return null;
    }
  }
}

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);
  final int id;
  final String name;
  final String designation;
  final int salary;
}

List<Employee> populateData() {
  return [
    Employee(10001, 'Jack Wilson', 'Manager', 150000),
    Employee(10002, 'Perry Martinez', 'Project Lead', 80000),
    Employee(10003, 'Sophia Anderson', 'Developer', 55000),
    Employee(10004, 'Roland Mendel', 'Developer', 45000),
    Employee(10005, 'Sven Ottlieb', 'UI Designer', 36000),
    Employee(10006, 'Daniel Tonini', 'Developer', 22000),
    Employee(10007, 'Mary Johnson', 'Developer', 28000),
  ];
}

```

</details>

<details>
<summary>Output Image</summary>

<img width="960" alt="Screenshot 2024-02-28 171015" src="https://github.com/syncfusion/flutter-widgets/assets/93904422/9f49e56d-a02f-4624-bbc5-39f8543101fb">

</details>

Regards,
Tamilarasan
