### ISSUE TITLE
[syncfusion_flutter_charts] Is there any migration guide from version 23 to version 24?

### ISSUE THREAD

**Issue by Macacoazul01** [syncfusion/flutter-widgets#1686]
I tried to migrate my code from `23.2.7` to the `24.x.y` version of the package but many things were replaced on this transition and the code is breaking.

Is there any migration guide or a clearer "this thing was replaced by this" than the package changelog?

**Comment by LokeshPalani** [comment]
Hi @Macacoazul01,

We have made performance improvements in our **Volume 4, 2023** release by changing the internal architecture of the charts. As a result, changes have also been made to the APIs. The details can be found below links.

Release notes - https://help.syncfusion.com/flutter/release-notes/v24.1.41?type=all
KB - https://support.syncfusion.com/en-US/kb/article/14642/release-v24141---nullability-enhancements

Please let us know if you need any further assistance.

Regards,
Lokesh P.

**Comment by Macacoazul01** [comment]
As I said, these docs doesnt help with the migration. They only help with the removed and added parts and new default values, but not in how i should migrate my code
