### ISSUE TITLE
FR - French localization of pdf viewer selection pop-up menu

### ISSUE THREAD

**Issue by B3n-d1v3** [syncfusion/flutter-widgets#1688]
Within PDF Viewer, when you select a content, a pop-up menu appears.
In this menu there are the following menu items:
* Copy
* Highlight
* Underline
* Strikethrough
* Squiggly

In French there are some errors in the translation and in the grammatical consistency, these should be corrected:
* Highlight -> Surligner
* Strikethrough -> Barrer
* Squiggly -> Onduler

**Comment by immankumarsync** [comment]
Hi @B3n-d1v3,

For localization we are use automated tools to generate the localized strings. Using the Google Translator, we will pass the English keyword and get the corresponding localization word. Also, we have attached the Google Translator screenshot for the same.

![image](https://github.com/syncfusion/flutter-widgets/assets/93641486/29e1f5e2-ffdf-4b75-a721-219073d44cb9)
![image](https://github.com/syncfusion/flutter-widgets/assets/93641486/ba6f98a8-2445-4311-ab89-963f42f491a5)
![image](https://github.com/syncfusion/flutter-widgets/assets/93641486/796fb344-a014-461e-805f-c6bed63e8ac7)

**Comment by ramkumarsync** [comment]
Could you please let us know whether the details shared in the last update are adequate or not? Also, if you need any further assistance, please feel free to contact us.

**Comment by Deepak1799** [comment]
@B3n-d1v3 As we have not heard back from you regarding the details shared in our last update, we will assume that the information provided was adequate. If you need any further assistance, please feel free to reopen this issue or create a new one.
