### ISSUE TITLE
19.1.54 release trackball tooltip on cartesian chart: behaviour change?

### ISSUE THREAD

**Issue by jonny7737** [syncfusion/flutter-widgets#169]
Did release 19.1.54 change the default behaviour for the trackball tooltip from (default) always visible on mouse over to only visible on long click?  If yes, how do I get back to the previous behaviour?

BTW: I am developing a desktop application on macOS.

The new support for names and the colored indicators look very nice.  Thank you.

Jonny

**Comment by Dharanipalani** [comment]
Hi Jonny,

We have analyzed your scenario and would like to tell you that, based on the given **activationMode** the user interactions will work for the desktop applications. Mouse hover will works if you set **activationMode** as a single tap. Mouse hover will not works if you set activation mode as double-tap or long-press. we have already fixed it and it will be included in our upcoming patch release which is expected to be rolled out on March 7, 2021. We appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi Jonny,

We are glad to inform you that we have included the reported case in the latest version of our charts. Now, the trackball will display on hovering the mouse while setting the  **activationMode** as singleTap. To resolve, please upgrade our charts to the latest version from the below link.

Latest version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.55+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.55+1)

Please revert us if you still have further concerns.

Thanks,
Dharanitharan. P
