### ISSUE TITLE
Build process failed

### ISSUE THREAD

**Issue by mathavkrishnan** [syncfusion/flutter-widgets#1694]
![image](https://github.com/syncfusion/flutter-widgets/assets/72874752/4763b7d0-bb25-4294-a036-c9178e7f4e38)

**Comment by mathavkrishnan** [comment]
This is the code
import 'dart:io';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
       
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  
  void _incrementCounter() {
    setState(() {
    
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      
      body: SfPdfViewer.asset("assets/pdf/test.pdf"),
    );
  }
}

**Comment by mathavkrishnan** [comment]
`import 'dart:io';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
       
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  
  void _incrementCounter() {
    setState(() {
    
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      
      body: SfPdfViewer.asset("assets/pdf/test.pdf"),
    );
  }
}

`

**Comment by immankumarsync** [comment]
@mathavkrishnan, We have migrated our source code to be compatible with Flutter SDK 3.19.0. In Flutter SDK version 3.19.0, they have made breaking changes to the RawKeyboardListener and replaced it with the KeyboardListener. So, we kindly request that you upgrade the Flutter SDK version to 3.19.0, or else use the package syncfusion_flutter_pdfviewer version below 24.2.7. We have also shared the breaking changes documentation below for your reference.

We hope it will help you resolve the issue. If you have any further queries, please get back to us. We are always happy to assist you.

Flutter 3.19.0 breaking changes, https://docs.flutter.dev/release/breaking-changes/key-event-migration#migrating-iskeypressed-and-related-functions

**Comment by ramkumarsync** [comment]
We believe that the issue has been resolved after upgrading to the version suggested; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.
