### ISSUE TITLE
Build failed - TextScaler - when upgraded above 22.2.12

### ISSUE THREAD

**Issue by nilshv** [syncfusion/flutter-widgets#1697]
Hello. I am currently using version 22.2.12, and that works great. But I thought of upgrading it, but then I only get a bunch of error messages. Every version above 22.2.12 gives me error. I though it maybe was my app, so I created a completly new prosject where I only included the syncfusion calendar and it also crash. I am pretty sure it isnt the code, because I copied and pased the Example code in the project. 
I have just upgraded flutter sdk to 3.19.1 
Any idea what can be wrong?
(this is just some of them, but they all seams quit like as the last error msg)

_/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-24.2.7/lib/src/calendar/sfcalendar.dart:2818:35: Error: Member not found: 'MediaQuery.textScalerOf'.
    _textScaleFactor = MediaQuery.textScalerOf(context).scale(_textScaleFactor);
                                  ^^^^^^^^^^^^
/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-24.2.7/lib/src/calendar/sfcalendar.dart:9996:23: Error: No named parameter with the name 'textScaler'.
                      textScaler: TextScaler.linear(widget.textScaleFactor),
                      ^^^^^^^^^^
/D:/Temp/Flutter/flutter_windows_2.10.3-stable/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-24.2.7/lib/src/calendar/sfcalendar.dart:10006:23: Error: No named parameter with the name 'textScaler'.
                      textScaler: TextScaler.linear(widget.textScaleFactor),
                      ^^^^^^^^^^
/D:/Temp/Flutter/flutter_windows_2.10.3-stable/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-24.2.7/lib/src/calendar/sfcalendar.dart:10786:31: Error: The getter 'TextScaler' isn't defined for the class '_ScheduleLabelPainter'.
 - '_ScheduleLabelPainter' is from 'package:syncfusion_flutter_calendar/src/calendar/sfcalendar.dart' ('/C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-24.2.7/lib/src/calendar/sfcalendar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'TextScaler'.
    _textPainter.textScaler = TextScaler.linear(textScaleFactor);_

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @nilshv,

In the Flutter SDK version 3.16, they have deprecated the textScaleFactor parameter. So, we have migrated our source compatible to the latest Flutter SDK version and we have checked and ensured the latest syncfusion_flutter_calendar version 24.2.8 with Flutter SDK version 3.19.1 and it is working fine. To avoid this you can use our syncfusion_flutter_calendar and syncfusion_flutter_datepicker version from 23.2.4 and below when having a Flutter SDK version below 3.16, after the Flutter SDK version 3.16 you can use our latest package. We have shared the related details below for your reference.

Breaking changes, https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

Regards,
Yuvaraj.

**Comment by nilshv** [comment]
Hi @Yuvaraj-Gajaraj
Thank you so much for the reply and clearing about the problem. I have upgraded Flutter SDK so now I am running latest Flutter SDK.
Flutter 3.19.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision abb292a07e (7 days ago) • 2024-02-20 14:35:05 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

But still get whole bunch of errors. Occurs at once when I import syncfusion calendar, import 'package:syncfusion_flutter_calendar/calendar.dart';
I have made a test-prosject. I have added syncfusion_flutter_calendar: ^24.2.7
If I compile with no import it runs great, but when I add the import line in my main, it crashes.

**Comment by nilshv** [comment]
This issue is solved. I guess Flutter 3.19 declared on my android studio. So what I did:
I downloaded and unzipped latest Flutter SDK  https://docs.flutter.dev/get-started/install/windows/mobile?tab=download
Then I went into File => settings => Language & Frameworks => Flutter and on right side I choose the 3 dots and selected the new flutter catalog.
I think that did the trick, but  at the same time I also did set the SDK for my flutter app (File => project structure => project=>SDK
Dont think that had anything to do with this, but I noticed I had forgot to do that. 
![27 02](https://github.com/syncfusion/flutter-widgets/assets/152852729/a84e99dd-7f61-4f37-8f5b-cd743ad01e21)

**Comment by Yuvaraj-Gajaraj** [comment]
We are happy to hear that the solution was found by yourself. If you have any further queries, please get back to us. We are always happy to assist you.

**Comment by philos3** [comment]
<img width="977" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/8424317/d8bfe113-4f10-44b1-a614-e583566c046e">
please update the Min Dart SDK limited

**Comment by philos3** [comment]
> Hi @nilshv,
> 
> In the Flutter SDK version 3.16, they have deprecated the textScaleFactor parameter. So, we have migrated our source compatible to the latest Flutter SDK version and we have checked and ensured the latest syncfusion_flutter_calendar version 24.2.8 with Flutter SDK version 3.19.1 and it is working fine. To avoid this you can use our syncfusion_flutter_calendar and syncfusion_flutter_datepicker version from 23.2.4 and below when having a Flutter SDK version below 3.16, after the Flutter SDK version 3.16 you can use our latest package. We have shared the related details below for your reference.
> 
> Breaking changes, https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor
> 
> Regards, Yuvaraj.

also need add syncfusion_flutter_core in dependency_overrides
dependency_overrides:
  syncfusion_flutter_core: 23.2.4

**Comment by LokeshPalani** [comment]
Hi @philos3, 

Will check and update the Dart SDK version for upcoming versions. Since the current version has already been published and cannot be modified. There is a user guide documentation link for the Syncfusion Compatible Package version. 


Syncfusion Compatible Package Version Link for Flutter SDK version:

https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

Regards,
Lokesh P.

**Comment by VijayakumarMariappan** [comment]
@philos3 The current minimum Dart version v2.17, is compatible with all of our current Syncfusion Flutter packages v25.2.7. Therefore, there is no need to increase the minimum Dart version at this time. Additionally, we will continue to verify the Dart version compatibility whenever we publish a new version to pub.dev.
