### ISSUE TITLE
Error updating to ^19.1.54-beta.1

### ISSUE THREAD

**Issue by pbeccegato** [syncfusion/flutter-widgets#170]
I've tried to update my pubspec.yaml as follow

```
  # syncfusion_flutter_datepicker: ^18.4.49-beta
  # syncfusion_flutter_datagrid: ^18.4.49-beta
  syncfusion_flutter_core: ^19.1.54+1
  syncfusion_flutter_datepicker: ^19.1.54-beta.1
  syncfusion_flutter_datagrid: ^19.1.54-beta.1
```
than I've got a lot of error like this:
`The method 'GridWidgetColumn' isn't defined for the type '_DocItemDataGridState'.
Try correcting the name to the name of an existing method, or defining a method named 'GridWidgetColumn'.dartundefined_method`

Set again as follow: 

```
  syncfusion_flutter_datepicker: ^18.4.49-beta
  syncfusion_flutter_datagrid: ^18.4.49-beta
  # syncfusion_flutter_core: ^19.1.54+1
  # syncfusion_flutter_datepicker: ^19.1.54-beta.1
  # syncfusion_flutter_datagrid: ^19.1.54-beta.1
```
Everything works fine.

What's wrong?

**Comment by NeelakandanKannan** [comment]
Hi @pbeccegato ,

Greetings from Syncfusion.

We have made API breakings in 2021 Volume 1 release to make the data row creation process more Flutter-idiomatic and expressive. GridWidgetColumn will not be available from 2021 Volume 1 release. We have documented all the API breaking changes and example of new API structure in below blog,

https://www.syncfusion.com/blogs/post/api-breaking-changes-in-flutter-datagrid-in-2021-volume-1.aspx

We request you to go through the above blog and let us know if you need further assistance.
