### ISSUE TITLE
[syncfusion_flutter_calendar] Taxt scale factor works incorrectly for dates

### ISSUE THREAD

**Issue by Mounix99** [syncfusion/flutter-widgets#1701]
It seems that the dates have a scaling factor that increases every time the user rotates the device, I noticed that hot reload triggers this issue too 

https://github.com/syncfusion/flutter-widgets/assets/64007188/563c5637-7536-4939-a5ca-d85d2bc9a547

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Mounix99 ,

We would like to let you know that the reported issue is already fixed and it will be rolled out in our Volume 1 main release which is expected to be rolled out on the 3rd week of March. We will update here once the release has been rolled out and we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Mounix99** [comment]
> update

Sounds good! Another problem that I'm blocked from updating cause package requires last Flutter stable version) but still thanks!

**Comment by Yuvaraj-Gajaraj** [comment]
We will migrate our source for every Flutter SDK version release based on API deprecation and linter warnings.  We have shared the breaking changes of Flutter SDK in 3.16 and 3.19 for your reference.

Breaking changes 3.19 - https://docs.flutter.dev/release/breaking-changes#released-in-flutter-319

Breaking changes 3.16 - https://docs.flutter.dev/release/breaking-changes#released-in-flutter-316

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue has been already fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_datepicker/versions/25.1.35
