### ISSUE TITLE
[syncfusion_flutter_datagrid] I think loadMoreViewBuilder is somewhat opinionated

### ISSUE THREAD

**Issue by dolbin-prime** [syncfusion/flutter-widgets#1704]
Hi, I'm using `syncfusion_flutter_datagrid: ^24.1.47`.

IMHO, `loadMoreViewBuilder` property is opinionated.

According to the [example code](https://help.syncfusion.com/flutter/datagrid/load-more#infinite-scrolling) for **Infinite scrolling**,

```dart
    ....
    loadMoreViewBuilder: (BuildContext context, LoadMoreRows loadMoreRows) {
        Future<String> loadRows() async {
          await loadMoreRows();
          return Future<String>.value('Completed');
        }

        return FutureBuilder<String>(
            initialData: 'loading',
            future: loadRows(),
            builder: (context, snapShot) {
              if (snapShot.data == 'loading') {
    ....
```
I have to use a `FutureBuilder` to implement infinite scrolling, because I can't control the event that causes 'load more'. So I cannot use `Bloc` with this, which means I cannot separate business logic from the view. The problem is solved when I build a [load more button](https://help.syncfusion.com/flutter/datagrid/load-more#load-more-button) because I can use `onTap` property of the button, but I prefer infinite scrolling to a load more button.

I think it will be better if props are something like the following:
```dart
loadMoreViewBuilder: (BuildContext context, LoadMoreRows loadMoreRows){
   //build a widget for load more
},
onLoadMore: (BuildContext context) {
  //handle load more event
  context.read<MyBloc>().add(MyBlocEvent());
}
```

But, this problem may be due to my lack of Flutter knowledge, so if there is a way to use `Bloc` to implement infinite scrolling, please let me know.

Thank you for your support!

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime ,

To further assist you and better understand your expectations, we kindly request that you provide any additional details or steps that may help us fulfill your needs. Additionally, we kindly request that you modify the attached sample to reflect the expected behavior and provide additional details. This will greatly assist us in investigating and providing an appropriate solution as quickly as possible.

- **Sample :** 

    [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14768854/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment]
Hi @abineshPalanisamy, sorry for the late response,

I think it will be okay if I use RiverPod rather than BLoC. So please never mind, it was not that big problem! 🙈

**Comment by ashok-kuvaraja** [comment]
Hi @dolbin-prime,

We hope that the reported issue is resolved in your end. We are closing this issue now. If you need any further assistance, kindly reopen this ticket. We are always happy to help you.

Regards,
Ashok K

**Comment by vgavrilovikj** [comment]
Did anyone find a workaround with BLoC? I am using BLoC throughout the whole app and am looking to implement this.. @dolbin-prime
