### ISSUE TITLE
[syncfusion_flutter_signaturepad] Add undo redo feature for more convenience 

### ISSUE THREAD

**Issue by rajnishsharma1** [syncfusion/flutter-widgets#1706]
While the signature pad is perfectly made, it is missing one important feature, user tend to make a lot of error while signing, a undo and redo feature will be very convenient and make the feature easy to use.

**Comment by ThilipChandru** [comment]
Hi @rajnishsharma1,

At this time, we do not have a specific timeline for when this feature will be implemented as our development priorities are determined by customer demand. During the planning stage for each release cycle, we will review all open features and identify which ones to implement based on specific parameters including product vision, technological feasibility, and customer interest. We will inform you once this feature is implemented. We appreciate your patience in the meantime.

If you have any additional specifications or suggestions for this feature request, feel free to leave them in the comments section of the feedback link. This will help us understand how you would like to use it and how we can improve it.

Feed back link :  https://www.syncfusion.com/feedback/51474/provide-undo-and-redo-option-in-the-signaturepad



Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Hi @rajnishsharma1 ,

This is an uncertain feature, so we are closing this ticket. Please follow up with the FR.
Feedback link : https://www.syncfusion.com/feedback/51474/provide-undo-and-redo-option-in-the-signaturepad
