### ISSUE TITLE
Major bug on tap events on grouping enabled

### ISSUE THREAD

**Issue by berslen** [syncfusion/flutter-widgets#1708]
When grouping enabled the group header is clickable as in like data rows. But there is no way to determine if the clicked row is group header or not. I tried to solve it with custom selection manager but it also has no information about the clicked row is group header or not.

My aim is that grouping enabled, multiselection enabled, custom row secondary click event callback and custom row click event 

My suggestion would be RowSelectionManager should provide handleGroupHeaderTap dedicated for group headers. It should not fire handeTap if group header is tapped. The necessary callbacks on SfDataGrid should also be updated with such details and provide onRowTap, onRowSecondaryTap, onGroupHeaderTap etc.

If you need more details on this topic feel free to comment

**Comment by berslen** [comment]
I tried the following logic which works correctly for the first group's items but if there are more than 1 group in the data, each group header's are clicked according to this logic like a row. And the index is shift meaning that the item that you click is actually the item below after the second grouping

`onCellTap: (details){
if(details.rowColumIndex.rowIndex != (groupColumn != null ? 1 : 0)){
final selectedRowIndex = details.rowColumnIndex.rowIndex - (groupColumn != null ? 2 :1 );
//logic for handling row click for selectedRow by index
}
}`

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,

You can follow up further on this feature through the feedback link. We are closing this ticket now. If you need any further assistance, feel free to reopen this ticket. We are always happy to help you.

Regards,
Ashok K
