### ISSUE TITLE
how to use Styling in DataGird

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#171]
![flutter-datagrid-styling (1)](https://user-images.githubusercontent.com/60202661/113412251-175a6e00-93b8-11eb-9e5e-2f1639b76874.png)

i want to do this

**Comment by NeelakandanKannan** [comment]
Hi @Joseph-Nathan ,

Greetings from Syncfusion.

You can set the row background conditionally by using the [DataGridRowAdapter.color](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridRowAdapter/color.html) property. You can refer the below UG documentation.

https://help.syncfusion.com/flutter/datagrid/conditional-styling#styling-based-on-content-1

Also, you can refer the below Sample Browser example,
https://github.com/syncfusion/flutter-examples/tree/master/lib/samples/datagrid/apperance/styling

**Comment by fathah** [comment]
How can I change the selected row background color?

**Comment by RenugaSadagoban98** [comment]
Hi @fathah,
Thanks for your update.

You can set the selected row background color by using the selectionColor property of SfDataGridThemeData in SfDataGridTheme.

Refer to the following UG documentation,
**UG Link:** https://help.syncfusion.com/flutter/datagrid/selection#appearance

Please let us know if need any further assistance. 

Regards,
Renuga devi S
