### ISSUE TITLE
SFCalendar gets smaller everytime i background the app

### ISSUE THREAD

**Issue by crobertson247** [syncfusion/flutter-widgets#1711]
Everytime i background my app and reopen it, the text and everything else on the calendar gets smaller and smaller until its no longer readable and then i need to go to another screen and back to get the text size back to normal, how can i fix this? 
My code for SFCalendar:
```
SfCalendar(
    view: CalendarView.schedule,
    dataSource: AppointmentDataSource(events),
    onTap: (CalendarTapDetails details) {
      /*if (details.targetElement ==
          CalendarElement.calendarCell) {
        // Tap on a calendar cell
        print('Tapped on date: ${details.date}');
      } else */
      if (details.targetElement ==
          CalendarElement.appointment) {
        // Tap on an appointment
        _handleAppointmentTap(details);
      }
    },
    allowAppointmentResize: false,
    headerStyle: const CalendarHeaderStyle(
        backgroundColor: Colors.black,
        textStyle: TextStyle(color: Colors.white)),
    scheduleViewSettings: ScheduleViewSettings(
        monthHeaderSettings: const MonthHeaderSettings(
            monthFormat: 'MMMM, yyyy',
            height: 120,
            textAlign: TextAlign.center,
            backgroundColor: Colors.black,
            monthTextStyle: TextStyle(
              color: Colors.white,
              fontSize: 25,
              fontWeight: FontWeight.w400,
            )),
        appointmentTextStyle: TextStyle(
          color: Theme.of(context).primaryColorLight,
        )),
  )
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @crobertson247 ,

We would like to let you know that the reported issue is already fixed and it will be rolled out in our Volume 1 main release which is expected to be rolled out on the 3rd week of March. We will update here once the release has been rolled out and we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue has been already fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_datepicker/versions/25.1.35

**Comment by crobertson247** [comment]
Hi @Yuvaraj-Gajaraj, I just upgraded the package but I get the following error:
`
../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-25.1.35/lib/src/calendar/common/calendar_view_helper.dart:750:35: Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.    
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('/C:/src/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAltPressed'.
    if (HardwareKeyboard.instance.isAltPressed) {

../../../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_calendar-25.1.35/lib/src/calendar/views/calendar_view.dart:4442:35: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('/C:/src/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    if (HardwareKeyboard.instance.isShiftPressed) {
`

**Comment by crobertson247** [comment]
Update: I upgraded flutter and it seemed to resolve the issue
