### ISSUE TITLE
[syncfusion_flutter_charts] Poor performance when upgrade to lastest verion.

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1712]
I have a large screen with almost 20 charts. I work fine in ListView but when i upgrade the version of package from 24.1.41 to the latest version. It's super lag when scroll and my web is almost freezed.

I hope this issue is will be fix soon. I apologize for not being able to provide sample source code.
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/dd9bed04-6adc-4c0e-9447-b7fe9f7fe723)

**Comment by NgoTruongThanh** [comment]
I have the same isuse in this video

This video i used  syncfusion_flutter_charts: ^21.2.9 with good performance
[Recording 2024-03-05 092938.zip](https://github.com/syncfusion/flutter-widgets/files/14489550/Recording.2024-03-05.092938.zip)

And this is syncfusion_flutter_datagrid: ^24.2.8 with bad performance 
[Recording 2024-03-05 092453.zip](https://github.com/syncfusion/flutter-widgets/files/14489567/Recording.2024-03-05.092453.zip)

**Comment by Trung15010802** [comment]
> Refere
I can't download the source code
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/dbf7e374-a176-4d53-8b88-f8a66297712f)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.
