### ISSUE TITLE
[Feature] SFDataGrid should provide onSortChanged callback

### ISSUE THREAD

**Issue by berslen** [syncfusion/flutter-widgets#1713]
Just like a filter, when sorting changed onSortChanged callback should fire.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @berslen,

We have already considered your request as a feature. We may implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,

**Feedback Link: [50455](https://www.syncfusion.com/feedback/50455/support-for-sort-callbacks-that-allow-sorting-the-column-and-retrieving-sorting)**

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,

You can follow up further on this feature through the feedback link. We are closing this ticket now. If you need any further assistance, feel free to reopen this ticket. We are always happy to help you.

Regards,
Ashok K
