### ISSUE TITLE
textScaler error

### ISSUE THREAD

**Issue by AgMarwanAg** [syncfusion/flutter-widgets#1714]
my app get this error when I try to run my app
`../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-24.2.8/lib/src/charts/utils/helper.dart:72:35: Error: Couldn't find constructor 'TextScaler.linear'.
                textScaler: const TextScaler.linear(1.2),`
                
Problem solved when i deleted the `textScaler: const TextScaler.linear(1.2),` from the helper class inside the code of the library ,
by the way the code is working fine on my other machine and both my machines has same flutter version "3.19.2"

**Comment by khanh307** [comment]
you try downgrade to version 22.2.12

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details to proceed further on this.

**Comment by AgMarwanAg** [comment]
still get this error when run
`../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-24.2.8/lib/src/charts/utils/helper.dart:72:35: Error: Couldn't find constructor 'TextScaler.linear'.
                textScaler: const TextScaler.linear(1.2),
                                  ^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-24.2.8/lib/src/charts/utils/helper.dart:72:17: Error: No named parameter with the name 'textScaler'.
                textScaler: const TextScaler.linear(1.2),`

**Comment by LokeshPalani** [comment]
Hi @AgMarwanAg,

 
We have ensured with the Flutter SDK version 3.19.2  in [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) and it was working fine at our end. We suspect that your Flutter SDK version path is not updated properly in your IDE. So, we kindly request you to cross check the Flutter SDK version path in your IDE and let us know.

 
Regards,
Lokesh P.
