### ISSUE TITLE
Null check operator used on a null value internal issue

### ISSUE THREAD

**Issue by iBog** [syncfusion/flutter-widgets#172]
Reproduced on SfCartesianChart after moving to next (cover current) widget page, then Back to page with chart.
Version: syncfusion_flutter_charts: ^19.1.54+1
Flutter (Channel beta, 2.1.0-12.2.pre, on Microsoft Windows [Version 10.0.19042.867], locale ru-BY)
Project compiled without sound null safety

The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  SfCartesianChart file:///E:/work/Project/lib/widgets/wave_chart.dart:83:13
When the exception was thrown, this was the stack: 
#0      _SplineRangeAreaChartPainter.paint (package:syncfusion_flutter_charts/src/chart/series_painter/spline_range_area_painter.dart:151:50)
#1      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:13)
#2      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:604:7)
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
#4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)

**Comment by iBog** [comment]
Chart widget in my source:

SfCartesianChart(
              margin: const EdgeInsets.only(
                  top: Consts.padding / 2, bottom: 0, left: 0, right: 0),
              plotAreaBorderWidth: 0,
              // title: ChartTitle(text: 'Title'),
              // legend: Legend(isVisible: true),
              series: _chartData,
              enableAxisAnimation: true,
              tooltipBehavior: TooltipBehavior(enable: true),
              primaryXAxis: NumericAxis(isVisible: false),
              primaryYAxis:
                  NumericAxis(isVisible: false, minimum: 0.0, maximum: 1.0),
            )
            
            List<XyDataSeries<ChartValue, int>> _chartData = 
             [
      SplineRangeAreaSeries<ChartValue, int>(
        enableTooltip: false,
        animationDuration: 200,
        dataSource: pointsFirst,
        xValueMapper: (ChartValue val, _) => val.index,
        highValueMapper: (ChartValue val, _) => val.amp,
        lowValueMapper: (ChartValue val, _) => 0.0,
        gradient: _firstGradient,
      )]
      
      final LinearGradient _firstGradient = LinearGradient(
    colors: <Color>[
      TripleWaveChart.waveColorTop.withOpacity(1.0),
      TripleWaveChart.waveColorBottom.withOpacity(1.0),
    ],
    stops: <double>[0.0, 1.0],
    transform: GradientRotation(90 * (3.14 / 180)),
  );

**Comment by Dharanipalani** [comment]
Hi @iBog,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and unable to replicate the reported scenario at our end. We checked with both stable and beta channels with both sound and unsound null safety, the spline range area series did not throw any exception while going to the new page and back to the chart. So, we attached the sample for your reference, please revert us the replicated issue in this sample. It will help us to resolve and provide the solution to you sooner.

Sample: [I322415-spline-range-area-null-safety-issues.zip](https://github.com/syncfusion/flutter-widgets/files/6264219/I322415-spline-range-area-null-safety-issues.zip)


Thanks,
Dharanitharan. P

**Comment by mazzonem** [comment]
I can confirm this is still happening in the version 19.1.66 👍 Do I need to duplicate this issue?

**Comment by Rameshfly** [comment]
In the latest version also, this issue came "Null check operator used on a null value" while event coming with date range and one day..!!!

**Comment by Goncharo** [comment]
Can also confirm this is *still* happening on version `19.2.62`, raised a new issue here: https://github.com/syncfusion/flutter-widgets/issues/447 , as this one was closed.

**Comment by emrgry** [comment]
I can confirm this as well on version 20.0.45

**Comment by bradintheusa** [comment]
I can confirm this as well on version 20.4.49

**Comment by vtharmalingam** [comment]
I also see this nasty issue with my experiments with this chart lib. I researched further on both Google and in the open/closed list of issues. But for every issue reported on this (with reference to various charts), the team is consistently seen saying "Not reproducible, please check the .zip". There is, indeed, an internal error and the team does not seem to have clue how to solve this?! The length of the stack trace is 60+ calls, and it is too difficult to understand whether it is to do with rendering axis animation, construction, rendering, or else. though I appreciate the work done by the team, it seems I cannot totally rely on the library as it causes an issue like this and may lead to "make-or-break" situation!

**Comment by bradintheusa** [comment]
For me this issue happened when I manipulated the chart data in the build method. Once I stopped doing that my issue stopped.

**Comment by vtharmalingam** [comment]
Thanks for sharing. Surprisingly, the chart (Candle chart) works perfectly with static data (i.e., loading from a file), but when I load exactly the same data (and formatted the same way) from the REST endpoint and pass that to the chart inside "didChangeDependencies", I get the error!! I spent all that I could do to corner the issue by removing all other differences between static and REST sources in every way - just to ensure there is absolutely no difference at my code level. But the lib keeps behaving differently. It is consistent in throwing that error :(

**Comment by vtharmalingam** [comment]
Sure, will check it out. Thank you, really appreciate your input!
