### ISSUE TITLE
 default margin applied to the page.

### ISSUE THREAD

**Issue by DeveloperAdam** [syncfusion/flutter-widgets#1720]
I am designing PDF but i'm unable to meet the design provided by the UI/UX through syncfusion as there is default margin applied to the pdfpage.page. There should not be it should be customize

**Comment by jeyalakshmit** [comment]
We can customize the PDF page margin using our PdfMargins API. Kindly add the following code before adding page to the PDF document.
`document.pageSettings.margins.all = 0;`
Please refer to the UG documentation for further details.
https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPageSettings/margins.html
