### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by ncumisaD** [syncfusion/flutter-widgets#1722]
I get this error when I run:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10632:42: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('/C:/src/flutter_windows_3.13.9-stable/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    } else if (HardwareKeyboard.instance.isShiftPressed &&
                                         ^^^^^^^^^^^^^^

**Comment by mellowcello77** [comment]
Same issue, first time use, confused.

**Comment by ncumisaD** [comment]
@mellowcello77 I take it you haven't gotten the solution yet. If not hopefully we will get one soon.

**Comment by mellowcello77** [comment]
@ncumisaD I downgraded to 23.1.36, my needs are super basic at the moment. I hope so yes.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ncumisaD ,

We have migrated our source which is compatible with Flutter SDK 3.19.0, in Flutter SDK version 3.19.0 they have done breaking changes in the RawKeyEvent and replaced it with HardWareKeyBoard. So, we kindly request you to upgrade the Flutter SDK version to 3.19.0 or else use the packages syncfusion_flutter_datepicker version below 24.2.7. We have also shared the breaking changes documentation below for your reference.

We hope it will help you to resolve the issue, if you have any further queries please get back to us. We are always happy to assist you.

Flutter 3.19.0 breaking change, https://docs.flutter.dev/release/breaking-changes/key-event-migration#migrating-iskeypressed-and-related-functions

Regards,
Yuvaraj.

**Comment by ncumisaD** [comment]
Thank you so much for getting back to me with a solution, I truly appreciate it @Yuvaraj-Gajaraj
