### ISSUE TITLE
[syncfusion_flutter_charts] Wrong rendering of column width with date-time axis

### ISSUE THREAD

**Issue by ThomLen** [syncfusion/flutter-widgets#1723]
When setting an minimum and maximum at DateTimeAxis and only several dates are proven, the bars are rendered way too wide. In the Example, the bars have a range over 10 days (instead of one day)

![syncf-bug-column-1](https://github.com/syncfusion/flutter-widgets/assets/88825472/4d451303-a461-41d6-99e7-f510c34b87b0)
<img width="636" alt="syncf-bug-column-2" src="https://github.com/syncfusion/flutter-widgets/assets/88825472/8a16d35e-4d7c-44e8-aa94-e3cebfef4560">

syncfusion test file:
[main.dart.zip](https://github.com/syncfusion/flutter-widgets/files/14539485/main.dart.zip)

**Comment by ThomLen** [comment]
Hi Preethika,
thanks for your replay. 
My use case is very simple. On a date range of the last 28 days we have a x-axis with these 28 days. The customer has e.g. 3 events in this period. The colums bars are not shown at the 3 dates but as 3 events with a range of e.g. 4 days each. This looks like a big bug to the customer, doesn't it?
I have no way to fix this through settings.

Regards, Thomas

**Comment by LokeshPalani** [comment]
Hi,

 

We have prepared a workaround sample for your requirement by using the custom column series renderer through the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback. If there are more than one data points in the series, the segment width will be decreased for the respective axis labels. We calculated the segment width by determining the difference between the previous axis label and the next label. Furthermore, we reduced the segment width by calculating the difference between the minimum and maximum range using series.sbsinfo, [width](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries/width.html), and [spacing](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries/spacing.html) in the [ColumnSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html). We have shared code snippet, screenshot, and sample for your reference. Please let us know if you need any further needs.

Code Snippet:

``` dart
@override
  void transformValues() {
    if (series.dataCount > 1) {
      List<AxisLabel> labels = series.xAxis!.visibleLabels;
      int length = labels.length;
      int index = -1;
      for (int i = 0; i < length; i++) {
        if (labels[i].value == x) {
          index = i;
          break;
        }
      }
      if (index > -1) {
        num diff = index > 1
            ? x - labels[index - 1].value
            : labels[index + 1].value - x;
        series.sbsInfo.minimum = -diff * series.width + series.spacing;
        series.sbsInfo.maximum = diff * series.width + series.spacing;
      }
    }
    super.transformValues();
  }

```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/4f7c9b23-c0fa-4fb6-9e30-8a9c66a77e26)

Regards,
Lokesh P.


[github_1723.zip](https://github.com/syncfusion/flutter-widgets/files/14855765/github_1723.zip)
