### ISSUE TITLE
When I add syncfusion_flutter_datepicker, it gives exception and does not work, but when I download a version  22.2.12 , it works without any error

### ISSUE THREAD

**Issue by Gaith-Kozali** [syncfusion/flutter-widgets#1724]
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10064:35: Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAltPressed'.
    if (HardwareKeyboard.instance.isAltPressed) {
                                  ^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10108:35: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
        HardwareKeyboard.instance.isShiftPressed) {
                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10131:35: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
        HardwareKeyboard.instance.isShiftPressed) {
                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10320:35: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    if (HardwareKeyboard.instance.isShiftPressed &&
                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10335:35: Error: The getter 'isControlPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isControlPressed'.
    if (HardwareKeyboard.instance.isControlPressed) {
                                  ^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10563:35: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    if (HardwareKeyboard.instance.isShiftPressed &&
                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10586:42: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    } else if (HardwareKeyboard.instance.isShiftPressed &&
                                         ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10609:42: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    } else if (HardwareKeyboard.instance.isShiftPressed &&
                                         ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_datepicker-24.2.9/lib/src/date_picker/date_picker.dart:10632:42: Error: The getter 'isShiftPressed' isn't defined for the class 'HardwareKeyboard'.
 - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../AppData/Local/Android/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'isShiftPressed'.
    } else if (HardwareKeyboard.instance.isShiftPressed &&
                                         ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Gaith\AppData\Local\Android\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1
my flutter sdk :  3.16.1
dart sdk : 3.2.1

**Comment by luisotavio-dev** [comment]
I have the same problem compiling for MacOS Sonoma 14.4, using version 24.2.6 it works, but on 24.2.9 the same error occurs.

**Comment by cybertheory** [comment]
can confirm this worked

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @cybertheory ,

As we stated earlier we have migrated our control which is compatible with Flutter SDK version 3.19, so we suggest using our package version below 24.2.7. Also, we have ensured that our package version is below 24.2.7 with the Flutter SDK version 3.16.1 and confirmed all are working fine.

We have shared the screenshot below for your reference, if you have any further queries please get back to us, we are always happy to assist you.

Screenshot:
![image](https://github.com/syncfusion/flutter-widgets/assets/61863686/8e800369-110b-4224-a512-92a21a895112)


Regards,
Yuvaraj.
