### ISSUE TITLE
groupCaptionTitleFormat Title not showing in new Group Feature

### ISSUE THREAD

**Issue by olgeestuff** [syncfusion/flutter-widgets#1725]
I used groupCaptionTitleFormat: '{ColumnName} : {Key} - {ItemsCount} Item(s)',

`late UsersProductsDataSource _dataSource;

  @override
  void initState() {
    super.initState();
    _dataSource = UsersProductsDataSource(widget.ndata);
    _dataSource.addColumnGroup(
      ColumnGroup(
        name: 'vMnthAndYrInString',
        //columnName: 'vMnthAndYrInString',
        sortGroupRows: true,
        // sortDirection: DataGridSortDirection.ascending),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return SfDataGrid(
      source: _dataSource,
      columns: [
        GridColumn(
          columnName: 'productName',
          label: Container(
            padding: const EdgeInsets.all(8.0),
            alignment: Alignment.center,
            child: const Text('Product Name'),
          ),
        ),
        GridColumn(
          columnName: 'productBrand',
          label: Container(
            padding: const EdgeInsets.all(8.0),
            alignment: Alignment.center,
            child: const Text('Product Brand'),
          ),
        ),
        GridColumn(
          columnName: 'vMnthAndYrInString',
          label: Container(
            padding: const EdgeInsets.all(8.0),
            alignment: Alignment.center,
            child: const Text('Date Of Entry'),
          ),
        ),
      ],
      gridLinesVisibility: GridLinesVisibility.both,
      headerGridLinesVisibility: GridLinesVisibility.both,
      //allowGroupingRows: true,
      allowExpandCollapseGroup: true,
      // groupCaptionTitleFormat: 'vMnthAndYrInString',
      //groupCaptionTitleFormat: '{ColumnGroup} : {Key} – {ItemsCount} Items',
      //groupCaptionTitleFormat: 'Group: {Key} (Count: {ItemsCount})',

      ///from sample code
      selectionMode: SelectionMode.multiple,
      navigationMode: GridNavigationMode.cell,
      groupCaptionTitleFormat: '{ColumnName} : {Key} - {ItemsCount} Item(s)',
    );
  }
}`

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @olgeestuff 

We have thoroughly investigated the provided sample and conducted extensive testing, but we were unable to reproduce the reported issue on our end. The **`groupCaptionTitleFormat`** appears to be correctly displayed in the group caption summary row as expected.

It's important to note that by default, the DataGrid does not display the group's caption summary value. To showcase the caption summary value, you need to override the **[DataGridSource.buildGroupCaptionCellWidget](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/buildGroupCaptionCellWidget.html)** method. This method receives the caption summary value as a parameter, and you must return the appropriate widget containing the summary value.

Please ensure that you have properly implemented this method on your end. We have attached a sample that we tested on our end for your reference.

<details>
<summary>Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const SfDataGridDemo(),
    );
  }
}

class SfDataGridDemo extends StatefulWidget {
  const SfDataGridDemo({super.key});

  @override
  State<SfDataGridDemo> createState() => SfDataGridDemoState();
}

class SfDataGridDemoState extends State<SfDataGridDemo> {
  List<Employee> employees = <Employee>[];
  late EmployeeDataSource employeeDataSource;

  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
    employeeDataSource
        .addColumnGroup(ColumnGroup(name: 'Designation', sortGroupRows: true));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
      body: SfDataGrid(
        source: employeeDataSource,
        allowExpandCollapseGroup: true,
        groupCaptionTitleFormat: '{ColumnName} : {Key} - {ItemsCount} Item(s)',
        columns: <GridColumn>[
          GridColumn(
              columnName: 'ID',
              label: Container(
                  padding: const EdgeInsets.all(8),
                  alignment: Alignment.center,
                  child: const Text('ID'))),
          GridColumn(
              columnName: 'Name',
              label: Container(
                  padding: const EdgeInsets.all(8),
                  alignment: Alignment.center,
                  child: const Text('Name'))),
          GridColumn(
              columnName: 'Designation',
              label: Container(
                  padding: const EdgeInsets.all(8),
                  alignment: Alignment.center,
                  child: const Text('Designation',
                      overflow: TextOverflow.ellipsis))),
          GridColumn(
              columnName: 'Salary',
              label: Container(
                  padding: const EdgeInsets.all(8),
                  alignment: Alignment.center,
                  child: const Text('Salary'))),
        ],
        columnWidthMode: ColumnWidthMode.fill,
      ),
    );
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'Jack', 'Manager', 150000),
      Employee(10002, 'Perry', 'Project Lead', 80000),
      Employee(10003, 'James', 'Developer', 55000),
      Employee(10004, 'Michael', 'Designer', 39000),
      Employee(10005, 'Roland Mendel', 'Developer', 45000),
      Employee(10006, 'Sven Ottlieb', 'UI Designer', 36000),
      Employee(10007, 'Williams', 'Developer', 44000),
      Employee(10008, 'Adams', 'Developer', 43000),
      Employee(10009, 'Edwards', 'QA Testing', 43000),
      Employee(10010, 'Grimes', 'Developer', 43000),
      Employee(10011, 'Maria Andres', 'Developer', 41000),
      Employee(10012, 'Thomas Hardy', 'Developer', 40000),
      Employee(10013, 'Hanna Moos', 'Sales Associate', 350000),
      Employee(10014, 'Elizabeth', 'Developer', 41000),
      Employee(10015, 'Patricio Simpson', 'Administrator', 33000),
      Employee(10016, 'Francisco Chang', 'Developer', 32000),
      Employee(10017, 'Yang Wang', 'Developer', 30000),
      Employee(10018, 'Peter Franken', 'Developer', 30000),
      Employee(10019, 'Carlos Schmitt', 'Developer', 30000),
      Employee(10020, 'Yoshi Latimer', 'Developer', 28000),
    ];
  }
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource({required List<Employee> employeeData}) {
    dataGridRows = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'ID', value: e.id),
              DataGridCell<String>(columnName: 'Name', value: e.name),
              DataGridCell<String>(
                  columnName: 'Designation', value: e.designation),
              DataGridCell<double>(columnName: 'Salary', value: e.salary),
            ]))
        .toList();
  }

  List<DataGridRow> dataGridRows = [];

  @override
  List<DataGridRow> get rows => dataGridRows;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(8),
        child: Text(
          e.value.toString(),
        ),
      );
    }).toList());
  }

  @override
  Widget? buildGroupCaptionCellWidget(
      RowColumnIndex rowColumnIndex, String summaryValue) {
    return Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 15),
        child: Text(summaryValue));
  }
}

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);

  final int id;
  final String name;
  final String designation;
  final double salary;
}

```
</details>

<details>
<summary>Output</summary>
<img width="960" alt="Screenshot 2024-03-12 132624" src="https://github.com/syncfusion/flutter-widgets/assets/93904422/21999466-35c5-458e-9db7-77c4925b4df7">
</details>

Regards,
Tamilarasan

**Comment by olgeestuff** [comment]
ok thanks so much it worked. 🙌🙌🙌🙌

what was missing in my code was this part

` @override
  Widget? buildGroupCaptionCellWidget(
      RowColumnIndex rowColumnIndex, String summaryValue) {
    return Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 15),
        child: Text(summaryValue));
  }
}`

it was kinda not "out there" when i copied from your  sample code ...
THANKS SO MUCH....UR AMAZING
