### ISSUE TITLE
error HardwareKeyboard

### ISSUE THREAD

**Issue by blackpink7** [syncfusion/flutter-widgets#1726]
Error (Xcode): ../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datagrid-24.2.9/lib/src/datagrid_widget/selection/selection_manager.dart:968:37: Error: The getter 'isControlPressed' isn't defined for the class 'HardwareKeyboard'.

**Comment by deniscass** [comment]
Same issues here. All working fine, but i need run a flutter pub upgrade and upgdate syncfusion datagrid to 24.2.9 and i get this issue

**Comment by ashok-kuvaraja** [comment]
Hi @blackpink7,

We suspect that the reported issue has been resolved at your end. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
