### ISSUE TITLE
Signature is not smooth in iOS drawing

### ISSUE THREAD

**Issue by ayechan-maung** [syncfusion/flutter-widgets#1728]
SfSignature is not smooth in iOS drawing 

```
SfSignaturePad(
  key: signaturePadKey,
  minimumStrokeWidth: 2,
  maximumStrokeWidth: 4,
  strokeColor: Colors.black,
  backgroundColor: Colors.white,
  onDraw: (offset, time) {
    
  },
  onDrawEnd: () {
    
  },
)

**Comment by Aboneyx** [comment]
Yes, when drawing, the application starts to lag, freeze

**Comment by Aboneyx** [comment]
https://github.com/syncfusion/flutter-widgets/assets/79087226/c14408f2-52d1-4324-9f82-0ddc95eb320e

iOS version 17.4. I launched the app in release mode.
Everything works fine on android

**Comment by Hammadbinnaeem** [comment]
I think this is the same issue
https://github.com/syncfusion/flutter-widgets/issues/1666
