### ISSUE TITLE
[syncfusion_flutter_charts] ChartTitle alignment for multiline titles

### ISSUE THREAD

**Issue by Knupper** [syncfusion/flutter-widgets#1729]
Hey,

we have an issue with the ChartTitle alignment for multiline texts. 

### Steps to reproduce:

```
SfCartesianChart(
      title: ChartTitle(
        text: 'Very long title that it breaks in multiple lines to demonstrate the bug for syncfusion. As this is maybe not long enough here is some more dummy text,
        alignment: ChartAlignment.far,
      ),
  ....
  );
```

### Actual result:
![image](https://github.com/syncfusion/flutter-widgets/assets/8080117/fd1affd8-6f17-49c3-a245-e27c9bf88d9e)
One Line Headlines are looking good, if we go two a multiline headline it is centered again.

### Expected:
If we use Alignment.near or Alignment.far, the text should always left or right aligned independent of the line count.

I hope that are enough information for you to take a look into it. 

Greetings Max

**Comment by Knupper** [comment]
@PreethikaSelvam thank you for your reply. Why is it not possible to align the text in a multi line scenario as well? So that we can decide if we want a centered title like:

```
      centered long line
               title
```
or move it to the start or end

```
centered long line
title
```

As far as i know the Text element in flutter has the option to manipulate the text alignment over the attribute `textAlign` sth. similar would be amazing to see in your packages as well.

Greetings

Max

**Comment by LokeshPalani** [comment]
Hi @Knupper,


Currently, there is no option to achieve your requirement in [Chart title](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/title.html), however you can achieve it by designing chart title on your own by wrapping [Text](https://api.flutter.dev/flutter/widgets/Text-class.html) and [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) within a [Column ](https://api.flutter.dev/flutter/widgets/Column-class.html)widget.



Regards,
Lokesh P.
