### ISSUE TITLE
How to show tooltip in data Gride

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#173]
Dear Team,
You are doing great work for us, I am facing some issue my Text name inside grid is large thats why give some solution to show tooltip or hover when i am calling **SelectionMode**  class inside, i am sharing sample picture for you clearens

<img width="218" alt="Screen Shot 2021-04-06 at 1 29 20 PM" src="https://user-images.githubusercontent.com/65191117/113682961-1fc6e780-96dd-11eb-9102-6667315e3e95.png">

**Comment by RenugaSadagoban98** [comment]
Hi @waqaryounusjatt788, 

Greetings from Syncfusion.

If you want to show the tooltip for cells, you can wrap the Text widget to the Tooltip widget when loading from buildRow method. When you long press the grid cells, tooltip will be shown with the cell value. 

Please refer the following code snippet

```

@override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataCell) {
      return Container(
        padding: EdgeInsets.symmetric(horizontal: 16),
        alignment: Alignment.center,
        child: Tooltip(
            padding: EdgeInsets.symmetric(horizontal: 16),
            message: dataCell.value.toString(),
            decoration: BoxDecoration(color: Colors.blue),
            child: Text(
              dataCell.value.toString(),
              overflow: TextOverflow.ellipsis,
            )),
      );
    }).toList());
  }


```
We have prepared the sample for your reference, 
Sample link:  ( https://www.syncfusion.com/downloads/support/directtrac/322674/ze/main-25649055)

![image](https://user-images.githubusercontent.com/77044081/113863984-f9ca4180-97c7-11eb-80d8-ab9a373e0995.png)


Please get back to us if you need further assistance from us.
