### ISSUE TITLE
Time column on the left and the date of the week on the top shrinks

### ISSUE THREAD

**Issue by joshoconnor89** [syncfusion/flutter-widgets#1732]
Im noticing some times, in week view, the far left column which shows the time but its super small. Shrinks to barely readable.  In addition, the top header which shows the date of the week shrinks too.  What causes this to occur?  
<img width="595" alt="Screenshot 2024-03-13 at 2 09 58 PM" src="https://github.com/syncfusion/flutter-widgets/assets/9359439/7ca9c36e-b02f-4fad-a9f3-85fa67660c07">

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue has been already fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_datepicker/versions/25.1.35
