### ISSUE TITLE
Error: Couldn't find constructor 'TextScaler.linear'.textScaler: const TextScaler.linear(1.2)

### ISSUE THREAD

**Issue by mohamdharris** [syncfusion/flutter-widgets#1737]
here , where i suppose to use TextScaler.linear properties and how to solve this issue.

**Comment by DrNiels** [comment]
I had the same issue when my Flutter version was 3.13. After updating to 3.19, everything went fine.

**Comment by philos3** [comment]
I had the same issue when my Flutter version was 3.13  use syncfusion_flutter_charts: ^25.1.35
<img width="998" alt="image" src="https://github.com/syncfusion/flutter-widgets/assets/8424317/7a8da414-8e52-487a-ac63-70ea89b5abf7">

**Comment by mohamdharris** [comment]
> Hi @mohamdharris,
> 
> We tried to replicate the reported issue at our end. We tried the following ways to reproduce the issue:
> 
> * We checked with the latest chart version 25.1.35 with the flutter SDK 3.19.3 to reproduce the reported issue.
> * We tested by setting the chart title with and without textStyle.
> * We checked by dynamically updating the font size.
> * We checked in mobile, windows and web platform.
> 
> Unfortunately, we are not able to reproduce the reported issue. However, we suspect that the mentioned issue might have occurred due to some cache, and we recommend that you check by clearing the cache using the below-mentioned methods:
> 
> * Stop the running application.
> * In the command prompt / terminal, run the "flutter pub cache clean" command to clear all the pub cache.
> * Then run the "flutter clean" command in your project.
> * Delete "pubspec.lock" file in your project.
> * Afterwards, run the "flutter pub get" command to get all the dependencies in the pubspec.yaml file.
> 
> If you still face the issue after clearing the cache, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.
> 
> Regards, Preethika Selvam. [gh1737.zip](https://github.com/syncfusion/flutter-widgets/files/14663030/gh1737.zip)

Thanks for your replay . after did the above steps . now working fine

**Comment by LokeshPalani** [comment]
Hi @philos3,

The textScaleFactor property has been deprecated from Flutter 3.16 and the Chart version mentioned 25.1.x will be compatible with Flutter 3.19. If Flutter 3.13 is used, use the 23.2.4 Chart version without the caret (^) sign to prevent upgrading to the latest version. Additionally, there is a user guide documentation link for the reference.



Syncfusion Compatible Package Version Link for Flutter SDK version 3.13.0: https://pub.dev/packages/syncfusion_flutter_charts/versions/23.2.4



UG Link, https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility 

Regards,
Lokesh P.
