### ISSUE TITLE
PDF & XLS Generartion in a server Side (pure dart / non flutter) environment

### ISSUE THREAD

**Issue by markbreuss** [syncfusion/flutter-widgets#1738]
I was wondering if these two package are only working on a flutter project. Or if they are also intended to be used in a dart backend package (dart_frog etc.)

If anyone has experience or there is an official guide for it - I am gratefull for directions.

Thanks

**Comment by AnanthaGokulaRaman** [comment]
Currently, we don't have support for creating or manipulating PDF documents in Dart. We have added it to our feature request list. As of now, we don't have any immediate plans to implement this. It will be available any of our upcoming releases. 
 
Kindly use the below feedback link to track the status of the feature.
[PDF document creation and manipulation support in Dart in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/54179/pdf-document-creation-and-manipulation-support-in-dart)
