### ISSUE TITLE
[syncfusion_flutter_pdfviewer] "getTileImage" build error

### ISSUE THREAD

**Issue by mdddj** [syncfusion/flutter-widgets#1745]
```yaml
  syncfusion_flutter_pdfviewer: ^25.1.35
  flutter: 3.19.3
```

```
../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-25.1.35/lib/src/common/pdfviewer_plugin.dart:157:10: Error: The method 'getTileImage' isn't defined for the class 'PdfViewerPlatform'.
 - 'PdfViewerPlatform' is from 'package:syncfusion_pdfviewer_platform_interface/src/pdfviewer_platform_interface.dart' ('../.pub-cache/hosted/pub.dev/syncfusion_pdfviewer_platform_interface-24.2.9/lib/src/pdfviewer_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getTileImage'.
        .getTileImage(pageNumber, scale, x, y, width, height, _documentID!));
         ^^^^^^^^^^^^

```

**Comment by immankumarsync** [comment]
@mdddj, we suggest you clear pub cache, clean the project, run pub upgrade, and check whether the issue is resolved.

**Comment by mdddj** [comment]
> > @mdddj, we suggest you clear pub cache, clean the project, run pub upgrade, and check whether the issue is resolved.
> 
> same here, ur suggest not fixing this issue. pls helpp

you can try add
```yaml
dependency_overrides:
    syncfusion_pdfviewer_platform_interface: ^last_version
```

**Comment by irxyad** [comment]
> > > @mdddj, we suggest you clear pub cache, clean the project, run pub upgrade, and check whether the issue is resolved.
> > 
> > 
> > same here, ur suggest not fixing this issue. pls helpp
> 
> you can try add
> 
> ```yaml
> dependency_overrides:
>     syncfusion_pdfviewer_platform_interface: ^last_version
> ```

Thank u
its fixed my issue👍
