### ISSUE TITLE
How to use WidgetAnnotation in Syncfusion_flutter_pdfviewer & Syncfusion_flutter_pdf?

### ISSUE THREAD

**Issue by ramsmart-inno** [syncfusion/flutter-widgets#1746]
I can't able to find the code snippets for WidgetAnnotation.

**Comment by immankumarsync** [comment]
At present, syncfusion_flutter_pdfviewer does not have the support for Widget annotations. We do not have any immediate plan to implement the support for “Widget annotations”. At the planning stage of every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know here when this feature implementation is started in the future.

Please follow the feedback link to track the status of Widget annotation feature,
https://www.syncfusion.com/feedback/51912/support-for-widget-annotation

**Comment by Deepak1799** [comment]
We are closing this issue now. As mentioned earlier, we do not have immediate plans to support Widget annotations. Please track the status of this feature through the following feedback link
https://www.syncfusion.com/feedback/51912/support-for-widget-annotation
