### ISSUE TITLE
Have any possibilities to change the annotation coordinates dynamically like drag and drop? in PdfViewer or Pdf

### ISSUE THREAD

**Issue by ramsmart-inno** [syncfusion/flutter-widgets#1749]
annotation coordinates change coordinates dynamically while drag.

**Comment by immankumarsync** [comment]
@ramsmart-inno, we understand that you are trying to change the position of the annotation that is already added to the PDF document. If our understanding is wrong, kindly share your entire use case; this will help us provide a prompt solution.
The syncfusion_flutter_pdfviewer has the support to edit text markup annotations. But the text markup cannot be moved by behavior.

Please refer to the documentation link to learn about the annotation feature: https://help.syncfusion.com/flutter/pdf-viewer/annotations-overview.

At present, syncfusion_flutter_pdfviewer doesn't support shape, free text, or ink annotations. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters, including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
 
Kindly use the below feedback link to track the status of the feature.
 
Shape annotation: https://www.syncfusion.com/feedback/26332/support-for-shape-annotations
Free text annotation: https://www.syncfusion.com/feedback/45202/support-for-free-text-annotations
Ink annotation: https://www.syncfusion.com/feedback/26333/support-for-ink-annotations

**Comment by ram-mohan-vst-au4** [comment]
Sure it will be an additional feature.

**Comment by immankumarsync** [comment]
Hi @ram-mohan-vst-au4, thank you for showing interest. We will inform you once these features are implemented. Kindly use the feedback links provided above to track the status of the feature.

**Comment by Deepak1799** [comment]
@ram-mohan-vst-au4 As we mentioned earlier, kindly use the below feedback link to track the status of the feature.
Shape annotation: https://www.syncfusion.com/feedback/26332/support-for-shape-annotations
Free text annotation: https://www.syncfusion.com/feedback/45202/support-for-free-text-annotations
Ink annotation: https://www.syncfusion.com/feedback/26333/support-for-ink-annotations
