### ISSUE TITLE
Resize pdf view.

### ISSUE THREAD

**Issue by chetan-cueclad** [syncfusion/flutter-widgets#175]
Hi, I’m unable to resize pdf view. I want to wrap view in container with 200 x 200 but problem is that it’s showing small part of page-width(example page-width is 600).

<img width="1193" alt="Screenshot 2021-04-06 at 6 23 43 PM" src="https://user-images.githubusercontent.com/39045302/113713744-4ef14f00-9705-11eb-8d89-77b61bcfd6a1.png">

**Comment by dillibabun** [comment]
Hi @chetan-cueclad 

Greetings from Syncfusion.

We can reproduce the reported issue with "Unable to resize PdfViewer inside a sized container". We are analyzing on this issue and will update the further details on 9 April 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @chetan-cueclad ,

The reported issue has been fixed and included in our upcoming weekly release which is estimated to be available on 13 April, 2021 tentatively.

Regards,
Dilli babu.

**Comment by chetan-cueclad** [comment]
That’s great 👍🏻

**Comment by dillibabun** [comment]
Hi @chetan-cueclad,

We have included the issue fix in [latest package](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.56-beta). Kindly let us know if you have any doubts.

Regards,
Dilli babu.
