### ISSUE TITLE
i want to give chart length according list but in the list data more then 20 but show only 5 in line graph

### ISSUE THREAD

**Issue by snehilmadvise** [syncfusion/flutter-widgets#1756]

**Comment by LokeshPalani** [comment]
Hi @snehilmadvise,


We have checked the reported issue regarding the 'Remaining dataPoints not being shown in the SfCartesianChart'. We suspect that you are using the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) property in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). It denotes the number of data points to be visible always in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html). For example, if there are 10 data points, the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) value set to 5, and the [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html) set to [AutoScrollingMode.start](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html#start), the first 5 data points will be displayed in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html), and the remaining data points can be viewed by panning the chart from left to right direction. You can view the remaining data points by setting the [enablePanning](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/enablePanning.html) property to true in the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html). We have shared a code snippet, sample, and user guide documentation for your reference.

 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-scrolling

Code Snippet:

``` dart
SfCartesianChart(
        zoomPanBehavior: ZoomPanBehavior(
           enablePanning: true,
        ),
        primaryXAxis: const NumericAxis(
           autoScrollingDelta: 5,
           autoScrollingMode: AutoScrollingMode.start,
        ),
        primaryYAxis: const NumericAxis(),
     )
```

Regards,
Lokesh P.
 
[github_1756.zip](https://github.com/syncfusion/flutter-widgets/files/14722829/github_1756.zip)
