### ISSUE TITLE
Confusing animation when inserting new values at front

### ISSUE THREAD

**Issue by DrNiels** [syncfusion/flutter-widgets#1757]
In my app, I want to load values on demand, based on panning (and possibly zooming later on). Now, when I load newer values and add them to the corresponding value array, everything looks smooth, similar to your live data example. But when I load older values and insert them at the front of the values via insertAll, a confusing animations moves the line all over the place before ending in the right spot. 

You can reproduce it with the following code:
````
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

bool detailed = false;

void main() async {
  runApp(
    MaterialApp(
      home: TestChart(),
    ),
  );
}

class TestChart extends StatefulWidget {
  static List<Offset> allData = [
    Offset(0, 0),
    Offset(1, 10),
    Offset(2, 2),
    Offset(3, 13),
    Offset(4, 4),
    Offset(5, 15),
    Offset(6, 6),
    Offset(7, 17),
    Offset(8, 8),
    Offset(9, 19),
    Offset(10, 10),
  ];

  _TestChartState createState() => _TestChartState();
}

class _TestChartState extends State<TestChart> {
  List<Offset> currentData = [
    TestChart.allData[3],
    TestChart.allData[4],
    TestChart.allData[5],
  ];
  double start = 3;
  double end = 5;

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      series: [
        SplineSeries<Offset, num>(
          xValueMapper: (data, _) => data.dx,
          yValueMapper: (data, _) => data.dy,
          dataSource: currentData,
        ),
      ],
      primaryYAxis: NumericAxis(
        minimum: 0,
        maximum: 20,
        interval: 1,
        axisLabelFormatter: (AxisLabelRenderDetails axisLabelRenderArgs) {
          return ChartAxisLabel(axisLabelRenderArgs.value.toString(), null);
        },
      ),
      primaryXAxis: NumericAxis(
        name: 'xAxis',
        minimum: 0,
        maximum: 10,
        initialVisibleMinimum: start,
        initialVisibleMaximum: end,
      ),
      tooltipBehavior: TooltipBehavior(
        enable: true,
      ),
      onActualRangeChanged: (ActualRangeChangedArgs args) {
        if (args.axisName != 'xAxis') {
          return;
        }

        WidgetsBinding.instance.addPostFrameCallback((Duration duration) {
          setState(() {
            start = args.visibleMin.floor();
            end = args.visibleMax.ceil();
            updateData();
          });
        });
      },
      zoomPanBehavior: ZoomPanBehavior(
        enablePanning: true,
        zoomMode: ZoomMode.x,
      ),
    );
  }

  void updateData() {
    List<Offset> prependData = [];
    for (int i = start.round(); i < currentData.first.dx; i++) {
      prependData.add(TestChart.allData[i]);
    }
    currentData.insertAll(0, prependData);
    List<Offset> appendData = [];
    for (int i = currentData.last.dx.round() + 1; i <= end.toDouble(); i++) {
      appendData.add(TestChart.allData[i]);
    }
    currentData.addAll(appendData);
  }
}
````

When I load newer values, i.e., pan to the right, everything looks great:
![loading-newer-values](https://github.com/syncfusion/flutter-widgets/assets/29275341/277c3920-3ed3-4784-a118-fd3e9aa149e6)

However, loading older values, i.e., pan to the left, looks really confusing. At first, I thought the values changed, but after the animation is done, all values are fine. However, you don't really see, that a single value was simply added to the front:
![loading-older-values](https://github.com/syncfusion/flutter-widgets/assets/29275341/e32b8117-4f91-44ea-aea1-e19d068b533b)

It would be great, if adding values to the front of my values would produce the same animation as adding them to the back.

I use version 25.1.35 of syncfusion_flutter_charts

Output of flutter doctor:

[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.86.0)
[√] Connected device (3 available)
[√] Network resources

I'm currently using Flutter in Web.

**Comment by LokeshPalani** [comment]
Hi @DrNiels,

 

We have checked your query and validated the attached code snippet. We need more details about your requirement regarding what you are trying to achieve in the attached sample. It will be more helpful to us to provide a solution to achieve your requirements.

 

Regards,
Lokesh P.

**Comment by DrNiels** [comment]
Basically, I want to add values on demand during panning. These values are added to the front or back of my data source while the current data remains.

As seen in the GIFs, when I pan to the right, it really looks like all current values stay in place and new ones are added.

However, when I pan to the left and add values to the front of the data source, things get confusing. It would be great if the animation would be equivalent to panning to the right, i.e., all existing values stay in place and a new line is drawn towards the new values.

My guess would be, that each value is animated based on its index within the data source. This works great when adding values to the back as the index remains the same. When inserting at the front however, the index is increased for each entry. Thus, all existing values are animated towards a previous one and thus do not stay in place. I could imagine that an animation based on the x value could work better, meaning when animating each value is matched with the value with the same x value. This would definitely work better in my specific case, but there could be scenarios that I'm not aware of where the previous approach is better.

**Comment by LokeshPalani** [comment]
Hi @DrNiels, 

We have validated your query and the shared code snippet. In the code snippet, you have inserted the data in the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) and updated the [visibleMin](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ActualRangeChangedArgs/visibleMin.html) and [visibleMax](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ActualRangeChangedArgs/visibleMax.html) using the [onActualRangeChanged](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onActualRangeChanged.html) callback. We suggest using the [loadMoreIndicatorBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/loadMoreIndicatorBuilder.html) for you to add a on-demand data points. We have also shared an online sample and user guide documentation for your reference below. Please let us know if you need any further assistance.
 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading

 

Sample Link,

https://flutter.syncfusion.com/#/cartesian-charts/infinite-scrolling

 

Regards,
Lokesh P.

**Comment by DrNiels** [comment]
Thank you for the support! I'm not sure if I really want to use the indicator builder, but the relevant part seems to be to call updateSourceData and the series' controller, which prevents animation and solved the issue for me.
