### ISSUE TITLE
Error CERTIFICATE_VERIFY_FAILED while accessing SfPdfViewer.network

### ISSUE THREAD

**Issue by alwaangk** [syncfusion/flutter-widgets#1758]
I got this error while accessing SfPdfViewer.network

```
SfPdfViewer.network(
urlRequest!,
canShowPasswordDialog: true,
 ),
```

```
E/flutter ( 4504): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error:
E/flutter ( 4504): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393))
E/flutter ( 4504): #0      NetworkPdf.getPdfBytes
package:syncfusion_flutter_pdfviewer/…/common/pdf_provider.dart:55
E/flutter ( 4504): <asynchronous suspension>
E/flutter ( 4504):
```

I think is because url ssl certificate. Is any chance to ignore ssl certificate?
Something like httpOverrides with dart.io
```
 class MyHttpOverrides extends HttpOverrides{
  @override
  HttpClient createHttpClient(SecurityContext? context){
    return super.createHttpClient(context)
      ..badCertificateCallback = (X509Certificate cert, String host, int port)=> true;
  }
}
```

**Comment by immankumarsync** [comment]
Hi @alwaangk,
For this case you can download the PDF document using custom HttpOverrides and load the downloaded PDF document using [SfPdfViewer.memory](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.memory.html) constructor.

Please find a sample in the attachment and modify the _getPdfBytes method  for your use case.
[Sample](https://github.com/syncfusion/flutter-widgets/files/14739541/pdfviewer_network.zip)

**Comment by Deepak1799** [comment]
@alwaangk We believe that the issue has been resolved; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.
