### ISSUE TITLE
Following "Referring packages source in your application" errors

### ISSUE THREAD

**Issue by ThreeFCompany** [syncfusion/flutter-widgets#1760]
I'm following the simple [Referring packages source in your application](https://github.com/syncfusion/flutter-widgets#referring-packages-source-in-your-application) and I'm getting a bunch of errors attached.
[Syncfusion_charts_errors.txt](https://github.com/syncfusion/flutter-widgets/files/14728290/Syncfusion_charts_errors.txt)

Mostly has to do with the behaviors folder missing in the charts package.

**Comment by LokeshPalani** [comment]
Hi @ThreeFCompany,
 
Thank you for informing us about this issue. We have included the missed file and published the changes. Please find the link below for your reference.
 
**GitHub Link:**  https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_charts/lib/src/charts/behaviors 
 
Kindly get back to us if you have further queries. We are always happy to assist you.
 
Regards,
Lokesh P.
