### ISSUE TITLE
DatePicker within Calendar does not adhere to theme

### ISSUE THREAD

**Issue by jakobkoerber** [syncfusion/flutter-widgets#1762]
While upgrading both `syncfusion_flutter_calendar` from 24.2.4 and `syncfusion_flutter_datepicker` from 24.2.9 to 25.1.35 I observed that the DatePicker header and DatePicker itself within the `SfCalendar` Widget does not adhere to the app's theme.

| 24.2.4 | 25.1.35 |
|------|------|
| ![Simulator Screenshot - iPhone 15 Pro - 2024-03-23 at 23 27 42](https://github.com/syncfusion/flutter-widgets/assets/56073945/11c7d86e-d0cf-4c4b-8cc3-c7ae4406dd94)![Simulator Screenshot - iPhone 15 Pro - 2024-03-23 at 23 27 45](https://github.com/syncfusion/flutter-widgets/assets/56073945/1d7b9c22-2afb-44cd-9694-c27991aeffc5) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-23 at 23 26 50](https://github.com/syncfusion/flutter-widgets/assets/56073945/3982fa17-8644-47a8-91ac-f017a0be4f9d)![Simulator Screenshot - iPhone 15 Pro - 2024-03-23 at 23 26 54](https://github.com/syncfusion/flutter-widgets/assets/56073945/d3c28625-6fc5-4e77-9569-192e3b398308) |

While the header can be adjusted with the `headerStyle` attribute, the DatePicker itself cannot. At least as far as I can tell 😄

Thanks for your help!

**Comment by MagTuxGit** [comment]
They've added pink colors in the material3 theme:
https://github.com/syncfusion/flutter-widgets/blob/8f0096cba87c414cc913d897df4850f32dc40bc9/packages/syncfusion_flutter_datepicker/lib/src/date_picker/theme.dart#L69-L77
I fixed that by adding backgroundColor to the theme:
```dart
SfDateRangePickerTheme(
  data: SfDateRangePickerThemeData(backgroundColor: Colors.transparent),
  child: SfDateRangePicker(...),
)
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jakobkoerber ,

We have provided Material 3 UI theme support to the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html) in our latest Volume 1 2024 main release with 25.1.35. So that the header and date picker color changed to the Flutter Material 3 UI theme. So, you can disable the Material 3 UI theme by wrapping the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html) widget inside the [MaterialApp](https://api.flutter.dev/flutter/material/MaterialApp-class.html) widget and setting the useMaterial3 to false.

| Enable Material 3 Theme | Disable Material 3 Theme |
|--------|--------|
| ![simulator_screenshot_35FF31BD-A6EF-4219-9D93-D18D551327C0](https://github.com/syncfusion/flutter-widgets/assets/61863686/360872b0-3bda-4927-9eb8-66577cd9eccb) | ![simulator_screenshot_E510BE6A-1DE3-4051-907A-63C9645EF978](https://github.com/syncfusion/flutter-widgets/assets/61863686/7f5b1abd-eca5-4c31-af97-bcf9992c1ca9) |

Code snippt:
```dart
return MaterialApp(
      theme: ThemeData(useMaterial3: false),
      home: Scaffold(
        appBar: AppBar(),
        body: SfCalendar(
          showDatePickerButton: true,
        ),
      ),
    );
```

**Comment by jakobkoerber** [comment]
> Hi @jakobkoerber ,
> 
> 
> 
> We have provided Material 3 UI theme support to the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html) in our latest Volume 1 2024 main release with 25.1.35. So that the header and date picker color changed to the Flutter Material 3 UI theme. So, you can disable the Material 3 UI theme by wrapping the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html) widget inside the [MaterialApp](https://api.flutter.dev/flutter/material/MaterialApp-class.html) widget and setting the useMaterial3 to false.
> 
> 
> 
> | Enable Material 3 Theme | Disable Material 3 Theme |
> 
> |--------|--------|
> 
> | ![simulator_screenshot_35FF31BD-A6EF-4219-9D93-D18D551327C0](https://github.com/syncfusion/flutter-widgets/assets/61863686/360872b0-3bda-4927-9eb8-66577cd9eccb) | ![simulator_screenshot_E510BE6A-1DE3-4051-907A-63C9645EF978](https://github.com/syncfusion/flutter-widgets/assets/61863686/7f5b1abd-eca5-4c31-af97-bcf9992c1ca9) |
> 
> 
> 
> Code snippt:
> 
> ```dart
> 
> return MaterialApp(
> 
>       theme: ThemeData(useMaterial3: false),
> 
>       home: Scaffold(
> 
>         appBar: AppBar(),
> 
>         body: SfCalendar(
> 
>           showDatePickerButton: true,
> 
>         ),
> 
>       ),
> 
>     );
> 
> ```

Hey @Yuvaraj-Gajaraj,

thanks for your reply!

This doesn't seem accurate. My app is wrapped in a MaterialApp Widget with useMaterial3 set to true. Yet all other widgets adhere to the material 3 theme customized by me. The SfCalendar header and date picker defaults back to the default purple material 3 theme. There seems to be an issue with the material 3 implementation of 25.1.35.

**Comment by MagTuxGit** [comment]
@jakobkoerber 
Have you checked my comment up there?
You can use SfCalendarTheme and SfDateRangePickerTheme with your backgroundColor.
https://github.com/syncfusion/flutter-widgets/issues/1762#issuecomment-2017590486

**Comment by jakobkoerber** [comment]
@MagTuxGit @Yuvaraj-Gajaraj 

Unfortunately this doesn't work even with `25.1.37`. Eitherway this seems like a weird developer experience to me having to wrap the `SfCalendar` widget in a `SfCalendarTheme`. Why not use the theme that is already defined in the `context`?

<img width="689" alt="Screenshot 2024-03-27 at 12 23 58" src="https://github.com/syncfusion/flutter-widgets/assets/56073945/cc81066c-7bc4-4e55-944a-8c9e88ae7064">
<img width="329" alt="Screenshot 2024-03-27 at 12 24 07" src="https://github.com/syncfusion/flutter-widgets/assets/56073945/3721deb0-6cd6-42a3-b116-58f5e94376ea">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jakobkoerber ,

Currently, we don't have the option to customize the datePicker background color which occurs when enabling the showDatePickerButton property in the SfCalendar. However, you can achieve this with the help of a custom header and show the date picker in showDialog. We shared the sample below for your reference, you can use this and achieve your requirements.

Screenshot:
![SimulatorScreenRecording-iPhone15ProMax-2024-04-03at16 42 08-ezgif com-video-to-gif-converter](https://github.com/syncfusion/flutter-widgets/assets/61863686/8f57c0a9-0b7e-40e4-b5ec-a44f8c41ed56)


Sample:
[github_1762.zip](https://github.com/syncfusion/flutter-widgets/files/14851224/github_1762.zip)


Regards,
Yuvaraj.
