### ISSUE TITLE
SfCalendar: Custom timeslot design

### ISSUE THREAD

**Issue by vgavrilovikj** [syncfusion/flutter-widgets#1767]
I am trying to achieve a custom timeslot design in Flutter mobile, however I cannot find a way to customize the timeslot fields.

This is the achieved design I want to have for the timeslots (instead of lines to be full containers with specific color and radius):
![image](https://github.com/syncfusion/flutter-widgets/assets/29601489/a61b64c8-655d-4aad-9a81-0b696646c8fc)

I am using the version `syncfusion_flutter_calendar: ^25.1.35`, is it possible to achieve this with the current package version or not?

Thank you in advance!

**Comment by vgavrilovikj** [comment]
@Yuvaraj-Gajaraj thanks a lot! How can I implement this for every field like in the image above? I successfully implemented it for one hour or multiple hours and can view the background changed - however how can I set it to be like that for every hour - like on the image above?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi,

To customize the timeslot region for every hour, you need to create a special region for every hour and customize it with the help of [timeRegionBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/timeRegionBuilder.html). Here we have taken a visible date with the help of the [onViewChanged](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/onViewChanged.html) callback and then created the [specialRegions](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/specialRegions.html) for every visible hour. Then customize it with the help of timeRegionBuilder. We have gotten the visible dates from the [onViewChanged](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/onViewChanged.html) event to avoid creating unwanted [specialRegions](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/specialRegions.html).

We have prepared the sample and shared it below. You can refer to this and achieve your requirements.

**Screenshot:**
<img src='https://github.com/syncfusion/flutter-widgets/assets/61863686/59b91eff-0f1e-44a9-a03e-882e43db30ef' width = 300px/>

**Sample:** 
[github_1767.zip](https://github.com/syncfusion/flutter-widgets/files/14850224/github_1767.zip)


Regards,
Yuvaraj.

**Comment by vgavrilovikj** [comment]
Thank you - it's working perfectly!
