### ISSUE TITLE
[synfusion_flutter_datagrid]  change background or text style in pop up select rows per page

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1771]
Could you please let me know how can i change text style or backgroud of this?
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/a64423fb-26ce-4186-bd4e-a1bdc4cc81a7)

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,

Based on the information you provided, it seems you want to change the text style of items in the rowPerPage dropdown. To achieve this, wrap the SfDataPager as a child of the **SfDataPagerTheme** widget. Set the desired  text style for **itemTextStyle** in the **SfDataPagerThemeData** class. We have attached the code snippets and output images for your reference. If you have any further concerns, please feel free to reach out.

- **Code snippet :** 
``` dart 
 SfDataPagerTheme(
    data: const SfDataPagerThemeData(
         itemTextStyle: TextStyle(color: Colors.red)),
    child: SfDataPager(),
```

- **Output images :** 

     [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14820207/SfDataGrid.zip)

Regards,
Abinesh P

**Comment by Trung15010802** [comment]
> Hi @Trung15010802 ,
> 
> Based on the information you provided, it seems you want to change the text style of items in the rowPerPage dropdown. To achieve this, wrap the SfDataPager as a child of the **SfDataPagerTheme** widget. Set the desired text style for **itemTextStyle** in the **SfDataPagerThemeData** class. We have attached the code snippets and output images for your reference. If you have any further concerns, please feel free to reach out.
> 
> * **Code snippet :**
> 
> ```dart
>  SfDataPagerTheme(
>     data: const SfDataPagerThemeData(
>          itemTextStyle: TextStyle(color: Colors.red)),
>     child: SfDataPager(),
> ```
> 
> * **Output images :**
>   [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14820207/SfDataGrid.zip)
> 
> Regards, Abinesh P

But i  do that all TextStyle will change. Not just row per pages text:
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/fe0c84c7-188c-4bc2-90de-271be1c2d177)

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,
 
Based on the information you provided, it seems you want to change the text style of items or the background color in the rowPerPage dropdown. You can achieve this by setting the desired text style for **itemTextStyle** in the **SfDataPagerThemeData** class. This will change all the itemTextStyle in the SfDataPager. However, currently, we do not have support to change the rowPerPage dropdown items directly.
 
However, we have a workaround that can help you achieve a custom background color for the dropdown. You can customize the background color of the dropdown menu by using the **Theme** widget. To achieve this, wrap the **SfDataPager** as a child of the Theme widget, and set the desired values for **canvasColor** in the Theme class.
 
We have attached the code snippet and output images for your reference. Please refer to the following code snippet for more information. If you have any further concerns, please feel free to reach out.

- **Code snippet :** 
``` dart
Theme(
  data: Theme.of(context).copyWith(
  canvasColor: Colors.red),
    child: SfDataPager(),
```
- **Output images :** 
   [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14832525/SfDataGrid.zip)

Regards,
Abinesh P
