### ISSUE TITLE
[pdf_viewer] How to zoom out below 0 zoom level?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#1772]
When I am showing the pdf viewer in full screen and the page fills the entire page width, I can only read about 1/4 of the page until i have to scroll. 

Is there some way to zoom out so that I can at least see a full page? This would require a zoom level below 0

**Comment by immankumarsync** [comment]
Hi @Wizzel1, at present, when displaying the PDF document in continuous page layout the page will fit to the width of the SfPdfViewer widget. You can use [PdfPageLayoutMode.single](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfPageLayoutMode.html#single) to fit the entire page in the SfPdfViewer widget.
Please refer to the documentation to learn more about [Page layout and Scrolling options in Flutter PDF Viewer](https://help.syncfusion.com/flutter/pdf-viewer/page-layout-and-scroll-direction)

**Comment by Wizzel1** [comment]
Thanks
