### ISSUE TITLE
[syncfusion_flutter_datepicker] dateRangePicker For Month Year select

### ISSUE THREAD

**Issue by quocviet1996** [syncfusion/flutter-widgets#1778]
Hi Guys, i have a question, are we planning to create a daterange month picker function? Like this image. Tks
![image](https://github.com/syncfusion/flutter-widgets/assets/48380821/31b9ec3c-699a-4a33-a4dd-2d384a1f7b29)

**Comment by Yuvaraj-Gajaraj** [comment]
You can achieve your requirement with the help of [allowViewNavigation](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/allowViewNavigation.html), [view](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/view.html), and [selectionMode](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/selectionMode.html) properties. Here you need to set the view to [DateRangePickerView.year](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerView.html) and disable [allowViewNavigation](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/allowViewNavigation.html) then set the [selectionMode](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/selectionMode.html) property to range, now you can select the month range between years. We have shared the code snippet below for your reference. If you have any further queries please get back to us.



Code snippet:
```dart
SfDateRangePicker(
  enableMultiView: true,
  view: DateRangePickerView.year,
  allowViewNavigation: false,
  selectionMode: DateRangePickerSelectionMode.range,
)
```

Screenshot:
![SimulatorScreenRecording-iPhone12-2024-04-12at17 07 59-ezgif com-video-to-gif-converter](https://github.com/syncfusion/flutter-widgets/assets/61863686/5ba25488-8799-4b08-a12d-44919449ca6a)

**Comment by quocviet1996** [comment]
wow, great, I'll try it tomorrow, tks you 💯

**Comment by quocviet1996** [comment]
Okay, tks Yuvaraj-Gajaraj, this is a great solution, except i can't click on the year button to be able to switch year quickly like normal, right?
![image](https://github.com/syncfusion/flutter-widgets/assets/48380821/a3e1a9fb-ba6e-4a39-bab7-1aea74600487)
