### ISSUE TITLE
How to pass selected date by DateRangePickerController ?

### ISSUE THREAD

**Issue by urvihs** [syncfusion/flutter-widgets#1779]
Need to pass selected date in controller without opening SfDateRangePicker

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @urvihs ,

You can set the selected date of SfDateRangePicker through DateRangePickerController by assigning a value in the initState. We have prepared the sample and shared it with you, please refer to it and achieve your requirements.

Screen shot:
<img src='https://github.com/syncfusion/flutter-widgets/assets/61863686/e31c6aff-1dee-487e-86a0-5f859b28686e' width = 300px/>


Sample: 
[github_1779.zip](https://github.com/syncfusion/flutter-widgets/files/14851399/github_1779.zip)



Regards,
Yuvaraj.
