### ISSUE TITLE
Change the license to something actually "open" like Dart requires on their website

### ISSUE THREAD

**Issue by cholojuanito** [syncfusion/flutter-widgets#178]
**Your license in every package is not compliant with Dart's requirements**, listed [here](https://dart.dev/tools/pub/publishing#preparing-to-publish). The very first point in the list is that the license must be an "open-source license" then provides a link to https://opensource.org which has a list of OSD-compliant licenses [here](https://opensource.org/licenses). Your license is not listed there.

I suggest you change or update your license to be more inclusive to everyone, OSD compliant, and free to use, forever.

If you are going to open source these packages then at least make it _open and free_ to all. Putting an arbitrary dollar amount on Flutter widgets is absurd. It defeats the whole purpose of Flutter

Even if you don't plan on actually taking legal action if someone doesn't get a commercial license, it's a legal problem that many may forget about now but have to deal with down the road.

**Comment by lsalazarm99** [comment]
Or don't publish it in pub.dev if it's not possible to make it "open".

**Comment by cholojuanito** [comment]
> Or don't publish it in pub.dev if it's not possible to make it "open".

That is also an option, just hosting it elsewhere since everyone that uses pub.dev has the expectation that the package has a OSD compliant license

**Comment by MisterJimson** [comment]
Also git dependancy would be an option for paid packages like these.

**Comment by cholojuanito** [comment]
As @MisterJimson mentioned a git dependency is probably the best option for something like this.

Either way with the license as is, these packages shouldn't be allowed to be on the official pub.dev. The options are listed [here](https://dart.dev/tools/pub/dependencies#hosted-packages) in Dart's documention

**Comment by cholojuanito** [comment]
Closing becase of the clarifications in the above pub-dev issue. All the best to everyone
