### ISSUE TITLE
PDF from assets opens when ElevatedButton is pressed?

### ISSUE THREAD

**Issue by adrinebt** [syncfusion/flutter-widgets#1780]
I'm trying to create a button inside a bottomsheet opens a PDF document from assets but this isn't working and doesn't return errors.
`        Column(
          children: [
            ElevatedButton(
                onPressed: () {
                  SfPdfViewer.asset(
                    'assets/document.pdf',
                    onDocumentLoaded: (PdfDocumentLoadedDetails details) {
                      print(details.document.pages.count);
                    },
                  );
                },
                child: Text(
                  'h-btn-pdf'.i18n(),
                  style: const TextStyle(fontSize: 16.0, color: Colors.white),
                ),
              style: ElevatedButton.styleFrom(
                backgroundColor: customColor[600],
                elevation: 15,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
              ),
            ),
          ],
        ),`

**Comment by immankumarsync** [comment]
Hi @adrinebt,

From the code that you have shared, we could see that the SfPdfViewer.asset widget is not mounted to the widget tree. Please try out with code snippet below and check whether your issue is resolved.

```
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(const MaterialApp(
    debugShowCheckedModeBanner: false,
    home: TestPage(),
  ));
}

class TestPage extends StatefulWidget {
  const TestPage({super.key});

  @override
  State<TestPage> createState() => _TestPageState();
}

class _TestPageState extends State<TestPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () {
              // Here the SfPdfViewer widget is instantiated but not mounted to the widget tree. 
              // SfPdfViewer.asset(
              //   'assets/document.pdf',
              //   onDocumentLoaded: (PdfDocumentLoadedDetails details) {
              //     print(details.document.pages.count);
              //   },
              // );

              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => PdfViewerPage()),
              );
            },
            child: Text(
              'h-btn-pdf',
              style: const TextStyle(fontSize: 16.0, color: Colors.white),
            ),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.blue,
              elevation: 15,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8.0),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class PdfViewerPage extends StatefulWidget {
  const PdfViewerPage({super.key});

  @override
  State<PdfViewerPage> createState() => _PdfViewerPageState();
}

class _PdfViewerPageState extends State<PdfViewerPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // Here the SfPdfViewer widget is mounted to the widget tree (asigned to the body of the Scaffold).
      body: SfPdfViewer.asset(
        'assets/document.pdf',
        onDocumentLoaded: (PdfDocumentLoadedDetails details) {
          print(details.document.pages.count);
        },
      ),
    );
  }
}
```

**Comment by adrinebt** [comment]
It worked well but when I try to configure a page it closes automatically, do I need to do additional configuration? Since I use the navigation system with Flutter Modular I adapted my code

`        Column(
          children: [
            ElevatedButton(
                onPressed: () {
                  Modular.to.push(MaterialPageRoute(builder: (_) => PdfViewerPage()));
                },
                child: Text(
                  'h-btn-pdf'.i18n(),
                  style: const TextStyle(fontSize: 16.0, color: Colors.white),
                ),
              style: ElevatedButton.styleFrom(
                backgroundColor: customColor[600],
                elevation: 3,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(8.0),
                ),
              ),
            ),
          ],
        ),`


https://github.com/syncfusion/flutter-widgets/assets/113125592/66ac0e1d-fe1a-481a-820c-5b2c47b8f08e

**Comment by immankumarsync** [comment]
@adrinebt, we are unable to replicate the reported issue with the [Navigator.push](https://api.flutter.dev/flutter/widgets/Navigator/push.html) method. Please find the screen recording where we use Navigator.push to open the PdfViewerPage.

https://github.com/syncfusion/flutter-widgets/assets/93641486/54281f0b-8e73-486a-8270-570e2b18f35f

We suspect that the issue occurs with the flutter modular package you use in your application. Please share with us a simple sample with the flutter modular package so that we can analyze the issue and provide you with a prompt solution.

**Comment by Deepak1799** [comment]
@adrinebt We are closing this issue since we do not have enough information to proceed further. You can reopen this anytime and share the requested details to proceed further.
