### ISSUE TITLE
A constant constructor can't call a non-constant super constructor - syncfusion_flutter_gauges

### ISSUE THREAD

**Issue by SanketKumarr** [syncfusion/flutter-widgets#1785]
I am using syncfusion_flutter_gauges package (version: 25.1.38) and getting the below error:

> /C:/Users/sanketkumar/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_gauges-25.1.38/lib/src/radial_gauge/axis/radial_axis_parent_widget.dart:36:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(key: key, children: children);
        ^
/C:/Users/sanketkumar/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_gauges-25.1.38/lib/src/linear_gauge/gauge/linear_gauge_render_widget.dart:38:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(key: key, children: children);
        ^

I am using Flutter version 3.7.12

**Comment by hwpl-bit** [comment]
/C:/Users/hwpl-2/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_gauges-24.2.9/lib/src/linear_gauge/gauge/linear_gauge_render_widget.dart:38:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(key: key, children: children);
        ^
/C:/Users/hwpl-2/AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_gauges-24.2.9/lib/src/radial_gauge/axis/radial_axis_parent_widget.dart:36:9: Error: A constant constructor can't call a non-constant super constructor.
      : super(key: key, children: children);
        ^
Target kernel_snapshot failed: Exception

**Comment by LokeshPalani** [comment]
Hi @SanketKumarr,

 
The mentioned syncfusion_flutter_gauges version 25.1.x will be compatible with Flutter SDK version 3.19.0. If you are using Flutter SDK version 3.7.12, then use the syncfusion_flutter_gauges version 21.2.8 without the caret (^) sign to prevent upgrading to the latest version. Additionally, we have shared a user guide documentation link for your reference.

 
Syncfusion Compatible Package Version Link for Flutter SDK version 3.7.12:

https://pub.dev/packages/syncfusion_flutter_gauges/versions/21.2.8  

 
UG Link, https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility


Regards,
Lokesh P.
