### ISSUE TITLE
Add support for custom legend icon

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-widgets#179]
How can I change only the icon of the legends without using **legendItemBuilder**?
I checked the api but couldn't find an appropriate and direct way to do it?
![Screenshot_1617816789](https://user-images.githubusercontent.com/16321223/113909857-d8298400-97e0-11eb-8d31-aa66628a3eed.png)

**Comment by Dharanipalani** [comment]
Hi @bismarabia,

Thanks for the interest in our Flutter charts. We have analyzed your query and would like to tell you that you can change the legend icon shape using the **legendIconType** property in the series. Sorry that we missed this in the help document and here we attached the sample for your reference, kindly make use of it.

Sample: [I322883-legend_icon.zip](https://github.com/syncfusion/flutter-widgets/files/6278900/I322883-legend_icon.zip)


Please revert us if you need any further assistance.

Thanks,
Dharanitharan. P

**Comment by bismarabia** [comment]
Hello and thanks for the reply.

But unfortunately this is not what I'm looking for.

as far as I checked the API, there are two options, 
- either we can choose legendIconType from [here](https://github.com/syncfusion/flutter-widgets/blob/e060c1d0abb8883e0d4509b3cb9009ced2d0da44/packages/syncfusion_flutter_charts/lib/src/common/utils/enum.dart#L61)
- or use **legendItemBuilder** and implement the legend from scratch.

My question is that, is it possible to customize only the icon with a  widget (Containers, ...) without implementing **legendItemBuilder** from scratch?
