### ISSUE TITLE
Upgrade device_info_plus dependency to 10.0.1

### ISSUE THREAD

**Issue by mbenci** [syncfusion/flutter-widgets#1790]
Kindly Upgrade to Latest Version
device_info_plus to 10.0.1

**Comment by immankumarsync** [comment]
Hi @mbenci,
We are checking the feasibility of upgrading the device_info_plus package in syncfusion_flutter_pdfviewer. We need to ensure that upgrading to the newer version will not affect the functionality of the SfPdfViewer widget. We will let you know once the analyzation is completed.

**Comment by sagnik-sanyal** [comment]
Any updates on the same ?

**Comment by kuhnroyal** [comment]
Next week we won't be able to release iOS apps anymore without this upgrade due to the requirement on Apple privacy manifest. This is a critical issue.

**Comment by immankumarsync** [comment]
@mbenci, @sagnik-sanyal, @kuhnroyal, to include or update a package within syncfusion_flutter_pdfviewer, we need to ensure compliance with our licensing requirements. Currently, we are conducting a thorough review to identify potential vulnerabilities in the package. Once this process is complete, we will update the package in our syncfusion_flutter_pdfviewer package. We appreciate your patience in this matter.

**Comment by sagnik-sanyal** [comment]
Hi @immankumarsync it has been almost a month and currently we are using a dependency override to atleast compile our application , but it is a blocker for future updates of our app. When can we expect this simple change from your side ?

**Comment by hugomc92** [comment]
Any news about that?? we need to upgrade more libraries as well which depends on `device_info_plus` so we need it to be upgrade please

**Comment by mrsrmn** [comment]
This package doesn't work with `amplify_flutter` because of this issue. Are there any ETA?

**Comment by baynarkozcu** [comment]
Hello, the problem still persists. When will he get better?

**Comment by pgulegin** [comment]
Waiting for an update on this as well.

**Comment by yuyaohongzheng** [comment]
expecting device_info_plus  10.0

**Comment by Imgkl** [comment]
@immankumarsync Any updates on this. We understand the compliance and security analysis, but would be great to have more transparency and updates on the process. Waiting almost 2 months for this a package update seems a lot.

**Comment by pedroserretti** [comment]
hi! thank you for the package, we appreciate it
any updates for this issue?
it's been almost 4 months that i'm receiving this problem.

**Comment by immankumarsync** [comment]
We have updated the device_info_plus package to the latest version in our syncfusion_flutter_pdfviewer package. This update will be available in our latest weekly release.

Package link: [syncfusion_flutter_pdfviewer v26.1.42](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/26.1.42)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
