### ISSUE TITLE
[synfusion_flutter_datagrid] enhance columnWidthMode with sort and filter icon

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1794]
I have already set `columnWidthMode: ColumnWidthMode.fitByColumnName`
But it doesn't look good. It should stay in the same line
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/e4d9b3ad-b814-473f-8426-1bb3293ff70d)

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,
 
Based on the information provided, we conducted tests using a simple sample to replicate the reported issues, and it worked correctly without any problems. In SfDataGrid, **ColumnWidthMode.fitByColumnName** calculates the width of the column based on the **GridColumn.columnName** property. I believe you may have handled different text in the columnName property compared to the text widget used in the label property of the GridColumn in your code. This discrepancy could cause improper alignment of the column name in the UI. To ensure proper alignment when using ColumnWidthMode.fitByColumnName, you need to maintain the same text in both places.

If you are still encountering the same problem, we kindly request you to modify the attached sample to reproduce the issue and provide additional details. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible.

- **Sample :** 

    [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14954898/SfDataGrid.zip)

 
Regards,
Abinesh P
