### ISSUE TITLE
ZoomMode.x with stacked coloumn chart with legend

### ISSUE THREAD

**Issue by FabioNieVec** [syncfusion/flutter-widgets#1795]
Hey,

I'm tying to use ZoomMode.x with stacked column chart and legend. 
```
 SfCartesianChart(
                        legend: const Legend(
                                isVisible: true,
                              position: LegendPosition.bottom,
                              overflowMode: LegendItemOverflowMode.wrap),
                          primaryXAxis: CategoryAxis(),
                          zoomPanBehavior:  ZoomPanBehavior(
                              enablePanning: true,
                              zoomMode: ZoomMode.x,
                              enableSelectionZooming: true),
                          series: <CartesianSeries>[
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y1
                            ),
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y2
                            ),
                            StackedColumnSeries<ChartData1,String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y3
                            ),
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y4
                            )
                          ]
                      )
```

If I now click on a legend item, this will happen -> 
![image](https://github.com/syncfusion/flutter-widgets/assets/32736671/a267ca27-cfe4-4c52-8a5a-4f510d5b11b7)

And I get following exception ->

The following IndexError was thrown during performLayout():
RangeError (index): Index out of range: no indices are valid: 0

The relevant error-causing widget was: 
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 600:7                 _get]
packages/syncfusion_flutter_charts/src/charts/series/chart_series.dart 3770:35    [_calculateYRange]
packages/syncfusion_flutter_charts/src/charts/series/chart_series.dart 5677:18    [_calculateYRange]
packages/syncfusion_flutter_charts/src/charts/series/chart_series.dart 6348:18    [_calculateYRange]
packages/syncfusion_flutter_charts/src/charts/series/chart_series.dart 3749:44    [_findVisibleIndexes]
packages/syncfusion_flutter_charts/src/charts/series/chart_series.dart 3668:7     didRangeChange
packages/syncfusion_flutter_charts/src/charts/axis/axis.dart 1988:20              <fn>
packages/flutter/src/rendering/object.dart 2686:51                                <fn>
packages/flutter/src/rendering/object.dart 1097:7                                 [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2686:7                                 invokeLayoutCallback
packages/syncfusion_flutter_charts/src/charts/axis/axis.dart 1986:7               [_calculateRangeAndInterval]
packages/syncfusion_flutter_charts/src/charts/axis/axis.dart 1772:7               performLayout
packages/flutter/src/rendering/object.dart 2575:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/syncfusion_flutter_charts/src/charts/base.dart 1961:13                   measureHorizontalAxes
packages/syncfusion_flutter_charts/src/charts/base.dart 1999:5                    performLayout
packages/flutter/src/rendering/object.dart 2575:7                                 layout
packages/flutter/src/rendering/box.dart 2389:11                                   layout
packages/syncfusion_flutter_charts/src/charts/base.dart 771:23                    performLayout
packages/flutter/src/rendering/object.dart 2575:7                                 layout

The Zoom is working with zoomMode: ZoomMode.xy,

**Comment by LokeshPalani** [comment]
Hi @FabioNieVec, 

 

We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below. 

 

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.40  

 

Root cause: Tried to access the stacked series y-values when the series visibility is false, and the zoom mode is 'x'. So, null exceptions occur when trying to calculate the y-axis range. 

 

If you have any further queries, please feel free to reach out to us.

 

Regards,
Lokesh P.

**Comment by FabioNieVec** [comment]
Hi @LokeshPalani,
Thanks for the fast answer and fix! I tested it and it works perfectly now! 

Kind regards
Fabio

**Comment by FabioNieVec** [comment]
Hi @LokeshPalani,
Thanks for the fast answer and fix! I tested it and it works perfectly now! 

Kind regards
Fabio
