### ISSUE TITLE
[syncfusion_flutter_datagrid] Programmatic Filtering not trigger onFilterChanged

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1798]
onFilterChanged not apply when DataGridSource.addFilter, DataGridSource.removeFilter, DataGridSource.clearFilters

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,
 
Based on the information provided, it appears that you are expecting filtering callbacks to be invoked when applying programmatic filtering. However, in SfDataGrid, filtering callbacks are currently only triggered when applying UI filtering.
 
To better assist you and gain a clearer understanding of your expectations, we kindly ask you to provide any additional details and sample regarding why you believe filtering callbacks should be invoked during programmatic filtering. This additional information will greatly aid us in further investigating the matter and delivering an appropriate solution as promptly as possible.

Regards,
Abinesh P

**Comment by Trung15010802** [comment]
> Hi @Trung15010802 ,
> 
> Based on the information provided, it appears that you are expecting filtering callbacks to be invoked when applying programmatic filtering. However, in SfDataGrid, filtering callbacks are currently only triggered when applying UI filtering.
> 
> To better assist you and gain a clearer understanding of your expectations, we kindly ask you to provide any additional details and sample regarding why you believe filtering callbacks should be invoked during programmatic filtering. This additional information will greatly aid us in further investigating the matter and delivering an appropriate solution as promptly as possible.
> 
> Regards, Abinesh P
Hi @abineshPalanisamy ,
Because if i want to create a SearchBar and use  Programmatic Filtering, the SfDatapage can't update page count

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,

Based on the information provided, it seems that you expect filtering callbacks to be invoked when applying programmatic filtering to change the page count in SfDataPager. However, in SfDataGrid, filtering callbacks are currently only triggered when applying UI filtering. We have a workaround that can help you achieve the required behavior. You need to update the DataPager’ s page count while filtering the rows. Update the pageCount value based on the length of the **DataGridSource.effectiveRows**. Within the search bar, update the page count whenever filtering is applied and removed.
 
We have attached a sample and code snippets for your reference. Please refer to the following sample for more information. If you have any further concerns, please feel free to reach out.

- **Code snippet :** 
```dart
  // To update the DataPager's page count while filtering the rows.
  void _updatePageCount() {
    final rowsCount = employeeDataSource.filterConditions.isNotEmpty
        ? employeeDataSource.effectiveRows.length
        : employeeDataSource._employeeRows.length;
    pageCount = (rowsCount / _rowsPerPage).ceil().toDouble();
  }


  Widget searchField() {
    return SizedBox(
      width: 200,
      height: 50,
      child: TextField(
        controller: searchController,
        onChanged: (value) {
          employeeDataSource.clearFilters(columnName: 'name');
          if (value.isNotEmpty) {
            employeeDataSource.addFilter(
                'name',
                FilterCondition(
                    type: FilterType.contains,
                    filterBehavior: FilterBehavior.stringDataType,
                    value: value));
          }
          WidgetsBinding.instance.addPostFrameCallback((_) {
            setState(() {
              // Need to update the page count.
              _updatePageCount();
            });
          });
          employeeDataSource.updateDataGriDataSource();
        },
        decoration: const InputDecoration(
          hintText: "serach",
        ),
      ),
    );
  }
```

- **Sample :**

     [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14957508/SfDataGrid.zip)


Regards,
Abinesh P
