### ISSUE TITLE
Code39 puts two more digits after the real value (syncfusion_flutter_barcodes)

### ISSUE THREAD

**Issue by MathieuSevegny** [syncfusion/flutter-widgets#180]
I'm using syncfusion_flutter_barcodes to show a barcode of a value in my app. But when I tried to use Code39 and code39 Extended I faced an issue. When I enter a value like "123324", it show a barcode with a value of 12332415. And when I enter a value of "532323", the reader shows "53232318". Is there a logical reason behind this? Every other barcodes works but only Code39 and Code39 Extended don't work.

My code for testing : 

import 'package:flutter/material.dart';
import 'package:wear/wear.dart';
import 'package:syncfusion_flutter_barcodes/barcodes.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: SfBarcodeGenerator(
          value: '532323',
          symbology: Code39(),
          showValue: true,
        ),
      ),
    ));
  }
}

**Comment by Dharanipalani** [comment]
Hi @MathieuSevegny,

Greetings from Syncfusion. We have analyzed your query and would like to tell you that adding additional values is the default behavior of the code39 and code39 extended. The extra value is the checksum value of the given original value, it used in some applications which require high-level accuracy.

For more information refer to the [help document.](https://help.syncfusion.com/flutter/barcode/one-dimensional#code39)

If you want to avoid adding of checksum value then you can disable it by using the **enableCheckSum** property like in the below code snippet.

`SfBarcodeGenerator(
  value: '532323',
  symbology: Code39(enableCheckSum: false),
  showValue: true,
)`

Please revert us if you have any further concerns on this.

Thanks,
Dharanitharan. P

**Comment by MathieuSevegny** [comment]
It solved my problem! 

Thank you!

Have a great day.
