### ISSUE TITLE
[syncfusion_flutter_datagrid] Next page button not trigger `onPageNavigationStart `function, previous page not trigger `onPageNavigationEnd`

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1801]
And next page button not trigger `onPageNavigationStart `function, previous page not trigger `onPageNavigationEnd`
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/515b6791-7ad8-4602-8ac5-0546c88db99f)

_Originally posted by @Trung15010802 in https://github.com/syncfusion/flutter-widgets/issues/1721#issuecomment-2050933136_

**Comment by abineshPalanisamy** [comment]
Hi @Trung15010802 ,
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([25.1.40](https://pub.dev/packages/syncfusion_flutter_datagrid)). If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.
 
Regards,
Abinesh P
