### ISSUE TITLE
End repeat bug 

### ISSUE THREAD

**Issue by samih93** [syncfusion/flutter-widgets#1804]
for example if i set endrepeat to 20240421T120000Z => that mean 21-04 not included  , and i don't want to add 1 day in backend , to avoiding add and substract days in view 
![image](https://github.com/syncfusion/flutter-widgets/assets/78031951/6b71b8fd-3e0c-462b-a721-70492b5916ff)

**Comment by LokeshPalani** [comment]
Hi @samih93,

 

We have checked the reported issue and tried to replicate it in the [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html) with version [25.1.40 ](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.40)by setting the [recurrenceRule](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/Appointment/recurrenceRule.html) to **[chart_580884.zip](https://github.com/syncfusion/flutter-widgets/files/15023237/chart_580884.zip)** in the [Appointment](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/Appointment-class.html). However, we were unable to reproduce it on our end. Please check the attached sample, and if you are still experiencing the issue, we request that you replicate it in the attached sample and provide us with more details regarding the specific scenario in which you are encountering this issue. This will help us to assist you more effectively. We have shared code snippet and screenshot for your reference.

Code Snippet:

``` dart
appointments.add(
      Appointment(
        startTime: DateTime(2024, 04, 18, 04),
        endTime: DateTime(2024, 04, 18, 08),
        subject: 'Meeting',
        color: Colors.blue,
        recurrenceRule: 'FREQ=DAILY;INTERVAL=1;UNTIL=20240421T120000Z',
      ),
    );
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/3a8c813a-b20c-475d-a427-e49a56529859)

Regards,
Lokesh P.


[chart_580884.zip](https://github.com/syncfusion/flutter-widgets/files/15023240/chart_580884.zip)
