### ISSUE TITLE
Inquiry about Grouping Rows within a Row in Data Grid

### ISSUE THREAD

**Issue by NJashwanth** [syncfusion/flutter-widgets#1807]
Hi,
I am reaching out regarding a feature inquiry for our project's data grid implementation. I am currently working on incorporating a data grid component that supports grouping rows within a row, allowing for expandable and collapsible functionality.

I'm currently using SfDataGrid , which offers a feature called grouping. However, I encountered a limitation with this feature. While it allows grouping using column names or custom logic, the group name is restricted to a string format. This presents a challenge for my specific use case, as I require the ability to group rows within a row, where the group title itself is also a row.

To provide a visual representation of my scenario, I have attached an image for reference.

Given this requirement, I am seeking guidance on whether it is possible to achieve this functionality within our current project setup. Specifically, I would like to inquire if there are any existing methods or workarounds that would allow for grouping rows within a row, with the group title also being represented as a row.

<img width="788" alt="Screenshot 2024-04-15 at 12 33 11 PM" src="https://github.com/syncfusion/flutter-widgets/assets/43280229/2227940c-8bdf-4314-9735-a80f12ef95fa">

**Comment by abineshPalanisamy** [comment]
Hi @NJashwanth ,
 
Based on the provided information, you need to group rows within a row. In SfDataGrid, you achieve this behavior by utilizing custom grouping to group the list rows under the required group. We have attached a sample and code snippets for your reference. Please consult the provided sample for more information.
 
Regarding considering the group title row as a row, currently, DataGrid does not support this feature. However, we have acknowledged your request and have it marked as a potential feature for implementation. During the planning stage of each release cycle, we assess all open features and prioritize them based on various factors such as product vision, technological feasibility, and customer interest. We appreciate your patience and understanding in the meantime. For further details, you can follow up using the feedback provided below.
 
Feedback link: [53098](https://www.syncfusion.com/feedback/53098/support-for-the-caption-summary-row-within-grouping)

- **Sample :**
     [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14997572/SfDataGrid.zip)


 
Regards,
Abinesh P

**Comment by andrewwahid** [comment]
Hi @abineshPalanisamy 
Could you also consider making the ColumnGroup widget accept a widget as its child (because as the OP mentioned it only supports having the group name as a string right now)

**Comment by abineshPalanisamy** [comment]
Hi @andrewwahid ,
 
Based on the information provided, it seems that you want to allow widgets in the ColumnGroup. In SfDataGrid, we retrieve the cell value based on the column name and perform grouping based on the cell value in the corresponding columns. Therefore, we can't consider widgets for grouping. Additionally, if you need to showcase widgets in the caption summary row, you can override the **DataGridSource.buildGroupCaptionCellWidget** method. Please refer to the following user guide documentation links for a deeper understanding.

UG link - [Grouping](https://help.syncfusion.com/flutter/datagrid/grouping)

Additionally, We have attached  code snippets for your reference.

- **Code snippet :** 
``` dart
  @override
  Widget? buildGroupCaptionCellWidget(
      RowColumnIndex rowColumnIndex, String summaryValue) {
   // Provide the required widget to display.
    return Container(
        padding: EdgeInsets.symmetric(horizontal: 12, vertical: 15),
        child: Text(summaryValue));
  }
```

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @NJashwanth,

We suspect that the reported issue has been resolved at your end. We are closing this ticket now. If you need any further assistance, you can reopen this issue. We are always happy to help you.

Regards,
Ashok K

**Comment by gltiennd** [comment]
@ashok-kuvaraja @abineshPalanisamy I really need this feature. When will it be available? Please

**Comment by abineshPalanisamy** [comment]
Hi @gltiennd ,
 
We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then.
 
Regards,
Abinesh P
