### ISSUE TITLE
Visual bug for combined line chart legend

### ISSUE THREAD

**Issue by savadodesigns** [syncfusion/flutter-widgets#181]
The coloured dots are all over the place. Used to line up correctly left of the series names.

![image](https://user-images.githubusercontent.com/21218628/114041626-fd6fce00-9884-11eb-9515-c8f53d7114d7.png)

**Comment by Dharanipalani** [comment]
Hi @savadodesigns ,

Greetings from Syncfusion. We would like to tell you that the legend overflow mode is scroll by default. When the legend width or height is greater than the chart area then default it renders as like this. But you can change the legend overflow mode by using the **overFlow** mode property in the legend. You can set it as **LegendItemOverflowMode.wrap.**

For more information, please refer to the [help document.](https://help.syncfusion.com/flutter/cartesian-charts/legend#legend-overflow)

Please revert us if you have further concerns on this.

Thanks,
Dharanitharan. P

**Comment by savadodesigns** [comment]
Hi @Dharanipalani,

Thank you for your reply and the advice concerning the overflow.

The issue I am more concerned about is the fact that the coloured circles representing the lines are all over the place. Any advice on that? Thanks in advance.

Sam.

**Comment by Dharanipalani** [comment]
Hi @savadodesigns,

We have already working on this bug and this fix will be included in the upcoming weekly patch release which is expected to be rolled out on 20th April 2021. We appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @savadodesigns,

We are happy to say that the recorded problem has been addressed in the most recent version of our charts. Now, all of the markers in the tooltip are aligned properly, and to fix this, please update our charts to the latest version from the link below.

Latest version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.57+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.57+1)

Thanks,
Dharanitharan. P

**Comment by savadodesigns** [comment]
Works like a charm. Thank you!
