### ISSUE TITLE
need widget on onMarkerRender

### ISSUE THREAD

**Issue by keskink** [syncfusion/flutter-widgets#1810]
### Use case

need to add widget to onMarkerRender event.
I need to add conditional marker to some specific data.
for example my data has 0 value in xAxis value, I want to set a start icon at the position.
and I want to set a flag icon at to included 100 on data position

### Proposal

I set only icon. But widget would be good.

onMarkerRender: (args) {
        var data = flights[0].flightData.firstWhere((element) => element.index == args.pointIndex);
        // Check your specific condition
        if (data.time == grnd ) {
          args.shape = DataMarkerType.image;
          **args.image = Icons.flight_takeoff_sharp;**
        } else if (data.time == 100 ) {
          args.shape = DataMarkerType.image;
          **args.image = Icons.flag;**
        } else
          {
            args.markerHeight = 0;
            args.markerWidth = 0;
            args.borderWidth = 0;
          }
      },

**Comment by keskink** [comment]
Hi @PreethikaSelvam,

First of all thanks for your valued answer.

But unfortunately your solution not working for me.
Because the each labels not showing on chart. My code as like this. it should work, but not working due to https://www.syncfusion.com/feedback/37565 issue.

      markerSettings: const MarkerSettings(isVisible: false),
        dataLabelSettings: DataLabelSettings(
            isVisible: true,
            // Templating the data label
            builder: (dynamic data, dynamic point, dynamic series, int pointIndex, int seriesIndex) {
              if (series!.dataSource![pointIndex].index == flights[0].groundPosition) {
                return Container(
                  //height: 30,
                  //width: 30,
                  child: const Icon(Icons.flight_takeoff_sharp),
                );
              }
              else {
                return SizedBox();
              }
            }
        )

**Comment by LokeshPalani** [comment]
Hi,

 

You can achieve your requirement by setting the [LabelIntersectAction](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelIntersectAction.html) to [LabelIntersectAction.none](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LabelIntersectAction.html#none) in the [DataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings-class.html). By doing this, the data labels will not hide when intersecting. We have shared a code snippet for your reference. Please let us know if you have any further needs.

 

Code Snippet:

``` dart
dataLabelSettings: DataLabelSettings(
              isVisible: true,
              builder: (data, point, series, pointIndex, seriesIndex) {
                return const Icon(Icons.circle);
              },
              labelIntersectAction: LabelIntersectAction.none,
            ),
```

Regards,
Lokesh P.
