### ISSUE TITLE
datagrid line color

### ISSUE THREAD

**Issue by stoneLee81** [syncfusion/flutter-widgets#182]
How to modify the color of the datagrid line？

**Comment by NeelakandanKannan** [comment]
Hi @stoneLee81 ,

Greetings from Syncfusion.

You can use the [SfDataGridThemeData.gridLineColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/gridLineColor.html) property to change the color of the grid lines. 

You can refer the below UG,
https://help.syncfusion.com/flutter/datagrid/styles#styling-grid-lines
