### ISSUE TITLE
After add package syncfusion_flutter_datagrid it's throw error like this

### ISSUE THREAD

**Issue by Jayakumar-AndroidDev** [syncfusion/flutter-widgets#1825]
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by abineshPalanisamy** [comment]
Hi @Jayakumar-AndroidDev ,

Based on the information provided, we have conducted tests to replicate the reported issues. However, we were unable to reproduce the issues as described. Kindly update the Flutter version ([3.19.6](https://flutter-ko.dev/development/tools/sdk/releases)) and SfDataGrid version([25.1.40](https://pub.dev/packages/syncfusion_flutter_datagrid)) to latest.  Additionally, please make sure you have correctly added syncfusion_flutter_datagrid to your pubspec.yaml.
 
If you are still encountering the same problem, we kindly request that you provide additional details related to the issue and the device information used to run the application. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible.
 
Regards,
Abinesh P

**Comment by Jayakumar-AndroidDev** [comment]
after restart my visual code this issue gone
