### ISSUE TITLE
show empty datagrid

### ISSUE THREAD

**Issue by stoneLee81** [syncfusion/flutter-widgets#183]
If there is no data, how to show that the header of datagrid, current  is blank

**Comment by RenugaSadagoban98** [comment]
Hi @stoneLee81 ,

Thanks for your feedback.
 
We have checked your reported issue and considered this as bug. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on 13th April 2021. 

Please refer to the below feedback link for further follow up, 
Feedback link: https://www.syncfusion.com/feedback/24163/column-header-is-not-showing-when-loading-empty-row

We will let you know once it gets rolled out. We appreciate your patience until then. Please let us know if you require any further assistance.

**Comment by RenugaSadagoban98** [comment]
Hi @stoneLee81,  

Thank you for your patience.
 
The reported issue “Column headers is not showing when loading empty rows” has resolved and we have included the changes in our weekly pub release. Please update datagrid package to 19.1.56-beta version. You can also refer to nuget.org.

Nuget link: https://www.nuget.org/
