### ISSUE TITLE
Get the coordinates in CalendarTapDetails and CalendarLongPressDetails

### ISSUE THREAD

**Issue by x-ji** [syncfusion/flutter-widgets#1833]
### Use case

I would like to trigger different actions based on where exactly the user tapped on the calendar cell. For example, tapping on the left half of the cell should create a different type of event by default compared with tapping on the right half.

### Proposal

With JS events I can get the exact coordinates where the click happened and e.g. compare it to the width of the whole calendar component to understand whether the click happened on the left part of the cell or the right part. I see that `CalendarTapDetails`'s properties only contain the `targetElement` but not the

**Comment by x-ji** [comment]
Hi @PreethikaSelvam thanks for the response. I see that `CalendarTapDetails` has the following properties:

[appointments](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarTouchDetails/appointments.html) → [List](https://api.flutter.dev/flutter/dart-core/List-class.html)?
    The collection of appointments that return from the date.

[date](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarTouchDetails/date.html) → [DateTime](https://api.flutter.dev/flutter/dart-core/DateTime-class.html)?
    The date that return from the view.

[hashCode](https://api.flutter.dev/flutter/dart-core/Object/hashCode.html) → [int](https://api.flutter.dev/flutter/dart-core/int-class.html)
    The hash code for this object.

[resource](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarTouchDetails/resource.html) → [CalendarResource](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarResource-class.html)?
    The resource associated with the calendar cell in timeline views.

[runtimeType](https://api.flutter.dev/flutter/dart-core/Object/runtimeType.html) → [Type](https://api.flutter.dev/flutter/dart-core/Type-class.html)
    A representation of the runtime type of the object.

[targetElement](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarTouchDetails/targetElement.html) → [CalendarElement](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarElement.html)
    The element that return from the view.

None of which gives me the precise coordinates within the `targetElement` this tap or long press took place, which is what I would like to make use of. On the web with HTML and Javascript, this is usually available when for example within the `onClick` event.

Does this make sense?

**Comment by x-ji** [comment]
Thanks for the update @PreethikaSelvam . I'll keep an eye on it.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
