### ISSUE TITLE
onLegendTapped is not getting called for the pie chart in the flutter version 3.19.4

### ISSUE THREAD

**Issue by Nanagoud007** [syncfusion/flutter-widgets#1835]
### Bug description

i am rendering pie chart with legend on click on that it has to trigger the functionality but it is not happening here is the code snippet

### Steps to reproduce

run the code snippet to produce 

### Code sample

<details open><summary>Code sample</summary>

```dart
Widget _pie_chart() {

    return Expanded(
      child: OverView2Function().isPiechartLoading.value
          ? Padding(
              padding: const EdgeInsets.all(8.0),
              child: Container(
                height: 300,
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              ),
            )
          : OverView2Function().connectorStatus.isNotEmpty
              ? SfCircularChart(

                  // tooltipBehavior: _tooltipBehavior,
                  title: ChartTitle(
                    text: 'Connector Status',
                    alignment: ChartAlignment.center,
                  ),

                  legend: Legend(
                      isVisible: true,
                      textStyle: TextStyle(
                          decoration: TextDecoration.underline,
                          color: Colors.blue[900]),
                      toggleSeriesVisibility: false),
                  onLegendTapped: (LegendTapArgs legendTapArgs) {
                    AppUtil.printData(legendTapArgs.pointIndex.toString(), isError: true);
                    final int? index = legendTapArgs.pointIndex;
                    final ConnectorStatusModel selectedStatus =
                    OverView2Function().connectorStatus[index!];
                    OverView2Function().getConnectorListByStatus(status: selectedStatus.status!);
                    GoRouter.of(AppUtil.context!).go(MyRoutes.connector_list_by_status +
                        '?status=${selectedStatus.status}');
                  },

                  // ignore: strict_raw_type
                  series: <CircularSeries>[
                    PieSeries<ConnectorStatusModel, String>(
                      dataSource: OverView2Function().connectorStatus,

                      pointColorMapper: (ConnectorStatusModel data, _) {
                        return OverView2Function()
                            .getTileColor(staus: data.status!);
                      },

                      xValueMapper: (ConnectorStatusModel data, _) =>
                          data.status,
                      yValueMapper: (ConnectorStatusModel data, _) =>
                          data.count,
                      dataLabelSettings: const DataLabelSettings(
                          isVisible: true,
                          labelIntersectAction: LabelIntersectAction.shift,
                          labelPosition: ChartDataLabelPosition.outside,
                          connectorLineSettings: ConnectorLineSettings(
                              type: ConnectorType.line, length: '15%')),
                      //radius: '100%',
                    )
                  ],
                )
              : const Center(
                  child: Text(
                    'No Data Found',
                  ),
                ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by LokeshPalani** [comment]
Hi @Nanagoud007,

We would like to inform you that when setting [toggleSeriesVisibility](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/toggleSeriesVisibility.html) to false in the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html) and tap on the Legend, the [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onLegendTapped.html) callback will not be triggered. The [toggleSeriesVisibility](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/toggleSeriesVisibility.html) indicates that legend item should be interactive or not, when it is set to false, the [onLegendTapped](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart/onLegendTapped.html) callback will not get triggered and this is the default behaviour. You can achieve your requirement by using the [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) widget in the [legendItemBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/legendItemBuilder.html) property for the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html). By doing this, you can get interaction details from the [GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html) widget in onTap callback when tapping on the Legend. We have shared a user guide documentation link for your reference below. Please let us know if you have any further needs.

Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
