### ISSUE TITLE
what happened to https://help.syncfusion.com????

### ISSUE THREAD

**Issue by mahdiqdi** [syncfusion/flutter-widgets#1836]
### Use case

i studied flutter syncfusion chart detail in that domain

### Proposal

where to read documantation of syncfusion charts

**Comment by LokeshPalani** [comment]
Hi @mahdiqdi,

 

In the User guide documentation, we have explained about how to create Syncfusion Flutter chart and it’s features and in the API documentation link, we have explained each API in detail. We have also shared user guide documentation link and API documentation link below for your reference. Please let us know if you need any further needs.

 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/overview

 

API documentation Link,

https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html

 

Regards,
Lokesh P.
