### ISSUE TITLE
How do I set only one axis zoom depends on pinching direction.

### ISSUE THREAD

**Issue by keskink** [syncfusion/flutter-widgets#1841]
### Use case

I need to I set only one axis zoom depends on pinching direction. independent zoom x and y axis.

### Proposal

I want to zoom only y axis when I pinch vertical or zoom only x axis when I pinch horizontal.
may be can be this parameter on ZoomMode.independent

**Comment by natrayansf** [comment]
Hi [keskink](https://github.com/keskink), 

Currently, we do not have an option for your requirement of independent mode in [zoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomMode.html) API in [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/zoomPanBehavior.html). However, we have prepared a workaround sample for your requirement of ‘How do I set only one axis zoom depending on pinching direction’ by overriding interaction callbacks in the [ZoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/zoomPanBehavior.html) and calculating the zoom position and zoom factor then deciding which axis gets tried to zoom with the help of [horizontalScale](https://api.flutter.dev/flutter/gestures/ScaleUpdateDetails/horizontalScale.html) and [verticalScale](https://api.flutter.dev/flutter/gestures/ScaleUpdateDetails/verticalScale.html) and applying it to the respective axis. We have shared a workaround sample with a zooming demo for your reference below. Please let us know if you need any further needs. 

We have shared the UG documentation below for your reference.
https://help.syncfusion.com/flutter/cartesian-charts/zoom-pan 

[independent zooming.zip](https://github.com/syncfusion/flutter-widgets/files/15199115/independent.zooming.zip)

Regards,
Natrayan

**Comment by keskink** [comment]
Many thanks for your solution. 
All ok for me. 

Thanks

**Comment by LokeshPalani** [comment]
Hi @keskink,

Most Welcome. Kindly get back to us if you have further queries. We are always happy to assist you.

Regards,
Lokesh P.
