### ISSUE TITLE
Disable Column Highlighting on Hover in Syncfusion Tables

### ISSUE THREAD

**Issue by EduardoYamauchi** [syncfusion/flutter-widgets#1845]
### Use case

Hello,

I would like to request the feature to disable the highlighting of columns when hovering over them in Syncfusion tables. This feature significantly disrupts the user experience, particularly when adding a custom menu or clickable elements at the top of the table. I noticed that it is possible to disable the highlighting of rows using the highlightRowOnHover parameter, but there is currently no similar option for column titles. Implementing this functionality would enhance the usability and customization of the tables.

Thank you for your attention, and I look forward to your response.

Best regards,

### Proposal

```dart
SfDataGrid(
highlightColumnOnHover: false, 
// ... Other properties...
)
```

**Comment by abineshPalanisamy** [comment]
Hi @EduardoYamauchi ,
 
Based on the provided details. Currently, SfDataGrid doesn't have any property to restrict the header row highlighting color on hovering. However, you can restrict the hover color of header cells by setting the header hover color to transparent using [SfDataGridThemeData.headerHoverColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/headerHoverColor.html). We have attached a sample and code snippets for your reference. Please refer to the following sample and snippets for more information. Additionally, for a more in-depth understanding, please consult the user guide documentation link provided. If you have any further concerns, please feel free to reach out.

- **Code snippet :** 
```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: SfDataGridTheme(
        data: SfDataGridThemeData(headerHoverColor: Colors.transparent),
        child: SfDataGrid( ),
      ),
    );
  }
```

- **UG link :** [Header Hover color](https://help.syncfusion.com/flutter/datagrid/styles#change-the-header-hover-color)

- **Sample :** 
   
    [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/15196513/SfDataGrid.zip)
    
Regards,
Abinesh P

**Comment by EduardoYamauchi** [comment]
It worked. Thanks.
