### ISSUE TITLE
[syncfusion_calendar_view] How to custom Quick view navigation colors ?

### ISSUE THREAD

**Issue by QuentinSc** [syncfusion/flutter-widgets#1850]
### Bug description

Can't find a way to custom the quick view navigation pannel

### Steps to reproduce

![flutter-calendar-quickview-navigation](https://github.com/syncfusion/flutter-widgets/assets/16439299/494d8a2e-0752-4cb3-8c85-13536f603f39)

### Code sample

<details open><summary>Code sample</summary>

```dart
 SfCalendar(
                    // backgroundColor: Colors.red,
                    headerStyle: CalendarHeaderStyle(
                      textAlign: TextAlign.center,
                      backgroundColor: Theme.of(context).colorScheme.surface,
                      textStyle: const TextStyle(fontSize: 20),
                    ),
                    view: CalendarView.month,
                    showDatePickerButton: true,
                    minDate: DateTime.now().subtract(const Duration(days: 7)),
                    showNavigationArrow: true,

                    },
                  ),
```

</details>

### Screenshots or Video

See above

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>
-

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @QuentinSc,

Currently, we don't have the option to customize the date picker, which appears after enabling [showDatePickerButton](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/showDatePickerButton.html) in [SfCalendar](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar-class.html). However, you can achieve this with the help of creating a custom header and showing the actual [SfDateRangePicker](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker-class.html) in the button click. We have prepared the workaround sample below for your reference.

Screenshot:
![ScreenRecording2024-04-08at3 31 32PM-ezgif com-video-to-gif-converter](https://github.com/syncfusion/flutter-widgets/assets/61863686/7b159a38-ec93-45dd-90b3-d89cc620fe60)

Sample: 
[i587667.zip](https://github.com/syncfusion/flutter-widgets/files/15258763/i587667.zip)

**Comment by QuentinSc** [comment]
Hello and thank you for your answer.
Sadly it does not fit my need.
Is there a plan to allow some customization on this part of the widget?
The background color seems to be harcode

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @QuentinSc,

We have a customized property for the SfDateRangePicker to customize all types of views in the SfDateRangePicker and shared the related UG documentation below for your reference.

UG, https://help.syncfusion.com/flutter/daterangepicker/customizations

If this is not your requirement then, please share more information about your requirement in detail along with the screenshot or screen recordings which is more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by QuentinSc** [comment]
> Hi @QuentinSc,
> 
> We have a customized property for the SfDateRangePicker to customize all types of views in the SfDateRangePicker and shared the related UG documentation below for your reference.
> 
> UG, https://help.syncfusion.com/flutter/daterangepicker/customizations
> 
> If this is not your requirement then, please share more information about your requirement in detail along with the screenshot or screen recordings which is more helpful to us to provide a solution sooner.
> 
> Regards, Yuvaraj.

Hello,

My issue concerns the SfCalendar widget, a month picker appears when you tap the header, as a popup. But I can't find a way to custom at least the background color
