### ISSUE TITLE
Unable to view summary text in SFDataGrid

### ISSUE THREAD

**Issue by jainharsh21** [syncfusion/flutter-widgets#1852]
### Bug description

I have been trying to view the summary for the revenue column but it is just showing an empty container, have been stuck on this for quite some time, please help.

### Steps to reproduce

Copy paste the code given, you will be able to reproduce

### Code sample

<details open><summary>Code sample</summary>

```dart
  return SfDataGrid(
      allowSorting: true,
      columnWidthMode: ColumnWidthMode.auto,
      gridLinesVisibility: GridLinesVisibility.both,
      headerGridLinesVisibility: GridLinesVisibility.both,
      source: ProductDataSource(productSummary),
      tableSummaryRows: [
        GridTableSummaryRow(
            showSummaryInRow: true,
            title: 'Total Revenue: {Sum}',
            columns: [
              const GridSummaryColumn(
                  name: 'Sum',
                  columnName: 'revenue',
                  summaryType: GridSummaryType.sum),
            ],
            position: GridTableSummaryRowPosition.bottom)
      ],
      columns: <GridColumn>[
        GridColumn(
          columnName: 'product',
          label: const Center(
            child: Text('Produce', style: AppTheme.fontStyleDefault),
          ),
        ),
        GridColumn(
          columnName: 'quantity',
          label: const Center(
              child: Text('Quantity', style: AppTheme.fontStyleDefault)),
        ),
        GridColumn(
          columnName: 'revenue',
          label: const Center(
            child: Text(
              'Revenue',
              style: AppTheme.fontStyleDefault,
            ),
          ),
        ),
      ],
    );
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![WhatsApp Image 2024-05-08 at 23 09 50](https://github.com/syncfusion/flutter-widgets/assets/44740658/2c7705de-9ca1-48f5-90d5-bcbe7c7883bd)

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by jainharsh21** [comment]
![WhatsApp Image 2024-05-08 at 23 09 50](https://github.com/syncfusion/flutter-widgets/assets/44740658/6208183b-4518-45ee-8435-7ca9cd9826cc)

For some reason the image isn't visible in the previous comment

**Comment by abineshPalanisamy** [comment]
Hi jainharsh,

Based on the provided details, the SfDataGrid doesn't automatically display summary values. To display the summary value, you need to override the [buildTableSummaryCellWidget](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/buildTableSummaryCellWidget.html) method in the [DataGridSource](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource-class.html) class. The calculated summary value is passed as a parameter to the DataGridSource.buildTableSummaryCellWidget method. Therefore, you need to return the required widget with the summary value. We have attached a sample and provided a UG link for your reference. Please consult the following sample and link for more information. If you have any further concerns, please feel free to reach out.
 
- **UG link -** [Table summary](https://help.syncfusion.com/flutter/datagrid/summaries#table-summary)

- **Sample :**  [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/15257900/SfDataGrid.zip)


 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @jainharsh21,

We hope that the reported issue has been resolved at your end. We're closing this issue now. If you need any further assistance, you can reopen this issue. We're always happy to help you!

Regards,
Ashok K
