### ISSUE TITLE
[Feature Request] Ability to conditionally display marker on Line/Spline series

### ISSUE THREAD

**Issue by btrautmann** [syncfusion/flutter-widgets#1855]
### Use case

![Screenshot 2024-05-09 at 11 53 26](https://github.com/syncfusion/flutter-widgets/assets/8343465/81a85b42-b614-40af-8ef6-6b8a47e73971)

In reproducing the above image, it's currently necessary to have _three_ series (rather than two) where the third series just a single data point that matches the x,y value of the second series (dark purple) so it makes the illusion that the marker is part of that series. As far as I can tell, there's no way to conditionally set markers on data points within a series.

### Proposal

I imagine the API would look something like:

```dart
markerSettings: MarkerSettings(
  isVisible: true,
  color: context.colors.brand200,
  shouldDraw: (point) => calculation()
),
```
In my case, the calculation might look something like checking whether the point's entry is the last in the source list.

**Comment by LokeshPalani** [comment]
Hi @btrautmann,


You can achieve your requirement by using the [onMarkerRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onMarkerRender.html) callback in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). By using this, you can show the marker for the last data point using the pointIndex from [MarkerRenderArgs](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/MarkerRenderArgs-class.html) for the SplineAreaSeries. We have shared a code snippet, user guide documentation link, screenshot, and sample for your reference. Please let us know if you have any further needs.

 

**UG Link,**

https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onmarkerrender

 

**Code Snippet:**

```
SfCartesianChart(
      onMarkerRender: (MarkerRenderArgs markerArgs) {
            markerArgs.borderColor =
                markerArgs.pointIndex == chartDataTwo.length - 1
                    ? Colors.pink
                    : Colors.transparent;
            markerArgs.color = markerArgs.pointIndex == chartDataTwo.length - 1
                ? Colors.pink
                : Colors.transparent;
          },
      )
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/1801105f-e1d1-4e9d-af64-4515401b7eab)

Regards,
Lokesh P.

[chart_588998.zip](https://github.com/syncfusion/flutter-widgets/files/15275285/chart_588998.zip)

**Comment by LokeshPalani** [comment]
Hi @btrautmann,

By using [CartesianChartAnnotation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation-class.html), you can also display the marker on the segment at different datapoints by setting the[ x](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation/x.html) and [y](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianChartAnnotation/y.html) positions from the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html). We have shared a user guide documentation link for your reference.

 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/annotations#positioning-the-annotation

 

Regards,
Lokesh P.
