### ISSUE TITLE
in syncfusion_flutter_datepicker ver 25.2.3 /lib/src/date_picker build error

### ISSUE THREAD

**Issue by volkanugur** [syncfusion/flutter-widgets#1857]
### Bug description

When try to build for ios i've get this error. **pub.dev/syncfusion_flutter_datepicker-25.2.3/lib/src/date_picker/date_picker.dart:10065:35: Error: A value of type 'Set<LogicalKeyboardKey>' can't be assigned to a variable of type 'bool'.**

### Steps to reproduce

just i was update the package and try to compile for ios.

### Code sample

that error not raised depended on my code, i've get this error while building

### Screenshots or Video

![image](https://github.com/syncfusion/flutter-widgets/assets/413624/8591c934-022d-48b7-852a-57275ba568a3)

### Stack Traces

i cannot build yet, i've get this error while building

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.16.8, on macOS 14.4.1 23E224 darwin-arm64, locale en-TR)
    ! Warning: `flutter` on your path resolves to /Users/Shared/Works/SDK/flutter/bin/flutter, which is not inside your current Flutter SDK checkout at
      /Users/Shared/Works/SDK/Flutter. Consider adding /Users/Shared/Works/SDK/Flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to /Users/Shared/Works/SDK/flutter/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/Shared/Works/SDK/Flutter. Consider adding /Users/Shared/Works/SDK/Flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.89.1)
[✓] VS Code (version 1.71.0)
[✓] VS Code (version 1.68.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @volkanugur ,

We have migrated our source which is compatible with Flutter SDK 3.19.0, in Flutter SDK version 3.19.0 they have done breaking changes in the RawKeyEvent and replaced it with HardWareKeyBoard. So, we kindly request you to upgrade the Flutter SDK version to 3.19.0 or else use the packages syncfusion_flutter_datepicker version below 24.2.7. We have also shared the breaking changes documentation below for your reference.

We hope it will help you to resolve the issue, if you have any further queries please get back to us. We are always happy to assist you.

Flutter 3.19.0 breaking change, https://docs.flutter.dev/release/breaking-changes/key-event-migration#migrating-iskeypressed-and-related-functions

Also, we would like to share our package compatibility with respect to the Flutter SDK below.

UG: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

Regards,
Yuvaraj.
