### ISSUE TITLE
Multi-touch like Apple IOS stock charts

### ISSUE THREAD

**Issue by brianschardt** [syncfusion/flutter-widgets#186]
Hi I am looking for multi-touch support for chart support. I have read your response on this github issue: https://github.com/syncfusion/flutter-widgets/issues/57

However, that does not solve the problem. The goal is for the user experience to be as good as Apple's. Right now users on the apple stock graph can select 2 points at the same time with different fingers and then find the difference in price between those 2 points. They can easily move their fingers and it responds immediately. 

Do you have any ETA for this getting done. If you guys had this we would pay for a license quickly.

**Comment by Dharanipalani** [comment]
Hi @brianschardt,

We have analyzed this requirement and considered this a new feature request. Also logged a feedback request in our portal and you can find it from the below link

Feedback link – [https://www.syncfusion.com/feedback/24153](https://www.syncfusion.com/feedback/24153)

As we have already planned our upcoming release (2021 Volume 2) roadmap, we couldn’t provide an exact timeline for this now. We will consider this feature based on the priority and complexities of the other features in our queue. We will update the feedback, once it got implemented. Please be patience until then.

Also, if you have any additional requirements or information regarding this feature, please post it in the comment section of this feedback.

Thanks,
Dharanitharan. P
