### ISSUE TITLE
[syncfusion_flutter_charts] tooltips go off screen for long labels

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-widgets#1860]
### Bug description

For long labels (ex. a long x value in a bar graph) the tooltip goes off page so you can't see the series name and the y value in the tooltip. As far as I can tell there is no way to fix this or constrain the width without rebuilding the tooltip from scratch.

### Steps to reproduce

1. Create a bar graph with very long x axis values (categorical)
2. Enable tooltip
3. View the tooltip

### Code sample

I do not have a minimum reproducible code sample, it should be simple enough as the requirement is just to add a width constraint to the tooltip in the image

### Screenshots or Video

<img width="1130" alt="Screenshot 2024-05-13 at 08 56 39" src="https://github.com/syncfusion/flutter-widgets/assets/37046316/95bfaff9-f9b5-4c75-9b88-6456806289d9">

### Stack Traces

no error

### On which target platforms have you observed this bug?

macOS

### Flutter Doctor output

not relevant

**Comment by LokeshPalani** [comment]
Hi @Justus-M,


We have validated your query and attached screenshot. We have checked in the latest version [25.2.4](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.2.4). In the attached screenshot, we have noticed that you have given longer x value. So, the tooltip was not rendered within the Plot Area. To overcome this issue, we suggest that you use the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property in the [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html). By using this, you can display the tooltip content within the Plot Area. We have displayed the tooltip content by placing the two [RichText](https://api.flutter.dev/flutter/widgets/RichText-class.html) widgets inside the [Row](https://api.flutter.dev/flutter/widgets/Row-class.html). We have also shared a workaround sample, screenshot, and a user guide documentation link for your reference. Please let us know if you require any additional assistance.

 

**UG Link,**

https://help.syncfusion.com/flutter/cartesian-charts/tooltip#tooltip-template

 

**Code Snippet:**

``` dart
builder: (data, point, series, pointIndex, seriesIndex) {
  String tooltipHeader = series.name.toString();
  const textStyle = TextStyle(color: Colors.white);
  const padding = EdgeInsets.only(bottom: 5);
  
  return ClipRRect(
    borderRadius: BorderRadius.circular(15),
    child: Container(
      color: Colors.black26,
      padding: const EdgeInsets.all(5),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            tooltipHeader,
            textAlign: TextAlign.center,
            style: textStyle,
          ),
          const Padding(padding: padding),
          const SizedBox(
            height: 2,
            width: 80,
            child: ColoredBox(color: Colors.white),
          ),
          SizedBox(
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Flexible(
                  child: RichText(
                    overflow: TextOverflow.ellipsis,
                    text: TextSpan(
                      text: '${point.x}',
                    ),
                  ),
                ),
                RichText(
                  overflow: TextOverflow.ellipsis,
                  text: TextSpan(
                    text: ' : ${point.y}',
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    ),
  );
},
```
Regards,
Lokesh P.

[chart_590750.zip](https://github.com/syncfusion/flutter-widgets/files/15335086/chart_590750.zip)

**Comment by Justus-M** [comment]
Hi @LokeshPalani 

The problem is this custom tooltip doesn't look anything like the original tooltip, and I think since you can limit the width of the x Axis for this same reason (because it's expected that some apps will have long x-Axis values) you should also be able to limit the width of the Tooltip.

As far as I understand, the only reason why you can limit the width of the x Axis labels is because Syncfusion is supporting use cases with long x-Axis values. But if that's the case, why not also allow limiting the width of the tooltips? Otherwise you have to create your own tooltip from scratch and it doesn't look as good as the original.

Alternatively, can you provide the code from the original tooltip?

**Comment by LokeshPalani** [comment]
Hi @Justus-M,


Here, we designed the builder tooltip widget similar to the default tooltip. We created a custom renderer for the series to restrict the tooltip width and to get the tooltip marker color. Below, we have shared a sample for your reference. Please let us know if you need any further assistance.


**Code Snippet:**

``` dart
tooltipBehavior: TooltipBehavior(
  enable: true,
  builder: (dynamic data, ChartPoint point, ChartSeries series, int pointIndex, int seriesIndex) {
    final ThemeData themeData = Theme.of(context);
    final TextStyle textStyle = themeData.textTheme.bodySmall!.copyWith(
      color: themeData.colorScheme.onInverseSurface,
    );
    final TextStyle headerStyle = textStyle.copyWith(fontWeight: FontWeight.bold);
    const String header = "Series Name";
    final Size headerSize = measureText(header, headerStyle);
    final String text = '${point.x} : ${point.y}';
    final Size textSize = measureText(text, textStyle);
    const EdgeInsets tooltipInnerPadding = EdgeInsets.all(6);
    const EdgeInsets tooltipMarkerPadding = EdgeInsets.all(2.0);
    const double tooltipMarkerSize = 10.0;
    const EdgeInsetsDirectional tooltipItemSpacing = EdgeInsetsDirectional.only(end: 3.0);

    double headerAlignedSize = max(headerSize.width, textSize.width);
    double dividerWidth = headerAlignedSize;
    if (headerAlignedSize >= _seriesSize.width) {
      headerAlignedSize = _seriesSize.width - tooltipInnerPadding.horizontal;
      dividerWidth = headerAlignedSize;
    } else {
      dividerWidth += tooltipMarkerSize + tooltipMarkerPadding.horizontal;
    }

    dividerWidth = min(dividerWidth, _seriesSize.width);
    final double xTextSize = dividerWidth -
        tooltipMarkerSize -
        tooltipItemSpacing.horizontal -
        tooltipMarkerPadding.horizontal -
        tooltipInnerPadding.horizontal -
        measureText(' : ${point.y}', textStyle).width;

    final bool hasHeader = header.isNotEmpty;
    Widget tooltip = Column(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        if (hasHeader)
          SizedBox(
            width: headerAlignedSize,
            child: Center(child: Text(header, style: headerStyle)),
          ),
        if (hasHeader)
          SizedBox(
            width: dividerWidth,
            child: Divider(
              height: 10.0,
              thickness: 0.5,
              color: themeData.colorScheme.onInverseSurface,
            ),
          ),
        if (text.isNotEmpty)
          Row(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Padding(
                padding: tooltipItemSpacing,
                child: Container(
                  padding: tooltipMarkerPadding,
                  width: tooltipMarkerSize,
                  height: tooltipMarkerSize,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    color: _seriesColor,
                    border: Border.all(
                      color: Colors.white,
                      width: 1.0,
                    ),
                  ),
                ),
              ),
              SizedBox(
                width: xTextSize,
                child: RichText(
                  overflow: TextOverflow.ellipsis,
                  text: TextSpan(text: '${point.x}', style: textStyle),
                ),
              ),
              Text(' : ${point.y}', style: textStyle),
            ],
          ),
      ],
    );

    return Padding(
      padding: tooltipInnerPadding,
      child: tooltip,
    );
  },
),

series: [
  BarSeries<ChartData, String>(
    xValueMapper: (ChartData data, int index) => data.x,
    yValueMapper: (ChartData data, int index) => data.y,
    dataSource: _chartData,
    onCreateRenderer: (series) {
      return _BarSeriesRenderer(this);
    },
  ),
],

class _BarSeriesRenderer extends BarSeriesRenderer<ChartData, String> {
  _BarSeriesRenderer(this._state);

  final _WorkaroundSampleState _state;

  @override
  void customizeSegment(ChartSegment segment) {
    super.customizeSegment(segment);
    _state._seriesColor = segment.fillPaint.color;
  }

  @override
  void performLayout() {
    super.performLayout();
    _state._seriesSize = size;
  }
}
```

**Screenshot:**

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/24693d42-a355-4bab-85c5-0d2e0a74fe5a)

Regards,
Lokesh P.
