### ISSUE TITLE
How to convert pdf to excel, doc and jpg?

### ISSUE THREAD

**Issue by junaidfiaz143** [syncfusion/flutter-widgets#187]

**Comment by Anand3595** [comment]
Hi Junaid Fiaz,

Currently, we do not have support for converting PDF to excel, doc and image in flutter.

We have logged below feature requests and we don't have any immediate plan to implement.
-	https://www.syncfusion.com/feedback/24217/support-for-converting-pdf-to-image
-	https://www.syncfusion.com/feedback/24218/support-for-converting-pdf-to-excel 
-	https://www.syncfusion.com/feedback/24219/support-for-converting-pdf-to-word-document

With Regards,
Anand Panchamoorthi

**Comment by junaidfiaz143** [comment]
Thanks, @Anand3595 Anand Panchamoorthi for your prompt response.
