### ISSUE TITLE
[syncfusion_flutter_datepicker] - Add focusNode to control cell focus

### ISSUE THREAD

**Issue by guilhermedaldim** [syncfusion/flutter-widgets#1871]
### Use case

In my web app I use navigation with keyboard and I need to control focus on the cell for select single or range date, but I can't do this, because the Focus Widget can't enter on cells.

### Proposal

 If focusNode is exposed in the class DateRangePickerCellDetails I think that I can control the focus in the cell. Or other way to arrive in this result.

**Comment by EderCosta21** [comment]
I have a similar problem here

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @guilhermedaldim ,



We have keyboard navigation support in our SfDateRangePicker widget and we have UG documentation to explain how to navigate select and switch focus on another clickable element in the date picker. Please find the UG documentation below for your reference. If you have any further queries please get back to us. We are always happy to assist you.



UG, https://help.syncfusion.com/flutter/daterangepicker/accessibility#keyboard-navigation



Regards,
Yuvaraj.

**Comment by guilhermedaldim** [comment]
Hi @PreethikaSelvam, thanks for your support and disponibilty. I really needs this feature for a delivery to a client.

I'll follow the new versions to test this feature.

Thanks so much!
