### ISSUE TITLE
Chart rendering issue

### ISSUE THREAD

**Issue by SaadSel** [syncfusion/flutter-widgets#1872]
### Bug description

in the beggining of the chart display, the rendering is not correct ( color and width)

### Steps to reproduce

1. no steps

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

https://github.com/syncfusion/flutter-widgets/assets/76970199/dc8b6f46-bcda-4dcb-8540-2c599fb36a43

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [version 10.0.22631.3593], locale fr-FR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.85.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 2 categories.

```

</details>

**Comment by LokeshPalani** [comment]
Hi @SaadSel,

 

We have checked the reported issue and tried to replicate it in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) with version [25.2.5 ](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.2.5)by enabling the [autoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) and added datapoint at the last index using [updateDataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController/updateDataSource.html) with [ChartSeriesController](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeriesController-class.html)﻿﻿ and applied color using [pointColorMapper ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/pointColorMapper.html)in the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html). However, we were unable to reproduce it on our end. Please check the attached sample, and if you are still experiencing the issue, we request that you replicate it in the attached sample and provide us with more details regarding the specific scenario in which you are encountering this issue. This will help us to assist you more effectively.

 

Regards,
Lokesh P.

[github_1872_chart_display (1).zip](https://github.com/syncfusion/flutter-widgets/files/15450281/github_1872_chart_display.1.zip)
