### ISSUE TITLE
Please make an optional textStyle parameter.

### ISSUE THREAD

**Issue by mahmudunnabiRain** [syncfusion/flutter-widgets#1873]
### Use case

Adding textStyle parameter will allow us to change the color of text for dark mode or any other purpose.

### Proposal

Adding textStyle parameter will allow us to change the color of text for dark mode or any other purpose.

**Comment by VijayakumarMariappan** [comment]
Hi @mahmudunnabiRain

We couldn't clearly understand your query from your content. Could you please share the following details to check further on our end?
- Which widget is the proposed feature request for?
- What feature have you used and are asking for improvement on?
It will be easier to understand if you share any references as images or videos.

**Comment by mahmudunnabiRain** [comment]
I meant there is no option to change the textStyle of the calendar. If you allow us to do that it would help a lot.

**Comment by mahmudunnabiRain** [comment]
Great to know. Thank you very much for looking into it.
