### ISSUE TITLE
[syncfusion_flutter_charts] point is not at the top

### ISSUE THREAD

**Issue by wenchaosong** [syncfusion/flutter-widgets#1874]
### Bug description

as the video show, the bottom chart is use 
```
syncfusion_flutter_charts: ^25.2.4
```

and the above chart is use 
```
fl_chart: ^0.67.0
```

I used two chart plugin and find a question
the different is at the corner, fl_chart is very near the top, but syncfusion_flutter_charts is away from the top

so, my question is 

how to let the syncfusion_flutter_charts near the top ?

### Steps to reproduce

as video show

### Code sample

just a simple use

### Screenshots or Video

https://github.com/syncfusion/flutter-widgets/assets/16938075/b714f76c-6589-4373-b30a-c2851c4319dd

### Stack Traces

as video show

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

Flutter (Channel stable, 3.19.6, on macOS 14.3.1 23D60 darwin-x64, locale zh-Hans-CN)

**Comment by LokeshPalani** [comment]
Hi,

 

We would like to inform that, the Trackball tooltip will render in the right position. When the tooltip exceeds the plot Area, the tooltip will move to the left side. This is the default behavior of Trackball tooltip in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). You can achieve your outcome by using the Custom TrackballBehavior in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). By using the Trackball public methods, you can customize the Trackball appearance in the SfCartesianChart. We have prepared a workaround sample by drawing marker and text in the [onPaint](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/onPaint.html) method. In this, you can get the ChartPoint details using chartPointInfo, and you can place the tooltip inside the Plot Area when it exceeds outside using plotAreaBounds in the _textPosition method. Additionally, we have shared code snippet, screen recording, user guide documentation link, and sample for your reference. Please let us know if you need any further needs.

 

UG Link,

https://help.syncfusion.com/flutter/cartesian-charts/methods#onpaint-in-trackballbehavior

 

Code Snippet:

``` dart
@override
void onPaint(PaintingContext context, Offset offset,
    SfChartThemeData chartThemeData, ThemeData themeData) {
  if (chartPointInfo.isEmpty) {
    return;
  }

  final Offset position =
      Offset(chartPointInfo[0].xPosition!, chartPointInfo[0].yPosition!);
  final String label = chartPointInfo[0].label!;

  // Draw custom marker.
  final Paint markerPaint = Paint()
    ..color = Colors.pink
    ..style = PaintingStyle.fill;
  context.canvas.drawCircle(position, 3, markerPaint);

  // Draw custom trackball text.
  final Paint textPaint = Paint()
    ..color = Colors.grey.shade200
    ..strokeWidth = 17
    ..strokeJoin = StrokeJoin.round
    ..strokeCap = StrokeCap.round
    ..style = PaintingStyle.stroke;
  final TextStyle textStyle = TextStyle(
    color: Colors.black,
    fontSize: 12,
    fontWeight: FontWeight.bold,
    background: textPaint,
  );

  _drawText(
    context.canvas,
    label,
    _textPosition(position.translate(-5, -32), label, textStyle),
    textStyle,
  );
}

// Display Trackball inside the PlotArea
Offset _textPosition(Offset position, String label, TextStyle textStyle) {
  final Size labelSize = measureText(label, textStyle);
  double xPos = position.dx;
  double yPos = position.dy;
  if (parentBox != null) {
    final Rect plotAreaBounds = parentBox!.paintBounds;
    if (xPos + labelSize.width > plotAreaBounds.right) {
      xPos = plotAreaBounds.right - (2 * labelSize.width);
    }
    if (xPos <= plotAreaBounds.left) {
      xPos = plotAreaBounds.left + (1 * labelSize.width);
    }
    if (yPos <= plotAreaBounds.top) {
      yPos = plotAreaBounds.top + (2 * labelSize.height);
    }
    if (yPos + labelSize.height < plotAreaBounds.top) {
      yPos = plotAreaBounds.top + (2 * labelSize.height);
    }
  }
  return Offset(xPos, yPos);
}

void _drawText(Canvas canvas, String text, Offset point, TextStyle style) {
  final TextPainter textPainter = TextPainter(
    text: TextSpan(text: text, style: style),
    textAlign: TextAlign.center,
    textDirection: TextDirection.ltr,
  );

  textPainter.layout();
  textPainter.paint(canvas, point);
}

```

Regards,
Lokesh P.

[github_1874_tooltip_ui (1).zip](https://github.com/syncfusion/flutter-widgets/files/15450272/github_1874_tooltip_ui.1.zip)

**Comment by wenchaosong** [comment]
this is very good and useful
