### ISSUE TITLE
[syncfusion_flutter_datepicker] Inconsistent Height of Month Selector with Vertical Scroll View and Small Fixed Height

### ISSUE THREAD

**Issue by huantd0111** [syncfusion/flutter-widgets#1877]
### Bug description

**Description**
When using the syncfusion_flutter_datepicker with vertical scroll mode and a fixed height (e.g., 300), there is padding at the bottom of the month view equivalent to the height of one row. When the numberOfWeeksInView property is set to 5, the padding disappears, but the view displays parts of two months instead of only the current month.

**Actual Behavior**
With a fixed height and vertical scroll mode, the bottom of the month view has padding equivalent to one row.
When numberOfWeeksInView is set to 5, parts of two months are displayed in the view instead of only the current month.

**Expected Behavior**

- Remove the padding and display five rows so that the height of the rows is maximized. This is beneficial for UIs with limited height for the date picker.

**Additional Notes**
Please provide a fix to ensure the date picker behaves as expected in scenarios with limited height and vertical scroll mode. Thank you.

### Steps to reproduce

1. Wrap the widget with a fixed height of 300.
2. Set the properties:
```dart
navigationDirection: DateRangePickerNavigationDirection.vertical,
navigationMode: DateRangePickerNavigationMode.scroll,
```
3. Observe the bottom padding in the month view.
![Screenshot 2024-05-22 at 17 25 16](https://github.com/syncfusion/flutter-widgets/assets/56102709/bfeb5a1b-9a7d-4efe-b8d0-bfda8c9d97e8)

4. Set the property _numberOfWeeksInView: 5_
5. Observe that parts of two months are displayed in the view instead of only the selected month.
![Screenshot 2024-05-22 at 17 34 57](https://github.com/syncfusion/flutter-widgets/assets/56102709/3437bb9c-94ff-4bae-aedd-7d452582212d)

### Code sample

<details open><summary>Code sample</summary>

```dart
Container(
                  height: 300,
                  constraints: BoxConstraints(
                    maxHeight: 300,
                  ),
                  child: SfDateRangePicker(
                    backgroundColor: Colors.white,
                    headerStyle: DateRangePickerHeaderStyle(backgroundColor: Colors.red, textStyle: FontUtil.medium_16),
                    monthViewSettings: DateRangePickerMonthViewSettings(
                      dayFormat: 'EEE',
                      viewHeaderHeight: 40.h,
                      firstDayOfWeek: 1,
                      numberOfWeeksInView: 6,
                      //showTrailingAndLeadingDates : true,
                      viewHeaderStyle: DateRangePickerViewHeaderStyle(
                        textStyle: FontUtil.regular_12.copyWith(color: Color(0xFF3C3C43)),
                      ),
                    ),
                    isShowHeaderLine: true,
                    //locale: LocalizationService.locale,
                    selectionMode: controller.state.flightType.value == FlightType.ONE_WAY.index
                        ? DateRangePickerSelectionMode.single
                        : DateRangePickerSelectionMode.range,
                    minDate: DateTime.now(),
                    maxDate: DateTime.now().add(Duration(days: 365)),
                    monthCellStyle: DateRangePickerMonthCellStyle(
                      textStyle: FontUtil.regular_14,
                      todayTextStyle: FontUtil.regular_14,
                      disabledDatesTextStyle: FontUtil.regular_14.copyWith(color: Color(0xFF8089A9)),
                      todayCellDecoration: BoxDecoration(color: Color(0x1A500EC1), shape: BoxShape.circle),
                    ),
                    rangeTextStyle: FontUtil.regular_14,
                    startRangeSelectionColor: Color(0xFF500EC1),
                    endRangeSelectionColor: Color(0xFF500EC1),
                    rangeSelectionColor: Color(0x33500EC1),
                    selectionTextStyle: FontUtil.regular_14.copyWith(color: Colors.white),
                    headerHeight: 40.h,
                    navigationDirection: DateRangePickerNavigationDirection.vertical,
                    navigationMode: DateRangePickerNavigationMode.scroll,
                    ///for custom item with tag
                    /*cellBuilder: (context, details){
                                return Container(
                                  child: Center(
                                    child: Text(
                                      details.date.day.toString(),
                                      textAlign: TextAlign.center,
                                    ),
                                  ),
                                );
                              },*/
                    enableMultiView: false,
                  ),
                ),
```

</details>

### Screenshots or Video

![Screenshot 2024-05-22 at 17 25 16](https://github.com/syncfusion/flutter-widgets/assets/56102709/2489b44b-a169-4689-bb73-14e2cf39d99f)
![Screenshot 2024-05-22 at 17 34 57](https://github.com/syncfusion/flutter-widgets/assets/56102709/7bdbe68a-3be4-4ce9-8ab7-0c64c80b4919)

### Stack Traces

none

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

 Flutter (Channel stable, 3.19.6, on macOS 13.6.6 22G630 darwin-x64, locale en-VN)
syncfusion_flutter_datepicker 25.2.5

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @huantd0111 ,

Currently, we don't have an option to remove the space below the leading date. and we have already logged a Feature request in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback: https://www.syncfusion.com/feedback/44304/auto-height-support-for-date-picker

Regards,
Yuvaraj.
