### ISSUE TITLE
[syncfusion_flutter_calendar] allowAppointmentResize how to use it on mobile

### ISSUE THREAD

**Issue by zenghuayang** [syncfusion/flutter-widgets#1878]
### Use case

allowAppointmentResize how to use it on mobile

### Proposal

allowAppointmentResize how to use it on mobile

**Comment by Yuvaraj-Gajaraj** [comment]
Hi,

Currently, we don't have support for allowing appointment resize in mobile platforms and it is only applicable for the web platform alone. We have already logged a feature request in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback, https://www.syncfusion.com/feedback/30674/provide-a-support-for-appointment-resizing-in-mobile-platform-of-flutter-calendar

**Comment by DaxeshV** [comment]
Hi team,

I hope you're doing well! I wanted to kindly check if there have been any updates regarding the support for appointment resizing on mobile platforms in the Syncfusion Flutter Calendar. 

This feature would be incredibly useful for our project, and we're eagerly looking forward to its availability. If possible, could you share an estimated timeline or any progress updates? 

Thank you for your efforts, and I appreciate your hard work in continuously improving the library!
