### ISSUE TITLE
[DataGrid] different width for columns (dependent on the content length)

### ISSUE THREAD

**Issue by qbait** [syncfusion/flutter-widgets#188]
Currently my columns have the same width
<img width="303" alt="Screenshot 2021-04-12 at 16 01 32" src="https://user-images.githubusercontent.com/2264901/114407523-c3663b00-9ba8-11eb-9825-1e920ed02560.png">

I would like DataGrid to automatically set width dependently on the content length, is that possible?

**Comment by RenugaSadagoban98** [comment]
Hi @qbait ,
 
Greetings from syncfusion. 

Currently, SfDataGrid does not have support for autofit (width and height) row and column.  We have considered your request as a feature. This feature will be implemented in our any of our upcoming release. We will let you know when this feature is implemented. You can refer to the below feedback for further follow up, 
 
Feedback link: https://www.syncfusion.com/feedback/22622/support-to-autofit-the-column-and-row-for-widget-column   


We appreciate your patience until then.    
 
You can set the column width as required using GridTextColumn.width property,
https://help.syncfusion.com/flutter/datagrid/column-types#set-manual-width-for-column

**Comment by qbait** [comment]
Fair enough, will use `GridTextColumn.width` for now then. Thank you.
