### ISSUE TITLE
[syncfusion_flutter_charts] Fill color not correctly set in SplineAreaSeries when y is less than 0

### ISSUE THREAD

**Issue by KrohnMi** [syncfusion/flutter-widgets#1881]
### Bug description

When I define the color in a SplineAreaSeries and the y-value is less than 0, I expect the color to start from the smallest y-value and not from 0. Otherwise, this leads to an unattractive representation of the graph.

### Steps to reproduce

1. Create a SplineAreaSeries with a data point whose y-value is less than 0.
2. Define a fill color for the SplineAreaSeries.
3. Observe the graph's representation.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart' hide LabelPlacement;

class Data {
  Data({required this.x, required this.y});
  final double x;
  final double y;
}

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final double _min = 2.0;
  final double _max = 19.0;
  late SfCartesianChart splineChart;

  @override
  void dispose() {
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
  }

  final List<Data> chartData = <Data>[
    Data(x: 2.0, y: -2.2),
    Data(x: 3.0, y: -3.4),
    Data(x: 4.0, y: -2.8),
    Data(x: 5.0, y: -1.6),
    Data(x: 6.0, y: -2.3),
    Data(x: 7.0, y: -2.5),
    Data(x: 8.0, y: 2.9),
    Data(x: 9.0, y: 3.8),
    Data(x: 10.0, y: 3.7),
    Data(x: 11.0, y: 2.2),
    Data(x: 12.0, y: 3.4),
    Data(x: 13.0, y: 2.8),
    Data(x: 14.0, y: 1.6),
    Data(x: 15.0, y: 2.3),
    Data(x: 16.0, y: 2.5),
    Data(x: 17.0, y: 2.9),
    Data(x: 18.0, y: 3.8),
    Data(x: 19.0, y: 3.7),
  ];
  @override
  Widget build(BuildContext context) {
    splineChart = SfCartesianChart(
      margin: const EdgeInsets.only(left: 10, right: 10, bottom: 20),
      primaryXAxis: NumericAxis(
        minimum: _min,
        maximum: _max,
        isVisible: true,
      ),
      primaryYAxis: const NumericAxis(isVisible: true),
      plotAreaBorderWidth: 0,
      series: <SplineAreaSeries<Data, double>>[
        SplineAreaSeries<Data, double>(
          color: const Color.fromARGB(255, 126, 184, 253),
          dataSource: chartData,
          animationDuration: 0,
          xValueMapper: (Data sales, int index) => sales.x,
          yValueMapper: (Data sales, int index) => sales.y,
        ),
      ],
    );

    return Column(
      children: <Widget>[
        Container(
          child: splineChart,
        ),
      ],
    );
  }
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1470" alt="Bildschirmfoto 2024-05-23 um 07 43 36" src="https://github.com/syncfusion/flutter-widgets/assets/46626775/763c7448-314c-482b-867c-dc881d653a81">

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
No Stacktrace
```

</details>

### On which target platforms have you observed this bug?

iOS, macOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] VS Code (version 1.88.1)
[✓] Connected device (5 available)
[✓] Network resources

! Doctor found issues in 3 categories.
```

</details>

**Comment by LokeshPalani** [comment]
Hi @KrohnMi,

We have validated the attached code snippet and screenshot. The [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html) was rendered correctly based on the given [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html'). The origin point of [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html) is 0, so positive datapoints were filled with color from 0 to the top and the negative datapoints were filled with color from 0 to the bottom. This is the rendering behavior of the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html) in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We kindly request you to share more details about what issue you are facing in detail. This will help you to assist you in better way.

 

Additionally, if you expect to display the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html) starting from -4, you can set the [crossesAt](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/crossesAt.html) to -4 in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html). We have shared code snippet, screenshot, online sample link, and user guide documentation link for your reference below.

 

SB Link: https://flutter.syncfusion.com/#/cartesian-charts/axis-features/axis-crossing

 

UG Link: https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#axis-crossing

 

Code Snippet:

```
 primaryXAxis: NumericAxis(
        minimum: _min,
        maximum: _max,
        isVisible: true,
        crossesAt: -4,
        placeLabelsNearAxisLine: false,
      ),
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/b83c585f-9cd1-48c2-bad2-b84721894475)

Regards,
Lokesh P.
