### ISSUE TITLE
[syncfusion_flutter_charts] bug in rebuilt SplineSeries

### ISSUE THREAD

**Issue by Lorenzobettega** [syncfusion/flutter-widgets#1882]
### Bug description

In an update between the last versions, the spline chart starts with an unexpected problem when I update the screen size. It generates this bug repeatedly:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was made while rebuilding dirty elements:
setState() or markNeedsBuild() called during build.
This CartesianChartArea widget cannot be marked as needing to be built because the framework is already
in the process of building widgets. A widget can be marked as needing to be built during the build
phase only if one of its ancestors is currently building. This exception is allowed because the
framework builds parent widgets before children, which means a dirty descendant will always be
built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  CartesianChartArea
The widget which was currently being built when the offending call was made was:
  SplineSeries<ModeloGrafico, dynamic>

The relevant error-causing widget was:
  SplineSeries<ModeloGrafico, dynamic>
  SplineSeries:file:///C:/Users/loret/%C3%81rea%20de%20Trabalho/FertplanApp/fertplan/lib/telas/indicadores/graficos/grafico1_controller.dart:96:12


The element being rebuilt at the time was index 359 of 550:
  SplineSeries<ModeloGrafico, dynamic>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Steps to reproduce

I can't seem to reproduce this bug in a separate code. I've tried many times, but it just won't happen. Despite that, I will add the separate archive here.

I'm writing this because the other charts are working normally, and it appears that there is no bug in my code. It was working before the change from version 23.1.39 to 24.1.41.

### Code sample

[syncfusion_rebuilt.zip](https://github.com/syncfusion/flutter-widgets/files/15418714/syncfusion_rebuilt.zip)

### Screenshots or Video

Can you see that initially, everything appears normal, but the issue arises when setState is called?
https://github.com/syncfusion/flutter-widgets/assets/84482292/f2db4d8a-e50a-4e06-aa63-387ca2a424c6

### Stack Traces

[syncfusion_rebuilt.zip](https://github.com/syncfusion/flutter-widgets/files/15418889/syncfusion_rebuilt.zip)

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [versÆo 10.0.22631.3593], locale pt-BR)
[!] Windows Version (Problem detected with Windows installation)
    ! The Topaz OFD Security Module was detected on your machine. You may need to disable it to build Flutter applications.
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 3 categories.

**Comment by LokeshPalani** [comment]
Hi @Lorenzobettega,


We have checked the attached sample, but there is no code snippet included. We have also checked the reported issue and tried to replicate it in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) with version [25.2.6](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.2.6) by setting the [SplineSeries ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineSeries-class.html)in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We have tested by resizing the output screen size. However, we were unable to reproduce it on our end. Please check the attached sample and screen recording, and if you are still experiencing the issue, we request that you replicate it in the attached sample and provide us with more details regarding the specific scenario in which you are encountering this issue. This will help us to assist you more effectively.

Regards,
Lokesh P.

[github_1882_splineseries.zip](https://github.com/syncfusion/flutter-widgets/files/15480092/github_1882_splineseries.zip)
