### ISSUE TITLE
Calendar: Allow spanning multiple timeslots at the same time when creating an event

### ISSUE THREAD

**Issue by x-ji** [syncfusion/flutter-widgets#1887]
### Use case

In the timeslot view, every timeslot has a fixed length. However, sometimes an event might last longer than the default length. For example, a meeting that lasts 2 hours instead of 1 hour, in which case the event should span 2 slots instead of 1. In places such as Google Calendar, the user is able to long press and keep dragging the box in order to create events of different lengths. I've looked around a bit but I'm not sure if this is possible with SfCalendar

### Proposal

Provide options so that the developer can allow the user to long press and drag when creating an event that potentially spans multiple time slots, both on the mobile and on desktop.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @x-ji ,



We have checked your query and found that in Google Calendar while performing a long press on an appointment it helps to drag and drop the appointment in different time slots. If SfCalendar you can achieve this with the help of the [allowDragAndDrop](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/allowDragAndDrop.html) property, which helps you to drag and drop the appointment in different time slots. We have shared the related UG documentation below for your reference.



UG, https://help.syncfusion.com/flutter/calendar/drag-drop#allow-drag-and-drop



Note: Currently, we don't have support for the appointment drag-and-drop feature in month view in the mobile platform.




If you have any further queries, please get back to us, we are always happy to assist you.

**Comment by x-ji** [comment]
Hi @Yuvaraj-Gajaraj thanks for your reply. I understand what we can drag and drop an already created appointment. What I mean is that when creating an appointment from empty cells, Google Calendar allows you to drag and drop in order to achieve different time lengths for the appointment to be created, while in SfCalendar it seems that the user can only click on a cell and have the `onTap` event get the details of that cell, instead of being able to span multiple cells.

The attached screenshot shows the behavior when trying to create an event in Google Calendar.

<img width="121" alt="Screenshot 2024-06-11 at 15 50 54" src="https://github.com/syncfusion/flutter-widgets/assets/2999209/08daf534-5cb9-45c1-ab87-ed0850523efe">


Thanks.

**Comment by ThilipChandru** [comment]
Hi @x-ji,

 

We would like to let you know that currently we don’t have support to  create an event by dragging and dropping time cell in SfCalendar. However, we have already considered this as a feature and logged feature request for it in our feedback portal.

 

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

 

Feedback link : [Provide support to create an event by dragging and dropping time cells in the Flutter Calendar in Flutter | Feedback Portal](https://www.syncfusion.com/feedback/41406/provide-support-to-create-an-event-by-dragging-and-dropping-time-cells-in-the)

 

Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Hi @x-ji ,

This is an uncertain feature, so we are closing this ticket. Please follow up with the FR.

Feedback link : [Provide support to create an event by dragging and dropping time cells in the Flutter Calendar in Flutter | Feedback Portal](https://www.syncfusion.com/feedback/41406/provide-support-to-create-an-event-by-dragging-and-dropping-time-cells-in-the)
