### ISSUE TITLE
Reordering rows using datasource

### ISSUE THREAD

**Issue by Uche01** [syncfusion/flutter-widgets#1896]
I have an application where I need to reorder the rows of a datagrid such that changes in the underlying list order triggers a change in the datagrid rows order/sequence.

Is there some sort of listener that listens to changes datasource list and then rebuilds the table while maintaining row selection.

I have initialized my datasource in initState hence changes in list are not reflected in datagrid on widget rebuild. How can I achieve this?

**Comment by Uche01** [comment]
Found the fix. needed to call notifyListeners after updating List<DataGridRow> in the datasource

**Comment by ashok-kuvaraja** [comment]
Hi @Uche01,

Thanks for the update. We're closing this issue since the reported issue has been resolved in your end. Kindly reopen this issue if you need any further assistance. We're always happy to help you.

Regards,
Ashok K
