### ISSUE TITLE
Date picker square selected date. 

### ISSUE THREAD

**Issue by beerline** [syncfusion/flutter-widgets#190]
Hello syncfusion developers!
First of all, thank you for such a great libraries! 

I try to implement square selection with red color, but i can't find the way to do it. There is always blue selection under my red container.

Could you please explain how to implement square selection

<details>
  <summary>Widget example</summary>
  
  ```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';

class DatePicker extends StatefulWidget {
  @override
  _DatePickerState createState() => _DatePickerState();
}

class _DatePickerState extends State<DatePicker> {
  DateRangePickerController _controller = DateRangePickerController();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SfDateRangePicker(
      controller: _controller,
      cellBuilder: (BuildContext context, DateRangePickerCellDetails details) {
        final now = DateTime.now();
        final currentDate = DateTime(now.year, now.month, now.day);
        final isToday = details.date == currentDate;
        final isPastDay = details.date.isBefore(currentDate);
        final isSelected = _controller.selectedDate == details.date;

        return Container(
          margin: EdgeInsets.all(2),
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            double size = constraints.maxWidth;
            if (constraints.maxHeight < constraints.maxWidth) {
              size = constraints.maxHeight;
            }
            return Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Container(
                  alignment: Alignment.center,
                  width: size,
                  height: size,
                  decoration: BoxDecoration(
                    color: isSelected ? Colors.red : null,
                    border: isToday
                        ? Border.all(color: Colors.purple, width: 1)
                        : null,
                  ),
                  child: Text(
                    details.date.day.toString(),
                    style: TextStyle(
                        color: isPastDay
                            ? theme.hintColor
                            : isSelected
                                ? Colors.white
                                : Colors.black),
                  ),
                ),
              ],
            );
          }),
        );
      },
      monthViewSettings: DateRangePickerMonthViewSettings(
        firstDayOfWeek: 1,
        dayFormat: 'EEE',
      ),
      showNavigationArrow: true,
      enablePastDates: false,
    );
  }
}

  ```
  
</details>

![2021-04-12 23 17 57](https://user-images.githubusercontent.com/7195911/114464144-68f3cb80-9bf6-11eb-81d1-4ee2bebef78e.png)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the provided information, we have checked, and your requirement is “**Changing the selection shape in the Flutter date range picker**”. We have a property for changing the selection shape in the date range picker. Kindly the **selectionShape** property for achieving your requirement. Please find the UG document from the following link.

**UG link:** 
https://help.syncfusion.com/flutter/daterangepicker/selections#selection-shape

Also, we have a KB document for the same. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/11900/how-to-change-the-selection-shape-in-the-flutter-date-range-picker-sfdaterangepicker

**Screenshot:**
![selection](https://user-images.githubusercontent.com/54974849/114509730-8014d680-9c53-11eb-9f4f-0504ca16c707.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by beerline** [comment]
@Indumathi1195R, thank you for quick response.

Yes, i tried to use `DateRangePickerSelectionShape.rectangle`, but it is more rectangle rather than square, and to get square, i have to calculate the size of the whole date picker. And, what is more important, with `DateRangePickerSelectionShape.rectangle` i can have only rounded corners rectangle while i need sharp corners.

Since we have SfDateRangePicker.cellBuilder() parameter, maybe it makes sense to avoid additional canvas drawing and let control cells state and decoration through `cellBuilder()`?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query:  Maybe it makes sense to avoid additional canvas drawing and let control cells state and decoration through cellBuilder()?**

 We have a KB document for selection with sharp corners using the **cellBuilder** property of the **DateRangePicker**. Please find the KB from the following link.

**KB link:** https://www.syncfusion.com/kb/12474/how-to-create-timeline-date-picker-in-flutter

Also please find the UG link for **cellBuilder**,

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by beerline** [comment]
@Indumathi1195R thank you for your link.

As you can see in the first message i successfully implemented sharp corners.
But the problem is to implement sharp corners and square selections simultaneously.

You can see on the screenshot that my selection (red color) and below red square is blue rectangle selection. This blue selection is by default. Default selections is calling in `monthView.drawCustomCellSelection` at `syncfusion_flutter_datepicker-19.1.55-beta/lib/src/date_picker/month_view.dart:3259`. If prevent calling `monthView.drawCustomCellSelection` on `month_view.dart:3259` when cellBuilder() is implemented, custom selection works perfectly.

[here is full demo](https://github.com/beerline/syncfusion-data-picker-demo) where you can check it.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for the update.

**Regarding Query: But the problem is to implement sharp corners and square selections simultaneously.**

As per the current date range picker implementation, default selection was applying while using **cellBuilder**. Can you please use the **selectionColor** value as transparent for avoiding this issue? We have attached the code snippet for the same.

**Code snippet:**
```
child: SfDateRangePicker(
  controller: _controller,
  selectionColor: Colors.transparent,
  view: DateRangePickerView.month,
  cellBuilder: cellBuilder,
),


Widget cellBuilder(BuildContext context, DateRangePickerCellDetails details) {
  var IsSelected = _controller!.selectedDate != null &&
      details.date.year == _controller!.selectedDate!.year &&
      details.date.month == _controller!.selectedDate!.month &&
      details.date.day == _controller!.selectedDate!.day;
  if (IsSelected) {
    return Column(
      children: [
        Container(
          width: 50,
          height: 40,
          decoration:
              BoxDecoration(shape: BoxShape.rectangle, color: Colors.red),
          child: Text(
            details.date.day.toString(),
            textAlign: TextAlign.center,
            style: TextStyle(color: Colors.white),
          ),
        ),
      ],
    );
  } else {
    return Container(
      child: Text(
        details.date.day.toString(),
        textAlign: TextAlign.center,
        style: TextStyle(color: Colors.black),
      ),
    );
  }
}
```
**Screenshot:**

![vidma_recorder_19042021_154354](https://user-images.githubusercontent.com/54974849/115222101-fddf5300-a127-11eb-96fb-2b3ebce15171.jpg)

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by beerline** [comment]
@Indumathi1195R thank you! This workaround works perfectly. 
I close this issue.
