### ISSUE TITLE
New selection mode for sfDataGrid

### ISSUE THREAD

**Issue by VladTheJunior** [syncfusion/flutter-widgets#1903]
### Use case

Currently sfDataGrid has only 4 modes based on documentation https://help.syncfusion.com/flutter/datagrid/selection

I was looking for something like this:
Allows selection of more than one row. Selection **is** cleared when selecting another row without key modifiers (ctrl or shift). When you click on a selected row for the second time, the selection is cleared. If key modifiers is CTRL it adds row to selection otherwise remove. For SHIFT is same but reacting as ranges.

So it will something between single and multiple selection modes. 

### Proposal

Add new selection mode called Extended for sfDataGrid

**Comment by abineshPalanisamy** [comment]
Hi @VladTheJunior , 
 
Thank you for your request. We have acknowledged it and already logged it as a feature. It will be considered for implementation in one of our upcoming releases. During the planning phase of each release cycle, we evaluate all pending features and select those for implementation based on several criteria, including product vision, technological feasibility, and customer demand. We appreciate your patience and understanding during this process. For further details, please refer to the feedback below.
 
Feedback link: [41135](https://www.syncfusion.com/feedback/41135/support-to-perform-the-extended-selection-on-datagrid)
 
Regards,
Abinesh

**Comment by ashok-kuvaraja** [comment]
Hi @VladTheJunior,

We're closing this issue now. You can track the future status through the provided feedback link. If you need any further assistance, kindly reopen this ticket. We're always happy to help you.

Regards,
Ashok K
