### ISSUE TITLE
Display indexes for rows in sfDataGrid

### ISSUE THREAD

**Issue by VladTheJunior** [syncfusion/flutter-widgets#1904]
### Use case

Missing feature to allow display row indexes like in Excel. 

### Proposal

Indexes display numbers from 1 to visible rows count. Clicking on index select entire row. Indexes do not depends on sorting and filter
Example: 
![image](https://github.com/syncfusion/flutter-widgets/assets/30210308/058821c0-6ab3-4809-93b4-8cb6c9e309aa)

If for example row 4 is not visible (by filter for example) row 5 should became 4, row 6 became 5 and so on. 
If rows are filtered by columns, indexes still should display number from 1 to visible rows count

**Comment by abineshPalanisamy** [comment]
Hi @VladTheJunior , 
 
You can achieve the display of indexes ranging from 1 to the visible row count by generating a separate column as the first one to show the count of rows, as you mentioned. Within the [buildRow](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/buildRow.html) method, you can add the respective index to the first column by utilizing the [effective](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/effectiveRows.html) rows collection. Obtaining the index from the effective rows ensures that it ranges from 1 to the visible row count, even when filtering or sorting occurs. 
 
We have attached a sample for your reference. Please consult the following sample for further information.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/15613710/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @VladTheJunior,

We hope that the provided workaround has resolved your issue. We're closing this issue now. Kindly reopen this issue, if you require any further assistance. We're always happy to help you.

Regards,
Ashok K
