### ISSUE TITLE
Add SelectionUnit for sfDataGrid

### ISSUE THREAD

**Issue by VladTheJunior** [syncfusion/flutter-widgets#1905]
### Use case

Missing feature to choose selection unit (sfDatagrid supports only row selection, not cells).

### Proposal

Add SelectionUnit enum propety (Cell, Row) for sfDataGrid

Cell - Only cells are selectable. Clicking a cell selects the cell. 
Row	- Only full rows are selectable. Clicking a cell or a row selects the full row.

Also it will require new field selectedCells for DatagridController.

For Cell mode it also need feature to select range of cells with mouse selection and drag over

**Comment by abineshPalanisamy** [comment]
Hi @VladTheJunior , 
 
As of now, We have already considered your request as feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedbacks for further details,
 
Feedback link: [37700](https://www.syncfusion.com/feedback/37700/support-to-select-the-cells)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @VladTheJunior,

We're closing this issue now. You can track the future status through the provided feedback link. If you need any further assistance, kindly reopen this ticket. We're always happy to help you.

Regards,
Ashok K
