### ISSUE TITLE
Placeholder for empty sfDataGrid

### ISSUE THREAD

**Issue by VladTheJunior** [syncfusion/flutter-widgets#1906]
### Use case

There is no option to add placeholder Widget for datagrid if datagrid is empty

### Proposal

add new property Widget? placeholder for sfDataGrid that display placeholder widget in center of space for displayed rows

**Comment by abineshPalanisamy** [comment]
Hi @VladTheJunior , 
 
Your request has been acknowledged, and we've already logged it as a feature. It will be considered for implementation in one of our upcoming releases. During the planning phase of each release cycle, we evaluate all pending features and select those for implementation based on several criteria, including product vision, technological feasibility, and customer demand. We appreciate your patience and understanding during this process. For further details, please refer to the feedback below.
 
Feedback link: [50967](https://www.syncfusion.com/feedback/50967/support-for-showing-an-empty-message-when-the-row-count-is-zero)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @VladTheJunior,

We're closing this issue now. You can track the future status through the provided feedback link. If you need any further assistance, kindly reopen this ticket. We're always happy to help you.

Regards,
Ashok K
