### ISSUE TITLE
SfRadialGauge.annotations is not displayed when the gauge is child of a Directionality widget having textDirection set to TextDirection.rtl

### ISSUE THREAD

**Issue by hrmoh** [syncfusion/flutter-widgets#191]
Hi,
Please consider the following code: 

```

...
import 'dart:ui' as dartui;
...
@override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'TestApp',
        builder: (BuildContext context, Widget child) {
          return Directionality(
            textDirection: dartui.TextDirection.rtl,
            child: Builder(
              builder: (BuildContext context) {
                return SfRadialGauge(axes: <RadialAxis>[
                  RadialAxis(minimum: 0, maximum: 100, pointers: <GaugePointer>[
                    NeedlePointer(value: 50)
                  ], annotations: <GaugeAnnotation>[
                    GaugeAnnotation(
                      widget: Container(
                        child: Text('annotation'),
                      ),
                    )
                  ])
                ]);
              },
            ),
          );
        });
  }

```

The text 'annotation' is not being shown unless you change the value for Directionality.textDirection to dartui.TextDirection.ltr.

In addition to gauge it seems that syncfusion flutter charts (I've tested SfCartesianChart) also have problems with being child of a Directionality widget with rtl text direction and the chart content is drawn outside the visible area.

Thanks.

**Comment by hrmoh** [comment]
PS I've seen the not-showing problem in flutter web. Now I checked the android version and there I see a positioning problem instead of not showing the annotations at all.
Thanks.

**Comment by Dharanipalani** [comment]
Hi @hrmoh,

**Query:** **syncfusion flutter charts (I've tested SfCartesianChart) also have problems with being child of a Directionality widget with rtl text direction and the chart content is drawn outside the visible area.**

We would like to tell you that we fixed this issue and it will be included in the upcoming patch release which is expected to be rolled out on April 20, 2021. We appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by MeikandaNayanar** [comment]
Hi Hamid,

Regarding the reported radial gauge issue when we set the direction as RTL, we consider 

> the annotation is hiding when having the radial gauge inside Directionality widget where the direction is set as RTL

 as a bug, and also we would like to let you know that the radial gauge is a data visualization component it should not change its content based on directions. Please refer to the below documentation for your reference. 

https://material.io/design/usability/bidirectionality.html#mirroring-layout

https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html

But still, as we mentioned above the annotation is hiding when we set the direction as RTL is a bug in our product and we will fix this in our future release expected by 27 April 2021. Also, we would suggest you to have the text direction as RTL in annotations as a workaround for time being till we fix this issue. Please refer to the below code snippet for this. 

```
GaugeAnnotation(
                  widget: Text('Annotation',
                  textDirection: TextDirection.rtl,
                  style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold)),
                  angle: 90,
                  positionFactor: 0.5)
```

Also, you can have the directionality widget as below to work around this issue. 

```
GaugeAnnotation(
                  widget: Directionality(
                    textDirection: TextDirection.rtl,
                    child: Text('Annotation',
                        style: TextStyle(
                            fontSize: 25, fontWeight: FontWeight.bold)),
                  ),
                  angle: 90,
                  positionFactor: 0.5)
```

Please let us know if you have any questions in this further.

Thanks
Meikandan

**Comment by hrmoh** [comment]
> 
> 
> Hi Hamid,
> 
> Regarding the reported radial gauge issue when we set the direction as RTL, we consider
> 
> > the annotation is hiding when having the radial gauge inside Directionality widget where the direction is set as RTL
> 
> as a bug, and also we would like to let you know that the radial gauge is a data visualization component it should not change its content based on directions. Please refer to the below documentation for your reference.
> 
> https://material.io/design/usability/bidirectionality.html#mirroring-layout
> 
> https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html
> 
> But still, as we mentioned above the annotation is hiding when we set the direction as RTL is a bug in our product and we will fix this in our future release expected by 27 April 2021. Also, we would suggest you to have the text direction as RTL in annotations as a workaround for time being till we fix this issue. Please refer to the below code snippet for this.
> 
> ```
> GaugeAnnotation(
>                   widget: Text('Annotation',
>                   textDirection: TextDirection.rtl,
>                   style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold)),
>                   angle: 90,
>                   positionFactor: 0.5)
> ```
> 
> Also, you can have the directionality widget as below to work around this issue.
> 
> ```
> GaugeAnnotation(
>                   widget: Directionality(
>                     textDirection: TextDirection.rtl,
>                     child: Text('Annotation',
>                         style: TextStyle(
>                             fontSize: 25, fontWeight: FontWeight.bold)),
>                   ),
>                   angle: 90,
>                   positionFactor: 0.5)
> ```
> 
> Please let us know if you have any questions in this further.
> 
> Thanks
> Meikandan

Thanks for your support and great work.
It is easier for an RTL application to parent all widgets with a Directionality widget at root level. So it might not be the case to try to affect a special widget in this case.
