### ISSUE TITLE
Expose resourcePanelScrollController to the endUser in SFCalendar

### ISSUE THREAD

**Issue by shatanikmahanty** [syncfusion/flutter-widgets#1911]
### Use case

For certain operations we want to make the resource panel jumpTo a specific position.

### Proposal

- Make SfCalendarState public. This will allow creating key through Global key approach.
- Make resourcePanelScrollController public

OR

- Allow access to resourcePanelScrollController through controller

**Comment by natrayansf** [comment]
Hi @shatanikmahanty,

Currently, we don't have support to allow access to resourcePanelScrollController through a controller. We have already logged a feature request for **ScrollController support in the Flutter Calendar** in our feedback portal and it is uncertain. This feature will be available in one of our upcoming releases. We will notify you when this feature is implemented. We appreciate your patience until then.

If you have any additional specifications or suggestions for this feature request, please feel free to leave them in the comments section of the feedback link. This will help us understand how you would like to use it and how we can improve it.

Feedback Link: https://www.syncfusion.com/feedback/33008

Regards,
Natrayan
