### ISSUE TITLE
Can not disable the trackball marker for specific series in Cartesian charts

### ISSUE THREAD

**Issue by furuyan** [syncfusion/flutter-widgets#1913]
### Bug description

I want to disable the trackball marker for specific series in Cartesian charts, 
and I implemented code based on this reference.
https://support.syncfusion.com/kb/article/10485/how-to-disable-the-trackball-marker-for-specific-series-in-cartesian-charts

It worked fine in syncfusion_flutter_charts 24.1.46, but in 25.2.5, TrackballMarker is now showing up in all Series.

### Steps to reproduce

1. Drag the chart

### Code sample

<details open><summary>Code sample</summary>

```dart
class _MyHomePageState extends State<_MyHomePage> {
  late TrackballBehavior _trackballBehavior;
  @override
  void initState() {
    _trackballBehavior = TrackballBehavior(
        enable: true,
        activationMode: ActivationMode.singleTap,
        shouldAlwaysShow: true,
        builder: (BuildContext context, TrackballDetails trackballDetails) {
            return Container(
              padding: const EdgeInsets.all(3.0),
              decoration: BoxDecoration(
                  border: Border.all(color: Colors.black)
              ),
              child: Text("Custom Tooltip"),
            );
        },
        markerSettings: TrackballMarkerSettings(
          markerVisibility: TrackballVisibilityMode.auto,
        ));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: Colors.grey,
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: Center(
          child: Container(
            height: 500,
            width: 340,
            child: SfCartesianChart(
                backgroundColor: Colors.white,
                primaryXAxis: CategoryAxis(),
                trackballBehavior: _trackballBehavior,
                series: <LineSeries<_SalesData, String>>[
                  LineSeries<_SalesData, String>(
                      dataSource: <_SalesData>[
                        _SalesData('Jan', 35),
                        _SalesData('Feb', 28),
                        _SalesData('Mar', 34),
                        _SalesData('Apr', 32),
                        _SalesData('May', 40)
                      ],
                      xValueMapper: (_SalesData sales, _) => sales.year,
                      yValueMapper: (_SalesData sales, _) => sales.sales,
                      markerSettings:
                          MarkerSettings(isVisible: true, width: 0, height: 0)),
                  LineSeries<_SalesData, String>(
                      dataSource: <_SalesData>[
                        _SalesData('Jan', 15),
                        _SalesData('Feb', 8),
                        _SalesData('Mar', 14),
                        _SalesData('Apr', 12),
                        _SalesData('May', 20)
                      ],
                      xValueMapper: (_SalesData sales, _) => sales.year,
                      yValueMapper: (_SalesData sales, _) => sales.sales,
                      markerSettings: MarkerSettings(
                          isVisible:
                              false // Setting false to this series to not to render marker for this series.
                          ))
                ]),
          ),
        ));
  }
}

class _SalesData {
  _SalesData(this.year, this.sales);

  final String year;
  final double sales;
}
```

</details>

### Screenshots or Video

24.1.46(Correct behavior)|25.2.7(Incorrect behavior)
--|---
<img src="https://github.com/syncfusion/flutter-widgets/assets/6193319/f48de08c-5b5e-47c3-b6e6-f00c26220dc5" width="320">|<img src="https://github.com/syncfusion/flutter-widgets/assets/6193319/743c5718-0c40-436e-b3c1-9361c00eb75f" width="320">|

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
no stack trace
```

</details>

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.5 23F79 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

**Comment by LokeshPalani** [comment]
Hi @furuyan,

We can be able to replicate the reported issue on our end and the issue is scheduled to be fixed in our **weekly patch release,** which is expected to be rolled out on **June 18, 2024**. We will update you here once the release is rolled out and we appreciate your patience until then.

Regards,
Lokesh P.

**Comment by LokeshPalani** [comment]
Hi @furuyan,

Thank you for your patience. The reported issue is fixed and rolled out in our weekly patch release. To avoid this issue, we kindly request you to upgrade the  syncfusion_flutter_charts package to the latest version below.

Version Link:   https://pub.dev/packages/syncfusion_flutter_charts/versions/26.1.38

Root cause:  Missed to consider the series marker visibility while rendering the trackball marker.

If you have any further queries, please feel free to reach out to us.

Regards,
Lokesh P.

**Comment by furuyan** [comment]
I confirmed that it works good.
Thanks for the fix!
