### ISSUE TITLE
can i build something like below picture with syncfusion AreaChart?

### ISSUE THREAD

**Issue by mahdiqdi** [syncfusion/flutter-widgets#1915]
### Use case

i have to build a chart like this.but i have no idea how to build this with AreaChart and LineCHart
can anyone help me to build this chart?
the problem is how to know chart is below zero to show redColor. pointColorMapper cant help

### Proposal

![IMG_1101](https://github.com/syncfusion/flutter-widgets/assets/67858014/34761fe8-3da9-4a80-93f1-20d1d1d23fbd)

**Comment by mahdiqdi** [comment]
i found a way 
i used onCreateShader property to do this color changes
but the problem is how to know data is below ZERO?
can anyone help me?

`onCreateShader: (ShaderDetails chartShaderDetails) {
                          return ui.Gradient.linear(
                            chartShaderDetails.rect.topCenter,
                            chartShaderDetails.rect.bottomCenter,
                            [
                              green,
                              green,
                              red,
                              red,
                            ],
                            [0, 0.51, 0.51, 1],
                          );
                        },`

**Comment by mahdiqdi** [comment]
@LokeshPalani 
can you help me mr.lokesh?
 really need help

**Comment by mahdiqdi** [comment]
thanks mr @PreethikaSelvam  
you guys are perfect
this package is the best package for charts in flutter
i always support this perfect package
but callbacks need more tutorials in my opinion.they are so helpful and onActualRangeChanged helped me to find zero line
thanks again

**Comment by VijayakumarMariappan** [comment]
Hi @mahdiqdi 

We will take into account your feedback to improve the API comments for callbacks and will make improvements in upcoming releases.
