### ISSUE TITLE
syncfusion_flutter_datepicker throws an error

### ISSUE THREAD

**Issue by ShiffaUrRehman** [syncfusion/flutter-widgets#1917]
### Bug description

I am using syncfusion_flutter_datepicker version 25.2.7 and it gives the following error:

"Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-25.2.7/lib/src/date_picker/theme.dart:83:55: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max."

For now, if I comment the line mentioned above in the error (../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-25.2.7/lib/src/date_picker/theme.dart:83:55:), it works fine: 

"// @override
  // Color? get weekNumberBackgroundColor => colorScheme.surfaceContainerHighest;"

### Steps to reproduce

1. Create a Flutter Project and Install syncfusion_flutter_datepicker version 25.2.7.
2. Use the widget "SfDateRangePicker()"
3. When building the app, it throws the following error: 
"Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-25.2.7/lib/src/date_picker/theme.dart:83:55: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max."

### Code sample

<details open><summary>Code sample</summary>

```dart
SfDateRangePicker(
            onSelectionChanged: _onSelectionChanged,
            selectionMode: DateRangePickerSelectionMode.range,
            initialSelectedRange: PickerDateRange(
                DateTime.now().subtract(const Duration(days: 4)),
                DateTime.now().add(const Duration(days: 3))),
          ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Uploading Screen Recording 2024-06-11 at 3.22.48 PM.mov…

![Screenshot 2024-06-11 at 3 19 20 PM](https://github.com/syncfusion/flutter-widgets/assets/77918908/e989eaed-5a16-4aa4-874c-f17871e622d7)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           10.5s
Failed to build iOS app
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_datepicker-25.2.7/lib/src/date_picker/theme.dart:83:55: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

Exited (1).
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.85.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by igormidev** [comment]
I am having the same error :/

**Comment by ShiffaUrRehman** [comment]
> Hi @ShiffaUrRehman, @igormidev,
> 
> We have checked the reported issue and suspect that you are using a lower version of the Flutter SDK which is not compatible with the latest Syncfusion Flutter package version [25.2.7](https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.2.7), therefore, to resolve the issue, we suggest you use the latest Flutter SDK version 3.22.2. We would like to inform you that 7 new [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html) were introduced from the Flutter SDK Version 3.22.0, and some properties have been deprecated. We have shared details below for 7 new color roles and deprecated color roles.
> 
> Please find the details for 7 new color roles included in the [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html): • surfaceBright • surfaceDim • surfaceContainer • surfaceContainerLow • surfaceContainerLowest • surfaceContainerHigh • surfaceContainerHighest
> 
> <style> </style>
> S No	Flutter SDK version 3.19.0	Flutter SDK version 3.22.0 (After deprecated)
> 1	background	surface
> 2	onBackground	onSurface
> 3	surfaceVariant	surfaceContainerHighest
> Release Notes link for Flutter SDK Version 3.22.0: https://docs.flutter.dev/release/release-notes/release-notes-3.22.0 Breaking changes link for Flutter SDK Version 3.22.0: https://docs.flutter.dev/release/breaking-changes#released-in-flutter-3-22
> 
> Additionally, we have shared user guide documentation for the Syncfusion Compatibility Package version. Please find the compatible Syncfusion Flutter package version based on your Flutter SDK version below.
> 
> UG Link: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility
> 
> Regards, Preethika Selvam.

Yes, my current version is 3.19.5, let me update the version and try again, thank you

**Comment by ShiffaUrRehman** [comment]
Thank you, updating the flutter sdk worked!
