### ISSUE TITLE
[DataGrid] listen for selection

### ISSUE THREAD

**Issue by qbait** [syncfusion/flutter-widgets#192]
I would like to listen to selection changes in my grid (to trigger observable in my controller), I've tried sth like
```
final gridController = DataGridController();
gridController.addListener(() {
  print('gridController CHANGED');
});
```
But it's not triggered when selection changes.

What's the best way to achieve that?

**Comment by RenugaSadagoban98** [comment]
Hi @qbait ,
 
Greetings from Syncfusion.
 
SfDataGrid provides following callbacks for listening to the selection changes,

[onSelectionChanging](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onSelectionChanging.html): This callback is raised while selecting a row at the execution time before the row is selected. So, it allows canceling the selection action by return false. 

[onSelectionChanged:](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onSelectionChanged.html) This callback is raised after the column is selected. 

You Can refer the below UG to know about the selection changes,

Link: https://help.syncfusion.com/flutter/datagrid/selection#callbacks

**Comment by qbait** [comment]
@RenugaSadagoban98 I've tried those callbacks.
When I'm using them, selection stopped working (I'm not getting Selection feedback on my rows anymore).
Is it bug?

**Comment by RenugaSadagoban98** [comment]
Hi @qbait , 

Thanks for your update. 

We have checked the reported scenario and we are unable to replicate the issue from our end. If you return the false from onSelectionChanging callback, selection will not be applied to datagrid. We suspect that you are returning false from the onSelectionChanging callback. Please check with onSelectionChanging callback at your end and revert us if you still facing the same issue? If yes, please provide your sample. 

Please refer the following sample for your reference,

Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1570506481

**Comment by qbait** [comment]
You are right! The problem was in my Observer implementation that was reloading the whole grid. Cheers
