### ISSUE TITLE
[syncfusion_flutter_charts] TooltipBehavior preventing vertical scroll

### ISSUE THREAD

**Issue by AdamBridges** [syncfusion/flutter-widgets#1920]
### Bug description

It appears that `TooltipBehavior` is taking priority over a parent `ListView`'s ScrollController when scrolling over the plot area of a chart, preventing one from scrolling from the plot area of a chart. This also happens when `explode` is set to `true` for some reason. Version 26.1.35.

### Steps to reproduce

1. Run example app with the following code below.
2. Try to scroll from the plot area of a chart.

### Code sample

<details open><summary>Code sample</summary>

```dart
ListView(
          children: [
            SfCircularChart(
              tooltipBehavior: TooltipBehavior(
                enable: true,
              ),
              series: <CircularSeries<int, String>>[
                PieSeries(
                  xValueMapper: (data, index) => "test",
                  yValueMapper: (data, index) => data,
                  // pointColorMapper: (data, index) => Colors.blue,
                  dataSource: const [
                    2,
                    4
                  ],
                ),
              ],
            ),
            SfCircularChart(
              tooltipBehavior: TooltipBehavior(
                enable: true,
              ),
              series: <CircularSeries<int, String>>[
                PieSeries(
                  xValueMapper: (data, index) => "test",
                  yValueMapper: (data, index) => data,
                  // pointColorMapper: (data, index) => Colors.blue,
                  dataSource: const [
                    2,
                    4
                  ],
                ),
              ],
            ),
          ],
        ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Unnecessary

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
None
```

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.19045.4412], locale en-CA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.10)
[√] Android Studio (version 2023.3)
[√] VS Code (version 1.87.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

```

</details>

**Comment by LokeshPalani** [comment]
Hi @AdamBridges,

 
Currently, chart always takes interaction when enabled TooltipBehavior, explode and it is current behavior. However, we understand your query and use case, so we have logged a feature request for **Improve the handling of interactions when placing the chart in scrollable views** in our feedback portal and it is uncertain. This feature will be available in one of our upcoming releases. We will notify you when this feature is implemented. We appreciate your patience until then.


If you have any additional specifications or suggestions for this feature request, please feel free to leave them in the comments section of the feedback link. This will help us understand how you would like to use it and how we can improve it.


**Feedback Link:** https://www.syncfusion.com/feedback/58227

Regards,
Lokesh P.

**Comment by AdamBridges** [comment]
@VijayakumarMariappan Why was this closed?

**Comment by VijayakumarMariappan** [comment]
Hi @AdamBridges 

As per our previous update, your requirement is considered a feature that is uncertain and will be available in one of our upcoming releases. You can track the progress of the feature with the provided Feedback [58227](https://www.syncfusion.com/feedback/58227). Therefore, we are closing this GitHub ticket.

If you have any additional specifications or suggestions for this feature request, you can it as a comment in the Feedback [58227].(https://www.syncfusion.com/feedback/58227)

**Comment by VijayakumarMariappan** [comment]
Hi @AdamBridges

As per our previous update, your requirement is considered a feature that is uncertain and will be available in one of our upcoming releases. You can track the progress of the feature with the provided Feedback [58227](https://www.syncfusion.com/feedback/58227). Therefore, we are closing this GitHub ticket.

If you have any additional specifications or suggestions for this feature request, you can it as a comment in the Feedback [58227](https://www.syncfusion.com/feedback/58227).

**Comment by AdamBridges** [comment]
@VijayakumarMariappan You don't think it's a bug when you can't scroll over charts that have zooming and panning disabled?

**Comment by VijayakumarMariappan** [comment]
Hi @AdamBridges 

We understand the usability issue that you are currently facing and recognize the importance of this requirement. However, we are unable to immediately change the existing behavior without providing an option. Taking these factors into consideration, we view your query as an improvement and have logged a feature request. We have already begun analyzing this to potentially include in one of our upcoming releases. We will update the new behavioral changes in the provided feedback link when we publish the package with these updates.

Feedback Link: https://www.syncfusion.com/feedback/58227

Thank you for your understanding and patience in the meantime.
