### ISSUE TITLE
[syncfusion_flutter_charts] Color LineSeries depending on Plotbands

### ISSUE THREAD

**Issue by Shunt22** [syncfusion/flutter-widgets#1923]
### Use case

I have a simple line series chart. I aslo have two dynamic horizontal plotbands, representing thresholds (can be changed by user). At the moment I can use `pointColorMapper` method, then compare values to plotband values and return color. My problem is that returned color covers whole segment between two lines. 
It would be great if I could split line series segment and color it differently depending on plotband values.

![image](https://github.com/syncfusion/flutter-widgets/assets/7492436/5c7bf358-dd38-497a-9103-17b7f33a51ee)

### Proposal

Desired result would look something like that:
![image](https://github.com/syncfusion/flutter-widgets/assets/7492436/ba9474f6-7c2e-4808-8fa5-758870657016)

**Comment by LokeshPalani** [comment]
Hi @Shunt22,



You can achieve your requirement by using the [onCreateShader](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateShader.html) callback in the [LineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LineSeries-class.html). By using this, you can display colors by setting the [stops](https://api.flutter.dev/flutter/painting/Gradient/stops.html) value in the [LinearGradient](https://api.flutter.dev/flutter/painting/LinearGradient-class.html). You can calculate the stops value based on the PlotBand ‘s start, end and the visibleMaximum value in the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html). We have shared a user guide documentation link, online sample link, code snippet, screenshot, and sample for your reference below. You can modify the sample based on your needs. Please let us know if you need any further needs.

UG Link: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#oncreateshader

SB Link: https://flutter.syncfusion.com/#/cartesian-charts/chart-types/line/line-zone

 

Code Snippet:

``` dart
series: <CartesianSeries<ChartSampleData, num>>[
  LineSeries<ChartSampleData, num>(
    dataSource: data,
    xValueMapper: (ChartSampleData sales, _) => sales.year,
    yValueMapper: (ChartSampleData sales, _) => sales.sales,
    onCreateShader: (ShaderDetails details) {
      const yAxisMaximumValue = 40; // Set Maximum Y-axis value
      double range1 = plotBand1 / yAxisMaximumValue;
      double range2 = plotBand2 / yAxisMaximumValue;

      return ui.Gradient.linear(
        details.rect.topCenter,
        details.rect.bottomCenter,
        <Color>[
          Colors.red,
          Colors.red,
          Colors.yellow,
          Colors.yellow,
          Colors.green,
          Colors.green,
        ],
        <double>[
          0.0,
          range1,
          range1,
          range2,
          range2,
          1.0,
        ],
      );
    },
  ),
],
```

Screenshot:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/391423d7-af26-40eb-89b3-4084ecf2e174)


Regards,
Lokesh P.

[github_1899_chart (1).zip](https://github.com/user-attachments/files/15879838/github_1899_chart.1.zip)

**Comment by Shunt22** [comment]
Great! I've managed to do it! `onCreateShader` helped.
Thank you!
