### ISSUE TITLE
[syncfusion_flutter_charts] LegendItemOverflowMode.wrap Line wrapping exceeds container

### ISSUE THREAD

**Issue by laoduan395** [syncfusion/flutter-widgets#1935]
### Bug description

legendItem External container causing excess
                

### Steps to reproduce

syncfusion_flutter_charts: ^21.2.10

                legend: Legend(
                  isVisible: true,
                  textStyle: TextStyle(fontSize: 14),
                  overflowMode: LegendItemOverflowMode.wrap,
                  position: LegendPosition.bottom,
                ),
                
     

### Code sample

          Expanded(
            child: GetWidgetSize(
              onSize: (size) {
                chartViewSize = size;
              },
              child: SfCartesianChart(
                plotAreaBorderWidth: 0,
                selectionGesture: ActivationMode.singleTap,
                margin: EdgeInsets.zero,
                palette: widget.chartConfig.originColor ??
                    ChartColorProvider.originColors,
                legend: Legend(
                  isVisible: true,
                  textStyle: TextStyle(fontSize: 14),
                  overflowMode: LegendItemOverflowMode.wrap,
                  position: LegendPosition.bottom,
                ),
                primaryXAxis: CategoryAxis(
                  majorGridLines: const MajorGridLines(width: 0),
                ),
                primaryYAxis: NumericAxis(
                  axisLine: const AxisLine(width: 0),
                  axisLabelFormatter: CommonChart.axisLabelFormatter,
                  numberFormat: NumberFormat.decimalPattern(),
                  majorTickLines: const MajorTickLines(size: 0),
                ),
                series: _generateSeriesList(),
                onTooltipRender: (args) {
                  SchedulerBinding.instance.addPostFrameCallback((timeStamp) {
                    if (selectArgs != null) {
                      toggleTipsView();
                      Future.delayed(Duration(milliseconds: 200), () {
                        toggleTipsView(args: args);
                      });
                    } else {
                      toggleTipsView(args: args);
                    }
                  });
                },
                tooltipBehavior: TooltipBehavior(
                  enable: true,
                  header: '',
                  activationMode: ActivationMode.singleTap,
                  canShowMarker: false,
                  // shared: true,
                  opacity: 0,
                  textStyle: Theme.of(context)
                      .textTheme
                      .bodyLarge
                      ?.copyWith(color: Colors.transparent),
                  textAlignment: ChartAlignment.center,
                  tooltipPosition: TooltipPosition.auto,
                  shouldAlwaysShow: false,
                  animationDuration: 0,
                  duration: 0,
                ),
              ),
            ),
          ),

### Screenshots or Video

![CB2037A1-D43B-48AE-B414-0879DE0D1B2A](https://github.com/syncfusion/flutter-widgets/assets/117624899/c6fd8c15-1796-422f-9da2-19ba8c748eaf)

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.16.5, on macOS 14.2.1 23C71
    darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.16.5 on channel stable at
      /Users/jay/Documents/flutter_sdk/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 months ago), 2023-12-19
      16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android
    SDK version 33.0.0)
    • Android SDK at /Users/jay/Library/Android/sdk
    • Platform android-34, build-tools 33.0.0
    • ANDROID_HOME = /Users/jay/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C65
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google
      Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (5 available)
    • iPhone Xs Max (mobile)     • 00008020-001368383ED1002E
      • ios            • iOS 17.3.1 21D61
    • iPhone 13 (mobile)         •
      C8B97878-EEF5-4DF1-BE80-6C65EC0FC2C7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro Max (mobile) •
      C43D5C0F-51CF-4100-8B84-9B8B25D61675 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos
      • darwin-x64     • macOS 14.2.1 23C71 darwin-x64
    • Chrome (web)               • chrome
      • web-javascript • Google Chrome 125.0.6422.142

[✓] Network resources
    • All expected network resources are available.

**Comment by LokeshPalani** [comment]
Hi @laoduan395,

We have checked the reported issue and tried to replicate it in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) with version[ 21.2.10](https://pub.dev/packages/syncfusion_flutter_charts/versions/21.2.10) by setting [overflowMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/overflowMode.html) to [LegendOverFlowMode.Wrap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LegendItemOverflowMode.html#wrap) and [position](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/position.html) to [LegendPosition.Bottom](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LegendPosition.html#bottom) in the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html). And, we have tested the following scenarios by wrapping the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html).

- Tested with [Card](https://api.flutter.dev/flutter/material/Card-class.html) widget by wrapping the chart and resizing the output.
- Tested with [SizedBox](https://api.flutter.dev/flutter/widgets/SizedBox-class.html) widget by setting the height and width when wrapping the chart and resizing the output.
- Tested with [Padding](https://api.flutter.dev/flutter/widgets/Padding-class.html) widget by setting the offset value in the [EdgeInsets](https://api.flutter.dev/flutter/painting/EdgeInsets-class.html) when wrapping the chart and resizing the output.

However, we were unable to reproduce the reported issue at our end. We kindly request that you replicate the reported issue in the sample attached below and provide us with more details regarding the specific scenario in which you encountered the issue with a screenshot or screen recording. This will help us to assist you more effectively.

Regards,
Lokesh P.

[github_1935_legend.zip](https://github.com/user-attachments/files/15927048/github_1935_legend.zip)
