### ISSUE TITLE
Why can't I use DateTimeCategoryAxis and RangeController to display it，but DateTimeAxis and RangeController can？

### ISSUE THREAD

**Issue by 15759101796** [syncfusion/flutter-widgets#194]
Why can't I use DateTimeCategoryAxis and RangeController to display it，but DateTimeAxis and RangeController can？
this is the code：
rangeController = RangeController(start: DateTime(2016,01,01), end: DateTime(2016,10,01));

// can display
primaryXAxis: DateTimeAxis(
        rangePadding: ChartRangePadding.auto,
        interactiveTooltip: InteractiveTooltip(enable: false),
        isVisible: false,
        dateFormat: DateFormat('y/M'),
        interval: 2,
        intervalType: DateTimeIntervalType.auto,
        majorGridLines: MajorGridLines(width: 0),
        rangeController: rangeController,
),

// can't display
 primaryXAxis: DateTimeCategoryAxis(
        rangePadding: ChartRangePadding.auto,
        interactiveTooltip: InteractiveTooltip(enable: false),
        isVisible: false,
        dateFormat: DateFormat('y/M'),
        interval: 2,
        intervalType: DateTimeIntervalType.days,
        majorGridLines: MajorGridLines(width: 0),
        rangeController: rangeController,
 ),

**Comment by LakshmiRadhaKrishnan** [comment]
Hi, 
 
We have considered your request as a feature “Provide a date time category axis support in the range selector” and the status can be tracked from the feedback portal link. 
 
**Feedback:** https://www.syncfusion.com/feedback/24414/provide-a-date-time-category-axis-support-in-the-range-selector   

We will prioritise the features every release based on the demands and priority. So, this feature will be available in any of our releases.
 
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal. 

Regards, 
Lakshmi R.
