### ISSUE TITLE
SfCalendar schedule view customization

### ISSUE THREAD

**Issue by VaishaliVi** [syncfusion/flutter-widgets#1947]
### Use case

In sfCalendar's schedule view , I am not able to customize dates as per our design.   I am attaching the design and customization we need .
![Screenshot (1278)](https://github.com/syncfusion/flutter-widgets/assets/89640072/995fb069-96d1-4ccf-976e-5e6de00ef68d)

Is it possible to customize the dates as per above screenshot.

### Proposal

In sfCalendar's schedule view , I am not able to customize dates as per our design.   I am attaching the design and customization we need .
![Screenshot (1278)](https://github.com/syncfusion/flutter-widgets/assets/89640072/995fb069-96d1-4ccf-976e-5e6de00ef68d)

Is it possible to customize the dates as per above screenshot.

**Comment by VaishaliVi** [comment]
Hi @ Preethika

Actually I want date to be at left and day at the right side. Along with
dates in rectangular container instead of circular. With all same color and
the one that is selected with different color.

Thanks and Regards
Vaishali Pandey

**Comment by VaishaliVi** [comment]
Ok . I will wait till feature added.

**Comment by VaishaliVi** [comment]
Not completed.

**Comment by ManzurulIslamBista** [comment]
<img width="392" height="765" alt="Image" src="https://github.com/user-attachments/assets/3048561a-c313-43b3-91be-454c32391753" />

here in header at weekly view i am getting only one month but here showing combine 2 month dates how can i show the months at header

**Comment by VijayakumarMariappan** [comment]
@ManzurulIslamBista I’ve created a new report for your query because it’s not related to the existing discussion. Please follow up on the new report at https://github.com/syncfusion/flutter-widgets/issues/2391 for further updates.

**Comment by ManzurulIslamBista** [comment]
@VijayakumarMariappan i have solve it by creating a new header section which is updating from onViewChanged method 
  void updateHeader(DateTime start, DateTime end) {
    final sameYear = start.year == end.year;
    final sameMonth = start.month == end.month;

    if (sameMonth && sameYear) {
      _headerText = DateFormat('MMMM yyyy').format(start);
    } else if (sameYear) {
      final firstMonth = DateFormat('MMMM').format(start);
      final lastMonth = DateFormat('MMMM yyyy').format(end);
      _headerText = '$firstMonth - $lastMonth';
    } else {
      final firstMonth = DateFormat('MMMM yyyy').format(start);
      final lastMonth = DateFormat('MMMM yyyy').format(end);
      _headerText = '$firstMonth - $lastMonth';
    }
  }

<img width="380" height="758" alt="Image" src="https://github.com/user-attachments/assets/16ffa763-13e4-4dda-a048-e6ea75ffd6ce" />
