### ISSUE TITLE
implement Verify pdf signatures like ninja-labs-tech/verify-pdf

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#1951]
### Use case

check if a PDF has a digital signature, check if a PDF has been tampered with/modified, i.e. check integrity, etc.

### Proposal

The signed PDF file has the public certificate embedded in it, so all we need to verify a PDF file is the file itself.

the implementation could be similar to https://github.com/ninja-labs-tech/verify-pdf

**Comment by jeyalakshmit** [comment]
Hi @insinfo ,

We can check whether the PDF signature field is signed or not using “isSigned” API available in the PdfSignatureField class. you can refer the following API documentation for further details. https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfSignatureField/isSigned.html
 
And we do not have support to validate the digital signatures in an existing PDF document. We have already logged this requirement as a feature request with “Support to validate the digital signatures in an existing PDF document” in our library. At present, we do not have any immediate plans to implement this feature and we will implement this support in any of our upcoming releases. We usually have an interval of at least three months between releases, at the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented.
 
Please use the below feedback link to track the status of the feature.
https://www.syncfusion.com/feedback/25198/support-to-validate-the-digital-signatures-in-an-existing-pdf-document

Regards,
Jeyalakshmi T

**Comment by insinfo** [comment]
If there was something like the VerifySignatureIntegrityAndAuthenticity API from the itext lib it would be great.

```c#
using System.Linq;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Signatures;

namespace HelloPdf
{
    class Program
    {
        static void Main(string[] args)
        {
            // using var document = new Document(new PdfDocument(new PdfWriter("helloworld-pdf.pdf")));
            // document.Add(new Paragraph("Isaque!"));

            verifySignatures("alexandre-manda-redes-sociais.pdf");
        }


        public static void verifySignatures(string path)
        {
            PdfDocument pdfDoc = new PdfDocument(new PdfReader(path));
            SignatureUtil signUtil = new SignatureUtil(pdfDoc);
            IList<string> names = signUtil.GetSignatureNames();



            Console.WriteLine(path);
            foreach (var name in names)
            {
                Console.WriteLine("===== " + name + " =====");
                verifySignature(signUtil, name);
            }

            pdfDoc.Close();
        }

        public static PdfPKCS7 verifySignature(SignatureUtil signUtil, String name)
        {
            PdfPKCS7 pkcs7 = signUtil.ReadSignatureData(name);

            pkcs7.GetCertificates()
            .ToList()
            .ForEach(cert => Console.WriteLine("IssuerDN: " + cert.GetIssuerDN() + "\r\nSubjectDN: " + cert.GetSubjectDN()));

            Console.WriteLine("The signature covers the entire document: " + signUtil.SignatureCoversWholeDocument(name));
            Console.WriteLine("Document Revision: " + signUtil.GetRevision(name) + " of " + signUtil.GetTotalRevisions());
            Console.WriteLine("Integrity check OK?" + pkcs7.VerifySignatureIntegrityAndAuthenticity());

            return pkcs7;
        }
    }
}
```

https://github.com/insinfo/itext_pdf_example

**Comment by jeyalakshmit** [comment]
We have provided signature validation support in our .NET PDF library. You can refer to the following UG link for further details:
[Working with Digital Signature | Syncfusion](https://help.syncfusion.com/document-processing/pdf/pdf-library/net/working-with-digitalsignature#digital-signature-validation)
As of now, we don't have any immediate plans for implementing this feature in the Flutter platform. We will consider and implement this support in one of our upcoming releases for Flutter.

**Comment by insinfo** [comment]
@chinnumuniyappan has the feature been implemented?

**Comment by jeyalakshmit** [comment]
As mentioned earlier, we currently do not have any immediate plans to implement this feature on the Flutter platform. Since there is no definite timeline for this, we will be closing this ticket for now. However, once we decide to proceed with the implementation, we will keep you informed through the feedback portal. For any further updates, you can follow the feedback link:
https://www.syncfusion.com/feedback/25198/support-to-validate-the-digital-signatures-in-an-existing-pdf-document
