### ISSUE TITLE
RangeError (length): Invalid value: Not in inclusive range 0..3: 4. Error thrown #1685

### ISSUE THREAD

**Issue by afei0906** [syncfusion/flutter-widgets#1956]
### Use case

package:syncfusion_flutter_charts/src/charts/series/chart_series.dart
Report this error and crash in  syncfusion_flutter_charts: ^25.1.42+1
![image](https://github.com/syncfusion/flutter-widgets/assets/148411812/89636c8a-6b9c-4ad2-8959-9a3da3bd5250)

### Proposal

package:syncfusion_flutter_charts/src/charts/series/chart_series.dart
Report this error and crash in  syncfusion_flutter_charts: ^25.1.42+1
![image](https://github.com/syncfusion/flutter-widgets/assets/148411812/89636c8a-6b9c-4ad2-8959-9a3da3bd5250)

**Comment by Trung15010802** [comment]
Where is your sample  code?

**Comment by afei0906** [comment]
SizedBox(
      height: 175.h,
      child: SfCircularChart(
          margin: const EdgeInsets.all(0),
          onLegendTapped: (legendTapArgs) {},
          legend:  Legend(
              isVisible: true,
              alignment: ChartAlignment.center,
              position: LegendPosition.right,
              toggleSeriesVisibility: false,
              legendItemBuilder:
                  (String text, dynamic pie, dynamic chart, int index) {
                return Container(
                  width: 130.w,
                  height: 22.h,
                  margin: index == 0 ? EdgeInsets.only(top: 20.h) : null,
                  child: Row(
                    children: [
                      Container(
                        width: 12.w,
                        height: 12.w,
                        decoration: BoxDecoration(
                            color: color[index],
                            borderRadius: appTheme.borderRadius.all3),
                      ),
                      CommonSizedBox().w5,
                      Row(
                        children: [
                          SizedBox(
                            width: 70.w,
                            child: Text(
                              text.tr,
                              maxLines: 1,
                              overflow: TextOverflow.ellipsis,
                              style: TextStyle(
                                  fontWeight: FontWeight.w600,
                                  letterSpacing: AppTheme.letterSpacing,
                                  height: 1.1,
                                  color: const Color(0xcc000000),
                                  fontSize: 10.sp),
                            ),
                          ),
                          Text(
                            "${((data[index].sales / total) * 100).toStringAsFixed(2)}%",
                            style: TextStyle(
                                letterSpacing: AppTheme.letterSpacing,
                                fontWeight: FontWeight.w600,
                                height: 1.1,
                                color: const Color(0xcc000000),
                                fontSize: 10.sp),
                          ),
                        ],
                      )
                    ],
                  ),
                );
              }
              ),
          // Enable tooltip
          tooltipBehavior: TooltipBehavior(enable: true),
          series: <CircularSeries<SalesData, String>>[
            PieSeries<SalesData, String>(
                dataSource: data,
                xValueMapper: (SalesData sales, _) => sales.name.tr,
                yValueMapper: (SalesData sales, _) => sales.sales,
                pointColorMapper: (SalesData data, _) => data.color,
                // name: 'Sales',
                // Enable data label
                dataLabelSettings: const DataLabelSettings(isVisible: false))
          ]),
    )

**Comment by LokeshPalani** [comment]
Hi @afei0906,

We have validated the reported issue and tried to replicate it in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html) with chart version [25.1.42+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.42+1) by setting [legendItemBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/legendItemBuilder.html) in the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html). We have tested by toggling the Legend and ensured that it was working fine on Windows, Web, and Android platform at our end. However, we were unable to reproduce the reported issue at our end. We kindly request you replicate the reported issue in the sample attached below and provide us with more details regarding the specific scenario in which you encounter the issue with a screenshot or screen recording. This will help us to assist you more effectively.

Regards,
Lokesh P.


[github_1956.zip](https://github.com/user-attachments/files/16030371/github_1956.zip)

**Comment by afei0906** [comment]
![image](https://github.com/syncfusion/flutter-widgets/assets/148411812/a989fd16-3b00-4130-b7d9-70a56f4143d6)
I have a Widget that uses two such charts, both of which reference the same code. This error is not mandatory, it just happens sometimes.

**Comment by LokeshPalani** [comment]
Hi @afei0906,

We have validated the attached screenshot and tried to replicate it in the [SfCircularChart ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html)with chart version [25.1.42+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.42+1). We have tested the following scenarios in the Android Platform, and it was working fine on our end.

- Tested with [Column](https://api.flutter.dev/flutter/widgets/Column-class.html) widget, by placing the two [SfCircularChart ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html)inside the [Column](https://api.flutter.dev/flutter/widgets/Column-class.html) widget.
- Tested with [TabBarView](https://api.flutter.dev/flutter/material/TabBar-class.html) widget, by placing the two [SfCircularChart ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html)inside the [TabBarView](https://api.flutter.dev/flutter/material/TabBar-class.html) widget.
- Tested with [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) widget, by placing the two [SfCircularChart ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html)inside the [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) widget.
- Tested with toggling the [Legend](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend-class.html) in the [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html).
- Tested with Auto-rotate and portrait output in the Android Platform.

However, we were unable to reproduce the reported issue at our end. We kindly request you to share more details to check the reported issue.

- In which scenario the Exception occur?
- What widget is used above the SfCircularChart.

We kindly request you replicate the reported issue in the sample attached below and provide us with more details regarding the specific scenario in which you encounter with a screen recording. This will help us to assist you more effectively.

Regards,
Lokesh P.

[github_1996__.zip](https://github.com/user-attachments/files/16143563/github_1996__.zip)

**Comment by afei0906** [comment]
![QQ_1722941944719](https://github.com/user-attachments/assets/afd1501e-dadb-4905-8b8f-9ebc44c2c28f)
https://github.com/user-attachments/assets/47f2c8e7-c622-494f-8031-93dc1b57177d
If you define multiple pages on a video, this error is inevitable. If you customize your own style in LegendItemBuilder
