### ISSUE TITLE
Any way to add a custom image Marker  on PDF files using pdfviewer like annotation

### ISSUE THREAD

**Issue by Tigran-Kosemyan** [syncfusion/flutter-widgets#1958]
I use [https://pub.dev/packages/syncfusion_flutter_pdfviewer](https://pub.dev/packages/syncfusion_flutter_pdfviewer) 
Any way to add a Marker or a Pin on PDF files with using onTap dx dy position?
I need add custon marker runtime, without reload the page and write new pdf document,
and I use syncfusion pdf viewer and need add markers with 
`onTap: (PdfGestureDetails detail) {details.pagePosition.dx, details.pagePosition.dy}`
I want to place marker or a customizable marker that opens up the current status screen of the marker on PDF files in a Flutter application. Need save markers and show when again pdf opened edit existing markers delete move and more

Note: I add annotation but annotation can't customize

**Comment by immankumarsync** [comment]
HI @Tigran-Kosemyan,

Your requirement can be achieved with custom stamp or image annotation support. This feature allows you to add custom image annotations at any position on a PDF page, move them, delete them, and save them for later review.

At present, we do not support custom stamp/image annotations in Flutter SfPdfViewer and do not have any immediate plans to implement this feature. During the planning stage for each release cycle, we review all open feature requests and identify those for implementation based on specific parameters, including product vision, technological feasibility, and customer interest. We will inform you when this feature is implemented.

Please use the feedback link to track the status of the feature,
https://www.syncfusion.com/feedback/33543/support-for-custom-stamp-annotation

**Comment by Tigran-Kosemyan** [comment]
thank you
