### ISSUE TITLE
Show filter popup programmatically in Datagrid 

### ISSUE THREAD

**Issue by omar0141** [syncfusion/flutter-widgets#1963]
### Use case

I need a function or a way to use filter popup programmatically as a function without using the filter icon

### Proposal

.

**Comment by abineshPalanisamy** [comment]
Hi @omar0141 ,
 
As of now, DataGrid does not have support for open the filter popup menu programmatically . We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [40756](https://www.syncfusion.com/feedback/40756/support-to-open-the-filter-popup-menu-programmatically)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @omar0141,

We are closing this issue now. You can follow the given feedback link for further updates. If you have any other concerns, please reopen this issue. We are always happy to help you.

Regards,
Ashok K
