### ISSUE TITLE
How to customize the appearance when the value is 0

### ISSUE THREAD

**Issue by lcm1475** [syncfusion/flutter-widgets#1972]
### Use case

If the value is 0 in the chart now, nothing will be displayed. I hope to customize the display when the value is 0
Current performance：
![WX20240710-115800@2x](https://github.com/syncfusion/flutter-widgets/assets/9637601/9ad0da8f-a973-4d95-9485-71d2d2d9da08)
My expected performance：
![WX20240710-115800@2x](https://github.com/syncfusion/flutter-widgets/assets/9637601/ba769f25-bbf0-47b9-92ef-f1e0275c50f4)

### Proposal

1

**Comment by LokeshPalani** [comment]
Hi @lcm1475,


We have validated your query and the attached screenshot. You can achieve your requirement by using the **_CustomColumnSeriesRenderer** in the [onCreateRenderer](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onCreateRenderer.html) callback of the [ColumnSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html). By using this, you can customize the height of the **segmentRect** in the **onPaint** method of **_CustomColumnPainter** when the [dataSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/dataSource.html) of the y value is 0 to display the column chart. We have shared a code snippet, screenshot, user guide documentation link, and a sample for your reference below. Please let us know if you have any further needs.

 
UG Link for onCreateRenderer callback in the ColumnSeries:  https://help.syncfusion.com/flutter/cartesian-charts/callbacks#oncreaterenderer


**Code Snippet:**

``` dart
ColumnSeries<ChartSampleData, String>(
  dataSource: [
    ChartSampleData(x: 'China', y: 0),
    ChartSampleData(x: 'Brazil', y: 4),
    ChartSampleData(x: 'Bolivia', y: 0),
    ChartSampleData(x: 'Mexico', y: 6),
    ChartSampleData(x: 'Egypt', y: 5),
    ChartSampleData(x: 'Mongolia', y: 0),
  ],
  xValueMapper: (ChartSampleData sales, _) => sales.x,
  yValueMapper: (ChartSampleData sales, _) => sales.y,
  borderColor: Colors.orangeAccent,
  borderWidth: 2,
  color: Colors.orange.shade100,
  borderRadius: BorderRadius.circular(borderRadius),
  onCreateRenderer: (ChartSeries series) {
    return _CustomColumnSeriesRenderer();
  },
),

const double borderRadius = 15;

class _CustomColumnSeriesRenderer extends ColumnSeriesRenderer<ChartSampleData, String> {
  _CustomColumnSeriesRenderer();

  @override
  ColumnSegment<ChartSampleData, String> createSegment() {
    return _ColumnCustomPainter();
  }
}

class _ColumnCustomPainter extends ColumnSegment<ChartSampleData, String> {
  _ColumnCustomPainter();

  @override
  void onPaint(Canvas canvas) {
    if (segmentRect!.height == 0) {
      segmentRect = RRect.fromLTRBAndCorners(
        segmentRect!.left,
        segmentRect!.top - 40,
        segmentRect!.right,
        segmentRect!.bottom,
        topLeft: const Radius.circular(borderRadius),
        topRight: const Radius.circular(borderRadius),
        bottomLeft: const Radius.circular(borderRadius),
        bottomRight: const Radius.circular(borderRadius),
      );
    }
    super.onPaint(canvas);
  }
}
```
**Screenshot:**

![image](https://github.com/user-attachments/assets/49247531-d821-485d-bfc7-071fb5f4ec1b)

Regards,
Lokesh P.

[columnchart_yvalue.zip](https://github.com/user-attachments/files/16192268/columnchart_yvalue.zip)
