### ISSUE TITLE
Why is the width of the border inconsistent when the median in the chart is 0 and the value is not 0

### ISSUE THREAD

**Issue by lcm1475** [syncfusion/flutter-widgets#1973]
### Use case

I hope the line width of the border remains consistent
![WX20240710-120236@2x](https://github.com/syncfusion/flutter-widgets/assets/9637601/417697cd-f934-4404-bfd3-63f7f702a279)

### Proposal

1

**Comment by lcm1475** [comment]
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

class Demo3 extends StatefulWidget {
  const Demo3({super.key});

  @override
  State<Demo3> createState() => _Demo3State();
}

class _Demo3State extends State<Demo3> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: _buildSplineAreaChart(),
    );
  }

  /// Returns the cartesian spline are chart.
  SfCartesianChart _buildSplineAreaChart() {
    return SfCartesianChart(
      legend: const Legend(isVisible: true, opacity: 0.7),
      margin: EdgeInsets.only(left: 20,right: 20,bottom: 20,top: 0),
      title: const ChartTitle(text: 'Inflation rate'),
      primaryXAxis: const NumericAxis(
          interval: 1,
          majorGridLines: MajorGridLines(width: 0),
          axisLine: AxisLine(width: 0),
          majorTickLines: MajorTickLines(size: 0), // 移除X轴上的主要刻度线

          edgeLabelPlacement: EdgeLabelPlacement.shift),
      primaryYAxis: const NumericAxis(
          labelFormat: '{value}',
          isVisible: false,
          minimum: 0,
          maximum: 6,
          axisLine: AxisLine(width: 0),
          majorTickLines: MajorTickLines(size: 0)
      ),
      series: _getSplineAreaSeries(
          true, true),
      tooltipBehavior: TooltipBehavior(enable: true),
    );
  }

  List<_SplineAreaData>? chartData;

  @override
  void initState() {
    chartData = <_SplineAreaData>[
      _SplineAreaData(2010, 1, 3.3),
      _SplineAreaData(2011, 2, 5.4),
      _SplineAreaData(2012, 0, 2.65),
      _SplineAreaData(2013, 0, 2.62),
      _SplineAreaData(2014, 5, 1.99),
    ];
    super.initState();
  }

  /// Returns the list of chart series
  /// which need to render on the spline area chart.
  List<CartesianSeries<_SplineAreaData, double>> _getSplineAreaSeries(
      bool isMaterial3, bool isLightMode) {
    final Color seriesColor1 = isMaterial3
        ? (isLightMode
        ? const Color.fromRGBO(6, 174, 224, 1)
        : const Color.fromRGBO(255, 245, 0, 1))
        : const Color.fromRGBO(75, 135, 185, 1);
    final Color seriesColor2 = isMaterial3
        ? (isLightMode
        ? const Color.fromRGBO(99, 85, 199, 1)
        : const Color.fromRGBO(51, 182, 119, 1))
        : const Color.fromRGBO(192, 108, 132, 1);
    return <CartesianSeries<_SplineAreaData, double>>[
      SplineAreaSeries<_SplineAreaData, double>(
        dataSource: chartData,
        splineType: SplineType.monotonic,
        color: seriesColor1.withOpacity(0.6),
        cardinalSplineTension: 0.7,
        animationDuration: 500,
        borderColor: seriesColor1,
        name: 'India',
        xValueMapper: (_SplineAreaData sales, _) => sales.year,
        yValueMapper: (_SplineAreaData sales, _) => sales.y1,
      ),
    ];
  }

  @override
  void dispose() {
    chartData!.clear();
    super.dispose();
  }
}

/// Private class for storing the spline area chart datapoints.
class _SplineAreaData {
  _SplineAreaData(this.year, this.y1, this.y2);
  final double year;
  final double y1;
  final double y2;
}

**Comment by LokeshPalani** [comment]
Hi @lcm1475,

We have validated your query and the attached screenshot. In the screenshot, the SplineAreaChart border was rendered on the **X-axis**, so it was clipped and displayed only half of the border when the x value is 0. To resolve this issue, we suggest setting half of the [borderWidth](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/borderWidth.html) of the [SplineAreaSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineAreaSeries-class.html) to the [plotOffset](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/plotOffset.html) in the [NumericAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis-class.html) of the [primaryYAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryYAxis.html). This will add a gap to the start and end of the **Y-axis**, and the SplineAreaChart border was displayed above the X-axis. We have shared code snippet, screenshot, sample and user guide documentation link for your reference below.

UG Link for PlotOffset in the Axis: https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#offset-the-rendering

 
**Code Snippet:**

``` dart

double borderWidth = 2;

primaryYAxis: NumericAxis(
  labelFormat: '{value}',
  isVisible: false,
  minimum: 0,
  maximum: 6,
  axisLine: const AxisLine(width: 0),
  majorTickLines: const MajorTickLines(size: 0),
  plotOffset: borderWidth / 2,
),

SplineAreaSeries<_SplineAreaData, double>(
  dataSource: chartData!,
  splineType: SplineType.monotonic,
  color: seriesColor1.withOpacity(0.6),
  cardinalSplineTension: 0.7,
  animationDuration: 500,
  borderColor: seriesColor1,
  borderWidth: borderWidth,
  name: 'India',
  xValueMapper: (_SplineAreaData sales, _) => sales.year,
  yValueMapper: (_SplineAreaData sales, _) => sales.y1,
),
```

[splinearea_chart.zip](https://github.com/user-attachments/files/16178864/splinearea_chart.zip)

**Comment by lcm1475** [comment]
@LokeshPalani Thank you for resolving my issue. Could you please help me take a look at my other question
[https://github.com/syncfusion/flutter-widgets/issues/1972](url)

**Comment by rituapplocum** [comment]
I am also facing the same issue. The above solution didn't. worked for me
![imgpsh_fullsize_anim](https://github.com/user-attachments/assets/70123d5e-e673-4fa7-8434-a7ff4433268e)

**Comment by rituapplocum** [comment]
I am also facing the same issue. The above solution didn't. worked for me
![imgpsh_fullsize_anim](https://github.com/user-attachments/assets/030caee7-8252-463d-9e33-b12cba011d06)
