### ISSUE TITLE
Resource View in Vertical

### ISSUE THREAD

**Issue by pradeep14598** [syncfusion/flutter-widgets#1974]
### Use case

Currently there is only way to place resources in horizontal need to display in vertical resource

### Proposal

add property to change resource direction

**Comment by LokeshPalani** [comment]
Hi @pradeep14598,

Currently, we don't have support to display the resource view vertically in the SfCalendar. We have already logged a feature request for **"Horizontal resource grouping support in the SfCalendar"** in our feedback portal, and it is uncertain. This feature will be available in one of our upcoming releases. We will notify you when this feature is implemented. We appreciate your patience until then.


If you have any additional specifications or suggestions for this feature request, please feel free to leave them in the comments section of the feedback link. This will help us understand how you would like to use it and how we can improve it.

Feedback Link:  https://www.syncfusion.com/feedback/15067

 
Regards,
Lokesh P.
