### ISSUE TITLE
deselect the selected row using a keyboard shortcut

### ISSUE THREAD

**Issue by gsanthosh91** [syncfusion/flutter-widgets#1977]
### Bug description

Hi, i want to deselect the selected row using 'Enter' key.

### Steps to reproduce

1.
2.
3.

### Code sample

<details open><summary>Code sample</summary>

```dart
class CustomSelectionManager extends RowSelectionManager {
  CustomSelectionManager(this.dataGridController);
  DataGridController dataGridController;
  @override
  Future<void> handleKeyEvent(KeyEvent keyEvent) async {
    if (keyEvent.logicalKey == LogicalKeyboardKey.enter) {
      var index = dataGridController.currentCell.rowIndex;
      dataGridController.selectedIndex = index;
    }
    super.handleKeyEvent(keyEvent);
  }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

1
</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
11
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>d</summary>

```console
-
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @gsanthosh91 ,

In SfDataGrid, to perform custom actions alongside default functionalities for keyboard key press actions, implement your custom actions within the [handleKeyEvent()](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/RowSelectionManager/handleKeyEvent.html) override of a custom selection manager class derived from [RowSelectionManager](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/RowSelectionManager-class.html). Assign this custom selection manager to the [SfDataGrid.selectionManager](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/selectionManager.html) property. Additionally, to achieve the required behavior, create an instance of [DataGridController](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridController-class.html) and set it to the [controller](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/controller.html) property. To deselect the selected row using the 'Enter' key, remove the rows you want to deselect from [DataGridController.selectedRows](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridController/selectedRows.html) and update the selected rows. 

We have included a sample for your reference. Please refer to these samples for more details and adapt them to suit your requirements.

* **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/16231060/SfDataGrid.zip)


Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @gsanthosh91,

We believe that your requirement has been resolved on your end. We are closing this issue now. If you need any further assistance, kindly reopen this issue. We are always happy to assist you.

Regards,
Ashok K
