### ISSUE TITLE
Please upgrade device_info_plus ^9.0.2 to ^10.0.1

### ISSUE THREAD

**Issue by Vextrov** [syncfusion/flutter-widgets#1978]
### Use case

I am unable to use newer versions of some of my libraries such as flutter_quill because of this error:

flutter_quill >=9.3.5 depends on device_info_plus ^10.0.1 and syncfusion_flutter_pdfviewer >=22.1.34
  depends on device_info_plus ^9.0.2, flutter_quill >=9.3.5 is incompatible with syncfusion_flutter_pdfviewer
  >=22.1.34.

### Proposal

Upgrade to device_info_plus ^10.0.1

**Comment by immankumarsync** [comment]
Hi @Vextrov, we plan to upgrade the device_info_plus package in synfusion_flutter_pdfviewer. And this upgrade will be included in our July 16, 2024 weekly release.

**Comment by immankumarsync** [comment]
Hi @Vextrov,

We have updated the device_info_plus package to the latest version in our syncfusion_flutter_pdfviewer package. This update will be available in our latest weekly release.

Package link: [syncfusion_flutter_pdfviewer v26.1.42](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/26.1.42)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Imman Kumar P
