### ISSUE TITLE
[DataGrid] option to hide outer grid lines

### ISSUE THREAD

**Issue by ozzy91** [syncfusion/flutter-widgets#198]
When the grid lines in a DataGrid are visible, there are also lines on the very outer positions like a border. In case of horizontal lines, there is  a line on above the column headers and below the last item.

This can lead to undesired design effects, for example when insetting the `DataGrid` in a `Card` or when having a fine line right above the grid, as seen in your web examples. The fine line looks to thick above the grid:
<img width="602" alt="Bildschirmfoto 2021-04-19 um 08 45 03" src="https://user-images.githubusercontent.com/2384189/115193370-5ee93580-a0ec-11eb-9381-751d666f6011.png">

Please provide a styling option to hide those outer lines.

**Comment by BalasubramaniSundaram** [comment]
Hi Ozzy,  
  
Thanks for contacting Syncfusion support. 
 
Currently, SfDataGrid does not have support to hide the outer (top and bottom) grid lines. We have considered your request as a feature. We will provide the feedback link by tomorrow with other details. 

We appreciate your patience until then.   
  
Regards, 
Balasubramani Sundaram

**Comment by RenugaSadagoban98** [comment]
Hi Ozzy,

Thanks for your patience.

As we said earlier, we will implement this feature in any of our upcoming releases.  

Please refer to the following feedback link for further follow up,  

Feedback link: https://www.syncfusion.com/feedback/24499/support-to-hide-the-top-and-bottom-borders 

We appreciate your patience until then. For further assistance, you can follow the feature request.
