### ISSUE TITLE
[syncfusion_flutter_datagrid] Filter for List<T> column type

### ISSUE THREAD

**Issue by divan** [syncfusion/flutter-widgets#1981]
### Use case

Filtering works awesome in DataGrid if column has only one item. Let's say in column "Color" we have 5 rows with color names - [Red, Blue, Red, Blue, Green]. Filter widget will show three unique colors available for filtering - Red, Green and Blue.

But often object might have two or more values of some type (T). If the same column would be "Colors" and underlying data is a list of colors - List<T>), then filter values would look like `toString()` output of that List object. So if we want to filter "all rows where Colors has Red", the filter won't work.

I'm trying to find a way to make this use case work with filters.

### Proposal

Provide a functionality for filtering for the columns with List<T> type.

**Comment by abineshPalanisamy** [comment]
Hi @divan ,
 
As of now, DataGrid does not have support for filtering the List of items. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link - [46212](https://www.syncfusion.com/feedback/46212/support-for-custom-filtering-list-in-checkbox-filters-in-sfdatagrid)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @divan,

We are closing this issue now. You can follow the given feedback link for further updates. If you have any other concerns, please reopen this issue. We are always happy to assist you.

Regards,
Ashok K
