### ISSUE TITLE
Performance issues on Flutter 3.22.2

### ISSUE THREAD

**Issue by berslen** [syncfusion/flutter-widgets#1984]
### Bug description

I am having major performance issues for the datagrid in WEB platform. I compared the performance of the same code with Flutter version 3.19.6. My table has 2 fixed columns and the rest of the columns are normal columns. I can't share the whole code. Please do compare the performnace in given flutter versions. I compared the same code with Windows platform and web is 6x times slower in Flutter 3.22.2 but in 3.19.6 the difference is only 2x. (0.4s vs 1.2s) 

### Steps to reproduce

1. Add fixed columns
2. see performance in flutter version 3.22.2
3. change flutter version to 3.19.6
4. see the performance in flutter version 3.19.6

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,
 
Based on the details provided, we have reviewed the performance of the DataGrid on both web and Windows platforms. After a thorough analysis, we did not identify any performance issues. To assist you further and better understand the problem, we kindly request that you provide additional details or steps on how you measured performance and conducted comparisons. Additionally, please replicate the performance issue in a simple sample and, if possible, provide a video recording demonstrating the issue for better clarity. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/16332327/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by berslen** [comment]
here is the solution, keep in mind you need to change index.html of the web folder according to the flutter version, just delete the web folder and add web platform when you changed the flutter version. you can definetly see the 1-2 seconds delay loading the table when you select new column 
[datagrid.zip](https://github.com/user-attachments/files/16348074/datagrid.zip)

**Comment by berslen** [comment]
if you can tell me how did you measure these times, i'll make the same on my side and share it with you

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,
 
We tested the time taken to add a new column to the DataGrid by selecting the checkbox. We started a stopwatch within the setState while adding the column at runtime and stopped it after the updateDataSource operation. The elapsed time was measured using **stopwatch.elapsedMilliseconds**. We have attached the sample we used to test the performance.
 
If there are any misunderstandings or if your needs differ, we kindly request that you provide additional details or steps on how you measured performance, conducted comparisons, or modified the attached sample. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible.

- **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/16423308/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,

We suspect that the reported issue has been resolved at your end. We are closing this issue now. If you need any further assistance, kindly reopen this issue. We are always happy to assist you!

Regards,
Ashok K

**Comment by berslen** [comment]
Hi there again sorry for late response,

Here is the Widget that I'm using for DataGrid and the render time results. Keep in mind I've removed some spesific parts of the code that is not relevant to datagrid.

`
class TableWidget<Type> extends StatefulWidget {
  const TableWidget({
    super.key,
    this.dataGridKey,
    required this.dataGridController,
    required this.dataGridSource,
    required this.columns,
    this.emptyStateText = 'List Empty',
    this.allowColumnsResizing = true,
    this.isScrollbarAlwaysShown = true,
    this.gridLinesVisibility = GridLinesVisibility.none,
    this.frozenColumnsCount = 0,
    this.columnWidthMode = ColumnWidthMode.fill,
    this.rowCountChanged,
  });

  final GlobalKey<SfDataGridState>? dataGridKey;
  final DataGridController dataGridController;
  final CustomDataGridSource<Type> dataGridSource;
  final List<TableColumn> columns;
  final String emptyStateText;
  final bool allowColumnsResizing;
  final bool isScrollbarAlwaysShown;
  final GridLinesVisibility gridLinesVisibility;
  final int frozenColumnsCount;
  final ColumnWidthMode columnWidthMode;
  final void Function(int rowCount)? rowCountChanged;

  @override
  State<TableWidget<Type>> createState() => _TableWidgetState();
}

class _TableWidgetState<Type> extends State<TableWidget<Type>> {
  late List<GridColumn> columns;
  late Map<String, double> columnWidths;
  late FocusNode focusNode;

  @override
  void initState() {
    super.initState();
    if (widget.dataGridSource.rows.isNotEmpty) {
      _initializeColumnsWidths();
      _initializeColumns();
    }
  }

  @override
  void didUpdateWidget(covariant TableWidget<Type> oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.dataGridSource.rows.isNotEmpty &&
        widget.dataGridSource.rows.isEmpty) {
      columnWidths.clear();
    }

    if (widget.dataGridSource.rows.isEmpty) {
      return;
    }

    if (widget.dataGridSource.rows != oldWidget.dataGridSource.rows ||
        widget.columns != oldWidget.columns) {
      _initializeColumnsWidths();
      _initializeColumns();
    }
  }

  @override
  void dispose() {
    if (widget.dataGridSource.rows.isNotEmpty) {}
    super.dispose();
  }

  void _initializeColumnsWidths() {
    columnWidths = {
      for (final element in widget.columns) element.columnName: element.width,
    };
  }

  void _initializeColumns() {
    columns = widget.columns
        .map(
          (column) => GridColumn(
            allowFiltering: column.allowFiltering,
            minimumWidth: column.minimumWidth,
            width: columnWidths[column.columnName] ?? double.nan,
            allowSorting: column.allowSorting,
            columnName: column.columnName,
            columnWidthMode: column.columnWidthMode,
            label: column.label,
          ),
        )
        .toList();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.dataGridSource.rows.isEmpty) {
      return EmptyPage(
        emptyStateText: widget.emptyStateText,
      );
    }

    return Shortcuts(
      shortcuts: <LogicalKeySet, Intent>{
        LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.keyC):
            const CopyRowsIntent(),
        LogicalKeySet(LogicalKeyboardKey.control, LogicalKeyboardKey.keyA):
            const SelectAllIntent(),
      },
      child: Actions(
        actions: {
          CopyRowsIntent: CallbackAction<CopyRowsIntent>(
            onInvoke: (CopyRowsIntent intent) async {
              return;
            },
          ),
          SelectAllIntent: CallbackAction<SelectAllIntent>(
            onInvoke: (SelectAllIntent intent) {
              return null;
            },
          ),
        },
        child: Focus(
          focusNode: focusNode,
          onFocusChange: (hasFocus) {
            if (!hasFocus) {
              setState(() {
                widget.dataGridController.selectedRows = [];
              });
            }
          },
          child: _table(),
        ),
      ),
    );
  }

  Widget _table() {
    return SfDataGridTheme(
      data: SfDataGridThemeData(
        indentColumnWidth: 0,
        groupExpanderIcon: const Icon(
          Icons.expand_more,
          size: 24,
        ),
        gridLineColor:
            Theme.of(context).colorScheme.brightness == Brightness.light
                ? Theme.of(context).colorScheme.primary.withAlpha(100)
                : Colors.white,
        headerColor: Theme.of(context).colorScheme.primary.withAlpha(30),
        gridLineStrokeWidth: 1.5,
        filterIconHoverColor:
            Theme.of(context).colorScheme.brightness == Brightness.light
                ? Theme.of(context).colorScheme.primary
                : Colors.white,
        sortIconColor:
            Theme.of(context).colorScheme.brightness == Brightness.light
                ? Theme.of(context).colorScheme.primary
                : Colors.white,
        columnResizeIndicatorColor:
            Theme.of(context).colorScheme.brightness == Brightness.light
                ? Theme.of(context).colorScheme.primary
                : Colors.white,
        filterIconColor:
            Theme.of(context).colorScheme.brightness == Brightness.light
                ? Theme.of(context).colorScheme.primary
                : Colors.white,
        columnResizeIndicatorStrokeWidth: 2,
      ),
      child: SfDataGrid(
        key: widget.dataGridKey,
        onFilterChanged: (details) {
          widget.rowCountChanged
              ?.call(widget.dataGridSource.effectiveRows.length);
        },
        controller: widget.dataGridController,
        isScrollbarAlwaysShown: widget.isScrollbarAlwaysShown,
        allowSorting: true,
        allowFiltering: true,
        gridLinesVisibility: widget.gridLinesVisibility,
        headerGridLinesVisibility: GridLinesVisibility.none,
        headerRowHeight: 32,
        rowHeight: 24,
        groupCaptionTitleFormat: '{Key} ({ItemsCount})',
        columnWidthMode: widget.columnWidthMode,
        frozenColumnsCount: widget.frozenColumnsCount,
        selectionMode: SelectionMode.multiple,
        allowColumnsResizing: widget.allowColumnsResizing,
        columnResizeMode: ColumnResizeMode.onResizeEnd,
        onColumnResizeUpdate: (ColumnResizeUpdateDetails details) {
          setState(() {
            columnWidths[details.column.columnName] = details.width;
            _initializeColumns();
          });
          return true;
        },
        onSelectionChanging: (addedRows, removedRows) {
          return true;
        },
        columns: columns,
        source: widget.dataGridSource,
      ),
    );
  }
}

class CopyRowsIntent extends Intent {
  const CopyRowsIntent();
}

class SelectAllIntent extends Intent {
  const SelectAllIntent();
}

`

I've measured time with a wrapper widget that just has 
`
 WidgetsBinding.instance.addPostFrameCallback((_) {
          final end = DateTime.now().millisecondsSinceEpoch;
          print('Render Time of $widgetName: ${end - start} ms');
        });
`
Here is the result 
![image](https://github.com/user-attachments/assets/c804b1a3-6443-4bf5-96b1-198bca3b05ca)

**Comment by abineshPalanisamy** [comment]
Hi @berslen ,

We tested a simple sample and were able to replicate the reported issue. We also checked similar cases using the framework's DataTable widget, and it appears the problem stems from the framework itself. We have reported this issue to the Flutter framework team. You can track further updates through the GitHub issue link provided below.
 
Framework issue link - https://github.com/flutter/flutter/issues/155293
 
We will wait until the Framework team responses. We will do the action plan from our end based on the update from the framework team. We appreciate your patience and understanding in the meantime. Please let us know if you need any further assistance with this. As always, we are happy to help you out.
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @berslen,

We are closing this issue now. You can track further updates through the Github issue link. If you need any further assistance, please reopen this ticket. We are always happy to help you.

Regards,
Ashok K
