### ISSUE TITLE
syncfusion_flutter_datagrid prevent  Ctrl+V into editable cell by CustomSelectionManager

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1985]
### Bug description

hey i am using Flutter DataGrid (SfDataGrid) with two editable cells now i was not able to capture event on CustomSelectionManager  Future handleKeyEvent(KeyEvent keyEvent) async {
    print('keyevent');} it only print i case of tab and enter not for others

### Steps to reproduce

i cannot able to detect paste event when cell is into input 

### Code sample

please provide sample code

### Screenshots or Video

not this time

### Stack Traces

please provide sample code

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)  
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.10.4)
[√] Android Studio (version 2023.3)
[√] Connected device (3 available)
[√] Network resources

**Comment by abineshPalanisamy** [comment]
Hi @abdulrehmananwar ,
 
In SfDataGrid, when you attempt to edit a cell, the focus shifts to the [TextField](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fmaterial%2FTextField-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C855abbacf79e489bb63f08dcaa4e51c4%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638572500602454316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=bmvX%2Ba8oON7wRbqQUhA4LGZvSOTa1%2FKFMd68VlzhbrM%3D&reserved=0) loaded in the [buildEditWidget](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource%2FbuildEditWidget.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C855abbacf79e489bb63f08dcaa4e51c4%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638572500602460951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=DhpYrzAn%2BxJS7FpOddyMvVEyfx30o12C8z6O4QgUmRo%3D&reserved=0). When the focus moves to the TextField, key events are no longer handled by the DataGrid. In SfDataGrid, we handle key events such as Enter (to submit the cell) and Tab (for navigation) during editing. If you want to handle the Ctrl+V key event, you will need to add a [Focus](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fwidgets%2FFocus-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C855abbacf79e489bb63f08dcaa4e51c4%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638572500602467379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=QOhYrOtP%2BF%2BJWAV2qHvwHdSPw1MNLEN5pRfWTazLG%2FA%3D&reserved=0) widget as the parent of the TextField and perform the action as needed.
 
Additionally, we have attached the user guide documentation for key behaviors handled by SfDataGrid, along with code snippets for your reference. Please review these code snippets for more details and adapt them to suit your specific requirements.
 
UG link - [Keyboard behavior](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Fselection%23keyboard-behavior&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C855abbacf79e489bb63f08dcaa4e51c4%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638572500602473407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=7MPT7i715rIPe5NVVYrY9RpQFtNtWuX6BNrQlpM0%2Fy8%3D&reserved=0)
 
Code snippets:
```dart
  @override
  Widget? buildEditWidget(DataGridRow dataGridRow,
      RowColumnIndex rowColumnIndex, GridColumn column, CellSubmit submitCell) {
    final String displayText = dataGridRow
            .getCells()
            .firstWhereOrNull((DataGridCell dataGridCell) =>
                dataGridCell.columnName == column.columnName)
            ?.value
            ?.toString() ??
        '';

    newCellValue = null;

    final bool isNumericType =
        column.columnName == 'ID' || column.columnName == 'Salary';

    return Container(
      padding: const EdgeInsets.all(8.0),
      alignment: isNumericType ? Alignment.centerRight : Alignment.centerLeft,
      child: Focus(
        onKeyEvent: (node, keyEvent) {
          if (keyEvent.logicalKey == LogicalKeyboardKey.keyA) {
            if (HardwareKeyboard.instance.isControlPressed) {
              // Execute the necessary action.
              return KeyEventResult.handled;
            }
          }
          return KeyEventResult.ignored;
        },
        child: TextField(
          autofocus: true,
          controller: editingController..text = displayText,
          textAlign: isNumericType ? TextAlign.right : TextAlign.left,
          decoration: const InputDecoration(
            contentPadding: EdgeInsets.fromLTRB(0, 0, 0, 8.0),
          ),
          keyboardType:
              isNumericType ? TextInputType.number : TextInputType.text,
          onChanged: (String value) {
            if (value.isNotEmpty) {
              if (isNumericType) {
                newCellValue = int.parse(value);
              } else {
                newCellValue = value;
              }
            } else {
              newCellValue = null;
            }
          },
          onSubmitted: (String value) {
            submitCell();
          },
        ),
      ),
    );
  }
```

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported issue has been resolved at your end. We are closing this issue now. If you need any further assistance, reopen this issue. We are always happy to assist you.

Regards,
Ashok k
