### ISSUE TITLE
merged cells

### ISSUE THREAD

**Issue by Ngochiendev** [syncfusion/flutter-widgets#1987]
### Use case

Please give me the solution to combine columns like this, I see there is a StackedHeaderRow attribute but I tried it and it only displays above. If possible, please give me the solution or give me sample code.

### Proposal

![Ảnh màn hình 2024-07-20 lúc 10 13 26](https://github.com/user-attachments/assets/52afd76b-6075-4c05-8bba-fa0ce9a969f4)

**Comment by abineshPalanisamy** [comment]
Hi @Ngochiendev ,
 
As of now, DataGrid does not have support for merge the rows and cells. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link - [23230](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F23230%2Fsupport-to-merge-the-rows-and-cells&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C67cc92c6cf2a45b7516f08dcaa4e550c%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638572500615156488%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=k2EUKVLbXH%2FH29RJ0T4j3i871%2BNmG84bSrNEmrkloo8%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @Ngochiendev,

We are closing this issue now. You can follow up regarding the merged cells and rows support through the provided feedback link. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok k
