### ISSUE TITLE
[syncfusion_flutter_signaturepad] Is there any way to change signature image size?

### ISSUE THREAD

**Issue by sgsm74** [syncfusion/flutter-widgets#1989]
Hey
Is there any way to change the signature image size? like changing width and height?or aspect ratio?

**Comment by LokeshPalani** [comment]
Hi @sgsm74,


You can reduce the size of the image by using the **copyResize** method within the **_renderImage** method. By utilizing **_signaturePadKey** in the **_readImageData** method, you can get the state of the signature pad for image extraction using [toImage](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState/toImage.html) function. This allows you to capture the signature as an image and convert it to ByteData. In the **_renderImage** method, you can resize the image using the **copyResize** method by assigning the new dimensions to the image's height and width. We have shared code snippet and sample for your reference below. Please let us know if you need any further needs.

 

**Code Snippet:**

``` dart
Future<ByteData> _readImageData() async {
  final ui.Image data = await _signaturePadKey.currentState!.toImage(pixelRatio: 1.0);
  final ByteData? bytes = await data.toByteData(format: ui.ImageByteFormat.png);
  return bytes!;
}

Future<void> _renderImage() async {
  final ByteData bytes = await _readImageData();

  final Uint8List uint8list = bytes.buffer.asUint8List();

  final img.Image? image = img.decodeImage(uint8list);
  if (image == null) return;

  final img.Image resizedImage = img.copyResize(image, height: 300, width: 300);

  // Save the resized image as a file
  final Directory directory = await getApplicationDocumentsDirectory();
  final String path = '${directory.path}/signaturepad.png';
  final File file = File(path);
  await file.writeAsBytes(img.encodePng(resizedImage));

  if (!mounted) return;

  await Navigator.of(context).push(
    MaterialPageRoute(
      builder: (BuildContext context) {
        return Scaffold(
          appBar: AppBar(),
          body: Center(
            child: Container(
              color: Colors.white,
              child: Image.file(file),
            ),
          ),
        );
      },
    ),
  );
}
```

Regards,
Lokesh P.
