### ISSUE TITLE
App is not compiled anymore after upgrade flutter to 2.2.0-10.1.pre

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#199]
syncfusion_flutter_sliders-19.1.56-beta/lib/src/range_selector.dart:1863:16: Error: Type `MouseTrackerAnnotation` not found
syncfusion_flutter_sliders-19.1.56-beta/lib/src/range_selector.dart:2946:3: Error: Type `PointerEnterEventListener` not found
syncfusion_flutter_sliders-19.1.56-beta/lib/src/range_selector.dart:2950:3: Error: Type `PointerHoverEventListener` not found
syncfusion_flutter_sliders-19.1.56-beta/lib/src/range_selector.dart:2953:3: Error: Type `PointerExitEventListener` not found

Why this? Any idea fow to fix?

**Comment by bambinoua** [comment]
It seems because `MouseTrackerAnnotation` is in package `flutter:flutter/services.dart` but in your code there is no such import.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi, 
  
In the Flutter latest beta version (2.2.0-10.1.pre), the MouseTrackerAnnotation class has been moved from “package:flutter/rendering.dart” to “package:flutter/services.dart” library. We have fixed this in our source and this fix will be included in our next weekly NuGet on April 27th, 2021.  
  
Regards,  
Lakshmi R.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,

As we mentioned earlier, we have included fix for the reported issue in our latest weekly release (19.1.58-beta). Kindly check and confirm us whether the issue resolved in your side.

Regards,
Lakshmi R.

**Comment by tusharthe** [comment]
Hi, its getting that same error 
![image](https://user-images.githubusercontent.com/20502003/116246088-45e52200-a787-11eb-9dc7-b39775e516b9.png)

flutter version 
![image](https://user-images.githubusercontent.com/20502003/116246205-64e3b400-a787-11eb-90e8-18fd36321ac3.png)

**Comment by SarathSk50** [comment]
Hi tusharthe,

We are able to reproduce the reported issue and logged a defect report. The fix for this issue will be included in our upcoming weekly NuGet release which is expected to be published on May 4, 2021.
 
Regards
Sarath Kumar Prakash

**Comment by bambinoua** [comment]
After upgrading package to version 19.1.58 all works fine. Thanks!
