### ISSUE TITLE
Error (Xcode): ../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-26.1.42/lib/src/form_fields/pdf_signature.dart:590:25: Error: Couldn't find constructor 'WidgetStatePropertyAll'.

### ISSUE THREAD

**Issue by badshamasala** [syncfusion/flutter-widgets#1992]
### Bug description

Error (Xcode): ../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdfviewer-26.1.42/lib/src/form_fields/pdf_signature.dart:590:25: Error: Couldn't find
constructor 'WidgetStatePropertyAll'.

### Steps to reproduce

error

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>
error

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>
error

**Comment by immankumarsync** [comment]
@badshamasala, we have migrated our source to be compatible with Flutter SDK 3.22.0. In Flutter SDK version 3.22.0, MaterialState and its related APIs have been moved out of the Material library and renamed to WidgetState.

So, we kindly request that you upgrade the Flutter SDK version to 3.22.0, or else use the syncfusion_flutter_pdfviewer package version below 25.2.4.

We have also shared the breaking changes documentation below for your reference.
[Rename MaterialState to WidgetState | Flutter](https://docs.flutter.dev/release/breaking-changes/material-state)


We hope it will help you resolve the issue. If you have any further queries, please get back to us.

**Comment by Deepak1799** [comment]
@badshamasala We believe that the issue has been resolved; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.
