### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range 

### ISSUE THREAD

**Issue by Mir1001** [syncfusion/flutter-widgets#1996]
### Bug description

Quick refresh of widget in first build throws exception (RangeError (index): Invalid value: Not in inclusive range 0..4: 5 ).  I have narrow bug to:
```dart
ColumnSeries<Result, int>(
          dataSource: data,
          xValueMapper: (Result data, index) => index + 1,
          yValueMapper: (Result data, _) => games.getResultValue(data).toDouble(),
          pointColorMapper: (Result data, _) => getVariantColor(data.variantId), // Error index...
    ];
```
If I comment pointColorMapper line it works well.

Further error is in chart_series.dart function effectiveColor. State:
![image](https://github.com/user-attachments/assets/1c7f5c67-3774-4f04-b97c-ec8e0b8fe8c3)

After guess is something about series segmentsCount and dataCount.
Data are all 5 columns.

**Error is at first build of widget, but when it is refreshed by other event it works well**. 

### Steps to reproduce

1. Screen is on, I have already nice garph.
2. Data is changed (specific data) not always.
3. First build throws error widget is not drawn
4. Other event triggers refresh
5. Graph is drawn correctly

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
════════ Exception caught by widgets library ═══════════════════════════════════ 
The following RangeError was thrown building KeyedSubtree-[GlobalKey#3f2db]: 
RangeError (index): Invalid value: Not in inclusive range 0..4: 5 
The relevant error-causing widget was: SfCartesianChart SfCartesianChart: graf_widget.dart When the exception was thrown, this was the stack: 
#0 List.[] (dart:core-patch/growable_array.dart:264:36) 
growable_array.dart:264
#1 ChartSeriesRenderer.effectiveColor (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:1842:31) 
chart_series.dart:1842
#2 ChartSeriesRenderer.updateSegmentColor (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:1785:30) 
chart_series.dart:1785
#3 ColumnSeriesRenderer.customizeSegment (package:syncfusion_flutter_charts/src/charts/series/column_series.dart:355:5) 
column_series.dart:355
#4 List.forEach (dart:core-patch/growable_array.dart:416:8) 
growable_array.dart:416
#5 ChartSeriesRenderer.markNeedsSegmentsPaint (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:2293:14) 
chart_series.dart:2293
#6 ChartSeriesRenderer.palette= (package:syncfusion_flutter_charts/src/charts/series/chart_series.dart:834:7) 
chart_series.dart:834
#7 RenderChartPlotArea.performUpdate.<anonymous closure> (package:syncfusion_flutter_charts/src/charts/base.dart:1249:13) 
base.dart:1249
#8 ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:4374:14) 
object.dart:4374
#9 RenderChartPlotArea.performUpdate (package:syncfusion_flutter_charts/src/charts/base.dart:1244:5) 
base.dart:1244
#10 RenderCartesianChartPlotArea.performUpdate (package:syncfusion_flutter_charts/src/charts/base.dart:1712:11) 
base.dart:1712
#11 ChartAreaUpdateMixin.update (package:syncfusion_flutter_charts/src/charts/base.dart:165:5) 
base.dart:165
#12 RenderCartesianChartArea._update (package:syncfusion_flutter_charts/src/charts/base.dart:802:18) 
base.dart:802
#13 ChartAreaRenderObjectElement.update (package:syncfusion_flutter_charts/src/charts/base.dart:113:15) 

```

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-SI)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.91.1)
[✓] VS Code (version 1.88.1)
[✓] Connected device (5 available)            
[✓] Network resources

• No issues found!```

</details>

**Comment by LokeshPalani** [comment]
Hi @Mir1001, 

We have checked the reported issue and tried to replicate it in [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) with chart version [26.2.5+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.5+1) by setting the [pointColorMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/pointColorMapper.html) in the [ColumnSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ColumnSeries-class.html), and it was working fine at our end. However, we were unable to reproduce the reported issue at our end. We kindly request you replicate the reported issue in the sample attached below and provide us with more details regarding the specific scenario in which you encounter with a screen recording. This will help us to assist you more effectively.


Regards,
Lokesh P.

[pointcolormapper.zip](https://github.com/user-attachments/files/16413306/pointcolormapper.zip)

**Comment by Mir1001** [comment]
At the beginning there was no way to repeat problem on your example. But I have found reason for unexpected behaviour. I have defined palette and pointColorMapper. If I remove palette it works.

Maybe it doesn't make sense to define both, but when you add/test functionality it is expected an error or warning or at least not random behaviour. 

***To replicate error you need to click buttons  Data1 and then Data2.... Use provided example at end.***
```dart
    SfCartesianChart(
            primaryXAxis: const NumericAxis(),
            primaryYAxis: const NumericAxis(),
            palette: <Color>[Colors.teal, Colors.red, Colors.brown],   //THIS IS A PROBLEM IF I REMOVE THIS LINE IT WORKS
            margin: EdgeInsets.all(1),
            plotAreaBorderWidth: 0,
            borderWidth: 0,

            title: ChartTitle(text: isCardView ? '' : 'Results'),
            legend: Legend(
                isVisible: isCardView ? false : true,
                overflowMode: LegendItemOverflowMode.wrap),
            series: <CartesianSeries<dynamic, dynamic>>[
              ColumnSeries<ChartSampleData, num>(
                dataSource: data,
                xValueMapper: (ChartSampleData sales, int index) => index + 1,
                yValueMapper: (ChartSampleData sales, _) => sales.sales,
                pointColorMapper: (ChartSampleData sales, int index) =>.      //USING palette makes this index error...
                    _getColor(index),
              )
            ],
          ),
``` 

[main.dart.zip](https://github.com/user-attachments/files/16456453/main.dart.zip)

For me this issue is closed, because iI have removed line `palette`, but maybe this can be prevented... Thanks.
