### ISSUE TITLE
[bug] SelectionMode.multiple

### ISSUE THREAD

**Issue by beerline** [syncfusion/flutter-widgets#200]
Hi syncfusion developers! 
Thank you for awesome library!

I faced with some  view behavior by using `DateRangePickerSelectionMode.multiple` and `cellBuilder`
Steps to reproduce:
1. select several dates. On screencast April 20,21,22.
2. unselect **all** selected dates
3. try to select again. it is work wit any dates, but on screen cast i selected same April 20,21,22.

**Result:** no selection.
Next steps:
1. slide to next month and back (April - May - April)
2. no result
3. slide 2 month forward and back ((April - May - June - May - April))
4. now you can see selected dates

[demo repository](https://github.com/beerline/syncfusion-data-picker-demo)

<details>
  <summary>Code example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';

class DatePicker extends StatefulWidget {
  @override
  _DatePickerState createState() => _DatePickerState();
}

class _DatePickerState extends State<DatePicker> {
  DateRangePickerController _controller = DateRangePickerController();

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SfDateRangePicker(
      controller: _controller,
      selectionColor: Colors.transparent,
      toggleDaySelection: true,
      allowViewNavigation: false,
      selectionMode: DateRangePickerSelectionMode.multiple,
      cellBuilder: (BuildContext context, DateRangePickerCellDetails details) {
        final now = DateTime.now();
        final currentDate = DateTime(now.year, now.month, now.day);
        final isToday = details.date == currentDate;
        final isPastDay = details.date.isBefore(currentDate);
        final isSelected = _controller.selectedDates?.contains(details.date) ?? false;

        return Container(
          margin: EdgeInsets.all(2),
          child: LayoutBuilder(
              builder: (BuildContext context, BoxConstraints constraints) {
            double size = constraints.maxWidth;
            if (constraints.maxHeight < constraints.maxWidth) {
              size = constraints.maxHeight;
            }
            return Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: <Widget>[
                Container(
                  alignment: Alignment.center,
                  width: size,
                  height: size,
                  decoration: BoxDecoration(
                    color: isSelected ? Colors.red : null,
                    border: isToday
                        ? Border.all(color: Colors.purple, width: 1)
                        : null,
                  ),
                  child: Text(
                    details.date.day.toString(),
                    style: TextStyle(
                        color: isPastDay
                            ? theme.hintColor
                            : isSelected
                                ? Colors.white
                                : Colors.black),
                  ),
                ),
              ],
            );
          }),
        );
      },
      monthViewSettings: DateRangePickerMonthViewSettings(
        firstDayOfWeek: 1,
        dayFormat: 'EEE',
      ),
      showNavigationArrow: true,
      enablePastDates: false,
    );
  }
}
```
</details>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/7195911/115278561-a5737a00-a156-11eb-8d51-f180e424950b.gif)

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the mentioned issue “**Unable to select the dates after deselecting in Flutter date range picker**”. We will include the issue fix in our upcoming Weekly Nuget package, which is expected to be rolled out by April 27, 2021 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have included the mentioned issue fix “**Unable to select the dates after deselecting in Flutter date range picker**” in our latest Weekly Nuget version 19.1.58-beta. Kindly update to the latest version for resolving this issue fix. Also please find the latest version from the following link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_datepicker/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by beerline** [comment]
Hi @Indumathi1195R!
Appreciate for fix. Now everything works properly
