### ISSUE TITLE
SfDataGrid How To make  gridLine and headerGridLine how only vertical line ?

### ISSUE THREAD

**Issue by aike1202** [syncfusion/flutter-widgets#2000]
### Use case

I want make table has no outline , only show the line inside table 

when i set  gridLinesVisibility and  headerGridLinesVisibility it draw the both line of last and frist and bottom cells line , 
`dart
gridLinesVisibility: GridLinesVisibility.vertical,
headerGridLinesVisibility: GridLinesVisibility.vertical,
`
![image](https://github.com/user-attachments/assets/fa8921d9-d0a8-4068-83db-e2af10b45c87)

### Proposal

add 'tableOutLineWidth and tableOutLineColor  ' to SfDataGrid or SfDataGridThemeData,
when tableOutLineWidth is 0 dont show line of table

**Comment by abineshPalanisamy** [comment]
Hi @aike1202 ,

In SfDataGrid version 25.2.7 and later, the outer border is drawn on all sides when gridline visibility is not set to 'None'. However, you can work around this by using the [ClipRect](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fwidgets%2FClipRect-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C83bea2acd30948103bec08dcb2be0e6f%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638581776557824471%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=zGMYRUiuvFgNr7jzyJgM%2BOlMsFiALYuaVtM3A7bNLws%3D&reserved=0) widget along with a custom clipper (CustomClipper<Rect>) to remove the outer borders.
 
To achieve this, you need to create a custom clipper class by extending the CustomClipper<Rect> class. In the getClip method, you can use Rect.fromLTWH to set the grid line stroke width for the left and top, and specify the appropriate size for the right and bottom based on the grid layout. After defining this custom clipper, wrap the SfDataGrid as a child of ClipRect to control the visibility of the borders as desired.
 
We have included a sample  for your reference. Please review this sample for more details and adapt it to suit your specific requirements.

- Sample : [SfDataGrid.zip](https://github.com/user-attachments/files/16466494/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by aike1202** [comment]
@abineshPalanisamy thanks a lot ! it works for me
