### ISSUE TITLE
[syncfusion_flutter_charts] Make tooltips clickable

### ISSUE THREAD

**Issue by louisdeveseleer** [syncfusion/flutter-widgets#2001]
### Use case

Tooltip can be customized through TooltipBehavior builder.
But the elements inside the tooltip are not actionable: there seems to be something in the plugin that prevents interacting with the content of the tooltip.
In the design attached, I'd like to be able to click on the button displayed in the tooltip.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-01 at 12 41 45](https://github.com/user-attachments/assets/61a6b21f-4049-4374-a848-3bc35f880a22)

### Proposal

Allow the user to interact with the tooltip content when using the TooltipBehavior builder.

**Comment by LokeshPalani** [comment]
Hi @louisdeveseleer,

You can display the Open button by using the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property of the [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html). By using this, you can place the button in the tooltip and perform the operation with the [onPressed](https://api.flutter.dev/flutter/material/ButtonStyleButton/onPressed.html) event in the [ElevatedButton](https://api.flutter.dev/flutter/material/ElevatedButton-class.html). We have prepared a workaround sample to navigate to the next page when the Open button is tapped in the [TooltipBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior-class.html). You can modify the sample to display the workout details when tap on the Open button based on your needs. We have provided a code snippet, user guide documentation link, sample, code snippet, and a screen recording for your reference below. Please let us know if you need any further needs.

UG Link for builder of TooltipBehavior: https://help.syncfusion.com/flutter/cartesian-charts/tooltip#tooltip-template

SB Link for builder of TooltipBehavior: https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/tooltip/tooltip-template

Code Snippet:

``` dart
SfCartesianChart(
  primaryXAxis: const DateTimeAxis(),
  tooltipBehavior: TooltipBehavior(
    enable: true,
    builder: (data, point, series, pointIndex, seriesIndex) => Padding(
      padding: const EdgeInsets.all(15),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const Text(
            'Workout Session',
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 16,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 8),
          Container(
            height: 1,
            width: 100,
            decoration: const BoxDecoration(
              border: Border(
                top: BorderSide(
                  color: Colors.white,
                  width: 2,
                ),
              ),
            ),
          ),
          const SizedBox(height: 8),
          ElevatedButton(
            onPressed: () => Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => const DetailPage()),
            ),
            child: const Text('Open'),
          ),
        ],
      ),
    ),
  ),
),
```

Regards,
Lokesh P.

[tooltip_touchinteraction.zip](https://github.com/user-attachments/files/16471190/tooltip_touchinteraction.zip)

**Comment by louisdeveseleer** [comment]
Hi @LokeshPalani  thanks for your detailed answer, and even a demonstration video!

I have no problem with creating a button, or using the navigator. The issue I have is that the button is not clickable: there seems to be something in the tootip that prevents the tap from getting to the button. However in your video it works, so I guess something else is interfering with the tooltip touch, possibly because of the way I use the plugin.

Note: the "hide tooltip on touch" behavior, described in the doc of the `shouldAlwaysShow` parameter, also does not work.

Here is my code:
```
SfCartesianChart(
  series: _syncfusionOptionedFilteredData(),
  margin: const EdgeInsets.symmetric(vertical: 0, horizontal: 0),
  enableAxisAnimation: true,
  tooltipBehavior: TooltipBehavior(
    enable: true,
    builder: (data, point, series, pointIndex, seriesIndex) {
      final dataPoint = data as DataPoint;
      final session = dataPoint.attachment;
      final style = Theme.of(context)
          .textTheme
          .labelMedium
          ?.copyWith(color: Colors.white);
      if (session is Session) {
        **return Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              child: Text(
                '${DateFormat.MMMd().format(dataPoint.date)}: ${session.getName(context)}',
                style: style,
              ),
            ),
            Expanded(
              child: TextButton(
                onPressed: () {
                  print('The button was clicked');
                  _openSession(session);
                },
                child: Text(S.of(context).generalOpen),
              ),
            ),
          ],
        );**
      } else {
        return Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              dataPoint.label,
              style: style,
            ),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              child: Container(
                width: 50,
                height: 1,
                color: Colors.white,
              ),
            ),
            Text(
              '${DateFormat.MMMd().format(dataPoint.date)}: ${dataPoint.value.toStringAsPrecision(widget.decimalPoints)}',
              style: style,
            ),
          ],
        );
      }
    },
  ),
  primaryXAxis: DateTimeAxis(
    isVisible: showAxisLabels,
    minimum: _getTimeBounds().first,
    maximum: _getTimeBounds().last,
  ),
  primaryYAxis: NumericAxis(
    plotBands: widget.experienceProfile
        ? List.generate(
            DifficultyIndicator.numberOfLevels,
            (index) {
              return PlotBand(
                start: index * 2,
                end: (index + 1) * 2,
                color: Color.alphaBlend(
                    Theme.of(context).scaffoldBackgroundColor.withOpacity(0.8),
                    DifficultyIndicator.difficultyColors[index]),
              );
            },
          )
        : [],
    minimum: widget.minimumValue,
    maximum: widget.maximumValue,
    labelsExtent: showAxisLabels ? null : 0,
    axisLine: showAxisLabels ? const AxisLine() : const AxisLine(width: 0),
    majorTickLines: widget.experienceProfile
        ? const MajorTickLines(size: 0, width: 0)
        : const MajorTickLines(),
    axisLabelFormatter: (details) =>
        yAxisLabelFormatter(details, widget.y1Unit),
    rangePadding: ChartRangePadding.round,
  ),
  axes: [
    NumericAxis(
      isVisible: _secondAxisFilteredData != null,
      opposedPosition: true,
      name: bodyweightYAxisName,
      axisLabelFormatter: (details) =>
          yAxisLabelFormatter(details, widget.y2Unit),
      title: AxisTitle(
        text: S.of(context).generalBodyweight,
        alignment: ChartAlignment.center,
        textStyle: Theme.of(context)
            .textTheme
            .labelSmall
            ?.copyWith(color: secondaryAxisColor),
      ),
    ),
  ],
)
```

and here is the result:
(in this video, I am clicking on the button, but nothing is happening)

https://github.com/user-attachments/assets/6862bd8a-8995-49f3-85a9-382795d5bb14

**Comment by louisdeveseleer** [comment]
Hi @PreethikaSelvam ,

Thanks for your answer.
After further analysis, I found what the issue is: the tooltip's content is only clickable if it's within the bounds of the graph area. The tooltip content that is stacked over the axis or under is not clickable. Only the part of the tooltip button that is stacked over the graph area is clickable. See screenshot attached for visual.

![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-08 at 08 38 40](https://github.com/user-attachments/assets/dd401630-9e77-4c32-b23c-91fea2a27041)

Can you reproduce that on your side, and is there anything you'd be able to do about this issue?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
