### ISSUE TITLE
[syncfusion_flutter_calendar][TimeSlotViewSettings] How to custom generate List left timeslot ?

### ISSUE THREAD

**Issue by phatdat-dev** [syncfusion/flutter-widgets#2005]
### Use case

I want custom left of time slot, how can i do that ?...

### Proposal

![e3173841-750e-45d3-880b-8da3e1e8efb0](https://github.com/user-attachments/assets/022fce44-9c6e-476d-83b8-93a1b6cf60e4)
![image](https://github.com/user-attachments/assets/91df484f-94ba-4402-b8c4-e6f2730a5fb2)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.
