### ISSUE TITLE
SFSfDataGrid localizations FilterElement EMpty 

### ISSUE THREAD

**Issue by aike1202** [syncfusion/flutter-widgets#2010]
### Bug description

SFSfDataGrid localizations FilterElement  (Blanks) Optioin is not translated 

### Steps to reproduce

found when i use cn ZH and find out the value   (Blanks) is fixed not in syncfusion_zh.arb ot any other language

### Code sample

1

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![QQ_1723003700969](https://github.com/user-attachments/assets/9b539a89-4c9c-4acd-884a-0e8735cd0a62)
</details>

### Stack Traces

1

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [版本 10.0.22000.2538], locale zh-CN)
    • Flutter version 3.22.2 on channel stable at C:\Users\Aike\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (9 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Aike\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.5)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34723.18
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2023.2.5
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.92.0)
    • VS Code at C:\Users\Aike\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.94.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.202
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.80

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @aike1202 ,
 
As of now, DataGrid does not have support for localizing the 'Blank' option in the check box filtering pop-up. We have  considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [60252](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F60252%2Fsupport-for-localizing-the-filtering-pop-up-when-the-cell-value-is-nullblank&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cc0273f177df8411b133508dcb776bbab%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638586967791793703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=FIU4rib9DY045flvQHZXtV84r43UegdkghufZ%2BaIJ84%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by aike1202** [comment]
Thanks  a lot ! best package ever!

**Comment by ashok-kuvaraja** [comment]
Hi @aike1202,

Your appreciation is greatly valued. It encourages us to keep striving.

Please follow the provided feedback link for further updates regarding the requested feature. We are closing this issue now, but if you need any further assistance, please feel free to reopen it. We're always happy to help!

Best regards,
Ashok K
