### ISSUE TITLE
latest updated can not be compiled

### ISSUE THREAD

**Issue by leong2015** [syncfusion/flutter-widgets#2012]
### Bug description

After Flutter update  to  syncfusion_flutter_charts: ^26.2.8

### Steps to reproduce

1. flutter pub add syncfusion_flutter_charts
2. flutter pub get
3. import 'package:syncfusion_flutter_charts/charts.dart';
import 'package:syncfusion_flutter_charts/sparkcharts.dart';
4. @override
Widget build(BuildContext context) {
  return Scaffold(
    body: Center(
        child: Container(
          child: SfCartesianChart()
        )
      )
  );
}

### Code sample

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: Center(
        child: Container(
          child: SfCartesianChart()
        )
      )
  );
}

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![Screenshot 2024-08-07 at 4 01 51 PM](https://github.com/user-attachments/assets/a7c3f35d-e8ca-4599-8a03-a13da500cfef)
![Screenshot 2024-08-07 at 4 01 59 PM](https://github.com/user-attachments/assets/27b113c2-89ea-41f3-a7fb-60e27653092c)

### Stack Traces

Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/cartesian_chart.dart:1367:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/base.dart:3317:7: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderLoadingIndicator'.
 - 'RenderLoadingIndicator' is from 'package:syncfusion_flutter_charts/src/charts/base.dart' ('../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/base.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
      markNeedsBuild();
      ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/common/core_tooltip.dart:168:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/common/core_legend.dart:452:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../FlutterDev/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/common/element_widget.dart:117:5: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderChartElementLayoutBuilder<T, D>'.
 - 'RenderChartElementLayoutBuilder' is from 'package:syncfusion_flutter_charts/src/charts/common/element_widget.dart' ('../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/common/element_widget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
    markNeedsBuild();
    ^^^^^^^^^^^^^^

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

[✓] Flutter (Channel master, 3.24.0-1.0.pre.487, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
    • Flutter version 3.24.0-1.0.pre.487 on channel master at /Users/ladong/FlutterDev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e0c051f47f (2 hours ago), 2024-08-07 01:52:41 -0400
    • Engine revision 5a0fd5fbec
    • Dart version 3.6.0 (build 3.6.0-122.0.dev)
    • DevTools version 2.38.0

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/ladong/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.2.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.90.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (7 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554                        • android-arm64  • Android 12 (API 32) (emulator)
    • sdk gphone64 arm64 (mobile)     • emulator-5556                        • android-arm64  • Android 12 (API 32) (emulator)
    • wing chung的 iPhone (mobile)     • 00008120-000C4909369B401E            • ios            • iOS 17.5.1 21F90
    • iPhone 15 (mobile)              • 2BA03989-D75B-44DA-81B2-5609181097E5 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

**Comment by fingineering** [comment]
#2008 is the same.

**Comment by UmairRehmat1** [comment]
getting the same issue.

**Comment by soufianebenyaala** [comment]
Yup, blocked by this issue!

**Comment by shahindadashov** [comment]
same

**Comment by MiladAtef** [comment]
same

**Comment by shahindadashov** [comment]
> getting the same issue. We have a major release and blocked by this

consider downgrade to 3.22

**Comment by Kaddtechnologies** [comment]
same here . Syncfusion come one what are you doing? You cant release a broken product

**Comment by jchirinosodio** [comment]
I can replicate it

**Comment by yogeshButani** [comment]
same issue

**Comment by UmairRehmat1** [comment]
There is no other solution except making the environment
from
```
environment:
    sdk: '>=3.0.0 <4.0.0'

```
to

```
environment:
    sdk: '3.22.2'
```
    
  or if you are not using, use code magic. it comes with 500 free minutes as well. set the environment version there to 3.22.2 and all good. no need to do any change in the application. 
  
  or if not. there is an other package [Graphic](https://pub.dev/packages/graphic) which you can use, it has all the charts but with different name.

**Comment by yogeshButani** [comment]
> There is no other solution except making the environment from
> 
> ```
> environment:
>     sdk: '>=3.0.0 <4.0.0'
> ```
> 
> to
> 
> ```
> environment:
>     sdk: '>=3.0.0 <3.22.2'
> ```
> 
> or if you are not using, use code magic. it comes with 500 free minutes as well. set the environment version there to 3.22.2 and all good. no need to do any change in the application.
> 
> or if not. there is an other package [Graphic](https://pub.dev/packages/graphic) which you can use, it has all the charts but with different name.

Still not working, tried your solution but keep getting same error pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/base.dart:3317:7: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderLoadingIndicator'.

**Comment by UmairRehmat1** [comment]
> > There is no other solution except making the environment from
> > ```
> > environment:
> >     sdk: '>=3.0.0 <4.0.0'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > environment:
> >     sdk: '>=3.0.0 <3.22.2'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or if you are not using, use code magic. it comes with 500 free minutes as well. set the environment version there to 3.22.2 and all good. no need to do any change in the application.
> > or if not. there is an other package [Graphic](https://pub.dev/packages/graphic) which you can use, it has all the charts but with different name.
> 
> Still not working, tried your solution but keep getting same error pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.8/lib/src/charts/base.dart:3317:7: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderLoadingIndicator'.

bro, clear chache with `flutter pub cache clean ` then remove pubspec.lock update pubspec with the environment. and then run

**Comment by zoualfkar15** [comment]
same after upgrade flutter to 3.24.0

**Comment by DaraGboyega** [comment]
what do we do in the meantime?

**Comment by Kaddtechnologies** [comment]
> Hi @leong2015, @fingineering, @UmairRehmat1, @soufianebenyaala, @shahindadashov, @hagen00, @viniciusddrft, @Kaddtechnologies, @jchirinosodio, @yogeshButani, @zoualfkar15,
> 
> The reported issue arises because our packages are currently compatible with Flutter SDK version 3.22.3. We have begun evaluating the compatibility and feasibility of updating our packages to work with the latest Flutter version, v3.24.0. We plan to make our packages compatible and include them in our Volume 3 main release, which is expected to be rolled out on second week of September.
> 
> Regards,
> 
> Preethika Selvam.

no this needs to be a hotfix as it is a showstopper. September isn't going to cut it. you have paying customers. they come first.

The fix should have been released yesterday

**Comment by dovahkiin98** [comment]
> > Hi @leong2015, @fingineering, @UmairRehmat1, @soufianebenyaala, @shahindadashov, @hagen00, @viniciusddrft, @Kaddtechnologies, @jchirinosodio, @yogeshButani, @zoualfkar15,
> > The reported issue arises because our packages are currently compatible with Flutter SDK version 3.22.3. We have begun evaluating the compatibility and feasibility of updating our packages to work with the latest Flutter version, v3.24.0. We plan to make our packages compatible and include them in our Volume 3 main release, which is expected to be rolled out on second week of September.
> > Regards,
> > Preethika Selvam.
> 
> no this needs to be a hotfix as it is a showstopper. September isn't going to cut it. you have paying customers. they come first.
> 
> The fix should have been released yesterday

The question would be, why is such a popular library using deprecating APIs? I'm sure Flutter didn't just remove those APIs over night, they have probably been deprecated for over a year

**Comment by soufianebenyaala** [comment]
It might be better to switch to another package rather than waiting for an update.

**Comment by Luvti** [comment]
as a temporary solution for those who migrate to Flutter 3.24 use:
```yaml
syncfusion_flutter_charts:
    git:
      url: https://github.com/Luvti/flutter-widgets
      path: packages/syncfusion_flutter_charts
      ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea #flutter/3.24 
```

**Comment by Macacoazul01** [comment]
Instead of releasing this in september, why not trying to review this fork and releasing an official hotfix?

**Comment by hagen00** [comment]
I'm using [fvm](https://fvm.app/) and am building this with 3.22.3. This is the best solution for me for now.

**Comment by David-Prelinger** [comment]
Are there any updates to release it as a hotfix?

**Comment by UmairRehmat1** [comment]
Downgrading flutter for this package creating problem with other packages as well.

**Comment by UmairRehmat1** [comment]
> as a temporary solution for those who migrate to Flutter 3.24 use:
> 
> ```yaml
> syncfusion_flutter_charts:
>     git:
>       url: https://github.com/Luvti/flutter-widgets
>       path: packages/syncfusion_flutter_charts
>       ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea #flutter/3.24 
> ```

This is not working anymore, unable to pull after flutter clean. permission changed or something?

**Comment by tgrushka** [comment]
Unbelievable. #1907 asked to address this back in June. This is creating all manner of problems for us.

**Comment by JiangXFei** [comment]
<img width="745" alt="7482724E4EC34E682292D5BAC4B60DE2" src="https://github.com/user-attachments/assets/15eab38d-22eb-4c6b-a7f6-ed514c0a1c13">
I directly in RenderConstrainedLayoutBuilder defines a markNeedsBuild () can run, but don't know will there be other effects.

**Comment by ThilipChandru** [comment]
Hi all,

Thank you for your patience. We have upgraded our Flutter Charts package to be compatible with Flutter SDK 3.24.0. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.

Regards,
Thilip Chandru.

**Comment by maxeema** [comment]
Thank you @ThilipChandru and team Syncfusion!
Thank you guys! :rocket: 
It works: I just tested it on Flutter 3.24.1!
Great job, and thanks for the amazing Syncfusion Flutter packages!

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
