### ISSUE TITLE
Enable SelectionBehavior for TrackballBehavior in BarSeries

### ISSUE THREAD

**Issue by Dao-Van-Thanh** [syncfusion/flutter-widgets#2016]
Hello,

I am currently using the BarSeries in your charting library and I have encountered an issue. I would like to use SelectionBehavior to highlight a bar when I click on the trackball. However, it seems that SelectionBehavior does not work with TrackballBehavior.

Could you please provide guidance on how to enable SelectionBehavior when interacting with the trackball? Specifically, I want to highlight the bar that corresponds to the trackball's position.

Thank you for your assistance.

**Comment by ThilipChandru** [comment]
Hi @Dao-Van-Thanh,
 
We are validating your query at our end and we will update further details in one business days. We appreciate your patience until then.
 
Regards,
S Thilip Chandru

**Comment by Dao-Van-Thanh** [comment]
Hi Preethika,

Thank you for the detailed solution and the code snippet. I’ll try it out and let you know if I need further assistance.

Best,
Dao Van Thanh

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
