### ISSUE TITLE
 SfPdfViewer.network not loading the pdf page with changes that has been done using syncfusion pdf editing 

### ISSUE THREAD

**Issue by Ak-sws** [syncfusion/flutter-widgets#2017]
### Bug description

**Bug**: 

when i try to open the link using 

SfPdfViewer.network(
              pdfUrl,
            ),

url ======. "https://gatedcaribbean.s3.amazonaws.com/documents/1723098805473_.pdf"

if you open the link on chrome you will see three things on the last page signature , name and date 
you can check that on screenshot below 
<img width="170" alt="Screenshot 2024-08-08 at 12 48 46 PM" src="https://github.com/user-attachments/assets/625f7b5c-40a6-4bf9-a058-881b52d92ec0">

but when i try to open with this SfPdfViewer.network(
              pdfUrl,
            ),
it give me error , pdf get rendered but the changes that i have done using syncfusin pdf editing library is not reflecting 

**Error**

E/flutter (16117): [ERROR:flutter/runtime/dart_isolate.cc(1291)] Unhandled exception:
E/flutter (16117): Invalid argument (Header of the stream can not be read.): -1
E/flutter (16117): #0      CompressedStreamReader._readZlibHeader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:220:7)
E/flutter (16117): #1      CompressedStreamReader._initialize (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:212:7)
E/flutter (16117): #2      new CompressedStreamReader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:12:5)
E/flutter (16117): #3      PdfZlibCompressor.decompress (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/pdf_zlib_compressor.dart:22:43)
E/flutter (16117): #4      PdfStream._decompressData (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:193:27)
E/flutter (16117): #5      PdfStream.getDecompressedData (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:151:30)
E/flutter (16117): #6      PdfPageLayerCollectionHelper._combineProcess (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:189:35)
E/flutter (16117): #7      PdfPageLayerCollectionHelper._combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:167:22)
E/flutter (16117): #8      PdfPageLayerCollectionHelper.combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:104:12)
E/flutter (16117): #9      PdfTextExtractor._getRecordCollection (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:925:14)
E/flutter (16117): #10     PdfTextExtractor._getText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:290:51)
E/flutter (16117): #11     PdfTextExtractor._extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:193:14)
E/flutter (16117): #12     PdfTextExtractor.extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:109:12)
E/flutter (16117): #13     _extractText.<anonymous closure> (package:syncfusion_flutter_pdfviewer/src/text_extraction/text_extraction.dart:59:27)
E/flutter (16117): #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (16117): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)

### Steps to reproduce

I have edited the and existing pdf using Pdfdocument library where i have used two methods 

1. drawString method 
        /// inserting the user name on the last page of the pdf document
         page.graphics.drawString(userNmaeController.text.trim(),
          PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 200, 100, 20));

/// inserting the date time at the last page 
page.graphics.drawString(
          dateTime, PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 150, 100, 20));

Using this method I am drawing a string on the last page of the pdf document, this does not give me any issue works perfectly 

2. after that i update again the last page with inserting the user signature 
/// inserting user signature
  page.graphics.drawImage(image,
          Rect.fromLTWH(pageSize.width - 200, pageSize.height - 250, 100, 20));

3. after that i upload the pdf to aws 

4. from the aws url i try to open pdf using  SfPdfViewer.network(
              pdfUrl,
            ), it is giving me the above error 

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

   page.graphics.drawString(userNmaeController.text.trim(),
          PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 200, 100, 20));

      page.graphics.drawString(
          dateTime, PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 150, 100, 20));

  File(path).writeAsBytesSync(await pdfDocument.save());

 final pageSize = page.getClientSize();
      final PdfBitmap image = PdfBitmap(imageSignature);
      page.graphics.drawImage(image,
          Rect.fromLTWH(pageSize.width - 200, pageSize.height - 250, 100, 20));

  File(path).writeAsBytesSync(await pdfDocument.save());

      pdfDocument.dispose();

/// Error loading pdf 
 SfPdfViewer.network(
              pdfUrl,
           
            ),

link to pdf ====== "https://gatedcaribbean.s3.amazonaws.com/documents/1723098805473_.pdf" 
</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

E/flutter (16117): [ERROR:flutter/runtime/dart_isolate.cc(1291)] Unhandled exception:
E/flutter (16117): Invalid argument (Header of the stream can not be read.): -1
E/flutter (16117): #0      CompressedStreamReader._readZlibHeader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:220:7)
E/flutter (16117): #1      CompressedStreamReader._initialize (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:212:7)
E/flutter (16117): #2      new CompressedStreamReader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:12:5)
E/flutter (16117): #3      PdfZlibCompressor.decompress (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/pdf_zlib_compressor.dart:22:43)
E/flutter (16117): #4      PdfStream._decompressData (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:193:27)
E/flutter (16117): #5      PdfStream.getDecompressedData (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:151:30)
E/flutter (16117): #6      PdfPageLayerCollectionHelper._combineProcess (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:189:35)
E/flutter (16117): #7      PdfPageLayerCollectionHelper._combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:167:22)
E/flutter (16117): #8      PdfPageLayerCollectionHelper.combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:104:12)
E/flutter (16117): #9      PdfTextExtractor._getRecordCollection (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:925:14)
E/flutter (16117): #10     PdfTextExtractor._getText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:290:51)
E/flutter (16117): #11     PdfTextExtractor._extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:193:14)
E/flutter (16117): #12     PdfTextExtractor.extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:109:12)
E/flutter (16117): #13     _extractText.<anonymous closure> (package:syncfusion_flutter_pdfviewer/src/text_extraction/text_extraction.dart:59:27)
E/flutter (16117): #14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)

</details>

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.3.1 23D60 darwin-arm64,
    locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version
    35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!

</details>

**Comment by immankumarsync** [comment]
@Ak-sws, we are able to replicate the issue as the provided stack trace. Currently, we are validating the cause of the issue, we will update the details once the validation is completed.

Regarding the rendering issue, we have checked this in Adobe Reader, and the signature, name, and date are also not present there. Please find the screenshot below.
![image](https://github.com/user-attachments/assets/9656bf8c-ac7f-4c6e-af0b-a536f558afd1)

**Comment by Ak-sws** [comment]
is there any update on this issue....

**Comment by immankumarsync** [comment]
@Ak-sws, could you please share the unmodified PDF document, so that we can replicate the issue on our end?

**Comment by Ak-sws** [comment]
@immankumarsync you can get the document from this link https://gatedcaribbean.s3.amazonaws.com/documents/1722853625919_.pdf

**Comment by immankumarsync** [comment]
Hi @Ak-sws, Thank you for sharing the unmodified document. We tried to replicate the issue, but it is not occurring on our end. Please find attached the sample we used to replicate the issue. We added the name, date, and string separately and then loaded the modified document in the SfPdfViewer. All the elements appeared correctly in the PDF document without any issues.

 
[sample.zip](https://github.com/user-attachments/files/16634013/sample.zip)

**Comment by Ak-sws** [comment]
Ok thanks @immankumarsync I will check and my end with your sample and my code  if anything comes up I will drop the comment

**Comment by Ak-sws** [comment]
@immankumarsync  Can you verify this code because i tested your sample it is working but when i am doing my way like downloading the pdf it is not working  
/// I am using this to download the file from the url  and after that calling the add all function to insert sign , date and name
Future<void> addSignToPdfDraw(String pdfUrl, String documentId) async {
    try {
      /// check if user has drawn anything using path points
      List<Path> path = keySignaturePad.currentState!.toPathList();

      /// path points are empty meaning user has drwan nothing on the sign pad
      if (path.isEmpty) {
        await DialogHelper.showErrorDialog(
            title: ErrorMessages.error,
            description: ErrorMessages.emptySignature);

        return;
      }

     

      String dir = (await getApplicationDocumentsDirectory()).path;
      DialogHelper.showLoading();
      await FileDownloader.downloadFile(
          url: pdfUrl,
          name: DateTime.now().millisecond.toString(), //(optional)
          subPath: dir, //(optional)

          onProgress: (String? fileName, double progress) {},
          onDownloadCompleted: (String path) async {
            DialogHelper.hideLoading();

            try {
              final image = await keySignaturePad.currentState?.toImage();

              final imageSignature =
                  await image!.toByteData(format: ui.ImageByteFormat.png);

              Uint8List imageData = imageSignature!.buffer.asUint8List();

              _addAll(
                  imageData, path, userNameController.text.trim(), documentId);

              // addAndPlaceSignToPdf(imageData, path, documentId);
            } catch (e) {
              debugPrint("error adding signature to pdf 1 ${e.toString()}");
            }
          },
          onDownloadError: (String error) {
            DialogHelper.hideLoading();
          });
    } catch (e) {
      await DialogHelper.showErrorDialog(
          title: ErrorMessages.error,
          description: ErrorMessages.noImageSelected);
      debugPrint("error adding signature to pdf ${e.toString()}");
    }
  }
  
  /// Add all function to add all other details like sign , name and date 
  
   void _addAll(Uint8List imageSignature, String path, String userName,
      String documentId) async {
    try {
      // PdfDocument document = PdfDocument(inputBytes: _pdfBytes!);

      Uint8List? pdfBytes = File(path).readAsBytesSync();
      PdfDocument document = PdfDocument(inputBytes: pdfBytes);
      final page = document.pages[document.pages.count - 1];
      final pageSize = page.getClientSize();
      // final imageData = await rootBundle.load('assets/signature.png');
      final image = PdfBitmap(imageSignature);

      // Draw name
      page.graphics.drawString(
          userName, PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 200, 100, 20));

      // Draw date
      page.graphics.drawString(DateTime.now().toString(),
          PdfStandardFont(PdfFontFamily.helvetica, 12),
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(
              pageSize.width - 200, pageSize.height - 150, 100, 20));

      // Draw signature
      page.graphics.drawImage(image,
          Rect.fromLTWH(pageSize.width - 200, pageSize.height - 250, 100, 20));

      List<int> save = await document.save();
      document.dispose();

      pdfBytes = Uint8List.fromList(save);
      await Get.to(PdfV(pdfpath: path));
    } catch (e) {
      debugPrint("error signing new ${e.toString()}");
    }
  }

**Comment by immankumarsync** [comment]
@Ak-sws, We have checked your code and it is working fine on our end. Please find the complete sample and the video recording below. In that sample, we have added a signature pad to draw the signature and commented the codes which throws compilation error (mainly the DialogHelper code).

https://github.com/user-attachments/assets/291a923c-add1-4fc8-86b2-012885a0b9bd

[sfpdfviewer_web.zip](https://github.com/user-attachments/files/16691071/sfpdfviewer_web.zip)
