### ISSUE TITLE
scrollable_panel/scrollview_widget Error FocusNode on Flutter Master

### ISSUE THREAD

**Issue by EricPHassey** [syncfusion/flutter-widgets#202]
Getting this error with syncfusion datagrid 

../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-19.1.54-beta/lib/src/control/scrollable_panel/scrollview_widget.dart:45:45: Error: The argument type 'bool Function(FocusNode, RawKeyEvent)' can't be assigned to the parameter type 'KeyEventResult Function(FocusNode, RawKeyEvent)?'.
[   +1 ms]  - 'FocusNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('../../../Software/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
[        ]  - 'RawKeyEvent' is from 'package:flutter/src/services/raw_keyboard.dart' ('../../../Software/flutter/packages/flutter/lib/src/services/raw_keyboard.dart').
[        ]  - 'KeyEventResult' is from 'package:flutter/src/widgets/focus_manager.dart' ('../../../Software/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
[        ]       _dataGridFocusNode = FocusNode(onKey: _handleFocusKeyOperation);

Note: This Error only occurs on Flutter Master using the latest version. on Flutter Dev it appears to work fine.

**Comment by RenugaSadagoban98** [comment]
Hi @EricPHassey ,

Thanks for your update.

Currently, we are analyzing your reported issue in flutter Datagrid. We will validate and update you with the details by tomorrow. We appreciate your patience until then.

Regards,
Renuga devi.

**Comment by RenugaSadagoban98** [comment]
Hi @EricPHassey,

Thanks for your patience.

Since our source is compatible with the stable channel, we will analyze the breaking change and make our source compatible once it is moved to stable.

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi @EricPHassey , 

Thanks for your patience. 

The reported issue “Compilation issue occurred when using master channel” has been resolved and we have included the changes in our weekly pub release. Please update the datagrid package to the 19.1.59-beta version. You can also refer to the following pub link. 

link: https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.1.59-beta
 
Regards,
Renuga devi S
