### ISSUE TITLE
SFDataGrid - Adding a advanced filter programmatically does not show in filter popup options

### ISSUE THREAD

**Issue by litterature** [syncfusion/flutter-widgets#2023]
### Bug description

I stock filter conditions from SFDataGrid in a provider. When I initialize the grid, I add filters previously stocked in the grid with AddFilter(). If I stock an advanced filter (ex: 'greaterThan' and a date value), the filter is correctly applied to the grid, but when I open the popup, inputs are blank (like it had no filter at all).

For the user, it's hard to remember what is the filter currently applied to his grid!

### Steps to reproduce

1. Add an advanced filter programmatically
2. Open filter popup of the filtered column
3. Open the advanced filters et look at the inputs

### Code sample

<details open><summary>Code sample</summary>

```dart
class _GridState<T> extends State<EntityGrid<T>> {
  late _GridDataSource<T> _grid;

  @override
  void initState() {
    super.initState();
    _grid = _GridDataSource();
 
   for(final filter in widget.filters){
     _grid.addFilter(
       column.title,
       filter.toFilterCondition(),
     );
   }
  }

 @override
 Widget build(BuildContext context) {
  return SfDataGrid(
     ...
  );
 }

}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/fbb7bf37-ac3a-47bc-b44a-4d65b233123b)
![image](https://github.com/user-attachments/assets/b0a9e7e8-f4bf-46af-9b72-225102412351)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
no exception/stack trace
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [version 10.0.22631.3880], locale fr-CA)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.7)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.2)
[✓] VS Code (version 1.92.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @litterature ,
 
As of now, DataGrid does not have support to set the filter options when loading in the advanced filter popup menu. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link - [52082](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F52082%2Fsupport-to-set-the-filter-options-when-loading-in-the-advanced-filter-popup-menu&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Ce93810c209a7487b9b3008dcbc30486d%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638592162781031170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=KLbzxqfkFGyJFd5I%2F0Epy8%2FHTI2o4K70oPqRZbtTMVM%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by litterature** [comment]
Ok! Thank you!

**Comment by ashok-kuvaraja** [comment]
Hi @litterature,

We are closing this issue. If we need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K
