### ISSUE TITLE
when to support Tree Grid 

### ISSUE THREAD

**Issue by ctracerpp** [syncfusion/flutter-widgets#2029]
### Use case

some data like :   [{id:1,name:"1",age:"3",children:[]}],for more data quick view and edit .

### Proposal

for some large dataset with children

**Comment by Baranibharathip** [comment]
Hi @ctracerpp,

We would like to let you know that currently we don’t have support for tree grid widget in flutter. However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

Feedback link: https://www.syncfusion.com/feedback/61739/provide-tree-grid-widget-support-in-flutter

Regards,
Baranibharathi P.

**Comment by LavanyaGowtham2021** [comment]
Hi @ctracerpp ,

This is an uncertain feature, so we are closing this ticket. Please follow up with the FR.

Feedback link: https://www.syncfusion.com/feedback/61739/provide-tree-grid-widget-support-in-flutter
