### ISSUE TITLE
Row Mouse Hover Effect Datagrid Flutter Web

### ISSUE THREAD

**Issue by EricPHassey** [syncfusion/flutter-widgets#203]
Using the latest version there is no mouse hover support, however this has been implemented in your packages for other languages.

Please add this support into the Flutter version as shown in the article below:

https://www.syncfusion.com/kb/11816/how-to-apply-the-row-mouse-hover-effect-in-wpf-datagrid-sfdatagrid

**Comment by RenugaSadagoban98** [comment]
Hi @EricPHassey ,

Greetings from syncfusion.

We have already logged the feature request for “Hovering effect for row in Datagrid”. This feature will be implemented in the 2021 Volume 2 release which is expected to be rolled out on mid of July 2021. You can refer to the below feedback link for further follow up,

Feedback link: https://www.syncfusion.com/feedback/22894/support-to-highlight-the-rows-when-hovering-on-it-in-web

We appreciate your patience until then. For further assistance, you can follow the feature request.

Regards,
Renuga devi S
