### ISSUE TITLE
Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.

### ISSUE THREAD

**Issue by Manfred2023** [syncfusion/flutter-widgets#2030]
### Bug description

when i want to use  syncfusion_flutter_calendar: ^26.2.10 in my existing project, i also have this error The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard
i have already upgrade my flutter version and all my other depandance but they don't run

### Steps to reproduce

1. when a download syncfusion_flutter_calendar in my existing project
2. when i want to call SfCalendar like widget 
3. am using  sdk: '>=3.2.6 <4.0.0'
4. and gradlle 8.5

### Code sample

that's exemple i found in flutter package page
class _AgendaViewState extends State<AgendaView> {
  final GlobalKey _mapKey = GlobalKey();
  late YandexMapController controllerYandex;

  bool locationPermissionGranted = false;
  Offset? widgetPosition;
  @override
  Widget build(BuildContext context) {
    double devicePixelRatio = MediaQuery.of(context).devicePixelRatio;

    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          SfCalendar(
            view: CalendarView.month,
            dataSource: MeetingDataSource(_getDataSource()),
            // by default the month appointment display mode set as Indicator, we can
            // change the display mode as appointment using the appointment display
            // mode property
            monthViewSettings: const MonthViewSettings(
                appointmentDisplayMode:
                    MonthAppointmentDisplayMode.appointment),
          )
        ],
      ),
    );
  }

  List<Meeting> _getDataSource() {
    final List<Meeting> meetings = <Meeting>[];
    final DateTime today = DateTime.now();
    final DateTime startTime = DateTime(today.year, today.month, today.day, 9);
    final DateTime endTime = startTime.add(const Duration(hours: 2));
    meetings.add(Meeting(
        'Conference', startTime, endTime, const Color(0xFF0F8644), false));
    return meetings;
  }
}

class MeetingDataSource extends CalendarDataSource {
  /// Creates a meeting data source, which used to set the appointment
  /// collection to the calendar
  MeetingDataSource(List<Meeting> source) {
    appointments = source;
  }

  @override
  DateTime getStartTime(int index) {
    return _getMeetingData(index).from;
  }

  @override
  DateTime getEndTime(int index) {
    return _getMeetingData(index).to;
  }

  @override
  String getSubject(int index) {
    return _getMeetingData(index).eventName;
  }

  @override
  Color getColor(int index) {
    return _getMeetingData(index).background;
  }

  @override
  bool isAllDay(int index) {
    return _getMeetingData(index).isAllDay;
  }

  Meeting _getMeetingData(int index) {
    final dynamic meeting = appointments![index];
    late final Meeting meetingData;
    if (meeting is Meeting) {
      meetingData = meeting;
    }

    return meetingData;
  }
}

class Meeting {
  /// Creates a meeting class with required details.
  Meeting(this.eventName, this.from, this.to, this.background, this.isAllDay);

  /// Event name which is equivalent to subject property of [Appointment].
  String eventName;

  /// From which is equivalent to start time property of [Appointment].
  DateTime from;

  /// To which is equivalent to end time property of [Appointment].
  DateTime to;

  /// Background which is equivalent to color property of [Appointment].
  Color background;

  /// IsAllDay which is equivalent to isAllDay property of [Appointment].
  bool isAllDay;
}

### Screenshots or Video

i don't have

### Stack Traces

[        ] ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-26.2.10/lib/src/theme/theme_widget.dart:148:47: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
[        ]  - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../tools/flutter%20m1&m2/flutter/packages/flutter/lib/src/material/color_scheme.dart').
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'surfaceContainerHighest'.
[        ]         surfaceVariant: themeData.colorScheme.surfaceContainerHighest,
[        ]                                               ^^^^^^^^^^^^^^^^^^^^^^^
[+6979 ms] [+37049 ms] ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_calendar-26.2.10/lib/src/calendar/common/calendar_view_helper.dart:753:35: Error: The getter 'isAltPressed' isn't defined for the class 'HardwareKeyboard'.
[  +44 ms] [  +47 ms]  - 'HardwareKeyboard' is from 'package:flutter/src/services/hardware_keyboard.dart' ('../../tools/flutter%20m1&m2/flutter/packages/flutter/lib/src/services/hardware_keyboard.dart').
[        ] [        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAltPressed'.
[        ] [        ]     if (HardwareKeyboard.instance.isAltPressed) {
[        ] [        ]  

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.24.0, on macOS 14.0 23A344 darwin-arm64, locale en-US)
    • Flutter version 3.24.0 on channel stable at /Users/woupo/Documents/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (3 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/woupo/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.87.2)
    • VS Code at /Users/woupo/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.91.1)
    • VS Code at /Users/woupo/Downloads/Visual Studio Code 2.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (6 available)
    • SM A315F (mobile)                    • RF8N71KDYRL                          • android-arm64  • Android 12 (API 31)
    • Android SDK built for arm64 (mobile) • emulator-5554                        • android-arm64  • Android 10 (API 29) (emulator)
    • iPhone 12 (mobile)                   • BF1516D7-1ACD-4AC5-82FE-3691C0B941A4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • macOS (desktop)                      • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Mac Designed for iPad (desktop)      • mac-designed-for-ipad                • darwin         • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)                         • chrome                               • web-javascript • Google Chrome 127.0.6533.120

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
