### ISSUE TITLE
Start editing when coming from another control

### ISSUE THREAD

**Issue by JuanLuisNL** [syncfusion/flutter-widgets#2031]
### Use case

In a Windows form I want to be able to start editing the grid when coming from another control by pressing TAB or ENTER.

### Proposal

![image](https://github.com/user-attachments/assets/abbc59f3-3d06-49e5-b295-e42e1fb331d7)
I would like an event that is triggered when the grid receives the focus via keyboard.
We used to work in NET and we are used to use grids like this, maybe there is a way to do it, but I have tried many things and I have not been able to do it.

**Comment by abineshPalanisamy** [comment]
Hi @JuanLuisNL ,
 
You can modify the **Tab or Enter** key behavior by using the [handleKeyEvent](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FRowSelectionManager%2FhandleKeyEvent.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C686d4cb53da4453e500408dcc1a49095%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638598159744224261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Zo9bqyI6iWllAsSIg2LyBS4qVQsZqlYY6EgatYI%2Fcy0%3D&reserved=0) method within the [RowSelectionManager](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FRowSelectionManager-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C686d4cb53da4453e500408dcc1a49095%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638598159744234372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Pz2l5VFcZRGQfAmNH%2F1BeeaQpbN4yrtpMe5QCnAv5P0%3D&reserved=0). Inside handleKeyEvent(), check if the Tab or Enter key is pressed. Based on the current cell's **rowColumnIndex**, you can then initiate cell editing. Additionally, wrap the DataGrid in a [Focus](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fwidgets%2FFocus-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C686d4cb53da4453e500408dcc1a49095%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638598159744242394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=c4pNyUa2Ofy6kGFpIFu5OlL6tSVKY5L4002Jr90m4ow%3D&reserved=0) widget. When the focus is removed from the DataGrid, clear the selection to ensure the DataGrid loses focus.
 
We have included a sample for your reference. Please review this sample for more details and adapt it to suit your specific requirements.

- **Sample:** [SfDataGrid.zip](https://github.com/user-attachments/files/16686495/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by JuanLuisNL** [comment]
Thank you very much for your quick response.
I am doing everything you have told me.
In your code when I write this, it works:
    focusText.addListener(() {
      if (!focusText.hasFocus) {
        WidgetsBinding.instance.addPostFrameCallback((_) async {
          await controller.beginEdit(RowColumnIndex(0, 1));
        });
      }
    });
Exiting the control with TAB puts the grid into edit mode.

In my code it doesn't work if I press TAB. However, it does work if, for example, from a button or from the ‘change’ of the TextEdit I call :          
await controller.beginEdit(RowColumnIndex(0, 1));

I will continue investigating, I know it is a problem of my code.
Thank you very much.
Regards,
Juan Luis Marcos

**Comment by JuanLuisNL** [comment]
He visto que cuando llamo a "beginEdit" desde el cambio de foco, en la siguien funcion, dataGridConfiguration.columns._actualWidth es igual NaN, por eso no encuentra ninguna columna. Sin embargo si hago click en la celda o llamo a  "beginEdit" desde un boton, tiene el valor correcto:

![image](https://github.com/user-attachments/assets/27208b08-c551-4d8c-8a4f-96d717bcd289)

**Comment by abineshPalanisamy** [comment]
Hi @JuanLuisNL ,
 
We are unclear about the issue based on the information provided. To assist you further and gain a better understanding of the problem, we kindly request additional details or steps related to calling beginEdit and reproducing the unexpected behavior. Please modify the previously attached sample to demonstrate the issue and provide a video recording that shows the problem for greater clarity. This will significantly aid us in investigating the issue and offering a prompt and appropriate solution.
 
Regards,
Abinesh P

**Comment by JuanLuisNL** [comment]
Hello
First of all, thank you for your attention.
The conclusion I have come to is that in the example you have provided it works because the widget is painted twice. The first time ‘dataGridConfiguration.columns._actualWidth’ is equal to NaN , the second time it already acquires the value of ‘width’, so the function getLastCellIndex can return a value and ‘beginEdit’ can continue. 
beginEdit > dataGridConfiguration.currentCell.onCellBeginEdit > getLastCellIndex (this function returns and does not continue if _actualWidth in NaN)

Sorry for not explaining well, I don't know how to reproduce it in a simple example, as I have my custom widgets with a lot of code.

I'll keep investigating.

Thanks for your help!


Translated with DeepL.com (free version)

**Comment by abineshPalanisamy** [comment]
Hi @JuanLuisNL ,
 
We are glad to know that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help.
 
Regards,
Abinesh P

**Comment by JuanLuisNL** [comment]
Thank you very much!
