### ISSUE TITLE
Inquiry About Disabling Move Action in SfCartesianChart

### ISSUE THREAD

**Issue by Dao-Van-Thanh** [syncfusion/flutter-widgets#2033]
Dear Syncfusion Team,

I hope this message finds you well.

I am currently working with the SfCartesianChart in the Syncfusion Flutter Charts library and would like to disable the move action (onChartTouchInteractionMove) entirely. I have explored the available configurations and found options to manage zoom and pan behavior, but I am specifically looking for a way to prevent users from moving the chart entirely.

Could you please provide guidance or recommend a solution for disabling the move action in SfCartesianChart?

Thank you in advance for your assistance.

Best regards,
Dao Van Thanh

**Comment by ThilipChandru** [comment]
Hi @Dao-Van-Thanh,

We have analyzed your requirement at our end, and currently, we don't have direct support for disabling the [onChartTouchInteractionMove ](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onChartTouchInteractionMove.html) in entire charts. However, the onChartTouchInteractionMove can be disabled for some interactive features with some restrictions. Can you please share your exact requirement with more details, It will be helpful for sharing the solution as soon as possible.

 
Regards,
S Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.
