### ISSUE TITLE
Syncfusion Flutter Pdfviewer Linux Support

### ISSUE THREAD

**Issue by tom-ludwig** [syncfusion/flutter-widgets#2035]
### Use case

It would be great to use this amazing PDF viewer on Linux as well.
It's probably not as easy as it sounds, hence the question if there is another similar pdf viewer for linux?

### Proposal

n.a

**Comment by immankumarsync** [comment]
@activcoding,
At present, we do not have support to render on the Linux platform. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters, including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
Please follow the feedback link to track the status of the feature,
[Linux support for Flutter SfPdfViewer](https://www.syncfusion.com/feedback/31376/linux-support-for-flutter-sfpdfviewer)

**Comment by LavanyaGowtham2021** [comment]
Hi @tom-ludwig ,

This is an uncertain feature, so we are closing this ticket. Please follow up with the FR.

FR: [Linux support for Flutter SfPdfViewer](https://www.syncfusion.com/feedback/31376/linux-support-for-flutter-sfpdfviewer)
