### ISSUE TITLE
How to customize label Style in SfSlider

### ISSUE THREAD

**Issue by ankii9600** [syncfusion/flutter-widgets#204]

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,

Greetings from Syncfusion support.

You can customize the labels of the SfSlider using the SfSliderThemeData.activeLabelStyle and SfSliderThemeData.inactiveLabelStyle properties. Kindly refer the below link for more details.

**Link:** https://help.syncfusion.com/flutter/slider/labels-and-divisor#label-style 

**Code snippet:** 
@override
Widget build(BuildContext context) {
   return MaterialApp(
     home: Scaffold(
       body: Center(
         child: SfSliderTheme(
           data: SfSliderThemeData(
             activeLabelStyle: TextStyle(
                 color: Colors.red, fontSize: 12, fontStyle: FontStyle.italic),
             inactiveLabelStyle: TextStyle(
                 color: Colors.red[200],
                 fontSize: 12,
                 fontStyle: FontStyle.italic),
           ),
           child: SfSlider(
             min: _min,
             max: _max,
             value: _value,
             interval: 20,
             showLabels: true,
             onChanged: (dynamic newValue) {
               setState(() {
                 _value = newValue;
               });
             },
           ),
         ),
       ),
     ),
   );
 }

Kindly let us know if you need further assistance on this.

Regards,
Lakshmi R.
