### ISSUE TITLE
Solution SfCartesianChart

### ISSUE THREAD

**Issue by Ander0106** [syncfusion/flutter-widgets#2040]
### Use case

this error is frecuentily en 3.24, but solution was this, read this report in the link
https://stackoverflow.com/questions/78882125/how-to-solve-the-issue-of-renderobject-markneedsbuild-not-present-in-flutter

### Proposal

https://stackoverflow.com/questions/78882125/how-to-solve-the-issue-of-renderobject-markneedsbuild-not-present-in-flutter

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need further assistance on this.
