### ISSUE TITLE
[SfCharts] Build error when running with Flutter 3.24.1

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#2041]
### Bug description

I am getting an error when trying to run my app with flutter 3.24.1 and fvm.

I am using charts version ^26.2.11. 

I tried flutter clean but that didn't solve the issue.

### Steps to reproduce

Install 3.24.1 via fvm.
Install syncfusion_flutter_charts: ^26.2.11
Run the project

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1244" alt="Bildschirmfoto 2024-08-28 um 14 45 50" src="https://github.com/user-attachments/assets/3adf0aa0-cd99-4344-a155-93145d101cdb">

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/macos-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.92.2)
```

</details>

**Comment by GalimzyanovDanil** [comment]
We have same issue. Please resolve it)

**Comment by Ramzes5614** [comment]
The same problem

**Comment by Macacoazul01** [comment]
@ThilipChandru do you have any updates on this issue?
We're waiting to change our app to flutter 3.24.0 because of syncfusion libraries.

**Comment by ThilipChandru** [comment]
Hi all,


Thank you for your patience. We have upgraded our Flutter Charts package to be compatible with Flutter SDK 3.24.0. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.

Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
