### ISSUE TITLE
Table with pagination does not export all data

### ISSUE THREAD

**Issue by CGrandez** [syncfusion/flutter-widgets#2044]
### Use case

There is no possibility of exporting the entire table, it only exports the current view of the table.

`Future<void> exportDataGridToExcel(GlobalKey<SfDataGridState> dataGridKey) async {
    final Workbook workbook = Workbook();
    final Worksheet worksheet = workbook.worksheets[0];
    dataGridKey.currentState!.exportToExcelWorksheet(worksheet, startColumnIndex: 1, startRowIndex: 3);
    final List<int> bytes = workbook.saveAsStream();
     await helper.FileSaveHelper.saveAndLaunchFile(bytes, 'titulo.xlsx');
     workbook.dispose();
}`

### Proposal

I propose to give the option to choose whether to export all the data or only the current view.

**Comment by abineshPalanisamy** [comment]
Hi @CGrandez ,
 
Please refer to the following Knowledge Base link for a deeper understanding of how to export all rows while having pagination in a Flutter DataTable. You can customize the provided code to suit your specific requirements.

KB link: [Export rows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.syncfusion.com%2Fkb%2Farticle%2F15891%2Fhow-to-export-all-rows-while-having-pagination-in-a-flutter-datatable&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C8c4144691d73496b756008dcc8b1f011%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638605913770897938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BDORYwowsm7URrXa8D%2FgAyGcUvC2DEbRsb%2F1DHrBCvk%3D&reserved=0)
 
Regards,
Abinesh P
