### ISSUE TITLE
[syncfusion_flutter_calendar] no option to disable cell border on hover on web

### ISSUE THREAD

**Issue by Altereyo** [syncfusion/flutter-widgets#2046]
### Bug description

When launching syncfusion_flutter_calendar on web, and hovering any cell, there is square border around cell. Didn't found option to disable it. cellBuilder doesn't fit to full cell decoration, only to inner widget

### Steps to reproduce

1. Run default SfCalendar on web
2. Hover any element

### Code sample

<details open><summary>Code sample</summary>

```dart
SfCalendar(
  view: CalendarView.month,
)
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

Default calendar:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/2a2f5cdd-7bac-4d23-a9eb-9a4a11a04a9c">

My calendar that needs to disable this border:
<img width="461" alt="image" src="https://github.com/user-attachments/assets/632f1c9a-fb18-4155-a2fd-4b79f0db9a25">

</details>

### Stack Traces

.

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by ThilipChandru** [comment]
Hi @Altereyo,

To disable the border color for hovered cell in SfCalendar, we recommend you to use [SfCalendarTheme](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfCalendarThemeData-class.html), where you can set [SelectionBorderColor](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfCalendarThemeData/selectionBorderColor.html) to transparent.

UG link : https://help.syncfusion.com/flutter/themes

Code snippet: 

```
child: SfCalendarTheme(
         data: SfCalendarThemeData(selectionBorderColor: Colors.transparent),
         child: SfCalendar(
           view: CalendarView.month,
         ),
     ),
```

Regards,
S Thilip Chandru.

**Comment by Altereyo** [comment]
Hi, @ThilipChandru

Transparent color draws grey border, but white color fits as well.
Thanks for your answer, this solves my issue!
