### ISSUE TITLE
ColumnSeries chart's column very small in size

### ISSUE THREAD

**Issue by AndreLiu1225** [syncfusion/flutter-widgets#2047]
### Bug description

For a certain set of data, the columns in the ColumnSeries are very small in size and cannot be made sufficiently bigger using the properties width and height.

### Steps to reproduce

Unable to replicate this issue as data is fetched from firebase at the moment

### Code sample

**Snippet of data being displayed**
{date: 2008-01-27, val: 797645000}, {date: 2008-07-27, val: 55876000}, {date: 2008-07-27, val: -120929000}, {date: 2008-10-26, val: 117624000}, {date: 2008-10-26, val: 61748000}, {date: 2009-01-25, val: -30041000}, {date: 2009-01-25, val: -30041000}, {date: 2009-04-26, val: -201338000}, {date: 2009-04-26, val: -201338000}, {date: 2009-07-26, val: -306640000}, {date: 2009-07-26, val: -306640000}, {date: 2009-07-26, val: -105302000}, {date: 2009-07-26, val: -105302000}, {date: 2009-07-26, val: -105302000}, {date: 2009-10-25, val: -199063000}, {date: 2009-10-25, val: -199063000}, {date: 2009-10-25, val: 107577000}, {date: 2009-10-25, val: 107577000}, {date: 2009-10-25, val: 107577000}, {date: 2010-01-31, val: -67987000}, {date: 2010-01-31, val: -67987000}, {date: 2010-01-31, val: -67987000}, {date: 2010-01-31, val: 131076000}, {date: 2010-05-02, val: 137594000},.........

The date starts in 2008 and ends in 2024

`SfCartesianChart(
                                        tooltipBehavior: tooltip,
                                        zoomPanBehavior: zoomPanBehavior,
                                        trackballBehavior: trackballBehavior,
                                        legend: const Legend(isVisible: true),
                                        primaryXAxis: DateTimeAxis(
                                            opposedPosition: true,
                                            enableAutoIntervalOnZooming: true,
                                            minimum: financialMinimumX,
                                            maximum: financialMaximumX,
                                            majorGridLines:
                                                const MajorGridLines(width: 0),
                                            majorTickLines:
                                                const MajorTickLines(width: 0),
                                            intervalType:
                                                DateTimeIntervalType.auto,
                                            dateFormat: DateFormat("MMM y"),
                                            labelStyle: GoogleFonts.poppins(
                                                fontSize: 11,
                                                fontWeight: FontWeight.bold)),
                                        primaryYAxis: NumericAxis(
                                            opposedPosition: true,
                                            enableAutoIntervalOnZooming: true,
                                            majorGridLines:
                                                const MajorGridLines(width: 0),
                                            majorTickLines:
                                                const MajorTickLines(width: 0),
                                            numberFormat:
                                                NumberFormat.compactCurrency(),
                                            labelStyle: GoogleFonts.poppins(
                                                fontSize: 11,
                                                fontWeight: FontWeight.bold)),
                                        series: <CartesianSeries>[
                                          ColumnSeries<CompanyFactGraph,
                                              DateTime>(
                                            name: companyFactGraphPoints
                                                .first.companyFact,
                                            color: const Color(0xffbf77f6),
                                            pointColorMapper:
                                                (CompanyFactGraph data, _) {
                                              if (data.value < 0) {
                                                return const Color(0xfffa2a55);
                                              } else {
                                                return const Color(0xff32cd32);
                                              }
                                            },
                                            dataSource: companyFactGraphPoints,
                                            xValueMapper:
                                                (CompanyFactGraph data, _) =>
                                                    data.date,
                                            yValueMapper:
                                                (CompanyFactGraph data, _) =>
                                                    data.value,
                                          ),
                                        ]),`

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

No errors reported

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-SG)
    • Flutter version 3.22.2 on channel stable at /Users/liuis/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (3 months ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/liuis/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)            
    • iPhone (63) (mobile)            • 00008120-000845A93CE8201E            • ios            • iOS 17.0.2 21A350
    • iPhone 15 Pro Max (mobile)      • 74ADEC2C-7C3D-413C-AC67-87FE58C249D9 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-4 (simulator)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 128.0.6613.113

[✓] Network resources
    • All expected network resources are available.```

</details>

**Comment by ThilipChandru** [comment]
Hi @AndreLiu1225 ,


The column segment width is determined by the axis range, the number of data points, and the column series' spacing and width properties. When there is a large set of data, the width of each column decreases. To maintain a desired column width, you can use one of the following solutions:
1.	**AutoScrollingDelta**: You can set the initial visible range of the axis using the [AutoScrollingDelta](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/autoScrollingDelta.html) value. If [autoScrollingMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/AutoScrollingMode.html)  is set to AutoScrollingMode.start, the first 5 points will be displayed, and the remaining data points can be viewed by panning the chart from right to left. Additionally, enable ZoomPanBehavior with enablePanning set to true to allow chart panning.
2.	**Initial Visible Range**: You can specify [initialVisibleMinimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/initialVisibleMinimum.html) and [initialVisibleMaximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/initialVisibleMaximum.html) properties on the axis to set the desired visible range when the chart loads. With panning enabled, you can navigate to the actual minimum range. For more details, refer the following user guide documentation:
 
UG link :  
1.	AutoScrollingDelta : [Axis customization in Flutter Cartesian Charts | Syncfusion](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#autoscrollingmode)
2.	InitialVisibleRange : [Initial visibile range in Flutter Cartesian Charts | Syncfusion](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#initial-visible-minimum)

Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Please let us know if you need further assistance on this.
