### ISSUE TITLE
[DataGrid] option to add Footer

### ISSUE THREAD

**Issue by qbait** [syncfusion/flutter-widgets#205]
I need the possibility to add Footer to Grid. I guess that's the common use case. Could you add this option, guys?

**Comment by RenugaSadagoban98** [comment]
Hi @qbait , 

Greetings from syncfusion. 

We are not clear with your requirement. Can you please provide the following requested details? 

•	Do you want to display the sticky footer for datagrid or do you want to last few rows to be sticky? If yes, we have provided the footerFrozenRowsCount property. This will enable you to freeze some rows at bottom.
**Footer frozen rows**
 
 
![image](https://user-images.githubusercontent.com/77044081/116525155-dc375600-a8f5-11eb-872d-9391ee0d54b0.png)

**Unbound sticky footer**
                      
![image](https://user-images.githubusercontent.com/77044081/116525126-d477b180-a8f5-11eb-8592-b7eced23be29.png)

 
•	Did you want to display the summary information at bottom(footer) like the following image? 
 

![image](https://user-images.githubusercontent.com/77044081/116525077-c9bd1c80-a8f5-11eb-972a-abc3558b18e8.png)

Please provide the above details, It will be helpful for us to check on it and provide you the solution at the earliest.  


Regards,
Renuga devi S

**Comment by qbait** [comment]
I don't want to add a sticky footer.
I would like to have the possibility to add a footer that is visible after scrolling to the bottom of the grid.

Best,
Jakub

**Comment by RenugaSadagoban98** [comment]
Hi @qbait ,

We regard for inconvenient.

Based on the provided information, we couldn’t understand your requirement clearly. So please provide more details about your footer query or provide any use case with a footer. It will help us to understand your requirement clearly and provide prompt solution at earliest.

Regards,
Renuga devi S

**Comment by qbait** [comment]
Here is my use case
<img width="319" alt="Screenshot 2021-05-03 at 19 14 20" src="https://user-images.githubusercontent.com/2264901/116909358-63613280-ac44-11eb-8f9d-890afa64b5d6.png">

It should work like a regular footer, after scrolling to the end of the grid or having no results, it should be the last row.

I see that more people need that kind of functionality https://github.com/syncfusion/flutter-widgets/issues/84

**Comment by RenugaSadagoban98** [comment]
Hi @qbait , 

Thanks for your update.
 
We have analyzed your requirement. Please clarify the following details, 
 
•	SfDataGrid does have support to load the data lazily i.e load more rows to the datagrid when vertical scrolling is reached at the bottom of datagrid. Please refer to the following ug document link, 
**UG link**:  https://help.syncfusion.com/flutter/datagrid/load-more#load-more-button 
 
**Screenshot** 
 
![image](https://user-images.githubusercontent.com/77044081/117000084-29546700-acfe-11eb-9e90-207e5af5cb45.png)

  
 
•	Also, we are analyzing the possibility to provide the support to show the widget when the datagrid has empty rows. We will get back to you on May 6th, 2021.

We appreciate your patience until then. 

Regards,
Renuga devi S

**Comment by qbait** [comment]
@RenugaSadagoban98 workaround using `loadMoreViewBuilder` doesn't work.

I've added to my `SfDataGrid`
```
        loadMoreViewBuilder: (BuildContext context, LoadMoreRows loadMoreRows) {
          return FutureBuilder<String>(
            builder: (context, snapShot) {
              return Container(
                height: 64,
                alignment: Alignment.center,
                padding: EdgeInsets.all(12),
                color: AppColors.white,
                child: Text('Sample Footer'),
              );
            },
          );
        },
```

However, there are 2 major issues with it:
1. it hides my last row
![2021-05-04 18 28 05](https://user-images.githubusercontent.com/2264901/117037225-85bb8480-ad06-11eb-9fe9-5a5e886f1d2c.gif)

2. it doesn't work when filtering grid, possibly because the keyboard is visible or scroll is not there
![2021-05-04 18 27 32](https://user-images.githubusercontent.com/2264901/117037122-6e7c9700-ad06-11eb-8027-2b69be4ddc2d.gif)

Footer seems to be a pretty common use case, why you are trying to avoid implementing it?

**Comment by RenugaSadagoban98** [comment]
Hi @qbait ,

Thanks for your update.

Currently, we are analyzing your requirement. We will validate and update you with the details by tomorrow. We appreciate your patience until then.

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi  @qbait ,  
Thanks for your patience. 
 
We have considered your requirement as a feature. We will provide the support to show the additional row (footer view) at the bottom i.e. after the last row. So, you can view this footer when you scroll down to the last row. Also if you have fewer rows in views, the footer row will be shown after the last row.

Also, we will provide the option to customize the height of the footer view.
Can you please confirm that the above behaviors will satisfy your requirement?

Regards,
Renuga devi S

**Comment by qbait** [comment]
Yes, sounds great!
BTW analogical option for the header would be welcome as well :)

**Comment by RenugaSadagoban98** [comment]
Hi @qbait, 

We are not clear about your requirement with an analogical option for the header. Please provide more details about your requirement. It will be helpful for us to provide a prompt solution at the earliest.  

Regards,
Renuga devi S

**Comment by qbait** [comment]
@RenugaSadagoban98 it was just a suggestion, feel free to carry on only with the footer if you don't find the header useful.

**Comment by RenugaSadagoban98** [comment]
Hi @qbait , 
Thanks for your update. 

In our previous update, we have requested more details about your requirement. If you could provide more details about your requirement in the header, we will look onto that and provide you the details.
However, as we promised earlier, we have considered your request as a feature. This feature will be implemented in our any of our upcoming release. 

Please refer to the below feedback link for further follow up, 
Feedback link: https://www.syncfusion.com/feedback/25060/support-to-show-footer-view-at-bottom-of-the-datagrid 

We appreciate your patience until then. For further assistance, you can follow the feature request. 

Regards,
Renuga devi S
