### ISSUE TITLE
The method 'markNeedsBuild' isn't defined for the class 

### ISSUE THREAD

**Issue by saprahits** [syncfusion/flutter-widgets#2050]
### Bug description

Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           114.6s
Failed to build iOS app
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.11/lib/src/charts/cartesian_chart.dart:1367:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.

### Steps to reproduce

```
flutter clean
flutter pub get
flutter build ios
flutter run
```

### Code sample

<details open><summary>Code sample</summary>

```dart
syncfusion_flutter_charts: ^26.2.11
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1692" alt="Screenshot 2024-09-02 at 12 18 13 PM" src="https://github.com/user-attachments/assets/e03a2813-6fd8-4b85-8e43-c21b23cd7776">

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```
flutter clean
flutter pub get
flutter build ios
flutter run
```

</details>

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
hiteshsapra@Hiteshs-MacBook-Pro mobileapp % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by postboxat18** [comment]
![image](https://github.com/user-attachments/assets/caa10b76-8278-4412-a323-b6ed48a4b3c2)

Remember the following text: 

Go to 'flutter/packages/flutter/lib/src/widgets/layout_builder.dart' and add:
`void markNeedsBuild() {
    markNeedsLayout();
  }`

 in the 'mixin RenderConstrainedLayoutBuilder' class.

Temporarily resolve problems.

**Comment by Prathap-Aosta** [comment]
> ![image](https://private-user-images.githubusercontent.com/77087523/363664760-caa10b76-8278-4412-a323-b6ed48a4b3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzYyODMsIm5iZiI6MTcyNTI3NTk4MywicGF0aCI6Ii83NzA4NzUyMy8zNjM2NjQ3NjAtY2FhMTBiNzYtODI3OC00NDEyLWEzMjMtYjZlZDQ4YTRiM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDExMTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZGUzM2FhYmY5MzdhOThlMTViNWI2M2NlMTg5YzFiMTAyNTJkODU2YzkxY2Y4MTFlYzliZjBhYmVmYmI3NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.71t3NGeXpG4HFe42DKyGCm3uxiugibNB4e403ygiKL8)
> 
> Remember the following text:
> 
> Go to 'flutter/packages/flutter/lib/src/widgets/layout_builder.dart' and add: `void markNeedsBuild() { markNeedsLayout(); }`
> 
> in the 'mixin RenderConstrainedLayoutBuilder' class.
> 
> Temporarily resolve problems.

Thank You , it works for me.

**Comment by akmaladib01** [comment]
hi, im having same problem "The method 'markNeedsBuild' isn't defined for the class" but in android. does the step to solve is same with ios? and my flutter sdk is 3.25.0

**Comment by saprahits** [comment]
Yes Not it's woking

**Comment by ThilipChandru** [comment]
Hi all,


Thank you for your patience. We have upgraded our Flutter Charts package to be compatible with Flutter SDK 3.24.0. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.

Regards,
Thilip Chandru.
