### ISSUE TITLE
syncfusion flutter datagrid on Column Resize columns goes invisible

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#2051]
### Bug description

please see the video issue into code is
when i  minimize the column width i cannot able to resize that column

### Steps to reproduce

1- i reduce the width
2- when i want to resize to increase width its not working
3- please see the video

### Code sample

<details open><summary>Code sample</summary>

```dart
[Add your code here]
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/dbb38317-c4b3-4277-91a7-f51e6922a5f6

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Web, Windows

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4842], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.10.4)
[√] Android Studio (version 2023.3)
[√] Connected device (3 available)
[√] Network resources

**Comment by Trung15010802** [comment]
You should specify `minWidth `for Column

**Comment by abineshPalanisamy** [comment]
Hi @abdulrehmananwar ,
 
Based on the provided information, you resized the width of the column to zero, which hides the column. Once a column is hidden, you can't resize it. To prevent a column from being hidden during resizing, use the [GridColumn.minimumWidth](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FGridColumn%2FminimumWidth.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C19d2e71b27094c43172608dcccb22e2e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638610312853740891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ogle1117Da6NrvFIVHKK0biinopPN%2FhsjJlLpt1Ggcc%3D&reserved=0) property to set the column's minimum width. This ensures the column won't be resized below the specified minimum width.

UG Links : [Prevent column from being hidden](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Fcolumns-resizing%23prevent-column-from-being-hidden-on-resizing&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C19d2e71b27094c43172608dcccb22e2e%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638610312853748777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uGrEcOQ%2BgbM2uFTCDKW01XvEUN01a6cH7kDrvGhX9Jc%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @abdulrehmananwar,

We suspect that the reported issue has been resolved on your end using the provided workaround. We are closing this issue now. If you need any further assistance, please reopen this issue. We are always happy to help you.

Regards,
Ashok K
