### ISSUE TITLE
[syncfusion_flutter_calendar] drag&drop with certain time interval as step

### ISSUE THREAD

**Issue by Oleksandr32** [syncfusion/flutter-widgets#2053]
### Use case

I find Drag&Drop with a 1-minute time interval as a step in most cases inconvenient. Could you please implement something like Google Calendar, where the step is, for example, 15 minutes?

<img width="460" alt="Screenshot 2024-09-04 at 16 30 09" src="https://github.com/user-attachments/assets/e280e653-cd7f-476d-8c65-50feef8335bc">

### Proposal

https://github.com/user-attachments/assets/bc55c27c-7470-46b4-9f6c-fe0e3b212aea

**Comment by Oleksandr32** [comment]
or does someone have a solution they would like to share?

**Comment by ThilipChandru** [comment]
Hi @Oleksandr32,

We would like to inform you that we currently do not have support for the **validated feature title**. However, we have already logged a feature request for it in our feedback portal. We will prioritize features for each release based on demand and priority, so this feature may be available in one of our upcoming releases. You can also track the status of the feature with the feedback provided. 

 

Feedback link : [https://www.syncfusion.com/feedback/50620](https://www.syncfusion.com/feedback/50620/improve-the-drag-and-drop-positioning-behavior)

 

If you have any additional specifications or suggestions, for this feature request, please feel free to leave them in the comments section. This will help us understand how you would like to use the feature and how we can improve it.



Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Since it’s an uncertain feature, I am closing this. Please follow up with the FR below.
Feedback link : [https://www.syncfusion.com/feedback/50620](https://www.syncfusion.com/feedback/50620/improve-the-drag-and-drop-positioning-behavior)
