### ISSUE TITLE
change the color of filter popup checkbox color to match app theme.

### ISSUE THREAD

**Issue by louaid** [syncfusion/flutter-widgets#2054]
### Use case

I am trying to change the checkbox color in the filter popup data-grid so it matches the app theme. I am not able to. does the option exist or not?

### Proposal

when I click on filter icon in datagrid table in flutter I see a popop filter with checkboxes that they are different color then my app theme for checkboxes.

**Comment by abineshPalanisamy** [comment]
Hi @louaid ,

As of now, DataGrid does not have support for customizing the appearance of the filter pop-up menu and Checkbox in the filter pop-up menu. We have considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,

Feedback link - [51938](https://www.syncfusion.com/feedback/51938/support-for-customizing-the-appearance-of-the-filter-pop-up-menu) & [49102](https://www.syncfusion.com/feedback/49102/support-for-customizing-the-appearance-of-the-checkbox-in-the-filter-pop-up-menu)

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @louaid,

We are closing this issue now. You can track further updates about the feature through the feedback link. If you need any further assistance, please reopen this ticket. We are always happy to help you.

Regards,
Ashok K
