### ISSUE TITLE
datagrid filtered table with number that shows the number of rows filtered

### ISSUE THREAD

**Issue by louaid** [syncfusion/flutter-widgets#2055]
### Use case

We are trying to show the user how many rows are available in the datagrid table when filtered. I was able to do show number of row in table by datasource.length as a string at the bottom of the table. But the issue is when the user filters the table. The number of rows is not updated.

### Proposal

when user filter the datagrid table in flutter we need to have a value in the footer for example that tells us how many rows are visible after the filter.

**Comment by abineshPalanisamy** [comment]
Hi @louaid ,
 
In SfDataGrid, we can fetch the total row count, even when filtering is applied, by using [DataGridSource.effectiveRows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource%2FeffectiveRows.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C85de64d48c4e42e17ce908dccd6b0c75%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638611106873262782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YA%2BbUIj2F6gofOQkcywfvzmBahpQL0s7%2FpLAejAdLW8%3D&reserved=0). By utilizing [WidgetsBinding.instance.addPostFrameCallback](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapi.flutter.dev%2Fflutter%2Fscheduler%2FSchedulerBinding%2FaddPostFrameCallback.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C85de64d48c4e42e17ce908dccd6b0c75%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638611106873274494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qiERcbixXOuyLSNPuF7cwLbgVxOgsQ2pX23ayvUODF8%3D&reserved=0) in the initState, the row count is updated once the DataGrid has completed its initial build. The [onFilterChanged](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2FonFilterChanged.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C85de64d48c4e42e17ce908dccd6b0c75%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638611106873283439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Z7G6h3RdR9Cg%2FhZDlgyjH4YJqjDlj411IvoVM6uo374%3D&reserved=0) callback is used to update the row count in the UI whenever filtering is applied. The [footer](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2Ffooter.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C85de64d48c4e42e17ce908dccd6b0c75%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638611106873291148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZUJHh69%2Bn5ASLdkRNxslG2XY76lVdUcBAB2KxhoS4S8%3D&reserved=0) of the SfDataGrid can be used to display the total row count, with an additional row that can be displayed under the last row .
 
We have included a sample for your reference. Please review it for more details and adapt it to suit your specific requirements.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/16884392/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @louaid,

We suspect that the reported problem has been resolved at your end. We are closing this issue now. If you need any further help, please reopen this issue. We are always happy to assist you.

Regards,
Ashok K
