### ISSUE TITLE
under sfDataGrid how to concatenate two or more value in single row  

### ISSUE THREAD

**Issue by MukeshWrms** [syncfusion/flutter-widgets#2059]
### Use case

i have need the one column under two or more value show 

country and department 

how can do this  

 DataSourceDepartment({required List<SummaryReport> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(
                  columnName: 'id',
                  value: getReturnSr(employeeData.indexOf(e))),
              DataGridCell<String>(columnName: 'project', value: e.projectName),
              DataGridCell<String>(columnName: 'country', value: e.level1Name),
              DataGridCell<String>(
                  columnName: 'department', value: e.level2Name.toString()),
          
            
            ]))
        .toList();
  }

### Proposal

i have need the one column under two or more value show 

country and department 

how can do this  

 DataSourceDepartment({required List<SummaryReport> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(
                  columnName: 'id',
                  value: getReturnSr(employeeData.indexOf(e))),
              DataGridCell<String>(columnName: 'project', value: e.projectName),
              DataGridCell<String>(columnName: 'country', value: e.level1Name),
              DataGridCell<String>(
                  columnName: 'department', value: e.level2Name.toString()),
          
            
            ]))
        .toList();
  }

**Comment by abineshPalanisamy** [comment]
Hi @MukeshWrms ,
 
You can build DataGrid rows in the DataSource by concatenating two or more values into a single row. In our example, the SfDataGrid widget defines a column named **name_designation**, where the concatenated values of the name and designation fields are displayed. In the DataSource class, the DataGridCell<String> for the name_designation column is created by combining the name and designation fields. The expression **value: '${e.name} - ${e.designation}'** concatenates the name and designation values.
 
We have included a sample for your reference. Please review it for more details and adapt it to suit your specific requirements.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/16927054/SfDataGrid.zip)

Regards,
Abinesh P

**Comment by MukeshWrms** [comment]
this is working but, i have used user image url and name how can do this.

  DataGridCell(
                  columnName: 'asset', value: '${e.assetIconUrl} - ${e.assetName}'),

 // Avatar cell
      if (dataGridCell.columnName == 'asset') {
        if (dataGridCell.value == null) return Container();
        return Row(
          children: [
            Padding(
              padding: const EdgeInsets.only(left: 4.0, right: 4),
              child: Container(
                alignment: Alignment.centerLeft,
                width: 35,
                height: 35,
                child: CustomImageWithType(
                  url: dataGridCell.value.toString(),
                  fit: BoxFit.cover,
                  height: 35,
                  width: 35,
                ),
              ),
            ),
      Text('Income'),
          ],
        );
      }

with image execution given the error 
only image value is working but with concatenates other is not working.

**Comment by abineshPalanisamy** [comment]
Hi @MukeshWrms ,
 
Based on your requirements, we have prepared a sample to concatenate the image and name values. In our example, we use a **Map<String, dynamic>** in the [DataGridCell](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridCell-class.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C3fed02249b454f76fed808dcd171a19f%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638615533184816054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Mmx4ks3j30qV4IbtNNNnC5MpGLY3qWujdsz6Ll7FoQc%3D&reserved=0) to hold both the image and the name. This allows us to store and access these two different types of data together. The column named **image_name** will hold both the image and the name, with the value being a map that contains the image (e.image) and the name (e.name).
 
We have included a sample for your reference. Please review it for more details and adapt it to suit your specific requirements.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/16942303/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by MukeshWrms** [comment]
Thanks its working .
