### ISSUE TITLE
Can customise hijri calendar?

### ISSUE THREAD

**Issue by InShad7** [syncfusion/flutter-widgets#2061]
like the hijri date is rearranged according to the sight seeing of the moon.
so according to that can we able to edit the date or not?

**Comment by KompelliSravanSyncfusion** [comment]
Hi @InShad7,

We have reviewed your query, and we suspect that you are asking about customization support in the Hijri calendar. We have provided customization support for the following features:

- Minimum and maximum date selection
- Customization of the first day of the week
- Month cell customization
- Year cell customization
- Different selection modes
- RTL (Right-to-Left) support
- Customization for special dates

For more detailed information, please refer to our documentation: [Syncfusion Hijri Date Picker Documentation](https://teams.microsoft.com/l/message/19:48b8cfdb0ed942a38083053c55566630@thread.tacv2/1727350879359?tenantId=77f1fe12-b049-4919-8c50-9fb41e5bb63b&groupId=a6892bcf-e609-43b2-a552-b13a634f6ff2&parentMessageId=1727333967248&teamName=DataViz%20-%20Mobile%20and%20Desktop&channelName=Flutter%20Supports&createdTime=1727350879359).

If the above solution does not meet your requirements, we kindly request you to provide more detailed information, along with any relevant screenshots or screen recordings. This will help us assist you more effectively. 

Regards,
kompelli sravan kumar.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.
