### ISSUE TITLE
In DataGrid, support consecutive `KeyEvent` please.

### ISSUE THREAD

**Issue by dolbin-prime** [syncfusion/flutter-widgets#2063]
### Use case

My app is targeting Windows desktop users(not Web), and there are lots of Synfusion datagrids in it. The problem is, sometimes a grid has many rows and a user wants to see more data using `LogicalKeyboardKey.pageUp` or `LogicalKeyboardKey.pageDown`, and when he/she presses then holds the key, the key event fires only once.🤔 What users want is to keep scrolling up or down until they release the key.

### Proposal

Please support a feature to decide whether to keep firing key events or not when a user holds a key
like:
```dart
class DataGridSelectionManager extends RowSelectionManager {
  DataGridSelectionManager();

  @override
  Future<void> handleKeyEvent(KeyEvent keyEvent) {
    if (keyEvent.logicalKey == LogicalKeyboardKey.pageUp) {
      return super.handleKeyEvent(keyEvent, repeated: true);
    }
    else {
      return super.handleKeyEvent(keyEvent, repeated: false);
    }
  }
}
```
or something. It would be nice if I can handle it! Thank you 😀

**Comment by abineshPalanisamy** [comment]
Hi @dolbin-prime ,
 
Based on the provided information, in SfDataGrid, the default behavior for key events is as follows: For PageDown, the SfDataGrid scrolls to the next set of rows that are not displayed in the view, and for PageUp, it scrolls to the previous set of rows that are not displayed in the view. When the key is held down, the [handleKeyEvent](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FRowSelectionManager%2FhandleKeyEvent.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cda7b1ef662c94a762a1808dcd0a12c08%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638614637880568704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=4s%2FXCgMw8ojdWtwQshRtfUETwxYsVhQ8Rf3E1bdVPUo%3D&reserved=0) is triggered continuously. We have conducted tests using a simple sample, and the DataGrid scrolled properly when pressing PageDown or PageUp until the key was released. Please refer to the User Guide for more information.
 
UG Link - [Keyboard behavior](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Fselection%23keyboard-behavior&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cda7b1ef662c94a762a1808dcd0a12c08%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638614637880577679%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=LdJwMvH6qmMyktUmvoFKdM5f6xFjFR6KFrZBB3lkqew%3D&reserved=0)
 
We tested this scenario using the attached sample, and it worked correctly without any issues. If you are still encountering the same problem, we kindly request you to modify the attached sample to reproduce the issue and  provide additional details when the key event fires only once and scrolling does not occur. Additionally, please provide a video recording demonstrating the issue for better clarity. This will greatly assist us in investigating the issue further and providing an appropriate solution as quickly as possible.
 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment]
Hi @abineshPalanisamy ,

thanks for your response, I tried your sample by creating new flutter project and found that I was using the old version of `syncfusion_flutter_datagrid`, `24.2.9`! I upgraded the package I'm using and it works well like you said.🎈 I can't find any [update](https://pub.dev/packages/syncfusion_flutter_datagrid/changelog) with this, but anyway, thank you! I solved the problem! 😁

**Comment by ashok-kuvaraja** [comment]
Hi @dolbin-prime,

We are glad to hear that the reported issue has been resolved on your end. We are closing this ticket. If you need any further assistance, please feel free to reopen the ticket. We are happy to help.

Regards,
Ashok K
