### ISSUE TITLE
markNeedsBuild compilation error

### ISSUE THREAD

**Issue by marinkobabic** [syncfusion/flutter-widgets#2065]
### Bug description

Please check your score https://pub.dev/packages/syncfusion_flutter_charts/score The project can't eve be built.

### Steps to reproduce

Used latest flutter version and try to install your package

### Code sample

not needed

### Screenshots or Video

not needed

### Stack Traces

not needed

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

static analysis

**Comment by EeroVilkuna** [comment]
https://github.com/syncfusion/flutter-widgets/issues/2050#issuecomment-2325808872

**Comment by marinkobabic** [comment]
@withden you are right. Thanks a lot

**Comment by ThilipChandru** [comment]
Hi @marinkobabic,

Thank you for your patience. We have upgraded our Flutter Charts package to be compatible with Flutter SDK 3.24.0. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.

Regards,
Thilip Chandru.
