### ISSUE TITLE
Hide Time and set text when select

### ISSUE THREAD

**Issue by eyadramzy** [syncfusion/flutter-widgets#2067]
### Bug description

I Want to hide the time if time have minutes.
Like this image
<img width="518" alt="Screenshot 2024-09-11 at 2 46 14 PM" src="https://github.com/user-attachments/assets/c7a43bf3-e495-405b-9794-ec3beccd4a51">
also, I Want to set text on selectionDecoration when selecting the item

<img width="491" alt="Screenshot 2024-09-11 at 2 51 39 PM" src="https://github.com/user-attachments/assets/b60790f4-2832-47e1-bfff-eb9867f33b8a">

**Comment by Hariram-SF4428** [comment]
Hi @eyadramzy,


**Query 1: To hide time if time have minutes**

Currently, we don’t have support to hide time if it includes minutes. However, we have already logged a feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.
 
**FR Link:** [Adjust TimeSlotViewSettings time labels in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/43409/adjust-timeslotviewsettings-time-labels)

**Query 2:  To set text when selecting the item**

Currently, we don't have direct support for adding or editing text when selecting a resource. However, in this knowledge base article, we have explained how to develop an appointment editor, which allows you to display the tapped appointment information as per your requirements. 
 
**KB Link:** [How to design and configure your appointment editor in Flutter Calendar (syncfusion.com)](https://support.syncfusion.com/kb/article/9667/how-to-design-and-configure-your-appointment-editor-in-flutter-calendar)


Please let us know if you need any further assistance.


Regards,
Hariram S

**Comment by LavanyaGowtham2021** [comment]
Please let us know if you need further assistance on this.

**Comment by eyadramzy** [comment]
thanks, @Hariram-SF4428 
I am waiting for the new feature to hide time if it includes minutes.
**Query 2: To set text when selecting the item**
Add a new feature next to selectionDecoration for editing to the widget 'selectionBuilder' this option returns the time selected.

**Comment by ThilipChandru** [comment]
Hi @eyadramzy ,
 
Thank you for your suggestion, we will consider this as improvement and implement in any of our upcoming releases.
 
Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Since it’s an uncertain feature, I am closing this. Please follow up with the FR below.
[Adjust TimeSlotViewSettings time labels in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/43409/adjust-timeslotviewsettings-time-labels)
