### ISSUE TITLE
LineSeries pointColorMapper appears to be delayed by 1 point

### ISSUE THREAD

**Issue by zambetpentru** [syncfusion/flutter-widgets#2069]
### Bug description

Hi,

As per the screenshot, I would have expected the colour between the 225->215 data point to be red and the next point between 215 and 230 to be green? Is there a way I can achieve this?

### Steps to reproduce

Run the sample code to reproduce

### Code sample

<details open><summary>Code sample</summary>

import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Syncfusion Line Chart with Color Change',
      home: Scaffold(
        appBar: AppBar(title: Text('Line Chart with Point Color Mapping')),
        body: LineChartExample(),
      ),
    );
  }
}

class LineChartExample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // Fake data for the chart
    List<ChartData> chartData = [
      ChartData(DateTime(2024, 9, 1), 200),
      ChartData(DateTime(2024, 9, 2), 210),
      ChartData(DateTime(2024, 9, 3), 215),
      ChartData(DateTime(2024, 9, 4), 220),
      ChartData(DateTime(2024, 9, 5), 225),
      ChartData(DateTime(2024, 9, 6), 215),
      ChartData(DateTime(2024, 9, 7), 230),
      ChartData(DateTime(2024, 9, 8), 240),
      ChartData(DateTime(2024, 9, 9), 250),
    ];

    return SfCartesianChart(
      title: ChartTitle(text: 'Stock Prices Over Time'),
      primaryXAxis: DateTimeAxis(
        title: AxisTitle(text: 'Date'),
      ),
      primaryYAxis: NumericAxis(
        title: AxisTitle(text: 'Price (USD)'),
      ),
      series: [
        LineSeries<ChartData, DateTime>(
          name: 'Closing Price',
          dataSource: chartData,
          xValueMapper: (ChartData data, _) => data.date,
          yValueMapper: (ChartData data, _) => data.price,
          pointColorMapper: (ChartData data, int index) {
            // Change point color based on price change (previous vs current)
            if (index == 0) {
              return Colors.blue; // First point is neutral (can be any color)
            } else {
              return chartData[index].price > chartData[index - 1].price ? Colors.green : Colors.red; // Green if price increased, red if decreased
            }
          },
          markerSettings: const MarkerSettings(
            isVisible: true,
            shape: DataMarkerType.circle, // Marker shape
          ),
          dataLabelSettings: DataLabelSettings(isVisible: true),
        ),
        ColumnSeries<ChartData, DateTime>(
          name: 'Closing Price',
          dataSource: chartData,
          xValueMapper: (ChartData data, _) => data.date,
          yValueMapper: (ChartData data, _) => data.price / 2,
          pointColorMapper: (ChartData data, int index) {
            // Change point color based on price change (previous vs current)
            if (index == 0) {
              return Colors.blue; // First point is neutral (can be any color)
            } else {
              return chartData[index].price > chartData[index - 1].price ? Colors.green : Colors.red; // Green if price increased, red if decreased
            }
          },
          markerSettings: const MarkerSettings(
            isVisible: true,
            shape: DataMarkerType.circle, // Marker shape
          ),
          dataLabelSettings: DataLabelSettings(isVisible: true),
        ),
      ],
    );
  }
}

// Data model for the chart
class ChartData {
  final DateTime date;
  final double price;

  ChartData(this.date, this.price);
}

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/a8834a69-4014-4674-8512-d73941453008)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

macOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
Flutter 3.24.2 and latest syncfusion 26.2.14
```

</details>

**Comment by ManiKesavaraj** [comment]
Hi @zambetpentru , 

We have reviewed the code snippet you provided and would like to inform you that the line series is connected to the previous data point. We have modified the logic for the line series in the code snippet below to achieve the desired output. Please adjust the conditions as needed based on your requirements.

Code Snippet: 
```
 LineSeries<ChartData, DateTime>(
        ….
         pointColorMapper: (ChartData data, int index) {
            if (index == 0) {
              // Change point color based on price change (previous vs current)
              return Colors.blue;
            } else if (index == chartData.length - 1) {
              // For the last point, use green because no next price to compare
              return Colors.green;
            } else {
              return chartData[index].price > chartData[index + 1].price
                  ? Colors.red
                  : Colors.green;
            }
          },
          ….
```

Screenshot:
![Screenshot 2024-09-17 173542](https://github.com/user-attachments/assets/db337848-f1d4-4e91-8243-8e2057f0d3ab)

Regards,
Naveen.

**Comment by zambetpentru** [comment]
Brilliant thank you for providing a working approach!
