### ISSUE TITLE
How to remove the margins of new added page?

### ISSUE THREAD

**Issue by taihangg** [syncfusion/flutter-widgets#2071]
I added a image to a pdf document, but there is always some margin around the image. 

I tried to set the document's margin to zero, but it does not work as expected.

```
PdfDocument _pdfDoc = PdfDocument(inputBytes: _fileData);
// _pdfDoc.pageSettings.margins.all = 0; // the result is worse than do not set it.

PdfBitmap image = PdfBitmap(_imgData);

final size = _pdfDoc!.pages[0].size;
// final size =page.getClientSize(); // tried this too

final newPage = _pdfDoc!.pages.insert(0);
newPage.graphics.drawImage(image, Rect.fromLTWH(0, 0, size.width, size.height));

saveFile("newABC.pdf", await _pdfDoc!.save());

```

and how to make the image's width fit to the pdf's or page's width without clip?

it always looks like this:
<img width="528" alt="capture" src="https://github.com/user-attachments/assets/b856c975-7155-4cbb-9e6c-c0837b63e221">

------------------------------------------------------------------------

now, I found that, use inisert will cause this result:
 `_pdfDoc!.pages.insert(pageIdx);`

use add works good:
```
        PdfDocument newPdfDoc = PdfDocument();
        //Initialize compression level
        newPdfDoc.compressionLevel = PdfCompressionLevel.normal;
        //Set the cross-reference type as cross reference stream
        newPdfDoc.fileStructure.crossReferenceType =
            PdfCrossReferenceType.crossReferenceStream;
        //Set page margins to zero.
        newPdfDoc.pageSettings.margins.all = 0;

        _addPdfPageToOtherPdf(PdfPage oldPage, PdfDocument newDoc) {
          //Load the existing page as template.
          PdfTemplate pageTemplate = oldPage.createTemplate();
          //Create a page in the new document.
          PdfPage newPage = newDoc.pages.add();
          //Draw the existing page template in the new document.
          newPage.graphics.drawPdfTemplate(
              pageTemplate, Offset.zero, newPage.getClientSize());
        }

        for (int i = 0; i < pageIdx; i++) {
          _addPdfPageToOtherPdf(_pdfDoc!.pages[i], newPdfDoc);
        }

        PdfDocument imgPdfDoc = PdfDocument(inputBytes: imagePdfData);
        _addPdfPageToOtherPdf(imgPdfDoc.pages[0], newPdfDoc);

        for (int i = pageIdx; i < _pdfDoc!.pages.count; i++) {
          _addPdfPageToOtherPdf(_pdfDoc!.pages[i], newPdfDoc);
        }

        await saveFile(
            "${_savePath}/abc-${timeStamp}-2.pdf", await newPdfDoc.save());

        imgPdfDoc.dispose();

```

--------------------------------------------------------------------------

another question:
```
PdfDocument newPdfDoc = PdfDocument();
for (int i = 0; i < pageIdx; i++) {
  _addPdfPageToOtherPdf(_pdfDoc!.pages[i], newPdfDoc);
}
newPdfDoc.pages[0].createTemplate(); // cause assert failed!
```

**Comment by jeyalakshmit** [comment]
Hi @taihangg ,
 
|     |     |
| --- | --- |
| I added a image to a pdf document, but there is always some margin around the image. I tried to set the document's margin to zero, but it does not work as expected. | We have checked the reported issue with the provided details on our end and reproduced it. Upon further analysis, we suggest setting the margins using [Insert](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPageCollection/insert.html) method. Please refer to the code snippet below for your reference. <br>``` PdfMargins margins=new PdfMargins(); margins.all=0; final newPage= _pdfDoc!.pages.insert(0,size,margins);``` |
| ```PdfDocument newPdfDoc = PdfDocument(); for (int i = 0; i < pageIdx; i++) { _addPdfPageToOtherPdf(_pdfDoc!.pages[i], newPdfDoc);} newPdfDoc.pages[0].createTemplate(); // cause assert failed!``` | The createTemplate method is designed to work exclusively with loaded pages. Creating a page template for a new page is not supported.<br><br>Kindly use the following link for reference, <br>[Creating templates from existing PDF document](https://help.syncfusion.com/document-processing/pdf/pdf-library/flutter/working-with-pdf-templates#creating-templates-from-existing-pdf-document).|

Regards,
Jeyalakshmi T

**Comment by taihangg** [comment]
oh, that's my mistake! a big wulong! i'm sorry! 
thank you!
