### ISSUE TITLE
Excuse me, how to get the image element of some page from PDF?

### ISSUE THREAD

**Issue by taihangg** [syncfusion/flutter-widgets#2072]
Excuse me, how to get the image element of some page from PDF?
I want to save the image element of some page.

**Comment by jeyalakshmit** [comment]
Currently, our Flutter library does not support extracting images from PDF documents. However, we have already added this feature request to our list. Additionally, we do not have any immediate plans to implement this support. We will consider implementing it in any of our upcoming releases. You can track the status of the feature using the following feedback link.
https://www.syncfusion.com/feedback/21130/support-for-extracting-the-images-from-pdf-document

**Comment by taihangg** [comment]
OK，thank you!

**Comment by taihangg** [comment]
Excuse me.
I got the stream data now，some data looks like the bin data of image.then i try to save it as a image.but when open the file，it's not a image. How can i translate the data to a image？
