### ISSUE TITLE
[SfDataGrid] Support  Merge Cells For Column And Row

### ISSUE THREAD

**Issue by aike1202** [syncfusion/flutter-widgets#2073]
### Use case

Need Show Summary data on Table 
![image](https://github.com/user-attachments/assets/4f3a0064-c9d1-4dfc-a5d7-a8291def72c3)

### Proposal

Support  colspan or  rowspan like html 
[HTML Table Colspan & Rowspan](https://www.w3schools.com/html/html_table_colspan_rowspan.asp)
Or Support Merge Cells Like Excel
![image](https://github.com/user-attachments/assets/04d939ad-7285-4243-a1ee-e445cccb18c1)

**Comment by abineshPalanisamy** [comment]
Hi @aike1202 ,
 
For the column span requirement in SfDataGrid, you can use stacked headers. The DataGrid supports displaying additional unbound header rows, known as [StackedHeaderRows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2FstackedHeaderRows.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9d7746d9704a447c4a4508dcd3d6b7eb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638618166367193326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xOuLw7a%2FRvPSu3eUW%2Btc8P4P6zRlR6K4v2LyR6p%2Fmvc%3D&reserved=0), which can span across multiple DataGrid columns. You can **group one or more columns under each stacked header**. Please refer to the User Guide for more information.
 
UG link - [Stacked headers](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Fstacked-headers&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9d7746d9704a447c4a4508dcd3d6b7eb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638618166367202394%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WzD%2FwCuiUpD59Rexe03RP7vdsBAlINHZ0RRe3PiDfh8%3D&reserved=0)
 
As of now, DataGrid does not have support to merge the rows and cells. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [23230](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F23230%2Fsupport-to-merge-the-rows-and-cells&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9d7746d9704a447c4a4508dcd3d6b7eb%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638618166367210150%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=iFVWnVpCKAyIrLr8NeHX8fbpjlDat0YSl%2FZe3sL7Cck%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by aike1202** [comment]
@abineshPalanisamy 
Thank you for your answers, I will follow the Feedback
