### ISSUE TITLE
[DataGrid] StackedHeader  same child headers, The parent header will be drawn overlapped

### ISSUE THREAD

**Issue by tylerjin** [syncfusion/flutter-widgets#208]
When different parent headers have exactly the same child headers,
The parent header will be drawn overlapped
version
syncfusion_flutter_datagrid: ^19.1.57-beta

**Comment by RenugaSadagoban98** [comment]
Hi @tylerjin , 

Greetings from syncfusion. 

You cannot add different parent headers that contain the same column name in a single StackedHeaderRow. We suspect that you want to display the two different stacked information for the same column. If you want to show multiple stacked information for the same columns, you can add the multiple parent stacked headers which contain the same column name.

Refer to the following code snippets, 

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: SfDataGrid(
          source: employeeDataSource,
          columnWidthMode: ColumnWidthMode.fill,
          gridLinesVisibility: GridLinesVisibility.both,
          headerGridLinesVisibility: GridLinesVisibility.both,
          stackedHeaderRows: [
            StackedHeaderRow(cells: [
              StackedHeaderCell(columnNames: [
                'salary',
                'designation'
              ], child: Center(child: Center(child: Text('Employee Details')))),
            ]),
            StackedHeaderRow(cells: [
              StackedHeaderCell(
                  columnNames: ['salary', 'designation'],
                  child: Container(
                      child: Center(child: Text('Designation Details'))))
            ]),
          ],
          columns: _column),
    );
  }

```

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-957487543


UG link:  https://help.syncfusion.com/flutter/datagrid/stacked-headers

Please let us know if you need further assistance. 


Regards,
Renuga devi S
