### ISSUE TITLE
i am using flutter  3.13.9 and it it showing this error  

### ISSUE THREAD

**Issue by mimoislam** [syncfusion/flutter-widgets#2085]
### Bug description

i am using flutter  3.13.9 and it it showing this error and some other textScanle and other errors Can Someone help ?
even when i use new version still the same error 
 

### Steps to reproduce

1. Flutter version 3.13.9
2. add last version of  syncfusion_flutter_core
3. relanch app  error

### Code sample

<details open><summary>Code sample</summary>

```dart
Expanded(child:  SfCartesianChart(
            primaryXAxis: CategoryAxis(),
            primaryYAxis: NumericAxis(),
            series: [
              ColumnSeries<UserTypeOrders, String>(
                dataSource: userTypesOrders,
                xValueMapper: (UserTypeOrders orders, _) => orders.type.toFriendlyString(),
                yValueMapper: (UserTypeOrders orders, _) => orders.totalOrders,
                pointColorMapper: (UserTypeOrders orders, _) => getColorForUserType(orders.type),
                dataLabelSettings: DataLabelSettings(isVisible: true),
              ),
            ],
            tooltipBehavior: TooltipBehavior(enable: true),
          ),
          ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]
![Screenshot 2024-09-20 072114](https://github.com/user-attachments/assets/bfdf6515-ec2d-413e-8561-5f0dabcab6a5)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```
pub.dev/syncfusion_flutter_charts-26.2.14/lib/src/charts/utils/helper.dart(76,35): error GF7CA4DBF: Couldn't find constructor 'TextScaler.linear'.  
pub.dev/syncfusion_flutter_charts-26.2.14/lib/src/charts/utils/helper.dart(76,17): error GC6690633: No named parameter with the name 'textScaler'.
pub.dev/syncfusion_flutter_core-26.2.14/lib/src/theme/theme_widget.dart(123,47): error G4127D1E8: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
pub.dev/syncfusion_flutter_core-26.2.14/lib/src/theme/theme_widget.dart(148,47): error G4127D1E8: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.
</details>

**Comment by ThilipChandru** [comment]
Hi @mimoislam ,

We’ve upgraded our Flutter package to the latest SDK version, 3.22. To address the issues you’ve encountered with our recent Syncfusion package on an older SDK, we recommend using a compatible version between [22.2.11](https://pub.dev/packages/syncfusion_flutter_charts/versions/22.2.11) and [23.2.4](https://pub.dev/packages/syncfusion_flutter_charts/versions/23.2.4). For more details on system compatibility, please refer to the following user guide:

UG link: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility

Regards,
Thilip Chandru.

**Comment by LavanyaGowtham2021** [comment]
Please let us know if you need further assistance on this.
