### ISSUE TITLE
Customizing Trackball Line Height Based on Data Point

### ISSUE THREAD

**Issue by Dao-Van-Thanh** [syncfusion/flutter-widgets#2093]
Hello Syncfusion team,

I am currently using the syncfusion_flutter_charts package and have come across a limitation with the TrackballBehavior feature. Specifically, I am trying to customize the vertical trackball line such that it only spans from the bottom of the chart to the specific data point where the trackball is positioned, instead of extending from the top to the bottom of the chart.

**Current Behavior:**
The vertical trackball line currently spans the full height of the chart, which may not be visually ideal for certain applications.
![image](https://github.com/user-attachments/assets/495fdbdc-e8c6-4637-9e95-6b01df89fc3f)

**Expected Behavior:**
I would like the trackball line to stop at the y-coordinate of the data point where the trackball marker is placed, as shown in this ![image](https://github.com/user-attachments/assets/ca70de72-4eb5-4bc0-bac9-a2c752d19cc8)

**Question:**
Is there currently any way to customize the height of the trackball line to achieve this behavior? If not, would it be possible to add support for controlling the trackball line height dynamically based on the y-value of the data point?

Thank you for your time and for the continuous improvements to this library!

Best regards,
Thanh

**Comment by ThilipChandru** [comment]
Hi @Dao-Van-Thanh,

We would like to inform you that we have a knowledge base (KB) to meet your requirement. We have shared it below for your reference. You can refer to this knowledge base and modify the sample based on your requirement. 

KB Links: [How to customize the trackball in Flutter CartesianChart? (syncfusion.com)](https://support.syncfusion.com/kb/article/16112/how-to-customize-the-trackball-in-flutter-cartesianchart).

Regards,
Thilip Chandru
