### ISSUE TITLE
[flutter-pdf-viewer] pdf viewer is not working in flutter web

### ISSUE THREAD

**Issue by adityajoshi12** [syncfusion/flutter-widgets#210]
I am trying to run the example provided in the repository on flutter web but pdf is not opening up.

**Comment by dillibabun** [comment]
Hi @adityajoshi12 ,

Greetings from Syncfusion.

The example project in syncfusion_flutter_pdfviewer package works as expected in Web platform. Kindly share us the following details.
1. syncfusion_flutter_pdfviewer package version. We recommend to use our latest package [19.1.59-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.59-beta).
2. Flutter doctor log. Kindly run flutter doctor command in Android Studio terminal and share us the output.
3. For [network ](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.network.html)constructor of SfPdfViewer, Internet access is required so kindly check this.
4, Screenshot of the issue in SfPdfViewer widget.

These pieces of information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by tsgregoryv** [comment]
There is an include required on your index.html file for flutter web.  This might be what you are missing if the demo file is not working properly.  Here is the link & the required includes.

https://help.syncfusion.com/flutter/pdf-viewer/getting-started

`<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
<script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
</script>`

**Comment by dillibabun** [comment]
Hi @tsgregoryv ,

As @adityajoshi12 stated, he is working on the example project of this package. Your suggestions have been included in the example project as well. I Hope, the issue might have resolved.

Regards,
Dilli babu.

**Comment by tsgregoryv** [comment]
It is in the repository, but I don't see it documented on pub.dev.  I would suggest adding it there as well. It would be an easy miss if someone didn't use the entire example package.

**Comment by adityajoshi12** [comment]
It's working now, after I put these scripts in my index.html, as mentioned by @tsgregoryv, it would be great if you can put this on pub.dev also. I am closing this issue now

```
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
<script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
</script>
```

**Comment by dillibabun** [comment]
Hi @adityajoshi12 @tsgregoryv ,

We have mentioned in https://pub.dev/packages/syncfusion_flutter_pdfviewer_web pub dev. We will modify in https://pub.dev/packages/syncfusion_flutter_pdfviewer as well.

Regards,
Dilli babu.
