### ISSUE TITLE
DoughnutSeries chart with rounded is possible?

### ISSUE THREAD

**Issue by hilderlanherbert** [syncfusion/flutter-widgets#2101]
### Use case

I'm trying to achieve this result, but I'm not getting it with what we have in sync today... 
I wanted to know if it is possible to leave this graph with rounded ends and one on top of the other?

I arrived at this result:

<img width="129" alt="image" src="https://github.com/user-attachments/assets/0ac645fa-6401-4f65-871f-f41368e03286">

And I wanted this:

![image](https://github.com/user-attachments/assets/522eb299-bc47-42f1-a1a9-b922ab5c1fa7)

Is this type of degrader possible? 

I apologize if this is in the wrong place, my first time

### Proposal

Imagine that it is not possible to do it now, so if I am right, I would like to ask if it were possible to round the ends and control the distance between them

Thank you very much and have a good week

**Comment by Hariram-SF4428** [comment]
Hi @hilderlanherbert,

By default, when using the doughnut series with four data points, the chart will render as a complete circle, filling all four segments and this is the default behavior. If you want to create a gap between two data points, you can achieve this by adding a fifth data point with its color set to transparent. 
 
We have attached a sample for your reference. If you have any further queries, please get back to us. We are always happy to assist you.

**Sample:** [gh_2101.zip](https://github.com/user-attachments/files/17243354/gh_2101.zip)

Regards,
Hariram S

**Comment by Hariram-SF4428** [comment]
Hi @hilderlanherbert,

By default, when using the doughnut series with two data points, the chart will render as a complete circle, filling all two segments and this is the default behavior. If you want to create a gap between two data points, you can achieve this by adding a third data point with its color set to transparent. 
 
We have attached a sample for your reference. If you have any further queries, please get back to us. We are always happy to assist you.

**Sample:** [gh_2101.zip](https://github.com/user-attachments/files/17256473/gh_2101.zip)
**Screenshot:** ![image](https://github.com/user-attachments/assets/13f6c32d-d03e-480f-9cf4-ec7b43018435)
 
Regards,
Hariram S

**Comment by hilderlanherbert** [comment]
Hii @Hariram-SF4428 

Thank you so much for your help! Your explanation was clear, and the sample was exactly what I needed. I was already trying to do it manually without much success, and your guidance helped me a lot. I truly appreciate your quick assistance and support.

Thanks again!

**Comment by Hariram-SF4428** [comment]
Hi @hilderlanherbert,

Most Welcome. Kindly get back to us if you have further queries. We are always happy to assist you.

Regards,
Hariram S
