### ISSUE TITLE
Debouncing the onChanged values from SfSlider?

### ISSUE THREAD

**Issue by arnab** [syncfusion/flutter-widgets#2106]
### Use case

First of all, thanks a lot for a great package. In my audio app, I am using the `SfSlider` to show a speed-selector. The user can drag the slider to select a value.

I see that for each intermediate step in the slider, the `onChanged` callback is called. For example, if I have steps of `0.25`, when a user slides from `1` and `2`, the `onChanged` callback is called for `1.25`, `1.5`, `1.75` and finally `2`.

How can set up a debouncing mechanism, since I am only interested in the end-result of the drag (and not all intermediate values)?

### Proposal

This is a question. I am assuming there is already a way to get what I want. 

However, if this requires a change in the package, and you have ideas on whether this should be incorporated into the library itself, please share guidance on where and how.

**Comment by arnab** [comment]
Ah I think I just need to use the `onChangeEnd` callback (but the `onChange` callback is required). So I have this:

```dart
  onChanged: (value) => {},
  onChangeEnd: (value) => _setSpeed(ref, value),
```

**Comment by Mugunthan-Ramalingam** [comment]
Hi @arnab,

We have analyzed your query, and you can achieve the desired behavior using both the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChanged.html) and [onChangeEnd](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChangeEnd.html) callbacks in the [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider-class.html).


- The [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChanged.html) callback is triggered whenever the value of the slider changes, and to update the UI, it is necessary to rebuild the slider with the new value provided in this callback.
- The [onChangeEnd](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChangeEnd.html) callback is triggered when the slider interaction is completed.

In our case, it is essential to rebuild the slider widget in the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChanged.html) callback with the new value to update the Slider UI as the value changes. Additionally, you should consider implementing the end value logic in the [onChangeEnd](https://pub.dev/documentation/syncfusion_flutter_sliders/27.1.51/sliders/SfSlider/onChangeEnd.html) callback.

If you are still facing any issues, please provide us with more detailed information regarding the problem. This will help us assist you more effectively.

Code snippet:
```
double _value;

SfSlider(
   onChanged: (dynamic value) {
      setState(() {
         _value = value;
      });
   },
   onChangeEnd: (dynamic value) {
       // end value logic
   }
)
```


Regards,
Mugunthan.

**Comment by arnab** [comment]
Thanks @Mugunthan-Ramalingam ! I also [noted the same](https://github.com/syncfusion/flutter-widgets/issues/2106#issuecomment-2384809166). Will close this now.
