### ISSUE TITLE
Sorting Button Only Sorts Visible Records in DataGrid Instead of Entire Dataset

### ISSUE THREAD

**Issue by abhirammadhumadhav** [syncfusion/flutter-widgets#2108]
### Bug description

When tapping the sorting button in the DataGrid, the grid initially displays only the currently visible records instead of all the records fetched from the database. The sorting action does not account for the entire dataset loaded from the database, but only sorts and displays the rows that are currently rendered on the screen.

### Steps to reproduce

Fetch data from the database.
Load the data into the DataGrid.
Scroll down the grid to make sure not all records are visible.
Tap the sorting button on a column.
Observe that only the currently visible records are sorted, not the entire dataset.

### Code sample

void _addMoreRows(int count) {
    int startIndex = dataGridRows.isNotEmpty ? dataGridRows.length : 0,
        endIndex = startIndex + count;

    if (endIndex <= xmlDataList.length) {
      List loadmoredatafromlisttogrid =
          xmlDataList.getRange(startIndex, endIndex).toList();

      //  print('loadmore $loadmore');

      for (int i = 0; i < loadmore!; i++) {
        Map<String, String> mapData = loadmoredatafromlisttogrid[i];

        dataGridRows.add(DataGridRow(
            cells: mapData.entries.map((entry) {
          // print('Key: ${entry.key}, Value: ${entry.value}');

          return DataGridCell(columnName: entry.key, value: entry.value);
        }).toList()));
      }
    } else {
      endIndex = xmlDataList.length;

      List loadmoredatafromlisttogrid =
          xmlDataList.getRange(startIndex, endIndex).toList();

      for (int i = 0; i < loadmoredatafromlisttogrid.length; i++) {
        Map<String, String> mapData = loadmoredatafromlisttogrid[i];

        dataGridRows.add(DataGridRow(
            cells: mapData.entries.map((entry) {
          return DataGridCell(columnName: entry.key, value: entry.value);
        }).toList()));
      }

      isloadmoreend = true;
    }

    //callback();

    currentrecordcount = dataGridRows.length;
    // print('current record count $currentrecordcount');
  }

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
![Screenshot 2024-10-01 183509](https://github.com/user-attachments/assets/95612420-9c9f-43ca-a783-e24729a5bb93)

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>
no stack trace is available

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>
![Screenshot 2024-10-01 183729](https://github.com/user-attachments/assets/4cd97f7c-eaba-49f2-9b54-6bbc6e9ed5e9)

**Comment by abineshPalanisamy** [comment]
Hi @abhirammadhumadhav ,
 
Based on the information provided, we have prepared a **'load more' sample that fetches data from JSON**. When sorting is performed, the rows added to the DataGrid are sorted correctly. As you mentioned, the issue where only the rows currently rendered on the screen are sorted did not occur in our sample.
 
We tested this scenario using the attached sample, and it worked correctly without any issues. If you are still encountering the problem, we kindly ask you to modify the attached sample to reproduce the issue and provide additional details on the steps to reproduce it. Additionally, please share a video recording demonstrating the issue for better clarity. This will greatly assist us in investigating the matter further and providing a solution as quickly as possible.

- **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/17239772/SfDataGrid.zip)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @abhirammadhumadhav,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K
