### ISSUE TITLE
Header checkbox callback

### ISSUE THREAD

**Issue by Tigran-Kosemyan** [syncfusion/flutter-widgets#2109]
How to handle checkbox callback action in header, when select all pressed from checkbox on header?

**Comment by abineshPalanisamy** [comment]
Hi @Tigran-Kosemyan ,

As of now, DataGrid does not have support for a callback to listen for value changes when the DataGrid checkbox is checked/unchecked. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [52162](https://www.syncfusion.com/feedback/52162/support-for-a-callback-to-listen-for-value-changes-when-the-datagrid-checkbox-is)
 
Additionally, we have a workaround to verify if all rows are selected using the '**Select All**' option in the header by leveraging the [onSelectionChanging](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onSelectionChanging.html) and [onSelectionChanged](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onSelectionChanged.html) callbacks. We’ve included a sample for your reference. Please review it for further details.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/17239599/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by Tigran-Kosemyan** [comment]
Thank you for the information and example. I think it will be implemented in the next release.

**Comment by ashok-kuvaraja** [comment]
Hi @Tigran-Kosemyan,
 
We are closing this issue now. You can follow the feedback link for further updates. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K
