### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Not working with Large Files

### ISSUE THREAD

**Issue by mibkvr** [syncfusion/flutter-widgets#211]
Hello Guys,
my Flutter App keep on crashing.
Im using the PDF Viewer with a local cached File.
Im using a 11mb File with raw pdf Text Data. (No Images)

`I/flutter ( 4409): /data/user/0/com.hidden.appname/cache/libCachedImageData/1f912370-ae34-11eb-ab21-cda42322637c.file
I/Choreographer( 4409): Skipped 148 frames!  The application may be doing too much work on its main thread.
W/ezis.montageap( 4409): Long monitor contention with owner pool-13-thread-1 (4871) at void android.graphics.pdf.PdfRenderer$Page.<init>(android.graphics.pdf.PdfRenderer, int)(PdfRenderer.java:315) waiters=0 in void android.graphics.pdf.PdfRenderer$Page.<init>(android.graphics.pdf.PdfRenderer, int) for 899ms
I/scudo   ( 4409): Stats: SizeClassAllocator64: 965M mapped (0M rss) in 24162180 allocations; remains 12319405
I/scudo   ( 4409):   00 (   128): mapped:  98048K popped:  790330 pushed:  788732 inuse:   1598 total: 783008 rss:      0K releases:      0 last released:      0K region: 0x7d0e48a000 (0x7d0e483000)

I/scudo   ( 4409):   01 (    32): mapped:  52224K popped: 3156426 pushed: 1493240 inuse: 1663186 total: 1663200 rss:      0K releases:      0 last released:      0K region: 0x7d1e48b000 (0x7d1e483000)

I/scudo   ( 4409):   02 (    48): mapped: 146432K popped: 5874321 pushed: 2754108 inuse: 3120213 total: 3120213 rss:      0K releases:      0 last released:      0K region: 0x7d2e48e000 (0x7d2e483000)

I/scudo   ( 4409): F 03 (    64): mapped: 261888K popped: 7882574 pushed: 3692374 inuse: 4190200 total: 4190200 rss:      0K releases:      0 last released:      0K region: 0x7d3e485000 (0x7d3e483000)

I/scudo   ( 4409):   04 (    80): mapped:  82688K popped: 1987753 pushed:  931098 inuse: 1056655 total: 1056697 rss:      0K releases:      0 last released:      0K region: 0x7d4e493000 (0x7d4e483000)

I/scudo   ( 4409):   05 (    96): mapped:  38912K popped:  784772 pushed:  372288 inuse: 412484 total: 412498 rss:      0K releases:      0 last released:      0K region: 0x7d5e48e000 (0x7d5e483000)

I/scudo   ( 4409):   06 (   112): mapped:   1024K popped:   16331 pushed:    7882 inuse:   8449 total:   8477 rss:      0K releases:      0 last released:      0K region: 0x7d6e48a000 (0x7d6e483000)

I/scudo   ( 4409):   07 (   144): mapped: 254720K popped: 3448067 pushed: 1637244 inuse: 1810823 total: 1810865 rss:      0K releases:      1 last released: 207436K region: 0x7d7e48b000 (0x7d7e483000)

I/scudo   ( 4409):   08 (   176): mapped:    768K popped:    6870 pushed:    3724 inuse:   3146 total:   3426 rss:      0K releases:      0 last released:      0K region: 0x7d8e485000 (0x7d8e483000)

I/scudo   ( 4409):   09 (   192): mapped:    256K popped:     210 pushed:      14 inuse:    196 total:    224 rss:      0K releases:      0 last released:      0K region: 0x7d9e486000 (0x7d9e483000)

I/scudo   ( 4409):   10 (   224): mapped:   6144K popped:   52452 pushed:   25060 inuse:  27392 total:  27420 rss:      0K releases:      1 last released:   4872K region: 0x7dae48a000 (0x7dae483000)

I/scudo   ( 4409):   11 (   288): mapped:    512K popped:    1428 pushed:     532 inuse:    896 total:   1190 rss:      0K releases:      2 last released:      8K region: 0x7dbe493000 (0x7dbe483000)

I/scudo   ( 4409):   12 (   352): mapped:    512K popped:    2060 pushed:    1498 inuse:    562 total:    912 rss:      0K releases:     27 last released:    100K region: 0x7dce48f000 (0x7dce483000)

I/scudo   ( 4409):   13 (   448): mapped:   3840K popped:   15500 pushed:    6902 inuse:   8598 total:   8640 rss:      0K releases:      0 last released:      0K region: 0x7dde48b000 (0x7dde483000)

I/scudo   ( 4409):   14 (   592): mapped:   1024K popped:    7698 pushed:    7033 inuse:    665 total:   1432 rss:      0K releases:      7 last released:      8K region: 0x7dee485000 (0x7dee483000)

I/scudo   ( 4409):   15 (   800): mapped:   6144K popped:   14468 pushed:    6640 inuse:   7828 total:   7848 rss:      0K releases:      5 last released:     20K region: 0x7dfe48a000 (0x7dfe483000)

I/scudo   ( 4409):   16 (  1104): mapped:  10752K popped:  108434 pushed:  108129 inuse:    305 total:   9972 rss:      0K releases:    607 last released:   9644K region: 0x7e0e48c000 (0x7e0e483000)

I/scudo   ( 4409):   17 (  1648): mapped:   5632K popped:    6284 pushed:    2864 inuse:   3420 total:   3420 rss:      0K releases:      4 last released:      8K region: 0x7e1e490000 (0x7e1e483000)

I/scudo   ( 4409):   18 (  2096): mapped:    256K popped:     114 pushed:      21 inuse:     93 total:    108 rss:      0K releases:      2 last released:     12K region: 0x7e2e491000 (0x7e2e483000)

I/scudo   ( 4409):   19 (  2576): mapped:    256K popped:     168 pushed:     102 inuse:     66 total:     72 rss:      0K releases:      7 last released:      4K region: 0x7e3e487000 (0x7e3e483000)
I/scudo   ( 4409):   20 (  3120): mapped:    768K popped:     622 pushed:     392 inuse:    230 total:    232 rss:      0K releases:      3 last released:      4K region: 0x7e4e491000 (0x7e4e483000)
I/scudo   ( 4409):   21 (  4112): mapped:   8448K popped:    4310 pushed:    2262 inuse:   2048 total:   2048 rss:      0K releases:      7 last released:      8K region: 0x7e5e485000 (0x7e5e483000)
I/scudo   ( 4409):   22 (  4624): mapped:    256K popped:      34 pushed:       4 inuse:     30 total:     32 rss:      0K releases:      1 last released:      4K region: 0x7e6e48d000 (0x7e6e483000)
I/scudo   ( 4409):   23 (  7120): mapped:    768K popped:     471 pushed:     367 inuse:    104 total:    105 rss:      0K releases:    187 last released:      8K region: 0x7e7e487000 (0x7e7e483000)
I/scudo   ( 4409):   24 (  8720): mapped:    512K popped:      50 pushed:      10 inuse:     40 total:     42 rss:      0K releases:      6 last released:      8K region: 0x7e8e48c000 (0x7e8e483000)
I/scudo   ( 4409):   25 ( 11664): mapped:    512K popped:      43 pushed:      22 inuse:     21 total:     30 rss:      0K releases:     11 last released:     84K region: 0x7e9e487000 (0x7e9e483000)
I/scudo   ( 4409):   26 ( 14224): mapped:    768K popped:      42 pushed:       6 inuse:     36 total:     40 rss:      0K releases:      9 last released:     36K region: 0x7eae48b000 (0x7eae483000)
I/scudo   ( 4409):   27 ( 16400): mapped:    512K popped:      30 pushed:       2 inuse:     28 total:     31 rss:      0K releases:      2 last released:     12K region: 0x7ebe493000 (0x7ebe483000)
I/scudo   ( 4409):   28 ( 18448): mapped:    256K popped:      10 pushed:       0 inuse:     10 total:     12 rss:      0K releases:      0 last released:      0K region: 0x7ece486000 (0x7ece483000)
I/scudo   ( 4409):   29 ( 23056): mapped:    512K popped:      14 pushed:       0 inuse:     14 total:     15 rss:      0K releases:      0 last released:      0K region: 0x7ede490000 (0x7ede483000)
I/scudo   ( 4409):   30 ( 29456): mapped:    768K popped:      28 pushed:       3 inuse:     25 total:     26 rss:      0K releases:      4 last released:     24K region: 0x7eee490000 (0x7eee483000)
I/scudo   ( 4409):   31 ( 33296): mapped:    768K popped:     231 pushed:     214 inuse:     17 total:     19 rss:      0K releases:      8 last released:     60K region: 0x7efe488000 (0x7efe483000)
I/scudo   ( 4409):   32 ( 65552): mapped:   1792K popped:      35 pushed:       8 inuse:     27 total:     27 rss:      0K releases:      3 last released:     60K region: 0x7f0e48f000 (0x7f0e483000)
I/scudo   ( 4409): Scudo OOM: The process has Exhausted 256M for size class 64.
I/scudo   ( 4409): Stats: SizeClassAllocator64: 995M mapped (0M rss) in 24586015 allocations; remains 12743240
I/scudo   ( 4409):   00 (   128): mapped:  98048K popped:  790330 pushed:  788732 inuse:   1598 total: 783008 rss:      0K releases:      0 last released:      0K region: 0x7d0e48a000 (0x7d0e483000)
I/scudo   ( 4409):   01 (    32): mapped:  53760K popped: 3207706 pushed: 1493240 inuse: 1714466 total: 1714480 rss:      0K releases:      0 last released:      0K region: 0x7d1e48b000 (0x7d1e483000)
I/scudo   ( 4409):   02 (    48): mapped: 151808K popped: 5989863 pushed: 2754108 inuse: 3235755 total: 3235797 rss:      0K releases:      0 last released:      0K region: 0x7d2e48e000 (0x7d2e483000)
I/scudo   ( 4409): F 03 (    64): mapped: 261888K popped: 7882574 pushed: 3692374 inuse: 4190200 total: 4190200 rss:      0K releases:      0 last released:      0K region: 0x7d3e485000 (0x7d3e483000)
I/scudo   ( 4409):   04 (    80): mapped:  97792K popped: 2180370 pushed:  931098 inuse: 1249272 total: 1249300 rss:      0K releases:      0 last released:      0K region: 0x7d4e493000 (0x7d4e483000)
I/scudo   ( 4409):   05 (    96): mapped:  39936K popped:  797585 pushed:  372288 inuse: 425297 total: 425325 rss:      0K releases:      0 last released:      0K region: 0x7d5e48e000 (0x7d5e483000)
I/scudo   ( 4409):   06 (   112): mapped:   1024K popped:   16359 pushed:    7882 inuse:   8477 total:   8477 rss:      0K releases:      0 last released:      0K region: 0x7d6e48a000 (0x7d6e483000)
I/scudo   ( 4409): F 07 (   144): mapped: 261888K popped: 3499558 pushed: 1637244 inuse: 1862314 total: 1862314 rss:      0K releases:      1 last released: 207436K region: 0x7d7e48b000 (0x7d7e483000)
I/scudo   ( 4409):   08 (   176): mapped:    768K popped:    6870 pushed:    3724 inuse:   3146 total:   3426 rss:      0K releases:      0 last released:      0K region: 0x7d8e485000 (0x7d8e483000)
I/scudo   ( 4409):   09 (   192): mapped:    256K popped:     210 pushed:      14 inuse:    196 total:    224 rss:      0K releases:      0 last released:      0K region: 0x7d9e486000 (0x7d9e483000)
I/scudo   ( 4409):   10 (   224): mapped:   6144K popped:   52452 pushed:   25060 inuse:  27392 total:  27420 rss:      0K releases:      1 last released:   4872K region: 0x7dae48a000 (0x7dae483000)
I/scudo   ( 4409):   11 (   288): mapped:    512K popped:    1428 pushed:     532 inuse:    896 total:   1190 rss:      0K releases:      2 last released:      8K region: 0x7dbe493000 (0x7dbe483000)
I/scudo   ( 4409):   12 (   352): mapped:    512K popped:    2060 pushed:    1498 inuse:    562 total:    912 rss:      0K releases:     27 last released:    100K region: 0x7dce48f000 (0x7dce483000)
I/scudo   ( 4409):   13 (   448): mapped:   3840K popped:   15514 pushed:    6902 inuse:   8612 total:   8640 rss:      0K releases:      0 last released:      0K region: 0x7dde48b000 (0x7dde483000)
I/scudo   ( 4409):   14 (   592): mapped:   1024K popped:    7698 pushed:    7033 inuse:    665 total:   1432 rss:      0K releases:      7 last released:      8K region: 0x7dee485000 (0x7dee483000)
I/scudo   ( 4409):   15 (   800): mapped:   6144K popped:   14468 pushed:    6640 inuse:   7828 total:   7848 rss:      0K releases:      5 last released:     20K region: 0x7dfe48a000 (0x7dfe483000)
I/scudo   ( 4409):   16 (  1104): mapped:  10752K popped:  108434 pushed:  108129 inuse:    305 total:   9972 rss:      0K releases:    607 last released:   9644K region: 0x7e0e48c000 (0x7e0e483000)
I/scudo   ( 4409):   17 (  1648): mapped:   5632K popped:    6284 pushed:    2864 inuse:   3420 total:   3420 rss:      0K releases:      4 last released:      8K region: 0x7e1e490000 (0x7e1e483000)
I/scudo   ( 4409):   18 (  2096): mapped:    256K popped:     114 pushed:      21 inuse:     93 total:    108 rss:      0K releases:      2 last released:     12K region: 0x7e2e491000 (0x7e2e483000)
I/scudo   ( 4409):   19 (  2576): mapped:    256K popped:     168 pushed:     102 inuse:     66 total:     72 rss:      0K releases:      7 last released:      4K region: 0x7e3e487000 (0x7e3e483000)
I/scudo   ( 4409):   20 (  3120): mapped:    768K popped:     622 pushed:     392 inuse:    230 total:    232 rss:      0K releases:      3 last released:      4K region: 0x7e4e491000 (0x7e4e483000)
I/scudo   ( 4409):   21 (  4112): mapped:   8448K popped:    4360 pushed:    2262 inuse:   2098 total:   2100 rss:      0K releases:      7 last released:      8K region: 0x7e5e485000 (0x7e5e483000)
I/scudo   ( 4409):   22 (  4624): mapped:    256K popped:      34 pushed:       4 inuse:     30 total:     32 rss:      0K releases:      1 last released:      4K region: 0x7e6e48d000 (0x7e6e483000)
I/scudo   ( 4409):   23 (  7120): mapped:    768K popped:     471 pushed:     367 inuse:    104 total:    105 rss:      0K releases:    187 last released:      8K region: 0x7e7e487000 (0x7e7e483000)
I/scudo   ( 4409):   24 (  8720): mapped:    512K popped:      50 pushed:      10 inuse:     40 total:     42 rss:      0K releases:      6 last released:      8K region: 0x7e8e48c000 (0x7e8e483000)
I/scudo   ( 4409):   25 ( 11664): mapped:    512K popped:      43 pushed:      22 inuse:     21 total:     30 rss:      0K releases:     11 last released:     84K region: 0x7e9e487000 (0x7e9e483000)
I/scudo   ( 4409):   26 ( 14224): mapped:    768K popped:      42 pushed:       6 inuse:     36 total:     40 rss:      0K releases:      9 last released:     36K region: 0x7eae48b000 (0x7eae483000)
I/scudo   ( 4409):   27 ( 16400): mapped:    512K popped:      30 pushed:       2 inuse:     28 total:     31 rss:      0K releases:      2 last released:     12K region: 0x7ebe493000 (0x7ebe483000)
I/scudo   ( 4409):   28 ( 18448): mapped:    256K popped:      10 pushed:       0 inuse:     10 total:     12 rss:      0K releases:      0 last released:      0K region: 0x7ece486000 (0x7ece483000)
I/scudo   ( 4409):   29 ( 23056): mapped:    512K popped:      14 pushed:       0 inuse:     14 total:     15 rss:      0K releases:      0 last released:      0K region: 0x7ede490000 (0x7ede483000)
I/scudo   ( 4409):   30 ( 29456): mapped:    768K popped:      28 pushed:       3 inuse:     25 total:     26 rss:      0K releases:      4 last released:     24K region: 0x7eee490000 (0x7eee483000)
I/scudo   ( 4409):   31 ( 33296): mapped:    768K popped:     231 pushed:     214 inuse:     17 total:     19 rss:      0K releases:      8 last released:     60K region: 0x7efe488000 (0x7efe483000)
I/scudo   ( 4409):   32 ( 65552): mapped:   1792K popped:      35 pushed:       8 inuse:     27 total:     27 rss:      0K releases:      3 last released:     60K region: 0x7f0e48f000 (0x7f0e483000)
I/scudo   ( 4409): Scudo OOM: The process has Exhausted 256M for size class 144.
I/scudo   ( 4409): Stats: SizeClassAllocator64: 1380M mapped (0M rss) in 29614224 allocations; remains 17764673
I/scudo   ( 4409):   00 (   128): mapped:  98048K popped:  792094 pushed:  790538 inuse:   1556 total: 783008 rss:      0K releases:      0 last released:      0K region: 0x7d0e48a000 (0x7d0e483000)
I/scudo   ( 4409):   01 (    32): mapped:  76544K popped: 3941582 pushed: 1493240 inuse: 2448342 total: 2448384 rss:      0K releases:      0 last released:      0K region: 0x7d1e48b000 (0x7d1e483000)
I/scudo   ( 4409):   02 (    48): mapped: 210944K popped: 7250087 pushed: 2754108 inuse: 4495979 total: 4496021 rss:      0K releases:      0 last released:      0K region: 0x7d2e48e000 (0x7d2e483000)
I/scudo   ( 4409): F 03 (    64): mapped: 261888K popped: 7882574 pushed: 3692374 inuse: 4190200 total: 4190200 rss:      0K releases:      0 last released:      0K region: 0x7d3e485000 (0x7d3e483000)
I/scudo   ( 4409): F 04 (    80): mapped: 261888K popped: 4283264 pushed:  931098 inuse: 3352166 total: 3352166 rss:      0K releases:      0 last released:      0K region: 0x7d4e493000 (0x7d4e483000)
I/scudo   ( 4409):   05 (    96): mapped:  57088K popped:  980946 pushed:  372288 inuse: 608658 total: 608672 rss:      0K releases:      0 last released:      0K region: 0x7d5e48e000 (0x7d5e483000)
I/scudo   ( 4409):   06 (   112): mapped:   1024K popped:   16751 pushed:    7882 inuse:   8869 total:   8869 rss:      0K releases:      0 last released:      0K region: 0x7d6e48a000 (0x7d6e483000)
I/scudo   ( 4409): F 07 (   144): mapped: 261888K popped: 3499558 pushed: 1637244 inuse: 1862314 total: 1862314 rss:      0K releases:      1 last released: 207436K region: 0x7d7e48b000 (0x7d7e483000)
I/scudo   ( 4409):   08 (   176): mapped: 127744K popped:  745724 pushed:    3724 inuse: 742000 total: 742028 rss:      0K releases:      0 last released:      0K region: 0x7d8e485000 (0x7d8e483000)
I/scudo   ( 4409):   09 (   192): mapped:    256K popped:     210 pushed:      14 inuse:    196 total:    224 rss:      0K releases:      0 last released:      0K region: 0x7d9e486000 (0x7d9e483000)
I/scudo   ( 4409):   10 (   224): mapped:   6144K popped:   52578 pushed:   25060 inuse:  27518 total:  27532 rss:      0K releases:      1 last released:   4872K region: 0x7dae48a000 (0x7dae483000)
I/scudo   ( 4409):   11 (   288): mapped:    512K popped:    1428 pushed:     532 inuse:    896 total:   1190 rss:      0K releases:      2 last released:      8K region: 0x7dbe493000 (0x7dbe483000)
I/scudo   ( 4409):   12 (   352): mapped:    512K popped:    2060 pushed:    1498 inuse:    562 total:    912 rss:      0K releases:     27 last released:    100K region: 0x7dce48f000 (0x7dce483000)
I/scudo   ( 4409):   13 (   448): mapped:   4096K popped:   15945 pushed:    6902 inuse:   9043 total:   9057 rss:      0K releases:      0 last released:      0K region: 0x7dde48b000 (0x7dde483000)
I/scudo   ( 4409):   14 (   592): mapped:   1024K popped:    7698 pushed:    7033 inuse:    665 total:   1432 rss:      0K releases:      7 last released:      8K region: 0x7dee485000 (0x7dee483000)
I/scudo   ( 4409):   15 (   800): mapped:   6400K popped:   14814 pushed:    6640 inuse:   8174 total:   8184 rss:      0K releases:      5 last released:     20K region: 0x7dfe48a000 (0x7dfe483000)
I/scudo   ( 4409):   16 (  1104): mapped:  10752K popped:  113390 pushed:  113099 inuse:    291 total:   9972 rss:      0K releases:    698 last released:   4248K region: 0x7e0e48c000 (0x7e0e483000)
I/scudo   ( 4409):   17 (  1648): mapped:   6144K popped:    6526 pushed:    2864 inuse:   3662 total:   3674 rss:      0K releases:      4 last released:      8K region: 0x7e1e490000 (0x7e1e483000)
I/scudo   ( 4409):   18 (  2096): mapped:    256K popped:     114 pushed:      21 inuse:     93 total:    108 rss:      0K releases:      2 last released:     12K region: 0x7e2e491000 (0x7e2e483000)
I/scudo   ( 4409):   19 (  2576): mapped:    256K popped:     168 pushed:     102 inuse:     66 total:     72 rss:      0K releases:      7 last released:      4K region: 0x7e3e487000 (0x7e3e483000)
I/scudo   ( 4409):   20 (  3120): mapped:    768K popped:     636 pushed:     392 inuse:    244 total:    248 rss:      0K releases:      3 last released:      4K region: 0x7e4e491000 (0x7e4e483000)
I/scudo   ( 4409):   21 (  4112): mapped:  11520K popped:    5087 pushed:    2262 inuse:   2825 total:   2825 rss:      0K releases:      7 last released:      8K region: 0x7e5e485000 (0x7e5e483000)
I/scudo   ( 4409):   22 (  4624): mapped:    256K popped:      34 pushed:       4 inuse:     30 total:     32 rss:      0K releases:      1 last released:      4K region: 0x7e6e48d000 (0x7e6e483000)
I/scudo   ( 4409):   23 (  7120): mapped:    768K popped:     472 pushed:     367 inuse:    105 total:    105 rss:      0K releases:    187 last released:      8K region: 0x7e7e487000 (0x7e7e483000)
I/scudo   ( 4409):   24 (  8720): mapped:    512K popped:      51 pushed:      10 inuse:     41 total:     42 rss:      0K releases:      6 last released:      8K region: 0x7e8e48c000 (0x7e8e483000)
I/scudo   ( 4409):   25 ( 11664): mapped:    512K popped:      43 pushed:      22 inuse:     21 total:     30 rss:      0K releases:     11 last released:     84K region: 0x7e9e487000 (0x7e9e483000)
I/scudo   ( 4409):   26 ( 14224): mapped:    768K popped:      42 pushed:       6 inuse:     36 total:     40 rss:      0K releases:      9 last released:     36K region: 0x7eae48b000 (0x7eae483000)
I/scudo   ( 4409):   27 ( 16400): mapped:    512K popped:      30 pushed:       2 inuse:     28 total:     31 rss:      0K releases:      2 last released:     12K region: 0x7ebe493000 (0x7ebe483000)
I/scudo   ( 4409):   28 ( 18448): mapped:    256K popped:      10 pushed:       0 inuse:     10 total:     12 rss:      0K releases:      0 last released:      0K region: 0x7ece486000 (0x7ece483000)
I/scudo   ( 4409):   29 ( 23056): mapped:    512K popped:      14 pushed:       0 inuse:     14 total:     15 rss:      0K releases:      0 last released:      0K region: 0x7ede490000 (0x7ede483000)
I/scudo   ( 4409):   30 ( 29456): mapped:    768K popped:      28 pushed:       3 inuse:     25 total:     26 rss:      0K releases:      4 last released:     24K region: 0x7eee490000 (0x7eee483000)
I/scudo   ( 4409):   31 ( 33296): mapped:    768K popped:     231 pushed:     214 inuse:     17 total:     19 rss:      0K releases:      8 last released:     60K region: 0x7efe488000 (0x7efe483000)
I/scudo   ( 4409):   32 ( 65552): mapped:   1792K popped:      35 pushed:       8 inuse:     27 total:     27 rss:      0K releases:      3 last released:     60K region: 0x7f0e48f000 (0x7f0e483000)
I/scudo   ( 4409): Scudo OOM: The process has Exhausted 256M for size class 80.
W/ezis.montageap( 4409): Long monitor contention with owner pool-14-thread-1 (4872) at void android.graphics.pdf.PdfRenderer$Page.<init>(android.graphics.pdf.PdfRenderer, int)(PdfRenderer.java:315) waiters=0 in void android.graphics.pdf.PdfRenderer$Page.render(android.graphics.Bitmap, android.graphics.Rect, android.graphics.Matrix, int) for 2.560s
I/ezis.montageap( 4409): Starting a blocking GC NativeAlloc`

[....] goes on for 200 lines

/scudo   ( 4409): Scudo OOM: The process has Exhausted 256M for size class 65552.
I/scudo   ( 4409): Scudo ERROR: internal map or unmap failure
I/scudo   ( 4409):  (OOM)
I/scudo   ( 4409): 
F/libc    ( 4409): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4872 (pool-14-thread-), pid 4409 (ezis.montageapp)

**Comment by dillibabun** [comment]
Hi @mibkvr,

Greetings from Syncfusion.

We tried to reproduce the reported issue from our side but large PDFs are loaded properly as expected in SfPdfViewer widget. We also ensured our benchmark documents which is large (up to 50 MB) in different android device. We suspect that the issue might due to opening a high-quality PDF document in lower RAM android device. Please share us the following details which will be helpful for us to provide a prompt solution at the earliest.
1.	Device specification. RAM, Android OS version.
2.	Issue reproducing document (with dummy data).

You can also share the information by creating incident using below link.
https://www.syncfusion.com/support/directtrac/incidents/newincident 

Regards,
Dilli babu.
