### ISSUE TITLE
Series name with value from data

### ISSUE THREAD

**Issue by Abhijit-Revamp** [syncfusion/flutter-widgets#2112]
### Use case

I have two series (BarSeries) where I want the name coming from dataSource
Example: I have two series say "Current Month" and "Previous Month"
The dataSource contains the actual month names  like "August 2024" and "September 2024"

I would like to specify something like
```dart

                          title: ChartTitle(
                            text:
                                'For ${series[0].data[0].name} & ${series[1].data[1].name} month',
                            )
                            .....
                            BarSeries(
                              name: "Month: ${data[0].Name}",
                              dataSource: viewModel.submissionsGroupedByRank,
                              .....
                            )
                            BarSeries(
                              name: "Month: ${data[1].Name}",
                              dataSource: viewModel.submissionsGroupedByRank,
                              .....
                            )
```
Is it possible to embed data from datasource in the name

Also can this be enabled to ChartTitle

### Proposal

Ability to get variables from series data in ChartTitle and Series Name

**Comment by Mugunthan-Ramalingam** [comment]
Hi @Abhijit-Revamp,

**Query 1: Is it possible to embed data from data source in the name**
  
Yes, it is possible to include data into the [name](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartSeries/name.html) property of the series by mapping the corresponding data value index from the data source.

Code snippet:
```
final List<ChartData> augustData = [ChartData('August 2024', 25)];
final List<ChartData> septemberData = [ChartData('September 2024', 20)];

series: <CartesianSeries>[
   BarSeries<ChartData, String>(
      name: augustData[0].x,
      dataSource: augustData,
      xValueMapper: (ChartData data, int index) => data.x,
      yValueMapper: (ChartData data, int index) => data.y,
   ),
   BarSeries<ChartData, String>(
      name: septemberData[0].x,
      dataSource: septemberData,
      xValueMapper: (ChartData data, int index) => data.x,
      yValueMapper: (ChartData data, int index) => data.y,
   ),
],
```

**Query 2: can this be enabled to ChartTitle**

Yes, we can achieve this by assigning the values from the data source to the [chartTitle](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartTitle-class.html) text value by mapping the corresponding data value index from the data source.

Code snippet:

```
title: ChartTitle( text: 'For ${augustData[0].x} & ${septemberData[0].x} month',),
```

Output: 

![Screenshot 2024-10-04 154652](https://github.com/user-attachments/assets/1a89c70c-26da-41d8-bcdc-e660414aa6ee)

We have also attached a simple sample for your reference, which you can modify based on your requirements. If this does not address your case, please provide more details about your requirement, along with a screenshot or screen recording. This will help us to provide a solution more efficiently.

[gh_2112.zip](https://github.com/user-attachments/files/17258425/gh_2112.zip)


Regards,
Mugunthan.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket if you need further assistance on this.
