### ISSUE TITLE
SFDataGrid - Not able to get DatagridRow when columns are grouped on double tap

### ISSUE THREAD

**Issue by litterature** [syncfusion/flutter-widgets#2115]
### Bug description

We want to show a screen with details from DatagridRow on cell double tap. If we use the rowIndex provided in DataGridCellDoubleTapDetails, we don't get the good row when columns are grouped (works it no columns are grouped). We want a way to get the good row data on double tap.

### Steps to reproduce

1. Double tap on a line, info should match with the line tapped
2. Group a column
3. Try again -> the info does not match the line tapped

### Code sample

<details open><summary>Code sample</summary>

```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: Column(
        children: [
          Align(
            alignment: Alignment.centerLeft,
            child: Padding(
              padding: const EdgeInsets.all(5),
              child: ElevatedButton(
                onPressed: _initGrouping,
                child: const Text('Group Columns'),
              ),
            ),
          ),
          Expanded(
            child: SfDataGrid(
              source: employeeDataSource,
              allowExpandCollapseGroup: true,
              allowFiltering: true,
              allowSorting: true,
              columns: columns,
              columnWidthMode: ColumnWidthMode.lastColumnFill,
              columnWidthCalculationRange: ColumnWidthCalculationRange.allRows,
              onCellDoubleTap: (details) {
                final doubleTappedRow = employeeDataSource
                    .effectiveRows[details.rowColumnIndex.rowIndex - 1];

                showDialog(
                  context: context,
                  builder: (context) => AlertDialog(
                    title: Text(
                      doubleTappedRow
                          .getCells()
                          .firstWhere((c) => c.columnName == 'name')
                          .value
                          .toString(),
                    ),
                    content: Text(
                      doubleTappedRow
                          .getCells()
                          .firstWhere((c) => c.columnName == 'salary')
                          .value
                          .toString(),
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/6acb5fab-8e05-4ea2-9a81-a18339b62dff

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
no exception
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.24.3, on Microsoft Windows [version 10.0.26100.1742], locale fr-CA)
    • Flutter version 3.24.3 on channel stable at C:\Users\[username]\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (4 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\[username]\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\[username]\AppData\Local\Android
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34902.65
    • Windows 10 SDK version 10.0.22621.0

[✓] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[✓] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin version 80.0.2
    • Dart plugin version 242.20629

[✓] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.2
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[✓] VS Code (version 1.93.1)
    • VS Code at C:\Users\[username]\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.26100.1742]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.90
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.79

[✓] Network resources
    • All expected network resources are available.
```

</details>

**Comment by abineshPalanisamy** [comment]
Hi @litterature ,
 
As of now, DataGrid does not have support for obtaining the row using the RowColumnIndex from the Tap callbacks when using grouping. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [50282](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F50282%2Fsupport-for-obtaining-the-row-using-the-rowcolumnindex-from-the-oncelltap-callback&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C482d936724974b4dee6908dce766a0e6%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638639675162813099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=XnJO80jr83veS3YktCLhFC5bq4IHYXzAQY6u4GqZNNE%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by litterature** [comment]
Hi! Thanks for your answer! Are you aware of a temporay fix for this?

**Comment by abineshPalanisamy** [comment]
Hi @litterature ,

In SfDataGrid, we manage **grouped rows as an internal collection at the source level**. Currently, we do not expose grouped rows at the sample level. The effectiveRows only returns a copy of the **DataGridSource.rows**. Therefore, it is not possible to fetch rows by their respective rowIndex at the sample level when grouping is applied. Consequently, we are currently unable to provide a temporary solution for this behavior.
 
However, as mentioned in our previous response, we have already considered your feature request, and we will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then.
 
Regards,
Abinesh P

**Comment by litterature** [comment]
ok! Thanks!

**Comment by ashok-kuvaraja** [comment]
Hi @litterature,

We are closing this issue now. You can follow the feedback link for further updates. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K
