### ISSUE TITLE
SfDateRangePicker enable to add month view radius

### ISSUE THREAD

**Issue by dath7** [syncfusion/flutter-widgets#2117]
### Use case

I want to add some border radius to month view in SfDateRangePicker in DateRangePickerView.month mode

### Proposal

- Current: 
![Screenshot 2024-10-08 at 17 46 17](https://github.com/user-attachments/assets/241ed11d-00ee-41c9-99d4-986d1d4330f3)

- Expected:
![Screenshot 2024-10-08 at 17 45 24](https://github.com/user-attachments/assets/41963ab2-aaec-4b43-b7ec-f0c611bfdd44)

**Comment by Kaviyarasansf4298** [comment]
Hi @dath7 ,

We would like to inform you that, according to the current implementation of the [SfDateRangePicker](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker-class.html), there is no support to achieve the expected result as the [SfDateRangePicker](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker-class.html) does not support applying a border radius specifically to the body of the month view.

However, you can customize the border radius for the entire [SfDateRangePicker](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker-class.html) widget by wrapping it with the ClipRRect widget based on the code snippet below.

```
ClipRRect(
  borderRadius: BorderRadius.circular(20),
  child: SfDateRangePicker(
    backgroundColor: Colors.lightGreen.shade500,
    headerStyle: const DateRangePickerHeaderStyle(
      backgroundColor: Colors.amber,
    ),
  ),
),
```
Also attached the output for the shared code snippet below for your reference. If you have any further queries, please free to reach us. 
<img width="381" alt="641488" src="https://github.com/user-attachments/assets/ec90512d-dd5f-4686-b15c-cdf37d5e08df">

Regards,
Kaviyarasan Arumugam.

**Comment by dath7** [comment]
Thank u so much for this reply.
