### ISSUE TITLE
[Syncfusion_Flutter_Datagrid] Can I separate the checkbox event and the selection event? Please 

### ISSUE THREAD

**Issue by gltiennd** [syncfusion/flutter-widgets#2118]

**Comment by abineshPalanisamy** [comment]
Hi @gltiennd ,
 
As of now, DataGrid does not have support for a callback to listen for value changes when the DataGrid checkbox is checked/unchecked.  We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [52162](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F52162%2Fsupport-for-a-callback-to-listen-for-value-changes-when-the-datagrid-checkbox-is&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cfd8e84d32c0f4f82976908dce833bbb5%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638640556086819526%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=JgbkSiS1Qv3tPU7eOxFizFnT99Om08fTAIW3PdVi7ac%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @gltiennd,

We are closing this issue now. You can follow the feedback link for further updates. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K
