### ISSUE TITLE
[syncfusion_flutter_datagrid] Does Lib support features like the video below? Thanks

### ISSUE THREAD

**Issue by gltiennd** [syncfusion/flutter-widgets#2122]
### Use case

https://github.com/user-attachments/assets/00fbebbe-98d4-4382-8046-e160dc5ad66f

### Proposal

![Screenshot 2024-10-11 at 18 18 00](https://github.com/user-attachments/assets/3c1829dd-298d-430f-908f-544ca2c41c74)

**Comment by abineshPalanisamy** [comment]
Hi @gltiennd ,

Based on the video provided, we are not clear about the expectations. Therefore, we have suggested some responses based on what we think is expected. In the SfDataGrid, we offer support for grouping, which allows related records to be combined into a hierarchical structure. Each group is represented by a CaptionSummaryRow, which appears at the top of each group and displays the summary value for that group.
 
UG - [Grouping](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fdatagrid%2Fgrouping&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7Cb7b820ce6d274637821a08dcec21586f%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638644875160878075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=sLjXvcjUkAbBV1enbR2X1E3kV0oJeXUb%2FPTUFp9kM6g%3D&reserved=0)
 
To assist you further and gain a better understanding of your expectations, we kindly request that you provide any additional details and share the specific use cases related to the behavior you are seeking. This information will greatly help us investigate your query and provide a prompt and appropriate solution.
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @gltiennd,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K
