### ISSUE TITLE
[syncfusion_flutter_calendar] Add indicator for selected day in schedule view sfcalendar

### ISSUE THREAD

**Issue by dath7** [syncfusion/flutter-widgets#2131]
### Use case

Currently, i've only found todayHighlightColor props that similar to this but only apply for today.
 
<img width="800" alt="Screenshot 2024-10-15 at 11 43 57" src="https://github.com/user-attachments/assets/876e1618-fdbe-46f5-b1d2-4725321a7424">

### Proposal

I want to add selected day indicator in schedule view in sfcalendar. Currently, i've only found todayHighlightColor props that similar to this but only apply for today. Can you provide support for my case? 
Thanks a lot.
 
<img width="800" alt="Screenshot 2024-10-15 at 11 43 57" src="https://github.com/user-attachments/assets/876e1618-fdbe-46f5-b1d2-4725321a7424">

**Comment by ThilipChandru** [comment]
Hi @dath7,



There is currently no direct support to achieve the color for selected date in schedule view. We have also explored a custom implementation, but unfortunately, it was not successful. We apologize for any inconvenience. If you have any further questions or need assistance, please don’t hesitate to contact us.

 

Regards,
Thilip Chandru.

**Comment by dath7** [comment]
I hope this feature will be avaiable in the future. Thank u very much.
