### ISSUE TITLE
How to change background color of filter popup menu?

### ISSUE THREAD

**Issue by MalikSamiAwan** [syncfusion/flutter-widgets#2147]
<img width="563" alt="Screenshot 2024-10-23 at 7 52 18 PM" src="https://github.com/user-attachments/assets/1ce32311-85c8-4d09-bbb0-416ef0e99619">

**Comment by abineshPalanisamy** [comment]
Hi @MalikSamiAwan ,
 
As of now, the DataGrid does not have support for customizing the appearance of the filter pop-up menu . We have 
already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [51938](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F51938%2Fsupport-for-customizing-the-appearance-of-the-filter-pop-up-menu&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C534ca448e90b47064d4308dcf3f67257%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638653487016186566%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cLjo3K7Y1VuOWls2kPvmrhn39crmVkQB%2BtAw4IIEUgo%3D&reserved=0)
 
Regards,
Abinesh P
