### ISSUE TITLE
If buildRows is filtered/sort than highlighted row messes up

### ISSUE THREAD

**Issue by MalikSamiAwan** [syncfusion/flutter-widgets#2148]
so if we apply sorting to any of columns and than highlight does not reflect rows located in table
as in demo you can see i am clicking on row 1 and its highlighting row 5 

 DataGridRowAdapter(
      color: currentRowIndex==highlightRowIndex?highlightRowColor:Colors.transparent,
)

https://github.com/user-attachments/assets/107ac49b-4e0a-4164-98af-a27d8ee2e77b

**Comment by abineshPalanisamy** [comment]
Hi @MalikSamiAwan ,

It seems you are trying to add background color to rows based on the tapped row index. **When performing sorting or filtering, you can use** [DataGridSource.effectiveRows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FDataGridSource%2FeffectiveRows.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C1f413e7a3fcf4fe9b8a108dcf3f668a7%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638653486853864379%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=7q3hug4SMRyNg1yIHcPdreNAR7buqBq7OMy8p%2B2DEwI%3D&reserved=0) **to retrieve the row index**. This method returns a copy of DataGridSource.rows, which contains the sorted or filtered collection if sorting or filtering is applied in the DataGrid. Use this property to get the corresponding visible row index for customizations such as setting alternate row colors, changing row colors based on the row index, and more. We have included a sample for your reference. Please review it for further details.

- **Sample :** [SfDataGrid.zip](https://github.com/user-attachments/files/17502644/SfDataGrid.zip)

 
Regards,
Abinesh P
