### ISSUE TITLE
SplineSeries fixed yAxis labels

### ISSUE THREAD

**Issue by roderikpeeters** [syncfusion/flutter-widgets#215]
Hi there,

On this momeny my yAxis lavels depends on the values in the data.

For example:

1.44
2.44
3.44

However I would like to set the labels to:
1.00
2.00
3.00 etc..
How is this possible? I don't want to change the format to no decimals because the labels won't be on the correct place.

**Comment by Dharanipalani** [comment]
Hi @roderikpeeters,

Thanks for the interest in our Flutter charts. We have analyzed your query and like to tell you that the y-axis intervals are calculate based on the data source and so you get labels in decimals and we suggest you use the [minimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/minimum.html), [maximum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/maximum.html), and [interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html) properties from the numeric axis as like in the code snippet and we attached the screenshot for your reference, kindly make use of it.

code snippet
```
primaryYAxis: NumericAxis(minimum: 1, maximum: 5, interval: 1),
```

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/117616977-854d3e80-b189-11eb-8c4c-ca12fb0fc113.png)


Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by roderikpeeters** [comment]
Ah thanks, what I've done is that I made the minimum and maximum without decimals. So that the Y Axis is also without decimals. Thanks!
