### ISSUE TITLE
exportToPdfDocument / exportToExcelWorkbook -> column heading for multiple languages

### ISSUE THREAD

**Issue by Abhijit-Revamp** [syncfusion/flutter-widgets#2156]
### Use case

My data grid has language specific header text in DataGrid. 
The "columnName" in GridColumn is a variable name while the value (displayed in Grid) is NOT SAME as "columnName" (picked up from language specific strings)

Is there a way to ensure the exported column names are same as the one displayed in the sfDataGrid?

See the attached screenshots
1. DataGrid
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/4ced2b32-83ba-4151-b9d9-1ca2fb43a20b">

2. Exported PDF
<img width="934" alt="image" src="https://github.com/user-attachments/assets/146c2855-12a3-464b-82cd-2bcbfcf41e5e">

3. Exported Excel
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/bd2f139d-767a-47ad-b880-269b24b27f1f">

### Proposal

Option to map columnName to exported header string

**Comment by abineshPalanisamy** [comment]
Hi @Abhijit-Revamp ,

Please refer to the following Knowledge Base link for a deeper understanding of How to customize column header text during Excel and PDF export in Flutter DataTable. You can customize the provided code to suit your specific requirements.

KB link - [Excel and PDF export](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.syncfusion.com%2Fkb%2Farticle%2F12596%2Fhow-to-customize-column-header-text-during-excel-and-pdf-export-in-flutter-datatable&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C28f87714ffd842aa703408dcfd5c8ab8%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638663821117578014%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ArBUt%2BCdEJ6V%2FjStKtk1qhRzcU2l3u%2Bi54LIE%2FczegE%3D&reserved=0)
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment]
Hi @Abhijit-Revamp,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K
