### ISSUE TITLE
PDF Viewer needs to export SfPdfViewerTheme and SfPdfViewerThemeData?!

### ISSUE THREAD

**Issue by tlueder** [syncfusion/flutter-widgets#218]
Hi, 

as far as can tell it is not possible to change certain theme colors,  like background color an so on.

Other plugins have Sf(PlugInName)ThemeData to do that, but the PDF Viewer does not export its theming.

Is this a bug or do I miss something?

Thanks for your help.

Thomas

**Comment by sarathkumar50** [comment]
Hi @tlueder,

Greetings from Syncfusion.

We have exposed SfPdfViewerTheme for customizing the appearance of SfPdfViewer widget. The following code example illustrates how to modify the appearance of SfPdfViewer widget.

```
import 'package:flutter/material.dart';import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';import 'package:syncfusion_flutter_core/theme.dart';void
main() {runApp(MaterialApp(title: 'Syncfusion PDF Viewer Demo',home: HomePage(),));}///class
HomePage extends StatefulWidget {@override_HomePage createState() => _HomePage();}class
_HomePage extends State<HomePage> {final GlobalKey<SfPdfViewerState>
_pdfViewerKey = GlobalKey();@overrideWidget build(BuildContext context) {return
Scaffold(appBar: AppBar(title: const Text('Syncfusion Flutter PdfViewer')),body: SfTheme(data: SfThemeData(pdfViewerThemeData: SfPdfViewerThemeData(brightness: Brightness.dark,backgroundColor: Colors.red,),),child: SfPdfViewer.asset('assets/sample.pdf',key:
_pdfViewerKey,),),);}}
```

To know more about theming in our Syncfusion Flutter widget, kindly refer the following User-Guide link.

https://help.syncfusion.com/flutter/themes/themes#using-sftheme-widget 

 
Regards,
Sarath Kumar Prakash.
