### ISSUE TITLE
Can we create complex grid with merge cells and some editables and coniditonal formatting on cell like the attached image?

### ISSUE THREAD

**Issue by MalikSamiAwan** [syncfusion/flutter-widgets#2181]
is this ui possible with this package:
1: Light Yellow Backgrounds are editable fields
2: yellow and orange are conditional formatted
3: green and white background are readonly
4: we have merge cells

![sample](https://github.com/user-attachments/assets/bda1ea02-892e-4985-a7f5-e91e40d95e35)

**Comment by SethupathyD** [comment]
Hi @MalikSamiAwan 

**Light Yellow Backgrounds are editable fields and green and white background are readonly.**
You can achieve this in flutter dataGrid and we had shared the Kb documentation for your reference.
KB link : [Editing in Flutter DataGrid](https://help.syncfusion.com/flutter/datagrid/editing)
 
**yellow and orange are conditional formatted**
From the attached image, we suspect you are inquiring about conditional styling of alternating cells. We have shared the KB documentation for your reference. If your requirement differs, kindly provide additional details to help us provide the correct solution.
Kb link : [Conditional Styling alternate cells](https://help.syncfusion.com/flutter/datagrid/conditional-styling#styling-alternate-cells)
 
**Merge Cells.**

As of now, DataGrid does not have support to merge the rows and cells . We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,
 
Feedback link: [23230](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F23230%2Fsupport-to-merge-the-rows-and-cells&data=05%7C02%7Cfarjanaparveena%40syncfusion.com%7C607aee6717f24cb4175708dce81fa069%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638640469740122209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=wZfEtzgo87mGg3PGcBaatnqScesPV2WPaI%2B13e5bDHo%3D&reserved=0)

Regards,
Sethupathy D.

**Comment by ashok-kuvaraja** [comment]
Hi @MalikSamiAwan,
 
We are closing this issue now. You can follow the feedback link for further updates. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K
