### ISSUE TITLE
Adding Read Excel Workbook Ability From Uint8list or File to Flutter XlsIO Library

### ISSUE THREAD

**Issue by berkbb** [syncfusion/flutter-widgets#220]
Hi, it is a feature request. Please add Excel workbook ability from Uint8list or File to Flutter XlsIO Library. Thanks.

**Comment by Sridhar-Sukumar** [comment]
Hi @berkbb, 

Currently, we don't have support to read Excel using Flutter XlsIO library.

However, you can create Excel files using "syncfusion_flutter_xlsio" library with the following features.

1. Create a simple Excel document
2. Add text, number, and datetime values
3. Add formulas
4. Apply formatting
5. Add images
6. Add charts
7. Add hyperlinks to texts and images
8. Protect workbooks and worksheets
9. AutoFit rows and columns
10. Insert or delete rows and columns
11. Apply conditional formatting

To know more about the "syncfusion_flutter_xlsio" library please refer the following link. https://pub.dev/packages/syncfusion_flutter_xlsio

Regards,
Sridhar.

**Comment by amoslai5128** [comment]
> Hi @berkbb,
> 
> Currently, we don't have support to read Excel using Flutter XlsIO library.
> 
> However, you can create Excel files using "syncfusion_flutter_xlsio" library with the following features.
> 
> 1. Create a simple Excel document
> 2. Add text, number, and datetime values
> 3. Add formulas
> 4. Apply formatting
> 5. Add images
> 6. Add charts
> 7. Add hyperlinks to texts and images
> 8. Protect workbooks and worksheets
> 9. AutoFit rows and columns
> 10. Insert or delete rows and columns
> 11. Apply conditional formatting
> 
> To know more about the "syncfusion_flutter_xlsio" library please refer the following link. https://pub.dev/packages/syncfusion_flutter_xlsio
> 
> Regards,
> Sridhar.

Thanks for the reply, but any road map for adding the read excel feature?  It'd super helpful for flutter web development.

**Comment by berkbb** [comment]
I wish they are plannig support it quickly :) @amoslai5128

**Comment by Sridhar-Sukumar** [comment]
Hi @berkbb,

We have the plan to provide this support. But currently, we don't have a definite timeline. 

Regards,
Sridhar.

**Comment by berkbb** [comment]
Thanks @Sridhar-Sukumar :)

**Comment by rshrc** [comment]
No update regarding this it seems @Sridhar-Sukumar
