### ISSUE TITLE
ColumnSeries width of area outside container

### ISSUE THREAD

**Issue by roderikpeeters** [syncfusion/flutter-widgets#222]
I created a chart with ColumnSeries inside a container with a width of double.infinity and padding of 15 to all sides.

I have a few datapoints inside, but for some reason I can't manage to get all the datapoints inside. As you can see on the screenshot, the last datapoint is cut off. While there is enough space to show all the lines.

Any solution on how to fix this? I want all the bars to be inside the area.

<img width="322" alt="Schermafbeelding 2021-05-12 om 13 27 50" src="https://user-images.githubusercontent.com/60385019/117968883-fb3adc80-b326-11eb-99a7-5a2717e0e857.png">

**Comment by Dharanipalani** [comment]
Hi @roderikpeeters,

Greetings from the team at Syncfusion. We have investigated your query and like to tell you that you there is not enough space for the column to render. You can overcome this by setting the minimum and maximum by customizing the range in the respective axis or also you can set the range padding to additional. You can refer about these in the below support document links.

[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range)
[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range)

Kindly revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P
