### ISSUE TITLE
In TrackballDisplayMode.groupAllPoints show only values that exist at that given point

### ISSUE THREAD

**Issue by petoknm** [syncfusion/flutter-widgets#225]
I do not want to see series that are not intersecting the trackball. Currently (in the screenshot) you can see also values of other series.

![screenshot](https://user-images.githubusercontent.com/5087675/117988453-b79e9d80-b33b-11eb-9966-f1d7576cc2c5.png)

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Thank you for the interest in our Flutter charts. We have investigated your request and can inform you that in group mode, the default behavior is for the trackball to display the information of all the series in the chart. If you just want to show the series on the touch spot, then you can set the nearestPoint using the [tooltipDisplayMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/tooltipDisplayMode.html) property in the [trackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/trackballBehavior.html).

Kindly revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P
