### ISSUE TITLE
Unable to view text on fields edited or annotated on PDF files using Adobe Acrobat

### ISSUE THREAD

**Issue by anil-sookshum** [syncfusion/flutter-widgets#226]
I am trying to use [syncfusion_flutter_pdfviewer](https://pub.dev/packages/syncfusion_flutter_pdfviewer) as a PDF viewer in my app. But I am not able to view the text that was added to the PDF using the Adobe Acrobat reader.

[Source PDF file](https://www.asthma.org.uk/globalassets/health-advice/resources/adults/adult-asthma-action-plan.pdf)
[Edited PDF file](https://pdfhost.io/v/Y43rWHOoq_asthmaplanacrobat_editedpdf.pdf)
Text added to fields like "Next asthma review date", "Name", "Phone number" on first page of edited PDF is not visible in PDF viewer.

Is this a known bug? And is there a rough timeline to fix this?

Thanks

**Comment by dillibabun** [comment]
Hi @anil-sookshum ,

At present we do not have support for "PDF forms”. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.
 
Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 4 main release. We will let you know when this feature is implemented. The status of the feedback can be tracked using the following link.
[https://www.syncfusion.com/feedback/25265/support-for-pdf-form](
https://www.syncfusion.com/feedback/25265/support-for-pdf-form)  
 
Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.
