### ISSUE TITLE
[Suggestion] Allow to add pages from one pdf document to other pdf document in syncfusion_flutter_pdf plugin

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#229]
Hello,
syncfusion_flutter_pdf is a great plugin but it would great if you add functionality to add pages from one document to another document. It would help in many use cases.

Thanks for providing this awesome plugin.

**Comment by chinnumuniyappan** [comment]
Hi @brightseagit ,

Greetings from Syncfusion. We can copy the PDF document content from one document to another one by using the [createTemplate](https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPage/createTemplate.html) option available on the PdfPage. Refer to the following code for further details. Kindly try this on your end and let us know whether it is achieving your requirement.

```dart
  //Load the document.
  PdfDocument document =
      PdfDocument(inputBytes: File('gis_succinctly.pdf').readAsBytesSync());

  //Create new second document.
  PdfDocument newDocument = PdfDocument();

  //Get the page from existing document.
  PdfPage page = document.pages[0];

  //Create the page as template.
  PdfTemplate template = page.createTemplate();

  //Set page size and add page.
  newDocument.pageSettings.size = page.size;
  newDocument.pageSettings.margins.all = 0;

  PdfPage newPage = newDocument.pages.add();

  //Draw the template to the new document page.
  newPage.graphics.drawPdfTemplate(template, Offset(0, 0));

  //Save the destination document.
  List<int> bytes = newDocument.save();

  File('output.pdf').writeAsBytesSync(bytes);

  //Dispose documents.
  newDocument.dispose();
  document.dispose();
```
Regards, 
Chinnu M

**Comment by brightseagit** [comment]
Thanks 👍 for giving this detailed reply. I didn't knew about these methods before. So, I would definitely try these tomorrow.

**Comment by brightseagit** [comment]
This worked.

I also made a few changes to make it work with different size page pdf.
I'm providing an example for future reference to anyone:

```dart
//Load the document.
PdfDocument document =
   PdfDocument(inputBytes: File('gis_succinctly.pdf').readAsBytesSync());

//Create new second document.
PdfDocument newDocument = PdfDocument();

//Function to return new document with existing document pages
Future<PdfDocument> creatingNewPdfDocumentFromOld() async {
       List<PdfPage> pageList = [];
       List<PdfTemplate> pageTemplateList = [];

       //Loop to get pages from existing document.
       for (var i = 0; i < document.pages.count; i++) {
         pageList.add(document.pages[i]);

         //Create the page as template and then add it to template list
         pageTemplateList.add(document.pages[i].createTemplate());
       }

       //Setting specific page sizes and adding pages.
       for (var i = 0; i < document.pages.count; i++) {

         //Creating new section in the document
         PdfSection section1 = newDocument.sections!.add();

         //Changing section orientation according to page height & width
         if (pageList[i].size.height < pageList[i].size.width) {
           section1.pageSettings.orientation = PdfPageOrientation.landscape;
         } else {
           section1.pageSettings.orientation = PdfPageOrientation.portrait;
         }

         //Assigning the page size to document section
         section1.pageSettings.size = pageList[i].size;
         section1.pageSettings.margins.all = 0;
         PdfPage newPage = section1.pages.add();

         //Draw the template to the new document page.
         newPage.graphics.drawPdfTemplate(pageTemplateList[i], Offset(0, 0));
       }

       return newDocument;
 }

//Save the destination document.
List<int> bytes = await creatingNewPdfDocumentFromOld().then((value) => 
         value.save());
File('output.pdf').writeAsBytesSync(bytes);

//Dispose documents.
newDocument.dispose();
document.dispose();

```

**Comment by brightseagit** [comment]
Hello, 
I'm reopening this issue as I am facing the following issues:-
1. Issue copying pages from this [0706jpeg2000king.pdf](https://github.com/syncfusion/flutter-widgets/files/6809935/0706jpeg2000king.pdf) pdf to new document -  When I tried copying the pages I found that the pages copied to the new document have changed rotation. 
2. I'm losing the annotation data while copying the pages.

Thank you.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thanks for the information provided.

**Query:** Issue copying pages from this 0706jpeg2000king.pdf pdf to new document - When I tried copying the pages I found that the pages copied to the new document have changed rotation.

**Response:** Currently we are not having support to get or set rotation to an existing PDF document page. We will consider it as a usability feature and include it in our upcoming weekly patch release which will be available on 27th July 2021. You can track the status of this support implementation by https://www.syncfusion.com/feedback/26998/page-rotation-support-for-an-existing-pdf-document

**Query:** I'm losing the annotation data while copying the pages.

**Response:** If the PDF document content copied from one document to another one by using the createTemplate option, the annotations are not preserved. This is our actual behavior. We can preserve annotations while copying pages from an existing PDF only with the merge PDF support. We have already logged the feature request. This feature will be implemented in any of our upcoming release. You can refer to the below feedback links for further follow up,
https://www.syncfusion.com/feedback/25644/add-support-to-merge-pdf-documents

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Hello,
Thanks for the prompt reply and adding support to get or set rotation to an existing PDF 👍.
But I think you misunderstood my 1st query. I was stating that when I create a template from a pdf page generally I get the same copy of the content as a template without any change in rotation but with this particular pdf ([0706jpeg2000king.pdf](https://github.com/syncfusion/flutter-widgets/files/6817645/0706jpeg2000king.pdf)), I'm receiving a rotated template. So, I was looking if you could help me understand what's the reason for that.

For example:-
| This is how the pdf looks originally  | And this is how it looks after converting it to the template and adding it to a new document |
| ------------- | ------------- |
| ![Screenshot_1626279312](https://user-images.githubusercontent.com/72334435/125656702-fde9fc00-4203-42fa-bea3-e727a9acd5cd.png)  | ![Screenshot_1626279477](https://user-images.githubusercontent.com/72334435/125656907-3c553027-5ee2-4647-84a0-6eb7e202b4a0.png)  |

**Conclusion - As you would have noticed that it has rotated itself automatically after getting converted to a template and added to a document.**

Now take a look at another example with a different pdf ([test pdf 2.pdf](https://github.com/syncfusion/flutter-widgets/files/6817630/test.pdf.2.pdf)) which has the same dimensions as the previous one but it works fine for it:-
| This is how the other pdf looks originally  | And this is how it looks after converting it to the template and adding it to a new document |
| ------------- | ------------- |
| ![Screenshot_1626279662](https://user-images.githubusercontent.com/72334435/125657618-db42a517-9226-477f-b5f6-19a01e3ab5da.png)  | ![Screenshot_1626279774](https://user-images.githubusercontent.com/72334435/125657726-0c5e4780-286f-422d-a546-9006c85701d9.png)  |

**Conclusion - As you would have noticed that it didn't rotate itself even both the pdf have the same dimensions.**

Now, what I would like to know is the reason behind this distinct behavior and how could I fix it.

Thank you.

**Comment by Anand3595** [comment]
Hi @brightseagit,

The input document [0706jpeg2000king.pdf](https://github.com/syncfusion/flutter-widgets/files/6817645/0706jpeg2000king.pdf) having 270 degree rotated pages, the page size of this document is 612x792, Due to the 270 degree rotation the document pages looks like an landscape view. If we create a template from this page, the template only creates the page content and does not add the rotation to the newly created page. So we have to create a new page with 270 degree rotation before drawing the template. Then only the newly created document is displayed as like the existing PDF document.

The [test pdf 2.pdf](https://github.com/syncfusion/flutter-widgets/files/6817630/test.pdf.2.pdf) having no rotation and it page size is (720, 540) as a width and height values, So it is displayed like landscape view.

So the problem is due to the rotation of the existing PDF document. As we said before, we don’t have support to retrieve the rotation angle from the existing PDF document page. We will add this support and it will be available in our weekly release on July 27th, 2021. After that we can get the rotation from the existing PDF document and set it to the newly created document as follows.

```
//Setting specific page sizes and adding pages.
for (int i = 0; i < document.pages.count; i++) {
  //Creating new section in the document
  final PdfSection section1 = newDocument.sections!.add();

  //Set rotation
  section1.pageSettings.rotate = pageList[i].rotation;

  //Changing section orientation according to page height & width
  if (pageList[i].size.height < pageList[i].size.width) {
    section1.pageSettings.orientation = PdfPageOrientation.landscape;
  } else {
    section1.pageSettings.orientation = PdfPageOrientation.portrait;
  }
  //Assigning the page size to document section
  section1.pageSettings.size = pageList[i].size;
  section1.pageSettings.margins.all = 0;
  final PdfPage newPage = section1.pages.add();
  //Draw the template to the new document page.
  newPage.graphics
      .drawPdfTemplate(pageTemplateList[i], const Offset(0, 0));
}
```
Please find the feedback link from https://www.syncfusion.com/feedback/26998/page-rotation-support-for-an-existing-pdf-document to track status of this support implementation.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thank you very much for this clarification. Now I completely understand what you meant before by getting the rotation 👍.

**Comment by Anand3595** [comment]
Hi @brightseagit , 
 
We have included the support to get or set rotation to an existing PDF document page in our latest weekly patch release with version [19.2.49-beta](https://pub.dev/packages/syncfusion_flutter_pdf/versions/19.2.49-beta). We can get rotation applied on existing PDF page by using ‘**PdfPage.rotation**’ property and assign it into ‘**section1.pageSettings.rotate**’ to preserve page rotation while copying pages as template.

```
//Setting specific page sizes and adding pages.
for (int i = 0; i < document.pages.count; i++) {
  //Creating new section in the document
  final PdfSection section1 = newDocument.sections!.add();

  //Set rotation
  section1.pageSettings.rotate = pageList[i].rotation;

  //Changing section orientation according to page height & width
  if (pageList[i].size.height < pageList[i].size.width) {
    section1.pageSettings.orientation = PdfPageOrientation.landscape;
  } else {
    section1.pageSettings.orientation = PdfPageOrientation.portrait;
  }
  //Assigning the page size to document section
  section1.pageSettings.size = pageList[i].size;
  section1.pageSettings.margins.all = 0;
  final PdfPage newPage = section1.pages.add();
  //Draw the template to the new document page.
  newPage.graphics
      .drawPdfTemplate(pageTemplateList[i], const Offset(0, 0));
}
```

Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/ReadPdfSample-852110359

Please let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks, this resolves the issue of rotation while creating a pdf form template,
