### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by noman404** [syncfusion/flutter-widgets#23]
I'm getting the following error when compiling 

Compiler message:
../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-18.3.40-beta/lib/src/slider.dart:1232:7: Error: The non-abstract class '_RenderSliderElement' is missing implementations for these members:
RenderObjectElement.insertChildRenderObject
RenderObjectElement.moveChildRenderObject
RenderObjectElement.removeChildRenderObject

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Noman,

Greetings from Syncfusion.

The methods shown in the error log is deprecated in the Flutter older version. To resolve this issue, kindly update the Flutter version to 1.22.0. 

**Link:** https://github.com/flutter/flutter/pull/64189 

Feel free to contact us, we are always happy to help you.

Regards,
Lakshmi R.

**Comment by noman404** [comment]
Sorry for the late reply! thanks for the feedback. but due to the time limit, I had to develop UI by myself. But appreciate your quick response!
