### ISSUE TITLE
How to change icon navigation arrow Date Picker

### ISSUE THREAD

**Issue by padgithub** [syncfusion/flutter-widgets#230]
Can you guide me how to change this icon?
Thank u
<img width="317" alt="Screen Shot 2021-05-14 at 23 14 27" src="https://user-images.githubusercontent.com/33429444/118298998-6a245b00-b50a-11eb-9c0c-a1003f1e3c0f.png">

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Can you guide me how to change this icon?**

Yes, it is possible to change the navigation arrow icon by using a custom header for the picker. We have a KB document for a custom header. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/11427/how-to-customize-the-header-view-of-the-flutter-date-range-picker

By adding the required icons in the highlighted place, you can change navigation arrow icons. Please find the code snippet for the same.

**Code snippet:**
```
Row(
  children: <Widget>[
    Container(
      height: cellWidth,
      width: cellWidth + 10,
    ),
    Container(
        width: cellWidth,
        height: cellWidth,
        color: Color(0xFFfa697c),
        child: IconButton(
          **icon: Icon(Icons.arrow_left),**
          color: Colors.white,
          iconSize: 20,
          highlightColor: Colors.lightGreen,
          onPressed: () {
            setState(() {
              _controller.backward!();
            });
          },
        )),
    Container(
      color: Color(0xFFfa697c),
      height: cellWidth,
      width: cellWidth * 4.5,
      child: Text(headerString,
          textAlign: TextAlign.center,
          style: TextStyle(
              fontSize: 25, color: Colors.white, height: 1.4)),
    ),
    Container(
        width: cellWidth,
        height: cellWidth,
        color: Color(0xFFfa697c),
        child: IconButton(
          **icon: Icon(Icons.arrow_right),**
          color: Colors.white,
          highlightColor: Colors.lightGreen,
          onPressed: () {
            setState(() {
              _controller.forward!();
            });
          },
        )),
    Container(
      height: cellWidth,
      width: cellWidth,
    )
  ],
),

```
By using the **forward**() and **backward**() methods of the **DateRangePickerController** you can navigate to previous and next visible dates of the calendar. Please find the UG document for the same.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatically-change-to-adjacent-dates

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
