### ISSUE TITLE
syncfusion flutter pdf viewer not supporting single page view

### ISSUE THREAD

**Issue by ajaygosh102** [syncfusion/flutter-widgets#231]

**Comment by dillibabun** [comment]
Hi ajaygosh102,

Greetings from Syncfusion.

At present we do not have support for “Single page view” in SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. 
Based on our present commitments and the above parameters, this feature is expected to be implemented on our 2021 Volume 3 main release. We will let you know when this feature is implemented. The status of this feature can be tracked using following link. 
https://www.syncfusion.com/feedback/18491/support-for-page-by-page-view 

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part. 

Regards,
Dilli babu.
