### ISSUE TITLE
Syncfusion chart license 

### ISSUE THREAD

**Issue by killerm250m** [syncfusion/flutter-widgets#232]
Hello, And thanks for this amazing library.
I heard that this library is free to use so that I am currently using it in my app without any problem so I wonder if I can use it in the production app without any license nor any configuration.

Thanks.

**Comment by dharanidharandharmasivam** [comment]
Hi @killerm250m ,

To use our package in your production app, it is mandatory to have a license. It can be either a Syncfusion community license or the Syncfusion commercial license.

To be qualified for the Syncfusion Community License Program you must have gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization and agree to be bound by Syncfusion’s terms and conditions. If you are not qualified for the community license, you can contact sales@syncfusion.com for commercial licensing options.

https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/LICENSE 
https://www.syncfusion.com/sales/products
https://www.syncfusion.com/products/communitylicense

Please revert us if you have any questions.

Thanks,
Dharani.
