### ISSUE TITLE
Excel sheet is not opening .

### ISSUE THREAD

**Issue by amitsh223** [syncfusion/flutter-widgets#234]
Future getExcelData() async {
print('working');

    final e.Workbook workbook = e.Workbook();

    final e.Worksheet sheet = workbook.worksheets[0];

    sheet.getRangeByName('A1').setText('Sno');

    sheet.getRangeByName('A2').setText('Sno');

    final List<int> bytes = workbook.saveAsStream();

    workbook.dispose();
    final Directory directory =
        await path_provider.getApplicationDocumentsDirectory();
    final String path = directory.path;
    final File file = File('$path/output.xlsx');

    await file.writeAsBytes(bytes);
    await open_file.OpenFile.open(file.path);
  }

i m using this code but on tapping the button nothing happens nd also its not showing any error. however print statement with working on tap

**Comment by Sridhar-Sukumar** [comment]
Hi @amitsh223, 

We have checked the your code snippet in our side and the Excel file is generated and opened properly in the Android Mobile. Please find the sample from below link

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_excel_file131660939.zip

Please check this application in your side and let us know whether this sample is working fine at your end. Also let us know that in which platform you are running the sample.

Regards,
Sridhar.

**Comment by amitsh223** [comment]
the project send by you , is also not woking for me i dont know why

**Comment by amitsh223** [comment]
yupp now its working ,, its not working because i don't have any app to open exel sheet. 
but then it should show some erorr like no app to open this file but its not showing . i think u can add this in futur updates.

**Comment by Sridhar-Sukumar** [comment]
Hi @amitsh223,
 
We are using the [open_file](https://pub.dev/packages/open_file) package to open the files from a Flutter application. open_file package doesn't have the support to throw the error if the application is not installed. So, you should add the codes to your application to achieve your requirement. This cannot be integrated into the Flutter XlsIO package.

Regards,
Sridhar.

**Comment by amitsh223** [comment]
yup i got it @Sridhar-Sukumar thanks for your help.

**Comment by amitsh223** [comment]
yup i got it @Sridhar-Sukumar thanks for your help.
