### ISSUE TITLE
Disable series from trackball tooltip

### ISSUE THREAD

**Issue by petoknm** [syncfusion/flutter-widgets#237]
Is there a way to disable a series from showing up in trackball tooltip?

Thank you

**Comment by dharanidharandharmasivam** [comment]
Hi @petoknm ,

Yes, we can disable the necessary series in the trackball's tooltip. Your scenario is achieved with below KB, kindly check to this.

https://www.syncfusion.com/kb/11638 

Hope this helps.

Thanks,
Dharani.

**Comment by petoknm** [comment]
Wow, that's more of a workaround, rather than a solution. But I can confirm that it works.

**Comment by dharanidharandharmasivam** [comment]
Hi @petoknm ,

Thanks for the revert. We are happy to hear that it works at your end. We are closing this issue now.

Thanks,
Dharani.
