### ISSUE TITLE
Is there any custom renderer for PDFviewer?

### ISSUE THREAD

**Issue by tomriddle7** [syncfusion/flutter-widgets#238]
Hello, I compared several PDFviewer in flutter and Your PDFviewer is best for me.

But I need custom renderer for support two page view and separate cover function.

If you support this custom renderer, It will perfect for me.

Do you have plan for support this function?

Thanks for your support.

**Comment by dillibabun** [comment]
Hi @tomriddle7 ,

Greetings from Syncfusion.

**Regarding custom renderer support:**
Currently, SfPdfViewer doesn’t provide support for custom rendering. Kindly share us the complete scenario in which custom rendering feature is used at your end. 

**Regarding two page view and separate cover function:**
Currently, SfPdfViewer doesn’t provide support for two-page view. We are analyzing on the feasibility of this feature from our end. Kindly provide us detailed information about “separate cover function” and its purpose. This detail will be helpful in analyzing your requirement and provide a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by tomriddle7** [comment]
> Hi @tomriddle7 ,
> 
> Greetings from Syncfusion.
> 
> **Regarding custom renderer support:**
> Currently, SfPdfViewer doesn’t provide support for custom rendering. Kindly share us the complete scenario in which custom rendering feature is used at your end.
> 
> **Regarding two page view and separate cover function:**
> Currently, SfPdfViewer doesn’t provide support for two-page view. We are analyzing on the feasibility of this feature from our end. Kindly provide us detailed information about “separate cover function” and its purpose. This detail will be helpful in analyzing your requirement and provide a prompt solution at the earliest.
> 
> Regards,
> Dilli babu.

In native_pdf_view, they have custom PdfRenderer library options. Such like that.

```
PdfView(
  controller: pdfController,
  document: snapshot.data,
  pageBuilder: (
    Future<PdfPageImage> pageImage,
    int index,
    PdfDocument document,
  ) => PhotoViewGalleryPageOptions(
      imageProvider: PdfPageImageProvider(
        pageImage,
        index,
        document.id,
      ),
      minScale: PhotoViewComputedScale.contained * 1,
      maxScale: PhotoViewComputedScale.contained * 3.0,
      initialScale: PhotoViewComputedScale.contained * 1.0,
      heroAttributes: PhotoViewHeroAttributes(tag: '${document.id}-$index'),
    ),
);
```

In flutter_fullpdfview, there is displayAsBook capabalitity, to show the first and last page as cover (alone). Seperate cover function means like this.

**Comment by dillibabun** [comment]
Hi @tomriddle7  

Thank you for your update.

Regarding two page view and separate cover function:
We are analyzing feasibility of providing support for “Two page view” with covers and will update the further details on 24 May 2021.

Regarding Custom Renderer support:
Custom renderer and page builder are different. The page builder is used to customize the layout the PDF page view in flutter and custom renderer is used to customize the image which is retrieved the PDF document. Based on your update, we suspect you are looking for page builder API for viewing the PDF pages in two-page view. As we mentioned above, we will analyze on “Two page view” so that you can achieve your requirement without using page builders.

Please let us know if you have any doubts.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @tomriddle7 ,

**Regarding two page view and separate cover function:**
At present we do not have support for a “Two-page view” and cover options. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of this feature can be tracked using the following link.
https://www.syncfusion.com/feedback/25630/support-for-two-page-view-with-cover-option 

**Regarding Custom Renderer support:**
Kindly share us more information about your requirement for custom renderers as requested in the above response. This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.
