### ISSUE TITLE
[SfPdfViewer] Text selection is not shown appropriately in some documents

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#240]
It seems that in some documents `enableTextSelection: true` does not shows text selection appropriately.

Attached is the sample dummy pdf document to reproduce the behaviour in which this can be reproduced on any page.
[dummy.pdf](https://github.com/syncfusion/flutter-widgets/files/6513399/dummy.pdf)

Below is the screenshot from page 1.
![Image](https://user-images.githubusercontent.com/60609139/118929799-9bfe4d00-b962-11eb-9c19-8ebea38da27b.png)

Regards,
Sagar

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Greetings from Syncfusion.

We can reproduce the reported issue from our side. In provided document, we are getting improper text bounds details while loading into PdfDocument instance. We have forwarded this issue to the concern team and will update the further details on 25 May 2021.

Regards,
Dilli babu.

**Comment by sarathkumar50** [comment]
Hi @sagarkardani ,
 
The concern team has confirmed that the issue with "Text selection is not shown appropriately in some documents" is a defect. The issue fix will be included in our June 2nd weekly package release which is expected to available on 8th June, 2021. The status of this issue can be tracked using following link
https://www.syncfusion.com/feedback/25659/text-bounds-not-retrieved-property-when-extract-text-from-pdf

For further queries, You can also contact us through our [support forum](https://www.syncfusion.com/forums)s, [Direct-Trac](https://www.syncfusion.com/support/directtrac/incidents), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar.

**Comment by sagarkardani** [comment]
> The concern team has confirmed that the issue with "Text selection is not shown appropriately in some documents" is a defect. The issue fix will be included in our June 2nd weekly package release which is expected to available on 8th June, 2021. The status of this issue can be tracked using following link

Now after updating to latest package it seems that text bounds are retrieved properly but then also sometimes text selection leaves some gaps in between words.

Attached is the screenshot
![Simulator Screen Shot - iPad Pro (11-inch)](https://user-images.githubusercontent.com/60609139/121299659-64584480-c913-11eb-9870-28c54ad954f0.png)

**Comment by sarathkumar50** [comment]
Hi @sagarkardani ,

We can reproduce the reported issue from our side. In provided document, space width is not sufficient to fill the gap between the words.We are analysing on this and will update the validation details on 16 June 2021.

Regards,
Sarath Kumar.

**Comment by sagarkardani** [comment]
Hi @sarathkumar50

What I am assuming is that this is justified text and I think in this case software has justified the text by either by increasing or decreasing the width of available white spaces.

Also I am assuming that if the text was not justified and if it was just left alined then probably the selection behaviour would be ok. However this is just my assumption. I have not tested the behaviour.

Regards,
Sagar

**Comment by dillibabun** [comment]
Hi Sagar,

As promised earlier, we will update the details on 16 June 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

We have forwarded the reported issue to the concerned team and they have suspected that this to be a defect. Based on their analysis, we will consider the empty whitespaces in the text selection. We will update you the further details on 21 June 2021.

Regards
Dilli babu.

**Comment by dillibabun** [comment]
Hi @sagarkardani,

Currently, Syncfusion Flutter PdfViewer doesn't consider the word spacing in the justified text while the text is been selected. So, the justified spacing was not considered as white space so there is a gap in text selection.

Regards,
Dilli babu.
