### ISSUE TITLE
[SfPdfViewer] Text search instances are not highlighted appropriately sometimes

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#241]
It seems that sometimes text search instances are not highlighted appropriately.

Attached is the sample dummy pdf document to reproduce the behaviour.
[dummy.pdf](https://github.com/syncfusion/flutter-widgets/files/6513643/dummy.pdf)

Below is the screenshot of 2nd occurance and 3rd occurance of text search of [Lorem] word
![Lorem2-3](https://user-images.githubusercontent.com/60609139/118935948-b4259a80-b969-11eb-8f47-1f3f2730707d.png)

Below is the screenshot of 4th occurance of text search of [Lorem] word
![Lorem4](https://user-images.githubusercontent.com/60609139/118936271-08c91580-b96a-11eb-941a-e80fc79e6bbf.png)

Below is the screenshot of 9th, 10th and 11th of text search of [ipsum] word
![ipsum9-10-11](https://user-images.githubusercontent.com/60609139/118936702-63fb0800-b96a-11eb-8619-a5fa7dbf6519.png)

This behaviour can be produced for other words also.

Regards,
Sagar

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Greetings from Syncfusion.

We can reproduce the reported issue from our side. In provided document, we are getting improper text bounds details while loading into PdfDocument instance. We have forwarded this issue to the concern team and will update the further details on 25 May 2021.

Regards,
Dilli babu.

**Comment by sarathkumar50** [comment]
Hi @sagarkardani ,
 
The concern team has confirmed that the issue with "Text search instances are not highlighted appropriately sometimes" is a defect. The issue fix will be included in our June 2nd weekly package release which is expected to available on 8th June, 2021. The status of this issue can be tracked using following link
https://www.syncfusion.com/feedback/25659/text-bounds-not-retrieved-property-when-extract-text-from-pdf

For further queries, You can also contact us through our [support forum](https://www.syncfusion.com/forums)s, [Direct-Trac](https://www.syncfusion.com/support/directtrac/incidents), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar.
