### ISSUE TITLE
[syncfusion_flutter_datagrid] crash in flutter latest stable version (2.2.0)

### ISSUE THREAD

**Issue by WingCH** [syncfusion/flutter-widgets#242]
# Reproduce Step 1:

1. change columnWidthMode to `none`
```dart
SfDataGrid(
        source: employeeDataSource,
        columnWidthMode: ColumnWidthMode.none,
)
...
```

2. Keep sliding
---

## flutter 2.0.6 is normal

https://user-images.githubusercontent.com/19588517/118951647-d7fad780-b98d-11eb-825f-b3e91f13797a.mp4

## flutter 2.2.0 will crash in debug mode, release is ok

https://user-images.githubusercontent.com/19588517/118951865-07a9df80-b98e-11eb-9b8e-2f84a0cf0168.mp4

```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Debug service listening on ws://127.0.0.1:59898/IyESc9xWgMo=/ws
Syncing files to device M2011K2C...
D/DecorView[](31390): getWindowModeFromSystem  windowmode is 1
I/atagrid_exampl(31390): ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
D/MIUIInput(31390): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=58603815, downTime=58603815 } moveCount:0
V/MiuiFrameworkFactory(31390): get AllImpl object = android.common.MiuiFrameworkFactoryImpl@a4e314c
F/libc    (31390): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7e90afb3e8 in tid 5339 (1.ui), pid 31390 (atagrid_example)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/venus/venus:11/RKQ1.200928.002/21.5.18:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2021-05-20 17:04:42+0800
pid: 31390, tid: 5339, name: 1.ui  >>> com.example.datagrid_example <<<
uid: 10325
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7e90afb3e8
    x0  ffffffffffff3fc8  x1  0000007eefbf2000  x2  00ffffffffffffff  x3  0000000000000019
    x4  0000007eefbf24a0  x5  0000007eefa3ce00  x6  0000000000000000  x7  0000000000000001
    x8  0000007eefb94800  x9  0000000000000000  x10 0000000019632c18  x11 0000007ec0000000
    x12 0000000019632218  x13 00000202c1506368  x14 00043d14e94275b2  x15 0000007e90afb3f8
    x16 0000000000000008  x17 0000007f82cbfffc  x18 0000007e8adf0000  x19 0000007eefb94800
    x20 0000007e90a16000  x21 0000007eefba7af0  x22 0000007e7da08041  x23 0000007e8f406548
    x24 0000007e7da0d7e1  x25 0000007e90aef060  x26 0000007eefb94800  x27 0000007eecc965f0
    x28 0000000000000006  x29 0000007e90aef3c0
    lr  0000007eed626f04  sp  0000007e90a16000  pc  0000007e7d983418  pst 0000000060001000
backtrace:
      #00 pc 0000000000003418  <anonymous:7e7d980000>
Lost connection to device.
```

**Comment by JesusMayuri7** [comment]
I have the same problem with Flutter 2.2, since the beta version comes the problem

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH ,

Greetings from syncfusion.

We have checked your reported issue and unable to reproduce this from our end, please provide the following details, 
1.	Which is Flutter channel (Stable, beta, dev, or Master) are you using? 
2.	Provide the version of datagrid package.
3.	Your emulator version or physical device details.  


It will be helpful for us to check on it and provide you the solution at the earliest.    

Regards,
Renuga devi S

**Comment by JesusMayuri7** [comment]
1. Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (6 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

2. syncfusion_flutter_datagrid: ^19.1.64-beta

3. Desktop Windows 10 x64

**Comment by WingCH** [comment]
1. Flutter Stable (2.2.0)
2. syncfusion_flutter_datagrid: ^19.1.64-beta
3. Android 11 API 30

Other details: 
![image](https://user-images.githubusercontent.com/19588517/119066744-0a9ae380-ba13-11eb-9935-91022ba4cce7.png)
![image](https://user-images.githubusercontent.com/19588517/119066765-14bce200-ba13-11eb-861b-c520b42a8568.png)

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH , 
 
Thanks for your update. 
 
From the provided information, we have checked your reported issue, but we could not able to reproduce the issue in our end. We have tested in simple sample in below mentioned device and it's working fine.
 
Please refer the below attached sample, video and version for more details.  
 
**Flutter Version:** 2.2.0 
**Flutter channel:** stable 
**Devices:** Redmi Note 4, Android version 7.0 
**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main739003676  
**Video link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/screen-capture-datagrid1526843304 
 
Please check the above sample and revert us if you still facing the same issue? If yes, please modify the sample based on your scenario and revert us back. 


Regards,
Renuga devi S

**Comment by WingCH** [comment]
I think you need to add more columns so that the datagrid can be `sliding` , in flutter 2.2.0 sliding datagrid will cause a crash

**Comment by WingCH** [comment]
I just added a few more repetitions of the name

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(MyApp());
}

/// The application that contains datagrid on it.
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: MyHomePage(),
    );
  }
}

/// The home page of the application which hosts the datagrid.
class MyHomePage extends StatefulWidget {
  /// Creates the home page.
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<Employee> employees = <Employee>[];
  late EmployeeDataSource employeeDataSource;

  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: SfDataGrid(
        source: employeeDataSource,
        columnWidthMode: ColumnWidthMode.none,
        columns: <GridColumn>[
          GridTextColumn(
              columnName: 'id',
              label: Container(
                  padding: EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: Text(
                    'ID',
                  ))),
          GridTextColumn(
              columnName: 'name',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Name'))),
          GridTextColumn(
              columnName: 'name2',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Name'))),
          GridTextColumn(
              columnName: 'name3',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Name'))),
          GridTextColumn(
              columnName: 'name4',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Name'))),
          GridTextColumn(
              columnName: 'name5',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Name'))),
          GridTextColumn(
              columnName: 'designation',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text(
                    'Designation',
                    overflow: TextOverflow.ellipsis,
                  ))),
          GridTextColumn(
              columnName: 'salary',
              label: Container(
                  padding: EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: Text('Salary'))),
        ],
      ),
    );
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'James', 'Project Lead', 20000),
      Employee(10002, 'Kathryn', 'Manager', 30000),
      Employee(10003, 'Lara', 'Developer', 15000),
      Employee(10004, 'Michael', 'Designer', 15000),
      Employee(10005, 'Martin', 'Developer', 15000),
      Employee(10006, 'Newberry', 'Developer', 15000),
      Employee(10007, 'Balnc', 'Developer', 15000),
      Employee(10008, 'Perry', 'Developer', 15000),
      Employee(10009, 'Gable', 'Developer', 15000),
      Employee(10010, 'Grimes', 'Developer', 15000)
    ];
  }
}

/// Custom business object class which contains properties to hold the detailed
/// information about the employee which will be rendered in datagrid.
class Employee {
  /// Creates the employee class with required details.
  Employee(this.id, this.name, this.designation, this.salary);

  /// Id of an employee.
  final int id;

  /// Name of an employee.
  final String name;

  /// Designation of an employee.
  final String designation;

  /// Salary of an employee.
  final int salary;
}

/// An object to set the employee collection data source to the datagrid. This
/// is used to map the employee data to the datagrid widget.
class EmployeeDataSource extends DataGridSource {
  /// Creates the employee data source class with required details.
  EmployeeDataSource({required List<Employee> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(columnName: 'name2', value: e.name),
              DataGridCell<String>(columnName: 'name3', value: e.name),
              DataGridCell<String>(columnName: 'name4', value: e.name),
              DataGridCell<String>(columnName: 'name5', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }

  List<DataGridRow> _employeeData = [];

  @override
  List<DataGridRow> get rows => _employeeData;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: EdgeInsets.all(8.0),
        child: Text(e.value.toString()),
      );
    }).toList());
  }
}

```

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH ,

Thanks for your update.

Currently, we are analyzing your reported issue. We will validate and update you with the details in two business days i.e 26th May 2021. We appreciate your patience until then.

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH ,

We can able to reproduce the reported issue. Due to complexity, we are still analyzing to find the root cause of this issue. We will update further details by tomorrow (May 27th).

Regards,
Renuga devi

**Comment by WingCH** [comment]
ok thanks your help!

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH ,

Thanks for your patient. 

We have considered your reported issue as a bug. We will include the changes in our volume 2 release which is expected to be rolled out on mid of June 2021. 

Please refer to the below feedback link for further follow up, 
Feedback link:  https://www.syncfusion.com/feedback/25710/application-is-closed-when-scroll-the-datagrid-in-debug-mode-and-flutter-2-2

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you would require any further assistance. 

Regards,
Renuga devi S

**Comment by WingCH** [comment]
Thank you for your follow up and look forward to the new version!

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH ,

Thanks for your update.

We appreciate your patience until then.

Regards,
Renuga devi S

**Comment by NeelakandanKannan** [comment]
Hi @WingCH ,

Recently we have checked this reported issue in Android and Flutter 2.2.1 stable version. Its working fine. Can you please test your reported issue in Flutter 2.2.1 stable version and confirm whether issue is resolved?

**Comment by WingCH** [comment]
thanks your attention.
In [pub.dev](https://pub.dev/packages/syncfusion_flutter_datagrid) I only see the beta version (syncfusion_flutter_datagrid 19.1.65-beta ), How do I access a channel that is not a beta channel?

I have just tested syncfusion_flutter_datagrid 19.1.65-beta  in  Android and Flutter 2.2.1 stable version, the problem still exists

**Comment by NeelakandanKannan** [comment]
Hi @WingCH ,

Thanks for the update.

I am referring to the Flutter beta channel not syncfusion_flutter_datagrid. Moreover, as we promised, we will work on the reported issue and resolve it in our 2021 Volume 2 release.

**Comment by WingCH** [comment]
same problem in release version of syncfusion_flutter_datagrid (^19.1.67-beta)


[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale zh-Hant-HK)

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH,

Thanks for your patience.

As we said earlier, we will include the fix in our 2021 Volume 2 release which is expected to be rolled out on end of June 2021.  

Please refer to the below feedback link for further follow up,  

**Feedback link:**  https://www.syncfusion.com/feedback/25710/application-is-closed-when-scroll-the-datagrid-in-debug-mode-and-flutter-2-2 
 
We appreciate your patience until then. Please get in touch with us if you would require any further assistance.  

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi @WingCH,

we have checked the reported issue with our flutter 2.2.2 version. We can't able to reproduce the issue. Please upgrade the flutter version and revert us if you are still facing the same issue. 
We will happy to assist you.

Regards,
Renuga devi S

**Comment by WingCH** [comment]
Work! thanks
