### ISSUE TITLE
Config auto fit row height based on the its content??

### ISSUE THREAD

**Issue by tantana5** [syncfusion/flutter-widgets#243]
How can i adjust (auto fit) the row height based on the its content?

**Comment by RenugaSadagoban98** [comment]
Hi @tantana5 ,  

Greetings from syncfusion.  

Currently, SfDataGrid does not have support for autofit (width and height) row and column.  We have considered your request as a feature. This feature will be implemented in our any of our upcoming release. We will let you know when this feature is implemented. 

You can refer to the below feedback for further follow up,
**Feedback link:** https://www.syncfusion.com/feedback/22622/support-to-autofit-the-column-and-row-for-widget-column  

We appreciate your patience until then. For further assistance, you can follow the feature request.  
 
Regards, 
Renuga devi

**Comment by SittiphanSittisak** [comment]
Is auto-fit for height avaiable?
