### ISSUE TITLE
crash in mac desktop app  when drag grid left or right

### ISSUE THREAD

**Issue by Ampy** [syncfusion/flutter-widgets#245]
crash in mac desktop app  when drag grid left or right

**Comment by RenugaSadagoban98** [comment]
Hi Ampy,
 
Greetings from Syncfusion support.
 
Currently, we are analyzing your reported issue. We will validate and update you with the details in two business days i.e 26th May 2021. We appreciate your patience until then.


Regards,
Renuga devi S

**Comment by HawkarShwany** [comment]
I have the same issue. The ios simulator loses connection whenever I drag left or right. Any idea how to fix it?

**Comment by RenugaSadagoban98** [comment]
Hi @Ampy ,

Thanks for your patient. 

We have considered your reported issue as a bug. We will include the changes in our volume 2 release which is expected to be rolled out on mid of June 2021. 

Please refer to the below feedback link for further follow up, 
Feedback link:  https://www.syncfusion.com/feedback/25710/application-is-closed-when-scroll-the-datagrid-in-debug-mode-and-flutter-2-2

We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you would require any further assistance. 

Regards,
Renuga devi S

**Comment by fathah** [comment]
Same issue with Windows desktop version.

**Comment by RenugaSadagoban98** [comment]
Hi @fathah  ,

Thanks for your update.

We have already considered your reported crashing issue ( For desktop, web, and Android platforms) as a bug. We will include the changes in our volume 2 release which is expected to be rolled out on mid of June 2021.

Please refer to the below feedback link for further follow up,
**Feedback link:** https://www.syncfusion.com/feedback/25710/application-is-closed-when-scroll-the-datagrid-in-debug-mode-and-flutter-2-2

We appreciate your patience until then. Please get in touch with us if you would require any further assistance.

**Comment by RenugaSadagoban98** [comment]
Hi,

we have checked the reported issue with our flutter 2.2.2 version. We can't able to reproduce the issue. Please upgrade the flutter version and revert us if you are still facing the same issue.
We will happy to assist you.

Regards,
Renuga devi S

**Comment by HawkarShwany** [comment]
this issue should not be closed. I'm still facing it on IOS simulator on this version `syncfusion_flutter_datagrid: ^19.1.69-beta`

**Comment by HawkarShwany** [comment]
HI @RenugaSadagoban98 ,

Thank you for your reply. I apologize for my previous comment which I deleted because it is no longer the case. I experienced it before upgrading flutter to 2.2.2, but after upgrading the issue seems to be resolved. 

Thank you.

**Comment by RenugaSadagoban98** [comment]
Hi @HawkarShwany,
Thanks for your update.

We are glad to know that issue is resolved at your end. Please let us know if you need any other assistance.

Regards,
Renuga devi S
