### ISSUE TITLE
[syncfusion_flutter_datagrid] i can not extend the widget 

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#246]
the widget do not fill the height .

` syncfusion_flutter_core: ^18.3.35`
` syncfusion_flutter_datagrid: ^18.4.49-beta`

code
`SingleChildScrollView(
              child: Column(
                   mainAxisSize: MainAxisSize.max,
                children : [
                  SfDataGrid(),
                  ]
              ),
            ),`

![Screenshot_90](https://user-images.githubusercontent.com/60202661/119137631-4b115600-ba41-11eb-849f-573e7d0ea6d3.png)

**Comment by RenugaSadagoban98** [comment]
Hi Joseph-Nathan,

Greetings from syncfusion.

By default, SfDataGrid will be rendered with the 300 * 300 (width and height). if the parent size is infinite. You have to set the proper width and height based on your requirement. To do so, please wrap the DataGrid inside Container and set the height based on the rows count.

Please refer to the following code snippet.

```
double defaultRowHeight = 49.0;
double defaultHeaderRowHeight = 56.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter DataGrid'),
        ),
        body: SingleChildScrollView(
          child: Column(
            children: [
              Container(
                  height: employees.length * defaultRowHeight + defaultHeaderRowHeight,
                  child: _buildDataGrid()),
            ],
          ),
        ));
  }

```

Please let us know if you need further assistance. 

Regards,
Renuga devi S

**Comment by AymanOmara** [comment]
just wrap SfDataGrid in Expanded Widget it worked fine with me

**Comment by roshansrashtasoft** [comment]
![Uploading image.png…]()

any solution ?

**Comment by roshansrashtasoft** [comment]
![Screenshot 2023-10-02 at 10 46 27 AM](https://github.com/syncfusion/flutter-widgets/assets/97586645/94ed6899-8b94-4ebb-9be6-1f4073af9767)

@Joseph-Nathan DataGrid is not set properly in tablet UI, Do you have any solution?
