### ISSUE TITLE
PDF Viewer doesn't work in web

### ISSUE THREAD

**Issue by BestRazer** [syncfusion/flutter-widgets#247]
Hello, I want to use the PDF Viewer in my web app but it doesn't work. I also added the script tag you provided [here](https://help.syncfusion.com/flutter/pdf-viewer/getting-started) to the `index.html`.

**Comment by dillibabun** [comment]
Hi @BestRazer 

Greetings from Syncfusion.

We have prepared a sample to reproduce the reported issue but the document is loaded properly in Flutter web platform. We have shared the simple sample for your reference.
[https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-21767305.zip
](https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-21767305.zip
)

Kindly let us know if you are faced with any issues with this sample. Please share the following details, if the issue exists.

1. syncfusion_flutter_pdfviewer package version. We recommend using our latest package [19.1.64-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.64-beta) 
2. Flutter doctor log. Kindly run flutter doctor command in Android Studio terminal and share us the output.
3. For network constructor of SfPdfViewer, Internet access is required so kindly ensure it from your side.

These pieces of information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by BestRazer** [comment]
Hello.

I have tried the sample you sent me and it works perfectly well.
In my code it still doesn't, even after upgrading the package,
Here is the output of `flutter doctor log`:
`
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

`

**Comment by dillibabun** [comment]
Hi @BestRazer,

We highly recommend upgrading your flutter SDK to support null safety and try out the sample. If the issue persists, please share with us the document which is loaded in SfPdfViewer widget along with browser's console output

Regards,
Dilli babu.

**Comment by BestRazer** [comment]
Hello.

I updated my flutter SDK but it doesn't work either. I can't really share the document because the app I need it for is for private matter but I can say that its an ordinary PDF file hosted on a http (not https) server. But I also tried it with your sample document and it did't work, so this shouldn't matter that much. I can share with you my console output (I share it as an image because else it's too unformatted):
![image](https://user-images.githubusercontent.com/65088083/119623037-12d69280-be08-11eb-8f09-64ea47bd3c49.png)

**Comment by dillibabun** [comment]
Hi @BestRazer,

Based on the exception, we suspect that you have been using [package_info](https://pub.dev/packages/package_info) package in the Web platform. As mentioned in pub dev documentation, this package is not supported on the Web platform. So kindly disable the codes related to this package in your application for the Web platform and let us know if you face any issues.

Regards,
Dilli babu.

**Comment by BestRazer** [comment]
Hello.

You were right. I actually used package_info for my android app in order to prompt the user to update.
Since I obviously don't need it in a web application I now disabled all code related to the package and deleted it from the pubspec.yaml but it still doesn't work.
Do you have an Idea why it still couldn't work?
On my question on StackOverflow question, someone wrote it would probably be something CORS related. Do you think he could be right?

Thank you for your investigation so far!

**Comment by dillibabun** [comment]
Hi @BestRazer ,

Yes, CORS needs to be set up for accessing the files from cross-origin in the Flutter Web application. We request to do the following config changes at your end for loading the document from your firebase storage. 
[]([https://pub.dev/packages/firebase_storage_web#downloading-files-with-getdata](https://pub.dev/packages/firebase_storage_web#downloading-files-with-getdata))  

We have prepared a sample for loading a PDF document from Firebase storage which can be downloaded from the following link.
[https://www.syncfusion.com/downloads/support/directtrac/general/ze/firebaseflutter_app-1053559921](https://www.syncfusion.com/downloads/support/directtrac/general/ze/firebaseflutter_app-1053559921)

**Regarding console error:** The reported error didn't occur at our end and we suspect the error might caused to application settings. So, we request you to share us the application by creating a support incident through our website, and information shared in the incident will be maintained confidentially.
[https://www.syncfusion.com/support/directtrac/incidents/newincident](https://www.syncfusion.com/support/directtrac/incidents/newincident)

For further queries, You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you! 

Regards,
Dilli babu.

**Comment by UnHired-Coder** [comment]
Indeed, after a  lot of attempts, I am unable to show Pfds on the web :(

**Comment by dillibabun** [comment]
Hi @UnHired-Coder 

Greetings from Syncfusion.

We have prepared a sample to reproduce the reported issue but the document is loaded properly in Flutter web platform. We have shared the simple sample for your reference.
[https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-21767305.zip
](https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-21767305.zip
)
Note: On your web/index.html file, add the following script tags, somewhere in the body of the document:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
<script type="text/javascript">
   pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
</script>
```

Kindly let us know if you are faced with any issues with this sample. Please share the following details, if the issue exists.

1. syncfusion_flutter_pdfviewer package version. We recommend using our latest package [19.1.66-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.66-beta) 
2. Flutter doctor log. Kindly run flutter doctor command in Android Studio terminal and share us the output.
3. For network constructor of SfPdfViewer, Internet access is required so kindly ensure it from your side.
4. Share the issue reproducing sample.

These pieces of information will be helpful for us to provide you a prompt solution at the earliest.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you! 

Regards,
Dilli babu.

**Comment by accompagne** [comment]
@dillibabun Thanks for your fix. Adding JS scripts in my index.html worked for me. Maybe you should add those steps on package documentation in a Web section? Thanks for your great work, keep going.

**Comment by houdayec** [comment]
@dillibabun Thanks for this fix. Adding JS scripts to my index.html worked for me. You should add those steps in the package documentation, it will help other people too. Thanks for the package, great work.

**Comment by dillibabun** [comment]
Hi @houdayec ,

We are glad that the reported issue is resolved at your end. We have already add this information in our [UG documentation](https://help.syncfusion.com/flutter/pdf-viewer/getting-started#initialize-the-pdf-viewer) and will add in pub dev documentation shortly.

Regards,
Dilli babu.

**Comment by Gerard-CK** [comment]
After adding the recommended script tags to index.html, it does indeed work in Flutter for Web with version [19.1.66-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.66-beta) and [19.1.67-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.67-beta)

However, it stopped working in version [19.1.69-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.69-beta)

**Comment by dillibabun** [comment]
Hi @Gerard-CK 

Greetings from Syncfusion.

We tried to reproduce the reported issue with the latest package in the above [sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app-21767305.zip). But, the document was loaded properly and we couldn't any issues with it. Kindly share us the following details to proceed further in this issue.

1. Flutter doctor log. Kindly run the flutter doctor command in the Android Studio terminal and share us the output.
2. Share the issue reproducing sample.

These pieces of information will be helpful for us to provide you a prompt solution at the earliest.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you! 

Regards,
Dilli babu.

**Comment by Gerard-CK** [comment]
Thanks Dilli.
Indeed your sample seems to work with 19.1.69-beta. I'll dig more into my code to try and understand why that version doesn't work for me then.
Cheers

**Comment by dillibabun** [comment]
Hi @Gerard-CK 

Once the analysis is over, you can share your findings in the application so that we can check and let you know how to resolve the issue. You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you! 

Regards,
Dilli babu.
