### ISSUE TITLE
Can I achieve 1st Column Freeze in syncfusion_flutter_xlsio Flutter Package

### ISSUE THREAD

**Issue by meetjanani** [syncfusion/flutter-widgets#248]
Can I achieve 1st Column Freeze in syncfusion_flutter_xlsio Flutter Package?
can anyone help me to Freeze the 1st Column in Flutter Project by using the syncfusion_flutter_xlsio Flutter Package! 

Concept Of Freeze Column: https://www.excel-easy.com/examples/freeze-panes.html

**Comment by Sridhar-Sukumar** [comment]
Hi @meetjanani, 

Currently, we don’t have the support for **“Freeze panes to lock rows and columns”** in Flutter XlsIO. However, we have logged a feature report for this, and it will be implemented in any of our upcoming releases.

**Feedback link:** https://www.syncfusion.com/feedback/25221/freeze-panes-to-lock-rows-and-columns 

Regards,
Sridhar.

**Comment by meetjanani-simformsolutions** [comment]
@JayavigneshwaranG  as you closed this issue so can you guild how Can I achieve 1st Column Freeze in syncfusion_flutter_xlsio Flutter Package?

**Comment by meetjanani** [comment]
@JayavigneshwaranG  as you closed this issue 
so can you please guild me what is the property to freeze any column in syncfusion_flutter_xlsio  flutter packages 

my core motive is to achieve 1st Column Freeze in syncfusion_flutter_xlsio Flutter Package?
can @JayavigneshwaranG help me to Freeze the 1st Column in Flutter Project by using the syncfusion_flutter_xlsio Flutter Package!

**Comment by meetjanani** [comment]
@Sridhar-Sukumar , @JayavigneshwaranG  
issue number 248 is now achievable with syncfusion_flutter_xlsio flutter packages or not 
kingly can we get any update on this?
