### ISSUE TITLE
[SfPdfViewer] Text search instances navigation should be finetuned

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#249]
Some improvement points when Text search instances are navigated with **`previousInstance()`** and **`nextInstance()`** methods.

### When document is not zoomed

When **`previousInstance()`** or **`nextInstance()`** methods are called, respected search instance is highlighted but the highlighted instance is always pushed to the top edge of the screen.

- Expected behaviour

1. When **`nextInstance()`** method is called, highlighted instance should remain at top edge of the PdfViewer. That is working fine at present. But it **should leave some margin**, say for example 40px or 60px or 80px, from **top edge** of the PdfViewer.

2. When **`previousInstance()`** method is called, highlighted instance **should remain at bottom edge** of the PdfViewer. At present this method is always pushing the instance at the top edge of the PdfViewer. Also it **should leave some margin** from **bottom edge** of the PdfViewer.

### When document is zoomed

When **`previousInstance()`** or **`nextInstance()`** methods are called, respected search instance is highlighted but the highlighted instance is always pushed to the top edge of the screen. Sometimes it leaves margin and sometimes not. One another problem is that calling these methods **always scrolls the PdfViewer and pushes the next or previous instance to the top edge of the PdfViewer even if it is already visible within the zoomed area**

- Expected behaviour

1. When **`nextInstance()`** method is called, highlighted instance should remain at top edge of the PdfViewer. That is working fine at present. But it **should leave some margin from top edge** and **PdfViewer should not scroll when next instance is already visible** within zoomed area.

2. When **`previousInstance()`** method is called, highlighted instance **should remain at bottom edge** of the PdfViewer. At present this method is always pushing the instance at the top edge of the PdfViewer. Also it **should leave some margin from bottom edge** and **PdfViewer should not scroll when previous instance is already visible** within zoomed area.

**Comment by dillibabun** [comment]
Hi @sagarkardani,

We have checking the feasibility of the requested enhancements and will update the further details by 27 May 2021.

For further queries, You can also contact us through our support forums, Direct-Trac, or feedback portal. We are always happy to assist you!

Regards,
Sarath.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

We have considered the mentioned suggestions and logged a feature request. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of this feature can be tracked using the following link.
[https://www.syncfusion.com/feedback/25755/text-search-enhancement-for-navigating-search-instance](https://www.syncfusion.com/feedback/25755/text-search-enhancement-for-navigating-search-instance )

For further queries, You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you! 

Regards,
Dilli babu.
