### ISSUE TITLE
[web] SfCartesianChart MajorGridLines dashArray not working on web

### ISSUE THREAD

**Issue by archie-sh** [syncfusion/flutter-widgets#25]
```
SfCartesianChart(
              plotAreaBorderWidth: 0,
              primaryXAxis: CategoryAxis(
                isVisible: true,
                labelStyle: TextStyle(color: Colors.black.withOpacity(0.0)),
                majorGridLines: MajorGridLines(width: 0),
                majorTickLines: MajorTickLines(width: 0),
                axisLine: AxisLine(color: Colors.black, width: 2),
              ),
              primaryYAxis: NumericAxis(
                isVisible: true,
                crossesAt: 0,
                numberFormat: chartYLabelFormat,
                labelStyle: chartLabel,
                axisLine: AxisLine(width: 0),
                majorGridLines: MajorGridLines(width: 2,
                    dashArray: <double>[2,2]),
                majorTickLines: MajorTickLines(
                  width: 0,
                ),
              ),
              trackballBehavior: TrackballBehavior(
                  enable: true,
                  tooltipSettings: InteractiveTooltip(
                      format: "point.x:  point.y", color: Colors.black)),
              series: getGradientAreaSeries(),
            ),
```

on mobile prodcues:

<img width="285" alt="Screenshot 2020-10-17 at 01 21 36" src="https://user-images.githubusercontent.com/680494/96321827-1bb3ea00-1017-11eb-9b8f-31d55f28b670.png">
 
on web produces:

<img width="414" alt="Screenshot 2020-10-17 at 01 21 56" src="https://user-images.githubusercontent.com/680494/96321838-266e7f00-1017-11eb-9391-22f666e4381c.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @archie-sh,

Thanks for contacting Synfusion Support. We have analyzed your scenario with the provided information and the reported issue regarding the dash array not working on the web is already a known issue and we have already provided a fix for it and rolled out in our latest weekly patch release. To overcome the reported issue, kindly please upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.42

Regards,
Sriram Kiran

**Comment by archie-sh** [comment]
Thanks for the reply, ill upgrade and test
