### ISSUE TITLE
Vertical label inside vertical bar chart.

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-widgets#253]
I checked the API and the sample app, I couldn't see a way to display a text (label) inside bars vertically.

So basically something like this.
<img width="756" alt="Pasted_Image_25_05_2021_16_04" src="https://user-images.githubusercontent.com/16321223/119503330-867a9000-bd73-11eb-99df-3dca10a0401c.png">

Is there a way to do so?

**Comment by Dharanipalani** [comment]
Hi @bismarabia,

Thanks for the interest in our Flutter charts. We have investigated your query and would like to tell you that to use the angle and offset properties in the datalabelSettings property of the column series. You can rotate the label as per your requirement using the angle property and position the data labels at the required position by using the offset property. We have attached the reference sample and kindly revert us if you need any further assistance on this.

Sample: [G-253-vertical_data_label.zip](https://github.com/syncfusion/flutter-widgets/files/6545388/G-253-vertical_data_label.zip)

Screenshot
![image](https://user-images.githubusercontent.com/19763272/119634686-9b692900-be30-11eb-8bb5-2dd66e1386ca.png)


Thanks,
Dharanitharan. P

**Comment by bismarabia** [comment]
Thanks for the reply!!

Are we able to use both an inside (vertical) and outside(horizontal) label at the same time?

**Comment by Dharanipalani** [comment]
Hi @bismarabia,

We have looked your scenario and would like to tell you that for the horizontal labels you can use the annotations feature in the chart, using this you can place the required widget in the required position. For the vertical labels you can use data labels like in the previous sample. Now, we attached the sample below for both horizontal and vertical labels as a reference and can alter with your requirement. Refer the below help documents for further reference.

[https://help.syncfusion.com/flutter/cartesian-charts/annotations](https://help.syncfusion.com/flutter/cartesian-charts/annotations)
[https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#label-position](https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#label-position)

Sample: [G-253-annotation_vertical_data_label.zip](https://github.com/syncfusion/flutter-widgets/files/6552512/G-253-annotation_vertical_data_label.zip)

Screenshot
![image](https://user-images.githubusercontent.com/19763272/119796672-31678700-bef7-11eb-883e-f965967ef571.png)


Thanks,
Dharanitharan. P
