### ISSUE TITLE
[syncfusion_flutter_pdfviewer] support new feature 

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#255]
- ScrollStatus failed in rtl lang => support ltr lang
- support  canDownLoad pdf 
- support  controller.downLoad ;
- support onLoading Widget

**Comment by dillibabun** [comment]
Hi @Joseph-Nathan 

Please find the status of the requested feature in the below table.


Feature | Status
-- | --
ScrollStatus failed in rtl lang =&gt; support ltr lang | We are analyzing the feasibility of RTL support and   will update the further details on 28 May 2021.
support canDownLoad pdf and support controller.downLoad | Currently, SfPdfViewer doesn’t provide support to edit  or manipulate the loaded document. The onDocumentLoaded callback triggers after the PDF document is loaded in the SfPdfViewer. The document in the PdfDocumentLoadedDetails will return the loaded PdfDocument instance. If you like to download the loaded   document, save the document as mentioned below.   https://help.syncfusion.com/flutter/pdf/loading-and-saving-document#saving-a-pdf-document-to-list-of-bytes   &nbsp;   If your requirement is to download the document   directly then kindly share us your complete scenario in this feature is   required. This will help us to investigate further.
support onLoading Widget | Kindly complete scenario in which onLoading callback is   required at your end. So, we will analyze and let you know its feasibility


Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @Joseph-Nathan,

At present we do not have RTL support in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 3 main release. We will let you know when this feature is implemented. The status of this feature can be tracked using following link.
[https://www.syncfusion.com/feedback/25831/rtl-support-for-sfpdfviewer](https://www.syncfusion.com/feedback/25831/rtl-support-for-sfpdfviewer)

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.
