### ISSUE TITLE
syncfusion_flutter_pdfviewer  does not show annotation

### ISSUE THREAD

**Issue by llearn** [syncfusion/flutter-widgets#258]
here is my code
```
SfPdfViewer.network("https://songcw-dev.oss-cn-shanghai.aliyuncs.com/test/allkeyword.signed.pdf")
```

android
![WX20210528-135759](https://user-images.githubusercontent.com/3062671/119937311-270fc080-bfbd-11eb-9378-559740d62880.png)

google browser
![WX20210528-135814](https://user-images.githubusercontent.com/3062671/119937318-28d98400-bfbd-11eb-83aa-31898c327e02.png)

**Comment by dillibabun** [comment]
Hi @llearn 

Greetings from Syncfusion.

We can reproduce the reported behavior from our side. We are analyzing on this and will update the further details on 2 June 2020.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @llearn ,

At present we do not have support for "PDF form annotation". As a workaround, we request to flatten the annotation using our [Syncfusion PDF package ](https://pub.dev/packages/syncfusion_flutter_pdf) and pass the saved memory bytes to the SfPdViewer widget. The following code example illustrates how to load the PDF document with form annotation in SfPdfViewer.

```
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
import 'package:syncfusion_flutter_pdf/pdf.dart';
import 'package:http/http.dart' as http;

void main() {
  runApp(MaterialApp(
    title: 'Syncfusion PDF Viewer Demo',
    home: HomePage(),
  ));
}

/// Represents Homepage for Navigation
class HomePage extends StatefulWidget {
  @override
  _HomePage createState() => _HomePage();
}

class _HomePage extends State<HomePage> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  Uint8List? _bytes;

  @override
  void initState() {
    super.initState();
    _getBytes();
  }

  // ignore: avoid_void_async
  void _getBytes() async {
    final Uint8List documentBytes = await http.readBytes(Uri.parse(
        'https://songcw-dev.oss-cn-shanghai.aliyuncs.com/test/allkeyword.signed.pdf'));
    final PdfDocument document = PdfDocument(inputBytes: documentBytes);
    _document.form.flattenAllFields();
    _bytes = Uint8List.fromList(document.save());
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter PDF Viewer'),
        actions: <Widget>[
          IconButton(
            icon: const Icon(
              Icons.bookmark,
              color: Colors.white,
            ),
            onPressed: () {
              _pdfViewerKey.currentState?.openBookmarkView();
            },
          ),
        ],
      ),
      body: _bytes != null
          ? SfPdfViewer.memory(
              _bytes!,
              key: _pdfViewerKey,
            )
          : Container(),
    );
  }
}
```
We do not have any immediate plans to implement the PDF form annotation feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.
 
Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 4 main release. We will let you know when this feature is implemented. The status can be tracked using the following link.
[https://www.syncfusion.com/feedback/25265/support-for-pdf-form](https://www.syncfusion.com/feedback/25265/support-for-pdf-form) 
 
Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli abbu

**Comment by llearn** [comment]
@dillibabun  Thank you very much, this solved my problem
