### ISSUE TITLE
Pdf viewer Add custom notes on selected region

### ISSUE THREAD

**Issue by lavahasif** [syncfusion/flutter-widgets#26]
How i add custom notes on pdfviewer .Get the pdf selected coordinate

**Comment by dillibabun** [comment]
Hi @lavahasif ,

At present we do not have support for “Sticky notes annotation”. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 2 main release. We will let you know when this feature is implemented. You can also track the status of this feature from the following link,

https://www.syncfusion.com/feedback/18433/support-for-sticky-notes-annotation 

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.

**Comment by lavahasif** [comment]
is there any way to get coordinate of selected region

**Comment by dillibabun** [comment]
Hi @lavahasif ,

The support for text selection and copy in SfPdfViewer widget is expected to be implemented in our upcoming 2020 Volume 4 main release. We will let you know once this feature is implemented. You can track the status of this feature in the following link,

https://www.syncfusion.com/feedback/18966/support-for-text-selection-and-copy

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @lavahasif,

Greetings from Syncfusion!!

We are glad to announce that the support for text selection has been included in our latest 2020 Essential Studio 2020 Volume 4 release. Please find the download link below.

https://www.syncfusion.com/forums/160733/essential-studio-2020-volume-4-release-v18-4-0-30-is-available-for-download

**Latest package link:** https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/18.4.34-beta

For more details, kindly refer to the following user guide documentation link,

**Documentation link:** https://help.syncfusion.com/flutter/pdf-viewer/text-selection 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Dilli babu,
