### ISSUE TITLE
[DataGrid] Displayed rowsPerPage

### ISSUE THREAD

**Issue by davidp918** [syncfusion/flutter-widgets#261]
Hi,

How can I modify the rows per page displayed? The default is 5, I can't find anywhere to change it.

**Comment by RenugaSadagoban98** [comment]
Hi @davidp918,

Greetings from Syncfusion.

Currently, SfDatagrid doesn’t have the option for providing rowsPerPage. But you can achieve your requirement through setting the value for page count by dividing the length of a collection with rows per page.
Also, use the rows per page value in handlePageChange method inside the DataGridSource class and load the rows.

```
Widget _buildDataPager() {
    return SfDataPager(
      delegate: orderInfoDataSource,
      pageCount: dataSource.length / rowsPerPage,
    );
  }

class _OrderInfoDataSource extends DataGridSource {
….
  @override
  Future<bool> handlePageChange(int oldPageIndex, int newPageIndex) async {
    int startIndex = newPageIndex * _rowsPerPage;
    int endIndex = startIndex + _rowsPerPage;
    _paginatedDataSource =
        _dataSource.getRange(startIndex, endIndex).toList(growable: false);
    notifyDataSourceListeners();
    return true;
  }
}

```

Please refer to the below UG link for your reference,

UG Link: https://help.syncfusion.com/flutter/datagrid/paging

And refer to our KB documentation for more details.

KB Link:  https://www.syncfusion.com/kb/12360/how-to-create-paginated-flutter-datatable-sfdatagrid

Please let us know if need any further assistance.

**Comment by davidp918** [comment]
Thanks, another question: How can I perform sort on initialization?

**Comment by davidp918** [comment]
Also, the sorting when using datapager is a bit broken. It only sorts the data of the current page instead of the whole data source. Is there any workaround to sort the whole thing?

**Comment by davidp918** [comment]
And also, how can I center the datagrid? It seems to be using up all the horizontal space, but the columns width is not using all that space, and so the grid is on the left(just like when using CrossAxisAlignment.start in Column).

**Comment by davidp918** [comment]
Hmm, I'll open a seperate issue on these.
