### ISSUE TITLE
[Issue] Adding all pages of existing pdf document to new empty pdf document results in increased file size in syncfusion_flutter_pdf plugin

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#262]
Hello, 

Issue:- I tried using syncfusion_flutter_pdf to create a new pdf document by adding all pages of the existing pdf document to the new pdf document with no extra content but when I checked the new pdf document size I found that it was double the size than the old pdf. This should not be the case as both pdfs have the same content.
I hope for a solution to this issue.

Thanks. for providing this awesome plugin.

**Comment by Anand3595** [comment]
Hi @brightseagit,

Thanks for contacting Syncfusion support.

Content copying from an existing PDF by using createTemplate() method is processed for each page in PDF document as a separate process. In this process, resources like images and fonts are duplicated for each page. So by default, the page size getting increased in new PDF, if an existing PDF document having same resource reference in difference pages. It is the behavior to copy the existing PDF pages via createTemplate() option.

The duplicate resource will be handled by merging of PDF documents. Currently we do not have support to merge PDF documents. We have already logged the feature for “Add support to merge PDF documents”. We will implement this feature in any of our upcoming release.

You can track the feature status using the feedback from https://www.syncfusion.com/feedback/25644/add-support-to-merge-pdf-documents.

Please let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thanks for providing this detailed response. I hope to see the 'support to merge PDF documents' feature in this plugin.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

Thank you for your patience.

As we said earlier, we will implement this feature “Add support to merge PDF documents” in any of our upcoming release. We usually have an interval of at least three months between releases, at the planning stage of every release cycle, will review all the open features and we will notify you once this support is included.    

You can track the status of the implementation in the below feedback.    
https://www.syncfusion.com/feedback/25644/add-support-to-merge-pdf-documents

With Regards,
Anand Panchamoorthi
