### ISSUE TITLE
Unsupported Error 

### ISSUE THREAD

**Issue by Rishabh11200** [syncfusion/flutter-widgets#263]
The following UnsupportedError was thrown building Builder:
Unsupported operation: Platform._operatingSystem

This error is coming while opening pdf on Microsoft edge web build . Flutter version is latest with null safety.

**Comment by Anand3595** [comment]
Hi Rishabh shah,

Thanks for contacting Syncfusion support.

We have tried the PDF creation with syncfusion_flutter_pdf package in Edge browser and the reported issue is not reproduced in our end. Please try the web application to create PDF with syncfusion_flutter_pdf package from https://www.syncfusion.com/kb/11973/how-to-create-a-pdf-file-in-flutter-web-platform.

We are requesting you to provide the below details to reproduce the reporting issue and to validate further in our side. It would more helpful for us to analyze further and provide you a prompt solution.
-	Sample/code to reproduce the reported issue.
-	Syncfusion package details which you have used for open the PDF document.

With Regards,
Anand Panchamoorthi
