### ISSUE TITLE
[syncfusion_flutter_pdfviewer] There is no method to get current page scroll offset

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#264]
At present scroll offset can be read by `_pdfViewerController.scrollOffset`.

This method gives the scroll offset and this is calculated from starting of document.

If i want to get the 1st visible line on screen or get onscreen text somehow then there is no method or I have to calculate the height of all previous pages.

It would be better if current page offset is also exposed relative to current page rectangle itself. For example `_pdfViewerController.currentPageOffset` or something similar method should return the offset.

Regards,
Sagar.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

The [getSelectedTextLines ](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewerState/getSelectedTextLines.html) API is used for extracting the text of the selected line, bounds information of the selected text, and to retrieve the page number of the selected text in a PDF document. This API will be helpful for adding annotation in the PDF document using Syncfusion Flutter PDF package which illustrated in the following KB link
[KB documentation](https://www.syncfusion.com/kb/12604/how-to-add-highlight-underline-and-strike-through-annotation-in-syncfusion-flutter-pdf)

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
Hi @dillibabun,

Thanks for quick reply.

I have alredy used that API. But that will give information only when there is selection. What if details to be taken without selection.

And if there is selection, how to find out how much selected text is currenlty visible on screen ?

At present SfPdfViewer already have `_pdfViewerController.scrollOffset` method, `SfPdfViewer.onPageChanged` callback and `SfPdfViewer.onZoomLevelChanged` callback available. But using all these methods together, I am unable to find out that how much part of page is currently visible on screen.

There is excellent documentation on coordinates [here](https://www.pdftron.com/documentation/core/guides/features/viewer/coordinates/)

Regards,
Sagar.

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Thank you for the update.

We can understand your requirement and API to be exposed "currentPageOffset " and "currentVisibleText". To implement these API, we need to know all requirement and usages of these APIs. So, kindly share us your complete usecase scenario in which these APIs are required which will be helpful in analyzing the feasibility and implement them.


For further queries, You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). If you face any problems while creating incident, it can be troubleshooted by following [this link](https://www.syncfusion.com/kb/8882/unable-to-create-a-support-incident). We are always happy to assist you! 

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
Hi @dillibabun,

At present I am busy with my some other important stuffs. Afterwards when I get time I will update the issue with exact usage scenario. At present I am closing the issue.

Thanks and Regards,
Sagar
