### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Open hyperlink on PDF Viewer

### ISSUE THREAD

**Issue by doanminhtien** [syncfusion/flutter-widgets#265]
Is this currently supported or will it be in the future?

Best regards,
Tien

**Comment by dillibabun** [comment]
Hi Tien,

At present we do not have hyperlink support in SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented on or before our 2021 Volume 4 main release. We will let you know when this feature is implemented. The status of this feature can be tracked using the following link.
[https://www.syncfusion.com/feedback/21134/support-for-hyperlink](https://www.syncfusion.com/feedback/21134/support-for-hyperlink) 

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.
