### ISSUE TITLE
syncfusion_flutter_sliders is not working in modal_bottom_sheet

### ISSUE THREAD

**Issue by kamleshwebtech** [syncfusion/flutter-widgets#266]
https://pub.dev/packages/syncfusion_flutter_sliders#add-range-slider-elements

I am using standard example of syncfusion_flutter_sliders mentioned in readme tab on pub.dev

```
SfRangeValues _values = SfRangeValues(40.0, 80.0);

@override
Widget build(BuildContext context) {
   return Scaffold(
     appBar: AppBar(
       title: const Text('Syncfusion Flutter Range Slider'),
     ),
     body: SfRangeSlider(
        min: 0.0,
        max: 100.0,
        values: _values,
        interval: 20,
        showTicks: true,
        showLabels: true,
        enableTooltip: true,
        minorTicksPerInterval: 1,
        onChanged: (SfRangeValues values){
          setState(() {
            _values = values;
          });
        },
      ),
   );
}
```

I have added it in modal_bottom_sheet but when I move/adjust slider ticker, it does not change from old ticker position to new ticker position. I think setState feature is not able to change the updated ticker state. Kindly suggest me how can I fix this issue and use this beautiful widget in my project. Thanks a lot. Look forward to hear you.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Kameshwebtech, 
 
Greetings from Syncfusion support. 
 
We have checked the thumb dragging and thumbs are moved to the new position while dragging. We have attached the sample for your reference. 
 
**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/range_slider623759775
 
**Query:** I have added it in modal_bottom_sheet 
 
We don’t know what the “model_bottom_sheet” is, so we can’t confirm from our end. Could you please check the above sample and, if you still have problems, kindly revert us by modifying the sample based on your requirement which will be helpful to assist you earlier. 
 
Regards, 
Lakshmi R.

**Comment by KaMing811** [comment]
hi i have same problem in this , when i put sfSlider into showModalBottomSheet() it can not slide

**Comment by KaMing811** [comment]
here is my code :
  showModalBottomSheet(
                isScrollControlled: true,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10.0),
                ),
                // isScrollControlled:true,

                context: context,
                builder: (_) {
                  return new Column(
                    children: <Widget>[
.....
 SfSlider(
                        min: 0.0,
                        max: 100.0,
                        value: _value,
                        interval: 20,
                        showTicks: true,
                        showLabels: true,
                        enableTooltip: true,
                        minorTicksPerInterval: 1,
                        onChanged: (dynamic value) {
                          setState(() {
                            _value = value;
                          });
                        },
                      ),
 ],
                  );
                });

**Comment by KaMing811** [comment]
i just find the answer is setBottomState in StateBuilder , hope this is helping

**Comment by love-311** [comment]
same trouble on showMaterialModalBottomSheet
