### ISSUE TITLE
How to use integer range?

### ISSUE THREAD

**Issue by kamleshwebtech** [syncfusion/flutter-widgets#267]
When I change range slider, it is returning and showing tool tips in double while I want to use only integer values every where. Kindly suggest how can I do? Thanks.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Kameshwebtech, 
 
Greetings from Syncfusion support. 
 
You can show tooltip in integer value using the tooltipTextFormatterCallback property in the SfRangeSlider. Please refer the below link for more details. 
 
https://help.syncfusion.com/flutter/range-slider/tooltip#tooltip-text-format 

**Code snippet:**
```
SfRangeValues _values = SfRangeValues(40.0, 80.0);

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfRangeSlider(
      min: 0.0,
      max: 100.0,
      values: _values,
      interval: 20,
      showTicks: true,
      showLabels: true,
      enableTooltip: true,
      tooltipTextFormatterCallback:
          (dynamic actualValue, String formattedText) {
        return actualValue.toStringAsFixed(0);
      },
      minorTicksPerInterval: 1,
      onChanged: (SfRangeValues values) {
        setState(() {
          _values = values;
        });
      },
    ),
  );
} 
```

Kindly let us know if you need further assistance with this. 
 
Regards, 
Lakshmi R.
