### ISSUE TITLE
SfDataPager button size & Custom button

### ISSUE THREAD

**Issue by jayan2019** [syncfusion/flutter-widgets#269]
Hi is there any way to add custom button for tha SfDataPager. And i would like to have small button, but the selected and other buttons are not resizing.

<img width="302" alt="Screenshot 2021-06-02 at 15 14 55" src="https://user-images.githubusercontent.com/46986762/120458903-4d669f00-c3b5-11eb-8976-bf91c8601f34.png">

Custom button means something like this:

<img width="372" alt="Screenshot 2021-06-02 at 15 16 30" src="https://user-images.githubusercontent.com/46986762/120459164-8ef74a00-c3b5-11eb-9429-8fc6f4b6f204.png">

**Comment by RenugaSadagoban98** [comment]
Hi @jayan2019,
Thank you for contacting Syncfusion support.


Currently, SfDataPager doesn’t have the support for adding the custom button.

We have considered your request as a feature. This feature will be implemented in our 2021 volume 3 release.

But you can able change the appearance of the page button using pageItemBuilder in SfDataPager.

Refer to the following code snippet,

```
  Widget _buildDataPager() {
    return SfDataPagerTheme(
      data: SfDataPagerThemeData(
        itemBorderColor: Colors.red,
        itemBorderWidth: 1,
        backgroundColor: Colors.transparent,
        itemBorderRadius: BorderRadius.circular(0),
      ),
      child: SfDataPager(
        pageItemBuilder: (String value) {
          return Container(
              child: Text(
            value,
            style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700),
          ));
        },
        delegate: orderInfoDataSource,
        pageCount:
            orderInfoDataSource.orders.length / orderInfoDataSource.rowsPerPage,
        direction: Axis.horizontal,
      ),
    );
  }
```
![image](https://user-images.githubusercontent.com/77044081/120670188-cf39f380-c4ad-11eb-9c57-fb23b6ed4071.png)

 
We will share the further details by tomorrow (3rd Jun 2021). If you have any concerns about this, please let us know.

Regards,
Renuga devi S

**Comment by RenugaSadagoban98** [comment]
Hi @jayan2019 ,
Thanks for your patient.

As we said earlier, we have considered “Support to change the size of page button in SfDatapager” as a feature. We have planned to implement this feature in our upcoming  2021 volume 3 release. Which is expected to be rolled out on mid of October 2021. You can follow up with the below feedback link,

Feedback Link: https://www.syncfusion.com/feedback/25938/support-to-change-the-size-of-the-page-buttons-in-sfdatapager

we appreciate your patience until then. For further assistance, you can follow the feature request.

Regards,
Renuga devi.

**Comment by RenugaSadagoban98** [comment]
Hi @jayan2019 , 
  
We are glad to announce that our Essential Studio 2021 Volume 3 Main Release V19.3.0.43 is rolled out and is available for download under the following link. 
  
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download 
 
Refer to the following UG links for resizing and hide the page button, 

https://help.syncfusion.com/flutter/datagrid/paging#set-the-height-and-width-for-the-page-items
https://help.syncfusion.com/flutter/datagrid/paging#hide-certain-navigation-page-items
 
  
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 

Regards, 
Renugadevi
