### ISSUE TITLE
Error on document loading after cache removal

### ISSUE THREAD

**Issue by UmairRehmat** [syncfusion/flutter-widgets#271]
Scenario
1-Load document from the URL. loaded successfully 
2-Replace screen/ navigate to another. and clear cache
3-open PDF screen again. it tried to load but then throw this error

![WhatsApp Image 2021-06-03 at 11 12 27 AM](https://user-images.githubusercontent.com/55428807/120597998-2b295b80-c45f-11eb-88c3-03cbfd5c62e9.jpeg)

**Comment by sarathkumar50** [comment]
Hi @UmairRehmat ,

Greetings from Syncfusion.

We tried to reproduce reported issue with "Error on document loading after cache removal" but the SfPdfViewer works properly. We have also ensured in the console and errors wasn't reproduced. We have shared the issue illustrating video which can be downloaded the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/VID-20210604-WA00011352748787.zip

sample code:
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
void main() {
  runApp(MaterialApp(
    title: 'Syncfusion PDF Viewer Demo',
    home: HomePage(),
  ));
}
/// Represents Homepage for Navigation
class HomePage extends StatefulWidget {
  @override
  _HomePage createState() => _HomePage();
}
class _HomePage extends State<HomePage> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter PDF Viewer'),
        actions: <Widget>[
          IconButton(
            icon: const Icon(
              Icons.arrow_forward,
              color: Colors.white,
            ),
            onPressed: () {
              Navigator.push<dynamic>(
                  context,
                  MaterialPageRoute<dynamic>(
                      builder: (BuildContext context) => SecondScreen()));
            },
          ),
        ],
      ),
      body: SfPdfViewer.network(
        'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
        key: _pdfViewerKey,
      ),
    );
  }
}
///
class SecondScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Second Screen'),
      ),
      body: const Center(
        child: Text('Second Screen'),
        ),
    );
  }
}
```

If you still facing any issue, kindly share us the detailed issue reproducing steps or sample application which will be helpful for us to provide you a prompt solution at the earliest.


Regards,
Sarath Kumar.

**Comment by UmairRehmat** [comment]
Hy.. thanks. 

I'll share the code. With you guys.

**Comment by UmairRehmat** [comment]
> Hi @UmairRehmat ,
> 
> Greetings from Syncfusion.
> 
> We tried to reproduce reported issue with "Error on document loading after cache removal" but the SfPdfViewer works properly. We have also ensured in the console and errors wasn't reproduced. We have shared the issue illustrating video which can be downloaded the following link:
> https://www.syncfusion.com/downloads/support/directtrac/general/ze/VID-20210604-WA00011352748787.zip
> 
> sample code:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
> void main() {
>   runApp(MaterialApp(
>     title: 'Syncfusion PDF Viewer Demo',
>     home: HomePage(),
>   ));
> }
> /// Represents Homepage for Navigation
> class HomePage extends StatefulWidget {
>   @override
>   _HomePage createState() => _HomePage();
> }
> class _HomePage extends State<HomePage> {
>   final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
>   @override
>   void initState() {
>     super.initState();
>   }
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Syncfusion Flutter PDF Viewer'),
>         actions: <Widget>[
>           IconButton(
>             icon: const Icon(
>               Icons.arrow_forward,
>               color: Colors.white,
>             ),
>             onPressed: () {
>               Navigator.push<dynamic>(
>                   context,
>                   MaterialPageRoute<dynamic>(
>                       builder: (BuildContext context) => SecondScreen()));
>             },
>           ),
>         ],
>       ),
>       body: SfPdfViewer.network(
>         'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
>         key: _pdfViewerKey,
>       ),
>     );
>   }
> }
> ///
> class SecondScreen extends StatelessWidget {
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Second Screen'),
>       ),
>       body: const Center(
>         child: Text('Second Screen'),
>         ),
>     );
>   }
> }
> ```
> 
> If you still facing any issue, kindly share us the detailed issue reproducing steps or sample application which will be helpful for us to provide you a prompt solution at the earliest.
> 
> Regards,
> Sarath Kumar.

We created a project for you to understand the issue batter and match the exact scenario. 
here is the link for the project | https://github.com/UmairRehmat/pdf-loading-error
Also check this video. https://www.dropbox.com/s/1nucju4k9xvbrzd/pdf_document_loading_error_video.mp4
 for batter understanding. Thanks.

**Comment by sarathkumar50** [comment]
Hi @UmairRehmat ,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 10th June 2021.

Regards,
Sarath Kumar.

**Comment by dillibabun** [comment]
Hi @UmairRehmat,

On analyzing your codes, we found that the reported issue is reproduced only when explicitly deleting the temporary directory and the application was working fine when clear cache in "App Info". Internally clearing cache in "App Info" doesn't delete the temporary directory of the application instead deletes all files in it. Since we have created a cache file to pass Android PdfRenderer, we need the temporary directory. We request you create a empty temporary directory once you clear the cache as mentioned in the following codes.

```
Future<void> _deleteCacheDir() async {
    final cacheDir = await getTemporaryDirectory();
    if (cacheDir.existsSync()) {
      cacheDir.deleteSync(recursive: true);
    }
    cacheDir.create(); // creating empty temp directory
  }
```

For further queries, You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). If you face any problems while creating an incident, it can be trouble-shooten by following [this link](https://www.syncfusion.com/kb/8882/unable-to-create-a-support-incident). We are always happy to assist you! 

Regards,
Dilli babu.
