### ISSUE TITLE
How to use .shp file from arcGIS?

### ISSUE THREAD

**Issue by dheerajsarwaiya** [syncfusion/flutter-widgets#275]
Is it possible to use .shp file from arcGIS to create maps? 

If yes, can you please provide an example?

If not, are you planning to add this feature?

thanks

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Dheerajsarwaiya, 
 
Greetings from Syncfusion support. 
 
You can use the .shp file to create maps by converting the shp file into Geojson file using the steps mentioned in the below KB. 
 
**KB:** https://www.syncfusion.com/kb/12367/how-to-visualize-the-shp-files-in-flutter-maps 
 
Please let us know if you need further assistance with this. 
 
Regards, 
Lakshmi R.
