### ISSUE TITLE
DataGridRow overlaping the content

### ISSUE THREAD

**Issue by fathah** [syncfusion/flutter-widgets#277]
When I set the ```rowHeight:```  the texts are overlapped. If I increase the ```rowHeight``` it's fine. I need a small sized row. Any fixes?

### ```rowHeight: 40``` 
<img src="https://i.ibb.co/wKtgdcf/datagrid.png" alt="datagrid" border="0"></a>

### ```rowHeight: 30```
<a href="https://ibb.co/260Svd1"><img src="https://i.ibb.co/GJf9WR4/datagrid30.png" alt="datagrid30" border="0"></a>

### ```rowHeight: 50```
<a href="https://ibb.co/W5cCWpg"><img src="https://i.ibb.co/7CGhJN2/datagrid50.png" alt="datagrid50" border="0"></a>

Also when I click (select) a row, the row size increases. It needs to be constant.

**Comment by fathah** [comment]
It was quite easy, and I was just not aware of

moify ```DataGridRowAdapter buildRow()```

**Comment by JesusMayuri7** [comment]
> Fue bastante fácil, y simplemente no estaba al tanto de
> 
> moificar `DataGridRowAdapter buildRow()`

Hi, I have the same problem, when performing some action, the row gets bigger

**Comment by fathah** [comment]
@JesusMayuri7  drop your code
