### ISSUE TITLE
Feature request for Checkbox column as in Flutter built-in PaginatedDataTable

### ISSUE THREAD

**Issue by fathah** [syncfusion/flutter-widgets#278]
Please add a similar feature as in Flutter built-in ```PaginatedDataTable``` with Checkbox column at the beginning and select-all checkbox in the column header.

<a href="https://ibb.co/L6TK607"><img src="https://i.ibb.co/bL4tL69/paginated.png" alt="paginated" border="0"></a>

Thanks

**Comment by RenugaSadagoban98** [comment]
Hi Fathah , 
 
Greetings from Syncfusion.
 
You can achieve your requirement by using programmatic selection support in DataGrid. To select the multiple rows in DataGrid, you should set the selectionMode property as SelectionMode.multiple. 
 
To select/deselect the rows based on the checkbox including the header checkbox, you can use the DataGridController.selectedRows property. For more information about this property, refer the below UG,
**UG link:** https://help.syncfusion.com/flutter/datagrid/selection#programmatic-selection

```

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(cells: [
      Container(
        alignment: Alignment.center,
        padding: EdgeInsets.symmetric(horizontal: 16),
        child: Text(row.getCells()[0].value.toString()),
      ),
      Container(
        alignment: Alignment.center,
        padding: EdgeInsets.symmetric(horizontal: 16),
        child: Text(row.getCells()[1].value),
      ),
      Container(
        alignment: Alignment.center,
        padding: EdgeInsets.symmetric(horizontal: 16),
        child: Text(row.getCells()[2].value.toString()),
      ),
      Container(
          alignment: Alignment.center,
          padding: EdgeInsets.symmetric(horizontal: 16),
          child: Checkbox(
            value: row.getCells()[3].value,
            onChanged: (value) {
              final index = _dataGridRow.indexOf(row);
              employeeData[index].isAvailable = value!;
              row.getCells()[3] =
                  DataGridCell(value: value, columnName: 'isAvailable');
              if (value) {
                _dataGridController.selectedRows = [
                  ..._dataGridController.selectedRows.toList()..add(row)
                ];
              } else {
                _dataGridController.selectedRows = [
                  ..._dataGridController.selectedRows.toList()..remove(row)
                ];
              }
            },
          ))
    ]);
  }
```


Please refer to the following code snippet to all rows selection and deselection using headerCell of Check box column.
```
SfDataGrid(
          source: productDataSource,
          controller: _dataGridController,
          selectionMode: SelectionMode.multiple,
          columns: <GridColumn>[
            GridTextColumn(
                columnName: 'id',
                width: 80,
                label: Container(
                    padding: EdgeInsets.symmetric(horizontal: 16.0),
                    alignment: Alignment.center,
                    child: Text(
                      'ID',
                    ))),
            GridTextColumn(
                columnName: 'product',
                width: 120,
                label: Container(
                    padding: EdgeInsets.symmetric(horizontal: 16.0),
                    alignment: Alignment.center,
                    child: Text('Product'))),
            GridTextColumn(
                columnName: 'price',
                width: 75,
                label: Container(
                    padding: EdgeInsets.symmetric(horizontal: 16.0),
                    alignment: Alignment.center,
                    child: Text('Price'))),
            GridTextColumn(
                columnName: 'isAvailble',
                width: 150,
                label: Container(
                  padding: EdgeInsets.symmetric(horizontal: 16.0),
                  alignment: Alignment.center,
                  child: Checkbox(
                    value: _isAvailble,
                    onChanged: (value) {
                      _isAvailble = value;
                      if (_isAvailble == true) {
                        _dataGridController.selectedRows = [];
                        setState(() {
                          productDataSource.employeeData.forEach(
                              (employee) => employee.isAvailable = true);
                          productDataSource.updateDataGridDataSource();
                        });
                        _dataGridController.selectedRows = [
                          ...productDataSource._dataGridRow
                        ];
                      } else {
                        // You need to clear the selectedRows collection before update the employee collection.
                        _dataGridController.selectedRows = [];
                        setState(() {
                          productDataSource.employeeData.forEach(
                              (employee) => employee.isAvailable = false);
                          productDataSource.updateDataGridDataSource();
                        });
                      }
                    },
                  ),
                ))
          ]),

```

We have prepared the sample for your reference,  
**Sample link:**   https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1612750852

We will publish a KB for this use case. Please let us know if you require any further assistance. 

Regards,
Renuga devi

**Comment by fathah** [comment]
It would be so useful if it's a feature in the library, instead of manual configurations. I saw this as a feature in **Syncfusion Blazor**

**Comment by RenugaSadagoban98** [comment]
Hi @fathah, 
Thanks for your update.  

 We have considered your request as a feature. This feature will be implemented in our any of our upcoming release. We will let you know when this feature is implemented. You can follow up with the below feedback for further follow up,  

**Feedback link:** https://www.syncfusion.com/feedback/26197/support-to-show-the-checkbox-column-to-select-the-rows

Regards,
Renuga devi S

**Comment by fathah** [comment]
Thanks, @RenugaSadagoban98 
Waiting for the update!

**Comment by RenugaSadagoban98** [comment]
Hi @fathah, 

Thanks for your patience. 

 
We are glad to announce that our Essential Studio 2021 Volume 3 Main Release V19.3.0.43 is rolled out and is available for download under the following link. 
  
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download 

Refer to the following UG link to know about showing check box column, 
UG link: https://help.syncfusion.com/flutter/datagrid/column-types#checkbox-column 


We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 

  
Regards, 
Renugadevi

**Comment by fathah** [comment]
@RenugaSadagoban98 thanks for this wonderful update. Great work🚀🤟

**Comment by RenugaSadagoban98** [comment]
Hi @fathah,

Thanks for your interest in Syncfusion Products. 
  
Please get in touch with us if you would require any further assistance. We will be happy to assist you.

Regards, 
Renugadevi
