### ISSUE TITLE
syncfusion_flutter_sliders  Numerical flip 

### ISSUE THREAD

**Issue by jahnli** [syncfusion/flutter-widgets#279]
![image](https://user-images.githubusercontent.com/20943608/121645919-5519f800-cac7-11eb-800b-345f91857bbf.png)
Currently the Syncfusion_Flutter_Sliders maximum is at the top and minimum is at the bottom  .
Is there a parameter or scheme that can be adjusted to have the maximum at the bottom and the minimum at the top   ？

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,  
 
We have considered your request as a feature and the status can be tracked from the feedback portal link.    
  
**Feedback:** https://www.syncfusion.com/feedback/26173/provide-an-option-to-change-minimum-and-maximum-position-of-vertical-slider  
  
We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our releases.   
    
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.   
 
Regards, 
Lakshmi R.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Jahnli,

We are glad to announce that our Essential Studio 2021 Volume 3 release v19.3.0.43 is rolled out and we have included the “Inversed option in the vertical slider and vertical range slider”. It is available for download under the following link. 
  
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download 

**Code Snippet:** 

```dart
 double _value = 40;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfSlider.vertical(
        min: 0,
        max: 100,
        value: _value,
        interval: 20,
        showLabels: true,
        isInversed: true,
        onChanged: (dynamic newValue) {
          setState(() {
            _value = newValue;
          });
        },
      ),
    );
  }
}
```

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
  
Regards,           
Lakshmi R.
