### ISSUE TITLE
New chart request - a chart with date axis and time axis

### ISSUE THREAD

**Issue by SamsonChris71** [syncfusion/flutter-widgets#281]
I need a chart with X-axis only deals with time and Y-axis deals with date.
The DateTime axis already given was not meeting my design criteria.
**I need to plot time on X-axis and date on Y-axis.**

For example, I need to indicate a range of time in a chart in which start and end DateTime should be plotted.
Given data with start DateTime as 18th June, 5.30 pm and end DateTime as 18th June, 5.45 pm,
the Y-axis (Date axis) should have one column with the date specified, which is 18th June.
Corresponding to the Y-axis two values should be plotted, which are 5.30 pm and 5.45 pm in respect to X-axis (Time axis).

Please develop this graph it would be much helpful for me.
If it can be implemented with the existing graphs please guide me on the same.
Thanks

**Comment by Dharanipalani** [comment]
Hi @SamsonChris71,

Thanks for the interest in our Flutter charts. We have analyzed your request and like to share this [calendar](https://flutter.syncfusion.com/#/event-calendar/recurrence) sample. Are you expecting the same as in the charts or other than this? Please share more details about your requirement like screenshot, competitor's reference links, will help us to analyze and provide the solution to you sooner.

Thanks,
Dharanitharan. P

**Comment by SamsonChris71** [comment]
Hi @Dharanipalani 

Thanks a lot for sharing the sample. It almost fulfilled my design requirement. 
The only thing is that I need to transpose both the X and Y axis, like in SfCartesianChart. 
Please guide me on this, and thanks for taking the effort in helping me.

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: The only thing is that I need to transpose both the X and Y axis, like in SfCartesianChart.**

We regret to inform you that as per the current implementation of the Flutter Calendar, does not have support to transpose the timeslots and days. However, could you please refer to the timeline views sample below for your requirements?

**Link:** https://flutter.syncfusion.com/#/event-calendar/timeline-views

If this is not your requirement, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by SamsonChris71** [comment]
Hi @Indumathi1195R,

Thanks for taking the effort to help me. I have shared my design requirement below. It's a simple diagram. Please guide me. 
Thanks again for your team, your team made our work much easier.

![Calendar_1](https://user-images.githubusercontent.com/30178043/123253994-b8fee080-d50b-11eb-8393-b3fba6252d47.jpg)

**Comment by Indumathi1195R** [comment]
Hi,

We regret to inform you that the current implementation of the Flutter Calendar, does not have support to show the date on the left side of the calendar. Please let us know if you require any other assistance.

Regards,
Indumathi R

**Comment by SamsonChris71** [comment]
@Indumathi1195R 

Oh okay. Thanks for your support.
