### ISSUE TITLE
Swiping in DataGrid should have RowIndex found in Details instead only DataGridRow is given

### ISSUE THREAD

**Issue by EricPHassey** [syncfusion/flutter-widgets#283]
In the official documentation, you have endSwipeActionsBuilder and startSwipeActionsBuilder, however you didn't expose the return of the Details, you only return DataGridRow. DataGridRow according to the documentation, does not tell you what index you're at. Only Details does.

You do return RowIndex in the Details callback, but given how important it is to know what row was tapped, this should have been a priority in the swipeActionsBuilder. I'm aware you can find the index, but it's extremely cluttered having to use the indexOf of the datagridsource just to find the index.

If you're exposing the index for the details, then clearly it should be available. Please add that to help simplify things.

Thank you.

**Comment by RenugaSadagoban98** [comment]
Hi Customer, 
Thanks for contacting Syncfusion support.  
 We have considered your request as enhancement. This enhancement will be implemented in our 2021 Volume 2 SP release. which is expected to be rolled out on mid of July 2021. You can follow up with the below feedback for further follow up,  
Feedback link: https://www.syncfusion.com/feedback/26346/pass-the-row-index-as-the-arguments-for-startswipeactionsbuilder-and

Regards,
Renuga devi S
