### ISSUE TITLE
excel (xlsio package) image does not fits in the cell

### ISSUE THREAD

**Issue by burakcbdn** [syncfusion/flutter-widgets#285]
I am trying to add image to merged cell and images are generally does not fits in the cell

Example:
![IMG_29FD4C1EC6DA-1](https://user-images.githubusercontent.com/55558309/122655391-a3c83180-d15a-11eb-97cd-6826e0899a42.jpeg)

my code: 
```Dart

          final Picture applicationPicture =
              worksheet.pictures.addStream(cell.row, cell.column, applicationPictureBytes)
            
              ..lastColumn = 5
              ..lastRow = cell.row + 1;
```

**Comment by Sridhar-Sukumar** [comment]
Hi @burakcbdn, 

We are unable to reproduce the reported issue at our end. The sample which we have tried can be downloaded from the following link.

Sample Link:  https://www.syncfusion.com/downloads/support/directtrac/general/ze/create_excel-25928361.zip

Kindly modify and share us the issue reproducing sample, which will be helpful for us in investigating the query and provide prompt solution at the earliest. 

Regards,
Sridhar.

**Comment by burakcbdn** [comment]
Seems like it was a problem with iOS file manager. When I open created excel file via other excel apps there is no problem, but if I open file on the iOS file manager this problem occurs.
