### ISSUE TITLE
[syncfusion_flutter_calendar] Anyway custom indicator size?

### ISSUE THREAD

**Issue by WingCH** [syncfusion/flutter-widgets#286]
![image](https://user-images.githubusercontent.com/19588517/122733128-79d45380-d2af-11eb-8525-4f5c4320c9c5.png)

I would like to set indicator size bigger.
 
```dart
SfCalendar(
              view: CalendarView.month,
              showNavigationArrow: true,
              initialSelectedDate: DateTime.now(),
              dataSource: state.dataSource,
              monthViewSettings: MonthViewSettings(
                appointmentDisplayMode: MonthAppointmentDisplayMode.indicator,
                // showAgenda: true,
                agendaViewHeight: 400,
                agendaItemHeight: 70,
                dayFormat: 'EEE',
              ),
              onTap: logic.calendarTapped,
            ),
```

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

**Regarding Query: Anyway custom indicator size?**

We regret to inform you that the current implementation of the Flutter Calendar doesn’t have support to increase the appointment indicator size. Using the custom builder, you can add the required UI for appointment cells. Also, we have a KB document for customizing the cell based on appointment using the custom builder. Please find the KB from the following links.

**KB links:** https://www.syncfusion.com/kb/12210/how-to-customize-the-month-cell-based-on-the-appointment-using-builder-in-the-flutter
https://www.syncfusion.com/kb/12306/how-to-customize-the-month-cell-with-appointment-count-in-the-flutter-calendar 

Regards,
Indumathi R

**Comment by WingCH** [comment]
thanks very much!
