### ISSUE TITLE
How to show short value of price in yMapper in Barchart

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#287]
Hi, 
I have facing problem to show short price value in yMapper like if price is 10000 then I want to show 10K in yMapper but I have seen in your library class there num value was showing in class, so its difficult to handle for me, kindly help me out this problem.

the values in given below picture on y-Axis can not showing like 25k, 10M

<img width="130" alt="Screen Shot 2021-06-23 at 11 14 30 AM" src="https://user-images.githubusercontent.com/65191117/123045391-4c54ea80-d414-11eb-8dee-f4a194830a33.png">

**Comment by Dharanipalani** [comment]
Hi @waqaryounusjatt788,

Thank you for taking the time to learn more about our Flutter charts. We have investigated your request and would like to recommend the following knowledge base article for customizing the axis labels with number format to meet your needs. This KB explains the axis labels in both currency and non-currency formats.

KB: [https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart](https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by waqaryounusjatt788** [comment]
Thank you
