### ISSUE TITLE
[syncfusion_flutter_charts] Display custom axis label at certain value 

### ISSUE THREAD

**Issue by millerovv** [syncfusion/flutter-widgets#288]
Hello, Syncfusion team!

I am trying to create a chart that displays stock market value dynamic. 
I have now managed to display the current stock size (the gray horizontal plot band on the screen shot) using PlotBand. Now I can't seem to find in the documentation the information on wether it is possible to put a custom label on the Y axis just beside the PlotBand (so, at the same Y value).

<img width="334" alt="Снимок экрана 2021-06-23 в 13 10 36" src="https://user-images.githubusercontent.com/31796433/123079968-1a984f80-d425-11eb-9b85-009bd462ce96.png">

I couldn't manage to do it with PlotBand.text, because this text is constrained by the plot area.

<img width="289" alt="Снимок экрана 2021-06-23 в 13 22 51" src="https://user-images.githubusercontent.com/31796433/123081066-3819e900-d426-11eb-9850-028ef0e36b24.png">

Thanks in advance

**Comment by Dharanipalani** [comment]
Hi @millerovv,

Thanks for the interest in our Flutter charts. We have investigated your request and found that we can't use plotbands to place text at a certain location. Instead, we recommend utilizing the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/axisLabelFormatter.html) callback to customize the label as like in the following kb.

KB: [https://www.syncfusion.com/kb/11678/how-to-customize-the-axis-labels-using-callback-events-sfcartesianchart](https://www.syncfusion.com/kb/11678/how-to-customize-the-axis-labels-using-callback-events-sfcartesianchart)

Furthermore, you may utilize the [annotations](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/annotations.html) property in the chart to set the custom widget in the needed location, and you can use this for your requirements as well. We would like to point out that if the annotation's width or height is greater than the chart, it will be hidden. Please see the assistance document below for further information.

[https://help.syncfusion.com/flutter/cartesian-charts/annotations](https://help.syncfusion.com/flutter/cartesian-charts/annotations)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by millerovv** [comment]
Thank you! I have managed to achieve the needed look
