### ISSUE TITLE
[syncfusion_flutter_charts] Disable SfCartesianChart trackball on one of the multiple series

### ISSUE THREAD

**Issue by millerovv** [syncfusion/flutter-widgets#289]
Greetings!

Is it possible to display multiple series on SfCartesianChart, and enable TrackballBehavior only for one of them? 
As you can see on the screenshot, there are two trackball circles on chart, and it is currently very misleading in my case.

<img width="403" alt="Снимок экрана 2021-06-23 в 14 05 59" src="https://user-images.githubusercontent.com/31796433/123086738-77e3cf00-d42c-11eb-8c4e-d534cba766bf.png">

As always, thank you for work!
Looking forward to your answer

**Comment by Dharanipalani** [comment]
Hi @millerovv,

Thank you for the interest in our Flutter charts. We have investigated your issue and would like to recommend the following knowledge base article, which hides the trackball marker for a specific series, as per your request.

KB: [https://www.syncfusion.com/kb/12107/how-to-disable-the-trackball-marker-for-specific-series-in-cartesian-charts](https://www.syncfusion.com/kb/12107/how-to-disable-the-trackball-marker-for-specific-series-in-cartesian-charts)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by millerovv** [comment]
@Dharanipalani Thank you very much! This helped a lot
