### ISSUE TITLE
Begin change and End change callbacks needed

### ISSUE THREAD

**Issue by Tonku** [syncfusion/flutter-widgets#29]
Hi
We need begin change and end change events for slider.
Thank you

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Tonku,

Greetings from Syncfusion.

Could you please share mode details about your requirement and how this feature will be helpful for you to achieve that?

Based on these details, we will provide a solution or log a new feature request for this.

Regards,
Lakshmi R.

**Comment by skripsimu** [comment]
I need this feature to change the value of the slider when the slider is not changed anymore. because if I change it in onchange there will be too many changes there. @LakshmiRadhaKrishnan
