### ISSUE TITLE
[SfPdfViewer]The visible area of high resolution PDF cannot be changed

### ISSUE THREAD

**Issue by zartzhao** [syncfusion/flutter-widgets#291]
This is my quetion ： 
There is HR pdf that only has one page . There are blank areas above and below the PDF。When I zoom in on the PDF, the white space above and below will not change.The display area of PDF remains unchanged, just a small area in the middle。
zoom = 1
[zoom=1](https://github.com/zartzhao/rsql_dart/blob/master/Screenshot_20210624_111130_com.zwj.jpg)
zoom > 1
[zoom>1](https://github.com/zartzhao/rsql_dart/blob/master/Screenshot_20210624_111145_com.zwj.jpgg)

**Comment by dillibabun** [comment]
Hi @zartzhao 

Greetings from Syncfusion.

The reported issue has been resolved and issue fix has been included in our upcoming 2021 Volume 2 main release which will be available in couple of days. We will let you know once the release is rolled out. As per Adobe PDF behavior, you expect the grey area will reduced when zooming value is increased(Zoom In) so you can expect the same behavior in Syncfusion Flutter PdfViewer.

Regards,
Dilli babu.

**Comment by zartzhao** [comment]
> Hi @zartzhao
> 
> Greetings from Syncfusion.
> 
> The reported issue has been resolved and issue fix has been included in our upcoming 2021 Volume 2 main release which will be available in couple of days. We will let you know once the release is rolled out. As per Adobe PDF behavior, you expect the grey area will reduced when zooming value is increased(Zoom In) so you can expect the same behavior in Syncfusion Flutter PdfViewer.
> 
> Regards,
> Dilli babu.

Thank you.

**Comment by sarathkumar50** [comment]
Hi @zartzhao ,

We are glad to announce that our Essential Studio 2021 Volume 2 release v19.2.0.44 is rolled out and is available for download under the following link.

[Essential Studio 2021 Volume 2 Main Release v19.2.0.44 is available for download | Announcements Forums | Syncfusion
](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F166800%2Fessential-studio-2021-volume-2-main-release-v19-2-0-44-is-available-for-download&data=04%7C01%7Cdillibabun%40syncfusion.com%7C4340b0ddf9404699e5e708d93b986993%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637606348053414928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UA5dMir7P7nfeAivGC5Wu%2BweDivNoZz8js12fHFe4os%3D&reserved=0)

We have resolved the grey area issue in single page high resolution PDF and now, the SfPdfViewer behaves similar to Adobe mobile PDF. This change has been included in
2021 Volume 2 main release.

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sarath Kumar.
