### ISSUE TITLE
[syncfusion_flutter_charts] SfCartesianChart multiple series match X axis position

### ISSUE THREAD

**Issue by millerovv** [syncfusion/flutter-widgets#293]
Good day

I have one more question regarding multiple series usage with `SfCartesianChart`:

I would like to display a `CandleSeries` with `ColumnSeries` in such a way, that their X axis positions would match, so candles would in some places **be painted over** the `ColumnSeries`

Currently (see screenshots), when I add the `ColumnSeries`, Candles width become smaller and each X axis entry displays the candle and the column side by side. I can't figure out how to achieve the necessary behavior. 

P.s: it does work when I use SplineSeries instead of the `CandleSeries`, but now I need `CandleSeries` specifically  

<img width="221" alt="Снимок экрана 2021-06-24 в 17 01 32" src="https://user-images.githubusercontent.com/31796433/123276695-13993c00-d50e-11eb-9a48-51513aae1b33.png">

<img width="224" alt="Снимок экрана 2021-06-24 в 17 01 47" src="https://user-images.githubusercontent.com/31796433/123277005-61ae3f80-d50e-11eb-9092-644482851ce4.png">

main.dart file:
https://gist.github.com/millerovv/ab5b89fb7600e88c384ae6b531bee318

**Comment by Dharanipalani** [comment]
Hi @millerovv,

We have looked over your query and the code and believe that disabling the [enableSideBySideSeriesPlacement](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/enableSideBySideSeriesPlacement.html) property in the chart will help you reach your goal. After disabling that property from the chart, we have sent a screenshot for your reference. Please feel free to utilize it.

Screenshot:
![image](https://user-images.githubusercontent.com/19763272/123389343-6a0e8500-d5b7-11eb-83fb-3123425f9377.png)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by millerovv** [comment]
Thanks a lot!
