### ISSUE TITLE
[syncfusion_flutter_charts] Introduce crosshair snapping

### ISSUE THREAD

**Issue by steebchen** [syncfusion/flutter-widgets#294]
It would be great to configure the crosshair to snap to either the x and/or y axis values. You can achieve by using a mix of crosshair and trackball but I think it'd be nice to be able to configure snapping via crosshair directly.

**Comment by Dharanipalani** [comment]
Hi @steebchen,

Thank you for your interest in our Flutter charts. We have investigated your request and, sadly, we are not sure about your requirement. Please provide more information regarding your demand, such as a screenshot and links to competitor references. These will assist us in analyzing your situation and providing you with a solution more quickly.

Thanks,
Dharanitharan. P

**Comment by steebchen** [comment]
When I have different data points, for example

[ a, 9300 ]
[ b, 9000 ]

The crosshair renders on each pixel, which means when I move my mouse or my finger, the crosshair tooltips show not just 9300 or 9000, but for example 9179.612:

<img width="360" alt="Screenshot 2021-07-06 at 16 15 31" src="https://user-images.githubusercontent.com/5013932/124575221-690e0b00-de75-11eb-9df4-b25f79639bb8.png">

It would be awesome if one could set snapping options to the crosshair, so that not very specific random values such as 9179.612 would be selected, but rather maybe rounded to something, such as 9179, 9180, etc.

The same goes for the x axis – it should be configurable to snap to x points as well (like the trackball behaves – it also snaps to x axis values).

Let me know if that makes sense.

**Comment by Dharanipalani** [comment]
Hi @steebchen,

Thanks for the information. Now, based on this query we suggest you use the [onCrosshairPositionChanging](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onCrosshairPositionChanging.html) call back to customize the crosshair tooltip. We have attached the sample for your reference by rounding the crosshair tooltip value as like your requirement and kindly make use of it. Please revert us if you need any further assistance on this.

Sample: [github_294.zip](https://github.com/syncfusion/flutter-widgets/files/6781745/github_294.zip)

Thanks,
Dharanitharan. P
