### ISSUE TITLE
[syncfusion_flutter_pdfviewer] SfPdfViewer does not allow zoom out less then screen width

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#295]
At present SfPdfViewer fills all the available width of the screen. After that if user try to do zoom out then it does not allow zoom out less then screen width. It would be better if SfPdfViewer also allows zoom out less then screen width.

This behaviour is very useful when device is rotated to landscape mode.

When device is rotated to landscape mode and if the pdfviewer does not allow zoom out below screen width then only a small (ofcourse a bit zoomed) portion of the document will be visible on the screen. If the viewer allows more zoom out then probably user can better adjust the visible part of the pdf document.

Below are the screen recordings in landscape mode.

### Current Behaviour

https://user-images.githubusercontent.com/60609139/123626950-05f5f600-d82f-11eb-96ca-d376716ba15e.mp4

### Expected Behaviour

https://user-images.githubusercontent.com/60609139/123627001-15753f00-d82f-11eb-92b8-527d107c1a2d.mp4

**Comment by dillibabun** [comment]
Hi @sagarkardani 

Greetings from Syncfusion.

We are analyzing the feasibility of the reported feature. We will update the analysis details on 2 July, 2021.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Dilli babu.

**Comment by sarathkumar50** [comment]
Hi @sagarkardani,

The support to set the minimum zoom level will help you to zoom out beyond the default zoom level (that is less than the screen width). At present we do not have support to set the minimum zoom level in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.

The status of this feature can be tracked further from the following feedback link,
 
https://www.syncfusion.com/feedback/26648/support-to-set-minimum-zoom-level

Regards,
Sarath Kumar
