### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Unloaded pages not loading again after coming back to them

### ISSUE THREAD

**Issue by astralstriker** [syncfusion/flutter-widgets#296]
Some pages that are unloaded if off-screen do not render back when I come back to them.
How should I tackle this situation?

My PdfViewer widget is in a stack with a custom painter on top of it. Everything works fine except for the pages "disappearing".

Thanks for this fantastic plugin.

**Comment by sarathkumar50** [comment]
Hi @astralstriker ,

Greetings from syncfusion.

We tried to reproduce the reported issue.But its working fine for us.We have prepared a sample for your reference which can be downloaded in the following link.

https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app663138708.zip

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing sample which will be helpful for us to provide a prompt solution at the earliest.
You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar.

**Comment by astralstriker** [comment]
Thanks for reply.

I was using version 19.1.69-beta but when I upgraded to 19.2.44-beta as per the sample app that you sent, the issue seems to have gone away.

Was it a known issue in 19.1.69-beta? I was not able to find any issue related to it in the issues section here.

Again, many thanks for for preparing the sample just for my case.

**Comment by sarathkumar50** [comment]
Hi @astralstriker ,
 
We tried to reproduce the reported issue with [19.1.69-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.69-beta) package as well.But its working fine for us.
We are glad that the reported issue has been resolved at your end. Kindly let us know if you need any doubts. We are always happy to assist you!
 
Regards,
Sarath Kumar.

**Comment by astralstriker** [comment]
Thanks for the info.
