### ISSUE TITLE
SfSlider label fontsize change

### ISSUE THREAD

**Issue by a914-gowtham** [syncfusion/flutter-widgets#297]
I couldn't find anything to set the label fontsize  in the documentation.

Is that possible?

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Gowtham, 
 
Greetings from Syncfusion support. 
 
Using the text style properties of [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html), you can change the font size of the labels. The activeLabelStyle and inactiveLabelStyle are used to customize the track labels, and tooltipTextStyle is used to customize the tooltip labels.
 
Kindly refer the below documentation links for more reference. 
1. https://help.syncfusion.com/flutter/slider/labels-and-divider#label-style
2. https://help.syncfusion.com/flutter/slider/tooltip#tooltip-label-style

Please let us know if you need further assistance with this. 
 
Regards, 
Lakshmi R.
