### ISSUE TITLE
Wrong display 24 date in iPhone 6

### ISSUE THREAD

**Issue by Sergionius** [syncfusion/flutter-widgets#30]
Hello, thank you for great widgets, but I found issue in iPhone 6 with iOS 12.4.5, date 24 positioned horizontally(see screenshot)
code: 

`Widget _calendarWidget(BuildContext context) {
    return Center( 
      child: Container(
          child: SfDateRangePicker(
                        monthViewSettings: DateRangePickerMonthViewSettings(
                          firstDayOfWeek: 1,
                        ),
                        onSelectionChanged: _onSelectionChanged,
                        selectionMode: DateRangePickerSelectionMode.range,
                        minDate: DateTime.now(),
                        showNavigationArrow: false,
                        allowViewNavigation: true,
                        navigationDirection: DateRangePickerNavigationDirection.horizontal,
                        selectionShape: DateRangePickerSelectionShape.circle,
                        headerHeight: 60,
                        rangeSelectionColor: Colors.red.withOpacity(0.5),
                        endRangeSelectionColor: Colors.red,
                        startRangeSelectionColor: Colors.red,
                      ),
        ),);
  }`
How can I fix it ?
![IMG_38391BAD1977-1](https://user-images.githubusercontent.com/10280032/97396658-8f4bd600-18f8-11eb-8372-d4e243d0cbf0.jpeg)

**Comment by Indumathi1195R** [comment]
Hi @Sergionius ,

Thank you for contacting Syncfusion support.

We have found and fixed the reported issue “**24th date of the Flutter date picker displayed wrongly in iOS version 12.4**”. We will include the issue fix in our upcoming 2020 Volume 3 SP1 release which is expected to roll out by November 3, 2020, and let you know once release rollout. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @Sergionius,

We are glad to announce that our 2020 Volume 3 SP1 release is rolled out with the mentioned issue fix “**24th date of the Flutter date picker displayed wrongly in iOS version 12.4**”. Kindly update to the **latest version 18.3.47** for resolving this issue.

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v18.3.0.47?type=all#date-range-picker

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Indumathi R
