### ISSUE TITLE
syncfusion_flutter_pdfviewer 19.2.44-beta doen't work

### ISSUE THREAD

**Issue by spacekestrel** [syncfusion/flutter-widgets#300]
Tried  this package with  very basic implementation and getx  package on trying to get pdf file, but screen turns grey and thats it.
No errors, no nothing.

scaffold body looks like this:
```
GetBuilder<PdfMainController>(
            init: PdfMainController(),
            builder: (controller) => controller.pdfFile != null
                ? SfPdfViewer.file(controller.pdfFile)
                : Container()),
```
and function for getting pdf file like this:
```
              getBookLocationPath().then((path) {
                dynamic setPdfFile = new io.File(path);
                pdfMainController.setPdfFile(file: setPdfFile);
              }
```
getBookLocationPath function:
```
Future<String> getBookLocationPath() async => await FilePicker.platform
    .pickFiles()
    .then((FilePickerResult filePickerResult) async =>
        filePickerResult != null ? filePickerResult.files.first.path : null);
```

OS - windows, editor is vs code, emulator is pixel4 with latest sdn

**Comment by sarathkumar50** [comment]
Hi @spacekestrel ,
 
Greetings from Syncfusion.

On analyzing the given codes, we confirmed that the reported issue is a usage level issue. Once the PDF file is obtained, SfPdfViewer widget must be re-initiated. We have modified your codes and prepared a sample which 
can be downloaded from the following link.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app570538708.zip
 
You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!
 
Regards,
Sarath Kumar.

**Comment by spacekestrel** [comment]
> 
> 
> Hi @spacekestrel ,
> 
> Greetings from Syncfusion.
> 
> On analyzing the given codes, we confirmed that the reported issue is a usage level issue. Once the PDF file is obtained, SfPdfViewer widget must be re-initiated. We have modified your codes and prepared a sample which
> can be downloaded from the following link.
> https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app570538708.zip
> 
> You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!
> 
> Regards,
> Sarath Kumar.

Thanks, that worked for some reason.

**Comment by gneL1** [comment]
same issue, and I change
```dart
@override
  void initState() {
    pdfMainController = PdfMainController();
    getBookLocationPath().then((path) {
       File setPdfFile = File(path!);
       pdfMainController!.setPdfFile(file: setPdfFile);
       setState(() {});
     });
    super.initState();
  }
```
to
```dart
@override
  void initState() {
    pdfMainController = PdfMainController();
    Future.delayed(Duration(seconds: 1), (){
      pdfMainController!.setPdfFile(file: File(Api.externalStorageDirectory + "/test.pdf"));
      setState(() {

      });
    });
    super.initState();
  }
```
this also works well. it seems like a lag issue.

**Comment by gneL1** [comment]
> Hi @spacekestrel ,
> 
> Greetings from Syncfusion.
> 
> On analyzing the given codes, we confirmed that the reported issue is a usage level issue. Once the PDF file is obtained, SfPdfViewer widget must be re-initiated. We have modified your codes and prepared a sample which can be downloaded from the following link. https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app570538708.zip
> 
> You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!
> 
> Regards, Sarath Kumar.

According to FilePicker provide a cache file，I guess pdf file need to be put int a cache directory, so I do a this change
```dart
  @override
  void initState() {
    pdfMainController = PdfMainController();
    super.initState();
    initPdf();
  }
  Future<void> initPdf() async{
    File rawPdfFile = File(Api.externalStorageDirectory + "/test.pdf");

    /// put raw pdf file in a cache directory
    String cachePath = (await getTemporaryDirectory()).path + "/test.pdf";
    if(rawPdfFile.existsSync()){
      File cacheFile = await rawPdfFile.copy(cachePath);
      File pdfFile = File(cacheFile.path);
      pdfMainController!.setPdfFile(file: pdfFile);
      setState(() {});
    }
  }

```
Now it works well.
