### ISSUE TITLE
String height?

### ISSUE THREAD

**Issue by Lawati97** [syncfusion/flutter-widgets#302]
I am working on having the legends based on the ScreenSize but am not sure why the height takes a string is there a reason for it?

I ended doing this 
(screenSize.height * 0.03).toString()

**Comment by dharanidharandharmasivam** [comment]
Hi @Lawati97 ,

Greetings from Syncfusion. We would like to let you know that, in order to consider both pixel value and percentage value, we are having the **height** property as a string type. Find the code to accomplish this

**Code snippet for pixel:**

  ```
legend: Legend(
                 isVisible: true,
                 height: '10'
             )
```
Code snippet for percentage:
 ```
legend: Legend(
                 isVisible: true,
                 height: '15%'
             )
```

Thanks,
Dharani.

**Comment by Lawati97** [comment]
@dharanidharandharmasivam Perfect Thank you

**Comment by petoknm** [comment]
```abstract class Size {
  const Size();

  double resolve(double totalSize);

  factory Size.pixels(double pixels) => PixelSize(pixels);
  factory Size.percentage(double percentage) => PercentageSize(percentage);
}

class PixelSize extends Size {
  final double pixels;

  const PixelSize(this.pixels);

  @override
  double resolve(double _) => pixels;
}

class PercentageSize extends Size {
  final double percentage;

  const PercentageSize(this.percentage);

  @override
  double resolve(double totalSize) => totalSize * percentage;
}

void usage() {
  final sizes = [
    Size.pixels(10),
    Size.percentage(0.1),
  ];

  for (final s in sizes) {
    print(s.resolve(100));
  }
}
```

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Thank you for providing an example of code. We would not update the existing legend feature because it may result in breaking changes, but we will investigate this scenario in future implementation.

Thanks,
Dharanitharan. P
