### ISSUE TITLE
Add support for time axis (`Duration`, not `DateTime`)

### ISSUE THREAD

**Issue by petoknm** [syncfusion/flutter-widgets#304]
I want to show a chart with x axis being time in the range from 0sec to few hours and I didn't find a way to do it. I see that there is a `DateTimeAxis` and with that I cannot get it to format time appropriately properly even if I for instance change all `Duration`s to `DateTime`s via `DateTime(2021).add(duration)`.

Display format (`[h:]m:s`):
0:00 - 59:59
1:00:00 - 9:59:59

**Comment by Dharanipalani** [comment]
Hi @petoknm,

Thanks for the interest in our Flutter charts. We have investigated your query and like to say that you can use the [intervalType](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/intervalType.html) as hours or minutes as per your requirement and you can format the date using the [dateFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/dateFormat.html) property of the axis. To know more information about this, refer to the help document below. 

[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals)
[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#formatting-the-labels-1](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#formatting-the-labels-1)

Please revert us if you need further assistance on this.

Thanks,
Dharanitharan. P
