### ISSUE TITLE
Tooltip not shown on setState

### ISSUE THREAD

**Issue by monolidth** [syncfusion/flutter-widgets#308]
Hello,
thanks for this awesome and well-tested chart library. 

I tried to add `onTrackballPositionChanging` listener to my `SfCartesianChart`. I want to achieve that if the position is changed, the new sum is shown in the text widget.

Therefore, I created a setter for the sum, which calls setState(). However, the tooltip is not shown anymore. Here is a short snippet.

## Snippet
```dart
Column(children: [
Text(sum)
SfCartesianChart(
  ...
   onTrackballPositionChanging: (TrackballArgs args) {
        if(args.chartPointInfo.chartDataPoint != null) {
          sum = args.chartPointInfo.chartDataPoint!.y; // calls set state
        }
      },
  
  ), 
],
);
```

Is there any workaround for this? How could I achive this?

Kindly regards,
William

**Comment by Dharanipalani** [comment]
Hi @monolidth,

Thanks for the interest in our Flutter charts. We have analzyed your query and the code and like to tell that the whole chart is get rebuild when calling the setstate in the trackball's callback and hence the trackball gets hides. So, we suggest you use the separate stateful widget for the text and refresh that corresponding state will resolve your issue. We have attached the sample for your reference kindly make use of it. Please revert us if you need any further assistance on this.

Sample: [I335388_trackball_text.zip](https://github.com/syncfusion/flutter-widgets/files/6792685/I335388_trackball_text.zip)

Thanks,
Dharanitharan. P

**Comment by monolidth** [comment]
Many thanks @Dharanipalani. It worked. I forgot to register the widget. Is there any chance to buy you a coffee?
