### ISSUE TITLE
How to customize Y Axis value?

### ISSUE THREAD

**Issue by yusriltakeuchi** [syncfusion/flutter-widgets#309]
Hi, can i ask how to customize format Y Axis value?
For example if Y Axis value is Rp600.000, i want to change to Rp600K
or if value Rp2.00.000 i want to change to Rp2Jt

<img width="157" alt="Screen Shot 2021-07-11 at 14 42 32" src="https://user-images.githubusercontent.com/10339660/125186751-64bb6680-e256-11eb-8af7-ae9a1aa4742a.png">

This is my code

```dart
     return Container(
          height: setHeight(400),
          child: SfCartesianChart(
            borderColor: Colors.transparent,
            enableAxisAnimation: true,
            plotAreaBorderColor: Colors.transparent,
            primaryYAxis: NumericAxis(
              numberFormat: NumberFormat.simpleCurrency(locale: "id", decimalDigits: 0)
            ),
            primaryXAxis: CategoryAxis(
              majorGridLines: MajorGridLines(color: graySoftColor),
              majorTickLines: MajorTickLines(color: Colors.transparent),
            ),
            tooltipBehavior: TooltipBehavior(
              enable: true,
            ),
            series: <ChartSeries>[
              SplineAreaSeries<StatisticsModel, String>(
                dataSource: reportProv.reportStatistics!.expenses!,
                borderColor: redColor,
                borderWidth: 2,
                markerSettings: MarkerSettings(
                  isVisible: true,
                  color: redColor
                ),
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    redColor,
                    redColor.withOpacity(0.1)
                  ]
                ),
                xValueMapper: (StatisticsModel sales, _) => sales.title,
                yValueMapper: (StatisticsModel sales, _) => sales.value,
                name: "Pengeluaran"
              ),
              SplineAreaSeries<StatisticsModel, String>(
                dataSource: reportProv.reportStatistics!.incomes!,
                borderColor: greenColor,
                borderWidth: 2,
                markerSettings: MarkerSettings(
                  isVisible: true,
                  color: greenColor,
                ),
                gradient: LinearGradient(
                  begin: Alignment.topCenter,
                  end: Alignment.bottomCenter,
                  colors: [
                    greenColor,
                    greenColor.withOpacity(0.1)
                  ]
                ),
                xValueMapper: (StatisticsModel sales, _) => sales.title,
                yValueMapper: (StatisticsModel sales, _) => sales.value,
                name: "Pemasukan"
              )
            ]
          ),
        );
```

**Comment by Dharanipalani** [comment]
Hi @yusriltakeuchi,

Thanks for the interest in our Flutter charts. We have analyzed your requirement and suggest using the [labelFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/labelFormat.html) property in the respective axis is used to append any symbol to the labels, please see the [support document](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#formatting-the-labels) for more details. You may also use the [numberFormat](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/numberFormat.html) property to format, as seen in the following kb. we also recommend using the [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/axisLabelFormatter.html) callback to customize the label as like in the following kb. 

[https://www.syncfusion.com/kb/11678/how-to-customize-the-axis-labels-using-callback-events-sfcartesianchart](https://www.syncfusion.com/kb/11678/how-to-customize-the-axis-labels-using-callback-events-sfcartesianchart) 
[https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart ](https://www.syncfusion.com/kb/11519/how-to-apply-the-currency-format-to-the-axis-labels-sfcartesianchart )

Please revert us if you need any further assistance on this.
 
Thanks,
Dharanitharan. P
