### ISSUE TITLE
[SFDataGrid] [Web] - Horizontal scrollbar not visible if rows exceed screen size

### ISSUE THREAD

**Issue by Abhijit-Revamp** [syncfusion/flutter-widgets#312]
If the SfDataGrid has rows more than the available height, vertical scrollbar is visible. However, the HORIZONTAL scrollbar is NOT visible.

If you scroll down to last row, then scrollbar is visible.

See attached PIC1 and PIC2

![image](https://user-images.githubusercontent.com/44320018/125424051-1bb86aa5-df4d-4462-9013-6c96eef558a3.png)
![image](https://user-images.githubusercontent.com/44320018/125424324-2dc5d4df-0a1d-4ad3-be34-d670fa9bf919.png)

**Comment by Abhijit-Revamp** [comment]
This is a BLOCKING issue on DESKTOPs that do not have trackpad.
It's impossible to scroll horizontally with mouse.

**Comment by RenugaSadagoban98** [comment]
Hi @Abhijit-Revamp , 
 
Greetings from Syncfusion.   
 
By default, framework itself has the same behavior. i.e.  If we have used two Scrollbar widgets to enable two way scrolling i.e. both horizontal and vertical scrolling, then it will show either vertical or horizontal scrollbar. Both the scrollbars will be shown only if the max scroll extent is reached. In SfDataGrid, we have used two Scrollbar widgets to enable two way scrolling, that why it behaves like framework behavior.

We have reported this issue to framework. For further details, you can refer to the following link,

Link: https://github.com/flutter/flutter/issues/86428

Please let us know if you require any further assistance.

Regards, 
Renuga devi S
