### ISSUE TITLE
[SfDataGrid] How to get access to SfDataGridTheme?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#313]
I have imported 

import 'package:syncfusion_flutter_datagrid/datagrid.dart';

and want to wrap the SfDataGrid in a Theme but 'SfDataGridTheme' isn't defined. Do I have to import another package?

**Comment by Wizzel1** [comment]
I am using version 19.2.47-beta

**Comment by RenugaSadagoban98** [comment]
Hi Customer,  
Greetings from Syncfusion. 

Yes. You can access the SfDataGridTheme by importing the following package in your application,

import 'package:syncfusion_flutter_core/theme.dart';

Please let us know if you require any further assistance.

Regards,
Renuga devi

**Comment by Wizzel1** [comment]
Yes that worked. May I suggest you add this import statement to the documentation? 

From this page https://help.syncfusion.com/flutter/datagrid/styles there is no way to find out how to get access to the ThemeData. 

Thanks

**Comment by RenugaSadagoban98** [comment]
Hi, 

Thanks for your suggesstion.

 

We will add the import details in our UG document. Please let us know if you require any other assistance. We will be happy to assist you.

 

Regards,

Renuga devi
