### ISSUE TITLE
SfSliderTheme don't works

### ISSUE THREAD

**Issue by Hekhy** [syncfusion/flutter-widgets#316]
As the title says this widget does not work for me, just use the example[ here](https://help.syncfusion.com/flutter/slider/track#track-color), but it does not work.

Neither does SfTheme.

I don't know what is happening but I would appreciate the help.

I send all the possible images that can be of help.

![image](https://user-images.githubusercontent.com/70041483/125711723-7c6b5fe3-e8c6-4ee9-bff4-229691c91c6b.png)

![image](https://user-images.githubusercontent.com/70041483/125711920-ce51d833-d46f-48ac-871e-57443000a905.png)

![image](https://user-images.githubusercontent.com/70041483/125711993-fa935312-4208-4212-adbf-b9d4c33431a7.png)

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Hekhy,

Greetings from Syncfusion support.

We have checked the shared images and you have missed to import the theme.dart library from the core package. Kindly import this library to use SfSliderThemeData properties.

```
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';
```

![image](https://user-images.githubusercontent.com/47354659/125735777-a1303c8f-dd75-4120-a817-2e43e3165a41.png)

https://help.syncfusion.com/flutter/slider/track#track-color   

Please refer the above documentation link to know more about the slider configuration. Kindly let us know if you need any other further assistance.

Regards,
Lakshmi R.

**Comment by Hekhy** [comment]
You're right, it's my problem for rushing and not reading this note.

![dgs](https://user-images.githubusercontent.com/70041483/125767027-4a94d25f-5bcf-4d02-86bd-ae9d342a1541.png)

You can close it, sorry xD

Now it is working well thanks.

![image](https://user-images.githubusercontent.com/70041483/125768030-43a8bda1-d23a-41f8-b17d-53fdfae0751f.png)
