### ISSUE TITLE
[syncfusion_flutter_datepicker] [Feature Request] SelectedCellDecoration

### ISSUE THREAD

**Issue by umutarpat** [syncfusion/flutter-widgets#32]
We have todayCellDecoration,cellDecoration,blackoutDatesDecoration etc. but we dont have SelectedCellDecoration.
I want to be able to change decoration of SelectedCells and cells Between startRange,endRange.

**Comment by Indumathi1195R** [comment]
Hi @umutarpat ,

Based on the provided information, we have checked your requirement “**Selected Cell decoration and selected range decoration in picker**”. We have already logged the feature request for “Custom builder support for month cells of date range picker”. Using this above feature, you can achieve your requirement. We will implement this feature in our upcoming 2020 Volume 4 release, which is expected to roll out by the end of December 2020, and let you know once the release rolled out. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below feedback link. 

**Link:** https://www.syncfusion.com/feedback/18537/providing-a-custom-builder-support-for-cells-of-the-flutter-date-range-picker

As of now, you can refer the following KB document for selected date decoration.

**KB link:** https://www.syncfusion.com/kb/11441/how-to-customize-the-selected-month-cell-in-the-flutter-date-range-picker-sfdaterangepicker

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi , 
 
We are glad to announce that our Essential Studio 2020 Volume 4 release v18.4.30-beta is rolled with the mentioned feature “**Providing a custom builder support for cells of the Flutter Date range picker (SfDateRangePicker)**”. Kindly update to the latest version for this feature. Please find the latest version from the following pub link. 
 
**Latest version link:** https://pub.dev/packages/syncfusion_flutter_datepicker/versions 
 
**Changelog link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog 
 
**UG link:** https://help.syncfusion.com/flutter/daterangepicker/builders 
 
**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v18.4.0.30?type=all#date-range-picker 
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
 
Regards,           
Indumathi R
