### ISSUE TITLE
 How to add label for currentValue without interval 

### ISSUE THREAD

**Issue by Archsx** [syncfusion/flutter-widgets#320]
Hi, I'm using SfSlider and I get a problem that the range is so wild. for example, min is 0 and max is 5000 . and the stepSize is 10. I want to put a label for the current value only. so, How can I solve the problem?

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Archsx,

Greetings from Syncfusion support.

We can achieve the requirement by,
1.	Using thumbIcon. Refer https://help.syncfusion.com/flutter/slider/thumb-and-overlay#thumb-icon for more details.
2.	Drawing in our own using SfThumbShape. We have shared the code snippets for your reference below.

```
class SliderLabelCustomSample extends StatefulWidget {
  @override
  _SliderLabelCustomSampleState createState() =>
      _SliderLabelCustomSampleState();
}

class _SliderLabelCustomSampleState extends State<SliderLabelCustomSample> {
  double _value = 40;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Slider - Custom Label'),
      ),
      body: SfSlider(
        min: 0,
        max: 5000,
        stepSize: 10,
        thumbShape: _CustomThumb(MediaQuery.of(context).textScaleFactor),
        value: _value,
        onChanged: (dynamic newValue) {
          setState(() {
            _value = newValue;
          });
        },
      ),
    );
  }
}

class _CustomThumb extends SfThumbShape {
  _CustomThumb(this.textScaleFactor)
      : _textSpan = TextSpan(),
        _textPainter = TextPainter();
  final double textScaleFactor;
  TextPainter _textPainter;
  TextSpan _textSpan;

  /// Returns the size based on the values passed to it.
  @override
  Size getPreferredSize(SfSliderThemeData themeData) {
    // To avoid overlapping of label from next widget, we had considered the label size also.
    return Size.fromRadius((textScaleFactor * 25) + themeData.thumbRadius);
  }

  @override
  void paint(PaintingContext context, Offset center,
      {required RenderBox parentBox,
        required RenderBox? child,
        required SfSliderThemeData themeData,
        SfRangeValues? currentValues,
        dynamic currentValue,
        required Paint? paint,
        required Animation<double> enableAnimation,
        required TextDirection textDirection,
        required SfThumb? thumb}) {
    paint ??= Paint()..color = themeData.thumbColor!;
    context.canvas.drawCircle(center, themeData.thumbRadius, paint);
    _textSpan = TextSpan(
      text: currentValue.toInt().toString(),
      style: TextStyle(color: Colors.black),
    );
    _textPainter
      ..text = _textSpan
      ..textDirection = textDirection
      ..textScaleFactor = textScaleFactor
      ..layout()
      ..paint(
        context.canvas,
        // To show the label below the thumb, we had internally used a
        // constant value 25.
        Offset(center.dx - _textPainter.width / 2,
            center.dy + (textScaleFactor * 25) - _textPainter.height / 2),
      );
  }
}
```

We hope that the above solution will resolve your problem, kindly let us know if you need further assistance with this.

Regards,
Lakshmi R.

**Comment by Archsx** [comment]
> Hi Archsx,
> 
> Greetings from Syncfusion support.
> 
> We can achieve the requirement by,
> 
> 1. Using thumbIcon. Refer https://help.syncfusion.com/flutter/slider/thumb-and-overlay#thumb-icon for more details.
> 2. Drawing in our own using SfThumbShape. We have shared the code snippets for your reference below.
> 
> ```
> class SliderLabelCustomSample extends StatefulWidget {
>   @override
>   _SliderLabelCustomSampleState createState() =>
>       _SliderLabelCustomSampleState();
> }
> 
> class _SliderLabelCustomSampleState extends State<SliderLabelCustomSample> {
>   double _value = 40;
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: Text('Slider - Custom Label'),
>       ),
>       body: SfSlider(
>         min: 0,
>         max: 5000,
>         stepSize: 10,
>         thumbShape: _CustomThumb(MediaQuery.of(context).textScaleFactor),
>         value: _value,
>         onChanged: (dynamic newValue) {
>           setState(() {
>             _value = newValue;
>           });
>         },
>       ),
>     );
>   }
> }
> 
> class _CustomThumb extends SfThumbShape {
>   _CustomThumb(this.textScaleFactor)
>       : _textSpan = TextSpan(),
>         _textPainter = TextPainter();
>   final double textScaleFactor;
>   TextPainter _textPainter;
>   TextSpan _textSpan;
> 
>   /// Returns the size based on the values passed to it.
>   @override
>   Size getPreferredSize(SfSliderThemeData themeData) {
>     // Considered label size and its offset along with thumb radius to avoid the label get overlapping with adjacent widget.
>     return Size.fromRadius((textScaleFactor * 25) + themeData.thumbRadius);
>   }
> 
>   @override
>   void paint(PaintingContext context, Offset center,
>       {required RenderBox parentBox,
>         required RenderBox? child,
>         required SfSliderThemeData themeData,
>         SfRangeValues? currentValues,
>         dynamic currentValue,
>         required Paint? paint,
>         required Animation<double> enableAnimation,
>         required TextDirection textDirection,
>         required SfThumb? thumb}) {
>     paint ??= Paint()..color = themeData.thumbColor!;
>     context.canvas.drawCircle(center, themeData.thumbRadius, paint);
>     _textSpan = TextSpan(
>       text: currentValue.toInt().toString(),
>       style: TextStyle(color: Colors.black),
>     );
>     _textPainter
>       ..text = _textSpan
>       ..textDirection = textDirection
>       ..textScaleFactor = textScaleFactor
>       ..layout()
>       ..paint(
>         context.canvas,
>         // To show the label below the thumb, we had internally used a
>         // constant value 25.
>         Offset(center.dx - _textPainter.width / 2,
>             center.dy + (textScaleFactor * 25) - _textPainter.height / 2),
>       );
>   }
> }
> ```
> 
> We hope that the above solution will resolve your problem, kindly let us know if you need further assistance with this.
> 
> Regards,
> Lakshmi R.

Hi, It's my fault that I confused the slider with rangeSlider, It should be **rangeSlider.**  I  try the code

```
class RangeSliderLabelCustomSample extends StatefulWidget {
  @override
  _RangeSliderLabelCustomSampleState createState() =>
      _RangeSliderLabelCustomSampleState();
}

class _RangeSliderLabelCustomSampleState extends State<RangeSliderLabelCustomSample> {

  SfRangeValues _values = SfRangeValues(0.0, 5000.0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('RangeSlider - Custom Label'),
      ),
      body: SfRangeSlider(
        min: 0.0,
        max: 5000.0,
        stepSize: 10,
        values:_values,
        thumbShape: _CustomThumb(MediaQuery.of(context).textScaleFactor),
        onChanged: (dynamic newValues) {
          setState(() {
            _values = newValues;
          });
        },
      ),
    );
  }
}

class _CustomThumb extends SfThumbShape {
  _CustomThumb(this.textScaleFactor)
      : _textSpan = TextSpan(),
        _textPainter = TextPainter();
  final double textScaleFactor;
  TextPainter _textPainter;
  TextSpan _textSpan;

  @override
  Size getPreferredSize(SfSliderThemeData themeData) {
    return Size.fromRadius((textScaleFactor * 25) + themeData.thumbRadius);
  }

  @override
  void paint(PaintingContext context, Offset center,
      {required RenderBox parentBox,
      required RenderBox? child,
      required SfSliderThemeData themeData,
      SfRangeValues? currentValues,
      dynamic currentValue,
      required Paint? paint,
      required Animation<double> enableAnimation,
      required TextDirection textDirection,
      required SfThumb? thumb}) {
    paint ??= Paint()..color = themeData.thumbColor!;
    context.canvas.drawCircle(center, themeData.thumbRadius, paint);
    _textSpan = TextSpan(
      text: currentValue.toInt().toString(),
      style: TextStyle(color: Colors.black),
    );
    _textPainter
      ..text = _textSpan
      ..textDirection = textDirection
      ..textScaleFactor = textScaleFactor
      ..layout()
      ..paint(
        context.canvas,
        Offset(center.dx - _textPainter.width / 2,
            center.dy + (textScaleFactor * 25) - _textPainter.height / 2),
      );
  }
}

```
I thought it would work because slider and rangeSlider lable is similar. But I got error: " The method 'toInt' was called on null. " , any suggestions?

**Comment by PraveenGopalsamy** [comment]
Hi @Archsx,

The [SfThumbShape ](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfThumbShape-class.html) class is common for Slider, RangeSlider and RangeSelector widgets. The **currentValue** parameter is applicable for Slider and **currentValues** parameter is for RangeSlider and RangeSelector widgets. 

We have modified the codes as per the requirement,
```
class RangeSliderLabelCustomSample extends StatefulWidget {
  @override
  _RangeSliderLabelCustomSampleState createState() =>
      _RangeSliderLabelCustomSampleState();
}

class _RangeSliderLabelCustomSampleState
    extends State<RangeSliderLabelCustomSample> {
  SfRangeValues _values = SfRangeValues(1500.0, 3000.0);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Range Slider - Custom Label'),
      ),
      body: SfRangeSlider(
        min: 0,
        max: 5000,
        stepSize: 10,
        thumbShape: _CustomThumb(
            textScaleFactor: MediaQuery.of(context).textScaleFactor,
            values: _values),
        values: _values,
        onChanged: (dynamic newValue) {
          setState(() {
            _values = newValue;
          });
        },
      ),
    );
  }
}

class _CustomThumb extends SfThumbShape {
  _CustomThumb({required this.textScaleFactor, required this.values})
      : _textSpan = TextSpan(),
        _textPainter = TextPainter();
  final double textScaleFactor;
  final SfRangeValues values;
  TextPainter _textPainter;
  TextSpan _textSpan;
  final double verticalSpacing = 5.0;

  @override
  Size getPreferredSize(SfSliderThemeData themeData) {
    _textSpan = TextSpan(text: values.start.toInt().toString());
    _textPainter
      ..text = _textSpan
      ..textDirection = TextDirection.ltr
      ..textScaleFactor = textScaleFactor
      ..layout();
    // Considered label height along with thumb radius to avoid the
    // label get overlapping with adjacent widget.
    return Size(themeData.thumbRadius * 2,
        (themeData.thumbRadius + _textPainter.height + verticalSpacing) * 2);
  }

  @override
  void paint(PaintingContext context, Offset center,
      {required RenderBox parentBox,
      required RenderBox? child,
      required SfSliderThemeData themeData,
      SfRangeValues? currentValues,
      dynamic currentValue,
      required Paint? paint,
      required Animation<double> enableAnimation,
      required TextDirection textDirection,
      required SfThumb? thumb}) {
    paint ??= Paint()..color = themeData.thumbColor!;
    context.canvas.drawCircle(center, themeData.thumbRadius, paint);
    String text = currentValues!.end.toInt().toString();
    if (thumb != null) {
      text = (thumb == SfThumb.start ? currentValues.start : currentValues.end)
          .toInt()
          .toString();
    }
    _textSpan = TextSpan(
      text: text,
      style: TextStyle(color: Colors.black),
    );
    _textPainter
      ..text = _textSpan
      ..textDirection = textDirection
      ..textScaleFactor = textScaleFactor
      ..layout()
      ..paint(
        context.canvas,
        // To show the label below the thumb, we had added it with thumb radius
        // and constant vertical spacing.
        Offset(center.dx - _textPainter.width / 2,
            center.dy + verticalSpacing + themeData.thumbRadius),
      );
  }
}
```

We hope that the above solution will resolve your problem, kindly let us know if you need further assistance with this.

Regards,
Praveen G.

**Comment by Archsx** [comment]
thank you so much! and I think you could add the demo to docs. I'm new to flutter so  I will read the code again to learn why it works. thanks again !
