### ISSUE TITLE
[PDF]Page Flicker

### ISSUE THREAD

**Issue by zartzhao** [syncfusion/flutter-widgets#321]
There is a page that needs to show a large resolution PDF file.  The PDF only has 2 pages.
When the PDF is initially displayed, two pages can be displayed in the window. At this time, the window keeps flashing.
If you double-click the screen and the PDF file is enlarged, it will not flash.
If the PDF is minimized, it starts flashing again.

**Comment by dillibabun** [comment]
Hi @zartzhao 

This is a known behavior in the SfPdfViewer widget. Whenever window size is changed, we have rendered the PDF page and grey area based on the window size. This change will provide more responsiveness for the application and corrects the PDF layout level issues.

Regards,
Dilli babu.
