### ISSUE TITLE
Can i show divisor on SfSlider Only on start value and last value?

### ISSUE THREAD

**Issue by skripsimu** [syncfusion/flutter-widgets#326]

**Comment by LakshmiRadhaKrishnan** [comment]
Hi,  
  
You can show dividers only for the first and last labels using the dividerShape property in the SfSlider. We have added code snippet for your reference. 

https://help.syncfusion.com/flutter/slider/shapes#divider-shape   

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/divider_customization-420860173

**Screenshot:**

![divider_customization](https://user-images.githubusercontent.com/47354659/127144169-5c038c9f-b5a5-42f7-a0a3-5e52870f0326.png)  

**Code Snippet:**
```
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  double _min = 2.0;
  double _max = 10.0;
  double _value = 6.0;
  double _interval = 2;
  DateTime _dateMin = DateTime(2010, 01, 01);
  DateTime _dateMax = DateTime(2016, 01, 01);
  DateTime _dateValue = DateTime(2013, 01, 01);
  double _dateInterval = 1;
  DateIntervalType _intervalType = DateIntervalType.years;
  int _initialCount = -1;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SfSliderTheme(
              data: SfSliderThemeData(activeDividerRadius: 7),
              child: SfSlider(
                min: _min,
                max: _max,
                value: _value,
                interval: _interval,
                showDividers: true,
                showTicks: true,
                showLabels: true,
                dividerShape: _DividerShape(_initialCount, (_max - _min) / _interval),
                onChanged: (dynamic newValue) {
                  setState(() {
                    _value = newValue;
                  });
                },
              ),
            ),
            SizedBox(height: 30),
            SfSliderTheme(
              data: SfSliderThemeData(activeDividerRadius: 7),
              child: SfSlider(
                min: _dateMin,
                max: _dateMax,
                value: _dateValue,
                interval: _dateInterval,
                dateIntervalType: _intervalType,
                showDividers: true,
                showTicks: true,
                showLabels: true,
                dateFormat: DateFormat.y(),
                dividerShape: _DividerShape(_initialCount, _getDateTimeDifference(_dateMin, _dateMax, _intervalType).toDouble() / _dateInterval),
                onChanged: (dynamic newValue) {
                  setState(() {
                    _dateValue = newValue;
                  });
                },
              ),
            ),
          ],
        ),
    );
  }
}

class _DividerShape extends SfDividerShape {
  _DividerShape(this.count, this.division);
  final double division;
  int count;

  @override
  void paint(PaintingContext context, Offset center, Offset? thumbCenter,
      Offset? startThumbCenter, Offset? endThumbCenter,
      {required RenderBox parentBox,
        required SfSliderThemeData themeData,
        SfRangeValues? currentValues,
        dynamic currentValue,
        required Paint? paint,
        required Animation<double> enableAnimation,
        required TextDirection textDirection}) {
    count++;
    if (count > division) {
      count = 0;
    }
    if (count == 0  || count == division) {
      context.canvas.drawCircle(center,
          themeData.activeDividerRadius!,
          Paint()
            ..isAntiAlias = true
            ..style = PaintingStyle.fill
            ..color = themeData.activeTrackColor!);
    }
  }
}

int _getDateTimeDifference(
    DateTime min, DateTime max, DateIntervalType? intervalType) {
  assert(intervalType != null);
  final Duration diff = max.difference(min);
  switch (intervalType!) {
    case DateIntervalType.months:
      return ((max.year - min.year) * DateTime.monthsPerYear) +
          max.month -
          min.month;
    case DateIntervalType.days:
      return diff.inDays;
    case DateIntervalType.hours:
      return diff.inHours;
    case DateIntervalType.minutes:
      return diff.inMinutes;
    case DateIntervalType.seconds:
      return diff.inSeconds;
    case DateIntervalType.years:
      return max.year - min.year;
  }
```


Kindly let us know if you need further assistance with this.

Regards,  
Lakshmi R.

**Comment by LakshmiRadhaKrishnan** [comment]
Hi skripsimu,  
  
We would like to inform you that the dividers are drawn based on the value of interval property in SfSlider. You can only show dividers at minimum and maximum positions by providing the interval value according to the min and max values. We have added code snippet for both numeric and date time slider. 

For the date time slider, the dividers are drawn based on both ‘interval’ and ‘dateIntervalType’ properties. Here dateIntervalType is set to DateIntervalType.years, so calculated interval value based on the year difference. 

**Code Snippet:**
```
class _MyHomePageState extends State<MyHomePage> {
  double _min = 2;
  double _max = 10;
  DateTime _dateMin = DateTime(2010, 01, 01);
  DateTime _dateMax = DateTime(2016, 01, 01);
  double _value = 6.0;
  DateTime _dateValue = DateTime(2013, 01, 01);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
          children: [
            SfSliderTheme(
              data: SfSliderThemeData(activeDividerRadius: 6, inactiveDividerRadius: 6),
              child: SfSlider(
                min: _min,
                max: _max,
                value: _value,
                interval: _max - _min,
                showDividers: true,
                showTicks: true,
                showLabels: true,
                onChanged: (dynamic newValue) {
                  setState(() {
                    _value = newValue;
                  });
                },
              ),
            ),
            SizedBox(height: 30),
            SfSliderTheme(
              data: SfSliderThemeData(activeDividerRadius: 6, inactiveDividerRadius: 6),
              child: SfSlider(
                min: _dateMin,
                max: _dateMax,
                value: _dateValue,
                interval: (_dateMax.year - _dateMin.year).toDouble(),
                dateIntervalType: DateIntervalType.years,
                showDividers: true,
                showTicks: true,
                showLabels: true,
                dateFormat: DateFormat.y(),
                onChanged: (dynamic newValue) {
                  setState(() {
                    _dateValue = newValue;
                  });
                },
              ),
            ),
          ],
        ),
    );
  }
}
```

![divider_without_color_properties](https://user-images.githubusercontent.com/47354659/127256369-ad43c74c-e1e4-4903-a647-ecd32d3d0107.png)

Kindly let us know if you need further assistance with this.

Regards,  
Lakshmi R.

**Comment by skripsimu** [comment]
> Hi skripsimu,
> 
> We would like to inform you that the dividers are drawn based on the value of interval property in SfSlider. You can only show dividers at minimum and maximum positions by providing the interval value according to the min and max values. We have added code snippet for both numeric and date time slider.
> 
> For the date time slider, the dividers are drawn based on both ‘interval’ and ‘dateIntervalType’ properties. Here dateIntervalType is set to DateIntervalType.years, so calculated interval value based on the year difference.
> 
> **Code Snippet:**
> 
> ```
> class _MyHomePageState extends State<MyHomePage> {
>   double _min = 2;
>   double _max = 10;
>   DateTime _dateMin = DateTime(2010, 01, 01);
>   DateTime _dateMax = DateTime(2016, 01, 01);
>   double _value = 6.0;
>   DateTime _dateValue = DateTime(2013, 01, 01);
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: Column(
>         mainAxisAlignment: MainAxisAlignment.center,
>           children: [
>             SfSliderTheme(
>               data: SfSliderThemeData(activeDividerRadius: 6, inactiveDividerRadius: 6),
>               child: SfSlider(
>                 min: _min,
>                 max: _max,
>                 value: _value,
>                 interval: _max - _min,
>                 showDividers: true,
>                 showTicks: true,
>                 showLabels: true,
>                 onChanged: (dynamic newValue) {
>                   setState(() {
>                     _value = newValue;
>                   });
>                 },
>               ),
>             ),
>             SizedBox(height: 30),
>             SfSliderTheme(
>               data: SfSliderThemeData(activeDividerRadius: 6, inactiveDividerRadius: 6),
>               child: SfSlider(
>                 min: _dateMin,
>                 max: _dateMax,
>                 value: _dateValue,
>                 interval: (_dateMax.year - _dateMin.year).toDouble(),
>                 dateIntervalType: DateIntervalType.years,
>                 showDividers: true,
>                 showTicks: true,
>                 showLabels: true,
>                 dateFormat: DateFormat.y(),
>                 onChanged: (dynamic newValue) {
>                   setState(() {
>                     _dateValue = newValue;
>                   });
>                 },
>               ),
>             ),
>           ],
>         ),
>     );
>   }
> }
> ```
> 
> ![divider_without_color_properties](https://user-images.githubusercontent.com/47354659/127256369-ad43c74c-e1e4-4903-a647-ecd32d3d0107.png)
> 
> Kindly let us know if you need further assistance with this.
> 
> Regards,
> Lakshmi R.

Thanks @LakshmiRadhaKrishnan , this was solved by setting the value to interval
