### ISSUE TITLE
Importing the graph in pdf

### ISSUE THREAD

**Issue by sujeetyadav01** [syncfusion/flutter-widgets#328]
I want to export the static graph view in the PDF format but it gives error that graph is not widget type. I was using "pdf" library. Is there a way to to export the graph in pdf?

**Comment by Anand3595** [comment]
Hi Sujeet,

Thanks for contacting Syncfusion support.

We don’t have direct support to draw the Flutter widget to PDF, we can convert the Flutter widget into image and draw the image using our library. So we suggest you to draw the graph content by exporting it to image and add to the PDF document as follows.
https://www.syncfusion.com/kb/11965/how-to-convert-image-to-pdf-in-syncfusion-flutter-pdf-library.

We request you to provide the following details to reproduce the reported issue in our end.
-	Complete stack trace
-	Code example to reproduce
-	Flutter doctor report

Regards,
Anand Panchamoorthi
