### ISSUE TITLE
[SfCircularChart] [Feature Request]  DoughnutSeries Decoration

### ISSUE THREAD

**Issue by umutarpat** [syncfusion/flutter-widgets#33]
I want to be able to change decoration of DoughnutSeries. We currently can change color,text and percantage. I need to be able to add boxshadow and gradient into chart.

```
 final List<ChartData> chartData = [
    ChartData('LIVE', 25, Color(0x0ff7262E4)),
    ChartData('MESAJ', 38, Color(0x0ffdce1e8)),
    ChartData('VIDEO', 54, Color(0x0ffADB3FF)),
  ];
DoughnutSeries<ChartData, String>(
          dataSource: chartData,
          
          pointColorMapper: (ChartData data, _) => data.color,
          xValueMapper: (ChartData data, _) => data.name,
          yValueMapper: (ChartData data, _) => data.percentage,
          dataLabelMapper: (ChartData data, _) => data.name,)
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @umutarpat,

Greetings from Syncfusion. We have analyzed your scenario at our end and we are sorry that currently, we do not have support to add gradient and shadow in circular charts. However, we will consider this as a feature request and we have already created a feature request for it in our feedback portal. We will plan and include the requested feature in any of our upcoming releases yet to come. You can also track the status of the feature using the below feedback link.
https://www.syncfusion.com/feedback/8229

Regards,
Sriram Kiran
