### ISSUE TITLE
[Syncfusion flutter pdf] [Help] Images to pdf without changing aspect ratio and same width for all pages

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#330]
Hello, I'm looking for help in achieving a pdf with images of different sizes without losing their aspect ratio and also keeping the pdf page's width of the same size.

For example, I have images of dimensions like these- 

> I/flutter (10720): Img 1 - width: 960.0, height: 1280.0
I/flutter (10720): Img 2 - width: 1280.0, height: 874.0
I/flutter (10720): Img 3 - width: 1280.0, height: 853.0
I/flutter (10720): Img 4 - width: 1280.0, height: 960.0
I/flutter (10720): Img 5 - width: 960.0, height: 1280.0
I/flutter (10720): Img 6 - width: 1280.0, height: 911.0
I/flutter (10720): Img 7 - width: 851.0, height: 1280.0

As you can see that all have different dimensions and so when converting I was getting some pdf with stretched or compressed images so to tackle that I got image dimensions through some code and then added those values to this ```document.pageSettings.size = Size(width, height);```  when creating and adding pages. With this, I was getting the correct aspect ratio for images in pdf but the result pdf had different sizes of pages as expected. The result pdf sample - [Output.pdf](https://github.com/syncfusion/flutter-widgets/files/6912713/Output.pdf)

Now the next thing would be to find a way to get a pdf with the same width or height without distorting the aspect ratio but I failed to do so.
This is the type of pdf I would want - [Image to pdf 2021-08-01 16_45_11.pdf](https://github.com/syncfusion/flutter-widgets/files/6912739/Image.to.pdf.2021-08-01.16_45_11.pdf)

Here is the sample project:- [ImageToPdfSample.zip](https://github.com/syncfusion/flutter-widgets/files/6912751/ImageToPdfSample.zip)

Now is there any way to do that?

Thank you.

**Comment by chinnumuniyappan** [comment]
Hi @brightseagit ,

Greetings from Syncfusion. We can add the PDF page based on the image sizes with the help of PdfSections, we have modified the sample to achieve this, Kindly check this on your end and let us know whether it is achieving your requirement.

```dart
    //Create PDF section.
    PdfSection section = document.sections!.add();
    //Load the image.
    final PdfImage image = PdfBitmap(await _readImageData('$imgName.jpg'));

    //set section orientation according to image size width
    if (image.height >= image.width) {
      section.pageSettings.orientation = PdfPageOrientation.portrait;
    } else if (image.height < image.width) {
      section.pageSettings.orientation = PdfPageOrientation.landscape;
    }
    //setting section size
    section.pageSettings.size =
        Size(image.width.toDouble(), image.height.toDouble());

    //removing any margin from document
    section.pageSettings.margins.all = 0;

    //Add the page
    PdfPage page = section.pages.add();
    //Load the image.

    //draw image to the first page
    page.graphics.drawImage(
        image, Rect.fromLTWH(0, 0, page.size.width, page.size.height));
```

Sample link: 
[ImageToPdfSample.zip](https://github.com/syncfusion/flutter-widgets/files/6915065/ImageToPdfSample.zip)

Regards,  
Chinnu M

**Comment by brightseagit** [comment]
Oh, I didn't know we can get the width and height this easily. But this was just half part of the problem. The other problem was to save all the images filling the same width in pdf pages without destroying the aspect ratio of images.

**Comment by Anand3595** [comment]
Hi @brightseagit ,

We can calculate and set page height based on the static width and image’s aspect ratio. The below code illustrates “How to draw all the images filling the same width in pdf pages without destroying the aspect ratio of images”,

```
//Width for all PDF pages
double pageWidth = 960;
//Create PDF section.
PdfSection section = document.sections!.add();
//Load the image.
final PdfImage image = PdfBitmap(await _readImageData('$imgName.jpg'));
//Caculating page height based on the fixed width and aspect ratio of the image
double ratio = pageWidth / image.width;
double pageHeight = image.height * ratio;
//Set section orientation according to image size width
if (image.height >= image.width) {
  section.pageSettings.orientation = PdfPageOrientation.portrait;
} else if (image.height < image.width) {
  section.pageSettings.orientation = PdfPageOrientation.landscape;
}
//Setting section size
section.pageSettings.size = Size(pageWidth, pageHeight);
//Removing any margin from document
section.pageSettings.margins.all = 0;
//Add the page
PdfPage page = section.pages.add();
//Load the image.
//Draw image to the PDF page
page.graphics.drawImage(
              image, Rect.fromLTWH(0, 0, page.size.width, page.size.height));
```

Please find the sample from https://www.syncfusion.com/downloads/support/directtrac/general/ze/ImageToPdfSample-1147411141.

Please let us know if you need any further assistance in this.

With Regards,
Anand Panchamoorthi

**Comment by brightseagit** [comment]
Thank you very much. It did the job 👍🙂.

**Comment by liquidiert** [comment]
Hey @chinnumuniyappan I can't seem to get it right with your provided code. I used this here: 
```dart
import 'package:syncfusion_flutter_pdf/pdf.dart' as spdf;

...

final newPdf = spdf.PdfDocument();

final imageData = spdf.PdfBitmap(img.encodePng(imgRepr));

newPdf.pageSettings.size = Size(
  imageData.width.toDouble(),
  imageData.height.toDouble(),
);

newPdf.pageSettings.margins.all = 0;

final page = newPdf.pages.add();

page.graphics.drawImage(
  imageData,
  Rect.fromLTWH(
    0.0,
    0.0,
    page.size.width,
    page.size.height,
  ),
);
```
With imgRepr being an Image object out of the image package.

As you can see here I still get a margin:
[scanned-document-497e028f-e612-46f6-aa6e-c178df082d01-1.pdf](https://github.com/user-attachments/files/15915285/scanned-document-497e028f-e612-46f6-aa6e-c178df082d01-1.pdf)

Any idea why?
