### ISSUE TITLE
Bug in example sorting code in data grid

### ISSUE THREAD

**Issue by edwardaux** [syncfusion/flutter-widgets#331]
Hi there,

Happened to write a simple custom sorter today and used the example code in the comments for `compare()`. Took me a while to figure out why the sorting wasn't working... turns out that the referenced line below has `valueA` and `valueB` around the wrong way - cut'n'paste strikes again 😂 

Easy fix but, I just thought I'd mentioned it. Thanks for what looks to be an awesome library.

https://github.com/syncfusion/flutter-widgets/blob/f9fb4bdcd90201d5c9379dd8be563d17e5314977/packages/syncfusion_flutter_datagrid/lib/src/control/datagrid_datasource.dart#L284

**Comment by RenugaSadagoban98** [comment]
Hi @edwardaux ,

Thanks for your feedback. 

We will change this, and these changes will be included in our upcoming 2021 Volume 2 SP release. which is expected to be rolled out on mid of August.

Regards,
Renugadevi.

**Comment by RenugaSadagoban98** [comment]
Hi @edwardaux ,
 
We are glad to announce that your reported feedback “Incorrect code snippet of compare method” changes was included our Essential Studio 2021 Volume 2 service pack Release v19.2.0.55 is rolled out and is available for download under the following link.
 
https://www.syncfusion.com/forums/168015/essential-studio-2021-volume-2-service-pack-release-v19-2-0-55-is-available-for-download
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
 
Regards,
Renugadevi
