### ISSUE TITLE
when called setState() in SfDataPager(onPageNavigationStart) , result in ERROR

### ISSUE THREAD

**Issue by Zhang-Ying-Zi** [syncfusion/flutter-widgets#332]
the ERROR is : 

```Error: setState() called after dispose(): _SfDataPagerState#565c4(lifecycle state: defunct, not mounted)```

when called setState() in SfDataPager(onPageNavigationEnd), is Fine, so what can I do to fix it ?

**Comment by Zhang-Ying-Zi** [comment]
this ERROR happens when SfDataPager in SfDataGrid(footer),  when make SfDataPager out of SfDataGrid(footer), the ERROR disappear

**Comment by RenugaSadagoban98** [comment]
Hi @Zhang-Ying-Zi ,  

Greetings from Syncfusion.  

From the provided information, we have checked your reported scenario. but we could not reproduce your reported issue at our end. We have loaded the datapager in footer with onPageNavigationStart, onPageNavigationEnd properties. 
 
We have tested the sample on the Android platform with the following device,  

Moto G5S plus,  
Flutter Channel: Stable
 
Please refer to the following sample for your reference,  
**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1756406179 
 
Please check the above sample and revert us if you still facing the same issue? If yes, please provide the following details,  

1. Which Flutter channel (Stable, beta or Master) are you using?  
2. Let us know your specific reason for loading datagrid in the footer? 
3. Which platform you are running?


It will be helpful for us to check on it and provide you the solution at the earliest.   

Regards,
Renugadevi
