### ISSUE TITLE
[syncfusion_flutter_pdfviewer] pdfviewer not gaining enough scrolling momentum on scrolling

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#334]
- User experience would be better if pdfviewer gains more scrolling momentum on scrolling as compared to current momentum.

### Current

https://user-images.githubusercontent.com/60609139/128128434-760c653b-2de5-4675-b43f-0a87aa6e8847.mp4

### Expected

https://user-images.githubusercontent.com/60609139/128128455-6ec47e6c-4082-428f-8d79-155a2861d70a.mp4

**Comment by dillibabun** [comment]
Hi @sagarkardani 

Greetings from Syncfusion.

Syncfusion Flutter PdfViewer uses InteractiveViewer widget internally to perform zooming and panning in a vertical, horizontal, and diagonal direction. Scrolling momentum is directly dependent on gesture deduction of InteractiveViewer so you are unable to scroll as per current momentum.

Regards,
Dilli babu.
