### ISSUE TITLE
[syncfusion_flutter_charts] Provide a EmptyPointSettings.dashArray

### ISSUE THREAD

**Issue by micimize** [syncfusion/flutter-widgets#336]
I find `EmptyPointMode.gap` too sparse while `EmptyPointMode.average` is a bit misleading and doesn't make the missing value clear. An option to change the dash array for a segment would be a good balance of the two.

**Comment by Dharanipalani** [comment]
Hi @micimize,

Thanks for the interest in our Flutter charts. We have investigated your query and would like to tell you that to use the empty point average mode and can customize this null value by giving distinct colors using the [color](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/EmptyPointSettings/color.html) property in the [EmptyPointSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/EmptyPointSettings-class.html). Also, can draw the dashed line by extendibility feature of our charts. We share the below demo link for customizing the chart using the extensibility feature and please make use of it as a reference. 

Help document: [https://help.syncfusion.com/flutter/cartesian-charts/series-customization#empty-points](https://help.syncfusion.com/flutter/cartesian-charts/series-customization#empty-points)

Demo: [https://flutter.syncfusion.com/#/cartesian-charts/chart-types/line/customized-line-chart](https://flutter.syncfusion.com/#/cartesian-charts/chart-types/line/customized-line-chart)

Please revert us if you need any further assistance on this.

Thanks,
Dharanitharan. P

**Comment by micimize** [comment]
Thanks for the response @Dharanipalani – I did not realize it was possible to supply a custom painter

**Comment by Lucverse** [comment]
@Dharanipalani hey, im trying to use the spline graph, in that i've a few null points, I want to show dashed lined connecting to those null data points. Is there any way to acheive this?
