### ISSUE TITLE
syncfusion_flutter_charts :  does not work on windows app

### ISSUE THREAD

**Issue by fabio21** [syncfusion/flutter-widgets#337]
`CUSTOMBUILD : error : Couldn't resolve the package 'syncfusion_flutter_charts' in 'package:syncfusion_flutter_charts/charts.dart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(4,8): error GDA81338A: Not found: 'package:syncfusion_flutter_charts/charts.dart' [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(41,3): error G7D2AEF3C: Type 'ChartTitle' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(51,3): error G7D2AEF3C: Type 'LineSeries' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(51,3): error G68675EF7: Expected 0 type arguments. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(74,3): error G7D2AEF3C: Type 'CategoryAxis' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(85,8): error G7D2AEF3C: Type 'PlotBand' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(89,3): error G7D2AEF3C: Type 'NumericAxis' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(99,3): error G7D2AEF3C: Type 'Legend' not found. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(37,16): error GEAA96E7B: 'LineSeries' isn't a type. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(28,12): error G76A9B1F6: The method 'SfCartesianChart' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(33,24): error G76A9B1F6: The method 'TooltipBehavior' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(36,15): error G76A9B1F6: The method 'Legend' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(42,12): error G76A9B1F6: The method 'ChartTitle' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(48,20): error GD65BB2B6: The getter 'ChartAlignment' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(52,12): error G76A9B1F6: The method 'LineSeries' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(63,23): error G76A9B1F6: The method 'MarkerSettings' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(66,26): error G76A9B1F6: The method 'DataLabelSettings' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(75,12): error G76A9B1F6: The method 'CategoryAxis' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(77,21): error GD65BB2B6: The getter 'ChartRangePadding' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(81,23): error G76A9B1F6: The method 'MajorGridLines' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(86,28): error G76A9B1F6: The method 'PlotBand' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(90,12): error G76A9B1F6: The method 'NumericAxis' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(92,21): error GD65BB2B6: The getter 'ChartRangePadding' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(95,23): error G76A9B1F6: The method 'MajorGridLines' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(100,12): error G76A9B1F6: The method 'Legend' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(103,17): error GD65BB2B6: The getter 'LegendPosition' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(104,18): error GD65BB2B6: The getter 'ChartAlignment' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
../Flutter.SellOut/lib/oslo/component/line_chart_component.dart(106,21): error GD65BB2B6: The getter 'LegendItemOverflowMode' isn't defined for the class 'ComponentLineChart'. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: Custom build for 'C:\projetos\Flutter\build\windows\CMakeFiles\b06ce6eccd8e0ad860a64e9fc1d9d1a9\flutter_windows.dll.rule;C:\projetos\Flutter\build\windows\CMakeFiles\685e801784c1fcc9b5f47ef36b80a3c1\flutter_assemble.rule' exited with code 1. [C:\projetos\Flutter\build\windows\flutter\flutter_assemble.vcxproj]
`

**Comment by Dharanipalani** [comment]
Hi @fabio21,

Thanks for the interest in our Flutter charts. We have analyzed your query and unfortunately, we are not able to replicate the reported issue. Kindly ensure using the latest stable channel of [Flutter SDK](https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_2.2.3-stable.zip) and [syncfusion_flutter_charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.2.51). We have no issues with the windows in the latest versions. Please ensure this and if the problem persists, kindly revert us with more details, this will help us to analyze and provide the solution to you sooner.

Thanks,
Dharanitharan. P
