### ISSUE TITLE
SfCartesianChart - detect trackball release

### ISSUE THREAD

**Issue by ericderegt** [syncfusion/flutter-widgets#342]
When using the SfCartesianChart trackball is it possible to react to the user releasing the trackball? The use case is that I want to update a value when the user releases the trackball.

I've tried looking through the properties of ChartPointInfo and implementing the logic in onTrackballPositionChanging, but I haven't been able to find a way to do it.

**Comment by Dharanipalani** [comment]
Hi @ericderegt,

Thanks for the interest in our Flutter charts. We have analyzed your query and would like to tell you that as of now there is no callback support for performing an action while releasing the trackball and we don't have any immediate plans to implement it in upcoming releases.

Thanks,
Dharanitharan. P
