### ISSUE TITLE
[syncfusion_flutter_datagrid] Text style is being overridden

### ISSUE THREAD

**Issue by edwardaux** [syncfusion/flutter-widgets#347]
My app has its own custom theme where I'm using custom fonts and colors... I've noticed that the datagrid doesn't seem to honour these and I finally got around to doing some digging today.

It looks like datagrid creates a hard-coded `TextStyle` for [each cell](https://github.com/syncfusion/flutter-widgets/blob/f9fb4bdcd90201d5c9379dd8be563d17e5314977/packages/syncfusion_flutter_datagrid/lib/src/cell_renderer/grid_cell_text_field_renderer.dart#L43) and then [wraps the cell's widget](https://github.com/syncfusion/flutter-widgets/blob/f9fb4bdcd90201d5c9379dd8be563d17e5314977/packages/syncfusion_flutter_datagrid/lib/src/cell_renderer/grid_virtualizing_cell_renderer_base.dart#L37) in a `DefaultTextStyle` which means my theme is totally ignored.

How do I stop this and get the grid to use the `Text` widgets that I actually pass it? Thanks.

**Comment by RenugaSadagoban98** [comment]
Hi @edwardaux , 

Greetings from syncfusion. 

We are getting the widgets directly from users. SfDataGrid provides support for load any type of widget in each column. So, you can set text style in text widget level itself.  In the below sample, we have set the custom fonts and different color for texts in Text widgets. Here, we have created an assets folder. There we have added the fonts. 
 
![image](https://user-images.githubusercontent.com/77044081/129905465-8d2a5fb8-2c3b-40c9-bb1c-c212c32883c6.png)

![image](https://user-images.githubusercontent.com/77044081/129905485-43d86db1-b1c8-44fa-94bb-95e48f4f1225.png)

Refer following code snippet,
```
  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      final index = _employeeData.indexOf(row);
      return Container(
        alignment: Alignment.center,
        padding: EdgeInsets.all(8.0),
        color: (index % 2) != 0 ? Colors.amber[100] : Colors.blue[100],
        child: Text(e.value.toString(),
            style: index % 2 != 0
                ? TextStyle(
                    fontStyle: FontStyle.italic,
                    fontFamily: 'HeeboBold',
                  )
                : TextStyle(
                    fontStyle: FontStyle.normal,
                    fontFamily: 'HeeboMedium',
                  )),
      );
    }).toList());
  }

```
Can you please look onto the below sample and let us know if anything we missed other than your customization?
**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main629594327

Regards, 
Renugadevi.

**Comment by edwardaux** [comment]
Thanks for the quick reply and sample code. It looks like it works OK as long as I set the style explicitly. eg.
```
  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
      cells: row.getCells().map<Widget>((dataGridCell) {
        return const Text('xxxx', style: TextStyle(color: Colors.red));
      }).toList(),
    );
  }
```
However, if I just return `const Text('xxxx')` then, instead of using the application's theme, the grid provides its own default fonts and color. I would suggest that that is unexpected behaviour. 

If we compare this behaviour to other Flutter container widgets (eg. `Row`, `Column`, `Table`, `ListView`, etc), if I pass in a `Text('xxx')` value, it will use `Theme.of(context)` to determine what the current `bodyText2` style is. Those containers don't override the current theme with their own styles. Obviously, this is your (excellent) widget and you can do whatever you like with it, but I do think that the current behaviour is unexpected.

In my case, I can work around it by passing my theme into my `DataGridSource` and explicitly apply it using something like:
```
  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
      cells: row.getCells().map<Widget>((dataGridCell) {
        return Text('xxxx', style: theme.textTheme.bodyText2);
      }).toList(),
    );
  }
```

In any case, thanks for an excellent widget and great support!

**Comment by RenugaSadagoban98** [comment]
Hi @edwardaux ,

Thanks for your update.

We would like to let you know that the reported behavior of textstyle is our expected behavior.
If you want to set the style for the cells, you can set text style in the widget level itself. Otherwise, the default grid style will be applied to the cells. You want to use the style from the framework theme then you can set the theme style to cell widget.

Kindly revert us, if you have any concerns.

Regards, 
Renugadevi.

**Comment by edwardaux** [comment]
👍 No problems. I'm able to get it working as I need by explicitly setting the style from my theme.

Thanks again for a great widget.
