### ISSUE TITLE
Add an option to place a string or widget in the middle of Doughnut

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-widgets#350]
Hello, 
Is there a way to place a string or widget in the middle of Doughnut?

![image](https://user-images.githubusercontent.com/16321223/130199587-dc361371-a469-434b-88f3-eb1578a0113d.png)

I checked SfCircularChart widget but couldn't find a direct way to do so.

**Comment by bismarabia** [comment]
Looks Like I can do that using **annotations** attribute and **CircularChartAnnotation**.

correct me if I am wrong please.

**Comment by dharanidharandharmasivam** [comment]
Hi @bismarabia ,

Yes, you can achieve your requirement using the annotation feature. You can find the samples and code below,

**Sample:** https://npmci.syncfusion.com/flutter/demos/html/#/circular-charts/chart-types/doughnut/color-mapping 
**Code link:** https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/circular_charts/chart_types/doughnut/doughnut_with_color_mapping.dart 
**API:** https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularChartAnnotation-class.html 

Hope this helps.

Thanks,
Dharani.
