### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Oblique Search Result

### ISSUE THREAD

**Issue by c3budiman** [syncfusion/flutter-widgets#355]
Hi,
First i would like to give an applause for this great libs.

i encountered some bugs that made the highlighted search result appear to be oblique.
screenshoot attached :
![image](https://user-images.githubusercontent.com/1578830/130721887-acbe8e68-32dd-4f89-8274-ff9e6f515914.png)

![image](https://user-images.githubusercontent.com/1578830/130721948-49f11468-f9fd-4a2a-83bb-0cbe0c0eb2e8.png)

i also create a github project to reproduce the bug, code as following :
https://github.com/c3budiman/syncflutterpdf-recreate-problems/blob/master/lib/main.dart

any help is really apreciated thanks 👍

**Comment by deepika134** [comment]
Hi c3budiman,

Greetings from Syncfusion.

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 27 August 2021.

You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal]( https://www.syncfusion.com/feedback/flutter).

Regards,
Deepika R

**Comment by deepika134** [comment]
Hi c3budiman,

We have confirmed that the reported issue “Resultant bounds are not proper while performing text search in particular PDF document” is a defect. The issue fix will be included in our upcoming weekly release, which will be available on 14 September 2021. The status of this issue can be tracked using the following link https://www.syncfusion.com/feedback/28320/text-search-bounds-are-not-proper-in-the-particular-pdf-document.

Regards,
Deepika R

**Comment by c3budiman** [comment]
Thanks for the update, looking forward for the upcoming weekly release 👍

**Comment by deepika134** [comment]
Hi c3budiman,

we have included the fix for this issue " Resultant bounds are not proper while performing text search in particular PDF document" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.2.62 to get the issue resolved.  
Package Link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.2.62-beta 

Regards,
Deepika R

**Comment by c3budiman** [comment]
Thanks Syncflutter team, 

i can confirm that it is fixed now.

![image](https://user-images.githubusercontent.com/1578830/133279267-99caad02-fec4-454c-9394-4871ef83ef43.png)

closing this issue. you guys are cool! keep up the good work 💪
