### ISSUE TITLE
[syncfusion_flutter_charts] numberFormat seems to cap at high decimalDigits

### ISSUE THREAD

**Issue by steebchen** [syncfusion/flutter-widgets#358]
When I use `primaryYAxis` with these options:

```
NumericAxis(
  opposedPosition: true,
  maximumLabels: 1,
  rangePadding: ChartRangePadding.round,
  numberFormat: NumberFormat.simpleCurrency(decimalDigits: 15),
)
```

And the line data contains like 10 digits, e.g. `0.00000755`, it does not seem to get displayed correctly:

<img width="1156" alt="Screenshot 2021-08-29 at 00 17 53" src="https://user-images.githubusercontent.com/5013932/131225708-8317d910-0260-472c-9c28-6d8ce85e2401.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @steebchen,

Greetings from Syncfusion. We have analyzed your scenario at our end, and we have created a simple sample in which we have used the **onTrackballPositionChanging** callback event to show the datapoint's y-value data fully in the trackball tooltip. For reference, please check the code snippet below.
```
SfCartesianChart(
       primaryYAxis: NumericAxis(decimalPlaces: 10),
       onTrackballPositionChanging: (TrackballArgs args) {
           num returnFormat = args.chartPointInfo.chartDataPoint!.y;
           /// As these are 8 decimal places in the y-value, I have set the fractionalDigits as 8 
           /// in the toStringAsFixed method.
          args.chartPointInfo.label =
              returnFormat.toStringAsFixed(8);
       },
       trackballBehavior: TrackballBehavior(
          enable: true,
       ),
       //...
)
```
**Screenshot:**
![image](https://user-images.githubusercontent.com/63577117/131338346-0bb7e1d4-c75f-4a7c-b951-cdb08f21a554.png)

The sample for reference can be found below.
[Sample.zip](https://github.com/syncfusion/flutter-widgets/files/7076638/ghfw_358_numberformat.zip)

Please check with the above sample and revert us if you still have further concerns.

Regards,
Sriram Kiran

**Comment by steebchen** [comment]
Thanks, both tips work! :)
