### ISSUE TITLE
is There any way to get selected or taped position x and y axis in pdfviewer.

### ISSUE THREAD

**Issue by lavahasif** [syncfusion/flutter-widgets#36]
i want to custom add  annotation based on x,y cordinate.is there any way to get taped region in pdf viewer

**Comment by dillibabun** [comment]
Hi @lavahasif ,

Yes, it is possible to obtain the tap coordinate of SfPdfViewer Widget. The following code example illustrates how to obtain the tapped position coordinate.

`return Scaffold(
  body: GestureDetector(
    onTapDown: (details) {
      print(details.localPosition);
    },
    child: SfPdfViewer.asset(
      'assets/sample.pdf',
    ),
  ),
);`

For further queries and better tracking, we recommend you to contact us through our support forum, Direct-Trac, or feedback portal. We are always happy to assist you!

Regards
Dilli babu

**Comment by lavahasif** [comment]
thank you .
