### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Error opening PDF

### ISSUE THREAD

**Issue by tlueder** [syncfusion/flutter-widgets#360]
Hi,

I get the following error opening the attached PDF.

example[14079] <Error>: kvImagePrintDiagnosticsToConsole: vImageConverter: kCGBitmapByteOrder16Little is not allowed on 8-bit images with pixel size of 32 bits.

Steps to reproduce:
1. get the example from the pdf viewer plugin
2. make sure its loading the attached pdf
3. start the app

[vent-axia_-_sustainability_is_attainable_-_infographic.pdf](https://github.com/syncfusion/flutter-widgets/files/7076443/vent-axia_-_sustainability_is_attainable_-_infographic.pdf)

**Comment by deepika134** [comment]
Hi tluder, 

We tried to reproduce the reported issue, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample (along with the output screen shot of the same) and it can be downloaded from the following link, 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1061216998.zip 

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.

1. Platforms in which the issue is reproduced (Android, iOS, Web). 
2. Device Specification.
3. Flutter Doctor log.
4. syncfusion_flutter_pdfviewer package version.
5. Flutter SDK version.

These information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika R

**Comment by tlueder** [comment]
Thanks for the reply. 
Yes I can confirm that it is working on Android, iOS and Web. 

But not on macOS, which is my dev environment and I only tested it there.
Sorry for the lack of information.

1,
macOS

2.
MacBook Pro

3.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.6.0-0.0.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

4.
syncfusion_flutter_pdfviewer: ^19.2.57-beta

5.
Flutter Channel dev, 2.6.0-0.0.pre

**Comment by tlueder** [comment]
Hi,

still the same error.
I've downloaded your zip and just hit flutter run without any mods.

Please find attached the output of flutter run --verbose

[flutter.log](https://github.com/syncfusion/flutter-widgets/files/7099080/flutter.log)

**Comment by tlueder** [comment]
flutter doctor --verbose
[✓] Flutter (Channel dev, 2.6.0-0.0.pre, on macOS 11.5.2 20G95 darwin-x64, locale en-AU)
    • Flutter version 2.6.0-0.0.pre at /Users/tluder/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 83b9e99cfb (10 days ago), 2021-08-23 19:03:21 +0200
    • Engine revision d5adde01dd
    • Dart version 2.15.0 (build 2.15.0-42.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/tluder/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.59.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

**Comment by sarathkumar50** [comment]
Hi @tlueder ,

We tried to reproduce the reported issue from our side with provided information but the PDF document was loaded properly. Please find the screen capture of the macOS app below.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/78202838/131977667-550873ac-6a6e-4aff-8c91-fe75dd40e505.png)
To check further on this, we like to have meeting and looking the issue in your machine. So, kindly a create a incident in our support site and mention your convenience time for the meeting.
https://www.syncfusion.com/support/directtrac/incidents

Regards,
Sarath Kumar.

**Comment by sarathkumar50** [comment]
Hi @tlueder ,

Sorry for the inconvenience.

We are still analyzing the reported issue since the reported issue is not reproduced and trying to setup a similar environment at our end. We are working on it with high priority. We will update the validation details on September 14, 2021 without any further delay.

Regards,
Sarath Kumar.
