### ISSUE TITLE
[Question] Too much appointments

### ISSUE THREAD

**Issue by TheCarpetMerchant** [syncfusion/flutter-widgets#361]
Hello,

I like like to know if there is any guidelines, or how the Calendar was envisionned to function when there is a lot of appointments in it, such as in the attached screenshot.
![image](https://user-images.githubusercontent.com/5080204/131974987-212f5216-0ce0-4e37-af44-04dc85f6c16f.png)

Idealy, I would like to be able to set a minimum size for the appointment widget, and have the calendar be scrollable across the week until you reach the last, upon which further scrolling loads the next week.

Is such a feature possible ? If not, what is your advice on how to deal with this situation ?

Thanks :)

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Based on the shared information we have analyzed your requirement “**Week view with more appointment and horizontally scrollable**” based on the current implementation of the calendar week view will look the same as the image, and there is no support to set the minimum appointment width, to achieve your requirement we suggest to the timeline week view, which will be horizontally scrollable and will display more appointments with required details. Also, by using the timeIntervalWidth property you can change the width of the **timeInterval**.

Kindly find the UG link for the same.

**UG links:**
https://help.syncfusion.com/flutter/calendar/timeslot-views#change-time-interval-width
https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarView-class.html

We hope that this helps you.  Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Cedricoh** [comment]
The timeline has the same fundamental problem : If you have too many appointments in one day, you would need to set a minimum height to the Appointment widget to see its content.

**Comment by muthulakshmi-123** [comment]
Hi,

Based on provided information we have analyzed your requirement **“How to set minimum size for appointment”** as per calendar implementation, you can set height for appointment in timeline views by using the timelineAppointmentHeight property, which is used to customize the height for appointments in timeline views of the calendar. Kindly, share more details about your requirement. It will be helpful for us to analyze and resolve your requirement.

Kindly find the UG documentation by referring to the following link:
https://help.syncfusion.com/flutter/calendar/timeslot-views#timeline-appointment-height

Kindly find the KB, by referring to the following link: https://www.syncfusion.com/kb/11411/how-to-prevent-multiple-assignments-of-the-same-time-events-in-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K

**Comment by Cedricoh** [comment]
timelineAppointmentHeight works fine, but since there is no vetical scroll in the timeline, it gets capped.
I can see that there is a vetical scroll enabled on the Resource View at https://flutter.syncfusion.com/#/event-calendar/resource-view, how can I achieve that for other views ?

**Comment by muthulakshmi-123** [comment]
Hi,

Thank you for the update.

Based on provided information your requirement is "Can I enable resource view for other views?". As per the current implementation, the resource grouping is only applicable for all timeline views. The vertical scrolling is enabled for timeline views only when the resource collection is set in the data source, based on the resource count. Kindly, share more details about your requirement. It will be helpful for us to analyze and resolve your requirement. 

Please refer to the following UG link for more information.  
https://help.syncfusion.com/flutter/calendar/resource-view

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muthulakshmi K
