### ISSUE TITLE
[syncfusion_flutter_pdfviewer] (1) Unnecessary scroll lock (2) Panning and zooming not working after scroll lock

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#363]
### (2) Panning and zooming not working after scroll lock

- Attached is the screen recording

https://user-images.githubusercontent.com/60609139/132084964-8f23fe17-e5e2-4db3-aef5-1462cc007871.mp4

### Desired behaviour

- Scroll lock is unnecessary : I have seen some pdfviewers doing horizontal or vertical scroll lock according to scroll direction. But IMHO user experience is much better if scrolling is not locked in any direction.

- Panning and zooming should work any time whenever performed.

    I think this issue is because of InteractiveViewer widget. However I have not gone into details. Previously I have also submitted other gestures and panning related issues which were also related to InteractiveViewer.

###  InteractiveViewer related total issues (I may be wrong)

- #334

- #333

- This issue - Scroll lock

- This issue - Panning and Zooming not working after scroll lock

### Expected enhancement work

- InteractiveViewer should either be replaced by CustomInteractiveViewer or transformationController should be handled in such a way that all these actions works fine.

Regards,
Sagar

**Comment by deepika134** [comment]
Hi sagarkardani,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 8 September 2021.

Regards,
Deepika R

**Comment by deepika134** [comment]
Hi sagarkardani,

We have confirmed that the reported issue “Panning and zooming not working after scroll lock” is a defect. The issue fix will be included in our upcoming volume 3 release, which is expected to be rolled out on last week of September 2021.

Regards,
Deepika R

**Comment by deepika134** [comment]
Hi sagarkardani,

we have included the fix for this issue “Panning and zooming not working after scroll lock” in our latest volume 3 release, so kindly upgrade to the latest version v19.3.43 to get the issue resolved.   
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.43-beta  

Regards, 
Deepika R

**Comment by sagarkardani** [comment]
Working Fine...
