### ISSUE TITLE
[Syncfusion_flutter_pdfviewer]  TextSelection does not select separate paragraps

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-widgets#364]
I am using Syncfusion_flutter_pdfviewer plugin. I was working with a  pdf that has two paragraphs (one at the left and other at the right side separated by spaces) and I wanted to select text just from one paragraph but whenever I select text , the selection handles drags such that it selects the complete lines thereby selecting both paragraphs.
@syncfusion

**Sample pdf**:  http://112.196.1.221:9023/pdf/Instagram Guide.pdf

**I am also attaching video for the same**. 
https://user-images.githubusercontent.com/60787872/132136096-1279ca98-8d90-4bca-b856-e052b0c3eeca.mp4

**Comment by deepika134** [comment]
Hi ritz-ch,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 8 September 2021.

Note: Unable to accesses the provided sample document. we can reproduce the reported issue on our side with a similar kind of document shown in the output screen record.

Regards,
Deepika R

**Comment by ritz-ch** [comment]
Hi @deepika134 ,
You can consider the below pdf for reproducing the issue.
[Instagram Guide.pdf](https://github.com/syncfusion/flutter-widgets/files/7118991/Instagram.Guide.pdf)

**Comment by deepika134** [comment]
Hi ritz-ch,

Sorry for the inconvenience.

We are still analyzing the reported issue and working on it with high priority. We will update the validation details on September 13, 2021 without any further delay.

Regards,
Deepika R

**Comment by deepika134** [comment]
Hi ritz-ch,

We found the root cause of the issue. In text selection, we selected the text based on the text line, didn't consider the text selection based on the paragraph wise. We suspect that this is a defect in text selection. we are analyzing more details about the issue, we will update the further details on September 15, 2021.

Regards,
Deepika R

**Comment by sarathkumar50** [comment]
Hi @ritz-ch ,
 
At present SfPdfViewer widget does not have support for “multi-column PDF selection”.
SfPdfViewer provides support only to select the text based on the text lines.We are considered this improvement as a feature.This feature is expected to be implemented on our october 2nd weekly package release which is expected to be available on 12th October, 2021.
 
The status of this feature can be tracked using following link. 
https://www.syncfusion.com/feedback/28697/text-selection-support-in-multi-column-pdf
 
Regards,
Sarath Kumar.
