### ISSUE TITLE
[Syncfusion_flutter_pdfviewer] Text Selection handle not pulling upward and are hard to use

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-widgets#365]
I am working with Syncfusion_flutter_pdfviewer plugin. Sometimes while selecting text when we pull the left selection handle upwards, the text is not selected. Also, sometimes the text selection handles appears late on the screen. I am attaching the video for the same.  @syncfusion

**Sample pdf used :**
[sample-pdf-download-10-mb.pdf](https://github.com/syncfusion/flutter-widgets/files/7110130/sample-pdf-download-10-mb.pdf)

**Video:**

https://user-images.githubusercontent.com/60787872/132136685-9294fff7-de77-48a3-a1b0-07100c2ab3a7.mp4

**Comment by deepika134** [comment]
Hi ritz-ch,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 8 September 2021.

Regards,
Deepika R

**Comment by sarathkumar50** [comment]
Hi @ritz-ch ,

We have confirmed that the issue with "Text Selection handle is difficult to drag towards upward" is a defect. The issue fix will be included in our September 2nd weekly package release which is expected to be available on 14th September, 2021. 

For further queries,You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar.

**Comment by deepika134** [comment]
Hi ritz-ch,

we have included the fix for this issue " Text Selection handle is difficult to drag towards upward" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.2.62 to get the issue resolved.  
Package Link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.2.62-beta 

Regards,
Deepika R
