### ISSUE TITLE
[syncfusion_flutter_datepicker] - allow to use a lower case day name

### ISSUE THREAD

**Issue by nank1ro** [syncfusion/flutter-widgets#368]
Hello,

currently in your code the name of the day is always uppercased:
```dart
 String dayText =
            DateFormat(monthViewSettings.dayFormat, locale.toString())
                .format(isHijri ? currentDate.toDateTime() : currentDate)
                .toString()
                .toUpperCase()
```
here it is the [link to the code](https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_datepicker/lib/src/date_picker/date_picker.dart#L6407): 

Can you provide a boolean in the `DateRangePickerViewHeaderStyle` to decide if the text should be uppercased?

Thank you in advance.

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

Based on the shared information, we have checked your requirement “**Lower case support for view header day text in SfDateRangePicker**”. As of now, there is no direct support for this requirement. But your requirement can be achieved by hiding (headerHeight=0, viewHeaderHeight=0) default headers. We have a KB document for the custom header. Please find the KB from the following link.

**KB link:**
https://www.syncfusion.com/kb/12098/how-to-replace-the-view-header-with-the-custom-widget-in-flutter-date-range-picker

Please find the UG documentation for customizing the header height.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/headers#customize-the-header-height

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
