### ISSUE TITLE
[syncfusion_flutter_gauges] Is it possible to use string as labels instead of numbers?

### ISSUE THREAD

**Issue by d-apps** [syncfusion/flutter-widgets#369]
I need to show names instead of numbers using gauges but I couldn`t find anything about this on the examples/documentation.

![Screen Shot 2021-09-10 at 17 33 25](https://user-images.githubusercontent.com/20110433/132914733-52b83fc5-162c-444b-a6f3-3550ddef63ff.png)

How to use names instead of numbers (0, 50, 100 in the image)?

for example, I have three words to replace those numbers (Bad, Ok, Good).

Thank you.

**Comment by praveeng2565** [comment]
Hi d-apps,

Greetings from Syncfusion support.

We have checked your query and found that you can achieve this by [RadiaAxis.onLabelCreated](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/onLabelCreated.html) callback. It passes an [AxisLabelCreatedArgs](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/AxisLabelCreatedArgs-class.html) to this callback which is used to change text value. For detailed information, Kindly check [this](https://help.syncfusion.com/flutter/radial-gauge/axes#events) user guide documentation link. We have attached a code snippet for your reference.

```
return SfRadialGauge(
    axes: <RadialAxis>[
      RadialAxis(
        minimum: 0,
        maximum: 100,
        interval: 25,
        minorTicksPerInterval: 0,
        startAngle: 180,
        endAngle: 360,
        onLabelCreated: _handleLabelCreated,
        ranges: <GaugeRange>[
          GaugeRange(startValue: 0, endValue: 33, color: Colors.green),
          GaugeRange(startValue: 30, endValue: 66, color: Colors.yellow),
          GaugeRange(startValue: 66, endValue: 100, color: Colors.red),
        ],
        pointers: <GaugePointer>[NeedlePointer(value: 50)],
      )
    ],
  );
}

/// Handled callback to change numeric value into a custom text.
void _handleLabelCreated(AxisLabelCreatedArgs args) {
  if (args.text == '0') {
    args.text = 'Bad';
  } else if (args.text == '50') {
    args.text = 'Ok';
  } else if (args.text == '100') {
    args.text = 'Good ';
  } else {
    args.text = '';
  }
}
```

We hope that the above solution will resolve your problem. Please let us know if you need any further assistance in this.  

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi d-apps,

Greetings from Syncfusion support.

We have checked your query and found that you can achieve this by [RadiaAxis.onLabelCreated](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/onLabelCreated.html) callback. It passes an [AxisLabelCreatedArgs](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/AxisLabelCreatedArgs-class.html) to this callback which is used to change text value. For detailed information, Kindly check [this](https://help.syncfusion.com/flutter/radial-gauge/axes#events) user guide documentation link. We have attached a code snippet for your reference.

```
return SfRadialGauge(
    axes: <RadialAxis>[
      RadialAxis(
        minimum: 0,
        maximum: 100,
        interval: 25,
        minorTicksPerInterval: 0,
        startAngle: 180,
        endAngle: 360,
        onLabelCreated: _handleLabelCreated,
        ranges: <GaugeRange>[
          GaugeRange(startValue: 0, endValue: 33, color: Colors.green),
          GaugeRange(startValue: 30, endValue: 66, color: Colors.yellow),
          GaugeRange(startValue: 66, endValue: 100, color: Colors.red),
        ],
        pointers: <GaugePointer>[NeedlePointer(value: 50)],
      )
    ],
  );
}

/// Handled callback to change numeric value into a custom text.
void _handleLabelCreated(AxisLabelCreatedArgs args) {
  if (args.text == '0') {
    args.text = 'Bad';
  } else if (args.text == '50') {
    args.text = 'Ok';
  } else if (args.text == '100') {
    args.text = 'Good ';
  } else {
    args.text = '';
  }
}
```

We hope that the above solution will resolve your problem. Please let us know if you need any further assistance in this.  

Regards,
Praveen G.
