### ISSUE TITLE
More flexible custom on agenda cell

### ISSUE THREAD

**Issue by khangpt** [syncfusion/flutter-widgets#37]
I wonder why we don't permit an custom widget for agenda cell in calendar (month view). It's so restrictive now. Please add more this support beside wonderful things at present  of calendar

**Comment by Indumathi1195R** [comment]
Hi @khangpt ,

Based on the provided information, we have checked your requirement “**Custom widget support appointment in the Flutter calendar**”. We have already logged the feature request for the same. We will implement this feature in our upcoming 2020 Volume 4 release, which is expected to roll out by end of December 2020, and let you know once the release rolled out. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below feedback link. 

**Link:** https://www.syncfusion.com/feedback/14380/custom-widget-support-for-appointments-in-flutter-event-calendar-sfcalendar

As of now, you can refer the following KB document for showing custom agenda view.

**KB link:** https://www.syncfusion.com/kb/11016/how-to-show-a-custom-agenda-view-in-the-flutter-event-calendar-sfcalendar-widget

Regards,
Indumathi R

**Comment by khangpt** [comment]
Thanks for your response. At the KB link inspire me so much. However, I still waiting for the next release of this calendar.

Regards,

**Comment by Indumathi1195R** [comment]
Hi,

We are glad to announce that our Essential Studio 2020 Volume 4 release v18.4.30 is rolled with the mentioned feature “**Custom widget support for appointments in Flutter event calendar (SfCalendar)**”. Kindly update to the mentioned version for this feature. Please find the latest version from the following pub link.

**Latest version link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions
 
**Changelog link:** https://pub.dev/packages/syncfusion_flutter_calendar/changelog

**UG link:** https://help.syncfusion.com/flutter/calendar/builders#appointment-builder

**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v18.4.0.30?type=all#calendar

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,           
Indumathi R
