### ISSUE TITLE
[syncfusion_flutter_maps] No way to handle network errors

### ISSUE THREAD

**Issue by lukepighetti** [syncfusion/flutter-widgets#370]
I have been trying to use the OpenTopoMap tileset, hosted here: `https://b.tile.opentopomap.org/{z}/{x}/{y}.png`

I keep getting uncaught exceptions that are triggering debug break in my IDE.

I don't see any way for me to handle these exceptions, since they appear to be internal to `syncfusion_flutter_maps`. I cannot suppress them or handle them. In order for the map to be durable I feel like these errors should be handled for me. Or we should be given a way to provide our own network handler.

```
════════ Exception caught by image resource service ════════════════════════════
The following HttpException was thrown resolving an image codec:
Connection closed before full header was received, uri = https://b.tile.opentopomap.org/15/10129/11808.png

When the exception was thrown, this was the stack
Image provider: NetworkImage("https://b.tile.opentopomap.org/15/10129/11808.png", scale: 1.0)
Image key: NetworkImage("https://b.tile.opentopomap.org/15/10129/11808.png", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
Connection closed before full header was received, uri = https://b.tile.opentopomap.org/15/10129/11807.png
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════
Connection closed while receiving data, uri = https://b.tile.opentopomap.org/15/10126/11804.png

```

**Comment by PraveenGopalsamy** [comment]
Hi lukepighetti,

Greetings from syncfusion support.

We are checking this case from our end and we will update you with more details by September 15, 2021.

Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi lukepighetti,

We have checked this case and found that it will be resolved by adding the subdomains support for loading tiles. Currently there is no option to set subdomains in our maps. So, we have considered your request as a feature and the status can be tracked from the feedback portal link.
 
Feedback: https://www.syncfusion.com/feedback/28667/provide-an-option-to-load-tiles-from-the-subdomains
 
If this does not meet your requirements, please let us know the details. 

Note: We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal. 

Regards,
Praveen G.
