### ISSUE TITLE
[syncfusion_flutter_pdf] - Windows Desktop Usage

### ISSUE THREAD

**Issue by memmen** [syncfusion/flutter-widgets#372]
Is there going to be support for syncfusion_flutter_pdf for desktop? I love using the package for iOS, web and android and would love to continue for desktop.

**Comment by Anand3595** [comment]
Hi Brian S Memmen,

Thanks for contacting Syncfusion support.

We have support to create and manipulate PDF in windows by using [syncfusion_flutter_pdf ](https://pub.dev/packages/syncfusion_flutter_pdf) package. Please find the complete documentation from https://help.syncfusion.com/flutter/pdf/overview.

Please find the sample to create PDF in windows from https://www.syncfusion.com/downloads/support/directtrac/general/ze/syncfusion_pdf_sample826141406.

With Regards,
Anand Panchamoorthi

**Comment by memmen** [comment]
Thank you for the resources. What about displaying the PDF?

**Comment by deepika134** [comment]
Hi Brian S Memmen, 
 
At present we do not have support for PDFViewer on the Windows platform. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked using following link, https://www.syncfusion.com/feedback/27240/windows-and-linux-support-for-flutter-pdfviewer  
 
Regards, 
Deepika R

**Comment by memmen** [comment]
Thank you.

**Comment by deepika134** [comment]
Hi @memmen ,

We have implemented the windows support in Flutter PdfViewer, which is available at the following link,
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.47-beta  

We are glad to announce that our Essential Studio 2022 Volume 1 Main Release V20.1.0.47 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/174125/essential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download  

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Deepika Ravi
