### ISSUE TITLE
getting error as: range error:invalid value: Not in inclusive range 0..6:10 while switching pages on use of flutter same bloc state

### ISSUE THREAD

**Issue by anishramagiri** [syncfusion/flutter-widgets#373]
implemented SfDataGrid as per documentation, using flutter bloc package 

for multiple pages we are using same bloc ,event & state . 
on navigation between pages  

example: 
as first page having records of 10 
as second page having records of 6

on first load of page showing records successfully

after switching between second page to first page 

we getting error as:
range error:invalid value: Not in inclusive range 0..6:10

**Comment by RenugaSadagoban98** [comment]
Hi @anishramagiri , 
 
Greetings from Syncfusion.
 
From the provided information, we have prepared the sample with bloc (BlocProvider, BlocBuilder) using the flutter_bloc(v 6.1.2) package. In this sample, we have three pages. And the first page contains ten records, the second page contains six records, and the third page contains five records. It's working fine while we are switching between the paging.
 
**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/lib1271443122
 
Please check the above sample and revert us if you still facing the same issue? If yes, please confirm the following details, 

Whether your sample have datagrid with datapager?
Syncfusion pub package version?
Issue reproducing steps or video (If possible)  

Can you please look into the above sample and let us know if we missed anything other than your customization.


Regards,  
Renugadevi

**Comment by anishramagiri** [comment]
> Hi @anishramagiri ,
> 
> Greetings from Syncfusion.
> 
> From the provided information, we have prepared the sample with bloc (BlocProvider, BlocBuilder) using the flutter_bloc(v 6.1.2) package. In this sample, we have three pages. And the first page contains ten records, the second page contains six records, and the third page contains five records. It's working fine while we are switching between the paging.
> 
> **Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/lib1271443122
> 
> Please check the above sample and revert us if you still facing the same issue? If yes, please confirm the following details,
> 
> Whether your sample have datagrid with datapager?
> Syncfusion pub package version?
> Issue reproducing steps or video (If possible)
> 
> Can you please look into the above sample and let us know if we missed anything other than your customization.
> 
> Regards,
> Renugadevi


thank you for replying to my query

am not able to resolve after implementing data pager, without data pager its working fine

please look into the below details as you mentioned

Whether your sample have datagrid with datapager?
yes we using data pager 

Syncfusion pub package version?
  syncfusion_flutter_datagrid: ^19.2.62-beta

Issue reproducing steps or video (If possible)


                                --------BlocBuilder -----
                         `BlocBuilder<TaskDocBloc, TaskDocState>(
                            bloc: BlocProvider.of<TaskDocBloc>(context),
                            buildWhen: (previousState, currentState) {
                              return previousState != currentState;
                            },
                            builder: (ctxt, state) {
                              if (state is TaskDocSuccess) {
                                TaskDataSource taskDataSource;
                                DocDataSource docDataSource;
                                taskDataSource = TaskDataSource(
                                  state.tasks,
                                  context,
                                );

                  List<Task> taskCount = state.tasks;
                  docDataSource = DocDataSource(documents: state.documents);

                  return LayoutBuilder(builder: (context, constraints) {
                    return Row(
                      children: [
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            SizedBox(
                              height: 550,
                              width: constraints.maxWidth,
                              child: SfDataGrid(
                                allowSorting: true,
                                source: taskDataSource.rows.length > 0
                                    ? taskDataSource
                                    : docDataSource,
                                columnWidthMode: ColumnWidthMode.fill,
                                columns: [
                                  GridColumn(
                                    columnName: 'id',
                                    label: Container(
                                      height: 50,
                                      width: 90,
                                      color: Color(0xffEFF5FC),
                                      padding: EdgeInsets.all(16.0),
                                      alignment: Alignment.center,
                                      child: Checkbox(
                                        value: checkedBox,
                                        onChanged: (value) {
                                          setState(() {
                                            checkedBox = value;
                                          });
                                        },
                                      ),
                                    ),
                                  ),
                                  GridColumn(
                                      columnName: 'title',
                                      label: Container(
                                          height: 50,
                                          color: Color(0xffEFF5FC),
                                          padding: EdgeInsets.all(16.0),
                                          alignment: Alignment.centerLeft,
                                          child: Text(
                                            Translate.of(context)
                                                .translate('title'),
                                          ))),
                                  GridColumn(
                                      columnName: 'description',
                                      label: Container(
                                          height: 50,
                                          color: Color(0xffEFF5FC),
                                          padding: EdgeInsets.all(16.0),
                                          alignment: Alignment.centerLeft,
                                          child: Text(
                                            Translate.of(context)
                                                .translate('description'),
                                          ))),
                                  GridColumn(
                                      columnName: 'createdAt',
                                      label: Container(
                                          height: 50,
                                          color: Color(0xffEFF5FC),
                                          padding: EdgeInsets.all(16.0),
                                          alignment: Alignment.centerLeft,
                                          child: Text(
                                            Translate.of(context)
                                                .translate('created_time'),
                                          ))),
                                  GridColumn(
                                      columnName: 'beginTime',
                                      label: Container(
                                          height: 50,
                                          color: Color(0xffEFF5FC),
                                          padding: EdgeInsets.all(16.0),
                                          alignment: Alignment.centerLeft,
                                          child: Text(
                                            Translate.of(context)
                                                .translate('begin_time'),
                                          ))),
                                  GridColumn(
                                      columnName: 'endTime',
                                      label: Container(
                                          height: 50,
                                          color: Color(0xffEFF5FC),
                                          padding: EdgeInsets.all(16.0),
                                          alignment: Alignment.centerLeft,
                                          child: Text(
                                            Translate.of(context)
                                                .translate('end_time'),
                                          ))),
                                  GridColumn(
                                    columnName: 'createdDepWorker',
                                    label: Container(
                                      height: 50,
                                      color: Color(0xffEFF5FC),
                                      padding: EdgeInsets.all(16.0),
                                      alignment: Alignment.centerLeft,
                                      child: Text(
                                        Translate.of(context)
                                            .translate('created_dep_worker'),
                                      ),
                                    ),
                                  ),
                                  GridColumn(
                                    columnName: 'filters',
                                    label: Expanded(
                                      child: Container(
                                        height: 26,
                                        width: 130,
                                        constraints:
                                            BoxConstraints(maxHeight: 30),
                                        alignment: Alignment.center,
                                        decoration: BoxDecoration(
                                          border: Border.all(
                                              color: Colors.black12, width: 1),
                                          borderRadius: BorderRadius.all(
                                              Radius.circular(4)),
                                        ),
                                        child: DropdownButton(
                                          onChanged: (val) {},
                                          icon: const Icon(
                                              Icons.expand_more_outlined),
                                          underline:
                                              Container(color: Colors.white),
                                          hint: Text(
                                              Translate.of(context)
                                                  .translate("bulk_actions"),
                                              style: TextStyle(fontSize: 12)),
                                          items: [
                                            DropdownMenuItem(
                                              value: 1,
                                              child: Text(
                                                  Translate.of(context)
                                                      .translate('cancel'),
                                                  style:
                                                      TextStyle(fontSize: 12)),
                                            ),
                                            DropdownMenuItem(
                                              value: 2,
                                              child: Text(
                                                  Translate.of(context)
                                                      .translate('sign'),
                                                  style:
                                                      TextStyle(fontSize: 12)),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ),
                                  )
                                ],
                              
                              ),
                            ),
                            Container(
                              height: 60,
                              width: constraints.maxWidth,
                              child: SfDataPager(
                                delegate: taskDataSource,
                                pageCount: taskDataSource.rows.length > 0
                                    ? (taskCount.length / 10).ceilToDouble()
                                    : docDataSource.rows.length / 10,
                                direction: Axis.horizontal,
                              ),
                            )
                          ],
                        ),
                      ],
                    );
                  });
                } else if (state is TaskDocLoading) {
                  return LoadingBox();
                } else {
                  return Text("load failed.");
                }
              },
            ),`
            
            
                            -------Task Data source-----
                   `class TaskDataSource extends DataGridSource {
                          List<Task> paginatedTask = [];
                          final int rowsPerPage = 10;

                              BuildContext contxt;
                              List<int> showCancelSignButtonWhen = [1, 5, 7];
                              List<int> showChangeButtonWhen = [1, 5, 6, 7];
                              int taskStatusId = 0;
                              Task task;
                              TaskDataSource(List<Task> tasksData, context) {
                                tasks = tasksData;
                                contxt = context;
                                if (tasks.length > 0) {
                                  paginatedTask = tasks.getRange(0, rowsPerPage).toList();
                                  buildPaginatedDataGridRows();
                                }
                              }

                              @override
                              Future<bool> handlePageChange(
                                int oldPageIndex,
                                int newPageIndex,
                              ) async {
                                int startIndex = newPageIndex * rowsPerPage;
                                int endIndex = startIndex + rowsPerPage;
                                if (endIndex > this.tasks.length) {
                                  endIndex = this.tasks.length;
                                }
                                paginatedTask = List.from(
                                  this.tasks.getRange(startIndex, endIndex).toList(growable: false),
                                );
                                buildPaginatedDataGridRows();
                                notifyListeners();
                                return true;
                              }
                            
                              List<DataGridRow> _tasks = [];
                              List<Task> tasks = [];
                            
                              @override
                              List<DataGridRow> get rows => _tasks;

                    void buildPaginatedDataGridRows() {
                      _tasks = paginatedTask
                          .map<DataGridRow>(
                            (e) => DataGridRow(
                              cells: [
                                DataGridCell(columnName: 'id', value: e.selected),
                                DataGridCell<String>(columnName: 'title', value: e.title),
                                DataGridCell<String>(
                                    columnName: 'description', value: e.description),
                                DataGridCell<String>(
                                    columnName: 'createdAt',
                                    value: DateFormat('yyyy/MM/dd hh:mm:ss')
                                        .format(DateTime.parse(e.createdAt))
                                        .toString()),
                                DataGridCell<String>(
                                    columnName: 'beginTime',
                                    value: DateFormat('yyyy/MM/dd hh:mm:ss')
                                        .format(DateTime.parse(e.startDate))
                                        .toString()),
                                DataGridCell<String>(
                                    columnName: 'endTime',
                                    value: DateFormat('yyyy/MM/dd hh:mm:ss')
                                        .format(DateTime.parse(e.endDate))
                                        .toString()),
                                DataGridCell<String>(
                                  columnName: 'createdDepWorker',
                                  value:
                                      e.taskCreator.department.name + ", " + e.taskCreator.name,
                                ),
                                DataGridCell(columnName: "filters", value: e)
                              ],
                            ),
                          )
                          .toList(growable: false);
                    }
                  
                    List<int> taskIds = [];
                  
                    @override
                    DataGridRowAdapter buildRow(DataGridRow row) {
                      return DataGridRowAdapter(
                        cells: [
                          Container(
                            alignment: Alignment.center,
                            child: Checkbox(
                              value: row.getCells()[0].value,
                              onChanged: (value) {
                                print(value);
                                int index = _tasks.indexOf(row);
                                if (value == true) {
                                  if (!taskIds.contains(row.getCells()[7].value.id)) {
                                    taskIds.add(row.getCells()[7].value.id);
                                  }
                                }
                  
                                row.getCells()[0] = DataGridCell(value: value, columnName: 'id');
                                notifyDataSourceListeners(
                                    rowColumnIndex: RowColumnIndex(index, 0));
                              },
                            ),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[1].value.toString()),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[2].value),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[3].value.toString()),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[4].value.toString()),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[5].value),
                          ),
                          Container(
                            alignment: Alignment.centerLeft,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Text(row.getCells()[6].value.toString()),
                          ),
                          Container(
                            alignment: Alignment.center,
                            padding: EdgeInsets.symmetric(horizontal: 16),
                            child: Row(
                              children: [
                                if (showCancelSignButtonWhen
                                    .contains(row.getCells()[7].value.taskStatusIdFk))
                                  InkWell(
                                    onTap: () {
                                      _cancelTask([row.getCells()[7].value.id]);
                                    },
                                    child: Icon(
                                      Icons.cancel_presentation,
                                      color: Color(0xff00A4E3),
                                    ),
                                  ),
                                if (showCancelSignButtonWhen
                                    .contains(row.getCells()[7].value.taskStatusIdFk))
                                  SizedBox(width: 10),
                                if (showChangeButtonWhen
                                    .contains(row.getCells()[7].value.taskStatusIdFk))
                                  InkWell(
                                    autofocus: true,
                                    onTap: () {
                                      _updateTask(row.getCells()[7].value);
                                    },
                                    child: Icon(
                                      Icons.edit_outlined,
                                      color: Color(0xff00A4E3),
                                    ),
                                  ),
                                SizedBox(width: 10),
                                if (showCancelSignButtonWhen
                                    .contains(row.getCells()[7].value.taskStatusIdFk))
                                  InkWell(
                                    onTap: () => _signTask([row.getCells()[7].value.id]),
                                    child: Icon(
                                      Icons.check_outlined,
                                      color: Color(0xff00A4E3),
                                    ),
                                  ),
                                if (!showCancelSignButtonWhen
                                        .contains(row.getCells()[7].value.taskStatusIdFk) &&
                                    !showChangeButtonWhen
                                        .contains(row.getCells()[7].value.taskStatusIdFk))
                                  Text(
                                    row.getCells()[7].value.taskStatus.name,
                                    style: TextStyle(
                                        color: Colors.black, fontSize: Sizes.TEXT_SIZE_12),
                                  )
                              ],
                            ),
                          ),
                        ],
                      );
                    }
                  }`

Same  List<Task> list items & Bloc state  we using in other pages too

I think the issue with data pager length

**Comment by RenugaSadagoban98** [comment]
Hi @anishramagiri ,
Thanks for the update. 
 
We have checked your code snippet. You are using two different datagridsources for DataGrid. But, you have not set the respective DataGridSource to SfDataPager like you did for DataGrid based on taskDataSource.rows.length. As a result, you should bind datagridsources to delegate of SfDataPager based on taskDataSource.rows.length. Please refer to the code snippet below. 

```

                Container( 
                          height: 60, 
                          width: constraints.maxWidth, 
                          child: SfDataPager( 
                            delegate: taskDataSource.rows.length > 0 
                                ? taskDataSource: docDataSource, 
                            pageCount: taskDataSource.rows.length > 0 
                                ? (taskCount.length / 10).ceilToDouble() 
                                : docDataSource.rows.length / 10, 
                            direction: Axis.horizontal, 
                          ), 
                        ) 
 
```
Please let us know if you need further assistance.  
 
Regards, 
Renugadevi

**Comment by anishramagiri** [comment]
Hi Renugadevi,

thanks for your code snippet..

but after adding below code

 TaskDataSource(List<Task> tasksData, context, int taskStatusId) {
    try {
      tasks = tasksData;
      contxt = context;
      statusId = taskStatusId;
      if (tasks.length < rowsPerPage) {
        paginatedTask = tasks.toList();
      } else {
        paginatedTask = tasks.getRange(0, rowsPerPage).toList();
      }
      buildPaginatedDataGridRows();
    } catch (e, stackTrace) {
      _completer.completeError(e, stackTrace);
    }
  }

now its working like charm...

**Comment by RenugaSadagoban98** [comment]
Hi @anishramagiri ,

Thanks for the update.

We are glad to know that your reported problem is resolved at your end. Please let us know if you need any other assistance. We will be happy to assist you.

Regards,
Renugadevi
