### ISSUE TITLE
Chart animation not working

### ISSUE THREAD

**Issue by Rifat-Hasan-Rono** [syncfusion/flutter-widgets#377]
If legend build using legendItemBuilder, charts animation stops working

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Rifat-Hasan-Rono,

Greetings from Syncfusion. We have analyzed your scenario at our end, and we would like to let you know that currently, the default animation behavior of our chart widget when legend is enabled in the chart is that the initial rendering animation (Series animation when start of application) will only happen and when the series legend is toggled or untoggled to enable or disable the series visibility, there will be no series animation performed for that series. This is the default behavior of our chart widget. Please revert us if you have further concerns on this.

Regards,
Sriram Kiran
