### ISSUE TITLE
[Syncfusion_flutter_pdfviewer] Search functionality - found phrase are not being highlighted

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-widgets#378]
I am using syncfusion_flutter_pdfviewer package. On searching a phrase, if a phrase comes in two lines (a current line and next line) then that phrase is not highlighted but it does show instance count of the searched phrase. Moreover, if that phrase comes in one line then the occurrences are highlighted.
I am showing a dialog box when no results are found.
@syncfusion

sample pdf: 
[Plumbing Part 2.pdf](https://github.com/syncfusion/flutter-widgets/files/7200670/Plumbing.Part.2.pdf)

video: 

https://user-images.githubusercontent.com/60787872/134123393-58e56340-44b7-4155-bb4b-f409fda80430.mp4

**Comment by Achin-verma** [comment]
Hi, I am facing the same issue. Please, anyone, guide me.

**Comment by deepika134** [comment]
Hi Rithika,

At present we do not have support for find multi line text search in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked using following link, https://www.syncfusion.com/feedback/28864/add-multiline-text-search-support-for-flutter-pdf . 

Regards, 
Deepika R

**Comment by JudithLocke** [comment]
Hey, 

I am too facing this issue, it is finding the search but not highlighting  if over 2 lines. Can you advise when this will be looked into as it makes searching a document very difficult?

**Comment by SharkDevsTom** [comment]
> Hi Rithika,
> 
> At present we do not have support for find multi line text search in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked using following link, https://www.syncfusion.com/feedback/28864/add-multiline-text-search-support-for-flutter-pdf .
> 
> Regards,
> Deepika R

Hey Deepika, 

I too am having this same problem, what confuses me is that currently the library will;

Find the Search 
Highlight if on one line 

surely highlighting over 2 lines as you already have both features would be a very straight fwd task to implement. 

When searching a PDF declaring that the wanted search term must be on one line is not user friendly at all.

I hope the team looks to include this feature soon.

Many Thanks :)

**Comment by Achin-verma** [comment]
Yes, I am also hoping to fix this soon because due to this bug/feature, I am completely stuck with my app and there is no other library, which offers the same functionality.
