### ISSUE TITLE
need call back function when slider on change end 

### ISSUE THREAD

**Issue by Prince4730** [syncfusion/flutter-widgets#383]
Please add call back function for slider on change end , we have call back function for on change , i want to call api when the slider change end .

**Comment by PraveenGopalsamy** [comment]
Hi Prince4730,  
   
Greetings from Syncfusion support.    
  
We have checked your query, though this requirement is not possible using the [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/SfSlider.html) or [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html) widgets, could you please check the below behavior of our [SfRangeSelector](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/SfRangeSelector.html) widget may be suitable for you?    
  
You may restrict the call to the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/onChanged.html) callback while thumbs are being dragged continuously using [SfRangeSelector.enableDeferredUpdate](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/enableDeferredUpdate.html) property. The delay in the update can be achieved by setting the [SfRangeSelector.deferredUpdateDelay](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/deferredUpdateDelay.html) property. The default value of the deferredUpdateDelay property is 500 milliseconds.   
 
It will invoke the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSelector/onChanged.html) callback when the thumb is dragged and held for the duration specified in the deferredUpdateDelay. However, thumb values are immediately updated in touch up action.     
   
  ```
import 'package:flutter/material.dart'; 
  import 'package:flutter/rendering.dart'; 
  import 'package:intl/intl.dart' show DateFormat; 
  import 'package:syncfusion_flutter_sliders/sliders.dart'; 
   
  class RangeSelectorPage extends StatefulWidget { 
  @override 
  _RangeSelectorPageState createState() => _RangeSelectorPageState(); 
} 
   
  class _RangeSelectorPageState extends State<RangeSelectorPage> { 
  final DateTime _min = DateTime(2010, 01, 01, 0), 
      _max = DateTime(2015, 01, 01); 
  final SfRangeValues _initialValues = 
      SfRangeValues(DateTime(2012, 01, 01, 0), DateTime(2013, 01, 01, 0)); 
   
  @override 
  Widget build(BuildContext context) { 
    return Scaffold( 
      appBar: AppBar(title: Text('Deferred update')), 
      body: Container( 
        padding: const EdgeInsets.only(top: 30), 
        width: 400, 
        child: SfRangeSelector( 
          min: _min, 
          max: _max, 
          initialValues: _initialValues, 
          interval: 1, 
          enableDeferredUpdate: true, 
          deferredUpdateDelay: 500, 
          dateIntervalType: DateIntervalType.years, 
          dateFormat: DateFormat.y(), 
          showTicks: true, 
          showLabels: true, 
          onChanged: (SfRangeValues values) {}, 
          child: SizedBox(), 
        ), 
      ), 
    ); 
  } 
}  
```
     
   
**UG link:** [https://help.syncfusion.com/flutter/range-selector/range-controller#deferred-update](https://help.syncfusion.com/flutter/range-selector/range-controller#deferred-update)    
  
Kindly check whether able to fulfil your requirement with the above code snippet. If your requirement is different from the above, kindly provide brief details about your requirement.   

Please let us know if you need any further assistance in this. 

Regards,
Praveen G.

**Comment by Prince4730** [comment]
my code , i want to call api when the slider end sliding , i have tried with above , i am not able to achieve what i want 

```
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:smart_home/src/utility/k_colors.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';

class BoastSlider extends StatefulWidget {
  BoastSlider(
      {this.activeLabelStyle,
      this.boostValue,
      this.onChanged,
      this.tooltipTextStyle});
  double boostValue;
  TextStyle tooltipTextStyle;
  TextStyle activeLabelStyle;

  ValueChanged<dynamic> onChanged;

  @override
  _BoastSliderState createState() => _BoastSliderState();
}

class _BoastSliderState extends State<BoastSlider> {
  @override
  Widget build(BuildContext context) {
    return SfSliderTheme(
      data: SfSliderThemeData(
          tooltipBackgroundColor: K_Colors().kWhite,
          inactiveTickColor: K_Colors().kWhite,
          activeTickColor: K_Colors().kWhite,
          tooltipTextStyle: widget.tooltipTextStyle,
          activeLabelStyle: widget.activeLabelStyle,
          inactiveLabelStyle: widget.activeLabelStyle),
      child: SfSlider(
        tooltipShape: SfPaddleTooltipShape(),
        // onChangeEnd: (double newValue) {
        //   print('Ended change on $newValue');
        // }

        min: 1,
        max: 9,
        value: widget.boostValue,
        showDividers: true,
        interval: 1.0,
        showTicks: true,
        showLabels: true,

        stepSize: 1,
        thumbIcon: Container(
          decoration: const BoxDecoration(
            color: Colors.white,
            shape: BoxShape.circle,
          ),
        ),
        enableTooltip: true,

        activeColor: Colors.white,

        inactiveColor: Colors.white,
        numberFormat:
            NumberFormat.currency(locale: "eu", symbol: "H", decimalDigits: 0),

        // onChanged: (dynamic value) {
        //   setState(() {
        //     print(_value);
        //     _value = value as double;
        //   });
        onChanged: widget.onChanged,
      ),
    );
  }
}

```

**Comment by chamartt** [comment]
Could be great to have onChangedEnd on this package !
The last thing missing to be perfect.

I have this error when I using sliders with your workaround @PraveenGopalsamy :
`'package:flutter/src/rendering/object.dart': Failed assertion: line 2383 pos 12: 'attached': is not true.`

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Prince4730, 

We have considered your request as a feature and the status can be tracked from the feedback portal link.    

**Feedback:** https://www.syncfusion.com/feedback/26154/add-onchangestart-onchangeend-properties  

We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our future releases. If you have any more specification/suggestions to the feature request, you can add it as a comment in the feedback portal with the above link.   

Regards, 
Lakshmi R.
