### ISSUE TITLE
[syncfusion_flutter_signaturepad] Set the starting image

### ISSUE THREAD

**Issue by mtc-jed** [syncfusion/flutter-widgets#389]
Hi,

Is there a way to set the starting image of the signaturepad ?

Thanks

**Comment by LakshmiRadhaKrishnan** [comment]
Hi mtc-jed,

Greetings from Syncfusion support.

At present, there is no direct API for setting an image in the SfSignaturePad. However, you can show an image in the signature pad by using Stack widget to place the SfSignaturepad widget on top of the Image widget. The SfSignaturePad is transparent by default.

**Code Snippet:**
```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: Center(
      child: Stack(
        children: [
          Image.asset('assets/background_image.png'),
          const SizedBox(
            height: 300,
            width: 300,
            child: SfSignaturePad(),
          ),
        ],
      ),
    ),
  );
}
```

**SignaturePad with image:**
![image](https://user-images.githubusercontent.com/47354659/135240559-7f41a93b-641c-42a9-a6d3-0f61f51f500b.png)

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/image_at_signature_pad1619496418 
 
We hope that the above solution will fulfill your requirement. Please let us know if your requirement is different from this.

Regards,
Lakshmi R.
