### ISSUE TITLE
Trackball show method issue

### ISSUE THREAD

**Issue by HemangHLink** [syncfusion/flutter-widgets#390]
As per document we have activation mode none and using show method we make trackball visible

Reference:
https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair
none - Hides the visibility of trackball when setting activation mode to none. It will be activated when calling the show method.

But this seems not working as expected:
Snip for 
Init trackball:

_trackballBehavior = TrackballBehavior(
      enable: true,
      lineColor: Color(0xFF00A5DB),
      shouldAlwaysShow: true,
      tooltipAlignment: ChartAlignment.center,
      tooltipDisplayMode: TrackballDisplayMode.floatAllPoints,
      tooltipSettings: const InteractiveTooltip(
        enable: true,
        canShowMarker: false,
      ),
      markerSettings: const TrackballMarkerSettings(
          height: 10,
          width: 10,
          shape: DataMarkerType.image,
          markerVisibility: TrackballVisibilityMode.visible,
          image: AssetImage('assets/images/current_point.png')),
      activationMode: ActivationMode.none,
    );

Show track ball
_trackballBehavior?.show(
            marginRight, MediaQuery.of(context).size.width - 100, "pixel");
            
Link with Chart
trackballBehavior: _trackballBehavior,

Show method is only working when activation mode is not set to none,
If we use any other mode it moves from it actual position to user interaction point which is not required in my case

version used:
syncfusion_flutter_charts: ^19.2.62

**Comment by SriramKiranSenthilkumar** [comment]
Hi @HemangHLink,

Greetings from Syncfusion. We have analyzed your scenario at our end, and we are able to replicate the reported behavior regarding the trackball show public method not working when the activation mode is set to none. We will change this behavior as per our documentation and will include the changes in our upcoming weekly patch release which is expected to be rolled out by second week of October. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran
