### ISSUE TITLE
[syncfusion_flutter_pdf] Drawing multiple images on pdf doesn't work on iOS 15

### ISSUE THREAD

**Issue by jplekkerkerker** [syncfusion/flutter-widgets#391]
We have multiple PDF's with formfields where we draw an signature image on the PDF. This used to work both on Android and iOS, but since iOS 15 this isn't working any more. On iOS it shows the first image (and the last image) it draws on all the locations we draw additional images.

An minimal code example of what we use to draw the image within bounds :
```
Future<List<int>?> generatePDF() async {

    PdfDocument document = PdfDocument();

    PdfPage page = document.pages.add();

    double top = 10;
    double left = 10;
    double width = 100;
    double height = 50;
    for(String value in images.values) {
      Rect bounds = Rect.fromLTWH(left, top, width, height);
      drawImageOnPage(page, value, bounds);
      top += height + 10;
    }

    document.form.flattenAllFields();
    List<int> bytes = document.save();
    //Dispose the document.
    document.dispose();

    return bytes;
  }

  void drawImageOnPage(PdfPage? page, String value, Rect bounds) {

    if (page != null) {
      Uint8List image = base64Decode(value.replaceAll('data:image/png;base64,', ''));
      PdfBitmap pdfImage = PdfBitmap(image);
      late Rect imageBounds;

      if (pdfImage.width >= bounds.width) {
        double imageWidth = bounds.width;
        double imageHeight = pdfImage.height / (pdfImage.width / imageWidth);
        double y = bounds.top + (bounds.height / 2) - (imageHeight / 2);
        imageBounds = Rect.fromLTWH(bounds.left, y, imageWidth, imageHeight);
      }
      if (imageBounds.bottom > bounds.bottom) {
        double imageHeight = bounds.height - 1;
        double imageWidth = pdfImage.width / (pdfImage.height/imageHeight);
        double x = imageBounds.left + (imageBounds.width / 2) - (imageWidth / 2);
        imageBounds = Rect.fromLTWH(x, bounds.top, imageWidth, imageHeight);
      }
      page.graphics.drawImage(
        pdfImage,
        imageBounds,
      );
    }

  }
  
  //removed the images itself for the overview
  final Map<String, String> images = {
    'one': '',
    'two': '',
    'three': '',
    'four': '',
    'five': '',
  }
```
I added 5 images, numbered 1 to 5. On iOS this code produces a pdf with 5 images, the first 4 image display image 1, the last one shows the 5th image, as shown in the PDFs:

Android PDF: https://drive.google.com/file/d/1XepbgDPHlCCyhUkQPkRbx4yt5RSyQOX4/view?usp=sharing
iOS PDF: https://drive.google.com/file/d/1SIj0_fMhmWuY5NjKGYtr7qK4TifaRKrf/view?usp=sharing

Is this a bug in the library or is this something we can fix in our code?

_Edit: simplified the example_

**Comment by chinnumuniyappan** [comment]
Hi @jplekkerkerker,

Greetings from Syncfusion,

We have tried to replicate the issue on our end but it is working as expected, We have attached the sample which we tried to reproduce on our end for your reference.

[pdf_sample.zip](https://github.com/syncfusion/flutter-widgets/files/7278126/pdf_sample.zip)

Kindly try this sample on your end and let us know the details. If still, you are facing the same issue we request you to share the following details to proceed further.

1. Modified sample to reproduce the issue.
2. Flutter doctor details
3. iOS SDK version details.

Regards,  
Chinnu M
