### ISSUE TITLE
syncfusion_flutter_datagrid 

### ISSUE THREAD

**Issue by B0ringM4n** [syncfusion/flutter-widgets#392]
buttons first, last in SfDataPager could be optional buttons, please

**Comment by RenugaSadagoban98** [comment]
Hi @B0ringM4n , 

Greetings from syncfusion.  

We have already considered your request as a feature. This feature will be implemented in our 2021 Volume 3 release which is expected to be rolled out on end of September 2021. We will let you know once this feature is rolled out. You can follow up with the following feedback for further follow up,  

Feedback link: https://www.syncfusion.com/feedback/25938/support-to-change-the-size-and-visibility-of-the-page-buttons-in-sfdatapager

Regards,
Renugadevi

**Comment by RenugaSadagoban98** [comment]
Hi @B0ringM4n ,

Thanks for your patience.

 We are glad to announce that our Essential Studio 2021 Volume 3 Main Release V19.3.0.43 is rolled out and is available for download under the following link.
 
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download

Refer the following UG document for hide the navigation page button,
**UG link:** https://help.syncfusion.com/flutter/datagrid/paging#hide-certain-navigation-page-items

 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.
 
Regards,
Renugadevi
