### ISSUE TITLE
SfDataGrid.onCellLongPress is triggered only when keyup instead of a timeout

### ISSUE THREAD

**Issue by takifouhal** [syncfusion/flutter-widgets#393]
a long press means that there is time constraint, when elapsed the callback should be triggered ,
what is happening now is , the callback get triggered only when the user releases (finger/mouse) .

**Comment by RenugaSadagoban98** [comment]
Hi @takifouhal , 

Greetings from syncfusion.  

Currently, we have triggered the onCellLongPress callback in DataGrid when we release the pointer. Our intention is that customer should listen the long press and do the required things when releasing the pointer. Now, we have considered your request as an enhancement. This enhancement will be implemented in our 2021 Volume 3 SP release which is expected to be rolled out on mid of November 2021.  You can follow up with the below feedback for further follow up, 



**Feedback link:** https://www.syncfusion.com/feedback/29092/change-the-behavior-of-the-oncelllongpress-callback

Regards,
Renugadevi

**Comment by Sangeetha-Raju** [comment]
Hi @takifouhal, 
 
We are glad to announce that our Essential Studio 2021 Volume 3 Service Pack Release V19.3.0.53 is rolled out and is available for download under the following link. 
 
https://www.syncfusion.com/forums/170353/essential-studio-2021-volume-3-service-pack-release-v19-3-0-53-is-available-for-download 
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 
 
Regards, 
Sangeetha Raju.
