### ISSUE TITLE
[syncfusion_flutter_charts] movingAverage Trendline inaccurate

### ISSUE THREAD

**Issue by christianreiser** [syncfusion/flutter-widgets#397]
It looks like the moving average trendline can only be at integer values. Would it be possible to change it to decimal values? 
![image](https://user-images.githubusercontent.com/22785164/135577512-9fda80b4-e145-4507-980f-d5150895c673.png)

Note that, blue dots/line are datapoints and green/teal is the trendline. In the red circle it is inaccurate.

The code generting the above image is at https://github.com/christianreiser/InsightMe/blob/420d96fa19132f6993ded8a5603385ec436b1a8d/lib/Core/widgets/chart.dart#L144

**Comment by dharanidharandharmasivam** [comment]
Hi @christianreiser ,

The reported scenario is working fine as per your expectation with the latest version of the chart. Can you please update to the latest version from below?

https://pub.dev/packages/syncfusion_flutter_charts/versions/19.3.44+1 

Thanks,
Dharani.

**Comment by christianreiser** [comment]
thanks and sorry for the inconvenience!
