### ISSUE TITLE
DateTimeAxis X Axis 

### ISSUE THREAD

**Issue by klkucaj** [syncfusion/flutter-widgets#404]
Hi!

It's possible to have the Date value between the vertical lines and not under them??
I tried everything i still i did not find a way to put the date between lines.
Please let me know if there is a way to do it ??!

Thank you!

![image](https://user-images.githubusercontent.com/78809795/136227861-c63058f2-0993-40a9-b66b-acb477a4d2dd.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @klkucaj,

We have analyzed your scenario at our end and we would like to let you know regarding the behavior of **DateTimeCategoryAxis** feature available in chart widget. The **DateTimeCategoryAxis** is a combination of both **CategoryAxis** and **DateTimeAxis** that is it can be used to display date-time values with non-linear intervals. For example, if there are 5 data points with date-time values as x-values then the **DateTimeCategoryAxis** will be generated only for those 5 date-time values in the chart non-linearly whereas in **DateTimeAxis**, the axis values are calculated linearly according to the provided date-time x-values in the data source. This is the default behavior. So, in your case, if you want the LineSeries data point to the end of the month you must have to use the linear **DateTimeAxis** and change the date-time x-value of the line series data points as per required but your previous requirement regarding to place the axis labels between the ticks can be achieved with **DateTimeAxis**. And so, with **DateTimeCategoryAxis**, the LineSeries marker data points cannot be shifted. Please get back to us if you have further concerns.

Regards,
Sriram Kiran
