### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Clear Text Selection call Navigator.of(context).maybePop()

### ISSUE THREAD

**Issue by tlueder** [syncfusion/flutter-widgets#409]
Hi,

The clear text selection calls Navigator.of(context).maybePop(); which messes up my app routing.

**Comment by tlueder** [comment]
Hi,

But why does clearing the selection changes the app route when making a selection does not?

1. Route is set to file list
2. User taps a file and route is set to file view
3. User selects something
4. Clear selection is called for whatever reason 

User end up in file list

**Comment by deepika134** [comment]
Hi tluder,

We tried to reproduce the reported issue with the provided details but the clear selection is working properly. We have prepared a sample as per your requirement which can be downloaded from the following link, https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample2114319691.zip  
If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika R
