### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Text Selection callback is fired to often

### ISSUE THREAD

**Issue by tlueder** [syncfusion/flutter-widgets#410]
Hi,

The call back onTextSelectionChanged is fires to many times.

Steps to reproduce:

Use the example app enable text selection

Add
          onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
            print(details.selectedText);
          },

Start the app
select something and click somewhere else for cancel the selection

expected behavior:

onTextSelectionChanged is call once and the print is null

actual behavior:

onTextSelectionChanged is called 4 times

I/flutter (15261): null
I/flutter (15261): null
I/flutter (15261): New
I/flutter (15261): null

which leads to removing and building and removing of the context menu.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 11.6 20G165 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.0)
[✓] Connected device (3 available)

• No issues found!

App is build on
Pixel 5 (mobile) • android-arm64  • Android 11 (API 30)

**Comment by tlueder** [comment]
I'm sorry,

But this answer makes no sense in the context of this issue.

I was not talking about dragging the handle.

1. select some text.
2. tap anywhere on the screen to clear, not change, the selection.

expected behavior:

The selection and the copy button should disappear

actual behavior:

The selection and the copy button disappears and gets repainted and disappear again.
aka both are blinking on the screen.


How is this related to dragging the selection handle?

**Comment by deepika134** [comment]
Hi tluder,

We tried to reproduce the reported issue with provided details, but the text selection and context menu removal is working properly without any blinking in the screen. We have prepared a sample for your reference and attached the output screen record of sample which can be downloaded in the following link, https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample1161456580.zip  
If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

You can also contact us through our [support forums](https://www.syncfusion.com/forums ), [Direct-Trac](https://www.syncfusion.com/support/directtrac ), or [feedback portal]( https://www.syncfusion.com/feedback/flutter ).

Regards,
Deepika R
