### ISSUE TITLE
How i can convert xls to pdf?

### ISSUE THREAD

**Issue by Hopheylalal** [syncfusion/flutter-widgets#414]
Hello friends. How i can convert xls to pdf? And how i can get total pages count of uploaded xls doument ?

**Comment by KeerthiHari** [comment]
Syncfusion Flutter XlsIO do not have support for Excel to PDF conversion. We have logged a feature report for this but do not have any plans to implement this feature. You can track the status of the defect report through the following feedback link. 

https://www.syncfusion.com/feedback/26954/convert-excel-documents-to-pdf-in-flutter-xlsio  

Also, we get the page count from PDF document (after Excel to PDF conversion). As there is no support for Excel to PDF conversion, it is not possible to get the page count as well. 

Kindly let us know if you need any further assistance. 

Regards, 
Keerthi.
