### ISSUE TITLE
[syncfusion_flutter_pdfviewer] [UseCase] pdfTextSearchResult.clear() throws exception if used in dispose()

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#415]
### Minimal Example
```dart
class PdfViewer extends StatefulWidget {
  const PdfViewer({
    Key? key,
  }) : super(key: key);

  @override
  PdfViewerState createState() => PdfViewerState();
}

class PdfViewerState extends State<PdfViewer> {
  final PdfViewerController _pdfViewerController = PdfViewerController();

  PdfTextSearchResult _pdfTextSearchResult = PdfTextSearchResult();

  @override
  void dispose() {
    _pdfTextSearchResult.clear();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SfPdfViewer.file(
      filePath,
      controller: _pdfViewerController,
      onDocumentLoaded: _onDocumentLoaded,
    );
  }

  void _onDocumentLoaded(PdfDocumentLoadedDetails details) async {
    _pdfTextSearchResult = await _pdfViewerController.searchText('String to Search', searchOption: TextSearchOption.caseSensitive);
  }
}

```

### Query 1

- Is it necessary to call `pdfTextSearchResults.clear()` before removing  PdfViewer widget from widget tree ?
- If search results are there and if `pdfTextSearchResults.clear()` called in `dispose()` then it throws below exception
```
#0      State.setState.<anonymous closure>                                        package:flutter/…/widgets/framework.dart:1052
#1      State.setState                                                            package:flutter/…/widgets/framework.dart:1087
#2      SfPdfViewerState._handleTextSearch                                        package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2659
#3      _ValueChangeNotifier.notifyPropertyChangedListeners                       package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3655
#4      PdfTextSearchResult.clear                                                 package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3634
```

### Query 2
- Some search is started by calling `_pdfViewerController.searchText('String to Search')`. Now controller is finding the instances but the PdfViewer widget is removed from the widget tree before search completes. My question is - Is it necessary to cancel the ongoing search by calling `pdfTextSearchResults.clear()` before removing the PdfViewer widget ?

Regards
Sagar

**Comment by deepika134** [comment]
Hi Sagardani,

Query 1: Is it necessary to call pdfTextSearchResults.clear() before removing PdfViewer widget from widget tree?

Answer: It is not necessary to call pdfTextSearchResults.clear() before removing PdfViewer widget from widget tree.

Query 2: Some search is started by calling _pdfViewerController.searchText('String to Search'). Now controller is finding the instances but the PdfViewer widget is removed from the widget tree before search completes. My question is - Is it necessary to cancel the ongoing search by calling pdfTextSearchResults.clear() before removing the PdfViewer widget?

Answer: It is not necessary to call pdfTextSearchResults.clear() to stop the ongoing search before removing the PdfViewer widget from the widget tree. When the PdfViewer widget is removed from the widget tree, the ongoing search is canceled without executing pdfTextSearchResults.clear().

Regards,
Deepika R
