### ISSUE TITLE
pdf viewer: library crashes with large pdf documents

### ISSUE THREAD

**Issue by thomas-topway-it** [syncfusion/flutter-widgets#419]
hello, the library appears in general to be really fine,
however it crashes with large pdf documents, like the following:

https://s3.documentcloud.org/documents/21055989/understanding-risk-bat-coronavirus-emergence-grant-notice.pdf

(I have another example of a smaller pdf document, about 50mb with non rasterized text inside which crashes as well, both files are taken from the device storage) (device: android 5.0.2 1gb ram)

Also, the opening of the first page on android is significantly slower than a library like mupdf, although, if I understand correctly, syncfusion pdf viewer handles natively (without dependencies ??!) pdf in dart.
(Thomas)

**Comment by thomas-topway-it** [comment]
Hello, 
after analyzing further the library, I have found out that on Android  it relies 
on PdfRenderer introduced by Lollipop.
PdfRenderer in turn relies on Pdfium as far as I know.
I think for a professional and/or production ready use of the library the following steps could be done:
1) include pdfium as a dependency, for instance using this repository 
https://github.com/barteksc/PdfiumAndroid
or this one
https://github.com/paulo-coutinho/pdfium-lib
2) include mupdf as a dependency (this solution seems more interesting, even if the developer or company has to manage two different licenses)
3) include as a dependency any other library either open-source or owned by syncfusion. This could also be a modified version of Pdfium to prevent out of memory issues and the correct handling of complex PDFs or PDFs non supported by Pdfium.

**Comment by deepika134** [comment]
Hi Thomas,

We are analyzing the feasibility of the requested enhancement and will update the further details by October 21, 2021.

Regards,
Deepika R.

**Comment by dillibabu1802** [comment]
Hi @rickydj 

As mentioned earlier, we will let you know once the feature is completed.

Regards,
Dilli babu.
