### ISSUE TITLE
[syncfusion_flutter_pdfviewer][Android]The same pdf file was showed blur in Android while clear in iOS

### ISSUE THREAD

**Issue by TennisAndy** [syncfusion/flutter-widgets#421]
Hi, I use syncfusion_flutter_pdfviewer ^19.2.62-beta to show a normal pdf, and place it in "assets/pdf/4dkankan_minion_manual_cn.pdf", you can download from: [link](http://4dkankan.oss-cn-shenzhen.aliyuncs.com/apps/pdf/manual/4dkankan_minion_manual_cn.pdf)

Here is the pdf viewer page, pass the file path: "assets/pdf/4dkankan_minion_manual_cn.pdf"

`import 'package:flutter/material.dart';
import 'package:flutter_module_eight_eye/page/abstract_camera_state.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class CameraPdfViewer extends StatefulWidget {
  String _fileName = "";
  String _filePath = "";

  CameraPdfViewer(this._fileName, this._filePath);

  @override
  State<StatefulWidget> createState() => CameraPdfViewerState();
}

class CameraPdfViewerState extends AbstractCameraState<CameraPdfViewer> {

  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();

  @override
  void initState() {
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          leading: Builder(builder: (BuildContext context) {
            return IconButton(onPressed: (){
              Navigator.pop(context);
            }, icon: Icon(
              Icons.arrow_back_ios_rounded,
              size: 18,
            ));
          },),
          title: Text((widget as CameraPdfViewer)._fileName),
          centerTitle: true,
          // actions: <Widget>[
          //   IconButton(
          //     icon: Icon(
          //       Icons. bookmark,
          //       color: Colors.white,
          //     ),
          //     onPressed: () {
          //       _pdfViewerKey.currentState?.openBookmarkView();
          //     },
          //   ),
          // ],
        ),
        body: Container(
            color: Colors.black,
            child: SfPdfViewer.asset((widget as CameraPdfViewer)._filePath, key: _pdfViewerKey,
                canShowPaginationDialog: false,
                enableDoubleTapZooming: false,
                enableTextSelection: true)
        ));
  }
}
`
As a result: 
Running in android:
![image](https://user-images.githubusercontent.com/9261741/137237409-390154ac-fc97-4a41-a67d-a07ed9a43d17.png)
![image](https://user-images.githubusercontent.com/9261741/137238301-a5671f28-3ba5-41df-9ea2-4ed3a376bb5e.png)

Running in iOS:
![微信图片_20211014100553](https://user-images.githubusercontent.com/9261741/137238478-bd01c181-2815-4a86-a5e1-d44b05a754d4.png)
![微信图片_20211014100603](https://user-images.githubusercontent.com/9261741/137238460-c96a307f-8339-4fb2-8a34-80ff405b3abb.png)

 You can see the display in Android seems to be compressed while iOS is orient.

Here is my dev env:

[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19042.1165], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.54.3)
[√] Connected device (3 available)

**Comment by TennisAndy** [comment]
I have already cofigure in build.gradle both in app and Flutter module
    aaptOptions {
        noCompress ".svg", ".pdf"
    }
But still the same blur.

**Comment by deepika134** [comment]
Hi TennisAndy, 
 
Sorry for the inconvenience. We have planned our volume 3 SP release this week. So, we do not have a weekly NuGet release this week. However, we will include this fix in the upcoming weekly release on November 10, 2021. 
 
Regards, 
Deepika R

**Comment by dillibabu1802** [comment]
Hi @TennisAndy,

The reported issue has been resolved and included in our latest package - [https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.54-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.54-beta). Kindly test this package and let us know whether the issue is resolved at your end.

Regards,
Dilli babu.

**Comment by dillibabu1802** [comment]
Hi @vovaklh20012,

We tried to reproduce the reported issue in iOS but the PDF pages were displayed properly. Kindly share us the issue reproducing PDF document which will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Dilli babu.

**Comment by TennisAndy** [comment]
Hi @dillibabu1802,

I have updated to 19.3.54-beta and this issue cannot be reproduced.
Thank you and your team for fixing it!
Close this issue now.
