### ISSUE TITLE
SfDataGrid: allow multiple row selection when SHIFT key is held

### ISSUE THREAD

**Issue by josh-burton** [syncfusion/flutter-widgets#429]
Quite a standard behaviour when selecting rows is to select a row, press and hold SHIFT, and select another row. All rows in between the first and last should be selected.

Currently when in selection mode `multiple`, only single rows are selected and SHIFT has no effect.

**Comment by Sangeetha-Raju** [comment]
Hi @josh-burton,

We are glad to announce that your requested selection behavior was included in our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download

Now, you can select in-between multiple rows by press and hold the SHIFT key and select another rows. 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards, 
Sangeetha Raju.
