### ISSUE TITLE
SfDataGrid RowSelectionManager too restrictive

### ISSUE THREAD

**Issue by josh-burton** [syncfusion/flutter-widgets#430]
SfDataGrid allows defining a custom RowSelectionManager to handle selection, but there is very little that can be done in this class, because most methods and fields are private.

In order to be able to inspect and change the current selection state, these methods and fields should be made public:
- _dataGridStateDetails
- _applySelection
- _addSelection
- _removeSelection
- _clearSelectedRow

**Comment by Sangeetha-Raju** [comment]
Hi Josh Burton,

As per request in our previous update, please share some more details about your exact use case. Based on your details, we will check and decide about what are the methods and APIs should be exposed in RowSelectionManager. Also, it will be helpful for us to understand your requirement properly and provide the appropriate solution at our end.

Regards,
Sangeetha Raju.

**Comment by josh-burton** [comment]
Hi, the usecase is to detect when a certain key combination has been pressed, and if a user taps on a row while that combination is 'down', to select a certain number of rows.

I came across these restrictions because I was trying to implement my own version of holding SHIFT to select from row 1 to 10. 

If these fields and methods weren't private, I could implement that functionality myself, but because they are I am unable to inspect the previously selected item, or to programmatically select other items when the user taps an item.
