### ISSUE TITLE
[syncfusion_flutter_charts]-[on-demand loading]-[ChartSwipeDirection] count 2 times with one swipe

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#435]
sample code below to reproduce the bug is based on:

[https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/chart/cartesian_charts/infinite_scrolling.dart]()

```
 class _InfiniteScrollingState extends SampleViewState {
    ...
  _InfiniteScrollingState();
  int swipeCounter = 0; // added code
    ...

  Widget getloadMoreIndicatorBuilder(BuildContext context, ChartSwipeDirection direction) {
    if (direction == ChartSwipeDirection.end) {
      swipeCounter++; // added code
      print('${DateTime.now()} swipeCounter $swipeCounter times'); // added code
      isNeedToUpdateView = true;
      globalKey = GlobalKey<State>();
      return StatefulBuilder(
      ...
```

with one swipe, terminal reads: 
```
Restarted application in 1,677ms.
flutter: 2021-10-22 03:08:52.543338 swipeCounter 1 times
flutter: 2021-10-22 03:08:52.563442 swipeCounter 2 times
```

This is extremely annoying when `getloadMoreIndicatorBuilder` triggers API call 2 times thus messing up the `datasoure` list.

If I swipe by the mouse on the simulator very very very carefully and precisely, I have a 30% chance to trigger it only one time as expected.
If I swipe by a finger on a physical iPhone, there's no way I can do it right.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL 

We are analyzing on the reported scenario and we will update you the status in 4 business days. We regret for the inconvenience.

Regards,
Yuvaraj.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @FisherWL,

The reported issue regarding the onDemandLoading indicator(**loadMoreIndicatorBuilder**) is firing twice when swiping is performed in the chart to load the data points on demand is already fixed at our end and the changes will be included in our upcoming weekly patch release which is expected to be rolled out by middle of next week(30 Nov 2021). We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran
