### ISSUE TITLE
[syncfusion_flutter_charts] real-time performance for large data sets

### ISSUE THREAD

**Issue by smofe** [syncfusion/flutter-widgets#437]
I am currently working on a project where I have to display sensor data in real time. I have a line chart which should show this data, allow interaction (zooming, panning) while not crippling the performance of the app.

To test the performance of the charts, I made a sample project which roughly works the following way:

- I use a SfCartesianChart with a FastLineSeries 
- Every 30ms a new data point is added to the data list. I call `updateDataSource` to add the new data point to the series. 

As long as the data list is relatively small (100s of points), the performance is alright. Once the data list grows to a few thousand items of length, performance drops heavily (10-15fps max) - even when the visible interval is just a few hundred data points. 
Now, I could always remove the older data points that are not shown from the data list, therefore limiting it's size and improving performance significantly. However, I want to be able to view all the previous data points by panning the chart, so I need to keep all the old data. 

Am I missing something obvious here, or are the syncfusion charts simply not made for this use case and unable to provide adequate performance? Any help is very appreciated!

Performance was tested on both Android and Windows and in profile mode.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Smofe,

Greetings from Syncfusion. We have analyzed your query, and we would recommend you to use on-demand loading feature. Here you can have required data alone in the viewport and required data can be loaded if necessary. Using the loadMoreIndicatorBuilder, you can show a widget for example a loading indicator. To know more on this, find the user guide and sample below.

User guide: https://help.syncfusion.com/flutter/cartesian-charts/on-demand-loading

Sample: https://flutter.syncfusion.com/#/cartesian-charts/infinite-scrolling

API reference: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/loadMoreIndicatorBuilder.html

And we are continuously working on improving and optimizing the performance of our chart widget at our end and will roll them out in of our upcoming main releases.   

Regards,

Yuvaraj.
