### ISSUE TITLE
syncfusion_flutter_datagrid cell textAligment

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#44]
I have seen when we showing data cell 
cellStyle: DataGridCellStyle(
              textStyle: TextStyle(fontSize: 10,),)
aligment of Text is missing please add Text Aligment its by default aligment left is showing

center, right etc is not showing just pass aligment params inside DataGridCellStyle() constructor

**Comment by NeelakandanKannan** [comment]
Hi @waqaryounusjatt788,

Thanks for contacting Syncfusion support.

We have provided the appearance oriented APIs in DataGridCellStyle class. We have provided the alignment, padding, and all other formatting related APIs in GridColumn itself. Please find the below code snippet and UG documentation to achieve your requirement,

https://help.syncfusion.com/flutter/datagrid/column-types#set-alignment-for-column

`
@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfDataGrid(
      source: _employeeDataSource,
      columns: [
        GridNumericColumn(mappingName: 'id', headerText: 'ID')
          **..textAlignment = Alignment.center
          ..headerTextAlignment = Alignment.center,**
        GridTextColumn(mappingName: 'name', headerText: 'Name'),
        GridTextColumn(mappingName: 'designation', headerText: 'Designation'),
        GridNumericColumn(mappingName: 'salary', headerText: 'Salary')
      ],
    ),
  );
}
`

**Comment by waqaryounusjatt788** [comment]
cellStyle: DataGridCellStyle(
             textStyle: TextStyle(fontSize: 10,),
              backgroundColor: Colors.white),
please provide here for cell **alignment**...

your above mentioned code works only works for header column not for  below cells

**Comment by waqaryounusjatt788** [comment]
Thanks @NeelakandanKannan
