### ISSUE TITLE
DataGrid when Sort not update Row Background

### ISSUE THREAD

**Issue by JesusMayuri7** [syncfusion/flutter-widgets#440]
![image](https://user-images.githubusercontent.com/13004243/139349439-ec455f18-9fc4-4960-bb69-6f2e94b39b89.png)

![image](https://user-images.githubusercontent.com/13004243/139349566-b63db373-6bdf-4b05-b7a8-74a7f4ee10d3.png)

After click Column Sort

![image](https://user-images.githubusercontent.com/13004243/139349612-ed1f83dd-a4d2-47a8-bda7-60a880ac1a7f.png)

How update Row background ??

**Comment by JesusMayuri7** [comment]
Resolved, thank's

**Comment by Sangeetha-Raju** [comment]
Hi JesusMayuri7, 
 
Thank you for the update. 
 
We are glad that the provided response meets your requirement. Please let us know if you need further assistance. As always, we are happy to help you out. 
 
Regards, 
Sangeetha Raju.
