### ISSUE TITLE
syncfusion_flutter_charts: when axis "isInversed" is true, the tooltips don't show

### ISSUE THREAD

**Issue by tapeo** [syncfusion/flutter-widgets#443]

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @tapeo,

Greetings from Syncfusion. We have analyzed your query, and we are tried to reproduce the reported issue, but it is not reproduced at our end. We have also checked with both the x and y-axis inversed and the tooltip is working properly. We have attached the sample which is used in the test phase for your reference.

Sample: [github_443.zip](https://github.com/syncfusion/flutter-widgets/files/7463301/github_443.zip)

Kindly try to reproduce the reported issue in the attached sample, this will be helpful in providing the solution sooner.

Regards,
Yuvaraj.

**Comment by tapeo** [comment]
Hi thank you very much for your support. Checked out your sample and find out my chart had TrackballBehavior bad configured.

Thanks again.
