### ISSUE TITLE
SfCartesianChart initial position

### ISSUE THREAD

**Issue by konstantsoftware** [syncfusion/flutter-widgets#449]
Hey there!

I would like to change the initial position of the graph to start at the end index (furthest to the right) instead of having the initial position at the start (furthest to the left)

I have been reading through the documentation and i haven't found any information on this subject, is this possible?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @konstantsoftware 

Greetings from Syncfusion. We have analyzed your query, and we would like to let you know that **isInversed** and **opposedPosition** of the axis properties which will help you to render a chart as per your scenario We have also added a code snippet below for your reference.

Code snippet:

```dart
SfCartesianChart(
          primaryXAxis: CategoryAxis(isInversed: true),
          primaryYAxis: NumericAxis(opposedPosition: true)
          // Other information
        ),
```

Screenshot:
![image](https://user-images.githubusercontent.com/61863686/141486911-6da11466-456b-4e85-88b0-d9746b7db9c4.png)

To know more about axis customization, find the user guide below
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization 

If this is not your case, please get back to us with more information like sharing a screenshot of your expected that will help us to provide a solution sooner.

Regards,
Yuvaraj.
