### ISSUE TITLE
SFGrid Scrolling behavior 

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#45]
Whenever  i am scrolling vertically or horizontally then below line is showing but after few seconds it is hiding..  in scrolling it should not hide

![image](https://user-images.githubusercontent.com/65191117/98237296-82795300-1f86-11eb-9566-0e96424bd220.png)

**Comment by NeelakandanKannan** [comment]
Hi waqaryounusjatt788,

Can you confirm whether you are reporting the below highlighted line?

![image](https://user-images.githubusercontent.com/42242041/98249779-acd60b00-1f9c-11eb-8243-83b26852bede.png)

If yes, that is the horizontal scrollbar which will be shown for some time when you scroll horizontally. Also, vertical scrollbar will be shown when you scroll vertically.

**Comment by waqaryounusjatt788** [comment]
yes, it is show some time but i want continuously show while scrolling required... if you see in the picture highlighted area there we need scroll line required every time. but when i scroll then line is showing otherwise it is hide. please give us an option for show scroll bar.
![screen](https://user-images.githubusercontent.com/65191117/98504185-252c1d00-2278-11eb-9538-0e8bb1d8b1ee.png)

**Comment by NeelakandanKannan** [comment]
Hi @waqaryounusjatt788 ,

Currently SfDataGrid does not have support to show the scrollbars always. We have considered this as feature and this will be implemented in our 2020 Volume 4 SP release which is scheduled on mid of January 2021. Please refer the below feedback link for better followup,
https://www.syncfusion.com/feedback/19678/support-to-show-scrollbars-always

**Comment by BalasubramaniSundaram** [comment]
Hi @waqaryounusjatt788, 

We are glad to inform you that these features have been included in our weekly pub release which was rolled out on 24th November 2020. You can use the below properties,

[isScrollbarAlwaysShown](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/isScrollbarAlwaysShown.html) - 

Indicates whether the horizontal and vertical scrollbars should always be visible. But, both the scrollbars can't be shown at the same time. Its framework side issue. We have reported the same,

https://github.com/flutter/flutter/issues/70380

[horizontalScrollPhysics](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/horizontalScrollPhysics.html) - To disable the scrolling for horizontal scroll bar.

[verticalScrollPhysics ](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/verticalScrollPhysics.html)- To disable the scrolling for vertical scrollbar.

Code Snippet

```
child: SfDataGrid(
                  source: _employeeDataGridSource,
                  columns: getColumns(),
                  gridLinesVisibility: GridLinesVisibility.both,
                  isScrollbarAlwaysShown: true,
                  verticalScrollPhysics: NeverScrollableScrollPhysics(),
                  horizontalScrollPhysics: NeverScrollableScrollPhysics(),
                ),
```

Regards, 
Balasubramani Sundaram.
