### ISSUE TITLE
syncfusion_flutter_xlsio Import dynamic data 

### ISSUE THREAD

**Issue by flomingdev** [syncfusion/flutter-widgets#453]
Let's say i have a local database, and I'm fetching data from it. when i try to import that list of data model datas into excel sheet using ExcelDataCell ,that time it didn't throw any exception ,it's successfully created xls but when i try to open excel and saw that data in that cell there will be a instance of exceldatarow? i don't know what's going wrong. please anybody can help me.I follow this package's demo,it has static data and it's working completely fine but what's wrong with dynamic data?

here is my function:

```
 Future<List<ExcelDataRow>> _buildReportDataRows() async {
    List<ExcelDataRow> excelDataRows = <ExcelDataRow>[];
    final Future<List<Entry>> reports = _getSalesReports();
    List<Entry> reports_1 = await Future.value(reports);
    excelDataRows = reports_1.map<ExcelDataRow>((Entry dataRow) {
      var index = reports_1.indexOf(dataRow);
      print(index);
      return ExcelDataRow(cells: <ExcelDataCell>[
        ExcelDataCell(columnHeader: 'No', value: index + 1),
        ExcelDataCell(
            columnHeader: 'Date of loan',
            value: changeStringToDate(dataRow.date)),
        ExcelDataCell(
            columnHeader: 'Amount',
            value:
                "${dataRow.landOrBorrowAmount}${provider.currencySymbol}"),
        ExcelDataCell(
            columnHeader: 'Type',
            value: dataRow.entryType),
        ExcelDataCell(
            columnHeader: 'Descriptions',
            value: dataRow.subEntryNote)
      ]);
    }).toList();
    return excelDataRows;
  }
```

**Comment by KonduruKeerthi** [comment]
Greetings from Syncfusion.

We have reproduce the mentioned issue as below.

If the data row value contains object like a class or new object, then, when importing that data, Flutter XlsIO converts the object to string type and that is the reason why cell value is shown as shows Instance of '_Report'.  
 
![image](https://user-images.githubusercontent.com/93245531/147915527-a02dae06-c96e-4c0b-8659-e1dc7889e0b7.png)
 
![image](https://user-images.githubusercontent.com/93245531/147915543-91ad1fbd-9fca-46e2-9f98-36af22faf9fe.png)

We suspect that your data row value do have objects like a class and this is causing issue. 

If this not the issue you are facing at your end, kindly share us the output Excel document along with code snippet of importing data, which will be helpful for us in investigating the query.

Regards,
Keerthi.
