### ISSUE TITLE
[syncfusion_flutter_charts] How to plot an audio file

### ISSUE THREAD

**Issue by bobosette** [syncfusion/flutter-widgets#454]
Hi everybody. Is there a way to plot an audio file with syncfusion_flutter_charts? I have this audio file recorded by a recorder widget and I need to plot it into a chart (x > time  y > amplitude) but I don't know how to convert it into chartdata.
Any suggests?

Thank you

**Comment by SriramKiranSenthilkumar** [comment]
Hi @bobosette,

Greetings from Syncfusion. We would like to let you know that currently, our charts widget doesn't support audio files. For rendering a chart you have convert your data into list type collection and then bind that data to the chart widget. Please find the user guide link below for binding chart data source below for your reference.
https://help.syncfusion.com/flutter/cartesian-charts/getting-started#bind-data-source

Also, you can able to bind the data available in JSON to our chart for which we have attached a simple sample in which we have rendered the chart by converting the JSON data into required list collection.
- Sample: https://flutter.syncfusion.com/#/cartesian-charts/data-source/json
- KB: https://www.syncfusion.com/kb/11674/how-to-render-a-flutter-chart-using-the-json-data-sfcartesianchart

Regards,
Sriram Kiran
