### ISSUE TITLE
Enable ToolTip

### ISSUE THREAD

**Issue by Avinash-kommareddy** [syncfusion/flutter-widgets#455]
How to show tooltip always enable?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Avinash-kommareddy,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that if your query is with chart package, then in **tooltipBehavior** it is having a **shouldAlwaysShow** property, it will help you to show the tooltip always on the screen. We have added the code snippet to enable tooltip always on the chart for your reference.

Code snippet:
```dart
SfCartesianChart(
   tooltipBehavior: TooltipBehavior(
     enable: true,
     shouldAlwaysShow: true,
   ),
   // Other information
 )
```

If this is not your case, then kindly mention the widget name in which you need the requested behavior, it will help us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by Avinash-kommareddy** [comment]
I need tooltip always true for SfSlider, but in that (shouldAlwaysShow: true)  is not available, but in my project i need to show always.
SfSlider(
        min: 20000,
        max: 5000000,
        value: _value,
        interval: 1245000,
        showTicks: true,
        showLabels: true,
        enableTooltip: true,
        tooltipShape: SfPaddleTooltipShape(),
        minorTicksPerInterval: 1,
        stepSize: 10000,
        activeColor: kPrimary,
        inactiveColor: kAthens,
        onChanged: (dynamic value) {
          setState(() {
            _value = value;
          });
        },
      ),

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Avinash-kommareddy,

As you have opened another ticket for your SfSlider widget related query, so kindly follow the same for further solution.

https://github.com/syncfusion/flutter-widgets/issues/464

Regards,
Yuvaraj.
