### ISSUE TITLE
row span & column span support?

### ISSUE THREAD

**Issue by acgleader** [syncfusion/flutter-widgets#457]

**Comment by dharanidharandharmasivam** [comment]
Hi @acgleader ,

Greetings from Syncfusion. We suspect that you are using the chart widget if so, we have already logged a feature request for your requirement. The feature will be available in any of the upcoming releases yet to come and you can track the status of the feature with below feedback

https://www.syncfusion.com/feedback/13611 

If your request is not with the chart widget, kindly get back to us with the widget you are using, this will be much helpful in providing the solution earlier.

Thanks,
Dharani.

Thanks,
Dharani.
