### ISSUE TITLE
Can you allow us to change the background color of the empty container ?

### ISSUE THREAD

**Issue by PavieOlivier** [syncfusion/flutter-widgets#458]
I looked into your code file and there is a parameter ≤≤ _pdfViewerThemeData≥≥ i would like to be able to change the background color if possible without having to fork your project

**Comment by dillibabu1802** [comment]
Hi @PavieOlivier 

Thank you for contacting Syncfusion support.

Yes, it is possible to change the background color of the SfPdfViewer. Please find the code example which illustrates how to change the background color of SfPdfViewer widget.

```
Widget build(BuildContext context) {
 return Scaffold(
     body: Center(
       child: SfTheme(
         data: SfThemeData(
           pdfViewerThemeData: SfPdfViewerThemeData(
             backgroundColor: Colors.blue
           )
         ),
     child: SfPdfViewer.network(
              'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf'),
       ),
     )
  );
}
```

To know more about backgroundColor property, please refer the following documentation.
[https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfPdfViewerThemeData/backgroundColor.html 
](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfPdfViewerThemeData/backgroundColor.html 
)

Regards,
Dilli babu

**Comment by PavieOlivier** [comment]
Thanks a lot, Worded like a charm

**Comment by PavieOlivier** [comment]
Thanks a lot, worked like a charm
