### ISSUE TITLE
Add Heat Map

### ISSUE THREAD

**Issue by deadsoul44** [syncfusion/flutter-widgets#46]
Add heat map like in the following picture:

![image](https://user-images.githubusercontent.com/31016182/98240999-55737300-1f7b-11eb-900a-2e0491dcdb92.png)

**Comment by NeelakandanKannan** [comment]
Hi @deadsoul44 ,

Thanks for your feedback.

Our DataGrid widget supports the conditional styling. You can achieve your requirement to highlight the cells based on the condition using [onQueryCellStyle](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/SfDataGrid/onQueryCellStyle.html) callback. Please refer the below below code snippet,

```dart
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:syncfusion_flutter_core/theme.dart';

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfDataGrid(
        source: _employeeDataSource,
        columns: <GridColumn>[
          GridNumericColumn(mappingName: 'id')..headerText = 'Order ID',
          GridTextColumn(mappingName: 'name')..headerText = 'Name',
          GridTextColumn(mappingName: 'designation')
            ..headerText = 'Designation',
          GridNumericColumn(mappingName: 'salary')..headerText = 'Salary'
        ],
        onQueryCellStyle: (QueryCellStyleArgs args) {
          if (args.column.mappingName == 'designation') {
            if (args.cellValue == 'Developer') {
              return DataGridCellStyle(
                  textStyle: TextStyle(fontStyle: FontStyle.italic),
                  backgroundColor: Colors.tealAccent);
            } else if (args.cellValue == 'Manager') {
              return DataGridCellStyle(
                  textStyle: TextStyle(fontStyle: FontStyle.italic),
                  backgroundColor: Colors.blue[200]);
            }
          }
          return null;
        }),
  );
}
```
You can refer the below example also,
https://github.com/syncfusion/flutter-examples/tree/master/lib/samples/datagrid/apperance/conditional_styling

Please let us know if your requirement differs from our solution.

**Comment by deadsoul44** [comment]
Thank you for the details. But, this approach paints individual cells without being aware of the adjacent cells. I thought more advanced and more smooth contour plots and heat maps with optional data annotations with various types can be painted like in the following example:

![image](https://user-images.githubusercontent.com/31016182/98344260-0cc3c480-2024-11eb-826b-03c394e8dc3a.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @deadsoul44,

We have analyzed your query and we have considered your suggestion as a feature request regarding implementing a new heat map chart widget. We have also logged feedback for it in our feedback portal and this will be available in any of our upcoming releases yet to come.

you can also track the status of the feature using the below feedback link and you can comment on the link if you have any suggestion or concern about the widget. 
https://www.syncfusion.com/feedback/19531

Regards,
Sriram Kiran
