### ISSUE TITLE
[sf_datagrid] How to disable sorting for a single row?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#462]
I am trying to exclude a single row from the column sort. It is the last row in a column. 

I have tried this:

- Set  `footerFrozenRowsCount` but that has no effect on the sorting. 
- Use the `footer` but since it takes a `Widget?`  as parameter this is useless in my case. 
- Give the cells of the last row a different column name

But nothing worked. So how am I excluding the last row of a column from sorting?

**Comment by Sangeetha-Raju** [comment]
Hi @Wizzel1,

Greetings from Syncfusion.

SfDataGrid supports to sort columns based on custom logic. You can exclude last row to achieve your requirement by using the [performSorting ](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/performSorting.html)method. This method has the argument which provides the list of DataGridRow. You can exclude the last row from that list and pass it to **super.performSort** method. So, rows will be sorted except the last row. Please refer the following code snippet.

```
class EmployeeDataGridSource extends DataGridSource {
  /// Creates the employee data source class with required details.
  EmployeeDataGridSource(
      {required List<Employee> employeeData}) {
    _dataGridRows = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }

  List<DataGridRow> _dataGridRows = [];

  @override
  List<DataGridRow> get rows => _dataGridRows;

  @override
  void performSorting(List<DataGridRow> rows) {
    final DataGridRow lastRow= rows.last;
    rows.removeLast();
    super.performSorting(rows);
    rows.add(lastRow);
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(8.0),
        child: Text(e.value?.toString() ?? ''),
      );
    }).toList());
  }
}
```
We have prepared a sample for your reference. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-323006647 

Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.

**Comment by Wizzel1** [comment]
Hi @Sangeetha-Raju thanks for the quick reply. Works perfectly.
