### ISSUE TITLE
I need tooltip always true for SfSlider, but in that (shouldAlwaysShow: true) is not available.

### ISSUE THREAD

**Issue by Avinash-kommareddy** [syncfusion/flutter-widgets#464]
SfSlider(
min: 20000,
max: 5000000,
value: _value,
interval: 1245000,
showTicks: true,
showLabels: true,
enableTooltip: true,
tooltipShape: SfPaddleTooltipShape(),
minorTicksPerInterval: 1,
stepSize: 10000,
activeColor: kPrimary,
inactiveColor: kAthens,
onChanged: (dynamic value) {
setState(() {
_value = value;
});
},
),

**Comment by lakshmi-radhakrishnan** [comment]
Hi Avinash, 

Greetings from Syncfusion support.
 
We have already considered your request as a feature and the status can be tracked from the feedback portal link.    
  
**Feedback:** https://www.syncfusion.com/feedback/29327/provide-an-option-to-display-the-tooltip-always-in-slider  
  
We have planned to include this feature in our Volume 4 2021 release, which is expected to be release at the end of December 2021.
    
If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.   

Disclaimer: The date for this feature implementation is tentative and not a commitment on our parts.
 
Regards, 
Lakshmi R.

**Comment by PraveenGopalsamy** [comment]
Hi Avinash,

We are glad to announce that our Essential Studio 2021 Volume 4 release v19.4.0.38  is rolled out and is available for download under the following link.

[https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F171304%2Fessential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download&data=04%7C01%7Cpraveen.gopalsamy%40syncfusion.com%7Ca1b22ce5b5364f2140ec08d9c37136cd%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637755713281022031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OJGzO%2BCa6%2F1YxRNwlr5rav0uI5re3%2FWsCNLTxwCoM0I%3D&reserved=0)

To show the tooltip always for slider or range slider or range selector widgets, set the [shouldAlwaysShowTooltip](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/shouldAlwaysShowTooltip.html) API as true. We had shown an example snippet using SfSlider.

```
double _value = 4.0;

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfSlider(
      min: 0,
      max: 10,
      value: _value,
      enableTooltip: true,
      shouldAlwaysShowTooltip: true,
      onChanged: (dynamic newValue) {
        setState(() {
          _value = newValue;
        });
      },
    ),
  );
}
```

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,          
Praveen G.
