### ISSUE TITLE
[syncfusion_flutter_datagrid] How to make selected rows persist when navigate to another page

### ISSUE THREAD

**Issue by Shuriken97** [syncfusion/flutter-widgets#466]
Hi there, would like to ask is it possible to make selected rows persist when navigating to another page and selecting new rows in the datagrid? 

So far when i tried to select rows in the first page of the datagrid and navigating to the second page of the datagrid and selecting new rows in that page will cause `controller.selectedRows` to reset and previously selected rows in the previous page will also not be highlighted anymore.

**Comment by Sangeetha-Raju** [comment]
Hi @Shuriken97,

Greetings from Syncfusion.

SfDataGrid supports to maintain the selectedRows collection within a page. While navigate to another page, we remove the old selectedRows from the DataGridController. This is the behavior of the DataGrid. We will check the possibilities and provide the further details on December 04, 2021.

We will appreciate your patience until then.

Regards,
Sangeetha Raju.

**Comment by Shuriken97** [comment]
Thanks for the reply! Hope to hear your response soon

**Comment by Sangeetha-Raju** [comment]
Hi @Shuriken97,

Thanks for the update.

As we said earlier, we will check the possibilities and update you the further details on December 06, 2021.

Regards,
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment]
Hi @Shuriken97,

Sorry for the inconvenience caused.

Due to some technical difficulties in providing the solution for your reported query, we need some more time to analyze it. We will update the further details on 7th December 2021.

We appreciate your patience until then.

Regards,
Sangeetha Raju.

**Comment by Shuriken97** [comment]
Thanks for the constant update ya. Another follow up question to ask is it normal behaviour for `DataGridController` to clear selected rows whenever changing light mode to dark mode? Is there a way to solve this issue?

**Comment by Sangeetha-Raju** [comment]
Hi @Shuriken97,

Thanks for your patience.

We have checked the possibility for the solution to meet your requirement. Currently, we don’t have sample level solution for your requirement. We have some known issue at our end while applying the below workaround. Please find the below workaround which will work in our upcoming 2021 Volume 4 release which is expected to be rolled out on mid of December 2021. 

**Solution**
This workaround will not work in the current package version. It will work in the upcoming **2021 Volume 4 release** package release as we mentioned. We will let you know when it gets rolled out. We appreciate your patience until then. You can maintain the internal collection to hold the selected data in **onPageNavigationStart** callback. Then, you should add those selected rows of the navigated page to the **DataGridController.selectedRows** property in **onPageNavigationEnd** callback. So, that you can maintain the selection even after navigation. Please refer the following code snippet.

```
@override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (context, constraint) {
      return Column(children: [
        SizedBox(
            height: constraint.maxHeight - _dataPagerHeight,
            width: constraint.maxWidth,
            child: _buildDataGrid(constraint)),
        Container(
            height: _dataPagerHeight,
            child: SfDataPager(
              controller: _pagerController,
              pageCount: _orders.length / _orderInfoDataSource._rowsPerPage,
              onPageNavigationStart: (int pageIndex) {
                selectedRows = _dataGridController.selectedRows;
                selRows[_pagerController.selectedPageIndex.toString()] =
                    selectedRows.toList();
              },
              delegate: _orderInfoDataSource,
              onPageNavigationEnd: (int pageIndex) {
                SchedulerBinding.instance!.addPostFrameCallback((_) {
                  if (selRows.containsKey('$pageIndex') &&
                      selRows['$pageIndex'] != null &&
                      selRows['$pageIndex']!.isNotEmpty) {
                    _dataGridController.selectedRows = selRows['$pageIndex']!;
                  }
                });
              },
              direction: Axis.horizontal,
            ))
      ]);
    });
  }
```

We have prepared sample for your reference. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1049736106 

Please refer to the below feedback link for further follow up,

**Feedback link:** https://www.syncfusion.com/feedback/30960/selectedrows-get-removed-when-navigate-into-new-page 

**Behavior of DataGridController:**
We have checked your reported case at our end. Unfortunately, we could not reproduce your reported case. We have prepared a sample for your reference. Please refer the following sample. Please let us know if we missed anything other than your customization. It will help us to find out the reason.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-20586932 

We hope this helps. Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment]
Hi @Shuriken97,

We are glad to announce that we have resolved the “Range exception is thrown when DataGridSource is changed at run time with multiple rows are selected” issue and included in our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 which is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download

The work around provided in the previous update will work with this package. Please update datagrid package to 19.4.38 version. You can also refer the following pub link. 

**Pub link:** https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.4.38 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards, 
Sangeetha Raju.
