### ISSUE TITLE
Custom loading indicator for pdf viewer?

### ISSUE THREAD

**Issue by NeatFastro** [syncfusion/flutter-widgets#468]
Can we customize the loading indicator of pdf viewer?

**Comment by dillibabu1802** [comment]
Hi @NeatFastro,

Thank you for contacting Syncfusion support.

Yes, it is possible to customize the color of the loading indicator in SfPdfViewer. Kindly refer to the following documentation link. 
[https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfPdfViewerThemeData/progressBarColor.html](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfPdfViewerThemeData/progressBarColor.html)

Regards,
Dilli babu.
