### ISSUE TITLE
[SfCartesianChart] AxisTitle position when using placeLabelsNearAxisLine: false

### ISSUE THREAD

**Issue by jlnrrg** [syncfusion/flutter-widgets#469]
The AxisTitle is placed within the chart, if I use `placeLabelsNearAxisLine: false`.
Is there a way to place the AxisTitle under the Axis Labels?

![Screenshot from 2021-12-02 13-55-09](https://user-images.githubusercontent.com/77293597/144426045-18e36db7-e265-4998-83f7-2c297e6cb4ce.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @jlnrrg 

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that the reported issue regarding axis title didn’t move along with axis label is already fixed and rolled out in our latest package. To resolve this kindly update the chart package to latest version.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.3.57 

Regards,
Yuvaraj.
