### ISSUE TITLE
type 'Null' is not a subtype of type 'Object'

### ISSUE THREAD

**Issue by WeiCongcong** [syncfusion/flutter-widgets#471]
The following exception will be thrown in a range picker if no date range is selected when the submit button is pressed.

> When the exception was thrown, this was the stack: 
#0      _SfDateRangePickerState._handleOk (package:syncfusion_flutter_datepicker/src/date_picker/date_picker.dart:6955:27)
#1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#5      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230:7)
#6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:558:9)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#22     _invoke1 (dart:ui/hooks.dart:185:10)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#3bd9b
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(336.3, 445.7)
  finalLocalPosition: Offset(40.2, 25.0)
  button: 1
  sent tap down
====================================================================================================

That might be caused by passing `dynamic value` which might be `null` as `Object` parameter.

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for contacting Syncfusion support.

Currently, we are validating the issue “**Exception occurred while tapping the action button without selecting the date in SfDateRangePicker**”. We will validate and update you the further details on or before December 8, 2021. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

Thank you for your patience.

We have fixed mentioned issue “**Exception occurred while tapping the action button without selecting the date in SfDateRangePicker**”. We will include the issue fix in our upcoming 2021 Volume 4 release, which is expected to be rolled out by mid of December 2021, and let you know once the release is rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Team,

We have included the issue fix for “**Exception occurred while tapping the action button without selecting the date in SfDateRangePicker**” in our 2021 Volume 4 release version 19.4.38. Kindly update to the latest version for resolving this issue fix. Please find the release notes and changelog from the following link.

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog 
**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v19.4.0.38?type=all#sfdaterangepicker-bug-fixes 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi Team,

We have included the issue fix for “Exception occurred while tapping the action button without selecting the date in SfDateRangePicker” in our 2021 Volume 4 release version 19.4.38. Kindly update to the latest version for resolving this issue fix. Please find the release notes and changelog from the following link.

**Changelog link:** https://pub.dev/packages/syncfusion_flutter_datepicker/changelog 
**Release notes link:** https://help.syncfusion.com/flutter/release-notes/v19.4.0.38?type=all#sfdaterangepicker-bug-fixes 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by WeiCongcong** [comment]
Great job!
