### ISSUE TITLE
RTL support for this Chart

### ISSUE THREAD

**Issue by JoelSuyati** [syncfusion/flutter-widgets#474]
There is Lack of RTL support for this widget

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @JoelSuyati 

Hi Team,
Greetings from Syncfusion. We have analyzed your query and we would like to let you know that you can achieve RTL in the chart using the Directionality widget. For more information on RTL, kindly find the user guide below.

User guide:
https://help.syncfusion.com/flutter/cartesian-charts/right-to-left


If this is not your exact case, then provide more information about in which scenario you get a lack of RTL support or a sample to reproduce the issue.

Regards,
Yuvaraj.
