### ISSUE TITLE
[syncfusion_flutter_charts] First and last datapoints not showing when zoomed in

### ISSUE THREAD

**Issue by ozzy91** [syncfusion/flutter-widgets#478]
I use a chart with a ZoomPanBehavior and a RangeController limiting the visible area (and used for other purposes).

In the default state (fully zoomed out) all datapoints are visible. When you zoom in, the first and last datapoints get cut off. This is visible when showing markers or using the TrackballBehavior.
Zooming alongside the edge (the first point always stays on the left) keeps the first point visible, but scrolling away from the beginning and then back to it will lead to the point missing 95% of the time.

This is all the way zoomed out:
![zoomed_out](https://user-images.githubusercontent.com/2384189/145174957-a2376b39-04df-4c3c-8e4d-fa6f3f8dc41f.png)

This is after zooming in and scrolling all the way to the left:
![zoomed_in](https://user-images.githubusercontent.com/2384189/145174972-f621478a-06b3-4ae1-a19c-618c6086d025.png)

I'm using flutter 2.5.3 and syncfusion_flutter_charts: ^19.3.56.
Here is the code to reproduce:
```
class ChartData {
  final DateTime x;
  final double y;

  ChartData(this.x, this.y);
}

class ZoomChart extends StatefulWidget {
  const ZoomChart({Key? key}) : super(key: key);

  @override
  State<ZoomChart> createState() => _ZoomChartState();
}

class _ZoomChartState extends State<ZoomChart> {
  final ZoomPanBehavior _zoomingBehavior = ZoomPanBehavior(
    enablePinching: true,
    zoomMode: ZoomMode.x,
    enablePanning: true,
    enableMouseWheelZooming: true,
  );

  final TrackballBehavior _trackballBehavior = TrackballBehavior(enable: true);
  late final RangeController _rangeController;

  final List<ChartData> data = [
    ChartData(DateTime(2000, 1, 1), 1),
    ChartData(DateTime(2000, 1, 2), 2),
    ChartData(DateTime(2000, 1, 3), 3),
    ChartData(DateTime(2000, 1, 4), 4),
    ChartData(DateTime(2000, 1, 5), 5),
    ChartData(DateTime(2000, 1, 6), 6),
    ChartData(DateTime(2000, 1, 7), 7),
    ChartData(DateTime(2000, 1, 8), 8),
    ChartData(DateTime(2000, 1, 9), 9),
  ];

  @override
  void initState() {
    super.initState();
    _rangeController = RangeController(start: data.first.x, end: data.last.x);
  }

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      primaryYAxis: NumericAxis(anchorRangeToVisiblePoints: false),
      primaryXAxis: DateTimeAxis(
        visibleMinimum: _rangeController.start,
        visibleMaximum: _rangeController.end,
        rangeController: _rangeController,
      ),
      series: _createSeries(),
      zoomPanBehavior: _zoomingBehavior,
      trackballBehavior: _trackballBehavior,
    );
  }

  List<FastLineSeries<ChartData, DateTime>> _createSeries() {
    return [
      FastLineSeries<ChartData, DateTime>(
        dataSource: data,
        xValueMapper: (ChartData d, _) => d.x,
        yValueMapper: (ChartData d, _) => d.y,
        markerSettings: const MarkerSettings(isVisible: true),
      ),
    ];
  }
}
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ozzy91,

Greetings from Syncfusion. We have analyzed your query and we have tested the reported scenario. We suspect that you might have panned the chart fastly and the panning is not completed before it gets panned to the right or left side of the device screen. So, the first and last point might not be visible. But when we try to pan normally it is working properly we have also attached the screen recorder for your reference. Hope this information might helps you.

Video: 

https://user-images.githubusercontent.com/61863686/145627787-08d03990-9bab-4c07-92b7-08bfcdbcfaa3.mp4



Regards,
Yuvaraj.
