### ISSUE TITLE
[syncfusion_flutter_charts] PlotBand line dashArray not working in the web

### ISSUE THREAD

**Issue by ozzy91** [syncfusion/flutter-widgets#479]
I'm using the PlotBands to show horizontal lines at certain positions. The lines are customized to show as dashed lines.
This works as expected on iOS but the line shows up without dashing on the web.

![plot_line_ios](https://user-images.githubusercontent.com/2384189/145178569-652bc8c4-4ad5-4d50-a99c-e1cd66ac953c.png)
![plot_line_chrome](https://user-images.githubusercontent.com/2384189/145178577-10b15d0f-4131-4ee9-a771-776c2ce9145d.png)

I'm using flutter 2.5.3 and syncfusion_flutter_charts: ^19.3.56.
Here is the code to reproduce:
```
class ChartData {
  final DateTime x;
  final double y;

  ChartData(this.x, this.y);
}

class PlotLineChart extends StatefulWidget {
  const PlotLineChart({Key? key}) : super(key: key);

  @override
  State<PlotLineChart> createState() => _PlotLineChartState();
}

class _PlotLineChartState extends State<PlotLineChart> {
  final List<ChartData> data = [
    ChartData(DateTime(2000, 1, 1), 1),
    ChartData(DateTime(2000, 1, 9), 9),
  ];

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      primaryXAxis: DateTimeAxis(),
      primaryYAxis: NumericAxis(
        plotBands: [
          PlotBand(start: 5.3, end: 5.3, borderWidth: 2, dashArray: const [5, 9]),
          PlotBand(start: 2.3, end: 2.3, borderWidth: 1, dashArray: const [4, 6]),
        ],
      ),
      series: _createSeries(),
    );
  }

  List<FastLineSeries<ChartData, DateTime>> _createSeries() {
    return [
      FastLineSeries<ChartData, DateTime>(
        dataSource: data,
        xValueMapper: (ChartData d, _) => d.x,
        yValueMapper: (ChartData d, _) => d.y,
        markerSettings: const MarkerSettings(isVisible: true),
      ),
    ];
  }
}
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ozzy91,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that in previous version of Flutter. they didn't provide support the dash array support on web platform, so we have prohibited the dash array rendering. In recent time only the dash array support is added in the Flutter web. So, we have already moved the changes for rendering dash array on web and it will be rolled out in our volume 4 main release until then we appreciate your patience.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @ozzy91,

Thanks for your patience, now we have provided dash array support on the web for plot bands and moved to the main release. To resolve this kindly update the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.40

Regards,
Yuvaraj.

**Comment by ozzy91** [comment]
Thank you!
