### ISSUE TITLE
[Charts] Add overallDataPointIndex as argument of onDataLabelTapped

### ISSUE THREAD

**Issue by andrea689** [syncfusion/flutter-widgets#48]
Hi, I need `overallDataPointIndex` as argument of `onDataLabelTapped` similar to `onSelectionChanged`

Thanks

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689, 

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we have considered your suggestion as an improvement regarding adding **`overallDataPointIndex`** as an argument in the **`onDataLabelTapped`** event. We will implement and include this improvement in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @andrea689 ,

Thanks for your patience. The requested improvement regarding adding **`overallDataPointIndex`** as an argument in the **`onDataLabelTapped`** event is implemented and rolled out in our weekly patch release. To use this improvement, kindly upgrade the chart widget package to the latest version below.
https://pub.dev/packages/syncfusion_flutter_charts/versions/18.3.50

Regards,
Sriram Kiran
