### ISSUE TITLE
change text active color

### ISSUE THREAD

**Issue by helloo0-0oword** [syncfusion/flutter-widgets#480]
I want to change the color of selected and unselected number area. For example, if you want to change the number in red, how do you do it?. Thks a lot

<img width="77" alt="Screen Shot 2021-12-08 at 23 51 07" src="https://user-images.githubusercontent.com/32776884/145249495-85a907af-88e4-42a9-9be6-fce2bfcb0783.png">

**Comment by PraveenGopalsamy** [comment]
Hi helloo0-0oword,
 
Greetings from Syncfusion support.
 
We have checked your query at our end. You can set the color for axis labels by using the [axisLabelStyle](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/axisLabelStyle.html) property or by using the [onLabelCreated](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/onLabelCreated.html) callback which is triggered when axis label creation. We have attached the sample project for your reference.

Attachment : [flutter_gauge_with_colored_labels.zip](https://github.com/syncfusion/flutter-widgets/files/7686755/flutter_gauge_with_colored_labels.zip)

Please let us know if you need any further assistance in this.
 
Regards,
Praveen G.
