### ISSUE TITLE
[syncfusion_flutter_pdfviewer]  QR Code not showing on pdf page

### ISSUE THREAD

**Issue by wanzismail** [syncfusion/flutter-widgets#482]
This case only happens to some pdf files that I use, I don't know if this problem comes from the pdf file or not.. because pdf file is the result generate from the back  office (API).

You can try to trace the issue when you open the following pdf file : 
https://files.fm/down.php?cf&i=76z94kkuq&n=Contoh_TTE_Berjenjang_25112021_signed.pdf

**Comment by deepika134** [comment]
Hi wanzismail,

Greetings from Syncfusion.

We can reproduce the reported behavior from our side. We are analyzing on this and will update the further details on 15 December 2021.

Regards,
Deepika Ravi.

**Comment by deepika134** [comment]
Hi wanzismail,

At present we do not have support for "PDF form annotation”. As a workaround, we request to flatten the annotation using our Syncfusion PDF package and pass the saved memory bytes to the SfPdViewer widget. We have prepared the sample for that and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app_3301281623682657.zip 

We do not have any immediate plans to implement PDF form annotation feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status can be tracked using following link. 
https://www.syncfusion.com/feedback/25265/support-for-pdf-form   

Regards,
Deepika Ravi

**Comment by wanzismail** [comment]
Okay @deepika134 , I hope it will be implemented soon.

Thank you for the help.
