### ISSUE TITLE
[Treemap] show a tooltip from initial build without user interaction

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#483]
currently to make a tooltip pops up, 
the user needs to tap on the treemap.

Is there a way to make one tooltip visible at the very beginning by default without any user tap/click?
------
the underlying idea is: 
currently the tooltip is buried under the UI, 
so some users wouldn't know the treemap is tappable.

**Comment by SuryaChinnadurai** [comment]
Hi FisherWL,

Greetings from Syncfusion support.

As we do not have this feature available in our widget, we considered your request as a feature and the status can be tracked from the feedback portal link. 
 
**Feedback:** [https://www.syncfusion.com/feedback/31127/display-the-tooltip-while-loading-treemap-widget](https://www.syncfusion.com/feedback/31127/display-the-tooltip-while-loading-treemap-widget)

We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our releases.  

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.   
 
Regards, 
Surya C.
