### ISSUE TITLE
 [syncfusion_flutter_charts] The soruce code in this reposiory is out-of date

### ISSUE THREAD

**Issue by MrCsabaToth** [syncfusion/flutter-widgets#487]
According to https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/CHANGELOG.md this source is only `[19.2.59] - 08/31/2021` version, whereas the package is at 19.3.57. This prevents me to craft a PR for https://github.com/syncfusion/flutter-widgets/issues/463

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @MrCsabaToth,

Greetings from Syncfusion. We have analyzed your query, and we would like to let you know that the flutter widgets GitHub repository only gets updated at the main release. So, we are close to our volume 4 main release, and we expect it will be rolled out at the end of this week. After that, the repository will get updated with the latest source. We update you once the flutter widget repository is updated with the latest source until then we appreciate your patience.

Regards,
Yuvaraj.

**Comment by MrCsabaToth** [comment]
All right, so this repository is not the direct source of the package builds and releases.
