### ISSUE TITLE
Can not scrollDirection as vertical

### ISSUE THREAD

**Issue by trankienbk** [syncfusion/flutter-widgets#488]
pageLayoutMode: PdfPageLayoutMode.single,
scrollDirection: PdfScrollDirection.vertical,

But I can not scroll as vertical, i only can scroll as horizontal. Please help me!!

**Comment by deepika134** [comment]
Hi trankienbk ,

Thank you for contacting Syncfusion support.

As mentioned in our documentation( https://help.syncfusion.com/flutter/pdf-viewer/page-layout-and-scroll-direction#page-layout-modes ), we are yet to provide support for vertical scrolling in single page layout mode, We are analyzing the feasibility of you requirement and will update the details on 20 December 2021.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi trankienbk,

At present we do not have support for “Vertical scrolling in single-page layout mode” in SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
The status of implementation can be tracked through the below feedback link,
https://www.syncfusion.com/feedback/31333/support-for-vertical-scrolling-in-single-page-view-page-layout  

Regards,
Deepika Ravi.
