### ISSUE TITLE
Can not display digital signature

### ISSUE THREAD

**Issue by trankienbk** [syncfusion/flutter-widgets#491]
I have a pdf file, which include digital signature. But I can not display digital signature with library.
Please help me to display it.
Thank you so much!!

**Comment by deepika134** [comment]
Hi trankienbk,

Thank you for contacting Syncfusion support.

At present we do not have support for "Digital Signature". We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of implementation can be tracked through the below feedback link  
https://www.syncfusion.com/feedback/26234/support-for-digital-signature 

Regards,
Deepika Ravi
