### ISSUE TITLE
I can't display on a chart negative value.

### ISSUE THREAD

**Issue by metcenger** [syncfusion/flutter-widgets#493]
made array:

`        data.add(_WeightData('15 Dec 15:18', -35, -180)); // weight.day, weight.weight, weight.weight_start_val (data in to chart)
        data.add(_WeightData('15 Dec 15:19', -28,  -180));
        data.add(_WeightData('15 Dec 15:06', -34,  -180));
        data.add(_WeightData('15 Dec 15:07', 56, -180));
        data.add(_WeightData('15 Dec 15:22', 60, -180));
        data.add(_WeightData('15 Dec 15:23', 55, -180));
        data.add(_WeightData('15 Dec 15:24', 55, 180));
        data.add(_WeightData('15 Dec 15:25', -65, 180));
        data.add(_WeightData('15 Dec 15:26', -75, 180));
        data.add(_WeightData('15 Dec 15:27', -90, 180));
        data.add(_WeightData('15 Dec 15:28', -40, 180));`

and chart shows only data with positive values ( 4-7 lines )
chart Y numeric from -180, like expected.
But there are no any negative data on the chart.

`                child: SfCartesianChart(
                    primaryXAxis: CategoryAxis(),
                    primaryYAxis: NumericAxis(minimum: _minimum_weight_of_array),

                    zoomPanBehavior: ZoomPanBehavior(enablePinching: true),

                    series: <ChartSeries<_WeightData, String>>[
                      SplineRangeAreaSeries<_WeightData, String>(
                          dataSource: data,
                          // Setting the gradient for the series
                          gradient: _linearGradient,
                          xValueMapper: (_WeightData weight, _) => weight.day,
                          highValueMapper: (_WeightData weight, _) => weight.weight,
                          lowValueMapper: (_WeightData weight, _) => weight.weight_start_val

                      )
                    ]
                )`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi metcenger,


Greetings from Syncfusion. We have analyzed your query and we would like to let you know that the reported issue has been already resolved in the latest version of our package. Kindly upgrade to our latest version from below.


Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.38


Regards,
Yuvaraj.
