### ISSUE TITLE
[syncfusion_flutter_charts]-[ScatterSeries]-[DataMarkerType] custom data maker type

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#494]
By default, there're several data maker types available,
but sometimes I need more than that,
so I try to fork the repo and modify the package's source code,

I added:

`lib/src/utils/helpers.dart `
-> `DataMakerType` `myNewShape` enum
-> `void darwMyNewShape` function

`lib/src/tooltip/tooltip.dart`
-> `case DataMarkerType.myNewShape:`

But it's not working, the makers disappear and nothing shows up.
Where/ what did I miss? Any tip is appreciated.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that you can add the custom markers as an image. To know more on this, find the user guide below,
https://help.syncfusion.com/flutter/cartesian-charts/marker-datalabel#image-marker 

And you can draw the custom shapes using the override method drawDataMarker. Here we have attached the code snippet to customize the data marker using onCreateRenderer callback property of series, which is used to override the rendering of the whole series, here we can use the drawDataMarker method to override the rendering of the marker. Please find the below code snippet for your reference.

Code snippet:

```dart
SfCartesianChart(
         series: <ChartSeries<ChartData, int>>[
            LineSeries<ChartData, int>(
              onCreateRenderer: (ChartSeries<dynamic, dynamic> series) {
                return CustomLineSeriesRenderer();
              },
            // Other information
          ],
        ),

// Customize the series rendering
class CustomLineSeriesRenderer extends LineSeriesRenderer {
  CustomLineSeriesRenderer();

  @override
  void drawDataMarker(int index, Canvas canvas, Paint fillPaint,
      Paint strokePaint, double pointX, double pointY,
      [CartesianSeriesRenderer? seriesRenderer]) {
    final Paint customerStrokePaint = Paint();
    customerStrokePaint.color = Colors.green;
    customerStrokePaint.strokeWidth = 4;
    customerStrokePaint.style = PaintingStyle.stroke;
    canvas.drawCircle(Offset(pointX,pointY), 6, customerStrokePaint);
  }
}
```

In the above code, we have drawn a circle, you can customize based on your scenario.

Regards,
Yuvaraj.
