### ISSUE TITLE
 Error on lauching Android: The non-abstract class 'SfLocalizations...

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#499]
I'm using a syncfusion_localizations version: ^19.3.47 in my pubspec.yaml. When running my android app it generates several errors referring to a newer version that I don't use:

`/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_localizations-19.4.38/lib/src/l10n/generated_syncfusion_localizations.dart:17:7: Error: The non-abstract class 'SfLocalizationsAf' is missing implementations for these members:
 - SfLocalizations.rowsPerPageDataPagerLabel
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class SfLocalizationsAf extends SfGlobalLocalizations {
      ^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-19.4.38/lib/src/localizations/global_localizations.dart:161:14: Context: 'SfLocalizations.rowsPerPageDataPagerLabel' is defined here.
  String get rowsPerPageDataPagerLabel;
             ^^^^^^^^^^^^^^^^^^^^^^^^^`

Flutter 2.5.3

Attached console output
[console.txt](https://github.com/syncfusion/flutter-widgets/files/7738550/console.txt)

**Comment by Alusio** [comment]
Same error here

**Comment by mdmota** [comment]
> Same error here

the worst thing is that I can no longer build my application

**Comment by Alusio** [comment]
I just downgraded to the version 19.3.59 and it works again

**Comment by mdmota** [comment]
@Alusio I downgraded and it keeps giving a build error in the version I don't use

/c:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_localizations-19.4.38/lib/src/l10n/generated_syncfusion_localizations.dart:17:7: Error: The non-abstract class 'SfLocalizationsAf' is missing implementations for these members:
 - SfLocalizations.rowsPerPageDataPagerLabel
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

**Comment by zanpen2000** [comment]
我的临时解决方案：

1. `flutter pub cache clean`
2. add "syncfusion_flutter_core: 19.3.59" to pubspec.yaml
3. make sure `syncfusion_*` packages's version is "19.3.59"


then it works again!

**Comment by Sangeetha-Raju** [comment]
Hi @mdmota ,

Sorry for the inconvenience caused.

We have resolved this localization issue and included the fix changes in our pub release. Please upgrade the **localization package to 19.4.38+1** version. You can also refer the following pub link. 

**Pub link:** https://pub.dev/packages/syncfusion_localizations/versions/19.4.38+1

Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.
