### ISSUE TITLE
Horizontal veiw

### ISSUE THREAD

**Issue by Sahmirzali** [syncfusion/flutter-widgets#5]
is this package support horizontal veiw? or will you support horizontal view?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sahmirzali,

Greetings from Syncfusion. We have analyzed on your query and as we are not sure of which Syncfusion Flutter widget you are using, We couldn't able to provide response for your query. So, we kindly request you to share us the more information on the Syncfusion flutter widget package you are using so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran

**Comment by huseynovali** [comment]
I'm using this package), i just ask you it will be support horizontal view, search and other features?

**Comment by Sahmirzali** [comment]
I'm using this package), i just ask you will it be support horizontal view, search and other features ?

**Comment by dillibabun** [comment]
Hi @Sahmirzali ,

Greetings from Syncfusion.

At present we do not have support for “Page by page view mode”. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 2 main release. We will let you know when this feature is implemented.

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

The status of this feature can be tracked using following link.
https://www.syncfusion.com/feedback/18491/support-for-page-by-page-view 

Regards,
Dilli babu.

**Comment by Sahmirzali** [comment]
Thanks. yes i'm using  syncfusion_flutter_pdfviewer package.

**Comment by dillibabun** [comment]
Hi @sahmirzali ,

We have planned to provide Horizontal scrolling support in SfPdfViewer widget for 2021 Volume 3 release. This feature won't includes single view and load the document page by page. The page by page view feature will be planned for any other future releases. Please let us know if you have any concerns.

Regards,
Dilli babu.
