### ISSUE TITLE
Enlarge touch to resize calendar schedule

### ISSUE THREAD

**Issue by minhduc1827** [syncfusion/flutter-widgets#50]
Hi all, in the google calendar, the users can touch to resize the calendar schedule.
Eg: We can increase or decrease hours when touching and enlarge the schedule.
Would you please add the feature on syncfusion calendar.
Thank you very much, your calendar is nice and if we have the feature that i told, it will be nicer.

**Comment by Indumathi1195R** [comment]
Hi minhduc1827,

We have already considered “**Resizing the appointment duration**” in the Flutter event calendar. We will implement this feature in any of our upcoming releases and let you know once the feature is implemented. We appreciate your patience until then.

Now you can track the current status of this feature request by using the below feedback link.

**Feedback link:**
https://www.syncfusion.com/feedback/15102/providing-support-for-drag-and-drop-and-resizing-the-appointment-duration-in-the

Regards,
Indumathi R
