### ISSUE TITLE
Candle Chart in Flutter Cartesian Charts: Hide Weekends

### ISSUE THREAD

**Issue by MilesAdamson** [syncfusion/flutter-widgets#500]
Hi, I have a chart which is plotting AAPL for the last 2 weeks with a daily candle resolution. It is working beautifully, except for one thing. The weekends and holidays leave empty gaps in the chart. I would like my app to be continuous such that the weekends and holidays which have no data are simply not plotted, which would make my x-axis a bit weird where it would skip days.

How would you suggest modifying my data or plot to make Fridays seamlessly connect to Mondays?

![image](https://user-images.githubusercontent.com/29047682/146652789-eacff842-b48d-416d-b258-3b0b40f2819e.png)

```
@freezed
class Candle with _$Candle {
  Candle._();
  factory Candle(
    double close,
    double high,
    double low,
    double open,
    DateTime timestamp,
    double volume,
  ) = _Candle;

  List<double> get spread => [low, close, open, high];
}
```

```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Chart'),
      ),
      body: SfCartesianChart(
        primaryXAxis: DateTimeAxis(),
        primaryYAxis: NumericAxis(
          minimum: plotMinimum.roundToDouble(),
          maximum: plotMaximum.roundToDouble(),
          interval: 1,
        ),
        series: <ChartSeries<Candle, DateTime>>[
          widget.candles.candleSeries,
        ],
      ),
    );
  }
```

```
    return CandleSeries<Candle, DateTime>(
      xValueMapper: (c, _) => c.timestamp,
      dataSource: this,
      openValueMapper: (c, _) => c.open,
      highValueMapper: (c, _) => c.high,
      closeValueMapper: (c, _) => c.close,
      lowValueMapper: (c, _) => c.low,
      bearColor: Colors.red,
      bullColor: Colors.green,
    );
```

**Comment by FisherWL** [comment]
change primaryXAxis to DateTimeCategoryAxis()

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @MilesAdamson ,

Greetings from Syncfusion. We have analyzed your query and to achieve your requirement you can use the date time category axis. To know more about date time category axis, find the user guide below.

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-category-axis 

We hope this will help you to achieve your requirement.

Regards,
Yuvaraj.

**Comment by MilesAdamson** [comment]
Thank you
