### ISSUE TITLE
[bug] Trackball unexpected behavior / Suddently disappears

### ISSUE THREAD

**Issue by lucavenir** [syncfusion/flutter-widgets#501]
Hello there,

Whenever I create a chart with this lib, I'd like to have some labeling when using the trackball feature, so that when my users drag their finger around the Plots, they get responsive info :-)

I use the `onTrackballPositionChanging` method to set some label (which is time based, say `09:59`).
It works great!

Although... well, here's an example:
```
  ...
  onTrackballPositionChanging: (args) {
    final currentIndex = args.chartPointInfo.dataPointIndex;
    final currentPoint =
        args.chartPointInfo.series?.dataSource[currentIndex ?? 0];
    if (currentPoint != null) {
      args.chartPointInfo.label = "09:59";  // Or some other label involving a `:`
    }
  },
  ...
```
Try this out and see what happens: the trackball label un-bold-izes everything that comes before the `:` character. In other words:
- Everything BEFORE the `:` is non-bold;
- Everything AFTER the `:` is bold.

This is kinda annoying. The final user can't appreciate this, especially on `DateTime` type Plots.
Expected behavior, instead:

- Everything is just "normal" (or everything's bold by default, but styles are not mixed).

I'm guessing this is a bug. How can I workaround this?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lucavenir ,

Greetings from Syncfusion. We have analyzed your query and we would like to inform you that in the trackball tooltip, the label getting bold after the colon is the default behavior. If you want to achieve your requirement like without bold, you can use the builder property. It will help you to customize the trackball tooltip as you wish, we have also attached the sample below for your reference.

Sample: [trackball_tooltip.zip](https://github.com/syncfusion/flutter-widgets/files/7755323/trackball_tooltip.zip)


UG: https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair#trackball-tooltip-template

Regards,
Yuvaraj.

**Comment by lucavenir** [comment]
Hi there,

thanks for your quick response, which has been very helpful.

In the end, just for future reference if someone else has my same problem, I implemented the trackball with the following code. Some parts still confuse (see comments) me but it's working. Thank you.

```dart
trackballBehavior: TrackballBehavior(
  builder: (ctx, details) {
    final data = details.series?.dataSource;
    final i = details.pointIndex;

    // `_label` is just a function that outputs some `String` value
    final label = _label(data?[i ?? 0]);  // why would `pointIndex` be `null`?
    final pointColor = details.point?.pointColorMapper;  // why would `point` be `null`?

    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: 10,
        vertical: 5,
      ),
      decoration: BoxDecoration(
        borderRadius: const BorderRadius.all(Radius.circular(6)),
        color: Colors.grey.shade100,
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Padding(
            padding: const EdgeInsets.all(5),
            child: Container(
              height: 10,
              width: 10,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                color: pointColor,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(5),
            child: Text(
              label,
              style: Theme.of(ctx)
                  .textTheme
                  .bodyText1
                  ?.copyWith(color: Colors.black),
            ),
          )
        ],
      ),
    );
  },
  enable: true,
  activationMode: ActivationMode.longPress,
  tooltipSettings: InteractiveTooltip(
    enable: true,
    canShowMarker: true,
    color: Colors.white,
    textStyle: Theme.of(context)
        .textTheme
        .bodyText1!
        .copyWith(color: Colors.black),
  ),
),
```

**Comment by lucavenir** [comment]
Hi there, unluckily your solution leads to an unexpected bug / behavior.

Sometimes the tooltip disappears. I'll attach a screenshot for the sake of clarity.
The code is the same as before (above).

![image](https://user-images.githubusercontent.com/28173024/156387050-328a4941-465d-4fe2-93f3-7b7debfe4970.png)

Oddly enough, the tooltip disappears only within the center of the plot.
For the sake of clarity I'll post here the full plot code.

Also, I suspected that the problem lied in the null check in the tooltip builder, `if (point == null)`, but after a debug session I verifies that condition never happens.

Is it a visual bug of some sort? Please let me know.

```
return SfCartesianChart(
      margin: EdgeInsets.only(right: 10.0),
      primaryXAxis: DateTimeAxis(
        //Hide the gridlines of y-axis
        majorGridLines: const MajorGridLines(width: 0),
        axisLabelFormatter: (args) => ChartAxisLabel(
          args.text,
          args.textStyle.copyWith(color: Colors.white),
        ),
        //Hide the axis line of y-axis
        axisLine: const AxisLine(width: 0),
        enableAutoIntervalOnZooming: false,
        dateFormat: DateFormat.H(),
        plotBands: [
          PlotBand(
            shouldRenderAboveSeries: true,
            associatedAxisStart: redLineValue,
            associatedAxisEnd: redLineValue,
            borderColor: const Color(0xffBC0000),
            borderWidth: 2,
            isVisible: true,
          ),
        ],
        desiredIntervals: 24 ~/ 4,
        interval: 4,
        intervalType: DateTimeIntervalType.hours,
      ),
      primaryYAxis: NumericAxis(
        title: AxisTitle(
          text: "kWh",
          textStyle: Theme.of(context).textTheme.bodyText1?.copyWith(
                height: 1, fontSize: 12
              ),
        ),
        rangePadding: ChartRangePadding.none,
        axisLabelFormatter: (args) => ChartAxisLabel(
          args.text,
          args.textStyle.copyWith(color: Colors.white),
        ),
        labelFormat: "{value}",
        numberFormat: NumberFormat('0.0', Localizations.localeOf(context).languageCode),
        maximum: redLineValue * 1.1,
      ),
      trackballBehavior: TrackballBehavior(
        builder: (ctx, details) {
          final i = details.pointIndex;
          final data = details.series?.dataSource;

          final point = i == null ? null : data?[i];

          if (point == null) {
            return Container();
          }

          final label = _label(point);
          final pointColor = details.point?.pointColorMapper;

          return Container(
            padding: const EdgeInsets.symmetric(
              horizontal: 10,
              vertical: 5,
            ),
            decoration: BoxDecoration(
              borderRadius: const BorderRadius.all(Radius.circular(6)),
              color: Colors.grey.shade100,
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Padding(
                  padding: const EdgeInsets.all(5),
                  child: Container(
                    height: 10,
                    width: 10,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: pointColor,
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(5),
                  child: Text(
                    label,
                    style: Theme.of(ctx).textTheme.bodyText1?.copyWith(
                          color: Colors.black,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                )
              ],
            ),
          );
        },
        enable: true,
        activationMode: ActivationMode.longPress,
        tooltipSettings: InteractiveTooltip(
          enable: true,
          canShowMarker: true,
          color: Colors.white,
          textStyle: Theme.of(context)
              .textTheme
              .bodyText1!
              .copyWith(color: Colors.black),
        ),
      ),
      series: [
        ColumnSeries(
          dataSource: data,  // some data
          yAxisName: unitOfMeasure,
          pointColorMapper: (LoadcurvePoint d, _) => d.timeSlot.color,  // some color that depends on the point
          xValueMapper: (LoadcurvePoint d, _) => d.ts,  // timestamp
          yValueMapper: (LoadcurvePoint d, _) => d.value,  // value
          animationDuration: 1,
          borderWidth: 1,
          width: 1,
        ),
      ],
    );
```

**Comment by lucavenir** [comment]
Hi there, is anyone able to reproduce this behavior or am I the only one having this problem?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lucavenir,

We have tried to reproduce the reported issue, but it is not getting reproduced at our end. We have attached the sample below which is used in the testing phase. So, can you please try to reproduce the reported issue in the attached sample and get back to us.

Sample: [github_501.zip](https://github.com/syncfusion/flutter-widgets/files/8218194/github_501.zip)


Regards,
Yuvaraj.

**Comment by lucavenir** [comment]
Hi @Yuvaraj-Gajaraj,

thanks for your kind and hard work.
You're quite right. I tried to export the following:
1. The plot, just as you did;
2. The actual data;
3. The parsing methods

And indeed I can see that every trackball label is being rendered.
Whereas in my real use case, it isn't.

This is extremely weird, as my app does nothing more than displaying the same widget I've pasted. The only difference is plot height. What could collide with SfCharts default behavior? 😕 

My only thought is that this is related related to data: my plot is way smaller than the one used in this example (plot's height is restricted to 250px) and maybe whenever the labels can't fit inside the plot, they're all hidden.

Do you think that is a possibility?

**Comment by lucavenir** [comment]
@Yuvaraj-Gajaraj Hello there,

I've found out what the problem is. It is indeed linked to what data is being displayed in the tooltip. Say we have the following `TrackballBehavior`'s `build` method that returns the following Widget:
```dart
    builder: (ctx, details) {
      // ... extract and format data ...

      return Container(
        padding: const EdgeInsets.symmetric(
          horizontal: 4,
          vertical: 3,
        ),
        decoration: BoxDecoration(
          borderRadius: const BorderRadius.all(Radius.circular(6)),
          color: Colors.grey.shade100,
        ),
        child: Wrap(
          alignment: WrapAlignment.start,
          crossAxisAlignment: WrapCrossAlignment.start,
          runAlignment: WrapAlignment.start,
          direction: Axis.vertical,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 2,
                vertical: 1,
              ),
              child: Container(
                height: 12,
                width: 12,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: pointColor,
                ),
              ),
            ),
            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 2,
                vertical: 1,
              ),
              child: Text(
                label,
                style: Theme.of(ctx).textTheme.bodyText1?.copyWith(
                      color: Colors.black,
                      fontWeight: FontWeight.bold,
                    ),
              ),
            ),
          ],
        ),
      );
    },
```

You can see a slight difference between the previous snippets and this one: this tooltip uses a Wrap. This allowed me to intuitively understand what was going on under the hood.

What happens is that, sometimes (and only on some screens) the tooltip isn't able to contain itself within the plot. You may say it's an overflow error. This, if you use a `Row`. Probably the chart is catching overflow errors under the hood.
The problem is that the developer (aka me) isn't able to infer this from the logs. No exceptions or overflow errors are being displayed anywhere.

If you instead use a `Wrap` (as it is done above) the outer container with its padding and background color is removed, while the tooltip labels are still displayed; at the same time, it is possible to infer that this is happening because of the limited available space of the plot (i.e. the tooltip is bigger than half of the current plot's width).

As a workaround I think I'll stick to using a `Wrap` widget that layouts my tooltips differently; this will solve my personal issue, but I don't think I should close github issue as:

1. I'd expect SfCharts to display at least an overflow warning or some sort of feedback;
2. I'd expect some documentation about this behavior (somewhere);
3. It is still weird that a `Wrap` 's content is being displayed, but its outer container (padding) isn't.

I'll post here a reproducible example ASAP. Thank you for assisting me.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lucavenir,

We have a few improvements in the trackball tooltip display, it will get rolled out in the vol1 main release which is expected in the middle of next week. We will update you once the release gets rolled out and we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by lucavenir** [comment]
Thank you!

There is no hurry, no worries (-:
Having feedback on the nature of this issue was more than enough! In the end, my problem was that I wasn't told there was an overflow problem on some screens.

Cheers!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lucavenir,

Thanks for your patience, our release got rolled out. Kindly upgrade the chart package to the latest version below and check.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.51

Regards,
Yuvaraj.

**Comment by lucavenir** [comment]
Thank you,

I'll close this issue right away. Have a nice day
