### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Tile Rendering Zoom will be better if clarity improved

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#502]
Thank you syncfusion for also adding Tile Rendering Zoom support in this awesome package.

It seems that in current implementation of tile rendering zoom it increases the resolution of the pages as zoom level increases. But then also rendering is not as sharp and crisp as what we normally see in pdf viewers. Can it be improved for better viewing quality ?

Device Tested : Android 10, API level 29
Flutter : 2.8.0, channel stable
syncfusion_flutter_pdfviewer: ^19.4.38-beta

### Current Rendering
![Current](https://user-images.githubusercontent.com/60609139/146880771-97fb37cd-0c18-4d67-8693-5740c1beae75.jpg)

### Expected Rendering
![Expected](https://user-images.githubusercontent.com/60609139/146880807-cfe037f6-8b89-403a-999e-0dbe54f46ed3.jpg)

Regards,
Sagar

**Comment by deepika134** [comment]
Hi Sagarkardani,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 27 December 2021.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi Sagarkardani,

At present we do not have support for “Active viewport rendering” in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
The status of implementation can be tracked through the below feedback link,
https://www.syncfusion.com/feedback/31524/active-viewport-rendering 

Regards,
Deepika Ravi.

**Comment by sagarkardani** [comment]
Is there any tentative timeline for this feature to be available ?

Regards,
Sagar

**Comment by dillibabu1802** [comment]
Hi @sagarkardani,

We planned to implement the active viewport rendering and include in our upcoming main release 2022 Volume 1 which is expected to be rolled out on March 2022 tentatively.

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.
