### ISSUE TITLE
abnormal behaviour on tap on graph legend

### ISSUE THREAD

**Issue by moazamadrobz** [syncfusion/flutter-widgets#504]
hey!! i am getting abnormal behaviour when I tap on legend to toggle visibility of graph data, some times respective slice not hide on tap on legend and sometimes only label hides. I am using following code

                   SfCircularChart(
                    palette: providerData.legendColorsList,
                    legend: Legend(
                      isVisible: true,
                      overflowMode: LegendItemOverflowMode.wrap,
                      position: LegendPosition.top,
                      height:
                          "100%", // take as mush space as required to display legends complete list
                    ),
                    series: <CircularSeries>[
                      PieSeries<GraphModel, String>(
                          radius: "100%",
                          animationDuration: 0,
                          legendIconType: LegendIconType.circle,
                          dataSource: providerData.chartData,
                          xValueMapper: (GraphModel data, _) => data.title,
                          yValueMapper: (GraphModel data, _) => data.value,
                          dataLabelSettings: const DataLabelSettings(
                              isVisible: true,
                              textStyle: TextStyle(fontSize: 16)))
                    ],
                  ),

![graph](https://user-images.githubusercontent.com/85628504/147101322-89a956aa-fbee-4d18-83f5-5e039d976515.PNG)
![graph2](https://user-images.githubusercontent.com/85628504/147101323-44590a4d-f519-447c-9bae-2ff1fa640225.PNG)
![graph3](https://user-images.githubusercontent.com/85628504/147101325-9c4fdf66-f458-49b6-8831-9eba540302d0.PNG)

and I have attached graphs screenshot where legend toggle property showing abnormal behaviour

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @moazamadrobz,

Greetings from Syncfusion. We have analyzed your query and we have tried to reproduce the reported issue regarding data label and pie slice is not hide when respective legend toggled. The reported issue is not reproduced at our end. so, we suggest to ensure with the latest version of chart package. Kindly find the updated package below.

Pub: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.38

If you still face any issue, kindly try to reproduce the issue in the below attached sample and provide the replication steps, this will be helpful in providing the solution earlier.

Sample: [pie_series.zip](https://github.com/syncfusion/flutter-widgets/files/7771267/pie_series.zip)

Regards,
Yuvaraj.
