### ISSUE TITLE
for the undefined MouseCursor error try to add import 'package:flutter/rendering.dart';

### ISSUE THREAD

**Issue by yassinedevop** [syncfusion/flutter-widgets#505]

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @yassinedevop ,

Greetings from Syncfusion. We are not aware of which widget you are facing this problem. So, kindly get back to us with the widget in which the issue is replicated, that will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.
