### ISSUE TITLE
undefined MouseCursor error

### ISSUE THREAD

**Issue by yassinedevop** [syncfusion/flutter-widgets#506]
for the undefined MouseCursor error, try to add import 'package:flutter/rendering.dart'; in the files where the error is shown

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @yassinedevop ,

Greetings from Syncfusion. We are not aware of which widget you are facing this problem. So, kindly get back to us with the widget in which the issue is replicated, that will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by yassinedevop** [comment]
in pdfviewer.dart I got an error here :
 SystemMouseCursor _cursor = SystemMouseCursors.basic;
the error was that SystemMouseCursor is undefined, after bothering with the code a I found that adding the line "import 'package:flutter/rendering.dart';" fixed the problem

**Comment by dillibabu1802** [comment]
Hi @yassinedevop 

We suspect that the reported error might be due to older stable versions reference. We recommend to refer the latest stable version - https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_2.8.1-stable.zip 
Then, please remove the added import statement and run the analyze command.

Regards,
Dilli babu.

**Comment by Sandeshshanbhag** [comment]
Hi Yuvaraj-Gajaraj

We are facing the issue with below file. 
File : "package:syncfusion_flutter_core/src/legend/legend.dart"

Error : 
The getter 'SystemMouseCursors' isn't defined for the class '_LegendItemState'.
 - '_LegendItemState' is from 'package:syncfusion_flutter_core/src/legend/legend.dart' ('../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-19.4.47/lib/src/legend/legend.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'SystemMouseCursors'.
            cursor: SystemMouseCursors.click,
                    ^^^^^^^^^^^^^^^^^^

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Sandeshshanbhag ,


Greetings from Syncfusion. We are not aware of which widget you are facing this problem with. So, kindly get back to us with the widget in which the issue is replicated, that will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.
