### ISSUE TITLE
Selecting text issue

### ISSUE THREAD

**Issue by Soedq** [syncfusion/flutter-widgets#508]
when I select text with background color the getSelectText return text without spaces!! ex -> 'hellopleasfixthisissue'.

**Comment by deepika134** [comment]
Hi Soedq,

We tried to reproduce the reported issue with provided details, but the selected text is shown as like in PDF. We have prepared a sample for your reference which can be downloaded in the following link , https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_app_508-1770545500.zip

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika Ravi
