### ISSUE TITLE
Calendar controller: is possible to trigger ontap event on calendar cell (programmatically)?

### ISSUE THREAD

**Issue by khangpt** [syncfusion/flutter-widgets#51]
When I explorer the **CalendarController** (view type is **CalendarView**._month_), I wonder why not have any solution to manually tap on calendar cell by programmarically. I have already tried **selectedDate** setter of **CalendarController**, but nothing happened.

Any solution for this scenarios? Thanks so much

**Comment by Indumathi1195R** [comment]
Hi @khangpt ,

Currently, we are validating this requirement “**Firing onTap callback when programmatically tapping the date in Flutter event calendar**”. We will validate and update you the further details on or before November 17, 2020. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi @khangpt ,

We have checked your requirement of “**Providing a support for Selected date changed callback in the Flutter event calendar**” in the Flutter event calendar. As of now, the calendar doesn’t support the onTap event programmatically and we have logged a feature request for the same. 
  
At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest and demands. We will implement this feature in any of our upcoming releases. We will let you know once the feature is implemented. We appreciate your patience until then.  
   
We are closing this incident now. You can also communicate with us regarding the open features any time using our Feature Report page.   
  
Please upvote this feature to make this our priority. While this feature itself is important we will prioritize the features every release, based on the user demands. So, this feature will be available in any of our upcoming releases.
   
**Feedback link:**  https://www.syncfusion.com/feedback/19687/providing-a-support-for-selected-date-changed-callback-in-the-flutter-event
   
If you have any more specifications/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.  

Regards,
Indumathi R
