### ISSUE TITLE
SfSliderTheme does not support text alignment

### ISSUE THREAD

**Issue by samdogg7** [syncfusion/flutter-widgets#510]
Feature request:
Currently SfSliderThemeData does not support text alignment. 

I would like to utilize `TextAlign.center`, but only have access to `TextStyle` (which does not support alignment).

![Example](https://user-images.githubusercontent.com/1322743/147291473-78caeac0-7edb-4173-bfa0-575923327254.png)

**Comment by SuryaChinnadurai** [comment]
Hi samdogg7,

There is no direct support to achieve your requirement and we are checking the possible workarounds from our end. We will update you regarding this further on 29th December 2021.

Please let us know if you need any further assistance in this.

Regards,
Surya C

**Comment by PraveenGopalsamy** [comment]
Hi samdogg7,
 
We have considered your request as a feature and the status can be tracked from the feedback portal link.
 
Feedback: https://www.syncfusion.com/feedback/31551/need-label-text-alignment-support-in-sfslider
 
We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal.
 
**Disclaimer:** The date for this feature implementation is tentative and not a commitment on our parts.
 
Regards,
Praveen G.
