### ISSUE TITLE
[SfDateRangePicker] How to use only one action button?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#511]
Hi, I am trying to use only one action button but "showActionButtons" shows 2. 
Is there a workaround to use only one?

I'd like to use "todayButton" and "confirmButton" only

**Comment by Indumathi1195R** [comment]
Hi Team,

Thank you for contacting Syncfusion support.

**Regarding Query: How to use only one action button?**

Based on the shared information, we have checked and your requirement is “Showing one action button in SfDateRangePicker”. As per the current implementation of the picker, we have shown both action buttons while enabling [showActionButtons](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/SfDateRangePicker/showActionButtons.html) property and it is an expected one in the Flutter date range picker.

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
