### ISSUE TITLE
[SfDataGrid] Long press on any cell in summary row throws error

### ISSUE THREAD

**Issue by dantsushko** [syncfusion/flutter-widgets#514]
It seems that _getDataCellBase function does not properly handle the case, when dataRow.rowType == RowType.tableSummaryRow

I/flutter (22256): ---------- ERROR ----------
I/flutter (22256): Null check operator used on a null value
I/flutter (22256): [2021-12-27 12:34:08.553576 | Catcher | INFO] #0      RenderVirtualizingCellsWidget._getDataCellBase (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/rendering_widget.dart:1275:20)
I/flutter (22256): [2021-12-27 12:34:08.553836 | Catcher | INFO] #1      RenderVirtualizingCellsWidget._onLongPressStart (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/rendering_widget.dart:1298:16)
I/flutter (22256): [2021-12-27 12:34:08.553918 | Catcher | INFO] #2      LongPressGestureRecognizer._checkLongPressStart.<anonymous closure> (package:flutter/src/gestures/long_press.dart:711:75)
I/flutter (22256): [2021-12-27 12:34:08.554265 | Catcher | INFO] #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
I/flutter (22256): [2021-12-27 12:34:08.554426 | Catcher | INFO] #4      LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:711:11)
I/flutter (22256): [2021-12-27 12:34:08.554803 | Catcher | INFO] #5      LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:615:5)
I/flutter (22256): [2021-12-27 12:34:08.555162 | Catcher | INFO] #6      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:591:5)
I/flutter (22256): [2021-12-27 12:34:08.555272 | Catcher | INFO] #7      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:535:41)

**Comment by Sangeetha-Raju** [comment]
Hi @dantsushko,

We have logged a bug report for reported issue. And we will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on 4th January 2022. 
 
Please refer to the feedback link below for further follow up,
 
**Feedback link:**  https://www.syncfusion.com/feedback/31500/null-check-operator-exception-is-thrown-when-long-press-the-table-summary-rows  
 
We will let you know once it gets rolled out. We appreciate your patience until then. Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.

**Comment by ashok-kuvaraja** [comment]
Hi @dantsushko,

Sorry for the inconvenience.

Unfortunately, we couldn't include the fix for the reported issue on January 4th weekly pub release. We will include the changes in our next weekly pub release which is scheduled to be rolled out on 11th January 2021.

We appreciate your patience until then.

Regards,
Ashok K

**Comment by RenugaSadagoban98** [comment]
Hi @dantsushko ,

The reported issue “The null check operator exception will no longer be thrown when long press the table summary rows” has been resolved and we have included the changes in our weekly pub release. Please update your datagrid package to the 19.4.42 version. You can also refer to the following pub link.

link: https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.4.42


Regards,
Renugadevi

**Comment by dantsushko** [comment]
Thank you

**Comment by RenugaSadagoban98** [comment]
Hi @dantsushko ,  
 
Please let us know if you need any other assistance. We will be happy to assist you. 
 
Regards, 
Renugadevi
