### ISSUE TITLE
How to change active divider height?

### ISSUE THREAD

**Issue by alpitebiztrait** [syncfusion/flutter-widgets#516]
I want to change the active divider height and I have to check all the points but didn't get any option for this.
https://prnt.sc/253w12c

**Comment by PraveenGopalsamy** [comment]
Hi alpitebiztrait ,
 
You can customize the divider size using the [activeDividerRadius](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeDividerRadius.html) and [inactiveDividerRadius](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveDividerRadius.html) properties in the [SfRangeSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfRangeSliderThemeData-class.html). Kindly refer to the link below for more details.   
  
Link: https://help.syncfusion.com/flutter/range-slider/labels-and-divider#divider-radius

![image](https://user-images.githubusercontent.com/83585210/147760066-514729e5-71dc-41bd-a8a7-224ffd492c96.png)
 
Please let us know if you need further assistance with this.   
 
Regards,
Praveen G.
