### ISSUE TITLE
How to show tool tip below the slider and can we change the tool tip UI or customise the tool tip UI?

### ISSUE THREAD

**Issue by alpitebiztrait** [syncfusion/flutter-widgets#518]
I want to set the tooltip below the slider and also want to change the UI and I want to show like [this](https://prnt.sc/257p56a).
Thank in advance

**Comment by PraveenGopalsamy** [comment]
Hi alpitebiztrait,

Currently, there is no direct support to show the tooltip at bottom of the range slider. So, we meet your requirement using [startThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/startThumbIcon.html) and [endThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/endThumbIcon.html) properties and prepared a sample for your reference.
 
```
late SfRangeValues _values;
late NumberFormat _numberFormat;
late TextEditingController _rangeStartController;
late TextEditingController _rangeEndController;

Widget _buildThumbIcon(TextEditingController controller) {
  return Transform.translate(
    // Here 25 is the size of thumb(20) and Spacing(5).
    offset: const Offset(0, 25),
    child: OverflowBox(
      maxWidth: 150,
      child: TextField(
        textAlign: TextAlign.center,
        decoration:
            const InputDecoration(border: InputBorder.none, isDense: true),
        controller: controller,
      ),
    ),
  );
}

String _getFormattedText(dynamic value) {
  return _numberFormat.format(value);
}

@override
void initState() {
  _values = const SfRangeValues(3.0, 7.0);
  _numberFormat = NumberFormat('#.## €');
  _rangeStartController = TextEditingController();
  _rangeEndController = TextEditingController();
  super.initState();
}

@override
void dispose() {
  _rangeStartController.dispose();
  _rangeEndController.dispose();
  super.dispose();
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfRangeSlider(
      min: 0.0,
      max: 10.0,
      startThumbIcon: _buildThumbIcon(_rangeStartController),
      endThumbIcon: _buildThumbIcon(_rangeEndController),
      values: _values,
      onChanged: (SfRangeValues newValues) {
        setState(() {
          _rangeStartController.text = _getFormattedText(newValues.start);
          _rangeEndController.text = _getFormattedText(newValues.end);
          _values = newValues;
        });
      },
      onChangeEnd: (SfRangeValues newValues) {
        _rangeStartController.text = "";
        _rangeEndController.text = "";
      },
    ),
  );
}
```
We hope that this solution will fulfill your requirement. Kindly let us know if you need further assistance with this.

Regards,
Praveen G.

**Comment by SivaElite** [comment]
This looks good but can we display tooltip all the time?

**Comment by LokeshPalani** [comment]
Hi @SivaElite,

Greetings from Syncfusion. 

Yes, you can display the tooltip all the time with the help of the [shouldAlwaysShowTooltip](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fslider%2Ftooltip&data=05%7C01%7Clokesh.palani%40syncfusion.com%7C41a412d14f6a4e6308b008daad155266%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638012604362098580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SOi36QsWf3e19I5MdDOeOuMMuntfcqk6aQslhzCIyLc%3D&reserved=0) property in SfSlider.

For more details about tooltip, please refer below user guide.
[https://help.syncfusion.com/flutter/slider/tooltip](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.syncfusion.com%2Fflutter%2Fslider%2Ftooltip&data=05%7C01%7Clokesh.palani%40syncfusion.com%7C41a412d14f6a4e6308b008daad155266%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638012604362098580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SOi36QsWf3e19I5MdDOeOuMMuntfcqk6aQslhzCIyLc%3D&reserved=0)

Regards,
Lokesh Palani.

**Comment by vinayOB** [comment]
> Hi alpitebiztrait,
> 
> Currently, there is no direct support to show the tooltip at bottom of the range slider. So, we meet your requirement using [startThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/startThumbIcon.html) and [endThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/endThumbIcon.html) properties and prepared a sample for your reference.
> 
> ```
> late SfRangeValues _values;
> late NumberFormat _numberFormat;
> late TextEditingController _rangeStartController;
> late TextEditingController _rangeEndController;
> 
> Widget _buildThumbIcon(TextEditingController controller) {
>   return Transform.translate(
>     // Here 20 is thumb diameter and 5 is spacing between thumb and text.
>     offset: const Offset(0, 25),
>     child: OverflowBox(
>       maxWidth: 150,
>       child: TextField(
>         textAlign: TextAlign.center,
>         decoration:
>             const InputDecoration(border: InputBorder.none, isDense: true),
>         controller: controller,
>       ),
>     ),
>   );
> }
> 
> String _getFormattedText(dynamic value) {
>   return _numberFormat.format(value);
> }
> 
> @override
> void initState() {
>   _values = const SfRangeValues(3.0, 7.0);
>   _numberFormat = NumberFormat('#.## €');
>   _rangeStartController = TextEditingController();
>   _rangeEndController = TextEditingController();
>   super.initState();
> }
> 
> @override
> void dispose() {
>   _rangeStartController.dispose();
>   _rangeEndController.dispose();
>   super.dispose();
> }
> 
> @override
> Widget build(BuildContext context) {
>   return Scaffold(
>     body: SfRangeSlider(
>       min: 0.0,
>       max: 10.0,
>       startThumbIcon: _buildThumbIcon(_rangeStartController),
>       endThumbIcon: _buildThumbIcon(_rangeEndController),
>       values: _values,
>       onChangeStart: (SfRangeValues newValues) {
>         _rangeStartController.text = _getFormattedText(newValues.start);
>         _rangeEndController.text = _getFormattedText(newValues.end);
>       },
>       onChanged: (SfRangeValues newValues) {
>         setState(() {
>           _rangeStartController.text = _getFormattedText(newValues.start);
>           _rangeEndController.text = _getFormattedText(newValues.end);
>           _values = newValues;
>         });
>       },
>       onChangeEnd: (SfRangeValues newValues) {
>         _rangeStartController.text = "";
>         _rangeEndController.text = "";
>       },
>     ),
>   );
> }
> ```
> 
> We hope that this solution will fulfill your requirement. Kindly let us know if you need further assistance with this.
> 
> Regards, Praveen G.

Hey thanks for this but how can I also implement the custom thumb widget now?

**Comment by VijayakumarMariappan** [comment]
@vinayOB Created a separate ticket for your query. Please use this link for further tracking: https://github.com/syncfusion/flutter-widgets/issues/2282.
