### ISSUE TITLE
How to change selected page

### ISSUE THREAD

**Issue by ducdac** [syncfusion/flutter-widgets#519]
I am using syncfusion_flutter_datagrid: 19.4.40 , How to change selected page index of SfDataPager?
Here is part of the code: 
`SfDataPager(
delegate: dataSource,
initialPageIndex: control.tableConfig.page!,
pageCount: control.tableConfig.total >= 10
    ? (control.tableConfig.total / 10).ceil() as double
    : 1,
direction: Axis.horizontal,
))`.
i changed initialPageIndex but it didn't change.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi Ducdac,

Greetings from Syncfusion.

Based on provided information, we are not able to reproduce your reported issue. Its working fine at our end. We have prepared a sample for your reference.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main720716504

Please check the above sample and revert us if you still facing the same issue? If yes, please provide the following details,

1. Which Flutter channel (Stable, beta or Master) are you using?
2. Issue replicating platform.

If we misunderstood anything, please modify the above sample based on your requirement. It will be helpful for us to check on it and provide you the solution at the earliest.

Regards,
Tamilarasan Paranthaman
