### ISSUE TITLE
How to apply search and filter for one column in SfDataGrid?

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#52]
How we can  search a column from SFGrid by using search bar.

**Comment by NeelakandanKannan** [comment]
Hi @waqaryounusjatt788 ,

We have already considered the feature to filter the columns through interactive UI. Please refer the below feedback link,
https://www.syncfusion.com/feedback/16318/support-to-filter-the-columns-through-ui

Can you please confirm whether you want to highlight the searched text in the cells like below screenshot?
![image](https://user-images.githubusercontent.com/42242041/98931759-718b8d00-2504-11eb-8ea3-b8c0b6cef548.png)

**Comment by waqaryounusjatt788** [comment]
Thnaks
