### ISSUE TITLE
How to show only sum of category when I have more than one value for CategoryAxis

### ISSUE THREAD

**Issue by naeimlotfali** [syncfusion/flutter-widgets#520]
I want to use column chart and CategoryAxis type for primaryXAxis, there is more than one value for each type of category and I need to show only the sum of values on each column. Also arrangeByIndex is  false.
![image](https://user-images.githubusercontent.com/45904349/148023318-45c54cb0-0ff6-43ed-bf15-a51fcf12fe79.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @naeimlotfali,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that our chart has an onDataLabelRender callback to customize the data label render. Here we have used onDataLabelRender callback and sum the value when having more than one value then render a data label which data point has the greater y value. We have attached the sample and code snippet below for your reference. 

Code snippet:
```dart
onDataLabelRender: (DataLabelRenderArgs args) {
    //Other required information
    }
```

Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/7858264/github_529.2.zip)


We hope this will help you to achieve your requirement.

Regards,
Yuvaraj.

**Comment by naeimlotfali** [comment]
> Hi @naeimlotfali,
> 
> Greetings from Syncfusion. We have analyzed your query and we would like to let you know that our chart has an onDataLabelRender callback to customize the data label render. Here we have used onDataLabelRender callback and sum the value when having more than one value then render a data label which data point has the greater y value. We have attached the sample and code snippet below for your reference.
> 
> Code snippet:
> 
> ```dart
> onDataLabelRender: (DataLabelRenderArgs args) {
>     //Other required information
>     }
> ```
> 
> Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/7858264/github_529.2.zip)
> 
> We hope this will help you to achieve your requirement.
> 
> Regards, Yuvaraj.

Hi @Yuvaraj-Gajaraj 
Thanks for your response. I checked the sample code but still have a problem. The labels of columns are now showing the correct number, same as I wanted, but in Y-axis it is not on the correct value.
![image](https://user-images.githubusercontent.com/45904349/149612577-14654434-b329-46ed-8506-dc5402730d6f.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @naeimlotfali,

We have analyzed your query and we have created the method **getSumOfData** that returns data list after adding the y values whose x values are same and removes the duplicate data. By using this you can achieve your requirement and we also attached the sample for your requirement.

Code snippet:

```dart
List<ChartData> getSumOfData(List<ChartData> chartData) {
    // Sum the y value of the duplicate data
  }
```

Sample: [sample](https://github.com/syncfusion/flutter-widgets/files/7889924/github_529.zip)

Regards,
Yuvaraj.

**Comment by naeimlotfali** [comment]
> Hi @naeimlotfali,
> 
> We have analyzed your query and we have created the method **getSumOfData** that returns data list after adding the y values whose x values are same and removes the duplicate data. By using this you can achieve your requirement and we also attached the sample for your requirement.
> 
> Code snippet:
> 
> ```dart
> List<ChartData> getSumOfData(List<ChartData> chartData) {
>     // Sum the y value of the duplicate data
>   }
> ```
> 
> Sample: [sample](https://github.com/syncfusion/flutter-widgets/files/7889924/github_529.zip)
> 
> Regards, Yuvaraj.

Hi @Yuvaraj-Gajaraj 
Thanks a lot. That was exactly what I wanted.
Best regards,
Naeim.
