### ISSUE TITLE
[Charts] String Axis Label

### ISSUE THREAD

**Issue by Yosiwealth** [syncfusion/flutter-widgets#522]
Please is it possible to have the xValueMapper accept strings intead of double, i want my x axis label to be : [Jan, Fed,Mar,Apr] not [1,2,3,4]

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Yosiwealth ,

Greetings from Syncfusion. We have analyzed your query and we would like to let you know that our chart supports for CategoryAxis, by using this you can bind the string values to chart using the xValueMapper. We have also provided a user guide and sample below for your reference.

User guide: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#category-axis

Sample: https://flutter.syncfusion.com/#/cartesian-charts/axis-types/category/default-category-axis

Regards,
Yuvaraj.
