### ISSUE TITLE
Is there a way to increment the max zoom?

### ISSUE THREAD

**Issue by FabianGrob** [syncfusion/flutter-widgets#528]
I mean, that i can zoom a pdf even more than the actual limit.

**Comment by deepika134** [comment]
Hi FabianGrob,

At present we do not have support to set the maximum zoom level beyond the default zoom level in Flutter SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
 https://www.syncfusion.com/feedback/26648/support-to-set-minimum-and-maximum-zoom-level 

Regards,
Deepika Ravi
