### ISSUE TITLE
[syncfusion_flutter_gauges] SfRadialGauge - problem for lower values in RangePointer with curved cornerStyle

### ISSUE THREAD

**Issue by charlou-aredidon** [syncfusion/flutter-widgets#530]
As you can see in the image below. The one on the right side showed a **sharp** corners instead of **curved**. 

I'm using:
- `RangePointer` with `cornerStyle: CornerStyle.bothCurve`

![image](https://user-images.githubusercontent.com/90191659/148915406-103ccfb3-ff37-4aff-9cb5-d81a61ef7cac.png)

### Full sample code

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_gauges/gauges.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const SampleWidget(),
    );
  }
}

class SampleWidget extends StatelessWidget {
  const SampleWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const value = 15;
    return Scaffold(
      appBar: AppBar(
        title: const Text('SfRadialGauge sample'),
      ),
      body: Center(
        child: SizedBox(
          height: 256,
          width: 256,
          child: SfRadialGauge(
            enableLoadingAnimation: true,
            axes: <RadialAxis>[
              RadialAxis(
                minimum: 0,
                maximum: 100,
                labelsPosition: ElementsPosition.outside,
                ticksPosition: ElementsPosition.outside,
                minorTicksPerInterval: 4,
                interval: 25,
                tickOffset: 5,
                axisLineStyle: const AxisLineStyle(
                  cornerStyle: CornerStyle.bothCurve,
                  thickness: 20,
                ),
                pointers: [
                  RangePointer(
                    value: value.toDouble(),
                    cornerStyle: CornerStyle.bothCurve,
                    color: Colors.blue,
                    width: 20,
                  ),
                ],
                annotations: <GaugeAnnotation>[
                  GaugeAnnotation(
                    widget: Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            "${value.toInt()}%",
                            style: const TextStyle(
                              fontSize: 28,
                            ),
                          ),
                          const Text(
                            'percent',
                            style: TextStyle(
                              fontSize: 14,
                            ),
                          ),
                        ],
                      ),
                    ),
                    angle: 90,
                    positionFactor: 0,
                  ),
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

### Steps to reproduce
- Simply edit the `value` variable from smallest (`1`). It will show sharp corners instead of curved.
- Set the `value` something higher like `55` and it will show properly curved corners.

**Comment by eleojasmil** [comment]
this is happening to me too. :(

**Comment by PraveenGopalsamy** [comment]
Hi,
 
We can reproduce the reported issue at our end, and we need some more time to validate this issue in the source level, so we will update you the details on Jan 17th, 2022.

Please let us know if you need any further assistance in this
 
Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi,
 
We have considered your request as an improvement in our [SfRadialGauge](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/gauges-library.html) source. The status of this feature can be tracked from the following feedback portal link.
 
**Feedback:** https://www.syncfusion.com/feedback/31915/improve-the-rangepointer-cornerstyle-calculation-when-the-values-are-low
 
We will prioritize the features every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal. 
 
**Disclaimer:** The date for this feature implementation is tentative and not a commitment on our parts.
 
Please let us know if you need any further assistance in this.

**Comment by eleomilagrosa** [comment]
Yes, Finally.

Looking forward for the fix.

**Comment by blitzdose** [comment]
Sorry for responding to a closed Issue but this is still an issue 1,5 years later. Do you know if this is going to be fixed? I cannot find any information about it here https://www.syncfusion.com/feedback/31915/improve-the-rangepointer-cornerstyle-calculation-when-the-values-are-low

**Comment by RomanPreis** [comment]
This is not fixed and should not have been closed, I'm also facing the same issue

**Comment by lxy8228535** [comment]
I'm also facing the same issue, but I don't have a  method to solve it
