### ISSUE TITLE
[syncfusion_flutter_charts] Column chart with 2 series cut off at edge

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#531]
Hi,
I am having a `SfCartesianChart` which displays 2 column series. At the left end of the x-axis, only one column is showing, because the other one is "outside" the visible region of the chart.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/8345062/148979464-6b85e12b-b21a-4da9-ad5f-96405b35a90e.png">

Is there a way to automatically offset the columns so that they are shown to the right of their respective x-value? It should also work with 3 or more columns of course.

**Comment by WieFel** [comment]
@Yuvaraj-Gajaraj thank you very much! This indeed solved most of my problem.
One thing I am missing now however with the `DateTimeCategoryAxis`:
```dart
...
primaryXAxis: DateTimeCategoryAxis(
  desiredIntervals: _desiredIntervals,
  // disable vertical grid lines
  majorGridLines: const MajorGridLines(width: 0),
  minimum: min,
  maximum: max,
  visibleMinimum: min,
  visibleMaximum: max,
)
```
Only categories that are present within the data are shown. The set `max` (00:00 of the following day) on the chart is basically ignored. (`min`=00:00 today, `max`=00:00 tomorrow, `_desiredIntervals`=max-min / intervalSize=6)
<img width="225" alt="image" src="https://user-images.githubusercontent.com/8345062/149893103-d8033dfa-04c0-49b3-8969-d9519d130aad.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @WieFel,

Sorry for the inconvenience, we have analyzed your query and we need time on this and will update you in two business days.

Regards,
Yuvaraj.

**Comment by WieFel** [comment]
> Hi @WieFel,
> 
> Sorry for the inconvenience, we have analyzed your query and we need time on this and will update you in two business days.
> 
> Regards, Yuvaraj.

Meanwhile I could circumvent the problem by "filling up" missing categories until `max` with `null` values and set `emptyPointSettings` to `gap`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @WieFel,

Thanks for the update, and happy to hear that the issue was fixed by your side. If you have any further queries, please get back to us.

Regards,
Yuvaraj.
