### ISSUE TITLE
[syncfusion_flutter_charts] Trackball builder

### ISSUE THREAD

**Issue by devasidmi** [syncfusion/flutter-widgets#532]
Hey guys, really nice library! Do you have any plans to add trackballBuilder with current index as parameter? Now I can't create trackball without white circle in the middle with custom colors + if I want use image in my multiple trackballs, i can't change it properties (color, image (different images for trackballs) and etc) based on index of trackball

Example of custom single trackball
<img width="360" alt="image" src="https://user-images.githubusercontent.com/20377394/149134156-94c38157-e181-47d8-a6a8-4d2bb28bc122.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @devasidmi,

We have analyzed the customer query and we would like to let you know that with the trackball builder itself, we can get the series index and point index and using this, you can show the different image as per your requirement. We already have demo sample for this requirement and can be found below,

https://flutter.syncfusion.com/#/cartesian-charts/user-interactions/trackball/customized-trackball 

To remove the white space inside the marker, you can make use of the markerSettings property in the trackball behavior find the code snippet and API documentation below.

Code snippet: 
```dart
SfCartesianChart(
        trackballBehavior: TrackballBehavior(
          markerSettings: TrackballMarkerSettings(color: Colors.blue)
        ),
)

```

API documentation: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballMarkerSettings-class.html 

Regards,
Yuvaraj.

**Comment by devasidmi** [comment]
Thanks for the answer, I think i was bad at explaining my problem. I have a screenshot from your example app, where selected trackballs have large white circle in the center
<img width="429" alt="image" src="https://user-images.githubusercontent.com/20377394/149600873-7916cb01-0d62-4540-b3ce-b5456cee70c7.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @devasidmi,

Thanks for the information. We suspect that you wish to render marker similar to other markers which are not selected. If so, then you can hide the visibility of the trackball marker setting then it looks like a normal. We have attached the code snippet below for your reference, we hope it will help you to achieve your requirement.

Code snippet:
```dart
trackballBehavior: TrackballBehavior(
          enable: true,
          markerSettings: const TrackballMarkerSettings(
            markerVisibility: TrackballVisibilityMode.hidden,
          ),
      )
```

Screenshot:
![image](https://user-images.githubusercontent.com/61863686/149960247-dec8b48c-b987-4d4b-902c-28771ffb0e39.png)

Regards,
Yuvaraj.
