### ISSUE TITLE
App crashes when rendering pdf 

### ISSUE THREAD

**Issue by tjuros01** [syncfusion/flutter-widgets#533]
Error happens on version 19.4... versions.

Log:

`
 thread #1, queue = 'com.apple.main-thread', stop reason = Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value
    frame #1: 0x000000010e00a3d0 syncfusion_flutter_pdfviewer`SwiftSyncfusionFlutterPdfViewerPlugin.getImageForPlugin(index=24, scale=2, documentID="392ca8c0-73ac-11ec-93ff-af185f3a40e3", self=<unavailable>) at SwiftSyncfusionFlutterPdfViewerPlugin.swift:124 [opt]
   121 	   
   122 	    private func getImageForPlugin(index: Int,scale: CGFloat,documentID: String) -> FlutterStandardTypedData
   123 	    {
-> 124 	        let document = self.documentRepo[documentID]!!
   125 	        let page = document.page(at: Int(index))
   126 	        var pageRect = page!.getBoxRect(.mediaBox)
   127 	        let imageRect = CGRect(x: 0,y: 0,width: pageRect.size.width*CGFloat(scale),height: pageRect.size.height*CGFloat(scale))
Target 0: (Runner) stopped.
`

**Comment by dillibabu1802** [comment]
Hi @tjuros01 

Thank you for contacting Syncfusion support.

We tried to reproduce the reported issue from our side, but the documents were loaded properly in iOS simulators. So, kindly share the PDF document in which you are facing the issue and also share the following details, to reproduce the reported issue in our end.

    1. Issue reproducing document and steps.
    2. Device Specification.
    3. Flutter Doctor log.
    4. syncfusion_flutter_pdfviewer package version.
    5. Flutter SDK version.

This will be helpful to investigate further and provide the solution at the earliest.

Regards,
Dilli babu.
