### ISSUE TITLE
Colors changing while zooming/panning in CandleSticks Chart

### ISSUE THREAD

**Issue by guilo8914** [syncfusion/flutter-widgets#534]
Hey, I've been trying to use a candlesticks chart while panning and zooming to see more details for the chart.  When doing so, the colors sometimes change, what should be a loss reported as green, gain as red, sometimes they are random.

I believe the issue is based off the bottom legend, zooming makes so it changes the interval below and that seems to cause this weird behaviour of changing the colors.

What I mean by it just having the following causes the weird behaviour in Candlesticks charts

`zoomPanBehavior: ZoomPanBehavior(
  zoomMode: ZoomMode.x,
  enablePinching: true,
  enablePanning: true,
  maximumZoomLevel: 0.2
),`

Hey, I figured it out.  The coloring of the candlesticks are based off a set order, and whichever appear on screen gets painted based on that order - if it is zoomed in and the third candlestick is showing, it will instead paint with whatever color the first value should be painted instead.
Should be noted the HiloOpenCloseSeries, which has similar functionality and types, doesn't have this problem

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @guilo8914,

Greetings from Syncfusion. We have analyzed your query and the reported issue is reproduced at our end, so we have considered this as a bug, we will fix the issue and rolled out in our next weekly patch release which is expected to be rolled out on 8th January 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by RomanIvnitzki** [comment]
Any updates on this issue?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @RomanIvnitzki,

As we stated earlier the issue will be fixed and roll out in our next weekly patch release. we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by guilo8914** [comment]
> Any updates on this issue?

Hey, sorry for the abstinence.  I managed to make a way around this issue.  Instead of letting the code render the color, I made so when I'm creating a new ChartSampleData, I'm also passing a new variable Color as segmentColor. and within the constructor of the ChartSampleData, it will check if the close value is lower or equal than open, giving it the color green or red:

`class ChartSampleData{
  final DateTime x;
  final num open, close;
  final low, high;
  final Color segmentColor;

  ChartSampleData(this.x,this.open,this.close) :
      this.low = close,
      this.high = open,
      this.segmentColor = (close >= open) ? Colors.green : Colors.red;

  @override
  String toString() {
    return 'ChartSampleData{x: $x, open: $open, close: $close}';
  }
}`

Then, within the chart widget CandleSeries, passing parameters as X, low, high, close and open, I also pass in the segment color as pointColorMapper, as seen here:

`series: <CandleSeries>[
            CandleSeries<ChartSampleData,DateTime>(
              enableSolidCandles: true,
              dataSource: _chartData,
              xValueMapper: (ChartSampleData sales, _) => sales.x,
              lowValueMapper: (ChartSampleData sales, _) => sales.low,
              highValueMapper: (ChartSampleData sales, _) => sales.high,
              closeValueMapper: (ChartSampleData sales, _) => sales.close,
              openValueMapper: (ChartSampleData sales, _) => sales.open,
              pointColorMapper: (ChartSampleData sales, _) => sales.segmentColor,
            )
          ],`
          
The app will have to spend extra computation/time to build up and calculate the new ChartSampleData objects and their color, but it works out in the end.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @guilo8914,

As we stated earlier the reported issue is fixed, it will be roll out in our weekly patch release on 8th Feb 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @guilo8914,

Thanks for your patience. The reported issue regarding candle series color getting changed during zoom and pan the chart is fixed and rolled in our weekly patch release. To avoid this issue kindly update the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.50

Regards,
Yuvaraj.
