### ISSUE TITLE
add support to Windows

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#535]
add support to Windows

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @insinfo,

Greetings from Syncfusion. We are unable to understand your requirement from your recent update. So, could you please provide us with more information on which widget you want the windows support? This will be helpful in providing the solution earlier.

Thanks,
Yuvaraj.

**Comment by insinfo** [comment]
Flutter PDF Viewer

**Comment by dillibabu1802** [comment]
Hi @insinfo ,

At present we do not have support to render in Windows platform. We planned to implement the Windows platform and include in our upcoming main release 2022 Volume 1 which is expected to be rolled out in March 2022 tentatively.

The status of implementation can be tracked through the below feedback link,
[https://www.syncfusion.com/feedback/27240/windows-support-for-flutter-pdfviewer](https://www.syncfusion.com/feedback/27240/windows-support-for-flutter-pdfviewer)

Regards,
Dilli babu

**Comment by insinfo** [comment]
any update on this?

**Comment by deepika134** [comment]
Hi @insinfo ,

We have implemented the windows support in Flutter PdfViewer, which is available at the following link,
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.47-beta  

We are glad to announce that our Essential Studio 2022 Volume 1 Main Release V20.1.0.47 is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/174125/essential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download  

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Deepika Ravi
