### ISSUE TITLE
[syncfusion_flutter_charts] Leftmost y-axis gets cut off when having multiple y-axes

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#536]
In the use cases of my app, charts can have up to 9 series and thus 9 different y-axes. The chart is made very wide, e.g. 1000 pixels width and horizontally scrollable.

In that case, the leftmost y-axis is almost completely cut off:
![image](https://user-images.githubusercontent.com/8345062/149313841-605f4f88-c545-4005-b051-e17850cb64f1.png)

To make it more clear, here is also a video where I scroll outside to the left, using the scrollbar:
![Screen Recording 2022-01-13 at 11 29 58(1)](https://user-images.githubusercontent.com/8345062/149314764-bcc3b008-5f08-420b-ae65-2c45a62c0062.gif)

Also when having only 7 axes, they are already cut off:
![image](https://user-images.githubusercontent.com/8345062/149313925-87f60b44-088a-4271-9f58-64f3eae1a112.png)

It seems that the higher the axis count, the more is cut off. Meanwhile I can resolve the problem by adding some padding around the chart. But the issue is, I can't predict how much padding will be needed to fit the axes entirely into view.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @WieFel,

Greetings from Syncfusion. We have analyzed your query and the reported issue is reproduced at our end, so we have considered this as a bug, we will fix the issue and rolled out in our next weekly patch release which is expected to be rolled out on 8th January 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by WieFel** [comment]
@Yuvaraj-Gajaraj  FYI: the same problem occurs also with "interior" axes, for example in real-time charts which force the y-axis to change it's values over time. E.g. at the beginning, the axes have some width, according to their current number values. But if the values change over time, the width might not be correct anymore:

At the beginning -> all fine:
![image](https://user-images.githubusercontent.com/8345062/152176875-a251ccad-25ba-4092-a64d-2b60411ff0d1.png)

After some live-data updates -> axes distorted:
![image](https://user-images.githubusercontent.com/8345062/152176714-6ea37723-314c-41af-b172-58ffa374ec4d.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @WieFel,

Thanks for your patience. The reported issue regarding the left-most y-axis label getting cutoff is fixed and rolled in our weekly patch release. To avoid this issue kindly update the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.50

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @WieFel,

We are having main releases at 3 months once, so the GitHub repository will get an update after the main release. If you want to access the latest source you need to refer to the `syncfusion_flutter_charts` from the `pub.dev`. Then for what purpose do you need to merge your changes into that repository can you explain this.

Regards,
Yuvaraj.
