### ISSUE TITLE
[syncfusion_flutter_charts] TrackballDetails.groupingModeInfo.visibleSeriesList missing series that are visible, but go outside y-axis max value

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#538]
Hi,

sorry for posting so many issues... ;)
I have a column chart which has a max value defined on its y-axis (3000 kWh).
When showing the values e.g. for a single day, everything works fine. The chart displays the columns and the trackball tooltip shows all the necessary values:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8345062/149916153-93935abe-39f1-4025-a96e-8f95bc0f67a9.png">

When I display the data for e.g. 1 entire week, the values for some columns rise over the fixed max of 3000, which is also fine and the chart displays it correctly.
However, when I swipe through the chart, columns that rise over the defined max value of the y-axis, don't appear in the `TrackballDetails.groupingModeInfo.visibleSeriesList`, which I would expect them to. Is it possible to customize this behaviour?
<img width="364" alt="image" src="https://user-images.githubusercontent.com/8345062/149916237-367478fb-9557-44f3-9bf9-ffdbc6af7d94.png">

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

Greetings from syncfusion. We have analyzed your query from our side. We were unable to achieve the customer requirement in the workaround because in our chart widget we've only displayed the visible data points in the trackball tooltip and ignored the data points which are placed outside of the display viewport.

If you have any further queries, please get back to us.

Thanks,
Yuvaraj.

**Comment by WieFel** [comment]
@Yuvaraj-Gajaraj thank you. So that also applies if the data points are actually in the visible viewport of the x-axis, but only rise above the max y-value of the y-axis, right?

Is there any way to circumvent this?
Probably I will have to take a look at the code myself I suppose...

**Comment by LokeshPalani** [comment]
Hi @WieFel,
 
We would like to let you know that currently we don’t have support for **"Including series details that are not in the visible range for the trackball tooltip"**. However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.
 
We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.
 
**FR Link,**
https://www.syncfusion.com/feedback/50845/include-the-series-details-that-fall-within-the-x-visible-range-but-not-in-the-y
 
Regards,
Lokesh P.
