### ISSUE TITLE
[syncfusion_flutter_charts 19.4.43] - this version disabled override method **drawDataMarker**

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#539]
code below used to work with 19.4.38,
the green circles become default black circles after upgrading to 19.4.43.
when downgrade to 19.4.38, it works again.

```dart
SfCartesianChart(
         series: <ChartSeries<ChartData, int>>[
            ScatterSeries<ChartData, int>(
              onCreateRenderer: (ChartSeries<dynamic, dynamic> series) {
                return CustomRenderer();
              },
            // Other information
          ],
        ),


class CustomRenderer extends ScatterSeriesRenderer {
  CustomRenderer();

  @override
  void drawDataMarker(int index, Canvas canvas, Paint fillPaint, Paint strokePaint, double pointX, double pointY,
      [CartesianSeriesRenderer? seriesRenderer]) {
    final Paint customerStrokePaint = Paint();
    customerStrokePaint.color = Colors.green;
    customerStrokePaint.strokeWidth = 1;
    customerStrokePaint.style = PaintingStyle.stroke;
    canvas.drawCircle(Offset(pointX, pointY), 6, customerStrokePaint);
  }
}

```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

Greetings from Syncfusion. We have analyzed the provided code snippet from our side and the drawDataMarker() override method doesn’t work as expected. So, we have achieved your requirement by using markerSettings property of ScatterSeries. Please find the modified code snippet below. Please let us know if you have any other queries.

Code snippet:
```dart
ScatterSeries(
   markerSettings: const MarkerSettings(
     color: Colors.transparent,
     borderWidth: 4,
     height: 12,
     width: 12,
     isVisible: true,
     borderColor: Colors.green,
   ),
   // Other required information
)
```

Regards,
Yuvaraj.

**Comment by FisherWL** [comment]
@Yuvaraj-Gajaraj 
I use green circle as an example to simplify the question, it's also the example you used in [https://github.com/syncfusion/flutter-widgets/issues/494](https://github.com/syncfusion/flutter-widgets/issues/494)

In actual situation, I want to draw a rotated triangle.
```dart
class CustomCornerRenderer extends ScatterSeriesRenderer {
  CustomCornerRenderer();

  @override
  void drawDataMarker(int index, Canvas canvas, Paint fillPaint, Paint strokePaint, double pointX, double pointY,
      [CartesianSeriesRenderer? seriesRenderer]) {
    final Paint customerStrokePaint = Paint();
    customerStrokePaint.color = Colors.white;
    customerStrokePaint.strokeWidth = 1;
    customerStrokePaint.style = PaintingStyle.stroke;
    // canvas.drawCircle(Offset(pointX, pointY), 6, customerStrokePaint);

    var path = Path();
    path.moveTo(pointX - 4.5, pointY + 4.5);
    path.lineTo(pointX + 4.5, pointY);
    path.lineTo(pointX - 4.5, pointY - 4.5);
    path.close();
    canvas.drawPath(path, fillPaint);
    canvas.drawPath(path, customerStrokePaint);
  }
}
```



I didn't add the custom markers as an image because  [https://github.com/syncfusion/flutter-widgets/issues/344](https://github.com/syncfusion/flutter-widgets/issues/344)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @FisherWL,

We have analyzed your scenario at our end and we would like to let you know that if you want to render customer marker for scatter series using the **drawDataMarker** method, then you will have to provide **animationDuration** for the series as '0' so that the **drawDataMarker** works properly in scatter series.
```
ScatterSeries(
   animatioDuration: 0,
   // Other required information
)
```

Also, if you need the initial rendering animation for the series, then you can use the line series with width set to '0' such that custom marker only will get rendered in the series with animation.
```
LineSeries(
    width: 0
    // other configurations..
)
```

Please get back to us if you require further assistance.

Regards,
Sriram Kiran

**Comment by FisherWL** [comment]
@Yuvaraj-Gajaraj @SriramKiranSenthilkumar
thx for the response but it (19.4.43 with animatioDuration: 0) doesn't work on my end.

same code with 19.4.38 vs 19.4.43: 
(triangle is expected rather than default circle)

![Screen Shot 2022-01-21 at 12 41 07 AM](https://user-images.githubusercontent.com/57275868/150495237-a7ae9baf-58b9-4a4e-8ab7-1003eaa87263.png)

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(ChartApp());
}

class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            SfCartesianChart(
              primaryXAxis: CategoryAxis(),
              series: <ChartSeries<SalesData, String>>[
                ScatterSeries<SalesData, String>(
                  dataSource: [
                    SalesData('Jan', 35),
                    SalesData('Feb', 28),
                    SalesData('Mar', 34),
                    SalesData('Apr', 32),
                    SalesData('May', 40)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  onCreateRenderer: (series) => CustomCornerRenderer(),
                  animationDuration: 0,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class SalesData {
  SalesData(this.year, this.sales);

  final String year;
  final double sales;
}

class CustomCornerRenderer extends ScatterSeriesRenderer {
  CustomCornerRenderer();

  @override
  void drawDataMarker(int index, Canvas canvas, Paint fillPaint, Paint strokePaint, double pointX, double pointY,
      [CartesianSeriesRenderer? seriesRenderer]) {
    final Paint customerStrokePaint = Paint();
    customerStrokePaint.color = Colors.white;
    customerStrokePaint.strokeWidth = 1;
    customerStrokePaint.style = PaintingStyle.stroke;

    var path = Path();
    path.moveTo(pointX - 4.5, pointY + 4.5);
    path.lineTo(pointX + 4.5, pointY);
    path.lineTo(pointX - 4.5, pointY - 4.5);
    path.close();
    canvas.drawPath(path, fillPaint);
    canvas.drawPath(path, customerStrokePaint);
  }
}
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

We have analyzed your query and the reported issue is already fixed and rolled out for Vol 4 SP release. We will let you know once it gets rolled out, we appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Thanks for your patience. The reported issue has been fixed and rolled out in our Vol 4 SP release, to avoid this issue please upgrade the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.48

Regards,
Yuvaraj.
