### ISSUE TITLE
the pdf containe chinese can't be printed

### ISSUE THREAD

**Issue by wrjcs** [syncfusion/flutter-widgets#54]
Hello,I using the code like 
https://github.com/syncfusion/flutter-widgets/issues/3
you give me.
It can generate chinese in pdf but I can't be printed.
this is open in pdf
![image](https://user-images.githubusercontent.com/7202194/99151421-6028b900-269b-11eb-8587-6df33d510155.png)
this is prview before print
![image](https://user-images.githubusercontent.com/7202194/99151433-6d45a800-269b-11eb-8640-7f8d8baccba6.png)
It can only print the symbol ","

**Comment by wrjcs** [comment]
this is the pdf, I generate.
[Output.pdf](https://github.com/syncfusion/flutter-widgets/files/5541045/Output.pdf)

**Comment by Anand3595** [comment]
Hi wrjcs,

We are checked the provided PDF document in our devices and taken screenshots for your reference. The adobe viewer and print preview in our devices are working as expected. Please find the screenshots below,

Viewing PDF document in adobe reader mobile,
![1](https://user-images.githubusercontent.com/72250552/99487565-a6786380-298c-11eb-9a57-bb762c1ad058.jpg)

Print preview in mobile device,
![2](https://user-images.githubusercontent.com/72250552/99487592-b2fcbc00-298c-11eb-9657-758601a39a96.jpg)

Please provide the following details, it will more helpful for us to analyze further and update you.

Android version
PDF viewer
Flutter version.
You can also try our TTF font support to draw the CJK text with supported fonts. For this we can use PdfTrueTypeFont class with appropriate font data as bas64String or list of bytes. Or else we can also load TTF font data from Google Fonts package as explained in https://www.syncfusion.com/kb/11976/how-to-draw-unicode-text-in-a-pdf-file-using-google-fonts-package .

Please find the more details to draw text with PdfTrueTypeFonts from https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-truetype-fonts .

With Regards,
Anand Panchamoorthi
