### ISSUE TITLE
[syncfusion_flutter_pdfviewer] [FEATURE REQUEST] Implement cached PDF

### ISSUE THREAD

**Issue by jeff-odopass** [syncfusion/flutter-widgets#542]
Hello here !

I'm thinking about switching to `syncfusion_flutter_pdfviewer`, however the cache is a feature I really need.
Is it planned that `syncfusion_flutter_pdfviewer` will support caching, like with a simple `true`/`false` parameter?

Thanks for your answer

**Comment by deepika134** [comment]
Hi jeff-odopass,

Thank you for contacting Syncfusion support.

Currently, Flutter PdfViewer doesn't provide cache support for the loaded documents. We need to know more about your requirement to analyze on the requested feature so kindly share us your complete requirement along with use cases.

If you are using a [network](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewer/SfPdfViewer.network.html) constructor to load a PDF document, then sample level caching can be done by retrieving document bytes once and reuse it through the app instance. The following code example illustrates the sam

```
Uint8List? _documentBytes;
@override
void initState() {
  getPdfBytes();
  super.initState();
}

///Get the PDF document as bytes
void getPdfBytes() async {
  _documentBytes = await http.readBytes(Uri.parse(
      'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf'));
  setState(() {});
}

@override
void dispose() {
  _documentBytes = null;
  super.dispose();
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text('Syncfusion Flutter PDF Viewer'),
    ),
    body: _documentBytes != null
        ? SfPdfViewer.memory(
            _documentBytes!,
          )
        : Container(),
  );
}
```
Regards,
Deepika Ravi

**Comment by jeff-odopass** [comment]
Hello Deepika, thank you for your answer.
Your solution does work, even if it is not as practical as a plugin integrated feature.

You can close this, I should have thought about this before opening this issue :D
