### ISSUE TITLE
[syncfusion_flutter_pdfviewer] - PDF zoom level ?

### ISSUE THREAD

**Issue by tranvanphay** [syncfusion/flutter-widgets#544]
Hello,
I have try to use this library to load the PDF document, this is a great library. Currently, I want to set zoom level, is there any way to do it ?

**Comment by deepika134** [comment]
Hi tranvanphay,

Kindly refer to the following UG link to set the zoom level in SfPdfViewer.
https://help.syncfusion.com/flutter/pdf-viewer/magnification#change-the-zoom-level-factor-programmatically

Regards,
Deepika Ravi
