### ISSUE TITLE
[syncfusion_flutter_gauges] Please add code to the sample images

### ISSUE THREAD

**Issue by adrianvintu** [syncfusion/flutter-widgets#546]
I have tried to create a gauge like the first one in this image https://cdn.syncfusion.com/content/images/FTControl/Flutter/Annotation.png but I have no idea how to do it.

Can you please provide sample configuration and maybe add it to the documentation.

Maybe to it for all the cool image samples as well?

**Comment by SuryaChinnadurai** [comment]
Hi adrianvintu,
 
We have already added samples for you mentioned cases in our Sample browser. Check the below links to create a gauge sample for the attached images.
 
Text annotation - https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/gauge/showcase/distance_tracker.dart
Multiple text annotation - https://github.com/syncfusion/flutter-examples/blob/master/lib/samples/gauge/annotation/direct_compass.dart
Image annotation - https://flutter.syncfusion.com/#/radial-gauge/gauge-annotation/temparature-tracker.
 
Please let us know if you need any further assistance in this.
 
Regards,
Surya C.

**Comment by adrianvintu** [comment]
Awesome, can you please add this to the documentation on pub.dev? Maybe with links to each file/implementation?
Thank you very much!

**Comment by SuryaChinnadurai** [comment]
Hi adrianvintu,

Yes, we will consider adding these details in the pub.dev documentation.

Regards,
Surya C.
