### ISSUE TITLE
[syncfusion_flutter_datagrid] changing mouse pointer to hand when hovering over a row

### ISSUE THREAD

**Issue by vaibhav891** [syncfusion/flutter-widgets#547]
Hi,
I wish to change the mouse pointer from arrow to hand when I hover over row in DataGrid. So that user knows that it is clickable. Kindly help in how I could achieve this.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @vaibhav891 ,

DataGrid provides support to load the MouseRegion widget in the data cells. You can load the MouseRegion widget to the corresponding cell of **DataGridRowAdaptor** in the **DataGridSource.buildRow** method. Please check the following code snippet.

**Code snippet:**
@override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return **MouseRegion(
          cursor: selectionMode != SelectionMode.none
              ? SystemMouseCursors.click
              : SystemMouseCursors.basic,
          child: Container(
              alignment: Alignment.center,
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              child: Text(
                dataGridCell.value.toString(),
                overflow: TextOverflow.ellipsis,
              )));**
    }).toList());
  }
}

As per your requirement, we have prepared a sample with a MouseRegion widget. If the row is selectable, you can change the cursor type to hand when hovering a row. Please check the following sample.

**Sample Link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/main89278300

We hope this helps. Please let us know if you need any further assistance.

Regards,
Tamilarasan

**Comment by vaibhav891** [comment]
Hi @Tamilarasan-Paranthaman Thanks for all the support on this. This is what I was looking for. Thanks. 👍
