### ISSUE TITLE
HiloOpenCloseSeries in chart

### ISSUE THREAD

**Issue by evangelme** [syncfusion/flutter-widgets#55]
i think there is a bug 
if low and high and open and close are the same equal it dose not show anything
i hope u can fix this.
thank u for ur awosoome project.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @evangelme,

Greetings from Syncfusion. We have analyzed your scenario and we would like to share some information regarding the data point indication feature of the financial chart series which when enabled shows indication for datapoints when its high and low values are same or open and close values or high, low, open and close values are the same. To enable this feature, you can set the **`showIndicationForSameValues`** to **_true_**.  Please check the code snippet below for reference.
```
SfCartesianChart(
               series: <ChartSeries>[
                 HiloOpenCloseSeries<ChartData, double>(
                     showIndicationForSameValues: true, // Indication feature enabled
                     dataSource: chartData,
                      xValueMapper: (ChartData data, _) => data.x,
                      highValueMapper: (ChartData data, _) => data.high,
                      lowValueMapper: (ChartData data, _) => data.low,
                      openValueMapper: (ChartData data, _) => data.open,
                      closeValueMapper: (ChartData data, _) => data.close)
                ]
)
```

The following are the types of indication when the combination of high, low, open and close values are the same for a data point.

- In the OHLC chart, if the open and close values are same then a horizontal line will be drawn at that value by default.
- If the high and low values are same and with **`showIndicationForSameValues`** property set to _**true**_ then, a thin vertical line is drawn and if API is set to false, the line will not be drawn.

For further reference on the **`showIndicationForSameValues`** property, please check the link below.
https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/HiloOpenCloseSeries/showIndicationForSameValues.html

Please get in touch with if you would require further assistance on this.

Regards,
Sriram Kiran
