### ISSUE TITLE
want to Turn on Edit mode on cell focus by pressing tab key. its working on tap button i want it to work also on keyboard tabkey.

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#555]
in syncfusion datagrid edit mode work on f2 or on single and double tap.  butt i want it to working also on tab key press with focus come in tab how to turn on edit mode

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar 

DataGrid supports to perform custom functionalities for keypress actions of the keyboard. As per your requirement, you can achieve the requirement with “Entering the edit mode when pressing the Tab key” by writing custom logic for the **TAB** key via **handleKeyEvent** method from **CustomSelectionManager** class by extending the **RowSelectionManager** class. We have prepared a sample for that, please check the following sample. 

**Code Snippet:**

```dart
class CustomSelectionManager extends RowSelectionManager {
  CustomSelectionManager(this.controller);

  DataGridController controller;

  @override
  void handleKeyEvent(RawKeyEvent keyEvent) {
    if (keyEvent.logicalKey == LogicalKeyboardKey.tab) {
      super.handleKeyEvent(keyEvent);
      controller.beginEdit(controller.currentCell);
      return;
    }
    super.handleKeyEvent(keyEvent);
  }
}

```
**Sample Link**:  https://www.syncfusion.com/downloads/support/directtrac/general/ze/main1315311054

We have already provided examples in our UG documentation. Please go through this,

**UG Document Link**:  https://help.syncfusion.com/flutter/datagrid/selection#customizing-selection-behavior

We hope this helps. If we misunderstood anything, please modify the above sample based on your requirement. It will be helpful for us to check on it and provide you with the solution at the earliest.   

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
perfect answer thanks
