### ISSUE TITLE
[syncfusion_flutter_xlsio] how to hide columns/rows ?

### ISSUE THREAD

**Issue by andrewwahid** [syncfusion/flutter-widgets#556]
How to hide columns and rows ?
I cannot find a 'hidden' property anywhere in your openxml implementation
is it not implemented or is there something I am missing ?

**Comment by andrewwahid** [comment]
#557

**Comment by SivakumarRamya** [comment]
Hi Andrewwahid,

Greetings from Syncfusion.

Thanks for contributing the changes to the library. But the API structure has to be validated and approved by Syncfusion.
We will validate and share the details on February 2, 2022. 

Regards,
Ramya.

**Comment by SivakumarRamya** [comment]
Hi Andrewwahid,

Appreciate your patience.

We have validated your request and found that your code changes doesn’t meet our API standards. So, we have planned to implement it on our end and logged a feature request “Hide rows and columns on Excel workbook creation”. We will include the changes of this implementation on **February 15, 2022**. 

You can track the status of defect report through following feedback link.

Track Status: https://www.syncfusion.com/feedback/32376/hide-rows-and-columns-on-excel-workbook-creation
