### ISSUE TITLE
do we have option to super trend indicator and Fibonacci pivot point in this plugin?

### ISSUE THREAD

**Issue by indiamaster** [syncfusion/flutter-widgets#563]

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @indiamaster,

Greetings from Syncfusion. We are not aware of which widget you are facing this problem with. So, kindly get back to us with the widget in which the issue is replicated, that will be more helpful to us to provide a solution sooner.

Regards,
Yuvaraj.

**Comment by indiamaster** [comment]
Hi @Yuvaraj-Gajaraj  thanks for your response, I'm trying to create a candle chart using the `SfCartesianChart` widget, there need to add super trend and Fibonacci pivot point indicator.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @indiamaster,

Thanks for your information. Currently, we don't have support for super trend and Fibonacci pivot point indicators, but we have considered as a feature request for this requirement and logged feedback. This will be available in any of our upcoming releases, and you can track the status of the feature below

Feedback: https://www.syncfusion.com/feedback/15987

Regards,
Yuvaraj.
