### ISSUE TITLE
[SfDataGrid] Possible to build entire rows?

### ISSUE THREAD

**Issue by Wizzel1** [syncfusion/flutter-widgets#565]
I want to build a sortable, paged listview and your datagrid looks like exactly what I need. 

However, I'd like to animate the rows on hover like this :

https://user-images.githubusercontent.com/43343510/151974342-6683af0f-d6fd-4d3c-b11d-be1470543d63.mov

So I would need to wrap the cells / row in an animated container. Do you think thats possible?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Wizzel1 

Greetings from Syncfusion.

Currently, DataGrid does not have support for animating the rows when hovering on it. We have considered your requirement as a feature request. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,

**Feedback link:** https://www.syncfusion.com/feedback/32354/support-to-animate-the-rows-when-hover-on-it

Regards,
Tamilarasan P
