### ISSUE TITLE
[Cartesian Charts]-[multiple column series]-column placement chaos

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#566]
full code is shown below,
expected:
(1,35) and (2,37) are next to each other;
(5,28) and (6,18) are next to each other;
(6,18) and (8,34) are not conflicting;
...
each column width == 1

![Simulator Screen Shot - iPhone 8 Plus - 2022-02-01 at 22 35 10](https://user-images.githubusercontent.com/57275868/152106207-2d3ebeb4-51cd-4410-937c-51e15c4db030.png)

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(ChartApp());
}

class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            SfCartesianChart(
              primaryXAxis: NumericAxis(
                minimum: 30,
                visibleMinimum: 0,
                majorGridLines: const MajorGridLines(width: 0.5),
                interval: 1,
                edgeLabelPlacement: EdgeLabelPlacement.shift,
              ),
              primaryYAxis: NumericAxis(),
              series: <ChartSeries<SalesData, int>>[
                ColumnSeries<SalesData, int>(
                  dataSource: [
                    SalesData(1, 35),
                    SalesData(5, 28),
                    SalesData(8, 34),
                    SalesData(12, 32),
                    SalesData(15, 40)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  color: Colors.amber,
                  width: 1,
                ),
                ColumnSeries<SalesData, int>(
                  dataSource: [
                    SalesData(2, 37),
                    SalesData(6, 18),
                    SalesData(10, 54),
                    SalesData(13, 22),
                    SalesData(18, 10)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  color: Colors.blue,
                  width: 1,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class SalesData {
  SalesData(this.year, this.sales);

  final int year;
  final int sales;
}
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Greetings from syncfusion. We have analyzed your query and you set the width of the column as 1, and our default value of the width for column series is 0.7, spacing is 0. To render the column as expected, we suggest setting space as 0.7. find the code below to accomplish this

Code snippet:
```dart
SfCartesianChart(
  series: <ChartSeries<SalesData, int>>[
     ColumnSeries<SalesData, int>(
       // Other required properties
       spacing: 0.7,
       width: 1,
     ),
   ],
)
```

Hope this helps.

Regards,
Yuvaraj.

**Comment by FisherWL** [comment]
@Yuvaraj-Gajaraj 
there're still issues after setting width to 0.7:
1,2 not adjoining;
5,6 not adjoining;
13,15 not supposed to adjoining;
etc.

![Simulator Screen Shot - iPhone 12 Pro Max - 2022-02-03 at 06 25 27](https://user-images.githubusercontent.com/57275868/152361921-d08d1842-c026-4d3a-913a-46623197e9dc.png)

**Comment by FisherWL** [comment]
@Yuvaraj-Gajaraj 
it becomes worse when series number increase,
when series # == 3:
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-02-03 at 06 34 57](https://user-images.githubusercontent.com/57275868/152363673-69cfe533-a4a2-4f22-960d-daef6f8dc990.png)

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(ChartApp());
}

class ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: Scaffold(
        appBar: AppBar(),
        body: Column(
          children: [
            SfCartesianChart(
              primaryXAxis: NumericAxis(
                minimum: 30,
                visibleMinimum: 0,
                majorGridLines: const MajorGridLines(width: 0.5),
                interval: 1,
                edgeLabelPlacement: EdgeLabelPlacement.shift,
              ),
              primaryYAxis: NumericAxis(),
              series: <ChartSeries<SalesData, int>>[
                ColumnSeries<SalesData, int>(
                  dataSource: [
                    SalesData(1, 35),
                    SalesData(5, 28),
                    SalesData(8, 34),
                    SalesData(12, 32),
                    SalesData(15, 40)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  color: Colors.amber,
                  width: 0.7,
                ),
                ColumnSeries<SalesData, int>(
                  dataSource: [
                    SalesData(2, 37),
                    SalesData(6, 18),
                    SalesData(10, 54),
                    SalesData(13, 22),
                    SalesData(18, 10)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  color: Colors.blue,
                  width: 0.7,
                ),
                ColumnSeries<SalesData, int>(
                  dataSource: [
                    SalesData(3, 47),
                    SalesData(7, 11),
                    SalesData(9, 51),
                    SalesData(14, 42),
                    SalesData(17, 19)
                  ],
                  xValueMapper: (SalesData sales, _) => sales.year,
                  yValueMapper: (SalesData sales, _) => sales.sales,
                  color: Colors.purple,
                  width: 0.7,
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class SalesData {
  SalesData(this.year, this.sales);

  final int year;
  final int sales;
}
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

We are analyzing the scenario, we will update the status in two business days. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Thanks for being patience. We have analyzed the reported scenario with the competitors using the numeric axis with the data you have provided, most of them are having the same behavior. For your convenience, we have attached the images and sample of [high chart](https://jsfiddle.net/e9f0412c/) and fl_chart for your reference.

| First Header  | Second Header |
| ------------- | ------------- |
|![image](https://user-images.githubusercontent.com/61863686/154930534-22b5fff0-6466-4ef7-b1f1-9e03d8c5632f.png)|![image](https://user-images.githubusercontent.com/61863686/154930562-8853c71f-7985-4dba-80f7-6557ae0a46cf.png)|

Here have taken the range based on the values in the series points and we will position the rect based on a particular point. For example, if we are having two series with x-values ranges from 1 to 10. Now for the x-value 2, since there are two series it may have two points to plot on it, so based on this the position will be calculated irrespective of empty points. 
In the CategoryAxis if the plot area width is 500px and having 5 data point then each column will have 100px. Here we have width of column as 0.7 then each column will occupy the 70px from 100px and with the balance 30px, 15px gap will be occupied at left and right side of the column. 
So, we suggest to use category axis for your scenario or if you wish to continue to use numeric axis, kindly customize the column width and spacing based on your scenario.

Sample: [i365084.zip](https://github.com/syncfusion/flutter-widgets/files/8108168/i365084.zip)

Regards,
Yuvaraj.

**Comment by FisherWL** [comment]
@Yuvaraj-Gajaraj 
thx, I ended up using `pointColorMapper`
