### ISSUE TITLE
How to get a pdf file path when using a network to share it?

### ISSUE THREAD

**Issue by majidebraa** [syncfusion/flutter-widgets#567]
How to get a pdf file path when using a network to share it?

**Comment by AnanthaGokulaRaman** [comment]
Hi @majidebraa,

Kindly use this following code reference to get a pdf using network link,

>   Future<void> LoadPDF() async {
    String url = 'http://www.africau.edu/images/default/sample.pdf';
    //Load the PDF document
    final PdfDocument document =
        PdfDocument(inputBytes: await _readUrlDocumentData(url));
    List<int> bytes = document.save();
    Directory directory = await getApplicationSupportDirectory();
    String path = directory.path;
    File('$path/output.pdf').writeAsBytesSync(bytes);
    OpenFile.open('$path/output.pdf');
  }
>
>  ////import 'package:flutter/services.dart';
  //Future<List<int>> _readAssetDocumentData(String name) async {
  //  final ByteData data = await rootBundle.load('assets/pdf/$name');
  //  return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  //}
>
>  //import 'package:flutter/services.dart';
  Future<List<int>> _readUrlDocumentData(String url) async {
    return (await NetworkAssetBundle(Uri.parse(url)).load(url))
        .buffer
        .asUint8List();
  }

Kindly use the following link to know more about the Syncfusion Flutter PDF loading and saving capabilities, https://help.syncfusion.com/flutter/pdf/loading-and-saving-document

Regards,
Anantha Gokula Raman J

**Comment by majidebraa** [comment]
Hi, @AnanthaGokulaRaman PdfDocument no access to import it to my project. I use syncfusion_flutter_pdfviewer: ^19.4.48-beta and I just Uint8List of pdf file a no need to save it. On the other hand, if I use the _readUrlDocumentData method, the file download twice and it's bad. if you add one line :
PdfProvider get provider => _provider;
in SfPdfViewer class problem solve and can get Uint8List by:
var uint8List = await sfPdfViewer.provider.getPdfBytes(context);

**Comment by deepika134** [comment]
Hi majidebraa c,

We have prepared the sample to get a PDF file from a URL. The sample can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/load_a_pdf_from_memory1054903349.zip 

Regards,
Deepika Ravi.

**Comment by majidebraa** [comment]
@deepika134 
Thanks a lot!
