### ISSUE TITLE
Unable to load local PDF files in Android Samsung Galaxy mobile

### ISSUE THREAD

**Issue by hemandroid** [syncfusion/flutter-widgets#568]
Hi, I'm using Android Samsung galaxy M51 mobile with version 11. I'm unable to load the local PDF files using 

`syncfusion_flutter_pdfviewer: ^19.4.47-beta`

Which is throwing the below error.

`I/flutter ( 9747): [E]  Caught error: MissingPluginException(No implementation found for method closeDocument on channel syncfusion_flutter_pdfviewer)
I/flutter ( 9747): [E]  #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
I/flutter ( 9747): <asynchronous suspension>
I/flutter ( 9747): #1      PdfViewerPlugin.closeDocument (package:syncfusion_flutter_pdfviewer/src/common/pdfviewer_plugin.dart:109:7)
I/flutter ( 9747): <asynchronous suspension>
I/flutter ( 9747): [E]  In dev mode. Not sending report to Sentry.io.`

**Comment by deepika134** [comment]
Hi hemandroid,

We tried to reproduce the reported issue with provided details, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample (along with the output screenshot of the same) and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample19196540.zip
and also, you can refer to the following UG to load a PDF document from internal storage in SfPdfViewer,
https://help.syncfusion.com/flutter/pdf-viewer/getting-started#load-document-from-the-file

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in the sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi Vinayak Ranjane,

We have implemented the closeDocument() method in syncfusion_flutter_pdfviewer, Please  see the following link,
https://github.com/syncfusion/flutterwidgets/blob/194afe6f24944c0d998bf2edc92e1a70e851e036/packages/syncfusion_flutter_pdfviewer/android/src/main/java/com/syncfusion/flutter/pdfviewer/SyncfusionFlutterPdfViewerPlugin.java#L170 
Kindly upgrade to the latest version of syncfusion_flutter_pdfviewer: ^19.4.50-beta, if the reported issue still reproduces on your end, then use the flutter pub cache clean command to clear the pub cache and check again.

Regards,
Deepika Ravi

**Comment by kkiigg** [comment]
Hello:
I am in a same situation ,and the link above is not accessable.
the plugin verison in my project is 24.1.41.

/flutter (12454): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceInfo on channel dev.fluttercommunity.plus/device_info)
E/flutter (12454): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (12454): #1      MethodChannelDeviceInfo.deviceInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19:10)
E/flutter (12454): #2      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:54:38)
E/flutter (12454): #3      SfPdfViewerState._findDevice (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2598:45)
E/flutter (12454): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getDeviceInfo on channel dev.fluttercommunity.plus/device_info)
E/flutter (12454): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (12454): #1      MethodChannelDeviceInfo.deviceInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19:10)
E/flutter (12454): #2      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:54:38)
E/flutter (12454): #3      SfPdfViewerState._findDevice (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2598:45)
