### ISSUE TITLE
Increase xAxis Clickable area &amp; rounded border and background color

### ISSUE THREAD

**Issue by nikunjramialtais** [syncfusion/flutter-widgets#569]
I have integrated chart in flutter. i got click event of xAxis label but i want in increase clickable area of x-axis label and want to show selected xAxis with rounded background color.
Check x Axis with value 15 . i want to show like this and increase click area, currently its working text click which is not responsive i
<img width="508" alt="Screenshot 2022-02-04 at 2 13 06 PM" src="https://user-images.githubusercontent.com/97666701/152526580-0d5aed0b-6016-429b-a70b-c669abd277de.png">
n

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @nikunjramialtais,
 
Greetings from Syncfusion. Using the axisLabelFormatter callback in the axis, you can customize the appearance of the axis label and using the onAxisLabelTapped callback, stored the tapped axis label index and in axisLabelFormatter callback customized the label. And the clickable region can't be increased dynamically. We have attached the sample below for your reference. 
 
Sample: https://www.syncfusion.com/downloads/support/forum/172581/ze/f172581-1120139646  
  
Regards, 
Yuvaraj.
