### ISSUE TITLE
marker_pointer_renderer.dart:607:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.  - 'WidgetsBinding'

### ISSUE THREAD

**Issue by Joldersman** [syncfusion/flutter-widgets#570]
after upgrading flutter & dart

`../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-19.4.48/lib/src/radial_gauge/pointers/marker_pointer_renderer.dart:607:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!
                     ^
../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-19.4.48/lib/src/chart/base/chart_base.dart:1792:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Developer/flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {`

flutter doctor -v
[✓] Flutter (Channel master, 2.11.0-0.0.pre.452, on macOS 11.6.3 20G415 darwin-arm,
    locale en-EN)
    • Flutter version 2.11.0-0.0.pre.452 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba01ec8faa (35 hours ago), 2022-02-05 22:05:18 -0500
    • Engine revision 0712096899
    • Dart version 2.17.0 (build 2.17.0-85.0.dev)
    • DevTools version 2.10.0

**Comment by PraveenGopalsamy** [comment]
Hi Joldersman,

We have checked the mentioned query with our [flutter gauge – 19.4.48](https://pub.dev/packages/syncfusion_flutter_gauges/versions/19.4.48) version with Flutter stable channel. We cannot reproduce the mentioned issue from our side. Could you please confirm the version and channel which you are using. This will help us to assist you in a better way by reproducing the exact same scenario which you are facing.

Please let us know if you need any further assistance in this.
 
Regards,
Praveen G.

**Comment by PraveenGopalsamy** [comment]
Hi,

We would like to let you know that the our [Syncfusion Flutter Gauge](https://www.syncfusion.com/flutter-widgets/flutter-radial-gauge) supports the latest Flutter [Stable](https://docs.flutter.dev/development/tools/sdk/releases?tab=windows) version. This issue is not reproduced with the latest Flutter stable version at our end. Could you please let us know in which Flutter channel you are reproducing this issue?

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by Joldersman** [comment]
> Hi,
> 
> We would like to let you know that our [Syncfusion Flutter Gauge](https://www.syncfusion.com/flutter-widgets/flutter-radial-gauge) supports the latest Flutter [Stable](https://docs.flutter.dev/development/tools/sdk/releases?tab=windows) version. This issue is not reproduced with the latest Flutter stable version at our end. Could you please let us know in which Flutter channel you are reproducing this issue?
> 
> Regards, Praveen G.
With Flutter Channel stable, 2.10.1 -all works fine. Thank you.
