### ISSUE TITLE
syncfusion radial chart edges gets cut

### ISSUE THREAD

**Issue by gauria24** [syncfusion/flutter-widgets#571]
![image](https://user-images.githubusercontent.com/97582254/152969898-dd8bc5e7-10dd-42f6-8ad6-2a1e39a7625c.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

We have analyzed your query, and the reported issue is not reproduced at our end. Here we have attached the sample which we have used for testing. Kindly try to replicate with the sample and get back to us with the sample, this will be more helpful to us to provide a solution sooner.

Sample: [i366045.zip](https://github.com/syncfusion/flutter-widgets/files/8033013/i366045.zip)


Regards,
Yuvaraj.

**Comment by gauria24** [comment]
Hi Team, 
I have analyzed the syncfusion-radial chart's code and found that above issue occurs when we give  radius: '100%',
In your above sample code I tried giving radius '100%' it was giving same issue.

![image](https://user-images.githubusercontent.com/97582254/153348072-84af8928-1b80-4834-b24d-db94024f7fe2.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @gauria24,

The reported issue is already fixed, it will roll out in our next weekly patch release, it will be expected on 15th Feb 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @gauria24,

The reported issue has been fixed and rolled out in our weekly patch release, to avoid this issue please upgrade the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.52

Regards,
Yuvaraj.

**Comment by gauria24** [comment]
Hi @Yuvaraj-Gajaraj 
Thank you !
