### ISSUE TITLE
[SfDataGrid] How do you remove datagrid scrollbar?

### ISSUE THREAD

**Issue by coyksdev** [syncfusion/flutter-widgets#574]

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @coyksdev,

You can remove the scrollbar by using the ScrollConfiguration widget. Wrap the DataGrid as a child of ScrollConfiguration and set the scrollbar as false in the behaviour property. We have prepared the sample for that. Please check the following sample and code snippet.

**Code snippet**:
``` dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: ScrollConfiguration(
        behavior: ScrollConfiguration.of(context).copyWith(scrollbars: false),
        child: SfDataGrid(
          source: _employeeDataSource,
          columns: getColumns,
        ),
      ),
    );
  }

```

**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main1261081022

We hope this helps. Please let us know if you need any further assistance.

Regards,
Tamilarasan

**Comment by coyksdev** [comment]
@Tamilarasan-Paranthaman Thanks for the respond. However, It still shows on iOS.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @coyksdev,

Can you please let us know the purpose of removing the scrollbar from the DataGrid, i.e., the use case for removing the scrollbars? Because currently, the DataGrid scrollbar is visible only when you are trying to scroll horizontally or vertically.

Regards,
Tamilarasan

**Comment by OnesWYong** [comment]
> Hi @coyksdev,
> 
> Can you please let us know the purpose of removing the scrollbar from the DataGrid, i.e., the use case for removing the scrollbars? Because currently, the DataGrid scrollbar is visible only when you are trying to scroll horizontally or vertically.
> 
> Regards, Tamilarasan

When I'm in the RotatedBox component, the scrollbar is blurry. So I want to hide it so that the client can't see the problem

```
RotatedBox(
  quarterTurns: 1,
  child: SfDataGrid(),
);
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @OnesWYong,

Based on the provided information, we have checked the DataGrid scrollbar with the RotatedBox widget and attached the output image below. 

![1 ScrollBar](https://user-images.githubusercontent.com/93904422/180783128-b789ae24-f563-462f-bbc3-a78c54ad42d3.png)


Can you please confirm that you want to hide the scrollbar shown in the reference image?

Regards,
Tamilarasan

**Comment by OnesWYong** [comment]
> Hi @OnesWYong,
> 
> Based on the provided information, we have checked the DataGrid scrollbar with the RotatedBox widget and attached the output image below.
> 
> ![1 ScrollBar](https://user-images.githubusercontent.com/93904422/180783128-b789ae24-f563-462f-bbc3-a78c54ad42d3.png)
> 
> Can you please confirm that you want to hide the scrollbar shown in the reference image?
> 
> Regards, Tamilarasan

Thank you very much for your reply, I use the example code, and this problem still occurs. Maybe my flutter SDK version is too low?

```
➜  test_datagrid flutter --version           
Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5464c5bac7 (3 months ago) • 2022-04-18 09:55:37 -0700
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

```
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_datagrid: ^20.2.39
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @OnesWYong ,

We are a little bit unclear about your requirement. We have tested the following sample, i.e., the sample with DataGrid and the RotatedBox widget. In that sample, the DataGrid scrollbar is visible only when you are trying to scroll vertically.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample918464781 

Please check the above sample, and can you please confirm that you want to hide the scrollbar shown while scrolling?

The configuration that we have:

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1706], locale en-IN)
    • Flutter version 3.0.5 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.8.31005.135
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

```

> When I'm in the RotatedBox component, the scrollbar is blurry. So, I want to hide it so that the client can't see the problem



It would be helpful if you provided more clear details about your query. Also, we would appreciate it if you provided an image representation of the issue that you have faced. It will help us to provide the solution as soon as possible.

Regards,
Tamilarasan

**Comment by OnesWYong** [comment]
> Hi @OnesWYong ,
> 
> We are a little bit unclear about your requirement. We have tested the following sample, i.e., the sample with DataGrid and the RotatedBox widget. In that sample, the DataGrid scrollbar is visible only when you are trying to scroll vertically.
> 
> Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample918464781
> 
> Please check the above sample, and can you please confirm that you want to hide the scrollbar shown while scrolling?
> 
> The configuration that we have:
> 
> ```
> [√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1706], locale en-IN)
>     • Flutter version 3.0.5 at C:\tools\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
>     • Engine revision e85ea0e79c
>     • Dart version 2.17.6
>     • DevTools version 2.12.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
>     • Android SDK at C:\Program Files (x86)\Android\android-sdk
>     • Platform android-31, build-tools 30.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.8.5)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
>     • Visual Studio Professional 2019 version 16.8.31005.135
>     • Windows 10 SDK version 10.0.22000.0
> 
> [√] Android Studio
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • android-studio-dir = C:\Program Files\Android\Android Studio
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> ```
> 
>  > When I'm in the RotatedBox component, the scrollbar is blurry. So, I want to hide it so that the client can't see the problem
> 
> It would be helpful if you provided more clear details about your query. Also, we would appreciate it if you provided an image representation of the issue that you have faced. It will help us to provide the solution as soon as possible.
> 
> Regards, Tamilarasan

@Tamilarasan-Paranthaman Thank you very much for your reply. I've used your code and upgraded the SDK and the problem still occurs. Are you sure it's under html render? Here is my run configuration


```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "web_datagrid",
            "request": "launch",
            "type": "dart",
            "args": [
                "--web-renderer",
                "html",
            ],
        },
        {
            "name": "test_datagrid (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        },
        {
            "name": "test_datagrid (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release"
        }
    ]
}
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/ones-wy/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (13 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ones-wy/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/ones-wy/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/ones-wy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @OnesWYong,

Thanks for the update. The issue is reproduced in the html web renderer. We have also checked it with the simple sample, i.e., the SingleChildScrollView with the list of containers. The issue is reproduced in that too. We will report this issue in the framework.

Currently, DataGrid does not have support for hiding the scrollbars. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented. We appreciate your patience until then. You can follow up with the below feedback for further details,

Feedback link: https://www.syncfusion.com/feedback/36456/support-to-hide-the-scroll-bars  

Regards,
Tamilarasan

**Comment by OnesWYong** [comment]
> Hi @OnesWYong,
> 
> Thanks for the update. The issue is reproduced in the html web renderer. We have also checked it with the simple sample, i.e., the SingleChildScrollView with the list of containers. The issue is reproduced in that too. We will report this issue in the framework.
> 
> Currently, DataGrid does not have support for hiding the scrollbars. We have already considered your request as a feature. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented. We appreciate your patience until then. You can follow up with the below feedback for further details,
> 
> Feedback link: https://www.syncfusion.com/feedback/36456/support-to-hide-the-scroll-bars
> 
> Regards, Tamilarasan

I noticed that the latest version 22.1.34 already supports hidden scrollbars. But when I use the latest version to render html, the scroll bar will still be displayed. This is an unfixed bug, right?
