### ISSUE TITLE
App crashing in iOS

### ISSUE THREAD

**Issue by mobileexpert1** [syncfusion/flutter-widgets#575]
App crashing while zoom in/zoom out the pdf in iOS.

Used version: syncfusion_flutter_pdfviewer: ^19.4.50-beta

**Comment by deepika134** [comment]
Hi mobileexpert1,

We tried to reproduce the reported issue with provided details, but the issue couldn’t be reproduced on our end. Please share the following details, to reproduce the reported issue on our end.

1. Device Specification
2. Flutter SDK version
3. Issue reproducing document
4. Flutter Doctor log

This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi.
