### ISSUE TITLE
[syncfusion_flutter_pdf] How to get pages separately? (or make a thumbnail viewer)

### ISSUE THREAD

**Issue by mirkancal** [syncfusion/flutter-widgets#576]
Hey folks, I build a thumbnail viewer by using [native_pdf_renderer](https://pub.dev/packages/native_pdf_renderer) package but unfortunately, it doesn't work on Android[ due to the underlying API throwing an exception when you ask to get more than one page as an image.
](https://github.com/rbcprolabs/packages.flutter/issues/268)

I'm playing with syncfusion packages right now. It has lot of features but I wasn't able to find it. I wonder if anyone build the same thing I sent as a screenshot or knows if it's possible to get pages separately with those packages.

<img width="359" alt="image" src="https://user-images.githubusercontent.com/26160059/153403727-5f2c335f-2bbc-44a1-be1b-2c8ba6e33a2c.png">

**Comment by deepika134** [comment]
Hi mirkancal,

Please find the details of the requested queries in the below table.

| Query                                | Details                                                                                    |
|--------------------------------|------------------------------------------------------------------------|
| Thumbnail viewer       | At present we do not have support for **“Thumbnail view”** in                                             SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked using the following link, https://www.syncfusion.com/feedback/32619/support-for-thumbnail-view                                                 
| How to get pages separately?  | Currently, the Syncfusion Flutter PDF package doesn't provide support for **“Extracting the images from PDF document”**. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked using the following link, https://www.syncfusion.com/feedback/21130/support-for-extracting-the-images-from-pdf-document  

Regards,
Deepika Ravi
