### ISSUE TITLE
[syncfusion_flutter_calendar] Callback when view changes

### ISSUE THREAD

**Issue by jaumard** [syncfusion/flutter-widgets#577]
I want to save in sharedpreference the last view selected (weekly, day, monthly...), but I didn't find any way to get notified when the user changed that view. 

I've check the widget and the controller but no callback is available for that use case.

**Comment by Indumathi1195R** [comment]
Hi Team,

Based on the shared information, we suspect your requirement is “**Getting the notification when changed the view in the Flutter Calendar**”.  [onViewChanged](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/onViewChanged.html) callback was triggered whenever the calendar view changes, by using this you can get the view changed details. We have a UG and KB documentation for the same. Please find the UG and KB from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/callbacks#view-changed-callback

**KB link:**
https://www.syncfusion.com/kb/11026/how-to-get-visible-dates-details-from-the-flutter-calendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by jaumard** [comment]
Thanks @Indumathi1195R, I have tried the `onViewChanged ` but it gives you only the visible dates, it doesn't tell you which view you are in, meaning that if I switch from week to month I have to check the dates to guess which view mode the caledandar is. Would be perfect if `ViewChangedDetails` had a property `view` that tells you the current mode of the calendar.

**Comment by Indumathi1195R** [comment]
Hi,

By using the [view](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController/view.html) property of the [CalendarController](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/CalendarController-class.html), you can get the current view the calendar. Please refer the following code snippet.

**Code snippet:**
```
CalendarController _calendarController=CalendarController();

body:
SafeArea(child: SfCalendar(onViewChanged: viewChanged,controller: _calendarController,),

void viewChanged(ViewChangedDetails viewChangedDetails) {
   print(_calendarController.view);
}
```

Also, we have KB documentation for programmatic view navigation in calendar.

**KB link:**
https://www.syncfusion.com/kb/12141/how-to-do-programmatic-navigation-using-flutter-calendar 

Regards,
Indumathi R

**Comment by jaumard** [comment]
Ho ok understood, I don't have a controller as I have no need for it so I miss that possibility. Thanks, I'll use one!
