### ISSUE TITLE
PDFviewer crashed when using bookmarks

### ISSUE THREAD

**Issue by dahef34** [syncfusion/flutter-widgets#578]
After upgrading to flutter 2.10.1, pdfviewer crashed the application when selecting a bookmark in android, macOS, and web.  It works on IOS.  It immediately kills the app so I don't get any logs from the event that I can tell and no message is provided in the debugger.  It worked well before the upgrade so I'm not sure what changed in the newest flutter version that is causing this behavior.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful,
      please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.64.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

syncfusion_flutter_pdfviewer: ^19.4.50-beta

class PedsEmergencies extends StatefulWidget {
  const PedsEmergencies({Key? key}) : super(key: key);

  @override
  _PedsEmergenciesState createState() => _PedsEmergenciesState();
}

class _PedsEmergenciesState extends State<PedsEmergencies> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey3 = GlobalKey();

  @override
  void dispose() {
    _pdfViewerKey3.currentState?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.secondaryContainer,
      appBar: AppBar(
        toolbarHeight: 20,
        titleTextStyle: TextStyle(
          backgroundColor: Theme.of(context).colorScheme.secondaryContainer,
          fontSize: 18,
          fontWeight: FontWeight.bold,),
        backgroundColor: Theme.of(context).colorScheme.secondaryContainer,
        title: const Text('Pediatrics Emergency Manual'),
      ),
      persistentFooterButtons: [
        IconButton(
          icon:  Icon(Icons.copyright_rounded, color: Theme.of(context).colorScheme.onSecondary,),
          onPressed: () {
            launch(
              'https://creativecommons.org/licenses/by-nc-nd/3.0/legalcode',);
          },
        ),
        IconButton(
          icon:  Icon(Icons.link_outlined, color: Theme.of(context).colorScheme.onSecondary,),
          onPressed: () {
            launch(
              'https://www.maskinduction.com/society-for-pediatric-anesthesia---pedi-crisisreg-critical-events-checklist.html',);
          },
        )
      ],
      floatingActionButton: FloatingActionButton(
        backgroundColor: Theme.of(context).colorScheme.secondaryContainer,
        onPressed: () {
          _pdfViewerKey3.currentState?.openBookmarkView();
        },
        child: const Icon(Icons.menu),),
      body: SfPdfViewer.asset(
        'assets/peds_emergency_manual.pdf',
        enableTextSelection: false,
        key: _pdfViewerKey3,
        pageLayoutMode: PdfPageLayoutMode.single,
      ),
    );
  }
}

**Comment by deepika134** [comment]
Hi dahef34,

We tried to reproduce the reported issue with provided details, but the PDFViewer didn’t crash when using the bookmark. We have prepared a sample for your reference and attached the output screen record of the sample which can be downloaded at the following link
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample1050715424.zip  

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in the sample and share the issue reproducing document. Which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika Ravi.
