### ISSUE TITLE
[syncfusion_flutter_calendar] can't access cell when scrollbar is present

### ISSUE THREAD

**Issue by jaumard** [syncfusion/flutter-widgets#579]
If I try to click on the right side of the cell to add a new event, the scrollbar takes the event and scroll so I can't access the cell. 

<img width="718" alt="Capture d’écran 2022-02-13 à 11 53 53" src="https://user-images.githubusercontent.com/2970449/153749956-a052543a-5be5-46b9-a139-124b30eaec5b.png">

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: the scrollbar takes the event and scroll so I can't access the cell**

You can improve the appointment and timeslot end padding by using the [cellEndPadding](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/cellEndPadding.html) property. It used to add padding at the right end of the cell when it has an appointment.

We have a UG documentation for the same. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/getting-started#cell-end-padding 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by jaumard** [comment]
Thanks @Indumathi1195R, nice workaround, I think it would be nice to have the ability to hide the scrollbar when it doesn't move. Or have a padding-right to the calendar widget so it's not under the scrollbar.

**Comment by Indumathi1195R** [comment]
Hi,

We have considered your requirement “Hiding the scrollbar in the Flutter Calendar” as feature and logged the feature request for the same. We will implement this in any of our upcoming releases and let you know once the release rolled out.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.

Thank you for requesting this feature. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.
 
You can also communicate with us regarding the open features any time using our Feature Report page. 
 
Feedback link: https://www.syncfusion.com/feedback/32679/providing-support-to-hide-the-scrollbar-in-the-timeslots-of-the-flutter-calendar  

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Indumathi R
