### ISSUE TITLE
[syncfusion_flutter_calendar] WorkDays from date.weekDay

### ISSUE THREAD

**Issue by jaumard** [syncfusion/flutter-widgets#580]
I had to create this helper method:

```
static WeekDays from(DateTime date) {
    final weekDay = date.weekday;
    switch(weekDay) {
      case DateTime.monday:
        return WeekDays.monday;
      case DateTime.tuesday:
        return WeekDays.tuesday;
      case DateTime.wednesday:
        return WeekDays.wednesday;
      case DateTime.thursday:
        return WeekDays.thursday;
      case DateTime.friday:
        return WeekDays.friday;
      case DateTime.saturday:
        return WeekDays.saturday;
      case DateTime.sunday:
        return WeekDays.sunday;
      default: return WeekDays.monday;
    }
  }
```

Would be nice to have this built in WorkDays to make it easier for people. Just my 2 cents. No big deal

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we are unable to understand your requirement clearly? If possible, can you please give more details about your requirement clearly with an illustration image. It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by jaumard** [comment]
Hey, 

What I'm trying to achieve is to create a weekly recurrence rule from a date. In my database I have the date and it's recurrence (weekly), from that I need in your data source to generate a recurrence rule.

So this is what I do:

```
@override
  String? getRecurrenceRule(int index) {
    final HealerOpening event = appointments![index];
    final start = event.start;
    if (event.repeat == null) {
      return null;
    }
    RecurrenceProperties recurrenceProperty;

    switch (event.repeat) {
      case OpeningRepeatType.weekly:
        recurrenceProperty = RecurrenceProperties(startDate: start, recurrenceType: RecurrenceType.weekly, weekDays: [WeekDaysExtension.from(start)]);
        break;
      case OpeningRepeatType.monthly:
        recurrenceProperty = RecurrenceProperties(
          startDate: start,
          recurrenceType: RecurrenceType.monthly,
          dayOfMonth: start.day,
        );
        break;
      default:
        recurrenceProperty = RecurrenceProperties(
          startDate: start,
          recurrenceType: RecurrenceType.daily,
        );
        break;
    }

    return SfCalendar.generateRRule(
      recurrenceProperty,
      start,
      start,
    );
  }
```

So to create a weekly recurrence I need to provide the `weekDays` in my case it is based only on the `start` day. So I get the  `start.weekDay` that I need to convert in WorkDays. That why I have created this helper function. 

Is it more clear now?

**Comment by Indumathi1195R** [comment]
Hi,

We have UG documentations for helper methods for getting recurrence properties and recurrence date collection of recurrence appointment in Flutter Calendar. Please find the UG from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/appointments#how-to-get-the-recurrence-editor-field-values-from-rrule

https://help.syncfusion.com/flutter/calendar/appointments#how-to-get-the-recurrence-dates-from-rrule

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
