### ISSUE TITLE
Tab Key not working Properly after FocusScope.of(context).notifyListeners()

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#581]
i am using grid for data entry on windows and web . grid last cell value update after focus goes to next.
so i call FocusScope.of(context).notifyListeners() on save button. butt after that when i press tab key its not work properly between cells.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Based on the provided information. We have checked your reported scenario, but we could not reproduce your reported issue. It's working fine at our end. On the button click focus goes from DataGrid cell to button then pressing tab button the focus coming to button first then it comes to DataGrid cell after that tab event called in the source. We have prepared a sample for your reference.

Sample Link: [https://www.syncfusion.com/downloads/support/directtrac/general/ze/main1595736477](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fdownloads%2Fsupport%2Fdirecttrac%2Fgeneral%2Fze%2Fmain1595736477&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C582d9d7e6d4b4cf6fa0208d9efb99216%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637804402569572718%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jeloy5dYSaYI84KcCHqbOl%2F4jRJdZLNwb4iGx6cRPSc%3D&reserved=0)

We hope this helps. If we misunderstood anything, can you please provide more details about your requirement? It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
issue resolved thanks
