### ISSUE TITLE
[SfDataGrid] Sort icon is hardcoded

### ISSUE THREAD

**Issue by jocubeit** [syncfusion/flutter-widgets#582]
I recently experienced an issue where the sort icons were not rendering and I was receiving an odd error in the console stating 

> Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing
> characters. See: https://flutter.dev/docs/cookbook/design/fonts

This error is very misleading as it turns out.

Screenshot below:

<img width="803" alt="Screen Shot 2022-02-14 at 10 49 47 am" src="https://user-images.githubusercontent.com/209968/153785614-6cfdd880-07b5-480a-8141-045594dc374f.png">

I logged a [support request](https://support.syncfusion.com/support/tickets/366755) because it seemed like an upstream issue with Flutter, that could be alleviated by Syncfusion if the sort icons could be provided by the developer.

I have since looked through the DataGrid source code and found the following line which specifies `Icons.arrow_upward` as the sort icon in the row header. See offending line:

https://github.com/syncfusion/flutter-widgets/blob/194afe6f24944c0d998bf2edc92e1a70e851e036/packages/syncfusion_flutter_datagrid/lib/src/datagrid_widget/widgets/cell_widget.dart#L578

This led me to understand that because I have turned off material design support in my project `uses-material-design: false` in my `pubspec.yaml` (because I'm using IBM Carbon Design), that my project was not loading the material design icon library; thus no support for the hardcoded sort icon.

Can I please ask that you allow developers to pass in the `sortIcon` as a property just like you do with `SfDataGridThemeData .sortIconColor`? This would allow projects not using material design to not have to load material design components just because of Syncfusion widgets.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @jocubeit 

Currently, we have used the material icons for our requirements. We have now considered your requirement as a feature request. We will implement this feature in our 2022 Volume 1 release, which is expected to be rolled out on end of March 2022. You can follow up with the below feedback link.

Feedback link: [https://www.syncfusion.com/feedback/32666/support-to-set-a-sort-icon-at-sample-level-in-datagrid](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F32666%2Fsupport-to-set-a-sort-icon-at-sample-level-in-datagrid&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7Cbf49ddee28b84ff954a108d9efbbc5d0%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637804412022271415%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YHF7mYLdNMLaaHgCtpU0dGuh9JofB%2Fe%2BPJBeBIDz0y0%3D&reserved=0)

We will let you know once it gets rolled out. We appreciate your patience until then.

Regards, 
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @jocubeit,

Thanks for your patience. 

We are glad to announce that our Essential Studio 2022 Volume 1 Main Release **V20.1.0.47** is rolled out and is available for download under the following link. 
  
[https://www.syncfusion.com/forums/174125/essential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F174125%2Fessential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C56f2622de373423c75e208da1629aa5f%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637846665454424059%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IayIfsE3KYmQpgQEe78RlBJ1jiTRkBTriUj6W01cDgM%3D&reserved=0)

Refer the following UG link for **set a custom sort icon feature**, 

**UG Link**: https://help.syncfusion.com/flutter/datagrid/sorting#set-a-custom-sorting-icon 

**API Document**: https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfDataGridThemeData/sortIcon.html

We thank you for your support and appreciate your patience in waiting for this release. Please contact us if you would require any further assistance. 

Regards, 
Tamilarasan

**Comment by jocubeit** [comment]
Thank you for implementing my suggested feature. Your team is extremely responsive, communicates properly, follows up when promises and as a direct result is a shining example and leader in the world of customer service. You can all be proud to work for such a company. Well done!
