### ISSUE TITLE
Dark theme PDF

### ISSUE THREAD

**Issue by raunak-many-ac** [syncfusion/flutter-widgets#583]
Currently dark theme is not applicable on PDF document. That is the only thing this package is missing. Which is very crucial since pdf docs are used in blog apps.

Having a dark theme will be a nice feature. Some flutter package do this: - 
Like: https://pub.dev/packages/flutter_pdfview

**Comment by deepika134** [comment]
Hi Raunak Narayan,

We have support for the theming in Flutter PDFViewer.  To achieve the dark theme, please find the following code snippet.

Code Snippet:
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp( MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
 ColorScheme colorScheme = const ColorScheme.dark();
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
          primarySwatch: Colors.blue,
          colorScheme: colorScheme
      ),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter PDF Viewer'),
        ),
        body: SfPdfViewer.network(
            'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf'),
      ),
    );
  }
}
```
To know more about the dark theme in Syncfusion widgets, please refer to the following link, https://help.syncfusion.com/flutter/themes#dark-theme

Regards,
Deepika Ravi

**Comment by raunak-many-ac** [comment]
Hi Deepika,

Thank you for your reply.

This issue is not regarding theme changing of UI widgets. The pdf itself should be rendered in dark mode (or night mode). 

For instance: - 
![image](https://user-images.githubusercontent.com/31949358/154069275-99d76f33-c5f2-4e1f-a793-52e026e3e3de.png)

& 

![image](https://user-images.githubusercontent.com/31949358/154069373-7a6c117e-bd4f-46c7-a0b6-13c91bcaf850.png)

The colour inversion makes the pdf readable in low light. 

This is more obvious render if user opts dark mode in the app.

Package in flutter which can do this are: -
https://pub.dev/packages/flutter_pdfview
https://pub.dev/packages/flutter_full_pdf_viewer
and a few more.

👆These are using platform views.

Currently syncfusion_package only makes the widgets in dark mode not the pdf

**Comment by deepika134** [comment]
Hi Raunak Narayan,

Currently, we don't have support for PDF page color inversion support in dark theme. We are analyzing the feasibility of this feature and will update the details on 18 February 2022.

Regards,
Deepika Ravi

**Comment by raunak-many-ac** [comment]
> Hi Raunak Narayan,
> 
> Currently, we don't have support for PDF page color inversion support in dark theme. We are analyzing the feasibility of this feature and will update the details on 18 February 2022.
> 
> Regards,
> Deepika Ravi
> 

Hi Deepika,

Thanks a lot for your consideration regarding this issue. I hope we find a solution to this.

This feature will add substantial value to this product in the market.

Regards,
Raunak

**Comment by deepika134** [comment]
Hi Raunak Narayan,

At present we do not have support for night mode in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/32848/support-for-night-mode 

Regards,
Deepika Ravi.

**Comment by Pheonix0101** [comment]
Hi @deepika @raunak

Please keep it posted our product is looking for a package like this but the night-mode feature is a crucial part.

The rest of the features are superb though but meanwhile, we are using the different packages for sake of this night mode.

Thanks and Regards
Purushottam kumar

**Comment by dillibabu1802** [comment]
Hi @Pheonix0101 

Thank you for contacting Syncfusion support.

Currently, we have no plans to implement this feature. As we have used flutter plugin architecture to retrieve the images from native platform, we suggest you to generate a pdf images in dark mode by changing the [color](https://github.com/syncfusion/flutter-widgets/blob/194afe6f24944c0d998bf2edc92e1a70e851e036/packages/syncfusion_flutter_pdfviewer/android/src/main/java/com/syncfusion/flutter/pdfviewer/SyncfusionFlutterPdfViewerPlugin.java#L227) until, the feature is implemented at our end.

Regards,
Dilli babu.

**Comment by raunak-many-ac** [comment]
Hi @dillibabu1802 

Thank you for you advice. 

We tried to apply it but the issue that showed up was link handling is not available. 
On tap of links in the pdf we cannot launch it (i.e. open in browser).

This is crucial feature and is unfortunately not in this package.

Rest are working fine😎. Hope it gets addressed asap since it is not a major change. We would love to switch to syncfusion after that

Regards,
Raunak

**Comment by deepika134** [comment]
Hi @raunak-many-ac ,

At present we do not have hyperlink support in the SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/21134/support-for-hyperlink 

Regards,
Deepika Ravi
