### ISSUE TITLE
[syncfusion_flutter_pdfviewer] We need to have a callback in the PDF Viewer that receives the URL when a user taps on a URL in the PDF

### ISSUE THREAD

**Issue by moazelsawaf** [syncfusion/flutter-widgets#586]
Hello,

Thanks a lot for the great work you always provide, we would be very greatful if you add a mechanism to open a URL in the PDF when the uses taps on it, or even have a callback to receive the url and pass it to the developer to work with it.

Example:
In the [book ](https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf) you are using as an example, there is a URL for Syncfusion website at the third page ( 3 ), I want to have a callback that receives the URL ( in this case www.syncfusion.com ) when the user taps on it.

Thanks ❤

**Comment by deepika134** [comment]
Hi Moaz El-sawaf,

At present we do not have hyperlink support in the SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. The status of the feature can be tracked using the following link,

https://www.syncfusion.com/feedback/21134/support-for-hyperlink

Regards,
Deepika Ravi

**Comment by moazelsawaf** [comment]
Thanks a lot for the fast response and for all the hard work you do for the community.

I hope to see this feature soon in the package.
