### ISSUE TITLE
App crashing in iOS: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ravi-aron** [syncfusion/flutter-widgets#587]
```
syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:124:
Fatal error: Unexpectedly found nil while unwrapping an Optional value

```

I am loading multiple PDFs in ListView.builder widget in Flutter. When I scroll down, it lazily downloads the new PDF but sometimes the iOS app gets crashed with the above error.

Package: `syncfusion_flutter_pdfviewer: ^19.4.50-beta`

This is my PDF Viewer widget:

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class PdfViewer extends StatefulWidget {
  final String? url;
  final bool isMinimal;

  const PdfViewer({this.url, this.isMinimal = true});

  @override
  _PdfViewerState createState() => _PdfViewerState();
}

class _PdfViewerState extends State<PdfViewer> {
  File? file;
  final PdfViewerController _controller = PdfViewerController();
  int _pageCount = 0;

  @override
  void initState() {
    super.initState();
    loadPdf();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: widget.isMinimal ? null : AppBar(),
      body: file == null
          ? const Center(child: CircularProgressIndicator())
          : SfPdfViewer.file(file!, controller: _controller,
              onDocumentLoaded: (PdfDocumentLoadedDetails details) {
              setState(() {
                _pageCount = _controller.pageCount;
              });
            }),
    );
  }

  Future<void> loadPdf() async {
    file = await createFileOfPdfUrl();

    if (mounted) {
      setState(() {});
    }
  }

  Future<File?> createFileOfPdfUrl() async {
    final url = widget.url;
    try {
      if (url != null) {
        final filename = url.substring(url.lastIndexOf('/') + 1);
        final dir = (await getApplicationDocumentsDirectory()).path;
        final file = File('$dir/$filename');

        final isFileAlreadyPresent = await File(file.path).exists();
        if (isFileAlreadyPresent) {
          return file;
        }

        final request = await HttpClient().getUrl(Uri.parse(url));
        final response = await request.close();
        final bytes = await consolidateHttpClientResponseBytes(response);

        await file.writeAsBytes(bytes);
        return file;
      }
    } catch (e) {
      print(e.toString());
    }

    return null;
  }
}

```

**Comment by deepika134** [comment]
Hi @ravi-aron,

We are analyzing on the reported issue and will update the further details on February 18, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi @ravi-aron ,

We can reproduce the reported issue on our end and will update the further details on February 22, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi ravi-aron, 
 
We have confirmed that the reported issue “Unexpected closure of the app when zooming and scrolling the pdf continuously” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 08 March 2021. The status of this issue can be tracked using the following link, https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously 

Kindly share the document in which you are facing the reported issue it will be helpful for us to ensure the fix. 

Regards, 
Deepika Ravi

**Comment by ravi-aron** [comment]
Thank you for looking into this.

**Comment by deepika134** [comment]
Hi ravi-aron,

We have included the enhancement of scrolling and image rendering module in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.56., so kindly upgrade to the latest version v19.4.56.   
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.56-beta

Regards,
Deepika Ravi
