### ISSUE TITLE
Loading pdf from network taking too much time and displays blank screen

### ISSUE THREAD

**Issue by baimamboukar** [syncfusion/flutter-widgets#588]
When I load a pdf from a network, it is taking too much time to display. And while waiting for the pdf to load completely, a blank screen is being displayed, which is not a good UX at all. 

### Is there any callback function like **onPdfLoading( )** that will allow to display a loader to the user while the pdf is loading ???

**Comment by deepika134** [comment]
Hi BAIMAM BOUKAR JEAN JACQUES,

We tried to reproduce the reported issue with provided details, but the linear progress bar indicator shows properly when loading a PDF and didn’t see any black screen on our end. We have prepared a sample for your reference (along with the output screen record), which can be downloaded at the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample41376540.zip   

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in the sample. Which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by baimamboukar** [comment]
Thanks for replying @deepika134 . I have just tested the sample and it works pretty fine. 

### But can I customize the loading behaviour ? i.e changing the linear progress indicator to a custom loader widget...

**Comment by deepika134** [comment]
Hi BAIMAM BOUKAR JEAN JACQUES,

At present we do not have support for customizing the loading indicator in SfPdfViewer. Kindly share your complete requirement and design of the custom loader widget. This information will be helpful for us to proceed further.

Regards,
Deepika Ravi
