### ISSUE TITLE
[syncfusion_flutter_datepicker] How to set format for header year and month

### ISSUE THREAD

**Issue by tatsuyuki25** [syncfusion/flutter-widgets#589]
![Screenshot_20220218_104426](https://user-images.githubusercontent.com/11785338/154607920-3f70b27f-ca11-47d6-b4eb-48c462e2b055.png)

I thank is `date_packer.dart` line 13193.
```dart
      text =
          '${DateFormat(monthTextFormat, locale.toString()).format(middleDate)}'
          ' ${middleDate.year}';
```
I want to swap year month to `2022 02` and set year format to `yyyy 年`

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Swap the month format in the Flutter SfDateRangePicker.**

As per the current implementation of the picker there is no support to swap the month and year of the header. By hiding default header and adding the custom header, you can achieve this requirement. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/localization-date-range-picker-flutter-master_(2)873764162.zip 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
