### ISSUE TITLE
Flutter Charts | User experience issue

### ISSUE THREAD

**Issue by brianschardt** [syncfusion/flutter-widgets#59]
When the user on a mobile device is using their finger to navigate the track ball, if their finger leaves the graph slightly the trackball disapears. On IOS in the stock app the user can start in the graph but then leave the graph and the trackball will still follow their finger. 

Other charting libraries for flutter have this by default it is sad to see that this does not support this

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Greetings from Syncfusion. We have analyzed your scenario at our end and we would like to share some information regarding the **`shouldAlwaysShow`** property of the **`TrackballBehavior`**. On setting true to this property, the trackball in the chart remains activated even after you took the finger from the graph. Please refer the code snippet below for further reference.
```
SfCartesianChart(
                trackballBehavior: TrackballBehavior(
                  enable: true,
                  shouldAlwaysShow: true
                )
)
```

Please get in touch with us if you would require further assistance.

Regards,
Sriram Kiran

**Comment by brianschardt** [comment]
I can confirm that the 
```
shouldAlwaysShow: true
``` 
does not work as intended then as i have tried that multiple times.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @brianschardt,

Thanks for the revert. We further analyzed the apple stocks app in IOS regarding its trackball behaviour and we will consider it as an improvement regarding navigating the trackball in the chart on dragging event after the finger leaves the chart area from our side and we have logged a feature request regarding this in our feedback portal. We will implement and include this improvement in any of our upcoming releases yet to come. You can also track the status of the feedback using the below link.

https://www.syncfusion.com/feedback/19918

Please get in touch with us if you would require further assistance.

Regards,
Sriram Kiran
