### ISSUE TITLE
Sorting and paging mechanism doesn't work properly at the same time

### ISSUE THREAD

**Issue by iremiko** [syncfusion/flutter-widgets#590]
Hi, 
Sorting and paging mechanism doesn't work properly when used at the same time. When I click on the line, it shows the item in the page order. But because I was sorting, its location had changed.
For examle;

I have 30 items and every page has 10 items. When I sort the column an tap the second row. Row shows 21. item.

How can I fix this?

Thank you

**Comment by RenugaSadagoban98** [comment]
Hi @iremiko ,

From the provided information, it seems you are trying to do the sorting for the rows available in a page without overriding the handlePageChange method in the DataGridSource class and the rowsPerPage property in SfDataPager. When you try to do the sorting without overriding the handlePageChange method, then the sorting will be applied to all the rows. You can avoid this behavior by overriding the handlePageChange method in the DataGridSource class. 

 UG link: https://help.syncfusion.com/flutter/datagrid/paging#sort-all-the-rows-instead-of-rows-available-in-a-page

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Rows_available_page_sorting-1364913596

Please refer to both the UG document and the sample. And revert back to us if you are still facing the same issue.

Regards,
Renuga devi.
