### ISSUE TITLE
[syncfusion_flutter_gauges] 19.4.52 Error: The getter 'secondaryContainer' isn't defined for the class 'ColorScheme'.

### ISSUE THREAD

**Issue by patelpathik** [syncfusion/flutter-widgets#592]
### Issue
I just added this plugin to my project and got the error, complete information is below.

### Error Details

../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-19.4.52/lib/src/radial_gauge/pointers/marker_pointer_renderer.dart:631:34: Error: The getter 'secondaryContainer' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'secondaryContainer'.
          _themeData.colorScheme.secondaryContainer.withOpacity(0.8)
                                 ^^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-19.4.52/lib/src/radial_gauge/pointers/marker_pointer_renderer.dart:642:36: Error: The getter 'secondaryContainer' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'secondaryContainer'.
            _themeData.colorScheme.secondaryContainer.withOpacity(0.12)
                                   ^^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-19.4.52/lib/src/radial_gauge/pointers/range_pointer_renderer.dart:567:34: Error: The getter 'secondaryContainer' isn't defined for the class 'ColorScheme'.
 - 'ColorScheme' is from 'package:flutter/src/material/color_scheme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/color_scheme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'secondaryContainer'.
          _themeData.colorScheme.secondaryContainer.withOpacity(0.8)
                                 ^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/home/pathik/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/pathik/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Running Gradle task 'assembleDebug'...                             12.6s
Exception: Gradle task assembleDebug failed with exit code 1

### Flutter doctor (flutter doctor -v)

[✓] Flutter (Channel stable, 2.8.1, on Manjaro Linux 5.15.21-1-MANJARO, locale en_IN.UTF-8)
    • Flutter version 2.8.1 at /home/pathik/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (10 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /home/pathik/Android/Sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /home/pathik/WORK/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.1)
    • Android Studio at /home/pathik/WORK/android-studio
    • Flutter plugin version 63.2.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Connected device (1 available)
    • DN2101 (mobile) • NVW48HK7W8KZFURC • android-arm64 • Android 11 (API 30)

! Doctor found issues in 1 category.

Please ask for more information if needed, I'm new to reporting issues.

**Comment by PraveenGopalsamy** [comment]
Hi Patelpathik,

We have found that you are using the flutter stable SDK version <=2.8.1. Kindly update your Flutter SDK to the [latest version](https://docs.flutter.dev/development/tools/sdk/releases)(>2.10.0) to solve this issue. If you wish to use the SDK version 2.8.1 only, please use the [Flutter Gauge - 19.4.48](https://pub.dev/packages/syncfusion_flutter_gauges/versions/19.4.48) version. Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by patelpathik** [comment]
Oh my bad, this resolved my issue.
Will keep the eye on the versions now!
Thanks much @PraveenGopalsamy
