### ISSUE TITLE
[syncfusion_flutter_charts]How to reset selected indexes.

### ISSUE THREAD

**Issue by YaoShuwei** [syncfusion/flutter-widgets#604]
I set the initialSelectedDataIndexes:[0], after I select an other index, how can I reset index to 0?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @YaoShuwei,

Yes, you can reset the selected point index to 0, to achieve this we suggest you the selectDataPoints public method of selection behavior. You need to call this public method in the button click and provide the index value you want to select. We have attached the code snippet below for your reference, this can be modified based on your scenario.

```dart
late SelectionBehavior _selectionBehavior;
@override
void initState() {
  _selectionBehavior = SelectionBehavior(enable: true);
   super.initState();
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(),
    body: Column(children: [
      SfCartesianChart(
        series: <ChartSeries<SalesData, DateTime>>[
          ColumnSeries(
            initialSelectedDataIndexes: <int>[0],
            selectionBehavior: _selectionBehavior,
            //Other required properties
          )
        ],
      ),
      ElevatedButton(
        onPressed: () {
          _selectionBehavior.selectDataPoints(0);
        },
        child: Text('press'))
     ]));
  }
```

Regards,
Yuvaraj.

**Comment by YaoShuwei** [comment]
> Hi @YaoShuwei,
> 
> Yes, you can reset the selected point index to 0, to achieve this we suggest you the selectDataPoints public method of selection behavior. You need to call this public method in the button click and provide the index value you want to select. We have attached the code snippet below for your reference, this can be modified based on your scenario.
> 
> ```dart
> late SelectionBehavior _selectionBehavior;
> @override
> void initState() {
>   _selectionBehavior = SelectionBehavior(enable: true);
>    super.initState();
> }
> 
> @override
> Widget build(BuildContext context) {
>   return Scaffold(
>     appBar: AppBar(),
>     body: Column(children: [
>       SfCartesianChart(
>         series: <ChartSeries<SalesData, DateTime>>[
>           ColumnSeries(
>             initialSelectedDataIndexes: <int>[0],
>             selectionBehavior: _selectionBehavior,
>             //Other required properties
>           )
>         ],
>       ),
>       ElevatedButton(
>         onPressed: () {
>           _selectionBehavior.selectDataPoints(0);
>         },
>         child: Text('press'))
>      ]));
>   }
> ```
> 
> Regards, Yuvaraj.

Thanks very much. I finish this job with your help!
