### ISSUE TITLE
syncfusion datagrid cell endedit call future function

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#607]
is there any option to call future function on cell end edit. "canSubmitCell" event dont support async . so i cant call future function there. if i call that function "onCellSubmit" event then cell focus already goes to next cell before return future value.
 i want to move focus after future function.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Can you please let us know the purpose of using a future function in the DataGridCell, i.e., the use case for using a future function? Please provide more details about your query or provide any use case. It will give us more understanding.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
thanks for replying. in textfield after input text i press tabkey before go to next cell
i want to call a future function which call api and return me back values against input text. and if no value found then canSubmitCell

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Currently, we are analyzing your requirement. We will validate and update you the details by tomorrow. We appreciate your patience until then.

Regards,
Tamilarasan
