### ISSUE TITLE
grid canSubmitCell issue 

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#608]
as per below code if i click salary cell then why i am able to click on other cells?? and if i input in other cell same value pass to other cells and which 
 @override
  bool canSubmitCell(DataGridRow dataGridRow, RowColumnIndex rowColumnIndex,
      GridColumn column) {
    if (column.columnName == 'salary')
      {
        return false;
      }

      // Return false, to retain in edit mode.
    return true; // or super.canSubmitCell(dataGridRow, rowColumnIndex, column);
  }

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

We have checked your reported issue and considered this as bug. We will include the changes in our weekly pub release which is scheduled to be rolled out on March 15, 2022. You can follow up with the below feedback for further details, 

Feedback link: https://www.syncfusion.com/feedback/33046/even-we-return-false-in-the-cansubmitcell-method-another-cell-goes-into-edit-mode


Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Thank you for your patience.

We are glad to inform you that the fix has been included in our weekly pub release. Please update DataGrid package to **19.4.56** version.

Please let us know if you need further assistance on this.

Regards,
Tamilarasan
