### ISSUE TITLE
[SfMaps] Show Bubbles in real size

### ISSUE THREAD

**Issue by YumNumm** [syncfusion/flutter-widgets#609]
I want to show bubbles of the size corresponding to the map layer below.
Is there a way to implement this?

**Comment by PraveenGopalsamy** [comment]
Hi YumNumm,

We could not get the exact requirement which you are trying to achieve with Maps. Please update us with your exact requirements with some possible reference links or screenshots. So that we can assist you better. The below link is our online documentation about using bubbles in Maps.

https://help.syncfusion.com/flutter/maps/bubble

Regards,
Praveen G.

**Comment by YumNumm** [comment]
I'm sorry that this expression is difficult to understand.
I've asked Syncfusion help center the same question.
[URL](https://t.co/cCLJoDw60I)

**Comment by PraveenGopalsamy** [comment]
Hi YumNumm,

The bubbles in Maps are intended to visualize the relative data. So, there is no direct option to set the size of the bubbles in kilometers. You can refer more about adding a bubble from the below link.

https://help.syncfusion.com/flutter/maps/bubble

The next closest element is the circle layer in Maps that might be useful to you. You can refer more about adding a circle layer from the below link.

https://help.syncfusion.com/flutter/maps/vector-layers/circle-layer

This circle layer has a radius property that you can use to set the size. Also, you can set the latlng for the circle to get displayed.

Anyhow as we do not have direct support, we have logged a feature request from our end. You can track the status of the feedback request from the below link.

**Feedback -** https://www.syncfusion.com/feedback/33050/support-for-specifying-the-circle-radius-in-linear-measures-like-kilometers-miles

We will prioritize the features of every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specifications/suggestions to the feature request, you can add them as a comment in the portal.

**Disclaimer:** The date for this feature implementation is tentative and not a commitment on our parts.

Please let us know if need any further assistance in this.

Regards,
Praveen G.
