### ISSUE TITLE
SystemMouseCursors.click with CupertinoPageScaffold? 

### ISSUE THREAD

**Issue by rasmusrbj** [syncfusion/flutter-widgets#610]
I get this error: The getter 'SystemMouseCursors' isn't defined for the class '_LegendItemState'.

Anyone has an idea?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @rasmusrbj,

The widget name is not specified in the query, and we are not aware of in which widget the exception get occurs. So kindly provide the below information that will be more helpful to us to provide a solution sooner,
•	In which widget are you facing this issue
•	If possible, please provide a code snippet with reproduce the issue
•	Please specify the package version you are using

Regards,
Yuvaraj.
