### ISSUE TITLE
[syncfusion_flutter_datepicker] Custom text for showTodayButton.

### ISSUE THREAD

**Issue by fannar** [syncfusion/flutter-widgets#611]
Would be nice ot have todayText for showTodayButton as cancelText and confirmText for showActionButtons.

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: Custom text for showTodayButton.**

We regret to inform that, as per the current implementation of the picker there is no support add custom text for today text and custom text applicable for action buttons only. Please get in touch with us if would you require any further assistance.

Regards,
Indumathi R
