### ISSUE TITLE
[syncfusion_flutter_datepicker] Decorations and styles not working with selectableDayPredicate

### ISSUE THREAD

**Issue by fannar** [syncfusion/flutter-widgets#612]
When using `selectableDayPredicate` custom decorations not working.

This code does not work when using the predicate. Would like to "hide" the circle around the current date but show different text color.

```dart
todayTextStyle: const TextStyle(
                          color: Colors.red,
                        ),
todayCellDecoration: BoxDecoration(
                          border: Border.all(
                            color: Colors.white,
                            width: 0,
                          ),
                          shape: BoxShape.circle,
                        ),
```

The text style gets the default disabled text style. The cell decoration shows up as default with `todayHighlightColor`'s circle shape.

**Comment by Indumathi1195R** [comment]
Hi Team,

Currently, we are checking the issue “**Decoration not working while using the selectableDayPredicate callback in the Flutter Calendar**”. We will validate and update you on the further details on or before March 4, 2022. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the issue “**Decoration not working while using the selectableDayPredicate callback in the Flutter Calendar**”. We will include the issue fix in our upcoming Weekly nuget release, which is expected to be rolled out by March 8, 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have improved the behavior of the “**Decoration not working while using the selectableDayPredicate callback in the Flutter DateRangePicker**” in our latest Weekly Nuget package version 19.4.55. If the today is selectable predicate date, then disabled date decoration will be applied for those date.  Kindly update to the latest version for this behavior. Please find the latest version from the following link.

**Pub link:**
https://pub.dev/packages/syncfusion_flutter_datepicker/versions 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
