### ISSUE TITLE
[syncfusion_flutter_datepicker] todayCellDecoration not working with onViewChanged

### ISSUE THREAD

**Issue by fannar** [syncfusion/flutter-widgets#613]
When using onViewChanged, todayCellDecoration is ignored.

The `todayCellDecoration` does not work when using `onViewChanged`. If I comment out the `onViewChanged` the behaviour of `todayCellDecoration` is right.

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';

void main() {
  return runApp(BlackoutDatesUpdation());
}

class BlackoutDatesUpdation extends StatefulWidget {
  @override
  BlackoutDates createState() => BlackoutDates();
}

class BlackoutDates extends State<BlackoutDatesUpdation> {
  List<DateTime> _blackoutDates = <DateTime>[];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Card(
            margin: const EdgeInsets.fromLTRB(50, 150, 50, 150),
            child: SfDateRangePicker(
              selectionMode: DateRangePickerSelectionMode.single,
              monthViewSettings: DateRangePickerMonthViewSettings(
                  blackoutDates: _blackoutDates),
              monthCellStyle: DateRangePickerMonthCellStyle(
                blackoutDateTextStyle: TextStyle(
                  color: Colors.red,
                  decoration: TextDecoration.lineThrough,
                ),
                todayCellDecoration: BoxDecoration( // Does not work with onViewChanged.
                  // color: Colors.green,
                  border: Border.all(
                    color: Colors.white,
                  ),
                ),
              ),
              onViewChanged: viewChanged,
            )),
      ),
    );
  }

  void viewChanged(DateRangePickerViewChangedArgs args) {
    List<DateTime> _blackoutDateCollection = <DateTime>[];
    final DateTime visibleStartDate = args.visibleDateRange.startDate!;
    _blackoutDateCollection.add(visibleStartDate);
    _blackoutDateCollection.add(visibleStartDate.add(Duration(days: 1)));
    _blackoutDateCollection.add(visibleStartDate.add(Duration(days: 2)));
    _blackoutDateCollection.add(visibleStartDate.add(Duration(days: 3)));
    _blackoutDateCollection.add(visibleStartDate.add(Duration(days: 4)));
    SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
      setState(() {
        _blackoutDates = _blackoutDateCollection;
      });
    });
  }
}
```

**Comment by Indumathi1195R** [comment]
Hi,

Currently, we are checking the issue “Decoration not working while using the blackout dates in the Flutter Calendar”. We will validate and update you on the further details on or before March 4, 2022. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have already found and fixed the issue “**Decoration not working while using the blackout dates in the Flutter Calendar**”. We will include the issue fix in our upcoming Weekly nuget release, which is expected to be rolled out by March 8, 2022 and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment]
Hi,

We have improved the behavior of the “**Decoration not working while using the blackout dates in the Flutter Calendar**” in our latest Weekly Nuget package **version 19.4.55.** If the today is blackout date, then blackout date decoration will be applied for those date.  Kindly update to the latest version for this behavior. Please find the latest version from the following link.

**Pub link:**
https://pub.dev/packages/syncfusion_flutter_datepicker/versions 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
