### ISSUE TITLE
[syncfusion_flutter_datepicker] Add future onViewChanged

### ISSUE THREAD

**Issue by fannar** [syncfusion/flutter-widgets#614]
Add a method to allow async onViewChanged. That would allow to update the picker based on data from API call.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we are unable to understand your requirement clearly. If possible, can you please share the below details to us  with clearly.

•	Exact requirement
•	In which scenario you need onViewChanged as async

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R
