### ISSUE TITLE
[syncfusion_flutter_maps] after running the example it showing white screen 

### ISSUE THREAD

**Issue by rashmisridar** [syncfusion/flutter-widgets#615]
A Blank white screen is showing not able to make out what is the issue. After adding the JSON file able to resolve it. But my requirement is based on the user's current location map need to show. After entering the drop location need to draw a path also both from and destination location pinpoint. Is this possible let me know Thanks

**Comment by madasamy99** [comment]
Hi Rashmi,
 
We can add the current live location in SfMaps, kindly check the below blog for the same

https://www.syncfusion.com/blogs/post/how-to-add-location-tracking-to-your-app-using-syncfusion-flutter-maps.aspx 

 
Please let us know if you need further assistance in this.
 
Regards,
Madasamy M

**Comment by rashmisridar** [comment]
Ok Sure. Thank you.
