### ISSUE TITLE
SfDataGrid han Row Default Height isDense: true

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#617]
is there any  isDense option for header and rows. default height is too much and if we set height . and we change font size its not perfect.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Based on the provided information, we suspect that you are trying to set the row height based on its content. If yes, you can set getIntrinsicRowHeight for the respective row in the onQueryRowHeight callback and set the autoFitPadding as zero in GridColumn. We have prepared a sample for that; please check the following sample and code snippet,

Code snippet:
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: SfDataGrid(
        source: _employeeDataSource,
        columnWidthMode: ColumnWidthMode.fill,
        columns: getColumns,
        gridLinesVisibility: GridLinesVisibility.both,
        onQueryRowHeight: (details) {
          return details.getIntrinsicRowHeight(details.rowIndex);
        },
      ),
    );
  }
```
In GridColumn:
```dart
GridColumn(
        autoFitPadding: const EdgeInsets.all(0),
        columnName: 'id',
        label: Container(
          alignment: Alignment.center,
          child: const Text(
            'ID',
            overflow: TextOverflow.ellipsis,
          ),
        ),
      ),
```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-410089681

We have already provided examples in our UG documentation. Please go through this,

UG Documentation: https://help.syncfusion.com/flutter/datagrid/row-height-customization#fit-the-row-height-based-on-its-content

Regards,
Tamilarasan P

**Comment by abdulrehmananwar** [comment]
thanks its working
