### ISSUE TITLE
SfSliderTheme labels alignment at min and max

### ISSUE THREAD

**Issue by dchaitu** [syncfusion/flutter-widgets#619]
In SfSlider

Expected:
![image](https://user-images.githubusercontent.com/33480220/156748704-626eede2-47ed-4d7a-8606-bd6e75df10f8.png)

Actually what I got
![image](https://user-images.githubusercontent.com/33480220/156749121-23e9a4ff-0731-458f-a197-f34e8f2d3117.png)
How to change the positioning of the labels?

**Comment by PraveenGopalsamy** [comment]
Hi,

At present, there is no direct way to achieve this requirement. However, we have achieved this UI by customizing the divider shape in sliders. We have attached the code snippet for your reference.

```
  double _value = 50000;
  double _min = 10000;
  double _max = 100000;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SfSlider(
      min: _min,
      max: _max,
      showLabels: true,
      showDividers: true,
      interval: _max - _min,
      value: _value,
      labelFormatterCallback: (dynamic value, String text) {
        return " ";
      },
      dividerShape: _CustomDivider(MediaQuery.of(context), _min, _max),
      onChanged: (value) {
        setState(() {
          _value = value;
        });
      },
    ));
  }
}

class _CustomDivider extends SfDividerShape {
  _CustomDivider(this.mediaQueryData, this.min, this.max)
      : _textSpan = TextSpan(),
        _textPainter = TextPainter();
  final MediaQueryData mediaQueryData;
  final double min;
  final double max;
  TextPainter _textPainter;
  TextSpan _textSpan;

  @override
  void paint(PaintingContext context, Offset center, Offset? thumbCenter,
      Offset? startThumbCenter, Offset? endThumbCenter,
      {required RenderBox parentBox,
      required SfSliderThemeData themeData,
      SfRangeValues? currentValues,
      dynamic currentValue,
      required Paint? paint,
      required Animation<double> enableAnimation,
      required TextDirection textDirection}) {
    super.paint(context, center, thumbCenter, startThumbCenter, endThumbCenter,
        parentBox: parentBox,
        themeData: themeData,
        paint: paint,
        enableAnimation: enableAnimation,
        textDirection: textDirection);
    bool isMinimumLabel;
    if (center.dx >= (mediaQueryData.size.width / 2)) {
      isMinimumLabel = false;
    } else {
      isMinimumLabel = true;
    }

    _textSpan = TextSpan(
      text: NumberFormat.currency(symbol: '₹ ', locale: "HI", decimalDigits: 0)
          .format(isMinimumLabel ? min : max),
      style: TextStyle(color: Colors.black),
    );

    _textPainter
      ..text = _textSpan
      ..textDirection = textDirection
      ..textScaleFactor = mediaQueryData.textScaleFactor
      ..layout();
    // To show the label below the track, we had internally used a
    // constant value 24.
    center += Offset((isMinimumLabel ? 0 : -_textPainter.width),
        (mediaQueryData.textScaleFactor * 24) - _textPainter.height / 2);
    _textPainter.paint(context.canvas, center);
  }
}
```

Also, we have considered your request as a feature and the status can be tracked from the feedback portal link.

**Feedback:** https://www.syncfusion.com/feedback/33239/need-edge-labels-text-alignment-in-sliders

 We will prioritize the features of every release based on the demands and priority. So, this feature will be available in any of our releases. If you have any more specifications/suggestions to the feature request, you can add them as a comment in the portal.

**Disclaimer:** The date for this feature implementation is tentative and not a commitment on our parts.

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by dchaitu** [comment]
Also is there any way to add RichText in ToolTip of the slider?

**Comment by PraveenGopalsamy** [comment]
Hi Chaitanya,

The Syncfsuion Sliders widget doesn't have support for having custom widget support in the tooltip. But you can give custom text styles to the tooltip text using the [SfSliderTheme.tooltipTextStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/tooltipTextStyle.html) property. Kindly check the following UG document to know about it.

https://help.syncfusion.com/flutter/slider/tooltip#tooltip-label-style

Please let us know if need any further assistance in this.

Regards,
Praveen G.
