### ISSUE TITLE
Move Row up or down in SfDataGrid

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#620]
is there any option to move any row position by long press and and change row position

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Currently, DataGrid does not have support for row drag and drop feature. We have already considered your request as a feature. This feature will be implemented in our any of our upcoming release. We will let you know when this feature is implemented. You can follow up with the below feedback for further follow up,  

Feedback link: https://www.syncfusion.com/feedback/22292/support-to-drag-and-drop-the-rows

We will let you know once it gets rolled out. We appreciate your patience until then. Please let us know if you require any further assistance.

Regards,
Tamilarasan
