### ISSUE TITLE
SfRangeSlider: when same values for start and end thumb are set, cant change the values for either thumb and an error shows : Null check operator used on a null value.

### ISSUE THREAD

**Issue by daniyalsaeed20** [syncfusion/flutter-widgets#621]
i am using range slider to pick two values to create a list, as long as the start value is smaller than the end value, everything works fine, but when i set both sliders on the same value, incase i only want to have a single value in the list, i cant change the value afterwards and the following issue is raised
_CastError (Null check operator used on a null value)

this issue only rises when ever the Range Slider is is initialized with the same start and end values for the sliders. Other tha  that it works fine, an solution on how to fix this
![2](https://user-images.githubusercontent.com/83030999/157023094-6459fdd7-149c-4c85-a3f5-7642b0e440f0.jpeg)

this is where i am stuck, i am saving this filter for next time and if a filter is selected whilst start and end being the same, i can change it the next time.

**Comment by PraveenGopalsamy** [comment]
Hi Daniyalsaeed20,

We have tried to replicate the mentioned issue with our slider's [latest version](https://pub.dev/packages/syncfusion_flutter_sliders/versions). But, we didn't face any cast error when setting the same SfRangeValues for the Range Slider. We have attached the sample which we tried for your reference. Kindly check the sample and still if you are facing an issue on your side, please provide a sample code snippet along with a replication procedure which will be helpful to reproduce at our side.

 ```
 double _min = 1;
  double _max = 7;
  SfRangeValues _values = SfRangeValues(5, 5);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfRangeSlider(
        min: _min,
        max: _max,
        showLabels: true,
        interval: 1,
        values: _values,
        onChanged: (value) {
          setState(() {
            _values = value;
          });
        },
      ),
    );
  }
}
```


Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by daniyalsaeed20** [comment]
the issue still remained until i reimported to package, for some reason reimporting fixed the issue for me. Thankyou for responding so quick

regards.
