### ISSUE TITLE
Improvements Needed

### ISSUE THREAD

**Issue by shubhamsinha2009** [syncfusion/flutter-widgets#622]
1. Update the packages of flutter
2. Flutter Upgrade Needed
3.  Use Kotlin instead of java(Use coroutine -- Improvement boost needed the pdf viewer)

**Comment by deepika134** [comment]
Hi @shubhamsinha2009 ,

We are analyzing your requirement and will update the further details on March 11, 2022.

Regards,
Deepika Ravi

**Comment by shubhamsinha2009** [comment]
I have done kotlin work forking it but not able to flutter upgrade all of the flutter widgets. But will try

**Comment by deepika134** [comment]
Hi @shubhamsinha2009 ,

Currently, we have no plans to switch our android implementation to kotlin. Please let us know what improvements you like to see in the Syncfusion Flutter PDFViewer android platform.

Regards,
Deepika Ravi.
