### ISSUE TITLE
SfDateRangePicker: Scroll calendar to an date ?

### ISSUE THREAD

**Issue by Frezyx** [syncfusion/flutter-widgets#625]
Is there any possibility to scroll up to a certain date inside the picker programmatically?

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we suspect your requirement is “**Scroll upto the specific date in the Flutter DateRangePicker**”. By using the minimum and maximum date property with navigationDirection as vertical you can achieve this requirement. We have prepared the simple sample for the same. Please find the sample from the following link.

**Sample link:**
https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_minmaxdate-1530760246.zip

We hope that this helps you. If this is not your requirement, can you please share more details about your requirement clearly? It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Frezyx** [comment]
Thanks for your answer, but that's not what I'm looking for.
When I click on the button in the interface, I need to select a date in the picker and scroll the tape of the month before this date. The selected date should be on top of the calendar.

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we have checked and your requirement is move to particular date programmatically. Your requirement can be achieved by using the [displayDate](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerController/displayDate.html) property of the [DateRangePickerController](https://pub.dev/documentation/syncfusion_flutter_datepicker/latest/datepicker/DateRangePickerController-class.html). We have a UG and KB documentation for the same. Please find the documentations from the following link.

**UG link:**
https://help.syncfusion.com/flutter/daterangepicker/date-navigations#programmatic-date-navigation

**KB link:** 
https://www.syncfusion.com/kb/12135/how-to-programmatically-navigate-to-the-date-in-the-flutter-date-range-picker 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
