### ISSUE TITLE
showLastLabel: false in SfRadialGauge not working

### ISSUE THREAD

**Issue by 2000calories** [syncfusion/flutter-widgets#627]
I set both `showFirstLabel`& `showLastLabel` to `false`. However, `showLastLabel` did not behave as expected.

expected: both first label and last label are hidden

output: only the first label is hidden, the last label is shown.

```
RadialAxis(
        radiusFactor: 0.8,
        startAngle: 145,
        endAngle: 35,
        axisLineStyle: const AxisLineStyle(thickness: 30),
        showTicks: false,
        showFirstLabel: false,
        showLastLabel: false,
        ranges: <GaugeRange>[
          GaugeRange(
            startValue: 0,
            endValue: 100,
            startWidth: 30,
            endWidth: 30,
            gradient:
                SweepGradient(colors: <Color>[
              HexColor("#f15532"),
              HexColor("#edca5d"),
              HexColor("#549646"),
            ], stops: const <double>[
              0.25,
              0.50,
              0.75
            ]),
          )
        ],
        pointers: <GaugePointer>[
          NeedlePointer(
            value: 50,
            enableAnimation: true,
            needleColor: HexColor("#edca5d"),
            knobStyle: const KnobStyle(
              color: Colors.white,
              borderColor: Color(0xFFDADADA),
              knobRadius: 0.06,
              borderWidth: 0.04,
            ),
          ),
        ],
        annotations: const <GaugeAnnotation>[
          GaugeAnnotation(
              axisValue: 50,
              angle: 90,
              positionFactor: 0.5,
              widget: Text(
                '50',
                style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 20),
              ))
        ],
      ),
    ],
```

![showLastLabel](https://user-images.githubusercontent.com/25191098/157584496-9cbbc7a7-e64d-4316-a6fc-515df5c12ee6.png)

**Comment by PraveenGopalsamy** [comment]
Hi hans.huang,

We can able to reproduce the reported issue at our end. We have fixed this now and the fix will be included in our Volume 1 main release which will be available at end of March 2022. We will notify you once the fix is rolled out in our release and we appreciate your patience until then. 

Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by 2000calories** [comment]
thanks

**Comment by PraveenGopalsamy** [comment]
Hi hans.huang,

You are welcome. As said, we will inform you once the release has been rolled out. Please let us know if you need any further assistance in this.

Regards,
Praveen G.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @2000calories,

Thanks for your patience. We are glad to let you know that the reported issue has been fixed and rolled out in our SP release. To resolve the issue at your end kindly upgrade the chart package to the latest version mentioned below.

Version: https://pub.dev/packages/syncfusion_flutter_gauges/versions/20.1.55

Regards,
Yuvaraj.
