### ISSUE TITLE
[syncfusion_flutter_datagrid]  Asynchronous data loading is not working properly

### ISSUE THREAD

**Issue by lclrobert2020** [syncfusion/flutter-widgets#629]
The Asynchronous data loading example of the flutter data grid is not working properly,
[https://github.com/SyncfusionExamples/how-to-show-loading-indicator-on-loading-page-in-flutter-datatable](https://github.com/SyncfusionExamples/how-to-show-loading-indicator-on-loading-page-in-flutter-datatable)
The build method is being called repeatedly (you can try adding print("build") in the build method ), also the handlePageChange method of DataGridSource will be called 2 times when the page is loaded.
This cause the page jumping between pages unstoppably when user tries to change pages.

A video showing the bug
[https://streamable.com/7n92v1](https://streamable.com/7n92v1)
Steps to reproduce:
1. Install the example on your device.
2. Press the "2" the change to page 2
3. Watch to see the page keeps jumping between page 1 and 2 (Without any press)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @lclrobert2020 

Based on the provided information, we could be able to reproduce your reported issue. We will validate and update you with the details in two business days i.e., March 15, 2021. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @lclrobert2020,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our weekly pub release. Please update DataGrid package to **20.1.48** version.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan
