### ISSUE TITLE
PDF view scroll horizontal and vertical option

### ISSUE THREAD

**Issue by ReounKompheareak** [syncfusion/flutter-widgets#63]

**Comment by dillibabun** [comment]
Hi @ReounKompheareak 

Greetings from Syncfusion.

At present we do not have support for “Page by page view mode”. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented in our 2021 Volume 2 main release. We will let you know when this feature is implemented.

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

The status of this feature can be tracked using the following link.
https://www.syncfusion.com/feedback/18491/support-for-page-by-page-view 

P.S: We assume that you are using SfPdfViewer widget and trying to view the page horizonatally, and provided the above response. If not, kindly let us know your exact requirement to be achieved in SfPdfViewer flutter widget.

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi @ReounKompheareak 

We have planned to provide Horizontal scrolling support in SfPdfViewer widget for 2021 Volume 3 release. This feature won't includes single view and load the document page by page. The page by page view feature will be planned for any other future releases. Please let us know if you have any concerns.

Regards,
Dilli babu.

**Comment by deepika134** [comment]
Hi @ReounKompheareak,

The support for "Page by page view with horizontal scrolling" has been provided and included in latest package release.
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.43-beta 
Documentation is available here -
https://help.syncfusion.com/flutter/pdf-viewer/page-layout-and-scroll-direction 

We are glad to announce that our Essential Studio 2021 Volume 3 release v19.3.0.43 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Deepika R
