### ISSUE TITLE
[syncfusion_flutter_gauges] - SfRadialGauge takes too much unnecessary space at bottom

### ISSUE THREAD

**Issue by Harsh1052** [syncfusion/flutter-widgets#630]
Hello Thank you for to give amazing and very customise library.
I need to add list of speed meter but it takes more space at bottom.
![image](https://user-images.githubusercontent.com/72139154/158307074-de386e7f-6e24-4e5c-88a8-4362ec40537f.png)

Any properties to remove that spaces

Thank You.

**Comment by Nikunj2505** [comment]
@SuryaChinnadurai I'm also facing the issue with the space at the bottom of the Radial Gauge. While waiting for the feature request, is there any workaround or temporary solution you can suggest?

**Comment by hamzahussainshah** [comment]
![image](https://github.com/user-attachments/assets/07668fa9-af3a-48c2-a892-6b92f73c3c77)
still in 2024 i am facing empty space at top and bottom. How i can remove empty spaces

**Comment by AswiniDileep** [comment]
Hi All,

Currently, removing the bottom space in the Radial Gauge is not directly supported. However, you can use the [canScaleToFit](https://pub.dev/documentation/syncfusion_flutter_gauges/latest/gauges/RadialAxis/canScaleToFit.html) property to vertically center the gauge within its container for a better alignment.
 
Screenshot:
![image](https://github.com/user-attachments/assets/c3745cec-951a-444d-bced-cbfbd2c829a7)
 
For more details, please refer to this UG link: [Positioning the axis based on its angle in radial gauge.](https://help.syncfusion.com/flutter/radial-gauge/axes#axis-customization:~:text=Positioning%20axis%20based%20on%20its%20angle)
 
we have already created FR regarding this Need to layout the radial gauge based on the start and end angles request and it has been already added to our Wishlist for future consideration. You can track its progress and status in our [Feedback Portal](https://www.syncfusion.com/feedback/27881/need-to-layout-the-radial-gauge-based-on-the-start-and-end-angles).  
 
Our team regularly reviews and prioritizes features based on user demand, and this request will be considered in any of our upcoming releases. If you have additional specifications, suggestions, or ideas, feel free to share them through the feedback portal, and they will be considered during the feature development process.
 
If you need any further assistance or clarification, please feel free to reach out.

Regards,
Aswini S.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you need further assistance on this.
