### ISSUE TITLE
How can i change the calendar view to threeDay? Is there any way?

### ISSUE THREAD

**Issue by sombreroinfotech2018** [syncfusion/flutter-widgets#631]

**Comment by Indumathi1195R** [comment]
Hi,

We have already considered this is a feature “**Providing a number of days support in the Flutter Calendar**” and implemented. We will include this feature in our upcoming 2022 Volume 1 release, which is expected to be rolled out by end of March 2022 and let you know once the release rolled out. We appreciate your patience until then.

You can track the status of this report through the following feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/27376/support-for-3-days-view-like-google-calendar 

Regards,
Indumathi R
