### ISSUE TITLE
Add Focus Node to buildEditWidget TextField and call Await Function on !hasFocus

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#635]
i am using textfield in buildEditWidget  and if i use autofocus it work fine butt if i use focus node its not working fine
i want to use focus node to call future funtion on leave foucus. butt i was unable to do so. its some thing like blow
 

focusnode.addListener(() async{
      if (!focusnode.hasFocus) {
        if (columnName=="qty")
        {
await new Future.delayed(new Duration(milliseconds: 1500), ()
{
   Navigator.of(context).pushNamed("/home");

}
        myFocusNode.requestFocus();         
        }
      }
    });

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Currently, DataGrid does not have support for calling the future function in cell editing. We have already considered the feature of making the onCellSubmit method async. We suspect that this feature can satisfy your requirements. Can you please check whether this meets your requirements?

We will implement this feature in our 2022 Volume 1 SP release, which is expected to be rolled out on mid of May 2022. You can follow up with the below feedback for further details,

Feedback Link: [https://www.syncfusion.com/feedback/33165/make-oncellsubmit-method-as-async-to-process-the-asynchronous-operation-on-editing](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F33165%2Fmake-oncellsubmit-method-as-async-to-process-the-asynchronous-operation-on-editing&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C3294be2642864627ca6008da08c4da8b%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637831938818132774%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cPY26T5jLftK8acT%2BJleT96eeWM7kh6RVbkMfaLaAkQ%3D&reserved=0)

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
if i just talk about focus node its also not working fine.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

We're not entirely sure what you're looking for. Are you attempting to open another page while entering edit mode on the "qty" column and will you need to again focus on the "qty" column cell after 1500 ms? Please confirm these details, it will assist us in validating the requirements and delivering the solution at the earliest.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
in cell textfield when user input some text i want to call API. i also want to show autocomplete against input value from Cloud API. and validate if user input some data its should be exist in API other wise canSubmitCell will be call.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

We suspect that your requirement can be achieved using the feature that we already shared, i.e., making the **onCellSubmit** method async. **Can you please check and confirm with us whether this meets your requirements?**

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
i want to call canSubmitCell remain false until completion of future function
