### ISSUE TITLE
[syncfusion_flutter_calendar] Add list padding to schedule view 

### ISSUE THREAD

**Issue by Justus-M** [syncfusion/flutter-widgets#636]
I would like to add padding to the schedule view, because I have it scrolling behind a transparent appbar and bottom bar, but without padding, the first and last event in the schedule view are behind the appbar and bottom navigation bar.

I would do it myself, but it looks like this repo is not up to date. Are the latest versions no longer public?

Otherwise, would it be possible for you to add this?

I think it would just require some optional sliverpadding in the customscrollview

**Comment by Indumathi1195R** [comment]
Hi,

Based on the shared information, we are unable to understand your requirement clearly. If possible, can you please share below details about your issue clearly? Or we suggest to use the padding property for the Calendar placed Widget. 

•	Code snippet 
•	Issue replication procedure

It would be helpful for us to analyze and provide you a solution at the earliest.

Regards,
Indumathi R

**Comment by Justus-M** [comment]
As you can see in the following screenshot, the bottom event is underneath the bottom navigation bar. It is stuck because there is no padding at the end of the list

I would like to add some padding inside the list, so that it can be scrolled to see this event.

I don't want to add padding to the entire calendar widget, because I want to keep this "glass" effect of the bottom bar, so you can see events passing underneath it as you scroll.
 

![simulator_screenshot_E9F9A4BA-0E48-4BAB-B615-4F30ABCDA51C](https://user-images.githubusercontent.com/37046316/159026914-11ad94a8-3943-48c7-a28f-39c4164b017f.png)

**Comment by Indumathi1195R** [comment]
Hi,

As per the current implementation of the calendar, there is no support for adding the padding event list. But you can achieve this by adding the appointment with transparent UI at the end date of the appointment list using the [appointmentBuilder](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/appointmentBuilder.html). We hope that this information helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
