### ISSUE TITLE
[syncfusion_flutter_xlsio] Add tables to worksheets

### ISSUE THREAD

**Issue by ahmednfwela** [syncfusion/flutter-widgets#637]
a full documentation is here: https://docs.microsoft.com/en-us/office/open-xml/working-with-tables
simply, a `<tableParts>` element is added to the `<worksheet>` element
```xml
<worksheet>
    <tableParts count="1">
        <tablePart r:id="rId1"/>
    </tableParts>
</worksheet>
```
and then in a new file (e.g. table1.xml) we define the actual table
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<table xmlns="https://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="Table1" displayName="Table1" ref="A1:C4" totalsRowShown="0">
    <autoFilter ref="A1:C4"/>
    <tableColumns count="3">
        <tableColumn id="1" name="Column1"/>
        <tableColumn id="2" name="Column2"/>
        <tableColumn id="3" name="Column3"/>
    </tableColumns>
    <tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/>
</table>
```

also closedXml has a great api for working with tables https://github.com/ClosedXML/ClosedXML/wiki/Inserting-Tables

**Comment by SivakumarRamya** [comment]
Hi Ahmed Fwela,

Greeting from Syncfusion.

Currently, we do not have the support for creating tables in Excel documents. But, this feature will be included in our upcoming release 2022 Volume 1 main release which is expected to be available at the end of March 2022.

Regards,
Ramya.

**Comment by SivakumarRamya** [comment]
Hi Ahmed Fwela,

We appreciate your patience.

As promised earlier **Implement the tables creation support in Flutter XlsIO** feature is included in the 2022 Vol1 main release. And We are glad to announce that our Essential Studio 2022 Volume 1 release v20.1.0.47 is rolled out and is available for download under the following link.

[https://www.syncfusion.com/forums/174125/essential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F174125%2Fessential-studio-2022-volume-1-main-release-v20-1-0-47-is-available-for-download&data=04%7C01%7Cramya.s%40syncfusion.com%7C3a7e230761264f5ec1fe08da16376e74%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637846724575763856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FANyw3mpqaFXup6M%2FiMx6fMBMh7hiy%2FpjU0v411r9a8%3D&reserved=0)

We thank you for your support and appreciate your patience in waiting for this release. Please contact us if you would require any further assistance.

Kindly refer the following link to know more about the tables.
https://help.syncfusion.com/flutter/xlsio/working-with-table

Regards,
Ramya.

**Comment by ahmednfwela** [comment]
I get a problem when opening excel files after saving them with tables
It asks me to repair the file, and then i get
```
Removed Feature: Table from /xl/tables/table1.xml part (Table)
```

**Comment by SivakumarRamya** [comment]
Hi Ahmed Fwela,

We deeply regret the inconvenience caused.

Kindly share the corrupted Excel file which would help us to proceed further.

Regards,
Ramya.

**Comment by ahmednfwela** [comment]
The issue was because i had some merged cells where the table was, once i undid the merge it worked fine, great job!
