### ISSUE TITLE
Memory leak in SfCartesianChart

### ISSUE THREAD

**Issue by BentEngbers** [syncfusion/flutter-widgets#639]
We need an interactive graph, with custom zooming and panning functionality. We also need to update the chart widget whenever the axes change for example, or whenever something else such as chart annotations changes.
This functionality is not possible, because everytime we rebuild the graph, the memory footprint increases drastically. 
What is causing the memory leak when rebuilding the chart widget? This should not be happening and definitely sounds like a serious bug to me.

We have created a simple reproduction, that shows the problem. Every time the chart is rebuilt (which in our case can be a lot depending on user actions), the chart points seem to be doubled. here is a snippet (with full source code attached)

```dart 
import 'dart:async';
import 'dart:math';

import 'package:syncfusion_flutter_charts/charts.dart';
import 'package:flutter/material.dart';

final Random random = Random();

class Chart extends StatefulWidget {
  // ignore: prefer_const_constructors_in_immutables
  Chart({Key? key}) : super(key: key);

  @override
  _ChartState createState() => _ChartState();
}

class _ChartState extends State<Chart> {
  @override
  void initState() {
    super.initState();

    Timer.periodic(
      const Duration(milliseconds: 100),
      (Timer t) => setState(() {}),
    );
  }

  final zoomPan = ZoomPanBehavior();

  final myAxis = NumericAxis();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Memory Leak Demo')),
      body: SfCartesianChart(
        primaryXAxis: myAxis,
        series: [
          LineSeries<_SalesData, double>(
            dataSource: List.generate(
              1000,
              (index) => _SalesData(index.toDouble(), index.toDouble()),
            ),
            xValueMapper: (_SalesData sales, _) => sales.year,
            yValueMapper: (_SalesData sales, _) => sales.sales,
          ),
        ],
        zoomPanBehavior: zoomPan,
      ),
    );
  }
}

class _SalesData {
  _SalesData(this.year, this.sales);

  final double year;
  final double sales;
}


```

Providing the chart with a unique key fixes the problem as it clears up the memory, but this stops further interaction with the chart.

We will have to rebuild the chart widget sometimes, and `updateDatasource` is not enough.
Especially since our datasource does not change. 

We have also posted this on the form https://www.syncfusion.com/forums/173730/memory-leak-on-rebuilding-charts . 

We believe this is a very serious issue, and we hope that a fix wil be available soon.

Regards, 

Bent

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @BentEngbers 

We could replicate the memory leaks on calling setState(). So we will ensure and resolve the memory leaks occurring in all the scenarios, including all the chart types and will include the fixes in our upcoming 2022 Volume SP release. This is expected to be out at the end of April 2022. Please be patience until then. 

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @BentEngbers,

The reported issue regarding memory leak while rebuilding the application has been fixed, and it is rolled out in our SP1 release. To avoid this issue please upgrade the chart package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.55

Regards,
Yuvaraj.

**Comment by daveshirman** [comment]
I am seeing a huge memory leak, leading to the complete unresponsiveness of our app still, with the latest version: `syncfusion_flutter_charts: ^20.1.59`

Can this be checked again?

**Comment by wenjiasen** [comment]
I'm using `SfCartesianChart` to create a real-time sound waveform graph, which does still have memory leaks when updated at high frequencies.
I have used the most version, `syncfusion_flutter_charts: ^20.3.59`.

This example code reproduces the problem in its entirety：
```dart
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

class SoundData {
  SoundData(this.milliseconds, this.value);
  final int milliseconds;
  final int value;
}

/// Example app.
class RecordChart extends StatefulWidget {
  const RecordChart({Key? key}) : super(key: key);

  @override
  State<RecordChart> createState() => _RecordChartState();
}

class _RecordChartState extends State<RecordChart> {
  List<SoundData> dataSource = [];

  @override
  void initState() {
    super.initState();
    Timer.periodic(Duration(milliseconds: (100).floor()), (timer) {
      setState(() {
        dataSource = freshData();
      });
    });
  }

  @override
  void dispose() {
    super.dispose();
  }

  List<SoundData> freshData() {
    List<SoundData> list = [];
    var random = Random();
    for (var i = 0; i < 2000; i++) {
      list.add(SoundData(i + 1, random.nextInt(32763) * (i % 2 == 0 ? 1 : -1)));
    }
    return list;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Record to Stream ex.'),
      ),
      body: SfCartesianChart(
        title: ChartTitle(text: 'Record'),
        primaryYAxis: NumericAxis(minimum: -32763, maximum: 32763),
        primaryXAxis: NumericAxis(),
        series: <LineSeries<SoundData, int>>[
          LineSeries<SoundData, int>(
              dataSource: dataSource,
              xValueMapper: (SoundData sales, _) => sales.milliseconds,
              yValueMapper: (SoundData sales, _) => sales.value)
        ],
      ),
    );
  }
}

```

![image](https://user-images.githubusercontent.com/16320597/206379090-4b190600-e1ea-40d8-9cfd-d614dea2145d.png)

**Comment by LokeshPalani** [comment]
Hi @wenjiasen,

We have fixed the issues related to memory leaks in our **Volume 4 Main Release** in 2023. To avoid this issue, please upgrade the **syncfusion_flutter_charts** package to the latest version provided below.


**Version Link**,
https://pub.dev/packages/syncfusion_flutter_charts/versions/24.2.4+3 


Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
