### ISSUE TITLE
[syncfusion_flutter_charts]Dynamic y axis range based on visible x axis category

### ISSUE THREAD

**Issue by julian919** [syncfusion/flutter-widgets#640]
When the chart first loads, it looks normal as shown below (displays y axis range based on x-axis value),

![image](https://user-images.githubusercontent.com/51945973/159418362-6d8fd7c6-c0ec-4b2f-8ca6-bc218f1f5e68.png)

But when the user starts to pan, the y axis range defaults to the max x-axis category value

![image](https://user-images.githubusercontent.com/51945973/159418512-48458c94-def8-4cf0-8a27-df4fbd451f14.png)
![image](https://user-images.githubusercontent.com/51945973/159440331-f07151eb-e987-4cdf-8946-efcacbc5e172.png)

Is it possible to dynamically calculate the y axis range based on the visible x axis category?

**Comment by julian919** [comment]
Sample code:

SfCartesianChart(
                trackballBehavior: _trackballBehavior,
                margin: const EdgeInsets.all(10),
                plotAreaBorderWidth: 0,
                primaryXAxis: CategoryAxis(
                  zoomFactor: 0.000001,
                  majorTickLines: MajorTickLines(width: 0),
                  majorGridLines: MajorGridLines(width: 0),
                  axisLine: AxisLine(width: 1, color: clr.lightGreyColor),
                  visibleMaximum: 10,
                  visibleMinimum: 0,
                  interval: 1,
                  labelStyle: Theme.of(context)
                      .textTheme
                      .subtitle1!
                      .copyWith(color: clr.indicatorColor),
                ),
                primaryYAxis: NumericAxis(
                    anchorRangeToVisiblePoints: true,
                    title: AxisTitle(
                        text: 'Coverage',
                        textStyle: Theme.of(context)
                            .textTheme
                            .subtitle1
                            ?.copyWith(
                                fontSize: 10, color: clr.lightGrey2Text)),
                    majorTickLines: MajorTickLines(width: 0),
                    majorGridLines: MajorGridLines(
                        color: Color(0xFF000000).withOpacity(0.04)),
                    axisLine: AxisLine(width: 0, color: Colors.transparent),
                    numberFormat: NumberFormat.compactSimpleCurrency(),
                    labelStyle: Theme.of(context)
                        .textTheme
                        .subtitle1!
                        .copyWith(color: clr.indicatorColor)),
                zoomPanBehavior: _zoomPanBehavior,
                series: widget.chartSeries),

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @julian919,

Greetings from syncfusion. In our chart, we have an [anchorRangeToVisiblePoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/anchorRangeToVisiblePoints.html) property on the axis. When we set this property to true and give the [zoomMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior/zoomMode.html) property value as ZoomMode.x in [zoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/zoomPanBehavior.html), it will render the y-axis range based on the visible data point's Y value. Currently, it is working for other series types except for the StackedColumnSeries. But we have already fixed this. The fix will be included in our next weekly patch release which is expected to be roll-out on 5th April 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @julian919,

The reported issue has been fixed and rolled out in our weekly patch release. To avoid this please upgrade your package to the latest version below.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.47+1

Regards,
Yuvaraj.
