### ISSUE TITLE
Pdf Viewer - Blank Space

### ISSUE THREAD

**Issue by ariefsn** [syncfusion/flutter-widgets#642]
Hello,
how to remove blank space above and below pdf view?
in single mode.
![image](https://user-images.githubusercontent.com/33569737/159697661-64b4e863-b72a-4842-867d-dbbd1feffb6f.png)

Thanks.

**Comment by deepika134** [comment]
Hi Arief Setiyo Nugroho,

To remove the black space in singlepagelayout mode, you can use the SizedBox widget with the height of the PDFViewer. The height depends on the mobile width with the proper aspect ratio. The following code example explains the same.

```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: const Text('Syncfusion Flutter PDF Viewer'),
    ),
    body: SizedBox(
      height: 565,
      child: SfPdfViewer.asset(
        'assets/gis_succinctly.pdf',
        pageLayoutMode: PdfPageLayoutMode.single,
      ),
    ),
  );
}
```
Regards,
Deepika Ravi
