### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by marcoberetta96** [syncfusion/flutter-widgets#643]
Hi.

I have this situation.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/11749393/159678259-2917024b-17f1-419f-a6fa-a89458f6f002.png">

I would like to make transparent the yellow area.
If I try I obtain this...
<img width="244" alt="image" src="https://user-images.githubusercontent.com/11749393/159678352-abeba604-b6cb-4788-a672-845ec477f89a.png">

... which is not very good because the tooltip is very far from the slider.
Is there a way I can reduce the white space between the tooltip and the slider?

Thanks!

**Comment by PraveenGopalsamy** [comment]
Hi Marco Beretta ,

Currently, there is no direct support to reduce the space between the tooltip text and thumb in the range slider. So, we meet your requirement using [startThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/startThumbIcon.html) and [endThumbIcon](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/endThumbIcon.html) properties and prepared a sample for your reference.

**Code Snippet:**

```
late SfRangeValues _values;
late NumberFormat _numberFormat;
late TextEditingController _rangeStartController;
late TextEditingController _rangeEndController;

Widget _buildThumbIcon(TextEditingController controller) {
  return Transform.translate(
    // Here -20 is thumb diameter and -5 is spacing between thumb and text.
    offset: const Offset(0, -25),
    child: OverflowBox(
      maxWidth: 150,
      child: TextField(
        textAlign: TextAlign.center,
        decoration:
            const InputDecoration(border: InputBorder.none, isDense: true),
        controller: controller,
      ),
    ),
  );
}

String _getFormattedText(dynamic value) {
  return _numberFormat.format(value);
}

@override
void initState() {
  _values = const SfRangeValues(3.0, 7.0);
  _numberFormat = NumberFormat('#.##');
  _rangeStartController = TextEditingController();
  _rangeEndController = TextEditingController();
  super.initState();
}

@override
void dispose() {
  _rangeStartController.dispose();
  _rangeEndController.dispose();
  super.dispose();
}

@override
Widget build(BuildContext context) {
  return Scaffold(
    body: SfRangeSlider(
      min: 0.0,
      max: 10.0,
      startThumbIcon: _buildThumbIcon(_rangeStartController),
      endThumbIcon: _buildThumbIcon(_rangeEndController),
      values: _values,
      onChangeStart: (SfRangeValues newValues) {
        _rangeStartController.text = _getFormattedText(newValues.start);
        _rangeEndController.text = _getFormattedText(newValues.end);
      },
      onChanged: (SfRangeValues newValues) {
        setState(() {
          _rangeStartController.text = _getFormattedText(newValues.start);
          _rangeEndController.text = _getFormattedText(newValues.end);
          _values = newValues;
        });
      },
      onChangeEnd: (SfRangeValues newValues) {
        _rangeStartController.text = "";
        _rangeEndController.text = "";
      },
    ),
  );
}
```

**Output:**

![image](https://user-images.githubusercontent.com/83585210/159906545-1e7acb33-a18b-43e1-80b6-f113d4ab9a22.png)


We hope that this solution will fulfill your requirement. Kindly let us know if you need further assistance with this.

Regards,
Praveen G.

**Comment by marcoberetta96** [comment]
It is perfect, thank you!!
