### ISSUE TITLE
[bug] Setting the axis to a maximum of zero gives a weird error message

### ISSUE THREAD

**Issue by lucavenir** [syncfusion/flutter-widgets#647]
Hi there,

the following is a minor issue that is easily avoidable, but the way this library gave me feedback that misled me about the bug I was introducing.

# Context:
My plot has a red plot band to be always visible on top of my data; it represents a "maximum value" threshold.
Such "maximum value" **could be zero in some cases**, mainly because of some server-side issues.

# Expectations:
What I'd expect from the library is the following: if you plot something with a maximum height of zero, you either:

1. Throw and let the user (me) decide how to handle the exception. Maybe we show an error message? An empty plot with an error message on top of it?
OR
2. Plot nothing, **but** let the user know that you're seeing nothing _because of that maximum value set to zero_.

# Behavior:
What happens, instead, is that whenever you set `maximum` to `0` I get the following error message:
```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during paint():
RRect argument contained a NaN value.
'dart:ui/painting.dart':
Failed assertion: line 37 pos 10: '<optimized out>'


The relevant error-causing widget was
SfCartesianChart
lib/main.dart:66
```

There's no reference on what caused this issue, and the stack trace doesn't help in this case.
Anyways, the library _catches_ this error and **plots an empty plot**. This may be desirable, or maybe not (to be fair, it is in my case), but this doesn't help me understand what's going on under the hood.

# Reproducible Example

In the following reproducible example I've pointed out the exact line causing the issue:
```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(
        title: 'Flutter Demo Home Page',
        someMaximumValue: 0,
        someTest: true,
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  final double someMaximumValue;
  final bool someTest;

  const MyHomePage({
    Key? key,
    required this.someMaximumValue,
    required this.title,
    required this.someTest,
  }) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<LoadcurvePoint> data;
  @override
  void initState() {
    data = parseResponse();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final aRedLine =
        widget.someTest ? widget.someMaximumValue / 4 : widget.someMaximumValue;

    return Scaffold(
      appBar: null,
      body: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text("My plot", style: Theme.of(context).textTheme.headline4),
          const SizedBox(height: 10),
          SfCartesianChart(
            margin: const EdgeInsets.only(right: 10.0),
            primaryXAxis: DateTimeAxis(
              // This hides the gridlines of y-axis
              majorGridLines: const MajorGridLines(width: 0),
              axisLabelFormatter: (args) => ChartAxisLabel(
                args.text,
                args.textStyle.copyWith(color: Colors.white),
              ),
              //Hide the axis line of y-axis
              axisLine: const AxisLine(width: 0),
              enableAutoIntervalOnZooming: false,
              dateFormat: DateFormat.H(),
              plotBands: [
                PlotBand(
                  shouldRenderAboveSeries: true,
                  associatedAxisStart: aRedLine,
                  associatedAxisEnd: aRedLine,
                  borderColor: const Color(0xffBC0000),
                  borderWidth: 2,
                  isVisible: true,
                ),
              ],
              desiredIntervals: 24 ~/ 4,
              interval: 4,
              intervalType: DateTimeIntervalType.hours,
            ),
            primaryYAxis: NumericAxis(
              title: AxisTitle(
                text: "kWh",
                textStyle: Theme.of(context)
                    .textTheme
                    .bodyText1
                    ?.copyWith(height: 1, fontSize: 12),
              ),
              rangePadding: ChartRangePadding.none,
              axisLabelFormatter: (args) => ChartAxisLabel(
                args.text,
                args.textStyle.copyWith(color: Colors.white),
              ),
              labelFormat: "{value}",
              numberFormat: NumberFormat(
                '0.0',
                Localizations.localeOf(context).languageCode,
              ),
              maximum: aRedLine * 1.1, // This is the breaking issue
            ),
            series: [
              ColumnSeries(
                dataSource: data,
                yAxisName: "kWh",
                pointColorMapper: (LoadcurvePoint d, _) => d.pointColor,
                xValueMapper: (LoadcurvePoint d, _) => d.ts,
                yValueMapper: (LoadcurvePoint d, _) => d.value,
                animationDuration: 1,
                borderWidth: 1,
                width: 1,
              ),
            ],
            // ),
            // ),
            // ],
          ),
        ],
      ),
    );
  }
}

// PRESENTATION UTILS
String _prefixLabel(DateTime ts) => DateFormat('HH:mm').format(ts);
String _label(LoadcurvePoint v) {
  final NumberFormat f = NumberFormat(
    '#,##0.#',
    Intl.getCurrentLocale(),
  );
  return "${_prefixLabel(v.ts)} ${v.value} Wh";
}

class LoadcurvePoint {
  LoadcurvePoint(this.ts, this.value, this.pointColor);
  final DateTime ts;
  final num value;
  final Color pointColor;
}
```

# Workaround

There isn't really a workaround, once I understood what the problem was (this zero-value) I simply display another Widget instead of the empty plot. This issue is about the error message being displayed misleading me about the nature of my bug.

**Comment by sfHariHaraSudhan** [comment]
Hi,
 
We are able to replicate the reported issue regarding “**Exception-thrown-in-rect-type-series-while-setting-the-axis-maximum-value-as-zero**” at our end and have logged bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on July 4, 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.
 
Feedback link: https://www.syncfusion.com/feedback/44657/exception-thrown-in-rect-type-series-while-setting-the-axis-maximum-value-as-0
 
Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment]
Hi @lucavenir,

The reported issue regarding **Exception thrown in rect type series while setting the axis maximum value as 0** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.1.37

Regards,
Hari Hara Sudhan. K.
