### ISSUE TITLE
Re-Caching pdf

### ISSUE THREAD

**Issue by AzharZouhir** [syncfusion/flutter-widgets#648]
i found out that every time i open pdf it get cached again with different name making data folder get bigger

**Comment by deepika134** [comment]
Hi @AzharZouhir,

We are checking on the reported query and will update the further details on April 1, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi @AzharZouhir,

We tried to reproduce the reported issue from our side. The PDF documents where cached properly in app folder of android devices. Kindly share us the issue reproducing steps and issue confirming ways of checking cache folder. We have checked in device file explorer of android studio, but cache PDF wasn't presented in the app folder.

Regards,
Deepika Ravi
