### ISSUE TITLE
[syncfusion_flutter_calendar] How to set color of selected cell like cellBorderColor?

### ISSUE THREAD

**Issue by Frezyx** [syncfusion/flutter-widgets#649]
SfCalendar have cellBorderColor. But i can't find how i can change border color of selected cell ?

**Comment by Indumathi1195R** [comment]
Hi,

**Regarding Query: How to set color of selected cell like cellBorderColor?**

By using the [selectionDecoration](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/selectionDecoration.html) property, you can customize the selected cell. We have a UG documentation for the same. Please find the documentation from the following link.

**UG link:** https://help.syncfusion.com/flutter/calendar/getting-started#selection-decoration 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by Frezyx** [comment]
Thank you, @Indumathi1195R !
