### ISSUE TITLE
How to change the size of the month navigation arrows?

### ISSUE THREAD

**Issue by ajaygautam** [syncfusion/flutter-widgets#65]
Hello

Thanks for the date selector plugin.
Question: How do I change the size of the arrow keys on the month navigation? (see attached screenshot)

<img width="316" alt="iPhone_11_Pro_–_14_2_and_aip_app_–_tournaments-add_dart" src="https://user-images.githubusercontent.com/60637/99927118-1763a680-2d12-11eb-951c-db4e2e903d20.png">

My current widget config:
```
SfDateRangePicker(
                onSelectionChanged: _onDateSelectionChanged,
                enablePastDates: false,
                showNavigationArrow: true,
                headerStyle: DateRangePickerHeaderStyle(
                  textStyle: TextStyle(
                    color: appState.visualData.textColor,
                    fontWeight: FontWeight.w600,
                    fontSize: 20,
                  ),
                ),
                monthCellStyle: DateRangePickerMonthCellStyle(
                    textStyle: TextStyle(
                  fontWeight: FontWeight.w500,
                  fontSize: 20,
                )),
                monthViewSettings: DateRangePickerMonthViewSettings(
                    dayFormat: 'EEE',
                    viewHeaderStyle: DateRangePickerViewHeaderStyle(
                      textStyle: TextStyle(
                        fontWeight: FontWeight.w600,
                        fontSize: 13,
                      ),
                    )),
              ),
```

**Comment by Indumathi1195R** [comment]
Hi @ajaygautam,

Based on the provided information, we have checked your requirement “**Changing the size of the month navigation arrow in SfDateRangePicker**”. Date range picker doesn’t have support for changing the navigation arrow size. But your requirement can be achieved by hiding the default header using **_headerHeight_** property value as 0 and placing the custom header in the date range picker. We have a KB document for header customization. Please find the KB from the following link,

**KB link:** https://www.syncfusion.com/kb/11427/how-to-customize-the-header-view-of-the-flutter-date-range-picker

**UG link:** https://help.syncfusion.com/flutter/daterangepicker/headers#customize-the-header-height

We hope that the above helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
