### ISSUE TITLE
[syncfusion_flutter_datagrid] - Top And Left Border Not Displayed 

### ISSUE THREAD

**Issue by Verzu23** [syncfusion/flutter-widgets#650]
Hi all,

I just implement the syncfusion DataGrid basic example and added all Border (vertical and horizontal).
This is what I get.

![2022_03_29_16_45_26_Window](https://user-images.githubusercontent.com/23505339/160638781-c0ab879c-d309-4851-9656-025b40eade11.png)

I just use these two lines of code 

`gridLinesVisibility: GridLinesVisibility.both,`
 `headerGridLinesVisibility: GridLinesVisibility.both,`

Is this a bug or i'm missing something?

Thanks in advance

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Verzu23,

Greetings from Syncfusion.

By default, we have shown only the bottom and right outer borders. So, the top and left borders are not shown. That’s the behavior of the DataGrid. You can set the top and left borders by wrapping the DataGrid inside a Container widget and setting the required borders for the Container. We have prepared the sample for that. Please check the following sample and code snippet.

Code Snippet:
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: Card(
        margin: const EdgeInsets.all(30),
        child: Container(
          decoration: BoxDecoration(
              border: Border(
                  top: BorderSide(
                      width: 1.0, color: Colors.grey.withOpacity(0.45)),
                  left: BorderSide(
                      width: 1.0, color: Colors.grey.withOpacity(0.45)))),
          child: SfDataGrid(
            source: _employeeDataSource,
            gridLinesVisibility: GridLinesVisibility.both,
            headerGridLinesVisibility: GridLinesVisibility.both,
            columnWidthMode: ColumnWidthMode.fill,
            columns: getColumns,
          ),
        ),
      ),
    );
  }

```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample482960491

Also, we have published the KB for how to set a border for Flutter DataGrid. Please refer to our KB documentation for more details.

KB Link: https://www.syncfusion.com/kb/12522/how-to-set-border-for-flutter-datatable-sfdatagrid

We hope this helps. Please let us know if you need any further assistance. We will be glad to assist you.

Regards,
Tamilarasan
