### ISSUE TITLE
Zooming and Scrolling not working when used together

### ISSUE THREAD

**Issue by HemangVHLink** [syncfusion/flutter-widgets#651]
Hi there
I have implemented scrolling to new/previous data using [loadmore sample](https://www.syncfusion.com/kb/12535/how-to-lazily-load-more-data-to-the-chart-sfcartesianchart).
Now when i used zooming and try to scroll zooming is reset to default
Also logs were kept to check for zooming Factor and Zooming position , at and they provide values 1.0 and 0.0 respectively

I need load more feature with zoooming
For eg if i zoom to level 0.6 then on scrolling same zooming should be utilise while scrolling
I Need sample for same where zooming and scrolling both are used

Thanks

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @HemangVHLink,


We have evaluated the load more sample with [zoomPanBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ZoomPanBehavior-class.html), the zoom factor is maintained when scrolling and works as expected. We have attached the sample which was used in the testing phase. If you are still facing the issue, please try to reproduce the reported issue in the sample below and get back to us.

Sample: [i373449.zip](https://github.com/syncfusion/flutter-widgets/files/8389909/i373449.zip)


Regards,
Yuvaraj.
