### ISSUE TITLE
Cupertino Theme Problems

### ISSUE THREAD

**Issue by imariman** [syncfusion/flutter-widgets#652]
Hello Syncfusion team, I have a problem with my Cupertino app uses syncfusion widgets.

Problem: Since Syncfusion uses "Theme.of(context)", the CupertinoApp does not work properly on dark mode.

What Happens?: When I switch to dark mode on my Cupertino (iOS, macOS) app; the widgets like Calendar, Datagrid, etc. all remain black.

Possible Solution: I think somehow we should pass a bool parameter like "useCupertinoTheme" for Cupertino apps. If true, use CupertinoTheme.of(context), else Theme.of(context).

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @imariman,

Greetings from Syncfusion. We are analyzing the query and we need time for this. We will update the status in business day on 1st April 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @imariman,

Currently, we don't provide theming support for Cupertino widgets. However, your scenario can be achieved using any of the solutions below.

**Solution - 1**

At present, we have progressed theme data based on the Theme. of(context). But, In the Cupertino dark theme, you should wrap the DataGrid inside the SfDataGridTheme. In the data property, set SfDataGridThemeData with the required color values to show the DataGrid elements based on Cupertino app theme. We have prepared the sample for that. Please check the following sample and code snippet.

```dart
@override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        child: SfDataGridTheme(
      data: SfDataGridThemeData(
          gridLineColor: Colors.grey.withOpacity(0.50),
          rowHoverColor: Colors.white.withOpacity(0.20),
          selectionColor: Colors.grey.withOpacity(0.30),
          headerHoverColor: Colors.white.withOpacity(0.20),
          sortIconColor: Colors.white.withOpacity(0.80),
          currentCellStyle: DataGridCurrentCellStyle(
              borderColor: Colors.grey.withOpacity(0.50), borderWidth: 1)),
      child: SfDataGrid(
        source: _employeeDataSource,
        columnWidthMode: ColumnWidthMode.fill,
        columns: <GridColumn>[
          GridColumn(
              columnName: 'id',
              label: Container(
                  padding: const EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: Text('ID', style: textStyle))),
          GridColumn(
              columnName: 'name',
              label: Container(
                  padding: const EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: Text('Name', style: textStyle))),
          GridColumn(
              columnName: 'designation',
              label: Container(
                  padding: const EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: Text('Designation', style: textStyle))),
          GridColumn(
              columnName: 'salary',
              label: Container(
                  padding: const EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: Text('Salary', style: textStyle)))
        ],
      ),
    ));
  }
 
  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
          alignment: Alignment.center,
          child: Text(
            dataGridCell.value.toString(),
            style: TextStyle(
                fontFamily: 'Roboto',
                fontWeight: FontWeight.w400,
                fontSize: 14,
                color: Colors.white.withOpacity(0.87)),
          ));
    }).toList());
  }
```
Sample Link: [https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1920415671](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fdownloads%2Fsupport%2Fdirecttrac%2Fgeneral%2Fze%2Fsample-1920415671&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7Cf3c6e4a9b19a4f34652608da13c27369%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637844023129720635%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aHS42bDiLNp6pwd9RI7pNR%2F%2BrhZse6paluoqh2CLJj8%3D&reserved=0)

Solution - 2

You can also achieve it by using the Theme widget. You can wrap the DataGrid as a child of Theme widget and then set the ThemeData.briteness as CupertinoTheme.of(context).brightness in the data property. Please check the following code snippet.

```dart
@override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        child: Theme(
          data: ThemeData(
              brightness:
                  CupertinoTheme.of(context).brightness ?? Brightness.light),
          child: SfDataGrid(
            source: _employeeDataSource,
            columnWidthMode: ColumnWidthMode.fill,
            columns: getColumns,
          ),
        ));
  }
```

Hope this helps.

Thanks,
Yuvaraj.

**Comment by imariman** [comment]
Hi Yuvaraj,

Thank you very much for the detailed explanation. I preferred the second solution, and it worked perfectly fine. Thanks for the help and for your time!

Regards,
Metehan.
