### ISSUE TITLE
[Future Request]: SfMaps padding for MapZoomPanBehavior latlngBounds

### ISSUE THREAD

**Issue by xyzbilal** [syncfusion/flutter-widgets#653]
Hi , 
thanks for your great efforts. I just wonder if it is possible to add padding to latLngBounds so that layers fits to screen according to needs. giving bounds programatically occupies all  height and widths given for maps and it not looks nice as expected. Can you please guide me to achive my goals. thanks.  

![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-03-31 at 11 34 24](https://user-images.githubusercontent.com/18241412/161014761-1343aad1-1885-42ed-8fca-193f1e7ba705.png)

**Comment by PraveenGopalsamy** [comment]
Hi xyzbilal, 

Currently, we don't have any direct option for this requirement. You can achieve this by giving the [initialLatLngBounds ](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapLayer/initialLatLngBounds.html)with considering the padding based on the zoomLevel.

Please let us know if you need any further assistance in this.

Regards,
Praveen G.
