### ISSUE TITLE
pdf viewer 1 page padding

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [syncfusion/flutter-widgets#658]
how can I remove the padding from top? 

<img width="326" alt="Screen Shot 2022-04-03 at 19 30 24" src="https://user-images.githubusercontent.com/49102327/161438058-f0854396-aab8-416b-b155-4ecbc8cc2d78.png">

**Comment by deepika134** [comment]
Hi Shahmirzali,

In a single-page layout, we have aligned the PDF pages in the center of the SfPdfViewer widget. You can use the [SizedBox](https://api.flutter.dev/flutter/widgets/SizedBox-class.html) widget to fill the PDF pages according to the height of the device. The following code example explains the same.

```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: const Text('Syncfusion Flutter PDF Viewer'),
    ),
    body: SizedBox(
   /// The height depends on the mobile width with the proper aspect ratio.
      height: 565,
      child: SfPdfViewer.asset(
        'assets/gis_succinctly.pdf',
        pageLayoutMode: PdfPageLayoutMode.single,
      ),
    ),
  );
}
```
Regards,
Deepika Ravi
