### ISSUE TITLE
syncfusion_flutter_datagrid -> Row selections disappears after the rebuilding

### ISSUE THREAD

**Issue by berkanaslan** [syncfusion/flutter-widgets#659]
Hi,
I'm working on syncfusion_flutter_datagrid: ^20.1.47 and Flutter 2.10.4.

In my scenario multiple selection is allowed and I execute these selections with some rules. (See: onSelectionChanging)
However, the selected rows disappear instantly when the widget is rebuilt.
I tried assigning selectedRows to the DataGridController on the didUptadeWidget instant, but to no avail.

Video: https://screenrec.com/share/UwsjJLnBSP

Code:

**SfDataGrid:**
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:tpi_ri_mfg_mobile/core/ui/theme/theme.dart';

class ExtendedDataTable extends StatelessWidget {
  final DataGridSource source;
  final List<GridColumn> columns;
  final DataGridController? dataGridController;
  final ScrollController? scrollController;
  final ColumnWidthMode? columnWidthMode;
  final void Function(DataGridCellTapDetails details)? onCellTap;
  final bool Function(List<DataGridRow> addedRows, List<DataGridRow> removedRows)? onSelectionChanging;
  final void Function(List<DataGridRow> addedRows, List<DataGridRow> removedRows)? onSelectionChanged;

  const ExtendedDataTable({
    Key? key,
    required this.columns,
    required this.source,
    this.dataGridController,
    this.scrollController,
    this.columnWidthMode = ColumnWidthMode.fill,
    this.onSelectionChanging,
    this.onSelectionChanged,
    this.onCellTap,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return buildSfDataGrid(context);
  }

  SfDataGridTheme buildSfDataGrid(BuildContext context) {
    return SfDataGridTheme(
      data: SfDataGridThemeData(frozenPaneElevation: 0, selectionColor: AppColor.TPI_BLUE.withOpacity(0.35)),
      child: SfDataGrid(
        controller: dataGridController,
        verticalScrollController: scrollController,
        columnWidthMode: columnWidthMode ?? ColumnWidthMode.fill,
        source: source,
        columns: columns,
        frozenColumnsCount: 2,
        isScrollbarAlwaysShown: true,
        showCheckboxColumn: true,
        checkboxColumnSettings: const DataGridCheckboxColumnSettings(showCheckboxOnHeader: false),
        selectionMode: SelectionMode.multiple,
        onSelectionChanging: onSelectionChanging,
        onSelectionChanged: onSelectionChanged,
        onCellTap: onCellTap,
      ),
    );
  }
}
```

**Using:** 
```
  AppScaffold buildBody() {
    return AppScaffold(
      body: Column(
        children: [
          TextButton(
              onPressed: () {
                setState(() {});
              },
              child: Text("setState")),
          Expanded(
            child: ExtendedDataTable(
              dataGridController: dataGridController,
              columns: tableColumns,
              source: JobDataTableSource(jobData: jobs),
              onCellTap: (DataGridCellTapDetails details) => selectedIndex = (details.rowColumnIndex.rowIndex - 1),
              onSelectionChanging: onSelectionChanging,
            ),
          ),
        ],
      ),
    );
  }

  bool onSelectionChanging(List<DataGridRow> addedRows, List<DataGridRow> removedRows) {
    AppSnackBar.dismissSnackBar();

    if (selectedJobs.isEmpty) {
      selectedJobs.add(jobs[selectedIndex!]);
      return true;
    }

    if (addedRows.isEmpty && removedRows.isNotEmpty) {
      selectedJobs.remove(jobs[selectedIndex!]);
      return true;
    }

    final selectedJobsGroupIds = selectedJobs.map((job) => job.groupId);

    if (selectedJobsGroupIds.contains(jobs[selectedIndex!].groupId)) {
      selectedJobs.add(jobs[selectedIndex!]);
      return true;
    }

    AppSnackBar.showSnackBar(message: "You can only select those in the same groups!", type: SnackBarType.ERROR);
    return false;
  }
```

**Controller initialization:**
```
  late final JobRepository jobRepository;

  final List<Job> jobs = [];
  final List<Job> selectedJobs = [];
  int? selectedIndex;

  @override
  RefreshController indicatorController = RefreshController(initialRefresh: true);
  DataGridController dataGridController = DataGridController();

  @override
  void initState() {
    super.initState();
    jobRepository = context.read<JobRepository>();
  }
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @berkanaslan,

Greetings from Syncfusion.

Based on the provided sample, you called the **JobDataTableSource** class constructor directly from the DataGrid source property. DataGridSource must be long-lived object. DataGrid will refresh the selected rows on **setState** method calling if the DataGridSource is changed. To overcome this, you need to create an instance for the JobDataTableSource class in the initState method to maintain the source when reloading, then assign that instance to DataGrid instead of calling the class constructor directly from the DataGrid source property. Please check the following code snippet.

Code Snippet:

```dart
  late JobDataTableSource _jobDataTableSource;
  List<Employee> _jobs = <Employee>[];

  @override
  void initState() {
    super.initState();
    _jobs = getJobData();
    _jobDataTableSource = JobDataTableSource(_jobs);
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        TextButton(
          onPressed: () {
            setState(() {});
          },
          child: const Text('Set State'),
        ),
        Expanded(
          child: SfDataGrid(
            source: _jobDataTableSource,
            frozenColumnsCount: 2,
            isScrollbarAlwaysShown: true,
            showCheckboxColumn: true,
            onSelectionChanging: onSelectionChanging,
            checkboxColumnSettings: const DataGridCheckboxColumnSettings(
                showCheckboxOnHeader: false),
            selectionMode: SelectionMode.multiple,
            onCellTap: (details) {
              selectedIndex = details.rowColumnIndex.rowIndex - 1;
            },
            controller: dataGridController,
            columnWidthMode: ColumnWidthMode.fill,
            columns: getColumns,
          ),
        ),
      ],
    );
  }

```

We hope this helps. Please let us know if you need any further assistance. We will be glad to assist you.

Regards,
Tamilarasan

**Comment by berkanaslan** [comment]
Thank you for your help. I was assume that checkbox state information was on the controller not the DataGridSource. My fault. Thanks for your patience.

**Comment by berkanaslan** [comment]
Hello @Tamilarasan-Paranthaman 

I have another similar issue. I don't know why this is happening.

When wrapper widget of data table rebuilt (or after the keyboard appears), data table scroll position shifts. Although, has scroll controller (vertical, horizontal or both).  I used syncfusion_flutter_datagrid such as quoted message in the below with same version:

Video link: https://i.imgur.com/2KjdpDP.mp4

> Hi, I'm working on syncfusion_flutter_datagrid: ^20.1.47 and Flutter 2.10.4.
> 
> In my scenario multiple selection is allowed and I execute these selections with some rules. (See: onSelectionChanging) However, the selected rows disappear instantly when the widget is rebuilt. I tried assigning selectedRows to the DataGridController on the didUptadeWidget instant, but to no avail.
> 
> Video: https://screenrec.com/share/UwsjJLnBSP
> 
> Code:
> 
> **SfDataGrid:**
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:syncfusion_flutter_core/theme.dart';
> import 'package:syncfusion_flutter_datagrid/datagrid.dart';
> import 'package:tpi_ri_mfg_mobile/core/ui/theme/theme.dart';
> 
> class ExtendedDataTable extends StatelessWidget {
>   final DataGridSource source;
>   final List<GridColumn> columns;
>   final DataGridController? dataGridController;
>   final ScrollController? scrollController;
>   final ColumnWidthMode? columnWidthMode;
>   final void Function(DataGridCellTapDetails details)? onCellTap;
>   final bool Function(List<DataGridRow> addedRows, List<DataGridRow> removedRows)? onSelectionChanging;
>   final void Function(List<DataGridRow> addedRows, List<DataGridRow> removedRows)? onSelectionChanged;
> 
>   const ExtendedDataTable({
>     Key? key,
>     required this.columns,
>     required this.source,
>     this.dataGridController,
>     this.scrollController,
>     this.columnWidthMode = ColumnWidthMode.fill,
>     this.onSelectionChanging,
>     this.onSelectionChanged,
>     this.onCellTap,
>   }) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return buildSfDataGrid(context);
>   }
> 
>   SfDataGridTheme buildSfDataGrid(BuildContext context) {
>     return SfDataGridTheme(
>       data: SfDataGridThemeData(frozenPaneElevation: 0, selectionColor: AppColor.TPI_BLUE.withOpacity(0.35)),
>       child: SfDataGrid(
>         controller: dataGridController,
>         verticalScrollController: scrollController,
>         columnWidthMode: columnWidthMode ?? ColumnWidthMode.fill,
>         source: source,
>         columns: columns,
>         frozenColumnsCount: 2,
>         isScrollbarAlwaysShown: true,
>         showCheckboxColumn: true,
>         checkboxColumnSettings: const DataGridCheckboxColumnSettings(showCheckboxOnHeader: false),
>         selectionMode: SelectionMode.multiple,
>         onSelectionChanging: onSelectionChanging,
>         onSelectionChanged: onSelectionChanged,
>         onCellTap: onCellTap,
>       ),
>     );
>   }
> }
> ```
> 
> **Using:**
> 
> ```
>   AppScaffold buildBody() {
>     return AppScaffold(
>       body: Column(
>         children: [
>           TextButton(
>               onPressed: () {
>                 setState(() {});
>               },
>               child: Text("setState")),
>           Expanded(
>             child: ExtendedDataTable(
>               dataGridController: dataGridController,
>               columns: tableColumns,
>               source: JobDataTableSource(jobData: jobs),
>               onCellTap: (DataGridCellTapDetails details) => selectedIndex = (details.rowColumnIndex.rowIndex - 1),
>               onSelectionChanging: onSelectionChanging,
>             ),
>           ),
>         ],
>       ),
>     );
>   }
> 
>   bool onSelectionChanging(List<DataGridRow> addedRows, List<DataGridRow> removedRows) {
>     AppSnackBar.dismissSnackBar();
> 
>     if (selectedJobs.isEmpty) {
>       selectedJobs.add(jobs[selectedIndex!]);
>       return true;
>     }
> 
>     if (addedRows.isEmpty && removedRows.isNotEmpty) {
>       selectedJobs.remove(jobs[selectedIndex!]);
>       return true;
>     }
> 
>     final selectedJobsGroupIds = selectedJobs.map((job) => job.groupId);
> 
>     if (selectedJobsGroupIds.contains(jobs[selectedIndex!].groupId)) {
>       selectedJobs.add(jobs[selectedIndex!]);
>       return true;
>     }
> 
>     AppSnackBar.showSnackBar(message: "You can only select those in the same groups!", type: SnackBarType.ERROR);
>     return false;
>   }
> ```
> 
> **Controller initialization:**
> 
> ```
>   late final JobRepository jobRepository;
> 
>   final List<Job> jobs = [];
>   final List<Job> selectedJobs = [];
>   int? selectedIndex;
> 
>   @override
>   RefreshController indicatorController = RefreshController(initialRefresh: true);
>   DataGridController dataGridController = DataGridController();
> 
>   @override
>   void initState() {
>     super.initState();
>     jobRepository = context.read<JobRepository>();
>   }
> ```

**Comment by berkanaslan** [comment]
Hi again @Tamilarasan-Paranthaman 

First of all, thank you for taking the time to reply.

I identified the problem by comparing the project you sent as an sample with my own project. I found out that the problem is caused by [this package](https://pub.dev/packages/pull_to_refresh) which is the wrapper for the relevant screen.

I'm sorry for opening an issue without further research.
