### ISSUE TITLE
Please add filter Option in Header 

### ISSUE THREAD

**Issue by waqaryounusjatt788** [syncfusion/flutter-widgets#66]
I have seen your WPF library your team have added filter column option in WPF but I have not find Filter option in  Flutter library and documentation as well, please add filter option in flutter as well

**Comment by BalasubramaniSundaram** [comment]
Hi @waqaryounusjatt788 , 

We are always trying to make our products better and feature requests like yours are a key part of our product growth. We have already created this as a feature request “**Support to filter the columns through UI**”. 

You can now track the status of this feature request here,

https://www.syncfusion.com/feedback/16318/support-to-filter-the-columns-through-ui

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. 

If you have any more specifications/suggestions for the feature request, you can add it as a comment in the portal.

Regards,
Balasubramani Sundaram.

**Comment by waqaryounusjatt788** [comment]
Please send me the code example how we use these filters

**Comment by NeelakandanKannan** [comment]
Hi @waqaryounusjatt788 ,

We didn't provide the support yet. We will let you know once this feature is implemented.
