### ISSUE TITLE
[syncfusion_flutter_pdfviewer] pages are not being rendered in high resolution on small screen.

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#662]
syncfusion_flutter_pdfviewer: ^20.1.47-beta

<details><summary>Flutter Doctor</summary>
<p>

```
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1586], locale en-IN)
    • Flutter version 2.10.1 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (8 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at C:\Users\sagark\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.32126.317
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.66.0)
    • VS Code at C:\Users\sagark\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1586]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 99.0.4844.84

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</p>
</details>

1. If I open pdf in mobile device which is having screen size of 6.4 inches with 1440 x 2960 pixels resolution, then the pages are not being rendered in higher resolution. But if I run the same app on tablet device having 12.4 inches screen with 1752 x 2800 pixels resolution then pages are being rendered very clear and sharp.
 
2. In both of them still performance is not so excellent. It tooks considerably higher time to draw/render the page.

Regards
Sagar

**Comment by deepika134** [comment]
Hi @sagarkardani ,

**Regarding higher time to draw/render the page**

We have improved the image rendering in SfPdfViewer. This implementation will be included in our upcoming weekly package release which will be estimated to be available on April 12, 2022.

**Regarding pages are not rendered in device**

We tried to reproduce the issue, but the PDF pages are loaded properly. For your reference, we have prepared the screen record of the out and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/screenrecord-1158554549.zip 
Kindly share the issue reproducing document and output screen record of the issue, it will be helpful for us to provide a prompt solution at the earliest.
Note: Testing Device- Samsung Galaxy M31s

Regards,
Deepika Ravi

**Comment by sagarkardani** [comment]
Hi @deepika134,

I just did a fresh build and I am also seeing the same results as you provided in the screen record. May be I have done something wrong in previous builds or I made mistake in my observation. I am waiting for upcoming weekly package release and have it a try. Thanks for support.

**Comment by deepika134** [comment]
Hi  @sagarkardani ,

**Regarding Active viewport rendering:**

At present we do not have support for “Active viewport rendering” in SfPdfViewer. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/31524/active-viewport-rendering 

**Regarding the resolution of page not updated when changing the orientation:**

We are analyzing on the reported query and will update the further details on 19th April 2022.

Regards,
Deepika Ravi.

**Comment by deepika134** [comment]
Hi @sagarkardani ,

We have confirmed that the reported issue “PDF page loses clarity while changing the orientation of the device” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on May 3, 2022. The status of the issue can be tracked by the following link,
https://www.syncfusion.com/feedback/34344/pdf-page-loses-clarity-while-changing-the-orientation-of-the-device 

Regards,
Deepika Ravi
