### ISSUE TITLE
[syncfusion_data_grid] Customising header borders

### ISSUE THREAD

**Issue by edwardaux** [syncfusion/flutter-widgets#665]
Hi there, I'm wrestling with how to reproduce a particular heading style.

![image](https://user-images.githubusercontent.com/1574429/162081881-9cef5924-4ed5-4a85-b474-9a7c90076722.png)

As you can see from the above, I want both the top/bottom horizontal lines as well as the vertical lines (except on the very ends). As I understand, the built-in `headerGridLinesVisibility` capability won't let me do this - if I set it to use `both`, then I get this result:

![image](https://user-images.githubusercontent.com/1574429/162082111-3eae6fa8-33cc-4d5b-ad0c-57f618500b1a.png)

So, what I've been doing is setting `headerGridLinesVisibility=none` and then just drawing the border myself... which works fine, EXCEPT for the sort icon. If you look in the first screenshot, you can see that the border doesn't extend to include the sort icon which looks really weird.

My question is two-fold:
* Why does using `headerGridLinesVisibility=both` not draw the left and top borders? I've seen [another issue](https://github.com/syncfusion/flutter-widgets/issues/585#issuecomment-1041875199) where the reply confirmed that that is the expected behaviour, but I must admit I don't understand why that is. The suggested workaround in that issue is to use a container with a border - which is what I'm doing (see second question).
* Is there a way to achieve what I need? If I could get `headerGridLinesVisibility=horizontal` to draw both lines, then I could draw the vertical ones myself where they are needed.

Any help would be appreciated. Thanks.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @edwardaux,

Greetings from Syncfusion.

By default, we have drawn only the bottom and right outer borders to avoid the thickness of the border while drawing four side of borders for adjacent cells and also considering the performance while drawing four borders for single cell. So, the top and left borders are not shown. That’s the behavior of the DataGrid. As per your requirement, you can achieve it by following steps.

**Step 1**: Set the **headerGridLinesVisibility** and **gridLinesVisibility** to **GridLinesVisibility.horizontal.**

**Step 2**. In the GridColumn container, you can set the left border for the cell instead of setting the right border. It would solve the issue with the sort icon which you're facing in the first screenshot. Also, we suspect that you are setting the top and bottom border for individual header cells. We are showing the sort icon and header cell in a row widget in the cell container. So, if you load any widget in label property, it will only take the area other than sort icon. That's why in the first screenshot DataGrid shows like that. Please check the following code snippet,

Code Snippet:
```dart
List<GridColumn> get getColumns {
    return [
      GridColumn(
          columnName: 'id',
          label: Container(
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text(
                'ID',
                overflow: TextOverflow.ellipsis,
              ))),
      GridColumn(
          columnName: 'name',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      left: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text('Name', overflow: TextOverflow.ellipsis))),
      GridColumn(
          columnName: 'designation',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      left: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child:
                  const Text('Designation', overflow: TextOverflow.ellipsis))),
      GridColumn(
          columnName: 'salary',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      left: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text('Salary', overflow: TextOverflow.ellipsis)))
    ];
  }

```

**Step 3**: In the **DataGridSource.buildRow** method, set the left border for the grid cells in the container widget except for the id column. Here, you can set the grid cell borders where you need them. Please check the following code snippet.

Code Snippet:
```dart
@override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
          decoration: BoxDecoration(
              border: Border(
            left: dataGridCell.columnName == 'id'
                ? BorderSide.none
                : BorderSide(width: 1.0, color: Colors.grey.withOpacity(0.45)),
          )),
          alignment: Alignment.center,
          padding: const EdgeInsets.symmetric(horizontal: 16.0),
          child: Text(
            dataGridCell.value.toString(),
            overflow: TextOverflow.ellipsis,
          ));
    }).toList());
  }

```

**Step 4**: For the header cell top outer border, you can set it by wrapping the DataGrid inside a Container widget and setting the top border for the Container. Please check the following sample and code snippet.

Code Snippet:
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: Card(
        margin: const EdgeInsets.all(30),
        child: Container(
          decoration: BoxDecoration(
              border: Border(
                  top: BorderSide(
                      width: 1.0, color: Colors.grey.withOpacity(0.45)))),
          child: SfDataGrid(
            source: _employeeDataSource,
            allowSorting: true,
            gridLinesVisibility: GridLinesVisibility.horizontal,
            headerGridLinesVisibility: GridLinesVisibility.horizontal,
            columnWidthMode: ColumnWidthMode.fill,
            columns: getColumns,
          ),
        ),
      ),
    );
  }

```

We have prepared the sample for that. Please check the following sample.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1777677477 

We hope this helps. Please let us know if you need any further assistance. We will be glad to assist you.

Regards,
Tamilarasan

**Comment by edwardaux** [comment]
Tamilarasan, thank you so much for the detailed reply. The support that SyncFusion offers here for their widgets is amazing. I'll look into using the sample code you provided today. Thanks a lot.

I wanted to offer some feedback on your initial comments about only drawing the bottom and right borders. I totally understand that that is a technical efficiency to avoid the double-drawing you mention. However, I feel like that is an internal implementation detail that is leaking out into your public API.

The public API offers a `headerGridLinesVisibility` parameter that takes a value called `GridLinesVisibility.horizontal` (and similar for vertical)... I don't think you would find any developer who would assume that this parameter only means draw borders on the bottom/right. 

Might I suggest that you consider revisiting this implementation detail? It would make your API act much more intuitively (in my opinion). Now, I realise that change the behaviour might be a breaking change (perhaps there are apps out there that rely in this behaviour), but if you didn't want to change the underlying behaviour you could perhaps deprecate `horizontal`/`vertical` and add two new enum cases called something like `horizontalBoth` (although this is a bit ugly too). Or what would be better again would be to add a new pattern totally. Something like (totally untested):

```
class HeaderGridLinesPolicy {
  final Border? leadingVerticalBorder;
  final Border? intermediateVerticalBorder;
  final Border? trailingVerticalBorder;

  final Border? topHorizontalBorder;
  final Border? bottomHorizontalBorder;
}
```
And then consumers could create their own instance of this class and pass it into the datagrid (or the theme). This way, consumers can explicitly control exactly what borders are/aren't drawn. And then obviously, `SfDataGrid` would have the smarts to draw the appropriate borders based on which ones are set.

The existing behaviour could easily be simulated internally by using something like:
```
HeaderGridLinesPolicy(
 leadingVerticalBorder: null,
 intermediateVerticalBorder: Border(...),
 trailingVerticalBorder: Border(...),
 topHorizontalBorder: null,
 bottomHorizontalBorder: Border(...),
)
```
Anyway, just some food for thought...

**Comment by edwardaux** [comment]
Howdy Tamilarasan, now that I've had a chance to look at your suggestion... this is pretty much exactly the solution I ended up going with myself 🙌  The one big shortcoming of both our workarounds, though, is that it assumes that there are a non-zero number of rows... if there are no rows, then the header doesn't have anything to draw the bottom border 😢 

I haven't found a way to work around that yet

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @edwardaux,

****Regarding Query**: https://github.com/syncfusion/flutter-widgets/issues/665#issuecomment-1092302595 

Thank you for your valuable suggestion for our DataGrid widget. Also, we will consider your suggestion as a feature request. We are planning to provide that support by drawing the header and grid cell leading border and header cell top border. As like the details in the below table,


**Current Visibility Appearance:**

![image](https://user-images.githubusercontent.com/93904422/162440850-895f2ce6-62f1-412b-8dd4-5db699dde969.png)


**Planned Visibility Appearance:**

![image](https://user-images.githubusercontent.com/93904422/162440942-e6c59983-c917-4728-a056-e21f401169a2.png)

Can you please check and confirm with us whether this meets your requirements? After that, we will proceed with further steps.

**Regarding Query**: https://github.com/syncfusion/flutter-widgets/issues/665#issuecomment-1092511498 

We suspect that you are setting **headerGridLinesVisibility** to **GridLinesVisibility.none**. As we said in the previous response, step 1: set the **headerGridLinesVisibility** to **GridLinesVisibility.horizontal** to draw the header cell bottom border. Please check the following screenshot.

![image](https://user-images.githubusercontent.com/93904422/162441024-b4c5030d-d8f6-44d7-80e8-2aaca5b2898a.png)

If we misunderstood anything, please let us know more clear details about your query. It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by edwardaux** [comment]
> We suspect that you are setting headerGridLinesVisibility to GridLinesVisibility.none. 
Oh dear... I'm an idiot. That is indeed what I'm doing. My apologies. Once I did that, I'm able to get exactly what I'm looking for. Thanks.

> Planned Visibility Appearance
Thanks for capturing your proposed changes. To be honest, I think that the proposed options are confusing for consumers of your API. For example, if I specify `horizontal` in your proposal, then it is going to draw top/bottom (which is good), but it is also going to draw one vertical bar (that's odd)?! That seems very counterintuitive (even if it might be documented)... why would specifying a horizontal option end up drawing a vertical bar? (I now know the answer is due to how it is implemented internally... but that's not really how I think the public API should work).

Ignoring the counterintuitive behaviour I mention above, I think the general problem is that having a single enum is not sufficient to represent the various options that users might want. For example, I can imagine someone wanting a header with any of the following:

* Only the top border
* Only the bottom border
* Only the left border
* Only the right border
* Both top and bottom
* Borders around all cells
* Borders just around the whole header row (no internal vertical borders)
* Top/Left/Right border (no bottom, no internal borders)
* Just internal vertical borders (no left/right)
* Certainly others...

There is just no way simple enums can represent that... which is why I suggested having a data structure that allows them the flexibility to specify exactly what they want.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @edwardaux,

Thank you for the update.

We have considered your request “customize the individual cell borders” as a feature. This feature will be implemented in any of our upcoming release. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,   

Feedback Link: https://www.syncfusion.com/feedback/34101/support-to-customize-the-individual-cell-borders 

Also, as we said earlier, we will provide the support to show the “top and left outer DataGrid borders”. This feature will be implemented in our 2022 Volume 3 release which is expected to be rolled out at the end of September 2022. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,   

Feedback Link: https://www.syncfusion.com/feedback/34100/support-to-draw-the-top-and-left-outer-border 

We appreciate your patience until then. 

Regards,
Tamilarasan
