### ISSUE TITLE
How to show column chart like this?

### ISSUE THREAD

**Issue by wrjcs** [syncfusion/flutter-widgets#670]
Hello,
How to show column chart like this?
![flutter-column-charts](https://user-images.githubusercontent.com/7202194/162580829-1d3732a0-b396-4f8d-8e82-9b1d564f122e.png)

Thanks.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @wrjcs,

We have created a sample with the column series based on the provided screenshot and attached the sample below for your reference. If you have any further queries, please get back to us.

Sample: [i374842.zip](https://github.com/syncfusion/flutter-widgets/files/8463953/i374842.zip)

Regards,
Yuvaraj.

**Comment by wrjcs** [comment]
Thank you very much
