### ISSUE TITLE
TextField focusNode not Working on buildEditWidget

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#672]
i am creating below textfield widget on buildeditwidget. on focusnode leave focus i want to call api and get value if value not exist i navigate to another window to find value.untill all the process user cannot navigate to another cell. if cell have some value.  its not listing on !_focusNode.hasFocus please give me a solution to do this.

import 'package:flutter/material.dart';
import '../screens/search_list.dart';
import '../style/style.dart';

class textfield_gridview extends StatefulWidget {
  const textfield_gridview({Key? key,required this.textEditingController}) : super(key: key);
final TextEditingController textEditingController;
  @override
  State<textfield_gridview> createState() => _textfield_gridviewState();
}

class _textfield_gridviewState extends State<textfield_gridview> {
  late FocusNode _focusNode;
  bool changed = false;

  @override
  void initState() {
    _focusNode = new FocusNode();
    // TODO: implement initState
    super.initState();
  }
  @override
  void dispose() {
    _focusNode.dispose();
    // TODO: implement dispose
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    _focusNode.addListener(() async{
      if (!_focusNode.hasFocus) {
        if (changed == true) {
        var result =   Navigator.push(context, MaterialPageRoute(builder: (context) => search_list()));
          if (result == null) {
            _focusNode.requestFocus();
            changed = true;
          }
          else
            {

            }
        }
      }});

    return TextField(
      focusNode: _focusNode,
      autofocus: true,
      controller: widget.textEditingController,
      style:standardstyle,
      onChanged: (value){
        changed = true;
      },
    );
  }
}

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Currently we are analyzing your requirement. We will validate and update you with the details in two business days. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
waiting for this

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

As we said in this update https://github.com/syncfusion/flutter-widgets/issues/635#issuecomment-1072258053, your requirement can be achieved using the feature making the onSubmit method async. Meanwhile, we are checking your requirement to achieve it at the sample level. We will update you with the details tomorrow i.e., April 19, 2022.We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
how to change focus to nextcell. without press tabkey

**Comment by abdulrehmananwar** [comment]
i also want to add focus node  on textfield.

**Comment by abdulrehmananwar** [comment]
because canSubmitCell work only for grid. 
example.
i we have any widget outside from grid like button. we can use it . butt in my case i want if canSubmitCell  false not one widget should be call

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Thanks for your patience.

We have checked all the possibilities to achieve your requirement with the workaround. We couldn’t achieve it at the sample level itself. Because the DataGrid progressed, the focus was based on the cell focus. If you tap any other cell, the focus immediately goes to the DataGrid. So, you can’t wait to proceed with the fetch data here. As we said in the previous update, your requirement can be achieved only by using the feature that makes the onSubmit method async. We will let you know when this feature is implemented. We appreciate your patience until then.

**Regarding Query:** https://github.com/syncfusion/flutter-widgets/issues/672#issuecomment-1103450035 
 
Without tap key, you can move the cell focus programmatically by using moveCurrentCellTo method. Please check the following code snippet for programmatic way to move currentcell.

```dart
  SizedBox(
         height: 50,
         width: 100,
         child: ElevatedButton(
                    onPressed: () {
                      _dataGridController.moveCurrentCellTo(RowColumnIndex(1, 2));
                    },
                    child: const Text('Move Focus')),
         ),


```
We hope this helps. Please let us know if need any further assistance.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
if canSubmitCell is false.  widgets outside from grid should be disable butt they are usable.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Currently, DataGrid does not have support for maintaining the focus on the DataGrid. We have considered your request as a feature. This feature will be implemented in our 2022 Volume 3 release which is expected to be rolled out at the end of September 2022. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,   

Feedback Link: https://www.syncfusion.com/feedback/34346/support-to-not-allow-the-focus-to-another-widget-outside-datagrid-when 

Regards,
Tamilarasan
