### ISSUE TITLE
flutter syncfusion datagrid - nested datagrid

### ISSUE THREAD

**Issue by SathiyaGirinathan** [syncfusion/flutter-widgets#673]
Hi,
![image](https://user-images.githubusercontent.com/65302254/163123801-440a58d9-a6f6-492a-9411-d9624e2ba154.png)
Found this image here https://github.com/flutter/flutter/issues/68695.
I'm using SfDatagrid. How to include the nested data grid in flutter like this?

Thanks
Sathiya

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @SathiyaGirinathan,

Greetings from Syncfusion.

Currently, DataGrid does not have support for grouping the rows i.e., nested grid. We have already considered your request as a feature. This feature will be implemented in our any of our upcoming release. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,

Feedback Link: [https://www.syncfusion.com/feedback/22294/support-to-group-the-rows](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F22294%2Fsupport-to-group-the-rows&data=04%7C01%7Ctamilarasan.paranthaman%40syncfusion.com%7C1deeb0b946a44dad42e308da1d47497a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637854489250374204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K9z83aKLBhVBL2YlH9slt9whj7Tcm3GffEL7PAA6Egw%3D&reserved=0) 

Regards,
Tamilarasan
