### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Get a page title or page text content

### ISSUE THREAD

**Issue by indmind** [syncfusion/flutter-widgets#675]
I'm trying to create a custom page bookmark and I want to store the current page number and it's title. Is there any way to get the page title or the text content?

![image](https://user-images.githubusercontent.com/29256127/163130182-080d0daa-6ed4-4ec8-bb5b-87ef153484e4.png)

It's going to be displayed like this
![image](https://user-images.githubusercontent.com/29256127/163130491-10cf928b-fd07-4307-9a32-674821468254.png)

But I want to show the page title and number, currently I'm doing it like this

```dart
return IconButton(
          icon: Icon(
            isBookmarked
                ? Icons.bookmark_rounded
                : Icons.bookmark_border_rounded,
            color: isBookmarked
                ? theme.colorScheme.error
                : theme.colorScheme.primary,
          ),
          onPressed: () {
            if (!isBookmarked) {
              bookmarkNotifier.addBookmark(
                _controller.pageNumber,
                'Page ${_controller.pageNumber}', // I want the page title or atleast the bookmark title where this page belongs to here
              );
            } else {
              bookmarkNotifier.removeBookmark(_controller.pageNumber);
            }
          },
        );
```

**Comment by deepika134** [comment]
Hi @indmind ,

Kindly refer to the following code snippet to get the title of the bookmark,

```
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: const Text('Syncfusion Flutter PDF Viewer'),
    ),
    body: SfPdfViewer.network(
      'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
      onDocumentLoaded: (PdfDocumentLoadedDetails details) {
        print(details.document.bookmarks[0].title);
      },
    ),
  );
}
```
Kindly refer to the following UG documentation link for more information,
https://help.syncfusion.com/flutter/pdf-viewer/bookmark-navigation#navigate-to-the-desired-bookmark-topic-programmatically 

Regards,
Deepika Ravi
