### ISSUE TITLE
syncfusion_flutter_pdfviewer Windows:  LINK : fatal error LNK1181: cannot open input file 'PDFium_IMPLIB-NOTFOUND.obj'

### ISSUE THREAD

**Issue by artnavsegda** [syncfusion/flutter-widgets#677]
Cannot build windows project with syncfusion_flutter_pdfviewer library, 'flutter build windows -v' fails with output:

...
[   +2 ms] PrepareForBuild:
[        ]   Creating directory "syncfusion_pdfviewer_windows_plugin.dir\Release\".
[   +1 ms]   Creating directory "C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\Release\".
[        ]   Creating directory "syncfusion_pdfviewer_windows_plugin.dir\Release\syncfusi.4C7378D5.tlog\".
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "syncfusion_pdfviewer_windows_plugin.dir\Release\syncfusi.4C7378D5.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +27 ms] CustomBuild:
[        ]   Building Custom Rule C:/charts/windows/flutter/ephemeral/.plugin_symlinks/syncfusion_pdfviewer_windows/windows/CMakeLists.txt
[  +26 ms] ClCompile:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\CL.exe /c /IC:\charts\windows\flutter\ephemeral
/IC:\charts\windows\flutter\ephemeral\cpp_client_wrapper\include
/IC:\charts\windows\flutter\ephemeral\.plugin_symlinks\syncfusion_pdfviewer_windows\windows\include\pdfium
/IC:\charts\windows\flutter\ephemeral\.plugin_symlinks\syncfusion_pdfviewer_windows\windows\include\pdfium\cpp /nologo /W4 /WX /diagnostics:column /O2 /Ob2 /D _WINDLL
/D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D NDEBUG /D _HAS_EXCEPTIONS=0 /D FLUTTER_PLUGIN_IMPL /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Release\"" /D
syncfusion_pdfviewer_windows_plugin_EXPORTS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17
/Fo"syncfusion_pdfviewer_windows_plugin.dir\Release\\" /Fd"syncfusion_pdfviewer_windows_plugin.dir\Release\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue
C:\charts\windows\flutter\ephemeral\.plugin_symlinks\syncfusion_pdfviewer_windows\windows\pdfviewer.cpp
C:\charts\windows\flutter\ephemeral\.plugin_symlinks\syncfusion_pdfviewer_windows\windows\syncfusion_pdfviewer_windows_plugin.cpp
[  +29 ms]   pdfviewer.cpp
[ +685 ms]   syncfusion_pdfviewer_windows_plugin.cpp
[ +921 ms]   Generating Code...
[ +322 ms] Link:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE
/OUT:"C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\Release\syncfusion_pdfviewer_windows_plugin.dll" /INCREMENTAL:NO /NOLOGO "PDFium_IMPLIB-NOTFOUND"
..\..\flutter\Release\flutter_wrapper_plugin.lib C:\charts\windows\flutter\ephemeral\flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib
ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
/PDB:"C:/charts/build/windows/plugins/syncfusion_pdfviewer_windows/Release/syncfusion_pdfviewer_windows_plugin.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT
/IMPLIB:"C:/charts/build/windows/plugins/syncfusion_pdfviewer_windows/Release/syncfusion_pdfviewer_windows_plugin.lib" /MACHINE:X64  /machine:x64 /DLL
syncfusion_pdfviewer_windows_plugin.dir\Release\pdfviewer.obj
[   +1 ms]   syncfusion_pdfviewer_windows_plugin.dir\Release\syncfusion_pdfviewer_windows_plugin.obj
[  +34 ms] LINK : fatal error LNK1181: cannot open input file 'PDFium_IMPLIB-NOTFOUND.obj'
[C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
[   +3 ms] Done Building Project "C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj" (default targets) --
FAILED.
[  +16 ms] Project "C:\charts\build\windows\runner\charts.vcxproj" (4) is building "C:\charts\build\windows\plugins\window_manager\window_manager_plugin.vcxproj" (9)
on node 1 (default targets).
[        ] PrepareForBuild:
[        ]   Creating directory "window_manager_plugin.dir\Release\".
[        ]   Creating directory "C:\charts\build\windows\plugins\window_manager\Release\".
[        ]   Creating directory "window_manager_plugin.dir\Release\window_m.3A2FDC02.tlog\".
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "window_manager_plugin.dir\Release\window_m.3A2FDC02.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +27 ms] CustomBuild:
[        ]   Building Custom Rule C:/charts/windows/flutter/ephemeral/.plugin_symlinks/window_manager/windows/CMakeLists.txt
[  +29 ms] ClCompile:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\CL.exe /c /IC:\charts\windows\flutter\ephemeral
/IC:\charts\windows\flutter\ephemeral\cpp_client_wrapper\include /nologo /W4 /WX /diagnostics:column /O2 /Ob2 /D _WINDLL /D _UNICODE /D UNICODE /D WIN32 /D _WINDOWS /D
NDEBUG /D _HAS_EXCEPTIONS=0 /D FLUTTER_PLUGIN_IMPL /D _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING /D UNICODE /D _UNICODE /D "CMAKE_INTDIR=\"Release\"" /D
window_manager_plugin_EXPORTS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"window_manager_plugin.dir\Release\\"
/Fd"window_manager_plugin.dir\Release\vc143.pdb" /external:W4 /Gd /TP /wd4100 /errorReport:queue
C:\charts\windows\flutter\ephemeral\.plugin_symlinks\window_manager\windows\window_manager.cpp
C:\charts\windows\flutter\ephemeral\.plugin_symlinks\window_manager\windows\window_manager_plugin.cpp
[  +28 ms]   window_manager.cpp
[+1129 ms]   window_manager_plugin.cpp
[+1215 ms]   Generating Code...
[ +806 ms] Link:
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE
/OUT:"C:\charts\build\windows\plugins\window_manager\Release\window_manager_plugin.dll" /INCREMENTAL:NO /NOLOGO ..\..\flutter\Release\flutter_wrapper_plugin.lib
C:\charts\windows\flutter\ephemeral\flutter_windows.dll.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib
advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed
/PDB:"C:/charts/build/windows/plugins/window_manager/Release/window_manager_plugin.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT
/IMPLIB:"C:/charts/build/windows/plugins/window_manager/Release/window_manager_plugin.lib" /MACHINE:X64  /machine:x64 /DLL
window_manager_plugin.dir\Release\window_manager.obj
[   +1 ms]   window_manager_plugin.dir\Release\window_manager_plugin.obj
[  +59 ms]      Creating library C:/charts/build/windows/plugins/window_manager/Release/window_manager_plugin.lib and object
C:/charts/build/windows/plugins/window_manager/Release/window_manager_plugin.exp
[  +68 ms]   window_manager_plugin.vcxproj -> C:\charts\build\windows\plugins\window_manager\Release\window_manager_plugin.dll
[   +5 ms] FinalizeBuildStatus:
[        ]   Deleting file "window_manager_plugin.dir\Release\window_m.3A2FDC02.tlog\unsuccessfulbuild".
[        ]   Touching "window_manager_plugin.dir\Release\window_m.3A2FDC02.tlog\window_manager_plugin.lastbuildstate".
[        ] Done Building Project "C:\charts\build\windows\plugins\window_manager\window_manager_plugin.vcxproj" (default targets).
[        ] Done Building Project "C:\charts\build\windows\runner\charts.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "C:\charts\build\windows\ALL_BUILD.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "C:\charts\build\windows\INSTALL.vcxproj" (default targets) -- FAILED.
[        ] Build FAILED.
[   +2 ms] "C:\charts\build\windows\INSTALL.vcxproj" (default target) (1) ->
[        ] "C:\charts\build\windows\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "C:\charts\build\windows\runner\charts.vcxproj" (default target) (4) ->
[        ] "C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj" (default target) (7) ->
[        ] (Link target) ->
[        ]   LINK : fatal error LNK1181: cannot open input file 'PDFium_IMPLIB-NOTFOUND.obj'
[C:\charts\build\windows\plugins\syncfusion_pdfviewer_windows\syncfusion_pdfviewer_windows_plugin.vcxproj]
[        ]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:01:03.83
[  +17 ms] Building Windows application... (completed in 66.7s)
[        ] "flutter windows" took 67,234ms.
[   +3 ms] Build process failed.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/windows/build_windows.dart:314:5)
           <asynchronous suspension>
           #2      buildWindows (package:flutter_tools/src/windows/build_windows.dart:80:5)
           <asynchronous suspension>
           #3      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:57:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

[  +39 ms] ensureAnalyticsSent: 37ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

'flutter doctor -v' output is: 
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on Microsoft Windows [Version 10.0.22000.613], locale en-US)
    • Flutter version 2.10.4 at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\Art Navsegda\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32407.343
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.66.2)
    • VS Code at C:\Users\Art Navsegda\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.38.1

[✓] Connected device (1 available)
    • Windows (desktop) • windows • windows-x64 • Microsoft Windows [Version 10.0.22000.613]

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by artnavsegda** [comment]
okay, I got it working

In case somebody will encounter the same problem the solution is:

flutter pub add pdfx

It will install missing library and everything will be built correctly.

**Comment by candrawardana** [comment]
needs to be added in documentation

**Comment by deepika134** [comment]
Hi  @artnavsegda ,

We are analyzing the reported query and will update the further details on 19th April 2022.

Regards,
Deepika Ravi

**Comment by dillibabu1802** [comment]
Hi @artnavsegda 

Due to improper shipment of dependent files, the reported issue occurred. The issue will be resolved in our upcoming weekly package release which is estimated to be available on 26 April 2022.

Regards,
Dilli babu.

**Comment by deepika134** [comment]
Hi artnavsegda,

we have included the fix for the reported issue in our latest weekly NuGet release, so kindly upgrade to the latest version v20.1.51-beta to get the issue resolved.
Package Link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.51-beta 

Regards,
Deepika Ravi
