### ISSUE TITLE
可否能添加一个立体带阴影的饼图

### ISSUE THREAD

**Issue by developerWn** [syncfusion/flutter-widgets#678]
<img width="496" alt="截屏2022-04-15 18 06 44" src="https://user-images.githubusercontent.com/17231306/163558446-f3005b9b-20a6-4fff-bfca-73e759afe788.png">
可否能添加一个立体带阴影的饼图。膜拜大佬，致敬！

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @developerWn,

Greetings from Syncfusion and thanks for the new feature request with us. However, we don't have any immediate plans for implementing the 3D charts, so we are closing this ticket for now.

Thanks,
Yuvaraj.
