### ISSUE TITLE
SfPdfViewer.network() doesn't display the PDF

### ISSUE THREAD

**Issue by kuntojirohan** [syncfusion/flutter-widgets#68]
The SfPdfViewer.network() doesn't display the Pdf and throws an error message, 
"Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)"

**Comment by aghanti7** [comment]
Same issue here on Android.

**Comment by dillibabun** [comment]
Hi @kuntojirohan  and @aghanti7 ,

Kindly share us more information about this issue. Please update the following to reproduce the issue from our side.
1. PDF Network URL link.
2. Syncfusion SfPdfViewer package version.
3. Flutter doctor log.

Regards,
Dilli babu.

**Comment by kuntojirohan** [comment]
Sorry, my bad, it worked. The issue was with the url being too long
