### ISSUE TITLE
Cartesian Chart auto range calculation

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#681]
I found this range calculation tends to include a big chunk of unnecessary range,
take the attached code for example,
range [0-8000] on Y-axis is unnecessary.
What's worse, oftentimes, the unnecessary range twists the scale of the chart's visible part.

![Screen Shot 2022-04-19 at 9 57 11 PM](https://user-images.githubusercontent.com/57275868/164154184-def22f96-5949-49c4-81f2-cbe9658c0151.png)
[how-to-create-flutter-financial-charts-like-candle-and-ohlc-in-10-minutes.zip](https://github.com/syncfusion/flutter-widgets/files/8518416/how-to-create-flutter-financial-charts-like-candle-and-ohlc-in-10-minutes.zip)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

We suggest you use the [rangePadding](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/rangePadding.html) property to avoid this unnecessary range in the y-axis. We have attached the code snippet and UG document below for your reference to achieve your requirement.

Code snippet:
```dart
primaryYAxis: NumericAxis(
       rangePadding: ChartRangePadding.round
  ),
```

UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#applying-padding-to-the-range 

Regards,
Yuvaraj.
