### ISSUE TITLE
MapTileLayer shows 4 same tile on screen

### ISSUE THREAD

**Issue by mehmettezcan** [syncfusion/flutter-widgets#682]
<img width="735" alt="Screen Shot 2022-04-20 at 10 08 24" src="https://user-images.githubusercontent.com/19556595/164170990-9532a85b-e912-4fe5-b208-c606295a8840.png">

`SfMaps(
  layers: [
    MapTileLayer(
      urlTemplate: 'https://tile.openstreetmap.org/15/16596/11261.png'
    ),
  ],
);`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @mehmettezcan,

We have analyzed and suggest using the link for the [urlTemplate](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapTileLayer/urlTemplate.html) property as per in the attached code snippet below and set the [focalLatLng](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapZoomPanBehavior/focalLatLng.html) property with the latitude and longitude value of your location then set the [zoomLevel](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapZoomPanBehavior/zoomLevel.html) value as per your requirement. We have also attached the UG documentation below for your reference.

Code snippet:
```dart
SfMaps(
  layers: [
    MapTileLayer(
      urlTemplate: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
      zoomPanBehavior: MapZoomPanBehavior(
        focalLatLng: MapLatLng(27.1751, 78.0421),
        zoomLevel: 5,
      ),
    ),
  ],
)
```

UG: https://help.syncfusion.com/flutter/maps/zoom-pan#customizing-the-zoom-level

Regards,
Yuvaraj.
