### ISSUE TITLE
Cartesian Charts [RangeError Exception caught by rendering library] when set [visibleMinimum]

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#684]
please see attached .zip

[how-to-create-flutter-financial-charts-like-candle-and-ohlc-in-10-minutes.zip](https://github.com/syncfusion/flutter-widgets/files/8533638/how-to-create-flutter-financial-charts-like-candle-and-ohlc-in-10-minutes.zip)

```
════════ Exception caught by rendering library ═════════════════════════════════
RangeError (index): Invalid value: Not in inclusive range 0..41: 42
The relevant error-causing widget was
SfCartesianChart
```
 if remove line `visibleMinimum`, there is no exception.
`visibleMaximum` is irrelevant to the exception.

if add indicators, there'll be no exception too, I'm very confused.
```
indicators: <TechnicalIndicators<dynamic, dynamic>>[
        EmaIndicator(seriesName: 'AAPL'),
      ],
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

We have analyzed the customer query, and the reported issue is reproduced at our end. We will consider this as a bug, and we will fix this and roll it out in our upcoming patch release. It would be expected in the middle of the week of May 2nd. We appreciate your patience until then.

Regards,
Yuvaraj.
