### ISSUE TITLE
onTap event on PDF Viewer

### ISSUE THREAD

**Issue by rodrigorafaeldamaceno** [syncfusion/flutter-widgets#685]
Hi, thanks for this package!!

I tried adding the pdfViewer inside the GestureDetector, to get the onTap event and it doesn't work. Is there any way to catch this event? I need to show some actions when the user taps the document

**Comment by deepika134** [comment]
Hi Rodrigo Rafael,

In SfPdfViewer, we have used the gestures to detect tapping and zooming, so when using the gestures in the main.dart , it does not trigger those gestures first instead, which triggers the gestures inside the SfPdfViewer widget. We recommend using the [RawGestureDetector]( https://api.flutter.dev/flutter/widgets/RawGestureDetector-class.html) over the SfPdfViewer widget. The following code example also explains the same.

Code snippet:

```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter PDF Viewer'),
      ),
      body: RawGestureDetector(
        gestures: {
          GestureRecognizer:
              GestureRecognizerFactoryWithHandlers<GestureRecognizer>(
            () => GestureRecognizer(), //constructor
            (GestureRecognizer instance) {
              //initializer
              instance.onTap = () => print('Tapped');
            },
          )
        },
        child: SfPdfViewer.network(
          'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
          key: _pdfViewerKey,
        ),
      ),
    );
  }
}

class GestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}
```
Regards,
Deepika Ravi

**Comment by rodrigorafaeldamaceno** [comment]
Thanks @deepika134, I switched to direct TapGestureRecognizer and onTapDown and it worked fine

`gestures: {
          TapGestureRecognizer:
              GestureRecognizerFactoryWithHandlers<TapGestureRecognizer>(
            () => TapGestureRecognizer(), //constructor
            (instance) {
              instance.onTapDown = (TapDownDetails details) {
                dbprint('onTapDown');
              };
            },
          )
        },`
