### ISSUE TITLE
Month on appBar:

### ISSUE THREAD

**Issue by valipanda** [syncfusion/flutter-widgets#687]
Not sure if i'ts an issue but I've been searching for an answer and I couldn't find any. 

I am trying to place the selected month on the appBar: and I cant find a solution for this. 

home: Scaffold(
        endDrawer: const NavBar(),
        
        appBar: AppBar(
          leading: IconButton(
            onPressed: () {},
            icon: Icon(Icons.search, size: 30,),
          ),
          backgroundColor: Colors.transparent,
          systemOverlayStyle: SystemUiOverlayStyle(statusBarColor: Colors.transparent),
          centerTitle: true,
          elevation: 0,
          iconTheme: const IconThemeData(color: Colors.black),
->      title: Text(),  //I WANT TO PLACE THE SELECTED MONTH HERE //
        ),
        body:

what am I missing?

**Comment by muthulakshmi-123** [comment]
Hi Valipanda,

Thank you for contacting Syncfusion support. 

Based on provided information your requirement **“Show selected month on the AppBar in calendar”**, you can achieve your requirement by adding a Selection changed callback, in which you can get the selected date when tapped any date and show the selected month on the AppBar, we have prepared a simple sample for the same.

Kindly find the sample by referring to the following link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/month_show_appbar1443541793

We hope that this helps you. Please let us know if you need further assistance.

Regards, 
Muthulakshmi K

**Comment by valipanda** [comment]
Thank you so much for the quick reply!
Unfortunately it's not what I was looking for. 

The title changes only if the selected date is "onTap",
what I meant: to change the title when you swipe the months. (left/right)....
(you would always have to swipe - select a date - to see in which month you are in. :D )

the description "selectedMonth" is correct: 
appBar: AppBar(
          title: Text(selectedMonth,
              textAlign: TextAlign.center,
              softWrap: true,
              textScaleFactor: 1,
              overflow: TextOverflow.fade,
              style: const TextStyle(
                fontSize: 24.0,
                color: Colors.white,
              )),

however, you would have to call it "selectedDay" not "selectedMonth" because everytime you select a Day it changes the title.... I would like to change the title by swiping (without selecting a day)

I hope that makes sense ;)

**Comment by muthulakshmi-123** [comment]
Hi Valipanda,

Thanks for the update.

Based on provided information your requirement **“How to show the month when swiping the calendar”**, you can achieve your requirement by using view changed callback in SfCalendar. The view changed callback is used to get the current visible dates value and the callback is triggered whenever the view is navigated or swiped to the previous or next view and the view is switched (calendar views changed).

Please refer to the following UG link for view changed callback
https://help.syncfusion.com/flutter/calendar/callbacks#view-changed-callback

Please find the KB for customizing the header in the calendar: 
https://www.syncfusion.com/kb/12144/how-to-style-a-header-in-the-flutter-calendar

Please let us know if you need further assistance.

Regards,
Muthulakshmi K
