### ISSUE TITLE
[syncfusion_flutter_datagrid] 20.1.50 async page change run 2 times

### ISSUE THREAD

**Issue by ducdac** [syncfusion/flutter-widgets#688]
my code : i'm use Getx , when i use Get.offAndToNamed so then
```
@override
  Future<bool> handlePageChange(int oldPageIndex, int newPageIndex) async {
    var config = control.tableConfig;
    if (config.page != newPageIndex) {
      config.page = newPageIndex;
      print('newPageIndex: $newPageIndex');
      await control.setCondition(config);
      notifyListeners();
    }
    return true;
  }
```
output:
syncfusion_flutter_datagrid: 20.1.47
`newPageIndex: 1`
syncfusion_flutter_datagrid: 20.1.50
```
newPageIndex: 1
newPageIndex: 0
```

**Comment by ducdac** [comment]
I found the cause, when I run update of getx controller, grid state is reset

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ducdac,

Based on the provided information, we are not able to reproduce your reported issue. It’s working fine on our side. Please check the following simple sample which we have tested i.e., datapager with await function in the handlePageChange. In that sample, handlePageChange is called only once while navigating between the pages.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-973814388 

If you are still facing the same issue, we need more details about your reported issue to do further analysis to reproduce it i.e., details about how you are updating the Getx with DataGrid. If possible, **can you please provide the sample which you’re facing an issue?** It will be helpful for us to check on it and provide you with the best solution at the earliest.

Regards,
Tamilarasan
