### ISSUE TITLE
[syncfusion_flutter_maps ] integrate theme to google map 

### ISSUE THREAD

**Issue by rashmisridar** [syncfusion/flutter-widgets#689]
Hi Team, 
Our requirement is to develop an OLA / Uber kind of app built-in dark theme.  Please share if you have any examples. Thanks

**Comment by sfHariHaraSudhan** [comment]
Hi @rashmisridar,

The [SfMaps](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/SfMaps-class.html) widget arranges the tile we get from the tile providers to form a complete map. It supports all type of map providers such as OSM, Bing, TomTom, and others.

[SfMaps](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/SfMaps-class.html) only fetches the image based on the zoom level, coordinate x and y values available in the URL link provided in the [urlTemplate](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapTileLayer/urlTemplate.html) property. If the URL link provided in the [urlTemplate](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapTileLayer/urlTemplate.html) property has the dark mode support, then the [SfMaps](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/SfMaps-class.html) will be render in the dark mode. But however, [SfMaps](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/SfMaps-class.html) does not have any built-in features for the dark mode.

Regards,
Hari Hara Sudhan. K
