### ISSUE TITLE
SfPdfViewer does not render PDFs in high resolution on zooming

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#69]
It seems that SfPdfViewer renders PDF fast and correctly but on zooming it does not increases the resolution of the page which is currently being rendered on the screen.

**Comment by dillibabun** [comment]
Hi @sagarkardani 

At present we do not have support for “Tile rendering zoom” in SfPdfViewer widget. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

Based on our present commitments and the above parameters, this feature is expected to be implemented on or before our 2021 Volume 2 main release. We will let you know when this feature is implemented. You can also track the status of this feature from the following link,
https://www.syncfusion.com/feedback/20165/support-for-tile-rendering-zoom  

Disclaimer: The date for the feature implementation is tentative and not a commitment on our part.

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
Any update on this feature ?

Is there any temporary way to increase the resolution till "Tile rendering zoom" not implemented...

**Comment by dillibabun** [comment]
Hi @sagarkardani ,

Currently, we don't have any immediate plans to implement this feature. We request to follow the feedback report to know the updates about this feature. At present, there is no workaround to achieve this feature.

Regards,
Dilli babu.

**Comment by sagarkardani** [comment]
HI @dillibabun ,

Thank you for support.

I just want to know that is this feature is expected to be available in 2021 Volume 2 main release ? I am just asking so that I can plan accordingly.

Regards,
Sagar.

**Comment by deepika134** [comment]
Hi Sagarkardani, 

We have included the requested feature “Tile rendering zoom” in our latest volume 4 release, so kindly upgrade to the latest version v19.4.38 to get the issue resolved.    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.38-beta 

We are glad to announce that our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,  
Deepika Ravi
