### ISSUE TITLE
[syncfusion_flutter_pdfviewer] selectedText doesn't recognize new line

### ISSUE THREAD

**Issue by reset2099** [syncfusion/flutter-widgets#690]
When user select  text from various lines,  the latest word  of first line and first word of next line are joining 
ex:
```
some word
new line
```
after selected text:
```
some wordnew line
```
here are some screenshots;
![photo_2022-04-22_17-01-09](https://user-images.githubusercontent.com/65749165/164793087-61a37832-892f-481a-8a39-15a4b5314acc.jpg)
![photo_2022-04-22_17-04-44](https://user-images.githubusercontent.com/65749165/164793378-cb4a0231-7d15-4344-8a3f-ce4b5c1b0483.jpg)
![photo_2022-04-22_17-04-39](https://user-images.githubusercontent.com/65749165/164793461-59816cfe-5273-45d8-ac43-1a10571a4dc4.jpg)
![photo_2022-04-22_17-04-42](https://user-images.githubusercontent.com/65749165/164793950-c2705f40-7c78-4040-ae3e-2d2a4e43a001.jpg)

my code 

![code](https://user-images.githubusercontent.com/65749165/164796149-7c211c34-7a26-4cfd-8eb2-88dbbe537fd9.png)

files to reproduce this issue:
[intro.pdf](https://github.com/syncfusion/flutter-widgets/files/8544062/intro.pdf)
[pdf from syncfusion doc](https://help.syncfusion.com/flutter/pdf/getting-started)

**Comment by deepika134** [comment]
Hi reset2099,

This is a known behavior in the SfPdfViewer widget. We have checked the behavior in Adobe and conformed that the reported issue is a default behavior of PDFViewer.

Regards,
Deepika Ravi

**Comment by reset2099** [comment]
Well, but how I can fix that problem?

**Comment by deepika134** [comment]
Hi @reset2099 ,

As we mentioned earlier this is the default behavior of the SfPdfViewer widget but you can customize the selected text lines by using the [getSelectedTextLines()](https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/SfPdfViewerState/getSelectedTextLines.html) method in SfPdfViewer . The following code example also explains the same.

```
@override
Widget build(BuildContext context) {
return Scaffold(
    appBar: AppBar(
      title: const Text('Syncfusion Flutter PDF Viewer'),
    ),
    actions: <Widget>[
      IconButton(
        icon: const Icon(
          Icons.select_all,
          color: Colors.white,
        ),
        onPressed: () {
_pdfViewerKey.currentState!
              .getSelectedTextLines()
              .forEach((PdfTextLine pdfTextLine) {
            print('${pdfTextLine.text} ');
          });
        },
      ),
    ],
    body: SfPdfViewer.network(
'[https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf'](https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf%27),
      key: _pdfViewerKey,
    ),
  );
}
```

Regards,
Deepika Ravi
