### ISSUE TITLE
Multiple Charts EmptyPointMode.drop not work

### ISSUE THREAD

**Issue by taosimple** [syncfusion/flutter-widgets#691]
Set empty point mode to `EmptyPointMode.drop` not work on Multiple Charts
That result in blank column and a group column not center with tick, looks odd.
```
        final groupSeries = pattern.items?.map((patternItem) {
          return ColumnSeries<ChartColumn, DateTime>(
              color: Color(patternItem.color ?? color.value),
              dataSource: columns,
              xValueMapper: configUtils.timeValueMapper,
              yValueMapper: (datum, index) => configUtils.yValueMapper(
                  datum.records.where((element) => element.patternItemUid == patternItem.uid).toList(),
                  index
              ),
              emptyPointSettings: EmptyPointSettings(mode: EmptyPointMode.drop),
              );
        });
        return <ColumnSeries<ChartColumn, dynamic>>[
          ...?groupSeries
        ];
```
![IMG_20220426_081849](https://user-images.githubusercontent.com/4014593/165195227-50f971f7-419b-4373-adb3-dc808b92411c.jpg)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @taosimple, 

On analyzing the provided code snippet and information regarding the reported scenario, we would like to let you know that this is default behavior for the emptyPoint drop mode for rect series when there are null values i.e., its drops the point to render but lefts the gap for that null point when there are multiple series. This is current behavior in our chart widget.

Also, you can try setting the emptyPoint average mode for this scenario if you don’t need the gap for the null points in case of using rect type series.

Regards,
Sriram Kiran
