### ISSUE TITLE
[syncfusion_flutter_datagrid] How to set padding grid with horizontal scroll ?

### ISSUE THREAD

**Issue by ducdac** [syncfusion/flutter-widgets#692]
when i use swipping so end row pressed by horizontal scroll lead to impossible swip
![image](https://user-images.githubusercontent.com/49010784/165243806-10d5c0eb-397a-4b53-b55c-fce0ad8770ec.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ducdac,

By default, the scrollbar is visible inside the DataGrid i.e., at the bottom of its height. Its behavior in the DataGrid. Also, DataGrid doesn’t have support for setting the padding between the data grid and the scrollbar. In your case, you can achieve your requirement by using the footer. Load the SizedBox widget in the footer property and set the required height. Then set the footerFrozenRowsCount to 1. The scrollbar is shown at the footer. We have prepared a sample for that. Please check the following sample and code snippet.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: SfDataGrid(
        source: _employeeDataSource,
        columns: getColumns,
        isScrollbarAlwaysShown: true,
        footerFrozenRowsCount: 1,
        footer: const SizedBox(),
        footerHeight: 20,
      ),
    );
  }

```
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample186925461

![image](https://user-images.githubusercontent.com/93904422/165505365-fee3619f-9b90-490f-b01c-e5990ce2900f.png)

We hope this helps. Please let us know if you need any further assistance.

Regards,
Tamilarasan
