### ISSUE TITLE
[syncfusion_flutter_datagrid] BoxConstraints has a negative minimum height.

### ISSUE THREAD

**Issue by FallenRiteMonk** [syncfusion/flutter-widgets#695]
If the table is in a column as follows:
```dart
Column(
  children: [
    SizedBox(
      height: 500, // something around 3/4 of the devices screen height
      child: TextField(),
    ),
    Expanded(
      child: SfDataGrid(),
    ),
  ],
)
```
and the widget gets displayed on a mobile device, a `BoxConstraints has a negative minimum height.` exception gets thrown if the text field gets and looses the focus.

StackTrace of the exception
```
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:516:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:547:9)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:564:6)
#3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2354:27)
#4      _ScrollViewWidgetState._buildScrollView (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:239:18)
#5      _ScrollViewWidgetState._addScrollView (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:297:31)
#6      _ScrollViewWidgetState.build (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:1025:5)
#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
```

The reason for this happening is that the keyboard reduces the available space for widget, the sized box using all the space and the expanded arround the table being reduced to a negative size

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @FallenRiteMonk,

We have checked your reported issue and logged this as a bug. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on May 10, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details, 

Feedback Link:  https://www.syncfusion.com/feedback/34525/boxconstraints-has-a-negative-minimum-height-exception-is-thrown-when-opening-the 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @FallenRiteMonk,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our volume 1 SP release. Please update the DataGrid package to the **20.1.55 version**.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan
