### ISSUE TITLE
[syncfusion_flutter_datagrid] Android back key doesn't work

### ISSUE THREAD

**Issue by quangson91** [syncfusion/flutter-widgets#696]
How to reproduce:

In the `mobile_view.dart` (https://github.com/syncfusion/flutter-examples/blob/master/lib/model/mobile_view.dart#L203)
Just add a TextField like this one:

```dart
                  title: Column(
                    children: [
                      const TextField(),
                      Text(
                          _category.controlList![_category.selectedIndex!].title
                              .toString(),
                          style: const TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 16.0,
                              color: Colors.white,
                              letterSpacing: 0.3)),
                    ],
                  ),
```

Now, run the example.
1. Open Datagrid example -> Move to tab `Selection`.
2. Click on the TextField -> Keyboard display.
3. Click on the back button -> Keyboard hide.
4. Select some rows on the grid (select some items)
5. Now, press the back button.

=> Nothing happens as the back button doesn't work.

Please help!

Thanks!

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @quangson91,

We have checked your reported issue and logged this as a bug. We will include the changes in our weekly pub release which is scheduled to be rolled out on May 10, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details, 

Feedback Link:  https://www.syncfusion.com/feedback/34561/android-back-key-is-not-working-if-the-datagrid-has-focus 

Regards,
Tamilarasan

**Comment by quangson91** [comment]
@Tamilarasan-Paranthaman 
I checked, and this issue is fixed. So please close this issue.
Thank you so much.
