### ISSUE TITLE
Add Cylindrical Chart feature for charts

### ISSUE THREAD

**Issue by Shantanu66** [syncfusion/flutter-widgets#697]

**Comment by sfHariHaraSudhan** [comment]
Hi @Shantanu66,

Please give us more information about your use case for the cylindrical charts if at all feasible. With that information, we can determine whether we can offer any feasible solutions to satisfy your needs, or whether you want the inclusion of cylindrical charts as a feature, in which case we will issue a Feature Request.

Regards,
Hari Hara Sudhan. K.
