### ISSUE TITLE
Adding syncfusion_flutter_gauges package Gradle issue

### ISSUE THREAD

**Issue by ghost** [syncfusion/flutter-widgets#699]
While adding the lastest package of syncfusion_flutter_gauges: ^20.1.51 it shows me a error with Gradle. It shows that I have to upgrade it to Gradle 8.0. 
How to solve it ?

![err](https://user-images.githubusercontent.com/91061153/165691866-040cbdce-d85d-4a88-bde7-71aba39c4283.PNG)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @animeshTradingswala,

The Gradle issue will not happen due to updating the gauge widget. As this might be due to some Gradles missing for android. We suggest using delete your android folder in your project and creating it again and trying. If it doesn't work check the android studio and install the required things or reinstall it, this may resolve your problems. If you yet facing any issues, we request to raise the query for Gradle query in StackOverflow.

Thanks,
Yuvaraj.

**Comment by animeshTradingswala** [comment]
Again I'm facing other issue with my own system.
I'm sharing the all documents here.

Here is my code....
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_gauges/gauges.dart';

class MyHomePage extends StatefulWidget {
  /// Creates the instance of MyHomePage
  MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Widget _getGauge({bool isRadialGauge = true}) {
    if (isRadialGauge) {
      return _getRadialGauge();
    } else {
      return _getLinearGauge();
    }
  }

  Widget _getRadialGauge() {
    return SfRadialGauge(
        title: GaugeTitle(
            text: 'Speedometer',
            textStyle:
                const TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold)),
        axes: <RadialAxis>[
          RadialAxis(minimum: 0, maximum: 150, ranges: <GaugeRange>[
            GaugeRange(
                startValue: 0,
                endValue: 50,
                color: Colors.green,
                startWidth: 10,
                endWidth: 10),
            GaugeRange(
                startValue: 50,
                endValue: 100,
                color: Colors.orange,
                startWidth: 10,
                endWidth: 10),
            GaugeRange(
                startValue: 100,
                endValue: 150,
                color: Colors.red,
                startWidth: 10,
                endWidth: 10)
          ], pointers: <GaugePointer>[
            NeedlePointer(value: 90)
          ], annotations: <GaugeAnnotation>[
            GaugeAnnotation(
                widget: Container(
                    child: const Text('90.0',
                        style: TextStyle(
                            fontSize: 25, fontWeight: FontWeight.bold))),
                angle: 90,
                positionFactor: 0.5)
          ])
        ]);
  }

  Widget _getLinearGauge() {
    return Container(
      child: SfLinearGauge(
          minimum: 0.0,
          maximum: 100.0,
          orientation: LinearGaugeOrientation.horizontal,
          majorTickStyle: LinearTickStyle(length: 20),
          axisLabelStyle: TextStyle(fontSize: 12.0, color: Colors.black),
          axisTrackStyle: LinearAxisTrackStyle(
              color: Colors.cyan,
              edgeStyle: LinearEdgeStyle.bothFlat,
              thickness: 15.0,
              borderColor: Colors.grey)),
      margin: EdgeInsets.all(10),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Syncfusion Flutter Gauge')),
        body: _getGauge());
  }
}


![err](https://user-images.githubusercontent.com/91061153/166292927-81f20f40-c1dc-49b3-8f7f-7359d1c97509.png)

![flutter-version](https://user-images.githubusercontent.com/91061153/166292962-1fe85407-9899-4e26-808f-d36f4c75c38b.png)

![pubspec](https://user-images.githubusercontent.com/91061153/166292993-d4a88451-47a6-49d0-9bf1-8f60a1a225ef.png)

**Comment by Yuvaraj-Gajaraj** [comment]
We have checked your code snippet and tried to reproduce the reported issue at our end. But unfortunately, the reported issue is not getting reproduced at our end. We request you to update the syncfusion_flutter_gauges package to the latest version and ensure once. If you still facing the issue please share the sample to reproduce the issue it will be more helpful to us to provide a solution sooner.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you need any assistance on this.
