### ISSUE TITLE
SfDataGrid - is there a way to make each row expandable?

### ISSUE THREAD

**Issue by Ne0n11** [syncfusion/flutter-widgets#700]
So, we have table, and on clicking on cell, we not only select the row, but also expand some panel with more info on selected row at the bottom of the selected row and before next row.

Something like in the image below
![image](https://user-images.githubusercontent.com/28736291/166465115-c5a861b2-569e-4969-8e1b-bc229637b827.png)

**Comment by ashok-kuvaraja** [comment]
Hi @Ne0n11,

Currently, DataGrid does not have support for the expandable rows. This feature will be implemented in any of our upcoming releases. We will let you know when this feature is implemented. You can follow up with the below feedback for further details,

Feedback Link: https://www.syncfusion.com/feedback/34627/support-to-show-a-preview-rows

Regards,
Ashok K
