### ISSUE TITLE
Weekday jumps higher as well when changing todayTextStyle's height property

### ISSUE THREAD

**Issue by valipanda** [syncfusion/flutter-widgets#701]
<img width="920" alt="Bildschirmfoto 2022-05-04 um 01 46 55" src="https://user-images.githubusercontent.com/57576185/166606191-ac401c70-f675-4e29-9d3d-555af25aa8d6.png">

I tried to gain some space by changing the hight value of todayTextStyle: (also trailing and leadingDates). but the weekday jumps higher as well (as you can see on the picture) - but only on the actual day (today - in this case Mi. (german for Wednesday) )

Am I doing something wrong or is this a bug?

**Comment by Indumathi1195R** [comment]
Hi Team,

**Regarding Query: Weekday jumps higher as well when changing todayTextStyle's height property.**

Based on the shared information, we have checked the mentioned issue “**While using the todayTextStyle height value other week days height also jumps higher  in the Flutter Calendar**” and we are unable to understand the issue from our end and height value is applied only for the today, rest of the weekdays are in same height and it was working fine as expected from our end. We have attached the tested image for the same. Please find the screenshot from the following link.

**Screenshot:**

![vidma_recorder_04052022_150434](https://user-images.githubusercontent.com/54974849/166660896-15a63b46-3414-4ca0-8b80-34ac62d4206a.jpg)


**Tested device:**
Samsung M21

If possible, could you please share the below details,

•	Device details
•	Flutter Calendar version

It will be helpful for us to check on it and provide you solution at the earliest.

Regards,
Indumathi R
