### ISSUE TITLE
Edit single cell in CalendarView.timeliveMonth

### ISSUE THREAD

**Issue by UmbertoGagliardini** [syncfusion/flutter-widgets#703]
Hi, 
is there any way to edit the single cell in view timeliveMonth (e.g. insert Text in each cell) like it is possible in view Month using monthCellBuilder? Thanks.

**Comment by Indumathi1195R** [comment]
UmbertoGagliardini,

**Regarding Query: is there any way to edit the single cell in view timelineMonth?**

Can you please share your requirement clearly with illustration image. It would be helpful for us to analyze and provide you a solution at the earliest.

**Regarding Query: it is possible in view Month using monthCellBuilder?** 

According to the shared information, you can add the required text in the month cell using the monthCellbuilder property of the calendar, cell builder allows you to design your own custom view and assign it to the month cells. We have a UG and KB documentations for the same. Please find the documentations from the following link.

**UG link:**
https://help.syncfusion.com/flutter/calendar/builders#month-cell-builder

**KB link:**

https://www.syncfusion.com/kb/12210/how-to-customize-the-month-cell-based-on-the-appointment-using-builder-in-the-flutter
https://www.syncfusion.com/kb/12306/how-to-customize-the-month-cell-with-appointment-count-in-the-flutter-calendar
