### ISSUE TITLE
Lazy load for SfDataGrid

### ISSUE THREAD

**Issue by 15563988825** [syncfusion/flutter-widgets#705]
how to load data lazy in datagrid when using SfDataPager to pagging data.
for exapmle:
each api return 100 columns,and load another 100 columns when click another page number.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi,

Greetings from Syncfusion.

We are a little bit unclear about your requirements. By default, the data pager is used to show the paginated rows. As per your example provided in the query, can you confirm whether you want to show another 100 rows with the same data collection on the next page or another 100 columns with different data collections? It will be helpful for us to check on it and provide you with the appropriate solution at the earliest.

Regards,
Tamilarasan
