### ISSUE TITLE
bug: stacked area chart border starting from offset(0, 0)

### ISSUE THREAD

**Issue by Korpyc** [syncfusion/flutter-widgets#706]
SfCartesianChart widget with StackedAreaSeries elements. 
Border mode is default - BorderDrawMode.top

But border starting drawing from Offset(0, 0) for the area.

Also, as you see another issue, green area is drawing above half of red border.

![photo_2022-05-05_17-39-05](https://user-images.githubusercontent.com/43324192/166948131-dac68c71-aff3-4373-9f2c-a1ba84dd3cfe.jpg)

**Comment by sfHariHaraSudhan** [comment]
Hi @Korpyc, 

We are able to replicate the reported issue regarding "**border draw mode property is not working properly in stacked area series**" at our end and have logged a bug report for it in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out on July 04, 2023. We will update you here once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the below feedback link.

Feedback link:  https://www.syncfusion.com/feedback/44618/borderdrawmode-property-is-not-working-property-in-stacked-area-series.

The rendering of the StackedAreaSeries extends beyond the border of StackedAreaSeries below, which is the current behavior in the SfCartesianChart.

Regards,
Hari Hara Sudhan. K

**Comment by sfHariHaraSudhan** [comment]
Hi @Korpyc,

The reported issue regarding **Border draw mode property is not working properly in stacked area series** has been fixed and rolled out in our Weekly patch release. Therefore, we kindly request that you upgrade the syncfusion_flutter_charts package to the latest version below to avoid this issue.

Version:  https://pub.dev/packages/syncfusion_flutter_charts/versions/22.1.37

Regards,
Hari Hara Sudhan. K.
