### ISSUE TITLE
[syncfusion_flutter_xlsio] add freeze row or column .

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#707]
add freeze option to row or column .

**Comment by SivakumarRamya** [comment]
Hi Joseph,



Greetings from Syncfusion.



We have a feature report as Freeze panes to lock rows and columns but do not have any immediate plans to implement this feature in near future. You can track the status of the feature report through the following feedback link.



Track Status: https://www.syncfusion.com/feedback/25221/freeze-panes-to-lock-rows-and-columns



Regards,

Ramya.Hi Joseph,



Greetings from Syncfusion.



We have a feature report as Freeze panes to lock rows and columns but do not have any immediate plans to implement this feature in near future. You can track the status of the feature report through the following feedback link.



Track Status: https://www.syncfusion.com/feedback/25221/freeze-panes-to-lock-rows-and-columns



Regards,

Ramya.
