### ISSUE TITLE
Can I use syncfusion_flutter_charts for free in my application?

### ISSUE THREAD

**Issue by Ghost180195** [syncfusion/flutter-widgets#71]
Can I use syncfusion_flutter_charts for free in my application?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Ghost180195,

Greetings from Syncfusion. We have analyzed your query at our end and we would like to share some information regarding our chart widget. In our last main release, we have made our syncfusion_flutter_charts package as open source. However, if you want to use our chart widget in your application, you need to license either under community license program or the syncfusion commercial license. To be qualified for the Syncfusion Community License Program you must have a gross revenue of less than one (1) million U.S. dollars ($1,000,000.00 USD) per year and have less than five (5) developers in your organization, and agree to be bound by Syncfusion’s terms and conditions. 
 
Please check below link for Syncfusion's terms and conditions regarding licensing.
https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/LICENSE

Also we have attached a knowledge base link below which explains on how to get community license and install it.
https://www.syncfusion.com/kb/11279/how-to-get-community-license-and-install-it

For further reference on our Syncfusion Flutter charts package, please refer the link below.
https://www.syncfusion.com/flutter-widgets

Regards,
Sriram Kiran

**Comment by Ghost180195** [comment]
Thank you for the answer. I will try it
