### ISSUE TITLE
SFMaps any user interactions is not working

### ISSUE THREAD

**Issue by guccisekspir** [syncfusion/flutter-widgets#711]
Hi there,

I user SFMaps in my Flutter Web project. Everything is perfect maps and cities drawing perfectly and hover things working but when I tap I get nothing. Not any callback about selectedIndex or showing tooltip or anything. Here my [geoJson](https://github.com/alpers/Turkey-Maps-GeoJSON/blob/master/tr-cities.json)

Flutter version : Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
Library version: ^20.1.52

https://user-images.githubusercontent.com/56968218/167252459-2d2f522a-aa28-422f-86f6-5037cf7ae674.mov

```dart  

_mapSource = MapShapeSource.asset('web/assets/jsons/tr-cities.json',
        shapeDataField: 'name',
        dataCount: 82,
        primaryValueMapper: (int index) => "ana" + index.toString(),
        shapeColorValueMapper: (int index) => Colors.red); 

 MapShapeLayer(
                      onSelectionChanged: (int a) {
                        debugPrint(a.toString() + " tıklandı");
                        setState(() {
                          selectedIndex = a;
                        });
                      },
                      selectedIndex: selectedIndex ?? -1,
                      selectionSettings: MapSelectionSettings(color: Colors.white),
                      color: themeHelper.primaryColor,
                      strokeColor: themeHelper.onBackground,
                      source: _mapSource,
                      showDataLabels: true,
                      shapeTooltipBuilder: (BuildContext context, int index) {
                        return Padding(
                            padding: const EdgeInsets.all(7),
                            child: Text(
                              "data[index].stateCode" + index.toString(),
                            ));
                      },
                      tooltipSettings:
                          MapTooltipSettings(color: Colors.blue, strokeColor: Colors.white, strokeWidth: 2),
                      strokeWidth: 0.5,
                      dataLabelSettings: const MapDataLabelSettings(
                          textStyle: TextStyle(color: Colors.black, fontWeight: FontWeight.bold, fontSize: 10)),
                    ),

**Comment by LokeshPalani** [comment]
Hi @guccisekspir,

We tried to replicate the reported issue regarding SfMaps user interactions is not working at our end. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure on what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.

Regards,
Lokesh.

[map_474242.zip](https://github.com/syncfusion/flutter-widgets/files/11796785/map_474242.zip)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this issue with requested details to proceed further on this.
