### ISSUE TITLE
footer rows not show last page

### ISSUE THREAD

**Issue by bekirelifkeremoruc** [syncfusion/flutter-widgets#713]
Hello,
I used your invoice example, when I add many rows to the table, the header and footer are not visible on the 2nd page,
I attached screenshot.
I have to show Header and Footer both on page 1 and page 2
![image](https://user-images.githubusercontent.com/61472696/167290900-e02f0f36-1ac3-4613-a5c6-3cc318f65fd2.png)

**Comment by GowthamrajKumar25** [comment]
Hi bekirelifkeremoruc,

We have tried to reproduce it with the simple sample, but it is working properly. We were not able to reproduce the reported overlap issue on our end. We have attached the complete code snippet and output document for your reference, please try the below code snippet and let us know the result.

Output: https://www.syncfusion.com/downloads/support/directtrac/general/pd/SampleOutput-1190468884

Please refer to the below UG documentation,
https://help.syncfusion.com/flutter/pdf/working-with-headers-and-footers

Please find the below code snippet to draw the header and footer with the grid,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/test148905498

If the above details do not help to resolve your issue, Kindly revert us with the below-required details. So, it will help us to provide a precise solution. 
•	Syncfusion package details with version.
•	Flutter details, the output document
•	complete code snippet or simplified sample to replicate the issue on our end.

Regards,
Gowthamraj K
