### ISSUE TITLE
Strange curves on  Line Chart

### ISSUE THREAD

**Issue by sunjianan9900** [syncfusion/flutter-widgets#715]
Why is there a bulge that looks very abnormal and incorrect

![image](https://user-images.githubusercontent.com/10936316/167767079-d3e57120-1f46-408e-a2b5-3cc1836ba8e7.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @sunjianan9900,

In [SplineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SplineSeries-class.html)  in general it will render with smooth curve only and by default type of the spline is natural. We have other types of splines, and we suspect that monotonic type may suit to your case. If so, use the below code to achieve your requirement and also you can check with other spline types. 

Code snippet
```dart
SfCartesianChart(
  series: <ChartSeries<SampleData, DateTime>>[
    SplineSeries(
      splineType: SplineType.monotonic,
      //Other required properties   
  ])
```

UG: https://help.syncfusion.com/flutter/cartesian-charts/chart-types/spline-chart#spline-rendering-types 

If you wish to have just a straight line connecting the two points, you can use the line series.

UG: https://help.syncfusion.com/flutter/cartesian-charts/chart-types/line-chart

Regards,
Yuvaraj.
