### ISSUE TITLE
Custom tooltip

### ISSUE THREAD

**Issue by andibardhi** [syncfusion/flutter-widgets#716]
I want to add a tooltip to the whole month container (like outlined in the screenshot below) is there any way to do that?

![image](https://user-images.githubusercontent.com/51854918/167833618-97df6524-b02b-4597-ab12-9928fcc5fb68.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @andibardhi,

We suggest you use [trackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/trackballBehavior.html) and [tooltipDisplayMode](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/tooltipDisplayMode.html) as [groupAllPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html), it will help you to display all the series y values in the tooltip that is with respect to the x value. It will help you to achieve your requirement and we have added the code snippet and UG documentation below for your reference.

Code snippet:
```dart
trackballBehavior: TrackballBehavior(
  enable: true,
  tooltipDisplayMode: TrackballDisplayMode.groupAllPoints
),
```

UG: https://help.syncfusion.com/flutter/cartesian-charts/trackball-crosshair#label-display-mode

Regards,
Yuvaraj.

**Comment by andibardhi** [comment]
Hi @Yuvaraj-Gajaraj,
in addition to `tooltipDisplayMode: TrackballDisplayMode.groupAllPoints` i also had to add `activationMode: ActivationMode.singleTap,` and also `lineColor: Colors.transparent,` so the line won't show. For the tooltip, I am using `builder`. One more question: Is there any way to make the part outlined with red change color on hover?
