### ISSUE TITLE
Export to Excel Not Exporting whole Data grid but only the current page that is selected

### ISSUE THREAD

**Issue by zeel007** [syncfusion/flutter-widgets#717]
Export to Excel Not Exporting whole Data grid but only the current page that is selected. is there any way to resolve this issue?

`void exportDataGridToExcel() {
    final Workbook workbook =
        key.currentState!.exportToExcelWorkbook(excludeColumns: ['edit']);
    final List<int> bytes = workbook.saveAsStream();
    workbook.dispose();
    AnchorElement(
        href:
            "data:application/octet-stream;charset=utf-16le;base64,${base64.encode(bytes)}")
      ..setAttribute("download", "new.xlsx")
      ..click();
  }`

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @zeel007,

You can achieve your requirement by using the **rows** property in the **exportToExcelWorkbook** method. Please check the following steps.

**Step 1**: Create an internal DataGridRows row with the entire underlying data collection. Please check the following code snippet.

``` dart
List<DataGridRow> _dataGridRows = [];


class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource() {
    paginatedDataSource = _employees.getRange(0, 10).toList();
    buildDataGridRows();
  }

  void buildDataGridRows() {
    _employeeData = paginatedDataSource
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
    _dataGridRows = _employees
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }
  
…
}

```
**Step 2**: Pass the internal DataGridRows collection to the rows property to export the whole DataGrid. We have prepared the sample for that. Please check the following sample and code snippet.

```dart
ElevatedButton(
        onPressed: () {
               final Workbook workbook = _key.currentState!.exportToExcelWorkbook(rows: _dataGridRows);
               final List<int> bytes = workbook.saveAsStream();
               workbook.dispose();
               AnchorElement(href: "data:application/octet-stream;charset=utf-16le;base64,${base64.encode(bytes)}")
               ..setAttribute("download", "new.xlsx")
               ..click();
                },
                child: const Text('Export')),
```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1122977763 

We have already provided examples in our UG documentation. Please go through this,

UG Documentation: https://help.syncfusion.com/flutter/datagrid/export-to-excel#export-the-selected-rows-to-excel  

We hope this helps. Please let us know if you need any further assistance.	

Regards,
Tamilarasan

**Comment by zeel007** [comment]
Thanks for the Solution This has worked for me!!
