### ISSUE TITLE
syncfusion_flutter_gauges-20.1.52 - Compile error with Flutter 3.0.0

### ISSUE THREAD

**Issue by michael-woolsey** [syncfusion/flutter-widgets#718]
Hello everyone,

I'm getting the following error `Error: A value of type 'Widget' can't be assigned to a variable of type 'InheritedWidget'.` once I upgraded to Flutter 3.0.0 today:
```
Cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges-20.1.52/lib/src/linear_gauge/gauge/linear_gauge_scope.dart:40:10: Error: A value of type 'Widget' can't be assigned to a variable of type 'InheritedWidget'.
- 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/flutter/packages/flutter/lib/src/widgets/framework.dart').
- 'InheritedWidget' is from 'package:flutter/src/widgets/framework.dart' ('/flutter/packages/flutter/lib/src/widgets/framework.dart').
        .widget;
```

Hopefully it's something that can get addressed soon!

Thank you,
Michael

**Comment by osmanGuler19** [comment]
Same here!

**Comment by michael-woolsey** [comment]
It appears that they have had a PR (https://github.com/syncfusion/flutter-widgets/pull/596) for this issue since Feb 21st and it still made it through to a production issue.

**Comment by osmanGuler19** [comment]
my flutter version isn't 3.0 but still I am getting the same error

**Comment by rienkkk** [comment]
Same here, preveting migration to Flutter 3.0.

**Comment by lucavenir** [comment]
I just got exactly the same problem here. Guess my project will wait for Flutter 3 until then 😔

**Comment by Hassanch15** [comment]
Same problem here.

**Comment by michael-woolsey** [comment]
Sadly, today's release of `20.1.55` DID NOT solve this problem.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @michael-woolsey,

The customer reported issue is reproduced at our end, because of the new Flutter version release. We will fix this and roll it out in our upcoming weekly patch release, we will update you once the patch got rolled out. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by michael-woolsey** [comment]
Hello @Yuvaraj-Gajaraj,

If you're telling me that I have another week to find a solution to this problem, my solution may very well be to find another product.

**Comment by lucavenir** [comment]
> Hello @Yuvaraj-Gajaraj,
> 
> If you're telling me that I have another week to find a solution to this problem, my solution may very well be to find another product.

Come on, it's open source software and 3.0 came out just yesterday (and it wasn't announced).

Let's wait one week and see if they can deliver, this fix shouldn't be much of a problem.

**Comment by michael-woolsey** [comment]
@lucavenir - Cause they didn't know about it coming since at least Feb 21st where someone else made a PR for them on a commercial product?  

If you find that acceptable, all the power to you, many will agree with you.

**Comment by pbertsch** [comment]
I just hit the same issue, temporarily fixed the issue by editing the linear_gauge_scope.dart and changed the InheritedWidget to a Widget. It works because it is only used for a basic comparison. It should look like that afterwards.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/7844575/168428896-2e082ce7-dc9d-4cd9-b002-0b5c4217c83d.png">

It's only temporary in my case so I can go ahead with the development for now.

**Comment by acx70** [comment]
Same problem after upgrading to flutter 3.0

**Comment by acx70** [comment]
> #### Temporary workaround:
> 
> ```
> # Hot fix for Flutter 3.0
>   syncfusion_flutter_gauges:
>     git:
>       url: https://github.com/AlexVegner/flutter-widgets.git
>       ref: flutter_3_0
>       path: packages/syncfusion_flutter_gauges
> ```

It does not work if you have to publish the package

**Comment by acx70** [comment]
> I just hit the same issue, temporarily fixed the issue by editing the linear_gauge_scope.dart and changed the InheritedWidget to a Widget. It works because it is only used for a basic comparison. It should look like that afterwards.
> 
> <img alt="image" width="604" src="https://user-images.githubusercontent.com/7844575/168428896-2e082ce7-dc9d-4cd9-b002-0b5c4217c83d.png">
> 
> It's only temporary in my case so I can go ahead with the development for now.

This is the only temporary solution that works

**Comment by michael-woolsey** [comment]
Thank you for the update this morning, that has corrected the build issue.
