### ISSUE TITLE
syncfusion_flutter_pdfviewer-20.1.55-beta 

### ISSUE THREAD

**Issue by santomalau03** [syncfusion/flutter-widgets#722]
Swift Compiler Error (Xcode): 'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'

**Comment by deepika134** [comment]
Hi   Santo Malau,

We are checking on the reported query and will update the further details on May 17, 2022.

Regards,
Deepika Ravi

**Comment by dillibabu1802** [comment]
Hi @santomalau03 

Thank you for contacting Syncfusion support.

We are unable to reproduce the reported error from our side. We found that the reported issue might occur when an improper swift version is used in PodFile. So, kindly share the following details.
1. Flutter Doctor log.
2. Confirm us whether issue is reproduced in `[this sample](https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer/example)`.

Regards,
Dilli babu,

**Comment by santomalau03** [comment]
Thank you, after i check my swift version. My Flutter app using old version. Thank you for your response
