### ISSUE TITLE
Need to be migrate new flutter version 3.0.0 to syncfusion pdf viewer

### ISSUE THREAD

**Issue by viralkachhadiya** [syncfusion/flutter-widgets#723]
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:918:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
                   ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1002:5: Warning: Operand of null-aware operation '?.' has type 'ImageCache' which excludes null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../../../Developer/flutter/packages/flutter/lib/src/painting/image_cache.dart').
    imageCache?.clear();
    ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1022:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.removeObserver(this);
                   ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1052:5: Warning: Operand of null-aware operation '?.' has type 'ImageCache' which excludes null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../../../Developer/flutter/packages/flutter/lib/src/painting/image_cache.dart').
    imageCache?.clear();
    ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1866:42: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
                          WidgetsBinding.instance?.window.viewInsets.bottom !=
                                         ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1872:48: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
                                WidgetsBinding.instance!.window.viewInsets,
                                               ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:1874:38: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
                                    .instance!.window.devicePixelRatio)
                                     ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:2653:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                     ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:2668:28: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
            WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                           ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:2692:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                         ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:2790:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                     ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:2804:26: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
          WidgetsBinding.instance
                         ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:3325:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {
                     ^
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.55-beta/lib/src/pdfviewer.dart:3335:24: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
        WidgetsBinding.instance?.addPostFrameCallback((Duration timeStamp) {

**Comment by viralkachhadiya** [comment]
@Indumathi1195R can you please look into my pr?

**Comment by deepika134** [comment]
Hi @viralkachhadiya,

We are checking on the reported query and will update the further details on May 17, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi @viralkachhadiya ,

We have upgraded the Flutter PDFViewer component in Flutter SDK v3, and these changes were included in our latest weekly NuGet release, so kindly upgrade to the latest version v20.1.56 to get the issue resolve.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.56-beta 

Regards, 
Deepika R
