### ISSUE TITLE
How can I listen saving woorkbook ?

### ISSUE THREAD

**Issue by Bahrom2101** [syncfusion/flutter-widgets#725]
https://stackoverflow.com/questions/72225317/how-to-listen-how-many-bytes-written-to-storage-while-saving-excel-file-in-syncf

**Comment by SivakumarRamya** [comment]
Hi

Greetings from Syncfusion.

Unfortunately, Flutter XlsIO does not have support for providing the status/progress of Excel document creation. And, we don’t have any plans to implement this feature.

Regards,
Ramya.
