### ISSUE TITLE
Flutter 3:  WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp)

### ISSUE THREAD

**Issue by JanRegent** [syncfusion/flutter-widgets#728]
/C:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.1.55/lib/src/datagrid_widget/sfdatagrid.dart:3907:20: Warning: Operand of null-aware operation '!'has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp) {
                   ^
/C:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.1.55/lib/src/datagrid_widget/sfdatagrid.dart:3917:20: Warning: Operand of null-aware operation '!'has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((Duration timeStamp) {
                   ^
/C:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.1.55/lib/src/datapager/sfdatapager.dart:506:20: Warning: Operand of null-aware operation '?.' has 
type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addPostFrameCallback((_) async {
                   ^
/C:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.1.55/lib/src/datapager/sfdatapager.dart:1383:22: Warning: Operand of null-aware operation '?.' hastype 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {

**Comment by KK-Karan-Kumar** [comment]
## Also i am greeting the same error

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @JanRegent / @KK-Karan-Kumar,

Greetings from Syncfusion.

We have already fixed the issue which occurred after upgrading the Flutter SDK version to 3.0.0. **It will be rolled out in our next weekly patch release**, **which is expected by tomorrow (May 17, 2022)**, and we will update you once the patch gets rolled out. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @JanRegent / @KK-Karan-Kumar,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our weekly patch release. Please update the DataGrid package to the **20.1.56** version.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan
