### ISSUE TITLE
intl dependency

### ISSUE THREAD

**Issue by GefaketHD** [syncfusion/flutter-widgets#73]
The newest (prerelease) version of intl is 0.17.0-nullsafety.2 (https://pub.dev/packages/intl). Please check if you could upgrade your dependencies to intl < 0.18 without a problem and if so, please do. Thank you in advance.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @GefaketHD ,

Thanks for contacting Syncfusion support. We have analyzed on your scenario at our end and we are sorry that currently, we provide support only for stable package versions our Flutter widgets. As the **intl** package version ([**0.17.0-nullsafety.2**](https://pub.dev/packages/intl/versions/0.17.0-nullsafety.2)) which you have requested to upgrade is in presale version, we cannot upgrade the **intl** package to its presale version. Sorry for the inconvenience. However, if you want to use the **intl** package’s presale version in your application then you can override the required version of dependencies in your project’s _pubspec.yaml_ file. Please check the code snippet below for further reference.

```
dependency_overrides:
    intl: ^0.17.0-nullsafety.2
```

For further reference on dependency overrides, please check the link below.
https://dart.dev/tools/pub/dependencies#dependency-overrides

Please get in touch with us if you require further assistance on this.

Regards,
Sriram Kiran
