### ISSUE TITLE
flutter 3: ERROR: A value of type 'Widget' can't be assigned to a variable of type 'InheritedWidget'.

### ISSUE THREAD

**Issue by royacodes** [syncfusion/flutter-widgets#731]
recently, I update flutter to version 3 and can't build the app. 
error below is generated:
                            ^
                /C:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_gauges- 
                20.1.55/lib/src/linear_gauge/gauge/linear_gauge_scope.dart:40:10: Error: A value of type 'Widget' can't be assigned to a 
                variable of type 'InheritedWidget'.
               - 'Widget' is from 'package:flutter/src/widgets/framework.dart' 
               -  ('/C:/flutter_3.0.0/packages/flutter/lib/src/widgets/framework.dart').
               - 'InheritedWidget' is from 'package:flutter/src/widgets/framework.dart' 
               -  ('/C:/flutter_3.0.0/packages/flutter/lib/src/widgets/framework.dart').

**Comment by rsbthebest** [comment]
Plus 1 to this!

**Comment by pbertsch** [comment]
I just hit the same issue, temporarily fixed the issue by editing the  `linear_gauge_scope.dart` and changed the InheritedWidget to a Widget. It works because it is only used for a basic comparison.  It should look like that afterwards. 

<img width="613" alt="image" src="https://user-images.githubusercontent.com/7844575/168428505-067b1869-4571-4343-acb3-196f084813e2.png">

It's only temporary in my case so I can go ahead with the development for now.

**Comment by cksdnr1** [comment]
same to me

**Comment by SimonHausdorf** [comment]
As a quick fix change the type `InheritedWidget` to `Widget` in

```
/syncfusion_flutter_gauges-20.1.55/lib/src/linear_gauge/gauge/linear_gauge_scope.dart:40
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @royacodes,

Greetings from Syncfusion. We have already fixed the issue which occurred after upgrading the Flutter SDK version to 3.0.0. It will be rolled out in our next weekly patch release, which is expected by tomorrow, and we will update you once the patch gets rolled out. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by royacodes** [comment]
> 

Thank you very much for your consideration.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @royacodes,

Thanks for your patience. The issues with Flutter v3.0.0 have been fixed and rolled out in our weekly patch release. To avoid the issues, please upgrade our package to the latest version 20.1.56.

Regards,
Yuvaraj.

**Comment by royacodes** [comment]
> Hi @royacodes,
> 
> Thanks for your patience. The issues with Flutter v3.0.0 have been fixed and rolled out in our weekly patch release. To avoid the issues, please upgrade our package to the latest version 20.1.56.
> 
> Regards, Yuvaraj.

Many thanks for the prompt reply
