### ISSUE TITLE
[Cartesian Charts] cannot-change-visible-range-after-pan-or-pinch.zip

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#735]
please see an example attached.
no exception is caught.

[cannot-change-visible-range-after-pan-or-pinch.zip](https://github.com/syncfusion/flutter-widgets/files/8697954/cannot-change-visible-range-after-pan-or-pinch.zip)

---------
this issue still exists under [syncfusion_flutter_charts 20.1.56 + flutter 3.0.0] on my end.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

The reported issue has been fixed already and it will be available in the next weekly patch release which is expected on May 24, 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Marismathan** [comment]
Hi @FisherWL ,

Thanks for your patience. The reported issue has been fixed and rolled out in our weekly patch release. To avoid the issue please upgrade the chart package to the below latest version.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.57

Thanks,
Marismathan G
