### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null. 

### ISSUE THREAD

**Issue by AyeshaIftikhar** [syncfusion/flutter-widgets#738]
I have been using **syncfusion_flutter_pdfviewer** in my project to display pdf files, but the recent version is not letting the compiler to build the application and throwing the following error:
```
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/flutter_stable/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter_stable/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.1.56-beta/lib/src/control/scroll_head_overlay.dart:287:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/flutter_stable/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                            ^^^^^^^^^^^^^^^^^^^^
2

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\flutter_stable\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\flutter_stable\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 14s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by SouravSinghSoftradix** [comment]
same issue coming from my end

**Comment by deepika134** [comment]
Hi @AyeshaIftikhar , @SouravSinghSoftradix ,

kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.
Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk 

Regards,
Deepika R

**Comment by Kalyan-2k** [comment]
Hi @deepika134 
I'm trying to view a pdf file in my flutter application when a button is pressed but i seem to get the following errors.
`/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:357:24: Warning: Operand of null-aware operation '!' has type     
'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'       
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/extension_navigation.dart:468:24: Warning: Operand of null-aware operation '!' has type     
'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.addPostFrameCallback((_) {
                       ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/snackbar/snackbar.dart:452:22: Warning: Operand of null-aware operation '!' has type        
'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(
                     ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_disposable.dart:20:22: Warning: Operand of null-aware operation '?.' has   
type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/rx_flutter/rx_notifier.dart:130:22: Warning: Operand of null-aware operation '?.' has    
type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance?.addPostFrameCallback((_) => onReady());
                     ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:90:20: Warning: Operand of null-aware operation '!' has type 
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_state_manager/src/simple/get_controllers.dart:96:20: Warning: Operand of null-aware operation '!' has type 
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/hosted/pub.dartlang.org/get-4.6.1/lib/get_navigation/src/router_report.dart:53:22: Warning: Operand of null-aware operation '!' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) {
                     ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/git/charts-d6adb193ff91d2042941bad388845cbc8c5cd964/charts_flutter/lib/src/chart_container.dart:205:27: Warning: Operand of null-aware operation '!'
has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    if (!SchedulerBinding.instance!.hasScheduledFrame) {
                          ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/git/charts-d6adb193ff91d2042941bad388845cbc8c5cd964/charts_flutter/lib/src/chart_container.dart:206:24: Warning: Operand of null-aware operation '!'
has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
      SchedulerBinding.instance!.scheduleFrame();
                       ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/git/charts-d6adb193ff91d2042941bad388845cbc8c5cd964/charts_flutter/lib/src/chart_container.dart:209:22: Warning: Operand of null-aware operation '!'
has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(startAnimationController);
                     ^
/C:/Users/NAGARJUNA/flutter/.pub-cache/git/charts-d6adb193ff91d2042941bad388845cbc8c5cd964/charts_flutter/lib/src/chart_container.dart:232:22: Warning: Operand of null-aware operation '!'
has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('/C:/Users/NAGARJUNA/flutter/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!.addPostFrameCallback(doRebuild);`

I tried your suggestion on updating the flutter SDK but the error isn't resolved .

**Comment by Kalyan-2k** [comment]
The flutter code for the above error is given below👇👇
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
import '../authentication/api.dart';

class Assessment extends StatefulWidget {
  const Assessment({Key key}) : super(key: key);

  @override
  State<Assessment> createState() => _AssessmentState();
}

class _AssessmentState extends State<Assessment> {
  // PdfViewerController _pdfViewerController;
  @override
  void initState() {
    // _pdfViewerController = PdfViewerController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        backgroundColor: Colors.white,
        body: Center(
          child: Container(
            margin: EdgeInsets.all(50),
            alignment: Alignment.topCenter,
            constraints:
                BoxConstraints(maxWidth: double.infinity, maxHeight: 100),
            child: Row(
              children: [
                Text(
                  "Practice test -1 :",
                  style: TextStyle(
                      fontSize: 16,
                      fontFamily: "DancingScript-Regular",
                      fontWeight: FontWeight.bold),
                  softWrap: true,
                  textAlign: TextAlign.center,
                ),
                SizedBox(width: 100),
                ElevatedButton(
                  onPressed: () {
                    SfPdfViewer.network(
                        'https://cdn.syncfusion.com/content/PDFViewer/encrypted.pdf',
                        password: 'syncfusion',
                        pageLayoutMode: PdfPageLayoutMode.single,
                        enableDoubleTapZooming: true);
                  },
                  child: Text(
                    "Start Assessment",
                    style: TextStyle(
                        fontSize: 16, fontFamily: "DancingScript-Regular"),
                  ),
                ),
                SizedBox(
                  width: 30,
                ),
                InkWell(
                  onTap: () async {
                    await Api.videocall(context);
                  },
                  child: Icon(
                    Icons.videocam,
                    size: 30.0,
                    color: Colors.black,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
Kindly help me resolve this issue

**Comment by KafkaWannaFly** [comment]
I think there's something wrong with the latest version.

In your `pubspec.yaml`, set this library to the fixed version: `syncfusion_flutter_pdfviewer: 20.1.51-beta`. Run `flutter clean` `flutter pub get`. Hope that will work for you.

**Comment by deepika134** [comment]
Hi Kalyan-2k,

Kindly run the flutter clean command and upgrade the latest version of Syncfusion PdfViewer. Please try this and let us know if the issue is resolved or not.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.56-beta

Regards,
Deepika Ravi

**Comment by Yahllil** [comment]
I experience this as well.
Run `flutter clean && flutter pub get` and still get the same error when using both `20.1.51-beta` and `20.1.56-beta`.

Any solution?

**Comment by deepika134** [comment]
Hi Yahllil,

We tried to reproduce the reported issue, but the PDF is loaded properly without any exception. For your reference, we have prepared the output screen record and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/SCREEN~1-1838049908.zip

Regards,
Deepika Ravi

**Comment by KafkaWannaFly** [comment]
> I experience this as well. Run `flutter clean && flutter pub get` and still get the same error when using both `20.1.51-beta` and `20.1.56-beta`.
> 
> Any solution?

Recently, upgrading to Flutter `3.x.x` broke my app. I tried downgrade Flutter version to `2.10.5`. You may give it a shot.
