### ISSUE TITLE
Compile error 3.0.0

### ISSUE THREAD

**Issue by acx70** [syncfusion/flutter-widgets#739]
_Thank you for the update this morning, that has corrected the build issue._

_Originally posted by @michael-woolsey in https://github.com/syncfusion/flutter-widgets/issues/718#issuecomment-1128805643_

Sorry but there must have been a misunderstanding. I have never said that the problem was solved by the new release.
The problem is still there, even with syncfusion_flutter_gauges 20.1.55

What I did, was to modify the source code provided with the package syncfusion_flutter_gauges (linear_gauge_scope.dart).
But this it is obviously a temporary solution.

I think you should provide a solution and make a new release.

**Comment by AlexVegner** [comment]
syncfusion_flutter_gauges: ^20.1.56

**Comment by acx70** [comment]
> **5 hours ago** syncfusion_flutter_gauges: ^20.1.56

Sorry again, my bad
