### ISSUE TITLE
Do you remove all syncfusion packages of verions 20.1.52?

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#743]
I have a project which uses your products of version 20.1.52. Now it does not compiled because it looks like version are removed? My flutter is not upgraded yet to 3.0.0 so I cannot use version 20.1.56?

So what do I need to do?

P.S. Please return old version.

**Comment by agoldm** [comment]
Hi @bambinoua, I'm with the same problem. If you have closed the issue it means you found a solution?
