### ISSUE TITLE
Problem viewing pdf

### ISSUE THREAD

**Issue by ederluca** [syncfusion/flutter-widgets#746]
Good Morning

I ended up encountering a difficulty when viewing a pdf file, what is happening is the following:

When the pdf file is signed with a digital certificate, more precisely signed with an e-cpf certificate issued by the Federal Revenue, the information is not displayed in the pdf view.

So in the place where the e-cpf data would be displayed, they are blank in the file view, is there any parameter that I can enable so that this information is displayed?

**Comment by ederluca** [comment]
Below is how I am using the component.

SfPdfViewer.memory(
      widget.data,
      key: _pdfViewerKey,
      enableTextSelection: true,
      enableDoubleTapZooming: true,
      onTextSelectionChanged: (PdfTextSelectionChangedDetails details) {
        if (details.selectedText == null && _overlayEntry != null) {
          _overlayEntry!.remove();
          _overlayEntry = null;
        } else if (details.selectedText != null && _overlayEntry == null) {
          _showContextMenu(context, details);
        }
      },
      controller: _pdfViewerController,
    );

**Comment by deepika134** [comment]
Hi ederluca,

At present we do not have support for "Digital Signature” in SfPdfViewer . We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/26234/support-for-digital-signature

We have a workaround for preserving existing annotations in SfPdfViewer, which can be referred from the following KB link,
https://www.syncfusion.com/kb/13014/how-to-preserve-the-existing-annotation-in-flutter-pdf-viewer-sfpdfviewer

Regards,
Deepika Ravi
