### ISSUE TITLE
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?'

### ISSUE THREAD

**Issue by HYL-TX** [syncfusion/flutter-widgets#749]
![image](https://user-images.githubusercontent.com/87801335/169690669-473fa89a-8a02-4dba-8119-537e1a12d014.png)

: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../sdks/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../sdks/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback((_) {
                              ^^^^^^^^^^^^^^^^^^^^

I'm new to flutter, I am using flutter version 2.10.5.
I used syncfusion_flutter_calendar version 20.1.51 for my college project, and it worked. When I try to copy my code to another project, this happens. Is there any solution for this?

**Comment by iyar-avital** [comment]
https://github.com/syncfusion/flutter-widgets/issues/745 
same thing here

**Comment by safu2011** [comment]
same

**Comment by Indumathi1195R** [comment]
Hi,

We have removed the warnings in the Flutter calendar after upgrading the latest Flutter version. We have included the fix in our latest Weekly nuget package version 20.1.56. Kindly update to the latest version for resolving this warning. Please find the latest version from the following link.

**Latest version link:**
https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.
  
Regards,
Indumathi R

**Comment by agoldm** [comment]
Hi @Indumathi1195R  ,
Can you please fix that also in syncfusion_flutter_chart ?

**Comment by jugbeep** [comment]
I have the same issue here: 

starting at line 603:

```
  /// To load the image from the image url
  // ignore: avoid_void_async
  void _loadImage() async {
    await _renderImage().then((void value) {
      WidgetsBinding.instance
          .addPostFrameCallback((Duration duration) => markNeedsPaint()); <--- Error being thrown here
    });
  }
```

**Comment by OfficialVreesie** [comment]
I have the same issue. This is my flutter version:
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (2 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

When I add this line to my code: `import 'package:syncfusion_flutter_charts/charts.dart';`, I get those errors and my application gets a SIGKILL when trying to deploy. Removing the import statement removes the errors, but then I can't use this package!

Please help!!

**Comment by OfficialVreesie** [comment]
This issue has already an answer [here](https://github.com/syncfusion/flutter-widgets/issues/745#issuecomment-1141770906)
