### ISSUE TITLE
How can I add a colored shadow around the SFCartesianChart?

### ISSUE THREAD

**Issue by agoldm** [syncfusion/flutter-widgets#753]
![Screenshot 2022-05-23 111918](https://user-images.githubusercontent.com/57689948/169775601-47ee4f49-5243-4f42-8767-a6cd0fb93fb9.png)

As shown in the image above, I want the line to have light shaded color, above and beneath it. 
Any suggestions, please?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Agoldm,

Greetings from Syncfusion. Currently, we do not have support for adding shadow to the series, and we have already logged the feature request for this. It will be implemented and rolled out in any of our upcoming releases yet to come. We have also attached the feedback below, you can track the status of this feature here.

Feedback: [https://www.syncfusion.com/feedback/12926](https://www.syncfusion.com/feedback/12926/shadow-support-for-series-and-markers)

Regards,
Yuvaraj.

**Comment by agoldm** [comment]
@Yuvaraj-Gajaraj  Thanks for answering
