### ISSUE TITLE
Datalabel Builder not Rendering on Circular Charts for versions > 20.1.47

### ISSUE THREAD

**Issue by omonare-nybble** [syncfusion/flutter-widgets#756]
Hi,

I'm not sure what exactly has changed but the Radial Data Label doesn't render anything when using the  builder in later versions. It also removed the widget that is in the centre.

**Expected:**
<img width="389" alt="Screenshot 2022-05-23 at 19 24 28" src="https://user-images.githubusercontent.com/52454472/169874498-fc8305b3-60bb-42c1-a4b6-3a6ce2d54dcb.png">

**Actual Result**

<img width="389" alt="Screenshot 2022-05-23 at 18 32 04" src="https://user-images.githubusercontent.com/52454472/169866061-4fd4e8ef-c343-4632-84a9-56d5a75530f8.png">

Here is the source code snippet for both

<img width="757" alt="Screenshot 2022-05-23 at 18 31 47" src="https://user-images.githubusercontent.com/52454472/169867489-eb1afa3c-3b47-410e-ac47-57209a76aa81.png">

Please note that I am also running on Flutter 3.0.1

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @omonare-nybble,

The reported issue regarding the data label builder, not rendering has been fixed and rolled out in our patch release. To avoid this please upgrade the chart package to the latest version below. 

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.1.58+1 

Regards,
Yuvaraj.

**Comment by omonare-nybble** [comment]
Thanks, it's resolved - I'll close this issue now
