### ISSUE TITLE
Flutter 3 Tooltip colors behaving strangely

### ISSUE THREAD

**Issue by sukhcha-in** [syncfusion/flutter-widgets#759]
Issue is happening only on Android, working fine on iOS

Rendering properly on some values:
![20220524_201705](https://user-images.githubusercontent.com/26461527/170072506-d04a8452-25e6-4241-84ae-0d99c129d973.jpg)
Rendering issues:
![Screenshot_20220524-201629](https://user-images.githubusercontent.com/26461527/170072542-544122b3-a660-46d8-9dcd-a8c0a3d34b5e.jpg)

```
SfCartesianChart(
  margin: EdgeInsets.symmetric(vertical: 20),
  primaryXAxis: DateTimeAxis(),
  primaryYAxis: NumericAxis(
    labelFormat:
        '${controller.product.value.currency}{value}',
  ),
  onTrackballPositionChanging: (args) {
    String dateString = DateFormat.yMMMd().format(
        args.chartPointInfo.chartDataPoint!.x);
    args.chartPointInfo.label =
        '$dateString : ${controller.formatter.format(args.chartPointInfo.chartDataPoint!.y)}';
  },
  trackballBehavior: TrackballBehavior(
    enable: true,
    activationMode: ActivationMode.singleTap,
    tooltipSettings: InteractiveTooltip(
      enable: true,
    ),
  ),
  zoomPanBehavior: ZoomPanBehavior(
    enableDoubleTapZooming: true,
    enablePinching: true,
    zoomMode: ZoomMode.x,
    enableMouseWheelZooming: true,
  ),
  series: <ChartSeries<ChartModel, DateTime>>[
    StackedAreaSeries<ChartModel, DateTime>(
      gradient: LinearGradient(
        begin: Alignment.topCenter,
        end: Alignment.bottomCenter,
        colors: [
          Colors.deepPurple[200]!,
          Colors.deepPurple[600]!
        ],
      ),
      dataSource: controller.product.data,
      xValueMapper: (ChartModel sales, _) =>
          sales.date,
      yValueMapper: (ChartModel sales, _) =>
          sales.price,
      animationDuration: 0,
    ),
  ],
)
```

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @sukhcha-in,

We have checked your scenario with the provided code snippet and no issue getting reproduced, so we have attached the sample which is used for testing. If this is not your scenario, please try to reproduce the issue in the attached sample and revert us back.

Sample: [i381572.zip](https://github.com/syncfusion/flutter-widgets/files/8773911/i381572.zip)

Regards,
Yuvaraj.

**Comment by sukhcha-in** [comment]
Hi @Yuvaraj-Gajaraj 

I tried running this example on my Android device, it's having same issue. Below are the screenshots:

Issue in all points except just one point:
![Screenshot_20220527-214252](https://user-images.githubusercontent.com/26461527/170738515-a1f03669-717f-4dc2-bf46-ef557f301f43.jpg)
![Screenshot_20220527-214318](https://user-images.githubusercontent.com/26461527/170738606-54c5967f-affb-4f6c-9a22-69969993a780.jpg)

My device details:
Android version: 9
Device: Samsung Galaxy S8

Please let me know if you need any other information to debug this issue.

**Comment by sukhcha-in** [comment]
@Yuvaraj-Gajaraj It works fine on iOS.

**Comment by xiakexiaoyi** [comment]
![image](https://user-images.githubusercontent.com/24860541/174259280-0c8be9e2-5d09-4acb-8c5b-c83b218184d4.png)

**Comment by sukhcha-in** [comment]
Version `20.1.60+1` fixes the issue!
