### ISSUE TITLE
SPline chart drag overlay

### ISSUE THREAD

**Issue by roitnaidu23** [syncfusion/flutter-widgets#769]
Is this kind of selection possible with syncfusion_flutter_charts plugin. Thanks

https://user-images.githubusercontent.com/8014744/171044744-463b9177-938a-4b9a-b37e-87909b473164.mp4

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @roitnaidu23,

Greetings from Syncfusion. We are not clear on your exact requirement with this selection however, this type of selection is possible with the range selector widget. Here is the demo and user guide for your reference.

Demo: https://flutter.syncfusion.com/#/range-selector/default
UG: https://help.syncfusion.com/flutter/range-selector/getting-started

And using the range selector widget we have found the difference between the two dates, you find the sample below

https://www.syncfusion.com/kb/12844 

If your query is misunderstood at our end, kindly provide more information on your exact usage of such type selection.

Thanks,
Yuvaraj.

**Comment by roitnaidu23** [comment]
Thanks for the reply will try this out.
