### ISSUE TITLE
Handle long press in SFCartesianChart

### ISSUE THREAD

**Issue by iyar-avital** [syncfusion/flutter-widgets#771]
There is a way to handle long press in any place of the chart in SFCartesianChart?

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @iyar-avital,

We suggest you the [onPointLongPress](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onPointLongPress.html) callback in the series, with the help of this callback you can handle the long press gesture in the chart by long press on the data point. We have attached the code snippet and UG link for your reference.

Code snippet:
```dart
LineSeries<ChartData, int>(
  onPointLongPress: (args) {
                 
  },
 // Other required property
)
```

UG: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onpointlongpress 

Regards,
Yuvaraj.
