### ISSUE TITLE
Local 'currentPoint' has not been initialized.

### ISSUE THREAD

**Issue by superwebarmy** [syncfusion/flutter-widgets#777]
I'm using the latest SDK of Flutter (3.0) and sync fusion chart. I'm trying to use SfCircularChart but it is throwing up the following error

LateInitializationError: Local 'currentPoint' has not been initialized.

could you please look into that and fix it

**Comment by superwebarmy** [comment]
`  List<Participants> chartData = [
    Participants('SHAKTI', '1'),
    Participants('ASHU', '2'),
    Participants('HARRY', '3'),
    Participants('MANOJ', '4')
  ];
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfCircularChart(
        series: <PieSeries>[
          PieSeries<Participants, String>(
            dataSource: chartData,
            xValueMapper: (Participants data,_){
              data.name;
            },
            yValueMapper: (Participants data,_){
              data.nameID;
            },
          )
        ],
      ),
    );
  }
}


class Participants {
  Participants(this.name, this.nameID);
  String name;
  String nameID;
}`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @superwebarmy,

We have checked the SfCircularChart with the latest Flutter SDK and chart version, and we didn’t get any lateInitialization exception. We are not aware of what are the properties you used in your sample, so kindly revert us with the sample code or revert us by modifying the attached sample to reproduce the issue. That will be more helpful to us to provide a solution sooner.

Sample: 
[i384208.zip](https://github.com/syncfusion/flutter-widgets/files/8853721/i384208.zip)


Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @superwebarmy ,

You can reopen this ticket if you still face the issue in the provided sample.

Thanks,
Lavanya A.
