### ISSUE TITLE
Question - Tooltip / DataLabels - SfCartesianChart ?

### ISSUE THREAD

**Issue by ShubhamHande99** [syncfusion/flutter-widgets#778]
1. in spline chart how to show all toopltip when clicking on makers ?
2. how to show and hide datalables on when clicking on markers

**Comment by Marismathan** [comment]
Hi @ShubhamHande99 ,

Greetings from Syncfusion. Kindly find the responses for your queries below,

Query 1: in spline chart how to show all toopltip when clicking on markers ?

We guess that you want to show the tooltip at tapped marker point alone. This can be achieved by enabling the tooltipbehavior property in SfCartesianChart. We have shared the API documentation link of tooltipbehavior property and the link of the spline series sample which has the tooltip functionality below.

Sample link: https://flutter.syncfusion.com/#/cartesian-charts/chart-types/spline/default-spline-chart

API link: https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/tooltipBehavior.html

Query 2: how to show and hide datalables on when clicking on markers

We suggest you to use the [onDataLabelRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onDataLabelRender.html) callback to hide and show the data labels while tapping the marker. To get the tapped point’s index, you can use the [onPointTap](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/onPointTap.html) callback. By using this workaround, we have achieved your scenario and shared that sample here.

Sample: 
[spline_marker_hiding.zip](https://github.com/syncfusion/flutter-widgets/files/8872019/spline_marker_hiding.zip)


Kindly go through that and get back to us if you have further queries.

Thanks,
Marismathan G

**Comment by ShubhamHande99** [comment]
Thanks.
