### ISSUE TITLE
How to read data using the excel library?

### ISSUE THREAD

**Issue by sakshitporwal** [syncfusion/flutter-widgets#78]

**Comment by Sridhar-Sukumar** [comment]
Hi @sakshitporwal ,

Currently, we don't support to read data from Excel using Flutter XlsIO library. However, you can create Excel files using _"syncfusion_flutter_xlsio"_ library with the following features.

Create a simple Excel document

- Add text, number, and datetime values
- Add formulas
- Apply formatting
- Add images
- Add charts

There are some more features which are mentioned below, will be available in the next version (18.4), expected to be available by next week.
	

- Add hyperlinks to texts and images
- Protect workbooks and worksheets
- AutoFit rows and columns
- Insert or delete rows and columns

**NOTE:** Data from the created document can be added with the respective APIs. To know more about the _"syncfusion_flutter_xlsio"_ library please refer the following link.

https://pub.dev/packages/syncfusion_flutter_xlsio

Regards,
Sridhar

**Comment by justkawal** [comment]
@sakshitporwal 
You can read, write and update the data in excel files with the help of excel: https://pub.dev/packages/excel/versions/2.0.0-null-safety-2

Long Live 🔥pen Source

**Comment by cabbi** [comment]
I can't believe these words: _Currently, we don't support to read data from Excel_

**Comment by huongtran84** [comment]
> @sakshitporwal You can read, write and update the data in excel files with the help of excel: https://pub.dev/packages/excel/versions/2.0.0-null-safety-3
> 
> Long Live 🔥pen Source

It has not supported read image yet
