### ISSUE TITLE
CartesianChart - Is it possible to combine data set with different YAxis?

### ISSUE THREAD

**Issue by JarvanMo** [syncfusion/flutter-widgets#783]
I have three sets of data but one of them value is much more smaller than the other two. My requirement is to measure them with different YAxis, is this posibble? Thanks.

**Comment by FisherWL** [comment]
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#multiple-axes

**Comment by JarvanMo** [comment]
Thanks @FisherWL ! Closing this issue.
