### ISSUE TITLE
Get Axis-Mapped String in TrackballBehavior builder

### ISSUE THREAD

**Issue by seikosantana** [syncfusion/flutter-widgets#786]
Hi, I'm currently working on a timeseries chart and I found that I need the trackball to show the time and the values of 3 different axes.

The problem is it is all in different units in different axes, and i wish i could just get the value result mapped by the axes in builder. Is there a way to achieve that?

Wishing for something like the following to show trackballs
```dart
"${getMappedOutputFromThePointXAxis(details.point!.x)} - ${getMappedOutputFromThePointYAxis(details.point!.y)}"
```

Thanks in advance

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @seikosantana,

Greetings from Syncfusion. Yes, you can get the data [point](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/point.html) value of all the visible [series](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/series.html) respective to where the trackball is currently activated. Here you can get the point, series, [pointIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/pointIndex.html), and [seriesIndex](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/seriesIndex.html) values and for [groupAllPoints](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDisplayMode.html) mode, you will get this information from [groupingModeInfo](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballDetails/groupingModeInfo.html). Then you can customize the widget as per your requirement, we have created the sample and attached it below for your reference. We hope it will help you to achieve your requirement.

Sample: [i385519.zip](https://github.com/syncfusion/flutter-widgets/files/8891144/i385519.zip)

If you have any further queries, please get back to us.

Regards,
Yuvaraj.
