### ISSUE TITLE
Spline does not start from 0 value.

### ISSUE THREAD

**Issue by shahryar-cmyk** [syncfusion/flutter-widgets#787]
Hi there, I made spline using this package. Some of my graphs show from 0 to upward while other are showing from 28.5 Millions and above.
![WhatsApp Image 2022-06-09 at 7 55 36 PM](https://user-images.githubusercontent.com/58168504/173230014-eb03619f-752f-44f4-a4dd-24bb33d3c5de.jpeg)
![WhatsApp Image 2022-06-09 at 7 56 55 PM](https://user-images.githubusercontent.com/58168504/173230015-45cd1959-229f-4773-bc58-57ce08a604e4.jpeg)

What can do assure it always start from 0 and then above.

**Comment by FisherWL** [comment]
https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#auto-range-calculation

https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range

**Comment by shahryar-cmyk** [comment]
Thanks 
Resolved the issue for me.
