### ISSUE TITLE
CartesianChart - button on customized trackball tooltip not clickable

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#789]
```
    _trackballBehavior = TrackballBehavior(
      enable: true,
      activationMode: ActivationMode.longPress,
      hideDelay: 2500,
      tooltipSettings: const InteractiveTooltip(enable: true),
      builder: (BuildContext context, TrackballDetails trackballDetails) {
         ...
         ElevatedButton(
                    onPressed: () {
                      print('button is pressed');
                     }
```

the action of button-click is never triggered,
if change activationMode to `singleTap`, button-click will be distracted by another trackball activation.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Greetings from Syncfusion. In this case, while positioning the custom widget based on the trackball activated location, it needs to find the custom widget width and height to position it in the center. But finding the size of the custom widget is a tedious process, and it involves calling the setState() method, so it will affect the performance of the chart. As of now, can you please place the button anywhere in the chart to achieve your requirement.

Regards,
Yuvaraj.
