### ISSUE TITLE
App gets stuck on white splash screen and than crashes in beta channel after adding this package

### ISSUE THREAD

**Issue by WaheedHussainHaans** [syncfusion/flutter-widgets#79]
My app works fine if i dont add this package actually was working fine with this package too yesterday but suddenly it stops at splash screen and than crashes with the error
Connecting to VM Service at ws://127.0.0.1:51472/9BGNUUvo2aQ=/ws
Error handling 'checkPlatformOverride' custom request: ext.flutter.platformOverride: (-32000) Bad state: The client closed with pending request "ext.flutter.platformOverride".
my flutter doctor -v 
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-PK)
    • Flutter version 1.23.0-18.1.pre at /Users/muhammadfarooqiqbal/Developer/flutter
    • Framework revision 198df796aa (8 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/muhammadfarooqiqbal/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • CPH1701 (mobile) • 5bd6c456   • android-arm64  • Android 6.0.1 (API 23)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.67

• No issues found!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @WaheedHussainHaans,

Greetings from Syncfusion. We have analyzed your query and as we are not sure of which Syncfusion Flutter widget you are using in your Flutter application, we are not able to replicate the reported issue at our end. So, we kindly request you to share us with more information on the Synfusion Flutter widget you have used and also if possible revert us with a simple replication sample so that it will be helpful in providing the solutions sooner.

Regards,
Sriram Kiran
