### ISSUE TITLE
syncfusion_flutter_pdfviewer Linux version

### ISSUE THREAD

**Issue by EdoardoVignati** [syncfusion/flutter-widgets#791]
Will `syncfusion_flutter_pdfviewer` also have the support for Linux in future?

**Comment by deepika134** [comment]
Hi Edoardo Vignati,

Greetings from Syncfusion.

At present we do not have support to render in Linux platform. We do not have any immediate plans to implement this feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.
The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/31376/linux-support-for-flutter-sfpdfviewer 

Regards,
Deepika R

**Comment by EdoardoVignati** [comment]
Awesome. Thank you.
