### ISSUE TITLE
: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by harryandroiddev** [syncfusion/flutter-widgets#792]
just added the package and the from pub.dev  example file and had this error.

: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @harryandroiddev,

Greetings from Syncfusion. We suspect that you are using the old version of Flutter SDK, so please try to update the Flutter SDK package to the latest version and check. If you want to stay with the old version of Flutter SDK, then use the chart package version as mentioned below.

syncfusion_flutter_charts: 20.1.50
syncfusion_flutter_core: 20.1.50

If you have any further queries, please get back to us.
	
Regards,
Yuvaraj.
