### ISSUE TITLE
Question - RadialBar Chart & Label's position

### ISSUE THREAD

**Issue by dhassault** [syncfusion/flutter-widgets#794]
Hi,

Is it possible to set the label's position at the **end of the radial bar** and not at the beginning like it is by default? 
![flutter-radial-bar-chart-smart-labels](https://user-images.githubusercontent.com/7040582/173725541-4e0a858a-7076-4164-aa0b-1ef3581bf295.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @dhassault,

Currently, we do not have support for placing the data label at the end of the radial bar, and we do not have any immediate plan to implement this. If you have any other queries, kindly get back to us.

Regards,
Yuvaraj.
