### ISSUE TITLE
CartesianChart - MACD indicator makes each candlestick thinner

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#795]
![WX20220614-221727](https://user-images.githubusercontent.com/57275868/173741963-ed2dc799-29fe-4852-9b48-4d8441208cab.png)

if set `macdType: MacdType.line`, candlesticks get back to normal

[main.dart.zip](https://github.com/syncfusion/flutter-widgets/files/8905873/main.dart.zip)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Sorry for the inconvenience, we are checking the reported scenario. So, hereafter can you please follow the below github issue for further information.

https://github.com/syncfusion/flutter-widgets/issues/821

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @FisherWL ,

We are following up with this https://github.com/syncfusion/flutter-widgets/issues/821 ticket, hence closing this.

Thanks,
Lavanya A.
