### ISSUE TITLE
CartesianChart - technical indicator makes axis rangePadding & auto range calculation invalid on app launch

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#796]
![WX20220615-015539](https://user-images.githubusercontent.com/57275868/173786735-09f44aa6-cfc8-4a55-b2a7-cc945892a472.png)

when `visibleMinimum` and `ZoomPanBehavior` are set,

if indicators are included, Y-axis tends to include an unnecessary range on app launch (0-26 is unnecessary in the above example).  The unnecessary range will vanish once there's pan/pinch behavior --- even if you pan from R to L without changing the X-axis range.

if indicators are not included, there's no issue. (as the middle screenshot)

code example:
[main.dart.zip](https://github.com/syncfusion/flutter-widgets/files/8907704/main.dart.zip)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Sorry for the inconvenience, we are checking the reported scenario. So, hereafter can you please follow the below GitHub issue for further information.

https://github.com/syncfusion/flutter-widgets/issues/821

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @FisherWL ,

We are following up with this https://github.com/syncfusion/flutter-widgets/issues/821 ticket, hence closing this. 

Thanks,
Lavanya A.
