### ISSUE TITLE
CartesianSeries: gradient in legend icons

### ISSUE THREAD

**Issue by benjamingaudin** [syncfusion/flutter-widgets#797]
This is about gradient in legend icons.

packages/syncfusion_flutter_charts/lib/src/common/legend/legend.dart

on line 697

`        ? !seriesType.contains('line') &&
`

handles `area` and `splinearea` differently. In the first case the legend will be rendered with a color gradient, while not in the second case.

Moreover, it would be good to allow the user to control the rendering of the icon. In the following case, the gradient applied to the legend does not look good

bad (with `AreaSeries`):
<img width="185" alt="gradient1" src="https://user-images.githubusercontent.com/57812158/174124493-cc2c0c90-68ef-4c72-8c19-1f05ed0b6074.png">
good (with `SplineAreaSeries`):
<img width="127" alt="gradient2" src="https://user-images.githubusercontent.com/57812158/174124507-71c61e7e-e70f-4b7d-a095-9b3f8944a075.png">

**Comment by LavanyaGowtham2021** [comment]
Hi @benjamingaudin ,

You can reopen this ticket if you have any concern on the provided solution. 

Thanks,
Lavanya A.
