### ISSUE TITLE
Flutter SfDataGrid Draw Table Lines 

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#802]
can we draw table line like FoxPro Datatable .
![image](https://user-images.githubusercontent.com/62530396/175799446-c191c623-555b-4a8d-af04-325a13cb9da8.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

We are a little bit unclear about your query. We suspect that you are trying to customize the header and row cell borders. DataGrid. You can set the custom borders for both header and row cell by following these steps.

**Step 1:** Set the headerGridLinesVisibility to GridLinesVisibility.none.

**Step 2:** In the GridColumn,  you can set the custom borders for the header cells. Also, the colour and thickness of the grid lines can be changed by using the SfDataGridThemeData.gridLineColor and SfDataGridThemeData.gridLineStrokeWidth properties.

```dart
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:syncfusion_flutter_core/theme.dart'; 

 @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Flutter SfDataGrid'),
        ),
        body: SfDataGridTheme(
          data: SfDataGridThemeData(
              gridLineColor: Colors.black, gridLineStrokeWidth: 1.5),
          child: SfDataGrid(
            source: _employeeDataSource,
            headerGridLinesVisibility: GridLinesVisibility.none,
            gridLinesVisibility: GridLinesVisibility.both,
            columnWidthMode: ColumnWidthMode.fill,
            columns: getColumns,
          ),
        ));
  }

  List<GridColumn> get getColumns {
    return [
      GridColumn(
          columnName: 'id',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      right: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)),
                      bottom:
                          const BorderSide(width: 1.5, color: Colors.black))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text(
                'ID',
                overflow: TextOverflow.ellipsis,
              ))),
      GridColumn(
          columnName: 'name',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      right: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)),
                      bottom:
                          const BorderSide(width: 1.5, color: Colors.black))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text('Name', overflow: TextOverflow.ellipsis))),
      GridColumn(
          columnName: 'designation',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      right: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)),
                      bottom:
                          const BorderSide(width: 1.5, color: Colors.black))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child:
                  const Text('Designation', overflow: TextOverflow.ellipsis))),
      GridColumn(
          columnName: 'salary',
          label: Container(
              decoration: BoxDecoration(
                  border: Border(
                      right: BorderSide(
                          width: 1.0, color: Colors.grey.withOpacity(0.45)),
                      bottom:
                          const BorderSide(width: 1.5, color: Colors.black))),
              padding: const EdgeInsets.symmetric(horizontal: 16.0),
              alignment: Alignment.center,
              child: const Text('Salary', overflow: TextOverflow.ellipsis)))
    ];
  }

```



 
![image](https://user-images.githubusercontent.com/93904422/175946304-5357afe9-a322-46c0-abb3-10bbe7f1434c.png)


We have already provided examples in our UG and KB documentation. Please go through this,

UG Documentation: https://help.syncfusion.com/flutter/datagrid/styles#styling-grid-lines 

We hope this helps. In case we misunderstood your requirement, please provide more specific or clear use case details. It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar ,   

We're not entirely sure what you're looking for. Can you please confirm whether you want to create the empty rows for the theme when the DataGrid rows are empty? If yes, we have already provided an example in our KB documentation i.e., how to create an empty row in the DataGrid. Please go through this,

KB Link: https://www.syncfusion.com/kb/12937/how-to-create-empty-rows-in-flutter-datatable-sfdatagrid   

We hope this helps. In case we misunderstood your requirement, please provide more clear use case details. It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
i want to know how many empty rows i need to add.
can we calculate the available empty area of grid to add emptyRowsCount. suppose my grid height is 400. my _employees cover height 100. how to calculate required height 300.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

You can calculate the remaining height at the sample level itself. We have prepared a sample for that. In that sample, we have calculated the DataGrid height by calculating the sum of all the rows height (default as 49.0) and header height (default as 56.0). Now, you can get the remaining value by subtracting the DataGrid height value from the total height. Please check the following sample and code snippet.

``` dart

double totalHeight = 0;
double totalDatagridHeight = 0;
double remainingHeight = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter SfDataGrid'),
      ),
      body: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        totalHeight = constraints.maxHeight;
        totalDatagridHeight = (_employees.length * 49) + 56;
        remainingHeight = totalHeight - totalDatagridHeight;
        if (totalDatagridHeight < totalHeight) {
          _employeeDataSource.addEmptyRows(remainingHeight);
        }

        return SfDataGridTheme(
            data: SfDataGridThemeData(gridLineColor: Colors.black),
            child: SfDataGrid(
              source: _employeeDataSource,
              columns: getColumns,
              columnWidthMode: ColumnWidthMode.fill,
              gridLinesVisibility: GridLinesVisibility.both,
            ));
      }),
    );
  }
}
```

**In DataGridSource class:**

```dart
class EmployeeDataSource extends DataGridSource {

….
  addEmptyRows(double remainingHeight) {
    double count = (remainingHeight / 49).ceilToDouble();   //49 the default height of the single row
    for (int i = 0; i < count; i++) {
      dataGridRow.add(const DataGridRow(cells: [
        DataGridCell(columnName: 'id', value: null),
        DataGridCell(columnName: 'name', value: null),
        DataGridCell(columnName: 'designation', value: null),
        DataGridCell(columnName: 'salary', value: null),
      ]));
    }
  }
  @override
  DataGridRowAdapter? buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
          alignment: Alignment.center,
          child: Text(
            dataGridCell.value?.toString() ?? '',
          ));
    }).toList());
  }
}


```

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample867163168 

 
![image](https://user-images.githubusercontent.com/93904422/176907870-6705339c-e157-4798-aa25-b487f663d33a.png)

We hope this helps. Please let us know if you require any further assistance on this. 

Regards,
Tamilarasan
