### ISSUE TITLE
Label color

### ISSUE THREAD

**Issue by fclauss72** [syncfusion/flutter-widgets#803]
Hello, 
in flutter, is it possible to change labels color (dates, numbers interval, ...) under the sfslider?
Thank you.

Fixed
I add theme.dart

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

We suggest you use the [activeLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeLabelStyle.html) and [inactiveLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveLabelStyle.html) property in the [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html), it will help you to customize the label in the Slider, you can customize the label color, font size, and font-weight, etc., We have attached the code snippet below for your reference.

Code snippet:
```dart
SfSliderTheme(
  data: SfSliderThemeData(
    tooltipBackgroundColor: Colors.black,
    activeLabelStyle: const TextStyle(
        color: Colors.red, fontSize: 12, fontStyle: FontStyle.italic),
    inactiveLabelStyle: TextStyle(
        color: Colors.red[200],
        fontSize: 12,
        fontStyle: FontStyle.italic),
  ),
  child: SfSlider(
  // Other required properties.
   ))
```

UG: https://help.syncfusion.com/flutter/slider/labels-and-divider#label-style 

Regards,
Yuvaraj.

**Comment by rajrushilmakkar** [comment]
> Hi @fclauss72,
> 
> Greetings from Syncfusion. We suggest you use the [activeLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeLabelStyle.html) and [inactiveLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveLabelStyle.html) property in the [SfSliderThemeData](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData-class.html), it will help you to customize the label in the Slider, you can customize the label color, font size, and font-weight, etc., We have attached the code snippet below for your reference.
> 
> Code snippet:
> 
> ```dart
> SfSliderTheme(
>   data: SfSliderThemeData(
>     tooltipBackgroundColor: Colors.black,
>     activeLabelStyle: const TextStyle(
>         color: Colors.red, fontSize: 12, fontStyle: FontStyle.italic),
>     inactiveLabelStyle: TextStyle(
>         color: Colors.red[200],
>         fontSize: 12,
>         fontStyle: FontStyle.italic),
>   ),
>   child: SfSlider(
>   // Other required properties.
>    ))
> ```
> 
> UG: https://help.syncfusion.com/flutter/slider/labels-and-divider#label-style
> 
> Regards, Yuvaraj.

Hi @Yuvaraj-Gajaraj , what if I don't want to change it based on active or inactive but want different colors for different labels irrespective of current value but based on the value of where they are located on the slider
for eg.  something like this
<img width="671" alt="Screenshot 2023-12-14 at 5 23 11 PM" src="https://github.com/syncfusion/flutter-widgets/assets/56961633/5a914fe7-68b4-4662-b24a-2009124f2aa8">

**Comment by jonasPfeifhofer** [comment]
I agree with @rajrushilmakkar suggestion

**Comment by Mugunthan-Ramalingam** [comment]
Hi @rajrushilmakkar,
 
We currently do not have support for the individual label customization in [SfSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider-class.html). However, we have already logged a feature request for this in our feedback portal. We will prioritize features for each release based on demand and priority, so this feature may be available in any of our upcoming releases. We will notify you here once the release has been rolled out, and we appreciate your patience in the meantime. You can also track the status of the feature using the feedback link provided below.
 
 
FR link: [Provide the option to customize the label style individually in Flutter | Feedback Portal](https://www.syncfusion.com/feedback/49315/provide-the-option-to-customize-the-label-style-individually)

 
Regards,
Mugunthan.
