### ISSUE TITLE
Chart widgets that use schedular binding could be null error

### ISSUE THREAD

**Issue by Tritonfc** [syncfusion/flutter-widgets#806]
I get  Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null. for almost all bases especially on new flutter versions

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

We suspect that you have an old version of the chart package or an old version of Flutter SDK, so we suggest you have a flutter package above version 20.1.50 for the latest Flutter SDK version. If you have a Flutter SDK version below 3, then have a chart package version as 20.1.50 and below. It will help you to resolve your issue.

If you have any further queries, please get back to us.

Regards,
Yuvaraj.

**Comment by LavanyaGowtham2021** [comment]
Hi @Tritonfc ,

You can reopen this ticket if you have any concern on the provided solution. 

Thanks,
Lavanya A.
