### ISSUE TITLE
extractText in some pdf files can not get the text correctly

### ISSUE THREAD

**Issue by luomo-pro** [syncfusion/flutter-widgets#810]
I use PdfTextExtractor extractText to obtain the text of the pdf file, most of the pdf are working properly.
But some pdf to get the text is garbled, completely unreadable.
I tried to use edge browser and other third-party software to open the pdf, you can get the correct text, so the pdf file itself should not be a problem.
This is the pdf file with the problem, its text is in Chinese:
[test.pdf](https://github.com/syncfusion/flutter-widgets/files/9039416/test.pdf)

This problem exists on both android and iOS.
I use:
syncfusion_flutter_pdf: ^20.2.36
Flutter Channel stable, 3.0.1

**Comment by luomo-pro** [comment]
hi，@deepika134
Can you take a look at this problem? I found a lot of Chinese content pdf have this problem, for example, today I found this again also has the same problem:
[2.pdf](https://github.com/syncfusion/flutter-widgets/files/9607072/2.pdf)

**Comment by irfanajaffer** [comment]
Currently, we do not have support to extract text from font encoding "UniGB-UCS2-H" and "GBK-EUC-H". We have logged the feature for “Extract text from font encoding "UniGB-UCS2-H" and "GBK-EUC-H"” and added it to our feature request list. We will implement this feature in any of our upcoming releases.

 

You can track the feature status using the feedback, https://www.syncfusion.com/feedback/40275/text-extraction-for-text-in-different-encoding

**Comment by luomo-pro** [comment]
Why was this issue closed?
I checked the latest now
syncfusion_flutter_pdf: 21.2.4
I found that the problem still exists and has not been solved yet.
So, why is this issue closed?

**Comment by Muhammad-Arbad** [comment]
This Issue still here in syncfusion_flutter_pdf 25.1.37 latest version on 27 March 2024. 
Any suggestion or solution is highly appreciated.
