### ISSUE TITLE
syncfusion_flutter_sliders: ^20.1.56

### ISSUE THREAD

**Issue by anchaoLu** [syncfusion/flutter-widgets#815]
can't slide on Android devices

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @anchaoLu,

Greetings from Syncfusion. We have checked the slider control in version 20.1.56 but dragging is working properly and no issue gets reproduced at our end. We have attached the sample below which is used in the testing phase, if still facing an issue please try to reproduce the reported issue and revert us back.

Sample: [i390612.zip](https://github.com/syncfusion/flutter-widgets/files/9065806/i390612.zip) 

Regards,
Yuvaraj
