### ISSUE TITLE
LateInitializationError: Local 'currentPoint' has not been initialized.

### ISSUE THREAD

**Issue by pksa07** [syncfusion/flutter-widgets#816]
I am using syncfusion_flutter_charts: ^19.4.56 with flutter 2.2.2 version. I am getting this error while loading SfCircularChart graph after load it shows perfectly. Do you have any solution to handle this error as I can't upgrade flutter version in my project.

Error:
he relevant error-causing widget was: 
  SfCircularChart file:///Users/FlutterProjects/app-flutter/lib/src/ui/dashboard/widget/dashboard_graph.dart:38:16
When the exception was thrown, this was the stack: 
#0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:208:5)
#1      getCircularPoint (package:syncfusion_flutter_charts/src/circular_chart/renderer/chart_point.dart:228:3)
#2      CircularSeriesBase.findVisibleSeries (package:syncfusion_flutter_charts/src/circular_chart/base/series_base.dart:71:26)
#3      SfCircularChartState._renderChartElements.<anonymous closure> (package:syncfusion_flutter_charts/src/circular_chart/base/circular_base.dart:950:38)
#4      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:121:31)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @pksa07,

Greetings from Syncfusion. We have analyzed the reported issue in the chart package version 19.4.56 with the circular series, but no issue gets reproduced at our end. We have also checked with the latest chart package version and ensured. So, we have attached the sample below used for the testing, and if you are still facing the same issue, please try to reproduce the reported issue in the attached sample and revert us. It will be more helpful to us to provide a solution sooner.

Sample: [i391094.zip](https://github.com/syncfusion/flutter-widgets/files/9086525/i391094.zip)

Regards,
Yuvaraj.

**Comment by pksa07** [comment]
Thank you for your response. Got the issue in my code and resolved it.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @pksa07,

Most welcome. Kindly get back to us if you have further queries. We are always happy to assist you.

Regards,
Sriram Kiran
