### ISSUE TITLE
Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' 

### ISSUE THREAD

**Issue by ixinrun** [syncfusion/flutter-widgets#818]
Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' 

Null safety Error!

path: pdfviewer.dart
lineNum: 959

`WidgetsBinding.instance.addObserver(this);`

you can add '?' dispose it.

**Comment by mvn-hoangho2-dn** [comment]
Hello, 
Also has same issue
```
Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/pointers/marker_pointer_renderer.dart:608
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.10.5/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
          .addPostFrameCallback((Duration duration) => markNeedsPaint());
```
Please help to fix it. Thank you.

**Comment by hoanghn418** [comment]
Hello,

Also has same issue.

```
Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
../…/pointers/marker_pointer_renderer.dart:608
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../fvm/versions/2.10.5/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
Try calling using ?. instead.
          .addPostFrameCallback((Duration duration) => markNeedsPaint());
```

Please help to fix it. Thank you.

**Comment by deepika134** [comment]
Hi XinRun,

kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.

Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk

Regards,
Deepika R

**Comment by vertcli** [comment]
Have this same issue running on Flutter 2.10.5. Which version of Flutter should I use to avoid this issue? Otherwise, can you please include @ixinrun suggestion please?

**Comment by deepika134** [comment]
To resolve this issue, upgrade the Flutter SDK to the latest version and also upgrade the latest Syncfusion package version [21.1.41]. Please try this and let us know if the issue is resolved or not.
PdfViewer package: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/21.1.41
