### ISSUE TITLE
Invalid position error

### ISSUE THREAD

**Issue by ali321-hub** [syncfusion/flutter-widgets#819]
Hello

Invalid position error 
when ı use this pdf: https://drive.google.com/file/d/1GLpKDFoUj-ht1BU8vTe1tPeNSrokbRwm/view?usp=sharing
I get this error and then I noticed that I didn't get an error when I deleted the "()" parentheses in the title of the book. what is the reason of this?

stack:
PdfStreamReader.position= (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\stream_reader.dart:22)
PdfReader.position= (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\pdf_reader.dart:55)
CrossTable._initialize (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\cross_table.dart:119)
new CrossTable (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\cross_table.dart:26)
PdfCrossTable._initializeCrossTable (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\pdf_cross_table.dart:177)
new PdfCrossTable (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\io\pdf_cross_table.dart:41)
PdfDocument._initialize (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\pdf_document\pdf_document.dart:757)
new PdfDocument (c:\Users\Hp\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\syncfusion_flutter_pdf-20.2.36\lib\src\pdf\implementation\pdf_document\pdf_document.dart:78)
GetFilesState.dosyaninKopyasiniOLusturYeniPathaEkle.<anonymous closure> (f:\ornekler\speed_eyes\lib\pdfcontrol\pdfcontrol.dart:102)
<asynchronous gap> (Bilinmeyen Kaynak:0)
GetFilesState.dosyaninKopyasiniOLusturYeniPathaEkle (f:\ornekler\speed_eyes\lib\pdfcontrol\pdfcontrol.dart:99)
<asynchronous gap> (Bilinmeyen Kaynak:0)
GetFilesState.openFileExplorer (f:\ornekler\speed_eyes\lib\pdfcontrol\pdfcontrol.dart:72)
<asynchronous gap> (Bilinmeyen Kaynak:0)
_AfterAntrenmanState.eklekitap (f:\ornekler\speed_eyes\lib\scrreen\reader.dart:316)
<asynchronous gap> (Bilinmeyen Kaynak:0)

**Comment by GowthamrajKumar25** [comment]
Hi ali321-hub,
 
We have checked the reported issue with a provided document on our end, but it is loaded properly. We can open an existing PDF document by using the PdfDocument class. The following example shows how to load an existing document from the list of bytes.
 
` PdfDocument document = PdfDocument(
      inputBytes: File(
              r"C:\Users\User\Downloads\21. Yüzyil için 21 Ders ( PDFDrive.com ).pdf")
          .readAsBytesSync());
  //Saves the document
  File('E://Flutter/LoadOutput.pdf').writeAsBytes(document.save()); 
//Disposes the document
  document.dispose();
` 
 
Please refer to the below documentation link,
UG: https://help.syncfusion.com/flutter/pdf/loading-and-saving-document#opening-an-existing-pdf-document

Please let us know if you need any further assistance in this.

Regards,
Gowthamraj K

**Comment by ali321-hub** [comment]
Hello ,


i keep getting the same error.
MY code:
 
` final PdfDocument document =
            PdfDocument  (inputBytes: pdfFile.readAsBytesSync());`

**Comment by irfanajaffer** [comment]
We have created a simple sample to load the reported PDF file. Kindly use the following link to download the sample, https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_demo_sample134681685



Note: Move the reported file to location “pdf_demo_sample\assets\pdf” before running the sample.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
