### ISSUE TITLE
BYDAY not allowing negative values

### ISSUE THREAD

**Issue by pauldemarco** [syncfusion/flutter-widgets#82]
Consider the following RRULE:
```
Monthly on the second to last Monday of the month:

  RRULE:FREQ=MONTHLY;BYDAY=-2MO
```

I seem to be getting errors for all rules that contain a negative BYDAY.

Any suggestions?

**Comment by pauldemarco** [comment]
Upon further testing, positive BYDAY is also throwing errors:
```
Monthly on the fourth Sunday:
FREQ=MONTHLY;BYDAY=+4SU
```

**Comment by Indumathi1195R** [comment]
Hi @pauldemarco,


As of now, we don’t have support for negative values support. We have logged the feature request for “**Provide negative values support for BYSETPOS property of recurrence rule in the Flutter event calendar**”. We will implement this feature in any of our upcoming releases and let you know once the release rolled out. We appreciate your patience until then.

You can track the current status of this report by the following feedback link,

**Feedback link:** https://www.syncfusion.com/feedback/20548/provide-negative-values-support-for-bysetpos-property-of-recurrence-rule-in-the

Regards,
Indumathi R

**Comment by pauldemarco** [comment]
@JayavigneshwaranG was this added somewhere?
