### ISSUE TITLE
#795 and #796 still exist on latest release (20.2.38)

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#821]
Hi Syncfusion team,

#795 and #796 have been ignored in the past month,
meantime all other questions got responses and answers.
It makes me feel excluded from the community and kinda hurts my feeling.

I tried to explain the issue as clearly as I can by providing scenarios, screenshots, and sample codes.
Is it not a preferred way to ask a question to your team? 
If so, could you articulate the correct way to submit an issue? I can rephrase the descriptions, thanks.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @FisherWL,

Sorry for the inconvenience, our developer team is checking the behavior of the reported issue. We will check and update you in two business days on 20th July 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by FisherWL** [comment]
Thank you @SriramKiranSenthilkumar for the response.

For https://github.com/syncfusion/flutter-widgets/issues/796 
I'm afraid anchoring range to all points is not the best solution in some cases,

take my project for example (as screenshots below):
the y-axis has a wide range of variation (about 0-1500 over 15 years of data),
if `anchorRangeToVisiblePoints: false` and a user chooses to view a shorter period of time -- e.g. 1 year of data,
the screenshot on the right shows how the data is compressed and distorted, it's basically unreadable.

![Screen Shot 2022-07-24 at 5 25 17 PM](https://user-images.githubusercontent.com/57275868/180672413-75388c0c-a3f3-45dc-b5a5-63154c79d3d3.png)

**Comment by LavanyaGowtham2021** [comment]
Hi @FisherWL ,

For GitHub issue https://github.com/syncfusion/flutter-widgets/issues/796, we have checked with the development team, and they confirmed this is an issue. So, we have logged a bug report for the issue “When panning the X axis with zoomMode as ZoomMode.x, the Y axis range changed” and you can track this issue using the following feedback. 

https://www.syncfusion.com/feedback/37039   

We will include this fix in our Volume 3 main release, which is scheduled for the end of September. We will let you know once the release gets rolled out. We appreciate your patience until then.


Thanks,
Lavanya A.

**Comment by FisherWL** [comment]
Thanks @LavanyaGowtham2021 for the update on https://github.com/syncfusion/flutter-widgets/issues/796, I really appreciate it.

for https://github.com/syncfusion/flutter-widgets/issues/795, I don't think v [20.2.43] has fixed the issue.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @FisherWL,

For GitHub issue #795, the reported issue regarding candle series width decreases when having a MACD indicator has been fixed. But we are facing some automation breaks and due to these we can't be able to move this into our weekly patch release, we will give priority to this and include it in our Volume 3 main release, which is scheduled for the end of September. We will let you know once the release gets rolled out. We appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
> Hi @FisherWL,
> 
> For GitHub issue #795, the reported issue regarding candle series width decreases when having a MACD indicator has been fixed. But we are facing some automation breaks and due to these we can't be able to move this into our weekly patch release, we will give priority to this and include it in our Volume 3 main release, which is scheduled for the end of September. We will let you know once the release gets rolled out. We appreciate your patience until then.
> 
> Regards, Sriram Kiran

Hi @FisherWL,

We are glad to announce that our Essential Studio 2022 Volume 3 release v20.3.0.47 is rolled out and is available for download under the following link.
[Essential Studio 2022 Volume 3 Main Release v20.3.0.47 is available for download | Announcements Forums | Syncfusion](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F177858%2Fessential-studio-2022-volume-3-main-release-v20-3-0-47-is-available-for-download&data=05%7C01%7Csriramkiran.senthilkumar%40syncfusion.com%7C2627996b27254eb5903008daa2123ab5%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638000496437916313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ypQVpWUZ%2Ba%2F%2FAwAYgHqJpjpSa3IfmSk02DWALhUxuc%3D&reserved=0)

The reported issue regarding the “Candle series width decreases when having a MACD indicator” is now fixed and rolled out in this release. So, kindly please upgrade the chart widget package version to the latest version below to overcome the issue.
https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.47

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
> Hi @FisherWL ,
> 
> For GitHub issue #796, we have checked with the development team, and they confirmed this is an issue. So, we have logged a bug report for the issue “When panning the X axis with zoomMode as ZoomMode.x, the Y axis range changed” and you can track this issue using the following feedback.
> 
> https://www.syncfusion.com/feedback/37039
> 
> We will include this fix in our Volume 3 main release, which is scheduled for the end of September. We will let you know once the release gets rolled out. We appreciate your patience until then.
> 
> Thanks, Lavanya A.

Hi @FisherWL,

The reported issue regarding the “When panning the X axis with zoomMode as ZoomMode.x, the Y axis range changed” is now fixed and rolled out in this release. So, kindly please upgrade the chart widget package version to the latest version below to overcome the issue.
https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.47

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sriram Kiran

**Comment by FisherWL** [comment]
Thank you @SriramKiranSenthilkumar 
It works like a charm!
