### ISSUE TITLE
[syncfusion_flutter_tooltip] Wrong number displayed in LogarithmicAxis

### ISSUE THREAD

**Issue by benjamingaudin** [syncfusion/flutter-widgets#824]
The data shown in the tooltip with LogarithmicAxis is wrong. Can I please have an update on #770, it has been two months.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @benjamingaudin,

We have checked and ensured the reported issue gets reproduced at our end. We will include the fix in an upcoming weekly patch release. We will update you know once the issue got fixed and rollout. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @benjamingaudin,

The reported issue regarding the wrong value displayed in the tooltip while using the logarithmic axis has been fixed and included in our Volume 2 SP release. It will be expected to be rolled out on 8th August 2022. We will update you once the release gets rolled out. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by benjamingaudin** [comment]
Thank you

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @benjamingaudin,

We are glad to announce that our Essential Studio 2022 Volume 2 service pack Release V20.2.0.43 is rolled out and the reported issue regarding the wrong value displayed in the tooltip when having the logarithmic axis in the chart is included and available for download under the following link.

[https://forumassist.syncfusion.com/176701](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforumassist.syncfusion.com%2F176701&data=05%7C01%7Cyuvaraj.gajaraj%40syncfusion.com%7Ce8c2e035f65544a492d908da792deabf%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637955535367436034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXVqPUte3ZNTq16ZhLiiGAhmygBV479i0E2RuY0xsqM%3D&reserved=0)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you require any further assistance.

Regards,
Yuvaraj.
