### ISSUE TITLE
[syncfusion_flutter_datagrid] handlePageChange infinity be call

### ISSUE THREAD

**Issue by vecharm** [syncfusion/flutter-widgets#825]
version:  syncfusion_flutter_datagrid: ^20.2.38

When I use sfdatapager, handlepagechange is always called. It doesn't appear every time, but it happens more frequently. If you call the server API here, it will be dangerous. It will always request the server.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/25290829/179965124-51901aa6-2cfe-4e70-9bde-f9719c34224b.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/25290829/179965354-76f68dc0-4727-42a0-b9d8-288d910600d1.png">

<img width="790" alt="image" src="https://user-images.githubusercontent.com/25290829/179967590-98e448d4-a349-4010-980d-f7f617b8bd1c.png">

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 13.1)
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2021.3.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @vecharm,

Based on the provided information, we are unable to reproduce the reported issue. It’s working fine on our end. We have tested the following sample with the below configuration. 

**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1621780200 

- **DataGrid Version: 20.2.38 (as you mentioned).**

- **Flutter Channel: Stable** 

- **Flutter Version: 3.0.5**

- **Platform:  Windows and Windows Web browser** 

Please check the above sample. If you are still facing the same issue, please provide the following details to check further.

- **Provide a sample that is reproducible or modify the above sample as reproducible.**

- **Provide the issue reproducing steps.**  

- **The platform (Web/Windows/Android/macOS/iOS) on which you faced the issue.**

It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by vecharm** [comment]
My project is running on IOS. I find it normal to use local data, but it will appear when I use the network to obtain data
