### ISSUE TITLE
Null Safety Not Supported

### ISSUE THREAD

**Issue by RjMakwana2660** [syncfusion/flutter-widgets#826]
Here is log attached

D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart:959:7: Warning: The class 'WidgetInspectorService' cannot be null.
Try replacing '?.' with '.'
      WidgetInspectorService?.instance!.performReassemble();
      ^^^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart:959:31: Warning: Operand of null-aware operation '!' has type 'WidgetInspectorService' which excludes null.
 - 'WidgetInspectorService' is from 'package:flutter/src/widgets/widget_inspector.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/widget_inspector.dart').
      WidgetInspectorService?.instance!.performReassemble();
                              ^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:959:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1046:16: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    imageCache.clear();
               ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1066:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1096:16: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    imageCache.clear();
               ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1918:51: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
                          WidgetsBinding.instance.window.viewInsets.bottom !=
                                                  ^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1924:57: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
                                WidgetsBinding.instance.window.viewInsets,
                                                        ^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:1925:57: Error: Property 'window' cannot be accessed on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try accessing using ?. instead.
                                WidgetsBinding.instance.window.devicePixelRatio)
                                                        ^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:2736:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:2751:37: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
            WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                                    ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:2775:35: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
          WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                                  ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:2873:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:2888:16: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
              .addPostFrameCallback((Duration timeStamp) async {
               ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:3404:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/pdfviewer.dart:3414:33: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
        WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                                ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/common/pdfviewer_plugin.dart:106:16: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    imageCache.clear();
               ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/common/pdfviewer_plugin.dart:153:16: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    imageCache.clear();
               ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:204:30: Error: Property 'imageCache' cannot be accessed on 'PaintingBinding?' because it is potentially null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/binding.dart').
Try accessing using ?. instead.
    PaintingBinding.instance.imageCache.clear();
                             ^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:204:41: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    PaintingBinding.instance.imageCache.clear();
                                        ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:205:30: Error: Property 'imageCache' cannot be accessed on 'PaintingBinding?' because it is potentially null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/binding.dart').
Try accessing using ?. instead.
    PaintingBinding.instance.imageCache.clearLiveImages();
                             ^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:205:41: Error: Method 'clearLiveImages' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
    PaintingBinding.instance.imageCache.clearLiveImages();
                                        ^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:213:32: Error: Property 'imageCache' cannot be accessed on 'PaintingBinding?' because it is potentially null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/binding.dart').
Try accessing using ?. instead.
      PaintingBinding.instance.imageCache.clear();
                               ^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:213:43: Error: Method 'clear' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
      PaintingBinding.instance.imageCache.clear();
                                          ^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:214:32: Error: Property 'imageCache' cannot be accessed on 'PaintingBinding?' because it is potentially null.
 - 'PaintingBinding' is from 'package:flutter/src/painting/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/binding.dart').
Try accessing using ?. instead.
      PaintingBinding.instance.imageCache.clearLiveImages();
                               ^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_page_view.dart:214:43: Error: Method 'clearLiveImages' cannot be called on 'ImageCache?' because it is potentially null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/painting/image_cache.dart').
Try calling using ?. instead.
      PaintingBinding.instance.imageCache.clearLiveImages();
                                          ^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdf_scrollable.dart:453:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/pdfviewer_canvas.dart:1211:31: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
      WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                              ^^^^^^^^^^^^^^^^^^^^
/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.2.39-beta/lib/src/control/scroll_head_overlay.dart:290:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/Flutter%20Development/flutter_windows_2.10.5-stable/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((Duration timeStamp) {
                            ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Flutter Development\flutter_windows_2.10.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\Flutter Development\flutter_windows_2.10.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by deepika134** [comment]
Hi RjMakwana2660,

We have checked the reported issue, but the PDF is loaded properly without any exception in windows platform. Kindly upgrade to the latest version of Flutter SDK and Syncfusion Flutter PDFViewer to get the issue resolved. Please try this and let us know if the issue is resolved or not.

Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk 

Syncfusion Flutter PDFViewer link for the latest version: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.39-beta  

Regards,
Deepika Ravi
