### ISSUE TITLE
[syncfusion_flutter_xlsio] Image with hyperlink bug on production

### ISSUE THREAD

**Issue by Macacoazul01** [syncfusion/flutter-widgets#829]
package version:
`syncfusion_flutter_xlsio: 20.2.36-beta`

I've followed your sample of how to add an image with hyperlink to another worksheet and everything is ok when running on debug:

![image](https://user-images.githubusercontent.com/57464965/180900702-ddd29d4e-145d-4806-b6b8-c9cb0fb662dd.png)

But after publishing my web app on firebase hosting and trying to execute the same code to generate the same excel sheet, here's the result for the images:

![image](https://user-images.githubusercontent.com/57464965/180900663-75d11938-9324-4252-902b-e83c4996e987.png)

even with the broken visualization, the hyperlink still works.

sample of the part that add the images:

```
await _definirImagem(sheet, 2, 2, 'eixos.png', 'Eixos!B1', 'Eixos');

Future<void> _definirImagem(
  Worksheet sheet,
  int linha,
  int coluna,
  String foto,
  String destino,
  String identificacao, {
  int altura = 30,
  int largura = 100,
  bool link = false,
}) async {
  final Picture imagem =
      sheet.pictures.addStream(linha, coluna, await _readImageData(foto));
  imagem.height = altura;
  imagem.width = largura;
  sheet.hyperlinks.addImage(
      imagem,
      link ? HyperlinkType.url : HyperlinkType.workbook,
      destino,
      identificacao);
}

Future<List<int>> _readImageData(String name) async {
  final ByteData data = await rootBundle.load('images/$name');
  return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
}

```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [versao 10.0.22000.832], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.69.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

**Comment by SivakumarRamya** [comment]
Hi

Greetings from Syncfusion.

We are unable to reproduce the issue at our end. We have shared a sample that we tried at our end, and it can be downloaded from the below link.

Sample link -  https://www.syncfusion.com/downloads/support/directtrac/general/ze/flutter_application520936674

We request you share the issue reproducing sample or modify this sample to reproduce the issue and share us along with the issue reproducing input documents. It will help us to proceed further and provide you with a solution at the earliest.

Regards,
Ramya.

**Comment by Macacoazul01** [comment]
Hi @SivakumarRamya i'm trying to replicate the error with your code but it's still something that don't happens everythime like on my app.
Gonna send the final code as soon as possible.

**Comment by SivakumarRamya** [comment]
Hi

As mentioned earlier, we are unable to reproduce the issue on our end. Kindly share a sample illustrating the issue or else modify the sample which we provided in the last update and reproduce the issue which would help us to proceed further.

Regards,
Ramya

**Comment by Macacoazul01** [comment]
I'm gonna close this issue and reopen it if i find a way to reproduce the bug
