### ISSUE TITLE
Need to always show tooltip

### ISSUE THREAD

**Issue by Alex0084** [syncfusion/flutter-widgets#83]
Hello,
  We need to show price above tooltip, Here is the image

![image](https://user-images.githubusercontent.com/31046727/101986255-01af2480-3cb3-11eb-93d2-d8ae9d6e172b.png)

**Comment by LakshmiRadhaKrishnan** [comment]
Hi Alex, 
 
Greetings from Syncfusion. 
 
We don’t have direct support to achieve your requirement. However, we have achieved by setting startThumbIcon and endThumbIcon properties with translation for them along with overriding the paint method of SfThumbShape.
 
If you want to customize the padding between the thumb and startThumbIcon/endThumbIcon, thumb size, and the startThumbIcon/endThumbIcon widgets size, please update the below respective fields.  
   
// Padding between the thumb and the startThumbIcon/endThumbIcon.
double _bottomPadding = 15; 
 
// You can change the thumb radius by changing this field.
double _thumbRadius = 10; 
 
// The width of the startThumbIcon/endThumbIcon widgets.
double _iconWidth = 20; 

![Screenshot 2020-12-15 at 4 41 56 PM](https://user-images.githubusercontent.com/47354659/102220266-98bfea80-3f06-11eb-9ec6-fb64e288ec54.png)

**Code snippet:**

`class _RangeSliderPageState extends State<RangeSliderPage> {
  SfRangeValues _values = SfRangeValues(0.0, 200.0);
  // The width of the startThumbIcon/endThumbIcon widgets.
  double _iconWidth = 20;

  // Padding between the thumb and startThumbIcon/endThumbIcon.
  double _bottomPadding = 15;

  // You can change the thumb radius by changing this field.
  double _thumbRadius = 10;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SfRangeSliderTheme(
        data: SfRangeSliderThemeData(
          thumbRadius: _iconWidth,
          thumbColor: Colors.red,
          activeTrackHeight: 2,
          inactiveTrackHeight: 2,
          activeTrackColor: Colors.red,
          inactiveTrackColor: Colors.red[200],
        ),
        child: SfRangeSlider(
          min: 0.0,
          max: 500.0,
          values: _values,
          onChanged: (SfRangeValues newValues) {
            setState(() {
              _values = newValues;
            });
          },
          thumbShape: _CustomThumbShape(_thumbRadius),
          startThumbIcon: _getThumbIcon(_values.start),
          endThumbIcon: _getThumbIcon(_values.end),
        ),
      ),
    );
  }

  Widget _getThumbIcon(double value) {
    return Transform.translate(
      offset: Offset(0, -(_thumbRadius + _bottomPadding)),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(value.toStringAsFixed(0)),
              Text('\$'),
            ],
          ),
          Center(child: Icon(Icons.keyboard_arrow_down, color: Colors.black)),
        ],
      ),
    );
  }
}

class _CustomThumbShape extends SfThumbShape {
  _CustomThumbShape(this.radius);

  final double radius;
  void paint(PaintingContext context, Offset center,
      {RenderBox parentBox,
      RenderBox child,
      SfSliderThemeData themeData,
      SfRangeValues currentValues,
      dynamic currentValue,
      Paint paint,
      Animation<double> enableAnimation,
      TextDirection textDirection,
      SfThumb thumb}) {
    Paint paint = Paint();
    paint.isAntiAlias = true;
    paint.color = ColorTween(
            begin: themeData.disabledThumbColor, end: themeData.thumbColor)
        .evaluate(enableAnimation);
    context.canvas.drawCircle(center, radius, paint);

    if (child != null) {
      context.paintChild(
          child,
          Offset(center.dx - (child.size.width) / 2,
              center.dy - (child.size.height) / 2));
    }
  }
}
`

**Sample:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/range-slider-icon2141414875.zip 
 
Kindly check the code snippet and let us know if you have any doubts.

Regards,
Lakshmi R.

**Comment by Alex0084** [comment]
Hello LakshmiRadhaKrishnan 

Thank you for your help
its working as expected

Thanks
