### ISSUE TITLE
[syncfusion_flutter_datagrid] rowColor not updating

### ISSUE THREAD

**Issue by socramm9** [syncfusion/flutter-widgets#832]
I am using `notifyDataSourceListeners` to trigger a row update. This row update is meant to re render the row with a new color. The `buildRow` function also runs als expected with the correct color, but the Row UI only updates after the user hovers in or out of the row. 

https://user-images.githubusercontent.com/52098754/181240166-6f521ad1-5ecd-465b-83ca-db909a2cb3c9.mov

I also created a project for easy Reproduktion. Just download https://github.com/socramm9/syncfusion_issue and run the app and right click any row.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @socramm9,

As per your requirement, you need to call the DataGrid **notifyListeners** to update the row color if it's changed at runtime. The **notifyListeners** will regenerate the row with the respective color. The DataGrid notifyDataSourceListeners are used to refresh the value of a specific cell when it's updated i.e., the respective index mentioned in the RowColumnIndex(rowIndex!, 0). Please check the following code snippet. 

```dart
  void setRowRightClicked(int rowIndex, int rowId) {
    rightClickRowIndex = rowIndex;
    rightClickRowId = rowId;
    notifyListeners();
  }

```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample1321160191 

We hope this helps. Please let us know if you require any further assistance on this. 

Regards,
Tamilarasan

**Comment by socramm9** [comment]
Yes it works with `notifyListeners` I was just expecting `notifyDataSourceListeners` to work because the new color is passed to the row. 

Thanks
