### ISSUE TITLE
[syncfusion_flutter_charts] Distinguish callback prototypes for `legendItemBuilder` of `SfCartesianChart` and `SfCircularChart`

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#835]
It would be good to have difference callback prototypes for differenct charts. For example, `SfCartesianChart` and `SfCircularChart` have the same prototype and it is confusing.
```dart
legendItemBuilder: (legendText, series, point, seriesIndex) {
  // 1.  point is null `SfCartesianChart`
  // 2. seriesIndex is equal to `point.index` for `SfCircularChart` but actually number of series is 1
}
```

It is also would be good to define data types for prototype parameters `series`, `point` instead of using `dynamic`.

**Comment by sfHariHaraSudhan** [comment]
Hi @bambinoua,

We can differentiate the [legendItemBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/LegendItemBuilder.html) callback to determine whether it is suitable for the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html) or [SfCircularChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCircularChart-class.html) using the point and series index prototype.

Currently we don’t have support for Removing dynamic data type in public callbacks. However, we have considered your requirement as a new feature and logged feature request for it in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback link below.

Feedback link: https://www.syncfusion.com/feedback/44540/remove-dynamic-datatype-in-public-callbacks 

Regards,
Hari Hara Sudhan. K.
