### ISSUE TITLE
[syncfusion_flutter_charts] Weird behavoir of some `Legend` properties.

### ISSUE THREAD

**Issue by bambinoua** [syncfusion/flutter-widgets#836]
I use `SfCircularChart` and its `Legend` property. I want to align the `Legend` exactly vertically centered but I cannot. I revealed that some properties have weird behaviour. The properties `padding` and `offset` do not affect anything. The property `height` does not affect height of legend correctly. I tried to use values like `NN%` and `NN`. When I specify values `height: '100'` and `height: '105'` I expect the difference in 5px but really it is more(!). So I am still not able to center my `Legend` vertically centered.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @bambinoua,

We have checked the mentioned scenario and were unable to replicate it from our side. We would like to let you know the functionalities of the properties you have mentioned below.

1. the height which is the percentage value from the overall chart will work only when the legend items take up more space than specified.
2. padding is a pixel value that is used to separate the legend item icon from the legend item text.
3. offset which is used to custom position the legend on the chart. If the offset is set and the position is set to the top, the legend will be placed on top and adjusted to the specified value.


Query: I am still not able to center my Legend vertically centered

Setting the Legend.position as right or left will center it vertically on the chart. Let us know if you need further assistance with this.

Regards,
Yuvaraj.
