### ISSUE TITLE
Can't scroll map vertically

### ISSUE THREAD

**Issue by alejandrogiubel** [syncfusion/flutter-widgets#838]
Hi. When I put syncfusion_flutter_maps inside a ListView or other scrollable widgets I can move the map horizontally
but not vertically. Any idea how can I fix this? Thx.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @alejandrogiubel,

We can reproduce the reported issue at our end, and we need some more time to validate this issue at the source level, so we will update you on the details on Aug 3rd, 2022.

Regards,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @alejandrogiubel,

Thanks for your patience.

Currently, we do not have an option to absorb the vertical gesture from the parent scrolling at the sample level. We can avoid parent vertical scrolling by wrapping SfMaps into GestureDetector and subscribing its onVertialDragUpdate callback, but unfortunately, SfMaps do not succeed in receiving this gesture either.

So we are considering your requirement as a feature request and have created feedback. You can use the following link to track the status of this feature.


Feedback: [https://www.syncfusion.com/feedback/36795](https://www.syncfusion.com/feedback/36795/absorb-the-vertical-gesture-when-placing-the-sfmaps-in-scrollable-widgets)

Regards,
Yuvaraj.
