### ISSUE TITLE
SfRangeSlider: when max is greater than 15, it seems impossible to have start equals to end

### ISSUE THREAD

**Issue by Bawen34** [syncfusion/flutter-widgets#843]
Hello,
When using SfRangeSlider: it seems we have an issue when max is greater than 15.

Let's we put it to 20, then I am not able to put the end cursor over the start cursor or vice-versa.

```
SfRangeValues _values = const SfRangeValues(4.0, 6.0);
 SfRangeSliderTheme(
              data: SfRangeSliderThemeData(thumbRadius: 14),
              child: SfRangeSlider(
                max: 20.0,
                stepSize: 1,
                startThumbIcon: Text(_values.start.toString()),
                endThumbIcon: Text(_values.end.toString()),
                values: _values,
                onChanged: (SfRangeValues values) {
                  setState(() {
                    _values = values;
                  });
                },
              )),
```

**Comment by QuynhEkoios** [comment]
I just have fixed this, only update stepSize is 2. Hope it useful for you.

**Comment by QuynhEkoios** [comment]
I have same issue, when max is greater than 20, it seems start not equals end
` SfRangeSlider(
          showTicks: false,
          showLabels: true,
          stepSize: 1,
          minorTicksPerInterval: 2,
          endThumbIcon: const ThumbIcon(),
          startThumbIcon: const ThumbIcon(),
          enableTooltip: true,
          max: 20.0,
          values: _values,
          activeColor: Colors.red,
          showDividers: true,
          onChanged: (SfRangeValues newValues) {
            setState(() {
              _values = newValues;
            });
          },
        )`

**Comment by Yuvaraj-Gajaraj** [comment]
Hi Team,

We tried to replicate your issue in a simple sample, but the reported issue is not reproduced at our end. We have shared the sample below for your reference. Please modify the sample as per your requirement to replicate the issue, which will help us to assist you in a better way.

![rangeslider](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif)

Sample: 
[i397056.zip](https://github.com/syncfusion/flutter-widgets/files/9283283/i397056.zip)

Regards,
Yuvaraj.

**Comment by QuynhEkoios** [comment]
Hi Yuvaraj-Gajaraj,
Please update max greater than 20, example max: 21,22 or .... it seems impossible to have start equals to end

**Comment by QuynhEkoios** [comment]
> Hi @Bawen34,
> 
> We tried to replicate your issue in a simple sample, but the reported issue is not reproduced at our end. We have shared the sample below for your reference. Please modify the sample as per your requirement to replicate the issue, which will help us to assist you in a better way.
> 
> ![rangeslider](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) [ ![rangeslider](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) ](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) [ ](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif)
> 
> Sample: [i397056.zip](https://github.com/syncfusion/flutter-widgets/files/9283283/i397056.zip)
> 
> Regards, Y

Hi @Yuvaraj-Gajaraj ,
I have same issue, when max is greater than 20, it seems start not equals end, I have shared the sample and screenshot below for your reference. Please check help me.

Thank you.

![Simulator Screen Shot - iPhone 8 - 2022-08-08 at 23 10 32](https://user-images.githubusercontent.com/100659188/183463717-32e49132-d206-404c-b73e-d014893dbffa.png)
uvaraj.

[demoslide.zip](https://github.com/syncfusion/flutter-widgets/files/9283360/demoslide.zip)

**Comment by Bawen34** [comment]
> Hi @Bawen34,
> 
> We tried to replicate your issue in a simple sample, but the reported issue is not reproduced at our end. We have shared the sample below for your reference. Please modify the sample as per your requirement to replicate the issue, which will help us to assist you in a better way.
> 
> ![rangeslider](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) [ ](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) ![rangeslider](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif) [ ](https://user-images.githubusercontent.com/61863686/183462197-537ad77c-a99c-4a9b-a47f-51c5e895d74d.gif)
> 
> Sample: [i397056.zip](https://github.com/syncfusion/flutter-widgets/files/9283283/i397056.zip)
> 
> Regards, Yuvaraj.

I can reproduce it with your code by putting it in a Row

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Bawen34 | @QuynhEkoios,

We can reproduce the reported issue at our end, and our development team is checking it at the source level. We will update further details in one business day, and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Bawen34 | @QuynhEkoios,

We considered the reported issue as a bug and created a feedback report “Discrete range slider thumbs do not overlap when placed inside the Row widget” and you can track this issue status using the following link.

https://www.syncfusion.com/feedback/37062

We will include this fix in our Volume 3 main release, which is scheduled for the end of September. We will let you know once the release gets rolled out. We appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Bawen34 | @QuynhEkoios,

We are glad to announce that our Essential Studio 2022 Volume 3 release v20.3.0.47 is rolled out and is available for download under the following link.
[Essential Studio 2022 Volume 3 Main Release v20.3.0.47 is available for download | Announcements Forums | Syncfusion](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F177858%2Fessential-studio-2022-volume-3-main-release-v20-3-0-47-is-available-for-download&data=05%7C01%7Csriramkiran.senthilkumar%40syncfusion.com%7C2627996b27254eb5903008daa2123ab5%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638000496437916313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ypQVpWUZ%2Ba%2F%2FAwAYgHqJpjpSa3IfmSk02DWALhUxuc%3D&reserved=0)

The reported issue regarding the “Discrete range slider thumbs do not overlap when placed inside the Row widget” is now fixed and rolled out in this release. So, kindly please upgrade the slider package version to the latest version below to overcome the issue.
https://pub.dev/packages/syncfusion_flutter_sliders/versions/20.3.47

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sriram Kiran
