### ISSUE TITLE
[syncfusion_flutter_maps]how to add/draw holed polygon?

### ISSUE THREAD

**Issue by yaolv7** [syncfusion/flutter-widgets#845]
Excuse me for bad English!

how to add holed polygon , like this , Thanks!
![FF581A25-6949-497E-ADAD-0CA3EEFE2BD1](https://user-images.githubusercontent.com/32125466/183590917-ced850ba-6c39-45c5-b7d2-76f45a552008.png)

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @yaolv7,

We suggest you use [MapPolygonLayer.inverted](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapPolygonLayer/MapPolygonLayer.inverted.html) to highlight a specific region in the maps. Here we have shared the online sample and KB documentation below for your reference.

Online sample: https://flutter.syncfusion.com/#/maps/tile-layer/polygon

KB: https://www.syncfusion.com/kb/12779/how-to-create-a-polygon-hole-in-flutter-maps

Regards,
Yuvaraj.
