### ISSUE TITLE
Null check operator used on a null value error on refresh 

### ISSUE THREAD

**Issue by Adithyan2295** [syncfusion/flutter-widgets#847]
While hitting refresh the following error is shown.

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building LayoutBuilder:
Null check operator used on a null value

The relevant error-causing widget was:
  LayoutBuilder
  LayoutBuilder:file:/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.2.43/lib/src/chart/base/cha
  rt_base.dart:2360:12

When the exception was thrown, this was the stack:
#0      ChartSeriesPanel._needAxisAnimation (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:103:66)
#1      ChartSeriesPanel._populateDataPoints (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:244:23)
#2      ChartSeriesPanel.processData (package:syncfusion_flutter_charts/src/chart/base/series_base.dart:90:7)
#3      ContainerArea._calculateBounds (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2564:34)
#4      ContainerArea._initializeChart (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2548:5)
#5      ContainerArea.build.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2539:34)
#6      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:119:77)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#8      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
#9      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2025:59)
#10     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#11     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025:14)
#12     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227:7)
#13     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#17     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:318:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#19     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#20     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#21     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#23     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#25     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#29     _ChartContainerBox.performLayout (package:syncfusion_flutter_charts/src/common/common.dart:34:12)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#32     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#33     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#34     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#35     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#36     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#37     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#38     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:829:43)
#39     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#41     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#43     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#44     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:552:43)
#45     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:579:12)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#47     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:318:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#49     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#50     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#51     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#52     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#53     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#57     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#92     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#96     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#105    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#107    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#111    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#112    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#113    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#114    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#115    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:504:19)
#116    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:892:13)
#117    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#118    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#119    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#120    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

![Screenshot 2022-08-12 at 3 59 19 PM](https://user-images.githubusercontent.com/94591962/184336657-2015feb5-02e9-4f1f-80d8-9d9995bb4911.png)

![Screenshot 2022-08-12 at 4 08 30 PM](https://user-images.githubusercontent.com/94591962/184337895-106fdb61-3512-4c8f-b121-c348b89530c6.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Adithyan2295,

We tried to replicate your issue in a simple sample, but the reported issue is not reproduced at our end. We have shared the sample below for your reference. Please modify the sample as per your requirement to replicate the issue, which will help us to assist you in a better way.

[i398578.zip](https://github.com/syncfusion/flutter-widgets/files/9350817/i398578.zip)

Regards,
Sriram Kiran
