### ISSUE TITLE
syncfusion_flutter_datagrid

### ISSUE THREAD

**Issue by Ashish-Raturi** [syncfusion/flutter-widgets#848]
Hi, thanks for this plugin

When I'm running on mac in syncfusion_flutter_datagrid

I'm trying to update the Row text font weight, but it's not working. It's just bold.

<img width="708" alt="Screenshot 2022-08-14 at 8 27 06 PM" src="https://user-images.githubusercontent.com/50191855/184542820-807fefdf-178d-4887-89bf-271b5b941cab.png">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Ashish-Raturi,

Based on the provided information, we are unable to reproduce the reported issue. It’s working fine on our end. We have tested the following sample with the **DataGrid Version: 20.2.43**

**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1791867135 

- **FontWeight.w300:**

![Screen Shot 2022-08-15 at 01 05 51 PM](https://user-images.githubusercontent.com/93904422/184594858-8cb85f57-a6b1-4452-af76-b82b4a9140a4.png)


- **FontWeight.w600:**

![Screen Shot 2022-08-15 at 01 09 32 PM](https://user-images.githubusercontent.com/93904422/184594862-3ad913ad-9feb-4820-a484-7624772a49b5.png)



Please check the above sample. If you are still facing the same issue, please provide the following details to check further.

- **Provide a sample that is reproducible or modify the above sample as reproducible.**

- **Flutter version which you have used.**


It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by Ashish-Raturi** [comment]
Hi, @Tamilarasan-Paranthaman I think it's on my side. Thanks for your reply.
