### ISSUE TITLE
[syncfusion_flutter_charts] Question: "Digital" line series

### ISSUE THREAD

**Issue by MarcelKr** [syncfusion/flutter-widgets#849]
Is there a possibility to have a "digital" line series? What I mean is: From one data point to the next, there shall be horizontal lines. In other words: The first value shall be held until there's a new value.

For example I want to visualize a switch state which has only on/off (1/0) values. It currently looks like this:
![grafik](https://user-images.githubusercontent.com/6226629/184831395-d9164380-927d-4c7d-bda6-b1c634f87d53.png)

Obviously I want to have horizontal lines instead of the skewed ones seen in the screenshot.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @MarcelKr,

We have checked your requirement at our end, and we suggest you use `StepLineSeries` instead of `LineSeries` and have appended the user guide documentation link for `StepLineSeries` for your reference.

UG: https://help.syncfusion.com/flutter/cartesian-charts/chart-types/step-line-chart

Please get back to us if you require further assistance.

Regards,
Sriram Kiran

**Comment by MarcelKr** [comment]
Hey @SriramKiranSenthilkumar, sorry for the late response. Is it possible to combine a regular line with the step line? It would be interesting in my case to overlay a temperature and a fan state.
BR Marcel

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,

We have checked your query at our end, and we would like to let you know that you can be able to render a combination of different series types in the same chart widget.
In your case, you can add two line series to render the temperature and fan state after the step line series in your chart. We have also appended the user guide documentation to render a combination of different series types below for reference.
https://help.syncfusion.com/flutter/cartesian-charts/multiple-charts#combination-series

Regards,
Sriram Kiran
