### ISSUE TITLE
how can i get date on tap of particular date in header?

### ISSUE THREAD

**Issue by urvashikharecha** [syncfusion/flutter-widgets#85]
How can i get date on tap of particular date on header ?
when week change i require start date and end date of week , how can i get those dates? please guide...

**Comment by Indumathi1195R** [comment]
Hi @urvashikharecha,

**Regarding Query 1: How to get the particular date when on tap.**

Your requirement can be achieved by **targetElement** of the Flutter event calendar **onTap** callback. Also, we have a KB document for the same. 

Please find the KB document from the following link,

**KB link:** https://www.syncfusion.com/kb/10998/how-to-get-datetime-details-while-tapping-the-flutter-event-calendar-elements

**Regarding Query 2: How to get the start and end date of the week.**

Using the **onViewChanged** callback, you can get the visibleDates details. We have a KB document for getting the start and end dates of the visible dates. Please find the KB from the following link.

**KB link:** https://www.syncfusion.com/kb/11026/how-to-get-visible-dates-details-from-the-flutter-event-calendar-sfcalendar

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R
