### ISSUE TITLE
cant view pdf on android 8.1

### ISSUE THREAD

**Issue by Mohamed98fadel** [syncfusion/flutter-widgets#850]
flutter syncfusion pdf viewer running fine on android 10, 11 but when running it on tablette with android 8.1 it keeps showing the progress line and the pdf never comes.

**Comment by deepika134** [comment]
Hi Mohamed Fadel,

We tried to reproduce the reported issue with provided details, but the PDF is loaded properly in Android 8.1 version in our side. For your reference, we have prepared a sample (along with the output screen record of the same) and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-850964719525.zip 

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.
1. Device Specification.
2. Flutter Doctor log.
3. Issue reproducing PDF document.
4. syncfusion_flutter_pdfviewer package version.
5. Flutter SDK version.
This information will be helpful for us to provide you a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by Hunaisp** [comment]
i got I/flutter ( 5398): Helvetica has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management
I/flutter ( 5398): Helvetica-Bold has no Unicode support see https://github.com/DavBfr/dart_pdf/wiki/Fonts-Management this issue
