### ISSUE TITLE
Example Chinese  not support  ,  Unhandled Exception: Invalid argument   The character is not supported by the font 

### ISSUE THREAD

**Issue by probe-pg** [syncfusion/flutter-widgets#851]
`headerRow.cells[1].value = '你好';`

**Comment by GowthamrajKumar25** [comment]
Hi PPZDP,

We can render the Chinese characters in PdfGrid header using our Syncfusion Flutter library. We have to apply the proper supported font to that particular grid cell by using Font property. In this below code snippet, we use the PdfCjkStandardFont to render the Chinese characters. Please try the below code snippet on your end and let us know the result.

```
//Add header rows to the grid.
  PdfGridRow header = grid.headers[0];
  header.cells[0].value = 'Employee ID';
  header.cells[1].value = '你好';
  var font1 = PdfCjkStandardFont(PdfCjkFontFamily.heiseiMinchoW3, 14);
  header.cells[1].style.font = font1;
  header.cells[2].value = 'Salary';

```
Output: https://www.syncfusion.com/downloads/support/directtrac/general/pd/Output418531724

Please refer to the below link for more information,
UG: https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-cjk-fonts

Please let us know if you need any further assistance in this.

Regards,
Gowthamraj K

**Comment by PPZDP** [comment]
use : 
`
header.cells[1].value = '你好';

var font1 = PdfCjkStandardFont(PdfCjkFontFamily.heiseiMinchoW3, 14);
 header.cells[1].style.font = font1;`

Exception: type 'PdfCjkStandardFont' is not a subtype of type 'PdfTrueTypeFont' in type cast
version:: ^20.2.43

**Comment by GowthamrajKumar25** [comment]
Hi PPZDP,

We have checked the code with latest version (20.2.43), but it is working properly. We have attached a sample to render the Chinese characters in PdfGrid header cell by using our Syncfusion Flutter library. Please try the below sample on your end and let us know the result.

Sample : https://www.syncfusion.com/downloads/support/directtrac/general/ze/CreatePdfFile-842808258

Please refer to the below link for more information,
UG: https://help.syncfusion.com/flutter/pdf/working-with-text#draw-text-using-cjk-fonts 
https://www.syncfusion.com/kb/11973/how-to-create-a-pdf-file-in-flutter-web-platform

Please let us know if you need any further assistance in this.

Regards,
Gowthamraj K

**Comment by kevinxxq** [comment]
A question may be not related of this one, Is it possible to have a pdf page very wide to match all the columns?

**Comment by irfanajaffer** [comment]
Yes, we can set custom page size or change the orientation of the page using PdfPageSettings to achieve your requirement.

 

Kindly use the following link to know more about page settings,

https://help.syncfusion.com/flutter/pdf/working-with-pages#adding-sections-with-different-page-settings

https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPageSettings/orientation.html

https://pub.dev/documentation/syncfusion_flutter_pdf/latest/pdf/PdfPageSettings/size.html

**Comment by baali-boudjemaa** [comment]
hi,
 I have this bug when try to print Arabic text. and i using the this version syncfusion_flutter_datagrid_export: ^19.3.44
Unhandled Exception: Invalid argument (The character is not supported by the font.): 1543

**Comment by baali-boudjemaa** [comment]
hi,
I have this bug when try to print Arabic text. and i using the latest version of syncfusion_flutter_datagrid_export
Unhandled Exception: Invalid argument (The character is not supported by the font.): 1543
