### ISSUE TITLE
How to check Signature Pad is Empty or not.???

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [syncfusion/flutter-widgets#852]

**Comment by sfHariHaraSudhan** [comment]
Hi @MustafaDev-shaikh,

Yes, we can determine whether the [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) is empty or not using the global key and the [toPathList](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState/toPathList.html) which is the publicly exposed method available at the [SfSignaturePadState](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState-class.html) that stores the path as a list. Here I have checked whether the [toPathList](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePadState/toPathList.html) method is empty; if it is, then the [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) is empty; if not, then the [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) is filled, and the text changed is controlled by a boolean property.

Snapshot:
 
![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/d24b5b3b-4bd7-49ff-abe0-49bfa8ebe62e)

![image](https://github.com/syncfusion/flutter-widgets/assets/105288122/9d07df69-561c-48cb-962e-997c0b894253)

Kindly check this code snippet:
```
class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<SfSignaturePadState> _signatureGlobalKey = GlobalKey();
  bool isEmpty = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(isEmpty
                ? 'Signature Pad is empty'
                : 'Signature Pad is filled properly'),
            const SizedBox(
              height: 10,
            ),
            SizedBox(
              height: 200,
              width: 300,
              child: SfSignaturePad(
                key: _signatureGlobalKey,
                backgroundColor: Colors.grey[200],
              ),
            ),
            const SizedBox(
              height: 10,
            ),
            ElevatedButton(
              child: const Text("Path collection"),
              onPressed: () {
                List<Path> paths =
                    _signatureGlobalKey.currentState!.toPathList();
                setState(() {
                  if (paths.isEmpty) {
                    isEmpty = true;
                  } else {
                    isEmpty = false;
                  }
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
Also kindly check the below attached sample for better reference.

Regards,
Hari Hara Sudhan. K


[473513.zip](https://github.com/syncfusion/flutter-widgets/files/11758441/473513.zip)
