### ISSUE TITLE
[syncfusion_flutter_datagrid] Swiping is sometimes making the screen scrolling by itself

### ISSUE THREAD

**Issue by Bawen34** [syncfusion/flutter-widgets#855]
Hello,
I am using the **syncfusion_flutter_datagrid: ^20.2.44** and when I use one of your sample in *swiping mode*, it seems sometimes the screen is scrolling by itself.

https://user-images.githubusercontent.com/36164800/185467796-4257274e-1cf5-41be-b5bb-ccef8380501d.mp4
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'customer_datagridsource.dart';

/// Renders column sizing data grid
class ColumnSizingDataGrid extends StatefulWidget {
  /// Creates column sizing data grid
  const ColumnSizingDataGrid({Key? key}) : super(key: key);

  @override
  State<ColumnSizingDataGrid> createState() => _ColumnSizingDataGridState();
}

class _ColumnSizingDataGridState extends State<ColumnSizingDataGrid> {
  /// Required for SfDataGrid to obtain the row data.
  late final CustomerDataGridSource columnSizingDataGridSource;

  List<GridColumn> _getColumns() {
    return <GridColumn>[
      GridColumn(
        columnName: 'ID',
        autoFitPadding: EdgeInsets.zero,
        label: Container(
          color: Colors.blue,
          child: const Text('ID'),
        ),
      ),
      GridColumn(
        columnName: 'Name',
        autoFitPadding: EdgeInsets.zero,
        label: Container(
          color: Colors.red,
          child: const Text('Name'),
        ),
      ),
      GridColumn(
        columnName: 'Shipped Date',
        autoFitPadding: EdgeInsets.zero,
        label: Container(
          color: Colors.green,
          child: const Text('Shipped Date'),
        ),
      ),
      GridColumn(
        columnName: 'City',
        autoFitPadding: EdgeInsets.zero,
        label: Container(
          color: Colors.yellow,
          child: const Text('City'),
        ),
      ),
    ];
  }

  SfDataGrid _buildDataGrid(BuildContext context) {
    return SfDataGrid(
      allowSwiping: true,
      verticalScrollPhysics: NeverScrollableScrollPhysics(),
      swipeMaxOffset: 100,
      source: columnSizingDataGridSource,
      columnWidthMode: ColumnWidthMode.fill,
      columns: _getColumns(),
    );
  }

  @override
  void initState() {
    super.initState();
    columnSizingDataGridSource = CustomerDataGridSource(isWebOrDesktop: false);
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Card(
          child: Column(children: [
        ExpansionTile(
          title: Text("Test1"),
          children: [_buildDataGrid(context)],
        ),
        ExpansionTile(
          title: Text("Test2"),
          children: [_buildDataGrid(context)],
        ),
        ExpansionTile(
          title: Text("Test3"),
          children: [_buildDataGrid(context)],
        )
      ])),
    );
  }
}

/// custom column sizer class
class CustomColumnSizer extends ColumnSizer {
  @override
  double computeCellWidth(GridColumn column, DataGridRow row, Object? cellValue, TextStyle textStyle) {
    return super.computeCellWidth(column, row, cellValue, textStyle);
  }
}

```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Bawen34,

Currently, we are analyzing the reported issue. We will validate and update you with the details in two business days. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Bawen34,

We have checked your reported issue and logged this as a bug. We will include the changes in our weekly pub release which is scheduled to be rolled out on September 06, 2022. We will let you know once it gets rolled out. We appreciate your patience until then. You can follow up with the below feedback for further details,

Feedback Link:  https://www.syncfusion.com/feedback/37230/scrollview-is-scrolled-at-sample-level-when-swiping-the-row-in-datagrid 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Bawen34,

Sorry for the inconvenience.

Due to some technical difficulties, we could not include the issue fix in this weekly pub release. We will include the changes in our weekly pub release which is scheduled to be rolled out on September 13, 2022. We will let you know once it is published. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Bawen34,

Sorry for the inconvenience. We could not include the issue fix in this weekly pub release. We will include the changes in our **Volume 3** main release which is scheduled to be rolled out at the end of September. We will let you know once it is published. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Bawen34,

We are glad to announce that our Essential Studio 2022 Volume 3 Main Release V20.3.0.47 is rolled out with the fix for mentioned issue and is available for download under the following link.



https://www.syncfusion.com/forums/177858/essential-studio-2022-volume-3-main-release-v20-3-0-47-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Tamilarasan
