### ISSUE TITLE
[syncfusion_flutter_treemap] change the color mapper from blue to another color

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#857]
by default, the component is already orange with shades of blue. Is there any way I can only pass the color and the component generate the shades?
I want to avoid having to create the TreemapColorMapper.range because my list is dynamic.
I just wanted to pass Colors.deeepPurple and the component generate the shades.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mdmota,

We are validating your query at our end, and we will update further details in one business day and we appreciate your patience until then.


Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @mdmota,

We have validated your query and considered your requirement as a feature request regarding ‘Support for direct min and max saturation in SfTreeMap’. We will include this feature in any of our upcoming releases yet to come and we appreciate your patience until then. You can track the status of the feedback using the link below.

https://www.syncfusion.com/feedback/37190

Regards,
Sriram Kiran
