### ISSUE TITLE
[syncfusion_flutter_pdfviewer] horizontal scroll direction doesn't change when changing the locale to RTL locale

### ISSUE THREAD

**Issue by assem16399** [syncfusion/flutter-widgets#858]
PDF horizontal scrolling direction is still LTR, even after changing the locale of the app to Arabic.

<img src="https://user-images.githubusercontent.com/56374551/185723038-053e5630-074f-43c3-a938-0969f5762bd9.png" width="200">

**Comment by deepika134** [comment]
Hi @assem16399 ,

We are checking on this and will update the further details on August 24, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment]
Hi Aasem,

At present we do not have support to “Scroll right-to-left horizontally in the RTL layout direction”. We have considered your feature request valid and based on our present commitments and other high priority works we will be implementing this feature in any of our upcoming releases.  We will let you know when this feature is implemented. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/37281/support-to-scroll-right-to-left-horizontally-in-rtl-layout-direction 

Regards,
Deepika R

**Comment by OmarYehiaDev** [comment]
Is there any details about this feature??
I need it ASAP :"""
@deepika134

**Comment by deepika134** [comment]
Hi @OmarYehiaDev ,

As we mentioned earlier, currently we do not have support for “Scroll right-to-left horizontally in the RTL layout direction”. We already have a feature request for this and will implement it in any of our releases. We will let you know once the feature is implemented and please follow the status of the feature in the following link.
https://www.syncfusion.com/feedback/37281/support-to-scroll-right-to-left-horizontally-in-rtl-layout-direction
