### ISSUE TITLE
PdfForm - image form field is visible as button

### ISSUE THREAD

**Issue by giaur500** [syncfusion/flutter-widgets#859]
My pdf file contains Image form field. How do I change image with new one? In my code, image field form is visible as button field and it's not possible to set/edit image for it.

**Comment by GowthamrajKumar25** [comment]
Hi giaur500,

We do not have support for set/edit image in button field of PDF document using Flutter PDF library. We do not have any immediate plans to implement this support. 

Regards,
Gowthamraj K

**Comment by giaur500** [comment]
Hi,
I there any other way to add image with Adobe designer and change it from dart code? We need it to place customer hand sign image in pdf.

**Comment by irfanajaffer** [comment]
To achieve your requirement on drawing image in a PDF document, we can use PdfBitmap class and drawImage method in page graphics,

Kindly refer code sample in following links for reference, https://help.syncfusion.com/flutter/pdf/working-with-images



We can also digitally sign in the PDF using the Syncfusion Flutter PDF, https://help.syncfusion.com/flutter/pdf/working-with-digital-signature

**Comment by RitliRoland** [comment]
This is still a problem, I have the same issue. I have an image type field, but the package recognizes as a PdfButtonField. It should be a PdfImageField or something like this, with a method to insert an image in this field.
