### ISSUE TITLE
PdfSignature field - change appearance without certificate set

### ISSUE THREAD

**Issue by giaur500** [syncfusion/flutter-widgets#860]
I have empty signature form field added to my pdf document form. I want to change appearance this way:

```
var sign = (fields[22] as PdfSignatureField);
PdfGraphics? graphics = sign.appearance.normal.graphics;
graphics?.drawImage(PdfBitmap(base64Decode(image)), sign.bounds);
final List<int> bytes = await document.save();

```
However,  there's no any image visible in saved pdf.  I have no certificate to sign document, I only need to display user's hand sign image. Do I also need do load cert to get it visible?

**Comment by irfanajaffer** [comment]
It is not possible to draw appearance in a signature with no certificate (Empty signature). To achieve your requirement, you can remove the signature field and draw the hand signed image in that position using drawImage method.



Kindly refer the code samples in following UG,

https://help.syncfusion.com/flutter/pdf/working-with-annotations#removing-annotations-from-an-existing-pdf

https://help.syncfusion.com/flutter/pdf/working-with-images
