### ISSUE TITLE
[syncfusion_flutter_pdfviewer] _CastError (type 'PdfDictionary' is not a subtype of type 'PdfReferenceHolder' in type cast)

### ISSUE THREAD

**Issue by ductranit** [syncfusion/flutter-widgets#862]
I got the following error when tap on pdf page, use version `20.2.45-beta`
```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _CastError was thrown while handling a gesture:
type 'PdfDictionary' is not a subtype of type 'PdfReferenceHolder' in type cast

When the exception was thrown, this was the stack
#0      PdfPageHelper.createAnnotations
package:syncfusion_flutter_pdf/…/pages/pdf_page.dart:787
#1      PdfPage.annotations
package:syncfusion_flutter_pdf/…/pages/pdf_page.dart:167
#2      CanvasRenderBox.handleTapUp
package:syncfusion_flutter_pdfviewer/…/control/pdfviewer_canvas.dart:753
#3      TapGestureRecognizer.handleTapUp.<anonymous closure>
package:flutter/…/gestures/tap.dart:611
#4      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
#5      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:611
#6      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:298
#7      BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:269
#8      GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#9      GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:449
#10     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:425
#11     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:329
#12     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:380
#13     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:344
#14     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:302
#15     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:285
#19     _invoke1 (dart:ui/hooks.dart:170:10)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onTapUp"
Recognizer: TapGestureRecognizer#f4ef3
    state: ready
    won arena
    finalPosition: Offset(128.0, 559.7)
    finalLocalPosition: Offset(128.0, 590.7)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```

**Comment by deepika134** [comment]
Hi ductranit,

We tried to reproduce the reported issue on our end but didn't get an exception when tapping the PDF page in SfPdfViewer. We have prepared a sample for your reference, and it can be downloaded from the following link,

https://www.syncfusion.com/downloads/support/directtrac/general/ze/github862506294334.zip 

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika R

**Comment by ductranit** [comment]
hi @deepika134 I you can reproduce with my pdf here:
```
Container(child: SfPdfViewer.network(
                                'https://dl.dropboxusercontent.com/s/3635wo42khv2d9g/test.pdf',
                                onDocumentLoaded: ((details) {
                                  data.value = false;
                                }),
                                onDocumentLoadFailed: (details) {
                                  data.value = false;
                                },
         ))
```
I think it only has trouble with my pdf. I tested on iOS (iphone & ipad)
The error happens when I click on link or text annotation on page.

**Comment by deepika134** [comment]
Hi @ductranit ,

We have confirmed that the issue with **"Exception occurs when tapping a PDF page in SfPdfViewer"** is a defect. The issue fix will be included in our September 1st weekly release which is estimated to be available on September 6, 2022. The status of this issue can be tracked using following link,
[https://www.syncfusion.com/feedback/37340/exception-occurs-while-trying-to-get-annotation-from-specific-pdf-document](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F37340%2Fexception-occurs-while-trying-to-get-annotation-from-specific-pdf-document&data=05%7C01%7Cdeepika.ravi%40syncfusion.com%7C71113bfd15354549506008da875256ba%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637971085021898532%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M4jkYh6fB4e5wrqnQEIU6ZA8iR%2BjVjDFXnV5nGKa4mQ%3D&reserved=0)

Regards,
Deepika R

**Comment by ramkumarsync** [comment]
Hi @ductranit ,

Sorry for the inconvenience caused,

Due to some technical conflicts, the fix was not moved to today's weekly NuGet release. However, we will include the fix in our upcoming weekly Nuget release which will be available on September 13, 2022. We appreciate your patience until then. 

Regards,
Ramkumar

**Comment by ductranit** [comment]
@ramkumarsync thanks for letting me know. I have no problem with that.
Actually atm I'm using the old version `19.4.56-beta` which can fix my issue

**Comment by deepika134** [comment]
Hi @ductranit ,

We have included the fix for the issue “**Exception occurs when tapping a PDF page in SfPdfViewer**” in our latest weekly release, so kindly upgrade to the latest version (20.2.49-beta) to get the issue resolved. 
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.49-beta

Regards,
Deepika Ravi

**Comment by ductranit** [comment]
@deepika134 thank you.
Confirm that it works on `20.2.49-beta`
