### ISSUE TITLE
Slider to work only when swiped

### ISSUE THREAD

**Issue by demrebicer** [syncfusion/flutter-widgets#864]
I want the slider to work only when swiped. Now when you click on a place on the slider, it determines the value directly as that place. I want it to continue from the last value when I swipe. Is this possible?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @demrebicer,

We have checked your query at our end, and we would like to let you know that currently, we don’t have any direct support for your requirement. However, we have considered this as a new feature request regarding “Provide option to enable or disable tap and drag gesture in SfSlider widget”. We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases.

Regards,
Sriram Kiran
