### ISSUE TITLE
[syncfusion_flutter_charts] BoxAndWhiskerSeries require entire data set

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#869]
When plotting a large number of entries on a box and whisker chart the `BoxAndWhiskerSeries` require entire data set for each charted entry to be passed in. That creates some performance issue when a large data set has to be retrieved from the storage.

It would be nice if the `BoxAndWhiskerSeries` class would have an option to pass in either a pre-calculated `BoxPlotQuartileValues` instance or some builder instead of the whole data set. 

Passing in pre-calculated `BoxPlotQuartileValues` will also help to address any math issues related to precision of the calculations used to compute the `BoxPlotQuartileValues`, e.g. when specific rounding is required.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ekuleshov,

Greetings from Syncfusion.

We have checked your query at our end, and we would like to let you know that we cannot achieve your requirement with the current chart source and also there is no feasible solution to achieve your requirement using a workaround. Sorry for the inconvenience.

Regards,
Sriram Kiran

**Comment by ekuleshov** [comment]
> Hi @ekuleshov,
> 
> Greetings from Syncfusion.
> 
> We have checked your query at our end, and we would like to let you know that we cannot achieve your requirement with the current chart source and also there is no feasible solution to achieve your requirement using a workaround. Sorry for the inconvenience.
> 
> Regards, Sriram Kiran

Not sure what the difficulty is. If it would help I can try to provide a pull request. Please let me know if you'd be willing to review proposed change.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ekuleshov,

We have checked your query at our end, and we would like to let you know that we will not be able to review and merge the proposed changes and merge them. However, we have considered your requirement as a feature and logged it in our feedback portal. We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.

https://www.syncfusion.com/feedback/37555

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.

Regards,
Sriram Kiran

**Comment by ekuleshov** [comment]
@DeviArunaM @SriramKiranSenthilkumar with this issue closed as completed, could you provide some pointers to the API how to use externally provided `BoxPlotQuartileValues` data with the `BoxAndWhiskerSeries` chart. Thank you.
