### ISSUE TITLE
SyncfusionLicense.registerLicense is deprecated

### ISSUE THREAD

**Issue by robertsLando** [syncfusion/flutter-widgets#87]
I saw this deprecation warning but online docs doesn't mention the new way to register a license: https://www.syncfusion.com/kb/11364/how-to-register-the-license-key-in-syncfusion-mac-demos

How can I fix this deprecation warning?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @robertsLando,

Greetings from Syncfusion. We have analyzed your query at our end and we would like to share some information regarding the licensing. In our latest vol 3 main release which rolled out by 1st October 2020, we have removed our licensing from our Flutter widgets framework and so, license key registration is not required for Flutter widgets if you are using v18.3.0.x or later versions i.e., hereafter you don’t need to register the generated license in you project if you are using v18.3.x or later versions of our Flutter widgets.

We have mentioned this information as a note in our user guide. Please check the user guide below for further reference.
https://help.syncfusion.com/common/essential-studio/licensing/license-key#flutter

Please get back to us if you still have further concerns.

Regards,
Sriram Kiran
