### ISSUE TITLE
Flutter Syncfusion DataGrid on Windows flicker on mouse hover and some time grid lines not show

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#874]
On Windows 10.
after update to flutter 3.3 . when i hover mouse on datagrid header cell it flucker. and some time gridcell lines are not visible.
![image](https://user-images.githubusercontent.com/62530396/188043577-edc61bb6-d3cd-4ce0-a548-08c03aa1f93f.png)
![image](https://user-images.githubusercontent.com/62530396/188043604-76befd6d-57bd-4d23-a765-3bc6620a03c7.png)
when i maximize windows screen then grid lines visible

**Comment by abdulrehmananwar** [comment]
![image](https://user-images.githubusercontent.com/62530396/188043718-57bd9a6d-9339-44cc-b1d5-fd46ce8dd607.png)
its

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @abdulrehmananwar,

Based on the provided information, we are unable to reproduce the reported issue. It’s working fine on our end. We have tested the following sample with the DataGrid version **20.2.46** and flutter version **3.3.0**.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample952169630 

Please check the above sample. **If you are still facing the same issue, please provide a simple sample that is reproducible or modify the above sample as reproducible to check further.** It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment]
ok its some other issue on windows. i have replace gridview with listview. butt screen flicker on windows. i am using flutter stable channel. it happened after upgrade to 3.3 version
