### ISSUE TITLE
[syncfusion_flutter_treemap] Limited Vision with enableDrilldown

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#875]
In the view grouped with enableDrilldown , when one value is too large and another too small, the label does not appear and there is no way to click on the smaller area to expand .
![Screenshot_20220902-215406](https://user-images.githubusercontent.com/21266037/188313279-e6f40954-87d8-4a11-b5d2-e236f73c524c.jpg)

**Comment by mdmota** [comment]
any updates?

**Comment by LokeshPalani** [comment]
Hi,


We would like to inform you that the [SfTreemap](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap-class.html) tile calculates based on weight, as it is the [SfTreemap](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap-class.html) behavior. However, you can adjust the weight according to your use case without needing to change the data. If you want to change the size of the tile, you can use weight for customization. We have passed the indices in the [tooltipBuilder](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/TreemapLevel/tooltipBuilder.html), which allows you to show the actual data based on the indices. We have provided a sample for your reference. Please let us know if you need further assistance.

Regards,
Lokesh.

[treemap_473100.zip](https://github.com/syncfusion/flutter-widgets/files/11788140/treemap_473100.zip)
