### ISSUE TITLE
[syncfusion_flutter_charts] CircularArea missing _showCircularTooltipTemplate method

### ISSUE THREAD

**Issue by bayernMfan** [syncfusion/flutter-widgets#876]
syncfusion_flutter_charts version higher then 20.1.56 throwing an error when trying to show tooltip by tap on circular chart.
Caused by missing method in CircularArea class.
In my case the error interrupts tooltip showing (doesn't show it at all) and all the call stack that might be called just after tooltip shown.
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/23279166/188427304-83dea8a4-88f8-4d55-9de7-c14cab0a47eb.png">

**Comment by SriramKiranSenthilkumar** [comment]
Hi @bayernMfan,

We have checked your query at our end, and we are able to replicate the reported issue at our end. We have considered this as a bug and logged a bug report regarding ‘NoSuchMethodError exception thrown when the activating tooltip using showByindex method in Circular charts’ in our feedback portal.

We will fix the reported issue and include the changes in our upcoming weekly patch release which is expected to be rolled out by the middle of next week. We will update you once the release is rolled out and we appreciate your patience until then. You can also track the status of the bug using the feedback link below.

https://www.syncfusion.com/feedback/37559

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi @bayernMfan,

Sorry for the inconvenience. We have fixed the reported bug and it's under testing phase in our end. We will include this fix in our volume 3 release, which is scheduled for the last week of September. We appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team,

We are glad to announce that our Essential Studio 2022 Volume 3 release v20.3.0.47 is rolled out and is available for download under the following link.
[Essential Studio 2022 Volume 3 Main Release v20.3.0.47 is available for download | Announcements Forums | Syncfusion](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F177858%2Fessential-studio-2022-volume-3-main-release-v20-3-0-47-is-available-for-download&data=05%7C01%7Csriramkiran.senthilkumar%40syncfusion.com%7C2627996b27254eb5903008daa2123ab5%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638000496437916313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ypQVpWUZ%2Ba%2F%2FAwAYgHqJpjpSa3IfmSk02DWALhUxuc%3D&reserved=0)

The reported issue regarding the “NoSuchMethodError exception thrown when the activating tooltip using showByindex method in Circular charts” is now fixed and rolled out in this release. So, kindly please upgrade the chart widget package version to the latest version below to overcome the issue.
https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.47

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sriram Kiran
