### ISSUE TITLE
Frame rendering time

### ISSUE THREAD

**Issue by amirr-dotcom** [syncfusion/flutter-widgets#877]
Syncfusion data grid is causing to much Frame rendering time which causes screen to flicker please fix this issue.
It causes it to go around 15 frame per second and more than 16ms rendering time is bad for maintaining app performance.

and memory usage is also a lot

![image](https://user-images.githubusercontent.com/71167542/188584408-c0ecd927-07b0-4374-a621-4685b7d0101d.png)

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @amirr-dotcom ,

Based on the provided information, we are unable to reproduce the reported issue. It’s working fine on our end. We have tested the following sample with the DataGrid version **20.2.49** and flutter version **3.3.0**. It took average of around 10 ms/frame (Raster). Please check the following reference image.

 
![image](https://user-images.githubusercontent.com/93904422/190178926-3fc59619-bc1c-4164-89c4-fdfa1535f1ed.png)


Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main1019159299 

Please check the above sample. If you are still facing the same issue, please provide a simple sample that is reproducible or modify the above sample as reproducible to check further. It will be helpful for us to check and provide an appropriate solution.

Regards,
Tamilarasan
