### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Vertical drag not working when inside a bottom sheet.

### ISSUE THREAD

**Issue by pgulegin** [syncfusion/flutter-widgets#880]
The vertical drag does not work on the pdfviewer when inside a modal bottom sheet. 

I have tried two different types of bottom sheets. 

1. [Flutter's showModalBottomSheet](https://api.flutter.dev/flutter/material/showModalBottomSheet.html)
2. [modal_bottom_sheet's showBarModalBottomSheet](https://pub.dev/packages/modal_bottom_sheet)

Quick Notes:

- When horizontally dragging, without lifting your finger, then switching to vertical dragging, it works.
- When diagonally dragging, without lifting your finger,  then switching to vertical dragging, it works.
- I have added a ListView Widget as a comparison.

Sample code:
```
import 'package:flutter/material.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

void main() {
  runApp(const MaterialApp(
    home: HomePage(),
  ));
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () {
              showModalBottomSheet(
                context: context,
                builder: (context) => const PdfViewerTest(),
              );
            },
            child: const Text(
              'showModalBottomSheet',
            ),
          ),
          ElevatedButton(
            onPressed: () {
              showBarModalBottomSheet(
                context: context,
                builder: (_) => const PdfViewerTest(),
              );
            },
            child: const Text(
              'showBarModalBottomSheet',
            ),
          ),
        ],
      ),
    );
  }
}

class PdfViewerTest extends StatelessWidget {
  const PdfViewerTest({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.white,
      child: Column(
        children: [
          Expanded(
            child: ListView(
              children: List.generate(
                1500,
                (index) => Text(index.toString()),
              ),
            ),
          ),
          Expanded(
            flex: 4,
            child: SfPdfViewer.network(
              'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
            ),
          ),
        ],
      ),
    );
  }
}
```

Added this line to pubspec.yaml:
```
 modal_bottom_sheet: ^2.1.2
```

**Comment by deepika134** [comment]
Hi @pgulegin,

We are checking on this and will update the further details on September 14, 2022.

Regards,
Deepika Ravi

**Comment by ManigandanShanmugam** [comment]
Hi @pgulegin 

In our Syncfusion Flutter PDF Viewer package, we used the interactive viewer widget to perform dragging and zooming behaviors. We have checked the reported issue and confirmed that this issue is reproduced due to the interactive viewer widget and have logged a bug report on the Flutter GitHub forum for this issue. We will let you once this issue has been fixed. You could also track the status of this issue from the following link.

https://github.com/flutter/flutter/issues/111573

Regard,
Manigandan Shanmugam
