### ISSUE TITLE
Pie chart labels are not displayed all when using builder

### ISSUE THREAD

**Issue by ducnghia69** [syncfusion/flutter-widgets#881]
I am having trouble getting image to show up when using builder.

I want to show image (replace by container with color). When I use builder then data showing only 3 items, although I have 5 items and not show full connectorLine

My screen:
![image](https://user-images.githubusercontent.com/38713982/189487773-8120b517-c3a7-4855-b901-3aedf7822b78.png)

My code:
```

 SfCircularChart(
                    tooltipBehavior: TooltipBehavior(
                      enable: true,
                      format: 'point.x: point.y%',
                    ),
                    series: <CircularSeries>[
                      // Render pie chart
                      PieSeries<ValueCode, String>(
                        radius: '60%',
                        dataLabelSettings: DataLabelSettings(
                          isVisible: true,
                          useSeriesColor: true,
                          builder: (
                            dynamic data,
                            dynamic point,
                            dynamic series,
                            pointIndex,
                            seriesIndex,
                          ) {
                            final _data = data as ValueCode;
                            final _point = point as ChartPoint;

                            return Container(
                              width: 32,
                              height: 32,
                              color: _point.color,
                            );
                          },
                          showZeroValue: false,
                          labelIntersectAction: LabelIntersectAction.shift,
                          labelPosition: ChartDataLabelPosition.outside,
                        ),
                        enableTooltip: true,
                        animationDuration: 500,
                        dataSource: widget.listValueCode,
                        xValueMapper: (ValueCode data, _) => data.name,
                        yValueMapper: (ValueCode data, _) => data.data,
                      ),
                    ],
                  ),
```

Example 1: Only show 3 items out of a total of 5 items and not show full connectorLine

```
<ValueCode>[
      ValueCode(data: 49.05, name: 'car 1'),
      ValueCode(data: 48.05, name: 'car 2'),
      ValueCode(data: 0.05, name: 'car 3'),
      ValueCode(data: 0.2, name: 'car 4'),
      ValueCode(data: 1.8, name: 'car 5'),
    ];

```

Example 2: Only show 4 items out of a total of 5 items and not show full connectorLine

```
<ValueCode>[
      ValueCode(data: 49.05, name: 'car 1'),
      ValueCode(data: 48.05, name: 'car 2'),
      ValueCode(data: 5.05, name: 'car 3'),
      ValueCode(data: 6.2, name: 'car 4'),
      ValueCode(data: 1.8, name: 'car 5'),
    ]
```
Please help me. Thank you so much.

**Comment by LokeshPalani** [comment]
Hi @ducnghia69,

We have analyzed your query and you can achieve your requirement by reducing the size of the pie chart using the [radius](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/radius.html) property in the [PieSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PieSeries-class.html) and by providing space to render data labels with [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DataLabelSettings/builder.html) property in the [dataLabelSettings](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/dataLabelSettings.html). Please inform us if you require any further assistance.


Regards,
Lokesh.
