### ISSUE TITLE
[syncfusion_flutter_pdf] PdfPageSettings Margin is ignored

### ISSUE THREAD

**Issue by devkirch** [syncfusion/flutter-widgets#882]
Hello,

when trying to display a Pdf Page in fullscreen with no border, the margin is ignored or not applied. 

`pageSettings.margins.all = 0` like in the example does not seem to work.
![Screenshot 2022-09-12 165332](https://user-images.githubusercontent.com/34398670/189686420-a1e75556-a602-4360-97cd-2cdef02f30f6.png)

Is there any other setting I am missing?

**Comment by theniceboy** [comment]
Same issue here

**Comment by irfanajaffer** [comment]
We were unable to reproduce the reported issue from our side.



The “pageSettings.margins.all = 0” is working as expected. Kindly use the following link to download the sample, https://www.syncfusion.com/downloads/support/directtrac/general/ze/pdf_demo_sample1182303810



Kindly refer the following link to know more about Flutter PDF pages, https://help.syncfusion.com/flutter/pdf/working-with-pages

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
