### ISSUE TITLE
[syncfusion_flutter_datagrid] SfDataPager is slow when we have many pages

### ISSUE THREAD

**Issue by tjuyou** [syncfusion/flutter-widgets#884]
SfDataPager is slow when we have many pages, for example 5000 pages, it may take 10 seconds.

**Comment by East333** [comment]
There is same problems in my project.
if the initial pageCount <= 5，after update widget，the pager will slow when the pagecount is many,
because it build every page button, the element is too many!
and it will happen when the initial pageCount <=5

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @tjuyou,

Based on the provided information, we are unable to reproduce the reported issue. We have tested the following sample with the 5000 pages and it’s working fine on our end. 

**Sample Link**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main1866088306 

Please check the above sample. If you are still facing the same issue, please provide the following details to check further.

- **Provide a sample that is reproducible or modify the above sample as reproducible.**
- **The platform (Web/Android/Windows/macOS/iOS) on which you faced the issue.**
- **Flutter version which you have used.**


It will be helpful for us to check on it and provide you with the solution at the earliest.

Regards,
Tamilarasan

**Comment by East333** [comment]
```dart
        FutureBuilder<double>(
          future: () async {
            await Future<void>.delayed(Duration(seconds: 1));
            return 100000.0;
          }(),
          builder: (context, snapshot) {
            switch (snapshot.connectionState) {
              case ConnectionState.none:
                return const Text('Press button to start');
              case ConnectionState.waiting:
                  return SfDataPager(
                    itemHeight: hiPagerItemHeight(),
                    itemWidth: hiPagerItemHeight(),
                    navigationItemHeight: hiPagerItemHeight(),
                    navigationItemWidth: hiPagerItemHeight(),
                    itemPadding: const EdgeInsets.all(2),
                    controller: dataPagerController,
                    availableRowsPerPage: Constants.instance.availableRowsPerPage,
                    delegate: saleOrderSourceView,
                    pageCount: 1,
                    direction: Axis.horizontal,
                    onRowsPerPageChanged: onRowsPerPageChanged,
                  );
              default: 
                if (snapshot.hasError) {
                  return Text('Error: ${snapshot.error}');
                } else {
                  return SfDataPager(
                    itemHeight: hiPagerItemHeight(),
                    itemWidth: hiPagerItemHeight(),
                    navigationItemHeight: hiPagerItemHeight(),
                    navigationItemWidth: hiPagerItemHeight(),
                    itemPadding: const EdgeInsets.all(2),
                    controller: dataPagerController,
                    availableRowsPerPage: Constants.instance.availableRowsPerPage,
                    delegate: saleOrderSourceView,
                    pageCount: snapshot.data!,
                    direction: Axis.horizontal,
                    onRowsPerPageChanged: onRowsPerPageChanged,
                  );
                }
            }
          },
        ),
```

If I use FutureBuilder or StatefulBuilder to change the pageCount by async way, the pager will build every page button 

My platform is windows

**Comment by tjuyou** [comment]
Fixed in the latest version， thanks
