### ISSUE TITLE
Availability for Students

### ISSUE THREAD

**Issue by AkshDesai04** [syncfusion/flutter-widgets#885]
Hey, I am a student from India and wanted to know if syncfusion_flutter_charts(package for flutter) was free to use for us.
I wanted to use it for a college project (no business motive with it in the foreseeable future).

Seeing it on the [pub.dev](https://pub.dev/packages/syncfusion_flutter_charts) website, it looks like a fantastic package but, after going to your website and its pricing section, I had this question.

**Comment by TesLake** [comment]
It is free for companies and individuals with less than $1 million USD in annual gross revenue and 5 or fewer developers. You do not require a license.

**Comment by sfHariHaraSudhan** [comment]
Hi @AkshDesai04,

You need to have a Syncfusion Flutter license to use our Flutter library in your applications. But there is no need to add the license key anywhere in your project.  

The Flutter controls from Syncfusion can be used without registering the license keys. 

You can refer the Syncfusion licensing terms and conditions from the below links.

https://github.com/syncfusion/flutter-examples/blob/master/LICENSE

https://help.syncfusion.com/flutter/licensing/overview 


And you can get more details about our community license from the below link.

https://www.syncfusion.com/products/communitylicense

Regards,
Hari Hara Sudhan. K
