### ISSUE TITLE
docx to pdf

### ISSUE THREAD

**Issue by AlexandreMaillot** [syncfusion/flutter-widgets#886]
is it possible to convert docx to pdf?

**Comment by GowthamrajKumar25** [comment]
Hi AlexandreMaillot,

No. It is not possible to convert Docx to PDF documents in the Syncfusion Flutter library. 

Regards,
Gowthamraj K

**Comment by bahman2000** [comment]
@AlexandreMaillot
Hi AlexandreMaillot, Have you found a solution?

**Comment by AlexandreMaillot** [comment]
> @AlexandreMaillot
> Hi AlexandreMaillot, Have you found a solution?

No unfortunately

**Comment by bahman2000** [comment]
> > [@AlexandreMaillot](https://github.com/AlexandreMaillot)
> > Hi AlexandreMaillot, Have you found a solution?
> 
> No unfortunately

Thank you for your reply. I am using the docx_template library to generate invoices from a template. The problem is that there is neither a good viewer in Flutter for displaying .docx files nor a good library for converting .docx to .pdf.
