### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Page rendering is too slow

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#889]
At present Pdfviewer is loading full page every time a part of the page is visible on screen. Can it be improved with only rendering the visible part of the page on screen ? There is already a feature request [here](https://www.syncfusion.com/feedback/31524/active-viewport-rendering) for Active Viewport Rendering. Is there any tentative plan for this to be available ?

Regards
Sagar

**Comment by deepika134** [comment]
Hi Sagar,

We do not have any immediate plans to implement the “**Active viewport rendering**” in SfPdfViewer. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented.

Regards,
Deepika Ravi
