### ISSUE TITLE
Cannot run and build app using latest syncfusion_flutter_pdfviewer: ^20.2.50-beta

### ISSUE THREAD

**Issue by RB-93** [syncfusion/flutter-widgets#890]
After updating the latest plugin in `pubspec.yaml`, the Flutter Android project cannot be run and build. 
Crashing with the following issue shown in the image:
![pdf2](https://user-images.githubusercontent.com/29726705/191248419-48951575-2ff9-4d9a-8d4d-aaa20282d0a2.png)

This is my flutter doctor log:
![pdf1](https://user-images.githubusercontent.com/29726705/191248527-44845beb-bd07-4914-94b0-860677dbded4.png)

Ealier used version was **syncfusion_flutter_pdfviewer: ^20.1.55-beta**.
But it showed a blank page when loading the pdf file from the network. So, I tried updating to the latest and the above issue occurred.

**Comment by abdullah230695** [comment]
Yes same issue for me

**Comment by deepika134** [comment]
Hi @RB-93 @abdullah230695 ,

kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.
Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk

Regards,
Deepika Ravi

**Comment by abdullah230695** [comment]
Okay but if I updated the SDK then other plugins may not work... So this is temporary solution...

**Comment by deepika134** [comment]
Hi @abdullah230695 ,

To use the latest (syncfusion_flutter_pdfviewer: ^20.2.50-beta) Syncfusion flutter PdfViewer package, you need to update to the latest Flutter SDK . If you are unable update to the latest Flutter SDK, kindly downgrade the Syncfusion flutter PdfViewer package version to lesser than v20.1.47, but it does not support the latest features.

Regards,
Deepika Ravi

**Comment by abdullah230695** [comment]
> Hi @abdullah230695 ,
> 
> To use the latest (syncfusion_flutter_pdfviewer: ^20.2.50-beta) Syncfusion flutter PdfViewer package, you need to update to the latest Flutter SDK . If you are unable update to the latest Flutter SDK, kindly downgrade the Syncfusion flutter PdfViewer package version to lesser than v20.1.47, but it does not support the latest features.
> 
> Regards,
> Deepika Ravi

Thanks for the info
