### ISSUE TITLE
[syncfusion_flutter_xlsio] Tables with filters not working.

### ISSUE THREAD

**Issue by lukaszciastko** [syncfusion/flutter-widgets#892]
I am trying to create a Table with auto filters. When I save the document and try to open it in Excel, I'm getting an error.

I use this code to create a Worksheet with a Table:

```dart
  final workbook = Workbook();

  final sheet = workbook.worksheets[0];

  sheet.getRangeByName('A1').setText('Fruit');
  sheet.getRangeByName('A2').setText('Banana');
  sheet.getRangeByName('A3').setText('Cherry');
  sheet.getRangeByName('A4').setText('Strawberry');

  sheet.getRangeByName('B1').setText('Price');
  sheet.getRangeByName('B2').setNumber(2.50);
  sheet.getRangeByName('B3').setNumber(7.0);
  sheet.getRangeByName('B4').setNumber(3.50);

  final range = sheet.getRangeByName('A1:B4');

  sheet.tableCollection.create('Table1', range)
    ..showHeaderRow = true
    ..builtInTableStyle = ExcelTableBuiltInStyle.tableStyleLight1;

  sheet.autoFilters.filterRange = range;

  final bytes = workbook.saveAsStream();
  final directory = await getApplicationDocumentsDirectory();
  final path = '${directory.path}/Report.xlsx';

  await File(path).writeAsBytes(bytes);

  workbook.dispose();
```

When I try to open the Document in Excel, I see this error:

<img width="372" alt="Screenshot 2022-09-21 at 15 28 28" src="https://user-images.githubusercontent.com/964414/191442331-d31ac9de-31ee-48cb-8ea5-511e70deb175.png">

How can I create a Table with filters so it works correctly?

**Comment by SivakumarRamya** [comment]
Hi 
 
Greetings from Syncfusion.
 
We have logged a feature report as Support for auto filters in the table but do not have any immediate plans to implement this feature in near future. You can track the status of the feature report through the following feedback link.


Track Status: [https://www.syncfusion.com/feedback/37918/support-for-auto-filters-in-the-table-in-flutter](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F37918%2Fsupport-for-auto-filters-in-the-table-in-flutter&data=05%7C01%7Cramya.s%40syncfusion.com%7C35605cea7dde43c9f25608da9c9cc04c%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637994494295615963%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZyDEL0Cifo%2F%2F3P96hyNZVaCES5sxmxRKUe40d3MnBG4%3D&reserved=0)
 
Regards,
Ramya.
