### ISSUE TITLE
Error: Type 'Uint8List' not found

### ISSUE THREAD

**Issue by flynihao53** [syncfusion/flutter-widgets#893]
flutter  version is 3.0.1 
/C:/flutter_windows_3.0.1/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/syncfusion_flutter_pdfviewer-20.2.50-beta/lib/src/pdfviewer.dart:911:8: Error: Type 'Uint8List' not found.
  late Uint8List _decryptedBytes;
       ^^^^^^^^^
/C:/flutter_windows_3.0.1/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/syncfusion_flutter_pdfviewer-20.2.50-beta/lib/src/pdfviewer.dart:1024:40: Error: Type 'Uint8List' not found.
  Future<void> _compareDocument(Future<Uint8List> oldBytesData,
                                       ^^^^^^^^^
/C:/flutter_windows_3.0.1/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/syncfusion_flutter_pdfviewer-20.2.50-beta/lib/src/pdfviewer.dart:1025:14: Error: Type 'Uint8List' not found.
      Future<Uint8List> newBytesData, String? oldPassword) async {
             ^^^^^^^^^
/C:/flutter_windows_3.0.1/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/syncfusion_flutter_pdfviewer-20.2.50-beta/lib/src/pdfviewer.dart:1743:36: Error: Type 'Uint8List' not found.
  void _decryptedProtectedDocument(Uint8List pdfBytes, String? password) {
                                   ^^^^^^^^^
/C:/flutter_windows_3.0.1/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/syncfusion_flutter_pdfviewer-20.2.50-beta/lib/src/pdfviewer.dart:1755:36: Error: Type 'Uint8List' not found.
  Future<PdfDocument?> _getPdfFile(Uint8List? value) async {
                                   ^^^^^^^^^

**Comment by deepika134** [comment]
Hi @flynihao53,

kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.
Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk

Regards,
Deepika Ravi

**Comment by mahmudph** [comment]
I'm also getting this issue in version 20.2.50-beta, I'm using flutter version 3.0.1

**Comment by deepika134** [comment]
Hi @mahmudph ,

As we mentioned earlier, kindly upgrade to the latest version of Flutter SDK to get the issue resolved. Please try this and let us know if the issue is resolved or not.
Flutter SDK setup link for the latest version: https://docs.flutter.dev/get-started/install/windows#get-the-flutter-sdk

Regards,
Deepika R

**Comment by bader-alden** [comment]
`import 'dart:typed_data';`
adding this line inside the file that contain **Uint8List** can solve the problem
it's work with me

**Comment by alexgheorghiu** [comment]
@deepika134 But  what if I'm stuck with Flutter 3.0.1 as client requirement? So please try to answer me these questions:
1. Is there any version of the library that will work with Flutter 3.0.1?
2. I understand that by simply importing typed_data in library's sources this might work. Why devs gave up on that import? Are new Flutter versions importing them by default?  
3. (Optional) Is there anyway a list of compatible Flutter for any library version?

**Comment by deepika134** [comment]
@alexgheorghiu , Yes, there is a version of Syncfusion Flutter PDFViewer that works with Flutter SDK 3.0.1. However, if you do not upgrade to the latest version of Syncfusion Flutter PDFViewer, you will not be able to access the newly added features and fixed bugs.

**Comment by yjt1216** [comment]
Error: 'Uint8List' isn't a type

**Comment by bader-alden** [comment]
> Error: 'Uint8List' isn't a type, I'm also getting this issue in version 20.3.59 (syncfusion_flutter_pdfviewer), I'm using flutter version 2.8.1 mac environtment

see this: https://github.com/syncfusion/flutter-widgets/issues/893#issuecomment-1270736477
