### ISSUE TITLE
Extending DataGridToPdfConverter Causes Stack Header Problem

### ISSUE THREAD

**Issue by bahadirarslan** [syncfusion/flutter-widgets#895]
I would like to change column names while exporting so I extended DataGridToPdfConverter class as described in the documents but this caused an error.
Even if the class is empty like below
```
class CustomDataGridToPdfConverter extends DataGridToPdfConverter {
}
```
An RangeError was thrown code below
` dataGrid.stackedHeaderRows[rowIndex];` //helper.dart line 77

Exception: **RangeError (RangeError (index): Invalid value: Only valid value is 0: 19)**

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @bahadirarslan,

Based on the provided information, we are unable to reproduce the reported issue. We have tested the following sample and it’s working fine on our end.

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/main-1857986750 

Please check out the above sample. If you are still facing the same issue, please provide the following details to check further.

- Provide a sample that is reproducible or modify the above sample as reproducible.

- The platform (Web/Android/Windows/macOS/iOS) on which you faced the issue.

- Flutter and DataGrid export version which you have used.

You can achieve it as per your requirement by using the **cellExport** callback. In the cellExport callback, set the required cell value if the cell type is **DataGridExportCellType.columnHeader** and the **pdfCell.value** is the respective value. Please check the following code snippet and sample.
 
```dart
Future<void> exportDataGridToPdf() async {
    final PdfDocument document = _key.currentState!.exportToPdfDocument(
        fitAllColumnsInOnePage: true,
        converter: customDataGridToPdfConverter,
        cellExport: (details) {
          if (details.cellType == DataGridExportCellType.columnHeader &&
              details.pdfCell.value == 'id') {
            details.pdfCell.value = 'Employee ID';
          }
        });

    final List<int> bytes = document.saveSync();
    await helper.saveAndLaunchFile(bytes, 'DataGrid.pdf');
    document.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('SfDatagrid Demo'),
      ),
      body: Column(children: [
        const Padding(padding: EdgeInsets.only(top: 30)),
        SizedBox(
            child: ElevatedButton(
                onPressed: exportDataGridToPdf,
                child: const Text('Export DataGrid to PDF'))),
        Expanded(
          child: SfDataGrid(
              source: _employeeDataSource,
              key: _key,
              columns: getColumns,
              stackedHeaderRows: stackedHeaderRows),
        ),
      ]),
    );
  }
}

```
Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample109841387 

We hope this helps. Please let us know if you need any further assistance on this.

Regards,
Tamilarasan
