### ISSUE TITLE
Search is very slow

### ISSUE THREAD

**Issue by pramod51** [syncfusion/flutter-widgets#896]
Can we add pagination so that it make some faster search.....
if it will search few 2-3 page then it will give better response...and on scrolling load and search....

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @pramod51,

We are a little bit unclear about your requirement i.e., for which widget you are asking. It would be helpful if you provided more clear details about your query and widget.

Regards,
Tamilarasan
