### ISSUE TITLE
SfCartesianChart Spline Series - show latest data based on datetime

### ISSUE THREAD

**Issue by ShubhamHande99** [syncfusion/flutter-widgets#897]
Hello, Syncfusion 

How to show only latest data based on datetime if there are multiple data on same datetime

example - datasource list
```
[
  {
    "date": "2022-06-1 02:30 PM",
    "value":5
  },
  {
    "date": "2022-06-1 02:45 PM",
    "value": 8
  },
  {
    "date": "2022-06-1 03:15 PM",
    "value": 11
  }
]
```

From the above data list, how to show the only latest data which is ( date: "2022-06-1 03:15 PM", value:11 ) insted of appending all the data in the chart view
![screenshot](https://user-images.githubusercontent.com/45396085/192283961-8e293e22-4681-4999-b4b3-f4c7c6d1e001.jpg)

**Comment by LokeshPalani** [comment]
Hi @ShubhamHande99,

We have analyzed your query, but we are unable to understand your exact requirement. Please provide us with more detailed information, such as whether you need to show the last segment or the last dataLabelSettings based on the latest data. This will help us to better assist you.

  
Regards,
Lokesh.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest charts version.
