### ISSUE TITLE
Range Slider End value drag issue.

### ISSUE THREAD

**Issue by Sagarz2422** [syncfusion/flutter-widgets#898]
Building and application where i need a range slider from values from 1-1000.
So the Start value goes to 0 but when i drag the slider from 1000 to the min it just goes min to 300 and not below that one.
How can we drag it below that, I don't want it to overlap on one another as it will make some issues. But some near value like 10 would salve the  thing.

Will be attaching the Gif for the issue that i am getting below:

 <img src="https://user-images.githubusercontent.com/106373072/192314597-c854afa7-c1ec-4ae7-9c5b-b75c982040a1.gif" width="200" height="350">

Posting the Code below: 
```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_sliders/sliders.dart';

void main() {
  return runApp(RangeSelectorApp());
}

/// This widget will be the root of application.
class RangeSelectorApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Range Selector Demo',
      home: MyHomePage(),
    );
  }
}

/// This widget is the home page of the application.
class MyHomePage extends StatefulWidget {
  /// Initialize the instance of the [MyHomePage] class.
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  _MyHomePageState();

  late double startValue = 0.0;
  late double endValue = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter Range Selector'),
      ),
      body: Container(
          margin: EdgeInsets.zero,
          padding: EdgeInsets.zero,
          child: Stack(
            children: <Widget>[
              Padding(
                padding: const EdgeInsets.only(top: 50),
                child: Center(
                  child: Column(
                    children: [
                      Text('Start : ${startValue}'),
                      Text(' End : ${endValue}'),
                    ],
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(top: 10),
                child: Center(
                  // ignore: missing_required_param
                  child: SfRangeSlider(
                    min: 0.0,
                    max: 10.0,
                    values: SfRangeValues(
                      startValue,
                      endValue,
                    ),
                    onChanged: (SfRangeValues value) {
                      print('Start : ${value.start}');
                      print('End : ${value.end}');

                      setState(() {
                        startValue = value.start as double;
                        endValue = value.end as double;
                      });
                    },
                  ),
                ),
              ),
            ],
          )),
    );
  }
}

```

**Comment by Sagarz2422** [comment]
thanks @SriramKiranSenthilkumar  waiting for the release

**Comment by SriramKiranSenthilkumar** [comment]
Hi @Sagarz2422,

We are glad to announce that our Essential Studio 2022 Volume 3 release v20.3.0.47 is rolled out and is available for download under the following link.

[Essential Studio 2022 Volume 3 Main Release v20.3.0.47 is available for download | Announcements Forums | Syncfusion](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Fforums%2F177858%2Fessential-studio-2022-volume-3-main-release-v20-3-0-47-is-available-for-download&data=05%7C01%7Csriramkiran.senthilkumar%40syncfusion.com%7C2627996b27254eb5903008daa2123ab5%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638000496437916313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4ypQVpWUZ%2Ba%2F%2FAwAYgHqJpjpSa3IfmSk02DWALhUxuc%3D&reserved=0)

As mentioned earlier, we have created a simple sample in which we have used the discrete selection feature and [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/onChanged.html) callback to achieve your requirement and attached the sample below for reference. Also, kindly please upgrade the slider package version to the latest version ([20.3.47](https://pub.dev/packages/syncfusion_flutter_sliders/versions/20.3.47)) in your application to achieve the requirement.

We thank you for your support and appreciate your patience in waiting for this release. Please contact us if you require any further assistance.

Regards,
Sriram Kiran

**Comment by Sagarz2422** [comment]
Hey @SriramKiranSenthilkumar  it seems the issue is sorted Thanks for the help will be closing the the as it is resolved
