### ISSUE TITLE
How SfCartesianChart only show part of data list?

### ISSUE THREAD

**Issue by ChloeSu** [syncfusion/flutter-widgets#90]
Hi 

I have a data list. The chart graph present is below...
![chart](https://user-images.githubusercontent.com/29650409/102315131-96b16680-3fae-11eb-9d0d-7af382b27c9c.PNG)

I want the screen only show latest 15 records in the beginning and support scroll to view old data(Panning)
How can I do? 

It's my code
```dart
SfCartesianChart(
                    backgroundColor: Color(0xCC0A1F32),
                    margin: EdgeInsets.fromLTRB(20,0,20,0),
                    enableAxisAnimation: true,
                    zoomPanBehavior: ZoomPanBehavior(
                      // Enables pinch zooming
                      enablePanning: true,
                      enablePinching: true,
                      zoomMode: ZoomMode.x
                    ),
                    legend: Legend(
                        position: LegendPosition.top,
                        orientation: LegendItemOrientation.horizontal,
                        isVisible: true,
                        textStyle: TextStyle(color: Color(0x80C4C6C8), fontSize: 16)
                    ),
                    palette:const <Color>[
                      Color(0xFF71AF99),
                      Color(0xFFC4BF92)
                    ],
                    primaryXAxis: CategoryAxis(
                      majorGridLines: MajorGridLines(width: 0),
                      labelIntersectAction: AxisLabelIntersectAction.hide,
                      labelRotation: 320,
                      labelAlignment: LabelAlignment.start,
                      maximumLabels: 10
                    ),
                    primaryYAxis: CategoryAxis(
                      majorGridLines: MajorGridLines(width: 0),
                      labelStyle: TextStyle(color: Color(0xFF71AF99), fontSize: 16),
                      minimum : 0,
                    ),
                    series: <ChartSeries>[
                      LineSeries<ListHistory, dynamic>(
                          name:"hint",
                          dataSource: state..history,
                          dataLabelSettings: DataLabelSettings(
                              isVisible: true,
                              labelAlignment: ChartDataLabelAlignment.top,
                              builder: (dynamic data, dynamic point, dynamic series, int pointIndex, int seriesIndex) {
                                  return Container(
                                      child: Text(data.total_price.toString(),style: TextStyle(color: Color(0xFF71AF99), fontSize: 16))
                                  );
                           }
                          ),
                          markerSettings: MarkerSettings(isVisible: true,borderWidth: 1,height: 4,width: 4),
                          xValueMapper: (ListHistory list, _) => list.service_date,
                          yValueMapper: (ListHistory list, _) => list.total_price
                      )
                    ]
                )
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @ChloeSu,

Greetings from Syncfusion. We have analyzed your scenario with the provided information at our end and we would like to share some information regarding the **visibleMinimum** and **visibleMaximum** properties of the chart axis with which you can be able to set necessary visible range for the chart according to your chart data source. We have also created a simple chart sample with the help of the provided code snippet and screenshot and used the **visibleMinimum** and **visibleMaximum** properties to set a visible range for the chart and with the help of the panning feature, you can pan the chart to view the data outside the visible range. We have also attached the sample below for your reference.

Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/5707969/sample.zip)

Please check with the above-attached sample and revert us if you still have further concerns.

For further reference on the **visibleMinimum** and **visibleMaximum** properties of the chart axis, please check the user guide below.
- **visibleMinimum** - https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-minimum
- **visibleMaximum** - https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#visible-maximum

Regards,
Sriram Kiran

**Comment by ChloeSu** [comment]
thanks a lot!
