### ISSUE TITLE
SfRangeSlider, How do I customize thumbShape?

### ISSUE THREAD

**Issue by myeongseop-sofit** [syncfusion/flutter-widgets#900]
I don't know.
Help me.

![스크린샷 2022-09-27 오후 6 07 16](https://user-images.githubusercontent.com/109493079/192484594-6260cb45-46c1-427e-ab34-dc13e4c3a0ca.png)

**Comment by LokeshPalani** [comment]
Hi @myeongseop-sofit,

You can achieve your requirement by using the [thumbShape](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider/thumbShape.html) property in the [SfRangeSlider](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfRangeSlider-class.html). With this property, you can change the size and shape of the thumb based on your use case. We have shared a user guide documentation for your reference. Please let us know if you need any further assistance.

UG,
https://help.syncfusion.com/flutter/range-slider/shapes#thumb-shape

Regards,
Lokesh.
