### ISSUE TITLE
syncfusion_flutter_pdfviewer License?

### ISSUE THREAD

**Issue by Webierta** [syncfusion/flutter-widgets#901]
I want to know if I need any license to use syncfusion_flutter_pdfviewer 20.2.50-beta in a small open source personal (non-commercial) project that I will publish in the F-Droid repository.
thanks

**Comment by deepika134** [comment]
Hi @Webierta ,

It is required that all developers working on the Flutter app have an active license with Syncfusion.  
Please check if you qualify for our Community License.  If so, please claim one.  
https://www.syncfusion.com/products/communitylicense 
If you are not eligible, let us know and we will have a sales rep contact you.
Once you are properly licensed, we will discuss what is needed for  you to make  your project open source

Regards,
Deepika R
