### ISSUE TITLE
[help] Circular doughnut chart with rounded corners

### ISSUE THREAD

**Issue by emersonsiega** [syncfusion/flutter-widgets#902]
Hi

I'm trying to create a circular chart, with rounded corners, following the prototype bellow:
![image](https://user-images.githubusercontent.com/2227499/192580638-861aa66f-9818-4fa5-b3d1-e22927d68f03.png)

I've tried this with two different approaches, but found some limitations in both cases. I'll describe bellow these approaches and their problems...

1. Using strokeWidth/strokeColor:

I'd created a separated doughnut chart with stroke width and color. This works only if I set CornerStyle.bothFlat. Using bothCurve, a circle is shown at the corners.

#### Using CornerStyle.bothFlat (this is closer to what I want):  

```dart
DoughnutSeries<InvestmentData, String>(
      dataSource: content,
      radius: '100%',
      innerRadius: '90%',
      cornerStyle: CornerStyle.bothFlat,
      strokeWidth: 4,
      strokeColor: Colors.white,
      pointColorMapper: (InvestmentData data, int itemIndex) =>
          getColor(currentIndex, data, itemIndex),
      xValueMapper: (InvestmentData data, int index) => index.toString(),
      yValueMapper: (InvestmentData data, _) => data.percentage,
)
```
![image](https://user-images.githubusercontent.com/2227499/192580674-786e2ff1-52cc-41e9-8b19-325dd7b1e042.png)

#### Using CornerStyle.bothCurve - Strange circle at the corners:  

```dart
DoughnutSeries<InvestmentData, String>(
      dataSource: content,
      radius: '100%',
      innerRadius: '90%',
      cornerStyle: CornerStyle.bothCurve,
      strokeWidth: 4,
      strokeColor: Colors.white,
      pointColorMapper: (InvestmentData data, int itemIndex) =>
          getColor(currentIndex, data, itemIndex),
      xValueMapper: (InvestmentData data, int index) => index.toString(),
      yValueMapper: (InvestmentData data, _) => data.percentage,
)
```
![image](https://user-images.githubusercontent.com/2227499/192580697-8d127716-3a25-42e6-8f96-470014f40f3a.png)

2. Using explodeAll

A doughnut chart using explodeAll is exactly what I need, but it seems to have an alignment issue:

```dart
DoughnutSeries<InvestmentData, String>(
        dataSource: content,
        animationDuration: 800,
        radius: '100%',
        innerRadius: '93%',
        cornerStyle: CornerStyle.bothCurve,
        explode: true,
        explodeGesture: ActivationMode.none,
        explodeAll: true,
        explodeOffset: '2%',
        pointColorMapper: (InvestmentData data, int itemIndex) =>
            getColor(currentIndex, data, itemIndex),
        xValueMapper: (InvestmentData data, int index) => index.toString(),
        yValueMapper: (InvestmentData data, _) => data.percentage,
 )
```
![image](https://user-images.githubusercontent.com/2227499/192580720-797dd71d-9987-4614-afd7-cb448585f745.png)

As you can see above, this result is very similar to what I want, but there's an alignment issue that prevents me to use this approach...

Can you guys have me a help with this issues? Thanks!

**Comment by SriramKiranSenthilkumar** [comment]
Hi @emersonsiega,

Greetings from Syncfusion.

We have analyzed your queries and provided the responses below.

**Query 1:** Using CornerStyle.bothCurve - strange circle at the corners.

We have checked on the above scenario at our end and we are able to replicate the reported issue. We will consider this as a bug and have logged bug report for it regarding “Rendering issue occurs when setting border for doughnut series with corner style set as both sides curved” in our feedback portal. We will fix and include the changes in our weekly patch release which is expected to be rolled out by 18th October 2022. We will update you once the release is rolled out and we appreciate your patience until then.

**Query 2:** Using explodeAll: A doughnut chart using explodeAll is exactly what I need, but it seems to have an alignment issue.

We have checked on the above query and we would like to let you know that exploding all the data points will be rendered like this when the doughnut series has larger [innerRadius](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/innerRadius.html) and so the explodeAll feature will not be feasible for your requirement. We have also ensured this case in Microsoft Excel by providing data points similar to the provided example and the same behavior is occurring in that too. This is the current default behavior.

Regards,
Sriram Kiran

**Comment by natrayansf** [comment]
Hi emersonsiega,

We would like to let you know that the reported issue ‘Rendering issue occurs when setting border for doughnut series with corner style set as both sides curved’ was already fixed and rolled out in our weekly patch release on 18th October 2022. So, we kindly request you to upgrade the SfCircularChart package to the latest version below.

Version link - https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.50 

Regards,
Natrayan
