### ISSUE TITLE
Multi Chart syncronization problem

### ISSUE THREAD

**Issue by miyazk4** [syncfusion/flutter-widgets#903]
Hello, 

I am implementing the Syncfusion charts library for Flutter and am struggling with the following problem:

I have multiple charts and am trying to syncronize their Trackballs, following this guide: https://www.syncfusion.com/kb/11881/how-to-synchronize-trackball-in-multiple-charts-sfcartesianchart

It works properly when I am using the default Trackball, but, when I am building a custom one, it won't appear after the first hide (Example: I have two charts, on the chartMove event for the first one, it displays, when I move onto the next one, the Trackball for the previous Chart won't appear)
![example](https://user-images.githubusercontent.com/61757484/192828819-476e402f-44d5-4599-97e0-518f2bc18269.gif)

Here's the following structure:

```dart
@override
  void initState() {
    _trackballBehavior1 = TrackballBehavior(
      enable: true,
      activationMode: ActivationMode.singleTap,
      builder: (context, trackballDetails) => const Text('Test'),
    );
    _trackballBehavior2 = TrackballBehavior(
      enable: true,
      activationMode: ActivationMode.singleTap,
      builder: (context, trackballDetails) => const Text('Test'),
    );
    super.initState();
  }
```

```dart
SfCartesianChart(
              trackballBehavior: _trackballBehavior2,
              onChartTouchInteractionMove: (ChartTouchInteractionArgs args) {
                // Called the second chart’s trackball show method with pixel position arguments as parameters
                _trackballBehavior1.show(
                    args.position.dx, args.position.dy, 'pixel');
              },
              onChartTouchInteractionDown: (args) {
                _trackballBehavior1.show(
                    args.position.dx, args.position.dy, 'pixel');
              },
              onChartTouchInteractionUp: (args) {
                _trackballBehavior1.hide();
              },
              primaryXAxis: CategoryAxis(),
              series: <ChartSeries>[
                // Initialize line series
                LineSeries<ChartData, String>(
                    dataSource: [
                      // Bind data source
                      ChartData('Jan', 125),
                      ChartData('Feb', 48),
                      ChartData('Mar', 14),
                      ChartData('Apr', 72),
                      ChartData('May', 40)
                    ],
                    xValueMapper: (ChartData data, _) => data.x,
                    yValueMapper: (ChartData data, _) => data.y)
              ],
            ),
```

**Comment by SriramKiranSenthilkumar** [comment]
Hi @miyazk4,

Greetings from Syncfusion.
We have checked your query at our end, and we can replicate the reported issue regarding the trackball tooltip with the builder not getting activated on its show method call after the trackball is dragged using user interaction.

We have considered this as a bug and created a bug report for it in our feedback portal. We will fix this and include the changes in our weekly patch release which is expected to be rolled out on 18th October 2022. We will update you once the release is rolled out and we appreciate your patience until then.

Regards,
Sriram Kiran

**Comment by natrayansf** [comment]
Hi miyazk4,

We would like to let you know that the reported issue ‘Trackball tooltip with the builder not getting activated on its show method call after the trackball is dragged using user interaction’ was already fixed and rolled out in our weekly patch release on 18th October 2022. So, we kindly request you to upgrade the SfCartesianChart package to the latest version below.

Version link – https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.50 

Regards,
Natrayan
