### ISSUE TITLE
[DataGrid] - How to change color and padding - icon filter

### ISSUE THREAD

**Issue by JesusMayuri7** [syncfusion/flutter-widgets#906]
![image](https://user-images.githubusercontent.com/13004243/193052211-ec7ac97a-998f-402a-8b40-e8e632e057c3.png)

Thank's

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @JesusMayuri7,

Currently, DataGrid does not have support for the changing color and padding of the filter icon. We have considered your request as a feature. This feature will be implemented in our 2022 Volume 3 SP release, which is expected to be rolled out at the end of October 2022. We will let you know when this feature is implemented. We appreciate your patience until then. You can follow up with the below feedback for further details,

Feedback Link:  https://www.syncfusion.com/feedback/38108/support-to-change-the-color-of-the-filter-icon-and-change-the-padding    

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @JesusMayuri7,

The support for changing the **color of the filter icon** and **filter icon padding** has been included in the Syncfusion Essential Studio 2022 Volume 4 Main Release version **20.4.38**.

Release Notes: https://help.syncfusion.com/flutter/release-notes/v20.4.0.38?type=all#datagrid
