### ISSUE TITLE
[syncfusion_flutter_sliders] discrete range slider

### ISSUE THREAD

**Issue by AAverin** [syncfusion/flutter-widgets#907]
Main readme mentions `Discrete selection - Provides an option for selecting only discrete numeric and date values`.

I have following range of values: `[0, 100, 200, 300, 400, 500, 1000, 1500, 2000, 2500, 3000, 5000, 7000, 10000, 15000, 20000]`.
How can I build discrete range slider that can jump between those values?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @AAverin,

Greetings from Syncfusion.
We have checked your query at our end, and we would like to let you know that the discrete selection feature allows you to move the thumbs in a discrete manner along the slider. However, we have created a simple sample in which we have achieved your requirement regarding the to move the thumbs in the slider based on the custom range stops and attached the sample below for reference.

Sample: [i410150.zip](https://github.com/syncfusion/flutter-widgets/files/9683127/i410150.zip)


Please check with the sample and get back to us if you require further assistance.

Regards,
Sriram Kiran
