### ISSUE TITLE
[syncfusion_flutter_calendar] Can't change fonts

### ISSUE THREAD

**Issue by Alyxsqrd** [syncfusion/flutter-widgets#908]
Hello! I'm using a custom font in my Flutter app, and luckily I was able to override the TextStyles for a majority of the calendar elements. Unfortunately, the "No selected date"/"No events" box in Agenda and the year text in DatePicker seem to be hardcoded to the Roboto font family with no property in SfCalendar to change their TextStyles.

**Comment by MuniappanSubramanian** [comment]
Hi Alyxsqrd,

Based on the shared information, we have checked and considered this as a feature of “**Provide support to customize the "No Events" and No Selected Date" text in the Flutter Calendar**” and logged a feature report for the same. We will implement this feature in our upcoming 2022 Volume 3 SP1 release, which is expected to roll out in the mid of November 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Now you can track the status of this feature report through the following feedback link.

Feedback link:
https://www.syncfusion.com/feedback/38141/provide-support-to-customize-the-no-events-and-no-selected-date-text-in-the

If you have any more specifications/suggestions for the feature request, you can add them as a comment in the portal and cast your vote to make it count.

Regards,
Muniappan S

**Comment by Alyxsqrd** [comment]
Thank you for implementing this in v20.3.56! 😄
