### ISSUE TITLE
[syncfusion_flutter_calendar] Agenda view "No events" customization

### ISSUE THREAD

**Issue by Alyxsqrd** [syncfusion/flutter-widgets#909]
Hello! It would be useful if there was a property in SfCalendar or AgendaStyle where I could set custom placeholder text such as "No meetings" or "No activities" for empty dates instead of the hardcoded "No events" text. 🙂

**Comment by MuniappanSubramanian** [comment]
Hi Alyxsqrd,

Based on the shared information, we have checked and considered this as a feature of “**Provide support to customize the "No Events" and No Selected Date" text in the Flutter Calendar**” and logged a feature report for the same. We will implement this feature in our upcoming 2022 Volume 3 SP1 release, which is expected to roll out in the mid of November 2022 and let you know once the release is rolled out. We appreciate your patience until then.

Now you can track the status of this feature report through the following feedback link.

Feedback link:
https://www.syncfusion.com/feedback/38141/provide-support-to-customize-the-no-events-and-no-selected-date-text-in-the

If you have any more specifications/suggestions for the feature request, you can add them as a comment in the portal and cast your vote to make it count.

Regards,
Muniappan S

**Comment by Alyxsqrd** [comment]
> Hi Alyxsqrd,
> 
> Based on the shared information, we have checked and considered this as a feature of “**Provide support to customize the "No Events" and No Selected Date" text in the Flutter Calendar**” and logged a feature report for the same. We will implement this feature in our upcoming 2022 Volume 3 SP1 release, which is expected to roll out in the mid of November 2022 and let you know once the release is rolled out. We appreciate your patience until then.
> 
> Now you can track the status of this feature report through the following feedback link.
> 
> Feedback link: https://www.syncfusion.com/feedback/38141/provide-support-to-customize-the-no-events-and-no-selected-date-text-in-the
> 
> If you have any more specifications/suggestions for the feature request, you can add them as a comment in the portal and cast your vote to make it count.
> 
> Regards, Muniappan S

Hi Muniappan, I appreciate the quick response! Unfortunately, it seems there might be some miscommunication. The latest update, 20.3.56, added TextStyle customization as I requested in issue #908, but issue #909 wasn't implemented at all.

To clarify: this issue is requesting a property be added to SfCalendar to customize the **string value** of the placeholder text, not the TextStyle. Sorry if there was any confusion earlier.

**Comment by MuniappanSubramanian** [comment]
**#Regarding Text style support for "No Events" and "No Selected Date" text in the Flutter calendar** 

Syncfusion Essential Studio 2022 Volume 3 Service Pack Release V20.3.0.56 is rolled out with the mentioned feature, "**Provide support to customize the "No Events" and "No Selected Date**" text in the Flutter Calendar." 

Latest version link: https://pub.dev/packages/syncfusion_flutter_calendar/versions 
Release notes link: https://help.syncfusion.com/flutter/release-notes/v20.3.0.56?type=all#calendar 
Changelog link: 
https://pub.dev/packages/syncfusion_flutter_calendar/changelog 

**#Regarding setting custom placeholder text such as "No meetings" or "No activities"** 
This requirement can be achieved by overriding the localization by using the extendibility options in the Flutter calendar. You can refer to our following KB documentation to customize the placeholder text in the Calendar: 

https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar

**Comment by MuniappanSubramanian** [comment]
**#Regarding Text style support for "No Events" and "No Selected Date" text in the Flutter calendar** 

Syncfusion Essential Studio 2022 Volume 3 Service Pack Release V20.3.0.56 is rolled out with the mentioned feature, "**Provide support to customize the "No Events" and "No Selected Date**" text in the Flutter Calendar." 

Latest version link: https://pub.dev/packages/syncfusion_flutter_calendar/versions 
Release notes link: https://help.syncfusion.com/flutter/release-notes/v20.3.0.56?type=all#calendar 
Changelog link: 
https://pub.dev/packages/syncfusion_flutter_calendar/changelog 

**#Regarding setting custom placeholder text such as "No meetings" or "No activities"** 
This requirement can be achieved by overriding the localization by using the extendibility options in the Flutter calendar. You can refer to our following KB documentation to customize the placeholder text in the Calendar: 

https://www.syncfusion.com/kb/12328/how-to-override-the-localization-in-the-flutter-calendar

**Comment by Alyxsqrd** [comment]
Thank you!

**Comment by vgavrilovikj** [comment]
@MuniappanSubramanian like this it forces to change the translation on all variables - in my case the way I use the calendar I only need to change the value of "No events" I do not have to change the other 109 variables.. any help? @Alyxsqrd how did you manage to customize only those fields?
