### ISSUE TITLE
package:flutter/gestures.dart import seems to be missing from syncfusion_flutter_datagrid.dart version 20.3.47

### ISSUE THREAD

**Issue by bismarabia** [syncfusion/flutter-widgets#913]
**import "package:flutter/gestures.dart";** seems to be missing from **syncfusion_flutter_datagrid**.dart version **20.3.47**

I'm getting this error when running the app

../../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.47/lib/src/datagrid_widget/widgets/cell_widget.dart:733:23: Error: 'PointerEnterEvent' isn't a type.
            onEnter: (PointerEnterEvent details) {
                      ^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.47/lib/src/datagrid_widget/widgets/cell_widget.dart:738:22: Error: 'PointerExitEvent' isn't a type.
            onExit: (PointerExitEvent details) {
                     ^^^^^^^^^^^^^^^^

turned out that **import "package:flutter/gestures.dart";** is missing from **syncfusion_flutter_datagrid**.dart file.

syncfusion_flutter_datagrid: ^20.3.47

you should either add import or hide the type as follow:
```dart
MouseRegion(
   onEnter: (details) {
      setState(() {
          isHovered = true;
      });
   },
   onExit: (details) {
       setState(() {
           isHovered = false;
       });
    },
```

could you please check?

**Comment by vitulgoyani** [comment]
Same error got today, Can't solve

**Comment by vitulgoyani** [comment]
thank you but not work for me

**Comment by bismarabia** [comment]
@vitulgoyani you should remove the caret sign ^

**Comment by ashok-kuvaraja** [comment]
Hi @bismarabia,

Based on the provided information, we are unable to reproduce the reported issue in the latest version (syncfusion_flutter_datagrid: ^20.3.47) and the latest Flutter version 3.3.3. So far we analyzed, there might be a flutter cache issue. Please run the `flutter pub cache repair` command in the terminal and check.

If you are still facing the same issue, please provide a simple sample that is reproducible and the current flutter version with the issue reproduced platform to check further. It will be helpful for us to check and provide an appropriate solution.

Regards,
Ashok K

**Comment by bismarabia** [comment]
hi @ashok-kuvaraja 

I don't think it's a flutter cache issue.
My other colleges at work also reported the same issue, when I debugged the source code, mainly cell_widgets.dart inside syncfusion_flutter_datagrid-20.3.47 I found that the import is missing and the clicking on `PointerEnterEvent` and `PointerExitEvent` class doesn't take me to their respective source code.

could you please try with pinning the version at exactly 20.3.47 (by removing the caret sign) as follow:
`syncfusion_flutter_datagrid: 20.3.47`
?

**Comment by bismarabia** [comment]
hi @ashok-kuvaraja 
can it be related to the Flutter version I'm using?

here is Flutter Doctor summary...
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.1.0, on macOS 12.0.1 21A559 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.2)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @bismarabia,

Can you please upgrade your **Flutter SDK version to 3.3.3** (**the latest stable version**) and let us know if you are still facing the same issue? We are unable to reproduce the reported issue with the latest version. We have tested the following sample with the exact **DataGrid version 20.3.47** (without the caret sign) and the latest **Flutter stable SDK version 3.3.3.** It’s working fine on our end. Please check the following sample and let us know if you still face the issue with it?

Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-714218181 

Regards,
Tamilarasan
