### ISSUE TITLE
[syncfusion_flutter_xlsio] RichText formatting for CellStyle

### ISSUE THREAD

**Issue by blueeyestw** [syncfusion/flutter-widgets#915]
Hello, I'm looking for a way to format text inside a single cell with multiple styles. Is there a way to achieve this?

The API only shows how to format the entire cell and not individual text strings inside the cell.
https://pub.dev/documentation/syncfusion_flutter_xlsio/latest/xlsio/CellStyle-class.html

**Comment by KonduruKeerthi** [comment]
Hi blueeyestw 

Greetings from Syncfusion.

This is to inform you that we do not have support for **RichText Formatting** in Syncfusion Flutter XlsIO and do not have any plans to implement this.

Regards,
Keerthi.
