### ISSUE TITLE
Typo in generated_plugin_registrant.dart by syncfusion_flutter_pdfviewer

### ISSUE THREAD

**Issue by odd-terje** [syncfusion/flutter-widgets#919]
- Installed syncfusion_flutter_pdfviewer 20.3.48 by adding to pubspec.yaml
- This generated a dependency for 'package:syncfusion_flutter_pdfviewer_web/pdfviewer_web.dart' in generated_plugin_registrant.dart
- error : Target of URI doesn't exist: 'package:syncfusion_flutter_pdfviewer_web/pdfviewer_web.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

- fix: change dependency to 'package:syncfusion_pdfviewer_web/pdfviewer_web.dart'
 Unsure of cause, but easy manual fix in generated_plugin_registrant.dart.

**Comment by deepika134** [comment]
Hi @odd-terje,

We tried to reproduce the reported issue, but the syncfusion_flutter_pdfviewer: ^20.3.48 package is works fine on our end. Clear the pub cache and check if the issue reproduced on your end. Kindly share the Flutter doctor, this will be helpful for us to proceed further.

Regards,
Deepika Ravi
