### ISSUE TITLE
Gauges: annotation at the bottom of each gauge side, centered

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#92]
Hi,
I am trying to build a gauge similar to this one:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/8345062/102466858-df6d2c00-404f-11eb-9e28-9e94cdc71604.png">
But I don't know how to reproduce the labels "Min" and "Max" for my gauge.

I tried with using `GaugeAnnotation` but I didn't succeed in centering the labels on the respective left/right side of the gauge.
```dart
SfRadialGauge(
      ...,
      annotations: <GaugeAnnotation>[
        ...,
        GaugeAnnotation(
            angle: 180,
            horizontalAlignment: GaugeAlignment.center,
            positionFactor: 1,
            verticalAlignment: GaugeAlignment.near,
            widget: Text("${formatDisplayNumber(minValue)}")),
        GaugeAnnotation(
            angle: 0,
            horizontalAlignment: GaugeAlignment.center,
            positionFactor: 1,
            verticalAlignment: GaugeAlignment.near,
            widget: Text("${formatDisplayNumber(maxValue)}")),
      ],
)
```
The outcome looks like this:
![Screenshot 2020-12-17 at 10 13 06](https://user-images.githubusercontent.com/8345062/102467406-8b167c00-4050-11eb-8490-c691b458f978.png)
But the text "0" and "50" should be centered. Of course I can play around with the `positionFactor`percentage value. Apparently with the current width settings, at `0.92` it seems to center the texts. But it should be centered independently of the used width `GaugeRange` and `RangePointer`.

Any tips on how to best achieve my goal?

**Comment by SriramKiranSenthilkumar** [comment]
Hi @WieFel,

Greetings from Syncfusion. We have analyzed your scenario with the provided information and we have created a simple radial gauge sample similar to the provided screenshot in which we have set the annotations for min and max values which will get centred according to the width of the **GaugeRange**, **RangePointer** and **RadialAxis**. We have also attached the sample below for your reference. Please check with the below-attached sample and revert us if you still have further concerns.

Sample: [annotationsample.zip](https://github.com/syncfusion/flutter-widgets/files/5715999/ghfw92_annotationsample.zip)

Regards,
Sriram Kiran

**Comment by WieFel** [comment]
@SriramKiranSenthilkumar awesome! Thank you so much! :)

**Comment by WieFel** [comment]
@SriramKiranSenthilkumar btw, have you at @syncfusion ever thought about creating a small sample app that contains multiple use-cases of your widgets along with sample code (similar to [Flutter Gallery](https://gallery.flutter.dev/))?

If so, you can take a look at my package [gallerize](https://github.com/WieFel/gallerize) ([pub](https://pub.dev/packages/gallerize))!
It will (hopefully) soon be part of @fluttercommunity widgets. Would be glad if you gave it a try. I can also provide you with a minimal sample app if you want to see how it could be used ;)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @WieFel,

Greetings from Syncfusion. We have analyzed your query at our end and we would like to let you know that we have already implemented a sample browser application which consists of demo samples of our widget types and their features available. We have also attached our flutter examples sample browser link below for your reference.
Sample browser - https://flutter.syncfusion.com/
GitHub Repo - https://github.com/syncfusion/flutter-examples

Also, we will consider your use cases too while creating new samples for our sample browser application in the near future. 

Please get in touch with us if you still have further concerns.

Regards,
Sriram Kiran
