### ISSUE TITLE
Flutter Syncfusion Datagrid-Copy the whole grid as excel compatible format

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#920]
Hi There,
Is there any way to copy the whole grid including merged cells to excel?

Thank you.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

DataGrid provides the support to export the content to Excel with several customization options. We have already provided detailed information about exporting DataGrid content to excel in the below UG link. Please go through this.

UG Document: https://help.syncfusion.com/flutter/datagrid/export-to-excel 

We hope this helps. Please let us know if you need any further assistance with this.

Regards,
Tamilarasan

**Comment by kevinxxq** [comment]
Hi @Tamilarasan-Paranthaman 
Thank you forv your support and example.
Yes, I have implement the feature to export content as excel file.

At this time, I would like to implement the feature to copy contents of datagrid to clipboard.
The culprit is that I don't know which keycode for the merged cell, e.g. tab for cells and "\n" for new line.

Thank you.

**Comment by kevinxxq** [comment]
Hi @Tamilarasan-Paranthaman ,
Thank you, that should be great.

The merged cells are same as "StackedHeaderCell" in sfdatagrid, I would like to know how to keep the cells merged when we take it out from clipboard.
There should be a connecting character to maintain the mergerd status in clipboard just like tab for columns delimiter and "\n" for a new row.

Thank you.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

As of now, DataGrid doesn’t have support for merging row cells. We have already logged the feature request regarding this. We will implement this feature in any of our upcoming releases. At the planning stage for every release cycle, we review all open features. We will let you know when this feature is implemented. You can follow up with the below feedback for further follow-up,

Feedback Link: https://www.syncfusion.com/feedback/23230/support-to-merge-the-rows-and-cells 

As we said earlier, we will implement the copying the cell content feature in any of our upcoming releases, and we will consider this requirement (i.e., copy the merged cell content) in the copying the cell content feature once we provide the support for merged cells.

Regards,
Tamilarasan
