### ISSUE TITLE
Disabling One or More Filter UI Feature

### ISSUE THREAD

**Issue by ashndev** [syncfusion/flutter-widgets#921]
Hi There!

Is there a way to disable one or more UI option from the filter pop up? For example if I want to not be able to filter by number. Can I disable that so that it doesn't show up in the UI?

<img width="612" alt="Screen Shot 2022-10-07 at 7 59 53 PM" src="https://user-images.githubusercontent.com/87834445/194685016-777ea7a7-7688-479e-8641-31bf47d0d531.png">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

Greetings from Syncfusion.

Currently, we are analyzing your requirement. We will validate and update you with the details in two business days. i.e., October 12, 2022. We appreciate your patience and understanding until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

Currently, DataGrid does not have support for disable the number filter from the filter popup menu. We have considered your request as a feature. This feature will be implemented in our 2022 Volume 4 release, which is expected to be rolled out by the mid of December 2022. We will let you know when this feature is implemented. We appreciate your patience until then. You can follow up with the below feedback for further details,

Feedback Link: https://www.syncfusion.com/feedback/38299/support-to-customize-the-filtering-popup-menu-options 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

The support for hiding the filter popup menu options has been included in the Syncfusion Essential Studio 2022 Volume 4 Main Release version **20.4.38.**

Release Notes: https://help.syncfusion.com/flutter/release-notes/v20.4.0.38?type=all#datagrid
