### ISSUE TITLE
How to non-average interval for SfSlider?

### ISSUE THREAD

**Issue by geekdmm0xff** [syncfusion/flutter-widgets#922]
For example, if [min] is 1.0 and [max] is 20.0 and [interval] is [4, 5, 5, 5, 5]
like this:

![dynamic interval slider](https://user-images.githubusercontent.com/10804912/194829634-a8206a9a-b0a7-4d19-91ba-63ea50ab74c9.png)

**Comment by LokeshPalani** [comment]
Hi @geekdmm0xff,

Greetings from Syncfusion.

We have validated your query and we have achieved your requirement by using the  [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html) , [interval](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/interval.html) , and [stepSize](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/stepSize.html) properties in SfSlider. We have set the minimum value as 0, the maximum value as 20, the [interval](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/interval.html) and [stepSize](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/stepSize.html) values as 4, and changed the 0th label value to 1 using  [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html) as per the following code snippet below.

**CODE SNIPPET:**

```
Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion flutter slider'),
          centerTitle: true,
        ),
        body: SfSlider(
          enableTooltip: true,
          value: _value,
          showLabels: true,
          showTicks: true,
          showDividers: true,
          onChanged: (dynamic newValue) {
            setState(() {
              _value = newValue;
            });
          },
          min: 0,
          max: 20,
          interval: 4,
          stepSize: 4.0,
          labelFormatterCallback: (dynamic actualValue, String formattedText) {
            return actualValue == 0 ? '1' : formattedText;
          },
        ),
      ),
    );
  }

```
**OUTPUT:**

![image](https://user-images.githubusercontent.com/105289202/195262255-06e7996f-b3aa-43d3-b128-d3e2f0989ce8.png)


Regards,
Lokesh Palani.

**Comment by geekdmm0xff** [comment]
@LokeshPalani  thanks.
but if stepSize = 1, like this:
![slider_bug](https://user-images.githubusercontent.com/10804912/195305067-e51c5dfb-f8b7-4e05-a20b-e8bdc1e59265.png)

**Comment by LokeshPalani** [comment]
Hi @geekdmm0xff,

Greetings from Syncfusion.

We have validated your query and achieved your requirement by using [tooltiptextFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/tooltipTextFormatterCallback.html) in SfSlider. In [tooltiptextFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/tooltipTextFormatterCallback.html), we have replaced the tooltip value 0 to 1 and restricted the interval value 1 in [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/onChanged.html) method. So, now the tooltip value displayed properly as per slider dragging value. Please refer the following code snippet.

**CODE SNIPPET:**

```
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion flutter slider'),
          centerTitle: true,
        ),
        body: SfSlider(
          tooltipTextFormatterCallback:
              (dynamic actualValue, String formattedText) {
            return actualValue == 0 ? '1' : formattedText;
          },
          onChanged: (dynamic newValue) {
            if (newValue != 1) {
              setState(() {
                _value = newValue;
              });
            }
          },
          stepSize: 1.0,
          min: 0,
          max: 20,
          interval: 4,
          labelFormatterCallback: (dynamic actualValue, String formattedText) {
            return actualValue == 0 ? '1' : formattedText;
          },
          enableTooltip: true,
          value: _value,
          showLabels: true,
          showTicks: true,
          showDividers: true,
        ),
      ),
    );
  }
```
**OUTPUT:**

![image](https://user-images.githubusercontent.com/105289202/195625777-e8c603c8-0650-4f53-a0cf-58b239e82d55.png)


Regards,
Lokesh Palani.

**Comment by geekdmm0xff** [comment]
@LokeshPalani thanks.
But the first interval should be different from the other intervals

**Comment by LokeshPalani** [comment]
Hi @geekdmm0xff,

We have validated your query, we would like to let you know that, currently we don’t have non-linear interval support in SfSlider. So we have achieved your requirement by setting the minimum value to 0 and displaying the 0 value as 1 in the slider label and tooltip with the help of the [labelFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/labelFormatterCallback.html) and the [tooltiptextFormatterCallback](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/tooltipTextFormatterCallback.html). And restricted the interval value as 1 in the [onChanged](https://pub.dev/documentation/syncfusion_flutter_sliders/latest/sliders/SfSlider/onChanged.html) method, hence the slider did not consider the value 1 while dragging it. So only the first interval differs from the other intervals. 

Regards,
Lokesh Palani.

**Comment by geekdmm0xff** [comment]
I know it, but this does not solve the problem perfectly, I hope this function can be added in the future

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @geekdmm0xff ,



We would like to let you know that currently, we don't have support for the non-linear interval in SfSlider. however, we have considered your requirement as a new feature and logged a feature request in our feedback portal.

We will prioritize the features of every release based on demand and priority. So, this feature will be available in any of our upcoming releases. You can also track the status of the feature with the feedback below.



Feedback: [https://www.syncfusion.com/feedback/38545](https://www.syncfusion.com/feedback/38545/provide-non-linear-interval-support-for-sfslider)



Regards,

Yuvaraj.
