### ISSUE TITLE
Can I use point data in SpLineChartseries

### ISSUE THREAD

**Issue by Gslvr** [syncfusion/flutter-widgets#923]
Hi I try to use your SfChart for learning.  I can use SFChartseries but I try to mix with this chart with dot series. 
Maybe I want like this 

https://www.researchgate.net/publication/301719174/figure/fig2/AS:362406233559046@1463415787310/Figur-3-Utviklingen-i-den-relative-lonnsinntektsforskjellen-mellom-99-persentilen-og.png

How I can use dot series (not Line) in SfChart table

**Comment by natrayansf** [comment]
Hi @Gslvr,

Greetings from Syncfusion.

We have validated your query and you can achieve your requirement by using the [scatter series](https://help.syncfusion.com/flutter/cartesian-charts/chart-types/scatter-chart), which is available in chart types. Please refer to the following code snippet.

```
SfCartesianChart(
      series: <ChartSeries>[
         ScatterSeries<ChartData, double>(
             dataSource: chartData,
             xValueMapper: (ChartData data, _) => data.x,
             yValueMapper: (ChartData data, _) => data.y,
             dataLabelMapper: (ChartData data, _) => data.label,
             dataLabelSettings: DataLabelSettings(isVisible: true),
             color: Colors.blueGrey)
       ],
),
````
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/195052286-de75834d-2ade-453c-bd07-f120426afe2e.png)

We have attached a sample for your reference. Please check with the above solution and get back to us if you need further assistance. 

Thanks,
Natrayan

Attachment: [i412362.zip](https://github.com/syncfusion/flutter-widgets/files/9753610/i412362.zip)
