### ISSUE TITLE
How to draw straight lines in chart

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#928]
Hi There,
I would like to draw one or more straight lines in the chart:
![image](https://user-images.githubusercontent.com/55800697/195993900-c32886b7-94f6-4a40-930f-d9dbcf16c678.png)

The lines intend to indicate the standard(or expectations) of series, so it would be better to add a list<T> to the StackedLineSeries:

`listStraightLine:<num>[num1,num2], `
or something more complex for custom settings like StraightLine(color, width, dash) and so on.

Thank you.

**Comment by natrayansf** [comment]
Hi @kevinxxq,

Greetings from Syncfusion.

We have validated your query and you can achieve your requirement ‘Draw one or more straight lines in the chart’ by using the [PlotBand](https://help.syncfusion.com/flutter/sfcartesianchart/axis-customization#plot-bands) feature which is available in chart axis. PlotBand renders below the series by default, however, you can change its rendering order with help of [shouldAlwaysAboveSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/PlotBand/shouldRenderAboveSeries.html) property. Please refer to the following code snippet.
```
SfCartesianChart(
     primaryYAxis: NumericAxis(
           plotBands: <PlotBand>[
               PlotBand(
                   isVisible: true,
                   start: 95,
                   end: 95,
                   borderWidth: 2,
                   borderColor: Colors.black,
                   shouldRenderAboveSeries: true,
              ),
              PlotBand(
                   isVisible: true,
                   start: 105,
                   end: 105,
                   borderWidth: 2,
                   borderColor: Colors.black,
                   shouldRenderAboveSeries: true,
              ),
         ],
    ),
)
```
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/196188608-4e09b625-0a4e-4f08-9303-d4e0e3743c4e.png)

Please check with the above solution and get back to us if you need further assistance. 

Thanks,
Natrayan
