### ISSUE TITLE
How to hide/show title and label of axis in Chart

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#929]
Hi there,
I would like to hide/show the  title and label of a chart, is there a way to achieve it?
For title, I have achieve it by setting the title:null to hide it. Is there any elegant way?

e.g. how to hide "3"?
![image](https://user-images.githubusercontent.com/55800697/195995294-cbc04a48-3315-4ead-b996-2f2835e8c7a8.png)

Thank you.

**Comment by LokeshPalani** [comment]
Hi @Kevinxxq,

Greetings from Syncfuison,

We have validated your query and we have achieved your requirement by using [axisLabelFormatter](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter) callback in axis. To hide the labels, We have returned the empty string in all axis labels using this [axisLabelFormatter](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#axislabelformatter). Please refer the following code snippet below.

CODE SNIPPET:

```
 Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Syncusion flutter charts'),
          centerTitle: true,
        ),
        body: SfCartesianChart(
          primaryXAxis: CategoryAxis(
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              return ChartAxisLabel('', details.textStyle);
            },
            majorGridLines: const MajorGridLines(width: 0),
            majorTickLines: const MajorTickLines(width: 0),
          ),
          primaryYAxis: NumericAxis(
            isVisible: false,
            majorTickLines: const MajorTickLines(width: 0),
            majorGridLines: const MajorGridLines(width: 0),
          ),
          series: <ChartSeries<ChartSampleData, int>>[
            ColumnSeries<ChartSampleData, int>(
                dataSource: chartData,
                dataLabelSettings: const DataLabelSettings(isVisible: true),
                xValueMapper: (ChartSampleData sales, _) => sales.x,
                yValueMapper: (ChartSampleData sales, _) => sales.y),
          ],
        ),
      ),
    );
  }
}

class ChartSampleData {
  ChartSampleData(this.x, this.y);
  final int? x;
  final double? y;
}

final List<ChartSampleData> chartData = [
  ChartSampleData(0, 50.56),
  ChartSampleData(1, 49.42),
  ChartSampleData(2, 53.21),
  ChartSampleData(3, 42.78),
  ChartSampleData(4, 59.97),
];
```
OUTPUT:

![image](https://user-images.githubusercontent.com/105289202/196187913-141c6016-9268-44c4-9c44-e45cadb31b93.png)

Regards,
Lokesh Palani.

**Comment by kevinxxq** [comment]
Hi @LokeshPalani 
Thank you for the support.

It works good, thank you.
