### ISSUE TITLE
Customizing Checkbox Filter Options and Advanced Filter Suggestions in the Data Grid

### ISSUE THREAD

**Issue by ashndev** [syncfusion/flutter-widgets#930]
Hi There, 

For my data grid I load my data from the server using a stream and I also have APIs set up to do the filtering from the server. Currently the filter pop-up you have displays the checkbox filter options and the advanced filter suggestions based on the data currently present in the DataGridSource. The issue I am having is that I do not seem to have a way to specify the options that show up for the checkbox filter options and the advanced filter suggestions. I would like to be able to specify what shows up for those widgets and then when a filter is selected make an API call based on the selection. 

Do you by any chance support something like that and if you don't are you able to create support for such functionality? 

Thanks so much in advance!

<img width="640" alt="Screen Shot 2022-10-16 at 2 57 51 PM" src="https://user-images.githubusercontent.com/87834445/196060307-cbb96d32-d871-4ec8-9e2e-22b70252da8d.png">

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

By default, we will show the options in the checkbox filter that you have set for the respective column in the DataGridSource. Also, DataGrid doesn’t have the support to load the options manually in the checkbox filter. Please let us know if you want to call the API when applying a filter in the DataGrid to filter the respective record from the server side. Could you please tell us more about your requirements? It will be helpful for us to check and provide an appropriate solution.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

Thank you for the detailed information about your requirements.

Can you please let us know whether you are using the load more feature (i.e., **calling the API for another batch of rows when scrolling down the DataGrid**) or getting all the data from the server by calling the API at initial load itself?

Regards,
Tamilarasan

**Comment by ashndev** [comment]
Hi @Tamilarasan-Paranthaman, 

I am loading batches of data from the server as the user scrolls and updating the data grid based on that. Being able to load the grid data as well as the filter data in the ways I described is important because I am dealing with very large data sets of up to several thousand records.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

As of now, Flutter SfDataGrid does not have support for performing asynchronous operation in UI filtering. We have considered your request as a feature. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.   

You can also communicate with us regarding the open features any time using our Feature Report page.    

Feedback link:  https://www.syncfusion.com/feedback/38552/support-to-perform-ui-filtering-asynchronously 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.   


Regards,
Tamilarasan

**Comment by ashndev** [comment]
Hi @Tamilarasan-Paranthaman, 

Thanks for looking into this. I have one more question. I work for CMiC (https://cmicglobal.com/) and our VP of Product has been trying to get in touch with someone from Syncfusion's sales team for about a week now. He tried calling the number on your website (+1 888.936.8638) and emailing sales@syncfusion.com, but hasn't been able to get a hold of anyone. Can you tell me what the best way to get in touch with someone from sales is? Thanks!

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

Thanks for the update. And we have alerted our sales team from our side. They will get in touch with you. Please let us know if you have any concerns.

Regards,
Tamilarasan

**Comment by ashndev** [comment]
Thanks @Tamilarasan-Paranthaman. Do you know how they will reach out? Just want to make sure they have got the email from our end and have the appropriate contact info.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ashndev,

They will get back to you via email. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @ashndev,

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Ashok K
