### ISSUE TITLE
[syncfusion_flutter_datagrid] How to set padding grid with vertical scroll ?

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#931]
Hi There,
Thank you for your support.

I just copied the title from #692. It works well for the horizontal scroll. But I need that for the vertical scrolling.

I also checked the issue #579 , the [cellEndPadding](https://pub.dev/documentation/syncfusion_flutter_calendar/latest/calendar/SfCalendar/cellEndPadding.html) may be a good workarround.

Thank you.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

Currently, we are analyzing your requirement. We will validate and update you with the details in two business days. i.e., October 20, 2022. We appreciate your patience and understanding until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

Sorry for the inconvenience. 

We are still validating your query at our end. We will validate and update you with the details on October 21, 2022. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

As of now, Flutter SfDataGrid does not have support for setting padding between DataGrid and Scrollbar. We have considered your request as a feature. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.   

You can also communicate with us regarding the open features any time using our Feature Report page.    

Feedback Link:  https://www.syncfusion.com/feedback/38675/support-to-set-the-padding-between-datagrid-and-the-vertical-and-horizontal 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.   


Regards,
Tamilarasan
