### ISSUE TITLE
[syncfusion_flutter_datepicker] [help] Rounded selection range

### ISSUE THREAD

**Issue by fakekey** [syncfusion/flutter-widgets#932]
It's possible to make selection range on row rounded? As seen in the image.
Current:
![current](https://user-images.githubusercontent.com/72339471/196090707-ce2efe63-6295-4c3a-99c1-6af4b37aa30f.png)
Expect:
![expect](https://user-images.githubusercontent.com/72339471/196090731-5834a553-70e1-472e-8172-a734f7b0771e.png)

**Comment by MuniappanSubramanian** [comment]
Hi fekekey,

**# Regarding the Rounded selection range**
We have checked your requirement and as per the current implementation of the Flutter DataRangePicker, we don’t have direct support for this. You can achieve your requirement by customizing the month cell using ‘cellBuilder’ widget from DataRangePicker.  You can refer to our following KB documentation to achieve your requirement.

https://www.syncfusion.com/kb/12860/how-to-use-multi-colors-for-multi-range-selection-in-the-flutter-date-range-picker

Note: In this KB, we have customized the cell and selection, based on your requirement you can modify it.

Please refer to our UG documentation to know more details about cell builder support in DateRangePicker,
https://help.syncfusion.com/flutter/daterangepicker/builders#cell-builder


We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muniappan S

**Comment by fakekey** [comment]
Hi @MuniappanSubramanian 

I couldn’t have done it without you.
Thank you!
