### ISSUE TITLE
 Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by Mbouziani** [syncfusion/flutter-widgets#933]
Restarted application in 811ms.
Reloaded 8 of 1628 libraries in 1 566ms.
Reloaded 8 of 1628 libraries in 1 456ms.
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/chart/base/chart_base.dart:1826:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/chart/base/chart_base.dart:1835:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());

                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/circular_chart/base/circular_base.dart:949:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {

                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/circular_chart/base/circular_base.dart:963:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());

                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/funnel_chart/base/funnel_base.dart:720:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {

                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/funnel_chart/base/funnel_base.dart:732:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());

                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/pyramid_chart/base/pyramid_base.dart:714:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/pyramid_chart/base/pyramid_base.dart:725:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());
                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:561:39: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
            SchedulerBinding.instance.addPostFrameCallback(
                                      ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:666:11: Error: No named parameter with the name 'thumbVisibility'.
          thumbVisibility: widget.shouldAlwaysShowScrollbar,
          ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:685:11: Error: No named parameter with the name 'thumbVisibility'.
          thumbVisibility: widget.shouldAlwaysShowScrollbar,
          ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:724:25: Error: No named parameter with the name 'thumbVisibility'.
                        thumbVisibility: widget.shouldAlwaysShowScrollbar,
                        ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:743:23: Error: No named parameter with the name 'thumbVisibility'.
                      thumbVisibility: widget.shouldAlwaysShowScrollbar,
                      ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:763:19: Error: No named parameter with the name 'thumbVisibility'.
                  thumbVisibility: widget.shouldAlwaysShowScrollbar,
                  ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/chart/base/chart_base.dart:1826:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {

                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/chart/base/chart_base.dart:1835:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());
                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/circular_chart/base/circular_base.dart:949:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/circular_chart/base/circular_base.dart:963:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());
                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/pyramid_chart/base/pyramid_base.dart:714:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {
                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/pyramid_chart/base/pyramid_base.dart:725:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());
                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/funnel_chart/base/funnel_base.dart:720:35: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
        SchedulerBinding.instance.addPostFrameCallback((_) {

                                  ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_charts-20.3.49/lib/src/funnel_chart/base/funnel_base.dart:732:37: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

          SchedulerBinding.instance.addPostFrameCallback((_) => _refresh());
                                    ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:561:39: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

            SchedulerBinding.instance.addPostFrameCallback(
                                      ^^^^^^^^^^^^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:666:11: Error: No named parameter with the name 'thumbVisibility'.
          thumbVisibility: widget.shouldAlwaysShowScrollbar,
          ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:685:11: Error: No named parameter with the name 'thumbVisibility'.
          thumbVisibility: widget.shouldAlwaysShowScrollbar,
          ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:724:25: Error: No named parameter with the name 'thumbVisibility'.
                        thumbVisibility: widget.shouldAlwaysShowScrollbar,

                        ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({

        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:743:23: Error: No named parameter with the name 'thumbVisibility'.
                      thumbVisibility: widget.shouldAlwaysShowScrollbar,

                      ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({

        ^^^^^^^^^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.3.49/lib/src/legend/legend.dart:763:19: Error: No named parameter with the name 'thumbVisibility'.
                  thumbVisibility: widget.shouldAlwaysShowScrollbar,
                  ^^^^^^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/material/scrollbar.dart:75:9: Context: Found this candidate, but the arguments don't match.
  const Scrollbar({
        ^^^^^^^^^

**Comment by LokeshPalani** [comment]
Hi @Mbouziani,

We tried to replicate the reported issue regarding **Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null** at our end. Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure on what scenario the issue is replicating. So, we kindly request you to try to replicate the reported issue in the below attached test sample and revert us so that it will help us assist you in a better way.

Regards,
Lokesh.

[chart_472709.zip](https://github.com/syncfusion/flutter-widgets/files/11734880/chart_472709.zip)

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest charts version.
