### ISSUE TITLE
syncfusion data grid issue when running the app

### ISSUE THREAD

**Issue by arv-aks** [syncfusion/flutter-widgets#934]
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.50/lib/src/datagrid_widget/widgets/cell_widget.dart:733:23: Error: 'PointerEnterEvent' isn't a type.
            onEnter: (PointerEnterEvent details) {
                      ^^^^^^^^^^^^^^^^^
../../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_datagrid-20.3.50/lib/src/datagrid_widget/widgets/cell_widget.dart:738:22: Error: 'PointerExitEvent' isn't a type.
            onExit: (PointerExitEvent details) {
                     ^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @arv-aks,

We suspect that you are using an older version of the Flutter SDK. We are unable to reproduce the reported issue with the latest version. It’s working fine on our end. If you're using an older version, can you please upgrade your **Flutter SDK version to 3.3.4** (the latest stable version) and let us know if you are still facing the same issue?

Regards,
Tamilarasan
