### ISSUE TITLE
[syncfusion_flutter_sliders] How to change label text font-size?

### ISSUE THREAD

**Issue by agent515** [syncfusion/flutter-widgets#936]
It is visible in the attached image that labels seem crowded and few are overlapping. I used `labelFormatterCallback` to have these custom labels but could not find a way to modify their font size. I would like to know the way if there's one.

<img src="https://user-images.githubusercontent.com/46898603/196933962-9ec8969e-0b3f-4836-b3d4-8db7493f5552.jpeg" 
width=400 />

**Comment by PraveenGopalsamy** [comment]
Hi,

We have checked your query on our end. You can customize the active and inactive label style using the [SfSliderThemeData.activeLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/activeLabelStyle.html) and [SfSliderThemeData.inactiveLabelStyle](https://pub.dev/documentation/syncfusion_flutter_core/latest/theme/SfSliderThemeData/inactiveLabelStyle.html) properties. For detailed information, Kindly check the below live user guide documentation link.

**Customize Label Style** - https://help.syncfusion.com/flutter/slider/labels-and-divider#label-style

We hope the above solution will resolve your requirement. Please let us know if you need any further assistance with this.

Regards,
Praveen G.

**Comment by agent515** [comment]
Thanks, @PraveenGopalsamy.

That resolved the issue. 👍
