### ISSUE TITLE
scrolling not smoothly

### ISSUE THREAD

**Issue by devappbox** [syncfusion/flutter-widgets#938]
Hello,

I have this code

SfCartesianChart(
            title: ChartTitle(text: 'Half yearly sales analysis'),
            // Enable legend
            legend: Legend(isVisible: true),
            tooltipBehavior: _tooltip,
            enableAxisAnimation: true,
            primaryXAxis: CategoryAxis(
                title: AxisTitle(text: "X"),
                plotOffset: 20,
                visibleMinimum: 0,
visibleMaximum: 3
                interval: 1,
                labelIntersectAction: AxisLabelIntersectAction.hide),
            primaryYAxis: NumericAxis(
              minimum: 0,
              maximum: 100,
              interval: 10,
              title: AxisTitle(text: "Y"),
            ),
            zoomPanBehavior: ZoomPanBehavior(
              enablePanning: true,
            ),
            series: <CartesianSeries<ChartData, String>>[
              ColumnSeries(
                dataLabelSettings: DataLabelSettings(
                    // Renders the data label
                    isVisible: true),
                dataSource: chartData!,
                xValueMapper: (ChartData data, _) => data.x,
                yValueMapper: (ChartData data, _) => data.y,
              ),
              ColumnSeries(
                dataLabelSettings: DataLabelSettings(
                    // Renders the data label
                    isVisible: true),
                dataSource: chartData!,
                xValueMapper: (ChartData data, _) => data.x,
                yValueMapper: (ChartData data, _) => data.y,
              ),
              ColumnSeries(
                dataLabelSettings: DataLabelSettings(
                    labelAlignment: ChartDataLabelAlignment.top,
                    // Renders the data label
                    isVisible: true),
                dataSource: chartData!,
                xValueMapper: (ChartData data, _) => data.x,
                yValueMapper: (ChartData data, _) => data.y,
              )
            ],
          );

How to make scrolling horizontal smoothly ?

**Comment by LokeshPalani** [comment]
Hi devappbox,

Greetings from Syncfusion.

We have validated your code snippet and we would like to let you know that you have enabled the [enableAxisAnimation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/enableAxisAnimation.html) property in chart. If the [enableAxisAnimation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/enableAxisAnimation.html) property is set to true, the gridlines, tick lines and labels will be animated while zooming the chart. So, we suggest you to set [enableAxisAnimation](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/enableAxisAnimation.html) to false in your application to scroll smoothly.

Regards,
Lokesh Palani.

**Comment by devappbox** [comment]
Ok I will try.

Thank's
