### ISSUE TITLE
[synfusion_flutter_datagrid] Default Icon when sorting is activated

### ISSUE THREAD

**Issue by sibaHofer** [syncfusion/flutter-widgets#939]
Pls add a possibilty to not show the DefaultSortingIcon even when sorting is active. It takes too much space on smaller screen like on smartphone.

ps: Demo in pubdev readme is not up to date. Default icon is not displayed when sorting is active

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @sibaHofer,

Greetings from Syncfusion.

As per your requirement, you can achieve that by using the **Builder** widget through the **SfDataGridThemeData.sortIcon.** You can change the icon based on each state of the sorting.  If the sort direction is not ascending or descending return the **SizedBox** for the unsorted icon. We have prepared a sample for that. Please check the following sample and code snippet.

```dart
import 'package:syncfusion_flutter_core/theme.dart';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter SfDataGrid')),
      body: SfDataGridTheme(
        data: SfDataGridThemeData(
          sortIcon: Builder(
            builder: (context) {
              Widget? icon;
              String columnName = '';
              context.visitAncestorElements((element) {
                if (element is GridHeaderCellElement) {
                  columnName = element.column.columnName;
                }
                return true;
              });
              var column = _employeeDataSource.sortedColumns
                  .where((element) => element.name == columnName)
                  .firstOrNull;
              if (column != null) {
                if (column.sortDirection == DataGridSortDirection.ascending) {
                  icon = const Icon(Icons.arrow_upward_outlined, size: 16);
                } else if (column.sortDirection ==
                    DataGridSortDirection.descending) {
                  icon = const Icon(Icons.arrow_downward_outlined, size: 16);
                }
              }
              return icon ?? const SizedBox();
            },
          ),
        ),
        child: SfDataGrid(
            allowSorting: true,
            source: _employeeDataSource,
            columns: getColumns,
            columnWidthMode: ColumnWidthMode.fill),
      ),
    );
  }
}

```
Sample Link: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/9848966/sample.zip)


We hope this helps. We have already provided detailed information about custom sort icon in the below UG link. Please go through this.

UG Documentation: https://help.syncfusion.com/flutter/datagrid/sorting#set-a-custom-sorting-icon   

Regards,
Tamilarasan
