### ISSUE TITLE
[PDFViewer]Support user interaction

### ISSUE THREAD

**Issue by rs5173** [syncfusion/flutter-widgets#94]
Thank you very much for providing such a powerful package, is it possible to support user interaction?

Add a callback when a element(Text, Image, hyperlink, etc) clicked. like

```
// get a text
onTextClick: (text) {

}

// get a image
onImageClick: (image) {

}

// get a url
onUrlClick: (url) {

}

...

```

thanks!

**Comment by dillibabun** [comment]
Hi @rs5173 

Greetings from Syncfusion.

By wrapping GestureDetector over SfPdfViewer widget, the user interaction in the widget can be identified. Currently, we don’t have support to identify the user interaction with PDF document specific elements (text, image, hyperlink and etc..). Kindly share us the complete use case or scenario in which this feature is required. Based on your requirement, we will analyze and provide a prompt solution at the earliest. 

Regards,
Dilli babu.

**Comment by meutraa** [comment]
onUrlClick would be to open a url in external/internal browser.

onImageClick would be to save image to the device, send to another application, or open a UI to zoom in on the image specifically.

**Comment by dillibabun** [comment]
Hi @meutraa ,

We will check the feasibilities for onUrlClick and onImageClick callbacks and share the details on or before 31 December 2020.  Kindly share us your requirement for using onTextClick which will be helpful for us to investigate further on this.

Regards,
Dilli babu.

**Comment by meutraa** [comment]
I do not see a use case for onTextClick; the ability to select text is already exposed by the library.

Perhaps to provide a dictionary lookup for a word.

**Comment by ramkumarsync** [comment]
Hi @meutraa,

Thank you for your update.

The use case to provide a dictionary lookup for the required/selected word can be achieved using the **onTextSelectionChanged** callback available in our SfPdfViewer widget. Please find the document link from below,

https://help.syncfusion.com/flutter/pdf-viewer/text-selection#text-selection-changed-callback  

The feasibility analysis to support the onUrlClick and onImageClick callbacks are still under progress. We will share the details on the same on or before January 5, 2020, without any further delay.  

Regards,
Ramkumar

**Comment by dillibabun** [comment]
Hi @meutraa,

Thank you for your patience.

Yes, it is feasible to achieve your requirement with help of hyperlink and extract image support in SfPdfViewer. At present,  we do not have support for hyperlink and extract image. We do not have any immediate plans to implement these feature. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest.

The status of these features can be tracked using following links.
https://www.syncfusion.com/feedback/21134/support-for-hyperlink 
https://www.syncfusion.com/feedback/21130/support-for-extracting-the-images-from-pdf-document

Regards,
Dilli babu.

**Comment by dillibabun** [comment]
Hi All ,

In SfPdfViewer, we have used different gestures to detect the different tapping, panning, and zooming. As per flutter architecture, a gesture that is detected first will trigger its callback and the remaining gestures will be rejected. Since gestures inside SfPdfViewer are detected first, gestures subscribed in main.dart is not invoked. To overcome this issue, we recommended using RawGestureDetector over SfPdfViewer which is illustrated in the following codes.
```

import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
void main() {
  runApp(MaterialApp(
    title: 'Syncfusion PDF Viewer Demo',
    home: HomePage(),
  ));
}
/// Represents Homepage for Navigation
class HomePage extends StatefulWidget {
  @override
  _HomePage createState() => _HomePage();
}
class _HomePage extends State<HomePage> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  @override
  void initState() {
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter PDF Viewer'),
          actions: <Widget>[
            IconButton(
              icon: const Icon(
                Icons.bookmark,
                color: Colors.white,
              ),
              onPressed: () {
                _pdfViewerKey.currentState?.openBookmarkView();
              },
            ),
          ],
        ),
        body: RawGestureDetector(
          gestures: {
            AllowMultipleGestureRecognizer:
            GestureRecognizerFactoryWithHandlers<
                AllowMultipleGestureRecognizer>(
                  () => AllowMultipleGestureRecognizer(),  //constructor
                  (AllowMultipleGestureRecognizer instance) {  //initializer
                instance.onTap = () => print('tap');
                instance.onTapUp = (TapUpDetails details) => print('tap up');
                instance.onTapDown = (TapDownDetails details) => print('tap down');
              },
            )
          },
          child: SfPdfViewer.asset(
            'assets/sample.pdf',
            key: _pdfViewerKey,
          ),)
    );
  }
}
///
class AllowMultipleGestureRecognizer extends TapGestureRecognizer {
  @override
  void rejectGesture(int pointer) {
    acceptGesture(pointer);
  }
}
```

Regards,
Dilli babu.
