### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Scroll zoom in WebMobile

### ISSUE THREAD

**Issue by adriancsbna** [syncfusion/flutter-widgets#943]
I am trying to implement syncfusion_flutter_pdfviewer: ^20.3.50
in an App and in Web, when the screen is small (mobile size) when you scroll up with the mouse, a zoom is applied.
On desktop size it does not happen.

What could be happening?

It happens even in the SyncFusion example:
https://flutter.syncfusion.com/#/pdf-viewer/getting-started

**Comment by deepika134** [comment]
Hi Adrian Casabuena Sáez,

We can replicate the reported issue on our side. We are checking on this and will update the further details on November 1, 2022.

Kindly conform us whether you are facing the same issue in the video and and you can download it from the below link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/GITHUB~11109499979.zip 

Regards,
Deepika R

**Comment by adriancsbna** [comment]
Hi. Thank you for replying.

Yes, exactly that is the problem I am referring to.

Best regards

**Comment by deepika134** [comment]
To resolve the issue , Please use the below package.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.3.58
