### ISSUE TITLE
TooltipBehavior Customize prompt text

### ISSUE THREAD

**Issue by devyueyue** [syncfusion/flutter-widgets#944]
How to display the icons in the pop-up frame dynamically? Some Chinese characters need to be spliced。

https://user-images.githubusercontent.com/96807013/197948925-888044fd-495b-4a8f-a94c-50b45c2c4ca7.png

![image](https://user-images.githubusercontent.com/96807013/197948925-888044fd-495b-4a8f-a94c-50b45c2c4ca7.png)

**Comment by SriramKiranSenthilkumar** [comment]
Hi @devyueyue,

Greetings from Syncfusion. We have checked your query at our end, and we would like to let you know that you can customize the tooltip content using any of the following ways.

- By using the [onTooltipRender](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/onTooltipRender.html) call back, you can customize the content, header content of the tooltip with the help of the available arguments.
User guide: https://help.syncfusion.com/flutter/cartesian-charts/callbacks#ontooltiprender

- By using the tooltip template feature, you can customize the appearance by using your own widget using the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TooltipBehavior/builder.html) property.
User guide: https://help.syncfusion.com/flutter/cartesian-charts/tooltip#tooltip-template

Please check with the above solutions and let me know if you have further concerns.

Regards,
Sriram Kiran
