### ISSUE TITLE
[syncfusion_flutter_calendar] Resource name max lines

### ISSUE THREAD

**Issue by CripyIce** [syncfusion/flutter-widgets#947]
Hi,
It seems like resource's name `_namePainter.maxLines` is a fixed value of `1`.
Any way of being able to change it so I can make the text size larger without losing any text?
Thanks.

**Comment by MuniappanSubramanian** [comment]
Hi Cripyice,

**#Regarding Resource name max lines**
We have checked your requirement and you can achieve your requirement by customizing the resource view header using the “**ResourceViewHeaderBuilder**” support from the Flutter calendar.

Please refer to our following KB documentation to customize the resource view header in the calendar,
https://www.syncfusion.com/kb/12883/how-to-use-resource-builder-in-the-flutter-calendar-sfcalendar

Please refer to our UG documentation to know more details about resource view header builder support in the Calendar,
https://help.syncfusion.com/flutter/calendar/builders#resource-view-header-builder

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Muniappan S.
