### ISSUE TITLE
[PDFViewer]Edit existing pdf and save

### ISSUE THREAD

**Issue by rs5173** [syncfusion/flutter-widgets#95]
Thank you very much for providing such a powerful package, is it possible to support editable?Such as changing the text color, adding or deleting text, etc.

thanks!

**Comment by dillibabun** [comment]
Hi @rs5173 

Greetings from Syncfusion.

SfPdfViewer widget is a viewer for existing PDF document. The scope of this widget to view the PDF document so it is not possible to edit the existing PDF document and save it. Kindly share us your complete requirement/use case which will be helpful for us to provide appropriate solution at the earliest. 

Regards,
Dilli babu.
