### ISSUE TITLE
Iowa not recognized in primaryValueMapper of MapShapeSource

### ISSUE THREAD

**Issue by mlars84** [syncfusion/flutter-widgets#952]
**Issue**: When using the `MapShapeSource` and passing data to the `primaryValueMapper`, `Iowa` is not recognized, but `Lowa` is. We are currently using a hardcoded ternary to get around this: 
```
primaryValueMapper: (int index) =>
          mapData[index].state == 'Iowa' ? 'Lowa' : mapData[index].state!,
```
**Version**: v.20.2.43

**Comment by PraveenGopalsamy** [comment]
Hi,

In the [MapShapeSource](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSource-class.html), the value specified for the [shapeDataField](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSource/shapeDataField.html) will be used to map with the respective value returned in
 [primaryValueMapper](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSource/primaryValueMapper.html). So, check whether you are passing the exact string in the [primaryValueMapper ](https://pub.dev/documentation/syncfusion_flutter_maps/latest/maps/MapShapeSource/primaryValueMapper.html)as like in the given GeoJSON source. We have attached the sample for your reference. Also, we suggest you to use the [latest version](https://pub.dev/packages/syncfusion_flutter_maps/versions) of our SfMaps.

To know more about JSON mapping, you can check the following user guide documentation. 

﻿﻿https://help.syncfusion.com/flutter/maps/getting-started#mapping-the-data-source-for-shape-layer

**Attachment:** [i416930_maps.zip](https://github.com/syncfusion/flutter-widgets/files/9909513/i416930_maps.zip)

Regards,
Praveen G.

**Comment by mlars84** [comment]
Thanks @PraveenGopalsamy! There was an issue with the GeoJSON.
