### ISSUE TITLE
[synfusion_flutter_datagrid] multiple rows selection UX on desktop

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#953]
Currently when `SfDataGrid` has property `selectionMode: SelectionMode.multiple`, on desktop platforms (web, windows and macos) a single click on a row adds or removes clicked row to the selection. This is very different from the row selection user experience on those platforms. Also a double-click on the row also adds/removes it from selection (regardless of the `onCellDoubleTap` callback provided or not).

This behaviour is good for Android and iOS, but it is not the same on desktop. E.g. compare it with platform native UIs like Windows Explorer or MacOS Finder:

* a single click on a row changes selection to that row
* double click selects that row and clears other selected rows
* to select multiple rows you have to use modifier keys ctrl or shift

It would be great if `SfDataGrid` provided an option to match the native platform UI experience.

Also on all platforms if the `onCellDoubleTap` callback is provided it should alter selection UX, so the doubletap won't change the selected rows.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov,

As of now, DataGrid doesn’t have the support for that. We are not entirely sure about the `onCellDoubleTap` (Also on all platforms, if the onCellDoubleTap callback is provided, it should alter the selection UX, so the double-tap won't change the selected rows) requirement. Can you provide more detailed information about the **onCellDoubleTap** requirement? Only then can we validate and proceed further.

Regards,
Tamilarasan

**Comment by KevinBeckers** [comment]
Is there a workaround to get the expected UX on desktop?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov / @KevinBeckers,

As of now, Flutter SfDataGrid does not have support for performing platform native selection (extended selection). We have considered your request as a feature. We will implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.   

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.   

Feedback: https://www.syncfusion.com/feedback/41135/support-to-perform-the-extended-selection-on-datagrid 

If you have any more specification/suggestions to the feature request, you can add it as a comment in the portal and cast your vote to make it count.   

Regards,
Tamilarasan
