### ISSUE TITLE
[SfCartesianChart] onLegendTapped how to double tap on legend to show one series, again double tap on legend to show all series again.

### ISSUE THREAD

**Issue by ilshookim** [syncfusion/flutter-widgets#955]
I used to SfCartesianChart in my open source project. in here like this
: https://github.com/ilshookim/simple-electron-nodejs-flutter-web/blob/master/lib/report.dart

I want that double tap on a legend to show one series also other all to hide, and again double tap on the legend to show all series again.

Question. Can I make this with onLegendTapped?

Actually when I have 9 series in a chart,
I was tapped on each legend until 8 times to see just one focused series.
Maybe did you understand in this situation?

Double tap on legend to show one series, again double tap on legend to show all series again.

How to make it? Do you have sample or snippets?

**Comment by natrayansf** [comment]
The requirement ‘’how to double tap on legend to show one series, again double tap on legend to show all series again’’ can be achieved by using the [legendItemBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/legendItemBuilder.html) property of legend and setting the [toggleSeriesVisibility](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/toggleSeriesVisibility.html) as false.  The text widget inside the GestureDetector in [legendItemBuilder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/Legend/legendItemBuilder.html) should be wrapped and the series visibility in [onDoubleTap](https://api.flutter.dev/flutter/widgets/GestureDetector/onDoubleTap.html) method available in GestureDetector class has to be changed. Please refer the following code snippet.

Code snippet:
```
legend: Legend(
     isVisible: true,
     toggleSeriesVisibility: false,
     legendItemBuilder: (legendText, series, point, seriesIndex) {
     return GestureDetector(
         child: Text(legendText,),
         onDoubleTap: () {
             setState(() {
                  visibility = !visibility;
                  visibleSeriesIndex = seriesIndex;
             });
         },
     );
   },
),
```
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/200567912-6a358b69-a7a2-46cc-b638-c3c9d5d854f9.png)

You can refer the below attached sample along with user guide documentation for more details about legendItemBuilder callback.
https://help.syncfusion.com/flutter/cartesian-charts/legend#legend-item-template

**Comment by natrayansf** [comment]
The requirement ‘’How to draw the pretty previous style in legendItemBuilder’’ can be achieved by using container, [icon](https://api.flutter.dev/flutter/material/Icons-class.html) and text widget in gesture detector and wrapping it in [row](https://api.flutter.dev/flutter/widgets/Row-class.html) widget. You can also change the [color](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CartesianSeries/color.html) of the legend text by changing the color in the line series color property. Please refer the following code snippet.

Code snippet:
```
legend: Legend (
        isVisible: true,
        overflowMode: LegendItemOverflowMode.wrap,
        position: LegendPosition.bottom,
        legendItemBuilder: (legendText, series, point, seriesIndex) {
        return Padding (
             padding: const EdgeInsets.all(8.0),
             child: GestureDetector(
                child: Container(
                    width: 80,
                    height: 50,
                    child: Row(
                      children: [
                        // Using the Icon widget you can customize the legend icons.
                        Container(
                          width: 10,
                          height: 2,
                          color: visibleSeriesIndex == seriesIndex ||
                                    visibleSeriesIndex == null ||
                                    visibility
                                ? series.color // If you want default legend text color, you can use the series color.
                                : series.color.withOpacity(0.4),
                        ),
                        const SizedBox(
                          width: 5,
                        ),
                        Text(
                          legendText,
                          style: TextStyle(
                            color: visibleSeriesIndex == seriesIndex ||
                                    visibleSeriesIndex == null ||
                                    visibility
                                ? Colors.black // If you want to change the legend text color, just use the series color.
                                : Colors.black.withOpacity(0.4),
                          ),
                        ),
                      ],
                    ),
                  ),
            ),
        ),
     );
  },
),
series: <CartesianSeries<ChartData, DateTime>>[
            LineSeries<ChartData, DateTime>(
              color: Colors.red,
  ),
]
```
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/200814488-1510dbe6-b030-48fd-9aa2-28cd900f0b5d.png)

You can refer to the below attached sample along with user guide documentation for more details about the legend widget.
https://help.syncfusion.com/flutter/cartesian-charts/legend 

Sample: [i418045.zip](https://github.com/syncfusion/flutter-widgets/files/9970340/i418045.zip)

**Comment by ilshookim** [comment]
Thank you, It was resolved!
