### ISSUE TITLE
Reading/Open existing xlxs file

### ISSUE THREAD

**Issue by MalikSamiAwan** [syncfusion/flutter-widgets#956]
Any updates on this feature

**Comment by MalikSamiAwan** [comment]
so we can edit it in
https://pub.dev/packages/syncfusion_flutter_xlsio#create-a-simple-excel-document
this package

**Comment by YancyHsu** [comment]
need this feature too

**Comment by Kurmitha4004** [comment]
Unfortunately, we don't have support for your requirement. And, we don’t have any plans to implement this support.
