### ISSUE TITLE
Unexpected '%' shown on footer summary cells.

### ISSUE THREAD

**Issue by gaddlord** [syncfusion/flutter-widgets#960]
I have a definition of a sfDataGrid but unexpectedly the footer Sums are shown with '%'. See the screenshot below:

![image](https://user-images.githubusercontent.com/279005/200198697-e8c8fd11-f1eb-4721-8d4b-8c7af0083820.png)

Seems OK for double columns (such as Price) but not working for the first 3 int columns.

child: SfDataGrid(
          allowColumnsResizing: true,
          allowEditing: true,
          allowMultiColumnSorting: true,
          allowSorting: true,
          allowTriStateSorting: true,
          columnWidthMode: ColumnWidthMode.fitByColumnName,
          gridLinesVisibility: GridLinesVisibility.both,
          headerGridLinesVisibility: GridLinesVisibility.both,
          headerRowHeight: 40,
          isScrollbarAlwaysShown: true,
          navigationMode: GridNavigationMode.cell,
          rowHeight: 20,
          selectionMode: SelectionMode.multiple,
          showCheckboxColumn: true,
          source: _cardPoolDataGridSource,
          tableSummaryRows: [
            GridTableSummaryRow(
              title: 'TOTALS',
              showSummaryInRow: false,
              position: GridTableSummaryRowPosition.bottom,
              color: Colors.yellow[100],
              columns: [
                const GridSummaryColumn(
                  name: 'collectionSummary',
                  columnName: CardPoolDataGridSource.collectionQtyColumnName,
                  summaryType: GridSummaryType.sum,
                ),
                const GridSummaryColumn(
                  name: 'tradeListSummary',
                  columnName: CardPoolDataGridSource.tradelistQtyColumnName,
                  summaryType: GridSummaryType.sum,
                ),
                const GridSummaryColumn(
                  name: 'decksNeededSummary',
                  columnName: CardPoolDataGridSource.sumNeededQtyColumnName,
                  summaryType: GridSummaryType.sum,
                ),
                const GridSummaryColumn(
                  name: 'cardNameSummary',
                  columnName: CardPoolDataGridSource.cardNameColumnName,
                  summaryType: GridSummaryType.count,
                ),
                const GridSummaryColumn(
                  name: 'priceSummary',
                  columnName: CardPoolDataGridSource.priceColumnName,
                  summaryType: GridSummaryType.sum,
                ),
              ],
            ),
          ],
  ....
);

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @gaddlord,

Attempting the scenario with SfDataGrid version 20.3.52 for calculating the summary values and confirming that the summary values are calculated correctly for the column cells. I've attached a simple sample based on the given code snippets. Also refer to the reference image for the same.


![image](https://user-images.githubusercontent.com/93904422/200488611-f01b2045-1af1-4a59-9caf-4b0c8ef007b9.png)


Sample: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/9958163/sample.zip)

**Comment by gaddlord** [comment]
You are right @Tamilarasan-Paranthaman it was an error on my end. Seems like I have overriden the buildTableSummaryCellWidget() having an extra '%' sign.

![image](https://user-images.githubusercontent.com/279005/200673892-f38f2276-56a3-4b31-b979-a887c8de4cf8.png)

Consider non issue and ticket closed.
