### ISSUE TITLE
[syncfusion_flutter_charts] spline chart - onPointTap method returns wrong point index

### ISSUE THREAD

**Issue by Jos-Sea** [syncfusion/flutter-widgets#961]
Hi there, 
I'm rendering marker only when point index is divisible by 3 using onMarkerRender method.
and showing data label only when we click on the marker which point index is divisible by 3 using onPointTap method.
but onPointTap method is returning wrong point index.

for example. if click on marker whose point index is 3 but onPointTap method is returning point index 2 because of that not able to show data Label.

onMarker method - 
```
onMarkerRender: (markerRenderArgs) {
        int pi = markerRenderArgs.pointIndex!;

        if (pi % 3 == 0) {
          markerRenderArgs.markerHeight = 8.0;
          markerRenderArgs.markerWidth = 8.0;
        } else {
          markerRenderArgs.markerHeight = 0.0;
          markerRenderArgs.markerWidth = 0.0;
        }
      },
```
onPointTap method -
 ```
onPointTap: (ChartPointDetails details) {
         int pi = details.pointIndex!;

            _dataLabelPI = pi;

            if (pi % 3 == 0) {
              setState(() {});
            }
          },
```
dataLabelMapper method - 
 ```
dataLabelMapper: (data, point) {
            var value = data.value.toStringAsFixed(1);

            if (_dataLabelPI == point) {
              return value;
            }

            //don't show dataLabel
            else {
              return '';
            }
          },
```

Data set - 
```
List chartData = [
  {"date": "2022-08-30", "value": 54},
  {"date": "2022-09-01", "value": 58},
  {"date": "2022-09-07", "value": 88},
  {"date": "2022-09-12", "value": 25},
  {"date": "2022-09-15", "value": 37},
  {"date": "2022-09-19", "value": 5},
  {"date": "2022-09-20", "value": 38},
  {"date": "2022-09-21", "value": 336},
  {"date": "2022-09-23", "value": 38},
  {"date": "2022-10-06", "value": 33},
  {"date": "2022-10-07", "value": 49},
  {"date": "2022-10-10", "value": 64},
  {"date": "2022-10-13", "value": 76},
  {"date": "2022-10-14", "value": 42},
  {"date": "2022-10-19", "value": 53},
  {"date": "2022-10-25", "value": 46},
  {"date": "2022-10-30", "value": 49},
  {"date": "2022-11-04", "value": 100}
];
```

ChartDataModel -
```
List<ChartDataModel> chartDataModelFromList(List data) =>
    List<ChartDataModel>.from(data.map((x) => ChartDataModel.fromMap(x)));

class ChartDataModel {
  ChartDataModel({
    required this.date,
    required this.value,
  });

  DateTime date;
  double value;

  factory ChartDataModel.fromMap(Map json) => ChartDataModel(
        date: DateTime.parse(json["date"]),
        value: double.parse(json["value"].toString()),
      );
}

```
Full Example - 
```
class SplineChartExample extends StatefulWidget {
  const SplineChartExample({Key? key}) : super(key: key);

  @override
  State<SplineChartExample> createState() => _SplineChartExampleState();
}

class _SplineChartExampleState extends State<SplineChartExample> {
  List<ChartDataModel> _chartDataList = [];
  int? _dataLabelPI;

  @override
  void initState() {
    super.initState();
    _data();
  }

  void _data() async {
    _chartDataList = chartDataModelFromList(chartData);
    _chartDataList.sort(
      (a, b) => b.date.compareTo(a.date),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: _chart(),
    );
  }
  Widget _chart() {
    return SfCartesianChart(
      margin: const EdgeInsets.only(left: 24, right: 16),

      primaryXAxis: DateTimeCategoryAxis(
        isVisible: false,
        labelPlacement: LabelPlacement.onTicks,
      ),
      primaryYAxis: NumericAxis(
        minimum: 0,
        maximumLabels: 3,
        rangePadding: ChartRangePadding.additional,
        decimalPlaces: 0,
      ),
      series: <ChartSeries>[
        SplineSeries<ChartDataModel, DateTime>(
          dataSource: _chartDataList,
          xValueMapper: (ChartDataModel data, _) => data.date,
          yValueMapper: (ChartDataModel data, _) => data.value,
          enableTooltip: false,
          sortFieldValueMapper: (data, _) => data.date,
          sortingOrder: SortingOrder.ascending,
          splineType: SplineType.monotonic,
          markerSettings: const MarkerSettings(
            isVisible: true,
            height: 8,
            width: 8,
          ),
          dataLabelMapper: (data, point) {
            var value = data.value.toStringAsFixed(1);

            if (_dataLabelPI == point) {
              return value;
            }

            //don't show dataLabel
            else {
              return '';
            }
          },
          dataLabelSettings: DataLabelSettings(
            isVisible: true,
            useSeriesColor: true,
            labelAlignment: ChartDataLabelAlignment.top,
            alignment: ChartAlignment.center,
            labelPosition: ChartDataLabelPosition.outside,
            textStyle: Theme.of(context).textTheme.bodyText2!.copyWith(
                  color: Colors.white,
                  fontSize: 10,
                ),
          ),
          onPointTap: (ChartPointDetails details) {
            int pi = details.pointIndex!;

            _dataLabelPI = pi;

            if (pi % 3 == 0) {
              setState(() {});
            }
          },
        ),
      ],
      onMarkerRender: (markerRenderArgs) {
        int pi = markerRenderArgs.pointIndex!;

        if (pi % 3 == 0) {
          markerRenderArgs.markerHeight = 8.0;
          markerRenderArgs.markerWidth = 8.0;
        } else {
          markerRenderArgs.markerHeight = 0.0;
          markerRenderArgs.markerWidth = 0.0;
        }
      },
    );
  }
}
```

**Comment by natrayansf** [comment]
The data point index starts from value 0 for the first data point, so when the 3rd point is tapped, the point tapped event returns the point index as 2. This is the default behavior.

However, this requirement can be achieved by increasing the point index value by 1 in the marker and point tap callback event. Please refer the following code snippet.

Code snippet:
```
onPointTap: (ChartPointDetails details) {
       int pi = details.pointIndex! + 1;
       _dataLabelPI = pi;
       if (pi % 3 == 0) {
           setState(() {});
       }
},
onMarkerRender: (markerRenderArgs) {
      int pi = markerRenderArgs.pointIndex! + 1;
      if (pi % 3 == 0) {
            markerRenderArgs.markerHeight = 8.0;
            markerRenderArgs.markerWidth = 8.0;
      } else {
            markerRenderArgs.markerHeight = 0.0;
            markerRenderArgs.markerWidth = 0.0;
      }
},
```
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/200570098-0c1d22b2-d5c3-4e08-91b6-3f633256ced5.png)

You can refer the below attached sample along with user guide documentation for more details about onPointTap and onMarkerRender callback.
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onpointtap 
https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onmarkerrender

Sample : [i418420.zip](https://github.com/syncfusion/flutter-widgets/files/9961295/i418420.zip)

**Comment by ShubhamHande99** [comment]
Thank you for your response. I'll check.

**Comment by Jos-Sea** [comment]
Thanks for your response. i'll check it.

**Comment by Jos-Sea** [comment]
Hi @natrayansf 
I checked it's not about tapping 3rd point, it's about tapping a marker whose point index is 3
as in above example we are rendering marker whose point index is divisible by 3 so it's rendering 0, 6, 9, 12, 15
point index markers so they should return same point index when we tap using onPointTap callback.

also you can check in above example by tapping on the markers the onPointTap method returns 
current point index for markers 1, 3, 5 ,6 (from right side)  and shows data label 

and wrong point index for 2, 4 (from right side) and does not show data label.

and when we click little above right / left outside the markers 2, 4 (from right side) it's returns the current point index 
as 3, 9 else it's return 2 and 8 point index when we click on exact on marker. thus it's not showing data label.

**Comment by natrayansf** [comment]
The requirement can be achieved by increasing the point index value by one in the onPointTap and onMarkerRender callback events, as well as in the [dataLabelMapper](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeries/dataLabelMapper.html) property. Now your marker and data label display a point index divisible by 3. Please refer the following code snippet.

Code snippet:
```
dataLabelMapper: (data, point) {
      var value = data.value.toStringAsFixed(1);
      if (_dataLabelPI == point + 1) {       // increasing the point index value by 1
           return value;
      } else {
           return '‘;
      }
},
```
Screenshot:
![image](https://user-images.githubusercontent.com/105288098/201094860-b17ea1c2-5cef-4097-b687-196cba0d793c.png)

We have modified the sample based on your requirements and attached the latest sample for your reference.

Sample: [i418420.zip](https://github.com/syncfusion/flutter-widgets/files/9980771/i418420.zip)

**Comment by Jos-Sea** [comment]
Hello @natrayansf 

After going through your sample code I noticed that it works perfectly on web app as clicking exactly on marker
it shows the data label.

But some markers don't show data label when tapping exactly on marker in mobile device,
For such marker we need to click outside a bit to show the marker.

Mobile device screenshot:

tapping exactly on marker -

![tapping_extactly_on_marker](https://user-images.githubusercontent.com/117063053/201260324-584ead25-9816-4e82-abba-a2f53127b422.png)

tapping outside the marker -
 
![tapping_outside_marker](https://user-images.githubusercontent.com/117063053/201260545-717a14ff-e518-47f2-8970-a099c9dfc13c.png)

**Comment by Yuvaraj-Gajaraj** [comment]
The reported issue that is **'onPointTap method returns the wrong point index value'** has been fixed and rolled out in our weekly patch release. To avoid this issue please upgrade the chart package to the latest version mentioned below.



Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/20.3.60

**Comment by Jos-Sea** [comment]
Thank you.
