### ISSUE TITLE
[syncfusion_flutter_calendar] Customize DateRangePickerHeaderStyle

### ISSUE THREAD

**Issue by Alyxsqrd** [syncfusion/flutter-widgets#964]
Hi, I'm using Flutter Calendar, and I've noticed there's no way to customize the header style for the date range picker that's used in the month view. I would greatly appreciate if you guys could expose this as a property we can change in the SfCalendar class! 👍

Edit: Mainly need this so I can set a custom font, as SfCalendar currently has it hardcoded to Roboto.

**Comment by MuniappanSubramanian** [comment]
# Regarding Customize HeaderStyle

This requirement can be achieved by customizing the header using the "headerStyle" property. In the calendar, you can change the header's background colour, text style, and text alignment by using the headerStyle property's backgroundColor, textStyle, and textAlign properties.

Refer to our KB document for customizing the header in the calendar,
https://www.syncfusion.com/kb/12144/how-to-style-a-header-in-the-flutter-calendar

Please refer to our UG document for more details about customizing the header in the Calendar,
https://help.syncfusion.com/flutter/calendar/headers#header-appearance

Please refer to our UG document for more details about customizing the view header in the Calendar,
https://help.syncfusion.com/flutter/calendar/headers#view-header-appearance

**Comment by Alyxsqrd** [comment]
> # Regarding Customize HeaderStyle
> 
> This requirement can be achieved by customizing the header using the "headerStyle" property. In the calendar, you can change the header's background colour, text style, and text alignment by using the headerStyle property's backgroundColor, textStyle, and textAlign properties.
> 
> Refer to our KB document for customizing the header in the calendar, https://www.syncfusion.com/kb/12144/how-to-style-a-header-in-the-flutter-calendar
> 
> Please refer to our UG document for more details about customizing the header in the Calendar, https://help.syncfusion.com/flutter/calendar/headers#header-appearance
> 
> Please refer to our UG document for more details about customizing the view header in the Calendar, https://help.syncfusion.com/flutter/calendar/headers#view-header-appearance

This issue is not related to the headerStyle property. I'm trying to change the header for the date range picker which is shown in the popup once you click on the header.
