### ISSUE TITLE
[syncfusion_flutter_calendar] Option to hide recurrence icon

### ISSUE THREAD

**Issue by Alyxsqrd** [syncfusion/flutter-widgets#965]
Hello, I would like to suggest a property be added to the SfCalendar class where we can disable the recurrence icon (in the top-right corner of each appointment) since the icon may not be necessary for our use case.

Thank you guys for making this great library! 😄

**Comment by MuniappanSubramanian** [comment]
# Regarding  removing cycle icon  
This requirement can be achieved by customizing the appointment using the ‘appointmentBuilder’ widget from the Flutter calendar.  

You can refer to our following KB documentation to customize the appointment in Calendar: https://www.syncfusion.com/kb/12191/how-to-customize-the-appointments-using-custom-builder-in-the-flutter-calendar 


Please refer to our UG documentation for more details about appointment builder support in Calendar. https://help.syncfusion.com/flutter/calendar/builders#appointment-builder

**Comment by Alyxsqrd** [comment]
Thank you!
