### ISSUE TITLE
[synfusion_flutter_datagrid] issues with keyboard navigation on desktop platforms

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#967]
The datagrid component has a lot of features that work great on mobile platforms, such as Android or iOS, but some features are problematic on desktop platforms, including web and windows.

For instance, you can navigate around the grid using keyboard, but neither tap or double tap callbacks can be activated from the keyboard. For example, the Syncfusion DataGrid "[editing demo](https://flutter.syncfusion.com/#/datagrid/editing)" does not allow to activate cell editor from keyboard in the web browser. Similarly, it is not possible or not obvious how to attach some keyboard shortcuts/actions, e.g. to open detail view for selected row (or multiple rows) using Enter or Space or some custom keyboard shortcut.

Also, unlike Flutter's `TextField/TextFormField` you can't override default grid component's actions with custom Flutter [actions/shortcuts](https://docs.flutter.dev/development/ui/advanced/actions_and_shortcuts), e.g. see `flutter/packages/flutter/lib/src/widgets/text_editing_intents.dart`.

**Comment by MalikSamiAwan** [comment]
@ekuleshov any workaround?

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov,

**Regarding query: it is not possible or not obvious how to attach some keyboard shortcuts/actions, e.g. to open detail view for selected row (or multiple rows) using Enter or Space or some custom keyboard shortcut.**

You can achieve your requirement by using the **RowSelectionManager** class. Write the **CustomSelectionManager** class by extending the **RowSelectionManager** class. Set the instance of the **CustomSelectionManager** class to the **SfDataGrid.selectionManager**. You can write the custom actions in the **RowSelectionManager.handleKeyEvent** method. Please check the following code snippet.

```dart
CustomSelectionManager customSelectionManager = CustomSelectionManager(dataGridController);
  

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
      body: SfDataGrid(
          source: _employeeDataSource,
          columns: getColumns,
          controller: dataGridController,
          selectionManager: customSelectionManager,
          allowEditing: true,
          navigationMode: GridNavigationMode.cell,
          selectionMode: SelectionMode.single,
          columnWidthMode: ColumnWidthMode.fill),
    );
  }

class CustomSelectionManager extends RowSelectionManager {
  CustomSelectionManager(this.dataGridController);
  DataGridController dataGridController;
@override
  void handleKeyEvent(RawKeyEvent keyEvent) async {
...
}

}
```
I've attached a simple sample. In that sample, I have the showed the selected ID value in the dialog when enter/space key is pressed. Please check the code snippet and sample below.

Sample Link: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/10042291/sample.zip)

**Regarding query: For instance, you can navigate around the grid using keyboard, but neither tap or double tap callbacks can be activated from the keyboard. For example, the Syncfusion DataGrid "editing demo" does not allow to activate cell editor from keyboard in the web browser.**

You can enter the edit mode by using the keyboard **F2** key and end the editing with the **Esc** key. There is already detailed information in the following UG documentation.

UG Document: https://help.syncfusion.com/flutter/datagrid/selection#keyboard-behavior

**Comment by ekuleshov** [comment]
> You can achieve your requirement by using the **RowSelectionManager** class. Write the **CustomSelectionManager** class by extending the **RowSelectionManager** class. Set the instance of the **CustomSelectionManager** class to the **SfDataGrid.selectionManager**. You can write the custom actions in the **RowSelectionManager.handleKeyEvent** method. Please check the following code snippet.
>
> I've attached a simple sample. In that sample, I have the showed the selected ID value in the dialog when enter/space key is pressed. Please check the code snippet and sample below.

Thank you for an example. Unfortunately the `handleKeyEvent()` method is not helpful for the described case and it does not allow to override how keyboard selection is handled in the grid (other than just disabling it).

That is mainly because all the actual methods that handle selections are private in the `RowSelectionManager` e.g.  `_processSelectionAndCurrentCell()`, `_processSelection()`, etc.

All in all it would be really nice if the `SfDataGrid` provided Desktop platform-alike experience for selecting rows out of the box without a need to write custom code to deal with the `RawKeyEvent`s.

> **Regarding query: For instance, you can navigate around the grid using keyboard, but neither tap or double tap callbacks can be activated from the keyboard. For example, the Syncfusion DataGrid "editing demo" does not allow to activate cell editor from keyboard in the web browser.**
> 
> You can enter the edit mode by using the keyboard **F2** key and end the editing with the **Esc** key. There is already detailed information in the following UG documentation.

In my case don't really need to enter the edit mode. There is a double tap callback declared on `SfDataGrid` that I need to activate with keyboard. Similarly for the tap call back on a given cell.

It might be possible to the `handleKeyEvent()` method for that, but generally Flutter framework has much richer and more fine granular [Actions and Shortcuts](https://docs.flutter.dev/development/ui/advanced/actions_and_shortcuts) API for adding custom keyboard interactions to widgets.

**Comment by MalikSamiAwan** [comment]
@Tamilarasan-Paranthaman Solved my problem 
Thanks

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @ekuleshov,


Currently, Flutter SfDataGrid does not have support for handling keyboard shortcuts through [Shortcuts](https://api.flutter.dev/flutter/widgets/Shortcuts-class.html) widget. We have already considered your request as a feature. We may implement this feature in any of our upcoming releases.

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience and understanding until then. You can follow up with the below feedback for further details,


**Feedback link:  https://www.syncfusion.com/feedback/40747/support-to-handle-the-custom-keyboard-actions-through-shortcuts-widget** 

Regards,
