### ISSUE TITLE
CategoryAxis: Predefined Ordering of Category Axis Labels/Values

### ISSUE THREAD

**Issue by zzzaJ** [syncfusion/flutter-widgets#969]
I am implementing a bar graph, where the X-Axis values are a category, and the Y-Axis represents the count or frequency of that category in some data set.

I would like to apply an order to the X-Axis category values, such that it is displayed as "Category 1", "Category 2", "Category 3", and so forth.

Currently, the categories seem to added to the X-Axis in the order that they are in the source data. Is there any way to pre-define the category axis values, as well as an order for them?

**Comment by LokeshPalani** [comment]
The requirement ‘Predefined Ordering of category Axis Labels/values’ can be achieved by using [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) callback in axis. Using this callback, you can customize the axis labels as per the following code snippet.

**Code snippet:**

```
body: SfCartesianChart(
          primaryXAxis: CategoryAxis(
            axisLabelFormatter: (AxisLabelRenderDetails details) {
              String text = 'Category ${details.value + 1}';
              return ChartAxisLabel(text, details.textStyle);
            },
          ),
       )
```
**Screenshot :**

![image](https://user-images.githubusercontent.com/105289202/202348362-76084f9f-0179-412c-8a14-e99f832098f0.png)

You can refer the below attached sample. please check with the above solution and get back to us if you need further assistance.

[chart_419491.zip](https://github.com/syncfusion/flutter-widgets/files/10027513/chart_419491.zip)
