### ISSUE TITLE
Paginated DataGrid only sort on one page.

### ISSUE THREAD

**Issue by svsno1** [syncfusion/flutter-widgets#97]
I need to sort on whole data.

**Comment by NeelakandanKannan** [comment]
Hi @svsno1,

Thanks for using Syncfusion widgets.

Currently, SfDataGrid does have the support to sort the currently assigned datasource (current page) alone. We are checking the possibility to sort whole data instead of current page alone. We will get back to you on 30th December 2020.

**Comment by NeelakandanKannan** [comment]
Hi @svsno1 ,

Thanks for your patience.

We have considered to provide this support and logged feature request for the same. We will implement this feature in any of our upcoming release. You can refer the below feedback link for follow up,
https://www.syncfusion.com/feedback/21023/support-to-sort-whole-data-instead-of-current-page-data

**Comment by svsno1** [comment]
I'm waiting for you.
Thanks so much!

**Comment by NeelakandanKannan** [comment]
Hi @svsno1 ,

We will let you know once this feature is implemented.

**Comment by RenugaSadagoban98** [comment]
Hi @svsno1 , 
  
Thanks for your patience. 


We are glad to announce that our Essential Studio 2021 Volume 3 Main Release V19.3.0.43 is rolled out and is available for download under the following link. 
  
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download 
 
Refer the following UG links for hole data sorting feature, 
**UG link:** https://help.syncfusion.com/flutter/datagrid/paging#sort-all-the-rows-instead-of-rows-available-in-a-page

 
  
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance. 

Regards, 
Renugadevi
