### ISSUE TITLE
Feature request [Android TV] : Allow manual scroll through button click

### ISSUE THREAD

**Issue by hardikm9850** [syncfusion/flutter-widgets#970]
Hi

We are using the syncfusion library to render pdf on Android TV. Although the user is able to view the pdf, they can't scroll it with the TV remote. 

It will be helpful if we somehow could interact with the pdf.

**Comment by deepika134** [comment]
We have included the support for “Scrolling via remote button clicks on Android TV” in our latest weekly release, so kindly upgrade to the latest version v20.4.43.   

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.4.43

**Comment by hardikm9850** [comment]
Thanks!
