### ISSUE TITLE
[syncfusion_flutter_treemap] Direction of TreeMap Rendering

### ISSUE THREAD

**Issue by Physicx101** [syncfusion/flutter-widgets#972]
Hey Syncfusion team, amazing library that you guys have created here, although I have a question regarding the rendering direction (which is different from `TreeMapLayoutDirection`). Is there a way to specify the tree map to render vertically? for example on hierarchical tree map, I'd like to have each categories to be rendered below each other.
![image](https://user-images.githubusercontent.com/21136067/201838543-ff87640e-a1a0-441d-b33d-4f837097276d.png)
Like based on my picture above.

Thanks a lot guys.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @Physicx101 ,

Your requirement can be achieved with the help of [SfTreemap.slice](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/SfTreemap/SfTreemap.slice.html) and [TreemapLevel ](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/TreemapLevel-class.html)[itemBuilder](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/TreemapLevel/itemBuilder.html) property. Using this we have rendered the type data in the slice's [TreemapLevel](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/TreemapLevel-class.html) as a first level and rendered the respective product item using the [itemBuilder](https://pub.dev/documentation/syncfusion_flutter_treemap/latest/treemap/TreemapLevel/itemBuilder.html) and mapped the respective point color. Here we have shared the sample below to achieve your requirement, you can modify the sample as per your requirement.



Screenshot:


<img width = 200, src = 'https://user-images.githubusercontent.com/61863686/202897447-f6c34c6f-6642-4415-b997-c8d90b0165c4.png'/>



UG: https://help.syncfusion.com/flutter/treemap/layout#slice
https://help.syncfusion.com/flutter/treemap/levels#squarified
https://help.syncfusion.com/flutter/treemap/item-builder


Sample: 
[i420029.zip](https://github.com/syncfusion/flutter-widgets/files/10049407/i420029.zip)



Regards,
Yuvaraj.

**Comment by Physicx101** [comment]
Hey @Yuvaraj-Gajaraj thanks a lot for the reply and the example, it's very helpful indeed, I have tried to implement the same thing shown based on your example, however I come across another issue which is that it will show an overflow on the last item of the slice and hence unable to render the items there. Please look at the images below 
<img width="364" alt="Screenshot 2022-11-23 at 12 19 16" src="https://user-images.githubusercontent.com/21136067/203473944-01738eda-5cc5-4c3e-9a01-1d5fe35ac717.png">
<img width="363" alt="Screenshot 2022-11-23 at 12 19 07" src="https://user-images.githubusercontent.com/21136067/203473961-220b5950-7bff-4545-9c0c-fe367e9a455c.png">

Here's the build method:
```
  Widget build(BuildContext context) {
    return SfTreemap.slice(
      dataCount: data.length,
      weightValueMapper: (int index) {
        return 1;
      },
      levels: [
        //First level tiles to display tag (sector/country).
        TreemapLevel(
          padding: EdgeInsets.all(4.w),
          color: Colors.transparent,
          groupMapper: (int index) => data[index].tag,
          labelBuilder: (BuildContext context, TreemapTile tile) {
            return AppSectorTag(
              tag: AdroitTag(
                tag: tile.group,
              ),
              width: double.infinity,
            );
          },
        ),
        // Inner level tiles to display stock name and changes.
        TreemapLevel(
          color: Colors.transparent,
          groupMapper: (int index) => data[index].tag,
          itemBuilder: (BuildContext context, TreemapTile tile) {
            return SfTreemap(
              dataCount: tile.indices.length,
              weightValueMapper: (int index) {
                return data[tile.indices[index]].value.toDouble();
              },
              levels: [
                TreemapLevel(
                  //padding: EdgeInsets.all(4.w),
                  border: RoundedRectangleBorder(
                    borderRadius: AppBorderRadius.appBorderRadius,
                  ),
                  colorValueMapper: (TreemapTile tile) {
                    final isPositive = data[tile.indices[0]].value > 0;
                    return isPositive
                        ? AppColors.lightGreen
                        : AppColors.lightRed;
                  },
                  groupMapper: (int index) => data[tile.indices[index]].stock.symbol,
                  labelBuilder: (BuildContext context, TreemapTile tile) {
                    return Text(tile.group);
                  },
                )
              ],
            );
          },
        ),
      ],
    );
  }
  ```
Once again thanks for the help, really appreciate it.

**Comment by Yuvaraj-Gajaraj** [comment]
We suspect that you have given a Treemap widget inside the fixed size widget. To resolve this render overflow issue, we suggest you wrap the Treemap with the scrollable widget it will expand the Treemap widget and avoid the render overflow issue. We hope it will help you to achieve your requirements, if you have any further queries please get back to us, we are always happy to assist you.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket, if you still facing an issue.
