### ISSUE TITLE
[syncfusion_flutter_calendar] Allow changing DateRangePickerHeaderStyle.textStyle

### ISSUE THREAD

**Issue by Alyxsqrd** [syncfusion/flutter-widgets#976]
Please expose the TextStyle property to SfCalendar so the DatePicker's header font can be customized. https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_calendar/lib/src/calendar/sfcalendar.dart#L8695-L8698

![IMG_3297](https://user-images.githubusercontent.com/25337749/202365246-6d4bc585-2e67-4a14-8631-0b8464cdbf48.jpg)

**Comment by MuniappanSubramanian** [comment]
The current implementation of the Flutter Calendar does not have support to customize the date picker header. The date picker is used to navigate different calendar views in Flutter Calendar, and it is mainly used for navigation purposes.

Please refer to our UG documentation to know more details about the date picker,
https://help.syncfusion.com/flutter/calendar/date-navigations#show-date-picker
