### ISSUE TITLE
Flicker issue with Doughnut Chart

### ISSUE THREAD

**Issue by kbessemer** [syncfusion/flutter-widgets#977]
When the screen loads the doughnut chart will flicker, meaning it kind of blinks, this happens everytime the screen loads that contains the chart.

``class ChartData {
  ChartData(this.x, this.y, this.color);
  final String x;
  final double y;
  final Color color;
}``

`double DisplaySales() {
    if (viewToday) {
      return double.parse(Provider.of<AppData>(context, listen: false).salesToday);
    } else if (viewMonth) {
      return double.parse(Provider.of<AppData>(context, listen: false).salesMonth);
    } else {
      return double.parse(Provider.of<AppData>(context, listen: false).salesYear);
    }
  }`

`late List<ChartData> chartData;
    if (DisplayProfits() == 0 && DisplaySales() == 0 && DisplayCosts() == 0) {
      chartData = [
        ChartData('', 100, Color(0xFF165BAA)),
      ];
    } else {
      chartData = [
        ChartData('', DisplayProfits(), Color(0xFF165BAA)),
        ChartData('', DisplaySales(), Color(0xFF16BFD6)),
        ChartData('', DisplayCosts(), Color(0xFFF765A3)),
      ];
    }`

`Container(
                          width: inputWidth / 2,
                          height: 150,
                          child: SfCircularChart(
                              series: <CircularSeries>[
                                // Renders doughnut chart
                                DoughnutSeries<ChartData, String>(
                                  dataSource: chartData,
                                  pointColorMapper:(ChartData data,  _) => data.color,
                                  xValueMapper: (ChartData data, _) => data.x,
                                  yValueMapper: (ChartData data, _) => data.y,
                                )
                              ]
                          ),
                        ),`

Not sure if anyone can give advice on how to include code better in these issue posts.... mine never seems to format correctly

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @kbessemer,

We suspect that you are using the setState method to update the data in the doughnut series, which is causing the flickering issue. However, you can resolve this issue by using the [updateDateSource](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/CircularSeriesController/updateDataSource.html) method in the circular chart to update the data source. We have shared a sample below for your reference, please modify it as per your requirement.

UG: https://help.syncfusion.com/flutter/circular-charts/callbacks#onrenderercreated

Screenshot:
![ezgif com-gif-maker (21) (1)](https://user-images.githubusercontent.com/61863686/210761077-2e049dca-8c26-49d8-a1ae-5515798a8f00.gif)

Sample: 
[i428027.zip](https://github.com/syncfusion/flutter-widgets/files/10351414/i428027.zip)
