### ISSUE TITLE
onBookmarkClicked

### ISSUE THREAD

**Issue by bkoznov** [syncfusion/flutter-widgets#978]
Thank you very much for providing such a powerful package! Is it possible that we could have visibility into what bookmarks the user clicks?
Suggested functionality:
Add a callback when a bookmark is clicked. like
```
// click a bookmark
onBookmarkClicked: (bookmarkIndex) {

}
```
[https://help.syncfusion.com/flutter/pdf-viewer/bookmark-navigation](https://help.syncfusion.com/flutter/pdf-viewer/bookmark-navigation)

I followed the above guide, and I see how I can navigate to a specific bookmark programmatically. What I am hoping for is the ability to click on that bookmark in the body of the PDF and be able to do something in my own Flutter app based on it.

 I.e. allow a user to attach a bookmarked location in a PDF to a issue they are submitting.
 
 It seems this package has functionality for a user to click on something in an issue which will take them to a bookmark location in the pdf, but no functionality to allow a user to save a bookmark location for other users to click on / view. Is that right?

**Comment by deepika134** [comment]
Hi @bkoznov, kindly share your complete requirement and use case. This information will be helpful for us to investigate on further.
