### ISSUE TITLE
[syncfusion_flutter_charts] Force Y-Axis Labels and minimum interval

### ISSUE THREAD

**Issue by miyazk4** [syncfusion/flutter-widgets#985]
Hello,

In my project, the Y-Axis of my charts, are being rendered as the following:

```dart
ChartAxis primaryYAxis = NumericAxis(
  majorGridLines: const MajorGridLines(width: 0),
  majorTickLines: majorTickLines,
  rangePadding: ChartRangePadding.round,
  axisLabelFormatter: (args) {
    late String text;
    text = '${args.value.abs().toStringAsFixed(1)}';
    return ChartAxisLabel(text, null);
  },
);
```

I am also using onActualRangeChanged, where I was trying to 'force' the 4 Y-Axis Labels on every single one of my charts:

```dart
ActualRangeChangedArgs onActualRangeChanged(ActualRangeChangedArgs args) {
  if (args.orientation == AxisOrientation.vertical) {
    const gridLineCount = 3;
    args.visibleInterval = (args.visibleMax - args.visibleMin) / gridLineCount;
  }

  return args;
}
```

In some of them, the number of Y-Axis labels are 4, and in others, 3, despite being rendered the exact same way,

![imagem](https://user-images.githubusercontent.com/61757484/203100749-22ef64d9-da2f-4859-b3ca-1bc2d3d0c475.png)

![imagem](https://user-images.githubusercontent.com/61757484/203100823-5c5a9ad1-615e-4817-9bb1-16723fa70d7c.png)

Is there any way to force the number of labels to always be 4, as well as the minimum value to be the closest to my data? (The first value is 4.0, even though my data values aren't close at all to it)

**Comment by LokeshPalani** [comment]
Hi,


You can achieve your requirement by setting the [minimum](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/NumericAxis/minimum.html) property to 4 and the [desiredIntervals](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/desiredIntervals.html) property to 4 in the Axis. This will enable you to display only 4 labels in the Axis. We have provided a code snippet, output, and sample for your reference.


**Code snippet:**

 ```
primaryYAxis: NumericAxis(
            minimum: 4,
            desiredIntervals: 4,
          ),
```


Output:

![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/0b5b9eac-3940-4a13-a8a4-dc37c33bcabe)

Regards,
Lokesh.

[chart_471909.zip](https://github.com/syncfusion/flutter-widgets/files/11730737/chart_471909.zip)
