### ISSUE TITLE
DataGrid - Add the ability to determine scrollbar placement

### ISSUE THREAD

**Issue by Elixell** [syncfusion/flutter-widgets#986]
Hi! In desktop when the content is scrollable i would like to show the scrollbar all the time, but i didn't find a way to ovveride the scrollbar placement to appear outside of the DataGrid. My scrollbar is really thick and it's overlapping the DataGrid's content, that's why i would like to place it outside or apply a padding.

Thanks for your help!

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @Elixell,

As of now, the SfDataGrid doesn't have support for setting "padding between DataGrid and the vertical and horizontal scrollbars". We have already considered your request as a feature. We may implement this in any of our upcoming releases. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters, including product vision, technological feasibility, and customer interest. You can follow up with the following feedback link for further updates.

Feedback link: https://www.syncfusion.com/feedback/38675/support-to-set-the-padding-between-datagrid-and-the-vertical-and-horizontal 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @Elixell,

We are closing this ticket as of now. You can follow up with the provided feedback link. If you have any additional needs or questions, please don't hesitate to reopen it. We're here to support you.

Regards,
Ashok K
