### ISSUE TITLE
DataGrid filters not working correctly

### ISSUE THREAD

**Issue by kaseyrossanderson** [syncfusion/flutter-widgets#988]
Hello,

We're using the SyncFusion DataGrid. When doing any type of filtering it works as expected when you first type or select items.. but when you clear filters it only brings some of the items back.. not all of them.

Just a quick example. When I first load the page with the code below I have two items in my data table:

`Personal` and `Professional`

When I use the the search field to type 'Per' then it only shows the `Personal` item as I'd expect. However if I backspace (remove everything from the search field, then only 'Personal' is shown. If I start to type 'Pro' then `Professional` is the only one to show up.. but if I again backspace to remove everything from the search it's back to only showing the item for `Personal`.

On one of my data grids using the same structure as below.. I have around 20 items or so in the list.. and when I clear the search field about half of them show up again but some of them are missing.

Also, please note that if I add a ```print('filter conditions: ${_source.filterConditions}');``` after the clear and before the add.. it shows 0 items in the filter conditions.. so it is clearing.. but something wrong is happening with the data.

```
late DataGridSource _source = DataGridSource();

@override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Expanded(
          child: SfDataGrid(
            source: _source,
            columns: [
              GridColumn(
                columnName: 'name',
                label: Container(
                  padding: EdgeInsets.symmetric(horizontal: 16.0),
                  alignment: Alignment.centerRight,
                  child: Text(
                    'Name',
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
              GridColumn(
                columnName: 'account',
                label: Container(
                  padding: EdgeInsets.symmetric(horizontal: 16.0),
                  alignment: Alignment.centerLeft,
                  child: Text(
                    'Account',
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ),
            ],
          ),
        ),
        TextFormField(
          onChanged: (value) {
            if ((_source.filterConditions.keys.contains('name'))) {
              _source.clearFilters(columnName: 'name');
            }

            _source.addFilter(
              'name',
              FilterCondition(
                type: FilterType.contains,
                value: value,
                filterOperator: FilterOperator.and,
                filterBehavior: FilterBehavior.stringDataType,
              ),
            );
          },
        ),
      ],
    );
  }
```

SyncFusion DataGrid Version: `20.3.58`

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kaseyrossanderson,

Attempting the scenario with SfDataGrid version **20.3.58** for filtering the records programmatically and confirming that the records are filtered properly. I've attached a simple sample based on the given code snippets. Also, refer to the attached video demo.

**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-1086696016** 

https://user-images.githubusercontent.com/93904422/203547432-f2400785-0afa-429d-97a2-18439adfe8a7.mp4

**Comment by kaseyrossanderson** [comment]
@Tamilarasan-Paranthaman I ended up rewriting the widgets that were not working properly and got this working. I'm still not sure what I'm doing different as the code looks essentially the same as before as far as the data grid goes. Anyways, it's working for me now. There must have been something different that was causing it. I'll have to analyze both widgets (old and new) and figure out what the culprit could have been to try and avoid in the future.

**Comment by kaseyrossanderson** [comment]
Hello @Tamilarasan-Paranthaman ,

I ran into this again with the new widget and can replicate it on demand :/ I'm not sure why it's not working. I'm printing out the `source.rows` and it shows all the rows regardless of filter, but when I print `source.effectiveRows` it shows the correct filtered values.. but it doesn't match up with what is shown on the page.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kaseyrossanderson,

The **DataGridSource.rows** property would contain the original order in which the data was loaded into the DataGrid, while **[DataGridSource.effectiveRows](https://pub.dev/documentation/syncfusion_flutter_datagrid/latest/datagrid/DataGridSource/effectiveRows.html)** holds the sorted and filtered collection if sorting/filtering is applied in the DataGrid. Based on the information you provided, we were unable to reproduce the reported issue on our end. It appears to be working properly. We tested a sample in which we entered the word "personal" in the search bar and then clicked the "Print Effective Rows" button to display the effective row Customer ID to ensure the rows, and it worked as expected. We believe the issue you are experiencing may be at the sample level. We have attached the sample we tested, along with an output video reference. It would be helpful if you could provide the sample, you are having trouble with, or modify the attached sample to be reproducible, so we can investigate and provide a solution as soon as possible.

**Sample Link: [sample.zip](https://github.com/syncfusion/flutter-widgets/files/10908741/sample.zip)**


https://user-images.githubusercontent.com/93904422/223407240-99983b70-325e-4f3e-9745-3a834dc160bc.mp4




Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment]
Hi @kaseyrossanderson, 

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards,
Ashok K
