### ISSUE TITLE
Need help with custom height in sfdatagrid for cells

### ISSUE THREAD

**Issue by syed-growexxer** [syncfusion/flutter-widgets#991]
details.getIntrinsicRowHeight is not working i need to change different row height according to the largest data in cell but it is not working please help with that

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @syed-growexxer,

Attempting the onQueryRowHeight scenario with SfDataGrid version **20.3.58** and confirming that the row height is set properly i.e., based on the largest cell content. I've attached a simple sample. Please check the following sample and reference image.

```dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
      body: SfDataGrid(
        source: _employeeDataSource,
        columns: getColumns,
        onQueryRowHeight: (details) {
          return details.getIntrinsicRowHeight(details.rowIndex);
        },
      ),
    );
  }
}

```
**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-195185819** 

![image](https://user-images.githubusercontent.com/93904422/203922262-6a8d85e5-013e-4cbc-bd03-1ca07895bbfb.png)

**Comment by syed-growexxer** [comment]
> Hi @syed-growexxer,
> 
> Attempting the onQueryRowHeight scenario with SfDataGrid version **20.3.58** and confirming that the row height is set properly i.e., based on the largest cell content. I've attached a simple sample. Please check the following sample and reference image.
> 
> ```dart
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
>       body: SfDataGrid(
>         source: _employeeDataSource,
>         columns: getColumns,
>         onQueryRowHeight: (details) {
>           return details.getIntrinsicRowHeight(details.rowIndex);
>         },
>       ),
>     );
>   }
> }
> ```
> 
> **Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-195185819**
> 
> ![image](https://user-images.githubusercontent.com/93904422/203922262-6a8d85e5-013e-4cbc-bd03-1ca07895bbfb.png)
![Screenshot 2022-11-25 at 2 36 53 PM](https://user-images.githubusercontent.com/114057852/203942761-e7082448-4f0b-4f22-b840-a2b92a32d24e.png)
 
 
I tried your sample when i am increasing the words in name column 1st cell all the words are hidden just some of it is showing up it's the same sample code just increased the word and it didn't take the size to adjust the cell it's same as before.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @syed-growexxer,

Sorry for the inconvenience caused. I have identified that the column name in **GridColumn.columnName** and **DataGridCell.columnName** is mismatched in that sample, which is causing the auto height feature to not work properly for the name column.

To fix this issue, you will need to make sure that the column name is set to the same value in both **GridColumn.columnName** and **DataGridCell.columnName**. This will ensure that the auto height feature works correctly for the name column. Please check the following code snippet and sample.

```dart
List<GridColumn> get getColumns {
  return <GridColumn>[
    GridColumn(
        columnName: 'id',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('ID'))),
    GridColumn(
        columnName: 'name',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('Name'))),
    GridColumn(
        columnName: 'companyName',
        label: Container(
            alignment: Alignment.centerLeft,
            child: const Text('Company Name'))),
    GridColumn(
        columnName: 'address',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('Address'))),
    GridColumn(
        columnName: 'city',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('City'))),
    GridColumn(
        columnName: 'country',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('Country'))),
    GridColumn(
        columnName: 'designation',
        label: Container(
            alignment: Alignment.centerLeft, child: const Text('Designation'))),
  ];
}

```
```dart 

class EmployeeDataGridSource extends DataGridSource {

…
  void buildDataGridRow() {
    dataGridRows = employees.map<DataGridRow>((Employee employee) {
      return DataGridRow(cells: <DataGridCell<String>>[
        DataGridCell<String>(columnName: 'id', value: employee.id),
        DataGridCell<String>(columnName: 'name', value: employee.name),
        DataGridCell<String>(
            columnName: 'companyName', value: employee.companyName),
        DataGridCell<String>(columnName: 'address', value: employee.address),
        DataGridCell<String>(columnName: 'city', value: employee.city),
        DataGridCell<String>(columnName: 'country', value: employee.country),
        DataGridCell<String>(
            columnName: 'designation', value: employee.designation),
      ]);
    }).toList();
  }
}
```
**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample134192983**

**Comment by ashok-kuvaraja** [comment]
Hi @syed-growexxer, 

We suspect that the reported problem has been resolved at your end. Please let us know if you have any further queries on this. We are happy to help you.

Regards, Ashok K
