### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Is there an option for scrolling speed？

### ISSUE THREAD

**Issue by cyz1901** [syncfusion/flutter-widgets#992]
https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfViewerController/jumpToPage.html 
It seems that there is only one parameter for the specified page

**Comment by deepika134** [comment]
SfPdfViewer provides support for the jumpTo() method, which can be used to jumps the specified offset in the PDF document. To know more details about jumpto() method refer following link , https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfViewerController/jumpTo.html
