### ISSUE TITLE
[syncfusion_flutter_charts] dataLabel  rendered value bug

### ISSUE THREAD

**Issue by miyazk4** [syncfusion/flutter-widgets#995]
Hello, I have multiple ColumnSeries, in which I display the value for each one of them, with the following result:

![image](https://user-images.githubusercontent.com/61757484/204526864-8b9ca32e-adad-4247-a754-7db91831dcfa.png)

The problem is, for example, on the second render, the first value is 0.01, the second is 0.62 and the third is 0.63.

The only values being displayed are the first and third ones.

This is my code structure:

```dart

List<ChartData> chartData = [
  ChartData(DateTime(2022, 01, 29), 5.58, 0.0, 0.40),
  ChartData(DateTime(2022, 01, 30), 0.01, 0.62, 0.63),
  ChartData(DateTime(2022, 01, 31), 0.0, 0.57, 0.57),
  ChartData(DateTime(2022, 02, 01), 2.69, 0.0, 0.67),
];

SfCartesianChart(
          backgroundColor: Colors.white,
          primaryXAxis: DateTimeAxis(),
          primaryYAxis: NumericAxis(
            isVisible: false,
          ),
          enableSideBySideSeriesPlacement: false,
          series: <ChartSeries>[
            ColumnSeries<ChartData, DateTime>(
              color: precipitationColor,
              dataLabelSettings: const DataLabelSettings(
                  isVisible: true,
                  showZeroValue: false,
                  labelAlignment: ChartDataLabelAlignment.outer),
              dataSource: chartData,
              xValueMapper: (data, _) => data.x,
              yValueMapper: (data, _) => data.y1,
            ),
            ColumnSeries<ChartData, DateTime>(
              color: const Color.fromRGBO(0, 196, 179, 0.5),
              dataLabelSettings: const DataLabelSettings(
                  isVisible: true,
                  showZeroValue: false,
                  labelAlignment: ChartDataLabelAlignment.outer),
              dataSource: chartData,
              xValueMapper: (data, _) => data.x,
              yValueMapper: (data, _) => data.y2,
            ),
            ColumnSeries<ChartData, DateTime>(
              color: const Color.fromRGBO(97, 0, 238, 0.5),
              dataLabelSettings: const DataLabelSettings(
                  isVisible: true,
                  showZeroValue: false,
                  labelAlignment: ChartDataLabelAlignment.outer),
              dataLabelMapper: (data, _) => data.y3.toStringAsFixed(2),
              dataSource: chartData,
              xValueMapper: (data, _) => data.x,
              yValueMapper: (data, index) => data.y3 * -1,
            ),
          ],
        ),

class ChartData {
  ChartData(this.x, this.y1, this.y2, this.y3);

  final DateTime x;
  final double y1;
  final double y2;
  final double y3;
}
```

Then, i changed my code, only showing y1, if the value was superior to 0.01, by adding

```dart
 dataLabelMapper: (data, _) =>
                    data.y1 > 0.01 ? data.y1.toStringAsFixed(2) : '')

```
![image](https://user-images.githubusercontent.com/61757484/204531398-40b4b2cc-b0d7-44b0-ba02-f95a56da4bdd.png)

If I remove ``` labelAlignment: ChartDataLabelAlignment.outer``` from all my ColumnSeries, this is what I end up with:

![image](https://user-images.githubusercontent.com/61757484/204531115-2094b0f4-1277-4e86-836b-16ed37413b3b.png)

The result I was looking was something like Image One, but, with the values being displayed as my I have conditioned

**Comment by miyazk4** [comment]
> Hello, I have multiple ColumnSeries, in which I display the value for each one of them, with the following result:
> 
> ![image](https://user-images.githubusercontent.com/61757484/204526864-8b9ca32e-adad-4247-a754-7db91831dcfa.png)
> 
> The problem is, for example, on the second render, the first value is 0.01, the second is 0.62 and the third is 0.63.
> 
> The only values being displayed are the first and third ones.
> 
> This is my code structure:
> 
> ```dart
> List<ChartData> chartData = [
>   ChartData(DateTime(2022, 01, 29), 5.58, 0.0, 0.40),
>   ChartData(DateTime(2022, 01, 30), 0.01, 0.62, 0.63),
>   ChartData(DateTime(2022, 01, 31), 0.0, 0.57, 0.57),
>   ChartData(DateTime(2022, 02, 01), 2.69, 0.0, 0.67),
> ];
> 
> SfCartesianChart(
>           backgroundColor: Colors.white,
>           primaryXAxis: DateTimeAxis(),
>           primaryYAxis: NumericAxis(
>             isVisible: false,
>           ),
>           enableSideBySideSeriesPlacement: false,
>           series: <ChartSeries>[
>             ColumnSeries<ChartData, DateTime>(
>               color: precipitationColor,
>               dataLabelSettings: const DataLabelSettings(
>                   isVisible: true,
>                   showZeroValue: false,
>                   labelAlignment: ChartDataLabelAlignment.outer),
>               dataSource: chartData,
>               xValueMapper: (data, _) => data.x,
>               yValueMapper: (data, _) => data.y1,
>             ),
>             ColumnSeries<ChartData, DateTime>(
>               color: const Color.fromRGBO(0, 196, 179, 0.5),
>               dataLabelSettings: const DataLabelSettings(
>                   isVisible: true,
>                   showZeroValue: false,
>                   labelAlignment: ChartDataLabelAlignment.outer),
>               dataSource: chartData,
>               xValueMapper: (data, _) => data.x,
>               yValueMapper: (data, _) => data.y2,
>             ),
>             ColumnSeries<ChartData, DateTime>(
>               color: const Color.fromRGBO(97, 0, 238, 0.5),
>               dataLabelSettings: const DataLabelSettings(
>                   isVisible: true,
>                   showZeroValue: false,
>                   labelAlignment: ChartDataLabelAlignment.outer),
>               dataLabelMapper: (data, _) => data.y3.toStringAsFixed(2),
>               dataSource: chartData,
>               xValueMapper: (data, _) => data.x,
>               yValueMapper: (data, index) => data.y3 * -1,
>             ),
>           ],
>         ),
> 
> class ChartData {
>   ChartData(this.x, this.y1, this.y2, this.y3);
> 
>   final DateTime x;
>   final double y1;
>   final double y2;
>   final double y3;
> }
> ```
> 
> Then, i changed my code, only showing y1, if the value was superior to 0.01, by adding
> 
> ```dart
>  dataLabelMapper: (data, _) =>
>                     data.y1 > 0.01 ? data.y1.toStringAsFixed(2) : '')
> ```
> 
> ![image](https://user-images.githubusercontent.com/61757484/204531398-40b4b2cc-b0d7-44b0-ba02-f95a56da4bdd.png)
> 
> If I remove ` labelAlignment: ChartDataLabelAlignment.outer` from all my ColumnSeries, this is what I end up with:
> 
> ![image](https://user-images.githubusercontent.com/61757484/204531115-2094b0f4-1277-4e86-836b-16ed37413b3b.png)
> 
> The result I was looking was something like Image One, but, with the values being displayed as my I have conditioned

**Comment by Yuvaraj-Gajaraj** [comment]
You have disabled the side-by-side placement, so the second series will render above the first series.  So the data label for the first series 0.01 will render above the second series only.

However, you can achieve your requirement with the help of dataValueMapper and customize the second series data label at specific conditions. We have shared the code snippet below for your reference.

Code snippet:
```dart
SfCartesianChart(
  series: <ChartSeries>[
    ColumnSeries<ChartData, DateTime>(
        // Other required properties
        dataLabelMapper: (data, _) =>
            data.y1 > 0.01 ? data.y1.toStringAsFixed(2) : ''),
    ColumnSeries<ChartData, DateTime>(
        // Other required properties
      dataLabelMapper: (data, int index) =>
                    index == 1 ? '0.01' : data.y2.toStringAsFixed(2),
    ),
    ColumnSeries<ChartData, DateTime>(
      dataLabelMapper: (data, _) => data.y3.toStringAsFixed(2),
    ),
 ],
),
```

Screenshot:
![rte_image_330](https://user-images.githubusercontent.com/61863686/210938676-e0dcd08d-2fa3-4c12-a8dd-335bd15b43e3.png)

Sample: 
[i428026.zip](https://github.com/syncfusion/flutter-widgets/files/10357610/i428026.zip)
