### ISSUE TITLE
[syncfusion_flutter_pdfviewer] add function to save pdf data to file .

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#996]
when i try to save pdf to file , i request it from my cloud storage again , 
is there way to get pdf data from controller to save it as a file ?

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by deepika134** [comment]
Currently, the Syncfusion Flutter PDF Viewer widget doesn’t allow editing or reviewing a PDF document, so the save support has not been provided yet. However, as a workaround solution, use the PdfDocument.saveSync method to obtain the loaded document bytes and save the document locally. The following code example explains the same,

**Code snippet:**

```
SfPdfViewer.asset(
      'assets/sample.pdf',
      key: _pdfViewerKey,
      onDocumentLoaded: (PdfDocumentLoadedDetails details) {
        // Document bytes of a PDF document loaded in SfPdfViewer.
        _documentBytes = details.document.saveSync();
      },
),
```

Kindly refer the following KB link for more details about how save a PDF document loaded in the Flutter SfPdfViewer to the local storage,

https://support.syncfusion.com/kb/article/12085/how-to-save-a-pdf-document-loaded-in-the-flutter-pdf-viewer-sfpdfviewer-to-the-local

**Comment by ramkumarsync** [comment]
We have provided support for saving the document in SfPdfViewer. 

https://pub.dev/documentation/syncfusion_flutter_pdfviewer/latest/pdfviewer/PdfViewerController/saveDocument.html
