### ISSUE TITLE
[syncfusion_flutter_pdf] Unhandled Exception: type 'PdfReferenceHolder' is not a subtype of type 'PdfDictionary?' in type cast

### ISSUE THREAD

**Issue by devkirch** [syncfusion/flutter-widgets#997]
Hello,

There is an error when adding images to certain PDF files. Images cannot be added to existing pages, but only to new pages. This only happens with certain PDF Files.

This code works

` bauteampdf.pages.add().graphics.drawImage(pdfimage, const Rect.fromLTWH(0, 0, 0, 150));`

This code does not work

` bauteampdf.pages[0].graphics.drawImage(pdfimage, const Rect.fromLTWH(0, 0, 0, 150));`

`E/flutter (23123): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'PdfReferenceHolder' is not a subtype of type 'PdfDictionary?' in type cast
E/flutter (23123): #0      PdfResources.add (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/pdf_resources.dart:115:58)
E/flutter (23123): #1      PdfResources.getName (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/pdf_resources.dart:70:9)
E/flutter (23123): #2      PdfGraphics._drawTemplate (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/pdf_graphics.dart:943:36)
E/flutter (23123): #3      PdfGraphics.drawPdfTemplate (package:syncfusion_flutter_pdf/src/pdf/implementation/graphics/pdf_graphics.dart:398:5)
E/flutter (23123): #4      PdfSignatureFieldHelper.draw (package:syncfusion_flutter_pdf/src/pdf/implementation/forms/pdf_signature_field.dart:382:39)
E/flutter (23123): #5      PdfFormHelper.beginSave (package:syncfusion_flutter_pdf/src/pdf/implementation/forms/pdf_form.dart:1009:20)
E/flutter (23123): #6      PdfDictionary.onBeginSave (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_dictionary.dart:543:26)
E/flutter (23123): #7      PdfDictionary.saveDictionary (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_dictionary.dart:210:7)
E/flutter (23123): #8      PdfDictionary.save (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_dictionary.dart:507:5)
E/flutter (23123): #9      PdfCrossTable._doSaveObjectAsync.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:875:24)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #10     PdfCrossTable._doSaveObjectAsync.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:874:15)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #11     PdfCrossTable._doSaveObjectAsync.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:873:13)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #12     PdfCrossTable._doSaveObjectAsync.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:872:11)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #13     PdfCrossTable._doSaveObjectAsync.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:871:9)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #14     PdfCrossTable._doSaveObjectAsync.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:870:7)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #15     PdfCrossTable._doSaveObjectAsync (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:869:5)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #16     PdfCrossTable._saveIndirectObjectAsync.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:527:11)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #17     PdfCrossTable._saveIndirectObjectAsync.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:525:9)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #18     PdfCrossTable._saveIndirectObjectAsync (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:490:5)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #19     PdfCrossTable._saveObjectsAsync (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:377:9)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #20     PdfCrossTable.saveAsync (package:syncfusion_flutter_pdf/src/pdf/implementation/io/pdf_cross_table.dart:258:5)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #21     PdfDocument._appendDocumentAsync (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:831:5)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #22     PdfDocument.save (package:syncfusion_flutter_pdf/src/pdf/implementation/pdf_document/pdf_document.dart:677:7)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): #23     _PDFSignaturePage._handleSigningProcess (package:envoltec/utils/pdf_signature_page.dart:275:27)
E/flutter (23123): <asynchronous suspension>
E/flutter (23123): 
`

PDF to reproduce the error: [https://drive.google.com/file/d/1D1ehxAmMaEVhrQgNJH2aMQV_1mk13Kpy/view?usp=sharing](url)

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by irfanajaffer** [comment]
The fix for the reported issue has been included in our latest release v21.2.3. 

 

Kindly use the following link to refer to our latest version,

https://pub.dev/packages/syncfusion_flutter_pdf/versions
