### ISSUE TITLE
[synfusion_flutter_datagrid]-multi stack header rows with empty cells

### ISSUE THREAD

**Issue by kevinxxq** [syncfusion/flutter-widgets#998]
Hi There,
Thank you for your support.
I would like to leave some cells of the first stackedHeaderRow empty or combining with second row in case there are cells in the correspond second stackedHeaderRow:

Just revise from document [multi-stacked-headers](https://help.syncfusion.com/flutter/datagrid/stacked-headers#multi-stacked-headers)

```
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

@override
Widget build(BuildContext context) {
  return SfDataGrid(
      gridLinesVisibility: GridLinesVisibility.both,
      headerGridLinesVisibility: GridLinesVisibility.both,
      source: _productDataSource,
      columns: <GridColumn>[
        GridColumn(
            columnName: 'orderId',
            label: Container(
                padding: EdgeInsets.symmetric(horizontal: 16.0),
                alignment: Alignment.centerRight,
                child: Text(
                  'ID',
                  overflow: TextOverflow.ellipsis,
                ))),
        GridColumn(
            columnName: 'customerName',
            label: Container(
                padding: EdgeInsets.symmetric(horizontal: 16.0),
                alignment: Alignment.centerLeft,
                child: Text(
                  'Name',
                  overflow: TextOverflow.ellipsis,
                ))),
        GridColumn(
            columnName: 'productId',
            label: Container(
                padding: EdgeInsets.symmetric(horizontal: 16.0),
                alignment: Alignment.centerRight,
                child: Text(
                  'ID',
                  overflow: TextOverflow.ellipsis,
                ))),
        GridColumn(
            columnName: 'product',
            label: Container(
                padding: EdgeInsets.symmetric(horizontal: 16.0),
                alignment: Alignment.centerLeft,
                child: Text(
                  'Product',
                  overflow: TextOverflow.ellipsis,
                ))),
      ],
      stackedHeaderRows: <StackedHeaderRow>[
        StackedHeaderRow(cells: [
          StackedHeaderCell(
              columnNames: ['productId', 'product'],
              child: Container(
                  color: const Color(0xFFF1F1F1),
                  child: Center(child: Text('Order Shipment Details')))),
        ]),
        StackedHeaderRow(cells: [
          StackedHeaderCell(
              columnNames: ['orderId', 'customerName'],
              child: Container(
                  color: const Color(0xFFF1F1F1),
                  child: Center(child: Text('Customer Details')))),
          StackedHeaderCell(
              columnNames: ['productId', 'product'],
              child: Container(
                  color: const Color(0xFFF1F1F1),
                  child: Center(child: Text('Product Details'))))
        ])
      ]);
}
```

I would expect the table as below(sorry I just drawed it):
![flutter-multi-stacked-headers](https://user-images.githubusercontent.com/55800697/205517297-3bd0feea-7f09-4ffb-ba27-60236953dfe2.png)

But I encountered exceptions:
```
Exception has occurred.
FlutterError (RenderBox did not set its size during layout.
Because this RenderBox has sizedByParent set to false, it must set its size in performLayout().
It appears that this did not happen; layout completed, but the size property is still null.
The RenderBox in question is:
  RenderVirtualizingCellsWidget#31927 NEEDS-LAYOUT NEEDS-PAINT)
```

I can add a empty widget to the first stackedHeaderRow to eleminate the exceptions.
Thank you.

**Comment by kevinxxq** [comment]
Hi There,
Just update the situation, you can't reproduce the exceptions as above.
the above exceptions take place in case all the cells of the first stackedHeaderRow are empty, this may be working as expections.

I just added a condition to eleminate the exception:
```
    if (headerCellsFirst.isNotEmpty) {
      stackedHeaderRows.add(
        StackedHeaderRow(cells: headerCellsFirst),
      );
    }
```
Thank you.

**Comment by Tamilarasan-Paranthaman** [comment]
Hi @kevinxxq,

The list of **StackedHeaderCell** is the required property of the **StackedHeaderRow**. You can't set this property as empty. By default, if you set the stacked header cell only for the third and fourth columns, then the first and second cells are merged with the next stacked header row or column cells.

Based on the expected image which you have shared, you can do it by setting StackedHeaderCell only for the third and fourth columns i.e., ID and Product in the first StackedHeaderRow and setting the padding for second row content. I've attached a simple sample for that. Also refer to the reference image for the same.

**Sample Link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-1685500758** 


![image](https://user-images.githubusercontent.com/93904422/205635931-a91cd987-2dc0-4256-a097-20126ad65ac3.png)
